### ISSUE TITLE
Commit history after checking out a commit

### ISSUE THREAD

**Issue by gtzogana** [junegunn/fzf#1001]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

After checking out a particular commit with `fcoc`, subsequent invocations of `fcoc` or `fshow` only reveal commit history up to the checked out commit. Is there any way to continue displaying the full commit history after a commit has been checked out?

**Comment by junegunn** [comment]
I can't always give help with the examples on the wiki page, as they are maintained by the community, not by me (I wasn't aware of `fcoc`). I believe you should be able to easily customize the command to your needs. See `git help checkout`.
