### ISSUE TITLE
Keyboard shortcut to scroll through commit history

### ISSUE THREAD

**Issue by gtzogana** [junegunn/fzf#1002]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

In repos with long commit histories, it would be helpful to use something like `b` to page through them.

**Comment by junegunn** [comment]
You can use `--bind` option to set up page-up and page-down bindings and add it to `$FZF_DEFAULT_OPTS`. See `man fzf`.
