### ISSUE TITLE
FZF and localvimrc don't play well together

### ISSUE THREAD

**Issue by RobertBuhren** [junegunn/fzf#1005]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [x] Vim
    - [x] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [ ] fish

I'm using localvimrc (https://github.com/embear/vim-localvimrc) to have project specific vim settings. 
E.g. I use "execute "lcd ".g:localvimrc_script_dir."/.." to change to a specific project root whenever I enter a buffer of that project. 

When I open a file from such a project using ":FZF" it will not process my local vimrc. It works however when I open the file with e.g. ":e path/to/file"

This also applies when using https://github.com/junegunn/fzf.vim

Please let me know if I should provide more details.

Regards,

Robert

**Comment by RobertBuhren** [comment]
The default event for localvimrc to trigger a loading of the localvimrc file is "BufWinEnter" which is apparently not triggered by :FZF

**Comment by junegunn** [comment]
I have no experience with localvimrc, but I can confirm that the following autocmd is triggered I open a file with FZF.

```vim
autocmd BufWinEnter * echom 'bwe: '.expand('%')

**Comment by RobertBuhren** [comment]
Yeah, after debugging a while I think I found the problem in the "dopopd" function: 

https://github.com/junegunn/fzf/blob/master/plugin/fzf.vim#L469

The last check is "!haslocaldir()". So when a "lcd" was issued e,g. by localvimrc the check will fail and continue. Shouldn't the check be "haslocaldir()" so that the dir is actually only popped when there was no lcoal dir set?

Regards,

Robert

**Comment by junegunn** [comment]
The condition in itself is correct, it checks if fzf plugin previously changed the working directory, if it didn't, then there's no need to "popd". The only problem with that condition is that it assumes that no other plugins change the directory in the process, which is not the case in your situation.

Does this patch help?

```patch
diff --git a/plugin/fzf.vim b/plugin/fzf.vim
index 7e19f25..f895537 100644
--- a/plugin/fzf.vim
+++ b/plugin/fzf.vim
@@ -466,11 +466,11 @@ augroup fzf_popd
 augroup END
 
 function! s:dopopd()
-  if !exists('w:fzf_prev_dir') || exists('*haslocaldir') && !haslocaldir()
+  if !exists('w:fzf_dir') || s:fzf_getcwd() != w:fzf_dir[1]
     return
   endif
-  execute 'lcd' s:escape(w:fzf_prev_dir)
-  unlet w:fzf_prev_dir
+  execute 'lcd' s:escape(w:fzf_dir[0])
+  unlet w:fzf_dir
 endfunction
 
 function! s:xterm_launcher()
@@ -719,7 +719,7 @@ function! s:callback(dict, lines) abort
   let popd = has_key(a:dict, 'prev_dir') &&
         \ (!&autochdir || (empty(a:lines) || len(a:lines) == 1 && empty(a:lines[0])))
   if popd
-    let w:fzf_prev_dir = a:dict.prev_dir
+    let w:fzf_dir = [a:dict.prev_dir, a:dict.dir]
   endif
 
   try
@@ -743,7 +743,7 @@ function! s:callback(dict, lines) abort
 
   " We may have opened a new window or tab
   if popd
-    let w:fzf_prev_dir = a:dict.prev_dir
+    let w:fzf_dir = [a:dict.prev_dir, a:dict.dir]
     call s:dopopd()
   endif
 endfunction
```

**Comment by RobertBuhren** [comment]
Yes, that works fine
