### ISSUE TITLE
Preview option does not work inside tmux

### ISSUE THREAD

**Issue by Chrysostomus** [junegunn/fzf#1006]
- Category
    - [ ] fzf binary
    - [x] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [ ] fish

The preview option does not work inside tmux. It works perfectly outside tmux, but when run from inside it gives only the message "**editor** variable unset". I suspect something is wrong with my tmux settings. How should I start troubleshooting this? $EDITOR and $VISUAL are both set and $TERM is screen-256colors, and fzf is up to date.

**Comment by junegunn** [comment]
I'm always on tmux and have no issues. Please provide the exact command you tried.

**Comment by Chrysostomus** [comment]
I'm running function from a bash script this is the fzf part:

```
sort -u -i /tmp/pacui-packages-install | fzf-tmux -m -e +s -i -1 --query="$input2" --cycle --ansi --reverse --margin=4%,1%,1%,2% --inline-info --preview '
			if ( pacman -Qq {} &>/dev/null )		# check, if selected line is a locally installed package
			then
				if [[ ! -e /usr/bin/pacaur ]]		# checks, whether file "pacaur" does not exist
				then
					yaourt -Qi {}
				else 				
					pacaur -Qi {} --color always
				fi
			elif ( pacman -Sgq {} &>/dev/null )		# check, if selected line in fzf is a package group
			then
				echo -e "\e[1m{} group has the following members: \e[0m"
				pacman -Sgq {}
			else									# do this if line is neither a group nor locally installed
				if [[ ! -e /usr/bin/pacaur ]]		# checks, whether file "pacaur" does not exist
				then 
					yaourt -Si {}
				else 
					pacaur -Si {} --color always
				fi
			fi
			' --preview-window=right:50%:wrap  --header="TAB key to (un)select. ENTER key to install. ESC or CTRL+C to quit." --prompt='Enter string to filter list > ' 

		
```

**Comment by junegunn** [comment]
`fzf-tmux --preview 'echo $VISUAL $EDITOR'` ?

**Comment by Chrysostomus** [comment]
I'll test it when I get back to my computer this evening.

**Comment by Chrysostomus** [comment]
Other investigation indicates that the problem is with pacaur, not fzf. Therefore, this issue is unnecessary.
