### ISSUE TITLE
[fzf-tmux] fish: Unknown signal '-SIGUSR1'

### ISSUE THREAD

**Issue by noahfrederick** [junegunn/fzf#1007]
- Category
    - [ ] fzf binary
    - [x] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [x] fish

`fzf-tmux` emits errors in the tmux pane it creates under fish 2.6.0:

```
- (line 1): function: Unknown signal '-SIGUSR1'
function __trap_handler_-SIGUSR1 --on-signal -SIGUSR1; kill; end
^
from sourcing file -
        called on line 109 of file /usr/local/Cellar/fish/2.6.0/share/fish/functions/trap.fish

in function 'trap'
        called on standard input
        with parameter list 'kill -SIGUSR1 -44257 EXIT SIGINT SIGTERM'

- (line 1): function: Unknown signal '-44257'
function __trap_handler_-44257 --on-signal -44257; kill; end
^
from sourcing file -
        called on line 109 of file /usr/local/Cellar/fish/2.6.0/share/fish/functions/trap.fish

in function 'trap'
        called on standard input
        with parameter list 'kill -SIGUSR1 -44257 EXIT SIGINT SIGTERM'
```

It looks like it could be a quoting problem related to [this line](https://github.com/junegunn/fzf/blob/master/bin/fzf-tmux#L173), but haven't confirmed.

Note: this error output is normally obscured by the FZF window, however you can see it briefly before FZF's UI appears, or by pressing `Ctrl-Z` from within FZF.

**Comment by junegunn** [comment]
I just installed fish 2.6.0 on my macbook, and fzf-tmux works as expected. Maybe a configuration problem?

**Comment by noahfrederick** [comment]
To be clear, the script still works in that `fzf` itself launches and exits normally, despite the error, and the text is not necessarily visible on screen unless you suspend FZF.

> Maybe a configuration problem?

I'll report back on whether I can reproduce this on a clean installation. (Won't be able to get to it in the next few days though.)

**Comment by junegunn** [comment]
So I guess the trap command is inconpatible in fish. Then we should explicitly execute the commands with bash. Oh, it's frustrating that fish always makes things more complicated.

**Comment by junegunn** [comment]
Can you check if this patch fixes the issue?

```diff
diff --git a/bin/fzf-tmux b/bin/fzf-tmux
index 5ec0dc4..c3834f7 100755
--- a/bin/fzf-tmux
+++ b/bin/fzf-tmux
@@ -146,6 +146,7 @@ cleanup() {
   fi
 
   if [ $# -gt 0 ]; then
+    trap - EXIT
     exit 130
   fi
 }
@@ -170,21 +171,22 @@ for arg in "${args[@]}"; do
 done
 
 pppid=$$
-trap_set="trap 'kill -SIGUSR1 -$pppid' EXIT SIGINT SIGTERM"
-trap_unset="trap - EXIT SIGINT SIGTERM"
+echo -n "trap 'kill -SIGUSR1 -$pppid' EXIT SIGINT SIGTERM;" > $argsf
+close="; trap - EXIT SIGINT SIGTERM $close"
 
 if [[ -n "$term" ]] || [[ -t 0 ]]; then
-  cat <<< "\"$fzf\" $opts > $fifo2; echo \$? > $fifo3 $close" > $argsf
+  cat <<< "\"$fzf\" $opts > $fifo2; echo \$? > $fifo3 $close" >> $argsf
+  cat $argsf
   TMUX=$(echo $TMUX | cut -d , -f 1,2) tmux set-window-option synchronize-panes off \;\
     set-window-option remain-on-exit off \;\
-    split-window $opt "$trap_set;cd $(printf %q "$PWD");$envs bash $argsf;$trap_unset" $swap \
+    split-window $opt "cd $(printf %q "$PWD");$envs bash $argsf" $swap \
     > /dev/null 2>&1
 else
   mkfifo $fifo1
-  cat <<< "\"$fzf\" $opts < $fifo1 > $fifo2; echo \$? > $fifo3 $close" > $argsf
+  cat <<< "\"$fzf\" $opts < $fifo1 > $fifo2; echo \$? > $fifo3 $close" >> $argsf
   TMUX=$(echo $TMUX | cut -d , -f 1,2) tmux set-window-option synchronize-panes off \;\
     set-window-option remain-on-exit off \;\
-    split-window $opt "$trap_set;$envs bash $argsf;$trap_unset" $swap \
+    split-window $opt "$envs bash $argsf" $swap \
     > /dev/null 2>&1
   cat <&0 > $fifo1 &
 fi
```

**Comment by noahfrederick** [comment]
> Can you check if this patch fixes the issue?

Yes, it fixes the issue. :+1:
