### ISSUE TITLE
Using vim line numbers with fzf or specifically fe from examples

### ISSUE THREAD

**Issue by partounian** [junegunn/fzf#1008]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [x] Vim
    - [x] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [x] fish

I would like to know if it's possible to use fe from the wiki while jumping to a specific line number in the file. Thank you!

**Comment by junegunn** [comment]
Sorry for the late reply.

fzf in fe example consumes the list of file paths, there's no line numbers. You might want to integrate fzf with file search tools that can display line numbers as well. For example, see #429.
