### ISSUE TITLE
How to ignore a folder from indexing

### ISSUE THREAD

**Issue by nikitavoloboev** [junegunn/fzf#1009]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ x] Etc.
- OS
    - [ ] Linux
    - [x ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ x] zsh
    - [ ] fish

I have this function I use to jump to folders 

```
# cd to selected directory
fa() {
  local dir
  dir=$(find ${1:-.} -path '*/\.*' -prune \
                  -o -type d -print 2> /dev/null | fzf +m) &&
  cd "$dir"
}
```

Is it possible to ignore node_modules from being indexed?

**Comment by junegunn** [comment]
Yes `find` can do that. `man find` will help you.
