### ISSUE TITLE
Do not map <C-j> (Return/Enter)

### ISSUE THREAD

**Issue by blueyed** [junegunn/fzf#101]
> Use CTRL-J and CTRL-K (or CTRL-N and CTRL-P) to change the selection

I have recently started the habit of using `<C-j>` instead of Enter. It would be nice if it worked in fzf, too.

Can this be configured?

**Comment by junegunn** [comment]
```sh
export FZF_DEFAULT_OPTS='--bind ctrl-j:accept'
```

:)
