### ISSUE TITLE
Use as a library

### ISSUE THREAD

**Issue by kalbasit** [junegunn/fzf#1010]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [x] Etc.
- OS
    - [ ] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [x] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

Hello,

I'm writing a TMUX wrapper that fits my workflow and I would like to use FZF as a library in order to present a big list of projects to start a session for. For now, I'll use the `fzf` binary but it would be more performant to embed. The current [`Run`](https://github.com/junegunn/fzf/blob/master/src/core.go#L46) assumes binary and it does quite a bit of `os.Exit()` which makes it unusable as a library. @junegunn are you planning to split fzf into library/binary?

**Comment by junegunn** [comment]
No, it's not planned as I don't want to make any promises regarding API stability for the time being.

Having said that, I wouldn't really worry about performance. I'm pretty sure that users will not notice any difference in response time.

**Comment by kalbasit** [comment]
thx for the quick reply @junegunn I'll use the binary for now.
