### ISSUE TITLE
FZF clears screen in fullscreen mode

### ISSUE THREAD

**Issue by arya** [junegunn/fzf#1011]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

In 0.16.8, when fzf exited, the selected line was placed in-place without clearing the screen. As of 6b5886c034800c46d25a02c8b91c2797ec5fb6d6 just invoking "fzf" and hitting enter clears the screen (with height set to 100%).

It seems upon digging into the source, that commit uncommented an unconditonal call to r.csi("s") but only conditionally calls r.csi("u"). I confirmed that wrapping r.csi("s") with `if !r.fullscreen` fixes the issue. I can submit a PR if this is the correct fix, or if you prefer another solution I'm happy to do that as well.

Also, I noticed that this line was initially commented out in 78a3f81972312d13d50e5b24dcabaa40284566b5 where it says `s` and `u` are unsupported. Is that no longer the case?

**Comment by junegunn** [comment]
Have you tried running fzf without `--height` option (or equivalently with `--no-height`)? In the recent versions, `--height=100%` (or `--height 99999`) is no longer equivalent to `--no-height`. The former allocates the space for fzf by printing line feeds, effectively clearing the screen. On the other hand, the latter uses alternate screen, leaving the original screen untouched.

`s` and `u` are still not supported by many terminal emulators, but it's not related to the issue.

**Comment by arya** [comment]
I just tried `--no-height` and that didn't work. I also confirmed that with my configuration the `r.fullscreen` is `true`. Guarding `r.csi("s")` behind `!r.fullscreen` does change the observed behavior.

**Comment by junegunn** [comment]
Which terminal emulator are you running? What happens when you do `echo -e "\x1b[s"` and `echo -e "\x1b[u"`?

**Comment by junegunn** [comment]
I can't reproduce the problem on my machine, but if `s` is causing the issue, I can update the code as you suggested.

```diff
diff --git a/src/tui/light.go b/src/tui/light.go
index f905918..15f4e01 100644
--- a/src/tui/light.go
+++ b/src/tui/light.go
@@ -209,7 +209,9 @@ func (r *LightRenderer) Init() {
 	r.csi(fmt.Sprintf("%dA", r.MaxY()-1))
 	r.csi("G")
 	r.csi("K")
-	r.csi("s")
+	if !r.clearOnExit && !r.fullscreen {
+		r.csi("s")
+	}
 	if !r.fullscreen && r.mouse {
 		r.yoffset, _ = r.findOffset()
 	}
```

**Comment by junegunn** [comment]
I just pushed the fix because I have to go to bed now :)
Let me know if you still have issues.

**Comment by arya** [comment]
Thanks!

FWIW I think it's iTerm2 (Build 3.1.beta.6) with tmux integration that doesn't support the save cursor position, since I can only repro there and not on anything else.

**Comment by junegunn** [comment]
I see, thanks for the comment.
