### ISSUE TITLE
Is it possible to paste the text and not run it from this fzf command?

### ISSUE THREAD

**Issue by nikitavoloboev** [junegunn/fzf#1013]
- OS
    - [ ] Linux
    - [x ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x ] zsh
    - [ ] fish

I have this script I use : 

```
# repeat history
j() {
  eval $( ([ -n "$ZSH_NAME" ] && fc -l 1 || history) | fzf +s --tac | sed 's/ *[0-9]* *//')
}
```

It searches through my previously entered commands and on enter it will rerun them. Is it possible to modify it so that on pressing TAB, it will simply enter the command into my terminal and let me edit the command (not run it instantly).

I looked into zsh and emulating tab keystroke but still am confused how to achieve this.

Thank you a lot for this wonderful tool.

**Comment by junegunn** [comment]
It should be possible. You'll have to learn how to define a "widget".

- http://zsh.sourceforge.net/Doc/Release/Zsh-Line-Editor.html#Zle-Widgets

To detect if the user pressed tab or enter, you can use `--expect tab` option of fzf. It tells fzf to finish when the key is pressed, and print the name of the key pressed as the first line of the output. 

`vi-fetch-history` and `accept-line` are two relevant zle actions you'll need.

**Comment by akharrou** [comment]
@nikitavoloboev, have you found how to get the `accept-line` effect ?
