### ISSUE TITLE
Possibility to print line numbers instead of content of chosen line

### ISSUE THREAD

**Issue by carnager** [junegunn/fzf#1014]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [x] Etc.
- OS
    - [x] Linux
    - [x] Mac OS X
    - [x] Windows
    - [x] Windows Subsystem for Linux
    - [x] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [ ] fish

**Comment by junegunn** [comment]
fzf doesn't provide an option for that. But since we can easily do it in several ways, I don't think it's necessary to add it.

```sh
find . | nl | fzf | awk '{print $1}'

# If you want to hide line numbers
find . | nl | fzf --with-nth 2.. | awk '{print $1}'
```

**Comment by carnager** [comment]
Yes, I guess that is good enough....
