### ISSUE TITLE
Use fzf in another go program

### ISSUE THREAD

**Issue by binaryplease** [junegunn/fzf#1016]
Hello,

I would like to create a terminal application and use fzf as method to interact with the user.
Specifically I would like to rewrite this app https://github.com/Neo-Oli/contact in go and expand on it.

Can fzf be used inside another program that is not bash/shellscript? If so, how would I pass input to it and get the output?

Thanks

**Comment by junegunn** [comment]
Yes, you can start it as an external program. Examples can be found here: https://junegunn.kr/2016/02/using-fzf-in-your-program

Related: #1010
