### ISSUE TITLE
Install fzf using Linuxbrew

### ISSUE THREAD

**Issue by thedrow** [junegunn/fzf#1017]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [ ] fish

Right now the only option to install fzf on Linux is using git.
Linuxbrew can be used instead.
We only need the formula to point to the correct binary when running in Linux.

**Comment by junegunn** [comment]
I don't use Linuxbrew but isn't this supposed to work?

https://github.com/Linuxbrew/homebrew-core/blob/master/Formula/fzf.rb

**Comment by thedrow** [comment]
Yes it should. We should point it out in the README.
Should this be the preferred installation method?

**Comment by junegunn** [comment]
Updated README.

> Should this be the preferred installation method?

Maybe. FWIW, README page no longer mentions that cloning option is recommended. https://github.com/junegunn/fzf/commit/8ef2420677abf5cca27b47bead6e70e42220c7aa
