### ISSUE TITLE
Shell parsing for preview command in Windows is incompatible with fzf#shellescape and cmd.exe

### ISSUE THREAD

**Issue by janlazo** [junegunn/fzf#1018]
- Category
    - [X] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [ ] Mac OS X
    - [X] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [ ] fish

Backslashes in the filepath of the preview command are escaped so they don't run in Windows.
The preview script itself (ruby or bash) has no issues with filepaths with backslashes.

https://github.com/junegunn/fzf.vim/pull/418#issuecomment-322641946 is caused by the network drive conflicting with the colon delimiter. I'll open a separate issue/PR for that.

**Comment by janlazo** [comment]
Escaping the preview command with `fzf#shellescape` doesn't work 😕

**Comment by janlazo** [comment]
Workaround from fzf.vim for escaping filenames correctly if not using a batchfile for the preview command
https://github.com/junegunn/fzf.vim/commit/a4d4986d18074b7867584f837bc09cc37a110fd0#diff-7274b7c6c87526542ef9087f2e997dfaR42

```viml
let path = 'C:\path\to\preview_script.sh'
if has('nvim')
  let path = split(system('for %A in ("'.path.'") do echo %~sA'), "\n")[1]
else
     let path = fnamemodify(path, ':8')
endif
let path = escape(path, '\')
endif
```

**Comment by janlazo** [comment]
Neovim support for DOS shortname is removed in https://github.com/neovim/neovim/pull/635. This hack is here to stay in fzf.vim 😢 and `fnamemodify(path, ':8')` and `expand('%:p:8')` are broken.

**Comment by janlazo** [comment]
@junegunn Do you know why a single double-quote is converted to a double backslash?
I'm testing the bash preview script in fzf.vim on a line with a single quote, https://github.com/junegunn/fzf/blob/master/plugin/fzf.vim#L2, and I get `File not found` error with the backslashes escaped?

**Comment by junegunn** [comment]
Not quite sure if I follow you. Can you provide the exact steps to reproduce the problem you described?

**Comment by janlazo** [comment]
In Vim/Neovim, run `Ag` with preview

```viml
call fzf#vim#ag('', fzf#vim#with_preview())
```

Query for a double quote

```sh
plugin\fzf.vim:2:1:"
Ag> "
```
In the preview window, the preview script outputs `File not found pluginfzf.vim` because the preview script got `pluginfzf.vim:2:1\\`

**Comment by junegunn** [comment]
I haven't tried it on Windows yet but it works on *nix.

On *nix, starting a command with `sh` is simple, we can just use `['sh', '-c', command]` as the arguments for `exec.Command` without any preprocessing.

https://github.com/junegunn/fzf/blob/077ae51f0511260ba2d2c793b776582d41fefd6a/src/util/util_unix.go#L20-L23

On Windows, it's a little more complicated. I don't fully remember, but I noticed the same approach didn't work with `cmd /c` and I had to "shellescape" each token in the command using [a third-party library](https://github.com/mattn/go-shellwords). 

https://github.com/junegunn/fzf/blob/077ae51f0511260ba2d2c793b776582d41fefd6a/src/util/util_windows.go#L18-L26

Do you have experience with Go? You can test the code like follows:

```go
package main

import (
	"fmt"
	"os/exec"

	"github.com/mattn/go-shellwords"
)

func main() {
	command := "echo 'foo\\bar:1:2:\"'"
	args, _ := shellwords.Parse(command)
	allArgs := make([]string, len(args)+1)
	allArgs[0] = "/c"
	copy(allArgs[1:], args)
	fmt.Printf("%#v\n", allArgs)
	out, err := exec.Command("cmd", allArgs...).Output()
	fmt.Println(out, err)
}
```

```sh
go get github.com/mattn/go-shellwords
go run shellesacpe.go
```

and it gives:

```
[]string{"/c", "echo", "foo\\bar:1:2:\""}
[] exec: "cmd": executable file not found in $PATH
```

Do you see anything strange about this?

**Comment by janlazo** [comment]
Windows ruby passes it as is so the ruby preview script is necessary after all.

**Comment by junegunn** [comment]
> Which echo are we testing on?

I tested it on macOS where `cmd` doesn't exist, and I knew it was bound to fail. Sorry for the confusion, I just wanted to show how arguments are passed.

> I think cygwin bash itself is the issue

Yeah, agreed.

**Comment by janlazo** [comment]
If we port `fzf#shellescape` in go such that we can shellescape the preview command into a single token, is tokenization still required?

**Comment by janlazo** [comment]
If the double quotes are not escaped somehow such that it is executed as is but previewCmd is wrapped in double quotes when it is run, then

```go
cmd := exec.Command("cmd", "/s", "/c", previewCmd).Output()
```

should work.

```dosbatch
:: internal echo
>cmd /s /c " echo foo\bar" "
foo\:bar"
:: cygwin echo.exe
> cmd /s /c " "echo" foo\bar" "
foo:bar
```

Imo, Vim and Neovim should use `/s` instead of `sxe` and `sxq` but this is unintuitive because of how cmd.exe dequotes the command.

**Comment by janlazo** [comment]
Have to explicity set syscall.SysProcAttr.CmdLine manually.

https://github.com/golang/go/issues/15566#issuecomment-333274825
https://golang.org/src/syscall/exec_windows.go

**Comment by janlazo** [comment]
Reference: https://play.golang.org/p/aU1PlbNTqM

@junegunn Can you set CmdLine and the run the preview command (no parsing and escaping) as is?

```go
package main

import (
	"fmt"
	"os/exec"
	"syscall"
)

func main() {
	cmd := exec.Command("cmd")
	command := `"echo" foo\:bar"`
	cmd.SysProcAttr = &syscall.SysProcAttr{
	    HideWindow: false,
	    CmdLine: fmt.Sprintf(` /s /c "%s"`, command),
	    CreationFlags: 0,
	}
	fmt.Println(cmd.SysProcAttr.CmdLine)
	out, err := cmd.Output()
	fmt.Printf("%s\n", out)
	fmt.Println(out, err)
}
```

**Comment by hungpham3112** [comment]
I still have this issue. Have fzf preview support Window yet?
