### ISSUE TITLE
Invoke fzf when tab completion is ambiguous

### ISSUE THREAD

**Issue by ptzz** [junegunn/fzf#1020]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [x] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

I have `show-all-if-ambiguous` set in .inputrc and would like to have the alternatives show up in an fzf selector on single tab, instead of just being printed. Is that possible? Guess that could potentially avoid lots of custom scripts, e.g.  `git checkout <TAB>` would start an fzf selector containing the files and branches of the repo (by using existing context-aware git completion).

**Comment by junegunn** [comment]
That would be cool, but I'm doubtful that it's possible. What I've learned so far is that bash is not very extensible.

**Comment by ptzz** [comment]
Suspected that. What fzf does is already quite amazing, thanks a lot!

**Comment by ptzz** [comment]
Maybe not impossible after all? At least tab completion list can be accessed programmatically ( https://brbsix.github.io/2015/11/29/accessing-tab-completion-programmatically-in-bash), but maybe there are other showstoppers? Perhaps not possible with `<TAB>`, but possibly with a custom shortcut?

**Comment by junegunn** [comment]
Interesting, I'll take a look when I get some time, thanks for sharing. Feel free to ping me if you managed to implement a solution.

**Comment by ptzz** [comment]
Did not try/manage to get the fzf selector on `TAB` only, but the following binds `<Ctrl-j>` to an fzf selector fed with the completion options from the original command. E.g. `git <Ctrl-j>` shows a list of git commands and `git checkout <Ctrl-j>` shows a list of branches.

```
    source ${_PROFILE_SCRIPT_DIR}/get_completions.sh
    _select_completion() {
        local completions=$(get_completions "${READLINE_LINE} ")
        local selection=$(echo "$completions" | fzf --tac +s +m -e --ansi --reverse)
        READLINE_LINE="${READLINE_LINE:0:$READLINE_POINT}$selection${READLINE_LINE:$READLINE_POINT}"
        READLINE_POINT=$(( READLINE_POINT + ${#selection} ))
    }
    bind -x '"\C-j": "_select_completion"'
```

`get_completion.sh` is a file containing the script at the end of https://brbsix.github.io/2015/11/29/accessing-tab-completion-programmatically-in-bash/.
