### ISSUE TITLE
How to fzf on variable expansion?

### ISSUE THREAD

**Issue by nikitavoloboev** [junegunn/fzf#1022]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [x] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [x ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

In zsh and bash you can start typing the name of variable like `$PA`, press tab and get a list of variables you can type. I would love to run that through `fzf` but not really sure how I can do it.

Would really appreciate and help on this. Thank you.

**Comment by junegunn** [comment]
It may not be trivial to extend completion functions to support the expansion of environment variables, but defining an extra key binding just for pasting selected variables on the command-line is quite doable. You can refer to the following post to see how it's done.

- https://junegunn.kr/2016/07/fzf-git
    - https://gist.github.com/junegunn/8b572b8d4b5eddd8b85e5f4d40f17236
