### ISSUE TITLE
Can't run FZF in multiple neovim windows

### ISSUE THREAD

**Issue by nkgm** [junegunn/fzf#1023]
- Category
    - [x] Neovim

For background, I'm a big fan of `let g:fzf_layout = { 'window': 'enew' }`.

Currently when I try to launch on a second split when it's already running on the first one, I get `FZF is already running (in buffer x)`. I realize this isn't for most users but it's a very useful powertool and it appears to just work with the check disabled. Would you consider making the check user configurable (or even disabling it when `enew`)?

**Comment by junegunn** [comment]
I think we can just remove the check now. It was needed because we used to give the terminal buffer to a fixed name (`[FZF]`) (#180), but we no longer do that (#264 -> #630).

Let me see if there's any other side effects.
