### ISSUE TITLE
Using a field index expression strips leading and trailing whitespace from a field even when a custom --delimiter is specified

### ISSUE THREAD

**Issue by ZDNoFYVe7iBFr804xAf1** [junegunn/fzf#1024]
- Category
    - [X] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [X] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [ ] fish

If I run
```shell
printf '  A  X  B  ' | fzf --delimiter X --preview 'printf %s {1}'
```
the preview window shows only the letter A with no spaces around it.

I thought this might be a display issue, but piping to `hd` shows that's not the case:
```shell
printf '  A  X  B  ' | fzf --delimiter X --preview 'printf %s {1} | hd'
```

The same happens with other kinds of whitespace:
```shell
printf '\t\n\v\f\r A' | fzf --read0 --print0 --delimiter X --preview 'printf %s {1} | hd'
```

**Comment by junegunn** [comment]
Yes, we're stripping off white spaces from the tokens before apply them to the preview command. I made the decision as I thought it would be more useful in more cases. For example, one would certainly not be interested in keeping white spaces when working with tables.

```
| File                  | Size  | Type                                                   |
| --------------------- | ----- | ------------------------------------------------------ |
| src                   | 1462  | src: directory                                         |
| src/algo              | 170   | src/algo: directory                                    |
| src/algo/algo.go      | 23371 | src/algo/algo.go: ASCII c program text                 |
| src/algo/algo_test.go | 7977  | src/algo/algo_test.go: UTF-8 Unicode Java program text |
| src/algo/normalize.go | 20991 | src/algo/normalize.go: ASCII C++ program text          |
| src/ansi.go           | 4930  | src/ansi.go: ASCII Java program text                   |
| src/ansi_test.go      | 3710  | src/ansi_test.go: ASCII Java program text              |
| src/cache.go          | 1619  | src/cache.go: ASCII Java program text                  |
| src/cache_test.go     | 877   | src/cache_test.go: ASCII Java program text             |
| src/chunklist.go      | 1694  | src/chunklist.go: ASCII Java program text              |
| src/chunklist_test.go | 1862  | src/chunklist_test.go: ASCII Java program text         |
| src/constants.go      | 1990  | src/constants.go: ASCII Java program text              |
```

The same holds true for text aligned with tab characters.

I don't know what you're trying to achieve here, but you can still have white spaces by passing the whole string to the command with `{}`, though it would be tedious for you to manually tokenize the string. Please understand that the behavior was optimized for more common use cases.
