### ISSUE TITLE
Reset cursor to first result when new search query is entered

### ISSUE THREAD

**Issue by phodge** [junegunn/fzf#1025]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [x] Key bindings
    - [x] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

Hi! I needed to delete a `.rej` file and a `.orig` file left over from a failed patch and realised fzf makes this super easy. I have configured zsh so that typing `**<tab>` will bring up fzf completion, so I ran:

* `rm **<tab>`
* type ".rej" and hit `<tab>` to select the .rej file
* backspace the ".rej" query and type ".orig" and hit `<tab>` to select the .orig file

This didn't actually work - I had to use CTRL+P after typing the second query to move the cursor back up to the first result because FZF moves the cursor down when I select the .rej file, but doesn't move the cursor back to the first row when I type a new query. I'm going to suggest that typing a new query should reset the cursor back to the first selection. What do you think?

**Comment by qoxxxx** [comment]
I believe you can already do that using by binding **top** action.
Or automatically with,
`fzf --bind bspace:backward-delete-char+top`
or
`fzf --bind ctrl-u:unix-line-discard+top`
or
`fzf --bind ctrl-w:unix-word-rubout+top`

**Comment by junegunn** [comment]
```sh
fzf --bind change:top
```

is possible since 0.16.8.

**Comment by phodge** [comment]
@junegunn: That's exactly what I was looking for, thankyou!
