### ISSUE TITLE
completion for 'unalias' iterates files under current directory

### ISSUE THREAD

**Issue by suewonjp** [junegunn/fzf#1026]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [x] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

 When I use `unalias **<TAB>`, everything goes fine except when I exit the finder, the command iterates every file under the current working directory.

I captured some of the output.

```
-bash: unalias: ww
w/res/screen/webos: not found
-bash: unalias: www/res/screen/webos/screen-64.png: not found
-bash: unalias: www/res/screen/windows-phone: not found
-bash: unalias: www/res/screen/windows-phone/screen-portrait.jpg: not found
-bash: unalias: www/spec: not found
-bash: unalias: www/spec-runner-es5.html: not found
-bash: unalias: www/spec-runner.html: not found
-bash: unalias: www/spec/all-spec.js: not found
-bash: unalias: www/spec/config.js: not found
...
```

Is this a normal behavior?

**Comment by suewonjp** [comment]
Here are some extra info

```
fzf --version
0.16.11 (brew)
```

Also, I use iTerm

**Comment by junegunn** [comment]
bash will fallback to the default completion when we interrupt fzf, so it'll list files, but the error messages you posted above look strange and are unexpected.

Can you create and post an asciinema recording of it? https://asciinema.org/

**Comment by suewonjp** [comment]
Never mind.

It was my fault. Looks like I pressed enter right after I got out of the finder.

Really sorry to bother you.

**Comment by junegunn** [comment]
No worries.
