### ISSUE TITLE
Font type and size issues using gvim 

### ISSUE THREAD

**Issue by gauthiermartin** [junegunn/fzf#1030]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [x ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x ] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [x ] bash
    - [ ] zsh
    - [ ] fish

I'm currently using GVim . I Know that the fzf is not supported internally into GVim but i would like to know if their is a way i could modify the font type and size of the opening shell when using the command ?

**Comment by junegunn** [comment]
I believe it should be possible by defining your own `g:fzf_launcher` (or `g:Fzf_launcher`).

https://github.com/junegunn/fzf/blob/master/README-VIM.md#configuration

In fact, we already adjust some options (foreground and background colors, position of the window) in the default launcher function, see https://github.com/junegunn/fzf/blob/b27dc3eb1745ed29146feca94652bba0f0dd21c2/plugin/fzf.vim#L472-L480

That said, you might be interested in #1019. Once it's done we will be able to display fzf inside GVim without opening an external window.

**Comment by gauthiermartin** [comment]
Thank you very much that was exactly what i was looking for.
I can't wait to use this new integration. Are you far from releasing it ?

**Comment by junegunn** [comment]
Well, it depends on how soon the new terminal emulator of Vim becomes stable. You can apply the patch in advance (https://github.com/junegunn/fzf/pull/1019.patch), install the latest GVim, test it, and help us (and Bram) push things forward.

**Comment by junegunn** [comment]
#1019 is now merged to master.
