### ISSUE TITLE
Question: Get the selected line **number**?

### ISSUE THREAD

**Issue by infokiller** [junegunn/fzf#1034]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [x] bash
    - [x] zsh
    - [ ] fish

Hey, is there an option in fzf for outputting the line number that I'm missing?

If not, what's the best way to get the selected line **number**, as opposed to the actual line content?
Right now I have a script which does this in an hacky way by grepping for the selected line, but this won't always work (for example, if there are duplicate lines in the stream).

Thanks!

**Comment by junegunn** [comment]
Have you looked at #1014?

**Comment by infokiller** [comment]
Thanks a lot @junegunn that looks perfect!
Didn't know about the --with-nth option which is what I needed to implement this.

**Comment by ElectricRCAircraftGuy** [comment]
To have `fzf` show the matching line number of a text file you are searching in, then do this:

```bash
grep -n '' "path/to/file.txt" | fzf
```

NOT this:
```bash
cat "path/to/file.txt" | fzf
```

**Comment by infokiller** [comment]
@ElectricRCAircraftGuy I'm not sure what comment are you replying to, since no one mentioned using `cat` for this in this issue. Anyway, the solution [posted here](https://github.com/junegunn/fzf/issues/1014#issuecomment-321974618) seems better: it can hide line numbers and it's also faster than `grep -n`.

**Comment by ElectricRCAircraftGuy** [comment]
@infokiller , oh, sorry, I'm just documenting a generic answer to the title of the question: "Get the selected line **number**?", which I am demonstrating how to do when passing regular text files to `fzf` to fuzzy search _within_ the file, which is something I previously did with `cat`. I wasn't able to find that anywhere, but google searches led me here so I just jotted it down for future readers who stumble here looking for what I was looking for.

**Comment by Agent-E11** [comment]
@ElectricRCAircraftGuy It looks like you can alter the the answer infokiller linked to to get what you want:

```sh
nl file.txt | fzf | awk '{ print $1 }'
```

This will add line numbers to the _contents_ of `file.txt`, and pipe that to `fzf` to search through. Then print out the line number of the selected line using `awk`.

Personally, I think this looks cleaner than the `grep -n` answer
