### ISSUE TITLE
when asking for input, don't accept input before the user presses return

### ISSUE THREAD

**Issue by mozkeeler** [junegunn/fzf#1035]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

I just installed fzf by running `./mach try fuzzy` for the first time. It asked me some y/n prompts. When I hit 'y', it accepted the input (rather than waiting for a return). This is counter to pretty much every other text interface I've encountered. Even worse, my muscle memory resulted in me pressing return before I had noticed that I was being asked another question, which meant I just accepted the default for the next question.

**Comment by junegunn** [comment]
Fair point, let me fix that, thanks.
