### ISSUE TITLE
Remove entry from list using a keybind

### ISSUE THREAD

**Issue by edubxb** [junegunn/fzf#1036]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [x] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

I wrote a Bash function that with the help of fzf, allows me browse my clipboard history managed by Gpaste cli (gpaste-client), I added a keybind to delete the current selected entry from the history (gpaste-client delete <number>), this works fine, but I also want to remove the same entry from fzf too.

So the question is, can fzf do this?

**Comment by junegunn** [comment]
No, it's not supported. You'll have to set up `--expect` key, and handle it in the script that calls fzf, and relaunch fzf with the updated list in a loop.
