### ISSUE TITLE
parse error in key-bindings.bash

### ISSUE THREAD

**Issue by TwIStOy** [junegunn/fzf#1038]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [x] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

I got an error when I open my terminal:
/Users/xxxxx/.fzf/shell/key-bindings.bash:7: parse error: condition expected: $-

**Comment by TwIStOy** [comment]
And I have update my zsh and oh-my-zsh to the latest version.

**Comment by junegunn** [comment]
You use zsh, you should load `key-bindings.zsh` not bash.
