### ISSUE TITLE
fzf-tmux shows bad output

### ISSUE THREAD

**Issue by goozler** [junegunn/fzf#1039]
- Category
    - [ ] fzf binary
    - [x] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

Hi! I started to get unnecessary output while executing `fzf-tmux` script.

Simple run of `fzf-tmux` always shows in the terminal
```bash
trap 'kill -SIGUSR1 -57719' EXIT SIGINT SIGTERM;"/Users/username/.fzf/bin/fzf"  "--no-height" > /var/folders/tx/l5vzxn11103b_knjp6ntrwg40000gn/T//fzf-fifo2-27770; echo $? > /var/folders/tx/l5vzxn11103b_knjp6ntrwg40000gn/T//fzf-fifo3-27770 ; trap - EXIT SIGINT SIGTERM
```

It breaks [some helpers](https://github.com/junegunn/fzf/wiki/examples#opening-files) that I used to use. The output above gets to the `files` variable. But it works fine when it's used via pipes like `git branch | fzf-tmux -d 15` (the output is clean)

Some time ago everything worked fine. Let me know if you need more information like which commit broke it or something like that, I would be glad to help!

**Comment by junegunn** [comment]
Duh, somehow I forgot to remove unnecessary `cat` command, should be fixed now. Thanks for letting me know!

**Comment by goozler** [comment]
OMG, so fast! Yes, it's helped! Thank you very much!
