### ISSUE TITLE
sed command doesn't work well in preview

### ISSUE THREAD

**Issue by amosbird** [junegunn/fzf#1044]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [x] fish

The command I'm using is 
`cat /usr/share/dict/words | fzf --preview "{ sdcv -en {} | sed -n '2,$p'; wn {} -over | sed -n '2,$p'; } | fold -s -w 100" --preview-window=up:60% --bind=ctrl-o:kill-line`

```
sed -e expression #1 , char 2: unexpected `,'
sed -e expression #1 , char 2: unexpected `,'
```

**Comment by junegunn** [comment]
It looks like `$p` should be escaped as `\$p` since you're using double-quotes. Does this help?

**Comment by amosbird** [comment]
oh, thanks!

**Comment by junegunn** [comment]
By the way, you don't need fold, just append `:wrap` to --preview-window

**Comment by amosbird** [comment]
does that :wrap at space character?

**Comment by junegunn** [comment]
Ah, so you don't want to break words, then `:wrap` won't help.

**Comment by amosbird** [comment]
yep

**Comment by amosbird** [comment]
@junegunn Hi, how can I make the preview arguments quoted?

**Comment by junegunn** [comment]
Preview arguments such as `{}` or `{1}` are evaluated to single-quoted strings. See `man fzf`.

**Comment by amosbird** [comment]
ah, it's sdcv to blame :)
