### ISSUE TITLE
How to apply fzf search on specific dir without going there

### ISSUE THREAD

**Issue by nikitavoloboev** [junegunn/fzf#1045]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [x] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

I have this function in my zshrc : 

```Bash
fe() {
  local files
  IFS=$'\n' files=($(fzf-tmux --query="$1" --multi --select-1 --exit-0))
  [[ -n "$files" ]] && nvim "${files[@]}"
}
```

It lets me search for contents of the current directory I am in and then edit that file. However I wish to modify this function so that it searches only a specific directory (~/.dotifles/ in my case) from wherever I am.

I first thought to cd ~/.dotfiles and then run the remaining of the command but I wish to avoid that.

Thank you for any help.

**Comment by junegunn** [comment]
fzf is a unix filter, so you can feed any input like so

```sh
# You can use any command you find fit as the source
find ~/.dotfiles | fzf-tmux
```

I hope this answers your question.
