### ISSUE TITLE
[Request] regex matcher for filtering list

### ISSUE THREAD

**Issue by carnager** [junegunn/fzf#1054]
- Category
    - [x] fzf binary
    - [ ] Etc.
- OS
    - [x] Linux
    - [x] Mac OS X
    - [x] Windows
    - [x] Windows Subsystem for Linux
    - [x] Etc.

In rofi there is a feature that allows to use regular expressions in the inputbar. E.g. I use it to show a range of ratings of my tracks displayed in rofi: r=([6-9]|10). 

Is there a chance a feature like this could be implemented in fzf as well?

**Comment by junegunn** [comment]
No, I don't have plan to support general regex anytime soon, as I'd like to keep fzf as simple and small as possible. https://github.com/peco/peco seems to support regex, so you might want to try it instead.

**Comment by kevinhwang91** [comment]
@carnager You can give skim a try, which supports the regex.

**Comment by rayiik** [comment]
also you can technically do this 
```bash
#!/bin/bash -
#===============================================================================
#
#          FILE: test.sh
#
#         USAGE: ./test.sh
#
#   DESCRIPTION:
#
#       OPTIONS: ---
#  REQUIREMENTS: ---
#          BUGS: ---
#         NOTES: ---
#        AUTHOR: Rayiik (), dsimon_aas@hotmail.com
#  ORGANIZATION:
#       CREATED: 08/03/2020 03:34:53 PM
#      REVISION:  ---
#===============================================================================


declare gvar=''
declare Fvar=''
if [[ -z "$1" ]]; then
  Fvar='.'; else
  Fvar="$1"
fi
if [[ -z "$2" ]]; then
  gvar='.'; else
  gvar="$2"
fi
_rgf="rg '{q}' ./ --color=always --colors=match:fg:12 --no-filename"
fd -uu -t f "$Fvar" | rg "$gvar" --no-filename | fzf --phony \
  --preview="cat  {} | $_rgf"
unset gvar
unset Fvar
unset _rgf

```
just to give an example of the concept, will search in folder
