### ISSUE TITLE
Feature request: new option preview-window-scroll

### ISSUE THREAD

**Issue by maikelmeyers** [junegunn/fzf#1057]
I'm working on a small wrapper for ag. The results of an ag search is fed into fzf. The preview window shall show the highlighted contents of the files found by ag. Additionally the line of the source file where the searched pattern was found shall be at the middle position of the preview window and extra highlighted.
I managed to achieve this by cutting the output for the preview window around the line of the searched pattern to the preview window height.
Disadvantage: I can not scroll thru the source file anymore. This would only be possible if there was an option to scroll the preview window by an fzf-option. This way it would be possible to output the full source file and to jump to the pattern.
This option must be similar to the --preview option, because the current selection is needed to extract the line number of the found pattern.

Example:

`fzf --preview-window-scroll='some_function_to_calculate_the_scroll_value {}'`

**Comment by junegunn** [comment]
> I'm working on a small wrapper for ag

FYI, there is a similar implementation in https://github.com/junegunn/fzf.vim, which looks like this:

<img width="1280" alt="screen shot 2017-09-24 at 11 07 32 am" src="https://user-images.githubusercontent.com/700826/30778751-aaedb51e-a118-11e7-8ee2-a477b8da38a8.png">

Anyway, I'll think about the request. I'm not sure though how many users will actually use it, as they have to come up with two commands for previewing, and it's a hassle.

**Comment by maikelmeyers** [comment]
OK. But it would be optional. No one needs to use this second command if he does not need it. I will take a look at the implementation in fzf.vim. Thanks for the hint.

**Comment by durcheinandr** [comment]
@maikelmeyers I search also for such a solution, but didn't need scrolling. Is it possible to show how you managed this (cutting the output for the preview window around the line of the searched pattern to the preview window height)?

**Comment by maikelmeyers** [comment]
Yes. I show you the first part of my fag function (fzf ag). Sorry it is currently a bit messy and uncommented yet and maybe sometimes it is not the best way to do it because of my poor bash knowledge, but anyway, it works. I skipped showing the second part of fag, that is for handling the results by different shortcuts (edit, replace and so on). This file is sourced in bashrc. I skipped also the rest of the whole file that also includes all the stuff from key-bindings.bash and bash-completion (slightly modified to my needs). If you are interested, I shall cleanup the file a little bit :) Regarding to your question: Look into the lines with FZF_AG_PREVIEW_COMMAND. I used tput to find the preview height (with the assumption that the preview window is half the terminal height)
```
FZF_DEFAULT_OPTS="--extended-exact --height 100% --cycle --no-reverse --bind ctrl-a:select-all "
FZF_DEFAULT_OPTS+="--bind pgup:preview-up --bind pgdn:preview-down --bind ctrl-f:jump --bind ctrl-k:kill-line --bind ctrl-p:toggle-preview"
FZF_DEFAULT_PREVIEW_COMMAND='\
  __file="$(echo {})"; \
  [[ $(file -L "$__file") =~ directory ]] && ls -la --color=always "$__file" \
  || [[ $(file -L --mime "$__file") =~ binary ]] && file -L "$__file" | cut -d":" -f2- \
  || (highlight -O ansi -l "$__file" || coderay "$__file" || rougify "$__file" || cat "$__file") 2> /dev/null | head -500'

fzf() {
  local __PREVIEW_WINDOW_COMMAND=$(if [ `tput cols` -lt 140 ]; then echo "up"; else echo "right"; fi)
  /usr/bin/fzf --preview-window="$__PREVIEW_WINDOW_COMMAND" --preview="$FZF_DEFAULT_PREVIEW_COMMAND" $FZF_DEFAULT_OPTS "$@" 
}

FZF_AG_PREVIEW_COMMAND='
  __file="$(echo {} | awk -F ":" '\''{print $1}'\'')"
  __line_nr="$(echo {} | awk -F ":" '\''{print $2}'\'')"
  __hl_content=$((highlight -O ansi -l --force "$__file" || coderay "$__file" || rougify "$__file" || cat "$__file") 2> /dev/null)
  __context_count=$(( $(tput lines) / 4 - 1 ))
  __start_line=$(( __line_nr - __context_count ))
  if (( __start_line < 1 )); then (( __start_line=1 )); fi
  if (( __start_line == __line_nr )); then (( __start_line=10000000000 )); fi
  __hl_line=$(printf "\e[1;33m%5s\e[0m " "$__line_nr"; cat "$__file" | sed "${__line_nr}q;d" | ag --color '\''__PATTERN'\'' | tr -d "\n")
  echo "$__hl_content" | sed -n "${__start_line},$(( __line_nr-1 ))p"; echo "$__hl_line"; echo "$__hl_content" | sed -n "$(( __line_nr+1 )),$ p"'


fag() {
  local __args_backup=("$@")
  local __pattern=''
  local __ag_color='--color'
  while [ $# -gt 0 ]; do
    if [[ $1 =~ ^-.* ]]; then
      shift
    else
      __pattern="$1"
      break
    fi
  done
  set -- "${__args_backup[@]}"
 
  if [ "$__pattern" == "." ]; then
    __ag_color='--nocolor'
  fi

  local __escaped_pattern=$(echo "$__pattern" | sed -e 's/[\/&]/\\&/g')
  local __preview_cmd=$(echo "$FZF_AG_PREVIEW_COMMAND" | sed "s/__PATTERN/$__escaped_pattern/g")
  local __selected=$(ag --nobreak --noheading --depth -1 -f --hidden "$__ag_color" "$@" 2> /dev/null | fzf --multi --ansi --preview="$__preview_cmd" --preview-window=down --expect=ctrl-o,ctrl-e,ctrl-s,ctrl-b,ctrl-n,ctrl-l,ctrl-r)
}
```

**Comment by durcheinandr** [comment]
@maikelmeyers Thanks a lot. Works (slightly modified) as expected.

**Comment by gibfahn** [comment]
>Anyway, I'll think about the request. I'm not sure though how many users will actually use it, as they have to come up with two commands for previewing, and it's a hassle.

FWIW I quite like this idea, it's actually pretty minimal compared to what I was expecting, which was something more like:

```bash
  --preview 'awk -F : "{print \$1 \" \" \$2}" <<<"{}" | \
             read _gib_file _gib_line; \
             BAT_PAGER="/usr/bin/less +$_gib_line" bat --color=always --style=full "$_gib_file"'
```

instead I think something like this would work:

```bash
  --preview 'awk -F : "{print \$1}" <<<"{}" | xargs bat --color=always --style=full' \
  --preview-scroll 'awk -F : "{print \$2}" <<<"{}"'
```

**Comment by edi9999** [comment]
For the :FZFAg command it would definitely be useful to be able to scroll in the file in the preview window.

Often times, the fact that I have just 6 lines on top and 15 lines below of context is not enough.

**Comment by edi9999** [comment]
To avoid `cat` on a huge file, it could also be an opt-in option where you would say : 

```
--preview  'mypreviewcmd {1} {scrollpos}'
```

And when the `{scrollpos}` argument is present in the preview command, it means that the scrolling behavior is managed by the preview command itself.

When the preview is run initially, scrollpos value would be 0.

If for example searching for 'foobar', the following command would be executed : 

```
mypreviewcmd foobar 0
```

in `mypreviewcmd`, this would mean that the scroll position is the initial one, and one would do : 

```
mypreviewcmd() {
   search="$1"
   scroll="$2"
   line_match="$(fn_to_get_linenumber "$search")"
  # The following sed prints line numbers st
   sed -n "$((line_match - 5 + $scroll)),$((line_match + 5 + $scroll))p" file-searched 
}
```

If the user scrolls to the top, the `mypreviewcmd` is run with following args : 

```
mypreviewcmd foobar -1
```

and the screen updates.

In the same way, if the user scrolls down 10 lines, the `mypreviewcmd` is run with following args : 

```
mypreviewcmd foobar 9 # 9 because the user scrolled one time up and ten times down.
```

One problem with that approach is that we don't know how much you can scroll up or down (which could as well be a feature cause it would mean we can do things such as infinite scroll). Maybe returning `""` (an empty string) could have a special meaning to say : you can't scroll below this {scrollto} amount.


What do you think of that ?
