### ISSUE TITLE
Select first item when search term changes

### ISSUE THREAD

**Issue by schoettl** [junegunn/fzf#1058]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

When I use `fzf -m` to select multiple items, a typical workflow is:

1. type "apple"
2. select e.g. the third matching item using arrow keys and tab
3. clear search and type "banana"
4. select items with tab

**I think it would make sense to automatically select the first matching item, when the user changes the search term.** Even for non multi-select this would make sense.

Considerations:

- The user change the search term to narrow down the result list. The best matching item is the first one, so why not select it automatically?

- Especially when the user clears the search term and types a new one, it does not make sense to keep the n-th item selected.

- Given the user moves the selection to the *third* item (using arrow keys). Then if they change the search term, how could they ever anticipate what will be the *third* item? In contrast, the first item is the best match for the search result.

**Comment by junegunn** [comment]
See https://github.com/junegunn/fzf/blob/master/CHANGELOG.md#0168 

You might want to read through the man page of fzf if you haven't already. You'll find some nice surprise.

Regading it not being the default behavior, please understand that I try to be conservative on changing the defaults as there are many users that have used fzf for years and I'd not surprise that with sudden changes.

**Comment by schoettl** [comment]
Thank you for the links to the changelog. Yes, the man page has really very nice surprises :) I just missed or forgot about the `top` action.

So both questions were actually about changing default behavior. I understand that you're conservative on changing these because of existing users... although for new users and the future in general I'd try to optimize defaults.

Anyway, thank you for this great tool and for the `--bind` option!
