### ISSUE TITLE
[multi-select mode] switch action of tab and shift-tab for non --reverse

### ISSUE THREAD

**Issue by schoettl** [junegunn/fzf#1059]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [x] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

`fzf -m --reverse` has great usability. I can just press the tab key 3 times to select the first 3 items.

In `fzf -m` I have to press shift-tab to select multiple items. Most beginners would probably press tab, up, tab, up, up, tab to select the first 3 items.

Could we switch the actions of tab and shift-tab in the normal mode but not in the --reverse mode?

**Comment by junegunn** [comment]
https://github.com/junegunn/fzf/blob/master/CHANGELOG.md#0112 should answer your question. I considered making that behavior the default, but I decided not to, as I felt it was confusing. That's probably because I'd been using fzf for years already and had gotten comfortable with shift-tab
