### ISSUE TITLE
Installation failed on AArch64

### ISSUE THREAD

**Issue by LER0ever** [junegunn/fzf#1060]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

### The installation will fail on armv8 (aarch64) because it checks `uname -sm` for `Linux armv8`. But instead, the result on armv8 is `Linux aarch64`.

**Comment by junegunn** [comment]
Thanks for the report. So does this patch fix the issue?

```diff
diff --git a/install b/install
index c6b4b8c..54c66d8 100755
--- a/install
+++ b/install
@@ -174,6 +174,7 @@ case "$archi" in
   Linux\ armv6*) download fzf-$version-linux_${binary_arch:-arm6}.tgz    ;;
   Linux\ armv7*) download fzf-$version-linux_${binary_arch:-arm7}.tgz    ;;
   Linux\ armv8*) download fzf-$version-linux_${binary_arch:-arm8}.tgz    ;;
+  Linux\ aarch64*) download fzf-$version-linux_${binary_arch:-arm8}.tgz  ;;
   FreeBSD\ *64)  download fzf-$version-freebsd_${binary_arch:-amd64}.tgz ;;
   FreeBSD\ *86)  download fzf-$version-freebsd_${binary_arch:-386}.tgz   ;;
   OpenBSD\ *64)  download fzf-$version-openbsd_${binary_arch:-amd64}.tgz ;;
```

**Comment by ehandal** [comment]
Unfortunately this didn't work because `Linux aarch64` fired the `Linux\ *64` so it tries to download the amd64 binary.

**Comment by junegunn** [comment]
@ehandal Thanks, fixed it.
