### ISSUE TITLE
:FZF ~ empty in (neo)vim

### ISSUE THREAD

**Issue by refacto** [junegunn/fzf#1061]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [x] Vim
    - [x] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [x] Etc. (Termux)
- Shell
    - [ ] bash
    - [ ] zsh
    - [ ] fish

Whenever I try to use :FZF ~ from within vim or neovim, it shows:
```
  0/0
~/
```
The same goes for :Files from the fzf.vim plugin.
Although, `find | fzf` works perfectly. Note that I'm using termux, so shell variables might be unusual, but they're correct: `$SHELL` is `/data/data/com.termux/files/usr/bin/zsh`, `$TERM` is `xterm`.

**Comment by junegunn** [comment]
> Although, find | fzf works perfectly

How about plain `fzf` (without stdin pipe)? Does it work?

**Comment by refacto** [comment]
That's empty as well.

**Comment by junegunn** [comment]
Do you have `$FZF_DEFAULT_COMMAND` defined? Is it a valid command? Does it work?

**Comment by refacto** [comment]
I've now set `$FZF_DEFAULT_COMMAND` to `cat`, no change.

**Comment by refacto** [comment]
According to #510 I've now manually set FZF_DEFAULT_COMMAND to 
```
find . -path '*/\.*' -prune -o -type f -print -o -type l -print 2> /dev/null | sed s/^..//
```
And now it works perfectly. Thanks for the hint!

**Comment by junegunn** [comment]
Setting `$FZF_DEFAULT_COMMAND` is not required. As noted in #510, fzf launches the default find command when the variable is not defined and it should work just fine. Also, recent versions of fzf prints `[ERROR]` on the screen when the command has failed.

```
  0/0 [ERROR]
>
```

Did you notice the message?

**Comment by refacto** [comment]
There was no message, just this.
```
  0/0
>
```
It still happens when i unset `$FZF_DEFAULT_COMMAND`

**Comment by junegunn** [comment]
That's strange, the following is the default command fzf uses, can you check if it works on your machine?

```sh
command find -L . -mindepth 1 \( -path '*/\.*' -o -fstype 'sysfs' -o -fstype 'devfs' -o -fstype 'devtmpfs' -o -fstype 'proc' \) -prune -o -type f -print -o -type l -print 2> /dev/null | cut -b3-
```

**Comment by refacto** [comment]
Nope, doesn't work.

**Comment by junegunn** [comment]
Okay thanks, I see. Looks like `| cut -b3-` at the end overrides the exit status of the find command (because `pipefail` is not set by default). I'll see what I can do about it.

Anyway, do you have any idea why that find command doesn't work on your system?

**Comment by refacto** [comment]
Yup. When I truncate the command a bit, I get this:
```
find: unrecognized: -fstype
```
My `find` is from BusyBox, might explain the missing options.

**Comment by junegunn** [comment]
I see, thanks for the investigation. Maybe I could change the default command to retry with simpler command on failure. i.e. `find -foo -bar -baz || find -foo`

**Comment by junegunn** [comment]
I'm thinking about changing the default command as follows

```diff
diff --git a/src/constants.go b/src/constants.go
index cfd3a3b..c3a3dd2 100644
--- a/src/constants.go
+++ b/src/constants.go
@@ -55,7 +55,7 @@ var defaultCommand string
 
 func init() {
 	if !util.IsWindows() {
-		defaultCommand = `command find -L . -mindepth 1 \( -path '*/\.*' -o -fstype 'sysfs' -o -fstype 'devfs' -o -fstype 'devtmpfs' -o -fstype 'proc' \) -prune -o -type f -print -o -type l -print 2> /dev/null | cut -b3-`
+		defaultCommand = `bash -c "set -o pipefail; (command find -L . -mindepth 1 \( -path '*/\.*' -o -fstype 'sysfs' -o -fstype 'devfs' -o -fstype 'devtmpfs' -o -fstype 'proc' \) -prune -o -type f -print -o -type l -print || command find -L . -mindepth 1 -path '*/\.*' -prune -o -type f -print -o -type l -print) 2> /dev/null | cut -b3-"`
 	} else if os.Getenv("TERM") == "cygwin" {
 		defaultCommand = `sh -c "command find -L . -mindepth 1 -path '*/\.*' -prune -o -type f -print -o -type l -print 2> /dev/null | cut -b3-"`
 	} else {
```

**Comment by refacto** [comment]
Sounds good. I'll try this.

**Comment by igbanam** [comment]
I ran into this error some hours ago. 

I'm in Termux also, with oh-my-termux (a ZSH flavour) installed.

I see 8eab611 reverts the change to use a simpler find. Is there a default command we should be using here?
