### ISSUE TITLE
ctrl-r doesn't work for fish 2.6.0

### ISSUE THREAD

**Issue by 3xp10it** [junegunn/fzf#1063]
I am using fish 2.6.0 and fzf,according to below content,I typed ctrl-r in my fish,but cann't get history commans,it seems fzf doesn't work on ctrl-r for fish 2.6.0

https://github.com/junegunn/fzf#key-bindings-for-command-line

env:
macOS sierra10.12.6
iterm2
fish2.6.0
tmux

**Comment by junegunn** [comment]
Works for me. Make sure you followed the installation instructions correctly.

**Comment by 3xp10it** [comment]
It works now,thanks.
