### ISSUE TITLE
fzf history completion -- question after a recent update

### ISSUE THREAD

**Issue by yevhen-m** [junegunn/fzf#1065]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [x] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

Recently I noticed `*` before some commands in fzf-history-completion? What does it mean?
<img width="174" alt="screen shot 2017-09-27 at 3 02 02 pm" src="https://user-images.githubusercontent.com/10185058/30912368-e02dd92e-a394-11e7-92a7-c071d7f07139.png">

**Comment by junegunn** [comment]
That is from zsh. I'm a bash user, so I can't be sure about zsh, but on bash, it happens when you edited the entry.

**Comment by yevhen-m** [comment]
@junegunn  thanks.
