### ISSUE TITLE
[neovim]  fzf#call not working anymore

### ISSUE THREAD

**Issue by cinghiopinghio** [junegunn/fzf#1066]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [X] Neovim
    - [ ] Etc.
- OS
    - [X] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [X] zsh
    - [ ] fish

Hi,
Not sure this is the right place since it's related to vim/neovim but I think `fzf#call` is defined in this place.

Anyway I had a command define with `fzf#call` but since last update however I call that function I get
![FZF#call bug](https://imgur.com/WXzND1k.jpg)
I really don't know what's going on.

Since last update I had a new slightly annoying bug on `:File` command: whenever the `find` command throw an error  (like it is unable to enter a folder due to permissions) it prints the warning on screen.
Not sure if this is related to the previous...

**Comment by janlazo** [comment]
There is `s:fzf_call` in the Vim plugin but users shouldn't use it directly anyway.
I can't find`fzf#call` in the git history of the Vim plugin so I don't think it's defined here.

**Comment by junegunn** [comment]
@janlazo Looks like it's a typo of `fzf#run`.

> but since last update

@cinghiopinghio Which version did you use before the update? And how did you update fzf?

**Comment by cinghiopinghio** [comment]
@junegunn I don't know which version I was on But maybe it's a neovim problem, in fact I tried the same configuration in vim8 and there it actually works as expected.

I tried to go back several commits in both `fzf` and `fzf.vim` but I couldn't find the incriminated commit. The problem is that there was not recent update in neovim recently (nor in python-neovim).

**Comment by junegunn** [comment]
There was an error in the code which caused Neovim to use `--height` instead of its terminal buffer when none of the layout options are given. Should be fixed now.

**Comment by cinghiopinghio** [comment]
I confirm it works now.
Thanks for the fast bug-fixing.
