### ISSUE TITLE
Suggestion for documentation

### ISSUE THREAD

**Issue by chrisjohnson** [junegunn/fzf#1067]
- Category
    - [x] Completion
- OS
    - [x] Mac OS X
- Shell
    - [x] zsh

This isn't a bug, just a suggestion for the documentation. Right now, in the [settings section](https://github.com/junegunn/fzf#settings), you mention a solution to use ag for `_fzf_compgen_path` and call out the fact that ag only works on files not directories. This is great because by default path and dir globbing in homedir take a long time on my machine with tons of files, and being able to use a `.ignore` would greatly improve that. However, it doesn't solve the issue for dir globbing.

I would propose adding the following function definition (or a comparable ag definition) to also work for directory completion:

```
_fzf_compgen_dir() {
	rg --hidden --files --null "$1" 2>/dev/null | xargs -0 dirname | awk '!h[$0]++'
}
```
I found the suggestion in ripgrep's issues and they proposed using `| uniq` instead of this awk command, but uniq requires duplicates to be adjacent to one another, which results in duplicate results. I tried prepending `| sort` which removes duplicates but makes the command take about 3x longer. Finally I stumbled on this awk snippet which doesn't require the duplicates to be adjacent, and has the happy benefit of actually being a decent bit faster than the `| uniq` approach.

----

**Note**: For anybody reading this, you need to use `gdirname` from the coreutils homebrew package on OS X instead of dirname. I used this block to determine which dirname to use:

```
if [[ $(uname) == "Darwin" ]]; then
	# dirname on OS X behaves funky, get gdirname via
	# brew install coreutils
	export dirname_command="gdirname"
else
	export dirname_command="dirname"
fi
```

I understand this dirname business is probably too much for the fzf documentation though

**Comment by junegunn** [comment]
Thanks for the suggestion. You're right that `_fzf_compgen_dir` is not mentioned on the page and I should add it.

I like how you implemented `_fzf_compgen_dir` with standard utilities, it's simple and concise. But it's sad to see that simplicity is undermined by the inconsistency of dirname on macOS. I'll see if there are simpler options.

Note that ripgrep may not be a good choice until a new version is released. See https://github.com/BurntSushi/ripgrep/issues/200

**Comment by chrisjohnson** [comment]
I posted the same snippet into a ripgrep issue and somebody responded with a zsh approach which used the `h` modifier but unfortunately zsh would wait for the entire list to be generated before extracting the dirname which made it infeasible. Also it consumed a huge amount of memory.

Given that you currently use ag in the path function it seems reasonable to do the same for dir which will alleviate waiting on ripgrep to release. But I haven't found a good portable alternative to `dirname/gdirname` yet

**Comment by chrisjohnson** [comment]
@junegunn Check it out, this `awk` command behaves just like `dirname` only faster. If I were smarter at `awk` I bet the two `awk` statements could be combined but for now it runs just as fast as the original `dirname/gdirname` approach:

```
_fzf_compgen_dir() {
	rg --hidden --files . 2>/dev/null | awk -F'/[^/]*$' '{print $1}' | awk '!h[$0]++'
}
```

**Comment by blankname** [comment]
@chrisjohnson How about:
```
_fzf_compgen_dir() {
	rg --hidden --files . 2>/dev/null | awk -F'/[^/]*$' '!h[$1]++ { print $1 }'
}
```

**Comment by chrisjohnson** [comment]
Yep that's what I meant, that's what #awk suggested. But I'm currently investigating that the number of results that comes back is the same -- it seems like it does not. I need to wrap up some work but I'll paste results later

**Comment by blankname** [comment]
I think in your snippet this: 
```
h[$0]
```
should have a $1, not a $0.

**Comment by chrisjohnson** [comment]
Yep typo on my paste here. I fixed that. But it looks like the logic to de-dupe dirname doesn't match up with other approaches. See gist: https://gist.github.com/anonymous/132daebf67acf0bacaf490377713ccfa

I get a different word count only for the 2 awk approaches that use awk to get the dirname

**Comment by chrisjohnson** [comment]
After diffing I can see it's because the awk snippet for grabbing the dirname doesn't handle filenames with no dir before them, so .foo/bar returns .foo but .foobar just returns .foobar. 

Here's an approach that #awk helped me put together, which is fast and has the correct number of results. The downside is that it's a bit long.

```
_fzf_compgen_dir() {
	rg --hidden --files . 2>/dev/null | awk 'function dirname(fn) { if (fn == "") return ".";  if (fn !~ "[^/]") return "/"; sub("/*$", "", fn); if (fn !~ "/") return "."; sub("/[^/]*$", "", fn); if (fn == "") fn = "/"; return fn } {$0 = dirname($0)} !a[$0]++'
}
```

**Comment by chrisjohnson** [comment]
Given your thumb I made a PR with this final version
