### ISSUE TITLE
A way to filter multiple occurrences

### ISSUE THREAD

**Issue by eyalev** [junegunn/fzf#1070]
- Category
    - [ ] fzf binary
    - [x] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

Let's say I run:

```
$ echo 1
1
$ echo 111
111
```
I would like to run `fzf` with some option so when I search the history with: `1 1 1` I will only see `echo 1 1 1` as a result and not `echo 1`.

Is there some flag that could enable that?

Thanks

**Comment by junegunn** [comment]
Why don't you just type in `111`?

**Comment by eyalev** [comment]
Forgot to mention: I'm using the `--exact` option. 

`export FZF_DEFAULT_OPTS="--exact"`

So `111` doesn't seem to work in that case.

**Comment by junegunn** [comment]
Literal spaces can be escaped, i.e. `1\ 1\ 1`. Or you can set `--no-extend`, but I don't recommend it. By the way, I don't see much point in `--exact`, as fzf will show exact matches as the top matches even in fuzzy matching mode.
