### ISSUE TITLE
fzf weird order

### ISSUE THREAD

**Issue by plexigras** [junegunn/fzf#1071]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [x] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

the order doesnt make any sense what so ever it shows me random files in far of directorys rather then what im acctually looking for

**Comment by junegunn** [comment]
Not enough information.

**Comment by plexigras** [comment]
@junegunn what do you want to know?

**Comment by plexigras** [comment]
i do
```
$ touch Documents/example.txt
$ fzf
```
and type `example`

... 

now a alot of stuff gets shown that is many directorys deap but `example.txt` is nowhere to be found

so i was wondering if there is some kind of priority system like with [fasd](https://github.com/clvv/fasd)?

is this the information you wanted @junegunn?

**Comment by junegunn** [comment]
> now a alot of stuff gets shown

I can't tell if fzf is doing the right thing or not with the information you provided. A screenshot would be helpful here.

> example.txt is nowhere to be found

I don't think it's possible unless you have a custom `FZF_DEFAULT_COMMAND` that bypasses `Documents` directory.
