### ISSUE TITLE
Fzf 0.17.0 shows "[ERROR]"

### ISSUE THREAD

**Issue by rstacruz** [junegunn/fzf#1076]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux (Ubuntu)
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [x] fish

Running `fzf` anywhere shows this:

![image](https://user-images.githubusercontent.com/74385/31105047-a4ac5ce4-a813-11e7-8a27-47517df99757.png)

Is there any way to investigate why it shows `[ERROR]`?

**Comment by rstacruz** [comment]
Reverting to 0.16.4, it doesn't show `ERROR` but the files list is still empty.

**Comment by junegunn** [comment]
It means your `$FZF_DEFAULT_COMMAND` is not working. Make sure that it's correct, or unset it.
