### ISSUE TITLE
Print more information on a failure of $FZF_DEFAULT_COMMAND

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [junegunn/fzf#1080]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [ ] fish

So, I've got an `$FZF_DEFAULT_COMMAND` that works when typed directly, but causes the infamous fzf `0/0 [Error]`, on my system:

```sh
export FZF_DEFAULT_COMMAND='/usr/local/bin/rg --files --hidden --smart-case --glob "\!.git/*"'
```

I can't really think of any way to begin debugging this, as it works just fine when executed directly. It'd be really helpful if command-line `fzf` were to print something more informative than `[Error]` if something goes wrong in executing the `FZF_DEFAULT_COMMAND`!

(For context, this is *eventually* intended to be used inside `fzf.vim`, which I found via [these instructions](https://medium.com/@crashybang/supercharge-vim-with-fzf-and-ripgrep-d4661fc853d2).)

Thanks! `(=`

**Comment by junegunn** [comment]
Actually, fzf cannot provide more information on why the command has failed. All it knows is that it finished with non-zero exit status. You might want to redirect the stderr of the command to a temporary log file to debug the issue.

Anyway, your command does not work for me on plain shell, with no output:

```sh
> /usr/local/bin/rg --files --hidden --smart-case --glob "\!.git/*"
> echo $?
1
```

I could make it work by using single quotes and unescaping `\!`

**Comment by ELLIOTTCABLE** [comment]
I mean, couldn't it display output in the case of failure, and show the numeric exit-code? That'd at least aid debugging more than simple `[Error]`, I'd think?

(And weird! Does `fzf` use a particular shell, instead of the user's selected shell? That works on my zsh, so it surprised me it didn't work in `fzf`. And yes, that indeed works! Thank you.)

**Comment by junegunn** [comment]
> it display output in the case of failure

Technically, fzf does not suppress the output in case of an error. Actually, it does not print `[ERROR]` if the program generated any output.

```sh
# No [ERROR] even though the script finished with non-zero exit status
FZF_DEFAULT_COMMAND='(echo foo; exit 1)' fzf
```

I'll see if there's a simple way to improve the message.

> Does fzf use a particular shell, instead of the user's selected shell? 

If uses `$SHELL`, if undefined, `sh`.
