### ISSUE TITLE
Install script should reference `fzf_base` for key binding install instead of `~/.fzf`

### ISSUE THREAD

**Issue by moollaza** [junegunn/fzf#1081]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [x] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [x] bash
    - [x] zsh
    - [ ] fish

Installing fzf keybinding doesn't work when installed via homebrew because the install script directly references `~/.fzf` instead of `$fzf_base`.

Happy to submit a PR, but wanted to confirm this is how it should behave.

Looks like lines [242](https://github.com/junegunn/fzf/blob/master/install#L242), [243](https://github.com/junegunn/fzf/blob/master/install#L243), and [355](https://github.com/junegunn/fzf/blob/master/install#L355) simple need to replace `~/` with `"$fzf_base"`. I've done this locally and confirmed that the keybindings install as expected.

**Comment by junegunn** [comment]
Hello, I think you're mistaken. It works with homebrew. Follow the instruction in `brew info fzf`, then reload your shell configuration file (or just start a new shell), and you'll see that the bindings work.

The lines you referenced points to `~/.fzf.bash` and `~/.fzf.zsh` that are generated by the install script which is not the base directory where fzf is installed.

**Comment by moollaza** [comment]
Odd, it didn't work before, but after doing another fresh install everything seems to work. Sorry for the noise.

**Comment by junegunn** [comment]
No problem.
