### ISSUE TITLE
![#]:command not found

### ISSUE THREAD

**Issue by GaryFurash** [junegunn/fzf#1082]
- Category
    - [X] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [X] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [ ] Mac OS X
    - [X] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [X] bash
    - [ ] zsh
    - [ ] fish

- ctrl-R
- pick a line from history
- returns error "-bash: !501: command not found" (or whatever line I pick)
- if I then type !501 (or whatever number) it works fine

**Comment by junegunn** [comment]
Can you provide more details on your environment?  bash on Windows, but not WSL?

**Comment by GaryFurash** [comment]
OS: Windows 7
Software: Cygwin x64 w/ latest build
Bash shell

**Comment by junegunn** [comment]
I haven't really tested the shell extensions on Cygwin environment, as I realized fzf can be used on Cygwin only recently. I'll look into it when I get a chance. And feel free to send me a pull request if you know how to fix it.

**Comment by GaryFurash** [comment]
Is there anyway i can undo the CTRL-R mapping. Everything else works fine.

**Comment by junegunn** [comment]
```sh
bind '"\C-r": reverse-search-history'
```

**Comment by GaryFurash** [comment]
Thanks!

**Comment by GaryFurash** [comment]
How can I help test this stuff. I use the Cygwin setup utility to get all my stuff.
