### ISSUE TITLE
vim: sets local dirs (via :lcd)

### ISSUE THREAD

**Issue by blueyed** [junegunn/fzf#1085]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [x] Vim
    - [x] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [ ] fish

The Vim plugin uses `:lcd` to push/pod dirs, but should rather use the most appropriate `cd` command (`let cd = haslocaldir() ? 'lcd' : (exists(':tcd') == 2 && haslocaldir(-1, 0)) ? 'tcd' : 'cd'`).
Therefore the window where fzf has been used with gets a local dir (`haslocaldir()`).

Any thoughts on this, otherwise I might provide a PR which remembers the prev dir together with the command being used (and use that also for popping).

**Comment by junegunn** [comment]
> fzf has been used with gets a local dir (haslocaldir())

I see, but I'm not sure what the issue is. What problem do you have when it's set? Also, `haslocaldir`  in Vim 7.4 does not take arguments, so I don't want to use it that way.

**Comment by blueyed** [comment]
I am using only `haslocaldir()` with Vim in the PR.

The problem is that `:lcd` is meant to be special, and that I normally have a global or tab-local working dir.  If a local window dir is set, this will not adjust.
When saving views (e.g. via vim-stay) you have to put additional workarounds in place to not store this (https://github.com/kopischke/vim-stay/issues/10).
