### ISSUE TITLE
Fix shell extensions on Cygwin

### ISSUE THREAD

**Issue by junegunn** [junegunn/fzf#1087]
- Category
    - [x] Key bindings
    - [x] Completion
- OS
    - [x] Windows (Cygwin)
- Shell
    - [x] bash
    - [x] zsh
    - [x] fish

- Key bindings fail with `--height options is currently not supported on Windows` even when `--no-height` is set inside `$FZF_DEFAULT_OPTS`
    - `fzf --height 40% --no-height` should not fail on Windows
    - Fixed in 64a6ced
- CTRL-R: #1082 
    - Works for me
- CTRL-T and ALT-C give empty lists
    - `find . | fzf` does not reliably work
    - Possibly related: https://github.com/golang/go/issues/22024

**Comment by GaryFurash** [comment]
How can I help test this stuff? I use the Cygwin setup utility to get all my stuff.

**Comment by janlazo** [comment]
`find .` on a cold cache can get stuck running even after `Ctrl-C`. I had to use ConEmu to force-kill `find`. It should be fine after a few runs to warm-up the cache so it's easier to kill but this is a cygwin issue.

Any luck running this on cmd.exe directly?

**Comment by drazde** [comment]
When I lunch `fzf` on `msys2` x64
~~~
$ fzf.exe
character set not supported
~~~

**Comment by janlazo** [comment]
@drazde https://github.com/junegunn/fzf/wiki/Windows#fzf-outputs-character-set-not-supported-when-term-environment-variable-is-set

**Comment by drazde** [comment]
> 
> 
> @drazde https://github.com/junegunn/fzf/wiki/Windows#fzf-outputs-character-set-not-supported-when-term-environment-variable-is-set
@janlazo 
Ok, I'm sorry, I didn't see or I didn't understand that guide

**Comment by caryyu** [comment]
Really nice that I found this similar issue, which I wanna know any progress being made on?

**Comment by junegunn** [comment]
Closing stale issue. The latest version of fzf and its shell integration work out of the box on Git bash (msys2).
