### ISSUE TITLE
fzf --height slow when height > 0

### ISSUE THREAD

**Issue by Alok** [junegunn/fzf#1088]
- Category
    - [x ] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [ x] Mac OS X (10.11.6)
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ x] bash
    - [ x] zsh
    - [ ] fish

Using fzf `0.17.1`, the command `fzf --height 01%` will take almost half a second to display output in `iterm`, `kitty`, and `alacritty` (latest builds of all). in `terminal.app`, it works as expected, though terminal.app has noticeable lag drawing the screen for plain fullscreen `fzf`.

**Comment by junegunn** [comment]
I can't reproduce the problem on iterm2 and terminal.app. I have no experience with kitty or alacritty.

- Do you have the same issue with earlier versions of fzf? I'm pretty sure that 0.17.1 didn't introduce any change that can cause the problem.
- Can you reproduce the problem with a minimal shell configuration?
    - For example, `HOME=/dev/null bash --norc` (avoid reading .bashrc and .inputrc)
- FWIW, terminal emulators of Neovim and Vim 8 are incapable of processing ANSI escape sequence fzf uses to find the cursor position when `--height` is used.

**Comment by Alok** [comment]
It's the `nvim` terminal emulator. I wonder if they'll ever be able to process the escapes correctly.
