### ISSUE TITLE
Feature Request: Please give option to prefer fzf_launcher instead of vim-terminal

### ISSUE THREAD

**Issue by SolaWing** [junegunn/fzf#1091]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [x] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [ ] fish

in recent version, fzf add vim8 terminal support. the vim8 terminal's experience is not perfect and slow. And I prefer to insist on using old fzf_launcher script way. Is there an option here?

**Comment by tuyenpm9** [comment]
I think the same, terminal's still buggy and slow.
