### ISSUE TITLE
Debian/Ubuntu packaging

### ISSUE THREAD

**Issue by orschiro** [junegunn/fzf#1094]
Dear all, 

Thanks for all your work on fzf! This is so brilliant. :-)

Currently, we are discussing the integration of fzf into Ubuntu [1]. That requires fzf to be in the Ubuntu repositories [2]. The easiest way to get it there is through Debian upstream [3]. The package for Debian is ready [4]. However, it needs a sponsor. Can anyone help? Quoting Tom Fitzhenry [2]:

> I'm neither a Debian Developer nor a Debian Maintainer, and thus to
upload fzf to the Debian archive, I need to find a sponsor to upload the
package for me.
The wiki[0] goes into more detail.

Thank you!

[1] https://community.ubuntu.com/t/integration-of-fzf-fuzzy-command-line-finder-or-equivalent-in-future-version-of-ubuntu/779

[2] https://bugs.launchpad.net/ubuntu/+bug/1724565

[3] https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=783307#49

[4] https://github.com/tomfitzhenry/pkg-fzf

**Comment by sfischer13** [comment]
Any news on this issue? @tomfitzhenry, have you found a Debian sponsor?

**Comment by yosefrow** [comment]
@junegunn  https://askubuntu.com/questions/71510/how-do-i-create-a-ppa

I love this tool. adding a ppa would help me to convince my coworkers to adopt it and possibly fasttrack  inclusion into the ubuntu repos, exposing this tool to a huge user-base.

**Comment by cdluminate** [comment]
@orschiro Have you found any sponsor?

**Comment by cdluminate** [comment]
@tomfitzhenry Have you found any sponsor?

**Comment by tomfitzhenry** [comment]
I'm no longer interested in maintaining this sorry.

**Comment by cdluminate** [comment]
fzf entered Debian unstable https://buildd.debian.org/status/package.php?p=fzf

This issue can be closed now.

**Comment by orschiro** [comment]
Dear M. Zhou, 

Thank you so much for packaging it and adding it to unstable!

Yours,

Robert
