### ISSUE TITLE
installing with Pathogen

### ISSUE THREAD

**Issue by mvolkmann** [junegunn/fzf#1095]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [x] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [x] fish

I haven't been able to get this to work. Inside Vim, :Files is not a recognized command.
I'm using Pathogen for my plugins.
I installed fzf as a command-line tool and that works.
I cloned this repo in my ~/.vim/bundle directory and restarted Vim, but it seems that isn't enough.
What else do I need to do?

**Comment by mvolkmann** [comment]
Nevermind. I was reading an article titled "VIM AFTER 15 YEARS" that claims the way to run this is to enter :Files. I see now that I have to enter :FZF.

**Comment by junegunn** [comment]
`:Files` is provided by https://github.com/junegunn/fzf.vim, which is a collection of commands built using the basic functionality provided by this main repo.

**Comment by mvolkmann** [comment]
That is what I installed, but I still don't have the :Files command. Maybe there is another step I need to take to activate the plugin. However, that isn't usually needed with Pathogen. I just need to clone the repo into my ~/.vim/bundle directory which is what I did with fzf. Not sure why it isn't working.

**Comment by junegunn** [comment]
You need both.

**Comment by bochen2014** [comment]
same here. look like `fzf.vim` can **only** be used with `vim-plug` , **not**  `pathogen` . can @junegunn please confirm? 

![image](https://user-images.githubusercontent.com/8207081/39818857-421209a2-53e5-11e8-9c99-991de1785f7d.png)

**Comment by cevhyruz** [comment]
@bochen2014 I think's it is `set rtp+=~/.fzf`

**Comment by VladRose** [comment]
Hey! I've cloned https://github.com/junegunn/fzf into .vim/bundle and it works without any edits in .vimrc
