### ISSUE TITLE
The theme in the README

### ISSUE THREAD

**Issue by logikon** [junegunn/fzf#1096]
What is the theme of the screenshot in the README file? It looks nice.
<img width="1280" alt="fzf-preview" src="https://user-images.githubusercontent.com/31476340/31788151-8130f4b2-b52b-11e7-9a89-8dd26257bf27.png">

**Comment by junegunn** [comment]
It's `fzf --color=light` running on seoul256-light terminal theme (https://github.com/junegunn/seoul256.vim).
