### ISSUE TITLE
Upcoming fish change (removal of $FISH_VERSION) creates errors in fzf-history-widget

### ISSUE THREAD

**Issue by oschrenk** [junegunn/fzf#1099]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [x] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [x] fish

Just a heads up that https://github.com/fish-shell/fish-shell/commit/fb8ae04f80c3a129f789e7b718464d014508315f creates error output with  `fzf-history-widget` as the current implementation relies on that env variable.

You will see something like

```
test returned eval errors:
        invalid integer ''
        invalid integer ''
```

before your results.

I don't think it's urgent and I can work on a fix if you agree.

**Comment by netmute** [comment]
Not strictly related to the issue, but for everyone on fish master who came here by searching for that error:

`set --export FISH_VERSION $version` is a temporary workaround you can do in your `config.fish` until this is resolved in upstream.
