### ISSUE TITLE
Vim as an "execute" action and piped fzf

### ISSUE THREAD

**Issue by smiglo** [junegunn/fzf#1101]
- Category
    - [X] fzf binary
    - [ ] fzf-tmux script
    - [X] Key bindings
    - [ ] Completion
    - [X] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [X] Linux
    - [X] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [X] bash
    - [ ] zsh
    - [ ] fish

Hi,

I need a little help.

I was playing with `--bind "key:execute()" parameters with the aim to invoke `vim` from `fzf`:
```
fzf --bind 'f1:execute(vim {1})'
```
And that works as it should.

However, I met a problem when `fzf` ran in a pipe, e.g.:
```
grep 'A_PATTERN' FILES | fzf -d ':' --bind 'f1:execute(vim +{2} {1})'
# even in this case there is the same problem:
fzf -d ':' --bind 'f1:execute(vim +{2} {1})' < <(grep 'A_PATTERN' FILES)
```
When `vim` is starting, it reports a warning "Input is not from a terminal" because of the above pipe and after quit, `fzf` becomes irresponsible. If the `execute(...)` is changed to `execute(cat {1} | vim -)`, then everything works correctly, but not the file is opened then, so my root intention - a quick "edit & close" does not work.

Do you or any other user reading that have in mind any idea, that would work in this case? Is it even possible to work? :)

Many thanks,
Tomek

**Comment by junegunn** [comment]
Overriding the standard input of the process, this works for me.

```sh
ls | fzf --bind 'f1:execute(vim {1} < /dev/tty)'
```

**Comment by smiglo** [comment]
It works like a charm. Thank you very much.
