### ISSUE TITLE
First keystroke after exiting FZF is lost

### ISSUE THREAD

**Issue by tyok** [junegunn/fzf#1103]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [x] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

Hi. Thanks for this great piece of software.

I've been using it with Vim 8 patch 1200 running on El Capitan. I have the layout set with:

```
let g:fzf_layout = { 'window': 'enew' }
```

Everytime I call `:FZF` then exit (by esc, ctrl-c, or choosing an entry), the fzf buffer is replaced as expected, but the first keystroke after that is always lost. This also happens when I use a very minimal .vimrc comprised of just that one line.

So far I've been able to cirumvent the issue by this patch:
```diff
diff --git i/plugin/fzf.vim w/plugin/fzf.vim
index bad7255..a1aa927 100644
--- i/plugin/fzf.vim
+++ w/plugin/fzf.vim
@@ -649,6 +649,7 @@ function! s:execute_term(dict, command, temps) abort
         enew
       endif
     endif
+    call feedkeys("\<Esc>")
   endfunction
   function! fzf.on_exit(id, code, ...)
     if s:getpos() == self.ppos " {'window': 'enew'}
```

Any idea what might be causing this?

**Comment by junegunn** [comment]
Thanks for the report. I can reproduce the problem. This could just be a bug of new Vim 8 terminal, which is, unsurprisingly, not very stable and optimized at the moment. I'll see if there's a better way to fix this.

**Comment by for-coursera** [comment]
If the problem is with the new `:terminal` command, then may be it's still possible to use `fzf` the old way, like it was used before this new Vim's command was introduced?

**Comment by junegunn** [comment]
Yes, just unset `g:fzf_layout`.

**Comment by junegunn** [comment]
Maybe it's now fixed in https://github.com/vim/vim/commit/a3f7e58bf846b28b347a5d5b96c2d829871bd212?

**Comment by tyok** [comment]
Confirmed. Thanks everyone for the help!

**Comment by totallymonkey** [comment]
Hi,
I am still having this issue even though I am on vim patch 1428.  If I close FZF with Esc I run into this.  If I close with Ctrl+G or Ctrl+C I don't.  I even rebuilt vim from sources to make sure I had the linked fix there and it appears that I do.  I also noticed that when closing FZF with Esc it is very slow to close the window, whereas with Ctrl+G or C it closes immediately.  In GVim I see in the status bar that !cmd.exe is still running until Esc is pressed another time.
