### ISSUE TITLE
Request: Capability to differentiate between CTRL-C and ESC

### ISSUE THREAD

**Issue by mmorearty** [junegunn/fzf#1105]
- Category
    - [x] fzf binary
    - [x] fzf-tmux script
    - [x] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [x] Mac OS X
    - [x] Windows
    - [x] Windows Subsystem for Linux
    - [x] Etc.
- Shell
    - [x] bash
    - [x] zsh
    - [x] fish

I'm using the fzf binary from the command line, invoking it from a script, and I have a somewhat complicated input scenario in which I would like to differentiate between when the user pressed ESC (which would mean "I'm done, I don't want to enter a value here") vs. CTRL-C (which would mean "I've changed my mind, I want to abort this whole script").

One easy way to do that would be to change the exit code — bot CTRL-C and ESC currently return 130. If you don't want to break backward compatibility of the exit codes, I suppose one way to do that is if I could so something like `--bind ctrl-c:SOMETHING_HERE` which would cause it to exit with a different return code.

I see under `man fzf` that there is already a `cancel` action which has no key bindings. (CTRL-C and ESC are both bound, by default, to a different action called `abort`.) What is `cancel`? I tried binding CTRL-C to that, but I saw no change in behavior. Is there a way to get that to do what I want?

**Comment by mmorearty** [comment]
Ah, I see that `cancel` is not what I am looking for — I found its explanation in `CHANGELOG.md`:

> - Added `cancel` action which clears the input or closes the finder when the
>  input is already empty
>    - e.g. `export FZF_DEFAULT_OPTS="--bind esc:cancel"`

Still hoping something could be added to support this use case. Thanks!

**Comment by mmorearty** [comment]
I did find another solution which I'm quite satisfied with: I am binding `ESC` to `unix-line-discard`, and leaving `CTRL-C` as `abort`.

**Comment by junegunn** [comment]
Hi, thanks for the suggestion, but since you found an alternative solution that works for you, and it's already possible to see which key was pressed using `--expect` option, though it may not be as convenient as a dedicated option for this particular use case, I'd rather not add a new option.

For your information, we use `--expect` option extensively in Vim plugin to distinguish which key was pressed and to act accordingly, i.e. `CTRL-T` opens the file in a new tab, `CTRL-V` vertical split, etc.

Close #1106

**Comment by mmorearty** [comment]
Sounds good to me, thanks!
