### ISSUE TITLE
Windows Defender Antivirus detect Trojan:Win32/Fuerboos.A!cl in fzf-0.17.1-windows_386.zip

### ISSUE THREAD

**Issue by Swich1987** [junegunn/fzf#1110]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [ ] Mac OS X
    - [x] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [ ] fish

Windows Defender Antivirus detect Trojan:Win32/Fuerboos.A!cl in fzf-0.17.1-windows_386.zip and automatically delete it.
It shows me this link: [https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?Name=Trojan:Win32/Fuerboos.A!cl](url) 
0.17.0 show same error.
fzf-0.17.1-windows_amd64.zip looks fine.

**Comment by junegunn** [comment]
Hmm, I'm pretty sure that it's a false positive. I built the binary on macOS using cross compilation feature of Golang and uploaded to GitHub.

**Comment by junegunn** [comment]
Related: https://github.com/crazy-max/WindowsSpyBlocker/wiki/miscFAQ#antivirus-complains-about-windowsspyblocker

**Comment by vhanla** [comment]
Same here on Avira it detected as TR/Crypt.XPACK.Gen, notice though that I recompiled it x86/x64 binaries and they are not detected as false positives, Something suspicious is going on here.

**Comment by junegunn** [comment]
See https://github.com/golang/go/commit/1be58dcda8f31eb0ed77fd5e33fb3f5fe47f33ab
