### ISSUE TITLE
buffer goes to insert mode after opening file at startup via fzf

### ISSUE THREAD

**Issue by damnskippy** [junegunn/fzf#1116]
- Category
    - [x] Vim
- OS
    - [x] Linux
- Shell
    - [x] bash

Using latest fzf & vim patches.
I have the following in my vimrc file:
```
autocmd StdinReadPre * let g:readingFromStdin=1
autocmd VimEnter * nested
    \   if argc() == 0 && get(g:, 'readingFromStdin', 0) != 1
    \|          call fzf#run({'source': 'cat ~/.vim_bookmark_files', 'sink': 'e', 'options' : '--reverse --no-sort', 'down': '50%'})
    \| endif
```

.vim_bookmark_files is just a list of file names.
Basically at vim startup if no file was specified (and not reading from stdin), present a list of bookmarks via fzf, and pick one to edit (or escape to quit).
This works perfectly fine and as expected in terminal vim.
However in gui vim, after fzf opens the selected file ("edit:"), the buffer somehow goes into INSERT mode after a couple of key strokes.  One hint may be that when looking at the window title bar, it seems a sh! script is still running after the buffer is opened.  Hitting escape a couple of times at this point gets the script to end it seems and the INSERT mode is not entered.

I'm not sure if this is related to my environment or not.  Unfortunately, I have not been able to isolate or narrow this down unfortunately.

Again, this only occurs with gui vim (using recent native vim terminal functionality) and when using fzf to open a file in the above manner.  Works fine with terminal vim.

Does this look like something obvious that I'm missing, and can someone else quickly try reproducing this in their setup?

**Comment by damnskippy** [comment]
Still wondering if I'm the only one running into this, and if this is a side effect of using terminal in gui vim?
Thank you.

**Comment by damnskippy** [comment]
I tracked down the behavior to the `startinsert `called in `s:execute_term` at this line in the code.
 https://github.com/junegunn/fzf/blob/a6d2ab33609ad20ce107e66d9648d908800fa3ad/plugin/fzf.vim#L715

Not clear about the intent of starting in insert at this point.

**Comment by damnskippy** [comment]
Now that I know what caused the insert, I was able to fix this by changing my autocmd above to do the following instead - basically added stopinsert after calling `fzf#run`:
```
autocmd StdinReadPre * let g:readingFromStdin=1
autocmd VimEnter * nested
    \   if argc() == 0 && get(g:, 'readingFromStdin', 0) != 1
    \|          call fzf#run({'source': 'cat ~/.vim_bookmark_files', 'sink': 'e', 'options' : '--reverse --no-sort', 'down': '50%'})
    \|          stopinsert
    \| endif

```

**Comment by tipu** [comment]
I ran into this problem myself. So far I just commented out the stopinsert in fzf.vim without any regressions yet.
