### ISSUE TITLE
[Suggest] Do not upgrade go to 1.9

### ISSUE THREAD

**Issue by tenfyzhong** [junegunn/fzf#1117]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

I use `brew upgrade fzf` to upgrade the fzf, but it upgrade my go also. It broke my go develop environment.

**Comment by junegunn** [comment]
That's how Homebrew works. You might want to discuss the issue with the developers of Homebrew instead. But you probably should not be using go installed with Homebrew if your project depends on a certain version of go.
