### ISSUE TITLE
`less` functionality is reduced in preview window

### ISSUE THREAD

**Issue by githorse** [junegunn/fzf#1118]
- Category
    - [X] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [X] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [X] bash
    - [X] zsh
    - [ ] fish

`less` doesn't seem to play well with the preview window. For instance,

    ag . | fzf -e -d':' --nth=3.. --preview 'less --pattern {q} {1}'
    ag . | fzf -e -d':' --nth=3.. --preview 'less +{2} {q} {1}'

In all cases `less` just `cat`s the file; it opens at line 1 with nothing highlighted. Note that the same command passed to `--bind` works correctly:

    ag . | fzf -e -d':' --nth=3.. --bind 'space:execute(less --pattern {q} {1})' 

Other `preview` commands also seem fine:

    ag . | fzf -e -d':' --nth=3.. --preview 'tail -n10 {1}'

I assume this is a complicated terminal thing I don't understand. I can play with other unix utils (maybe `grep --color` to do what I want here, but is there a way to make this work with `less`?

**Comment by junegunn** [comment]
`--preview` executes the command in non-interactive mode and `less` refuses to print ANSI escape codes when its standard output is not a tty device like many other unix tools do.

```sh
# Highlights enabled
less --pattern foo somefile

# Highlights disabled
less --pattern foo somefile | cat

# This usually makes sense because you don't want ANSI escape codes in a file
less --pattern foo somefile > output
```

`execute` on the other hand runs in interactive mode so you can see the highlighted pattern.

Some tools provide options for forcing ANSI colors, but I don't know if less have the option.

```sh
# Colors
git log --oneline

# No colors
git log --oneline | cat

# Force ANSI colors
git log --oneline --color=always | cat
```

And I don't think it's possible to support +LINE_NO option in non-interactive mode.

```sh
# What can less do?
less +10 ~/.bashrc > /tmp/foo
```

#1057 is related to this case, but it's not quite simple so I don't think I want to add the option at the moment.
