### ISSUE TITLE
Duplicate results on Ubuntu when there is a file system loop

### ISSUE THREAD

**Issue by henrik** [junegunn/fzf#1120]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [x] bash
    - [x] zsh
    - [ ] fish

I get duplicate results on Ubuntu 12.04.5 LTS in a virtual machine (Virtual Box on a macOS host) when there is a file system loop (a recursive symlink).

The reason is that the default command for listing files (https://github.com/junegunn/fzf/blob/a6d2ab33609ad20ce107e66d9648d908800fa3ad/src/constants.go#L58) basically does `(find -L … || find -L …)`. So if the first find fails, it runs the second.

But when the first `find` fails due to a file system loop, it will fail *and* return results. Then the second `find` runs and we get duplicates.

I have a repro that shows the issue on Ubuntu (but it does not give duplicates on macOS):

```
$ mkdir /tmp/foo
$ touch /tmp/foo/bar.xyz
$ ln -s /tmp/foo /tmp/foo/foo2
$ find -L /tmp -path '*.xyz'
/tmp/foo/bar.xyz
find: File system loop detected; `/tmp/foo/foo2' is part of the same file system loop as `/tmp/foo'.
$ (find -L /tmp -path '*.xyz' || find -L /tmp -path '*.xyz')
/tmp/foo/bar.xyz
find: File system loop detected; `/tmp/foo/foo2' is part of the same file system loop as `/tmp/foo'.
/tmp/foo/bar.xyz
find: File system loop detected; `/tmp/foo/foo2' is part of the same file system loop as `/tmp/foo'.
$ (find -L /tmp -path '*.xyz' || find -L /tmp -path '*.xyz') 2>/dev/null
/tmp/foo/bar.xyz
/tmp/foo/bar.xyz
```

Or I could go into `/tmp`, run `fzf` and then type "xyz" to see the duplicates.

**Comment by junegunn** [comment]
That's unfortunate. We changed the default command in #1061 for systems that do not support some options we use in the first find command. Didn't see this coming.

I'll see if there's a simple way to address this. For the time being, consider using a custom `$FZF_DEFAULT_COMMAND` using fd or rg.

https://github.com/junegunn/fzf#respecting-gitignore

**Comment by henrik** [comment]
Thank you, @junegunn! I'll give those a try for now.

**Comment by junegunn** [comment]
I'm wondering if it's possible to distinguish the type of error by looking at the exit status (`$?`) of the find command? Can you check the exit status of find command when `find: File system loop detected` happens?

**Comment by henrik** [comment]
Afraid not :/

```
$ find -L /tmp -path '*.xyz'; echo $?
/tmp/foo/bar.xyz
find: File system loop detected; `/tmp/foo/foo2' is part of the same file system loop as `/tmp/foo'.
1
$ find -L /tmp/no_such_dir -path '*.xyz'; echo $?
find: `/tmp/no_such_dir': No such file or directory
1
```

**Comment by leighmcculloch** [comment]
I'm experiencing the same thing on Ubuntu 16.04.
