### ISSUE TITLE
How to match against hidden fields

### ISSUE THREAD

**Issue by mudox** [junegunn/fzf#1121]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [ ] fish

lines.txt

```
Asia 	            \t         China Japan Korea[0m

  China

  Japan

  Korea

Europea 	            \t         England France German

  England

  France

  German

North America 	    \t        Canada USA

  Canada

  USA

South America 	    \t       Brazil Columbia Mexico

  Brazil

  Columbia

```

`cat lines.txt | fzf -d '\t'  --tiebreak=index  --nth=1,2  --with-nth=1`

I wanted to type **USA** to match both the line **North Ameria** and **USA**

It seems that the `—nth`list is limited by the list specified by `—with-nth`

Is there any way to match against the hidden (2nd) column?

**Comment by junegunn** [comment]
No, it's not supported. I decided to limit the search scope to only visible fields to avoid user confusion.
