### ISSUE TITLE
How to return fzf result with to a command

### ISSUE THREAD

**Issue by akinh** [junegunn/fzf#1123]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

This might be more related to bash than fzf, but couldn't make sure and couldn't figure it out. 

I have the following command in my inputrc

`"\C-]": "$(tmux capture-pane -Jp  | tr \" \" \"\\n\" | sort | uniq | fzf)"
`

which I can use like

`some-command c-]`

this works fine. I mean it runs some-command with selected fzf result. But, what I want fzf to do is just returning my selection to the command line, making it like 

`some-command result-returned-from-fzf  --option
`

and keep typing. How can I do this ?

**Comment by akinh** [comment]
Turns out I needed to brush up my bash skills. Followed the examples in the [wiki](https://github.com/junegunn/fzf/wiki/examples) and after a bunch of iterations, viola!

**Comment by kohane27** [comment]
I figured it out.

As noted in [Command history](https://github.com/junegunn/fzf/wiki/examples#command-history):

> Replacing `eval` with `print -z` will push the arguments onto the editing buffer stack, allowing you to edit the command before running it.

For my case, I need to read a file line by line and then get the selected output to the terminal:

```
print -z $(cat ~/Downloads/log.txt | fzf)
```

Hopefully this is helpful to others without resorting to the wiki. Cheers!
