### ISSUE TITLE
Forward selection to next command only if not aborted and without emitting extra output?

### ISSUE THREAD

**Issue by danijar** [junegunn/fzf#1124]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [x] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

I'm trying to write a fzf script for installing Ubuntu packages. I'd like to fuzzy search the list of available packages, install on <kbd>return</kbd> and abort on <kbd>Ctrl+C</kbd>. My first attempt was to implement that using fzf as a pipe:

```shell
alias install="
  apt-cache search '.*' | \
  grep -Eo '^[^ ]+' | \
  fzf --bind='ctrl-c:abort' --preview 'apt-cache show {}' | \
  xargs sudo apt-get install"
```

However, the pipe doesn't stop on abort and so on <kbd>Ctrl+C</kbd> apt is still executed. To circumvent this problem, I tried to bind apt to the return key instead of using a pipe:

```shell
alias install="
  apt-cache search '.*' | grep -Eo '^[^ ]+' | \
  fzf --bind 'return:execute(sudo apt-get install {})+abort' \
  --preview 'apt-cache show {}'"
```

Abort works with this, but hitting return emits some output so that the following apt prompt (`Do you want to continue? [Y/n]`) automatically gets answered with no and so the installation aborts. How can I forward the selection to another command only on <kbd>return</kbd> and without emitting extra output?

**Comment by junegunn** [comment]
> However, the pipe doesn't stop on abort and so on Ctrl+C apt is still executed

On bash, pipefail option can be used to terminate the whole pipe. I believe zsh has a similar option. Using `return:execute` to workaround issue doesn't seem like a good idea. You might want to write a proper shell function where you check the exit status of fzf before passing the output of it to the next command.

**Comment by albohlabs** [comment]
For all those who come here via a search engine in the future ... xargs has a `--no-run-if-empty` option. 

>  If the standard input does not contain any nonblanks, do
              not run the command.  Normally, the command is run once
              even if there is no input.  This option is a GNU
              extension.

**Comment by jeffwindsor** [comment]
thanks for that @albohlabs
