### ISSUE TITLE
fzf-tmux not working and fzf configured wrong?

### ISSUE THREAD

**Issue by wldcordeiro** [junegunn/fzf#1125]
- Category
    - [ ] fzf binary
    - [x] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

I tried using the example from the readme and it doesn't seem to do anything. 🙁 I thought the idea was that I could use it to pipe to `git checkout` but have had no success.

Additionally I think I may have issues with fzf in general as trying the `**` expansion in my home directory spits out this...

```
Documents/projects/aqueduct on  flow-update [$?] is 📦  v0.1.4-0 via ⬢ v9.0.0 took 3s
•100% [I] ➜ ls /Users/wellingtoncordeiro/Applications /Users/wellingtoncordeiro/Creative\ Cloud\ Files /Users/wellingtoncordeiro/Desktop /Users/wellingtoncordeiro/Documents /Users/wellingtoncordeiro/Downloads /Users/wellingtoncordeiro/Dropbox /Users/wellingtoncordeiro/Library /Users/wellingtoncordeiro/Movies /Users/wellingtoncordeiro/Music /Users/wellingtoncordeiro/Pictures /Users/wellingtoncordeiro/Public /Users/wellingtoncordeiro/VirtualBox\ VMs /Users/wellingtoncordeiro/antigen /Users/wellingtoncordeiro/dev /Users/wellingtoncordeiro/exercism
```

**Comment by junegunn** [comment]
You're probably having some configuration issues, and I can't really help you with that.
