### ISSUE TITLE
Use this for all tab completion without typing **

### ISSUE THREAD

**Issue by theonlygusti** [junegunn/fzf#1132]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [x] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

How can I tab-complete with this by default? I don't want to have to type `**` every time.

Also, is there a way to just cycle options when pressing tab instead of "selecting" them?

**Comment by junegunn** [comment]
Although I'm not sure if it's a good idea, that can be done by using empty FZF_COMPLETION_TRIGGER. More information can be found here: https://github.com/junegunn/fzf/wiki/Configuring-fuzzy-completion#zsh

> cycle options when pressing tab

```sh
export FZF_DEFAULT_OPTS='--bind tab:down --cycle'
```

**Comment by lanespade** [comment]
Hey @junegunn!

I was playing around with this dedicated completion key / empty FZF_COMPLETION_TRIGGER and found that this results in `~/.fdignore` (and `~/.config/fd/ignore`) no longer being respected. In my case, `node_modules/` was the big difference. Running `fd` directly, i.e. `fd --type f . ~` would exclude `node_modules/` folders, but typing `vi <TAB>` would still show files in `node_modules/` (or anything else that I expected to be ignored).

Is this expected for the "context-aware fuzzy completion" or a bug?

P.S. I'm a big fan of fzf, thanks for making and maintaining it!

**Comment by ahmadie** [comment]
** autocompletion also use following function so you can customise them as you wish, also written in home page:

``
_fzf_compgen_path() {
  fd --hidden --exclude .git --exclude .local/share/nvim/undo . "$1"
}

#Use fd to generate the list for directory completion
_fzf_compgen_dir() {
  fd --hidden --type d --exclude .git --exclude .local/share/nvim/undo . "$1"
}

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
``
