### ISSUE TITLE
Still seeing .gitignore'd things in tab completion

### ISSUE THREAD

**Issue by theonlygusti** [junegunn/fzf#1138]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [x] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

The last lines of my zshrc are

```sh
export FZF_COMPLETION_TRIGGER=''
export FZF_DEFAULT_COMMAND='ag -g ""'

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
```

When I press tab now to complete file paths I am still getting results from `node_modules` and other ignored things in my `.gitignore`.

**Comment by junegunn** [comment]
Fuzzy completion does not use FZF_DEFAULT_COMMAND. You should be able to find some related discussions in the issue tracker.

See https://github.com/junegunn/fzf#settings
