### ISSUE TITLE
Can't make preview window work

### ISSUE THREAD

**Issue by tuyenpm9** [junegunn/fzf#1140]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [ ] fish

I can see that it works here #1057. I read document https://github.com/junegunn/fzf.vim but seems it doesn't work for me, or I miss disabled some options that require for preview to work.
```
command! -bang -nargs=* Rg
  \ call fzf#vim#grep(
  \   'rg --column --line-number --no-heading --color=always '.shellescape(<q-args>), 1,
  \   <bang>0 ? fzf#vim#with_preview('up:60%')
  \           : fzf#vim#with_preview('right:50%:hidden', '?'),
  \   <bang>0)
```

I tried with more minmal one but still doesn't work - empty result, picture [here](https://imgur.com/a/QPMvX):
```
command! -bang -nargs=* Find
  \ call fzf#vim#grep(
  \   'rg --column --line-number --no-heading --color=always'.shellescape(<q-args>), 1,
  \   <bang>0)
```

Later when writing this issue, I've found fzf.vim has conflict with vim-ripgrep plugin that also set `Rg` as default command, I disable vim-ripgrep and try with the first one, it works but no preview window of code, picture [here](https://imgur.com/a/MU2ub).  
So how to trigger to open preview window or Does it have some specific options that need to be enabled to run?, I've change my vimrc a lot.

**Comment by junegunn** [comment]
Please re-read the README page of fzf.vim.

**Comment by tuyenpm9** [comment]
Thanks, after re-read, I found `?` make preview windows but it just shows buffer's path, nothing else.
picture [here](https://imgur.com/a/aNfsF).

**Comment by junegunn** [comment]
That looks like an error message from bash. You might want to enable "wrap" option of preview window to see the full message. Though I don't use Windows, I'm not sure if I can help. Let me know if you figure out how to fix it.

**Comment by tuyenpm9** [comment]
I've tried with minimal vimrc as below:  
```
command! -bang -nargs=* Rg
  \ call fzf#vim#grep(
  \   'rg --column --line-number --no-heading --color=always '.shellescape(<q-args>), 1,
  \   <bang>0 ? fzf#vim#with_preview('up:60%')
  \           : fzf#vim#with_preview('right:50%:hidden', '?'),
  \   <bang>0)

```
Picture [here](https://imgur.com/a/uZvnZ). It say `fzf.vim/bin/preview.sh: No such file or directory`. Any suggestions?
