### ISSUE TITLE
How to remove bar at the bottom when using Neovim?

### ISSUE THREAD

**Issue by lokesh-krishna** [junegunn/fzf#1143]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [x] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

Using Neovim, running FZF always adds a line to the bottom which I would rather not have. 

![screenshot from 2017-11-14 19-24-51](https://user-images.githubusercontent.com/20235646/32783538-2a4cc378-c972-11e7-9453-8e36de5ced9b.png)

I do not have this problem with Vim though.

![screenshot from 2017-11-14 19-25-11](https://user-images.githubusercontent.com/20235646/32783570-40c25d5c-c972-11e7-98ef-c6a3469ae134.png)

How do I get FZF to look the same in Neovim?

**Comment by tuyenpm9** [comment]
Same issue as #1142?

**Comment by lokesh-krishna** [comment]
Hmmm...

I don't think so. I am not even sure I understand what that issue is about. Also, the problem here is that I don't have a problem while using Vim. Only while using Neovim though I am using the same `.vimrc`.

**Comment by junegunn** [comment]
Short answer: you cant. Neovim cannot start external processes like Vim does so fzf can only start inside its built-in terminal emulator. #137

**Comment by junegunn** [comment]
The same applies to GVim.

**Comment by lokesh-krishna** [comment]
Ah, anything I can do to at least make it (that bar) look a bit more presentable?

**Comment by junegunn** [comment]
Setting `laststatus` to 0 while fzf is running can help.

```vim
if has('nvim') || has('gui_running')
  autocmd! FileType fzf
  autocmd  FileType fzf set laststatus=0 | autocmd WinLeave <buffer> set laststatus=2
endif
```

**Comment by tuyenpm9** [comment]
Won't work on gvim/windows 10.

**Comment by junegunn** [comment]
You have to bear in mind that Windows/GVim support is experimental and I would generally recommend using terminal Vim on WSL instead.

**Comment by lokesh-krishna** [comment]
Thank you so much! That worked perfectly! Any chance of adding this to the wiki?

**Comment by junegunn** [comment]
Will do.

**Comment by andreypopp** [comment]
Note that in case `fzf` is configured with `enew` you need to use `BufLeave` rather than `WinLeave`.

**Comment by junegunn** [comment]
Good point.

**Comment by junegunn** [comment]
Added https://github.com/junegunn/fzf/blob/master/README-VIM.md#hide-statusline to the README-VIM page.

```vim
autocmd! FileType fzf
autocmd  FileType fzf set laststatus=0 noshowmode noruler
  \| autocmd BufLeave <buffer> set laststatus=2 showmode ruler
```
