### ISSUE TITLE
Changing FZF prompt in Neovim

### ISSUE THREAD

**Issue by lokesh-krishna** [junegunn/fzf#1144]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [x] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

I added

`call fzf#run({'options': '--reverse --prompt "❯ "'})` 

in order to change the fzf prompt to `❯`.

However, launching Neovim now results in the following error:  

`E117: Unknown function: fzf#run`

I already have that set as the prompt in my `.zshrc` using 

`export FZF_DEFAULT_OPTS='--prompt=❯\ '`

and this works in my terminal as I get the desired prompt.

What am I doing wrong?

**Comment by junegunn** [comment]
`call fzf#run({'options': '--reverse --prompt "❯ "'})` is a command to start a fzf session with the options, it's not a way of configuring the default options. `FZF_DEFAULT_OPTS` should apply inside Vim/Neovim.
