### ISSUE TITLE
How to append history command instead of replace?

### ISSUE THREAD

**Issue by eyalev** [junegunn/fzf#1145]
- Category
    - [ ] fzf binary
    - [x] fzf-tmux script
    - [x] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

I would like to append a command from history instead of replacing the whole line.

For example:

```
$ first-command && [launch fzf, choose second command to be appended] second-command && [launch fzf, same..] third-command
```

How can I do this?

Maybe with `--expect`? or `FZF_CTRL_T_COMMAND`?

**Comment by junegunn** [comment]
It's not supported by the key bindings this repository provides and I have no idea how to implement it. Feel free to share your solution when you find one, thanks.

**Comment by eyalev** [comment]
This seems to work:

```
# In .zshrc

fzf-history-append-widget() {
  selected=( $(fc -il -30000 | eval "$(__fzfcmd) +e --tac +m -n2..,.. --tiebreak=index --preview='echo {}' --preview-window=up:30%:wrap --toggle-sort=ctrl-r $FZF_CTRL_R_OPTS") )
  num=$selected[1]
  command=$(fc -nl "${num}" | head -n 1)
  LBUFFER="${LBUFFER}${command} "
  local ret=$?
  zle redisplay
  typeset -f zle-line-init >/dev/null && zle zle-line-init
  return $ret
}

zle     -N   fzf-history-append-widget
bindkey '^O' fzf-history-append-widget

```

**Comment by jlescher** [comment]
fzf-history-widget() {
  local selected num lbuffer
  lbuffer=${LBUFFER}
  setopt localoptions noglobsubst noposixbuiltins pipefail no_aliases 2> /dev/null
  selected=( $(fc -rl 1 | perl -ne 'print if !$seen{(/^\s*[0-9]+\**\s+(.*)/, $1)}++' |
    FZF_DEFAULT_OPTS="--height ${FZF_TMUX_HEIGHT:-40%} $FZF_DEFAULT_OPTS -n2..,.. --tiebreak=index --bind=ctrl-r:toggle-sort,ctrl-z:ignore $FZF_CTRL_R_OPTS --query=${(qqq)} +m" $(__fzfcmd)) )
  local ret=$?
  if [ -n "$selected" ]; then
    num=$selected[1]
    if [ -n "$num" ]; then
      zle vi-fetch-history -n $num
    fi
  fi
  LBUFFER="${lbuffer}${LBUFFER}"
  zle reset-prompt
  return $ret
}

Did the trick for me !
