### ISSUE TITLE
Couldn't get fzf to work without running sudo 

### ISSUE THREAD

**Issue by raffylopez** [junegunn/fzf#1146]
I'm running the latest version of fzf, and it only yields results if I run it on sudo. Without sudo, I'm getting an empty resultset, just an `0/0 [ERROR]`.

While fzf runs fine through keybindings without elevation, I'm unable to use fzf in Nvim, except when I put Nvim on sudo as well. 

`chown`ing the ~/.fzf folder doesn't help. Any idea to help fix this?

- Category
    - [x] fzf binary
    - [x] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [x] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [x] bash
    - [x] zsh
    - [ ] fish

**Comment by junegunn** [comment]
You should check if your FZF_DEFAULT_COMMAND is valid.

**Comment by raffylopez** [comment]
Thank you, well that was it, apparently. My FZF_DEFAULT_COMMAND was invalid (set to `ag`, but `ag` wasn't on the machine).
