### ISSUE TITLE
file@btag search similar to Sublime Text?

### ISSUE THREAD

**Issue by JesseLeite** [junegunn/fzf#1150]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [x] Vim
    - [x] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [x] Mac OS X
    - [x] Windows
    - [x] Windows Subsystem for Linux
    - [x] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [ ] fish

Sublime Text has two handy fuzzy finders:

- CMD-P (project scoped file search)
- CMD-R (buffer tag search)

However you can also use the `@` operator within a `CMD-P` file search to switch to a tag search.  ie)  Hitting `CMD-P` and searching `Site@scopeBy` will fuzzy search for tags of `scopeBy` within the selected `Site` file, without having to press enter and begin a separate tag search...

<img width="925" alt="screen shot 2017-11-19 at 10 44 16 pm" src="https://user-images.githubusercontent.com/5187394/33001381-8786f740-cd7b-11e7-8345-89d8352e340c.png">

Curious if this could be a possibility with with fzf.vim?  😬

**Comment by junegunn** [comment]
No, fzf is a general-purpose text filter and it's not possible to dynamically change the context. The closest one can do is to set up some key bindings (`--bind` or `--expect`) for closing the current fzf session and starting a new session with different input.

**Comment by JesseLeite** [comment]
@junegunn Thank you for reply!

>The closest one can do is to set up some key bindings (--bind or --expect) for closing the current fzf session and starting a new session with different input.

Do you mean to setup key bindings for fzf.vim in Vim?  Or does this need to be done at a global fzf CLI level?

**Comment by junegunn** [comment]
I mean one can try to implement a similar flow from scratch using the options fzf provides. It's not something you can easily achieve just by setting a few global options.
