### ISSUE TITLE
min-width for filter selection / adaptive preview (hidden depending on available terminal space)

### ISSUE THREAD

**Issue by mfussenegger** [junegunn/fzf#1153]
- Category
    - [x] fzf binary
- OS
    - Probably all
- Shell
    - Probably all

First of all - thanks for fzf, it's really great.

I've a couple of aliases where I'd like to have a `--preview` if there is
enough terminal space, but have it hidden if there isn't. The use case is to
have the same alias that works kind of adaptive, depending on how big the
terminal is.

As far as I'm aware of this is currently not possible. Only the preview-window
size can be set, but not the filter-selection window size.

I'm thinking of something like a `selection-min-width` option. If set, the
preview window could just take the remaining space (or be hidden, if there
isn't any available)

**Comment by junegunn** [comment]
Thanks for the suggestion. This can be handled outside of fzf, i.e. shell functions applying different sets of options depending on `$COLUMNS` (or `&columns` in Vim scripts). Having to write external script may seem inconvenient, but I believe it's always going to be more flexible than any option we may add to fzf trying to support the use case.
