### ISSUE TITLE
fzf-tmux -u call from vim sets both panes to the same height

### ISSUE THREAD

**Issue by promisedlandt** [junegunn/fzf#1157]
- Category
    - [ ] fzf binary
    - [x] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

Hello,

I found this problem using fzf.vim, but I was able to reduce it to fzf-tmux I think.
When I open fzf in a tmux pane at the top of the screen, the height of the bottom pane (containing vim) gets sets to the same height.
As you can see in this screenshot, the top pane has a height of 7 (correct), but the bottom pane has a height of 7 too, instead of the expected 30.
![fzf-tmux](https://user-images.githubusercontent.com/557201/33154709-9ebe1f08-cfea-11e7-8e6f-8ee75fac29ff.png)

The command I used for this was `call system("LINES=37 COLUMNS=131 fzf-tmux -u7")`, also visible in the screenshot.
The problem only occurs with `-u`, `lrd` all work as expected.

I was trying to debug fzf-tmux myself, but all debug output looked correct to me. And when I execute the command in bash, everything works as expected:
![fzf-tmux-bash](https://user-images.githubusercontent.com/557201/33154829-83e89c34-cfeb-11e7-8997-6fcc9f70f063.png)

For testing, I removed all vim plugins and deleted my custom vimrc.
This problem occurs with vim 7.4 and 8 (I have not tested neovim yet), on Linux (Debian 8 / 9, Mac OS X), with fzf-tmux at sha 37d4015d5611576e5d93af524b6420956d8c7c9a (from 2017-11-21).
Other program versions used:
bash 4.4.12
tmux 2.3

Do you have any idea what could cause this? I'm stumped.

**Comment by junegunn** [comment]
I can reproduce the problem, but I don't know how to fix it.

If you have the latest version of Vim, fzf can use a terminal buffer, and fzf-tmux is not needed.

```vim
" fzf opens in a terminal buffer inside Vim
call fzf#run(fzf#wrap({'up': 10}))
```

**Comment by promisedlandt** [comment]
Thank you. It's good to know it's not some weird setup thing on my machines, and also not a simple fix I overlooked.
