### ISSUE TITLE
window preview crash

### ISSUE THREAD

**Issue by excalibur1234** [junegunn/fzf#1159]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

i try to dispaly the content of root files using fzf's useful window preview functionality. here is a simplified code example:
`find /etc/ | fzf --preview 'sudo cat{}'  `
( only this code crashes fzf. `find /etc/ | fzf --preview 'cat{}'  ` does not work in this situation, but also does not crash fzf)

this code works find as long as the user already has root privileges. but if not (and a password prompted) multiple thing happen:
- i am unable to enter my password. entering text does not work and messes up fzf.
- the interface of fzf is messed up. it is impossible to fix that.
- quitting fzf with CTRL+C only works on the second try (when a text has been entered after the password prompt)
- my terminal is messed up even after fzf has been killed.

something should be done to prevent this nasty behavior of fzf triggered by a password prompt. ideally, a warning text (or no text at all) should be shown in window preview.

**Comment by junegunn** [comment]
Thanks for the suggestion, but I don't think there's a way fzf can prevent such cases, as it allows free-form command as the preview command and fzf cannot know if a command will demand terminal input that interferes with fzf. *With great **flexibility**, comes great responsibility*. The user has to make sure that the command is non-interactive.

> my terminal is messed up even after fzf has been killed.

Type in "reset", and it will be fixed.
