### ISSUE TITLE
Allow Shift-Enter and Ctrl-Enter in --expect

### ISSUE THREAD

**Issue by blackheaven** [junegunn/fzf#1160]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [x] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

I'd like to be able to map Shift-Enter and Ctrl-Enter in --expect.

I've browsed a bit in the source code and it seems that there is a layer on top of tcell preventing us to have a more composable --expect parameter. Wouldn't it be a good opportunity to remove it and let [keyMatch](https://github.com/junegunn/fzf/blob/master/src/terminal.go#L1100) compare the key number and the mod?

**Comment by junegunn** [comment]
Most terminals don't recognize shift-enter, but I believe we can support ctrl-enter like we support ctrl-space. I'll look into it when I get some time. And for your information, tcell implementation is only used on Windows. I don't want to change the implementation as the coverage is already quite good, especially if we filter out key chords that are not natively supported by terminals, such as shift-enter.

**Comment by junegunn** [comment]
Hmm, unfortunately, I realized that my terminal does not distinguish CTRL-Enter from Enter, and I don't think it's a good idea to support key chords that are not supported on most terminals, as it can unnecessarily confuse users.

See https://stackoverflow.com/questions/598113/can-terminals-detect-shift-enter-or-control-enter
