### ISSUE TITLE
Don't exit if there is no match

### ISSUE THREAD

**Issue by maln0ir** [junegunn/fzf#1162]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [x] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [ ] fish

Currently, fzf exits with code 1 if there is no match. Add an option to disable this behaviour and allows fzf to exit only if there is at least one match.
This is useful when you use fzf to search through large list of entries from slow source and don't want to repeat searching after hitting Enter accidentally. Or if you use fzf as an application launcher and want to make sure you run something.

**Comment by junegunn** [comment]
Starting from 0.17.2, you can do

```sh
fzf --bind enter:accept-non-empty
```

**Comment by svermeulen** [comment]
This is really useful but I wish it still did not exit even when it is done reading and the length of choices is zero.  In my case there are other keys I'm setting that allow the user to exit

**Comment by luckman212** [comment]
is `--no-exit-0` also useful here?
