### ISSUE TITLE
Feature Request: one arguments off history search

### ISSUE THREAD

**Issue by quicknir** [junegunn/fzf#1163]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [x] Key bindings
    - [x] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.

- Shell
    - [x] bash
    - [x] zsh
    - [x] fish

When entering the history search widget it would be really cool if you could use keys (say C-h and C-l for left right) that would let you pick out individual arguments from the command line. This is useful often, e.g. if you have a long command that involved a directory somewhere and you want to cd to that directory. It feels much more natural to do cd <C-r> and pick out the directory you want, then to take the whole command start chopping it up.

The way I would envision it working: if you don't hit C-h/C-l then it works the same as now. If you hit e.g. C-l, Then the highlight command stops being fully highlighted, and instead only the left most argument is highlighted. You can hit C-l to move right and C-h to move left. When you hit enter, it grabs only the current argument. If you move off the the end, then it goes back to being fully highlighted.

What do you think? I think it would be useful and would have zero impact on the current usage of history search, while adding a nice new piece of functionality without a new shortcut.

**Comment by quicknir** [comment]
An alternative: if this would be onerous (looking over the code it seems like this might require modifying the binary), would be to bind C-<n> to taking the nth argument. C-1 takes the first, C-2 the second, etc.

**Comment by junegunn** [comment]
I think it's a nice idea, I believe you can implement the scheme using `--expect` option of fzf. alt-[0-9] keys can be used, see `man fzf` for more info. However, I'm not interested in extending the functionality of the key bindings, please see my comment below. Thanks.

https://github.com/junegunn/fzf/pull/1161#issuecomment-347002445
