### ISSUE TITLE
Error running '/usr/local/Cellar/fzf/0.17.1/bin/fzf'

### ISSUE THREAD

**Issue by almccann** [junegunn/fzf#1164]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [X] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [X] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [X] bash
    - [ ] zsh
    - [ ] fish

I get the following problem using `:FZF <search>` on macOS:
`Error running '/usr/local/Cellar/fzf/0.17.1/bin/fzf'  '--multi' '--prompt' '~/dotfiles/' 'README.md' --expect=ctrl-v,ctrl-x,ctrl-t --height=19 > /var/folders/zj/6xrn345n1ygf4_b5b4zc
c0nh0000gn/T/vZbpzbI/1`

fzf is brewed, vim version version 8.0.1300 (brewed).

I have tried re-installing, using `set rtp+=/usr/local/opt/fzf` and 
```
Plug '/usr/local/opt/fzf'
Plug 'junegunn/fzf.vim'
```

**Comment by junegunn** [comment]
You can run the command in the message on your shell to see what went wrong. I see `README.md` in the command which is not expected. `:FZF <search>` only takes fzf options and an optional directory argument. e.g. `:FZF`, `:FZF --reverse`, `:FZF --reverse /tmp`, etc.
