### ISSUE TITLE
Keep fzf open [binary] on terminal.

### ISSUE THREAD

**Issue by AndreaHasani** [junegunn/fzf#1165]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

###
Is it possible to keep fzf open while executing the command on selected or highlighted query. I mostly want this to use it with mpd. So I select a music and fzf stays open to query another song if I want too.

Thanks.

**Comment by junegunn** [comment]
Have you looked at `man fzf`? You may find `execute` action useful (maybe also invisible `--preview` #820).
