### ISSUE TITLE
Fuzzy completion for custom commands is broken.

### ISSUE THREAD

**Issue by gregorias** [junegunn/fzf#1170]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [x] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

**Steps to reproduce and behaviour**

1. Run `complete -F _fzf_path_completion -o default -o bashdefault fake_cmd`
2. Type `fake_cmd any_dir<TAB><TAB>`

Now typing `fake_cmd **<TAB><TAB>` stops working and returns default tab completion.

**Root cause**

In step 2. the completion function for fake_cmd is changed to bash' default - `_minimal`.

Before step 2., `complete | grep fake_cmd` outputs `complete -F _fzf_path_completion -o default -o bashdefault fake_cmd`, but after step 2., the command outputs `complete -F _minimal fake_cmd`.

This change happens, when `_completion_loader` is run at: https://github.com/junegunn/fzf/blob/9615c4edf13b0cedbc8c9b1c22bac905e12de8af/shell/completion.bash#L125
L125 affects all other commands, however the original completion function is restored later - https://github.com/junegunn/fzf/blob/9615c4edf13b0cedbc8c9b1c22bac905e12de8af/shell/completion.bash#L127-L128 
This restoration doesn't affect fake_cmd, because it is not in `a_cmds`: https://github.com/junegunn/fzf/blob/9615c4edf13b0cedbc8c9b1c22bac905e12de8af/shell/completion.bash#L265

Note that this if the `fake_cmd` is inside `/etc/bash_completion.d/`, then `_completion_loader` doesn't fail, and the switch doesn't happen.

**Comment by junegunn** [comment]
Thanks for the detailed report. Let me see if I can find a way to fix it.

**Comment by gregorias** [comment]
I made `a_cmds` variable configurable in https://github.com/gregorias/fzf/commit/3fc31ac3b6a15a1c18c292dae841954216de4ebe and use it in my personal config: I presume that you might want something different for a wider audience.

**Comment by junegunn** [comment]
I believe 620f0649d4e01766115a994bad7cf381d5942134 fixes the issue (it's not in the master branch).

**Comment by gregorias** [comment]
+1 I confirm that the current devel branch doesn't exhibit this bug. Thank you!

I wonder if it's reasonable to add a regression test for this bug.

**Comment by junegunn** [comment]
Yes, we should. I'm just putting if off because it's a tedious task and I don't have much time. Patches are welcome.

**Comment by gregorias** [comment]
Got it, I'll take a look today (CET time) to see if I can do it within a reasonable timeframe, but I don't expect much. The testing infrastructure is to me usually the second most arcane thing in projects; right behind the build infrastructure.

**Comment by junegunn** [comment]
No hurries, we can do it anytime. The testing code is actually a bit of a mess, we're using ruby code to control tmux windows and panes to test interactive test scenarios.

**Comment by jbriales** [comment]
I'm hitting an issue that exhibits the EXACT same behavior explained in the original post. Wasn't this fixed in master already by a previous commit?
I can provide more details if necessary to try and reproduce.
