### ISSUE TITLE
searching for characters without regard for sequence

### ISSUE THREAD

**Issue by Tim-at-AST** [junegunn/fzf#1176]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

`fzf` uses the characters I enter from the keyboard in the sequence that I type them to match files.
Is it possible / easy to match characters *without* regard to sequence?
for example, if I am looking for `clothes-boys`
i would like to be able to type:
`boyscl`
and get a close match.

Many of my filenames are composed of 2 or 3 words concatenated together, but I cannot easily guess the order of them, so this feature would be useful.

**Comment by junegunn** [comment]
Order matters in fzf, but you can split the query into two terms: `boys cl` will work in this case.
See https://github.com/junegunn/fzf#search-syntax for details.

**Comment by Tim-at-AST** [comment]
Thank you, you are right.

I love FZF!
