### ISSUE TITLE
$FZF_DEFAULT_COMMAND not respected in fish shell

### ISSUE THREAD

**Issue by jberglinds** [junegunn/fzf#1178]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [x] fish

I'm unable to get fzf to respect `$FZF_DEFAULT_COMMAND` when using fish. 
In my fish config, I set `FZF_DEFAULT_COMMAND` to a ripgrep-command for listing files. When I run fzf either using `fzf` or with a keybinding it lists everything as usual, ignoring the variable.
Echoing the variable shows that it has been set.
Running the ripgrep-command manually and piping it to fzf works.

Everything works as expected in bash.

Any pointers for how one would achieve this? Or is it an actal bug?

**Comment by junegunn** [comment]
Works for me just fine

```
jg@junegunn /p/tmp> env FZF_DEFAULT_COMMAND='echo foo' fzf --filter foo
foo
jg@junegunn /p/tmp> env FZF_DEFAULT_COMMAND='echo bar' fzf --filter foo
jg@junegunn /p/tmp>
```

Make sure to export the variable (`-x`).

**Comment by jberglinds** [comment]
Yep, `-x` did it 😓
You have no idea for how long I've tried to understand/fix this.
Thank you so much for this and for fzf!

**Comment by jkryanchou** [comment]
it does not work fine thought shortcut such like `ctrl` + `t`
