### ISSUE TITLE
Changed username, receive "key-bindings.bash: No such file or directory" How to fix?

### ISSUE THREAD

**Issue by Spectator6** [junegunn/fzf#1179]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [x] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

I had to rename a user account, and since then, I receive the following notice whenever launching a terminal session: 
`bash: /home/<old_username>/.fzf/shell/key-bindings.bash: No such file or directory`

How do I go about reconfiguring fzf so that it points to the newly updated /home/<new_username>/.fzf/... directory? 

Thank you in advance! Your Vim plugins are excellent, they always perform well and are very reliable!

**Comment by junegunn** [comment]
Just rerun the install script (`~/.fzf/install`) and it will generate `~/.fzf.bash` file with the updated path that is loaded by your `.bashrc`.

**Comment by Spectator6** [comment]
Excellent, thank you for your help Junegunn!

Sent from my Windows 10 phone

**Comment by millyrowboat** [comment]
If you came here from Google, like me, and installed through `brew install fzf` you might need to run 

```
/usr/local/opt/fzf/install
```

instead

**Comment by VVVFO** [comment]
Just installed with `brew` and it gave yet another path (perhaps because of Apple Silicon):

```sh
/opt/homebrew/opt/fzf/install
```

I think the best way is to read the output of your `brew install` command, or do a `brew reinstall fzf` it's already lost.

**Comment by z0xyz** [comment]
Just rename the `/home/<user name>` with `${HOME}` at your `~/.fzf.bash` or `~.fzf.zsh` files . If you want to improvise and rename this segment with something like the tilde character, then for some reason it will result in the same error. So, just stick to the former substitution.
