### ISSUE TITLE
.fzf.zsh:source:13 no such file or directory: /Users/.../.fzf/shell/key-bindings.zsh

### ISSUE THREAD

**Issue by romenigld** [junegunn/fzf#1180]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [x ] Etc.
- OS
    - [ ] Linux
    - [x ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ x] zsh
    - [ ] fish

When I begin on terminal I have this error:
```
[oh-my-zsh] Random theme '/Users/romenigld/.oh-my-zsh/themes/pygmalion.zsh-theme' loaded...
/Users/romenigld/.fzf.zsh:source:13: no such file or directory: /Users/romenigld/.fzf/shell/key-bindings.zsh
```
my fzf version:
```
fzf --version
0.17.3 (brew)
```
I tried run this and get this error:
```
(brew --prefix)/opt/fzf/install
zsh: parse error near `/opt/fzf/install'
```

**Comment by junegunn** [comment]
You missed `$` at the beginning: `$(...`

**Comment by romenigld** [comment]
Generally this  $ can be for the user run on terminal.
It was this, thank you junegunn!
