### ISSUE TITLE
[Question] Any way to update the preview pane while fzf is running?

### ISSUE THREAD

**Issue by fnurglewitz** [junegunn/fzf#1181]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

Is there any way to update the preview pane with a binded command? I would like to inspect some logs with fzf but I can't find a way to update the preview pane while fzf i still running.

Thanks

**Comment by LuRsT** [comment]
As of version `0.20.0`, you can use `reload` :) 

https://github.com/junegunn/fzf/blob/master/CHANGELOG.md.

Could you try with the new version and if it fits your use case, close this issue?

**Comment by junegunn** [comment]
### Using `refresh-preview` binding (since 0.22.0)

```sh
fzf --preview 'date' --bind space:refresh-preview
```

### Real-time rendering of preview window (since 0.24.0)

```sh
# fzf can render preview window before the command completes
fzf --preview 'sleep 1; for i in $(seq 100); do echo $i; sleep 0.01; done'

# Preview window can process ANSI escape sequence (CSI 2 J) for clearing the display
fzf --preview 'for i in $(seq 100000); do
  (( i % 200 == 0 )) && printf "\033[2J"
  echo "$i"
  sleep 0.01
done'
```
