### ISSUE TITLE
Line grouping

### ISSUE THREAD

**Issue by aureooms** [junegunn/fzf#1182]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [x] fish

I am writing a script that finds duplicate files in a directory. I am using fzf to select which files to delete. What would be the cleanest way of displaying the file list to hint at which lines correspond to the same duplicate file (other than listing filenames by group and trying to guess from the filenames where the group delimitation is)? I was using one instance for each group of duplicate files. However I find it tedious to press enter for each group and I am thinking about displaying all filenames in a single fzf instance and have some way of showing which filenames correspond to the same file. I could add a random symbol in front of the first line of each group. I am wondering if there are better options.

**Comment by LuRsT** [comment]
Hi @aureooms, I'm guessing by now you've managed to work this out, wanna share your solution and close this issue?

**Comment by aureooms** [comment]
@LuRsT I still use a single instance per group of duplicate files. I close this issue since nobody seems to be interested in this feature.
