### ISSUE TITLE
Searching filename & contents while updating preview?

### ISSUE THREAD

**Issue by hydrajump** [junegunn/fzf#1184]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

I'm using the following bash script from [here](https://gist.github.com/BaseCase/c45299e4f8474119881d708a4b728fbf):

```
#!/usr/bin/env bash
set -e

main() {
  previous_file="$1"
  file_to_edit=`select_file $previous_file`

  if [ -n "$file_to_edit" ] ; then
    "$EDITOR" "$file_to_edit"
    main "$file_to_edit"
  fi
}

select_file() {
  given_file="$1"
  fzf --preview="cat {}" --preview-window=right:70%:wrap --query="$given_file"
}

main ""
```

The issue is that it only searches the _filename_ and not the _contents_.

I tried modifying the `select_file()` function like this:

```
select_file() {
  given_file="$1"
  grep --line-buffered --color=never -r "" * | fzf --preview="cat {}" --preview-window=right:70%:wrap --query="$given_file"
}
```

Now I can use `fzf` to search for matching file names and file contents, but the preview window just shows `cat: somefile.txt: # file contents: No such file or directory`.

How can I get `fzf` to search the contents, but still display it properly in the preview window?

**Comment by junegunn** [comment]
```sh
fzf --delimiter=: --preview="cat {1}"
```
