### ISSUE TITLE
Can not bind print-query to a key

### ISSUE THREAD

**Issue by QiangF** [junegunn/fzf#1188]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [x] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

An example is:

    s='';s=$(echo hello, world | fzf --bind 'ctrl-m:print-query')

copy paste the above line into a terminal, type return to select the line, check s with:

    echo $s

and s is empty since no query is typed. 
The expected returned value should be the selected line.
This causes problems in a script I used to add tags to bookmarks, if the tag
doesn't match any existing tags, I create a new tag with ctrl-m.

**Comment by junegunn** [comment]
You should use `--print-query` instead of bind action of the same name. See `man fzf` for details.

**Comment by QiangF** [comment]
No. I only want print-query when the key combination is pressed. 

I use fzf to select tags from a tag list, but if the query is not in the list, only print-query (and then create a tag in my script). In case I don't want to create a new tag, don't print-query.

**Comment by junegunn** [comment]
Well, that's how it works. You can easily process output lines from fzf in your scripts.

**Comment by QiangF** [comment]
Sorry, it's my mistake, I was using ansi-term in emacs. Binding to another key works.
