### ISSUE TITLE
How to preserve ordering

### ISSUE THREAD

**Issue by mudox** [junegunn/fzf#1189]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

I am wrting a litte tool https://github.com/mudox/tav
I want to perserve the item ordering when filtering, but specifying `--tiebreak=index` seems of no use.
```bash
echo 'xxxaaa
aaa
a' | fzf --tiebreak=index
```
gives me 
```
aaa
a
xxxaaa
```
with input `a`

**Comment by junegunn** [comment]
The result is correct, 1. fzf ranks `aaa` and `a` higher than `xxxaaa`, 2. `aaa` and `a` are tied, 3. and `aaa` comes before `a`.

You can completely turn off sorting with `--no-sort`.

**Comment by mudox** [comment]
@junegunn thank you for the quick reply.
Is it possbile to set the __index__ as the  highest ranking criteria.
The position relationship realy matters in my tool.

**Comment by junegunn** [comment]
> Is it possbile to set the index as the highest ranking criteria.

Isn't that what `--no-sort` does?

**Comment by mudox** [comment]
My bad, not perform a clean build.
`-not-sort` works perfectly
