### ISSUE TITLE
Is there a reason not to use --multi ever?

### ISSUE THREAD

**Issue by chenglou** [junegunn/fzf#119]
Gosh I love this plugin! Thanks a lot =)

This is not that bothersome since I can just alias `fzf` to `fzf -m`, but I was wondering if there's any reason to expose the non-multi version as an option in the first place. Just a nit.

**Comment by junegunn** [comment]
Thanks. A good example is when selecting a previous command from the command history (e.g. `CTRL-R` set up by the installer). If you really prefer the option, I recommend that you include it in `$FZF_DEFAULT_OPTS` variable instead of aliasing the command.

```sh
export FZF_DEFAULT_OPTS="--multi --extended"
```

**Comment by chenglou** [comment]
Makes sense.
