### ISSUE TITLE
fzf bash history CTRL+R not working

### ISSUE THREAD

**Issue by m147** [junegunn/fzf#1190]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [* ] Etc.
- OS
    - [* ] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [* ] bash
    - [ ] zsh
    - [ ] fish

I used to be able to invoke an fzf search with CTRL+R in bash.  However, last night I killed my home dir by accident.  I had to rebuild.  However, now fzf CTRL+R doesn't work, all I get is the standard history search.  My bashrc does include

[ -f ~/.fzf.bash ] && source ~/.fzf.bash

Originally, I think I had installed fzf through a vim plugin.  But I'm not understanding what the problem is now.  Anyway, the fzf history search was very convenient, I would like to get it back.

**Comment by junegunn** [comment]
Rerun the install script.

**Comment by m147** [comment]
You mean from vim? Could you point me in the direction of the install
script?

Mindaugas
ミンダウガス

**Comment by junegunn** [comment]
https://github.com/junegunn/fzf#installation

**Comment by m147** [comment]
Thank you

Mindaugas
ミンダウガス

**Comment by stsully** [comment]
worth noting that my macOS bash environment didn't come with .bashrc, but rather .bash_profile. So my CTRL-R didn't work until I merged the two, by sourcing .bashrc from .bash_profile as discussed here: https://apple.stackexchange.com/questions/51036/what-is-the-difference-between-bash-profile-and-bashrc#comment417289_51038

**Comment by horseinthesky** [comment]
Hello.
I've missed the moment when it stopped working. Tried to run `./install` again but no success.

Now
`Ubuntu`: Ctrl+R doesn't work, Ctrl+t works
`Arch`: neither of two works

This is what I have in my `.zshrc`:
```
if [[ -f "$HOME/.fzf.zsh" ]]; then
  source ~/.fzf.zsh
  export FZF_DEFAULT_COMMAND='fd --type file --follow --hidden --exclude .git'
  export FZF_DEFAULT_OPTS="--height 60% --layout=reverse"
  export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
fi
```

When launching `fzf` manually everything works great.
Could you pls help me with this?

**Comment by Ahmed-Khaled-1271999** [comment]
I run Ubuntu 
This command enabled bash Default bindings 

Enable Bash Key Bindings with CNTR+R [مهم]```
# fzf keybindings for Bash:
source /usr/share/doc/fzf/examples/key-bindings.bash
```

**Comment by rootex-** [comment]
In my case, 
```
source /usr/local/share/zsh-vi-mode/zsh-vi-mode.zsh
```
in `~/.zshrc` was blocking `CTRL+R`
