### ISSUE TITLE
Is it possible fzf on WSL work with GVim in Windows

### ISSUE THREAD

**Issue by rickywu** [junegunn/fzf#1191]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [x] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [x] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

I have installed fzf on WSL and it works well, also have Vim 8.0 has terminal feature
Is that possible fzf on WSL work with gvim on Windows?

**Comment by janlazo** [comment]
Non-WSL gvim with WSL fzf?

**Comment by rickywu** [comment]
yes, GVim on Windows with WSL fzf

**Comment by janlazo** [comment]
Need info on your (G)Vim environment since I don't have WSL.
Post the output of the VimL code I posted in https://github.com/junegunn/fzf/issues/1093#issuecomment-339200028

**Comment by rickywu** [comment]
$TMP: C:\Users\Ricky\AppData\Local\Temp

tempname(): C:\Users\Ricky\AppData\Local\Temp\VIAD29A.tmp

  shell=wsl.exe

  shellcmdflag=/c

  shellxquote=

  shellxescape="&|<>()@^

  shellquote=

  shellpipe=

  shellredir=>

**Comment by janlazo** [comment]
1. Does wsl.exe use `/c` for its shell flags? I thought it's a replacement for bash.exe but wsl.exe does not require `-c`.
2. If you unset `shellxescape`, does it still work?
3. Can you find the absolute path of fzf through something like `wsl.exe` which fzf` or similar command?
4. Is wsl.exe exclusive to Windows 10? I can't find any feature detection in Vim for Windows 10 with WSL support.

**Comment by rickywu** [comment]
1. No need /c, just use wsl.exe directly.
2. I use set shellxescape='' and then run terminal still work
3. run in cmd.exe:
C:\Users\Ricky>wsl.exe which fzf
/usr/bin/fzf
run in vim terminal:
999603WJ:/mnt/e/Workstation:)which fzf
/usr/bin/fzf
4.Yes, you must use Windows 10 anniversary update, vim should config like this:
    set shell=wsl.exe
    set shellpipe=|
    set shellredir=>

**Comment by janlazo** [comment]
@rickywu Does wsl.exe allow creation of files/directories named `nul`? cmd.exe and powershell.exe don't allow it and fzf's Vim plugin relies on it.

**Comment by rickywu** [comment]
what's the command to create file/dire named nul, I'll try it.
chcp, do you mean change code page in Windows?

**Comment by janlazo** [comment]
In Ubuntu bash, does `touch nul` create a file?

`chcp` is for code page. fzf needs it for UTF-8 on Windows.

**Comment by rickywu** [comment]
Yes, it create a file named nul

**Comment by janlazo** [comment]
It behaves like bash.exe (msys2). cmd.exe and powershell cannot delete files named `nul`. Does `wsl.exe` use UTF-8 by default? Can you check the language environment variables?

Also, can you test https://github.com/junegunn/fzf/pull/1194?

**Comment by rickywu** [comment]
wsl use utf-8 by default

C:\Users\Ricky>wsl which fzf
/usr/bin/fzf

in vim set shellcmdflag as empty and  :!which fzf return:
wsl.exe  which fzf
/usr/bin/fzf
Hit any key to close this window...

**Comment by rickywu** [comment]
@janlazo anything I can do for you?

**Comment by janlazo** [comment]
@rickywu Can you apply the patch from #1194? I updated the Vim plugin but the current changes are small enough that you can copy/paste it.

**Comment by rickywu** [comment]
@janlazo 
It's working in default settings but not working if I use these:
    set shell=wsl.exe
    set shellpipe=|
    set shellredir=>
    set shellcmdflag=
after set use wsl as shell, I can use wsl in vim terminal but this line
let wsl_fzf = get(split(system('wsl which fzf'), "\n"), 0, '') will start vimrun in windows to run"cmd.exe wsl which fzf", because it calls cmd.exe so will hang up

**Comment by janlazo** [comment]
@rickywu That's an upstream issue with Vim but it can be worked around.

Replace the line

```vim
let wsl_fzf = get(split(system('wsl which fzf'), "\n"), 0, '') 
```

with

```vim
let wsl_fzf = get(split(system('cmd /s/c "wsl which fzf"'), "\n"), 0, '') 
```

**Comment by janlazo** [comment]
@rickyu No. I forgot to consider `shellcmdflag` when switching shells.
