### ISSUE TITLE
Duplicate spaces after rsync bash completion

### ISSUE THREAD

**Issue by arjunkc** [junegunn/fzf#1192]
- Category
    - [] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [x] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

This seems to be a duplicate of this issue [here](https://github.com/junegunn/fzf/issues/375). However, it affects me on all rsync commands, and not just git commit commands. I type

```bash
rsync -aX /home/<Tab>
```
It completes it to
```bash
rsync -aX /home/user/  
```
but with two extra spaces at the end. This does not allow me to continue using completion!

**Comment by edi9999** [comment]
How did you install fzf ? Are you using the latest version?
