### ISSUE TITLE
Ctrl-T not working in tmux

### ISSUE THREAD

**Issue by nayefc** [junegunn/fzf#1193]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [x] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

Hi all,

I've installed fzf keybindings. Ctrl-T doesn't seem to work in a tmux session. I tested this on MacOS and on Linux, and with and without my fzf bash setup posted below.

The other keybindings work. How can I make Ctrl-T work in tmux? I am not using the fzf-tmux script.

Here is my fzf bash setup:
```bash
## fzf
[ -f ~/.fzf.bash ] && source ~/.fzf.bash
export FZF_DEFAULT_OPTS='--height 50% --border'
export FZF_DEFAULT_COMMAND='fd --type f'
# Use fd
_fzf_compgen_path() {
    fd --hidden --follow --exclude ".git" . "$1"
}
# Use fd to generate the list for directory completion
_fzf_compgen_dir() {
    fd --type d --hidden --follow --exclude ".git" . "$1"
}
# Fuzzy complete using fzf
complete -F _fzf_path_completion -o default -o bashdefault ag
complete -F _fzf_dir_completion -o default -o bashdefault tree

# fasd & fzf change directory - jump using `fasd` if given argument, else filter output of
# `fasd` using `fzf`
_z() {
    [ $# -gt 0 ] && fasd_cd -d "$*" && return
    local dir
    dir="$(fasd -Rdl "$1" | fzf -1 -0 --no-sort +m)" && cd "${dir}" || return 1
}
alias z="_z"
alias fzfprev="fzf --preview 'head -100 {}'"
```

**Comment by denisinla** [comment]
Random question, did you update FZF first and were the FZF keybindings successfully installed and noted in your .bashrc?

**Comment by nayefc** [comment]
@denisinla fzf is installed with the latest version (I am using it).

I have the fzf keybindings installed. This was placed in my .bashrc:
```
[ -f ~/.fzf.bash ] && source ~/.fzf.bash
```

Any ideas?

**Comment by denisinla** [comment]
Hmm, the issue I had on my end was that the key bindings were not being copied into my ~/.bashrc when using it in tmux not to mention I am using ZSH instead of bash as well.

**Comment by nayefc** [comment]
As in, `~/.fzf.zsh` wasn't getting added to your rc file?

**Comment by denisinla** [comment]
It wouldn't continue copying over to /.zshrc if there was an issue with my ~/.bashrc for some odd reason.

**Comment by junegunn** [comment]
I'm always on tmux but I don't have the issue. Maybe you have a conflicting tmux key binding on CTRL-T?

**Comment by nayefc** [comment]
I installed it using homebrew and ran the tool to install keybindings which sources .fzf from my bash.

So here's what happens:
I start fzf, search for something and hit `Ctrl-T` and `Ctrl-R` and nothing happens while selecting a file.

When I start fzf with `Ctrl-R` to search bash history, and hit `Ctrl-R` again, it does sort properly (doesn't work when I just run fzf plain), but `Ctrl-T` doesn't do anything.

Am I using it in a wrong way?

**Comment by dmralev** [comment]
I had the same issue, but it turned out to be because of an old tmux session.
Killing it and starting a fresh one resolved the problem.

**Comment by deepredsky** [comment]
@nayefc Doest Ctrl-T work outside of Tmux?

**Comment by nayefc** [comment]
@deepredsky Yep. That's the problem I'm having. How is tmux interfering?  I cleared .tmux.conf and still same issue. Is that the case with you as well?

**Comment by deepredsky** [comment]
@nayefc I dont have that issue now. For me the issue was one of my binding was conflicting with one for fzf but the fix was easy to remove the binding in tmux. I can suggest to kill tmux server after clearing ur `.tmux.conf` by running `tmux kill-server`. Since other keybindings work, it highly likely that there is a keybinding conflict somewhere

**Comment by MeisterTea** [comment]
Same issue for me ! 
Stock fzf, even with empty .tmux.conf
It happens on two Mac-os mojave devices, Ctrl T just moves the letter under the cursor to the right / adds a space at the left if at the rightmost position.
This behavior only happens on tmux.
Any idea ?

**Comment by deepredsky** [comment]
@MeisterTea I commented the the tmux issue page

r u using bash? it seems you have binding of \C-t to the transpose function. try running bind -P | grep transpose to check. Also u can check if the fzf file widget it bound or not by running

```bash
bash-4.4$ bind -X
"\C-t": "fzf-file-widget"
```

**Comment by deepredsky** [comment]
for anybody reading this, solution for @MeisterTea  https://github.com/tmux/tmux/issues/1694#issuecomment-487935184

> most likely u have the emacs binding setting after loading fzf bindings. in your bashrc, try moving set -o emacs after sourcing of the fzf bindings script

**Comment by faruzzy** [comment]
This is happening for me still. I can't use `CTRL-T` nor `CTRL-R` nor `cd <directory>/**` for example in `tmux`. @deepredsky Can you please provide some assistance?

Running `bind -X` returns:

```
"\C-p": "fe"
"\C-r": "__fzf_history__"
"\C-t": "fzf-file-widget"
```

**Comment by deepredsky** [comment]
@faruzzy try invoking the cmds directly to see if they work first

example

```
$ fzf-file-widget
```

also helps to know which shell you are running.

**Comment by faruzzy** [comment]
When I run `fzf-file-widget` the caret just freezes and nothing happens until I run `CTRL-C`.
This is happening on `bash`

**Comment by faruzzy** [comment]
Well, after restarting my mac everything started working normally! Thanks for looking into this
