### ISSUE TITLE
Need to do 3 keypresses to use fzf

### ISSUE THREAD

**Issue by superDuperCyberTechno** [junegunn/fzf#1196]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [x] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [x] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

When I invoke fzf thorugh any of its shortcuts (ctrl-t, ctrl-r, alt-c), I need to add 2 additional, arbitrary keystrokes before I can actually start using it. This has resulted in me invoking fzf by pressing ctrl-r three times in quick succesion. 

First keystroke adds `` `__fzf_history__` `` to the terminal.
Second keystroke adds a newline.
Third keystroke actually summons the list interface to search through.

Is this intentional, am I missing something?

**Comment by junegunn** [comment]
You on Neovim terminal? If so, see #809.

**Comment by superDuperCyberTechno** [comment]
Yes, thanks a lot, dude. Much appreciated. Sorry I couldn't find the issue on my own.
