### ISSUE TITLE
Trailing characters are present in the results

### ISSUE THREAD

**Issue by JonahMoses** [junegunn/fzf#1199]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [x] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

I have:
```
nnoremap ? :Find<SPACE>
command! -bang -nargs=* Find call fzf#vim#grep('rg --line-number --ignore-case --color "always" '.shellescape(<q-args>).'| tr -d "\017"', 1, <bang>0)
```

in my `.vimrc`, and it "mostly" works. However when I search for a term and make a selection, it automatically overwrites some text.

Example:
Step 1. I search for "assetstable"
![image](https://user-images.githubusercontent.com/3462296/34887654-1836f248-f77c-11e7-97fc-8be5e408730d.png)

Step 2. I make a selection on the `web/components/AssetsTab/ProfilesTable.js:23:} = require(../AssetsTable'`

Step 3. Within that selection, on the line where my cursor is at, I see:
![image](https://user-images.githubusercontent.com/3462296/34887714-4f4d991c-f77c-11e7-90f5-1666c9b70ddb.png)

and the file has been changed. If I undo the previous change I get:
![image](https://user-images.githubusercontent.com/3462296/34887751-6904fb52-f77c-11e7-9317-d7475874d182.png)

It is somehow replacing the `c` character in `const` on line 25 with `re('../AssetsTable')|e`

Any suggestions?

**Comment by junegunn** [comment]
Your rg command does not print column number, but you're setting the second parameter of `fzf#vim#grep` to 1 (expects column number). Either add `--column` to rg command, or change 1 to 0.

**Comment by JonahMoses** [comment]
Thank you!
