### ISSUE TITLE
Move install code to the binary itself.

### ISSUE THREAD

**Issue by dcbishop** [junegunn/fzf#120]
Might I recommend moving the install code into the binary itself (other than the bits that download the binary) and making the whole thing go gettable for those with Go already installed.

    get get -u github.com/junegunn/fzf
    fzf install

Actually this already works for building the binary with the current repo format:

    go get -u github.com/junegunn/fzf/src/fzf

People who don't have go can still use the included install script, that will just download the binary then use it to to install the source scripts.

People who don't have git can just download the correct binary directly rather than checkout the tarball of the repo.

**Comment by junegunn** [comment]
Thanks, it's a very interesting idea. But I have mixed feelings about it.

1. I don't think Go is the right tool for doing what the current install script does. We could try to embed the script as a raw string, or to make fzf download the script from GitHub, but I don't want to rewrite the script in pure Go.
1. If you look at the commit history, you'll realize that the auxiliary scripts (install, fzf-completion.bash) have been updated far more often than fzf itself. So if we embed them in the binary we may have to provide compiled binaries for every small changes in them for the users without Go.
1. I'm not sure if I want to recommend using `go get` to build the latest version from the tip of the repo though I know it's a common convention. It forces me to keep the master branch always stable. It's not impossible of course, it's exactly what I've done so far with the Ruby version, but I personally believe it's a better practice to use tagged releases.
