### ISSUE TITLE
Feature request: Add shift-up and shift-down keybinds

### ISSUE THREAD

**Issue by Mange** [junegunn/fzf#1201]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [x] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [x] bash
    - [x] zsh
    - [x] fish

I'd like to use `shift-down` and `shift-down` in my key bindings, but only `shift-left` and `shift-right` are supported.

For context: My plan is to have preview scrolling on `shift-down`, `shift-up`, `page-up` and `page-down`.  Right now I'm fine with just having `pgdn`/`pgup` so I'm still happy and all. ❤️

**Comment by junegunn** [comment]
Thanks for the suggestion. You can now test them by building fzf from source.

**Comment by AriSweedler** [comment]
To get this to work on MacOS native terminal, see https://superuser.com/questions/841391/os-x-terminal-eating-the-shift-key
