### ISSUE TITLE
FZF_ALT_C_COMMAND Not Working

### ISSUE THREAD

**Issue by bryaan** [junegunn/fzf#1202]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [x] fish

Is `FZF_ALT_C_COMMAND` supposed to be working still?  It isnt working for me.  Even tried setting it to junk to get it to fail.  Any quirks using it with fish shell?

Just tested with ZSH and it is working there.

**Comment by junegunn** [comment]
Works for me just fine.

**Comment by bryaan** [comment]
Buried somewhere in readme

53:NOTE: On OS X, Alt-c (Option-c) types ç by default. In iTerm2, you can send the right escape sequence with Esc-c. If you configure the option key to act as +Esc (iTerm2 Preferences > Profiles > Default > Keys > Left option (⌥) acts as: > +Esc), then alt-c will work for fzf as documented.

**Comment by bryaan** [comment]
Ok so that didn't actually work.

**Comment by bryaan** [comment]
Ok it looks like a reinstall got me somewhere.  Also might be the fisherman/fzf package that was causing problems.

By any chance do you know how to do an or statement like this but without the print out from git when it fails?

```
set -x FZF_DEFAULT_COMMAND 'git ls-tree -r --name-only HEAD; or rg --files --follow --glob "!.git/*" --glob "!Library/" '
```

**Comment by Nefari0uss** [comment]
@bryaan You were on the right track. This is how I did it - [Imgur](https://imgur.com/a/pvAQW).

**Comment by 0xdevalias** [comment]
See also:

- https://github.com/junegunn/fzf/issues/164
