### ISSUE TITLE
Tab complete with git results in double spaces

### ISSUE THREAD

**Issue by octol** [junegunn/fzf#1203]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [x] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

I just installed fzf on all my Debian machines (3) and I'm seeing exactly the same issue on all of them. Including on latest 'unstable' Debian. Tab completion with git results in double spaces.
```
git add[tab]
```
results in
```
git add[space][space]
```

Git version 2.15.1
Latest fzf.

As far as I can see this is exactly like #288

**Comment by junegunn** [comment]
I can take a look if you can post a Dockerfile so I can reproduce the problem locally on my machine.

**Comment by lanker** [comment]
https://github.com/junegunn/fzf/commit/d6588fc835aff6d952d86b1bdc5ed7378a846ab9 introduced the double spaces.

**Comment by junegunn** [comment]
Okay, I'll look into it when I get some time.

**Comment by edi9999** [comment]
I can't reproduce either on Fedora.

I have bash --version : GNU bash, version 4.4.12(1)-release (x86_64-redhat-linux-gnu)

What is yours @lanker ?

**Comment by lanker** [comment]
@edi9999: "GNU bash, version 4.4.12(1)-release (x86_64-unknown-linux-gnu)" on an up-to-date Arch Linux.

**Comment by lanker** [comment]
https://github.com/junegunn/fzf/pull/1208 fixes it for me. I'm in a bit of deep water here, but it seems to not break anything on the systems I've tried. But I guess nospace was removed for a reason...?

**Comment by junegunn** [comment]
Can't reproduce the problem on Ubuntu 16

```dockerfile
FROM ubuntu:16.04
RUN apt-get update && apt-get -y upgrade && \
    apt-get install -y --force-yes git curl vim
RUN echo '. /usr/share/bash-completion/completions/git' >> ~/.bashrc
RUN git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf && \
    ~/.fzf/install --all
CMD cd /root && /bin/bash
```

```
docker build -t ubuntu16 .
docker run -it ubuntu16
```

**Comment by junegunn** [comment]
No problem on Arch either

```dockerfile
FROM base/archlinux:2018.01.01
RUN pacman-key --populate archlinux && pacman-key --refresh-keys
RUN pacman-db-upgrade && pacman -Syu --noconfirm base-devel git
RUN echo '. /usr/share/bash-completion/completions/git' >> ~/.bashrc
RUN git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf && \
    ~/.fzf/install --all
CMD cd /root && /bin/bash
```

**Comment by philsc** [comment]
I can reproduce the issue when I use this:
```dockerfile
FROM debian:jessie
RUN apt-get update
RUN apt-get upgrade -y --force-yes
RUN apt-get install -y --force-yes git curl vim bash-completion
RUN git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
RUN ~/.fzf/install --all
CMD cd /root && /bin/bash
```

```ShellSession
$ sudo docker build -t jessie8 .
$ sudo docker run -it jessie8
# . /etc/bash_completion
# . .fzf/shell/completion.bash
# git clon<TAB>
# git clone  [CURSOR]
```

The tab completion added two spaces after clone and will do so after other items as well.

**Comment by junegunn** [comment]
@philsc Thanks, I can reproduce the problem with it. This is a simple, yet incomplete patch (because fzf completion will not append a space when it's expected to do so). I'll see if there's a better way to resolve this. (For those who are interested, make sure to see #1170)

```diff
diff --git a/shell/completion.bash b/shell/completion.bash
index d2287c8..fae35cc 100644
--- a/shell/completion.bash
+++ b/shell/completion.bash
@@ -128,7 +128,11 @@ _fzf_handle_dynamic_completion() {
     # _completion_loader may not have updated completion for the command
     if [ "$(complete -p "$cmd")" != "$orig_complete" ]; then
       eval "$(complete | command grep "\-F.* $orig_cmd$" | _fzf_orig_completion_filter)"
-      eval "$orig_complete"
+      if complete | command grep "o nospace.*\-F.* $orig_cmd$" > /dev/null 2>&1; then
+        eval "$(sed 's/-F/-o nospace -F/' <<< "$orig_complete")"
+      else
+        eval "$orig_complete"
+      fi
     fi
     return $ret
   fi
```

**Comment by junegunn** [comment]
Okay, this looks pretty scary, but I can't think of a better solution right now.

```diff
diff --git a/shell/completion.bash b/shell/completion.bash
index d2287c8..ec3140e 100644
--- a/shell/completion.bash
+++ b/shell/completion.bash
@@ -112,6 +112,8 @@ _fzf_opts_completion() {
   return 0
 }
 
+__fzf_nospace_commands=''
+
 _fzf_handle_dynamic_completion() {
   local cmd orig_var orig ret orig_cmd orig_complete
   cmd="$1"
@@ -128,14 +130,19 @@ _fzf_handle_dynamic_completion() {
     # _completion_loader may not have updated completion for the command
     if [ "$(complete -p "$cmd")" != "$orig_complete" ]; then
       eval "$(complete | command grep "\-F.* $orig_cmd$" | _fzf_orig_completion_filter)"
-      eval "$orig_complete"
+      if complete | command grep "o nospace.*\-F.* $orig_cmd$" > /dev/null 2>&1; then
+        __fzf_nospace_commands="${__fzf_nospace_commands} $cmd "
+        eval "$(sed 's/-F/-o nospace -F/' <<< "$orig_complete")"
+      else
+        eval "$orig_complete"
+      fi
     fi
     return $ret
   fi
 }
 
 __fzf_generic_path_completion() {
-  local cur base dir leftover matches trigger cmd fzf
+  local cur base dir leftover matches trigger cmd fzf separator
   fzf="$(__fzfcmd_complete)"
   cmd="${COMP_WORDS[0]//[^A-Za-z0-9_=]/_}"
   COMPREPLY=()
@@ -145,6 +152,8 @@ __fzf_generic_path_completion() {
     base=${cur:0:${#cur}-${#trigger}}
     eval "base=$base"
 
+    separator="$3 "
+    separator=${separator/%  / }
     dir="$base"
     while true; do
       if [ -z "$dir" ] || [ -d "$dir" ]; then
@@ -153,9 +162,9 @@ __fzf_generic_path_completion() {
         [ -z "$dir" ] && dir='.'
         [ "$dir" != "/" ] && dir="${dir/%\//}"
         matches=$(eval "$1 $(printf %q "$dir")" | FZF_DEFAULT_OPTS="--height ${FZF_TMUX_HEIGHT:-40%} --reverse $FZF_DEFAULT_OPTS $FZF_COMPLETION_OPTS" $fzf $2 -q "$leftover" | while read -r item; do
-          printf "%q$3 " "$item"
+          printf "%q$separator" "$item"
         done)
-        matches=${matches% }
+        [[ "$separator" = " " ]] || matches=${matches% }
         if [ -n "$matches" ]; then
           COMPREPLY=( "$matches" )
         else
@@ -202,7 +211,9 @@ _fzf_complete() {
 }
 
 _fzf_path_completion() {
-  __fzf_generic_path_completion _fzf_compgen_path "-m" "" "$@"
+  local trailer=""
+  [[ "$__fzf_nospace_commands" = *" ${COMP_WORDS[0]} "* ]] && trailer=" "
+  __fzf_generic_path_completion _fzf_compgen_path "-m" "$trailer" "$@"
 }
 
 # Deprecated. No file only completion.
```

**Comment by philsc** [comment]
I can't claim to understand that I understand your patch, but I was curious if you could elaborate a little bit as to what's causing this issue? Seems like only Debian has this issue?

**Comment by junegunn** [comment]
git completion, to which fzf falls back when tab is pressed without completion trigger `**`, is dynamically loaded by bash via `_completion_loader`.

```sh
# No completion for git
root@a0e9fa0048f5:~# complete | grep git$

# Tab is pressed, bash invokes "_completion_loader git"
root@a0e9fa0048f5:~# git <tab>^C

# Git completion is loaded
root@a0e9fa0048f5:~# complete | grep git$
complete -o bashdefault -o default -o nospace -F __git_wrap__git_main git
```

Note that it uses non-default `-o nospace` option, and the completion function should add trailing space or not depending on the context.

Meanwhile, fzf.bash sets up fuzzy completion for git,

```sh
# Start a new shell
root@a0e9fa0048f5:~# bash
root@a0e9fa0048f5:~# complete | grep git$
root@a0e9fa0048f5:~# source ~/.fzf.bash
root@a0e9fa0048f5:~# complete | grep git$
complete -o bashdefault -o default -F _fzf_path_completion git
```

and now `_fzf_path_completion` becomes responsible for calling `_completion_loader git` which will load dynamic completion function for git. And doing so changes the completion for git command as shown above, i.e. `complete -o bashdefault -o default -o nospace -F __git_wrap__git_main git`. fzf extracts and remembers the name of the function, which is `__git_wrap__git_main`, so that it can be used when completion trigger is not given, and it restores the fuzzy completion for git to `complete -o bashdefault -o default -F _fzf_path_completion git`. No `-o nospace`. That's why we ended up with an extra space, using `__git_wrap__git_main` which was designed for `-o nospace` without `-o nospace`.

```sh
# 1. Sets up fuzzy completion
root@a0e9fa0048f5:~# source ~/.fzf.bash
root@a0e9fa0048f5:~# complete | grep git
complete -o bashdefault -o default -F _fzf_path_completion git

# 2. When tab is pressed without **, fzf calls "_completion_loader git" to load dynamic completion functions
root@a0e9fa0048f5:~# git no-trigger<tab>^C
# 3. Completion signature for git changes to "complete -o bashdefault -o default -o nospace -F __git_wrap__gitk_main gitk"
# 4. fzf examines the line and extracts and remembers __git_wrap__gitk_main, so that it can fall back to it later
# 5. fzf restores the completion to "complete -o bashdefault -o default -F _fzf_path_completion git"
```

The patch I posted above adds another step before step 5. fzf now looks at the line `complete -o bashdefault -o default -o nospace -F __git_wrap__gitk_main gitk` and realizes that it has `-o nospace`, and it appends the name of the command to the internal `__fzf_nospace_commands` variable. It also sets up `_fzf_path_completion` with `-o nospace`.

Now `_fzf_path_completion` is responsible for appending extra space only on fuzzy completion.

**Comment by philsc** [comment]
Wow, thank you for the detailed explanation. It makes sense to me now I think. Seems like a rough world, this auto-complete business.

I tested the patch you posted above and so far haven't run into any issues. Thanks!

**Comment by junegunn** [comment]
Turned out that the patch was not good enough and it introduced another issue for the rest of the commands. Fixed it and pushed to master.

**Comment by maharjanaman** [comment]
I'm having a similar problem with macOS and ssh. Am I missing some configs?
