### ISSUE TITLE
Cannot use a list for `options` when specifying `down` in call to `fzf#run()`

### ISSUE THREAD

**Issue by natebosch** [junegunn/fzf#1205]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [x] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [ ] fish

Error thrown is:
```
E730: using List as a String
E15: Invalid expression: get(a:dict, 'options', '').$FZF_DEFAULT_OPTS
```

This is happening here:
https://github.com/junegunn/fzf/blob/7f0caf06833130727b238a2afeb58f3b5096a34c/plugin/fzf.vim#L589

Workaround is to set `options` as a string - but the docs say it should accept a list (and that works when not using `down` - even when using other directions)

Repro is here:
https://github.com/natebosch/dotfiles/commit/4eb2f5eb12e8b71221959d57edbc8ca9834f8e61#diff-028351efa21b460446b5985f7ca2d486R15
(change the string to a list)

Vim in tmux. My `$FZF_DEFAULT_OPTS` is `--exact`.

**Comment by junegunn** [comment]
Should be fixed now. Thanks.
