### ISSUE TITLE
Question: Certain custom completions without a trigger

### ISSUE THREAD

**Issue by ahmedre** [junegunn/fzf#1207]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [x] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

Hi,
Thanks for fzf!

I had a question - in the built in `kill` [command completion](https://github.com/junegunn/fzf/blob/eaf6eb897879becff31ea9b27046c0eff9e1e646/shell/completion.zsh), there's a part that explicitly allows for an empty trigger, allowing me to type `kill` followed by tab to complete it (without setting the `FZF_COMPLETION_TRIGGER` environment variable, since I may not want everything to go through fzf by default).

Is it possible to do this for custom fzf [completion commands](https://github.com/junegunn/fzf/wiki/Examples-(completion)) as well?

Thank you!

**Comment by junegunn** [comment]
Yes, though it's not possible with `_fzf_complete` helper. You'll have to manually update `LBUFFER`. See how kill completion is implemented.

https://github.com/junegunn/fzf/blob/0.17.3/shell/completion.zsh#L165-L171
