### ISSUE TITLE
Accept input separated by NUL bytes

### ISSUE THREAD

**Issue by blueyed** [junegunn/fzf#121]
This would be useful with `find`'s `-print0`.

**Comment by junegunn** [comment]
Could you explain why we would need it?

**Comment by blueyed** [comment]
It would be useful for the `cd` widget to handle directories with newlines for example.

**Comment by junegunn** [comment]
Whoa, do you really have directories with newlines?

**Comment by blueyed** [comment]
No.. :)

But it's good practice to use `find .. -print0` anyway.

**Comment by NightMachinary** [comment]
@junegunn This `--null` option is not present in `fzf 0.18.0`?
