### ISSUE TITLE
Scoring by the frequency of line in input

### ISSUE THREAD

**Issue by notramo** [junegunn/fzf#1213]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [ ] fish

---
I mostly use `fzf` for history searching (in [Elvish](https://elvish.io) shell).
I would like to see an option in `fzf` that enables higher scoring for more frequent items in the input. (So the more frequently used command would get higher score even if its matching score is lower than a rarely used command.

**Comment by junegunn** [comment]
fzf will not support custom scoring system. What you can do is to implement your own sorting program for preprocessing the input and feed the sorted output to fzf with `--no-sort`.

```sh
some-input | custom-sorter | fzf --no-sort
```

**Comment by YasserKa** [comment]
For anyone interested in a frequency tracker, check  [camdencheek/fre: Command line frecency tracking](https://github.com/camdencheek/fre).
