### ISSUE TITLE
bash kill fuzzy completion not returning PIDs on Xubuntu 17.10: Unknown option

### ISSUE THREAD

**Issue by marcelpaulo** [junegunn/fzf#1215]
- Category
    - [x] Completion
- OS
    - [x] Linux
- Shell
    - [x] bash

Fuzzy completion for the **kill** command shows this error message:

`Unknown option`

and doesn't return any PIDs. Here's a screenshot of the result of typing `kill <tab>`:

![image](https://user-images.githubusercontent.com/10074769/36108282-9cc0ffa0-1003-11e8-81d8-3fe30030c5f0.png)

and here, after selecting `smplayer`:

![image](https://user-images.githubusercontent.com/10074769/36108371-dcbe0b02-1003-11e8-8e81-03c41af10046.png)

and here after typing `<enter>`:

![image](https://user-images.githubusercontent.com/10074769/36108429-fb029efc-1003-11e8-801b-0a55ffdab879.png)

As you can see, the PID for smplayer was not completed on the command line.

Here's my version of fzf, which I installed with `go get -u github.com/junegunn/fzf`:

```
paulo@monk:~$ fzf --version
0.17.3
```

**Comment by junegunn** [comment]
Can you investigate which command in this command pipeline produces "Unknown option" message?

https://github.com/junegunn/fzf/blob/cce6aef557b22e28269e1b435e1079a694d43f92/shell/completion.bash#L227
