### ISSUE TITLE
Yank buffer clobbered in Bash emacs mode when accepting reverse search (Ctrl-R) 

### ISSUE THREAD

**Issue by stecman** [junegunn/fzf#1216]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [x] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [x] bash `4.3.48(1)-release`
    - [ ] zsh
    - [ ] fish

Under Bash in its default emacs mode, using fzf's reverse-search binding replaces the yank buffer with a single space character after a command is selected from history:

1. Type "foo bar" on an empty command line and hit <kbd>ctrl</kbd>-<kbd>u</kbd> to cut the line to the yank buffer
2. Start a recursive-i-search with fzf: <kbd>ctrl</kbd>-<kbd>r</kbd>
3. Select any result
4. Press <kbd>ctrl</kbd>-<kbd>y</kbd> to paste "foo bar" where the cursor is
5. Pastes " " instead of the expected "foo bar"

This doesn't occur when Bash is in vi mode (`set -o vi`).

fzf's shell integration is really nice, but as a heavy user of yank this is pretty frustrating :fire_engine:

**Comment by junegunn** [comment]
I believe it should be fixed now. Can you test it?

**Comment by stecman** [comment]
Works great - thanks!
