### ISSUE TITLE
Process for submitting fzf snippets to the Wiki?

### ISSUE THREAD

**Issue by kshenoy** [junegunn/fzf#1217]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

Do you have a preferred way for accepting fzf snippets?

**Comment by junegunn** [comment]
Write permission to the page has been open to anyone, but I think it was a bad idea. The page now has a bunch of untested, inconsistent scripts and I really think we need someone who looks over the updates, but I'm not motivated for the role. Or maybe wiki is not a good medium for sharing scripts.

**Comment by deepredsky** [comment]
might be a good idea to have a separate repo for community submitted snippets, rather than using wiki. That way ppl can submit snippets via PR, and ppl having issues running some snippet can open Issue/PR to address it. I will be happy to test fish shell based snippets
