### ISSUE TITLE
Slight access right inconsistencies prevent from using fzf as a library

### ISSUE THREAD

**Issue by conceptacid** [junegunn/fzf#1220]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [x] Etc.
- OS
    - [ ] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [x] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

I was trying to use fzf as a library within another go application (backend of a web application). Motivation was to access fzf's events directly rather than going through a terminal in order to make the interactive search faster. The core.go file seems to be almost good enough to be a basis of a fzf adapter, however there is one place where the slight inconsistency of access rights prevent from using it as planned. The private fields of the "Item" struct are accessed directly here. One possible solution would be adding public setters to the Item struct. Another, easy but, perhaps, more solid solution would be making a default implementation of the ItemBuilder. Current implementation defines it as a closure type, but it is impossible to provide an implementation from outside of the fzf namespace. If there was a publicly accessible implementation of ItemBuilder similar to the one in the core.go file, it would be possible to re-use all components similar to core.go within another namespace, thus providing an external API.

**Comment by junegunn** [comment]
> I was trying to use fzf as a library

Sorry, I have no plan to support the use case. See #1270

**Comment by jonaz** [comment]
My workarround: https://github.com/junegunn/fzf/issues/1270#issuecomment-504000372
