### ISSUE TITLE
Dismiss fzf vim window before FZF_DEFAULT_COMMAND has finished

### ISSUE THREAD

**Issue by entropia1** [junegunn/fzf#1223]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [x] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

I have an FZF_DEFAULT_COMMAND that does a lengthy file search, but yields the relevant results within milliseconds, most of the time. If I select the file to open, the fzf window clears but stays open until the file search has finished. I can CTRL-C to speed it up, but that feels wrong. Would it be possible to terminate the process upon selecting an item?

I can reproduce it with this simple command:

    let $FZF_DEFAULT_COMMAND = 'echo foo; sleep 2; echo bar;'

Try selecting "foo" before "bar" appears.

This appears to be specific to the vim plugin, the fzf command line process does not have this issue.

**Comment by junegunn** [comment]
See https://github.com/junegunn/fzf/issues/398

**Comment by entropia1** [comment]
Thanks! Handling SIGPIPE indeed inproves the situation a lot. Though the signal is not raised immediately, so there still is a delay.
