### ISSUE TITLE
replace-query takes truncated line

### ISSUE THREAD

**Issue by bAndie91** [junegunn/fzf#1225]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [ ] fish

I noticed that `replace-query` command takes only the visible part of the current selection (when the terminal's width is too small and lines get truncated).
I consider this to be a bug.

**Comment by junegunn** [comment]
The length of a query string is currently limited. Maybe we can fix it (need to implement horizontal scroll of query string in that case), but I don't know why one would want to paste a long query string on fzf prompt.

**Comment by bAndie91** [comment]
I see, query string (even when it's typed manually) is limited to the terminal's width.
my bad, I did not noted my real requirement here.
it's indeed not realistic to allow so long query string.
