### ISSUE TITLE
External UI for fzf?

### ISSUE THREAD

**Issue by vheon** [junegunn/fzf#1228]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [x] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [ ] fish

Hi junegunn,

This is more a question than an issue: is it already possible or do you ever considered to allow external UI to the fzf binary? right now it doesn't seems possible to create an interface and using fzf as a backend of such UI. I'm bringing this up because I'm trying emacs and it might be because I'm accustomed to my vim workflow but every potential replacement that I tried does not compare with the speed of fzf and would be awesome to create a package for emacs similar to helm or ivy but backed by fzf for speed and defer all the UI stuff to emacs itself like the preview and such.

**Comment by sullyj3** [comment]
#1010 and #743 seem relevant

**Comment by junegunn** [comment]
No, it's not planned.
