### ISSUE TITLE
Trying to reconfigure fzf to not do fuzzy-matching

### ISSUE THREAD

**Issue by kuwze** [junegunn/fzf#1230]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [x] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

I installed FZF and configured it for fuzzy search, but I realize I don't want that and want strict searching instead. How do I go about changing that? I tried reinstalling fzf but that didn't work. Where does fzf store configuration files outside of ~/.fzf?

**Comment by junegunn** [comment]
The answer can be found on the README page.
