### ISSUE TITLE
Ctrl-T not working after fresh install (Ctrl-R does though)

### ISSUE THREAD

**Issue by cmatzenbach** [junegunn/fzf#1232]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [x] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux (Arch)
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

Just downloaded fzf for the first time (on this particular machine) from the official Arch repos (via pacman).  Restarted zsh, verified that the code to source fzf is in .zshrc, and tried Ctrl-T, but it doesn't work (just beeps).  Ctrl-R, on the other hand, does work, but not Ctrl-T.  Any ideas?

**Comment by deathtrip** [comment]
I'm also on Arch and have the same problem on zsh. It works on bash and fish though. 
But when i change the action to 'fd --type f' i get this error on zsh:
`(eval):1: command not found: fd --type f`
and on fish this one:
- (line 1): Variables may not be used as commands. In fish, please define a function or use 'eval $FZF_DEFAULT_COMMAND'.
begin; $FZF_DEFAULT_COMMAND | fzf -m --query "" 
       ^
from sourcing file -
	called on line 60 of file /usr/share/fish/functions/eval.fish

in function “eval”
	called on standard input

in function “fzf-file-widget”
	called on standard input

On bash everything works with both the default find and with fd.

**Comment by cmatzenbach** [comment]
@deathtrip You're absolutely right - I just tested, and it works on bash.  So it's an Arch/zsh problem - although I doubt it has anything to do at all with Arch since bash and fish are fine.  Does this mean it's broken for zsh?  I would think this would be a big issue with how popular this program is

**Comment by deathtrip** [comment]
Well, it certainly looks like fzf needs more testing on zsh. As this is the second problem i found (other being #1257) where something works on bash and fish, but is broken in zsh.

**Comment by junegunn** [comment]
I have very limited knowledge and experience on zsh as I don't use it. Patches are welcome.

**Comment by junegunn** [comment]
I can't reproduce with the latest archlinux docker image, everything works as expected.

```
# docker run -it base/archlinux

pacman-db-upgrade
pacman -Syyu --noconfirm
pacman -S --noconfirm fzf zsh fish

mkdir -p ~/.config/fish/functions
cat > ~/.config/fish/functions/fish_user_key_bindings.fish << EOF
function fish_user_key_bindings
	fzf_key_bindings
end
EOF

echo '. /usr/share/fzf/key-bindings.zsh' >> ~/.zshrc

export FZF_DEFAULT_COMMAND='seq 1 100'
```

It's probably a configuration issue.

@deathtrip 

```
(line 1): Variables may not be used as commands. In fish, please define a function or use 'eval $FZF_DEFAULT_COMMAND'.
begin; $FZF_DEFAULT_COMMAND | fzf -m --query ""
^
```

This repository does not even contain the code you mentioned. I don't know where that came from? Please verify your configuration. If you're certain that it's an issue of fzf, please provide the steps to reproduce the problem with the docker image (like I posted above) so I can try it locally on my macbook.

**Comment by gavlinski** [comment]
In my case I had just to install [fd](https://github.com/sharkdp/fd). Then it worked with ZSH.
