### ISSUE TITLE
Add {alt,ctrl}-{up,down} keybinds

### ISSUE THREAD

**Issue by zx8** [junegunn/fzf#1234]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [x] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [x] bash
    - [x] zsh
    - [x] fish

Similar to https://github.com/junegunn/fzf/issues/1201, would it be possible to add the following keybinds:
- `alt-up`
- `alt-down`
- `ctrl-up`
- `ctrl-down`

**Comment by junegunn** [comment]
I can add support for alt-up/down/left/right keys. But I don't think terminals support ctrl-up and down.

**Comment by alok** [comment]
When I bind something to an alt key, it doesn't work. I just get the escape sequences:

```
3C (alt right)
3D (alt left)
3A (alt up)
3B (alt down)
```
