### ISSUE TITLE
Cannot update using vim-plug.

### ISSUE THREAD

**Issue by tutabeier** [junegunn/fzf#1235]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [x] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

Tried to update using `vim-plug` and I receive.
```
- Finishing ... Done!
x fzf:
    fatal: refusing to merge unrelated histories
```

It's happening for a while, so I'm not sure if it was a breaking change.

**Comment by junegunn** [comment]
Did you make any commits manually on fzf directory?

`:PlugClean` will detect the problem and delete the directory. If it doesn't, you can manually delete the directory. Then re-run `PlugUpdate` or `PlugInstall`.

**Comment by tutabeier** [comment]
I didn't, @junegunn.

I removed both `~/.vim/plugged` and `~/.fzf` folders and rerun the commands and now is working as expected.

Thanks.

**Comment by WloHu** [comment]
@junegunn Sorry for necro-bumping. But to give more context I've had the same issue and in my case the reason of this message was that `origin/master` of some plugin was rebased and force pushed.

One solution was to run `:PlugClean` and `:PlugInstall` and another to `git pull --rebase` inside direcotry of failing package.

I'm writing that in case where you'd like to handle that base during `:PlugUpdate`.
