### ISSUE TITLE
Pressing <Esc>C when using set -o vi calls fzf and deletes the line being edited

### ISSUE THREAD

**Issue by Aster89** [junegunn/fzf#1238]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [x] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

I use the `vi` editing mode for `bash`. Specifically the line `set -o vi` is in my `.bashrc` file and `set show-mode-in-prompt on` in my `.inputrc`.

The sequence <kbd>Esc</kbd><kbd>C</kbd> while in insert mode results in a call to fzf, which is not what should be done, since that sequence of keys is what one press if wants to exit insert mode and change something (_e.g._ <kbd>Esc</kbd><kbd>C</kbd><kbd>B</kbd>, ...). Actually the problem exists only if the two keys <kbd>Esc</kbd> and <kbd>C</kbd> are pressed in rapid succession, no matter what mode is active before the combo.

**EDIT**
I noticed that what happens when I press <kbd>Esc</kbd><kbd>C</kbd> is a call to `__fzf_cd__`, which is binded, in the `key-bindings.bash` file, to the escape sequence `\ec`, for which the comment reads `# ALT-C - cd into the selected directory`; indeed, when I press <kbd>Esc</kbd><kbd>C</kbd> the same thing happens as I had pressed <kbd>Alt</kbd>+<kbd>C</kbd>. After all, I verify, by preceding them with <kbd>Ctrl</kbd>+<kbd>V</kbd> on the command line, that both <kbd>Esc</kbd><kbd>C</kbd> and <kbd>Alt</kbd>+<kbd>V</kbd> are represented with the characters `^[c`, which should be the same as `\ec`.

**Comment by Aster89** [comment]
I noticed that what happens when I press <kbd>Esc</kbd><kbd>C</kbd> is a call to `__fzf_cd__`, which is binded, in the `key-bindings.bash` file, to the escape sequence `\ec`, for which the comment reads `# ALT-C - cd into the selected directory`; indeed, when I press <kbd>Esc</kbd><kbd>C</kbd> the same thing happens as I had pressed <kbd>Alt</kbd>+<kbd>C</kbd>. After all, I verify, by preceding them with <kbd>Ctrl</kbd>+<kbd>V</kbd> on the command line, that both <kbd>Esc</kbd><kbd>C</kbd> and <kbd>Alt</kbd>+<kbd>V</kbd> are represented with the characters `^[c`, which should be the same as `\ec`.

**Comment by junegunn** [comment]
Yeah, <kbd>ALT-C</kbd> is indeed <kbd>ESC</kbd><kbd>C</kbd>, that's how terminals interpret alt key chords. I can see that it can be a problem on vi-mode, but I'm not sure if I can change the binding and break backward compatibiliy. If that's too annoying, you might want to disable the binding:

```sh
set -o vi
[ -f ~/.fzf.bash ] && source ~/.fzf.bash
[[ $- =~ i ]] && bind '"\ec": nop'
```

or bind the functionality to another key chord like so

```sh
set -o vi
[ -f ~/.fzf.bash ] && source ~/.fzf.bash

# Re-bind it to CTRL-Q
bind "$(bind -s | grep '^"\\ec"' | sed 's/ec/C-q/')"
[[ $- =~ i ]] && bind '"\ec": nop'
```

**Comment by Aster89** [comment]
Wow. Maybe I've always missed this: when I press <kbd>Alt-C</kbd>, where <kbd>C</kbd> can be any key, my keyboard is really sending the same electrical signal as I had quickly pressed <kbd>Esc</kbd><kbd>C</kbd>, so there's no way to distinguish which one was pressed, right?

**Comment by Frydac** [comment]
Because I had to invest some time to find this out, in zsh this seems to work for me:
```[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
[[ $- =~ i ]] && bindkey -r '\ec'
```

**Comment by mrbig033** [comment]
I opened an issue with a similar problem: https://github.com/junegunn/fzf/issues/1291

**Comment by Aster89** [comment]
At the time of my last comment I abandoned fzf, but recently I've been using the Vim plugin and that made me want to reuse it even in command line, so I've looked at your suggestion


> ```shell
> set -o vi
> [ -f ~/.fzf.bash ] && source ~/.fzf.bash
> 
> # Re-bind it to CTRL-Q
> bind "$(bind -s | grep '^"\\ec"' | sed 's/ec/C-q/')"
> [[ $- =~ i ]] && bind '"\ec": nop'
> ```

but I observe a strange behavior, where <kbd>Alt</kbd>+<kbd>c</kbd> keeps triggering fzf, as the GIF below shows.

Do you have any clue?

![altc](https://user-images.githubusercontent.com/20521900/194089250-b3b98c18-d8ff-4441-9811-d5fd6b3e0c18.gif)

I'm not sure what could trigger this behavior, so please, tell me if more information is needed to understand what's going on.

For now, I can think of the following info:

  - I've added these two lines at the end of my `~/.bashrc`
    ```bash
    bind "$(bind -s | command grep '^"\\ec"' | sed 's/ec/ed/')"
    [[ $- =~ i ]] && bind '"\ec": nop'
    ```
    leaving the other two because
    1. I don't have an `~/.fzf.bash` file
    2. I set the vi mode via `~/.inputrc`
  - `~/.inputrc` has the following content
    ```inputrc
    $include /etc/inputrc
    set editing-mode vi
    set show-mode-in-prompt on
    set vi-ins-mode-string \1\e[36;1m\2 \1\e[0m\2
    set vi-cmd-mode-string \1\e[32;1m\2☻ \1\e[0m\2
    set skip-completed-text on
    "\t": menu-complete
    "\e[Z": menu-complete-backward
    set completion-ignore-case on
    "\C-e": shell-expand-line
    set colored-stats on
    set visible-stats on
    ```

**Comment by diminutivesloop** [comment]
I use https://github.com/jeffreytse/zsh-vi-mode ZSH plugin for vi mode and the following config worked for me to remap this behavior to `alt-q`:
```shell
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
bindkey -r '\ec' 
bindkey -M vicmd '\eq' fzf-cd-widget
bindkey -M viins '\eq' fzf-cd-widget
```
