### ISSUE TITLE
--header ignores ansi codes, despite man page to the contrary

### ISSUE THREAD

**Issue by brandondrew** [junegunn/fzf#1239]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

In fzf 0.17.3 (the latest version the Homebrew has), I am not able to get a --header to honor ansi escape codes.  The code below illustrates the problem, where `echo -e` gives the expected results, but `fzf --header` does not.  I'm using both "\e" and "\033", and both interpolation and including them directly in the string, and none of these approaches are working.

The man page says that ANSI codes are honored in the `--header`, even without `--ansi`, but that's not what I'm seeing.

~~~
reverse=\e[7m
reverse_end=\e[27m
fzf --header "\033[33;5m?\033[0m Toggle Preview ${reverse}esc${reverse_end} Exit"
echo -e "\033[33;5m?\033[0m Toggle Preview ${reverse}esc${reverse_end} Exit"
~~~

**Comment by brandondrew** [comment]
(I also tried using `--ansi` and that didn't solve the problem either.)

**Comment by junegunn** [comment]
In this case, you're passing literal `\e` to fzf and echo. `-e` flag tells echo command to treat it as an escape character.

```sh
# Literal \e
echo "\e[33;5myellow\e[m"

# \e interpreted as escape character
echo -e "\e[33;5myellow\e[m"

# Pass the output of "echo -e" to fzf
fzf --header "$(echo -e "\e[33;5myellow\e[m")"

# https://www.gnu.org/software/bash/manual/html_node/ANSI_002dC-Quoting.html
fzf --header $'\e[33;5myellow\e[m'
```
