### ISSUE TITLE
Quick-match like feature of Unite.vim

### ISSUE THREAD

**Issue by mhrebenyuk** [junegunn/fzf#124]
Quick-match is powerful feature of Unite.vim. 

Basically it let you pick the candidate in narrowed list by entering quick-match mode and pressing one of home-row key (like easy-motion). To get the idea  please see this [pic](https://cloud.githubusercontent.com/assets/2410802/5996634/93c357ea-aaad-11e4-86a4-1e0f8515e0bb.png). 
It is blazingly quick compare to other ways of chosing the candidate.

**Comment by junegunn** [comment]
Thanks for the suggestion. But I don't like the extra complexity it adds. Users have to learn about the mode and how to properly use it. Maybe it's just me, but I usually don't spend more than a couple of seconds on fzf and most of the time, I can easily narrow down the list and get what I want just by typing in a few more characters (especially with extended-search mode) without actually *reading* the list. I don't deny that some users might find it useful, but extra features always have their cost, and in this case I'd like to keep it simple. Thanks!
