### ISSUE TITLE
Spinner not shown when --select-1 or --exit-0 is used

### ISSUE THREAD

**Issue by arunvelsriram** [junegunn/fzf#1240]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [x] bash
    - [x] zsh
    - [ ] fish

Hi, I noticed that when using `--select-1` or `--exit-0` spinner is not shown. It looks like `fzf` waits for the result list and then enters the list selection mode. Is this the intended behavior?

![fzf](https://user-images.githubusercontent.com/6568319/37552749-f01cfb3a-29e0-11e8-8788-623b2fc1e9dd.gif)

**Comment by junegunn** [comment]
Yes. fzf does not start user interface until it's clear that the condition cannot be met.

```sh
# No point of starting the finder interface
seq 10 | fzf -q 5 --select-1
```
