### ISSUE TITLE
How to configure to always offer src/path/to/file before lib/path/to/file

### ISSUE THREAD

**Issue by snoblenet** [junegunn/fzf#1244]
When I type `file`, fzf rightly suggests both `src/path/to/file` and `lib/path/to/file`. However, the latter is always auto-selected, while the former is almost always the file I need to edit. Is there a way to make fzf always promote `src` ahead of `lib`? Thanks.

**Comment by junegunn** [comment]
Both matches will have the same score, so fzf will simply point to the one that came before the other.

```sh
fzf --query file << EOF
src/path/to/file
lib/path/to/file
EOF

fzf --query file << EOF
lib/path/to/file
src/path/to/file
EOF
```

What you can do is to preprocess the input list based on your preferences before feeding it to fzf.
