### ISSUE TITLE
First line of files clobbered

### ISSUE THREAD

**Issue by nyarly** [junegunn/fzf#1246]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [x] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [x] fish

When I use fzf, in Neovim, or on the command line, inside tmux or out, the first file is represented like
```
?]11;#fdf6e3??]10;#...
```
In tmux the output is like
```
?Ptmux;??]11;#fdf6e3??\?Ptmux;...
```
(this runs off the right side of my terminal, but I can't copy and paste it...)

This happens in urxvt and alacritty, but not xterm.

*Most* of the time, it's an unfortunate visual glitch, but sometimes it means I can't use fzf.vim to open important files in my projects.

I've tried setting FZF_DEFAULT_COMMAND to see if it's related to that bash vs. sh or the command itself, but `rg --files --color never` has the same effect.

**Comment by junegunn** [comment]
I recall this was specific to fish, you might want to take a look at the related issues.
https://github.com/junegunn/fzf/search?q=Ptmux&type=Issues&utf8=%E2%9C%93

**Comment by nyarly** [comment]
None of those solutions appear to apply. I don't have any of the mentioned fish configurations, and setting my TERM explicitly doesn't make a difference.

Note that `rg --color never --files | fzf` doesn't exhibit the issue, but `env FZF_DEFAULT_COMMAND="rg --color never --files" fzf` does.

**Comment by junegunn** [comment]
> Likewise, running bash and then calling fzf from with that shell does produce the issue.

Make sure that `$SHELL` is set to bash in that case.

**Comment by nyarly** [comment]
Not only that, but I was running 0.16.4 :fearful: Updating to 0.17.4 fixed the issue.
