### ISSUE TITLE
Selection isn't always printed

### ISSUE THREAD

**Issue by r-darwish** [junegunn/fzf#1247]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [ ] fish
    - [x] xonsh

I've been trying to use fzf to complete xonsh history and noticed that sometimes, despite the fact that an entry is selected, it is not inserted to the command line.

At first, I suspected that it's probably the xonsh plugin's fault as this problem never occurred to me in zsh. However, I tried to isolate the problem by running `history show all | fzf` directly multiple times. The gif shows that sometimes no output is printed despite my consistent action for choosing the first candidate.

![fzf](https://user-images.githubusercontent.com/1383193/38163546-066fff90-34fe-11e8-8c1b-4828a4f09634.gif)

**Comment by junegunn** [comment]
I think it's a display issue of your shell. Have you tried

```sh
history show all | fzf >> output
```

to see if fzf properly prints the selection to stdout?

**Comment by r-darwish** [comment]
It seems like a display issue indeed
