### ISSUE TITLE
godoc completion 

### ISSUE THREAD

**Issue by monouser7dig** [junegunn/fzf#1250]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [x] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

I'd like to fuzzy search the godoc standard library full text or functions/struct names.
Like `godoc io Writer`
I could not find an example for this yet though and no option in the godoc command line help page. Does someone have an idea how to do that?
I just assume some people around here use go as well and might have had the same issue.

Thanks!

**Comment by junegunn** [comment]
You'll have to find a command that lists all the symbols in the standard library. It's not something I can answer.

**Comment by monouser7dig** [comment]
found this s/dmenu/fzf
https://eli.thegreenplace.net/2018/command-line-autocomplete-for-go-documentation/
