### ISSUE TITLE
Terminal is frozen after running vim from inside fzf

### ISSUE THREAD

**Issue by jdevera** [junegunn/fzf#1252]
- Category
    - [x] fzf binary

- OS
    - [x] Linux

- Shell
    - [x] bash

On this command:
```bash
(cd ~/.dotfiles && fd -tl -tf) | 
    fzf --preview 'pygmentize -g -f terminal256 -P style=emacs ~/.dotfiles/{}' \
        --bind 'enter:execute(vim ~/.dotfiles/{})'
```

When I hit enter on a file, I get this warning for a couple of seconds before Vim opens the selected file:

    Vim: Warning: Input is not from a terminal

I notice that hitting the backspace key in Vim results in `^?` being added to the file.

But the real problem comes when I exit Vim. I am back in the fzf screen, but everything is frozen, **really** frozen, and no amount of C-C, or C-Z, or C-Q will get be my terminal back.

Is this a known issue? Is there a workaround to start Vim bound to a key in fzf?

**Comment by junegunn** [comment]
Does https://github.com/junegunn/fzf/issues/1101#issuecomment-338495142 help?

**Comment by jdevera** [comment]
It does! Thanks!
