### ISSUE TITLE
Add command for specifying a different exit status

### ISSUE THREAD

**Issue by urbainvaes** [junegunn/fzf#1258]
Sometimes I would like to handle the match returned by `fzf` differently according to the keybinding that was used to accept it. I haven't found a way to do this easily in the current version of `fzf` (though I imagine writing to a temporary file with the `execute` command would work, but that feels like a workaround), but thought that a possible solution would be to add a command such like `accept-[exit-code]`, that would accept the match and terminate with the exit status `[exit-code]`, a bit like the `sed` command `q [exit-code]`. If you think that this would be a good idea, I'd be happy to work on it and submit a pull request.

**Comment by junegunn** [comment]
`--expect` is exactly what you're looking for. See man page for details.
