### ISSUE TITLE
Add tmux example

### ISSUE THREAD

**Issue by george-b** [junegunn/fzf#126]
I've just added an example of using fzf to search tmux panes to the wiki and thought this would open as a PR or issue but was surprised to find the edit automatically accepted. Not sure what the guide lines are for contributing so I thought I'd open an issue to check.

Example of tmux pane selection;  

```sh
# ftpane - switch pane
ftpane () {
  local panes current_window target target_window target_pane
  panes=$(tmux list-panes -s -F '#I:#P - #{pane_current_path} #{pane_current_command}')
  current_window=$(tmux display-message  -p '#I')

  target=$(echo $panes | fzf)

  target_window=$(echo $target | awk 'BEGIN{FS=":|-"} {print$1}')
  target_pane=$(echo $target | awk 'BEGIN{FS=":|-"} {print$2}' | cut -c 1)

  if [[ $current_window -eq $target_window ]]; then
    tmux select-pane -t ${target_window}.${target_pane}
  else
    tmux select-pane -t ${target_window}.${target_pane} &&
    tmux select-window -t $target_window
  fi
}
```

**Comment by junegunn** [comment]
Thanks, it looks really useful! Yes, anyone can edit wiki without restriction.
I tested your example on bash, and I had to change a line to make it work on my bash.
See: https://github.com/junegunn/fzf/wiki/Examples/_compare/993a79e%5E...993a79e

**Comment by junegunn** [comment]
Since I use 1 as the base index, I can set up the following key binding.

```
set-option -g base-index 1
bind-key 0 run "tmux split-window -p 40 'bash -ci ftpane'"
```

Thanks!

**Comment by george-b** [comment]
Ah I hadn't tested bash, thanks for making the correction for this to be more generic.
