### ISSUE TITLE
Not an editor command: Ag

### ISSUE THREAD

**Issue by weaming** [junegunn/fzf#1263]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [x] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

Error: `Not an editor command: Ag` after execute `:Ag<CR>` in neovim

**Comment by junegunn** [comment]
It's in https://github.com/junegunn/fzf.vim
