### ISSUE TITLE
Q: disable for fzf reverse search "set-hook -g after-new-window"

### ISSUE THREAD

**Issue by eugenevd** [junegunn/fzf#1264]
- Category
    - [ ] fzf binary
    - [x] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

When using tmux conf:
set-hook -g after-new-window 'command-prompt -I "#{window_name}" "rename-window '%%'"'

1. Open two panes
2. Maximise one pane
3. Press C-r to initiate fzf reverse search

Now it prompts for a window name?
From my point of view, this is not a new window, it's just a new pane (for fzf)?

Is there a way to disable the hook when doing C-r ?

**Comment by junegunn** [comment]
I can't reproduce the problem with that line in my tmux.conf. Must be a configuration issue.
