### ISSUE TITLE
[Question] how can I toggle exact match behavior in fzf

### ISSUE THREAD

**Issue by amosbird** [junegunn/fzf#1265]
fzf provides  `'` prefix for exact match, however it isn't convenient for daily usage since a common use case of exact match often appears after a fuzzy match, thus toggling exact match seems to be a better way. Is there a way to achieve this? thanks!

**Comment by junegunn** [comment]
No, you can't change `--exact`ness dynamically. But fzf implements all relevant readline key bindings, so you can easily move your cursor around if you're familiar with them. For example, you can move your cursor to the front with <kbd>CTRL-A</kbd>, to the end with <kbd>CTRL-E</kbd>, and to the front of the current word by <kbd>ALT-B</kbd>, etc. Which means you can quickly prepend `'` by pressing <kbd>CTRL-A</kbd><kbd>'</kbd> or <kbd>ALT-B</kbd><kbd>'</kbd>, then you can move your cursor back to the end with <kbd>CTRL-E</kbd> if you need to type in more search keywords.
