### ISSUE TITLE
Feature req: Select w/modifier

### ISSUE THREAD

**Issue by tofagerl** [junegunn/fzf#1269]
This one is a little hard to describe, and honestly it would require a lot of work, since functions that make use of fzf would have to be rewritten to take advantage of it, but I feel like I should still put it down "on paper" so to say. 

I'd like a way to select a file in different ways - that is to send it back to one of several different functions. For example, instead of just typing the file into the function that called the fzf, you could send it to one of 2-3 different functions. Find file could send it to "open in Sublime Text" directly from fzf, for example. 

The only way I can think of doing this is with modifiers, so if I have a txt file selected I could press enter to just send the file back to the terminal, alt-enter to open with sublime text, or shift-enter to open in vim. Perhaps even ctrl-space to open in Visual Studio Code.

The more I write, the more this looks like a launcher workflow, but the possibilities are a little larger I think.

**Comment by junegunn** [comment]
You can already implement the scheme with `--expect` option.

```sh
fzf --expect ctrl-x,ctrl-t,ctrl-v,enter,alt-enter
```

Then the first line of the output will be the name of the key pressed. Note that the key selection is limited to what terminals can understand, so no ctrl-enter or shift-enter. See `man fzf` for details.
