### ISSUE TITLE
ruby/go clarification

### ISSUE THREAD

**Issue by acornejo** [junegunn/fzf#127]
I just stumbled on this project. Its amazing!

I briefly explored the code base, and I can't figure out what is going in ruby. There seems to be a full ruby implementation at the root of the project directory.

On the other hand, inside the src directory there is what looks to be like a complete go implementation. I would expect the go version to be a lot faster, so then I don't understand why the ruby thing is still there.

Browsing through the install script it seems like the ruby version is only there for the special case when there is no binary distribution for your platform, but then why keep it in the repository (is it still being updated and developed together with the newer go version, or has it been replaced/deprecated in favor of go?)

**Comment by junegunn** [comment]
fzf has been around for more than a year as a ruby script, it was recently rewritten in go.
See: https://github.com/junegunn/fzf/blob/master/src/README.md

I'm not going to further develop the Ruby version, but I'll just leave it there for backward compatibility. If I remove the file from the repo, users on systems where Go version doesn't run (e.g. Centos/RHEL 5.5) will immediately run into trouble when they update the repository. Note that [the recommended way of installing fzf](https://github.com/junegunn/fzf#installation) has been to clone the repository and run the install script though you can choose to just download Go binary or Ruby script. If one simply follows the instruction, the install script will try its best to choose the right version for the system.

**Comment by acornejo** [comment]
Thanks for the prompt answer. it makes sense, too bad ruby can't be compiled to put it also in the release section (or maybe it could go there, even in source form, and be fetched via curl/wget as the go binaries)

Been using fzf for the last day, and I love it. Thanks for sharing it!
