### ISSUE TITLE
Use as a Go library?

### ISSUE THREAD

**Issue by nyarly** [junegunn/fzf#1270]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [x] Mac OS X
    - [x] Windows
    - [x] Windows Subsystem for Linux
    - [x] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [ ] fish

It would be really incredible to be able to use fzf as part of the interface to Go commands. I think all that would be needed is a refactor of `src.Run` and maybe a pass on the exported interface. Is that a change you're willing to accept?

**Comment by junegunn** [comment]
See https://github.com/junegunn/fzf/pull/1053#issuecomment-330024275

It was suggested before but I don't want to maintain the change and the new requirements that will stem from it, so no, I won't accept.

**Comment by nyarly** [comment]
:+1: I hadn't seen that PR.

**Comment by jonaz** [comment]
I just wrote this function to use in my cli tools that needs fzf. Works fine but depens on external binary fzf:

```
func fzf(data io.Reader) (string, error) {
	var result strings.Builder
	cmd := exec.Command("fzf")
	cmd.Stdout = &result
	cmd.Stderr = os.Stderr
	stdin, err := cmd.StdinPipe()
	if err != nil {
		return "", err
	}
	_, err = io.Copy(stdin, data)
	//_, err = data.WriteTo(stdin)
	if err != nil {
		return "", err
	}
	err = stdin.Close()
	if err != nil {
		return "", err
	}

	err = cmd.Start()
	if err != nil {
		return "", err
	}

	err = cmd.Wait()
	if err != nil {
		return "", err
	}
	return result.String(), nil

}
```
