### ISSUE TITLE
Is it possible to reload fzf input?

### ISSUE THREAD

**Issue by jan-warchol** [junegunn/fzf#1271]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [x] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

I’d like to use fzf for filtering data that takes some time to fetch from a server. To improve user experience, I’d like to use a cache as the initial input (so that the user can start typing the pattern and see how it matches against the cached data) and _replace_ the input with actual data when it finishes downloading.

I’ve looked at the man page but I don’t see any such feature and I’m not sure if this can be done. Is it possible? How should I go about it?

**Comment by junegunn** [comment]
No, it's not possible.

**Comment by jan-warchol** [comment]
Ok, I understand. Do you think it would be hard to add such a feature to fzf? Maybe I could contribute it. Would you accept such contribution?

Thanks!
