### ISSUE TITLE
Chained completion in Vim

### ISSUE THREAD

**Issue by jarednorman** [junegunn/fzf#1274]
- Category
    - [x] Vim

Is there an officially supported way to accomplish multiple chained completions? What I mean is that I previously had a setup (with fzy, switching because I prefer the exact-match matching) where I was able to have a keybinding that:

1. fuzzy searched the gems in the current ruby project
1. after one was selected, fuzzy searched the files in that project

Is something like that easily achievable with fzf.vim?

**Comment by junegunn** [comment]
Can you clarify what you mean by "completion"? It usually means typing-aid system in insert mode.

Anyway, if that's not the case, you can achieve it with callback functions.

```vim
function! Foo()
  call fzf#run(fzf#wrap({'source': 'seq 100', 'sink': {line -> Bar(line)}}))
endfunction

function! Bar(line)
  call fzf#run(fzf#wrap({'source': 'seq '.a:line, 'sink': 'echom'}))
endfunction

call Foo()
```

**Comment by jarednorman** [comment]
Sorry, I was just using the wrong word. Your snippet accomplishes what I wanted. Thanks!
