### ISSUE TITLE
request: line delimiter and my bug: glued words

### ISSUE THREAD

**Issue by D1mon** [junegunn/fzf#1276]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [x] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

with the --print0 option, all spaces are cleared and filenames are glued together. Is it possible to do something like this so that at the end of each file name there is a space, **but not at the very last.**?

--print0
/path/file1.mp3/path/file2.mp3

I tried to skip through various programs (tr, sed, ...) but I can not find the ideal solution. That extra space is something else. I did not turn all the lines into quotes (") either. I replaced new-line translations with spaces, and I tried many other things, but I can not achieve what I wanted.

Need:
/path/file1.mp3 /path/file2.mp3 ...
"/path/file1.mp3" "/path/file2.mp3" ...
/path/my\ music/file\[1\]\ -\ \(2018\).mp3 /path/my\ music/file\[2\]\ -\ \(2018\).mp3

mpv $(cat file.txt | fzf -e -m)

files contain:
spaces, [ ], ( ) - which need to be escaped or wrapped in ""

And if there is no such option, then it's not bad to add it. Make it possible to specify any character in which to wrap selected lines.

For example, I chose `"` instead of the standard translation to a new line
"/path/file1.mp3" "/path/file2.mp3"

**Comment by junegunn** [comment]
You might want to write a proper shell function instead of trying to achieve it in a one-liner.

```sh
mkdir /tmp/files
cd /tmp/files
touch "foo" "foo bar" "hello[world]"
readarray -t files < <(fzf -fo)
ls -l "${files[@]}"
```

I believe there are other ways to achieve the same.
