### ISSUE TITLE
Do not modify .bashrc. Do not create ~/.fzf.bash. Or, add option to disable this.

### ISSUE THREAD

**Issue by dsifford** [junegunn/fzf#1277]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [x] Completion
    - [ ] Vim
    - [ ] Neovim
    - [x] Etc.
- OS
    - [x] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

Hello.

Currently, it appears that every time fzf updates, it both creates a `~/.fzf.bash` file and then adds `[ -f ~/.fzf.bash ] && source ~/.fzf.bash` to the user's bashrc file.

Is there any way to disable this?

For users who follow the [XDG Base Directory](https://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html) specification, this creates an issue in that it places files in the wrong locations.

Second, I have the contents of `.fzf.bash` being sourced in different locations that work better for me, so this ends up happening twice.

Please add an option to disable this behavior if it does not already exist.

Thanks for considering.

**Comment by junegunn** [comment]
`./install --bin` will only download the binary and do nothing else. Then you can maintain `.fzf.bash` file manually. The file simply updates `$PATH` and loads two files, so you can consider just putting the lines in your `.bashrc` instead of having them in a separate file.

**Comment by junegunn** [comment]
Also, see `./install --help` for more options.

**Comment by dsifford** [comment]
Also, yeah, this is clearly documented in the `--help` message.

The source of my confusion I think came from the install instructions in fzf.vim not being totally clear on this.

Specifically, this line: https://github.com/junegunn/fzf.vim/blame/master/README.md#L63

To me, that suggests that it would be impossible to use fzf outside of vim, rather than it just doesn't create the files to source it automatically.
