### ISSUE TITLE
fzf dont start up with terminal

### ISSUE THREAD

**Issue by ryanbas21** [junegunn/fzf#1280]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [x ] Etc.
- OS
    - [ ] Linux
    - [ x] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x ] zsh
    - [ ] fish

Is there a way for zsh to not start up on terminal load. I dont always need fzf to pop open when i open a terminal. I havent found in the documentation anything about it.

**Comment by junegunn** [comment]
fzf doesn't automatically start. Sounds like a configuration issue.

**Comment by ryanbas21** [comment]
hmm, very possible, I am a noob.

I am doing

```
export TERM="xterm-256color"
set -o vi
export ZSH=/Users/rbasmajian/.oh-my-zsh
DEFAULT_USER=`whoami`

ZSH_THEME="powerlevel9k/powerlevel9k"
source $ZSH/oh-my-zsh.sh

plugins=(git npm)

source /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source ~/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh

alias ohmyzsh="mate ~/.oh-my-zsh"
export PATH=/usr/local/gnupg-2.1/bin:$PATH

# NVM
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# FZF SETTINGS
rg --type f | fzf

fzf --preview '[[ $(file --mime {}) =~ binary ]] &&
                 echo {} is a binary file ||
                 (highlight -O ansi -l {} ||
                  coderay {} ||
                  rougify {} ||
                  cat {}) 2> /dev/null | head -500'


complete -F _fzf_path_completion -o default -o bashdefault rg
complete -F _fzf_dir_completion -o default -o bashdefault tree

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

```

**Comment by ptzz** [comment]
```
rg --type f | fzf

fzf --preview '[[ $(file --mime {}) =~ binary ]] &&
```

This does not belong in the shell startup script. Not sure what you’re trying to achieve? To configure `fzf` you should set its config environment variables, it’s quite well documented in `README.md`.
