### ISSUE TITLE
fzf bash history issue on macOS

### ISSUE THREAD

**Issue by moonwater** [junegunn/fzf#1281]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [x] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

fzf works fine in many of my linux Box.
But the it doesn't  work under MacOS X after `brew install fzf`
I found the initial script `[ -f ~/.fzf.bash ] && source ~/.fzf.bash` in the .bashrc was not executed.  
the problem solved after I moved `[ -f ~/.fzf.bash ] && source ~/.fzf.bash` into .bash_profile.
the fzf installation script needs to be updated.

**Comment by junegunn** [comment]
See https://github.com/junegunn/fzf/issues/282#issuecomment-116651487

I'll see if I can clarify on that in the installation instruction. Thanks.

**Comment by cemo** [comment]
@junegunn I hit same issue. There is another explanation at here: 

https://github.com/janmoesen/tilde/blob/master/.bashrc

**Comment by sukoy** [comment]
XX XX
