### ISSUE TITLE
echo output from sink

### ISSUE THREAD

**Issue by SevereOverfl0w** [junegunn/fzf#1285]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [X] Neovim
    - [ ] Etc.
- OS
    - [X] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [ ] fish

When I do an `echo` in a sink, the output seems to be lost, taking advantage of lambdas I can show this concisely:

```
:call fzf#run({'source': 'echo hi', 'sink': {a -> execute("echomsg 'foobar >><< ".a."'", "")}})
```

Does add to `:messages`, but any echo that happened immediately flashes off the screen.

**Comment by junegunn** [comment]
Thanks, I can reproduce but unfortunately, I have no idea how to fix it. FYI, regular Vim doesn't have the issue.

**Comment by SevereOverfl0w** [comment]
Potentially this is caused by the approach used by fzf do integrate a terminal. Perhaps it triggers a redraw, where the vim integration does not.

**Comment by LuRsT** [comment]
Hi @SevereOverfl0w, is this still an issue? I tried to reproduce it, but couldn't on neovim.

If it's still a problem, maybe this is a "won't fix" @junegunn? Or maybe you could submit a PR @SevereOverfl0w :)

**Comment by junegunn** [comment]
@LuRsT Thanks for helping with outstanding issues. This is not exactly "wontfix", it's more like "it would be nice to fix this but I just don't know how", so I'm leaving it open, hoping that someone has some clue.

**Comment by SevereOverfl0w** [comment]
I'm still seeing this on neovim 0.4.3.
