### ISSUE TITLE
fd & fzf across a large directory structure delays on fzf exit

### ISSUE THREAD

**Issue by m-fonseca** [junegunn/fzf#1286]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

-->
fzf --version
0.17.3 (390b496)

Not sure if this a problem with fzf or with fd, or ripgrep (but I'm starting to suspect fd and ripgrep).  When I traverse a large directory structure (lets say / ). I get a hangup when using fd or ripgrep, but not with find.
``
: find / 2>/dev/null | fzf
``
and select a file, it returns immediately.  Perfect.

When I do
``
: fd -F "" / 2>/dev/null | fzf
``
and select a file, it will hang, waiting for fd to finish.  The same happens if I use ripgrep.

Thanks.

**Comment by junegunn** [comment]
Explanation can be found in #398. IIRC, ripgrep fixed the issue some time ago, please make sure that you have the latest versions of those programs.
