### ISSUE TITLE
Request: Provide instructions to update to go version (bleeding edge)

### ISSUE THREAD

**Issue by jdevera** [junegunn/fzf#129]
I just realised you have rewritten fzf in go. I'd like to update to the latest in master, but following instructions to set up a go dev environment and so on did not take me anywhere.

I don't write go, but I'm happy to build the tool every time, rather than using the precompiled binary you provide.

I got stuck with what to set as the value of my `GOPATH`. `$HOME/.fzf` does not work.

**Comment by junegunn** [comment]
Have you tried `go get github.com/junegunn/fzf/src/fzf`?
It will clone the repository in your `$GOPATH/src/github.com/fzf`.
