### ISSUE TITLE
Escape sends backspace (or something like that) on tmux

### ISSUE THREAD

**Issue by mrbig033** [junegunn/fzf#1291]
- Category
    - [x] fzf binary

- OS
    - [x] Linux

- Shell
    - [x] bash

[my dotfiles](https://gist.github.com/mrbig033/63fd7f4f51b6a8ae379abae74c52aff2)

Whenever I use the history function (\<c-r\>) on tmux, fzf interprets \<esc\> like what seems to be \<backspace\>. [I use bash in vi-mode](https://gitlab.com/mrbig/dotfiles/blob/master/bash/.inputrc#L18), and [I have my \<esc\> swapped with \<caps_lock\> using xmodmap](https://gitlab.com/mrbig/dotfiles/blob/master/maps/bin/mykeymaps). I tried using `setxkbmap`, but the problem remains. It goes away if I "unswap" the keys.

Here's how it actually looks (I'm pressing \<escape\> when the characters are being deleted):
https://asciinema.org/a/6c1FkIisFJNLnUiKnMRii5j4E

**Comment by LuRsT** [comment]
Hi @mrbig033,

Does this still happen?

**Comment by mrbig033** [comment]
> Hi @mrbig033,
> 
> Does this still happen?

This does not happen anymore, but I cannot say the issue was resolved since my environment is now completely different from what it two years ago.

I won't close the issue myself since I'm not sure what is the etiquette here.

Sorry about that and thank you for answering.

**Comment by LuRsT** [comment]
Hi @mrbig033, maybe it was your environment, maybe it was fzf, but if the issue is solved, please close the PR. Someone else looking for an issue can still find this.
