### ISSUE TITLE
fzf missed one of the default Ctrl-R behavior

### ISSUE THREAD

**Issue by guocb** [junegunn/fzf#1292]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [x] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

Fzf is a good tool. When press ctrl-r, it list recent command history. However, in vanilla bash environment, the ctrl-r behavior is not only search back in history, it also allow us to type a substring in the current command line and move the cursor to the first match.
I hope fzf can continue to keep this feature. In more specific:
1. when current command is empty, press ctrl-r ==> list command history
2. when current command isn't empty, press ctrl-r ==> start to match in the current command line of the string typed later.

**Comment by junegunn** [comment]
The behavior is currently implemented for zsh, but unfortunately, I doubt it's possible with bash. Let me know if you know how to implement the scheme on bash.

**Comment by gertcuykens** [comment]
If I understand correctly you have to put the command line cursor in a bind command to the beginning like so and inject `fzf` ?

vi mode
`bind '"\C-r": "\e0ifzf -- \C-j"'`

default mode
`bind '"\C-r": "\C-afzf -- \C-j"'`

Don't know the raw fzf command how to add the input parameter exactly?

**Comment by relastle** [comment]
This issue can be closed by https://github.com/junegunn/fzf/pull/1886 ?
