### ISSUE TITLE
feature of search in specify path not work in ZSH

### ISSUE THREAD

**Issue by zyf0330** [junegunn/fzf#1295]
https://github.com/junegunn/fzf/blob/62f062ecfa6ae55e3d677e19c2fda60b7cf7c301/shell/completion.zsh#L175

I find that problem is related to `tokens=(${(z)LBUFFER})` of zsh. When I enter `cd /tmp;`, `tokens` is `(cd /tmp ;)`, so `prefix` is not right value.
I add
```
  if [ ${#tokens} -gt 2 ]; then
    tokens[-2]="${tokens[-2]}${tokens[-1]}"
    tokens=(${tokens[0,-2]})
  fi
``` 
to line number 150.

**Comment by junegunn** [comment]
I don't think I follow you. Can you provide the exact steps to reproduce the problem you experience?

**Comment by zyf0330** [comment]
I use zsh.
When I am at `$HOME`, and want to search `/tmp`, I enter this `ls /tmp**<TAB>` and it doesn't work.
I inspect code, and think this feature should be supported. So I fix it with above code.

**Comment by zyf0330** [comment]
Sorry, I just ignored my specified `FZF_COMPLETION_TRIGGER`. I use `;`, and `(${(z)LBUFFER})` will split `;` by space. `**` won't be.
That fix is not proper, I will update.

**Comment by zyf0330** [comment]
I have issue a new PR
