### ISSUE TITLE
**<TAB> does not list all matches

### ISSUE THREAD

**Issue by ptzz** [junegunn/fzf#1301]
- Category
    - [x] Completion
- OS
    - [x] Mac OS X
- Shell
    - [x] bash

Given the following hierarchy
```
├── foo
│   ├── baz
│   └── qux
└── foobar
```
`cat foo**<TAB>` only shows `foo`, `foo/baz` and `foo/qux`. I would expect `foobar` to be included as well.

If I instead do `cat fo**<TAB>`, all four matches are listed.

I guess the problem has something to do with `foo` being identified as the target directory in the first case, hence `foobar` being excluded?

**Comment by junegunn** [comment]
> I guess the problem has something to do with foo being identified as the target directory in the first case, hence foobar being excluded?

Correct.
