### ISSUE TITLE
Ctrl-T not working while other key bindings work

### ISSUE THREAD

**Issue by RidaAyed** [junegunn/fzf#1306]
# Ctrl-T not working while other key bindings work

- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [x] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

Hi

While the other commands work I can't figure out how to enable the `ctrl-t`?

.bashrc:  

```bash
[ -f /usr/share/fzf/key-bindings.bash ] && source /usr/share/fzf/key-bindings.bash
export FZF_DEFAULT_COMMAND='rg --files --no-ignore --follow -g "!{.git,node_modules}/*" 2> /dev/null'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
bind -x '"\C-p": vim $(fzf);'
```

**Comment by deepredsky** [comment]
most likely ur bindings are overwritten. Similar issue https://github.com/junegunn/fzf/issues/1304

check if you have correct binding in ur shell 

you should see something like this. if not there is a binding problem.

```
bind -X | grep fzf
"\C-t": "fzf-file-widget"
```

**Comment by RidaAyed** [comment]
@deepredsky :1st_place_medal: Another binding was overwriting the command

**Comment by Norfeldt** [comment]
On mac this did the trick: 

```
 "terminal.integrated.allowChords": false,
```


https://code.visualstudio.com/docs/editor/integrated-terminal#_chord-keybindings-in-the-terminal
