### ISSUE TITLE
{q} truncated

### ISSUE THREAD

**Issue by henkye** [junegunn/fzf#1310]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

```
echo 'aaa
bbb' | fzf --bind 'change:execute(echo {q} > /tmp/l)'
```
and type in:
dsfdsf

/tmp/l  will not contain same string. It somehow truncates {q}. Results may vary depending if typed text matches or not item in list

Anyway, very, very nice SW. Such a joy using it! Thanks for sharing.

**Comment by LuRsT** [comment]
Hi @henkye, I can't reproduce the issue, I'm guessing by now it has been fixed, do you still have this problem? If not could you close this issue?

**Comment by henkye** [comment]
Hi, yes, it's OK now. My fzf version: 0.20.0
Thanks.
