### ISSUE TITLE
canot show directory

### ISSUE THREAD

**Issue by imtianx** [junegunn/fzf#1311]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

When I using fzf ,it can only search some files,not showing folders. If I enter a directory under the terminal using fzf,it can only search the files under this directory,and canot show some folders or others files.

Thanks for giving help ！

**Comment by junegunn** [comment]
If you start fzf without explicit standard input source, it will start the default find command for listing files but not directories. I suggest that you read through the documentation, README page and `man fzf` to learn how to use fzf properly.
