### ISSUE TITLE
No max length limit of --query or multiple line layout support

### ISSUE THREAD

**Issue by statfs** [junegunn/fzf#1312]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

It seems that the --query switch can pass a very long content, but it will be truncated. 
The interactive query length also limited by the terminal/window size.
So if it can be a solution with multiple line layout support for the query?

**Comment by junegunn** [comment]
I don't think it's worth the effort. What would be the point of allowing exceptionally long query strings? Also, the time complexity of the search algorithm of fzf is proportional to the length of the query, so having some limit makes sense in that regard as well.

**Comment by statfs** [comment]
this is my scenario,  I'm using cmux (https://github.com/kakao/cmux) to operation a huge cluster, which filter the node by fzf.   
The cluster  consist of 2000 machines, when I need filter 3 nodes out of them by hostname, it is very easy by a query "node111 | node293 | node123 ".  But it's very hard to filter more than 10 nodes because the length limit of query. 
A long query will effect the search efficiency indeed, but my case is:  to accurately describe a result set from condicates, the length limit of query may be a little bigger.
Thank you very much.

**Comment by junegunn** [comment]
Interesting, thanks for the clarification. I think I'm going to make the query prompt horizontally scrollable, so that longer queries can be typed in. But I'm still going to put some limit on the maximum length of a query. How long do you think your query will grow? Is 300-char limit enough?

**Comment by statfs** [comment]
@junegunn can we just provide a switch to set the maximum length of a query, 300 char works at most of times, but it should have the ability to work at 3000 or 30000.
Thank you.

**Comment by junegunn** [comment]
Can you describe what you're trying to achieve with such a long query on tmux in detail? Typing in tens or hundreds of hostnames doesn't sound like an elegant solution. I happen to be one of the maintainers of cmux, so if your use case sounds valid, I can consider adding features to cmux that might allow you to achieve the same without having to type in such a long query string on fzf prompt.

**Comment by statfs** [comment]
@junegunn My case is rolling restart hundreds or thousands roles(like datanode, nodemanager). I just add a switch for rolling restart just like 

> cmux rrr -q "node111 | node293 | node123"

Then I can restart these roles without typing and choosing, and the query contains a lot hostnames which are not easy to describe by regex. The query are generated by a script. 
So I just want restart a lot roles from command, in non-interactive way.
Thank you for your patience.

**Comment by junegunn** [comment]
I see. I'll discuss the issue with the main author of cmux.
