### ISSUE TITLE
using fzf for bash 'read -p'

### ISSUE THREAD

**Issue by albasili** [junegunn/fzf#1313]
I am wondering whether it is possible to 'plug' fzf into a bash 'read -p' instruction. My basic idea is that when a scripts requests for user input I'd like to use fzf for fast completion based on a list of potential entries (like a list of labels, addresses, whatever ...).

Would that be possible?

**Comment by DanielFGray** [comment]
Not with `read -p` directly, but you could get by with `fzf --print-query`
