### ISSUE TITLE
When installed through homebrew documentation for vim does not exist

### ISSUE THREAD

**Issue by dylan-chong** [junegunn/fzf#1318]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [x] Vim
    - [x] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

Installed throgh homebrew and then added  `set rtp+=/usr/local/opt/fzf` to vimrc

the doc folder does not exist in the location installed through homebrew. Therefore running `h fzf` inside Vim does not find any documentation

**Comment by deepredsky** [comment]
you probably want to install https://github.com/junegunn/fzf.vim which is a wrapper around fzf and has docs for vim

**Comment by junegunn** [comment]
Please send a pull request to https://github.com/homebrew/homebrew-core/ if you're interested in contributing.
