### ISSUE TITLE
Selecting (or quitting) from Ctrl-R deletes previous line of multiline Zsh prompt

### ISSUE THREAD

**Issue by henrebotha** [junegunn/fzf#1322]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

In Zsh 5.5.1, if I use <kbd>Ctrl</kbd><kbd>R</kbd>, accepting a search result (or quitting the prompt with <kbd>Ctrl</kbd><kbd>C</kbd>) deletes the previous line of my two-line prompt. Please see this recording for a demonstration: https://asciinema.org/a/oYDK7jNv3oOUbT7D7P4NDWvLv

I know [there's currently an issue with oh-my-zsh's `COMPLETION_WAITING_DOTS`](https://github.com/robbyrussell/oh-my-zsh/issues/5765), possibly only on macOS, that results in similar line-eating behaviour whenever tab completion is used. Perhaps fzf is doing something similar here?

**Comment by vbauerster** [comment]
I use [prezto](https://github.com/sorin-ionescu/prezto) with [pure](https://github.com/sindresorhus/pure) prompt and so far have no such issue on macOS.

**Comment by henrebotha** [comment]
That's a good point, I should have given more information. I was on oh-my-zsh `6af58f49`. I have now upgraded to `547a6ce2` and the error is gone.

For historical purposes, [my prompt can be seen here](https://github.com/henrebotha/dotfiles/blob/master/henrebotha.zsh-theme).
