### ISSUE TITLE
FZF keybindings for git question

### ISSUE THREAD

**Issue by yevhen-m** [junegunn/fzf#1330]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [x] Etc.
- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

I just have a question and I don't know a better place where I can ask it, so putting it here. I have a snippet that I guess belongs to you:
```
# Browse git commits
fzf-show() {
    is_in_git_repo || return
    git log --color=always \
        --format="%Cred%h%Creset %Cgreen(%cr)%Creset %C(bold blue)<%an>%Creset %s" "$@" |
    fzf-down --height 100% --ansi --no-sort --reverse --tiebreak=index --bind=ctrl-s:toggle-sort \
        --bind "ctrl-m:execute:
    (grep -o '[a-f0-9]\{7\}' | head -1 |
    xargs -I % sh -c 'git show --color=always % | diff-so-fancy | less --tabs=4 -RX') << 'FZF-EOF'
    {}
    FZF-EOF"
}
bindkey -s '^g^l' 'fzf-show\n'
```
Can you please explain how the `execute` part works here and why do we need `head -1` (I can see that FZF-EOF gets through to less and we want to strip it, but I don't understand why).

**Comment by junegunn** [comment]
A line may contain multiple matches, so we use `head -1`.
```sh
echo foo hello foo | grep -o foo
```

**Comment by yevhen-m** [comment]
@junegunn thanks!
