### ISSUE TITLE
Option to reset position in the list after query line changes

### ISSUE THREAD

**Issue by Bellaktris** [junegunn/fzf#1331]
Hi,

Sometimes when I use fzf I first move around the list, and then decide to add few more characters. Currently cursor stays at the same line (relatively to the start of the list) which is little awkward as the lines have changed. I would expect cursor to restart to the start of the list after any character addition/deletion. Is there any way to configure fzf to behave this way? Or would it be possible to support such an option?

**Comment by junegunn** [comment]
You can bind `top` action to `change` event as follows:

```sh
fzf --bind change:top
```

See https://github.com/junegunn/fzf/blob/master/man/man1/fzf.1#L512-L515

**Comment by Bellaktris** [comment]
Thank you. Not sure how I missed this.
