### ISSUE TITLE
Is it possible to have fzf complete environmental (shell) variables?

### ISSUE THREAD

**Issue by lukelbd** [junegunn/fzf#1332]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [x] Completion
    - [ ] Vim
    - [ ] Neovim
- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

Simple question: Is it possible to have fzf complete environmental (shell) variables when tab-completing a word preceded with the dollar sign `$`? Currently I have fzf completion enabled all the time by setting `FZF_COMPLETION_TRIGGER=''`, but this messes up the default shell variable completion at times.

**Comment by junegunn** [comment]
Probably not possible with the current implementation because it expands the current line to resolve `$ENVVAR`s and `~` expressions. For example, for `vim $HOME**<tab>`, it is designed to find files inside `$HOME` directory instead of searching for environment variables that start with `HOME`.
