### ISSUE TITLE
Warning: Output is not to a terminal

### ISSUE THREAD

**Issue by klassegeljakt** [junegunn/fzf#1333]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

I'm trying to assign assign the resulting file of fzf while also having a keybinding to edit the file in Vim.
```
RESULT=$(fzf --bind="ctrl-o:execute(vim {} < /dev/tty)")
```
The problem is that when I press `ctrl-o`, I get `Vim: Warning: Output is not to a terminal`. Is there a way to solve this?

**Comment by junegunn** [comment]
Try `vim {} < /dev/tty > /dev/tty`

**Comment by klassegeljakt** [comment]
Thanks, it works!
