### ISSUE TITLE
Suggestion: Optionally preserve colors of match in {}

### ISSUE THREAD

**Issue by klassegeljakt** [junegunn/fzf#1335]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

I think it could be useful if there was an option to output `{}` in ANSI. For example, I'm using fzf to with ripgrep to search files for strings. The preview window then highlights the matching line. If output in ANSI, I'd also be able to highlight the specific matching characters.

![img](https://i.imgur.com/kduQaw1.png)

**Comment by junegunn** [comment]
Thanks for the suggestion, but I'm going to pass on this one as it's strictly a niche feature and I don't think I'm going to need it.
