### ISSUE TITLE
Preview window

### ISSUE THREAD

**Issue by Bmsandoval** [junegunn/fzf#1337]
- Category
    - [ x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x ] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ x] bash
    - [ ] zsh
    - [ ] fish

 Admittedly the usecase is minimal... but "--preview 'declare -f {}'" gives undesired results if it is passed a bash function that is not in the bashrc (even if the bashrc sources the other file). It seems to be because fzf runs these in a non-login shell. This would be convenient for editing bash functions by allowing you to search for all your bash functions and then display the bash code in the preview window.

**Comment by junegunn** [comment]
Bash functions are not visible to child processes if you don't explicitly export them.
 
```sh
> foo() { echo foo; }
> declare -f foo
foo ()
{
    echo foo
}
> bash -c 'declare -f foo'
> export -f foo
> bash -c 'declare -f foo'
foo ()
{
    echo foo
}
```

**Comment by junegunn** [comment]
Or you can load your configuration files in preview command

```sh
fzf --preview 'source ~/.bashrc; declare -f {}'
```

**Comment by klassegeljakt** [comment]
How can one do this in ZSH?

**Comment by atusy** [comment]
With the trick of https://github.com/junegunn/fzf/issues/1337#issuecomment-407604686,
I come up with a way to call the internal function by `--preview`.

```bashfunction preview() {
function preview() {
  echo $1
}

export -f preview
fzf --preview 'bash -c "preview {}"'
```

**Comment by danielbisar** [comment]
you can just use 

> fzf --preview 'bash -c "preview {}"'

can be simplified:

`fzf --preview='preview {}'`

and it even works if `export -f preview` is placed in a sourced script.

**Comment by Shuraken007** [comment]
I want to show example, which works for both bash and zsh, also arguments are sending.

I use some variable to ignore folders for exa https://github.com/ogham/exa
```bash
export EXA_IGNORE='-I ".git|.vscode"'
export EXA_IGNORE_ESC=${EXA_IGNORE//\"/\\\"} # -I \".git|.vscode\"
```


file fzf_preview
```bash
function preview_dir() {
   dir="$1"
   exa_ignore="$2"
   exa "$dir" \
      --tree \
      --icons \
      --group-directories-first \
      --all \
      $exa_ignore \
      | 
   less
}

function alt_c_preview() {
   dir="$1"
   exa_ignore="$2"
   preview_dir "$dir" "$exa_ignore"
}

[[ $0 =~ "bash" ]] && export -f alt_c_preview

```

export -f works only for bash, not zsh

file fzf
```bash

PREVIEW="$DDIR/sh_common/fzf_preview"

export_folder_alt_c_search() {
   export FZF_ALT_C_COMMAND=' fd --type d . --color=never --hidden'
   export FZF_ALT_C_OPTS="
   --preview \"source '$PREVIEW'; alt_c_preview '{}' '$EXA_IGNORE_ESC'\"
   --bind \"ctrl-o:execute(fd --full-path {+} --type f --color=never --hidden | fzf)\"
   "
}
```
