### ISSUE TITLE
Tiebreak option: complete match on (specific) field

### ISSUE THREAD

**Issue by stefanwascoding** [junegunn/fzf#1338]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [x] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.

I have a suggestion / feature request: an option for the tiebreak argument so that when there is a complete match in a specific field that the entry gets ranked higher.
Use case: better control over the order;  in my case for a `brew-lookup` method:

For example when looking for *zsh* I would like for the direct match to come first, but when I use `--tiebreak=begin`, I get:
<img width="687" alt="begin" src="https://user-images.githubusercontent.com/2292035/43111455-a7768894-8ef1-11e8-95a2-76ef0c14c213.png">

and `begin,length` gives me:
<img width="695" alt="begin length" src="https://user-images.githubusercontent.com/2292035/43111454-a759fec2-8ef1-11e8-8bd6-02547eb85966.png">

Neither is exactly what I want. Ideally fzf would see the complete match in the first (visible) field, and show the `zsh` entry first.

**Comment by stefanwascoding** [comment]
Used command is:
```shell
LC_ALL=C ggrep -rE --max-count=1 --include='*.rb' '\b(desc|name)\b' /usr/local/Homebrew/Library/Taps/**/(Casks|Formula)(/) | perl -ne 'm{^(.*/)?(.*?)\.rb.*?['"'"'"](.*)['"'"'"]$} and print "$1|$2|$3\n"' | column -t -s '|' | fzf --layout=reverse --with-nth=2.. --bind change:top --preview 'echo {3..}"\n"{2}' --preview-window down:2:hidden --bind "?":toggle-preview --tiebreak=begin,length --no-hscroll --multi --exit-0 --query="zsh"
```
(`ggrep` is the GNU grep utitlity from homebrew)

Or as download:
[brew-lookup.zip](https://github.com/junegunn/fzf/files/2221619/brew-lookup.zip)

**Comment by junegunn** [comment]
Thanks for the suggestion but I don't have plans to add more sophisticated options to fzf for the time being. In this particular case, I suggest that you pre-sort the input and use `--tiebreak index` to get the desired behavior. For example,

```sh
(sort -k 1 | fzf --reverse --tiebreak index) << EOF
zsh-foo   bar
zsh       barrr
EOF
```
