### ISSUE TITLE
Scroll preview window left and right for long lines

### ISSUE THREAD

**Issue by ym1234** [junegunn/fzf#1339]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [x] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [x] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

Would it be possible to add a preview left and preview right commands for scrolling long lines without using wrap?

**Comment by junegunn** [comment]
No. It's not trivial to implement the feature so I'm not interested in implementing it.
