### ISSUE TITLE
Replace ALL zsh auto completion with fzf

### ISSUE THREAD

**Issue by vitalybe** [junegunn/fzf#1340]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [X] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [X] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [X] zsh
    - [ ] fish

Would it be possible to have fzf completely replace zsh tab completion? At the lowest level. I don't want to configure fzf per command, e.g just for `cd` and `docker` etc - Just replace all tab completion with it.

**Comment by dasl-** [comment]
@junegunn is this possible?

**Comment by Aloxaf** [comment]
Yes it is possible, I have started a project several days ago: https://github.com/Aloxaf/fzf-tab
It hooks zsh's low level function of completion system to capture the completion list, so it works everywhere!

![](http://storage.aloxaf.cn/fzf-tab.gif?v=2)
