### ISSUE TITLE
FR: preview() action

### ISSUE THREAD

**Issue by cpriest** [junegunn/fzf#1342]
1st, Thank you!
    - [X] Etc.
    - [X] Linux
    - [X] zsh

Describe your problem or suggestion from here ...

Would it be possible to have a preview() action, like execute().

**Comment by super-cooper** [comment]
If you mean a way to change the `--preview` flag, I would also like to see this implemented :)

**Comment by junegunn** [comment]
Added in 0.22.0.

https://github.com/junegunn/fzf/blob/master/CHANGELOG.md#0220

**Comment by cpriest** [comment]
Thank you!
