### ISSUE TITLE
256 color seems not support on windows

### ISSUE THREAD

**Issue by hulucc** [junegunn/fzf#1344]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [ ] Mac OS X
    - [x] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [ ] fish
    - [x] cmd

This is the red color schema on wiki looks like on win10.
Also I tried the same operation on mac, it just works fine.

![20180731173850](https://user-images.githubusercontent.com/4343900/43451904-9d95642e-94e8-11e8-91fa-0b296db34d25.png)

`dir /s/b | fzf --color=fg:124,bg:16,hl:202,fg+:214,bg+:52,hl+:231,info:52,prompt:196,spinner:208,pointer:196,marker:208`

**Comment by janlazo** [comment]
256-color support is WIP in https://github.com/junegunn/fzf/pull/1341

**Comment by hulucc** [comment]
thank u!
