### ISSUE TITLE
replace -q ... with -- ...

### ISSUE THREAD

**Issue by gertcuykens** [junegunn/fzf#1347]
To be able to press `\C-r` on already typed input on the bash command line `--` would be better to be able to bind. Example https://github.com/dvorka/hstr does this also to solve this problem. Note that a empty input shouldn't result in error like -q does but just open search

bash vi mode
`bind '"\C-r": "\e0ihistory | fzf -q \C-j"'`

bash default
`bind '"\C-r": "\C-ahistory | fzf -q \C-j"'`

ref: https://github.com/junegunn/fzf/issues/1292

**Comment by junegunn** [comment]
Interesting approach. One problem is that it does not work with multi-line command. The current implementation doesn't handle the case nicely either but at least fzf starts and the user is not exposed to some broken command string.
