### ISSUE TITLE
Accessing zsh functions inside preview window

### ISSUE THREAD

**Issue by klassegeljakt** [junegunn/fzf#1348]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

I'm trying to run `zsh` functions inside of the preview window. The code from #1337 only appears to work in `bash`.

```zsh
> foo() { echo foo; }
> declare -f foo
foo ()
{
    echo foo
}
> bash -c 'declare -f foo'
> export -f foo
> bash -c 'declare -f foo'
foo ()
{
    echo foo
}
```

Is there possibly a workaround?

**Comment by junegunn** [comment]
I'm not a zsh user so I don't think I can give you a good answer. You need to find out how to export zsh function to its child process, or just source your zsh configuration file that contains the definition of the function similarly to what I suggested here: https://github.com/junegunn/fzf/issues/1337#issuecomment-407605331

**Comment by Shuraken007** [comment]
I want to show example, which works for both bash and zsh, also arguments are sending.

I use some variable to ignore folders for exa https://github.com/ogham/exa
```bash
export EXA_IGNORE='-I ".git|.vscode"'
export EXA_IGNORE_ESC=${EXA_IGNORE//\"/\\\"} # -I \".git|.vscode\"
```


file fzf_preview
```bash
function preview_dir() {
   dir="$1"
   exa_ignore="$2"
   exa "$dir" \
      --tree \
      --icons \
      --group-directories-first \
      --all \
      $exa_ignore \
      | 
   less
}

function alt_c_preview() {
   dir="$1"
   exa_ignore="$2"
   preview_dir "$dir" "$exa_ignore"
}

[[ $0 =~ "bash" ]] && export -f alt_c_preview

```

export -f works only for bash, not zsh

file fzf
```bash

PREVIEW="$DDIR/sh_common/fzf_preview"

export_folder_alt_c_search() {
   export FZF_ALT_C_COMMAND=' fd --type d . --color=never --hidden'
   export FZF_ALT_C_OPTS="
   --preview \"source '$PREVIEW'; alt_c_preview '{}' '$EXA_IGNORE_ESC'\"
   --bind \"ctrl-o:execute(fd --full-path {+} --type f --color=never --hidden | fzf)\"
   "
}
```
