### ISSUE TITLE
Repeating arrow key can occasionally cause fzf to exit prematurely 

### ISSUE THREAD

**Issue by kelleyma49** [junegunn/fzf#1349]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [x] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [ ] fish

Run `fzf` with the `--height` option.

Pressing and holding the arrow keys while fzf is processing is still processing input can cause fzf to exit prematurely.

**Comment by kelleyma49** [comment]
This issue can be seen more under the Windows version with the `--height` option from a forthcoming commit.

**Comment by junegunn** [comment]
Merged, thanks.
