### ISSUE TITLE
Directory commands bash completion behaves like files

### ISSUE THREAD

**Issue by vexplore** [junegunn/fzf#135]
The fzf-completion.bash adds completion to many standard directory commands including cd. But the completion behaves like files: it adds a space instead of a /, which prevent me from keeping tab complete a long path.

The fix is easy: add -o plusdirs for the complete commands for directory commands.

**Comment by junegunn** [comment]
Good point. I'll see what I can do.

**Comment by junegunn** [comment]
Should be fixed now. Let me know if it doesn't work as expected. Thanks.
