### ISSUE TITLE
pure directory only key binding command line completion

### ISSUE THREAD

**Issue by boulderob** [junegunn/fzf#1352]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [x] Key bindings
    - [x] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

I love how fzf provides *both* filename and path completion from anywhere on the command line via CTL-T.

however, it doesn't appear that you have a combined bind map plus function to provide *only* directory completion though.  for instance if i'm moving lots of files to lots of different directories, i would like to be able to type "mv_" followed by "CTL+t" (to insert the file(s) to move), followed by typing " CTL+D" (to insert *just* the target move directory).    i know  i could just use CTL+t two times, BUT i'm working with thousands of files and hundreds and directories at a time.. and it's hard to even remember what to search for at times.  i often only have about 10-20 target directories i want to move the files to in the current directory though.  so if i had a separate CTL+D fzf map that used only "find -type d" as input, i could easily see my directory targets much easier (and cutting down on brain drain) vs trying to search through full list of files *and* dirs using CTL+T.  i hope that makes sense.   basically it would be a great productivity boost to simply have a pure directory CTL+D (or similar) map (since CTL +D is probabaly already used). 

currently ALT+C does most of what i want but unfortunately it's hard coded as a bash 'cd' command.  basically, i'd like to duplicate the functionality in my local .fzfrc file but with a different mapping and no "cd".  so this is probably just a customization for my own dotfiles though i think the functionality would be useful for others as well.

any thoughts on best way to implement this

thx

**Comment by davidsierradz** [comment]
Something like (this includes hidden directories) but for ZSH, I don't know how to use it in BASH (reuse the __fseldir() function?):

```zsh
# ALT-D - Paste the selected directory path into the command line
__fseldir() {
    local cmd="command find -L . -mindepth 1 \\( -path '*/\\\.*' -o -fstype 'sysfs' -o -fstype 'devfs' -o -fstype 'devtmpfs' -o -fstype 'proc' \\) -prune \
        -o -type d -print 2> /dev/null | cut -b3-"
    setopt localoptions pipefail 2> /dev/null
    eval "$cmd" | FZF_DEFAULT_OPTS="--height ${FZF_TMUX_HEIGHT:-40%} --reverse $FZF_DEFAULT_OPTS $FZF_ALT_C_OPTS" $(__fzfcmd) -m "$@" | while read item; do
    echo -n "${(q)item} "
done
local ret=$?
echo
}

fzf-search-dir-widget() {
LBUFFER="${LBUFFER}$(__fseldir)"
local ret=$?
zle reset-prompt
return $ret
}

zle     -N   fzf-search-dir-widget
bindkey '\ed' fzf-search-dir-widget
```
