### ISSUE TITLE
Unable to map ctrl-_

### ISSUE THREAD

**Issue by natechan** [junegunn/fzf#1353]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [x] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [x] fish

Would it be possible to add support for binding ctrl-_?

When I try, I see
```
> env FZF_DEFAULT_OPTS='--bind=ctrl-_:abort' fzf
unsupported key: ctrl-_
```

Related issue: https://github.com/junegunn/fzf/issues/825

**Comment by dlee** [comment]
I'd like support for `alt--` (AltMinus) and `alt-\` (AltBackslash) as well.

**Comment by viniciusmiradouro** [comment]
Support for ctrl+bspace would be grat too.

**Comment by junegunn** [comment]
https://github.com/junegunn/fzf/commit/168453da71af199a76279b9d4017ad1f72ba1f26
