### ISSUE TITLE
Change directory has stopped working

### ISSUE THREAD

**Issue by dtcyganok** [junegunn/fzf#1356]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [x] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [ ] fish

I use a custom command to quickly access the NERDTree bookmarks. But after the last commit "[vim] Clear temporary window-local working directory" global directory change does not work.

My command looks like this:

```vim
let g:NERDTreeChDirMode = 1
command! -nargs=1 -complete=dir Nc NERDTree <args> | wincmd p
command! Bookmarks call fzf#run(fzf#wrap('Bookmarks', {'options': ['--prompt', 'Bookmark> '], 'source': 'cut -sd" " -f1 ' . g:NERDTreeBookmarksFile, 'sink': 'Nc'}))
```

**Comment by junegunn** [comment]
I don't use NERDTree bookmarks, so I had to change it a bit.

```vim
let g:NERDTreeChDirMode = 1
command! -nargs=1 -complete=dir Nc NERDTree <args> | wincmd p
command! Bookmarks call fzf#run(fzf#wrap({'source': 'find ~ -type d', 'sink': 'Nc'}))
```

And it works for me as expected. Can you check again?

**Comment by dtcyganok** [comment]
It's not working for me. The global directory remains the same. But thanks anyway!

**Comment by junegunn** [comment]
```vim
set nocompatible hidden laststatus=2

if !filereadable('/tmp/plug.vim')
  silent !curl --insecure -fLo /tmp/plug.vim
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
endif

source /tmp/plug.vim
call plug#begin('/tmp/plugged')
Plug 'junegunn/fzf', { 'do': './install --bin' }
Plug 'junegunn/fzf.vim'
Plug 'scrooloose/nerdtree'
call plug#end()

let g:NERDTreeChDirMode = 1
autocmd VimEnter * PlugClean! | PlugUpdate --sync
command! -nargs=1 -complete=dir Nc NERDTree <args> | wincmd p
command! Bookmarks call fzf#run(fzf#wrap({'source': 'find ~ -type d', 'sink': 'Nc'}))
```

I tested with this minimal vimrc.

**Comment by khalidchawtany** [comment]
The following does not work
```vim
  let g:projects = [
        \ "~/Projects/PHP/Knights/",
        \ "~/Projects/React/koga/",
        \ "~/Projects/PHP/koga/"
        \]
  command! -nargs=? CdP :cd <args>
  nnoremap <c-p><c-\> :call fzf#run({"source": g:projects , "sink":"CdP"})<cr>

```

**Comment by junegunn** [comment]
I realized that the problem is only reproducible on Neovim, works fine on Vim 8. I'll look into it when I have some time.

**Comment by junegunn** [comment]
Alright, can you guys check if 8c6fcee fixes your problems?

**Comment by dtcyganok** [comment]
The last commit fixes the problem.
