### ISSUE TITLE
Help with fuzzy completion

### ISSUE THREAD

**Issue by sn0wyfall** [junegunn/fzf#1357]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [x] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [x] ~~Mac OS X~~ macOS
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

So, I would like fuzzy completion have this behavior: instead of writing 

    convert Figure4.png

I would want to type 

    convert fig4 <TAB>

and have it expand to the above.

Is this possible?

**Comment by junegunn** [comment]
Have you read https://github.com/junegunn/fzf#fuzzy-completion-for-bash-and-zsh?

**Comment by sn0wyfall** [comment]
@junegunn Yeah... unfortunately I was not able to understand it at all. I'm sorry, I'm not extremely experienced with the Terminal and bash/zsh in general
