### ISSUE TITLE
Line numbers missing after piping `rg` output to `fzf`

### ISSUE THREAD

**Issue by sh78** [junegunn/fzf#1358]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [x] Mac OS X
    - ~[ ] Windows~
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [x] fish

Hey @junegunn 👋

I'm getting some strange results while sending output from ripgrep into `fzf` from the shell. Once I get to the fuzzy finding screen, the line numbers from `rg` disappear. Here's a demo:

[![asciicast](https://asciinema.org/a/30IxBBxDilV6YwOziP0gXcsp0.png)](https://asciinema.org/a/30IxBBxDilV6YwOziP0gXcsp0)

This happens inside/outside of tmux in both bash and fish. 

The goal here is to grep for a pattern across all files, and then parse the output line from `rg`  to create a command like `nvim .vim/user/plugin-settings.vim +32` which would jump to line 32 of the selected match upon opening Vim.

Here is my fzf default command:

```fish
set -gx FZF_DEFAULT_COMMAND 'rg --files --hidden --follow --glob "!{.git,.svn,node_modules,bower_components}"'
```

And the commands/output:

```shell
[I] sean at temas in ~/D/dotfiles (master|✚4…1)
> rg --no-heading --hidden goyo
.vim/user/plugins.vim:111:Plug 'junegunn/goyo.vim'
.vim/user/plugin-vundle.vim:115:Plugin 'junegunn/goyo.vim'
.vim/user/plugin-settings.vim:30:let g:goyo_width = 80
.vim/user/plugin-settings.vim:31:let g:goyo_margin_top = 3
.vim/user/plugin-settings.vim:32:let g:goyo_margin_bottom = 3
.vim/user/plugin-settings.vim:34:function! s:goyo_enter()
.vim/user/plugin-settings.vim:44:function! s:goyo_leave()
.vim/user/plugin-settings.vim:58:autocmd! User GoyoEnter call <SID>goyo_enter()
.vim/user/plugin-settings.vim:59:autocmd! User GoyoLeave call <SID>goyo_leave()
[I] sean at temas in ~/D/dotfiles (master|✚4…1)
> rg --no-heading --hidden goyo | fzf
.vim/user/plugin-settings.vim:let g:goyo_margin_bottom = 3
[I] sean at temas in ~/D/dotfiles (master|✚4…1)
>
```

**Comment by junegunn** [comment]
I suggest that you read the documentation of ripgrep because this is really not an issue of fzf. You'll see the same result when you pipe it into simple `| cat`. (hint: `--vimgrep`)
