### ISSUE TITLE
History size is stuck at 1,000 even changing the option

### ISSUE THREAD

**Issue by minjang** [junegunn/fzf#1359]
- Category
    - [x] fzf binary
    - [x] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

- Make sure that you have the latest version of fzf: **Yes, latest version**
- If you use tmux, make sure $TERM starts with "screen": **screen-256color**

On my Linux server (centos-release-7-5.1804.el7.centos.2.x86_64), Ctrl + R shows a bit wrong behavior.

I found out that history can only back to 1,000, which is the default value. On my Mac, it goes to the very oldest one, which is more than 10,000. I didn't touch any default options on both machines.

So I tried this on my Linux:

```
export FZF_DEFAULT_OPTS='--history-size=50000 --height=30% '
```

I also added `--height` to make it sure `FZF_DEFAULT_OPTS` is working.

When I hit ctrl + r, the height now becomes 30%, so the default option environment variable works. But I can't still go back beyond 1,000 histories. Still it is limited to 1,000.

I'm wondering how I can resolve this issue.

**Comment by junegunn** [comment]
fzf keeps track of the search keywords you type inside fzf finder when `--history=FILE` is set, and `--history-size` is for putting a limit on the size of the file. So it's unrelated to the command history your shell provides to fzf.

```sh
# This is what happens when you hit CTRL-R on zsh
fc -rl 1 | fzf

# Being a general-purpose text filter, fzf does not provide options for specific types of input.
# We would use an additional filter if we wanted to limit the size of the input.
fc -rl 1 | head -100 | fzf
```

So you need to find a set of zsh options for increasing the size of the command history.

https://unix.stackexchange.com/questions/273861/unlimited-history-in-zsh

Also note that there is `FZF_CTRL_R_OPTS` that is only used by CTRL-R implemenation.

https://github.com/junegunn/fzf#key-bindings-for-command-line
