### ISSUE TITLE
Vim: Warning: Input is not from a terminal

### ISSUE THREAD

**Issue by aranmohyeddin** [junegunn/fzf#1361]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [x] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

I run fzf like this:
`fd a | fzf --height 40% --reverse --bind 'ctrl-o:execute(rifle -- {})+abort,ctrl-y:execute-silent(echo -n {} | xclip -selection clipboard)+abort'`
and then I select a .py file and press ^o 
rifle is something like xdg-open
so then vim opens the file for me but before it does it warns me that input is not from terminal, iirc that warning is for when you pass standard input to vim without - 
but It doesn't seem like I'm doing that!
if I directly do `rifle <that file>`
vim opens the file normally.

Why am I getting that warning?

**Comment by junegunn** [comment]
Have you tried overriding the stdin of the process?

```sh
fzf --bind 'ctrl-v:execute(vim {} < /dev/tty)'
```

**Comment by aranmohyeddin** [comment]
problem solved:D thanks!
