### ISSUE TITLE
FAQ - Use vim/nvim/nano as preview

### ISSUE THREAD

**Issue by PombaM** [junegunn/fzf#1362]
- Category
    - [x] fzf binary
    - [x] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [x] Vim
    - [x] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

I'm trying to pipe files to fzf and view the contents in a preview window inside vim/nvim/nano etc.

While `cat` works perfectly eg:
```bash
find * -type f | fzf-tmux --reverse -d 100 --preview 'cat {}' 
```

However using `vim/nvim/nano` doesn't work.

```bash
find * -type f | fzf-tmux --reverse -d 100 --preview 'nvim {}' 
```

Example:
https://drive.google.com/file/d/1Z66KfWHCPKw0C23mmnn-WwsPqvCT456M/view?usp=sharing

Am i missing something obvious? Any help is greatly appreciated.

**Comment by junegunn** [comment]
fzf is not a terminal multiplexor and you can't use an interactive process as the preview command. Also, the command should finish quickly as the preview window is updated only when the process completes.

You can still make fzf launch vim or an interactive editor by binding a key to `execute` action as follows:

```sh
fzf --preview 'head -100 {}' --bind 'ctrl-v:execute(vim {} < /dev/tty)'
```

**Comment by MeritonAliu** [comment]
> fzf is not a terminal multiplexor and you can't use an interactive process as the preview command. Also, the command should finish quickly as the preview window is updated only when the process completes.
> 
> You can still make fzf launch vim or an interactive editor by binding a key to `execute` action as follows:
> 
> ```shell
> fzf --preview 'head -100 {}' --bind 'ctrl-v:execute(vim {} < /dev/tty)'
> ```

is there on option to use fzf to open up a file in nano/vim after searching?
