### ISSUE TITLE
fzf vim plugin not prompting when swp file exists

### ISSUE THREAD

**Issue by jshort** [junegunn/fzf#1365]
- Category
    - [] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [x] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [x] bash
    - [x] zsh
    - [ ] fish

If I have a file open (and therefore a .swp file exists) and I have another nvim process open and I use fzf to search for that file and hit enter, it seemingly freezes (though I think the typical prompt for "Found a swap file by the name...." is hidden). If I hit enter again, it opens the file in read only mode.  I recently did a brew upgrade of neovim and updated all my plugins but I'm pretty sure this has previously worked.

EDIT:
I just confirmed that the "Found a swap file by the name" does pop up on neovim 0.2.2, 0.2.2_1, and 0.3.0.  It starts to behave as described above on 0.3.1.

**Comment by lambdadelta34** [comment]
ran to the same behaviour today in neovim + macos + fish

**Comment by sethwoodworth** [comment]
I believe I'm getting the same behavior on Ubuntu 18.04 with neovim 0.3.1.

**Comment by afn** [comment]
The commit in neovim that broke this was https://github.com/neovim/neovim/commit/b7514493a0c4a4389a5921f15b0b429dae5c75e7, which changed the default value of `shortmess` to include the `F` flag. This flag is described as:

> don't give the file info when editing a file, like :silent was used for the command

You'll see the same behavior if you do `:silent! e some_file.txt`: it omits the "Swap file exists" attention message, but still waits for user input (besides Enter, you can also type `E` to (E)dit anyway, etc). I think this is a bug in neovim (and apparently in vim too!)... I would expect it to either not wait for user input (and default to read-only), or show the message and wait for input. I'll open an issue in neovim.

**Comment by cema-sp** [comment]
@jshort Could this ticket be closed since it seems to be a **neovim** bug?

**Comment by jshort** [comment]
Closing, thanks @afn for the neovim issue.
