### ISSUE TITLE
Howto disable fzf color on console?

### ISSUE THREAD

**Issue by tuyenpm9** [junegunn/fzf#1366]
- Category
    - [x] fzf binary
- OS
    - [x] Linux
- Shell
    - [x] zsh

I seem can't find howto change color of fzf or it might hard-coded in source? using fzf-scripts from this repo https://github.com/DanielFGray/fzf-scripts/ but each command give different color of fzf.

**Comment by alexandergraul** [comment]
`fzf --no-color` disables the color output. I did not take a good look at _your_ wrapper scripts to see if you can pass that flag to the wrapper functions.
