### ISSUE TITLE
[zsh] Howto guide fzf hosts completion for a specific command

### ISSUE THREAD

**Issue by ghost** [junegunn/fzf#1368]
- Category
    - [x] fzf binary
    - [x] Completion
    - [x] Vim
- OS
    - [x] Linux
- Shell
    - [x] zsh

Currently we have `ssh **` and `telnet **`, how can I trigger fzf for hosts completion for other command, I usually write some scripts that need to trigger hosts completion.

**Comment by junegunn** [comment]
Unfortunately, fuzzy completion API is still rough around the edges. You'll have to read the source code to see how it's done. Also take a look at https://github.com/junegunn/fzf/wiki/Examples-(completion)

Anyway, one easy way is to define `_fzf_complete_COMMAND` function that uses the existing ones.

```sh
_fzf_complete_scp() {
  _fzf_complete_ssh "$@"
}
```
