### ISSUE TITLE
Searching File Contents And Opening File

### ISSUE THREAD

**Issue by magicalbanana** [junegunn/fzf#1371]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

How do you use searching file contents and then opening the file?

**Comment by plitter** [comment]
Maybe someone knows better, but I think fzf is used to select text, I don't think it knows how to open a file. 
But for example you could 
<program to open file with> $(grep -Rl <pattern> | fzf)

**Comment by junegunn** [comment]
See #429.
