### ISSUE TITLE
feature request: fuzzyfinding the results of first fzf run

### ISSUE THREAD

**Issue by man0xff** [junegunn/fzf#1375]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [x] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [x] Mac OS X
    - [x] Windows
    - [x] Windows Subsystem for Linux
    - [x] Etc.
- Shell
    - [x] bash
    - [x] zsh
    - [x] fish

often i face with situation when i get too many results and results differs only in beginning of each line. and it is not comfortable to erase and find again. this slows down search. it will be great if there will be a key combination to continue searching from scratch through results of first search.

please point me to the answer if it already exists. i googled and didn't find any recipies...

**Comment by sudo-nice** [comment]
Let me explain this for OP. Suppose, there is a directory with video files along with thumbnails, named like this:
```
movie1.mp4
movie1.mp4.jpg
movie2.mp4
movie2.mp4.jpg
```

Now, if we want to operate on `.mp4` files only, we should always add the suffix `.mp4$` to the search string.
But if there was a command to fix the intermediate results, the workflow could be like this:
1. Type `.mp4$`, to keep `.mp4` files only.
2. Apply some kind of `fixate` command (the point of the issue).
3. Clean the search string, but have only `.mp4` files as the input.
4. Any subsequent searching applies to `.mp4` file, as if `.jpg` files never were there.

**Comment by ochi** [comment]
I believe there's no need to add custom functionality to fzf itself - standard shell bindings are working just fine

1. Start fzf and type .mp4$, to keep .mp4 files only. (`_` denotes cursor position)
`> .mp4$_`
2. Apply some kind of fixate command (the point of the issue).
`> .mp4$ jpg`
3. press <kbd>CTRL+W</kbd> to clean last entered value (if in bash - for fish it will be something like `\cW` <kbd>CTRL+BS</kbd>)
`> .mp4$ jpg _`
4. hit <kbd>CTRL+W</kbd> again
`> .mp4$ _`
4. hit <kbd>CTRL+Y</kbd> to pate last removed thing
`> .mp4$ jpg _`
6. Any subsequent searching applies to .mp4 file, as if .jpg files never were there.

is that what you need?

**Comment by sudo-nice** [comment]
@ochi, thank you. The method you provided is indeed a pretty good solution to the mentioned example. However, that `fixate` command would take away the need of being careful about the search string manipulations.

**Comment by junegunn** [comment]
@ochi Thanks for the comment.

Searching with multiple out-of-order search terms is the way to go, it's more flexible that you can easily "un-fixate"/"re-fixate" the search without having to learn about new features.

https://github.com/junegunn/fzf#search-syntax
