### ISSUE TITLE
Are these two feature already available?

### ISSUE THREAD

**Issue by jiangweiatgithub** [junegunn/fzf#1377]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [ ] Mac OS X
    - [x] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [ ] fish

 I would like suggest the following features, if not already available:
1. Specify maximum number of results to return
2. Return the line numbers of the fount matches only

Thanks!

**Comment by junegunn** [comment]
> Specify maximum number of results to return

```sh
seq 10000 | fzf -m | head -10

# Or do you mean ... ?
seq 10000 | head -10 | fzf -m
```

> Return the line numbers of the fount matches only

```sh
# Prepend line number to each line
ls | nl | fzf | awk '{print $1}'

# Suppress line numbers in fzf finder
ls | nl | fzf --with-nth 2.. | awk '{print $1}'
```

These examples aren't for Windows, but I hope you get the idea.

**Comment by jiangweiatgithub** [comment]
Thanks. BTW, is there already a "n-best" feature? (For example, if I query with 5  key words,  I want the returned results to contain as many of them as possible, and to be sorted so. Hope I am not asking to much.
