### ISSUE TITLE
Add extra directories to CTRL-T

### ISSUE THREAD

**Issue by vmasrani** [junegunn/fzf#1386]
- Category
    - [X ] fzf binary
    - [ ] fzf-tmux script
    - [ X] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [X ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ X] zsh
    - [ ] fish

With https://github.com/andrewferrier/fzf-z we have the option of specifying an environment variable that lists additional directories besides the current one to search through. Is there any such flag in fzf? It would be nice to be able to CTRL-T and have fzf search through the downloads folder as well (for example).

**Comment by junegunn** [comment]
Yes, via FZF_CTRL_T_COMMAND. Please read through README page before opening an issue.
