### ISSUE TITLE
fzf trigger seems only work for ls, cd, cat, cp. 

### ISSUE THREAD

**Issue by benzwt** [junegunn/fzf#1387]
- Category
    - [*] Completion
- OS
    - [*] Linux
- Shell
    - [*] bash

fzf version: 0.17.4 (f0fe79d)
---------------------------------------------------------------
I found that the ** trigger only works for simple system command such as ls, cp, cat, cd and etc.
It is possible to use this feature with other command such mpv or evince ?

thanks!

**Comment by junegunn** [comment]
See https://github.com/junegunn/fzf#supported-commands
