### ISSUE TITLE
finer control to restrict the pattern to certain fields in extended search mode

### ISSUE THREAD

**Issue by liushapku** [junegunn/fzf#1388]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [ ] fish

I know that with `-n` and `--with-nth` we can restrict the **whole query pattern** to certain fields. But this still cannot work well if we want to **apply one pattern to one field while apply another pattern to another filed**, like what we can do in sql query or excel filtering. A simple example is like this from `ls /` (I manipulated the output to serve as a better example):

    drwxr-xr-x  25 root root       4096 Sep 13 22:42 ./
    drwxr-xr-x  25 root root       4096 Sep 13 22:42 ../
    drwxr-xr-x   2  dev root      12288 Sep 13 22:36 bin/
    drwxr-xr-x   4  dev root       4096 Sep 19 06:59 boot/
    drwxr-xr-x   2 root  dev       4096 Nov 23  2017 cdrom/
    drwxr-xr-x   5 root root       4096 Oct 16  2017 dev/
    drw-r--r--   5 root root       4096 Oct 16  2017 external

1. If I want to search all `executable` folders containing `o` in the filename, I would want to apply `x` to the first field while `o` to the last field; note that there is a file `external` which matches `x`
1. If I want to search all folders containing `o` in the filename which also belongs to user `dev` or group `dev`, `dev` should only be applied to the 3rd and the 4th field but not the filename filed, there happens to have a folder also named `dev`. These cannot be solved with `-n` or `--with-nth`

Thus I suggest a new feature to handle this. For example, we can add a pattern suffix like `@n` which is to select the field (or fields) that the previous pattern is to be applied. For example, the first example used above can be queried using `x@1 o@9`; and the second can be queried using `dev@2,3 o@9`. 

We can reuse the `FIELD INDEX EXPRESSION` here. A suffix will particularly more helpful comparing to a prefix because after typing `dev` we would then know that `dev` appears in multiple fields and we can continue to type the `@...` part as guided by our eyes. 

The choice of symbol `@` needs more careful thinking to avoid breaking existing code. A safer way is to add another option to selectively enable this feature, say for example `--field-selector @`. Only with this `@` in the query pattern gains this special treatment and the user can choose to use other symbol ( or several symbols together like `@@`) to denote this.

**Comment by junegunn** [comment]
Thanks for the suggestion but it's a bit too complicated for my taste and it requires significant rework of the code, so I'm going to pass on this one.
