### ISSUE TITLE
fzf.kak - fzf integration plugin for Kakoune

### ISSUE THREAD

**Issue by andreyorst** [junegunn/fzf#1389]
- Category
    - [X] fzf-tmux script
    - [X] Etc.
- OS
    - [X] Linux

Hello. I've made [fzf.kak](https://github.com/andreyorst/fzf.kak) script, which is a [Kakoune](https://github.com/mawww/kakoune) plugin, that brings integration with your awesome tool. I wonder if I should add it to the Wiki and/or to your readme. I thought you might be interested, since you have a plugin for vim here.

This plugin adds ability to open files, change directories, browse git-tree, search for tags with universal-ctags, and switch buffers. In general it is a wrapper around lists, and kakoune commands, so other usages are possible too, I just don't came with another yet. It support both tmux, and X11. I've tested it on several environments, and it works fine.
I've also made mnemonic keybindings that are the main way of interaction with plugin.
Here are some gifs:
**Opening files**:
![files](https://user-images.githubusercontent.com/19470159/45917778-3988e200-be85-11e8-890d-b180d013b99e.gif)

**Searching tags with universal-ctags**
![ctags](https://user-images.githubusercontent.com/19470159/45917775-3988e200-be85-11e8-8959-d7ddf17961b7.gif)
If running outside of tmux another terminal will be launched, and result of fzf will go back to Kakoune.

**Comment by junegunn** [comment]
Cool, thanks for sharing. Feel free to add it to the wiki page here: https://github.com/junegunn/fzf/wiki/Related-projects.

We can consider also mentioning it directly on the README page, maybe along with fzf.el, but for now, I'll just add a link to that page. Thanks.
