### ISSUE TITLE
Keyboard shortcuts

### ISSUE THREAD

**Issue by cartolari** [junegunn/fzf#139]
In the vim plugin is it possible to map commands like Ctrl-p? For example C-x for open the selected line in a horizontal split or C-v for a vertical split?
Just for example, the shortcuts  could not be the same.

**Comment by junegunn** [comment]
I hope it was possible, but no. See #61. This is a price to pay for fzf being a general-purpose filter rather than a plugin for a certain platform.

**Comment by junegunn** [comment]
ctrlp-compatible key bindings are now implemented in the new version.
