### ISSUE TITLE
Empty space in path during install script

### ISSUE THREAD

**Issue by BarbzYHOOL** [junegunn/fzf#1390]
When using the install script

If the installed path has an empty space in its name, then it will fail at this step

`set: Warning: $PATH`

**Comment by BarbzYHOOL** [comment]
Then I retried by cloning the repo in /tmp

and I get this

`Update fish_user_paths ... Failed`

**Comment by junegunn** [comment]
Thanks for the report, it should be fixed now.

You may need to remove invalid paths from `$fish_user_paths` if it's corrupted; see https://github.com/fish-shell/fish-shell/issues/2639

**Comment by BarbzYHOOL** [comment]
yes, i had to do that and since i didn't know, it was a bit annoying to do :P but i found how yesterday

and now I renamed many of my directories for nothing lol
