### ISSUE TITLE
FZF not closing with <Esc>+<Another Key>

### ISSUE THREAD

**Issue by sQVe** [junegunn/fzf#1393]
- Category
    - [X] fzf binary
    - [ ] fzf-tmux script
    - [X] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [X] Neovim
    - [ ] Etc.
- OS
    - [X] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [X] zsh
    - [ ] fish

--------------------------

**TL;DR** `fzf` does not close window when `<Esc>+<Another Key>` is pressed.

I mainly use `fzf` in `neovim` and I have noted that sometimes the closing of it locks up strangely. Today I did some investigating to why and I quickly noted that I sometimes double tap `<Esc>`. `fzf` seems to set `<Esc>` as some kind of *leader key* as keys pressed quickly after `<Esc>` puts it into some kind of state.

The expected behavior would be that `<Esc>` would exit `fzf` cleanly and straight-away just like `<C-c>` does.

**Comment by junegunn** [comment]
Escape character indeed works as alt modifier on terminal. i.e. `escape + a` is `alt-a`. However, fzf clearly isn't properly handling double escape characters and unnecessarily waits for more key strokes. I'll fix this.

**Comment by junegunn** [comment]
Fixed pushed to master. Let me know if you still see the issue.

**Comment by sQVe** [comment]
@junegunn Works now, made a huge workflow improvement for me - so thank you!

Just a side-note, it it possible for `fzf` to take a config option that disables `<Esc>` as a modifier? I'm seeing a slight delay in closing the window compared to `<C-c>`.

**Comment by junegunn** [comment]
Reducing ESC delay can make fzf unable to read keys with ALT modifier on some terminals. Since you use Neovim, consider setting up a terminal mapping for fzf buffer.

```vim
autocmd! FileType fzf tnoremap <esc> <c-c>
```

**Comment by sQVe** [comment]
@junegunn Ahhh :yum:, that did the trick! Yet again thank you - and thank you for creating such a **indispensable** tool.

**Comment by madox2** [comment]
Using the code above `autocmd! FileType fzf tnoremap <buffer> <esc> <c-c>` disabled me to use `<shift> + <tab>` for selecting multiple results. I have found another workaround that works also in this case:

```
set ttimeoutlen=0
```
