### ISSUE TITLE
Fuzzy completion not using FZF_DEFAULT_COMMAND?

### ISSUE THREAD

**Issue by tbenst** [junegunn/fzf#1398]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [x] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

I am trying `cd **` while in home, but all my results are from `.dropbox/*` or `.wine/*`, and I'd like to exclude them. I tried `export FZF_DEFAULT_COMMAND='rg --files --no-hidden --follow'` with no luck. Any tips? thx!

**Comment by edi9999** [comment]
I think you need to use _fzf_compgen_path instead : 

In the source code : 
```
# To use custom commands instead of find, override _fzf_compgen_{path,dir}
if ! declare -f _fzf_compgen_path > /dev/null; then
  _fzf_compgen_path() {
    echo "$1"
    command find -L "$1" \
      -name .git -prune -o -name .svn -prune -o \( -type d -o -type f -o -type l \) \
      -a -not -path "$1" -print 2> /dev/null | sed 's@^\./@@'
  }
fi
```

**Comment by ev-agelos** [comment]
I just had the same problem. Just saw in the [docs](https://github.com/junegunn/fzf#respecting-gitignore) that this exists `FZF_CTRL_T_COMMAND=`. Wow didn't use it all this time and I thought I had set it up correctly.

```
# Feed the output of fd into fzf
fd --type f | fzf

# Setting fd as the default source for fzf
export FZF_DEFAULT_COMMAND='fd --type f'

# Now fzf (w/o pipe) will use fd instead of find
fzf

# To apply the command to CTRL-T as well
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
```

**Comment by rileyrg** [comment]
Is this the same for Alt c? Which begs the Q what IS FZF_DEFAULT_COMMAND if it's not picked up by the fzf cli?

**Comment by rileyrg** [comment]
Ditto for alt-c command. Its ignoring all my git submodules. I added skip vcs options to fzf_default_command. Whats the point for a default command if it's not used?

**Comment by junegunn** [comment]
@rileyrg See https://github.com/junegunn/fzf#key-bindings-for-command-line

FZF_DEFAULT_COMMAND is supposed to list files, while ALT-C needs a list of directories. Fuzzy completion cannot use FZF_DEFAULT_COMMAND because you want different results depending on the prefix (e.g. `ls ~/dir1/**` vs. `ls ~/dir2/**`) and a static command defined in FZF_DEFAULT_COMMAND cannot satisfy the requirement.

**Comment by rileyrg** [comment]
May I ask how I get alt c to look through hierarchies of git directories. I've obviously missed something really easy as it must be straightforward.

**Comment by colinmollenhour** [comment]
```
    FD_OPTIONS="--follow --exclude .git --exclude node_modules"
    export FZF_DEFAULT_COMMAND="fd --type f --type l --strip-cwd-prefix --hidden $FD_OPTIONS"
    export FZF_CTRL_T_COMMAND="fd $FD_OPTIONS"
    export FZF_ALT_C_COMMAND="fd --type d $FD_OPTIONS"
```
