### ISSUE TITLE
split fzf-binary and shell/vim scripts into separate repos

### ISSUE THREAD

**Issue by DanielFGray** [junegunn/fzf#1399]
I'd like to suggest splitting all of the shell wrappers into a separate repo, maybe "fzf-shell" or "fzf-contrib", and the minimal vim plugin into fzf.vim

**Comment by junegunn** [comment]
I could have considered the direction if fzf was a young project, but the ship has sailed years ago. There are too many users of the project and changing the structure of the project will cause unnecessary confusion. And I don't have the time or any incentive to do all the legwork.
