### ISSUE TITLE
illegal option: --tac

### ISSUE THREAD

**Issue by narkisr** [junegunn/fzf#140]
Wheh pressing CTRL-R I get illegal option: --tac

Not sure what have changed since it used to work

Thanks

**Comment by narkisr** [comment]
Ok, iv edited .fzf.zsh and it seems to have solved it (removed the options)

**Comment by junegunn** [comment]
Yeah, there was [a backward incompatible change in 0.9.4](http://junegunn.kr/2015/03/fzf-0.9.4/). Update the repo and re-run the install script and you'll be fine.

By the way, how did you install fzf and what does `fzf --version` say? (I'm trying to see whether if you're using the new Go version or the legacy Ruby version.)

**Comment by narkisr** [comment]
fzf 0.8.9 (Dec 24, 2014)

I did a pull but didn't run install yet ill do that now

Thanks

**Comment by junegunn** [comment]
Ah I see, you're using the old version. The Go version (from 0.9.0) is much faster.

**Comment by narkisr** [comment]
Odd because I cloned it not too long ago (about a week), I don't know how I got the older version in the first place

Thanks
