### ISSUE TITLE
Custom command moves the prompt down one line

### ISSUE THREAD

**Issue by bananatranada** [junegunn/fzf#1402]
- Category
    - [ ] fzf binary
    - [x] Key bindings
    - [ ] fzf-tmux script
    - [ ] Vim
    - [ ] Neovim
    - [ ] Completion
    - [ ] Etc.
- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

```
# fh - repeat history
fh() {
  print -z $( ([ -n "$ZSH_NAME" ] && fc -l 1 || history) | fzf +s --tac | sed 's/ *[0-9]* *//')
}
```

I'm using the code above, but it creates a blank line in my shell (also excluding the prompt). Anyone know how to fix this? Thanks

![image](https://user-images.githubusercontent.com/18587905/46809320-d24ba880-cd33-11e8-8865-188584c040f0.png)

**Comment by edi9999** [comment]
What are you trying to achieve exactly ?

**Comment by bananatranada** [comment]
I'm trying to get the above command to behave the same way as the native `ctrl+r` command, where the cursor ends up on the same line. Is this possible via custom functions in bash or zsh?
