### ISSUE TITLE
Misunderstanding tiebreak begin ?

### ISSUE THREAD

**Issue by edi9999** [junegunn/fzf#1403]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

Hello @junegunn,

I have a question about how tiebreak works.

From the docs, I understand that when I write : 

fzf --tiebreak begin,length,end

it will show : 

- matches which have the matches most to the left of the string that is matched
- in case of equality, matches which have shorter length
- in case of equality, matches which have the matches most to the right of the matched string.

I have an example : 

I use FZF_DEFAULT_OPTS="" to be sure there is no other option

```
printf "MachineList\nMy super duper list of machines\nMy funny ........ machine of lists\n" |  FZF_DEFAULT_OPTS="" fzf -i --tiebreak begin,length,index
```

Now, If I query `machine list`, the matches are not ordered correctly : 

```
  MachineList                                                                                                                                                                                  
  My funny ........ machine of lists                                                                                                                                                           
> My super duper list of machines                                                                                                                                                              
  3/3                     
                                                                                                                                                                     
> machine list                                                                                                                                                                                
```

I would expect that the "MachineList" match would come up at the cursor by default. 

Is this a bug of fzf or do I misunderstand something ?

**Comment by junegunn** [comment]
The option is working as expected here, but yeah, it's really hard to comprehend. Since we updated the ranking algorithm, ties are rare and `--tiebreak` has lost most of its significance. I've even considered removing the option because it can be too confusing. `--tiebreak=index` would be a good default then.

`My super duper list of machines` has higher score than `MachineList` for `machine list` or (`list machine`) because both `m` and `l`, the starting characters of search terms, appear at the start of a word. `l` for `MachineList` matches an uppercase `L` which also gets some bonus score, but it's smaller.

See https://github.com/junegunn/fzf/blob/0.17.5/src/algo/algo.go#L108-L128

You can just type in `machinelist` instead of `machine list` if you want `MachineList` to appear at the top.

**Comment by edi9999** [comment]
I wasn't aware that now the sort algorithm was using a "scoring" method (this is the method I prefer, since it makes it possible to have "races", in the sense that there is no "absolute sorting" where one criteria is applied after the other, but rather each criteria has a strength).

Would you accept to let the users configure the values that are defined in algo, for example : 

--sort-multipliers "scoreMatch:20,scoreGapStart:-5" 

to override the values ?

**Comment by junegunn** [comment]
No, I'm not into the idea of introducing such esoteric options that are hard to use correctly. Pretty much I'll be explaining how they work over and over again and it's going to be painful. I'd like to keep things simple and focus on providing good defaults that work okay most of the cases. But more adventurous users can always build fzf from source, experiment with their ideas.

**Comment by edi9999** [comment]
Ok, I totally understand your point, adding low level options will lead to a lot of issues, which you already have a lot to handle.
