### ISSUE TITLE
--expect key isn't working properly with different letter cases

### ISSUE THREAD

**Issue by andreyorst** [junegunn/fzf#1404]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [x] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [x] bash
    - [x] zsh
    - [x] fish

By executing `fzf --expect alt-n --expect alt-N` and pressing <kbd>Alt</kbd>+<kbd>n</kbd> will always
return `alt-N`. If I change command to `fzf --expect alt-N --expect alt-n` it will always return `alt-n`. I understand that both keys are `n`, but those are different key codes. I thought that maybe I should use the same flag, as `--expect ctrl-alt-n`, but turn's out that `--expect alt-shift-n` isn't supported. I need this functionality for having dynamic mappings in my [fzf.kak](https://github.com/andreyorst/fzf.kak) plugin, since I want to support universal ctags filtering of different tag kinds.

**Comment by cevhyruz** [comment]
@junegun can i work on this? Any pointers?

**Comment by junegunn** [comment]
Fixed in 7f8e0dbc408eff786865d0e2d9e3c62ec3ed4776
