### ISSUE TITLE
fuzzy

### ISSUE THREAD

**Issue by jinyounkyum** [junegunn/fzf#1405]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [ ] fish

**Comment by andreyorst** [comment]
@edi9999 I've understood everything, just can't explain it...
