### ISSUE TITLE
[$FZF_DEFAULT_COMMAND failed]

### ISSUE THREAD

**Issue by TsaiKoga** [junegunn/fzf#1408]
- Category
  - [x] fzf binary
  - [ ] fzf-tmux script
  - [ ] Key bindings
  - [ ] Completion
  - [ ] Vim
  - [ ] Neovim
  - [ ] Etc.
- OS
  - [ ] Linux
  - [x] Mac OS X
  - [ ] Windows
  - [ ] Etc.
- Shell
  - [x] bash
  - [x] zsh
  - [ ] fish

I use fzf today.

    brew install fzf

and I add export in ~/.bash_profile

    export FZF_DEFAULT_COMMAND="fd --exclude={.git,.idea,.vscode,.sass-cache,node_modules,build} --type f"
    export FZF_DEFAULT_OPTS="--height 40% --layout=reverse --preview '(highlight -O ansi {} || cat {}) 2> /dev/null | head -500'"

and then

    source ~/.bash_profile

And then use ```fzf``` 
It's show this error

         [$FZF_DEFAULT_COMMAND failed]
and the preview configuration is work, but the default command is failed.

And I remove that line from the bash_profile, or reinstall the fzf it still failed.

**Comment by DzKaki** [comment]
How did you install fd? Can you check it is working properly?
I tried to reproduce the issue here, it worked under fish and not under bash and zsh, so I realized that my $PATH wasn't properly configured to include the fd binary. After I fixed that the command is working in all three shells.

**Comment by TsaiKoga** [comment]
I install fd by ```brew```
It work after I removed the configuration from ```.bash_profile```, and add it to ```.zshrc```

**Comment by originalix** [comment]
@TsaiKoga Thank you. Is worked for me.
