### ISSUE TITLE
fzf is not added to PATH (Cygwin)

### ISSUE THREAD

**Issue by dmos62** [junegunn/fzf#141]
`~/.fzf/fzf` is not automatically added to PATH. `~/.fzf/fzf-tmux` is added, and the appended line in .zshrc sources `~/.fzf.zsh`, however none of the functionality works complaining command not found.

**Comment by junegunn** [comment]
`~/.fzf/fzf` is the legacy ruby version that is no longer used unless your platform does not support the new go version which is placed inside `~/.fzf/bin` by the install script. Can you post the output of the install script?

**Comment by dmos62** [comment]
~ % git clone https://github.com/junegunn/fzf.git ~/.fzf && ~/.fzf/install
    Cloning into '/home/Domas/.fzf'...
    [ommited]
    Do you want to add auto-completion support? ([y]/n) y
    Do you want to add key bindings? ([y]/n) y

    Generate ~/.fzf.bash ... OK
    Generate ~/.fzf.zsh ... OK
    which: no fish in [ommited]
    

    Update /home/Domas/.bashrc:
      - [ -f ~/.fzf.bash ] && source ~/.fzf.bash
        + Added

    Update /home/Domas/.zshrc:
      - [ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
        + Added

    Finished. Restart your shell or reload config file.
      source ~/.bashrc  # bash
      source ~/.zshrc   # zsh

    Use uninstall script to remove fzf.

    For more information, see: https://github.com/junegunn/fzf
    ~ % source ~/.zshrc
    ~ % fzf
    zsh: command not found: fzf
    127 ~ % fzf-tmux                                                             :(
    /home/Domas/.fzf/bin/fzf-tmux: line 86: fzf: command not found
    127 ~ % echo $PATH | tr : "\n"                                               :(
    /home/Domas/bin
    /home/Domas/.fzf/bin
    /home/Domas/bin
    /usr/local/bin
    /usr/bin
    /cygdrive/c/Windows/system32
    /cygdrive/c/Windows
    /cygdrive/c/Windows/System32/Wbem
    /cygdrive/c/Windows/System32/WindowsPowerShell/v1.0
    /cygdrive/c/Program Files/Java/jdk1.7.0_71/bin
    /cygdrive/c/Program Files/Java/jre7/bin
    /cygdrive/c/Program Files (x86)/Calibre2
    /cygdrive/d/ivairus/apache-maven-3.2.3/bin
    /home/Domas/d/ivairus/appengine-java-sdk-1.9.17/bin
    /home/Domas/d/ivairus/appengine-java-sdk-1.9.17/bin

**Comment by junegunn** [comment]
Ah, you're on cygwin. I haven't been able to test fzf on cygwin lately.
The go versions are [only supported on OS X and Linux](https://github.com/junegunn/fzf-bin/releases/tag/0.9.4), so the install script will choose to use the legacy Ruby version in your case (note that some new features are not available), but there was a bug in the install script. Update the repository and try again.

**Comment by dmos62** [comment]
The ruby `fzf` installed properly now, thanks. Unfortunately, opening in a tmux pane doesn't work well: `Ctrl-T` opens in a pane, but always runs from home directory, while `Alt-C` and `Ctrl-R` do not open in a new pane and run fullscreen (from correct directory). Under tmux + vim `:FZF` does not give any response, but at least the fullscreen bang version works. I'll open a new issue.
