### ISSUE TITLE
Scripting a "back-to-last-list" button for combining more than one fzf executions

### ISSUE THREAD

**Issue by Wolfsrudel** [junegunn/fzf#1412]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [x] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [x] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

I'll try to explain what i'm currently want to achive:

I'm combining three executions of fzf after each other:

`fzf1 -> listing1 -> selection1 -> fzf2 -> listing2 -> selection2 -> fzf3 -> listing3 -> selection3 -> command-execution`

In every listing I want to have a kind of "back" or ".." at the the bottom (or top) of the list and if i select this i want to get back to the last listing.

`listing3 -> ".." -> listing2 -> ".." -> listing1`

Any ideas? :)
Instead of using ".." (or "back") the ESC key could be a possible opportunity.

**Comment by LuRsT** [comment]
Hi @Wolfsrudel,

This seems like a very power use of fzf, I'm unsure of how you'd achieve this, which makes me think that fzf may not be the right tool for this job. Did you figure out how to do this using fzf? Care to share?
