### ISSUE TITLE
fzf --multi result order

### ISSUE THREAD

**Issue by stfl** [junegunn/fzf#1417]
I noticed that the output order when doing multi selection is the same order as selected.
I want it to be the order of the search. Especially when dealing with a git history, the order is important.

    echo "1
    2
    3" | fzf --multi

selecting 1, then 3, then 2 yields:

    1
    3
    2

I want this to result in

    1
    2
    3

Is there an option for that?

**Comment by junegunn** [comment]
No, there's no such option. But you can sort the output afterwards.

```sh
git log --oneline --color=always | nl | fzf --multi --ansi --with-nth 2.. | sort -nk1
```

**Comment by stfl** [comment]
sounds good. thanks
