### ISSUE TITLE
wrong height when --header uses a multiline string

### ISSUE THREAD

**Issue by liushapku** [junegunn/fzf#1418]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [x ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [ ] fish

the margin added to `height` is always set to 1 when `--header` is used, regardless of whether the header has more than one line. In the multiline case, because the header occupies more than what is assigned, some of the choices are not visible.

The problem is caused by the `s:calc_size` function in `fzf.vim`, where the margin for header is 1 whenever it exists.

I get a naive workaround as follows, which assumes the newline character only exists in the header string:

      if stridx(opts, '--header') > stridx(opts, '--no-header')
        let margin += len(split(opts, "\n"))
      endif

If we can assume each newline character in the `opts` should consume one more line in the display, no matter it is for `--header` or for other options, we can instead add this line before the `return` statement:

    let margin += len(split(opts, "\n")) - 1

Would you please investigate and provide a more robust solution?

**Comment by LuRsT** [comment]
Hi @liushapku, did you try `--header-lines` as suggested?

**Comment by junegunn** [comment]
Thanks, although we have no perfect way to find the correct margin, your suggestion definitely improves the current heuristic.

**Comment by p1r473** [comment]
Heres a code sample in case anyone was wondering how to do it
```
local entries_with_headers=("All warp points:" "Press enter to select. Press delete to remove" "${entries[@]}")
    local fzf_bind="delete:execute(echo {} | awk -F ' -> ' '{print \$1}' | xargs -I {} $script_path/wd.sh rm {} > $wd_remove_output)+abort"
    local fzf_command=$(printf '%s\n' "${entries_with_headers[@]}" | fzf --height 100% --reverse --header-lines=2 --bind="$fzf_bind")
```
