### ISSUE TITLE
fzf is slow in large directory

### ISSUE THREAD

**Issue by heycam** [junegunn/fzf#1419]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

I'm working in a project directory that has almost 300,000 files under it.  I'd like to use fzf to avoid typing out long path names but it's too slow on my machine:

```
cam@zoo /z/moz/central $ time find . -type f | wc -l
289362

real	0m0.391s
user	0m0.172s
sys	0m0.236s
```

```
cam@zoo /z/moz/central $ time /z/fzf/bin/fzf -f properties.mako.rs | head -1
servo/components/style/properties/properties.mako.rs

real	1m22.918s
user	0m36.776s
sys	0m30.108s
```

Is there anything I can do to make fzf fast enough for interactive use?

**Comment by DanielFGray** [comment]
fzf is rarely ever the bottleneck in my usage. Consider using a different program to list files, for example `export FZF_DEFAULT_COMMAND` with your choice of `ag` `rg` or similar.

Compared to other filter related programs, eg `selecta` or `fzy`, `fzf` is the only I've found that doesn't buffer stdin and makes the UI visible and usable while the input program is still running. If you have ideas on how to improve "throughput" from stdin to the UI I would love to read your pull request.

**Comment by heycam** [comment]
Thanks for the hint, Daniel! It looks like the default command when `FZF_DEFAULT_COMMAND` is not set,

```
find -L . -mindepth 1 \( -path '*/\.*' -o -fstype 'sysfs' -o -fstype 'devfs' -o -fstype 'devtmpfs' -o -fstype 'proc' \) -prune -o -type f -print -o -type l -print 2> /dev/null | cut -b3-
```

is just super slow.  When I do use `find . -type f`, I get much more reasonable times:

```
cam@zoo /z/moz/central $ time FZF_DEFAULT_COMMAND='find . -type f' /z/fzf/bin/fzf -f properties.mako.rs | head -1
./servo/components/style/properties/properties.mako.rs

real	0m0.407s
user	0m0.360s
sys	0m0.320s
```

**Comment by ogaida** [comment]
i know it's old, but anyway a hint, i use `--walker-skip=Library,.git,node_modules`

**Comment by johnrhunt** [comment]
This shouldn't be closed? I'd expect this tool to be fast due to its indexing but it isn't.

**Comment by DanielFGray** [comment]
> I'd expect this tool to be fast due to its indexing but it isn't.

fzf is not a file finder, it is an interactive filter for stdin, that *just so happens* to list files as a default behavior when not given stdin

afaik it does not index your file system, and on windows you are likely to experience some fairly noticeable performance issues due to windows antivirus hooks in the filesystem

**Comment by mrlee14** [comment]
Had same issue, what I found: FZF can be set with default search program eg. 'find' or 'fd' and 'fd'  search its much faster then 'find' ('fd' is rust program similar to 'find'). 

Put this into your .profile  (.zprofile or .bash_profile) to make FZF run faster/proper:
```
export FZF_DEFAULT_COMMAND='fd --type f --hidden --exclude .git'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
```
IMPORTANT: some users have extra flag '--follow' set for 'fd' what makes fd very slow as it searches more then just '/home/dir' also some other places/devices this way scans extra/useless file, see 'fd' authors comment about: [[find the targets very slow in a large directory when using fzf. 8.0.0 works well.](https://github.com/sharkdp/fd/issues/599#issuecomment-633228003)]

**Comment by schnej7** [comment]
For anyone looking to speed up `fzf` further, check out this post: https://dev.to/jerry_schneider/how-i-made-fzf-feel-snappy-again-in-large-repositories-208n
