### ISSUE TITLE
[ZSH] multiple line command histroy problem?

### ISSUE THREAD

**Issue by xuchunyang** [junegunn/fzf#142]
For example,
```
➜  ~  git \
> --version
git version 2.3.2
```
`fzf` (by using `C-r` in ZSH) gave me
```
➜  ~  git \\n--version
error: invalid key: pager.\n--version
error: invalid key: alias.\n--version
git: '\n--version' is not a git command. See 'git --help'.
```
which doesn't work like the normal `C-r` .

Any ideas?

**Comment by junegunn** [comment]
Hmm, thanks for the report. bash version also seems to have problem with multi-line commands.

**Comment by junegunn** [comment]
Should be fixed now. Please [upgrade fzf](https://github.com/junegunn/fzf#upgrading-fzf) and let me know if you see any issue. Thanks.

**Comment by xuchunyang** [comment]
It works now. Thanks for your work. @junegunn
