### ISSUE TITLE
fzf-tmux is slow to appear, but fzf works normally

### ISSUE THREAD

**Issue by glentakahashi** [junegunn/fzf#1421]
- Category
    - [ ] fzf binary
    - [x] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

For some reason on Mac OS X mojave + tmux 2.8 and the latest fzf, the fzf-tmux script is very slow to start up (>3 seconds). Normal `fzf` works fine, if I run a command like `echo foo | fzf` it instantly pops up, but instead doing `echo foo | fzf-tmux` takes 3 seconds. The pane appears immediately, but then fzf takes ~3 seconds to appear, but once fzf has appeared it is extremely responsive.

Any ideas on how to debug this?

**Comment by LuRsT** [comment]
Hi @glentakahashi,

It's been a while since you submitted this issue, are you still experiencing this or has it been fixed?

**Comment by junegunn** [comment]
You could try `echo foo | bash -x $(which fzf-tmux)` to see what's going on.

**Comment by glentakahashi** [comment]
Haha this is a very old issue, just tested it and it doesn't seem to be slow for me any more. Going to close out!

**Comment by zhimsel** [comment]
Sorry to drag this back up, but I'm experiencing the same issue, but in newer versions. `fzf` is very quick, but `fzf-tmux` is very slow.

To be more specific, when using `fzf-tmux` (either by piping to it or setting `FZF_TMUX=1`), a new tmux pane opens almost immediately, but it takes a few seconds for fzf to display anything inside it. This has nothing to do with _what_ fzf is reading. The same delay is present for very large datasets (e.g. `find / | fzf-tmux` with many thousands of entries) and small ones (e.g. `printf "hello\ngoodbye" | fzf-tmux`).

Versions:
- MacOS Mojave 10.14.6
- zsh 5.8 (x86_64-apple-darwin18.7.0)
- tmux 3.1a

This behavior is identical, regardless of which terminal emulator I use:
- iTerm2 3.3.9
- alacritty 0.4.2 (f68de37)
- Terminal 2.9.5 (421.2)

Note: using almost nearly identical config for tmux, zsh, and fzf, I do not experience this behavior using Konsole on Arch Linux.

For reference: https://github.com/zhimsel/dotfiles
There are some machine-local configs, but they don't appear to affect this behavior.

**Comment by junegunn** [comment]
```sh
tmux split-window 'bash -c "echo foo"'
```

Does this finish immediately? If it doesn't, it's probably some configuration issue and you'll have to figure out why.

**Comment by zhimsel** [comment]
Hm, that (and `zsh -c "echo foo"`) does finish pretty quick, however, noticeably slow than on Linux (which is fast enough to not even see the window open and exit). I'm going through the `fzf-tmux` code now to see what may be conflicting...

Curious,

**Comment by zhimsel** [comment]
I don't know what happened, but it's much faster today. I'll keep an eye on it...
