### ISSUE TITLE
Suggested FZF_DEFAULT_COMMAND for README prunes symbolic links

### ISSUE THREAD

**Issue by lilyball** [junegunn/fzf#1422]
- Category
    - [X] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [X] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [X] fish

By default, running `fzf` with no input at the terminal appears to run the command

```
find -L . -mindepth 1 ( -path */\.* -o -fstype sysfs -o -fstype devfs -o -fstype devtmpfs -o -fstype proc ) -prune -o -type f -print -o -type l -print
```

However the [README](https://github.com/junegunn/fzf/blob/b46227dcb6f1718d66ad828443d9f03a4bd58c4c/README.md) suggests a much simpler command to use if you want to use `fd`, namely

```
export FZF_DEFAULT_COMMAND='fd --type f'
```

This new command behaves differently than the original, and it's not obvious from the README that it will do so. Not only does it not traverse symbolic links, it will also skip files from `.gitignore` as well (also the fstype stuff, but the only one that applies to macOS is devfs and I don't particularly care about whether `fzf` traverses `/dev`). Since my goal is to replace `find` with `fd` without changing behavior, the README should instead suggest the equivalent `fd` command, which I believe is `fd -L -I -t f -t l` (well, barring the fstype stuff, which it appears `fd` doesn't support).

**Comment by junegunn** [comment]
Thanks for the feedback. But the command on the README page is just an example. It is not meant to be equivalent to the default command. I don't want to suggest `fd -L -I -t f -t l` cause it should be too cryptic for most users. They read the document to learn how they can configure fzf, not to learn about the options of another tool they may or may not use.

**Comment by lilyball** [comment]
The README does not make it obvious that `export FZF_DEFAULT_COMMAND='fd --type f'` is not the `fd` equivalent of the default behavior, as it does not document what the default command is if this env var is unset.

Even if you don't want to document `fd -L -I -t f -t l`, you should at least update the README to make it obvious that the example isn't equivalent. But I really think you *should* document `fd -L -I -t f -t l` because most people aren't going to have the requisite knowledge to construct that themselves.

**Comment by junegunn** [comment]
README currently states that

> Without STDIN pipe, fzf will use find command to fetch the list of files excluding hidden ones. (You can override the default command with FZF_DEFAULT_COMMAND)

And repeats under "Environment variables" section that `FZF_DEFAULT_COMMAND` is the "Default command to use when input is tty". The use of "e.g." tells that it's just an example and the purpose of it is to show users how to set the variable. I could just put `export FZF_DEFAULT_COMMAND='seq 100'` there but I wanted to give a better example that is actually useful and easy to understand.

> most people aren't going to have the requisite knowledge to construct that themselves.

Even if that's the case, I believe they should not blindly use some code snippets they don't understand.

**Comment by lilyball** [comment]
> Even if that's the case, I believe they should not blindly use some code snippets they don't understand.

They effectively already are, if they don't set that variable. Without it, they're using the code snippet `find -L . -mindepth 1 ( -path */\.* -o -fstype sysfs -o -fstype devfs -o -fstype devtmpfs -o -fstype proc ) -prune -o -type f -print -o -type l -print`. And for that matter `fd -L -I -t f -t l` isn't that hard to figure out what it does, it just requires checking out `fd -h`, and you could also rewrite it as `fd --follow --no-ignore --type file --type symlink` if you want it to be more obvious.

The fundamental problem here is the user who simply wants to switch `fzf` to `fd` without otherwise changing behavior. They're going to see that snippet in the README and follow it without understanding that this is in fact changing behavior, quite significantly. To solve this, you have two good options:

1. Make it clear that this example is not equivalent to the default behavior, either by stating this explicitly, or by making the example obviously bogus (e.g. `export FZF_DEFAULT_COMMAND='ls -1'`).
2. Update the example to use the closest `fd` equivalent to the default `find` command.

I prefer the second approach because that helps everyone who wants to use `fd`, but the first approach would be better than nothing.

**Comment by junegunn** [comment]
Thanks for the comment. But I don't understand how you got the idea that the example is meant to be equivalent to the default find command. There are other examples on the page, such as `e.g. export FZF_DEFAULT_OPTS="--layout=reverse --inline-info"` just below that one. With that logic, we should also mention that the options are not the actual default fzf uses. And I feel that it's not necessary.

And FZF_DEFAULT_COMMAND is mentioned multiple times throughout the page with different values. The purpose of the variable should be very clear to the user once he read through the page.

**Comment by lilyball** [comment]
For `FZF_DEFAULT_OPTS` it's fairly clear that this is changing the default options to something else. No confusion there.

For `FZF_DEFAULT_COMMAND` the example is changing from `find` to `fd`. It doesn't state that the new command is equivalent to the old, but it doesn't state that it *isn't* either, and it's perfectly reasonable to believe that the purpose of this example is to show how to get the `fd` equivalent. It's so reasonable that that is literally what I believed, until I realized that I was getting different results with `fd --type f` than I was with the default `find` command and started doing research. I'm sure I'm not the only person who made the assumption that the example was demonstrating how to switch to `fd`.

**Comment by Drew-Daniels** [comment]
Just chiming in here to agree with @lilyball that the readme is confusing to me too. I think it would be helpful to users if it's noted somewhere in the readme what the default fzf command is, if it's not `fd --type f`.

I think explaining what the default is, and then making it clear to users that they can change this to something else if they choose to is more understandable than just showing an alternative, but not the actual default.
