### ISSUE TITLE
Incorrect spaces in preview window with colored `git log`

### ISSUE THREAD

**Issue by ptzz** [junegunn/fzf#1423]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

With
```bash
git log --oneline --color=always --date=short --pretty="format:%C(auto)%h %s %Cblue%an %C(green)%cd" "$@" | fzf --exact --no-sort --ansi --preview 'git show -p --stat --pretty=fuller --color=always {1}'
```
, I see the following in the preview window:

![screenshot 2018-11-08 at 13 23 22](https://user-images.githubusercontent.com/11414930/48198878-9881b800-e35a-11e8-90fc-5e8d587627e6.png)

Note the additional (wrong) space inserted in the the diff chunk.

Version 0.17.5 (brew).

**Comment by junegunn** [comment]
Thanks for the report. Fixed.
