### ISSUE TITLE
no colors with `color=dark`

### ISSUE THREAD

**Issue by ChoppinBlockParty** [junegunn/fzf#1426]
- Category
    - [x ] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x ] zsh
    - [ ] fish

For some reasons I do not have colors when `fzf --color=dark`, though I have colors with `fzf --color=dark`, though I have colors with `fzf --color=light`. Any ideas? `TERM=xterm-256color`.

**Comment by LuRsT** [comment]
Hi @ChoppinBlockParty,

I'd say the issue is probably related to your terminal theme colours, do you still have this issue, or have you figured out the problem and fixed it?
