### ISSUE TITLE
Legacy ruby fzf malfunctions in tmux (Cygwin)

### ISSUE THREAD

**Issue by dmos62** [junegunn/fzf#143]
Opening in a tmux pane doesn't work well: `Ctrl-T` opens in a pane, but always runs from home directory, while `Alt-C` and `Ctrl-R` do not open in a new pane and run fullscreen (from correct directory). Under tmux + vim `:FZF` does not give any response, but at least the fullscreen bang version works.

**Comment by junegunn** [comment]
Thanks for the report. I'm not sure when I'll be able to work on Cygwin. But I'll try to look into it soon. In the meantime, `export FZF_TMUX=0` not to use tmux pane on CTRL-T.

**Comment by junegunn** [comment]
I think I fixed the problem. Please update (git pull and rerun the install script) and let me know how it goes.

**Comment by dmos62** [comment]
Yes you have. Thank you. As far as I can tell everything works like it should.
