### ISSUE TITLE
fzf-cd-widget no such file or directory

### ISSUE THREAD

**Issue by ruslaniv** [junegunn/fzf#1430]
- Category
    - [x] fzf binary
- OS
    - [x] Mac OS X
- Shell
    - [x] zsh

I have the following keybinding set:
`export FZF_ALT_C_COMMAND="cd ~/; bfs -type d -nohidden | sed s/^\./~/"  
`
When I press CTRL+C I get fzf prompt to start searching for a directory, the search successfully completes but after pressing enter to cd to a particular directory I get this message: 

`fzf-cd-widget:cd:9: no such file or directory: /path/to/directory `

Although the directory in question does exist. How can I troubleshoot this problem?

**Comment by junegunn** [comment]
It's because fzf-cd-widget expects to receive an expanded path from fzf, and pass it as the argument to `cd`. If the output contains unexpanded `~`, `cd` will fail (`cd "~"` vs. `cd ~`). Although there's no option to change the behavior, you can still redefine the function in your shell configuration file.

**Comment by junegunn** [comment]
Some pointers: https://stackoverflow.com/questions/3963716/how-to-manually-expand-a-special-variable-ex-tilde-in-bash

**Comment by rileyrg** [comment]
I'm having a similar issue and I'm afraid I don't really understand https://github.com/junegunn/fzf/issues/1430#issuecomment-449710553

How do I get alt-c and C-t to search from my $HOME directory?

`export FZF_ALT_C_COMMAND="cd ~ ; fdfind --type directory"`

doesnt work as the match from fdfind is relative to the directory I invoke Alt-C despite the cd ~.

This seems like a pretty common use case, but I cant find a solution as I dont really want to have to fully understand fzf and bash internal workings.
