### ISSUE TITLE
Suggestion for improved suggestions towards user input

### ISSUE THREAD

**Issue by kkoomen** [junegunn/fzf#1432]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [x] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

First of all: big +1 for the amazing project.

I couldn't find anything about it in the manual, wiki or docs, but is there a flag I can pass (or maybe it's built-in already, but it doesn't look like it) to keep track of what the user has selected the most of from all the suggestions and then put that file as the first suggestion the next time I do a search. 

So for example: I have a project running in Drupal where I am searching for a `template.php` file, but I do get these suggestions:
```
modules/contrib/libraries/tests/themes/libraries_test_theme/template.php
modules/contrib/service_links/template.php
themes/ofcorp_redesign_theme/template.php
themes/basetheme/template.php
themes/corporate/template.php
> themes/aurora/template.php
```

and the one I am always selecting from those suggestions is `themes/ofcorp_redesign_theme/template.php` so I think an improvement would be the next time I am doing the same query, the `themes/ofcorp_redesign_theme/template.php` should be the first one, like this:

```
modules/contrib/libraries/tests/themes/libraries_test_theme/template.php
modules/contrib/service_links/template.php
themes/basetheme/template.php
themes/corporate/template.php
themes/aurora/template.php
> themes/ofcorp_redesign_theme/template.php
```

If this is not built-in yet into the module, I would like to make some time to create this or let you guys implement this. I think this would be a good idea to give better suggestions. Items should be prioritized as well based on the amount of times they have been selected. The higher the amount, the higher it should appear in the suggestions list.

Let me know what  you guys think of this and if this does/doesn't exist yet.

**Comment by junegunn** [comment]
Hi, fzf is designed to be a simple text filter, it does not know the meaning or the context of the lines it's processing. The behavior you described can be implemented outside of fzf. i.e. Remembering the latest selection and feeding it as the first line in the next invocation. But, the desired behavior is highly dependent on the context or the user's preferences and it's not easy to provide a general solution, so I'm not going to try.

A few alternative approaches I can suggest:
- Type in a more descriptive query string such as `tate`, `tcte` or `tem ta`...
- Use `:Buffers` command from [fzf.vim project](https://github.com/junegunn/fzf.vim)
