### ISSUE TITLE
unable to run install script on amazon linux without using dos2unix to remove dos line endings

### ISSUE THREAD

**Issue by baron** [junegunn/fzf#1435]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

Ran the install instructions on Amazon Linux (amazon-linux-ami/2018.03)

git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
 ~/.fzf/install

Output:
: No such file or directory

Fix:
Install dos2unix and convert files

dos2unix ~/.fzf/install
dos2unix ~/.fzf/uninstall
dos2unix ~/.fzf/shell

Unfortunately git diff is completely blank even though the files show up as modified.

**Comment by i-am-eva** [comment]
Checkout on my system does not include incorrect line ending (osx), what does `git config --get core.autocrlf` return? 

```
~/fzf-issue-1435
λ git clone --depth 1 https://github.com/junegunn/fzf.git
Cloning into 'fzf'...
remote: Enumerating objects: 95, done.
remote: Counting objects: 100% (95/95), done.
remote: Compressing objects: 100% (88/88), done.
remote: Total 95 (delta 4), reused 22 (delta 2), pack-reused 0
Unpacking objects: 100% (95/95), done.

~/fzf-issue-1435
λ cd fzf

~/fz/fzf master ✔
λ ls
BUILD.md       Makefile       doc/           main.go        src/
CHANGELOG.md   README-VIM.md  glide.lock     man/           test/
Dockerfile     README.md      glide.yaml     plugin/        uninstall*
LICENSE        bin/           install*       shell/

~/fz/fzf master ✔
λ file install
install: Bourne-Again shell script text executable, ASCII text

~/fz/fzf master ✔
λ vim install

# in vim ...

:set ff

# => fileformat=unix

~/fz/fzf master ✔
λ git config --get core.autocrlf

~/fz/fzf master ✔
λ
```

**Comment by baron** [comment]
You're analysis was spot on.

It seems the server's git was set to "core.autocrlf=true"

Changed it to 
git config --global core.autocrlf false

and was able to run the install script without any trouble. Sorry for the trouble and thanks for this tool!
