### ISSUE TITLE
Segmentation fault on zsh tab completion

### ISSUE THREAD

**Issue by leafnode** [junegunn/fzf#1438]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [x] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

I've installed FZF into a VM from git, with commands suggested in README: git clone to `~/.fzf`, then run `~/.fzf/install`, installing all the features. After restarting the shell, I've tried a normal tab completion (no wildcards, just <tab> after a command), and I had a SSH connection to the VM dropped. I've connected again, increased ulimit for core file, tried the completion again, and I had a core file. I've put it into a debugger, and it said:
```
Core was generated by `-zsh'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  __wmemcmp_sse4_1 () at ../sysdeps/x86_64/multiarch/memcmp-sse4.S:1052
```

Distro: ubuntu 16.04
ZSH: zsh 5.1.1 (x86_64-ubuntu-linux-gnu) from distro package.

Let me know if I can provide any more details.

**Comment by leafnode** [comment]
update: no issues when using bash.

**Comment by leafnode** [comment]
another update: completion with `**` works fine

**Comment by leafnode** [comment]
yet another update: hitting <ctrl+i> dumps the core too.

**Comment by junegunn** [comment]
It's clearly an issue of zsh. Have you tried upgrading zsh? 5.1.1 is pretty old.

**Comment by leafnode** [comment]
In general, yes, it shouldn't dump core, yet it behaves this way with the configuration added by fzf. I know that it's not up to fzf to take care about old and (apparently) broken fzf, yet, I have to live with it as we run some projects on ubuntu 16.04, and if it'd be possible to derive a configuration that'd work with older and newer zsh's, it'd be awesome. I've filed this issue as maybe you are aware of the issue and know how to fix it, but if not, I'll try to pinpoint the problem.

**Comment by junegunn** [comment]
No, I was unaware of the issue, I'm a bash user. If you find a workaround, please consider opening a pull request, but I'm going to close this for now as it's really not an issue of fzf.

**Comment by zyf0330** [comment]
I use Tilix. I upgrade ubuntu 24.10 and kde 6, and then every time `fzf` execution makes the Tilix crashed and exit with segmentation fault. The Konsole doesn't have the same problem.
Finally, I see https://github.com/zsh-users/zsh-autosuggestions/issues/126.
I solve it by execute `source .zshrc` manually after opening Tilix window and zsh. Don't know why.
