### ISSUE TITLE
Option for Ctrl-R to use current command-line content as a search pattern [idea]

### ISSUE THREAD

**Issue by balta2ar** [junegunn/fzf#144]
Very often I reuse parts of commit messages from previous commands (history) in command line. zsh-autosuggestions helps me with that. For example, I type `hg ci` and it suggests `hg ci -m "RT123456 Some previous commit message"`. However, sometimes it doesn't suggest the right thing. That's when I press `Ctrl-R`.

I thought that when my command line already contains `hg ci` and I press `Ctrl-R` to search in the history, it would be handy to use what I've already typed as initial search pattern to avoid typing it again.

I have a feeling this might be useful. Do you think you could add an option to enable such behavior? I'm using zsh. Thank you.

**Comment by wellle** [comment]
I think that should be doable by using the `--query` flag.

**Comment by junegunn** [comment]
I like the idea, though I think it will be only possible on zsh, or maybe fish.. but I'm not really into that and growing weary of dealing with its non-standard stuff.

I'll look into it when I get some time. (I'm a bash user and honestly not really familiar with zsh stuff) Feel free to send me a PR if you feel like it.

**Comment by junegunn** [comment]
```sh
# CTRL-R - Paste the selected command from history into the command line
fzf-history-widget() {
  local selected
  if selected=$(fc -l 1 | fzf +s --tac +m -n2..,.. --query "$LBUFFER"); then
    num=$(echo "$selected" | head -1 | awk '{print $1}' | sed 's/[^0-9]//')
    LBUFFER=!$num
    zle expand-or-complete
  fi
  zle redisplay
}
zle     -N   fzf-history-widget
bindkey '^R' fzf-history-widget
```
Does this work? I tried to fix #142 as well.

**Comment by junegunn** [comment]
Committed the code. Please [upgrade fzf](https://github.com/junegunn/fzf#upgrading-fzf) and let me know if you see any issue.

**Comment by balta2ar** [comment]
Yes, it's awesome! Thank you very much! I'll start using it right away.
