### ISSUE TITLE
there is no space after completion when input |

### ISSUE THREAD

**Issue by zyf0330** [junegunn/fzf#1442]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [x] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

I have a file like `1.csv`, and enable fuzzy completetion. Then do these:
1. `ls csv<TAB>`, show `ls 1.csv <CURSOR>`
2. input `|`, show `ls 1.csv|<CURSOR>`

I hope `<SPACE>` appears before `|`.

**Comment by i-am-eva** [comment]
I believe this is the default behaviour of `zsh`'s completion. `fzf`'s auto completes are only triggered if you include a `**` before you press tab.

In fact if I use `ls 1**` and select via fzf, then adding a pipe *does not* shift the cursor backwards.

where `[]` is my cursor position,

```
~/fzf-issue-1442
λ zsh -f #start a fresh zsh with no config
shodan% ls 1[]<tab>
shodan% ls 1.csv [] # cursor has space
shodan% ls 1.csv|[] # behaves as issue describes
shodan% ls 1**[] # does not trigger FZF due to unconfigured zsh
shodan% ls 1.csv[]
```

```
~/fzf-issue-1442
λ ls 1**[]<tab>

# shows fzf ui, select file

~/fzf-issue-1442
λ ls 1.csv [] # after fzf we have a space

~/fzf-issue-1442
λ ls 1.csv |[] # typing pipe does not move cursor backwards
```
You should close this issue.

**Comment by i-am-eva** [comment]
I believe this is the default behaviour of zsh's completion. fzf's auto completes are only triggered if you include `**` before you press tab.

where [] is my cursor position,

```
~/fzf-issue-1442
λ zsh -f #start a fresh zsh with no config
host% ls 1[]<tab>
host% ls 1.csv [] # cursor has space
host% ls 1.csv|[] # behaves as issue describes
host% ls 1**[] # does not trigger FZF due to unconfigured zsh
host% ls 1.csv[]
```

In fact if I use ls 1** and select via fzf, then adding a pipe does not shift the cursor backwards.

```
~/fzf-issue-1442
λ ls 1**[]<tab>

# shows fzf ui, select file

~/fzf-issue-1442
λ ls 1.csv [] # after fzf we have a space

~/fzf-issue-1442
λ ls 1.csv |[] # typing pipe does not move cursor backwards
```
You should close this issue. Likely this is a feature of zsh to avoid issues when performing completion in the middle of long command lines.

**Comment by zyf0330** [comment]
You are right, this problem is from Zsh. I have tried with 'zsh -p'.

**Comment by zyf0330** [comment]
Now I find solution at https://superuser.com/a/613817/759512
