### ISSUE TITLE
fzf: allow trimmed url

### ISSUE THREAD

**Issue by tuyenpm9** [junegunn/fzf#1448]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

I trimmed url with this command (it's too long to display on screen)

    echo 'https://example.com' | awk -v len=10 -F '\t' 'BEGIN { OFS=FS  } { for (i=1; i<=NF; ++i) if (length($i)>len) $i = substr($i,1,len-3) "»"  }; 1'
    https:/»

Then I pipe the output to fzf, how to make fzf understand the original url, I then take some actions on the full url - e.g: open the url link.

**Comment by i-am-eva** [comment]
This sound similar to #1440 apparently its not possible

**Comment by junegunn** [comment]
Matching against hiddens part of the string (`--with-nth`) is not supported.
