### ISSUE TITLE
{q} in query is not always initially displayed when using fzf --query

### ISSUE THREAD

**Issue by notevenodd** [junegunn/fzf#1452]
Category: fzf binary
OS: Linux (and probably others too)
Shell: bash

Commands:
```
export INITIAL_QUERY="<SOMETHING HERE>"
fzf --preview 'printf "query: %s\nselection: %s" {q} {}' --query "$INITIAL_QUERY"
```
Expectation: Preview will always be displayed (even before the user types something in fzf)
Observed behaviour: The preview is initially displayed if and only if `$INITIAL_QUERY` makes a match

**Comment by junegunn** [comment]
61feee6 should fix the problem. Thanks for the report.
