### ISSUE TITLE
Reverse i-search prepends gibberish characters to selected command

### ISSUE THREAD

**Issue by bancron** [junegunn/fzf#1453]
- OS
    - [x] Mac OS X
- Shell
    - [x] bash

Hi,

I have a problem with using reverse i-search with fzf. Ctrl-R results in a list of commands rather than just one; that is working fine. However, when I hit enter, it prepends a bunch of gibberish which looks like color codes.

Searching for `source`:
```
^[[01;31m^[[K 2^[[m^[[K^[[01;31m^[[K4^[[m^[[K^[[01;31m^[[K4^[[m^[[K^[[01;31m^[[K1^[[m^[[K source ~/.bashrc
```

I have tried various settings of `FZF_DEFAULT_OPS`, notably `--ansi`. I am running version 0.17.5 (brew).

Any idea what's going on here?

Thanks!

**Comment by junegunn** [comment]
No idea. Can you still reproduce the problem without any other bash configuration?

```sh
bash --rcfile ~/.fzf.bash
```

**Comment by alexcusack** [comment]
@bancron running into this as well, were you ever able to resolve? 

@junegunn I was able to reproduce. 

```bash
:> bash --rcfile ~/.fzf.bash
bash-3.2$ echo test
test
# do reverse-i lookup, hit enter 
bash-3.2$ ^[[01;31m^[[K 2^[[m^[[K^[[01;31m^[[K6^[[m^[[K^[[01;31m^[[K8^[[m^[[K echo test
```

**Comment by bancron** [comment]
With `bash --rcfile ~/.fzf.bash` I don't encounter the issue.

**Comment by wiggzz** [comment]
I have this issue if I  `export GREP_OPTIONS='--color=always'`.

Not sure why this would affect fzf, but, I changed my grep options to `--color=auto` and it is working as expected again.

**Comment by alexcusack** [comment]
+1 worked for me!

**Comment by junegunn** [comment]
Whoa, you should **never** set `export GREP_OPTIONS='--color=always'`. It will break so many scripts that rely on grep.

```sh
export GREP_OPTIONS='--color=always'
vim "$(ls | grep . | head -1)"
```

Related: https://unix.stackexchange.com/a/69267/62171

**Comment by bancron** [comment]
So I don't have `GREP_OPTIONS` set anywhere.

However, `export GREP_OPTIONS='--color=auto'` makes it work correctly.

So, problem solved ¯\\\_(ツ)\_/¯ Thanks!
