### ISSUE TITLE
Keybindings don't works on Windows

### ISSUE THREAD

**Issue by Zer0Division** [junegunn/fzf#1454]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [x] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [ ] Mac OS X
    - [x] Windows
    - [x] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [ ] fish

If I press Ctrl+T in the shell, I get a character swap instead of the fzf prompt. It's unfortunate because this is a really useful feature.

**Comment by Khorkhe** [comment]
Ctrl+T is a bash keybinding to swap characters, facing the same issue with zsh under Linux

**Comment by junegunn** [comment]
The key bindings and fuzzy completion code we provide here are for Unix systems.
However, there are some third-party projects for Windows that you might want to try.
See: https://github.com/junegunn/fzf/wiki/Windows#powershell-support
