### ISSUE TITLE
Don't reload preview when new lines arrive

### ISSUE THREAD

**Issue by Synthetica9** [junegunn/fzf#1455]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [x] fish

Currently, when using fzf to view the output lines of a long-running command, the preview command is re-ran when new lines arrive from that command (and the scroll is lost).

Try, for instance:

```
seq 1000000 | pv -qL 20 | fzf --preview="seq 1 10000"
```

And try scrolling.

**Comment by junegunn** [comment]
Thanks for the report, fixed it.
