### ISSUE TITLE
Infinite loop trying to read from /dev/tty

### ISSUE THREAD

**Issue by blueyed** [junegunn/fzf#1456]
- Category
    - [x] fzf binary
    - [x] Vim
    - [x] Neovim
- OS
    - [x] Linux
- Shell
    - [x] bash  (used Zsh, but the same when using `bash` in this terminal window)
    - [x] zsh

fzf 0.17.5

Not sure how / what triggered this, but in a certain terminal window (using urxvt/rxvt-unicode) invoking `fzf` causes 100% CPU.

`strace` shows:

With Vim:
```
[pid 15569] read(3, "", 1)              = 0
[pid 15569] fcntl(3, F_GETFL)           = 0x8800 (flags O_RDONLY|O_NONBLOCK|O_LARGEFILE)
[pid 15569] fcntl(3, F_SETFL, O_RDONLY|O_LARGEFILE) = 0
[pid 15569] fcntl(3, F_GETFL)           = 0x8000 (flags O_RDONLY|O_LARGEFILE)
[pid 15569] fcntl(3, F_SETFL, O_RDONLY|O_LARGEFILE) = 0
[pid 15569] fcntl(3, F_GETFL)           = 0x8000 (flags O_RDONLY|O_LARGEFILE)
[pid 15569] fcntl(3, F_SETFL, O_RDONLY|O_NONBLOCK|O_LARGEFILE) = 0
```

There `kill -9` is needed, and it displays then:
```
Error running ( /usr/bin/zsh '/tmp/vaOUYHc/4' )|'fzf' --history '/home/user/.local/share/fzf-history/files'  '-m' '--prompt' '~/s/neomake/' --expect=ctrl-v,ctrl-x,ctrl-t --height=20 > /tmp
/vaOUYHc/3
```

With Neovim it displays the initial file list (which does not happen in Vim), and normal `kill` works, displaying no error.

It also happens with just running "fzf".  I can provide the `strace -f` output for that.

`fd 3` is `/dev/tty`.

`stty` displays:
```
speed 0 baud; line = 0;
-iexten
```

normal `stty`:
```
speed 38400 baud; line = 0;
iutf8
```

I could not reproduce it in another terminal window though with the same options, so this is not related maybe (but strange to have changed, and might indicate that e.g. Vim left some terminal settings in place when not finished cleanly (I've run Vader tests in this terminal window before)).

While this might be some issue with the terminal itself, fzf should not cause 100% CPU in this case.

**Comment by junegunn** [comment]
Is this still reproducible with the latest version of fzf?

**Comment by blueyed** [comment]
@junegunn I could not reproduce it back then in another terminal window even, and have since rebooted.. ;)

Let's close it - I've hoped that maybe somebody/you would know from what I had collected what might have gone wrong / could be improved back then.
