### ISSUE TITLE
Mojave warns that precompiled fzf is 32-bit

### ISSUE THREAD

**Issue by chdiza** [junegunn/fzf#1457]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

I use the prebuilt macOS binary of fzf (from junegunn/fzf-bin).  On macOS Mojave, the macOS periodically pops up a dialog box warning that fzf is 32-bit and that macOS will soon not allow 32-bit software.

Can there be a 64-bit-only precompiled binary release?

**Comment by chdiza** [comment]
Well, I don't have an amd processor in my machine, so I didn't download the `amd64` prebuilt binary.

**Comment by chdiza** [comment]
I used the `386` build.

**Comment by junegunn** [comment]
You should use that one. See https://github.com/golang/go/issues/3426, and https://en.wikipedia.org/wiki/X86-64
