### ISSUE TITLE
[bash] CTRL-R cannot handle multi-line commands

### ISSUE THREAD

**Issue by junegunn** [junegunn/fzf#146]
```sh
> echo 'foo
bar'
> <CTRL-R>
```

**Comment by D630** [comment]
This works for me:

```
shopt -s cmdhist
shopt -u lithist
```

and `-m` in 

```
bind '"\C-r": " \C-e\C-u$(HISTTIMEFORMAT= history | fzf +s --tac +m -n2..,.. | sed \"s/ *[0-9]* *//\")\e\C-e\er"'
```

**Comment by junegunn** [comment]
> and `-m`

So you mean, selecting both lines in fzf? I don't think it's a good solution to the problem, as there's no guarantee that both lines appear on the finder with some query string, not to mention that it's not straightforward for users to use.
