### ISSUE TITLE
FZF completion with existing tab completions

### ISSUE THREAD

**Issue by saamalik** [junegunn/fzf#1461]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [X] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [X] Linux
    - [X] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [X] bash
    - [X] zsh
    - [ ] fish

Kubernetes (_kubectl_) provides a rich set of tab completion functions, e.g: `source <(kubectl completion bash)`: 
```sh
complete -o default -o nospace -F __start_kubectl kubectl
```

Is there some special _completion_ which can get the results from the kubectl _completion_ but render them using _FZF_? e.g: `complete -F _fzf_magic_magic -o default -o bashdefault kubectl`

**Comment by junegunn** [comment]
No. There's no "automagic" way to transform a completion function to use fzf. It would be really nice, but I don't know if it's even possible. There are some kube utils that integrate with fzf, you might want to check them out.

- https://github.com/ahmetb/kubectx#interactive-mode
- https://github.com/arunvelsriram/kube-fzf

**Comment by dasl-** [comment]
@junegunn fyi it does seem possible to make zsh native autocompletion always use fzf. See this project: https://github.com/Aloxaf/fzf-tab

**Comment by junegunn** [comment]
@dasl- Thanks for reminding me. I'm not a zsh user, so I haven't tried.
