### ISSUE TITLE
usage confusing

### ISSUE THREAD

**Issue by E3D3** [junegunn/fzf#1462]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [x ] Etc.
- OS
    - [ ] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [x ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [ ] fish

I was used to *peco* and switched to "fzf" after discovering its nice preview option.

The usage in the README is very confusing. I had to read it many times to understand.
For example:
1) *fzf will launch interactive finder, read the list from STDIN, and write the selected item to STDOUT.
   find * -type f | fzf > selected*
What is the use of the redirection ? It outputs defaults to STDOUT so no **>** seems to be necessary.
2) *Without STDIN pipe, fzf will use find command to fetch the list of files excluding hidden ones. (You can override the default command with FZF_DEFAULT_COMMAND)
   vim $(fzf)*
Confusing is that in the example above it, you use the find command and a STDIN pipe, and then say that it also uses find without STDIN pipe. Maybe use another command than find in the first example, and explain which find-command is used without STDPIPE.
I also think its beter to say that it fetches the list of files **from the current directory** and explain what the example does e.g. something like: *Select a file (in the current directory) with fzf and open/execute it with vim*.
3) Using the above given vim-example since then is very confusing because vim has nothing to do with the explanation. E.g. under *layout* you give  examples like
   *vim $(fzf --height 40%)*
   Why not give as example *fzf --height 40%*
4)*Fuzzy completion for bash and zsh*
It took a while for me to find out that again this has nothing to do with *vim* or the by fzf modified *cd* and that it has become a feature of the terminal. E.g. *ls **<TAB>* also activates fzf.

I also have a question:
How to deactivate a key binding cq functions like *Alt-C", temporary or always. *FZF_CTRL_T_COMMAND=""* didn't work.

**Comment by junegunn** [comment]
Thanks for the suggestions, I'll think about them.

> How to deactivate a key binding cq functions like *Alt-C"

You can choose not to enable the key bindings during the installation process. However, if you want to disable not all, but only a subset of the bindings, you can *rebind* each one of them as you like. For example, if you use bash,

```sh
[ -f ~/.fzf.bash ] && source ~/.fzf.bash

# Remove bindings
bind -r "\C-t"

# Or, rebind to the original functions
bind '"\C-t": transpose-chars'
bind '"\C-r": reverse-search-history'
bind '"\ec": capitalize-word'
```

Similarly in zsh,

```sh
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

if [[ $- =~ i ]]; then
  bindkey '\ec' capitalize-word
fi
```

**Comment by E3D3** [comment]
I knew how to set a key binding but not how to remove one, nor could remember the orginal C-t binding (although I'm an Emacs-user). Now I see that the real key binding problem is with  [marker](https://github.com/pindexis/marker).
Thank you for the quick and clear reply, and of course for sharing the more than usefull fzf.
