### ISSUE TITLE
fzf-history-widget: fc:3: history events are in wrong order, aborted

### ISSUE THREAD

**Issue by manfredlotz** [junegunn/fzf#1465]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [x] Completion
 
- OS
    - [x] Linux

- Shell
    - [x] zsh
 

I'm often working on an older Debian system where I get
   fzf-history-widget: fc:3: history events are in wrong order, aborted
when searching history with Ctrl-R.

fzf is 0.17.5 (b46227d)

I'm not sure if this related to zsh being pretty old. zsh is zsh 4.3.17 (x86_64-unknown-linux-gnu)

Things work fine on my laptop which is Fedora 29, the same fzf version but an up to date zsh 5.6.2 (x86_64-redhat-linux-gnu)

Any idea where to dig deeper to find the cause of the problem? Thanks.

**Comment by junegunn** [comment]
Although not clearly documented, such old versions of zsh are not supported. Please use zsh 5.1 or higher.
