### ISSUE TITLE
Option to remove the numbers from "paste the selected command from history"

### ISSUE THREAD

**Issue by erusev** [junegunn/fzf#1470]
OS: MacOS
Shell: zsh

Paste the selected command from history (⌃R) shows a number on the left of each item:

![image](https://user-images.githubusercontent.com/184170/50742008-1acd1200-120e-11e9-925f-b5bf963d6a48.png)

In this screenshot, these numbers are 1887, 1886, 1885, etc.

It seems that these numbers reflect the recency of the command and I understand that this could be useful, but I'd love an option to remove them.

**Comment by junegunn** [comment]
I'm not interested in adding more options. Instead, I suggest that you override the implementation in your shell configuration file. Copy, paste, and change it to your needs.

https://github.com/junegunn/fzf/blob/5d16b288698ecec96080a5d576521d92550e78fd/shell/key-bindings.zsh#L66-L83
