### ISSUE TITLE
Ctrl-T hides current command line while showing fzf selector

### ISSUE THREAD

**Issue by zestyping** [junegunn/fzf#1473]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [x] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

When I type Ctrl-T, the current command is erased and replaced with the ugly string ``` `__fzf_select__` ``` while fuzzy selection is being performed.  For example, if I type this:

    host$ vi <Ctrl-T>

then my terminal looks like this:

    host$ `__fzf_select__`
    > 
    \ 5073/5073
    > a.txt
      b.txt
      c.txt
    ...

This is inconvenient because I can no longer see the context of the command I typed, `vi` in this case.  It also doesn't match typical completion behaviour where, if you hit `vi foo<Tab>`, you can still see the `vi foo` that you typed while you are presented with the list of completions.

So I looked for the binding for Ctrl-T in `key-bindings.bash`.  I use vi-mode, so the line that applies to me is this:

        bind '"\C-t": "\C-x\C-a$a \C-x\C-addi`__fzf_select__`\C-x\C-e\C-x\C-a0Px$a \C-x\C-r\C-x\C-axa "'

This seems very strange.  Why does this binding go through a complicated process of deleting my command line (`dd`), then running fzf, then re-pasting my command line (`0P`), all the while inserting and deleting lots of spaces (`$a ` and `x` and then `$a ` again and then `xa `)?

Clearly there must have been some intended purpose, but I can't figure it out.  This simpler binding seems to work just fine for me, and it doesn't hide my current command line:

    bind '"\C-t": "`__fzf_select__`\C-x\C-e\C-x\C-r"'

So I'm wondering, why couldn't fzf use this simpler binding?

**Comment by junegunn** [comment]
To avoid evaluating the other parts of the command.

Example 1:
```sh
alias ls='ls -G'
ls <CTRL-T>
```

Example 2:
```sh
echo $(ls) <CTRL-T>
```

Does this answer your question? Having said that, if you know better ways to handle this, feel free to let me know.

**Comment by jbriales** [comment]
I also agree the behavior above (hiding the current line) is quite annoying.
I saw that the autocompletion feature, i.e. `cat **<TAB>` behaves as we would like (showing everything starting at the next line).
I'm sorry, but I didn't understand the fundamental limitations why this cannot be done with Ctrl+T but it can with the autocomplete feature. More hints would be appreciated! :D
