### ISSUE TITLE
How to make Ctrl-T aware of input under current cursor position?

### ISSUE THREAD

**Issue by balalaXD** [junegunn/fzf#1475]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [X] Key bindings
    - [X] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [X] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [X] zsh
    - [ ] fish

Here is my config:
```
export FZF_DEFAULT_COMMAND='fd --type f'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
```
Run command `vim boooom<Ctrl-T>`, but the results is the same `vim <Ctrl-T>`, without aware of `boooom` :crying_cat_face:

**Comment by junegunn** [comment]
CTRL-T was not designed to examine the current command line.
Since you use zsh, see https://github.com/junegunn/fzf/wiki/Configuring-fuzzy-completion#dedicated-completion-key
