### ISSUE TITLE
[Feature] Display results with multiple columns

### ISSUE THREAD

**Issue by rockandska** [junegunn/fzf#1476]
- Category
    - [x] fzf binary
    - [x] Etc.
- OS
    - [x] Linux
- Shell
    - [x] bash
    - [x] zsh
    - [x] fish

Hi,

Not sure if many people will love it, but it will be really handy in my opinion to have an option to add the possibility to display the results split over multiple columns (kind of what zsh does for the auto complete).

Best regards,

**Comment by junegunn** [comment]
I'm not interested in adding the option, but you can try https://github.com/p-gen/smenu instead.

**Comment by rockandska** [comment]
thanks for the link, sadly, smenu doesn't provide a search filter as fzf does.
It makes me sad seeing all this space unused on right when you have many results and having them displayed on multiple columns will help in selection :cry:

**Comment by junegunn** [comment]
It is not trivial to implement the new layout, I just don't have time or energy to do it myself.

If you're on tmux, using `fzf-tmux` can be an option. e.g. `fzf-tmux -r 20%`
