### ISSUE TITLE
Feature request: just match like only match

### ISSUE THREAD

**Issue by tsuyoshicho** [junegunn/fzf#1479]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [x] Mac OS X
    - [x] Windows
    - [x] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [x] bash
    - [x] zsh
    - [x] fish

## Feature request:
fzf currently support `--select-1        Automatically select the only match` like this

```console
> cat file
abc
def

> fzf -1 -q ab
 -> abc
```

request new feature just like this

```console
> cat branch
work
work-test

> fzf -just -q work
 -> work
# currently match multiple line to start select UI , new opt if just match one string, select done
#  It may be necessary Automatically select at -1
```

Usage

```console
> cat branch
work
work-test

# (checkout fzf alias , completion support)
> git co wo
 -> fzf start
> git co work
 -> direct checkout work branch
```

On the premise that there is supplementation, follow-up complements and follow up with miss spell or incomplete, respecting the fixed branch (string).

How about that?

**Comment by junegunn** [comment]
Thanks for the suggestion, but the use case you described is fairly niche and I don't think we need a new option for that. I can imagine that you can easily implement the scheme in a shell function.

```sh
match=$(git branch | sed 's/^..//' | grep foo | head -1)
if [ -n "match" ]; then
  echo "$match"
else
  # Start fzf
fi
```

**Comment by tsuyoshicho** [comment]
Okay.
Suggestion thanks a lot.
