### ISSUE TITLE
Build fails on Debian 9

### ISSUE THREAD

**Issue by vext01** [junegunn/fzf#1485]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

```
$ make release
GOARCH=386 go build -a -ldflags "-X main.revision=5d16b28 -w -extldflags=" -tags "" -o target/fzf-linux_386
main.go:3:8: cannot find package "github.com/junegunn/fzf/src" in any of:
        /usr/lib/go-1.7/src/github.com/junegunn/fzf/src (from $GOROOT)
        ($GOPATH not set)
Makefile:98: recipe for target 'target/fzf-linux_386' failed
make: *** [target/fzf-linux_386] Error 1
```

**Comment by cevhyruz** [comment]
modules are only supported for version 1.11.x. upgrade your go installation and it should work just fine.
