### ISSUE TITLE
Error in vim: Error running 'fzf'  '-m' '--prompt' '~/g/gr/' --expect=ctrl-v,ctrl-x,ctrl-t --height=26

### ISSUE THREAD

**Issue by drhayes** [junegunn/fzf#1487]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [X] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [X] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [X] zsh
    - [ ] fish

When I try to execute `:Files` in vim, I get this error:

    Error running 'fzf'  '-m' '--prompt' '~/g/gr/' --expect=ctrl-v,ctrl-x,ctrl-t --height=26 > /tmp/vYXgRPo/1

The tmpfile in that path is empty. `fzf` is available within my shell. I am running the kitty terminal emulator.

I don't know if it's good data, but when I tested my setup just inside of `urxvt` I was able to use the `:Files` command. I exited `urxvt` with `CTRL+D`, re-opened it, and now could not use the `:Files` command again. Same error as above.

**Comment by lungten** [comment]
@drhayes I am also having the same problem with the same environment except my terminal emulator is Konsole.

```
Error running '/home/user/.vim/pack/bundle/start/fzf/bin/fzf'  '--multi' '--prompt' '~/P/directory/' --expect=ctrl-v,ctrl-x,ctrl-t --height=20 > /tmp/vr3O5Ye/13
```

I have a shortcut `Ctrl-p` bound to `FZF` inside Vim and it used to work fine until few days ago. I see this error from time to time but if I try to invoke FZF again it works. This happens randomly. I even tried reinstalling FZF but doesn't help.

**Comment by drhayes** [comment]
Yeah, that's precisely my setup. In my case it happens if I invoke it as `:Files` or via my shortcut. From my `.vimrc`:

    nnoremap <c-p> :Files<CR>
    inoremap <c-p> <esc>:Files<enter>

Interestingly, `:GFiles` still works. That might be my workaround since the files under version control are usually the ones I care about. ( =

**Comment by lungten** [comment]
There's another issue reported here:
https://github.com/junegunn/fzf/issues/1486

I learned from this that the problem could be because of the recent kernel update on Ubuntu 18.04 (my OS).

**Comment by junegunn** [comment]
Closing since #1486 is resolved. If this is a separate issue, please leave a comment.
