### ISSUE TITLE
Vim plugin error Ubuntu 18.04

### ISSUE THREAD

**Issue by anoopd** [junegunn/fzf#1488]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [x] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

I have been using the fzf vim plugin for sometime . Updated my Ubuntu to the latest LTS 18.04 and still it was working fine . But from today onward it is showing the error . 

    Error running cd '/var/www/html/oopsandbox' && LINES=33 COLUMNS=136 '/home/anoopd/.fzf/bin/fzf- 
    tmux' -r20% - -- --color=bg+:0,bg:8,spinctrl-t  
    /tmp/vujPWsu/19:10,info:9,pointer:2,marker:2,fg+:12,prompt:2,hl+:2 '-m' '--prompt' '/v/w/h/oopsandbox/' 
    --expect=ctrl-v,ctrl-x,
    Press ENTER or type command to continue

if i change the row in vimrc `let g:fzf_layout={'down':'~40%'}` to `let g:fzf_layout={'right':'~40%'}` there is no error but the fzf window takes the full screen and does not move to right side either .

I removed the plugin using `PlugClean` and reinstalled , but the error persists .

**Comment by junegunn** [comment]
Possibly related: https://github.com/junegunn/fzf/issues/1486#issuecomment-459091653
