### ISSUE TITLE
Allow only the current query string to be selected 

### ISSUE THREAD

**Issue by nohandles** [junegunn/fzf#1491]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

I am trying to mimic the behavior of the address/search bar found in modern browsers in that the default selection is the query string. In this situation the user has the option of navigating to a suggestion using the arrow keys but is able to select nothing from the list by navigating back to the bar itself - as it stands I see no way of obvious way of doing this. 

I thought to perhaps have the current query string somehow piped into the list as the user types - this would have the desired affect as it would be best matched entry at all times and would sit right above/below the input box. I am not sure if fzf is capable of dynamically updating the list in this way, are you able to offer any suggestions on how I might achieve this? 

edit: spelling.

**Comment by junegunn** [comment]
fzf does not support the use case. Alternatively, you can set up a key binding for printing the current query string so that the user can choose it or the first match.

```sh
fzf --bind 'ctrl-x:print-query'
```

**Comment by vivekkalyan** [comment]
Would this be something you would accept as a PR? I am especially interested in implementing in for the vim plugin.

**Comment by junegunn** [comment]
You might want to experiment with `reload` action. See man page for details.

**Comment by vivekkalyan** [comment]
thanks! works for my intended usecase like a charm!
