### ISSUE TITLE
C-R doesn't work in bash with the Debian sid packaged version

### ISSUE THREAD

**Issue by fishy** [junegunn/fzf#1493]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [x] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

I recently switched from the vim managed version of fzf (vim-plug) to the packaged version in Debian Sid. Everything works except the C-R keybinding in bash. C-T still works in bash, and C-R works in fish.

With the Debian packaged version I use this line in my `~/.bashrc`:

```
source /usr/share/doc/fzf/examples/key-bindings.bash
```

While before I used this line:

```
[ -f ~/.fzf.bash ] && source ~/.fzf.bash
```

and inside `~/.fzf.bash` the keybinding part is:

```
source "/home/fishy/.fzf/shell/key-bindings.bash"
```

I did a diff and the two keybinding files are exactly the same.

When hitting C-R on bash with the Debian packaged version, I got this line instead:

```
 ^E __fzf_history__fzf_history__`
```

**Comment by vimirror** [comment]
I am guessing a vi confliction here.

This is a temporary and not a wanted solution but commenting out this line from your readline initialization file should do the trick.

`set editing-mode vi`

**Comment by junegunn** [comment]
I have no idea what's going on here but if the issue is indeed related to the vi mode, then note that the README page mentions this:

> If you use vi mode on bash, you need to add `set -o vi` *before* `source ~/.fzf.bash` in your .bashrc, so that it correctly sets up key bindings for vi mode.

```sh
[[ $- == *i* ]] && set -o vi
[ -f ~/.fzf.bash ] && source ~/.fzf.bash
```

And if I'm not mistaken, `.inputrc` is evaluated before `.bashrc`, so having `set editing-mode vi` in `.inputrc` (instead of `set -o vi` in `.bashrc) should work too.

**Comment by vimirror** [comment]
Works;

1) Set none.

2) Set both;
     --> `set editing-mode vi` in .inputrc
     --> `set -o vi` in .bashrc before `source ~/.fzf.bash`

3) Set only on .bashrc;
     --> no mode setting in .inputrc
     --> `set -o vi` in .bashrc before `source ~/.fzf.bash`

No luck;

1) Set only on .inputrc;
     --> `set editing-mode vi` in .inputrc
     --> no mode setting in .bashrc

**Comment by fishy** [comment]
Confirmed that if I add `set -o vi` line before the `source` line, everything works fine (before I have `set editing-mode vi` in `~/.inputrc` so I don't need `set -o vi` inside my `.bashrc`). I think `.inputrc` is probably evaluated after `.bashrc`?
