### ISSUE TITLE
how use fzf with /usr/share/applications/uxterm.desktop files

### ISSUE THREAD

**Issue by soloturn** [junegunn/fzf#1494]
how would one use fzf so it considers the contents of *.desktop files? to give an example how uxterm could be found
$ cat /usr/share/applications/uxterm.desktop 
```
[Desktop Entry]
Name=UXTerm
#GenericName=Terminal
Comment=standard terminal emulator for the X window system
Exec=uxterm
Terminal=false
Type=Application
Encoding=UTF-8
Icon=xterm-color_48x48
Categories=System;TerminalEmulator;
Keywords=shell;prompt;command;commandline;cmd;
```

**Comment by dkrieger** [comment]
`find /usr/share/applications -name '*.desktop' | awk -F'=' '$1~/^Name$|^Exec$/ {ORS="\t";print $2}END{printf "\n"}' | xargs cat | fzf |  awk -F$'\t' '{print $2}'`

disclaimer: that specific oneliner is untested, but the concept works. Assumes Name appears before Exec
