### ISSUE TITLE
Add support for ANSI color codes

### ISSUE THREAD

**Issue by junegunn** [junegunn/fzf#150]
(Previously: #148)

Interpret ANSI color codes from the input.

### Why?

Because... colors.

#### Use cases

- https://github.com/D630/fzf-fs
- https://github.com/peco/peco/issues/188

#### `CLICOLOR_FORCE=1 ls -al | fzf`
![fzf-ls](https://cloud.githubusercontent.com/assets/700826/6714463/bae03e64-cddb-11e4-9be1-92a237140d78.png)

#### `CLICOLOR_FORCE=1 ls -al | fzf --ansi`
![fzf-ansi-ls](https://cloud.githubusercontent.com/assets/700826/6714465/bae23afc-cddb-11e4-802e-67795caf821a.png)

#### `screenshotTable.sh | fzf --ansi`
![screenshot-table](https://cloud.githubusercontent.com/assets/700826/6714464/bae0daa4-cddb-11e4-9630-0cb7157d8498.png)

### Then, why hesitate?

- Code complexity
- Performance overhead in reader (*how much?*)
- Increased memory footprint for large input (> 1M items)
- A typical command-line program suppresses ANSI color codes when its output is redirected
    - Must explicitly enable colors.
        - OSX: `CLICOLOR_FORCE=1 ls -al`
        - Linux: `ls --color=always -al`
- :sleepy: 

### TBD

- Should fzf remove ANSI codes from its output?
    - Probably. It might make it less flexible, but more convenient/suitable for most cases.

**Comment by junegunn** [comment]
## Simple benchmark

### Reader performance

No noticeable difference when `--ansi` option is not used (good!). Using `--ansi` makes reader about 4-times slower, but it's unrealistic to have 3.5M-line input with ansi colors anyway, so I think it's okay.

```
> wc -l list5
3516470 list5

> time cat list5 | ./fzf-0.9.4-linux_amd64 -f '' > /dev/null
real    0m7.361s
user    0m8.048s
sys     0m1.541s

> time cat list5 | ./fzf-linux_amd64 -f '' > /dev/null
real    0m7.175s
user    0m8.105s
sys     0m1.404s

> time cat list5 | ./fzf-linux_amd64 -f '' --ansi > /dev/null
real    0m27.470s
user    0m32.565s
sys     0m2.527s
```

### Memory footprint

Memory footprint is increased by about 10% even when `--ansi` option is not used, this is due to the additional field in Item struct.

```
> memsz() { pmap -x $(ps -ef | grep ./fzf- | awk '{print $2}') | tail -1 | awk '{print $4 / 1024.0 "MB"}'; }

> # cat list5 | ./fzf-0.9.4-linux_amd64
> memsz
1300.75MB

> # cat list5 | ./fzf-linux_amd64
> memsz
1418.79MB

> # cat list5 | ./fzf-linux_amd64 --ansi
> memsz
1767.57MB
```

**Comment by junegunn** [comment]
Wow, thanks to d94dfe, the initial memory footprint is now 751MB w/o `--ansi` and 1319MB with `--ansi`. This no longer seems like an issue.

**Comment by junegunn** [comment]
![fshow](https://cloud.githubusercontent.com/assets/700826/6801581/6265b4ae-d26c-11e4-87de-5421a1be8f31.gif)

```sh
# fshow - git commit browser
fshow() {
  local out sha q
  while out=$(
      git log --graph --color=always \
          --format="%C(auto)%h%d %s %C(black)%C(bold)%cr" |
      fzf --ansi --multi --no-sort --reverse --query="$q" --print-query); do
    q=$(head -1 <<< "$out")
    while read sha; do
      [ -n "$sha" ] && git show --color=always $sha | less -R
    done < <(sed '1d;s/^[^a-z0-9]*//;/^$/d' <<< "$out" | awk '{print $1}')
  done
}
```

**Comment by unphased** [comment]
This is amazing, could you comment on how I could get this working?

**Comment by junegunn** [comment]
The most recent version of `fshow` can be found [here](https://github.com/junegunn/dotfiles/blob/c6959cd4f/bashrc#L283-L303).

Just put it in your .bashrc/.zshrc and type in `fshow` in a git repository.

**Comment by m42e** [comment]
Is there a plan to enable this in the ruby version? I'm stuck to Cygwin and cannot get the go version running anyhow.

**Comment by junegunn** [comment]
No, the required code change is non-trivial, and I no longer maintain the ruby version. I wonder if it's possible to build the go version on Cygwin, if someone can help me on Windows (or cygwin) support, that'd be super.
