### ISSUE TITLE
Keep using ANSI color codes when --with-nth provided

### ISSUE THREAD

**Issue by sudo-nice** [junegunn/fzf#1500]
i
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish
---
Let's assume the directory structure:
```
.
└── 1
    └── 2
        └── file.rb
```
And let's assume we have LS_COLORS set to colorize `*.rb` files, so if we run
```sh
ls --color=always 1/2/file.rb | fzf --ansi
```
...fzf will colorize the string `1/2/file.rb`.

**But** if we run it like below:
```sh
ls --color=always 1/2/file.rb | fzf --ansi --delimiter / --with-nth 3..
```
...then we see `file.rb` with no color.

Is it possible to preserve coloring even with `--delimiter | --with-nth` options bundle?

---
fzf:
0.17.5 (b46227d)

**Comment by junegunn** [comment]
Can you check if the above commit in devel branch fixes the problem?

**Comment by sudo-nice** [comment]
Works like a charm, thank you very much!

**Comment by junegunn** [comment]
Thanks for the confirmation. The fix will be included in the next release.
