### ISSUE TITLE
alias vf="vim $(fzf)" can't work!

### ISSUE THREAD

**Issue by ppnman** [junegunn/fzf#1501]
If I write  `alias vf="vim $(fzf)"` into my zshrc, the command `vim $(fzf)` will run automatically whenever I open a new terminal.
What should I do?

**Comment by junegunn** [comment]
Use single quotes to avoid immediate evaluation: `alias vf='vim $(fzf)'`

**Comment by ppnman** [comment]
Thanks for your good answer! @junegunn

**Comment by UltiRequiem** [comment]
Thanks!
