### ISSUE TITLE
vi keymap for the finder

### ISSUE THREAD

**Issue by marcopaganini** [junegunn/fzf#1505]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [x] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [ ] fish

It would be nice to have a "vi keymap" in the fzf finder screen. If set, we would be able to use the traditional vi movement keys (HJKL) and use "/" to start a fuzzy search. As a heavy vi user, I'd love not having to take my hands out of the main keyboard to navigate in the finder. :)

**Comment by junegunn** [comment]
Thanks for the suggestion, but I think it's overkill. CTRL-J/K are already good enough for those who don't want to leave "the main row".

**Comment by thjbdvlt** [comment]
it's possible to achieve this with `fzf --bind="..."`

for example, for a typical vimlike thingi (quotes may be missing, don't copy-paste this):

```bash
fzf \
    --bind=j:down,k:up,s:jump,p:toggle-preview \
    --bind=h:backward-char,l:forward-char,e:forward-word,b:backward-word \
    --bind=d:clear-query \
    --bind='y:execute(echo {} | xsel -b)' \
    --bind=E:preview-half-page-down,U:preview-half-page-up \
    --bind=c:cancel,x:forward-char+backward-delete-char \
    --bind=X:backward-delete-char \
    --bind=start:enable-search+unbind(e,j,s,p,h,l,é,b,d,y,E,U,c,x,X,i,a,A,I)  \
    --bind=i:enable-search+unbind(j,k,s,p,h,l,e,b,d,y,E,U,c,x,X,i,a,A,I) \
    --bind=a:enable-search+unbind(j,k,s,p,h,l,e,b,d,y,E,U,c,x,X,i,a,A,I)+forward-char \
    --bind=A:enable-search+unbind(j,k,s,p,h,l,e,b,d,y,E,U,c,x,X,i,a,A,I)+end-of-line \
    --bind=I:enable-search+unbind(j,k,s,p,h,l,e,b,d,y,E,U,c,x,X,i,a,A,I)+beginning-of-line \
    --bind=esc:disable-search+rebind(j,k,s,p,h,l,e,b,d,y,E,U,c,x,X,i,a,A,I) \
```

ive made an ugly script, sometimes ago, that generates that bindings from a config file. [repo is here](https://github.com/thjbdvlt/fzf-vi-mode) if someone is interested.

:-)
