### ISSUE TITLE
[Feature Request] Is there any way to have fzf's input filtered by something other than newline?

### ISSUE THREAD

**Issue by lanza** [junegunn/fzf#1507]
- [x] fzf-binary

fzf's man page has

       -x, --extended
                Extended-search mode. Since 0.10.9, this is enabled by default. 
        -e, --exact
                Enable exact-match

and I have a script that autocompletes command options via something like `cat file | fzf | awk '{print $1}'` which I trigger on the command line like with ^X^O (like omni completion in vim). Currently, I have to concatenate all these lines to

        -x, --extended - Extended-search mode. Since 0.10.9, this is enabled by default. 
        -e, --exact - Enable exact-match

for fzf to be able to split this information properly.

Unfortunately, this makes the fzf popup much more difficult to read as well as making this process much more cumbersome to maintain. 

Is there any way to set the line filter as some magic character here so that `fzf` will display the entries as the multiline chunks?

**Comment by junegunn** [comment]
No, fzf does not support multi-line entries. Adding support for it is going to be a huge amount of work.
