### ISSUE TITLE
fzf binary for directories

### ISSUE THREAD

**Issue by haji-ali** [junegunn/fzf#1508]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

Is there a way to call the fzf binary with an option to search for directories only?
I use fzf in my emacs setup and I would like to have a command to open directories with dired.

**Comment by junegunn** [comment]
fzf is just an interactive filter, it's up to you to feed a list of directories to fzf. Please read usage section of the documentation: https://github.com/junegunn/fzf#usage
