### ISSUE TITLE
Error E684 when attempting to open selected file

### ISSUE THREAD

**Issue by typhooncamel** [junegunn/fzf#1509]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [x] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

I've been trying to set up a command that allows me to search the contents of files _in a specific folder_. I've added this to my init.vim:

```
command! -bang -nargs=* Rg
  \ call fzf#vim#grep(
  \   'rg --line-number --heading --color always --smart-case '.shellescape(<q-args>) . ' ~/Documents/', 1,
  \   <bang>0 ? fzf#vim#with_preview('up:60%')
  \           : fzf#vim#with_preview('right:50%:hidden', '?'),
  \   <bang>0)
```

The file searching works well, but then selecting a file will not open it, throwing up an error:

```
Error detected while processing function 7[38]..<SNR>37_callback:
line 21:
vim(let):E684: list index out of range: 1
```

I imagine it has to do with the `1` after the path I put in. Depending on whether I choose a file in the list, or a line within a file, the index in the error message can change.

I am quite clueless about Vimscript so apologies if I'm making a stupid mistake.

**Comment by mars90226** [comment]
The second argument of `fzf#vim#grep()` is `with_column`, which is used to tell fzf if the grep output contain column. If `with_column` is 1, you need to add `--column` flag to tell ripgrep to output column.

**Comment by typhooncamel** [comment]
Thanks for pointing that out. However, either adding the `--column` flag or removing the `1` both lead to errors when trying to open a file (the former to the same error as above, the latter returning
`
Vim(let):E728: Using a Dictionary as a Number
`.

**Comment by junegunn** [comment]
In addition to what @mars90226 suggested, you need to use `--no-heading` to include file path in each line, so that fzf can see it.

**Comment by typhooncamel** [comment]
Thank you @junegunn. However, when I add the `--no-heading` flag, it does not show up any search results. The current code is

```
command! -bang -nargs=* Rg
    \ call fzf#vim#grep(
    \     'rg --line-number --noheading --color always --smart-case '.shellescape(<q-args>) . ' ~/Documents/', 1,
    \     <bang>0 ? fzf#vim#with_preview('up:60%')
    \             : fzf#vim#with_preview('right:50%:hidden', '?'),
    \     <bang>0)
```

**Comment by junegunn** [comment]
Your command has a typo.
