### ISSUE TITLE
FZF with Ag not ignoring node_modules

### ISSUE THREAD

**Issue by redreceipt** [junegunn/fzf#1511]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

`fzf` with `ag` is not ignoring my `node_modules` directories.

*`.bash_profile`*
```sh
# fzf
# to completely uninstall, use /usr/local/opt/fzf/uninstall
[ -f ~/.fzf.bash ] && source ~/.fzf.bash
export FZF_DEFAULT_COMMAND='ag --hidden --ignore .git --ignore node_modules --ignore Library -g ""'
```

*output of `fzf`*

![screen shot 2019-02-28 at 9 50 18 am](https://user-images.githubusercontent.com/2659478/53574815-53b6a280-3b3e-11e9-8cf1-24fc51f4f4e6.png)

**Comment by junegunn** [comment]
Fuzzy completion and CTRL-T do not use $FZF_DEFAULT_COMMAND for various reasons. You have to separately configure them.

https://github.com/junegunn/fzf#key-bindings-for-command-line
https://github.com/junegunn/fzf#fuzzy-completion-for-bash-and-zsh

**Comment by redreceipt** [comment]
So how do I ignore directories?

**Comment by MatthewWid** [comment]
For those coming from Google, CTRL-T uses `FZF_CTRL_T_COMMAND` instead, so you just need to copy `FZF_DEFAULT_COMMAND` to it to get it to use the same command:

```bash
export FZF_DEFAULT_COMMAND="your custom command here"
export FZF_CTRL_T_COMMAND=$FZF_DEFAULT_COMMAND
```
