### ISSUE TITLE
How can I refresh the files/directories?

### ISSUE THREAD

**Issue by chrism2671** [junegunn/fzf#1513]
- [X ] Vim
- OS
    - [ X] Linux
- Shell
    - [X ] bash

Simple question- sometimes fzf doesn't pick up newly created files. Is there a shortcut to refresh fzf's view of the filesystem?

**Comment by junegunn** [comment]
> sometimes fzf doesn't pick up newly created files

Maybe you created a new buffer and didn't save it to disk? fzf is an external process so it cannot see files that are not persisted on disk.

It depends on the source command used, but by default fzf always scans the file system.

Please read https://github.com/junegunn/fzf#usage

**Comment by mnaei** [comment]
Same issue. I can bring up the file with :e command but not :GFiles. This is on a mac with zsh.
