### ISSUE TITLE
Possible to use Cmd + R on MacOS?

### ISSUE THREAD

**Issue by spjspjspj** [junegunn/fzf#1515]
- Category
    - [x ] fzf binary
    - [ ] fzf-tmux script
    - [x ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [ x] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [x ] bash
    - [x ] zsh
    - [ ] fish

It would be great if possible to use Cmd + R instead of Ctrl + R on MacOS. Thanks!

**Comment by junegunn** [comment]
Configure your terminal emulator (e.g. iterm2) to remap Command key to control key.
