### ISSUE TITLE
.fzf.bash might generate PATH with empty component

### ISSUE THREAD

**Issue by dfn-certling** [junegunn/fzf#1517]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

If $PATH is empty, the generated script at .fzf.bash creates a PATH with an empty first component by
```
export PATH=$PATH:...
```
An empty component is interpreted by bash to look in the current directory (see man bash entry for PATH), so the above will instruct bash to always look for any executable in the current directory first.

In order to only append the fzf path to the existing one, above line should read
```
export PATH=${PATH:+${PATH}:}...
```
This way if PATH is set, it is expanded to `$PATH:` otherwise to the empty string and the empty component in PATH is not created.

**Comment by junegunn** [comment]
Good suggestion, fixed in devel branch. Thanks.
