### ISSUE TITLE
Problem with custom _fzf_complete_ function

### ISSUE THREAD

**Issue by barjeshbarry** [junegunn/fzf#1518]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

I have written the following function in the .bashrc but it's not working.

`

 _fzf_complete_git() { 
 
       ARGS="$@"
        local branches
        branches=$(git branch)
        if [[ $ARGS == 'git co'* ]]; then
            _fzf_complete "--reverse --multi" "$@"  < <(
                echo "$branches" 
            )
        else
            eval "zle ${fzf_default_completion:-expand-or-complete}"
        fi
}
[ -n "$BASH" ] && complete -F _fzf_complete_git -o default -o bashdefault git

`

Note: $BASH is /bin/bash

On the command prompt when I type git co**{tab}, it shows me the following:
`
git co**{tab}
>co
`
Only when I remove 'co', it displays all the branches I have.

Secondly, after selecting a branch, the 'co' from the command prompt disappears.
`
$git {selected branch}
`
Please see what's going wrong.

The code example is taken from the following link:

https://github.com/junegunn/fzf/wiki/Examples-(completion)

(Sorry for the bad formatting. I could not get it right)

**Comment by junegunn** [comment]
I didn't write it the example on the wiki page, but it is for zsh. I should mention that on the page.

**Comment by barjeshbarry** [comment]
@junegunn Could you please point me to some code/documentation which I can use to make it work in bash?

**Comment by junegunn** [comment]
Well, it's basically a bash completion function followed by `_fzf_complete` at the end. You should be able to find the reference manual on bash completion on Google.

Having said that, git is a very complicated program with many subcommands and it's not easy to write a decent completion function for it and I'm not sure if it's a good idea to write one from scratch.

So my advice is that you use [the official completion package](https://github.com/git/git/blob/master/contrib/completion/git-completion.bash) and additionally use dedicated key bindings for eacg git object as shown here: https://junegunn.kr/2016/07/fzf-git/

The latest source code can be found here: https://gist.github.com/junegunn/8b572b8d4b5eddd8b85e5f4d40f17236

**Comment by ebkalderon** [comment]
I found an incredibly hacky solution to this and documented it here, if you're interested: https://github.com/junegunn/fzf/issues/3169#issuecomment-1962253127
