### ISSUE TITLE
Install script failes after installing via brew

### ISSUE THREAD

**Issue by engelju** [junegunn/fzf#1519]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

---

- I installed fzf via `brew install fzf`
- After that I wanted to install the key bindings and fuzzy completions (per the installation instructions) via the installation script:
```
 10:01:11 ~ $ $(brew --prefix)/opt/fzf/install
Downloading bin/fzf ...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   617    0   617    0     0   1083      0 --:--:-- --:--:-- --:--:--  1086
100 1020k  100 1020k    0     0   674k      0  0:00:01  0:00:01 --:--:-- 1614k
  - Checking fzf executable ... dyld: Library not loaded: /usr/local/opt/readline/lib/libreadline.7.dylib
  Referenced from: /usr/local/bin/awk
  Reason: image not found
Error:
  - Invalid binary !!!
Building binary (go get -u github.com/junegunn/fzf) ... # golang.org/x/sys/unix
/var/folders/jf/fmw70wxd6wx_610ql5wfqvl80000gn/T/fzf-gopath/src/golang.org/x/sys/unix/ioctl.go:18: undefined: runtime.KeepAlive
/var/folders/jf/fmw70wxd6wx_610ql5wfqvl80000gn/T/fzf-gopath/src/golang.org/x/sys/unix/ioctl.go:28: undefined: runtime.KeepAlive
Failed to build binary. Installation failed.
```

And this kept failing even after multiple tries.

Is there someting I'm doing wrong or should be doing?

**Comment by junegunn** [comment]
It is not an issue of fzf. Looks like your system is messed up somehow. You'll have to figure out why you're getting that `dyld: Library not loaded: /usr/local/opt/readline/lib/libreadline.7.dylib` message.

**Comment by localhostdotdev** [comment]
macOS's provided version of readline is buggy, you have to use a brew installed version: https://stackoverflow.com/a/20319294/10993539

```
brew install readline
brew link --force readline
```
