### ISSUE TITLE
2 second delay when selecting an item in tmux using Ctrl+T

### ISSUE THREAD

**Issue by unphased** [junegunn/fzf#152]
I am wondering if there is some bad interaction with my tmux config or if this is expected behavior. When I use a bare shell and use the Ctrl+T binding, `fzf` is insanely fast, and it's perfect. When I am in tmux, it splits and starts working just as fast, but when I select anything, it will take about 2 seconds before the item I selected actually gets entered into the command line. 

I think I can workaround it by disabling fzf-tmux but maybe there is something for me to fix here.

**Comment by unphased** [comment]
I can't reproduce this so I guess I should close it. 

I should also mention that this is on OS X (on a system that's been upgraded from Mountain Lion to Mavericks to Yosemite so it's probably got decent cruft buildup).

What I also did was I added `TERM=screen-256color` to all the `fzf` calls made in `~/.fzf.zsh`. May have had something to do with it, but doubtful on that.

**Comment by junegunn** [comment]
I'm mainly on OSX with tmux but haven't experienced the problem. Anyway thanks for the report.

**Comment by unphased** [comment]
I have seen it a few more times but it's mostly a rare occurrence. Might be some kind of interaction with tmux. I will be back if I can gain any more insight into this.

**Comment by unphased** [comment]
I upgraded fzf on OSX (which means my $TERM override got blown away) which brought back the intermittent tmux freezing issue. it always comes back but it might freeze for 4 seconds before the tmux pane becomes responsive again. It isn't tmux itself freezing. It's definitely the longest delay when I use the Alt+C (for fzf-chdir'ing). 

Using top/htop/activity monitor didn't lead anywhere, it's not CPU load... 

Also this simply does not happen on Linux

**Comment by junegunn** [comment]
I don't think TERM is the reason of the delay. By the way, you have to use `screen` or `screen-256color` on tmux. Always, not just for fzf. 

Excerpt from: http://tmux.cvs.sourceforge.net/viewvc/tmux/tmux/FAQ

```
******************************************************************************
* PLEASE NOTE: most display problems are due to incorrect TERM! Before       *
* reporting problems make SURE that TERM settings are correct inside and     *
* outside tmux.                                                              *
*                                                                            *
* Inside tmux TERM must be "screen" or similar (such as "screen-256color").  *
* Don't bother reporting problems where it isn't!                            *
*                                                                            *
* Outside, it must match your terminal: particularly, use "rxvt" for rxvt    *
* and derivatives.                                                           *
******************************************************************************
```

**Comment by unphased** [comment]
Okay, I'll deal with that, but yes i dont believe that is related to this issue. 

Dug a little more, with `pstree`: 

During fzf Alt+C run: 
```
 | |-+= 79934 lust -zsh                                                                                  
 | | \-+- 90173 lust -zsh                                                                                
 | |   |--- 90174 lust find -L . ( -path */\.* -o -fstype dev -o -fstype proc ) -prune -o -type d -print 
 | |   |--- 90175 lust sed 1d                                                                            
 | |   |--- 90176 lust cut -b3-                                                                          
 | |   \--- 90178 lust fzf +m                                                                            
 | |--= 10149 lust -zsh                                                                                  
 | |-+= 43021 lust -zsh                                                                                  
```

Seems fine. 

After, to see what the hell is running inside the same terminal, which is 79934:

```
| |-+= 79934 lust -zsh
| | \-+- 90436 lust -zsh
| |   \-+- 90445 lust git symbolic-ref HEAD
| |     \--- 90446 lust /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -license check
| |--= 10149 lust -zsh
| |-+= 43021 lust -zsh
```

Ok that is pretty screwed up. Something being run by git (which is run by zsh for the RPROMPT prompt on the right side of my zsh shell)
