### ISSUE TITLE
Can I preserve the original Ctrl-R behaviour of bash

### ISSUE THREAD

**Issue by udgithub** [junegunn/fzf#1520]
- Category
    - [x] fzf binary
    - [x] Key bindings
- OS
    - [x] Linux
- Shell
    - [x] bash

Thanks for your great tool !!
Would it be possible to redefine Ctrl-R or use another shortcut for fzf?
I'm using Ctrl-R in bash since years and I would like to use it in it's original form.
So I need another shortcut for fzf.

Thanks

**Comment by Elvyria** [comment]
You can edit `/usr/share/fzf/key-bindings.bash` or copy it somewhere else and replace your source line in `.bashrc` with new path. Also, similar question was already asked #253.

**Comment by udgithub** [comment]
Elvyria, thanks for this useful hint.
I've seen that I could also disable keybindings when installing fzf at all.
But for me it's not clear how I could then use fzf?
BTW: 
I installed fzf only in my home-directory.
Now I could change .fzf/shell/key-bindings.bash
Would it be possible to use Ctrl-Shift-R as a keybinding? I yes, how do I have to do this?
So I could use both ways to search through the history.

**Comment by Elvyria** [comment]
I'm not using bash, but shouldn't uppercase letter do the `Shift` trick? Also, you can pipe any strokes into fzf to search through them, like `ls | fzf`

**Comment by junegunn** [comment]
If you don't want to edit that file, you can use the following trick:

```sh
# Bind CTRL-R from fzf to CTRL-X CTRL-R
bind "$(bind -s | grep '^"\\C-r"' | sed 's/"/"\\C-x/')"

# Then bind CTRL-R to the original reverse history search
bind '"\C-r": reverse-search-history'
```

> Would it be possible to use Ctrl-Shift-R as a keybinding? 

No, terminals can't tell the difference between CTRL-SHIFT-*X* and CTRL-*X*.
