### ISSUE TITLE
add MacPorts install option in README

### ISSUE THREAD

**Issue by cardi** [junegunn/fzf#1521]
- Category
    - [x] Etc.
- OS
    - [x] Mac OS X

Hello, there is now an option to install `fzf` with [MacPorts](https://www.macports.org/) (fzf [Portfile](https://github.com/macports/macports-ports/blob/master/sysutils/fzf/Portfile)):

The command to install it is:
```
sudo port install fzf
```

Thank you and everyone else for developing this!

**Comment by junegunn** [comment]
Thanks for sharing. Any reason you prefer MacPorts over Homebrew? Homebrew seems to have been the de-facto standard package manager for mac users for the past few years.

**Comment by cardi** [comment]
I've been using MacPorts for many years now (and recently, making or updating Portfiles for software) and haven't had a compelling reason to try or switch to other package managers--I suppose the same goes for Homebrew users. (I think both are reasonably mature enough that a user can't go wrong one way or the other.)

**Comment by cardi** [comment]
Thank you!
