### ISSUE TITLE
Publish release assets

### ISSUE THREAD

**Issue by hdnivara** [junegunn/fzf#1523]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [x] Etc.
- OS
    - [ ] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [x] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [ ] fish

---
Would it be possible to [publish the release assets](https://developer.github.com/v3/repos/releases/#upload-a-release-asset) for releases so that users can fetch the latest release tarball using the [GitHub API](https://developer.github.com/v3/repos/releases/#get-the-latest-release)?

Finding the latest release's data without any stateful information such as version number is quite useful in automating binary updates. 

For example, the latest release API for `fzf` repo returns "Not Found" ...

```
$ curl --silent "https://api.github.com/repos/junegunn/fzf/releases/latest"
{
  "message": "Not Found",
  "documentation_url": "https://developer.github.com/v3/repos/releases/#get-the-latest-release"
}

```

... whereas a different project that (I think) publishes the assets returns the latest release details.

```
$ curl --silent "https://api.github.com/repos/BurntSushi/ripgrep/releases/latest" | head
{
  "url": "https://api.github.com/repos/BurntSushi/ripgrep/releases/12790314",
  "assets_url": "https://api.github.com/repos/BurntSushi/ripgrep/releases/12790314/assets",
  "upload_url": "https://uploads.github.com/repos/BurntSushi/ripgrep/releases/12790314/assets{?name,label}",
  "html_url": "https://github.com/BurntSushi/ripgrep/releases/tag/0.10.0",
  "id": 12790314,
  "node_id": "MDc6UmVsZWFzZTEyNzkwMzE0",
  "tag_name": "0.10.0",
  "target_commitish": "master",
  "name": "",
```
Thanks!

**Comment by junegunn** [comment]
Binary releases are uploaded to https://github.com/junegunn/fzf-bin
