### ISSUE TITLE
[FR] Colors based on pattern

### ISSUE THREAD

**Issue by rockandska** [junegunn/fzf#1525]
- Category
    - [X] fzf binary
- OS
    - [X] Linux
- Shell
    - [X] bash

Not sure if it already exist, but it will be very handy to be able to change the colours of the lines based on a pattern.
This way some extensions could be colourized with one colour for example and other usage could come from this as colourized directories with other colour etc...

Best regards,

**Comment by junegunn** [comment]
This should be done by a pre-process filter. `--ansi` option of fzf.

```sh
ls | some-program-that-can-colorize-the-entries | fzf --ansi
```

Or use a program that prints colored output, such as`fd`:

```sh
fd --color=always | fzf --ansi
```
