### ISSUE TITLE
clear preview immediately

### ISSUE THREAD

**Issue by AUTplayed** [junegunn/fzf#1530]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

hi, I'm using a 3rd party script that uses fzf so I'm not an expert with fzf, but I have an issue that affects this program. 

Referencing the line in the README: 
> Since the preview window is updated only after the process is complete, it's important that the command finishes quickly.

would it be possible to clear the preview before the new preview process is executed? because as it is right now the preview window is stuck on an old entry while the new one is loaded with no sign/indicator that something is being done.

**Comment by junegunn** [comment]
No. It would cause constant flashing of the window in most cases where the preview process finishes quickly. As the name implies, the feature was added to address simple "previewing" needs. It was not designed for long running processes, and I'd like to keep it simple as it is now.

**Comment by mooreye** [comment]
For me, this seems to work:
`--bind='focus:hide-preview+show-preview'`
clears the preview as soon as other item is selected.
