### ISSUE TITLE
can change alt+c to other key combination？

### ISSUE THREAD

**Issue by usernameisnull** [junegunn/fzf#1531]
- Category
    - [x ] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x ] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

I use xshell connect to my virtual machine, alt+c is the xshell's default hot key.
through i disabled the xshell's alt+c, fzf can't use alt+c.
can change alt+c to other key conbination? like alt+x?

**Comment by junegunn** [comment]
No option for that, but in bash, you can get the bind expression like so:

```sh
bind -s | grep '^"\\ec"'
```

Then you can use the expression to re-bind it to another key.

```sh
bind "$(bind -s | grep '^"\\ec"' | sed 's/\\ec/\\ex/')"
```

Or you can just fork/edit the source code.

In zsh, it's much easier: `bindkey '\ex' fzf-cd-widget`
