### ISSUE TITLE
Formatting corrupted when Unicode East Asian Ambiguous characters are wide

### ISSUE THREAD

**Issue by Nuru** [junegunn/fzf#1533]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [s] bash
    - [ ] zsh
    - [ ] fish
---
Under macOS built-in Apple Terminal, if you have the setting "Unicode East Asian Ambiguous characters are wide" checked, and are using the `--preview` option, the formatting is corrupted. You get something like this:
![fzf](https://user-images.githubusercontent.com/2793313/54850441-6edf8280-4ca4-11e9-909f-f6a3bec0ec75.png)

Of course, the workaround is to uncheck the option, but that option is needed in many situations. East Asian users need it for their text. See [Unicode® Standard Annex #11: East Asian Width](http://www.unicode.org/reports/tr11/).

In particular, if the command prompt or command line has an ambiguous width character and that option is not set, then searching and editing command lines can fail because the cursor is not properly placed. 

See https://github.com/bpython/bpython/issues/254 for how a similar issue was resolved in another project. This utility might be a help: https://github.com/mattn/go-runewidth/blob/master/runewidth_posix.go

**Comment by junegunn** [comment]
Since fzf has no way to know if the option is enabled or not, the only option is to add a new option to draw borders in ASCII characters instead of Unicode box drawing characters as in https://github.com/bpython/bpython/commit/566dfe5a5fab815fdd8d04d6d3d131333c2a5800. Also related: https://github.com/workshopper/workshopper/issues/73

By the way, I'm also an East Asian user, but I use iTerm2 and never had the issue. Have you tried using other terminal emulators?

**Comment by Nuru** [comment]
> Since fzf has no way to know if the option is enabled or not, the only thing we can do is to add a new option to draw borders in ASCII characters instead of Unicode box drawing characters as in [bpython/bpython@566dfe5](https://github.com/bpython/bpython/commit/566dfe5a5fab815fdd8d04d6d3d131333c2a5800). 

Yes, but I think that is not an unreasonable option to add, preferably via both a command line option and a single-function environment variable. (The problem with `FZF_DEFAULT_OPTS` is that it is difficult to add or change options to it, for example changing the color based on day or night, because doing that the easy way wipes out any other default options you have set.)

> 
> By the way, I'm also an East Asian user, but I use iTerm2 and never had the issue. Have you tried using other terminal emulators?

Yes. "Ambiguous width characters" is a very well known issue and has more to do with the version of Unicode support the OS has installed rather than anything specific to individual terminal programs.
