### ISSUE TITLE
Is there a way to see the end of the filename/path instead of the beginning?

### ISSUE THREAD

**Issue by YangVincent** [junegunn/fzf#1534]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [x] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

I work with very long file paths. I want to show the ending of the path (near where the files are). Is this possible?

**Comment by sudo-nice** [comment]
It is possible.
```sh
echo '/very/long/file/path.sh' | fzf --delimiter / --with-nth -1
```

**Comment by junegunn** [comment]
Not exactly what you want, but another thing you can do is to enable toggleable (or always-on) preview window for showing the full path.

```sh
fzf --preview 'echo {}' --preview-window down:2

fzf --bind ?:toggle-preview --preview 'echo {}' --preview-window hidden:down:1
```

**Comment by joech4n** [comment]
It seems that the preview window approach is also truncated at the end. Is there any other solution for maximizing the amount of path that is shown starting from the end?

**Comment by NightMachinary** [comment]
@junegunn

> Not exactly what you want, but another thing you can do is to enable toggleable (or always-on) preview window for showing the full path.
> 
> ```shell
> fzf --preview 'echo {}' --preview-window down:2
> 
> fzf --bind ?:toggle-preview --preview 'echo {}' --preview-window hidden:down:1
> ```

Can we have a way to just prioritize showing the end? I do not want the `--with-nth` because I need to search through the higher dirs sometimes, and the preview window solution doesn't let me see everything at a glance.

**Comment by junegunn** [comment]
Check out `--keep-right` option.

**Comment by rayiik** [comment]
Just another option if all you care about is the last field Two solutions come to mind
```zsh
—preview=“basename <<<{}”
—preview=“awk -F/ 'NF>=3{ print $(NF-2), $(NF-1), $NF}' <<<{}” #last 3 fields
```
