### ISSUE TITLE
Disable fzf --preview for binary files

### ISSUE THREAD

**Issue by 3N4N** [junegunn/fzf#1536]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

I've following in my `~/.bashrc`:
```
export FZF_DEFAULT_OPTS='
	--height 40% --multi --layout=reverse --border
	--bind ctrl-f:page-down,ctrl-b:page-up
	--preview "head -100 {}"
'
```

But this also includes preview for binary/non-text files. So, I tried the following:
```
export FZF_DEFAULT_OPTS='
	--height 40% --multi --layout=reverse --border
	--bind ctrl-f:page-down,ctrl-b:page-up
	--preview "if file {} | grep -i 'text'; then head -100 {}; fi"
'
```

This doesn't include the external command for binary files. But the preview window remains active i.e. the border remains.

How can I disable preview, i.e. remove the preview border for binary files?

**PS** I know about keybinding to toggle preview window. But I want it to toggle automatically depending on whether the currently selected line is a binary file or text file.

**Comment by junegunn** [comment]
> toggle automatically depending on whether the currently selected line is a binary file or text file

It's not supported. You might want to print a message saying that it's a binary file (e.g. https://github.com/junegunn/fzf.vim/blob/master/bin/preview.sh#L25-L28)

Having said that, setting context-sensitive `preview` option in `FZF_DEFAULT_OPTS` is a very bad idea.

```sh
seq 100 | fzf
ls -al | fzf
ps -ef | fzf
cat /usr/share/dict/words | fzf
history | fzf
```

You get the point.

**Comment by 3N4N** [comment]
@junegunn Thanks
