### ISSUE TITLE
Support nerdfonts / devicons

### ISSUE THREAD

**Issue by brodock** [junegunn/fzf#1537]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [x] Vim
    - [x] Neovim
- OS
    - [x] Linux
    - [x] Mac OS X
    - [x] Windows
    - [x] Windows Subsystem for Linux
- Shell
    - [ ] bash
    - [ ] zsh
    - [ ] fish

Please consider supporting https://nerdfonts.com as file icons.

**Comment by junegunn** [comment]
fzf is a text filter.
