### ISSUE TITLE
Handle Newlines

### ISSUE THREAD

**Issue by unphased** [junegunn/fzf#154]
I think it can be helpful if there's a way to specify an escape sequence that represents a newline but which does not separate the text into different options. 

I can get 90% of the way there (by defining the escape sequence myself and splicing it in before and replacing the output with newlines), but I need support inside fzf to show the entry as a multiple line entry with the whole thing being one item. 

But as a workaround having a big ugly placeholder escape code that I can see inside the menu is still more or less usable.

(Example use case -- I want to use fzf with my shell history, and the shell history can contain multi line commands that would be cool if I can reproduce faithfully, rather than what `fc -l 1` does which is just print `\n` for them)

**Comment by junegunn** [comment]
Related: #121 

Thanks for the suggestion but it's non-trivial to implement multi-line entry display and it will make many parts of the code much more complex. Think about how we should handle long-line truncation, multi-part highlighting in extended-search mode, page scroll, terminal resize, mouse clicks, etc. I have very limited time to work on fzf, so I can't say anything about it right now.

**Comment by unphased** [comment]
Yep, and I definitely can't fault you for making the decision originally (or even now) to say that newline is the de facto standard delimiter.

My workaround works fine... I will close since you left #121 open.

**Comment by junegunn** [comment]
https://junegunn.github.io/fzf/tips/processing-multi-line-items/
