### ISSUE TITLE
How can I rebind a key to the functionality of <Alt-C> in bash

### ISSUE THREAD

**Issue by 3N4N** [junegunn/fzf#1541]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [x] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

I want to bind `Alt-C` to `Alt-O`, how do I do that without directly editing `~/.fzf/shell/key-bindings.bash` or needing to copy-paste that files functions to my `bashrc`? I want to just set the keybindings from my `bashrc`

I want to do this because bash emacs style readline gives `capitalize-word` function bound to `Alt-C`

**Comment by junegunn** [comment]
See #1531

**Comment by 3N4N** [comment]
@junegunn I'm gonna leave here the answer that I ended on at last, if you don't mind. For anyone else, going through the problems.

```
# source the keybindings file
# you don't need to source it if you installed fzf with `install --all`
source path/to/fzf/shell/key-bindings.bash

# set cd binding to Alt-O
bind '"\eo": " \C-e\C-u`__fzf_cd__`\e\C-e\er\C-m"'
# overwrite Alt-C binding
bind '"\ec": capitalize-word'
```
