### ISSUE TITLE
Build failure on armv7

### ISSUE THREAD

**Issue by Ikke** [junegunn/fzf#1547]
- Category
    - [x] fzf binary
- OS
    - [x] Linux

The Makefile mentions armv7, but when we try to [compile] it on ARM, the following error occurs:

>  /usr/lib/go/pkg/tool/linux_arm/link: running gcc failed: exit status 1
/tmp/go-link-121509314/go.o: file not recognized: file format not recognized
collect2: error: ld returned 1 exit status

Any idea what might go wrong?

[compile]:https://cloud.drone.io/alpinelinux/aports/1091/5/2

**Comment by junegunn** [comment]
Have you tried setting `GOOS=linux`? I just run `make release-all` on my MacBook to build all the binaries and this is the command Makefile generates.

```sh
GOOS=linux GOARCH=arm GOARM=7 go build -a -ldflags "-X main.revision=ff95134 -w -extldflags=" -tags "" -o target/fzf-linux_arm7
```
