### ISSUE TITLE
Feature suggestion: command options fuzzy completion

### ISSUE THREAD

**Issue by izemmouri** [junegunn/fzf#1548]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [X] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [X] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [X] zsh
    - [ ] fish

 Hi,
This is more of a feature suggestion than an issue, although maybe the feature exists and I didn't notice; the only thing that seems missing with fzf is the ability to fuzzy-find options: for example, if you do `ls -` with bare zsh with compinit and press tab, it will display a list of options in a format more or less like this:
  --all                     -a                    -- short description
  --author                                     -- another short description
  --classify            -F                    -- yet another one
 and so on...
In bare zsh, you cannot navigate through this easily, as you have to either repeatedly tab your way through it or navigate with CTRL-{hlpn} or arrows, which is quite bothersome. What would be nice, in the spirit of fzf, would be to actually fuzzy search these lines to match the right option either through the options' short/long names or even by the text of their short description.

Now I don't know whether this is a simple feature to add or not, or maybe there's already an even better way to do this and I don't know about it, but it's a thought. Let me know what you think.

**Comment by junegunn** [comment]
It would be nice but I don't think it's possible since there is no standardized API to get the list of options as far as I know (and I'm a bash user).

**Comment by izemmouri** [comment]
For zsh, there is https://github.com/Valodim/zsh-capture-completion which I use approximately (if anyone is interested). All one has to do is to have a widget that passes the $BUFFER to the capture-script and call fzf on the script's output,
Something like CAPTURE=$(zshcapture "${BUFFER}" | tr -d '\r' | fzf -1 -0 | awk '{print $1}')
and LBUFFER="${LBUFFER}${CAPTURE}"

**Comment by RobSis** [comment]
@izemmouri 
That sounds awesome! Would you mind sharing that? Ideally, I'd like to be able to use fzf for all zstyle completions.

**Comment by izemmouri** [comment]
Actually, it looks more like this:
```
# /path/to/widget/_zshcapture
# zle -N _zshcapture # given it's in your $path
local SPACE=" "
local CAPTURE=$(zshcapture "${LBUFFER}" | tr -d '\r' | sed 's/ -- / | /p' | 
               column -t -s '|' | fzf -q "${LBUFFER}" -1 -0 | awk '{print $1}')

if [[ ! "$LBUFFER[-1]" =~ [[:blank:]] ]]; then
   zle .backward-delete-word
fi

LBUFFER="${LBUFFER}${CAPTURE}"

if [[ "$LBUFFER[-1]" =~ "/" ]]; then
   SPACE=""
fi
```

It has many shortcomings depending on what you're trying to complete, sometimes the backward-delete-word is unwanted (for example when there is no completion for that context). What would be really good is some way to know the completion context, but hacking into zsh does not seem simple. With some kind of context information, you could make the decision that you want to use fzf-file-completion instead of calling zshcapture and completing one path-component at a time. 
Tbh, I'm more of a mediocre zsh user, so there might be ways to do this I didn't even try to investigate, so if you can improve this, please let me know.

Another thing that comes to mind is the zsh-completion-generator plugin. With zshcapture, you have effectively a way to know whether a command has option completion or not, and if not you can automatically generate completions for those commands, which might come in handy.

**Comment by RobSis** [comment]
This is absolutely awesome! Thanks a lot for sharing this. I made some changes to it - mainly removing the last word only if there's any result from fzf. Also, the /p in your sed makes makes everything print twice. I also think that `--prompt` instead of `-q` makes more sense (for example `cd x[TAB]` would pre-fill the fzf with `cd x`, which isn't in the results.

```
  local LAST_WORD=${LBUFFER##* }
  local PREFIX=${LBUFFER%"$LAST_WORD"}
  local CAPTURE="$(zshcapture "${LBUFFER}" \
                    | tr -d '\r' \
                    | sed 's/ -- / | /' \
                    | column -t -s '|' \
                    | fzf --prompt "${LBUFFER}" -1 -0 \
                    | awk '{print $1}')"
  if [[ -n "$CAPTURE" ]]; then
    if [[ -n "$LAST_WORD" ]]; then
      LBUFFER="${PREFIX}"
    fi
    LBUFFER="${LBUFFER}${CAPTURE}"
    if ! [[ "$LBUFFER[-1]" =~ "/" ]]; then
      LBUFFER="${LBUFFER} "
    fi
  fi
```
The biggest problem I have with this now is that `awk {print $1}` is kinda dumb with filenames with spaces. (`file\ name.mp3` returns only `file`).

Otherwise it looks pretty promising!

**Comment by izemmouri** [comment]
I've improved a bit myself. Here is what it currently looks like:

```
setopt localoptions shwordsplit
local BUFFERLINE=($LBUFFER)
# CURWORD is the last word or empty when you're trying to complete
# on whitespace (like in `ls `)
local CURWORD="${BUFFERLINE[$#BUFFERLINE]}"
# currently useless
local SAVEBUF="$LBUFFER"

# set CURWORD to an empty string when completing on whitespace
if [[ "$LBUFFER[-1]" =~ [[:blank:]] ]]; then
	CURWORD=''
fi

# remove the last word for our prompt
local PROMPT="${LBUFFER%$CURWORD}"

# This should complete filenames with spaces correctly, but who knows what pitfalls it might induce
local CAPTURE=$(zshcapture "${BUFFER}"  \
		| tr -d '\r' 	        \
		| sed 's/ -- / | -- /' 	\
		| column -t -s '|' 	\
		| fzf --prompt "$PROMPT" -q "$CURWORD" -0 -1 \
		| awk '{print ($1 ~ / -- /)?$1:$0}')

# revert to normal completion when no capture is available?
if [[ -z "$CAPTURE" ]]; then
	zle expand-or-complete-prefix
	return 0
fi

#echo DEBUG

# kill current word before completing stuff
if [[ ! "$LBUFFER[-1]" =~ [[:blank:]] ]]; then
	zle backward-kill-word
fi

LBUFFER="${LBUFFER}${CAPTURE}"

```

You're indeed right, giving LBUFFER as --query isn't great. However, giving the last word as --query is great, especially in directory completion.

I have also discovered you don't want to add a space in most cases; consider completing a variable like this ${<Tab> : adding a space in this case forces you to backspace to close the brace, and most cases are like this, options that require an argument, variables, filename flags like in `ls *(:<Tab>`, subscript completion, basically, you never want to add a space except when completing options you know have no arguments (and I don't see a way to gather this information from what's around, so I just go to the trouble of adding the space manually).

The awk one-liner should do the trick with the previously given sed substitution, but as said in the comment, who knows what pitfalls it might induce.

Let me know how this works for you or what pitfalls you might stumble upon.
