### ISSUE TITLE
[Feature Request] Syntax extension for filtering conditions

### ISSUE THREAD

**Issue by reaysawa** [junegunn/fzf#1549]
For instance, when filtering through a source with numbered entries, it would be nice to do something like the following:

### Considering a source with only numbers

```
1
2
3
4
5
```

### Only the sources with numbers greater than four (regex-based approach)

The regex-based approach tests the condition against the first captured group on each item

`
[0-9]+ >= 4
`

I don't like this approach because
- It would need to bring in regex-parsing to FZF, making it more difficult to maintain and adding more lines to the code base.
- Regex isn't as flexible as eval-based approach, which can leverage every process in the shell.

### Only the sources with numbers greater than four (line eval-based approach)

The script between the brackets gets evaluated by the shell for each item, and it should echo something if the item is to be kept.

`{[ $LINE -gt 4 ] && echo "keep this item" ]}`

It would also allow for pretty much anything else, e.g. comparing two dates by converting them to timestamps and filtering dates greater than $TODAY or $TOMORROW.

**Note:** brackets are only for demonstration purposes and it could instead follow the Bash syntax more closely with \`command\`.

**Comment by reaysawa** [comment]
My main motivation is that I wish to be able to filter, for instance, only Markdown headings which are below three levels.

```
# Shelf                          - H1
├── ## Banana                    - H2
├── ## Cherry                    - H2
├── ## Oranges                   - H2
├────── ### Fresh Oranges        - H3
```

`'Banana {[ $(regex_to_extract_number $LINE) -gt 2 ] && echo "keep" ]}`

Or only tasks before a certain date

```
04/04/2018 Do laundry
05/04/2018 Run in the park
06/04/2018 Watch movie
```

`{[ $(convert_line_to_number $LINE) -lt $TODAY ] && echo "keep" ]}`

**Comment by junegunn** [comment]
Thanks for the suggestion, but this is going to be a niche feature, and in my opinion, it's beyond the scope of the project. fzf was designed to be a simple interactive grep, rather than a building block for sophisticated terminal applications and I want to keep it simple.

**Comment by NightMachinary** [comment]
[**@resolritter**](https://github.com/resolritter) commented on [Apr 4, 2019, 4:58 PM GMT+4:30](https://github.com/junegunn/fzf/issues/1549#issue-429250980 "2019-04-04T12:28:43Z - Replied by Github Reply Comments"):
> For instance, when filtering through a source with numbered entries, it would be nice to do something like the following:
> 
> ### Considering a source with only numbers
> 
> ```
> 1
> 2
> 3
> 4
> 5
> ```
> 
> ### Only the sources with numbers greater than four (regex-based approach)
> 
> The regex-based approach tests the condition against the first captured group on each item
> 
> `[0-9]+ >= 4`
> 
> I don't like this approach because
> 
> *   It would need to bring in regex-parsing to FZF, making it more difficult to maintain and adding more lines to the code base.
> *   Regex isn't as flexible as eval-based approach, which can leverage every process in the shell.
> 
> ### Only the sources with numbers greater than four (line eval-based approach)
> 
> The script between the brackets gets evaluated by the shell for each item, and it should echo something if the item is to be kept.
> 
> `{[ $LINE -gt 4 ] && echo "keep this item" ]}`
> 
> It would also allow for pretty much anything else, e.g. comparing two dates by converting them to timestamps and filtering dates greater than $TODAY or $TOMORROW.
> 
> **Note:** brackets are only for demonstration purposes and it could instead follow the Bash syntax more closely with \`command\`.

Did you find any alternatives to `fzf` that were more suited to UI building?

**Comment by resolritter** [comment]
@NightMachinary 

> Did you find any alternatives to `fzf` that were more suited to UI building?

I didn't try to find anything else. The use-case I had in mind was something like a poor man's wiki based on Markdown headers; instead of having links and all sorts of structured formatting like those wiki plugins usually have, I'd instead grep a whole "notes" directory through FZF and narrow to what I wanted with the expression syntax which was proposed here.

I ended up doing some custom CLI scripts instead which do those things separately and not using FZF after all.

Not sure which kind of UI you're going for, but there're a couple of libraries for CLI UIs you could try (e.g. [tig](https://github.com/jonas/tig) uses ncurses).

**Comment by NightMachinary** [comment]
[**@resolritter**](https://github.com/resolritter) commented on [Jul 31, 2020, 2:35 AM GMT+4:30](https://github.com/junegunn/fzf/issues/1549#issuecomment-666734680 "2020-07-30T22:05:45Z - Replied by Github Reply Comments"):
> [@NightMachinary](https://github.com/NightMachinary)
> 
> > Did you find any alternatives to `fzf` that were more suited to UI building?
> 
> I didn't try to find anything else. The use-case I had in mind was something like a poor man's wiki based on Markdown headers; instead of having links and all sorts of structured formatting like those wiki plugins usually have, I'd instead grep a whole "notes" directory through FZF and narrow to what I wanted with the expression syntax which was proposed here.
> 
> I ended up doing some custom CLI scripts instead which do those things separately and not using FZF after all.
> 
> Not sure which kind of UI you're going for, but there're a couple of libraries for CLI UIs you could try (e.g. [tig](https://github.com/jonas/tig) uses ncurses).

BTW, take a look at org-mode if you haven't seen it already. It seems the closest thing to a good free-software solution to having a knowledge graph on the desktop. Unfortunately, it's mobile support isn't very good.
