### ISSUE TITLE
fzf --help should go to stdout

### ISSUE THREAD

**Issue by felixrabe** [junegunn/fzf#1554]
Currently `fzf --help` goes to stderr, forcing me to `fzf --help 2>&1 | less` (Bash, macOS).

I recommend sending help output to stdout, as seems to be the convention for most programs I've tested:

```sh
bat    --help > /dev/null
clang  --help > /dev/null
diff   --help > /dev/null
fd     --help > /dev/null
gcc    --help > /dev/null
git    --help > /dev/null
irb    --help > /dev/null
less   --help > /dev/null
node   --help > /dev/null
patch  --help > /dev/null
perl   --help > /dev/null
python --help > /dev/null
rg     --help > /dev/null
rustc  --help > /dev/null
```

Notable exception(s):

```sh
go     --help 2> /dev/null
```

Also, most BSD tools that come with macOS (e.g. `cat`, `find`, `ls`, `wc`) write their usage (mostly) to stderr. A funny one is `file` - neither stdout nor stderr contains the full output of `file --help`.

**Comment by junegunn** [comment]
> `fzf --help 2>&1 | less`

Okay, this makes a good point. The benefit of using stdout is clear.

That said, you might want to read `man fzf` instead which gives the full documentation.

**Comment by junegunn** [comment]
GNU coding standard recommends using stdout for `--help` message: https://www.gnu.org/prep/standards/html_node/_002d_002dhelp.html
