### ISSUE TITLE
ALT-I to paste item from locate / output

### ISSUE THREAD

**Issue by balta2ar** [junegunn/fzf#156]
Since fzf is now very fast, I started using it to draw items from locate output. I find it a little overwhelming to type `locate / F` each time, so I've added fzf-locate-widget similar to fzf-history-widget and I've bound it to 'ALT-C'. The change is pretty simple, could you consider including it into default (zsh only)?

``` zsh
# ALT-I - Paste the selected entry from locate output into the command line
fzf-locate-widget() {
  local selected
  if selected=$(locate / | fzf +s -q "$LBUFFER"); then
    LBUFFER=$selected
  fi  
  zle redisplay
}
zle     -N    fzf-locate-widget
bindkey '\ei' fzf-locate-widget
```

**Comment by junegunn** [comment]
Thanks for the suggestion and I like it. But I'm not sure if I want to expand the set of default keybindings as making sure those work as expected on various platforms (and fixing them) has been a bit stressful for me. And if I'm going to add it, I want to make it available on all three shells (bash, zsh, fish) not to surprise the users. Another point to consider is that locate database is not available by default on OS X.

So for now, I'll just keep the default set small. But feel free to add your code to [the wiki page](https://github.com/junegunn/fzf/wiki/Examples) (write permission is open to anyone), or discuss it with @D630 who took the initiative of maintaining [fzf-contrib](https://github.com/D630/fzf-contrib) repository.

**Comment by junegunn** [comment]
By the way, I also have a locate key binding in my tmux configuration.

```
# fzf-locate (all)
bind-key -n 'M-`' run "tmux split-window -p 40 'tmux send-keys -t #{pane_id} \"$(locate / | fzf -m | paste -sd\\  -)\"'"
```

**Comment by balta2ar** [comment]
Thank you! I've added the recipe to the wiki page. I'll also try to use your tmux alias along with my version to see which works better for me.

**Comment by junegunn** [comment]
Thanks. Your version is better that it uses $LBUFFER as the initial query. But I'm a bash user, so :)
