### ISSUE TITLE
Provide way for users to add commands for autocomplete

### ISSUE THREAD

**Issue by jamadagni** [junegunn/fzf#1560]
Hmm this is effectively a dup of #536 but since that is closed and I can't reopen a closed issue in GitHub (unlike Bugzilla) I am filing this separately.

- Category
    - [x] Completion
- OS
    - [x] Linux
- Shell
    - [x] bash

Hello. I'm new to `fzf` and tried to use `**` to trigger it while trying at the terminal to open a file using `kate` which is my favourite editor. However it did not work.

I was able to dig in and find that only commands that are given under `a_cmds` in `fzf/shell/completion.bash` are completed this way. So I added `kate` and a few other (like `nano`, `clang` since I prefer it to `gcc` which is included, `python3` apart from existing `python` since I use only Py 3) to this variable and got the completion working.

However, this is not optimal since if there is a new `fzf` release and I re-pull the repo, the changes would get overwritten or I have to maintain a separate branch.

It would be better if there is some way like an environment variable (which can be set under `.bashrc`) or config file where one can add one's own custom commands for which one would like `fzf` `**` completion.

In #536 I see you suggesting to add a `complete` line to `.bashrc` but this method (preferably envvar) would be much more easier. Something like `FZF_COMPLETE_FOR='clang clang++ kate nano'` which would then get included at the end of `a_cmds`.

BTW I think you should at least include `nano` and `python3` in the basic list since they are so ubiquitous and used by users of all desktop environments.

**Comment by junegunn** [comment]
We would need not just `FZF_COMPLETE_FOR`, but `FZF_COMPLETE_PATH_FOR`, `FZF_COMPLETE_FILE_FOR`, and `FZF_COMPLETE_DIR_FOR`. And I do not think adding a new set of environment variables that the users have to learn separately is better than recommending the builtin bash feature. Shortcuts may seem like a good idea at the moment, but they usually make the software more complicated, bloated, and harder to grasp in the long run.

> BTW I think you should at least include nano and python3 in the basic list since they are so ubiquitous and used by users of all desktop environments.

Agreed, please send a pull request.

**Comment by jamadagni** [comment]
> We would need not just `FZF_COMPLETE_FOR`, but `FZF_COMPLETE_PATH_FOR`, 

Well you left out `FZF_COMPLETE_PID_FOR` 😉 because I do have a `waitfor` script that takes a pid argument, but I didn't ask for that first because I thought it may be too specific to me.

> `FZF_COMPLETE_FILE_FOR`, 

Um **fzf** supports selecting just files? You have written in `completion.bash` above `_fzf_file_completion`:

`# Deprecated. No file only completion.`

Perhaps you forgot!

> and `FZF_COMPLETE_DIR_FOR`. 

You seem to already have this: `FZF_COMPLETION_DIR_COMMANDS`. So you have already expected users would like to specify their own. I'm just asking to actually publicize and document this.

> And I do not think adding a new set of environment variables that the users have to learn separately is better than recommending the builtin bash feature. 

One doesn't have to “learn” anything here. One just has to specify these in `~/.fzf.bash`. Either one easily writes:

```sh
FZF_COMPLETE_PATH_FOR='clang clang++ rg'
FZF_COMPLETE_DIR_FOR='tree'
FZF_COMPLETE_PID_FOR='waitfor'
```

Or one writes the longer `complete` command whose syntax one has to actually *learn* 😏.

> Shortcuts may seem like a good idea at the moment, but they usually make the software more complicated, bloated, and harder to grasp in the long run.

What shortcuts do you mean? I am asking not for shortcuts but for ability to enable **fzf** completion for other commands.

> > BTW I think you should at least include nano and python3 in the basic list since they are so ubiquitous and used by users of all desktop environments.
> 
> Agreed, please send a pull request.

OK. Here you are: #1562. (For all of the requests, not just adding `nano` and `python3`.)

**Comment by junegunn** [comment]
Sorry for being not clear enough. `FZF_COMPLETE_PATH_FOR` can be thought of as a shortcut for the method described in https://github.com/junegunn/fzf#supported-commands. We can already enable fuzzy completion for any command using bash builtin (`complete`) with more flexibility (i.e. you may want different options per command; `help complete`) without having to introduce new environment variables with arbitrary names only for bash users.

> You seem to already have this: FZF_COMPLETION_DIR_COMMANDS.

See the commit message here: https://github.com/junegunn/fzf/commit/96176476f3990507b38f2ec45d24c12fcb7aa075. The variable was left undocumented on purpose. 3 years have passed, I don't think it was a good idea.

So I'm okay with adding `nano` and `python3` to the list, but I don't want the extra variables.
