### ISSUE TITLE
Unable to highlight text

### ISSUE THREAD

**Issue by OliverJAsh** [junegunn/fzf#1567]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [x] bash
    - [x] zsh
    - [ ] fish

```
fzf --preview "echo bar"
```

I am trying to highlight the text in the preview window, however it appears this isn't possible for some reason.

For context, I would find this useful when browsing git commits, as I often want to copy snippets from commits.

**Comment by junegunn** [comment]
I'm not sure what you mean by "highlight", but if it means selecting text using mouse or trackpad, you can try disabling mouse support by passing `--no-mouse` option. Or, if you use iTerm2, you can select text with mouse regardless of the option by holding down the option key while dragging over the text.

**Comment by OliverJAsh** [comment]
> try disabling mouse support by passing --no-mouse option

That seemed to do the job, thanks.

That also seems to help with this other issue I was having: https://github.com/junegunn/fzf/issues/1568.
