### ISSUE TITLE
Extended-search mode help text

### ISSUE THREAD

**Issue by strokirk** [junegunn/fzf#157]
Extended-search mode is very useful (enough so that is should probably be added to the default `.fzf.zsh`), but I totally forgot that the explanation of the syntax is in https://github.com/junegunn/fzf today, while searching for how to make matches exact. 

Could the extended-search syntax be added to the `--help` flag, or a `man` page? I do like very much that the help text currently fits in one screen, so perhaps it could be printed with `--help-extended`, or something like that.

**Comment by junegunn** [comment]
Thanks for the suggestion. I agree that the instruction should be accessible from the command-line in some way. Now as fzf is distributed as a compiled binary, I probably shouldn't release a new version just to update `--help` message, and also I feel the same about what you said about the length of help message. So, I like the idea of providing man page though I have no experience with man pages. I'll see what I can do.

**Comment by junegunn** [comment]
I added a basic man page. The updated install script will generate `.fzf.{bash,zsh}` that will extend `$MANPATH` so that `man fzf` is available without root privilege. Please try it and let me know what you think.

**Comment by strokirk** [comment]
Yes, this seems to work perfectly!
