### ISSUE TITLE
fzf run by itself

### ISSUE THREAD

**Issue by kkew3** [junegunn/fzf#1572]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

This might be a dumb question but I haven't got fruitful result via searching Google or skimming existing issues. Firstly, what's `fzf` supposed to do if I run `fzf` without any parameters? On my computer it gives me a list of, like hundreds of thousands of files. I feel, but not assure, that it's doing something like `find . -type f -print`. If I select any item, it just print it, nothing more. My second question is: is there any way to change the default behavior (sorry if it's already in `man` but I didn't find it)? Thanks in advance.

**Comment by junegunn** [comment]
See https://github.com/junegunn/fzf#usage
