### ISSUE TITLE
fzf#run doesn't work for left and right positions

### ISSUE THREAD

**Issue by echuraev** [junegunn/fzf#1577]
- Category
    - [x] Question
    - [x] Bug
    - [ ] Suggestion
- OS
    - [x] Linux
    - [x] macOS
    - [ ] Windows
    - [ ] Etc.
- Vim
    - [x] Vim
    - [ ] Neovim

Hi @junegunn and everyone who works on this awesome plugin!

First of all thank you for this amazing plugin. I have one issue with it. I try to use `fzf#run` with different window positions, but it works only for 'bottom' and 'top'. Could you please help me? What should I do to fix issue with 'left' and 'right' positions?

I did the following steps:
1. Start vim with a minimal configuration: `vim -Nu <(curl https://gist.githubusercontent.com/junegunn/6936bf79fedd3a079aeb1dd2f3c81ef5/raw)`
2. Run `:let s = fzf#run({'source': ['1 - bottom', '2 - left', '3 - top', '4 - right'], 'bottom': 10})` and select first item.
   Try to print this value: `:echo s` and got: `['1 - bottom']`
3. Run `:let s = fzf#run({'source': ['1 - bottom', '2 - left', '3 - top', '4 - right'], 'left': 40})` and select second item.
   Try to print this value: `:echo s` and got: `[]`
4. Run `:let s = fzf#run({'source': ['1 - bottom', '2 - left', '3 - top', '4 - right'], 'top': 10})` and select third item.
   Try to print this value: `:echo s` and got: `['3 - top']`
5. Run the following command: `:let s = fzf#run({'source': ['1 - bottom', '2 - left', '3 - top', '4 - right'], 'right': 40})` and select fourth item.
   Try to print this value: `:echo s` and got: `[]`

All these steps you can see on the screencast:
![fzf_bug_position_min](https://user-images.githubusercontent.com/5525113/57587274-49842d80-750b-11e9-9dbc-46dab2af4730.gif)

**Comment by junegunn** [comment]
First off, `fzf#run` doesn't understand `top` and `bottom` options (they should be `up` and `down` respectively), so I think you're confused somehow.

See https://github.com/junegunn/fzf/blob/master/README-VIM.md#fzfrun

Secondly, you can't rely on the return value of `fzf#run` as it may or may not return values depending on how fzf was started so it's undocumented.

If you use a layout option other than `down`, `fzf#run` will start fzf process in a terminal buffer and the function returns immediately. There's no way to wait for its completion in a synchronous manner.

You can take the return value using a callback function given as `sink` or `sink*` option.

```vim
function! MySink(line)
  let g:selected = a:line
endfunction

call fzf#run({'source': range(5), 'up': '10%', 'sink': function('MySink')})
```

**Comment by echuraev** [comment]
Ups, sorry, about `top` and `bottom`... I forgot to change it. Thanks!
And thanks for clarification about other layout options. I'll try to use approach with callback function.
Thank you!
