### ISSUE TITLE
Weird characters in bash after selecting

### ISSUE THREAD

**Issue by chsasank** [junegunn/fzf#1578]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [x ] Etc.
- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

Invoking fzf from bash and selecting an command gives weird characters before my selected command.  

<img width="482" alt="image" src="https://user-images.githubusercontent.com/9305875/57780745-82f4ad00-7746-11e9-8f4b-57bced3d2486.png">

<img width="831" alt="image" src="https://user-images.githubusercontent.com/9305875/57780772-8e47d880-7746-11e9-899d-b5b8f528f1a5.png">

```
^[[1;35;40m^[[K 6^[[m^[[K^[[1;35;40m^[[K1^[[m^[[K^[[1;35;40m^[[K4^[[m^[[K ls
```

I don't even know what to call these characters. Sorry if this was a naive question.

**Comment by chsasank** [comment]
I had following `export GREP_OPTIONS='--color=always'` in my bash_profile. Removing this fixed the issue.

**Comment by junegunn** [comment]
Duplicate of #1453.
