### ISSUE TITLE
Views (add/modify hidden filters) 

### ISSUE THREAD

**Issue by m42e** [junegunn/fzf#1580]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [ ] fish

Could there be something like an internal filter which could be set by a key binding, so you are able to switch between somewhat like views.

**Comment by atsepkov** [comment]
I too would like something like an internal keybinding for a few use cases, it can be used to calibrate the search, show/hide hidden files, or even set a flag that would change the behavior of the "enter" key once the result is selected. For example, sometimes user may want to spawn an external program with the result, other times the user may want to perform further searching using the result.

**Comment by atsepkov** [comment]
I've figured out how to accomplish this (for a different project of mine that needed to have a way to open a webpage in separate browser or as preview page inside fzf (https://github.com/atsepkov/Graphene)). You can make use of `--bind` command for this functionality: https://github.com/junegunn/fzf#executing-external-programs

Basically, bind one of the F keys to update results or respawn fzf with new parameters.

**Comment by m42e** [comment]
I'm using it for histdb history and currently I'm writing a file and respawn as long as the file was written.
but maybe, someone else has an idea of how to do it better:

```zsh
  histdb-fzf-widget() {
    local selected num
    temp_dir=$(mktemp -d)
    if [[ -z ${HISTDB_SESSION} ]]; then
      default_next='loc'
    else
      default_next='session'
    fi
    touch ${temp_dir}/.${default_next}
    ORIG_FZF_DEFAULT_OPTS=$FZF_DEFAULT_OPTS
    query=${(qqq)LBUFFER}
    while [ -f ${temp_dir}/.loc -o -f ${temp_dir}/.session -o -f ${temp_dir}/.global ]; do
      setopt localoptions noglobsubst noposixbuiltins pipefail 2> /dev/null
      if [ -e ${temp_dir}/.global ]; then
        cmd="histdb --desc --sep '  ' --limit 10000000"
        typ='GLOBAL history'
        next_type=${default_next}
      elif [ -e ${temp_dir}/.loc ]; then
        cmd="histdb --desc --sep '  ' --in"
        typ="Directory local history $(pwd)"
        next_type='global'
      elif [ -e ${temp_dir}/.session ]; then
        cmd="histdb --desc --sep '  ' -s ${HISTDB_SESSION}"
        typ="Session local history (${HISTDB_SESSION})"
        next_type='loc'
      fi
      rm -f ${temp_dir}/.*
      selected=( $( eval ${cmd} | sed '1d' | awk '{tm=$1;cmd="";for (i = 4; i <= NF; i++) cmd = cmd $i " ";printf "%7s\t%s\n", tm, cmd}' |
        FZF_DEFAULT_OPTS="--height ${FZF_TMUX_HEIGHT:-40%} $ORIG_FZF_DEFAULT_OPTS --header='$typ' --delimiter='  ' -n2 --tiebreak=index --bind='ctrl-r:execute(touch ${temp_dir}/.${next_type})+print-query' --query=${query} +m" $(__fzfcmd)) )
      query=$selected
    done
    selected=$(echo $selected | awk '{tm=$1;cmd="";for (i = 2; i <= NF; i++) cmd = cmd $i " ";printf cmd}')
    rm -rf ${temp_dir}

    LBUFFER=$selected
    zle redisplay
    typeset -f zle-line-init >/dev/null && zle zle-line-init
    
    return $ret
  }

```

**Comment by junegunn** [comment]
fzf is an interactive version of "grep" and it was not designed to reload the input, so you have to restart it if you need a different set of input.

And if you need to perform different actions depending on the key user pressed, use `--expect` option. This will give you an idea of what you can do with the option.

```sh
while true; do
  lines=$(seq 100 |
          fzf --height 30% --no-clear \
              --expect f1,f2,f3,f4 \
              --preview "[ -n '$key' ] && echo You selected $selected with $key")
  [ $? -eq 0 ] || break

  readarray -t lines <<< "$lines"
  key=${lines[0]:-enter}
  selected=${lines[1]}
done

# Manually clear below the cursor
echo -en "\x1b[J"
```

(`--no-clear` is for reducing the flickering of the screen when fzf restarts)
