### ISSUE TITLE
Separately search terms on the filename, and on the contents of the files in the same filter

### ISSUE THREAD

**Issue by GabrielDuarteM** [junegunn/fzf#1583]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [x] Vim
    - [x] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

I'd like to know if there's a way to a search in the following conditions:
- I have a folder containing a file named `Colors.js`
- I want to search for the keyword `color`, but limit this search to the contents of the file only (not search that on the file path).
- I want that search to be performed only on files with the extension`.js` and `.jsx` (using something like so `'.js$ | '.jsx$`, but limiting the search of those terms to the file path only).

In the image below, I'd like the `Heading.jsx` file on line 4 to show on the results (because it has `color` inside the file), but I wouldn't like the file `Color.js` to show, unless, of course, the file has the word `color` inside it.
![image](https://user-images.githubusercontent.com/7675500/58163466-5ed42700-7c84-11e9-8448-3d5e00eba8c3.png)

Even better would be to have by default the filter only working on the contents of the file, and if I needed, I could specify with some [search syntaxes](https://github.com/junegunn/fzf#search-syntax) on the extensions terms to limit those to the path of the file, so in the same query, i could search terms on the filename, and on the contents of the files.

Is there a way of doing that? If not, would you think its something worthy to implement?
I guess this could also be useful for ignoring a filename on a search...

What do you think?

**Comment by junegunn** [comment]
First off, you don't need `'` prefix when you use`$` suffix or `^` prefix because they are for exact matches as described in https://github.com/junegunn/fzf#search-syntax (fuzzy match doesn't really make much sense in those contexts).

By the way, `'.js$` working in the above case seems like a bug. What does it mean? Is it looking for a line that ends with `'.js` or a line that contains `.js$`? In either case, it shouldn't match any line.

Anyway, in this case, I usually take advantage of `:` between the path and the content. For example, `js: color` or even `js:color`. `js:` also matches `jsx:` because it's fuzzy but the lines with `js:` take precedence, so it usually suffices.

**Comment by GabrielDuarteM** [comment]
@junegunn Indeed, now that I think about it, the `'.js$` seems indeed a bug. My initial reasoning was "Match the files that end with exactly `.js`"

Image to ilustrate:
![image](https://user-images.githubusercontent.com/7675500/58408354-eeefe300-806d-11e9-9780-1b7ba1884ddd.png)

Here, my reasoning was: Match for `js: color`, ignoring the extensions `json`, `.story.js`, `js.snap`, and `.test.js`

The project is quite big, so I end up with lots of false positives, like `console.log('Running tests ...');`, which is not optimal. That's why I think it would be good to have a way to define something like a "path" syntax search.

I tried adding `'color` to the search terms, but then it starts searching again for `color` on the filename

**Comment by junegunn** [comment]
Why don't use pass `color` to `:Rg` command in the first place? It's much more efficient to use fzf only as the secondary filter. I almost always start `:Ag` or `:Rg` with a search keyword using these mappings:

```vim
nnoremap <silent> <Leader>ag       :Ag <C-R><C-W><CR>
xnoremap <silent> <Leader>ag       y:Ag <C-R>"<CR>
```

**Comment by GabrielDuarteM** [comment]
That's a good point! I'll start doing that.

Thanks for the help and, of course, for the awesome plugins!
