### ISSUE TITLE
how to force fzf to don't follow symbolic link ?

### ISSUE THREAD

**Issue by kevlarcade** [junegunn/fzf#1584]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

Hi,
In a folder, I have a symbolic link to a folder upstream so if I run `fzf -e` in this folder it include the folder multiple time like:
```
foo/bar/symlink_to_foo
foo/foo/bar/symlink_to_foo
```
So, how to force fzf to don’t follow symbolic link?

**Comment by junegunn** [comment]
You might want to read through the README page and learn about `FZF_DEFAULT_COMMAND` environment variable.

Related:
- https://github.com/junegunn/fzf#usage
- https://github.com/junegunn/fzf#tips
- `man find`
