### ISSUE TITLE
Ansi mode only supports 8 colors, but tcell supports 24-bit

### ISSUE THREAD

**Issue by atsepkov** [junegunn/fzf#1585]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [x] Mac OS X
    - [x] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [x] bash
    - [x] zsh
    - [x] fish

FZF relies on tcell for ansi/color conversion, so initially I thought the 8-color limitations came from tcell. When reading tcell description,  as well as looking at its color implementation (https://github.com/gdamore/tcell/blob/master/color.go), we can see that tcell supports 24-bit colors without issues. Almost all modern terminals support at least 256 colors, and many now support 24-bit as well. Yet when attempting to send either the 24-bit ansi code (ESC[38;2;{r};{g};{b}m) or the 256-color (ESC[38;5;#m) to the preview window, the escape sequence gets garbled.

**Comment by junegunn** [comment]
True color support was added in 0.23.0.

https://github.com/junegunn/fzf/pull/2156
