### ISSUE TITLE
Removing single quotes seems impossible

### ISSUE THREAD

**Issue by snowe2010** [junegunn/fzf#1586]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

Using preview to display `--with-nth` with any other text causes issues with single quote escaping. 

```
➜ echo "a'b \0c'd \0e'f \0g'h" | fzf --delimiter="\\0" --with-nth=1,2,3,4 --nth=1,2,3,4 --preview="echo 'Test: {1}'" 
```

results in 

```
zsh:1: unmatched ' 
```

in the preview window. 

I'm unsure of how to solve this, as I've tried escaping the single quotes in the `echo` before piping to fzf and the issue is the same.

**Comment by junegunn** [comment]
> {} in the command is the placeholder that is replaced to the single-quoted string of the current line.

`{}` is already quoted that you can use it without worrying about escaping issues. So just try this:

```sh
echo "a'b \0c'd \0e'f \0g'h" | fzf --delimiter="\\0" --with-nth=1,2,3,4 --nth=1,2,3,4 --preview="echo 'Test: '{1}"
```

**Comment by snowe2010** [comment]
I had read the man page about 5 or 6 times and didn't understand how I would escape those strings. I did not realize that echo could handle parameters that way. Is it that `echo` just echos everything it is passed, but you need to put quotes around things with spaces? If so that makes a ton more sense now. 

I would never have figured this out, due to not understanding that functionality of `echo`. Thanks for the help.

**Comment by dinomon456** [comment]
Is there a way to perform operations like `rg --smart-case vim -r $'\nvom'` in bash or `rg --smart-case vim -r \n'vom'` in fish where you want to use an escaped character in the command you are executing for the preview or execute()
