### ISSUE TITLE
__fzf_history__ of `echo "* * *"` is invalid

### ISSUE THREAD

**Issue by miyanokomiya** [junegunn/fzf#1587]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [x] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

### Before submitting

- Make sure that you have the latest version of fzf
0.18.0 (brew)
- If you use tmux, make sure $TERM starts with "screen"
occurred without tmux

## issue
When I get a command `echo "* * *"` from `__fzf_history__` (Ctrl-r), the command is invalid (the asterisk is expanded as a wildcard?)
<img width="299" alt="スクリーンショット 2019-05-26 21 58 43" src="https://user-images.githubusercontent.com/20733354/58382226-b36bff00-8002-11e9-8088-d63e3d43a65d.png">
<img width="517" alt="スクリーンショット 2019-05-26 21 59 09" src="https://user-images.githubusercontent.com/20733354/58382232-c2eb4800-8002-11e9-88ff-1d08ba34ea1a.png">

**Comment by junegunn** [comment]
I can't reproduce the problem. Can you test again without any other configuration?
i.e. `bash --rcfile ~/.fzf.bash`

**Comment by miyanokomiya** [comment]
I'm sorry, you are right. It is because of my configuration to omit duplicated histories.
If I remove this config, fzf works well. Thanks.

```sh
__fzf_history__() {
  if type tac > /dev/null 2>&1; then tac="tac"; else tac="tail -r"; fi
  shopt -u nocaseglob nocasematch
  echo $(HISTTIMEFORMAT= history | command $tac | sed -e 's/^ *[0-9]\{1,\}\*\{0,1\} *//' -e 's/ *$//' | awk '!a[$0]++' |
    FZF_DEFAULT_OPTS="--height ${FZF_TMUX_HEIGHT:-40%} $FZF_DEFAULT_OPTS --sync -n2..,.. --tiebreak=index --bind=ctrl-r:toggle-sort $FZF_CTRL_R_OPTS +m" $(__fzfcmd))
}
```
