### ISSUE TITLE
Installing FZF for all users (existing and future) in Linux Ubuntu 18.04

### ISSUE THREAD

**Issue by KShutter** [junegunn/fzf#1589]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

While it is very easy to install FZF for a given user under Linux server, I am wondering if there is a way to install it such that it automatically becomes available for all users - existing or new. Having that clearly laid out would help wonder to make FZF the standard server feature that it has long deserved to be. Thanks!

**Comment by mcepl** [comment]
I don't understand. What's wrong with ``sudo apt-get install fzf``?

**Comment by archaeogeek** [comment]
`sudo apt-get install fzf` is not given as an option in the install instructions at https://github.com/junegunn/fzf/blob/master/README.md? Also for me at least it simply doesn't work (Ubuntu 18.04), so if it's supposed to be possible to install it this way, we need information on which repository to add.

**Comment by mcepl** [comment]
I see, https://packages.ubuntu.com/search?keywords=fzf it is just for more recent distributions. Couldn't you install from Debian repos (https://packages.debian.org/search?keywords=fzf)? I really don't know, I don't use any Debian-base distro.

**Comment by NickLarsenNZ** [comment]
Would be nice as either an `apt` or `snap` package

**Comment by 0xphk** [comment]
Maybe you could make use of the /etc/skel and /etc/bash.bashrc skeleton files used in ubuntu to create home environments for new users. You could just manually install from git and prepare the files for it. As fzf install just sources some files, this should be doable but I did not try it myself.

**Comment by johnny88** [comment]
Yeah the problem is for anyone that is using the lts version as the fzf package only exists in 19.04... So yeah I'd say it's git for now.

**Comment by Ray-Eldath** [comment]
Sad... 😞  My distribution is ubuntu 18.04...

**Comment by mcepl** [comment]
Isn’t there some PPA? Didn’t anybody create the one?

**Comment by rojan** [comment]
> Sad...  My distribution is ubuntu 18.04...

There is fzf ppa for ubuntu 18.04

https://launchpad.net/~fmarier/+archive/ubuntu/ppa

```
sudo add-apt-repository ppa:fmarier/ppa
sudo apt-get update
sudo apt install fzf
```

**Comment by fkromer** [comment]
+1 for installation of fzf on Ubuntu 18.04. Provifing fzf via [snap](https://snapcraft.io/) would possbile as well, right?

**Comment by JurrianFahner** [comment]
@mcepl @fkromer It is also possible to download the deb manually via https://packages.ubuntu.com/eoan/fzf

and then perform the install

```bash
sudo dpkg -i ./fzf_0.18.0-2_amd64.deb
```

Disadvantage of this workaround is you won't get any updates.

**Comment by fkromer** [comment]
@JurrianFahner Thanks a lot for the hint!

**Comment by mcepl** [comment]
> @mcepl @fkromer It is also possible to download the deb manually via https://packages.ubuntu.com/eoan/fzf

Or if there is some altruism in you, you can create your own PPA and just rebuild (and then follow) the package from the modern distro.

**Comment by smnbbrv** [comment]
Why is this closed? Ubuntu is the most used Linux distro and there is support of pretty much everything else but Ubuntu.

**Comment by junegunn** [comment]
Because I'm not a maintainer of any of the Linux packages.

**Comment by andres-blanco** [comment]
if somebody is using debian 9, you need to add the backports package repository:
```
echo "deb http://ftp.debian.org/debian stretch-backports main" | sudo tee /etc/apt/sources.list.d/backports.list
sudo apt update
```

then, you can install fzf with:
```
sudo apt-get install fzf
```
