### ISSUE TITLE
Open vim from the fzf terminal list

### ISSUE THREAD

**Issue by naseer** [junegunn/fzf#159]
In a directory, I'm doing something like ` ag mysearchstring | fzf`
Is it possible to bind a shortcut to open vim at the line number of the result ?

**Comment by junegunn** [comment]
Yes we have the filename and the line number, it's trivial to write a shell script for that

```sh
# fag - (sorry about the name though)
fag() {
  [ $# -eq 0 ] && return
  local out cols
  if out=$(ag --nogroup "$@" | fzf); then
    cols=(${out//:/ })
    vim ${cols[0]} +"normal! ${cols[1]}zz"
  fi
}
```

By the way, I tried to enable colored output with `ag --nogroup "$@" | fzf --ansi`, but realized the current version of fzf does not correctly remove some ANSI escape sequences. This will be fixed in the next release. (#162)

**Comment by balta2ar** [comment]
@naseer sorry for offtopic, but if you use ag, you might also want to try `pt` (the platinum searcher). On some inputs it's even faster than ag (however lacks few options).

**Comment by naseer** [comment]
@junegunn - thanks, works like a charm, although I renamed it to agv in my bashrc :)
Now all it needs is to go to the next result from within vim - if it's possible :)

@balta2ar thanks for the `pt` tip - It does seem slightly faster

**Comment by junegunn** [comment]
@naseer fzf 0.9.6 is released with the fix. Now you can have properly colored output with `ag --nogroup --color "$@" | fzf --ansi`.

**Comment by ldong** [comment]
For **zsh** people

```zsh
fag() {
  [ $# -eq 0  ] && return
  local out cols
  if out=$(ag --nogroup --color "$@" | fzf --ansi); then
    setopt sh_word_split
    cols=(${out//:/  })
    unsetopt sh_word_split
    vim ${cols[1]} +"normal! ${cols[2]}zz"
  fi
}
```

Or if you [bogado/fileline](https://github.com/bogado/file-line)

```zsh
fag() {
  [ $# -eq 0  ] && return
  local out cols
  if out=$(ag --nogroup --color "$@" | fzf --ansi); then
    setopt sh_word_split
    cols=(${out//:/  })
    unsetopt sh_word_split
    filepath=${cols[1]}:${cols[2]}
    vim $filepath
  fi
}
```


Note: *zsh* does not split by whitespace and array index is 1-based by default.
