### ISSUE TITLE
Open in Editor result of Search File Content

### ISSUE THREAD

**Issue by flamendless** [junegunn/fzf#1590]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [x] Vim
    - [ ] Neovim
    - [x] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

how can i open the file in vim when i press enter on the result of this in the [wiki?](https://github.com/junegunn/fzf/wiki/Examples#searching-file-contents)

**Comment by junegunn** [comment]
This is a general shell scripting question rather than an issue specific to fzf. I suggest that you ask these questions on different places such as stackoverflow.

**Comment by VladimirMikulic** [comment]
@flamendless you can configure an alias:
alias vopen="fzf | xargs vim"

Try it :)
