### ISSUE TITLE
Selection/copy of text in preview window

### ISSUE THREAD

**Issue by atsepkov** [junegunn/fzf#1591]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [x] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

Currently FZF preview mode is limited to scrolling, but does not allow selecting any text within it, which would be a useful feature for anyone wishing to copy/paste something from preview window. In my case (a text-based web browser based on FZF), the preview window takes up considerable chunk of the screen and being able to interact with the text in it in some way would be very desirable, here is an example of a web-page from which I may want to copy/paste some code:
![Screen Shot 2019-05-30 at 2 33 14 PM](https://user-images.githubusercontent.com/2549997/58655328-e3a7ec00-82e7-11e9-9c61-f10f39215bdf.png)

The logic responsible for scrolling the preview window seems to be at https://github.com/junegunn/fzf/blob/master/src/terminal.go#L1925, but aside from scrolling ignores all other mouse/keyboard events. Would it be possible to either add ability to select text via mouse (i.e. into some buffer I can then reference via an FZF key bind) or add a mode toggle so I can capture keyboard events instead of having FZF apply them to the search results (i.e. to simulate selection via some key toggle, followed by arrow keys to move cursor around preview window, and then toggle to confirm/cancel)?

I'm aware that there is `--no-mouse` flag, which would allow FZF to fall back to terminal's own selection, but as you can see from the screenshot, that would just end up selecting a bunch of garbage (the FZF search results I use as a manifest to allow the user to search/navigate the document).

**Comment by junegunn** [comment]
I'm not interested in adding more functionality to the preview window. It's named "preview" window because I designed it for quick and simple previewing purposes and no more than that.

It's cool that you're pushing the limits of what you can do with fzf, but please remember that fzf is still just an interactive version of "grep", so it may not be suitable for building more sophisticated TUI applications.
