### ISSUE TITLE
fzf doesn't work with overloaded history command

### ISSUE THREAD

**Issue by shalak** [junegunn/fzf#1592]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

I'm using overloaded `history` command that strips the history entry numbering like so:

```bash
history() {
  if [ -t 1 ]; then                                                          
    # to terminal: print numbers and timestamps
    builtin history "$@"
  else
    # grepping: only command
    HISTTIMEFORMAT='' builtin history "$@" | awk '{$1="";print substr($0,2)}'
  fi
}
```
Without the entry numbering the `ctrl+r` feature of `fzf` doesn't work properly - when I choose the command it's not filled into the prompt

Note that with the command above stuff like `!12` still works properly.

**Comment by junegunn** [comment]
Does this fix your problem?

```diff
diff --git a/shell/key-bindings.bash b/shell/key-bindings.bash
index be24dec..2ecf685 100644
--- a/shell/key-bindings.bash
+++ b/shell/key-bindings.bash
@@ -55,7 +55,7 @@ __fzf_history__() (
   local line
   shopt -u nocaseglob nocasematch
   line=$(
-    HISTTIMEFORMAT= history |
+    HISTTIMEFORMAT= builtin history |
     FZF_DEFAULT_OPTS="--height ${FZF_TMUX_HEIGHT:-40%} $FZF_DEFAULT_OPTS --tac --sync -n2..,.. --tiebreak=index --bind=ctrl-r:toggle-sort $FZF_CTRL_R_OPTS +m" $(__fzfcmd) |
     command grep '^ *[0-9]') &&
     if [[ $- =~ H ]]; then
```

**Comment by shalak** [comment]
Yes, it does

**Comment by kiemrong08** [comment]
Hi @shalak , can you explain step by step how to only display command and remove line number from history ? I trying modify the `key-bindings.bash` but dont accomplish

**Comment by bAndie91** [comment]
IMO when you overload a command, you have to keep its interface (input arguments, stdout output format).

**Comment by shalak** [comment]
> Hi @shalak , can you explain step by step how to only display command and remove line number from history ? I trying modify the `key-bindings.bash` but dont accomplish

Hi @kiemrong08! Sorry for late reply, I must've missed it.

The code I pasted does exactly that. If I use the `history` command in terminal (it's checked by `[ -t ]` it's forced to bypass the recurrent call to said `history` by using `builtin history`, so the behavior is not changed whatsoever. But if you use `history` in some script (i.e. the output is not terminal), is forces consistent format by setting `HISTTIMEFORMAT` temporarily. Then, since the format is consistent, I can pipe the output to `awk` which first removes the first field from the whole line (i.e. the number). Then it prints substring of the the line starting from the second character till the end - that way the whitespace between number and command is also not printed.

@bAndie91 
Dude, it's bash, it's scripting, not a strictly typed language with contracts :) The possibility to do this is the very reason for existence of the `builtin` command.
