### ISSUE TITLE
Piping a command to fzf seems to break interactivity of 'execute' bind?

### ISSUE THREAD

**Issue by atsepkov** [junegunn/fzf#1593]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [x] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

I'm not sure if I understand the problem correctly, I'm basically guessing by the symptoms. I believe less in non-interactive mode works like `cat`, simply dumping the contents to screen. That behavior seems to be consistent with a bug I'm noticing. The following simple command works as expected, launching less upon the `f1` bind in interactive mode:

    fzf --bind "f1:execute(less -f {})"

Creating a simple test script (for my purposes I created a js file with 10 `console.log()` statements, 1 on each line), and piping that to fzf results in less window terminating as soon as invoked:

    node test.js | fzf --bind "f1:execute(less -f {})"

Moreover, when quitting fzf, I see that the terminal tried to execute each one of those lines, implying that the contents of the file were simply dumped to the terminal, like `cat` would do. Just to test that the problem wasn't with node, I also tried catting the same file to fzf:

    cat test.js | fzf --bind "f1:execute(less -f {})"

The file contents:

```
console.log('foo bar baz quuz');
console.log('foo bar baz quuz');
console.log('foo bar baz quuz');
console.log('foo bar baz quuz');
console.log('foo bar baz quuz');
console.log('foo bar baz quuz');
console.log('foo bar baz quuz');
console.log('foo bar baz quuz');
console.log('foo bar baz quuz');
console.log('foo bar baz quuz');
console.log('foo bar baz quuz');
```

**Comment by junegunn** [comment]
Interactive programs read from standard input assuming it's a TTY device, so you need to redirect STDIN (and STDOUT) when it's not.

```sh
# Doesn't work
#   Vim: Warning: Output is not to a terminal
#   Vim: Warning: Input is not from a terminal
ls | fzf --bind "f1:execute(vim {})" > selected

ls | fzf --bind "f1:execute(vim {} < /dev/tty > /dev/tty 2>&1)" > selected
```

**Comment by joeshaw** [comment]
I'm a new user and I got burned by this too, thank you for the answer.  Please consider adding this to the `less` example in the README.

**Comment by doronbehar** [comment]
Thanks @junegunn for answering this. I have a similar issue but a little bit more complex:

```
some command | fzf --bind "f1:execute(show {} | less)" | do something with output
```

I want to be able to both run a piped command inside the `exectue(` and pipe the output of fzf to another program. Where should I put the `/dev/tty` redirection in this case?

I tried:

```
some command | fzf --bind "f1:execute(show {} | less < /dev/tty > /dev/tty 2>&1)" | do something with output
```

But that produced weird behavior when I pressed `f1`.

**Comment by junegunn** [comment]
You're redirecting the output of `show {}` as the standard input of `less`, but at the same time setting `/dev/tty` as the standard input as well, sending two conflicting messages to less. Instead of piping it, pass the file name to less directly.

```sh
ls | fzf --bind "f1:execute(less {} < /dev/tty > /dev/tty 2>&1)"
ls | fzf --bind "f1:execute(less -f <(cat {}) < /dev/tty > /dev/tty 2>&1)"
```

**Comment by cohml** [comment]
I'm attempting to do something similar, and perhaps even simpler? But I'm struggling (zsh user btw).

Basically my goal is to bind `enter` to an action which echoes one of the fields to the terminal for further editing.

For example, given the following output

```bash
❯ git grep import | head
asr/0.1.0/asr.py:import sys
asr/0.1.0/asr.py:import json
asr/0.1.0/asr.py:from pathlib import Path
asr/0.1.0/asr.py:import wave
asr/0.1.0/asr.py:from vosk import KaldiRecognizer, Model, SetLogLevel
asr/0.1.0/asr.py:from speech_fluency import SpeechFluencyService  # noqa
asr/0.1.0/audio.py:import base64
asr/0.1.0/audio.py:import logging
asr/0.1.0/audio.py:import ffmpeg
asr/0.1.0/audio.py:from pydub import AudioSegment
```

I want to pipe this to `fzf`, select one or more results, then hit `enter` to echo the "filepath" field (i.e., `{+1}`, using `:` as the delimiter). So if I select the first and last entries above, then hit `enter`, I should see

```
❯ asr/0.1.0/asr.py asr/0.1.0/audio.py
```

and be able to modify that text right away.

Here is what I thought would work:

```bash
--bind='enter:execute(echo -n {+1})'
```

I've also tried `become` and `execute-silent`, plus various flavors of tee `/dev/tty` stuff recommended above, but I was mostly guessing blindly.

In all cases, what happens is that `fzf` never terminates, and when I manually exit it, I *do* see the intended text on my screen, but I can't interact with/edit it, and it disappears when I press enter. It's as if I can see the `echo` process working, but its outputs are not available to me.

Is the problem description clear? Any pointers?

**Comment by LangLangBart** [comment]
> Basically my goal is to bind `enter` to an action which echoes one of the fields to the terminal for further editing.


`zsh` has a unique `print -z` command, which places a string onto the buffer stack for editing[^1]

```bash
print -z "$(
	git grep --color=always -- import |
		head |
		fzf --multi --delimiter : \
			--bind 'enter:become:echo {+1}' \
			--bind 'ctrl-t:execute:less -+F {1} >/dev/tty'
)"
```

[^1]: [zsh: 17 Shell Builtin Commands - print](https://zsh.sourceforge.io/Doc/Release/Shell-Builtin-Commands.html#index-print)

**Comment by cohml** [comment]
So I see that `print -z` has the desired effect in the context of a function:

```bash
❯ function foo() {
  print -z "bar"
}
❯ foo
❯ bar
```

In other words, when I execute `foo`, `"bar"` is magically pasted to the command line for downstream editing.

Running your snippet, I also see that the desired field is pasted to the command line. That's exactly what I want.

But I'm unsure how to adapt your snippet for execution via an `fzf` keybinding instead of `print -z $(... fzf ...)` as you have it. For example, after running the following and making a selection, my command line is blank:

```bash
❯ git grep import | head | fzf --delimiter=":" --bind="enter:become(print -z {+1})"
```

Is there a way to achieve this same behavior via keybinding as above?

**Comment by doronbehar** [comment]
> Is there a way to achieve this same behavior via keybinding as above?

I think that in any case you'd need to wrap the `fzf` call inside `zsh`, and not the other way around. That's because `print -z` is a ZSH internal function, and you need to run it inside the ZSH session you are in.

You could create a ZSH function that will run `fzf` with something like:

```
--bind="enter:execute(echo PRINTZ_NEXTLINE)+accept"
```

And then inside that ZSH function, catch that `PRINTZ_NEXTLINE` (conditionally if needed), and `print -z` the next line that is printed thanks to accept.

**Comment by cohml** [comment]
> You could create a ZSH function that will run `fzf`

I've actually had a lot of trouble doing this. Is the following what you mean?

```zsh
❯ function foo() {
  print -z "${@}"
}
❯ git grep import | head | fzf --delimiter=":" --bind="enter:become(foo {+1})"
zsh:1: command not found: foo
```

For some reason, my functions can't be found inside the child processes spawned by `fzf` actions.

I haven't asked about this problem yet because I'm still unsure whether this problem is particular to me, versus a quirk of `fzf`.

**Comment by doronbehar** [comment]
Here's a sketch for a ZSH code:

```zsh
function foo() {
  importChoice="$(git grep import | head | fzf --delimiter=":" --bind=enter:"execute(echo PRINTZ_NEXTLINE)+accept")"
  if echo "$importChoice" | head -1 | grep -q PRINTZ_NEXTLINE; then
    printz -z "$(echo "$importChoice" | tail -n +2)"
  else
    # Maybe don't do anything, or:
    echo "$importChoice"
  fi
}
