### ISSUE TITLE
CTRL-R shows me the list of files instead of history

### ISSUE THREAD

**Issue by rofrol** [junegunn/fzf#1594]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [x] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

When I press `Ctrl+r`, I see list of files instead of entries from history.

**Comment by junegunn** [comment]
Must be a configuration issue. You won't be able to reproduce the problem with a minimal config.

i.e. `bash --rcfile ~/.fzf.bash`

**Comment by rofrol** [comment]
I don't know what this command do but I got this output:

```
$ bash --rcfile ~/.fzf.bash
update_history: command not found
```

**Comment by junegunn** [comment]
It clearly shows that this is just a configuration issue and I can't help you with that. This repository does not contain `update_history` whatever it may be. You may have some offending environment variables set, so prepend `env -i` to exclude them.

```sh
env -i bash --rcfile ~/.fzf.bash
```
