### ISSUE TITLE
Eval Flag

### ISSUE THREAD

**Issue by zQueal** [junegunn/fzf#1595]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [x] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

```zsh
alias _history='cat ~.zhistory | fzf'
alias history='eval $(_history)'
```

The above works perfectly. It runs through my `~/.zhistory` file for all commands, and allows me to fuzzy find previous commands and execute them by pressing return.

It's a bit hacky. Wouldn't it make more sense to add a flag that attempts to execute `STDOUT` as a command?

```zsh
alias history='cat ~/.zhistory | fzf --exec'
```

**Comment by junegunn** [comment]
fzf is an interactive version of grep, thus it is designed to be context-agnostic. It should not have `--exec` option for the same reason it does not have `--open-with-editor`, `--open-in-browser`, `--kill-pid`, `--connect-to-host`, `--lookup-dictionary` or any type of action that can be performed with a line of text.
