### ISSUE TITLE
feature request: page up/down in results list

### ISSUE THREAD

**Issue by crichardson332** [junegunn/fzf#1597]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

Feature request: Would it be possible to add a configuration option in fzf to bind keys for paging up and down in the fzf list in the vim way? As in, binding ctrl-u and ctrl-d to half-page up/down (also ctrl-f and ctrl-b for full page) in the results list instead of having to press ctrl-j and ctrl-k many times to navigate?

**Comment by junegunn** [comment]
See `KEY BINDINGS` section of the man page.

**Comment by crichardson332** [comment]
omg so good
