### ISSUE TITLE
Really long prompts render oddly in certain cases

### ISSUE THREAD

**Issue by wart-github** [junegunn/fzf#1599]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

Hi,

I'm using dwm + st.  The behavior occurs both inside tmux and outside tmux, and if I have TERM="st-256color" or TERM="screen-256color" or TERM="screen".  Note the behavior only seems to be in st: xterm works fine!  

To reproduce:

1. Set a really long prompt, e.g., 

fzf --prompt "a really long prompt that will render funky and it is really long and it is going to render funky and so on"

2. Enter tile mode such that the prompt is wider than the (tiled) window's width.

Result:

The prompt will get scrambled in an odd way.  If, however, I have st in full screen (monocle mode in dwm) the really long prompt gets clipped properly.

**Comment by junegunn** [comment]
I can't reproduce the problem with the latest version of fzf. Please leave a comment if you still have the problem.
