### ISSUE TITLE
fish bindings only work in vi normal mode, not insert mode

### ISSUE THREAD

**Issue by oschrenk** [junegunn/fzf#160]
I'm using the vi bindings in fish, mostly via fzf-tmux. The key bindings only work in normal mode. Is it possible to allow them also in insert mode thus saving me a few keystrokes?

**Comment by junegunn** [comment]
Hi, actually I'm not really familiar with fish and didn't even know that fish has vi mode. Feel free to send me a pull request for that.

**Comment by oschrenk** [comment]
Will try, but can't promise.

**Comment by junegunn** [comment]
No pressure. FYI, vi mode on bash has the same problem. I'll close the issue for now. Thanks!
