### ISSUE TITLE
fzf history not working when GREP_OPTIONS is set

### ISSUE THREAD

**Issue by j86989** [junegunn/fzf#1603]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [x] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [x] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

Hi!

I've experienced this issue for months. Finally I've found out the cause.

If you use newer grep, it warns you about use of `GREP_OPTIONS` as this environment variable is deprecated:

```
$ `__fzf_history__`
    206  source ~/.bashrc
    207  pwd
    208  vim ~/.bash_profile
    209  echo $RAND
    210  echo $RANDOM
    211  export GREP_OPTIONS='--color=always'
    212  [01;31m[K  2[m[K10  echo $RANDOM
    213  unset GREP_OPTIONS
    214  echo $RANDOM
    215  man grep
    216  grep -v
    217  grep -V
    218  man grep
    219  grep fdsafadsfsd
    220  grep fdsafadsfsd .bash_history
>   221  export GREP_OPTIONS='--color=always'
  221/221 +S
> grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
``` 

Unfortunately this behavior breaks `fzf`. In consequence, `fzf` prepends junk characters to selected command.

```
$ export GREP_OPTIONS='--color=always'
$ `__fzf_history__`
$ ^[[01;31m^[[K  2^[[m^[[K07  pwd
ommand not found
31m: command not found
```

It took me so long to discover what was wrong because `grep` warning message doesn't show up in some environments (`macOS`). I got this warning message when I loaded my `.bashrc` on `WSL`.

**Comment by junegunn** [comment]
See:
- https://github.com/junegunn/fzf/pull/1113
- https://github.com/junegunn/fzf/issues/1453#issuecomment-489290576
