### ISSUE TITLE
Watch mode for preview

### ISSUE THREAD

**Issue by csreegn** [junegunn/fzf#1605]
- Category
    - [X] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [X] Linux
    - [X] Mac OS X
    - [X] Windows
    - [X] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [X] bash
    - [X] zsh
    - [X] fish

As an FZF user I want a preview flag that allows the preview command to be executed every n seconds (similarly to the unix 'watch' command).
Sadly I cannot use the watch command, as FZF preview formats it in a weird way.

Eg. I am using this command:
```
kubectl api-resources --no-headers | fzf --preview='kubectl get --all-namespaces {1} --watch' --preview-window=down:75%:wrap
```
I want the preview command to be executed periodically while in preview, not just once, because the output of that command is changing continuously and I want to monitor that within the preview mode.

**Comment by junegunn** [comment]
"Preview" window, as the name implies, was designed only for simple, static contents. It's extremely non-trivial to implement a preview window that renders dynamic content.

Consider starting/restarting the command in a tmux split pane by using a hidden preview window (`--preview-window hidden`).

**Comment by junegunn** [comment]
This is now possible with the latest version of fzf. Here is something I use for Kubernetes pods.

```sh
pods() {
  local selected tokens
  selected=$(
    kubectl get pods --all-namespaces |
      fzf --info=inline --layout=reverse --header-lines=1 --border \
          --prompt "$(kubectl config current-context | sed 's/-context$//')> " \
          --header $'Press CTRL-O to open log in editor\n\n' \
          --bind ctrl-/:toggle-preview \
          --bind 'ctrl-o:execute:${EDITOR:-vim} <(kubectl logs --namespace {1} {2}) > /dev/tty' \
          --preview-window up:follow \
          --preview 'kubectl logs --follow --tail=100000 --namespace {1} {2}' "$@"
  )
  read -ra tokens <<< "$selected"
  [ ${#tokens} -gt 1 ] &&
    kubectl exec -it --namespace "${tokens[0]}" "${tokens[1]}" -- bash
}
```

**Comment by vchirikov** [comment]
@junegunn I don't test it in Linux, but on Windows it doesn't change preview window if you select another pod. But if I remove `--follow` from kubectl everything works fine :(

**Comment by timsofteng** [comment]
@junegunn 

```
 kubectl -n name get pod --no-headers \
  | fzf --reverse --preview-window right:follow --preview "kubectl -n name logs {1} --tail 100 | bat --plain --style=numbers -"
  ```
  
  Doesn't work for me
  what do I do wrong?
