### ISSUE TITLE
Feature request: optional neovim floating window for FZF

### ISSUE THREAD

**Issue by unclechu** [junegunn/fzf#1613]
To show FZF buffer in a neovim's floating window.

Here is my own example of calling this API:
https://github.com/unclechu/neovimrc/blob/de52d4a451e667381d73488f82f45af6dcba46cd/my-modules/open-padded-floating.vim#L42-L48

**Comment by junegunn** [comment]
https://github.com/junegunn/fzf/blob/master/README-VIM.md#starting-fzf-in-a-popup-window
