### ISSUE TITLE
How to go back to the fzf list after editing using vim in `vim (rg -i string . -l | fzf)`

### ISSUE THREAD

**Issue by c02y** [junegunn/fzf#1615]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [x] fish

When I use vim to open the file searched by rg/ag/grep like this:
~~~
vim (rg -i string . -l | fzf)
~~~
after if I edit the file using vim, I need to come back to fzf list (include the filter I typed) for me to choose again instead of exiting the entire command, but currently I have to execute `vim (rg -i string . -l | fzf)` again and type the filter to get the list I wanted, since the command cost a few seconds, it will waste time.

After exiting vim, how can make fzf back to the state before editing using vim(`Enter` on the chosen file)?

**Comment by junegunn** [comment]
fzf doesn't maintain persistent state in any way so it's not possible. However, as a workaround, you can consider using `execute` action using `--bind` option like so:

```sh
rg -i string . -l | fzf --bind 'enter:execute:vim {} < /dev/tty'
```

**Comment by c02y** [comment]
Thank you, it works
Could you please add a built-in option for fzf to maintain persistent state, it is very useful for a lot of other programs.

**Comment by junegunn** [comment]
No, it's beyond the scope of the project. And it's not really possible because fzf reads from standard input over which we don't have any control.
