### ISSUE TITLE
Extra space appended messes up bash history on ctrl-R

### ISSUE THREAD

**Issue by kkew3** [junegunn/fzf#1617]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [x] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

When using `Ctrl-R` key binding, the completed history command is appended by incrementally more spaces, rendering multiple visually duplicate entries in bash history. It exhibits the same behavior when I was using `__fzf_history` function from the Wiki page. Is there anything I should do to fix it? Thank you so much! (Attached gif; there are multiple `echo 'hello'` commands in history in the end; sorry that the GIF is a bit slow)

![ScreenRecording2019-06-23at1](https://user-images.githubusercontent.com/13264071/59971958-55f2b000-95b8-11e9-92a6-ad116e64cf05.gif)

**Comment by junegunn** [comment]
I believe the latest version does not exhibit this problem.
