### ISSUE TITLE
Question with potential FeatureRequest - How to turn off/on FZF in shell?

### ISSUE THREAD

**Issue by marcotrosi** [junegunn/fzf#1619]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [x] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [x] Mac OS X
    - [x] Windows
    - [x] Windows Subsystem for Linux
    - [x] Etc.
- Shell
    - [x] bash
    - [x] zsh
    - [x] fish

Hi,

how can I turn off/on FZF in a shell **without uninstalling FZF**?
**In a way that the triggers \*\* (double star), Ctrl-t, Ctrl-r, Alt-c get back their original shell behavior** (if they had a meaning before installing FZF).

Thank you

If this is not possible, then I would like to suggest a shell variable to activate/deactivate FZF.

Thank you

Have a great day

--marco

**Comment by rod-stuchi** [comment]
Maybe this can help

```sh
fzf-disable() {
  sed -i -E 's/(.*fzf\.zsh)/#\1/' ~/.zshrc
  exec $SHELL -l
}

fzf-enable() {
  sed -i -E 's/#(.*fzf\.zsh)/\1/' ~/.zshrc
  exec $SHELL -l
}
```
![demo-fzf-enable-disable](https://user-images.githubusercontent.com/19471811/67149644-1432f700-f284-11e9-9bf1-7fcc731b2af7.gif)

**Comment by marcotrosi** [comment]
Hi @rod-stuchi ,

thanks for your feedback. very appreciated.

I can't find fzf lines in my bash files. I need to figure out where "brew" added such lines on macOS
