### ISSUE TITLE
Feature request: allow sorting by file "distance"

### ISSUE THREAD

**Issue by sitaktif** [junegunn/fzf#1624]
- Category
    - [x] fzf binary
- OS
    - [x] Any
- Shell
    - [x] Any

It would be great to have a feature that sorts files by "distance" to the current directory. By distance I mean "how many directory changes are needed to be in that file's directory".

Examples of distance values:
- `otherfile1` --> 0
- `otherdir1/otherfile2` --> 1
- `../otherfile3` --> 1
- `../otherdir2/otherfile4` --> 2

The implementation could be quite simple: take the number of slashes in the path as the distance.

This would be quite useful when called from an editor when one wants to open a file that is close to the currently edited file.

**Comment by wookayin** [comment]
See #788

**Comment by junegunn** [comment]
Thanks @wookayin!
