### ISSUE TITLE
fzf with (pk)ksh shell?

### ISSUE THREAD

**Issue by drozdowsky** [junegunn/fzf#1628]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [x] FreeBSD
- Shell
    - [ ] bash
    - [ ] zsh
    - [ ] fish

Is it possible to run fzf in other shell?

**Comment by junegunn** [comment]
fzf is an executable binary, so why not?

Shell key bindings (CTRL-T, CTRL-R, ALT-C) and fuzzy completion (https://github.com/junegunn/fzf/tree/master/shell) are only implemented for bash, zsh, and fish, but they are optional components of the project.

**Comment by drozdowsky** [comment]
If anyone want to use FZF without bash on FreeBSD:
```
pkg add fzf
pkg remove -f bash
```
