### ISSUE TITLE
Simplistic key mapping support

### ISSUE THREAD

**Issue by junegunn** [junegunn/fzf#163]
There has been demands for custom key mappings inside fzf (#139, #96, #61) mostly for better integration with Vim. So here's a simple idea that might meet such requirements.

Let's say we add an option that takes a comma-separated list of key chords, such as `ctrl-v`, `ctrl-t`, or `alt-a`. I can't think of a good name for this imaginary option, but let's call it `--select-with` for now.

```
fzf --select-with=ctrl-v,alt-s
```

Then fzf will allow me to select the item with any of the given key chords in addition to the default enter key. But in this case, fzf will print the name of the key chord used as the first line of the output.

```
> fzf --select-with=ctrl-v,alt-s
alt-s
foobar
```

Now we know which key was pressed, and our script can use the information to decide what to do next.

There are some questions to be answered:

1. What should be the name of the option?
    - `--select-with`
    - `--select-key`
    - `--selector`
    - `--expect`
    - `--using`
    - `--with`
    - `--via`
    - `--on`
2. Should we allow enter key by default? Or should we demand that the user specify enter key (or ctrl-m) as well? (e.g. `--select-with=alt-t,enter`)
    - I don't think it makes a lot of sense to disable enter key
3. When this option is used with `--print-query`, which should be printed first, query or the key pressed?
    - You type in query, then press the key chord, so query should be printed first

**Comment by junegunn** [comment]
Added `--expect` option in 0.9.6.

**Comment by Tranquility** [comment]
I updated to 0.9.6 but get `unknown option: --expect`. The vim plugin also fails.

**Comment by junegunn** [comment]
@Tranquility Did you rerun the install script? It'll download the new binary.

**Comment by junegunn** [comment]
Hmm, maybe I should check if the version is >= 0.9.6 from inside vim plugin.

**Comment by Tranquility** [comment]
`fzf --version` tells me that I am at 0.9.6

**Comment by junegunn** [comment]
@Tranquility What's the output of `:!fzf --version` from inside vim?

**Comment by Tranquility** [comment]
It is not related to vim. Version 0.9.6 does not contain the option, even `fzf --help` does not list it.

**Comment by junegunn** [comment]
That's super strange. I have tested it both on OS X and Linux. Can you show me the md5 hash of the binary installed?

**Comment by Tranquility** [comment]
Oh, I am sorry, I found the problem. I built it from source yesterday. So the version from by $GOPATH was used which already had the new version number. After I removed the file it uses the correct binary.

**Comment by junegunn** [comment]
Ah, I see. No problem :) Try CTRL-T/X/V from `:FZF` command.

**Comment by Tranquility** [comment]
It's awesome!

**Comment by junegunn** [comment]
Cool, thanks!

**Comment by junegunn** [comment]
FYI, there was a bug in the new vim plugin :pensive: (#167) Please update again.
