### ISSUE TITLE
Automate/unattended installation of FZF?

### ISSUE THREAD

**Issue by ReneFroger** [junegunn/fzf#1632]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ x ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [x] fish

Hi, due to my obsessive inclination to fiddle with my setup, my system breaks every two á three weeks I guess. That's why my whole system configuration ( `.config` or `.local`) is symlinked with Dropbox. 
Every time when my system breaks, I run a 1600 lines long bash script to reinstall everything, then symlink from my Dropbox to my home folder and then I'm in the system again, everything is restored.

There is only one thing that prevents me to have an unattended installation. When I clone FZF, and start with `fzf/install`, it ask me everytime when I want keybindings, fuzzy find file, and to attend my scripts. I choose every time yes, yes and no. Is there a way to 'pre-set' this, so I can the FZF installation, like with `apt install -y [package-name]`?

**Comment by junegunn** [comment]
To bypass the prompt, you can use the options shown in `install --help`. e.g. `./install --all`

**Comment by ReneFroger** [comment]
That's great! Didn't knew even the `install` contains a manual. Perhaps mention that in documentation too? 

Thanks!
