### ISSUE TITLE
'ctrl-i:toggle-in' breaks the default action of 'tab:toggle+down'

### ISSUE THREAD

**Issue by moriakijp** [junegunn/fzf#1633]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [x] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

When using --bind 'ctrl-i:toggle-in', tab's action seems to be changed to toggle+up, this is the opposite of the normal Tab behavior. Please check it.
The following are my nice keymaps:

```
 --bind 'ctrl-i:toggle-in,ctrl-o:toggle-out,ctrl-x:select-all,ctrl-r:deselect-all,ctrl-t:toggle-all,ctrl-s:toggle-sort,ctrl-j:jump,ctrl-k:kill-line,ctrl-g:cancel,alt-up:half-page-up,alt-down:half-page-down,ctrl-alt-p:preview-page-up,ctrl-alt-n:preview-page-down'
```

**Comment by moriakijp** [comment]
fzf version: 0.18.0 (brew)
OS: macOS Mojave 10.14.5 18F132 x86_64
Host: MacBookPro13,2
Kernel: 18.6.0
Shell: zsh 5.7.1
Terminal: iTerm2

**Comment by junegunn** [comment]
The direction of the movement is determined by "reverse"-ness of the layout (i.e. `--reverse` or `--layout=reverse`). Try it with and without `--reverse`. It works for me as expected.

**Comment by moriakijp** [comment]
Oh `ctrl-i` and `tab` cannot be assigned separately.
Now I see why the brackets are attatched to `tab`, in the manual. 
```
toggle+down  ctrl-i (tab)
toggle-in   (--layout=reverse* ? toggle+up : toggle+down)
toggle-out  (--layout=reverse* ? toggle+down : toggle+up)
toggle+up   btab (shift-tab)
```
Thanks for giving me awareness.
