### ISSUE TITLE
No keybindigs after installation on Manjaro

### ISSUE THREAD

**Issue by baatochan** [junegunn/fzf#1636]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [x] Key bindings
    - [x] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

After installing the `fzf` on Manjaro (via `pacman` or Octopi) keybindings are not set and files `~/.fzf.bash` and `~/.fzf.zsh` are not created.

Effectively using `CTRL+R` doesn't trigger `fzf` and `CTRL+T` doesn't work.

I couldn't find any info how to manually create those missing files.

Looks like it's related to #1385.

**Comment by vitorfreitas** [comment]
Managed to solve this by adding these two lines at the end of my .zshrc file:

```bash
source /usr/share/fzf/key-bindings.zsh
source /usr/share/fzf/completion.zsh
```

**Comment by baatochan** [comment]
Shouldn't it be somehow automated? Like why does installing manually from repo does it automatically for you, but installing from official system repo forces you to set it up by yourself?

**Comment by junegunn** [comment]
You should ask the maintainers of the Manjaro package.
