### ISSUE TITLE
fzf --preview is empty if $SHELL points to missing file

### ISSUE THREAD

**Issue by lilyball** [junegunn/fzf#1637]
- Category
    - [X] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [X] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [X] fish

If my `SHELL` variable points to a file that doesn't exist, the preview window shown with `fzf --preview` is completely empty, not even showing an error.

I didn't even know the preview command was executed using my current shell. I don't see any documentation to this effect. Apparently the preview works by executing the equivalent of `${SHELL:-sh} -c "$previewCommand"`, so if `SHELL` points at a missing file, this fails. But in this case, the failure isn't printed to the preview window, it's just silently swallowed.

I discovered this when using `fzf` from a `fish` shell after having reinstalled fish in a new location and uninstalling the old (and then running `exec fish -l` from my active terminal window, which preserved existing env vars including `SHELL`).

Due to this, I think two things need to be done:

1. The fact that `--preview` uses `$SHELL` should be documented somewhere, ideally both in the manpage and in the repo README.
2. If the execution of `$SHELL` itself fails, fzf should print an error to the preview window indicating that. It should probably only do so if the execution result indicates that the command couldn't be found or executed at all, rather than on any non-zero result from the shell, as there are many commands that return an expected non-zero status code (such as `grep`)

**Comment by azzoz20148** [comment]
h●●●●●@hotmail.com

**Comment by junegunn** [comment]
Thanks for the suggestion. I just merged #1810 which addresses the points.
