### ISSUE TITLE
Strange CTRL-R behaviour, opens file finder instead of history search

### ISSUE THREAD

**Issue by 0xphk** [junegunn/fzf#1639]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [x] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

Hi, 

since yesterday I have a strange behavior when using the fzf_ctrl_r_command.
Not quite sure if I messed up something but now issuing CTRL-R opens the fzf file finder instead of the history search. 
If canceling this with CTRL-C an empty editor opens and if I close the editor, the fzf_history search finally opens and is usable. 

I already did a reinstall but the behaviour persists. I added some extra defaults to my .bashrc but think I did not mess with the fzf files itself. 

I've found the issue #1594 with a supposed config issue. I tried your suggestion with an empty environment and it was working again as expected.

The following I have added to my .bashrc, could please anyone help and look where the issue could be? 

Thanks a lot

```
[ -f "${XDG_CONFIG_HOME:-$HOME/.config}"/fzf/fzf.bash ] && source "${XDG_CONFIG_HOME:-$HOME/.config}"/fzf/fzf.bash
export FZF_DEFAULT_OPTS="--ansi --layout=reverse --height=80% --preview='bat --color=always --style='numbers,grid' {}' --preview-window=right:60% " 
export FZF_DEFAULT_OPTS+="--bind ctrl-f:jump --bind ctrl-k:kill-line --bind ctrl-p:toggle-preview "
export FZF_DEFAULT_OPTS+="--bind alt-o:preview-up --bind alt-n:preview-down --bind alt-m:preview-page-down --bind alt-p:preview-page-up"

export FZF_DEFAULT_COMMAND='ag --hidden --ignore .git -g ""'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"

bind -x '"\C-e": nano $(fzf);'

alias nf='nano $(fzf)'
alias ne='nano $(fzf --exact)'
alias vf='vim $(fzf)'
alias ve='vim $(fzf --exact)'
```

Thank you for this awesome project.

**Comment by junegunn** [comment]
> I've found the issue #1594 with a supposed config issue. I tried your suggestion with an empty environment and it was working again as expected.

It's not something we can help you with. You'll have to find which part of your config is interfering with the binding, maybe by incrementally commenting in and out your config file.

P.S. Setting `--preview` option for file paths in `$FZF_DEFAULT_OPTS` is not recommended since fzf is not just for file paths.
