### ISSUE TITLE
Alt-C not working on OSX

### ISSUE THREAD

**Issue by simonweil** [junegunn/fzf#164]
Using OSX Yosemite in bash with vim mode, `Alt-C` just prints out `ç`.

`CTRL-T` & `CTRL-R` work perfectly.

Thanks for a great tool and really awaiting the neovim support!

**Comment by junegunn** [comment]
If you use iterm2, try this (excerpt from https://iterm2.com/faq.html)

```
Q: How do I make the option/alt key act like Meta or send escape codes?

A: Go to Preferences->Profiles tab. Select your profile on the left, and then open the Keyboard tab. At the bottom is a set of buttons that lets you select the behavior of the Option key. For most users, Esc+ will be the best choice.
```

**Comment by johnhamelink** [comment]
It's important to note that if you have a GB keyboard; this will stop you being able to use the `#` character with `alt+3` in iTerm. If you want to do this, you'll need to change your keyboard to Australian, which is exactly the same except `£` and `#` are swapped.

**Comment by simonweil** [comment]
Works great, thanks!
Maybe add this info to the readme?

**Comment by varepsilon** [comment]
Note that you don't necessarily need to change the behavior of the `Alt` key if you use it to type special characters. You may just use `Esc+C` instead of `Alt-C` to do fzf's fuzzy directory change.

**Comment by andrewclapham** [comment]
If you are using a normal Mac OSX terminal (not iTerm2), here are two solutions:

Solution 1:
You can open your terminal, and in the menu at the top of the screen, open "Preferences", click the "Profiles" tab then go to "Keyboard" section and then check the checkbox that is called "Use Option as Meta key". The downside of this is that you can't type characters like øœåΩ®ü etc easily at the terminal.

So instead:

Solution 2:
You can send the "Meta" by typing pressing "Control-[", so then the solution to get fzf's awsome magical find-the-directory-and-cd-into-it feature is to simply press:
"Control-[ c". Similar to varepsilon's solution of hitting "Esc c".

Thanks!

**Comment by TheJavaGuy** [comment]
If you use ZSH, add this line to `.zshrc`:
`bindkey "ç" fzf-cd-widget`

**Comment by jordelver** [comment]
I use Fish with Vim keybindings and I used the Fish version of what @TheJavaGuy suggested

`bind -M insert "ç" fzf-cd-widget`

**Comment by NightMachinary** [comment]
I needed to manually set `alt-down` and `alt-up` in iTerm:
![image](https://user-images.githubusercontent.com/36224762/109409966-1ba3fd80-79ac-11eb-9d19-8d884a3edb7c.png)

The default was `^[[1;9A` instead of `^[[1;3A`.

**Comment by vivek-dg** [comment]
Even adding `ALT-C` wasn't as pleasing to me as including the following at the bottom my `~/.fzf.zsh` file. You do need to adjust the query if you don't have `fd` installed. 

<pre><code>
if type fd &> /dev/null; then
    cdc () {
        cd "$( fd -td | fzf )"
    }
    cdh () {
        cd "$( fd -td . $HOME | fzf )"
    }
fi
</code></pre>

Just type `cdc<ENTER>` in the command prompt to change into a subdirectory. Use `cdh<ENTER>`  to search for a directory under the entire home directory. Create new definitions as needed. You won't have to delete the leftovers from using `cd` and `ALT-C` upon completion. Plus it was much faster for whatever reason. You could change it based on any other command equivalent instead of `fd`.

**Comment by mahfuzsust** [comment]
I use Fish(v3.3.1) and this helped for me
`bind "ç" fzf-cd-widget`

**Comment by misraelson** [comment]
Getting something strange when doing this:
unknown option: -t

**Comment by Yarden-zmr** [comment]
Anyone using iterm can also just rebind it to the expected behavior like so
<img width="617" alt="Screen Shot 2022-07-29 at 15 47 39" src="https://user-images.githubusercontent.com/8178413/181763697-97c19977-3671-4359-8e92-a917a7878a7d.png">

**Comment by corneliusroemer** [comment]
For hyper the hyper terminal, you need to add the following to the config:
```
        modifierKeys: {
            altIsMeta: true,
        },
```

Without this setting, you will get the cedille ç instead of `meta-c` or `alt-c`

See https://apple.stackexchange.com/questions/445913/how-to-pass-option-c-to-hyper-terminal-rather-than-%c3%a7

**Comment by pcj** [comment]
Bash users: the given `share/fzf/key-bindings.bash` has:

```bash
# ALT-C - cd into the selected directory
bind -m emacs-standard '"\ec": " \C-b\C-k \C-u`__fzf_cd__`\e\C-e\er\C-m\C-y\C-h\e \C-y\ey\C-x\C-x\C-d"'
bind -m vi-command '"\ec": "\C-z\ec\C-z"'
bind -m vi-insert '"\ec": "\C-z\ec\C-z"'
```

So this can be additionally bound in the `~/.bashrc` or similar to the cedille character as:

```bash
# ALT-C - cd into the selected directory
bind -m emacs-standard '"ç": " \C-b\C-k \C-u`__fzf_cd__`\e\C-e\er\C-m\C-y\C-h\e \C-y\ey\C-x\C-x\C-d"'
bind -m vi-command '"ç": "\C-z\ec\C-z"'
bind -m vi-insert '"ç": "\C-z\ec\C-z"'
```

**Comment by vishalpaudel** [comment]
Ok, so you need to do the `opt-c` or `alt-c` not after `cd **` like as for tab. Actually in a empty prompt do `opt-c` and you will go into `__fzf_cd__`-ing. The tutorial video linked in the README.md was unclear about this at [04:18](https://www.youtube.com/watch?v=qgG5Jhi_Els&t=258s).  


For Alacritty lovers, add this to ~/.config/alacritty/alacritty.yml:  

```yaml
key_bindings:
  - { key: F,  mods: Alt,           chars: "\x1bf"                       }
  - { key: B,  mods: Alt,           chars: "\x1bb"                       }
```. 

**Mind the two spaces**.  

Also, to find more of these useful bindings for alacritty, check out my [alacritty yml](https://github.com/vishalpaudel/dotfiles/blob/main/terminal/.config/alacritty/alacritty.yml)

**Comment by johnend** [comment]
None of the above working for me on `zsh` for some reason (just inserting a blank line) the widget solution from @TheJavaGuy didn't work for me either 🤦 

So instead I use this:
```zsh
bindkey -s 'ç' "fd --type d . --hidden | fzf --preview 'tree -C {} | head -50'^M"
```
Not very clean but it works. Probably something I'm missing, or there is a conflict somewhere, just leaving this here incase someone else has similar issues.

**Comment by pumpkinmuffin** [comment]
the earlier solution for alacritty did not work for me but this does in my `alacritty.toml`:
```toml
[keyboard]
bindings = [{ key = "C", mods = "Alt", chars = "\u001bc" }]
```

**Comment by sliminality** [comment]
Likewise here is the updated Alacritty config from @vishalpaudel's suggestion:

> For Alacritty lovers, add this to `~/.config/alacritty/alacritty.yml`:
> 
> ```yaml
> key_bindings:
>   - { key: F,  mods: Alt,           chars: "\x1bf"                       }
>   - { key: B,  mods: Alt,           chars: "\x1bb"                       }
> ```

```yaml
key_bindings:
  - { key: F,  mods: Alt,           chars: "\u01bf"                       }
  - { key: B,  mods: Alt,           chars: "\u01bb"                       }
```

**Comment by asrarsyed** [comment]
@davidfitzgerald-p Just had the same issue and I managed to get it working by changing iTerm2 preferences. The other suggestions didn't seem to work, only the key rebind seems to work. You just need to ensure it is a global keybind (not profile specific) and apply it to all sessions!

**Comment by jrcasey** [comment]
Anyone figure out a fix for Ghostty?

**Comment by hajiboy95** [comment]
> Anyone figure out a fix for Ghostty?

two options, either 
```config
keybind = opt+c=text:\x1bc
```

to your Ghostty config (`\x1b = esc`) 

or you remap the command in your `.zshrc` config file via e.g. `bindkey '^Z' fzf-cd-widget` (i used `ctrl + z` here to not overwrite the shortcut for `ç`)
