### ISSUE TITLE
Names garbled when using neovim master 

### ISSUE THREAD

**Issue by neevparikh** [junegunn/fzf#1644]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [x] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

Directory names and file names appear garbled when using neovim master with FZF (floating window or not)

![fzf](https://user-images.githubusercontent.com/41182432/61608735-6ce8f880-ac71-11e9-997e-67cabac4940c.png)

Any fix on the fzf side or is it a neovim issue?

**Comment by junegunn** [comment]
Looks like an issue of your `$FZF_DEFAULT_COMMAND`. fzf doesn't parse ANSI color codes when not explicitly requested via `--ansi` for performance reasons.

**Comment by victoriastuart** [comment]
* https://unix.stackexchange.com/questions/403916/getting-started-with-fzf-on-arch-linux

"When selecting files with fzf, we show file content with syntax highlighting, or without highlighting if it's not a source file. If the file is a directory, we use tree to show the directory's contents.  We only load the first 200 lines of the file which enables fast previews of large text files. Requires highlight and tree: `pacman -S highlight tree`"

* https://github.com/junegunn/fzf#performance

"`--ansi` tells fzf to extract and parse ANSI color codes in the input and it makes the initial scanning slower. So it's not recommended that you add it to your `$FZF_DEFAULT_OPTS`."

Try this:

`export FZF_DEFAULT_OPTS="--ansi --preview '(highlight -O ansi -l {} 2>/dev/null || cat {} || tree -C {}) 2>/dev/null | head -200'"`

... note the `--ansi` before `--preview` ...
