### ISSUE TITLE
Install script doesn't take "no" for an answer in updating dotfiles

### ISSUE THREAD

**Issue by henrebotha** [junegunn/fzf#1648]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [x] Key bindings
    - [x] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

I noticed this odd behaviour while updating (which I did by updating my repo in `~/.fzf` to `6577388` & then running `~/.fzf/install`):

```
Do you want to update your shell configuration files? ([y]/n) n

Update /home/hbotha/.bashrc:
  - [ -f ~/.fzf.bash ] && source ~/.fzf.bash
    - Already exists: line #119

Update /home/hbotha/.zshrc:
  - [ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
    - Already exists: line #357
```

It seems like the install script is ignoring my choice here.

**Comment by junegunn** [comment]
The message can be confusing, but when you say no to the question, the script won't update the file, so don't worry. It checks if the line exists, but that's it. If your configuration doesn't have the line, it prints:

```
Update /Users/jg/.bashrc:
  - [ -f ~/.fzf.bash ] && source ~/.fzf.bash
    ~ Skipped
```
