### ISSUE TITLE
ctrl-r stopped showing commands from other shells

### ISSUE THREAD

**Issue by srsudar** [junegunn/fzf#1649]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [x] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

Until recently, I am 90% sure, `ctrl-r` would reverse search an up-do-date version of my history. Put another way, `ctrl-r` would always show the same list of most recent commands no matter which terminal I was running it in.

Recently, however, the output of `ctrl-r` does not immediately include commands run from other shells. For example say that I opened two shells. In my first shell I wrote `echo 'from shell 1'`. When I ran `ctrl-r` in that shell, the first entry would be something like: `10088 echo 'from shell 1'`. When I go to the second shell and run `ctrl-r`, the first entry would be: `10087 ls`.

`ctrl-r` in shell one:

```
10087 ls
10088 echo 'from shell 1'
```

`ctrl-r` in shell two:

```
10087 ls
```

However, I appear to be able to fix this by running a command from the second shell (inadvertently editing the history file), running `less .zhistory` on the history file, or even just `fc -rl 1 | less`. After any of those operations, `ctrl-r` in the second shell will be correct again.

This is especially weird because `which fzf-history-widget` shows to be calling `fc -rl 1` as part of the function, so I would expect that command to be equivalent to manually invoking `fc -rl 1 | less`.

`bindkey | rg fzf` shows that `ctrl-r` is bound to fzf-history-widget.

Is there any way that the history results could be cached by fzf or something similar? I would love to get shared history across shells back.

**Comment by srsudar** [comment]
edit typo in title, my apologies

**Comment by junegunn** [comment]
> This is especially weird because which fzf-history-widget shows to be calling fc -rl 1 as part of the function

As you have noted, `fzf-history-widget` simply runs `fc -rl 1` to get the list of commands. There is no cache or anything it separately maintains. You'll have to find a way to make the command return the up-to-date command history. Maybe there are some related zsh options? I'm not a zsh user so I can't really help you with that.
