### ISSUE TITLE
[Question] Can fzf use /bin/ls instead of ls? (alias issue)

### ISSUE THREAD

**Issue by stevenBorisko** [junegunn/fzf#1650]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

On Arch, I have lsd installed (https://github.com/Peltoche/lsd) and have ls aliased to lsd (alias ls="lsd"). When this alias is set, fzf runs crazy slow since I assume it uses the command ls to see files, and lsd, being fancy, takes longer to run. The obvious fix is to stop aliasing it, but the alias is really convenient.

Is there a way in fzf to specify that I want it to use '/bin/ls' instead of the command ls?

**Comment by junegunn** [comment]
> Is there a way in fzf to specify that I want it to use '/bin/ls' instead of the command ls?

fzf by default does not use `ls`. Please read through the README page to learn about configuration options.
