### ISSUE TITLE
What's the keyboard shortcut to open file current directory?

### ISSUE THREAD

**Issue by zero-jack** [junegunn/fzf#1651]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [x] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

Describe your problem or suggestion from here ...
I want to open files current directory on Finder when I use `fzf` on iTerm2 as below 

```
  test/t2.txt
  test/t3.txt
> test/t1.txt
  4/142
> txt
```

I used Alt-C to click on files like Command-C  but nothing happened though I followed this suggestion

> Q: How do I make the option/alt key act like Meta or send escape codes?
> 
> A: Go to Preferences->Profiles tab. Select your profile on the left, and then open the Keyboard tab. At the bottom is a set of buttons that lets you select the behavior of the Option key. For most users, Esc+ will be the best choice.

**Comment by junegunn** [comment]
There is no such shortcut. fzf is just a text-filter. It's up to you to implement what you're trying to do with the selected text. Please read through the README page to understand what fzf really is.
