### ISSUE TITLE
Support an --align parameter in fzf

### ISSUE THREAD

**Issue by andrewferrier** [junegunn/fzf#1652]
- Category
    - [X] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [X] Linux
    - [X] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [X] zsh
    - [ ] fish

This is a feature request, really. It would be nice if `fzf` could support some alignment command-line parameter, so that items could be aligned within the window with a non-leftmost alignment if they are longer than the window.

For a more specific example - I maintain a vim plugin called [vim-fileselector](https://github.com/andrewferrier/vim-fileselector), which allows for file selection of recently-opened files, etc. I typically find that some filenames (which include full file paths) are longer than the screen-width (especially when also using `fzf`'s preview window). Typically, the most relevant and important part of a filename is the right-most; the base filename itself. However, the user sometimes can't see that, because it runs past the edge of the `fzf` window. It would be nice if `fzf` supported a parameter such as `--align=right`, which tried to keep the text right-aligned as much as the current search pattern allows (and the search pattern starts off empty, so all lines would be aligned right).

This principle could be extended to support an `--align=center`, I suppose, although I have no specific use-case for that right now.

(I am using fzf `0.18.0 (brew)`).

**Comment by junegunn** [comment]
I added `--keep-right` option, which will trim the left side of the string, instead of the right.

The option is somewhat partially implemented to keep the implementation simple, that it is effective only when the query string is empty. But I believe that it's good enough for most cases especially when used with a large `--hscroll-off`.

**Comment by andrewferrier** [comment]
Thank you very much! Have added support for `--keep-right` to my plugin.

**Comment by doplumi** [comment]
is there anyway to go to right without that option enabled? i.e. select a line that ends with scroll indicator and press right arrow to show the right content? I see there's a `--no-scroll` option, so that's probably already implemented but I don't know how to trigger it?
