### ISSUE TITLE
Toggling ignore files or temporarily disabling it?

### ISSUE THREAD

**Issue by flipjs** [junegunn/fzf#1653]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [x] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

Not an issue, but I want to know if there's a way to temporarily disable respecting gitignore? I have `node_modules`in my .gitignore, which most of the time, I dont want them in my search results. But sometimes, I want to peek and open files from it. Is there a way to toggle this feature inside vim and on the terminal? Thanks.

**Comment by junegunn** [comment]
You can define separate commands for both use cases. To learn how to define custom commands in Vim, see https://github.com/junegunn/fzf/blob/master/README-VIM.md#fzfrun
