### ISSUE TITLE
--tiebreak ignores -n

### ISSUE THREAD

**Issue by NoSuck** [junegunn/fzf#1655]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

Thank you for `fzf`.  It is one of those tools you can no longer live without, once it has infected your brain.

```
printf '%s\n' 'a looooooooong' 'aaa short' | fzf -n1
```

Type `a` after invoking `fzf` as above.  The `aaa short` item is selected, even though `-n` has supposedly limited search scope to the first field (`a` vs `aaa`).

It seems that tie-breaking settings ignore `-n`.  Is this a bug?  #926 looks to be related.

```
■ fzf --version
0.18.0 (6577388)
```

**Comment by junegunn** [comment]
You can use `--tiebreak chunk` now.
