### ISSUE TITLE
How do I disable the TAB keybinding in zsh?

### ISSUE THREAD

**Issue by NightMachinary** [junegunn/fzf#1656]
I have taken a look at https://github.com/junegunn/fzf/blob/master/shell/key-bindings.zsh, but I don't know what part is responsible for setting TAB.

**Comment by wookayin** [comment]
https://github.com/junegunn/fzf/blob/master/shell/completion.zsh#L197

**Comment by NightMachinary** [comment]
`    bindkey '^I' expand-or-complete`
