### ISSUE TITLE
bug: alt-<number> keybindings not recognized

### ISSUE THREAD

**Issue by herrsimon** [junegunn/fzf#1657]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [x] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

Hello,

<alt+number> keybindings don't seem to work in fzf. For example, when running

``echo test | fzf --expect=alt-1 --delimiter=' '``

or

``echo test | fzf --bind=alt-1:abort``,

nothing happens when pressing alt-1. In contrast to this, the above commands work when replacing alt-1 by alt-a or any other alt+<letter> combination. Also, the builtin alt-keybindings (alt-f, alt-b etc.) work as well.

My terminal (urxvt on X) sends escape codes for both letters and numbers, i.e. pressing alt-1 or alt-a sends ^[1 and ^[a, respectively. I made sure that the alt-<number> sequence is not intercepted by a window manager or any other application. The issue is also present on a tty without running X.

**Comment by junegunn** [comment]
Thanks for the report, this indeed turned out to be a bug of fzf.

**Comment by herrsimon** [comment]
thanks a lot for the quick fix!
