### ISSUE TITLE
Alternative way of installing fzf

### ISSUE THREAD

**Issue by SiliconKite** [junegunn/fzf#1659]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [X ] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [ ] fish

This is an installation issue on an work machine running where I do not have root access to update stuff, running an old red hat 5.6 OS. 
It is not possible for me to run the install file, as things start to fail due to old libraries of OpenSSL, wget, curl etc. Is there any other way of installing fzf ? 
Thanks

**Comment by LuRsT** [comment]
Hi @SiliconKite,

You could try to build the binary from another computer and copying it over to the machine you want.

**Comment by junegunn** [comment]
You can download pre-built binaries from https://github.com/junegunn/fzf-bin/releases.

The install script doesn't do much, it basically
1. downloads the latest binary
2. generates a script that adds fzf to $PATH, and loads key bindings and completion script
3. and updates your shell configuration to load that script.
