### ISSUE TITLE
FZFTag not working - awk error

### ISSUE THREAD

**Issue by LmtEdition** [junegunn/fzf#166]
I'm starting to use some of the vim examples in the wiki in my workflow. This is probably a dumb question, but does anyone know why FZFTag isn't working for me?

OS: OSX Yosemite 10.9.5
Vim 7.3 that came with installed.
Shell: fish, version 2.1.1-1205-gdd595dd

I'm assuming I just type :FZFTag, and it should bring up a list of functions from my tags file. The error I'm seeing instead is:

awk: syntax error at source line 1
 context is
	clear 2> >>>  /dev/null/^ <<< clear 2> /dev/null/ { print \$1 }
awk: bailing out at source line 1

I don't think it's because vim version is too old, since I see a similar issue on Ubuntu where I'm running a more current version of vim.

Thanks!

**Comment by junegunn** [comment]
Yeah, it didn't work for me either. Now here's the working version.

```vim
command! FZFTag if !empty(tagfiles()) | call fzf#run({
\   'source': "sed '/^\\!/d;s/\t.*//' " . join(tagfiles()) . ' | uniq',
\   'sink':   'tag',
\ }) | else | echo 'No tags' | endif
```
