### ISSUE TITLE
Is there a way to get the index of the selection?

### ISSUE THREAD

**Issue by NightMachinary** [junegunn/fzf#1660]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [ ] fish

I want to get the indices of selections (relative to the input).

**Comment by notevenodd** [comment]
I don't think there's a fzf option for this, but one possibly way/workaround you might wish to use is to prefix the input to fzf with line numbers, for example ... | cat -n | fzf ..., then extract the line number from the selected line.

**Comment by bAndie91** [comment]
see #1482

**Comment by junegunn** [comment]
To add to what @notevenodd suggested above, you can use `--with-nth` to hide the index field inside fzf.

```sh
ls | cat -n | fzf --with-nth 2.. | awk '{print $1}'
```

And for `--preview` command and `execute` bindings, `{n}`  and `{+n}` should do the trick.

**Comment by desk7** [comment]
I was also searching for a solution and finally found one simpler with the command options available in this moment:
```bash
ls | fzf --accept-nth={n}
```
