### ISSUE TITLE
FZF_CTRL_T_OPTS seemingly not applied

### ISSUE THREAD

**Issue by PMarci** [junegunn/fzf#1661]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [x] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

I have been periodically improving my `fzf` configuration, and recently I noticed that the preview window doesn't show anymore when pressing CTRL + T. I shuffled around my options quite a bit, so I'm not sure what might have caused it. I have my fuzzy completion configured like described at [Configuring-fuzzy-completion#dedicated-completion-key](https://github.com/junegunn/fzf/wiki/Configuring-fuzzy-completion/dedicated-completion-key).
Here are the relevant lines of my `.zshrc`:
```
# fzf config
export FZF_ALT_C_OPTS="--preview 'tree -C {} | head -200'"

# export FZF_CTRL_T_OPTS="--preview '[[ $(file --mime {}) =~ binary ]] &&
#                  echo {} is a binary file ||
#                  (bat --style=numbers --color=always {} ||
#                   highlight -O ansi -l {} ||
#                   coderay {} ||
#                   rougify {} ||
#                   cat {}) 2> /dev/null | head -500' --preview-window=right:60%"
export FZF_CTRL_T_OPTS="--preview 'cat {}'"
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
export FZF_COMPLETION_TRIGGER=''
bindkey '^T' fzf-completion
bindkey '^I' $fzf_default_completion
```
The commented out value comes from my recent testing with the suggested preview option from `README.md`. As you can see the current value is `--preview 'cat {}'`, for testing a minimal version to rule out issues in the commands themselves. Even with `--preview 'cat {}'` or `--preview 'cat {}' --preview-window=right:60%`, the preview window doesn't show up, not under `tmux` and not in the plain GNOME terminal either.
**_Strangely enough_** `FZF_ALT_C_OPTS` **_does_** work under all circumstances.

### Notes
* I have `bat` installed
* my `$TERM` under tmux doesn't start with `screen` (it's `tmux-256color`), but the behaviour I'm describing is identical both under tmux and outside it, in GNOME terminal, and in Xterm as well
* I have `oh-my-zsh` installed, but I made sure to **not** have their "plugin" of `fzf` enabled
* I don't `setopt vi` anywhere, yet `bindkey '^I'` still returns `"^I" expand-or-complete`, but it seems to me that shouldn't be relevant for my problem
* after noticing the issue I updated my installation using `git pull` and `~/.fzf/install`
* I call `bindkey '^X'` and `zle -N` in my `.zshrc` after the last line in the fragment above, but nothing else
* I also tried reinstating the default `FZF_COMPLETION_TRIGGER='**'` setting because that was one of the things I was messing around with, but this didn't fix my problem

Any help is appreciated, thanks.

**Comment by PMarci** [comment]
I'd also like to note that when I run `fzf ` with the contents of `FZF_CTRL_T_OPTS` appended, the preview works as expected

**Comment by junegunn** [comment]
It's because you mapped your CTRL-T to fuzzy completion, not default "CTRL-T" binding.

So you need to customize fuzzy completion instead. See https://github.com/junegunn/fzf#settings

**Comment by PMarci** [comment]
Many thanks for looking into my issue! I'm very glad to have this detail resolved in my setup.

**Comment by PMarci** [comment]
I just discovered that if you want to use the example preview config from `README.md` as your `FZF_COMPLETION_OPTS` like so:
```
export FZF_COMPLETION_OPTS="--preview '[[ $(file --mime {}) =~ binary ]] &&
				       echo {} is a binary file ||
				       (bat --style=numbers --color=always {} ||
					highlight -O ansi -l {} ||
					coderay {} ||
					rougify {} ||
					cat {}) 2> /dev/null | head -500' --preview-window=right:60%"

```
It won't work since the `$()` around the `file` command will be evaluated early. 
If your command to complete was `vi` it prints:
``` 
$ vi unknown option: (No
```
and exits. To fix it, escape the dollar sign once, so the subshell command looks like this: `\$(file --mime {})`. This should've been more obvious to me, but I missed it. I'll note it here for future reference.
