### ISSUE TITLE
ctrl-R history search suddenly stopped working

### ISSUE THREAD

**Issue by ehudt** [junegunn/fzf#1662]
- Category
    - [ X ] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ X ] Etc.
- OS
    - [ X ] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ X ] zsh
    - [ ] fish

Hi, my history search (ctrl-R) began malfunctioning in zsh this morning. The search works, and I can also browse the history with the arrows, but when I press ENTER, the command isn't pasted into the shell, and instead the selection just goes down one. You can also see that soon after I press ctrl-R, the '>' switches back to my shell prompt, which didn't happen before. I'm attaching a short screencast with the issue.
What I tried so far:
* Upgraded fzf
* Downgraded fzf
* Unset PROMPT and RPROMPT
None of these worked.

% zsh --version
zsh 5.6 (x86_64-debian-linux-gnu)
 % fzf --version
0.18.0 (ff95134)

Thanks!

![fzf-issue](https://user-images.githubusercontent.com/1566271/62690096-bdcc5100-b9d4-11e9-8be6-dac9a592207d.gif)

**Comment by mnowotnik** [comment]
Check if you use `bash` shell accidentally.

**Comment by ehudt** [comment]
When I use bash it does work :)

**Comment by mnowotnik** [comment]
Try to run it with empty `.zshrc`. I haven't experienced any problems related to `Ctrl-R` fuzzy history search with `fzf` in `zsh` shell. Only in `bash`.

Run `fzf-history-widget` to check if widget is visible in your env.

**Comment by ehudt** [comment]
Works. Thanks!
