### ISSUE TITLE
Add style support to `--color` option (bold, italic, underline, etc.)

### ISSUE THREAD

**Issue by zx8** [junegunn/fzf#1663]
- Category
    - [x] fzf binary
- OS
    - [x] Linux
    - [x] Mac OS X
    - [x] Windows
    - [x] Windows Subsystem for Linux
- Shell
    - [x] bash
    - [x] zsh
    - [x] fish

---

Right now it's possible to configure colours, e.g.

```
--color dark,fg:-1,bg:-1,hl:230,fg+:#ffffaf,bg+:233,hl+:229
--color info:150,prompt:110,spinner:150,pointer:167,marker:174
```

But when using `fzf --ansi` to parse colours from stdin, it can be quite difficult to see what's being highlighted when searching, as we generally have no control over the colours that are passed in.

It would be great if we could specify a different style to better differentiate matches (e.g. by underlining matching characters rather than displaying them in potentially clashing/static colours)

**Comment by junegunn** [comment]
Feature pushed to master. And this is how it looks.

![image](https://user-images.githubusercontent.com/700826/97111253-2827f900-1721-11eb-9086-60d20a0a877a.png)

```sh
rg --line-number --no-heading --color=always "" |
  fzf --ansi --prompt "Rg: " \
      --color fg+:italic,hl:underline:-1,hl+:underline:reverse:-1 \
      --color pointer:reverse,prompt:reverse,input:159 \
      --pointer '  '
```

It was a big change, so there can be some bugs. So please build, test it, and report any issues you run into.
