### ISSUE TITLE
'FZF ~' not working

### ISSUE THREAD

**Issue by mclearc** [junegunn/fzf#167]
Since the last update `FZF ~` isn't working for me. It just tells me that my home directory is an "unknown option". Is it possible a typo got inserted somewhere?

**Comment by junegunn** [comment]
Ha, you're right. Thanks for the report. It's fixed in the last commit.

**Comment by Shurakai** [comment]
@mclearc was this report only related to vim?

I just checked out  fzf today (cloned the repo) and used this command; but fzf will tell me the same as you. (I use zsh)

 % fzf ~
unknown option: /home/heinrich

**Comment by junegunn** [comment]
fzf does not take any arguments unlike `:FZF` on Vim. See `fzf --help` or `man fzf`.

**Comment by mclearc** [comment]
@Shurakai - I think this was a bug in FZF vim. With the current commit it works both in vim (nvim) and zsh for me.
