### ISSUE TITLE
Question/Feature Request: selectable delimiter in addition to \n and NUL

### ISSUE THREAD

**Issue by reschex** [junegunn/fzf#1670]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

I've only discovered fzf it a few days ago and I'm already in love - thanks for your work on this!

Now.. I've been looking for a way to change fzf's behaviour when it comes to seperating items and have not worked it out using man pages..

In my particular use case, a lot of the time it is much easier to generate a space seperated list of items than it is a \n seperated list, and whilst I've got a workaround, I think it would be neat to choose the dilimeter similar to how is available for the --nth/--with-nth option.

`echo "foo bar" | fzf --input-delimiter=" "` should give me two options - "foo" and "bar", opposed to just one - "foo bar" (don't care what the options is named, you've already used the obvious -d :) )

**Comment by junegunn** [comment]
You can pre-process the input before passing it to fzf like so:

```sh
echo "foo bar" | tr ' ' '\n' | fzf
```

fzf follows Unix philosophy, it was designed to be composable with other tools rather than reimplementing the wheel.
