### ISSUE TITLE
Option to ignore empty records

### ISSUE THREAD

**Issue by NightMachinary** [junegunn/fzf#1671]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [ ] fish

I use NUL-separated records and feed them into fzf, and sometimes there are empty records in those files (`some record^@^@some other record`)(`^@` is the NUL char.). I like to tell fzf to just ignore these empty records.

**Comment by junegunn** [comment]
You can use any text processing program to pre-process the input before passing it to fzf.

```sh
echo -e "foo\0bar\0\0baz" | perl -pe 's/\0\0/\0/g' | fzf --read0
```
