### ISSUE TITLE
Shell tab completion in Debian/Ubuntu non-functional

### ISSUE THREAD

**Issue by WebsterWing** [junegunn/fzf#1672]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [x] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

Fresh install of fzf on Debian 10.0 and Ubuntu 19.04 both do not allow ssh **<tab> completion. This is after the line `source /usr/share/doc/fzf/examples/key-bindings.bash` was added to .bashrc and C-r / C-t commands appear to be working.

**Comment by junegunn** [comment]
The implementation is in `completion.bash`.

**Comment by WebsterWing** [comment]
Where is that file? It doesn't appear to be installed in the .deb package.
```
$ dpkg-query -L fzf | grep '.bash$'
/usr/share/doc/fzf/examples/key-bindings.bash
```

**Comment by junegunn** [comment]
I don't use Debian, so I have no idea. Related: #1565

**Comment by absort0** [comment]
I can see that this is an old issue, but since I don't see any solution here I might as well point to what worked for me. On **Debian 10** (Codename Buster) after you have instaled **fzf** you will need to source the files for the key-bindings and bash completion, assuming you want to use bash. 

The key binds file path was already pointed out (`/usr/share/doc/fzf/examples/key-bindings.bash`), however, the bash-completion file was not. So, in order to have both working you will need to source the files at the end of your `.bashrc` like so:

```bash
source /usr/share/doc/fzf/examples/key-bindings.bash   
source /usr/share/bash-completion/completions/fzf                                                                             │
```

**Comment by mxmlnkn** [comment]
Would be really nice if this was mentioned in the README.md!

**Comment by gasull** [comment]
> I can see that this is an old issue, but since I don't see any solution here I might as well point to what worked for me. On **Debian 10** (Codename Buster) after you have instaled **fzf** you will need to source the files for the key-bindings and bash completion, assuming you want to use bash.
> 
> The key binds file path was already pointed out (`/usr/share/doc/fzf/examples/key-bindings.bash`), however, the bash-completion file was not. So, in order to have both working you will need to source the files at the end of your `.bashrc` like so:
> 
> ```shell
> source /usr/share/doc/fzf/examples/key-bindings.bash   
> source /usr/share/bash-completion/completions/fzf                                                                             │
> ```

This didn't work for me, but I see it's a [bug in bash-completion on Debian 10](https://unix.stackexchange.com/a/180677/206082).

**Comment by gasull** [comment]
> I can see that this is an old issue, but since I don't see any solution here I might as well point to what worked for me. On **Debian 10** (Codename Buster) after you have instaled **fzf** you will need to source the files for the key-bindings and bash completion, assuming you want to use bash.
> 
> The key binds file path was already pointed out (`/usr/share/doc/fzf/examples/key-bindings.bash`), however, the bash-completion file was not. So, in order to have both working you will need to source the files at the end of your `.bashrc` like so:
> 
> ```shell
> source /usr/share/doc/fzf/examples/key-bindings.bash   
> source /usr/share/bash-completion/completions/fzf                                                                             │
> ```

This didn't work for me on Debian 10 (Buster).  Ctrl+R in the terminal results in this text being expanded as if I typed it:

```
  ^E /usr/share/bash-completion/completions/fzffzf_history__`
```

I wonder if it's a bug in `bash-completion`.

**Comment by haxtibal** [comment]
@mxmlnkn 
> `/usr/share/bash-completion/completions/fzf` does not exist after installing fzf on Ubuntu 20.10

The bash-completion file path is different there (at least it is on my 20.04 installation):
```
$ dpkg -S fzf | grep 'bindings\|completion'
fzf: /usr/share/doc/fzf/examples/key-bindings.zsh
fzf: /usr/share/doc/fzf/examples/key-bindings.bash
fzf: /usr/share/doc/fzf/examples/completion.bash
fzf: /usr/share/fish/vendor_functions.d/fzf_key_bindings.fish
fzf: /usr/share/doc/fzf/examples/key-bindings.fish
fzf: /usr/share/doc/fzf/examples/completion.zsh
```

`source /usr/share/doc/fzf/examples/completion.bash` worked for me.

**Comment by venthur** [comment]
Here's a [bugreport](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1013356) from Debian, the bottom line is, the tab completion **only** works if you do `fzf <tab>` first. I.e.

> In practice, this means that in a new shell, doing "cd **<tab>" does not
offer completion. If I then do "fzf <tab>", the completion is loaded,
and after that "cd **<tab>" *does* offer fzf completion.
