### ISSUE TITLE
-1 doesn't work when use fzf+pipe+--bind

### ISSUE THREAD

**Issue by c02y** [junegunn/fzf#1673]
- Category
    - [x ] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x ] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [x ] fish

 When I use find+fzf+--bind to find a file and open with fzf, and then open with vim like this:
~~~
find Dir -iname Pattern | fzf --bind 'enter:execute vim {} < /dev/tty'
~~~
it works fine when there are multiple matches in the result of `find`, but when there is only one match, it will print the only match instead of open the file with vim

I already set `set -gx FZF_DEFAULT_OPTS '-1 -0 --reverse'` in my fish shell config file.

If I'm not using `FZF_DEFAULT_OPTS` right.
~~~
find Dir -iname Pattern | fzf -1 -0 --bind 'enter:execute vim {} < /dev/tty'
~~~
doesn't work for single match either.

So is it a bug?

**Comment by junegunn** [comment]
> when there is only one match, it will print the only match

You have `-1` in your `FZF_DEFAULT_OPTS ` and that's what the option is supposed to do; finish fzf immediately. It is unrelated to `bind` option which is only triggered when you manually hit the key.

You can use shell script to catch the output and open it with the editor.
