### ISSUE TITLE
Bind key to an existing key

### ISSUE THREAD

**Issue by neerajbadlani** [junegunn/fzf#1674]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [ X ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [X ] Linux
    - [X ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ X] bash
    - [ ] zsh
    - [ ] fish

Qeustion : Possible to bind 1 key to 2nd key which is bound to a task . 
Reason I want to do this , is that because of muscle memory i tend to press key 1 a lot , but 
for the task key 2 is logical binding .

**Comment by junegunn** [comment]
Can you be more specific? Preferably with some example cases.
