### ISSUE TITLE
FZF Not Listing Files in Certain Directories (Not Sym Links)

### ISSUE THREAD

**Issue by EarthCitizen** [junegunn/fzf#1676]
- Category
    - [ X] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [X ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ X] bash
    - [ ] zsh
    - [ ] fish

fzf version: *0.18.0*
bash version: *5.0.7*

I have a directory with the following structure:
```
src/test/groovy
src/integration-test/groovy
src/main/groovy
src/main/resources
```
`fzf` will find files in neither `src/main/groovy` nor `src/test/groovy`.

Here are the attributes of the directories:
```
drwxr-xr-x  3 user  group   96 Jan 18  2019 src/integration-test
drwxr-xr-x  3 user  group   96 Jan 18  2019 src/main/groovy
drwxr-xr-x  3 user  group   96 Jan 18  2019 src/test/groovy
drwxr-xr-x  9 user  group  288 May 31 18:52 src/main/resources
```
Even when I completely type `src/main/groovy`, nothing is found.

**Comment by junegunn** [comment]
Do you have `FZF_DEFAULT_COMMAND` defined?

**Comment by EarthCitizen** [comment]
I will close this as I am no longer working at the company I was at when I was having the problem. If it happens again, I will re-open this.
