### ISSUE TITLE
git ls-tree snippet doesn't work

### ISSUE THREAD

**Issue by xcambar** [junegunn/fzf#168]
Hi,
I can't have the tip about using `git ls-tree` (https://github.com/junegunn/fzf#git-ls-tree-for-fast-traversal) to work. I'm afraid it's outdated since `fzf` has been rewritten in Go.

Honestly, my only clue here is the `declare -f fzf` statement, which, according to SO, outputs the contents of a function. But as `fzf` is a binary executable, it doesn't realy make sense to me...

Correct me if I'm wrong, and if I am, I would nonetheless appreciate some help on getting the snippet to work under zsh 5.0.7.

Thanks for the project and the others, they're great!

**Comment by junegunn** [comment]
You're right, it was an outdated snippet, thanks for letting me know :)
I replaced the snippet with an equivalent `$FZF_DEFAULT_COMMAND`.
