### ISSUE TITLE
.ignore files are not respected in zsh

### ISSUE THREAD

**Issue by ReekyMarko** [junegunn/fzf#1681]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [x] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

I have a .ignore file in my home directory, which has `.steam/` in it. This works when I run fzf from the command line, but not when used in completion, f.ex `vim **<tab>`. I'm using ripgrep like this: 
`export FZF_DEFAULT_COMMAND='rg --files --hidden'`

**Comment by junegunn** [comment]
See https://github.com/junegunn/fzf#fuzzy-completion-for-bash-and-zsh

Fuzzy completion cannot use `FZF_DEFAULT_COMMAND` because it may have to traverse files under a different directory. e.g. `vim ~/**` So you need to override `_fzf_compgen_path` function.

**Comment by mirsella** [comment]
sorry to message in this issue closed from 2019, but personally I only use ** so use fzf only with _fzf_compgen_{dir,path}.

i tried in completion.zsh to change the long `command find -L "$1"...` to command `$FZF_DEFAULT_COMMAND $1` which don't work for the reason you cited, but when i past directly the command and adding `$1` at the end it work.

maybe using something like `$FZF_DEFAULT_COMMAND_DIR` and `$FZF_DEFAULT_COMMAND_PATH` for the command ? would be dope.
