### ISSUE TITLE
Unable to locate package on Linux Mint

### ISSUE THREAD

**Issue by pakosel** [junegunn/fzf#1682]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [x] Installation
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

On Linux Mint 18.2 I'm not able to install fzf using `apt-get` getting an error:
`sudo apt install fzf`
`Reading package lists... Done`
`Building dependency tree`
`Reading state information... Done`
`E: Unable to locate package fzf`

Also tried `sudo apt update` and `sudo apt upgrade` but still `apt` can't find the package... Any thoughts? Thanks,

**Comment by DonSlaughter** [comment]
It is not in the repository. You need to clone this git repository and install it manualy. It's all written there.

**Comment by pakosel** [comment]
It have to be in the repository since I managed to install it on my RPi with DietPi (also Debian distribution). On Mint 18.2 still cannot install it from the repository despite the fact I've changed repository source to the other mirror

**Comment by DonSlaughter** [comment]
It is in Ubuntu 19.04 but not in 16.04 which Mint 18.2 depends on or Mint 19.2 which depends on Ubuntu 18.04.

**Comment by pakosel** [comment]
OK, that's might be the case, thanks!
