### ISSUE TITLE
[FR] Show altered text on selection, but printing the orignal on validation

### ISSUE THREAD

**Issue by rockandska** [junegunn/fzf#1683]
- Category
    - [X] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [X] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [X] bash
    - [ ] zsh
    - [ ] fish

Will be handy if fzf could support an expression/function to alter the text only when we select items but printing the original text when validate it.
For example, for the files completion, better than having this kind of display :
```
$ cd test/
>
  test/acat.gif
  test/bob.jpb
  test/another_test/
$ cd test/another_test
```
it will allow us to have an expression/function to do basename and have this kind of display :
```
$ cd test/
>
  acat.gif
  bob.jpb
  another_test/
$ cd test/another_test
```

Regards,

**Comment by junegunn** [comment]
You can already do that with `--with-nth`

```sh
echo 'original-name display-name' | fzf --with-nth=2 | awk '{print $1}'
echo 'test/foo.bar' | fzf --with-nth=-1 --delimiter=/  
```

Please refer to `man fzf` for details.

**Comment by rockandska** [comment]
it partially works with the case i've posted, the directories are not shown due to the fact i want a trailing "/" for directories

results expected:
```
$ find test \( -type d -printf '%p/\n' \) -or \( -type f -print \)
test/
test/bob.jpb
test/another_test/
test/acat.gif
$ find test \( -type d -printf '%p/\n' \) -or \( -type f -print \) | fzf --with-nth=-1 --delimiter=/
>
  test/
  bob.jpb
  another_test/
  acat.gif
  4/4
```

result using `--with-nth=-1`:
```
$ find test \( -type d -printf '%p/\n' \) -or \( -type f -print \) | fzf --with-nth=-1 --delimiter=/
>

  bob.jpb

  acat.gif
  4/4
```

that's the reason why i was looking for a way to do it but with a kind of `sed` expression, for example:

```
$ find test \( -type d -printf '%p/\n' \) -or \( -type f -print \)  | sed -r 's#.*/([^/]+/?)$#\1#'
test/
bob.jpb
another_test/
acat.gif
```

**Comment by junegunn** [comment]
> it partially works with the case i've posted, the directories are not shown due to the fact i want a trailing "/" for directories

You can pre-process the input however you like using any program you prefer and use the first trick I mentioned above:

```sh
echo 'original-name display-name' | fzf --with-nth=2 | awk '{print $1}'
```
