### ISSUE TITLE
fzf does not use FZF_DEFAULT_COMMAND on windows?

### ISSUE THREAD

**Issue by James-A1** [junegunn/fzf#1684]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [x] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [ ] Mac OS X
    - [x] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [ ] fish
    - [x] powershell

Hi, 

I am using the fzf plugin for gvim on windows. I have ripgrep installed via choco, and I have been using it to search in files while ignore specific folders (.git, node_modules, vendor etc.). I've been able to set it via `let:rg_command`. I was looking for documentation on how to ignore the folders for the :Files command which uses fzf, when I stumbled upon setting the FZF_DEFAULT_COMMAND variable which I could use.

Yet, setting FZF_DEFAULT_COMMAND on windows doesn't seem to take effect:
As an experiment, I set the variable in powershell via:` setx FZF_DEFAULT_COMMAND 'rg -g "!{.git,node_modules,vendor,.tags}/*" -F -e '`

Running `fzf -q XXX` in the terminal as well in vim, I can still see the old output as if I had never set the FZF_CTRL_T_COMMAND.

Thank you.

**Comment by junegunn** [comment]
Is the variable visible on GVim?

```vim
" In GVim
:echo $FZF_DEFAULT_COMMAND
```

**Comment by janlazo** [comment]
```powershell
# cmd.exe syntax
> $env:FZF_DEFAULT_COMMAND = 'rg --files . 2> nul'
> vim -es --cmd 'execute ''!echo \"''.$FZF_DEFAULT_COMMAND.''\"''' -c q
"rg --files . 2> nul"
> echo '*' | Out-File -Encoding ascii .rgignore
> rg . # no output
> fzf # rg finds nothing so fzf does not show anything
```
Need more info because you used setx, https://ss64.com/nt/setx.html, which targets the registry. A shell gets environment variables from the registry after spawning a new shell or killing the process tree if spawning shell via a terminal, like ConEmu. I don't know why you want to test this via the registry when you can define environment variables in your powershell profile.

**Comment by marcotrosi** [comment]
Hello guys,

I was about to create an issue but then I read through the existing issues and this comes kind of closest to my Feature Request.

If I didn't oversee any option in the help then I guess the only way to provide the default command is with the environment variable FZF_DEFAULT_COMMAND.
But fzf has options for everything that can be passed on the command line, and I don't understand why the default command can not be passed as a command line argument.

I wish there was a flag like --default-command or --dflt-cmd or whatever you wanna call it, to pass something like --default-command='fd -t d'

Shall a create a separate feature request?
Or can someone explain why the default command seems to be the only options that can not be passed as a command line argument?

thank you in advance

--marco

**Comment by dinesh0430** [comment]
# Setting FZF_DEFAULT_COMMAND in Windows (GVIM)

I didn't know how to change fzf_default_command in **Windows** and presumed that it is only possible in ***nix (Linux and MacOS)** systems.
Then I somehow came across this issue opened by @James-A1 upon Googling for some solution and tried this in powershell:
```powershell
setx FZF_DEFAULT_COMMAND 'rg --files '
```
![powershell](https://user-images.githubusercontent.com/32917000/88652736-d7d0d900-d0e8-11ea-98cc-5cd2617a9bbf.gif)
## It _worked_!!
Below is the result in a gif
![fzfRipgrep](https://user-images.githubusercontent.com/32917000/88652909-077fe100-d0e9-11ea-846c-d35952dcd3d0.gif)

@junegunn , @janlazo  , I hope you can include this in the **documentation** or if possible I will try to update the documentation with required windows specific method hoping that you would accept the **pull request**.

**Comment by janlazo** [comment]
https://ss64.com/nt/setx.html mentions that `setx` affects the registry so I cannot recommend it. Bad experiences from tampering with the registry. Set the environment variable  with [set](https://ss64.com/nt/set.html) on cmd.exe or Powershell's [$env](https://ss64.com/ps/syntax-env.html) variable.

Update https://github.com/junegunn/fzf/wiki/Windows if there are any other findings on fzf's behavior on `FZF_DEFAULT_COMMAND`. fzf uses a native file walker https://github.com/junegunn/fzf/commit/311b78ae82fc8b06f0eefbd54d6290f3a40d5e23 so you likely need `FZF_DEFAULT_COMMAND` to get more results.

**Comment by dinesh0430** [comment]
@janlazo , How about using the GUI version of `edit environmental variables` in windows (though they potentially could mean the same) to set the variable `FZF_DEFAULT_COMMAND` so, that we can have control over when to remove and what to do with it?

The documentation mentions that :
> Environment variables are stored in the registry

and `setx` will write environment variables to registry.

But upon your suggestion, I tried `set` in **cmd** and `$env` in **powershell** and they didn't have any effect.

SET documentation even mentions that:
> Changes made with SET will remain only for the duration of the current CMD session

So, I think that using `setx` or GUI version of **edit environment variables** is one option that worked for me.
Please correct me or provide some alternatives if there are some available.

**Comment by janlazo** [comment]
> @janlazo , How about using the GUI version of `edit environmental variables` in windows (though they potentially could mean the same) to set the variable `FZF_DEFAULT_COMMAND` so, that we can have control over when to remove and what to do with it?
> 
> The documentation mentions that :
> 
> > Environment variables are stored in the registry
> 
> and `setx` will write environment variables to registry.
> 
> But upon your suggestion, I tried `set` in **cmd** and `$env` in **powershell** and they didn't have any effect.
> 
> SET documentation even mentions that:
> 
> > Changes made with SET will remain only for the duration of the current CMD session
> 
> So, I think that using `setx` or GUI version of **edit environment variables** is one option that worked for me.
> Please correct me or provide some alternatives if there are some available.

I recommended `set` and `$env` because they remain only for the duration of the current shell session. If things go south, then I can create a new session with none of my mistakes. Some people prefer modifying the registry but registry modifications may require new sessions and may not update the current session. I don't know of any other alternatives for modifying environment variables.

Not sure what you mean by GUI version of editing environment variables. I would open up the Control Panel and configure the system and user environment variables that should persist such as `PATH`. Then, I kill all of my shell sessions via Task Manager and try creating a new session that has my modifications. It's time-consuming for me to do this per update so I don't recommend it.

> Setx writes variables to the master environment in the registry. Variables set with setx variables are available in **future** command windows only, not in the **current** command window.
> You cannot use the setx command to remove values that have been added to the local or system environments. You can use set with a variable name and no value to remove a corresponding value from the local environment.
https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/setx
