### ISSUE TITLE
[FR] access query in execute()

### ISSUE THREAD

**Issue by laur89** [junegunn/fzf#1685]
- Category
    - [X] fzf binary

Could it be possible to make query string available in `execute[-*]()` functions? Similar to how it's available via `--print-query` when exiting fzf.
Perhaps introduce another placeholder that would get replaced with it?

**Comment by junegunn** [comment]
From `man fzf`:

> You can use the same placeholder expressions as in --preview.

`{q}` works in execute command template as well.

```sh
fzf --bind 'space:execute:echo {q} {n}; read'
```
