### ISSUE TITLE
Suggestion option for fuzzy matching: hide ~single-char results when longer substrings are exactly matched

### ISSUE THREAD

**Issue by khughitt** [junegunn/fzf#1687]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

# Overview

Often, when searching for some string, after typing a few characters that exactly match part of the filepath.

For example, when typing "exa" to match some filepath:

```
/path/to/some/[exa]ct_match`
```

It might be nice to then hide all partial matches that only include substrings of a smaller size, in particular, single character matches, e.g.:

```
/p[a]th/which/[x]/only/includ[e]s/single/char/hits
```

The motivation is that by the time a file is exactly-matched with some substring >= ~3 characters, all of the (often very many) chance hits due to single character matches across long filepaths are unlikely to be the desired targets and are just noise in the results.

The give the user flexibility, you could perhaps create a setting corresponding to the minimum number of exactly-matched characters required before switching behavior from fuzzy -> exact matching.

... Just a thought.

**Comment by junegunn** [comment]
Closing as `wontfix` as the benefit of the suggested feature is not clear to me.

* Partial matches are ranked lower than the exact matches so you don't get to choose them unless you move your cursor around
* The current way of prefixing a term with `'` gives the most flexibility. e.g. `'exa pts`
