### ISSUE TITLE
Parse error in key bindings

### ISSUE THREAD

**Issue by lucian303** [junegunn/fzf#1688]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [X ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [ ] fish

Getting this error when sourcing the file from .zshrc:

/home/myuser/.fzf/shell/key-bindings.zsh:14: parse error near `done'

**Comment by junegunn** [comment]
zsh version?

**Comment by lucian303** [comment]
zsh 5.4.2 (x86_64-ubuntu-linux-gnu) @junegunn

**Comment by junegunn** [comment]
I can't reproduce. It works for me fine. We recently made that global aliases are ignored inside the function (https://github.com/junegunn/fzf/commit/0c6c76e08115d0ba160e2c95c8692e4174aa5368). That may help, so you might want to update and try again. But other than that, I don't think I can't help you.

**Comment by vimkim** [comment]
For somebody who came across this issue, DO NOT alias 'do' or 'done' or something like this. It's a reserved keyword of zsh.

My cause was that I aliased docker as 'do' and it broke the zsh `for do; done;` loop.
