### ISSUE TITLE
Allow customizing default command(s) interactively

### ISSUE THREAD

**Issue by borekb** [junegunn/fzf#1689]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

I'm quite new to fzf but so far, I've interacted with it via these methods:

- Typing `fzf` directly.
- Piping into fzf, e.g., `fd -t d dir | fzf`
- Via Ctrl+T, e.g., `code [CTRL+T]`
- Via `**`, e.g., `code project/**[TAB]`

I'm using `fd` as the default command:

```bash
# .zshrc
export FZF_DEFAULT_COMMAND='fd --type f'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
_fzf_compgen_path() {
  fd --type f . "$1"
}
```

My trouble is when the file I need to find is hidden, e.g., `.prettierrc`. In that case, those commands (depending on the way I interact with fzf) should be something like `fd --type f -H`.

I originally came here to propose to add some CLI argument to pass down to the default command but only when writing this, I realized that there are multiple ways to interact with fzf and that it wouldn't work. It has also been suggested already and rejected: https://github.com/junegunn/fzf/issues/1522.

So how about being able to do this **interactively**? An example scenario I have in mind:

1. I type `code [CTRL+T]` in hope to autocomplete to `code subdir/.prettierrc`.
2. I realize that that file is hidden. Fortunately, fzf has an interactive mode!
3. I press `/`, a special key, that gives me a mini-shell within fzf, showing that my current search command is `fd --type f`. I type ` -H [ENTER]` and fzf starts a new search, this time listing also hidden files.
4. I type `.pret`, press `[ENTER]` and am happy.

What do you think?

**Comment by junegunn** [comment]
Thanks for the suggestion, but I think it goes beyond the scope of the project. fzf was designed to be a simple interactive Unix filter.

```sh
seq 100 | fzf
```

In retrospect, I could have just told the users to use a simple wrapper function instead of introducing `FZF_DEFAULT_COMMAND`.

```sh
fzf() {
  if [ -t 0 ]; then
    find . | command fzf "$@"
  else
    command fzf "$@"
  fi
}
```

Having said that, I believe you can implement the scenario using `--expect /` option. 

```sh
mode=0
while true; do
  if [ "$mode" = 0 ]; then
    command="echo foo"
  else
    command="echo bar"
  fi
  readarray -t lines < <(
    eval "$command" | fzf --expect / --no-clear --height 10 --header "Press / to toggle between modes" --prompt "Mode $mode> "
  )
  if [ "${lines[0]}" = / ]; then
    mode=$(( mode ^ 1 ))
  else
    echo -e "\x1b[J" > /dev/tty
    echo ${lines[1]}
    break
  fi
done
```

**Comment by borekb** [comment]
Thanks for the response. Would this solve the "`code CTRL+T`, oops, hidden files are not here" scenario though?

The trouble is that I don't know in advance if CTRL+T will or will not include the file types I'm looking for. And I cannot quite imagine "piping something into CTRL+T" (sorry if I'm missing something).

**Comment by junegunn** [comment]
Yes.

```zsh
fzf-demo-loop() (
  mode=0
  while true; do
    if [ "$mode" = 0 ]; then
      command="echo foo"
    else
      command="echo bar"
    fi
    lines=(
      "${(@f)$(eval "$command" | fzf --expect / --no-clear --height 10 --header "Press / to toggle between modes" --prompt "Mode $mode> ")}"
    )
    if [ "${lines[1]}" = / ]; then
      mode=$(( mode ^ 1 ))
    else
      echo -e "\x1b[J" > /dev/tty
      echo ${lines[2]}
      break
    fi
  done
)

fzf-demo() {
  LBUFFER="${LBUFFER}$(fzf-demo-loop)"
  local ret=$?
  zle reset-prompt
  return $ret
}

zle     -N   fzf-demo
bindkey '^T' fzf-demo
```
