### ISSUE TITLE
Slow startup with keybindings in fish

### ISSUE THREAD

**Issue by talexand** [junegunn/fzf#169]
This is using Ubuntu 14.04, fzf installed from commit 8a4db3c, and fish version 2.1.1, installed using the instructions in the README.

For some reason, starting fzf with CTRL+T or ALT+C is extremely slow (>30s), where typing `fzf` in manually starts it almost immediately.

Is there anything I can provide to help debug this?

**Comment by junegunn** [comment]
Unfortunately, I don't use fish and I know very little about fish so I'm not sure if I can fix the problem. I could use some help.

**Comment by ekeitho** [comment]
Rather than piping __fzf_list | fzf [params].
I simply just have 'fzf -m > $TMPDIR/fzf.result' in my fish functions and the response is almost instant.

**Comment by junegunn** [comment]
For some reason, fish buffers the entire list when the a function is used as the input:

```vim
# Immediate
find / | fzf

# Wait until complete
function list
  find /
end
list | fzf
```

I was able to remove the buffering delay by inlining the subroutines.

**Comment by talexand** [comment]
Tested working on my side also. Thanks.
