### ISSUE TITLE
Typing special characters erases typed input and flashes __fzf_cd__

### ISSUE THREAD

**Issue by markkutikkanen** [junegunn/fzf#1691]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [x] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

Using version 0.18 installed from `git` & `./install`. No special configuration to fzf. No screen / tmux.

Issue happens on Ubuntu 16.04 server with above setup. I use a Macbook with Scandinavian keyboard (with umlaut keys 'öäå') and connect to the server using `ssh`. 

When typing those umlauts or other special characters like 'ü' or 'ç' the whole previously typed input line in shell is erased and `__fzf_cd__` is flashed briefly. It's quite annoying when you have typed a long command and then you accidentally hit those keys.

**Comment by markkutikkanen** [comment]
Found out that on Ubuntu 16.04.xx `locale` is broken by default:
```
$ locale
locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_ALL to default locale: No such file or directory
...
```
by setting LANGUAGE and LC_ALL to sane value (for example `en_US.UTF-8`) in `/etc/default/locale` fixed this issue.

**Comment by zoechi** [comment]
Thanks, this worked for me, but only outside tmux :-/
