### ISSUE TITLE
Add dedicated config file support

### ISSUE THREAD

**Issue by kmoschcau** [junegunn/fzf#1692]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [x] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [x] fish

Hi, I would like to suggest, that fzf supports a config file just for itself. I find setting the default options via environment variables rather clunky.
I am fine setting the default command that way, because I can check what is actually installed, but setting the styling and some other things this way just seems weird.

I understand that designing a config language and implementing the parsing logic for it is not trivial, but I am still surprised nobody suggested this yet.

**Comment by junegunn** [comment]
I don't think we need it. You can just write down the options in a file, which isn't too different from [flagfiles for gflags](https://gflags.github.io/gflags/), and use it to populate the environment variable:

```sh
$ cat > /tmp/foo << EOF
> --height 40%
> --layout reverse
> --color bg+:#1e2132,bg:#161821,spinner:#84a0c6,hl:#6b7089,fg:#c6c8d1,header:#6b7089
> --color info:#b4be82,pointer:#84a0c6,marker:#84a0c6,fg+:#c6c8d1,prompt:#84a0c6,hl+:#84a0c6
> EOF

$ export FZF_DEFAULT_OPTS=$(cat /tmp/foo)

```
