### ISSUE TITLE
Print Query if there is no match

### ISSUE THREAD

**Issue by Jab2870** [junegunn/fzf#1693]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [x] bash
    - [x] zsh
    - [ ] fish

Is it possible to make fzf automatically print the query, only if there is no match found. This is the behaviour of other fuzzy finders such as dmenu and rofi.

Thanks for creating this tool!

**Comment by junegunn** [comment]
> automatically print the query, only if there is no match found

Then it's not clear if the printed line is the query or the selection, and we would need to define an arbitrary exit status for that specific case. A simpler way would be to use `--print-query` option and use shell script to check the number of output lines.

```sh
$ echo 1 | fzf --print-query -0 -1 | wc -l
       2
$ : | fzf --print-query -0 -1 | wc -l
       1
```

**Comment by LamaRaz** [comment]
@junegunn 
when you don't care about if the selection came from a list or was typed manually (for example a launcher that most of the time selects from a list but sometimes you want to type the whole command with env variables and arguments) you can use

[list] | fzf --print-query | tail -1 | xargs -r ...

there doesn't appear to be such a simple solution to the problem if you use --print0 however, have to resort to actual scripts.

is there a way to make fzf abstain from printing an empty line?

**Comment by guidocella** [comment]
I managed to make fzf behave like dmenu with this binding. You may find it useful as an alternative to `--print-query` + `tail -1` compatible with `--print0`:
`export FZF_DEFAULT_OPTS='--bind=enter:replace-query+print-query'`

`print-query` doesn't work in vim though so you'll have to reset the binding in `init.vim`/`vimrc`:
`let $FZF_DEFAULT_OPTS = $FZF_DEFAULT_OPTS.' --bind=enter:accept'`

**Comment by Superty** [comment]
Note that `replace-query+print-query` will not work if the selection is too long since there seems to be a limit on the size of the query.
