### ISSUE TITLE
Ctrl-T not working over ssh

### ISSUE THREAD

**Issue by hotpxl** [junegunn/fzf#1694]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [x] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

I ssh onto a Linux box from my Mac. On the Linux box I source `.fzf.zsh` with keybindings enabled. Ctrl-R and Alt-C all works, but Ctrl-T doesn't. I can verify `"^T" fzf-file-widget` is in bindkey.

I find that once I do `stty -isig` (on the Linux box) it starts working again. But once I `stty isig` Ctrl-T it stops working. But to my understanding, Ctrl-T shouldn't have anything to do with `stty isig`.

Here is my `stty -a`:
```speed 38400 baud; rows 72; columns 273; line = 0;
intr = ^C; quit = ^\; erase = ^?; kill = ^U; eof = ^D; eol = <undef>; eol2 = <undef>; swtch = <undef>; start = ^Q; stop = ^S; susp = ^Z; rprnt = ^R; werase = ^W; lnext = ^V; discard = ^O; min = 1; time = 0;
-parenb -parodd -cmspar cs8 -hupcl -cstopb cread -clocal -crtscts
-ignbrk -brkint -ignpar -parmrk -inpck -istrip -inlcr -igncr icrnl ixon -ixoff -iuclc -ixany -imaxbel iutf8
opost -olcuc -ocrnl onlcr -onocr -onlret -ofill -ofdel nl0 cr0 tab0 bs0 vt0 ff0
isig icanon iexten echo echoe echok -echonl -noflsh -xcase -tostop -echoprt echoctl echoke -flusho -extproc
```

**Comment by fanlei** [comment]
I have same issue over SSH.

**Comment by hotpxl** [comment]
I found my issue was totally on my end..

**Comment by yasselpiloto** [comment]
I had this same issue on Debian and solved it by re-installing fzf using git 

```bash
git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
~/.fzf/install
```
