### ISSUE TITLE
Paste results into command line without executing (Bash)

### ISSUE THREAD

**Issue by HarrisonMc555** [junegunn/fzf#1695]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [X] Key bindings
    - [X] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

I apologize if there is already an issue/tutorial for this. I've been looking for several minutes and haven't found it yet.

I looked through the [examples](https://github.com/junegunn/fzf/wiki/examples) and thought they were great. However, for most of them, I would prefer to **have the command be pasted to the command line without being run**. At the very least, I would like to add it to the bash history so I can <kbd>Ctrl</kbd>+<kbd>P</kbd> and run it again if I want.

Looking through the [key-bindings file](https://github.com/junegunn/fzf/blob/master/shell/key-bindings.bash) and the [bash completion file](https://github.com/junegunn/fzf/blob/5c7dcaffe892dad764d0130ee49198646cd8fd73/shell/completion.bash) and it looks pretty intimidating. Will I need to mess around with completion or readline stuff in order to get this to work? It seems like it would be nice if there were a flag or possibly another command that could help with this.

If it is necessary to mess around with completion and/or readline stuff, would it be possible to include a brief tutorial for how to get them to work together? If you walk me through how to do it I would be willing to write up a brief tutorial.

Right now, my workaround is to get the result from `fzf`, run `history -s "$cmd"`, and then run `eval "$cmd"`. It works pretty well. My minor nitpick is that it doesn't show up on my terminal screen, although it does show up with <kbd>Ctrl</kbd>+<kbd>P</kbd> and <kbd>Ctrl</kbd>+<kbd>R</kbd>.

**Comment by junegunn** [comment]
> have the command be pasted to the command line without being run

You know that it's the default behavior of CTRL-R key binding `key-bindings.bash` provides, right? And yes, you need to know about readline stuff to manipulate your command line.

You might want to take a look at https://junegunn.kr/2016/07/fzf-git

**Comment by HarrisonMc555** [comment]
I'm aware that this is the default behavior of the normal CTRL-R keybinding, I just wasn't sure how to emulate that with other commands.

I guess I'll have to take a look into some readline stuff then :-) I'm not familiar with it (yet) but I think I should manage. And most of the things I wanted to do I've figured out ways to do already, so that's nice.

Thanks for the pointer! That is helpful.

**Comment by eyalev** [comment]
Also tried something similar but with no results so far.

I'm trying to create something like:

```
$ cat commands.txt | fzf | paste-to-command-line
```

This is the closest I got:

```
$ cat commands.txt | fzf | perl -e 'ioctl STDOUT, 0x5412, $_ for split //, do{ chomp($_ = <>); $_ }'
```

But the result is also being prepended to the prompt.

**Comment by elhenro** [comment]
If you use [zsh](https://www.zsh.org/), you can do this:

`print -z -- $(fzf)`

This will paste the fzf selection into the command line input with the cursor to the right.  The command can then be edited and executed.
