### ISSUE TITLE
How to send the result to stdout when there are no matches?

### ISSUE THREAD

**Issue by igorhub** [junegunn/fzf#1696]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [x] fish

Hi!

I want to either select one of the items I’ve sent to fzf, or type a new string, not present in the items I’ve sent. I want to be able to make the decision between new or existing item during the selection (as opposed to making that decision before I start fzf). In other words, when I’ve done the search in fzf and found no match, I want to type the right answer rigth there, and send it to stdout.

When I try to use fzf in this manner, I get empty stdout and exit status 1. Is there a way to override this behavior? I’ve read the manual and found nothing.

**Comment by junegunn** [comment]
Bind a key to `print-query` action and press it when you want the query, not the selection.

```sh
fzf --bind 'ctrl-x:print-query'
```
