### ISSUE TITLE
.fdignore file doesn't take effect

### ISSUE THREAD

**Issue by ashkrosh** [junegunn/fzf#1698]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

I am trying to exclude Music, Moves and such folders in $HOME from fzf index. Adding them in .fdignore file (similar to .gitignore) doesn't seem to work at least on latest version of fzf.

**Comment by FractalWire** [comment]
Does the ignore file works with `fd` alone ? What command do you use ?
I have no problem to use `.fdignore` file with fzf.

**Comment by ashkrosh** [comment]
No it doesn't work! Here are my env vars:
`# FD
  2 FD_OPTIONS='--type=symlink --hidden --follow --glob --ignore-file=$HOME/.fdignore --exclude .git'
  1
76  # FZF settings
  1 FZF_DEFAULT_COMMAND="git ls-files --cached --others --exclude-standard | fd --type f $FD_OPTIONS"`

and here is a part of my .fdignore file:
`  9 .vimprojects
  8 .viper
  7 .wine
  6 .wireshark
  5 .wireshark-etc
  4 .zcompdump*
  3 Dropbox*
  2 Library
  1 Movies
  0 Music/*`

I tried to exclude both using default regex and also by setting --glob instead of regex and seems fd can't pick either of them.

**Comment by FractalWire** [comment]
Your problem is most likely due to the fact that you use apostrophe for your `$FD_OPTIONS`
So your `$HOME` variable is not resolved in `$FZF_DEFAULT_COMMAND`

Try that instead : 
```
FD_OPTIONS="--type=symlink --hidden --follow --glob --ignore-file=$HOME/.fdignore --exclude .git"
```

**Comment by ashkrosh** [comment]
Thanks @FractalWire , it corrected expanding the $HOME var correctly. So now FD works as expected however when I run "FZF" in shell it still shows the ignored directories like Music

**Comment by FractalWire** [comment]
Well, it should.
Note however that your `FZF_DEFAULT_COMMAND` is a bit weird. Your ` git ls-files` won't be picked up, ever, like that. Not sure what your goal is here.

Try that in your home directory:
```
fd -t f --ignore-file=$HOME/.fdignore | fzf
```
It should properly ignore your Movie and Music folders.

**Comment by junegunn** [comment]
Closing as this is definitely not an issue of fzf. As @FractalWire pointed out, your command looks strange. You should make sure that your command works as expected without fzf.

```sh
eval "$FZF_DEFAULT_COMMAND" | fzf
```
