### ISSUE TITLE
error message when closing fzf buffer

### ISSUE THREAD

**Issue by frescoraja** [junegunn/fzf#1700]
- Category
    - [X] Neovim

- OS
    - [X] Mac OS X

- Shell
    - [X] zsh

I do not remember this happening always - seems to be a fairly recent thing .. but if i close the fzf search buffer (by hitting `<Esc>` to get out of insert mode, then `:q<Enter>`, i get an error message like the following:

`Error running ( /usr/local/bin/zsh '/var/folders/gv/qdygj2ss0_jgn8xdmjqt6sdr0000gp/T/nvimxuvGwv/3' )|'/Users/username/.fzf/bin/fzf'  '-m' '--prompt' '~/D/F/c/c/s/g/servicecode/' '--preview-window' 'right:50%:hidden' '--preview' ''\'
'/Users/username/.vim/vimplugs/fzf.vim/bin/preview.sh'\'' {}' '--bind' '?:toggle-preview' --expect=ctrl-v,ctrl-x,ctrl-t --no-height > /var/folders/gv/qdygj2ss0_jgn8xdmjqt6sdr0000gp/T/nvimxuvGwv/2`

is this intended behavior? is it a bug?
thanks for looking into it

**Comment by junegunn** [comment]
It's not a bug. Pressing ESC should normally close the fzf window; you probably mapped it to exiting insert mode using `tnoremap`. In that case, you can just press CTRL-C instead to close fzf. Or you can override the mapping only on fzf windows.

```vim
autocmd! FileType fzf tnoremap <buffer> <esc> <c-c>
```

**Comment by frescoraja** [comment]
thanks, you're right. 👍
