### ISSUE TITLE
[bug]--no-clear and --no-height options together messing up terminal shortcut

### ISSUE THREAD

**Issue by FractalWire** [junegunn/fzf#1701]
- Category
    - [X] fzf binary
- OS
    - [X] Linux
- Shell
    - [X] bash
- Terminal
   - [X] Termite

I can usually scroll up and down in my terminal using Shift+PgUp/Shift+PgDown or the mouse wheel.
But, after using `fzf` with the `--no-clear` and `--no-height` options together, this is no longer possible and `Shift+PgUp` will then print `2~` instead for example.

It seems like my terminal does not recognize properly that key combination anymore.

**Comment by FractalWire** [comment]
This can be solved by issuing the terminfo sequence to stop full screen mode :

```
tput rmcup
```

See here : https://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h2-The-Alternate-Screen-Buffer

**Comment by junegunn** [comment]
This is a documented behavior:

https://github.com/junegunn/fzf/blob/80b5bc1b682898e3089f6caf1120919fc0933562/man/man1/fzf.1#L381-L385
