### ISSUE TITLE
find command doesn't quote arguments which can conflict with global aliases

### ISSUE THREAD

**Issue by chrisjohnson** [junegunn/fzf#1708]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [x] Key bindings
    - [x] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

The way the `find` command is written, there are unquoted strings as arguments: https://github.com/junegunn/fzf/blob/master/shell/key-bindings.zsh#L8-L10

I have an alias defined in my .zshrc:

```
$ which "l"
l: globally aliased to | less
```

Which conflicts and causes the `find` command arguments to be parsed as my alias. Adding single quotes around `f`, `d`, `l` fixes the issue. I know I could extend the function and change it myself but it seems more helpful to fix upstream

**Comment by junegunn** [comment]
> Adding single quotes around f, d, l fixes the issue. 

That would work, but quoting every single argument to every command doesn't seem like an elegant solution to the problem.

But do you really have to use global (`-g`) aliases? 

```sh
$ alias -g l=less
$ echo l
less
$ alias l=less
$ echo l
l
```

**Comment by chrisjohnson** [comment]
The global alias includes a pipe which won't work if it's not global.

 Either way, it's a feature that certainly exists and asking people not to
use it instead of just correcting the malformed command doesn't seem like
the right answer

So far I haven't found any other cases of malformed command causing issues
so I'm not asking to update everything, just this one

**Comment by junegunn** [comment]
I do not agree that the command is malformed. Instead, I would say that you have a dangerous alias that can easily cause problems. I can just quote `l` this time, but someone else may have another global alias `d`, `f`, or anything. So just quoting `l` is not a proper solution.

I wonder if there's a way to temporarily suppress global aliases in a function, but I'm not a zsh user, so pull request is welcome.

**Comment by junegunn** [comment]
> adding some zsh-specific logic here would be the proper solution

The problem is specific to zsh, because bash and fish don't have an equivalent feature.

> simple "properly quote all of the arguments"

Global aliases expand at all places, so until we write `'command' 'find' -L '.' -mindepth '1' ...`, it's only a partial solution (malformed?). I don't like that and I wanted to see if there's a better option. Why settle for less? Shouldn't we at least try? If "the perfect solution" is unnecessarily complex or even impossible, then I'm okay with quoting a few arguments that affect you.

**Comment by chrisjohnson** [comment]
> The problem is specific to zsh, because bash and fish don't have an equivalent feature.

To be clear, the actual problem is that the shell is expanding arguments that we don't want it to expand, and that's possible in any shell. Imagine if you had needed to use `**` as an argument to `find`, bash would expand that before giving it to `find`. The proper way to tell a shell not to expand an argument is to quote it.

That said, I don't know of any mechanism for temporarily disabling shell expansion behavior inside a function, but if you would rather go that route it seems reasonable to me. I think this whole thing could be much more expediently resolved by simply quoting the arguments that we don't want the shell to expand but it's also not my project to own :)

**Comment by junegunn** [comment]
> and that's possible in any shell. 

The problem is that on bash or fish, we know which keywords expand, so we can only quote them, but on zsh, because of global aliases, not a single keyword is safe to use without quotes regardless of its position. Not just arguments.

**Comment by junegunn** [comment]
> What happens if bash adds a new expansion keyword tomorrow and users start using it?

I should correct myself, bash doesn't expand ordinary keywords, only a few symbols and the keywords prefixed by a certain symbol. Not sure you're making a valid point here, you're talking about a hypothetical future backward incompatibility of a very stable shell that has existed for more than 30 years. On the other hand, zsh with global aliases can break right now, just like you experienced here.

Like I said, I'm not a zsh user, and I haven't researched yet if there is a better, no-compromise solution or not, and if it exists, if it's simple or not. I'm just saying that I don't want to accept a partial fix before thoroughly looking for better options. Not sure why you insist that we settle with an incomplete solution right now.

**Comment by chrisjohnson** [comment]
> Not sure why you insist that we settle with an incomplete solution right now.

I'm not, I'm just saying that since we are compromising (i.e. not going to quote every keyword, which is the only truly portable solution) may as well go with the simplest compromise. But if you'd rather research a more complicated one I'm not opposed to that.

**Comment by junegunn** [comment]
A quick google search showed me this:

https://unix.stackexchange.com/questions/161973/clear-or-disable-aliases-in-zsh

And this is all we need:

```diff
diff --git a/shell/key-bindings.zsh b/shell/key-bindings.zsh
index 6aacc7e..a77d136 100644
--- a/shell/key-bindings.zsh
+++ b/shell/key-bindings.zsh
@@ -8,7 +8,7 @@ __fsel() {
     -o -type f -print \
     -o -type d -print \
     -o -type l -print 2> /dev/null | cut -b3-"}"
-  setopt localoptions pipefail 2> /dev/null
+  setopt localoptions pipefail no_aliases 2> /dev/null
   eval "$cmd" | FZF_DEFAULT_OPTS="--height ${FZF_TMUX_HEIGHT:-40%} --reverse $FZF_DEFAULT_OPTS $FZF_CTRL_T_OPTS" $(__fzfcmd) -m "$@" | while read item; do
     echo -n "${(q)item} "
   done
@@ -49,7 +49,7 @@ zle -N fzf-redraw-prompt
 fzf-cd-widget() {
   local cmd="${FZF_ALT_C_COMMAND:-"command find -L . -mindepth 1 \\( -path '*/\\.*' -o -fstype 'sysfs' -o -fstype 'devfs' -o -fstype 'devtmpfs' -o -fstype 'proc' \\) -prune \
     -o -type d -print 2> /dev/null | cut -b3-"}"
-  setopt localoptions pipefail 2> /dev/null
+  setopt localoptions pipefail no_aliases 2> /dev/null
   local dir="$(eval "$cmd" | FZF_DEFAULT_OPTS="--height ${FZF_TMUX_HEIGHT:-40%} --reverse $FZF_DEFAULT_OPTS $FZF_ALT_C_OPTS" $(__fzfcmd) +m)"
   if [[ -z "$dir" ]]; then
     zle redisplay
@@ -66,7 +66,7 @@ bindkey '\ec' fzf-cd-widget
 # CTRL-R - Paste the selected command from history into the command line
 fzf-history-widget() {
   local selected num
-  setopt localoptions noglobsubst noposixbuiltins pipefail 2> /dev/null
+  setopt localoptions noglobsubst noposixbuiltins pipefail no_aliases 2> /dev/null
   selected=( $(fc -rl 1 |
     FZF_DEFAULT_OPTS="--height ${FZF_TMUX_HEIGHT:-40%} $FZF_DEFAULT_OPTS -n2..,.. --tiebreak=index --bind=ctrl-r:toggle-sort $FZF_CTRL_R_OPTS --query=${(qqq)LBUFFER} +m" $(__fzfcmd)) )
   local ret=$?
```

**Comment by chrisjohnson** [comment]
Thanks, I appreciate it :)
