### ISSUE TITLE
preview placeholder not working in bash command substition

### ISSUE THREAD

**Issue by co-dh** [junegunn/fzf#1711]
- Category
    - [X] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [X] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [X] bash
    - [ ] zsh
    - [ ] fish

I'm trying to preview grep result from the line matched, and this work.
rg -n -w spid  | fzf --delimiter=: --preview="tail -n  +{2} {1}"

However, if I want to see a few line of context, and add expr into preview command, it looks like {2} is not interpretered. 

rg -n -w spid  | fzf --delimiter=: --preview="tail -n  +`expr {2} - 5` {1}"

This might be a bash question.

**Comment by junegunn** [comment]
Syntax highlighting is broken, but it looks like you used backticks inside the command.  Yes, it's a bash question. Use single quotes around the command so the backticks are not evaluated immediately.
