### ISSUE TITLE
Change directory separator (config flag)

### ISSUE THREAD

**Issue by hecerinc** [junegunn/fzf#1714]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [ ] Mac OS X
    - [x] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [ ] fish

Is there configuration for changing the directory separator in the fzf binary in Windows? I use cmder which uses `/`  forward slashes but fzf uses backward slashes and it creates an issue when opening files from vim.

**Comment by junegunn** [comment]
Please read through the README page which should answer your question.

**Comment by buckleyGI** [comment]
I read through the man page but could not find a solution. We are using Linux via WSL and Windows path interchangeably. When I am looking for a file, the path sometimes has forward slashes in them and at other times they are backslashed while pointing to the same file. Windows is forgiving so you can specify both, but is there an option to treat both / and \ as a valid path separator in fzf?

**Comment by pdc1** [comment]
For others who find this issue and prefer forward slashes on Windows (Cygwin, WSL, etc.), there is no longer an answer in the README. However, per documentation for `fastwalk`, specifically [DefaultToSlash()](https://pkg.go.dev/github.com/charlievieth/fastwalk#DefaultToSlash), forward slashes can be "forced" on Windows by setting the `MSYSTEM` environment variable to an arbitrary string.
