### ISSUE TITLE
vim-specific FZF_DEFAULT_OPTS

### ISSUE THREAD

**Issue by kshenoy** [junegunn/fzf#1715]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [x] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

Is there a way to have vim-specific equivalent of FZF_DEFAULT_OPTS? eg. I like having `--reverse` set while using fzf in shell but not in vim. By not specifying it in `FZF_DEFAULT_OPTS`, I get the not-reverse behavior in vim and to get the reverse behavior in shell, I've to set it in `FZF_CTRL_T_OPTS`, `FZF_CTRL_R_OPTS` and `FZF_ALT_C_OPTS`. 

This works because I'm specifying an extra option to configure shell behavior but if it was the other way around, I'd have been out of luck. Is there a way to specify options such that they apply only for vim?

**Comment by junegunn** [comment]
You can define the variable in your .vimrc so that it only applies inside vim.

```vim
let $FZF_DEFAULT_OPTS = '--no-reverse'
```
