### ISSUE TITLE
how do use vim keybindings for up/down arrow during search

### ISSUE THREAD

**Issue by dustymabe** [junegunn/fzf#1716]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [x] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

On Fedora `fzf-0.18.0-1.fc29.x86_64` I simply run `fzf` and a list of files under the current directory pop up. I type a few letters to search. 10 items appear on screen that match the search. I now need to use my arrow keys to select the item I'm looking for. Is there a way to escape and enter a mode where  `j` `k` will up and down arrow through the list?

I've done a lot of work to eliminate up and down arrows from my typing workflow and would love to not have to use them to get fzf to work. I'm sure this exists I just don't know how to do it and all of my googling about vim key bindings points me to the vim plugin.

**Comment by junegunn** [comment]
> Is there a way to escape and enter a mode where j k will up and down arrow through the list?

No. fzf doesn't implement Vim-style multi-mode.

You can use CTRL-J/K or CTRL-N/P to move your cursor up and down, or you can set up your own bindings with `--bind`. See `man fzf` for details.

**Comment by dustymabe** [comment]
Thanks @junegunn for the reply! I have a few clarifying questions:



> No. fzf doesn't implement Vim-style multi-mode.

It doesn't now, is this something you'd think about adding (if someone were to open a PR?).

> You can use CTRL-J/K or CTRL-N/P to move your cursor up and down, or you can set up your own bindings with `--bind`. See `man fzf` for details.

I did not know about `CTRL-J/K`. That should work for me!

**Comment by junegunn** [comment]
> is this something you'd think about adding

No, I'd like to keep fzf as simple as possible. In my case, I usually type in a few more characters until the item becomes the best match and just hit enter, instead of moving cursor around.
