### ISSUE TITLE
Matching substrings first

### ISSUE THREAD

**Issue by treyharris** [junegunn/fzf#1717]
- Category
    - [x] fzf binary
    - [x] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

I frequently need to find a pane in Tmux by its tty, and fzf is great for that when the tty number I’m searching for is close to the maximum number of digits currently allocated to ttys (e.g. `pts/123` when there are less than 1000 pseudoterminals).

But right now, I’m looking for the pane matching `pts/4`, and unfortunately any search string I can come up with will have 38 matches: `pts/4, pts/14, pts/24, pts/34, pts/40, pts/41, [...], pts/49, pts/54, [...], pts/194`.

The only workaround I can find is to change Tmux’s output format so it puts the tty last, so I can search for `/4$`. Unfortunately, if the output line is long, Tmux truncates it, so I’m only sure to get it _at all_ if I put it before variable-width elements in the format. (I could also set aside a key bind for a special search that _just_ formats `pane_tty` and nothing else, but that’s a specific and heavyweight workaround.)

Neither the quote operator nor `--exact` seem to help here. Is there a way to get the `pts/4` match (whether alone, or first in results) I’m missing? I see other results from closed issues where requests to add the `\b` word-boundary metacharacter and other regex metacharacters were dismissed (legitimately!) as feature creep—but it also sounded like there was another way to get the desired behavior, and I’ve missed what that is.

**Comment by arkku** [comment]
`fzf --nth=1,2..` seems to work with `pts/4` in the first field. Apparently the end of that field is then considered a separate ending that matches `$`, even though the next field is also included.
