### ISSUE TITLE
Preview script and data through stdin

### ISSUE THREAD

**Issue by srfraser** [junegunn/fzf#1719]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [x] Mac OS X
    - [x] Windows
    - [x] Windows Subsystem for Linux
    - [x] Etc.
- Shell
    - [x] bash
    - [x] zsh
    - [x] fish

We use `fzf` with multi-select and a preview window to select tests and builds to perform, and the list of possible selections is large (~16000). In some situations, the length of the options chosen is longer than `getconf ARG_MAX`, meaning passing in the selections to the preview script on the command-line with `{+}` is not possible, and the preview window becomes blank.

I'd like to add an option to provide the preview script with its data using `stdin` instead of as command-line arguments. Ideally, this would be one entry per-line, as this is how most things reading stdin expect to get their data; keeping the quoting could still have benefits if newline is the delimiter, and it might simplify transition of any parsing script.

**Comment by junegunn** [comment]
I have to say this is a very niche use case, but it's true there's no way to work around the limitation of ARG_MAX.

I've looked at your pull request, but there are several things I'd do differently.

- It doesn't support variations of `{+}` such as `{+n}`, `{+1..3}`, etc, all of which may exceed ARG_MAX.
- And the preview command template may contain any number of them.
    - `--preview "my-previewer {+n} {+1..3} {+-1}"`
- I want them to work with `execute` bindings as well.
- It's strange to keep shell-quoting when they are not passed as shell arguments. Line delimiter can be determined by `--print0`.

So I would instead introduce `f` flag that can be added to the expression. And fzf will replace each of them with a temporary file containing the evaluated list.

```sh
fzf --multi --preview 'my-previewer {+nf} {+2..f}'
```

**Comment by srfraser** [comment]
>     * It doesn't support variations of `{+}` such as `{+n}`, `{+1..3}`, etc, all of which may exceed ARG_MAX.
> 
>     * And the preview command template may contain any number of them.
>       
>       * `--preview "my-previewer {+n} {+1..3} {+-1}"`

Fair points.

>     * It's strange to keep shell-quoting when they are not passed as shell arguments. Line delimiter can be determined by `--print0`.

That was mostly to avoid much larger changes to `replacePlaceholder`, I do agree with you, though.

> So I would instead introduce `f` flag that can be added to the expression. And fzf will replace each of them with a temporary file containing the evaluated list.
> 
> ```shell
> fzf --multi --preview 'my-previewer {+nf} {+2..f}'
> ```

This is a good idea. I'm happy to work on a PR for it. At first thought this would be using `os.TempFile` inside `replacePladerholder` if `parsePlaceholder` reports it has the new flag, and filling in the command with the path to the temporary file. I'm unsure how cleaning up the temporary files would work with the change in scopes but I'm sure I can work it out.

**Comment by junegunn** [comment]
Closed by #1733.

**Comment by icholy** [comment]
I'm unclear about how this is supposed to work. I'm trying to get a live preview of a `jq` expression applied to json read from stdin. The following isn't working for me:

```
curl http://localhost:8080 | fzf --print-query --preview-window wrap --preview 'jq {q} {f}'
```

**Comment by vovcacik** [comment]
@icholy, do you have some sample data?

```
2>nul curl https://gist.githubusercontent.com/Rezvitsky/fd364fd01b22feb1f4a38c34f1066100/raw/e51ac3d0e3a50201d004beebfb7bf5a7c2a4f89f/json.json | fzf.exe --disabled --multi --reverse --bind ctrl-a:select-all --preview "jq {q} {+f}"
```

and the query is `.response.users` for example. It sort of works, maybe you want to file new issue.
