### ISSUE TITLE
fzf blocks after selection until line is read or stdin is closed

### ISSUE THREAD

**Issue by stephentalley** [junegunn/fzf#1724]
- Category
    - [ x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [x ] bash
    - [ x] zsh
    - [ ] fish

I have a use case where a long-running script with infrequent output is piped to fzf.  If I select an item in fzf before all input is read, fzf waits until another line is read or stdin is closed before exiting. **This causes fzf to take significantly longer than it should before exiting.**

My use case is simulated with:

    (echo one; sleep 15; echo two) | fzf

If I immediately select "one" in fzf, the process should immediately exit.  Instead, fzf waits 15 seconds until "two" is read from stdin.

In my actual use case, this adds significant overhead to my script run time.

**Comment by junegunn** [comment]
See https://github.com/junegunn/fzf/issues/398
