### ISSUE TITLE
Problems with fd and zsh

### ISSUE THREAD

**Issue by Mladia** [junegunn/fzf#1725]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [x] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

Pressing Ctrl+T always gives the output:
```
find: paths must precede expression: `file`
```

I have added this to my .zshrc
```
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
export FZF_DEFAULT_COMMAND='fd --type file -H'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
```

and I am using the fzf plugin in oh-my-zsh from here
https://github.com/robbyrussell/oh-my-zsh/blob/master/plugins/fzf/fzf.plugin.zsh

Any ideas what might be causing the problem?

**Comment by jose1711** [comment]
interesting, i cannot reproduce the issue on my system. can you share output of `fd --version` and `which fd`?

**Comment by Mladia** [comment]
Yes, thank you, I got it. It seems oh-my-zsh has aliased `fd` to find
