### ISSUE TITLE
failed to read /dev/tty

### ISSUE THREAD

**Issue by ychnh** [junegunn/fzf#1726]
- Category
    - [x] Neovim
- OS
    - [x] Linux
- Shell
    - [x] bash

Running Neovim on Ubuntu 16.04
FZF displays 'failed to read /dev/tty' when opened in a virtualenv environment in Neovim.
FZF runs fine outside a virtual environment in Neovim.
I will investigate further once I have more time since I am not familiar with /dev/tty or FZF.

**Comment by ychnh** [comment]
Ok. I looked through the issue and it seems like FZF just has a hard time finding tty in NVIM
I have a virtualenv folder at '~/gpu-ai' and under this folder are local folders for 'bin' 'dev' 'include'... etc.
I created a new folder called 'dev' here and symbolic linked tty inside this folder `ln -s dev\tty tty` and now :FZF works in NVIM.
Is there a way to handle this smartly? I remember another plugin had a similar issue and resolved it by searching for '/dev/tty' in the chain of parent folders.

**Comment by LuRsT** [comment]
Hi @ychnh, is this still happening?

**Comment by junegunn** [comment]
Works for me in a virtualenv environment running inside terminal buffer of Neovim.

**Comment by GPN211314** [comment]
still happen on my ubuntu 16.04 running on virtualbox

**Comment by kevin-king** [comment]
I get this on the iSH app on an iPad Pro M2, which runs an x86 alpine emulator.

<img width="557" alt="Screenshot 2023-03-18 at 4 58 50 PM" src="https://user-images.githubusercontent.com/4614395/226139732-9134b797-1285-40f2-9139-3b9616d2f409.png">
