### ISSUE TITLE
fzf works but exits with SIGINT(2)

### ISSUE THREAD

**Issue by phatsk** [junegunn/fzf#1727]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [x] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

I noticed the following when `:q` quitting `fzf` in NeoVim - note that fzf works fine, and this only happens when an option is not selected:

```sh
Error running ( ag --nogroup --column --color  '^(?=.)' )|'/Users/phatsk/.fzf/bin/fzf' '--color=bg+:#343d46,bg:#1b2b34,spinner:#fac863,hl:#65737e,fg:#c0c5ce,header:...selec
t-all' '--color' 'hl:4,hl+:12' --delimiter : --nth 4.. --expect=ctrl-v,ctrl-s,ctrl-t --no-height > /var/folders/1p/2y8_8lvx3131z80ktzz6ftcr0000gn/T/nvimBvoevO/2
```

After digging a bit, I tried updating with `~/.fzf/install` which seemed to go fine. I restarted my terminal session and tried again to no avail. 

Next, I ran `fzf` directly in the terminal. It runs fine, but upon exit it leaves with `SIGINT(2)`. No errors are reported to the screen. My guess is that this exit code is what is causing it to throw the error in nvim.

**Comment by junegunn** [comment]
> when :q quitting fzf in NeoVim

Why do you close fzf with `:q`? You can just hit ESC or CTRL-C to close it and if you do that, the exit code is handled gracefully.

**Comment by phatsk** [comment]
Interesting. It's just habit for me for quitting windows. ESC does not quit my `fzf` window, however `^C` does. Previously to updating NeoVim, `:q` would quit the window gracefully.

**Comment by junegunn** [comment]
You must have remapped ESC to something else using `tnoremap` (see `:tmap`).

To override:

```vim
autocmd! FileType fzf tnoremap <buffer> <esc> <c-c>
```
