### ISSUE TITLE
Feature request: manipulate selected items from a different process

### ISSUE THREAD

**Issue by jose1711** [junegunn/fzf#1728]
- Category
    - [x] fzf binary
    - [x] Key bindings
- OS
    - [x] Linux
    - [x] Mac OS X
- Shell
    - [x] bash
    - [x] zsh
    - [x] fish

I'd find it useful if `fzf` has an option to provide a mechanism for remote processes to manipulate current selection in background while `fzf` is in interactive mode. This could allow things like being able to bind shortcuts to add/remove predefined matches (`deselect mp4$ avi$ webm$`) to/from selection or save/restore state between invocations like mentioned in #1478.

**Comment by notevenodd** [comment]
Perhaps it is "too much", but indeed, it would indeed open endless possibilities if one could query/modify the internal state of the fzf process via commands sent over a (unix-domain) socket.

**Comment by junegunn** [comment]
Please take a look at #3094.
