### ISSUE TITLE
Tab complete without recursion

### ISSUE THREAD

**Issue by jubishop** [junegunn/fzf#1729]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [x] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [ ] fish

It's an interesting hack to set FZF_COMPLETION_TRIGGER to an empty string and get tab completion but the problem is since FZF recurses (presumably using _fzf_compgen_path and _fzf_compgen_dir) it generates potentially a ton of results.  I'd love to have tab completion act simply on the results of the current directory, without recursion.  Is this possible?

**Comment by junegunn** [comment]
```sh
_fzf_compgen_path() {
  ls "$1"
}
```

(https://github.com/junegunn/fzf#settings)
