### ISSUE TITLE
Feature request: insert entered filter text

### ISSUE THREAD

**Issue by igorsol** [junegunn/fzf#1732]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [x] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

When I use fzf finder I often type something quickly then look at the list and see there is nothing matching my typed text. If I press Esc at this moment all my typed text will be lost but sometimes I need it so after pressing Esc I must type the same text second time.
To avoid entering text second time I propose to add one more key binding to the finder, something like <Ctrl-Enter> to insert typed search filter instead of any currently selected item[s].

**Comment by junegunn** [comment]
Have you read through `man fzf`?

**Comment by igorsol** [comment]
Thank you for the clue.
I added following line to my .bashrc:

> export FZF_DEFAULT_OPTS='--bind alt-enter:print-query'

Unfortunately this does not work correctly with Ctrl-R bash history search but I'll try to tweak shell/key-bindings.bsh

**Comment by igorsol** [comment]
Just for the record, here is my modified version of `__fzf_history__` function which inserts query text into the command line when I press Alt-Enter:
```
__fzf_history__() (
  local rawline
  shopt -u nocaseglob nocasematch
  rawline=$(
    HISTTIMEFORMAT= builtin history |
    FZF_DEFAULT_OPTS="--height ${FZF_TMUX_HEIGHT:-40%} $FZF_DEFAULT_OPTS --tac --sync -n2..,.. --tiebreak=index --bind=ctrl-r:toggle-sort $FZF_CTRL_R_OPTS +m" $(__fzfcmd) )
  local line
  if line=$(command grep '^ *[0-9]' <<< "$rawline"); then
    if [[ $- =~ H ]]; then
      sed 's/^ *\([0-9]*\)\** .*/!\1/' <<< "$line"
    else
      sed 's/^ *\([0-9]*\)\** *//' <<< "$line"
    fi
  else
    echo $rawline
  fi
)
```
