### ISSUE TITLE
Hang with 100% cpu usage after running rosbag play

### ISSUE THREAD

**Issue by rcywongaa** [junegunn/fzf#1734]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

I am running version `0.17.5 (b46227d)`.
After I run `rosbag play` on a plane and then run `fzf`, `fzf` hangs with 100% CPU usage.  I see fzf scanning for files, as indicated by the `xxx/xxx` value increasing, but I cannot type anything and Ctrl-C / Esc does not work.  I can only kill it with SIGTERM

Running `fzf --height 40%` makes the problem worse where I can only kill `fzf` with SIGKILL.

`echo $FZF_DEFAULT_OPTS` returns nothing
`printenv` also that aside from `$TMUX_PANE`, nothing else is different from panes where `fzf` still works

**Comment by anna1980-6** [comment]
https://github.com/junegunn/fzf/pull/1824#issuecomment-575882159

**Comment by junegunn** [comment]
I have no idea what "rosbag" is, so I don't think I can be of help. Is this still an issue with the latest version of fzf?

**Comment by rcywongaa** [comment]
Seems to have magically disappeared recently
