### ISSUE TITLE
Ram usage grow exponentially with the result

### ISSUE THREAD

**Issue by nordmagnus999** [junegunn/fzf#1739]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

I made a script based on the [notational-fzf-vim](https://github.com/alok/notational-fzf-vim)'s main command, which you can find [here.](https://gist.github.com/nordmagnus999/02b2594d2527d4b91320d430a21e1f09)

It does work great (i mainly use it in bash) and the only problem i noticed was that fzf was filling the ram exponentially with every added result.(which i'm sure sound normal but i thought of raising this issue just in case).

Now it didn't do that normally, and would only do this if i run the said script/or normal fzf with the same option as the script, in a nested directory (repo from mercurial, precisely [this repo from mozilla](https://hg.mozilla.org/mozilla-central)).

I did lots of testing with this, and i do know it might be because of the `--with-nth=1..` and `--ansi` option as noted/described in the fzf's wiki, but even so i wanted to make sure if it was normal.

For added detail, my current ram locally is ~6GB, and fzf use roughly 1GB per 1Million result with the linked script (result are that huge because of the fzf's option `--with-nth=1..` as you might have noticed already) but while this seems excessive, it is indeed a feature found useful.
I'm also using the latest version from github as well as running it on ubuntu 19.04.

**Comment by nordmagnus999** [comment]
I basically want to keep the functionality of the script/fzf's option i used intact, while making it use less ram, if possible.

**Comment by LuRsT** [comment]
Could you merge this issue with #1740? Since they are duplicates?
