### ISSUE TITLE
Any way to cache results from fzf listing?

### ISSUE THREAD

**Issue by nordmagnus999** [junegunn/fzf#1740]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

I thought it would be useful for another issue i'm having [here](https://github.com/junegunn/fzf/issues/1739) to cache the result from fzf's listing, to a file for example, so i could just pipe that to it in a script, and dedupes with new entry.
I'm just unsure on how to pipe the said listing to a file in bash.

**Comment by LuRsT** [comment]
Hi @nordmagnus999, you've probably fixed it by now, but you can pipe the command with a big output into awk/sed/a script to trim the list down before passing it to fzf instead of using a cache files.

If you managed to solve it some other way, do let us know.
