### ISSUE TITLE
Ability to draw a border around the finder

### ISSUE THREAD

**Issue by notevenodd** [junegunn/fzf#1741]
- Category
    - [x] fzf binary
- OS
    - [x] Linux
- Shell
    - [x] bash
    - [x] dash

This is a _feature request_: "_Add ability to draw a border around the finder_".
Currently `--border `only draws a line above and below. The ability to draw a border is especially needed when fzf has been invoked with some left and right margin (`--margin`) around the finder.

As one example use case, one of my script fills the screen with information and on occasion invokes:
`... | fzf --no-clear --height 33% --margin 0,15 --border `
It's not so easy to distinguish content in finder from the rest of screen, a full border would provide a clear separation.

**Comment by notevenodd** [comment]
What I ended up doing as _workaround_ in my example use case is invoking fzf with a different background color (`fzf --color bg=4 ...`), thus it's clear that way what's part of fzf finder vs what's content of the screen.

**Comment by junegunn** [comment]
> fzf with a different background color 

Yeah, that's a much better approach IMO. It's especially nice with 24-bit colors. (`fzf --color 'bg:#334455'`)

I may revisit full border support in the future, but for now, I don't think we desperately need it.
