### ISSUE TITLE
History search uses id instead of command

### ISSUE THREAD

**Issue by divramod** [junegunn/fzf#1742]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux (Ubuntu 18 server)
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

Hey, i use fzf with great joy. 
Thx for the awesome project!!!

I installed fzf on ubuntu using the following script

```
#!/bin/sh
fzf_exists=$(command -v fzf)
if [ -z "${fzf_exists}" ]; then
  mkdir -p /tmp/fzf
  cd /tmp/fzf
  git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
  ~/.fzf/install
  rm -rf /tmp/fzf
fi
```

Now i have the problem that when invoking the history search function with c-r, and selecting a history entry the fzf functions prints out the number.

When i manipulate the function with awk its running fine, but i like to be able to use the standard install.

```
__fzf_history__() (
  local line
  shopt -u nocaseglob nocasematch
  line=$(
    HISTTIMEFORMAT= builtin history |
    FZF_DEFAULT_OPTS="--height ${FZF_TMUX_HEIGHT:-40%} $FZF_DEFAULT_OPTS --tac --sync -n2..,.. --tiebreak=index --bind=ctrl-r:toggle-sort $FZF_CTRL_R_OPTS +m" $(__fzfcmd) |
    command grep '^ *[0-9]') &&
    if [[ $- =~ H ]]; then
      # sed 's/^ *\([0-9]*\)\** .*/!\1/' <<< "$line"
      echo $line | awk '{$1=""}1'
    else
      # sed 's/^ *\([0-9]*\)\** *//' <<< "$line"
      echo 'else'
    fi
)
```

I am using bash vi mode.

Can someone help me out here?

**Comment by divramod** [comment]
i see its not fixing it, it keeps the ticks around env-vars like ```echo '$SOME_VAR'```. hmmm

**Comment by LuRsT** [comment]
Hey @divramod, since there's been a few months since you posted this question, did you manage to get it working using default config with newer versions of `fzf`, or did you manage to use a workaround?
