### ISSUE TITLE
unable to use --preview command

### ISSUE THREAD

**Issue by zachvalenta** [junegunn/fzf#1743]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [x] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

unable to use the preview command 
```sh
$ fzf --preview
preview command required
```

despite following installation instructions https://github.com/junegunn/fzf#using-homebrew-or-linuxbrew
```log
$ brew install fzf
$ $(brew --prefix)/opt/fzf/install
```

**Comment by junegunn** [comment]
Please read through `man fzf`

**Comment by jsheedy** [comment]
This example from the man page helped:

`fzf --preview='head -$LINES {}'`

preview is great!
