### ISSUE TITLE
Bind 'Insert' key

### ISSUE THREAD

**Issue by bAndie91** [junegunn/fzf#1744]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish
    
Question
---

Can I bind the <kbd>Insert</kbd> key?
It produces <kbd>esc</kbd>`[2~` escape sequence on my terminal.

**Comment by LuRsT** [comment]
On `zsh` you can use `bindkey` to do what you want:

```zsh
 bindkey -s '\e[2~' 'ls'
```

More instructions here: https://unix.stackexchange.com/questions/116562/key-bindings-table

Since you use `bash`, I'm unsure, you could try using the program `xbindkeys`.
