### ISSUE TITLE
highlighted entry ignores ansi colors of input string

### ISSUE THREAD

**Issue by herrsimon** [junegunn/fzf#1745]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

When supplying colored input to 'fzf --ansi', the highlighted entry does not respect the input color. This problem disappears when '--no-bold' is passed in addition, so I guess that bold text somehow overrides the foreground color.

Example:

`echo 'entry1\n\x1b[38;5;4mentry2' | fzf --ansi`

 'entry1' is uncolored, 'entry2' has colored foreground. As soon as 'entry2' is selected, the color disappears. However,

`echo 'entry1\n\x1b[38;5;4mentry2' | fzf --ansi --no-bold`

works as expected, i.e. entry2 remains colored when focused.

**Comment by LuRsT** [comment]
Hi @herrsimon, 

It seems like this has been fixed, at least I couldn't reproduce your issue. Do you still find that problem in your enviroment?

Also, remember to add `-e` to those `echo` commands, I'm guessing you have an alias for that, I needed the flag for it to work.
