### ISSUE TITLE
Add key binding options for {ctrl,alt}-{backspace,del,left,right}

### ISSUE THREAD

**Issue by smallid** [junegunn/fzf#1747]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

Similar to #1234 and #1201, please add support for these key bindings:

`ctrl-left`
`ctrl-right`
`ctrl-bs`
`ctrl-del`
`alt-del`

(These bindings would be very useful to me for editing the input. Ctrl-left/right are alternate emacs bindings for moving between words: https://www.gnu.org/software/emacs/manual/html_node/emacs/Moving-Point.html)

**Comment by junegunn** [comment]
I'm not sure if those key chords are supported by the standard terminal. Your terminal emulator may have settings to send certain escape sequences when they are pressed, but it may not work on other terminal emulators if they are not part of the standard.

- https://unix.stackexchange.com/a/264871/62171
- https://apple.stackexchange.com/a/24282/125495

If you think it's possible, please send a pull request to devel branch.

**Comment by haosdent** [comment]
alt-del should be a standard operation when I try it in different emulators. @junegunn

**Comment by haosdent** [comment]
@junegunn raise a PR at https://github.com/junegunn/fzf/pull/2771 , but I am not sure if my change is correct.
