### ISSUE TITLE
Is fuzzy search for file contents, with preview, available outside of vim? 

### ISSUE THREAD

**Issue by headdab** [junegunn/fzf#1751]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

Is it possible to replicate the functionality of :Ag and :Rg with support for preview so that it works from the command line instead of inside VIM?  I've searched for and read a lot about the vim stuff but can't find anything that applies.

**Comment by junegunn** [comment]
You can use this script: https://github.com/junegunn/fzf.vim/blob/master/bin/preview.sh

```sh
rg --column --line-number --no-heading --color=always --smart-case foo |
    fzf --preview 'preview.sh {}'
```

**Comment by headdab** [comment]
Thanks!
