### ISSUE TITLE
use fzf non interactively or use algorithm separately

### ISSUE THREAD

**Issue by dickshaydle** [junegunn/fzf#1753]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [x] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

First, fzf is an awesome tool. The algorithm is is incredibly fast. 
It could be useful if there is an option to use fzf without user interaction. Maybe a command line option or even a separate library so it can be used in python for example. 
Has somebody gone in this direction already?

**Comment by junegunn** [comment]
Use `--filter` option. And there is a third-party python binding called https://github.com/dahlia/iterfzf

**Comment by dickshaydle** [comment]
Thanx man. The --filter option was what i was looking for. Must have read over it in the manual.

iterfzf is interactive only, but should not be so difficult to add the --filter option for it.
