### ISSUE TITLE
binding :FZF ~ does not work in vim

### ISSUE THREAD

**Issue by bragjo** [junegunn/fzf#1754]
Hi,

I'm trying to map a key to be able to use FZF to search through all files on the system by binding :FZF ~ to something like CTRL+å (swedish keyboard) or anything else, but it just doesn't work.

When I bind CTRL+p to execute the command :FZF -m it works perfectly fine (show files in current directory).

I was also wondering if there's an alternativate to :FZF ~ ?

Maybe a command that shows all the files in the parent root directory of current directory?

For example if I have a folder structure like this:

Code/timereporting/server
and
Code/timereporting/client

I want to be able to access all files within the folder "timereporting" so I can easily switch between files in both the server and client dir using FZF and not being forced to quit vim.

Please help. I love FZF and want to make it my primary tool for navigating, searching/greping and so on!

I'm on MAC OSX Catalina, using a swedish keyboard.

Thanks

Best,

J

**Comment by junegunn** [comment]
Please explain how exactly you did with real code.

**Comment by LuRsT** [comment]
Hi @bragjo,

It'd be easier for us to help if you told us how you tried to map it. These work for me:

```
map <A-t> :Tags<CR>
map <A-f> :Files<CR>
map <A-a> :Ag<CR>
map <A-h> :History<CR>
```

The vim config you want is this:

```
nnoremap <C-å> :FZF<CR>
```

I don't have a Swedish keyboard, but it should work as expected. Try it and let us know how it works

**Comment by rafaelleru** [comment]
I think this can be closed, you provided info and he is not giving feedback anymore.

Only trying to help :)
