### ISSUE TITLE
match-scoring algorithm as freestanding project?

### ISSUE THREAD

**Issue by stumash** [junegunn/fzf#1756]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

It would be awesome if the core match-scoring algorithm was exposed as its own module, maybe even a separate repo. Then we could use your epic algorithm in random applications! Just think, your custom Smith-Waterman would be in autocomplete suggestions all over the internet!

Just an idea for the wishlist. Big fan.

**Comment by junegunn** [comment]
I personally don't have a need for it. if anyone's interested in extracting the code and maintaining the project, feel free to do so.
