### ISSUE TITLE
Using $HOME in --history file path doesn't work

### ISSUE THREAD

**Issue by Melkster** [junegunn/fzf#1757]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

I want my FZF history file to be located in my `$HOME` directory, and so I put the following in my `~/.zshrz`:
```sh
export FZF_DEFAULT_OPTS='--history="$HOME/.fzf_history"'
```

And created the file `.fzf_history` in `$HOME`.

However, when activating FZF I get the following error:

```
invalid history file: open $HOME/.fzf_history: no such file or directory
```

It seems like FZF doesn't use the `$HOME` variable in the path. I don't want to use an an absolute path to my home directory.

**Comment by junegunn** [comment]
```sh
export FZF_DEFAULT_OPTS="--history='$HOME/.fzf_history'"
```

**Comment by Melkster** [comment]
> ```shell
> export FZF_DEFAULT_OPTS="--history='$HOME/.fzf_history'"
> ```

Thanks, that solved it!
