### ISSUE TITLE
Trouble with pass completion in zsh

### ISSUE THREAD

**Issue by xoihiox** [junegunn/fzf#1759]
Newb question.

I copied the pass completion script to my `.zshrc` from the [examples](https://github.com/junegunn/fzf/wiki/Examples-(completion)) page.

It doesn't seem to work out of the box for zsh.  
```
# pass completion suggested by @d4ndo (#362)
_fzf_complete_pass() {
  _fzf_complete '+m' "$@" < <(
    pwdir=${PASSWORD_STORE_DIR-~/.password-store/}
    stringsize="${#pwdir}"
    find "$pwdir" -name "*.gpg" -print |
        cut -c "$((stringsize + 1))"-  |
        sed -e 's/\(.*\)\.gpg/\1/'
  )
}
[ -n "$BASH" ] && complete -F _fzf_complete_pass -o default -o bashdefault pass 
```
I do not know my way around the zsh completion engine, but so far have tried loading bashcompinit compatibility mode in zsh and fiddling with `[ -n "$BASH" ] &&`, to no avail.  

Any advice?

Thanks.

**Comment by LuRsT** [comment]
Hi @xoihiox, when you say it doesn't work, what exactly happens when you try to use the autocomplete?
