### ISSUE TITLE
Bash completion improvements

### ISSUE THREAD

**Issue by gene-pavlovsky** [junegunn/fzf#1761]
Hello!
I would like to find out how to improve bash completion abilities of fzf for a particular task, but I guess it would be also helpful for other similar things.
I'm working on a project that uses gradle for building, I have gradle and gradle-completion installed, so typing ./gradlew <TAB><TAB> shows a list of 300+ build tasks. I'd like to be able to search this list using fzf. How to achieve that?
Thanks

**Comment by rockandska** [comment]
I create as the side a project a completion wrapper who use fzf over all original completion scripts named [fzf-obc](https://github.com/rockandska/fzf-obc/)
I don't use gradle, but if bash complete show the build tasks, fzf-obc should be able to works with.
Give it a try and post an issue on [fzf-obc](https://github.com/rockandska/fzf-obc/) if needed

Regards

**Comment by gene-pavlovsky** [comment]
@rockandska Hi, this seems to work, but not without issues.
1. There is an error message about /proc/cpuinfo not existing (macOS), which I've opened an issue about in your repo

2. The completion list seems to be reversed (e.g. the "wrapper" gradle task, which is the last in the list of tasks in our project, is displayed first when using fzf-obc)

3. It's probably not an issue of fzf-obc itself, but some room for thought:
The regular completion list from gradle-completion includes the tasks description, e.g. "wrapper  - Generates Gradle wrapper files.". When not using fzf-obc, this helps to figure out what is what, then I can type the first (few) letter(s) of the task and hit tab again to complete it - now without the description. When using fzf-obc, the whole list with descriptions is displayed. After that if the wrapper task is selected in the list, it gets copied to the command line with the description. As a result, usability is not great. The only workable usages I can imagine is use the initial completion with fzf to quickly find the name of the desired task, then either cancel completion and type the task name manually, or accept the completion and manually delete the unwanted description part from it. If it would be possible to define a custom post-processing for the result picked for gradle tasks, then the post-processing step could remove the [whitespace] [dash] [whitespace] [description] parts.

**Comment by junegunn** [comment]
No. I'll be focusing only on fzf binary itself. I'm not interested in extending the auxiliary shell scripts anymore. Advanced use cases of fzf should be covered by third-party projects.
