### ISSUE TITLE
Feature request: hide entries with a length longer than N characters

### ISSUE THREAD

**Issue by syedelec** [junegunn/fzf#1763]
- [X] I have read through the manual page (`man fzf`)
- [X] I have the latest version of fzf
- [X] I have searched through the existing issues

## Info

- OS
    - [X] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [X] bash
    - [ ] zsh
    - [ ] fish
    
## Problem / Steps to reproduce
I want to automatically hide entries longer than N characters with a parameter.

In the following example, it would be nice to hide entries with more than 100 chars for example because for some reason, `git/.gitalias` is listed at the end even with `tiebreak=length`

![Screenshot from 2019-11-18 14-50-03](https://user-images.githubusercontent.com/9877335/69100773-c213fb80-0a12-11ea-939f-6d98880d4b2d.png)

If there is an other way to workaround this, let me know.
fzf version 0.19.0

Thanks

**Comment by junegunn** [comment]
This should not be an option of fzf. You can always use some preprocessor to filter out unwanted lines.

```sh
input-program | pre-processor-program | fzf | post-processor
```
