### ISSUE TITLE
Different character for fuzzy matching in --exact mode

### ISSUE THREAD

**Issue by hotsphink** [junegunn/fzf#1768]
- [x] I have read through the manual page (`man fzf`)
- [ x I have the latest version of fzf
- [x]I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

For what I use fzf for, I always want to default to --exact. But that means I can't share my match strings with other people because the meaning of `'` is inverted. Would it be possible to have an alternate prefix character for specifying fuzzy matching, and disabling unquoting via `'`? (Also, unquoting just feels wrong. Typing in a quote very much feels like I want a substring match, and it feels weird to use it for a fuzzy match.)

Right now, patterns will always change behavior depending on whether or not --exact is used. With a different prefix, it would be possible to write and share patterns that have a fixed meaning. Say we use `?` for example. Then `'src ?exit` would mean the same thing with or without --exact. `src ?exit` would still change its meaning, but I'm ok with that.

This partly comes up because people ask me "how do I X?" and my answer is "oh, you do Y, unless you're using --exact and then it would be Z." I'd like to be able to tell people something that will always work.

As for the character, my first thought was `*` because you're spreading the following characters. But to me that felt like it conflicted with globbing too much, so now I'm thinking `?` would work well. (Single-character glob matching is much less common than asterisk.)

If disabling `'` from unquoting is too big a change, then I would request that an `=` prefix always mean exact substring match, and a `?` prefix always mean fuzzy matching. Then I can just stop using `'` entirely and my match strings will work regardless of the --exact setting.

**Comment by junegunn** [comment]
> This partly comes up because people ask me "how do I X?" and my answer is "oh, you do Y, unless you're using --exact and then it would be Z." I'd like to be able to tell people something that will always work.

I'm not sure why you can't just tell them to type in some query on fzf regardless of `--exact` mode, because the ranking algorithm of the fuzzy matcher will almost always give the exact matches the highest scores and put them on the top of the list. I don't know about your audience, but shouldn't they at least read [the README page](https://github.com/junegunn/fzf#usage) to learn how fzf basically works before blindly following your instruction? If you want your instruction to be perfectly reproducible, the suggested change is not sufficient. You should also pass them your `FZF_DEFAULT_OPTS` because there are more options that can affect the result, e.g. `+x`, `+s`, `-i`, `+i`, `--algo` to name a few.

**Comment by hotsphink** [comment]
> because the ranking algorithm of the fuzzy matcher will almost always give the exact matches the highest scores and put them on the top of the list.

This has not been my experience with what we are using it for.

By far the most frequent thing I use fzf for is for selecting builds in Mozilla's continuous integration system. Most people aren't aware that fzf is what is being used under the hood. We all run `mach try fuzzy` or `mach try fuzzy --exact`, where `mach` is a wrapper python script that generates a large list of possible jobs to run and then hands over to fzf for selection. So almost nobody is going to have `FZF_DEFAULT_OPTS` set; we do everything through the `mach` driver, and it doesn't expose anything analogous.

Sorry, I realize that this makes my request somewhat specific to our setup. The scoring does not consistently rank the desired jobs near the top, and it wouldn't help that much if it did -- it's most common to want to select a large set of jobs, not a single one. So typical usage is to filter down to all or a subset of what you want and select them all, then possibly change the filter to select more jobs and select all of them, etc.

An example of the scoring going wrong for this usage: I often want to select jobs that have "spidermonkey" in the name. If I just filter on `spider`, I get about 40 jobs like `test-windows7-32/opt-mochitest-devtools-chrome-e10s-3` (te***s***t-windows7-32/o***p***t-moch***i***test-***de***vtools-ch***r***ome-e10s-3) before I get to the ones I want, like `spidermonkey-sm-rootanalysis-linux64/debug`.

For both of these reasons, using a substring match `'spider` is much better. First because it doesn't have the 40 unwanted jobs listed first (a scoring problem), and second because there are 20 spidermonkey jobs so I don't want to select them individually (not a scoring problem), I want to press Ctrl-A to grab them all at once without getting any extra.

I do see now that the change I'm requesting may make sense for what we are using fzf for, but not necessarily for general fzf usage. I still think that having a single quote do a fuzzy match in --exact mode is confusing, and it would be better to have a consistent prefix character for substring vs fuzzy.

**Comment by hotsphink** [comment]
I should mention that the connection to fzf isn't as cryptic as I made it out to be. The tool has a help line: `For more shortcuts, see mach help try fuzzy and man fzf`. So it is possible that people might read the man page and see `FZF_DEFAULT_OPTIONS`, though I've never heard anyone mention it yet.

**Comment by junegunn** [comment]
>  I get about 40 jobs like test-windows7-32/opt-mochitest-devtools-chrome-e10s-3 (test-windows7-32/opt-mochitest-devtools-chrome-e10s-3) before I get to the ones I want, like spidermonkey-sm-rootanalysis-linux64/debug.

Hmm, that doesn't sound right. For me

```sh
fzf -q spider <<_
test-windows7-32/opt-mochitest-devtools-chrome-e10s-3
spidermonkey-sm-rootanalysis-linux64/debug
_
```

puts `spidermonkey-sm-rootanalysis-linux64/debug` on top as expected. Can you check again?

> and second because there are 20 spidermonkey jobs so I don't want to select them individually (not a scoring problem), I want to press Ctrl-A to grab them all at once without getting any extra.

That's a valid concern.

> Most people aren't aware that fzf is what is being used under the hood

So they don't even know about [the search syntax of fzf](https://github.com/junegunn/fzf#search-syntax). In that case, disabling extended search mode can be an option. i.e. `fzf +x -e`

**Comment by hotsphink** [comment]
> Can you check again?

Yes, you are 100% right. I somehow never realized that fzf puts the highest scores at the bottom of the list and scrolls *up*.

**Comment by junegunn** [comment]
You might want to adjust `--layout` which determines the orientation.
