### ISSUE TITLE
[feature request] customizable line continuation characters

### ISSUE THREAD

**Issue by herrsimon** [junegunn/fzf#1769]
- [x ] I have read through the manual page (`man fzf`)
- [x ] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

Could you please add an option to specify the line continuation characters (currently '.. ') which are inserted by fzf when --no-hscroll is used and a line exceeds the terminal width? In particular, please allow to specify the empty string so that no continuation characters are printed at all.

In my use case (which is rather typical), I'm selecting some id by its human-readable description by outputting the description with terminal width and then adding the id to the right. The two dots and the space inserted by fzf are not very useful in this case.

Thank you very much!

**Comment by junegunn** [comment]
When it comes to the formatting of the input, it's almost impossible to come up with a general solution that meets all kinds of different requirements. So fzf leaves it up to the users. Instead of using `--no-hscroll`, you can pre-process the input to fit in screen before passing it to fzf.

```sh
input-generating-program | formatting-program | fzf
```

**Comment by herrsimon** [comment]
I completely agree to what your saying but my problem does not fit your solution. Let me elaborate a bit more: Imagine you have a text file with lines of the form

``UUID       DESCRIPTION``

where only DESCRIPTION is meaningful for the user. Then, when you would like to select a UUID by its DESCRIPTION, your ``formatting-program`` has no choice as to display the full (and rather long) UUID somewhere on each line, unnecessarily using a lot of screen space without adding any additional information for the user. In such a situation, it is very useful to use --no-hscroll and hide the UUID on the right of the viewable screen area, and use something like 

``input-generating-program | formatting-program | fzf --no-hscroll | post-process-program``,

where post-process-program extracts the UUID. I think such a use case is not that exotic (I currently use it for a textfile-based personal database). 

Another point would be to just replace the '.. ' line continuation characters by '>' or any other symbol, in order to save some screen space. 

Of course we can now raise the question whether it is worthwile to discuss about three columns of screen space, but as fzf is perfect and fully customizable in every other aspect it would be sad not to have such a feature.

Unless the '.. ' is hardcoded in ncurses somewhere, it should furthermore be very easy to implement. I never programmed in Go but if you agree to have such a feature and optimally point me to the relevant files which would need to be changed, I would be happy to try and come up with some code.

**Comment by herrsimon** [comment]
I have to apologize, actually fzf can already do what I want by using the ``--with-nth`` option. My second point is still valid, however: It would not hurt if one could replace the line continuation characters '.. ' by '>' or any other string, either in order to save space or to simply customize fzf's appearance to one's liking.

**Comment by junegunn** [comment]
> It would not hurt if one could replace the line continuation characters

Yeah, but with this approach, we'll end up with all kinds of minor options that very few actually need which would lead to software bloat, and I have to draw the line somewhere. fzf is an open-source project so users with different preferences can always build it with their tweaks.

**Comment by herrsimon** [comment]
Well, I would not call this particular feature bloat (probably less than ten lines of code to implement and no measurable performance loss), but of course I accept your decision.

**Comment by junegunn** [comment]
Little things quickly pile up. We can imagine so many ways to tweak minor visual elements of fzf and there is no good reason to allow one but not the others. Feature bloat is not just about the number of lines of code or performance loss, it's also about conceptual complexity and cognitive overhead exerted on the average users who have to read through the lengthy manual full of irrelevant niche options.
