### ISSUE TITLE
:FZF not working with a path passed

### ISSUE THREAD

**Issue by Randuin** [junegunn/fzf#177]
In vim `:FZF` and `:FZF ~` will all work fine but `:FZF app/models` shows nothing
Some other odd notes. If I try `:FZF! app/models` that works, but only once, any subsequent attempts will also show nothing

**Comment by junegunn** [comment]
Ouch! Thanks for the report. I realized that it didn't work with relative paths. Fixed it. Let me know if you still see any issues.

**Comment by Randuin** [comment]
It works on first go now :+1: But after I use it once, it changes the directory to that relative path and any subsequent runs will use that. This wasn't the behavior before as far as I remember. Is there a way to get it to not change?

**Comment by junegunn** [comment]
It is not supposed to work that way. So you mean `:pwd` is changed after `:FZF RELPATH`?

**Comment by Randuin** [comment]
Yes

**Comment by junegunn** [comment]
Strange, it's handled [in the code](https://github.com/junegunn/fzf/blob/master/plugin/fzf.vim#L237) and I can't seem to reproduce the case. I just pushed another commit that may or may not fix your problem. Please update and let me know of the exact scenario that I can follow to reproduce the problem.

**Comment by Randuin** [comment]
That worked! Thanks so much!

**Comment by junegunn** [comment]
Great. Thanks!
Now I see that the previous code had a bug. It didn't restore the current path when FZF is started w/o tmux and user interrupted the process (ESC or CTRL-C). I should really be adding proper test cases for vim plugin.
