### ISSUE TITLE
Option to set background of highlights

### ISSUE THREAD

**Issue by zsugabubus** [junegunn/fzf#1770]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

That would be great if I could set the background of highlights, not just their foreground. I'm experimenting with colorful (`--ansi`) inputs and I found that there is no good setting for `hl`.

**Comment by LuRsT** [comment]
Hi @zsugabubus, isn't this more of a feature request for `highlight` or the program you use for previewing things?

**Comment by zsugabubus** [comment]
Thanks for the feedback. I’m talking about highlightings of searched substrings. You can set their foreground using `hl` or `hl+` but as I said, sometimes it would be more suitable if you could set its background (too). I usually match fancy colored lines, so these highlights get lost in the rainbow. I could achieve greater contrast with this option.

**Comment by junegunn** [comment]
Still no color option for background, but since 0.24.0, you can set `reverse` attribute which might suit your needs.

```sh
# Apply reverse attribute
rg --line-number --no-heading --color=always "" |
  fzf --ansi --color hl:reverse,hl+:reverse

# -1 means keeping the original foreground color
rg --line-number --no-heading --color=always "" |
  fzf --ansi --color hl:reverse:-1,hl+:reverse:-1
```

**Comment by zsugabubus** [comment]
Thanks a lot, looks great!

(Though the issue is not _exactly_ about it I'm satisfied with the result, so you can close it if you want.)
