### ISSUE TITLE
Ranking of overlapping pattern matches

### ISSUE THREAD

**Issue by zsugabubus** [junegunn/fzf#1771]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

I regularly find myself filtering lines containing repeating/overlapping patterns.

For example, typing `abc abc abc` or `abc bbb bbb`... gives the exact same ranking as `abc`.

```sh
fzf <<_
aaa/bbb/ccc/
aaa/bbb/ccc/aaa/bbb/ccc/
aaa/bbb/ccc/aaa/bbb/ccc/aaa/bbb/ccc/
_
```

I think it would be more intuitive if I type `aaa aa aa`, I get the third line first ranked; instead of that two `aa`s match inside `aaa` that will never result better hits.

What do you think?

**Comment by junegunn** [comment]
You can just type in `abcabcabc`, `abcbbbbbb`, or `aaaaaaa` for better results. There is no reason to add spaces between the words.

**Comment by zsugabubus** [comment]
Of course it doesn't cause an issue if you know in advance what's best pattern. One pattern maybe not even enough, think of "!foo" or "'bar", so you unavoidably have to press space.
The universal goal is to get the desired result in the shortest possible time, so you will:
1. Minimize typing.
   As a result, you probably give suboptimal patterns that you may not even able to extend (e.g. pressing another four "a") to further filter the list without losing hits. Then it could be even faster if you use arrow keys.
2. Decide quickly.
   You decide based on the unhighlighted parts, so overlapping matches seems to kill this.

And at the end, if you pressed space then it currently will mean lot's of typing, that against our goals.

**Comment by xerus2000** [comment]
I had the same issue while browsing through packages:

I searched for `dragon drag`, but `dragon` was still ranked higher than `dragon-drag-and-drop`, which is unintuitive.
