### ISSUE TITLE
[Discuss] Logically trigger fzf base on conditional patterns?

### ISSUE THREAD

**Issue by tmpm697** [junegunn/fzf#1773]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] ArchLinux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

I can trigger `fzf` to start only command start with, for e.g: `j`

But in complex situation we might want to set `fzf` to trigger when command start with `j` and commandline contains `get`, for e.g: `j arg1 arg2 get arg3`

How to achieve this scenarios?

**Comment by junegunn** [comment]
This is more like a general shell scripting/configuration question, rather than an issue of fzf. How about asking this on more relevant sites, such as StackOverflow? I don't use zsh and I'm not a zsh expert.
