### ISSUE TITLE
Possibility to specify the preview-window's color

### ISSUE THREAD

**Issue by notevenodd** [junegunn/fzf#1776]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

This is a feature request: add possibility to specify preview-window's bg / fg color via the --color option

**Rationale**: sometimes the content in the preview window is meant for a light theme while content piped to fzf is meant for dark theme (or the other way around). This case often typically happens when using a syntax highlighter filter as preview, and some tool (using LS_COLORS or own color scheme) for the fzf input.

**Comment by junegunn** [comment]
![image](https://user-images.githubusercontent.com/700826/70718400-7adc0a80-1d33-11ea-8d1a-3d0c288ded97.png)
