### ISSUE TITLE
Ctrl-R, Alt-C not working on Mac OS X, macports installation

### ISSUE THREAD

**Issue by tvendelin** [junegunn/fzf#1782]
- [ x] I have read through the manual page (`man fzf`)
- [ x] I have the latest version of fzf
- [ x] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [x ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ x] bash
    - [ ] zsh
    - [ ] fish
    
## Problem / Steps to reproduce
I have installed both bash and fzf from macports. Unfortunately, although basic file search works, neither Ctrl-R nor Alt-C has no effect with defaults.

```
fzf --version
0.19.0
``` 
What am I missing? What additional info could be supplied?

**Comment by junegunn** [comment]
Please refer to the package documentation: https://github.com/macports/macports-ports/blob/master/sysutils/fzf/Portfile#L53-L70

**Comment by tvendelin** [comment]
Thank you, but I do not immediately understand what should I do about it.
