### ISSUE TITLE
ssh completion doesn't search hostname

### ISSUE THREAD

**Issue by yargevad** [junegunn/fzf#1783]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

I have an auto-generated `~/.ssh/config` with a pretty good variety of hosts defined. Sometimes the `Host` alias is useful, and sometimes the `HostName` contains what I'm looking for. For a toy example, with the following in `~/.ssh/config`:

```
Host t-bar2
    HostName b.foo.tst
Host p-bar1
    HostName a.foo.prd
```

I'd like to be able to type `ssh **<tab>` (fzf prompt) then either `p-` or `prd` to show production `Hosts` and `HostName`s, respectively.

This is what I've done locally in my `~/.zshrc`, and I can submit a PR with these changes if that looks like something you'd be willing to accept:

```
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
# copied & modified from
# https://github.com/junegunn/fzf/blob/b911af200c4ed4085a76d3e0a12458ccba2d3b3f/shell/completion.zsh#L115
_fzf_complete_ssh() {
  _fzf_complete '+m' "$@" < <(
    setopt localoptions nonomatch
    command cat <(cat ~/.ssh/config ~/.ssh/config.d/* /etc/ssh/ssh_config 2> /dev/null | command grep -i '^\s*host\(name\)\? ' | command grep -v '[*?]' | awk '{for (i = 2; i <= NF; i++) print $1 " " $i}') \
        <(command grep -oE '^[[a-z0-9.,:-]+' ~/.ssh/known_hosts | tr ',' '\n' | tr -d '[' | awk '{ print $1 " " $1 }') \
        <(command grep -v '^\s*\(#\|$\)' /etc/hosts | command grep -Fv '0.0.0.0') |
        awk '{if (length($2) > 0) {print $2}}' | sort -u
  )
}
```

Here's a simplified diff showing the change I made to the line starting with `command cat`:

```
- command grep -i '^host '
+ command grep -i '^\s*host\(name\)\? '
```

**Comment by junegunn** [comment]
Thanks. The patch looks good to me. Can you open a pull request? Please make sure to change both bash and zsh script.
