### ISSUE TITLE
Make header message dynamic

### ISSUE THREAD

**Issue by stephencheng** [junegunn/fzf#1786]
This is generic request to make the header message dynamic

The use case would be in the execute code, I want to use a env var as switch to do things. For example, if I bind a key ctrl-s to switch on/off, I use env var switched_on, when I type ctrl-s, switched_on=on, and I am expecting the the rendering in the header message showing it to be on, when I use bind key ctrl-s again, it will become off, then the header message goes to off

Can this be implemented?

Thanks

**Comment by junegunn** [comment]
Please properly fill in the issue template.

**Comment by stephencheng** [comment]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

This is generic request to make the header message dynamic
The use case would be in the execute code, I want to use a env var as switch to do things. For example, if I bind a key ctrl-s to switch on/off, I use env var switched_on, when I type ctrl-s, switched_on=on, and I am expecting the the rendering in the header message showing it to be on, when I use bind key ctrl-s again, it will become off, then the header message goes to off

Can this be implemented?

**Comment by junegunn** [comment]
I'm not quite sure what you're trying to achieve here. Can you post the actual code you tried to run?

Anyway, the latest version of fzf can reload the input with an arbitrary command, so you can use `--header-lines` option to dynamically change the header.

```sh
(echo 'header 1'; seq 10) | fzf --header-lines=1 --bind 'ctrl-a:reload:echo header 2; seq 20' --bind 'ctrl-b:reload:echo header 3; seq 30'
```

**Comment by aclist** [comment]
I have essentially the same request, but the nature of my use case is different.

I would like to dynamically pass the value of the currently selected `{}` or some other field index expression to a function that performs some arbitrary action or transforms the input, and return the result to the header. 

This should be done without manually invoking some keybinding to reload. I tried doubling up movement bindings to reload the view, but this is a mess, and it crucially doesn't work on the first item when you start.

It would have the same syntax as preview: `header="myfunc {} args"`

This would be useful in cases where the preview window is already being used for other content and the header itself provides some additional context or value based on which item is currently highlighted. It's also particularly useful for menus, where the header could provide context about what the selected option does.
