### ISSUE TITLE
deselect-all does not deselect all items.

### ISSUE THREAD

**Issue by lemnos** [junegunn/fzf#1787]
- [X] I have read through the manual page (`man fzf`)
- [X] I have the latest version of fzf
- [X] I have searched through the existing issues

## Info

- OS
    - [X] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [X] bash
    - [ ] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

I'm not sure whether or not this is a bug or a feature but deselect-all only deselects items in the current filter list. If this is indeed by design, how would one go about automatically selecting all filtered items in multi mode? Ideally I want something like this

`fzf --bind 'change:deselect-everything+select-all'`

where deselect-everything deselects all items (not just the currently filtered ones) so that as I progressively type I can build a filter. This seems like a natural use case for what is a fantastic and well designed tool.

**Comment by junegunn** [comment]
Please properly fill in the issue template.

**Comment by lemnos** [comment]
Updated

**Comment by junegunn** [comment]
It's a feature, discussed in #1364.

I'm not against adding a separate action for that purpose, but I can't think of a good name. `clear-selection` maybe?

**Comment by lemnos** [comment]
Hah, looks like someone else made exactly the opposite assumption about how it should work and so the bug -> feature -> bug cycle continues ;). `clear-selection` sounds like a reasonable name considering that you don't want to break backwards compatibility (again). Alternatively (or additionally) it might be useful to add `select-matches` which exclusively selects the filtered items (my current use case) since it seems like something that might done quite often.
