### ISSUE TITLE
Feature Request: More event types.

### ISSUE THREAD

**Issue by lemnos** [junegunn/fzf#1789]
- [X] I have read through the manual page (`man fzf`)
- [X] I have the latest version of fzf
- [X] I have searched through the existing issues

## Info

- OS
    - [X] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [X] bash
    - [ ] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

Thanks for adding clear-selection, you work remarkably fast! Unfortunately
there are still a few problems using it in the way I intended (there may be an
alternative to achieve this, but I think the features I proposed below are
sufficiently generic and useful to warrant consideration).

The reload event executes after the query has been updated, however it is often
useful to run an action *after* the input has been updated. Consider the
construction of a simple filter (using the recently added clear-selection
command).

`fzf -m --bind 'change:reload:clear-selection+select-all'`

The problem of course is that the command will select all entries matched by
the *last* query rather than the current one. Adding a 'post-reload' event
would seem like a natural solution. Additionally there should be a way to begin
this process at the start of the command (before any input is entered) which
may lend itself to a 'start' event and/or an 'update' event.

**Comment by junegunn** [comment]
- The example command is invalid. `reload` requires a command template. I guess that was just a mistake.
- `reload` automatically clears the previous selection, there's no reason to trigger `clear-selection` right after it.
- For now, I'm against the idea of adding an event that is not directly triggered by the user. fzf consumes input asynchronously, which means it may take some time for a `reload` to finish, during which the UI is not blocked and the user cannot predict when exactly the "post-reload" event will happen. It can be triggered when the user hasn't finished typing in a search term. In that case, triggering `select-all` 
(or any other action) automatically isn't really desirable.
    ```sh
    # reload will take a considerable amount of time and we don't know when it will finish
    fzf --bind 'ctrl-r:reload:find /' --bind 'post-reload:select-all'
    ```
- Also, I'm not sure why one would want to automatically `select-all` after the consumption. What would be the use case?

**Comment by rvaiya** [comment]
- Sorry, you're right, the reload was a mistake. I meant simply `fzf --bind 'change:clear-selection+select-all`.

- Instead of a 'post-reload' event I think an 'update' event which triggers each time the current list of filtered items is updated (including when the user enters something) would be useful. This would allow the user to automatically select all items which match a specific query without having to press an additional key. In addition to automatically accommodating incoming list elements this would be useful for small lists which load almost instantaneously. 

E.G

Suppose I wanted to list all files which do not match a specific query (but I want to dynamically construct the query, hence the use of fzf). I could then do something like

```
ls | fzf -m --bind 'update: clear-selection+select-all' > tee filtered_file_list.txt
``` 

As I typed my query all of the items in the list would automatically be selected. I just realized that in this case I could simply rebind enter to select all of the elements before exiting, but a variant of this problem in which I want to manually deselect items (rather than explicitly select them) would require an extra keystroke. I can't think of any other use cases at the moment, so I'm not sure how generically useful it would be. Maybe a flag which inverts the selection algorithm (all selected items are excluded while the others are printed) would make sense, or else simply an action to invert the current selection. The main use case being to use fzf as a filter for lists (which it seems naturally suited for).

**Comment by lemnos** [comment]
- Sorry, you're right, the reload was a mistake. I meant simply `fzf --bind 'change:clear-selection+select-all`.

- Instead of a 'post-reload' event I think an 'update' event which triggers each time the current list of filtered items is updated (including when the user enters something) would be useful. This would allow the user to automatically select all items which match a specific query without having to press an additional key. In addition to automatically accommodating incoming list elements this would be useful for small lists which load almost instantaneously. 

E.G

Suppose I wanted to list all files which do not match a specific query (but I want to dynamically construct the query, hence the use of fzf). I could then do something like

```
ls | fzf -m --bind 'update: clear-selection+select-all' > tee filtered_file_list.txt
``` 

As I typed my query all of the items in the list would automatically be selected. 

I just realized that in this case I could simply rebind enter to select all of the elements before exiting, but a variant of this problem in which I want to manually deselect items (rather than explicitly select them) would require an extra keystroke.

I can't think of any other use cases at the moment, so I'm not sure how generically useful it would be. Maybe a flag which inverts the selection algorithm (all selected items are excluded while the others are printed) would make sense, or else simply an action to invert the current selection. The main use case being to use fzf as a filter for lists (which it seems naturally suited for).

**Comment by junegunn** [comment]
I see, but it sounds like a very niche use case. And it can be covered by using `toggle-all`.

```sh
fzf --multi --bind 'change:clear-selection+top,enter:toggle-all+accept' \
    --header 'Mark items to exclude'
```

**Comment by lemnos** [comment]
Good point. No other use cases immediately come to mind and I should have realized that I can achieve what I want using the existing actions. Thanks again for writing this fantastic program, it's exactly what I imagined before I discovered it (and executed far better than I could have done it).

**Comment by junegunn** [comment]
Thanks, I'm going to close this until we see more use cases where this is neccessary.

**Comment by korjjj** [comment]
Hi.
How about adding an event for something like SIGUSR1, so it could be triggered by other applications?

**Comment by rvaiya** [comment]
Can you provide an example use case? I can't think of an instance when I
would want to do something in fzf because something happened in an external
program.

**Comment by lemnos** [comment]
Can you provide an example use case? I can't think of an instance when I
would want to do something in fzf because something happened in an external
program.

**Comment by korjjj** [comment]
I was thinking about using it as a dashboard,
so it could be reloaded by something like cron
or an application that did update to files piped into fzf.
It probably could be useful with more dynamic kind of stuff.

**Comment by lemnos** [comment]
```
I was thinking about using it as a dashboard,
so it could be reloaded by something like cron
```

fzf isn't really designed for that sort of thing, you're better off writing a domain specific terminal application if you need something like that.

```
or an application that did update to files piped into fzf.
```

I'm not sure what you mean by that. fzf already dynamically updates based on incoming input. If you want something which is contingent on the search query you can already use the `change` event as illustrated above.

**Comment by korjjj** [comment]
> I'm not sure what you mean by that.
Well, for example i've got temporary files with data from several sources.
I could pipe them through a parser or whatever and into fzf.
So after external script (application) updates those tmp files it could send a signal for fzf to reload.

> fzf isn't really designed for that sort of thing
Ok. I still think it'd allow new uses for fzf.

**Comment by lemnos** [comment]
```
Well, for example i've got temporary files with data from several sources.
I could pipe them through a parser or whatever and into fzf.
So after external script (application) updates those tmp files it could send a signal for fzf to reload.
```

There isn't enough detail (perhaps you can provide a specific example) but I can't understand why you can't just use a normal shell script for this.
```
Ok. I still think it'd allow new uses for fzf.
```

My point was that fzf is designed as a 'selection/filtering' program not a continuously updated 'dashboard'. If you need something like the latter it can either fairly trivially be written as a shell script (using watch and the like) or else is complex enough to necessitate some custom code (which offers more flexibility anyway). The circumstance you describe in which you need the input elements to be continuously updated and simultaneously filterable seems to be a fairly uncommon one. You can fairly trivially write something that monitors a command or file and continually displays the output and then pipe that to fzf when you need to interact with it. If you provide a concrete example which has a broad enough use case it might make sense.

**Comment by korjjj** [comment]
> There isn't enough detail (perhaps you can provide a specific example)

Oh, sorry, I see that it was not clear what it has to do with fzf.
The point was to be able to search through relatively dynamical data,
to call external applications on the result of a query or part of it,
and to watch for change in amount of records fitting the selection.

> I can't understand why you can't just use a normal shell script for this.

I was writing a simple shell script and fzf was fitting nicely in it. Well, almost.
Anyway it probably should be done in something other than shell,
but everything looks like a shell script for me for some reason.

**Comment by lemnos** [comment]
```
to call external applications on the result of a query or part of it,
```
You can already do this.

```
and to watch for change in amount of records fitting the selection.
```

This is the thing whose utility I question. Usually you want to watch the same query and if not it's easy enough to restart the script. If you want to dynamically filter something interactively then fzf makes sense, otherwise it doesn't seem to.

I think your case could be greatly served if you provide some sample code (e.g a simple pipeline or small script) in which you use the feature you want and explain why it is necessary in that case.

**Comment by korjjj** [comment]
> I think your case could be greatly served if you provide some sample code

The related part is really oneliner of no particular interest.
Just to elaborate on what i've been trying to do - a monitoring dashboard.

I've got several scripts that get data from several different endpoints in different formats, parse them and save as structurally similar jsons. It is rarely done faster than once a minute.

jsons are piped through jq to pick only the stuff I need (hostname, event, timestamp, source).
It is then passed through 'sort' and 'column' (and sed, but thats only for colors rn) to fzf.

The result is something like that:
![image](https://user-images.githubusercontent.com/7048/71492903-dc2fcd80-284b-11ea-9a7e-f6f54c5c3678.png)

I can now search by hostname and event, curl "acknowledged" to a source of a selected event, ssh to a host probably, check everything that is related to a host or check hosts with similar issues.
I thought that it'd be nice for this all to periodically refresh by the scripts that deliver and parse jsons instead of me pressing a button, so I came to github and wrote several somewhat lengthy comments.

**Comment by lemnos** [comment]
If this pulls from multiple APIs I would probably rewrite it in python rather than relying on fzf, jq (which is awesome for explotation), and shoe string ;). Otherwise I would just use 'watch/grep' and have a script that spins up fzf if I was to select one of them. 

If the host filter is going to change that frequently (so frequently that you can be bothered to employ an extra 3 keystrokes to rerun your filter script) then I can see why it would be useful, however I can't imagine a real world use case in which I need something that interactive which is also polling data at a non-human rate.  It's worth noting that if your process is refreshing data while you are interacting with the menu then it can potentially cause operator race conditions in which the item you select is swapped out from under you right before you select/do something with it.

Having said all of that, implementing it seems trivial enough and doesn't seem like it would break anything (though I am not that familiar with the codebase). Ultimately @junegunn will have to decide.

**Comment by korjjj** [comment]
Hehe, I see how it could be done using another unimplemented feature - making fzf reload on inactivity timeout: https://github.com/junegunn/fzf/issues/1211

**Comment by lemnos** [comment]
Yeah, this

**Comment by lemnos** [comment]
Yeah, that starts to feel a bit like feature creep. You should really have a separate program for monitoring and filtering (fzf). The sort of thing you

**Comment by lemnos** [comment]
Yeah, that starts to feel a bit like feature creep (imo). You should really have a separate program for monitoring and filtering (fzf). The sort of thing you don't want your filtering tool to do is to swap data out from under you while it's hot (which is why externally driven events dont make sense). If you want to monitor interesting changes in data use a dedicated tool for the job and then have it interact with your selector. From everything you have described the sort of thing you want can be achieved using a small script of which fzf only serves as the filter (which it is what it was designed for). 

E.G

```
#!/bin/sh

trap "" INT

pid=$$
filter=""

input_file="/tmp/dummy.test"

while true; do
    watch 'cat '"$input_file"'|grep "'"$filter"'"'
    filter="$(fzf --print-query --bind 'q:execute(kill $pid)' < "$input_file")"
    test $? -eq 130 && exit
    filter=`echo $filter|head -1`
done
``` 

You could of course use a fancier watcher (which also suits your needs better) but that seems to be the essence of the problem.
