### ISSUE TITLE
Giving preference to exact matches, no matter which mode

### ISSUE THREAD

**Issue by edi9999** [junegunn/fzf#179]
When I use the Ctrl-R keyboard shortcut, and search for `ssh`, I get the following results:

    ssh site@site
    ssh site@site
    git remote add origin ssh://blabla
    gs  source /usr/local/lib/python2.7/dist-packages/powerline/bindings/tmux/powerline.conf
    source ~/.zshrc

the order of the results is not optimal, because `ssh site@site` is probably what I want.

Is they anyway to get exact matches first ?

I know exact match exists, but what I would like to have is something that would intelligently get exact matches first, and then the fuzzy matches.

I think they are two ways to implement this:

  1. Make exact matches come up first

  2. Prioritize the matches that have the lowest number of chunks. If they is equality, prioritize according to the shortest match.

Also: Is they a keyboard shortcut to switch from normal mode to exact-match mode from within fzf ?

**Comment by junegunn** [comment]
As mentioned in the [README page](https://github.com/junegunn/fzf#key-bindings-for-command-line), sorting is disabled by default for CTRL-R because chronological ordering is relevant for command history. You can toggle sorting by pressing CTRL-R again and you'll notice that exact/closer matches appear first.

**Comment by Ram-Z** [comment]
You can also edit the `fzf-history-widget()` in `~/.fzf.zsh` and add `-x` to the fzf command. Now you can search for exact matches by prepending your search string with `'` (f.ex. `'ssh`).

Also have a look at the discussion in #178.

**Comment by junegunn** [comment]
> You can also edit the fzf-history-widget() in ~/.fzf.zsh and add -x to the fzf command.

I suggest setting up `$FZF_DEFAULT_OPTS` (e.g. `export FZF_DEFAULT_OPTS='-x'`) instead of editing the source directly.

@Ram-Z Please note that the latest `install` script no longer generates `~/.fzf.{zsh,bash}` with full definitions. Those files now simply load files in `~/.fzf/shell/`.

**Comment by edi9999** [comment]
I found https://github.com/junegunn/fzf/issues/111 which already gave me the idea of using `export FZF_DEFAULT_OPTS='-x'`

I've used it since yesterday and it seems a good solution. 

Out of curiosity, what other config do you use @junegunn on your machine ?

**Comment by junegunn** [comment]
You can check out my dotfiles repo on github. I'm still experimenting with stuff, and I recently managed to integrate Chrome browsing history and bookmarks with fzf.

Anyway, I believe I answered your initial question with 1. quoting in extended-search mode 2. and the recent addition of `--toggle-sort=ctrl-r` (see #173). I'm closing this. Thanks.
