### ISSUE TITLE
Cannot apply styling expression such as '[1' and '[0'

### ISSUE THREAD

**Issue by rlaqltmxm** [junegunn/fzf#1790]
- [ ] I have read through the manual page (`man fzf`)
- [ ] I have the latest version of fzf
- [ ] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [0] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [0] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

Not I'm using fzf in my shell script application, and found some bug or unsupported syntax like below 

`echo "\033[1mID\tContents\t\tDate\033[0m`

<img width="368" alt="스크린샷 2019-12-12 오전 11 07 13" src="https://user-images.githubusercontent.com/44524767/70676464-9a414c00-1ccf-11ea-98f8-9524080d55eb.png">

Is this intended to not be supported?

**Comment by junegunn** [comment]
You need to use `--ansi` option.
