### ISSUE TITLE
delimiter appended to the selected field

### ISSUE THREAD

**Issue by antoniy** [junegunn/fzf#1792]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

I'm trying to use fzf to pick a key from a configuration file which has this layout:
```
some key 1:some value 1
some key 2:some value 2
```

Here is reproducible example:
```shell
echo "some key 1:some value 1\nsome key 2:some value 2\nsome key 3:some value 3" | fzf -d ':' --with-nth=1
```

What I expect is to have a list of my keys without delimiter:
```
some key 1
some key 2
```

I actually got a list including the specified delimiter:
```
some key 1:
some key 2:
```

Is there a way to achieve that goal? Some mapping function that I can pass to reformat the presentation of each key maybe?

Thank you.

**Comment by junegunn** [comment]
That's how it's designed to work. It makes sense in cases where you need to manipulate the input with a series of field indexes.

```sh
echo -e "some key 1:some value 1\nsome key 2:some value 2\nsome key 3:some value 3" | fzf -d ':' --with-nth=1,1,1,2
```

```sh
fzf --reverse -d '\|' --with-nth 1,3,2 <<'_'
| Distro       | Command                    |
| ---          | ---                        |
| Alpine Linux | `sudo apk add fzf`         |
| Arch Linux   | `sudo pacman -S fzf`       |
| Debian       | `sudo apt-get install fzf` |
| Fedora       | `sudo dnf install fzf`     |
| FreeBSD      | `pkg install fzf`          |
| NixOS        | `nix-env -iA nixpkgs.fzf`  |
| openSUSE     | `sudo zypper install fzf`  |
_
```

A workaround is to replace the delimiter to a whitespace character (tab, space, non-breaking space (`\u00a0`), etc) since fzf trims trailing whitespaces since 0.19.0.

```sh
echo -e "some key 1:some value 1\nsome key 2:some value 2\nsome key 3:some value 3" | tr ':' '\t' | fzf -d '\t' --with-nth=1
```
