### ISSUE TITLE
Completion for `unset` not working

### ISSUE THREAD

**Issue by gene-pavlovsky** [junegunn/fzf#1795]
Using fzf 0.19.0, installed on macOS Catalina via homebrew.
The completion for the `unset` shell built-in is not working.
unset<TAB><TAB> shows the list of files in the current directory.
unset HIST<TAB> doesn't do anything.

Commenting out fzf in ~/.bashrc and bash's built-in unset completion works correctly (completes environment variables).

**Comment by gene-pavlovsky** [comment]
Hi, I have installed 0.20.0 via brew, however the issue is still present.

**Comment by junegunn** [comment]
0.20.0 was released days ago.

**Comment by gene-pavlovsky** [comment]
I didn't quite understand the meaning of your reply.
It was released days ago, but it was indeed available very quickly on homebrew.
I checked once again and yes, I have fzf 0.20.0 installed. I reinstalled it once again, for good measure.
However, unset doesn't complete environment variables for me, unalias doesn't complete aliases.
On the other hand, typing "export HOM" and pressing TAB completes to "HOME=".

My bashrc includes:
```
[ -f ~/.fzf.bash ] && . ~/.fzf.bash
[ -f ~/.fzf.extras ] && . ~/.fzf.extras
```

~/.fzf.bash:
```
# Setup fzf
# ---------
if [[ ! "$PATH" == */usr/local/opt/fzf/bin* ]]; then
  export PATH="${PATH:+${PATH}:}/usr/local/opt/fzf/bin"
fi

# Auto-completion
# ---------------
[[ $- == *i* ]] && source "/usr/local/opt/fzf/shell/completion.bash" 2> /dev/null

# Key bindings
# ------------
source "/usr/local/opt/fzf/shell/key-bindings.bash"
```

~/.fzf.extras
```
export FZF_DEFAULT_COMMAND='fd --type f --hidden --follow --exclude .git'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"

complete -F _fzf_path_completion -o default -o bashdefault ag
complete -F _fzf_dir_completion -o default -o bashdefault tree
```

/usr/local/opt/fzf -> ../Cellar/fzf/0.20.0/

**Comment by junegunn** [comment]
0.20.0 was released a few days before I fixed it and left the comment. It does not include the fix. Try installing HEAD version: `brew install fzf --HEAD`

**Comment by gene-pavlovsky** [comment]
Ok, I understand now, thanks for clearing it up.
Installing HEAD indeed fixed the issue.
Thanks!

**Comment by norioxkimura** [comment]
Reproducing this bug in version 0.48.0 using Bash.

It appears that the function `__fzf_orig_completion()` only handles `complete -F`, but not `complete -a` for `unalias` or `complete -v` for `unset`.

I am using Ubuntu 22.04 with the bash-completion package version 2.11.
