### ISSUE TITLE
Abort on <BS> if prompt is empty

### ISSUE THREAD

**Issue by mitinarseny** [junegunn/fzf#1797]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish
    
## Feature Request
It would be really convenient to add functionality to abort FZF if current search line is empty and backspace is pressed. Howerver, it should not abort if backspace was held to actually delete characters as it would be hard to unpress arrow button right before it reaches the start of line to avoid accidental exiting. Is it possible to implement?

**Comment by junegunn** [comment]
Please fill in the issue template.

**Comment by LuRsT** [comment]
@mitinarseny, could you edit your Issue description using the template please?

Here is the template: https://raw.githubusercontent.com/junegunn/fzf/master/.github/ISSUE_TEMPLATE.md
