### ISSUE TITLE
Toggle phony mode

### ISSUE THREAD

**Issue by petobens** [junegunn/fzf#1798]
- [X] I have read through the manual page (`man fzf`)
- [X] I have the latest version of fzf
- [X] I have searched through the existing issues

## Info

- OS
    - [X] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [X] bash
    - [ ] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

Hi! I was wondering if it possible to add (if it doesn't exist already) and option/action to toggle phony mode (i.e to toggle between the selector and the search interface). My use case is that I'm using the new phony switch along with the reload action to do some "interactive" grepping however once I have written a specific grep pattern I would like to filter the results using the fuzzy search interface. Thanks in advance

**Comment by junegunn** [comment]
Please fill in the issue template.

**Comment by petobens** [comment]
Filled. Sorry for ignoring it in the first place.

**Comment by junegunn** [comment]
I can easily add `toggle-phony` action, but I doubt that it's gonna be useful to you because you're probably using `change:reload` binding. So even if you disable `--phony`, subsequent `change` events will still trigger `reload` with the updated query.

So for it to be truly useful, fzf should provide a way to "unbind" or "rebind" existing bindings. But no, that's too much for just a niche use case.

I can think of two alternatives:
- Use `--expect` and `--print-query` options to restart fzf on a certain keypress; with no `--phony` and `change` binding.
- Instead of binding `reload` to `change`, bind it to a special key. For me, this actually makes more sense than making fzf a dumb selector.

```sh
# CTRL-R to restart ripgrep
RG() {
  RG_PREFIX="rg --column --line-number --no-heading --color=always --smart-case "
  INITIAL_QUERY="$1"
  local selected=$(
    FZF_DEFAULT_COMMAND="$RG_PREFIX '$INITIAL_QUERY' || true" \
      fzf --bind "ctrl-r:reload:$RG_PREFIX {q} || true" \
          --ansi --query "$INITIAL_QUERY" \
          --preview "~/.vim/plugged/fzf.vim/bin/preview.sh {}"
  )
  [ -n "$selected" ] && $EDITOR "$selected"
}
```

Both options are not ideal I guess, but you should understand that fzf wasn't really designed for this type of work anyway.

**Comment by petobens** [comment]
Thanks for the thorough explanation. I thought that since you eventually decided to do include this new selection interface (different from the fuzzy finder one) you might also be willing to include an easy way of switching between them. I understand however your reasons no to do so. Feel free to close if you deem fit (and happy christmas).

**Comment by LuRsT** [comment]
Could you close this @junegunn? Or are you planning on implementing this?

**Comment by petobens** [comment]
> Hi! I was wondering if it possible to add (if it doesn't exist already) and option/action to toggle phony mode (i.e to toggle between the selector and the search interface). My use case is that I'm using the new phony switch along with the reload action to do some "interactive" grepping however once I have written a specific grep pattern I would like to filter the results using the fuzzy search interface. Thanks in advance

Hi @junegunn! Is this now possible after your changes in https://github.com/junegunn/fzf/commit/d779ff7e6dcf068fbcf743bed45127c3b857ec92 ? (I tried a few things but cannot get quite to work; I thought it might be possibel to the do the two step filtering now but I'm probably misunderstading the changes). Thanks in advance

**Comment by rayiik** [comment]
Hey yes this should be possible both however the reload feature only changes the command being filtered into fzf if you want to change the fzf command itself you'd use the --sync flag. However I wrote this one up for your use case and it works for me so let me know if it works for you.
   
```bash
fd -uu -t f -d 3 | fzf --preview='cat {}' --bind='alt-q:toggle-search+unix-line-discard' \
--bind="ctrl-alt-r:select-all+reload:rg {q} <{+} --files-with-matches"
```
   
This can be modified for your case use as you may want to keep your query field when you go back to interactive filtering so you may want to remove the unix-line-discard. and if your using grep not ripgrep you should download ripgrep, or just use grep :). This works if the search field is producing files, if its producing commands the <{+} will need to be replaced with <({+}) or <<<"$(echo {+})". but basically the contents of file are redirected to ripgrep/grep with the search parameter of your query. now really fun if we know we want regular expressions this also works adding the -e flag to the rg -e {q} this must be added outside of the placeholder call, as all placeholders come out single quoted which disassociates the flag from the commands its meant to modify (haven't found a way around this yet) however doenst seem to generally be an issue and i tend to use the -e flag as is and just keep it in mind that its searching by regular expression. if you need to search a fixed string you can always either create a secondary binding or at the start of your query lead with a  -- search (double dash space signals the end of flags for the previous command)

**Comment by rayiik** [comment]
Just to build on that a little more this is also a fun case use. 
```bash
fd -uu . "${1:-'.'}" -t "${2:-'f'}" -d "${3:-'1'}" |  \
fzf --bind='alt-q:toggle-search+replace-query' \
--bind='ctrl-alt-q:toggle-search+clear-query' \
--bind='ctrl-alt-a:toggle-search' \
--bind='alt-e:execute:{q} {}' \
--bind='ctrl-alt-e:select-all+reload:{q} <{+}'
```
this lets us build the command that we are going to run against the selected list (default everything thats left before execution) you can either remove the select-all to manually select that you want (in my case i generally have select all already bound but once you toggle the search you can you can either include the selected line discard your search filter or just toggle searching in general then you type the command you want to be run and execute it against the entire list which gets thrown back into fzf.

**Comment by petobens** [comment]
Hi @rayiik thanks for the help and examples! AFAICT I have to either i) avoid using change on reload to be able to use the toggle search thing ii) use change on reload but then the search toggling doesn't work (since everything is still updated on a keypress) .
This is basically what @junegunn  said in his original comment which I guess still stands:

> I can easily add toggle-phony action, but I doubt that it's gonna be useful to you because you're probably using change:reload binding. So even if you disable --phony, subsequent change events will still trigger reload with the updated query.

So my use case is still elusive even with the last changes that allow to toggle search action.

**Comment by rayiik** [comment]
Yes but just a though have you considered using doubling your output to both fzf and preview  binding change to refresh preview then when you have the expression you looking for using the sync flag?

**Comment by petobens** [comment]
I don't think I follow. Can you show an example?

**Comment by rayiik** [comment]
Hey sorry been pulling 16 hour days these last two weeks im bagged but this is an example of what im talking about but its in no way completed (just to tired to draw the last few lines right now) but the concept is that you through your list into an array then you send the list to fzf and the preview so your working on identical lists  the refresh-preview flag replaces the change-reload, haveing the two identical data streams means you get both the interactive query grepping with out messing with your main search field then when you have the results narrowed down and to closer to you what you want youll either want ot use reload or pipe to fzf with the --sync flag. ive only found really two ways to redirect && reload backwards up the pipe and they're hit and miss depending on the command one is to have a more or less variable function (where the command it self is not determined)  which is escaped when set so its set when called 
   
   var1="\$(var2)" or to pipe it to a file and the source the file. Hopefully that gives you some stuff to work give you some ideals you can always check out my https://github.com/rayiik/Man-fzf-ide-resource ive relocated all my dot files to be called from downloading it to ~/project and adding source "$HOME"/project/Man-fzf-scripts/config-files/sourcefile to my /etc/bash.bashrc but that repo is more or less a testing ground as ive built most of my learning in bash around fzf so hopefully you can find some inspiration (or at least some useful scripts to take :))". as a side note. the estrip is there to remove control characters from output as i use colors in my terminal including my text output it sometimes garbles scripts so i wrote that function to strip the control characters for reusable output.
```bash
#!/bin/bash
estrip () {
sed 's/\x1b\[[0-9;]*m//g'
sed 's/\x1b\[[0-9;]*[mGKHF]//g'
sed 's/\x1b\[[0-9;]*[mGKF]//g'
sed 's/\x1b\[[0-9;]*[a-zA-Z]//g'
}
var=( "$(fd -uu -t f -d 1 . | estrip)" )
while read line;
do
var2+="$line"
done <<<"$(var[@]}"
echo "${var[@]}" | fzf --preview= "echo ${var[@]} | rg {q}" --bind='change:refresh-preview' \
--bind='ctrl-p:preview: cat {}' --bind="alt-r:reload:var2=( $(cat <<<${var1[@]} )|
```
