### ISSUE TITLE
keys bindings for F1, F2, F3, F4 not working on the urxvt-unicode terminal

### ISSUE THREAD

**Issue by notevenodd** [junegunn/fzf#1799]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish
    
## Problem

When passed to --expect or in --bind, fzf doesn't recognize functions keys F1, F2, F3, F4 being pressed when using the [rxvt-unicode terminal](https://wiki.archlinux.org/index.php/Rxvt-unicode).

## Steps to reproduce
do the following on rxvt-unicode terminal: `: | fzf --prompt 'press F1,F2,F3, or F4 ' --expect F1,F2,F3,F4`

## Possible Cause

Having a quick look at the terminfo database, i see that xterm and most terminals have the following capabilities encoded as:
kf1 => \eOP
kf2 => \eOQ
kf3 => \eOR
kf4 => \eOS
kfN (N>5) => \e[1XX~ where XX is a number

However rxvt uses:
kf1 => \e[11~
kf2 => \e[12~
kf3 => \e[13~
kf4 => \e[14~
kfN (N>5) => same code as xterm

## Workaround

Using fzf inside tmux works on rxvt-unicode (but this is hardly a valid workaround)

**Comment by junegunn** [comment]
```diff
diff --git a/src/tui/light.go b/src/tui/light.go
index 5c4fadf..c32a1ba 100644
--- a/src/tui/light.go
+++ b/src/tui/light.go
@@ -486,10 +486,18 @@ func (r *LightRenderer) escSequence(sz *int) Event {
 				switch r.buffer[3] {
 				case 126:
 					return Event{Home, 0, nil}
-				case 53, 55, 56, 57:
+				case 49, 50, 51, 52, 53, 55, 56, 57:
 					if len(r.buffer) == 5 && r.buffer[4] == 126 {
 						*sz = 5
 						switch r.buffer[3] {
+						case 49:
+							return Event{F1, 0, nil}
+						case 50:
+							return Event{F2, 0, nil}
+						case 51:
+							return Event{F3, 0, nil}
+						case 52:
+							return Event{F4, 0, nil}
 						case 53:
 							return Event{F5, 0, nil}
 						case 55:
```

Does this patch fix the problem?

**Comment by junegunn** [comment]
Fixed on master, thanks for the report.
