### ISSUE TITLE
execute with current input if no available matches

### ISSUE THREAD

**Issue by amosbird** [junegunn/fzf#1800]
- [X] I have read through the manual page (`man fzf`)
- [X] I have the latest version of fzf
- [X] I have searched through the existing issues

## Info

- OS
    - [X] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [X] bash
    - [ ] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

1. `printf 'foo\nbar' | fzf --bind 'enter:execute(echo {})'`

2. typing `test`

3. press `enter`

expect `test` being echoed

actual the execute action isn't executed at all.

Can we have an execute variant that runs no matter if there is a selected candidate?

**Comment by junegunn** [comment]
If the command template contains `{q}`, the action will trigger even when `{}` is null.

```sh
printf 'foo\nbar' | fzf --bind 'enter:execute(echo {}/{q}; sleep 1)'
```

**Comment by rdunlapSP** [comment]
Sorry for the necro, but is there a way to automatically exit with 0 status in this situation? I've tried the `-0` flag, and also 
```bash
$ printf 'foo\nbar' | fzf --bind 'enter:execute(echo {}/{q}; exit 0)'
```

**Comment by junegunn** [comment]
You can use `--print-query` and process the output using shell script.
