### ISSUE TITLE
Unicode characters in file names are shown as question marks.

### ISSUE THREAD

**Issue by Konstantin-Glukhov** [junegunn/fzf#1801]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [ ] Mac OS X
    - [x] Windows 10
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [ ] fish
    - [x] cmd.exe
## Problem / Steps to reproduce
Unicode (specifically Chinese) characters in file names are shown as question marks. The fonts tested: "NSimSun", "MS Gothic", "MS Mincho". Windows command "dir" shows file names correctly.

**Comment by janlazo** [comment]
Does this happen on any Windows environment or with codepages, language settings only? Is fzf invoked directly on cmd.exe or indirectly via another program?

**Comment by Konstantin-Glukhov** [comment]
This problem is reported only for cmd.exe with the standard code page 437 in US. If code page is set to 65001 (UTF-8), fzf works fine. There is a workaround to change code page via registry for each cmd.exe invocation, but this is not an ideal solution.

Here is my test (it is important to notice that echo displays characters correctly, it is the pipe that is affected):

```
cmd.exe
C:>chcp
437
C:>echo 世界
世界
C:>echo 世界 | fzf
??
```

**Comment by janlazo** [comment]
Does it happen on powershell with codepage 437 or other codepages?

**Comment by Konstantin-Glukhov** [comment]
With PowerShell it is even worse, it does not work with 65001 (UTF8)

**Comment by janlazo** [comment]
Using [unicode/utf16](https://golang.org/pkg/unicode/utf16/) on Windows instead of [unicode/utf8](https://golang.org/pkg/unicode/utf8/) should fix this issue.

**Comment by LuRsT** [comment]
@Konstantin-Glukhov, is this still an issue?

**Comment by Konstantin-Glukhov** [comment]
Switching Code Page to UTF-8 fixex the issue for both cmd.exe and Power Shell.

**Comment by janlazo** [comment]
@Konstantin-Glukhov That's a workaround, not a fix.

**Comment by Konstantin-Glukhov** [comment]
On Windows fzf relies on built-in dir output from cmd.exe. The only way to control the character set of cmd.exe pipe is via Code Page. Unless fzf introduces its own efficient file walker there is no way to fix it.

**Comment by ashthespy** [comment]
After running into some `??` today, came across this, but it doesn't seem to be helping here.
Am I missing something? Shouldn't this work?
```
~> $PSVersionTable.PSVersion

Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      19041  1023

~> chcp 65001
Active code page: 65001
~> echo 世界 | fzf
> ??                                               
```

**Comment by Konstantin-Glukhov** [comment]
Yes, UTF8 pipe does not work with PS 5.1

**Comment by owenstake** [comment]
> Switching Code Page to UTF-8 fixes the issue for both cmd.exe and Power Shell.

It works for me. I add `[Console]::OutputEncoding = [System.Text.Encoding]::utf8` in powershell.
