### ISSUE TITLE
Move fast causes flicker inside tmux or asciinema.

### ISSUE THREAD

**Issue by kevinhwang91** [junegunn/fzf#1805]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish
    
I found fzf causes a flicker when moving preview content continuously inside tmux (without tmux works perfect), and intend to record this issue by asciinema. 

Unfortunately, I using asciinema to record it outside tmux still cause this issue. 
Is it an issue of fzf performance?

Here is my record, the upload version compresses many details but still causes a slight flicker than the local version.
https://asciinema.org/a/291018

**Comment by junegunn** [comment]
The rendering part is not highly optimized, so some flickering is expected and is normal. But I don't think it's really bad. If you can improve the rendering performance, please let me know. Thanks.
