### ISSUE TITLE
Hide Preview File Length When Exceeding Buffer Size

### ISSUE THREAD

**Issue by iFallUpHill** [junegunn/fzf#1807]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

`fzf --preview 'bat -p --color=always {}'`

Is there a way to hide the number in the top right corner of the preview window? I find that it's distracting and doesn't really add value to my workflow.

![image](https://user-images.githubusercontent.com/8867997/71657192-d8e58780-2d0c-11ea-8649-e9edc486e4ab.png)

Thanks!

**Comment by junegunn** [comment]
No, there isn't, but I believe you can easily remove that part from the source code and build your own binary. Or, you could trim the preview content like so:

```sh
fzf --preview 'bat -p --color=always {} | head -$FZF_PREVIEW_LINES'
```

**Comment by iFallUpHill** [comment]
Second solution worked, thank you!
