### ISSUE TITLE
Feature Request: Ability visibly convert input to columns using a delimiter

### ISSUE THREAD

**Issue by SpicyLemon** [junegunn/fzf#1808]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

The problem I'm running into is that I often want a nice columnar display for selection. Currently, to get that, I run the input through the `column` command, then into fzf with `--delimiter='  +'`. I often also have a `--with-nth='...'` option to hide things like a url or id that doesn't help a user make a selection, but is needed for further processing. However the delimiter '  +' is less precise than the one used in the original input. This can cause problems both with displaying lines and parsing needed pieces out of the selected line(s).

It would be nice if I could skip the `column` command step and have fzf do the column conversion for display, then return the original selected line(s).

### Current functionality:
```bash
echo -e "a1111~a2~a3~a4\nb1~b222~b3~b4\nc1~c2~c3~c44\n" | fzf --with-nth='1,2,4' --delimiter='~'
```
will display:
```
c1~c2~c44
b1~b222~b4
a1111~a2~a4
```
And return the full selected line(s), e.g. `a1111~a2~a3~a4`

### Desired functionality:
What I'd like, though, is for the fzf selection screen to look like what this command produces:
```bash
echo -e "a1111~a2~a3~a4\nb1~b222~b3~b4\nc1~c2~c3~c44\n" | column -s '~' -t | fzf --with-nth='1,2,4' --delimiter='  +'
```
displays
```
c1     c2    c44
b1     b222  b4
a1111  a2    a4
```
But still return the original line `a1111~a2~a3~a4` when selected (instead of `a1111  a2    a3  a4` like the above command).

### Idea for solution:
Add a `--to-columns[=<column delimiter>]` flag/option.
* Presence of this flag/option will indicate that the provided input should be transformed to columnar format for display/selection.
* If no `<column delimiter>` is provided, the value provided by `--delimiter=..` will be used. 
* If neither `<column delimiter>` nor `--delimiter=...` is provided, the default will be used for both.
* If a `<column delimiter>` is provided, but a `--delimiter=...` is not, the `<column delimiter>` will also be used as the delimiter for the `--nth` and `--with-nth` options (if provided).
* If both `<column delimiter>` and `--delimiter=...` are defined, the `<column delimiter>` will only be used for identifying the columns to transform the input for display. The `--delimiter=...` value will still be used for the `--nth` and `--with-nth` options.

**Comment by junegunn** [comment]
Thanks for the suggestion, but I strongly believe this shouldn't be done by fzf. You can see my previous comment on the issue in #1076.
