### ISSUE TITLE
Using with vim

### ISSUE THREAD

**Issue by firedev** [junegunn/fzf#181]
Hi,

I tried to add fzf to vim via Vim Plug as described, but only `:FZF!` works. 

`:FZF` simply does nothing (I am using tmux), neither are [Open in splits](https://github.com/junegunn/fzf/wiki/Examples-(vim)#open-files-in-splits) mappings.

What am I doing wrong?

Also on a side note, I couldn't find a way to supply a list of ignored files and folders. Is there a way to ignore certain patterns? 

Thanks.

**Comment by junegunn** [comment]
Does `fzf-tmux` or `fzf` command work on your shell?

**Comment by junegunn** [comment]
> Also on a side note, I couldn't find a way to supply a list of ignored files and folders. Is there a way to ignore certain patterns?

fzf is a command line filter that can be used with anything, so it doesn't have the notion of ignored files and folders.

```
ps -ef | fzf
seq 1 100 | fzf
```

When the input is not specified (`fzf` w/o STDIN pipe), it will use `find` command as the default input. You can set `$FZF_DEFAULT_OPTS` environment variable to a command that lists the files as you like.

**Comment by firedev** [comment]
Yes both `fzf` and `fzf-tmux` work, and `:FZF!` works fine. I have copied the whole FZF part of (your config)[https://github.com/junegunn/dotfiles/blob/da378217ad008d422bc5b577802cad237a2930e1/vimrc#L1196-L1198] but no shortcuts do anything.

**Comment by firedev** [comment]
Hmm looks like they do work when not in tmux session. If that helps.

**Comment by junegunn** [comment]
Can you try `:call system('seq 100 | fzf-tmux')` in vim on tmux session. Does it open a tmux pane below?

By the way, "Open in splits" mappings in the wiki page is no longer needed. As `:FZF` can now do it with `CTRL-X/V/T`.

**Comment by firedev** [comment]
`:call system('seq 100 | fzf-tmux')` does nothing

**Comment by junegunn** [comment]
How about
- `:echo system('which fzf')`
- `:echo system('which fzf-tmux')`

**Comment by firedev** [comment]
Hmm... both not found.

**Comment by junegunn** [comment]
Okay, create a new tmux window (which will load ~/.bashrc or ~/.zshrc), open vim there and try again.

**Comment by firedev** [comment]
I have added '/Users/me/.fzf/bin' to '~/.zshenv', that made it work. I guess it is better to install FZF with Homebrew rather than vim plugin, is it?

**Comment by junegunn** [comment]
> I have added '/Users/me/.fzf/bin' to '~/.zshenv', that made it work

No don't do that. The install script will download fzf binary and inject code to your ~/.zshrc that extends your `$PATH`, so manual update of your env files is not required. The reason `:FZF!` worked and `:FZF` didn't is that `fzf-tmux` script expects `fzf` to be in `$PATH`, but it wasn't as the updated ~/.zshrc was loaded on the tmux window you're running vim. As I mentioned earlier, if you open another window, the shell will have `fzf` and `fzf-tmux` in $PATH. So vim started in the window should run without a problem. I know this can be confusing, so I'll push a commit that makes fzf-tmux try to use fzf binary in the same directory if it's not found in `$PATH`.

**Comment by junegunn** [comment]
> I guess it is better to install FZF with Homebrew rather than vim plugin, is it?

No, not necessarily. I use vim-plug to manage fzf.

**Comment by firedev** [comment]
I opened a new Terminal window, killed tmux server and everything. It just didn't work until I've changed `.zshenv`

**Comment by junegunn** [comment]
Do you see `[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh` in your .zshrc?

**Comment by junegunn** [comment]
You said:

> Yes both fzf and fzf-tmux work

But you also said:

> Hmm... both not found.

when I asked you about `:echo system('which fzf')`. I'm not sure what's going on.

**Comment by firedev** [comment]
`[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh` in `.zshrc` - yes.

But as far as I know vim uses different shell that bypasses `.zshrc` or something. That's why I have a duplicate of `$PATH` in `.zshenv`.

`fzf` and `fzf-tmux` did work from terminal, just not from Vim, adding path to `.zshenv` fixed that.

**Comment by junegunn** [comment]
> fzf and fzf-tmux did work from terminal, just not from Vim, adding path to .zshenv fixed that.

If they work from terminal, and you started Vim from that shell, they should also work in Vim which is a subprocess of the shell. You'll notice that `$PATH` is `export`ed inside `~/.fzf.zsh`.

Anyway, with the previous commit, now both `:FZF` and `:FZF!` should run on a shell where fzf is not (yet) in `$PATH`. Thanks for the report.
