### ISSUE TITLE
Neovim shows `--expect=ctrl-v,ctrl-x,ctrl-t --no-height`

### ISSUE THREAD

**Issue by exoticus** [junegunn/fzf#1811]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [X] I have searched through the existing issues

## Info

- Versions
    - fzf 0.20.0
    - nvim 0.4.3
- OS
    - [x] Linux
    - [x] Mac OS X
- Shell
    - [x] bash
    - [x] zsh
    - [x] fish
    
## Problem / Steps to reproduce

So basically on both my machines (Linux and MacOS) using Fish on my mac and zsh on my linux neovim (not vim) shows this `#89b482' '--multi' '--prompt' '~/' --expect=ctrl-v,ctrl-x,ctrl-t --no-height > /var/folders/gh/63h_dqcs2n707qw4ps4j787m0000gn/T/nvimvtRckP/1;#FZF` upon excuting `:FZF` i don't know what causes it and it only happens in neovim (even with no plugins or setting changes applied)

## Interesting Find

After fiddling around a bit more i find that the issue seems to go if use vim plug to install fzf instead of 

```vim
set rtp+=/usr/local/opt/fzf
```

which works in vim but not in neovim, in neovim i had to use instead, kinda weird though

```vim
Plug '/usr/local/opt/fzf'
Plug 'junegunn/fzf.vim'
```

**Comment by junegunn** [comment]
It's probably a configuration issue. Check if it's reproducible with a minimal configuration like https://gist.githubusercontent.com/junegunn/6936bf79fedd3a079aeb1dd2f3c81ef5/raw.

**Comment by LuRsT** [comment]
@exoticus, did you manage to fix it?
