### ISSUE TITLE
CTRL+R executes reverse-i-search

### ISSUE THREAD

**Issue by VancouverJohn** [junegunn/fzf#1812]
- [Y] I have read through the manual page (`man fzf`)
- [Y] I have the latest version of fzf
- [Y] I have searched through the existing issues

## Info

- OS
    - [Y] Linux (Arch)
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [Y] bash
    - [ ] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

CTRL+R does not bring up fzf

Tested in terminator and termite

**Comment by junegunn** [comment]
How did you install fzf? You may need to take extra steps to enable shell key bindings depending on your package manager.

- https://github.com/junegunn/fzf#using-linux-package-managers

**Comment by VancouverJohn** [comment]
Thank you very much junegunn, you were right!  I just added 

source /usr/share/fzf/key-bindings.bash
source  /usr/share/fzf/completion.bash

to my .bashrc file and it is working

Thanks again!
