### ISSUE TITLE
Why not implement the install.bat on windows just like the function on the file install?

### ISSUE THREAD

**Issue by jiangjianshan** [junegunn/fzf#1814]
Hello,

     I'm using Vim8.2 on Windows 10. I want to do some setting on _vimrc like below:

" -------------------------------------------- begin -------------------------------------
if has('win32')
    Plug 'junegunn/fzf', { 'dir': '$HOME/.fzf', 'do': './install.bat --all' }
else
    Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
endif
"-----------------------------------------------end ---------------------------------------

      It is recommend there is one file maybe call it "install.bat", which function is just like "install", can be released from the git respository.

**Comment by junegunn** [comment]
Are you interested in making a pull request?

**Comment by jiangjianshan** [comment]
@junegunn, I'm trying to write it down on these days, when it ready, I will request to do it.

**Comment by jiangjianshan** [comment]
@junegunn, sorry for later reply, I have just make a new pull request for it. You can check it.

**Comment by junegunn** [comment]
Closed by #1845
