### ISSUE TITLE
Feature request: action to add new item when using --multi

### ISSUE THREAD

**Issue by jjlee** [junegunn/fzf#1816]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

I would like to use `fzf --multi` for selecting tags.  However, I would also like to be able to enter new tags, alongside existing ones, in the same `fzf` invocation.  As far as I can tell there is no way to achieve this currently.  Perhaps there would be a new action to add a new item whose text value would be the current search string, and perhaps a default keybinding for that action.  Or maybe just TAB would be enough: if the new option is supplied (I've called it `--allow-add-items`), then add the current search string as a new item if there are no matches for the current search string.

Expect (something like):

```echo -e 'foo\nbar\nbaz\n' | fzf --multi --allow-add-items```

* user types `bleep`
* user types default key binding for "add new item" action
* user hits TAB
* output now looks like:
```
>>bleep
```
* user deletes search term
* output now looks something like:
```
> baz
> bar
> foo
>>bleep
```
* user types `fo`
* output now looks something like:
```
> foo
```
* user hits TAB
* output now looks like:
```
>>foo
```
* user deletes search term
* output now looks something like:
```
> baz
> bar
>>foo
>>bleep
```
* user hits RETURN
* fzf prints:
```
foo
bleep
```

**Comment by junegunn** [comment]
The feature you described is beyond the scope of this project. fzf, which can be thought of as an interactive version of grep, doesn't seem like the best tool for the use case. You might want to try out different options such as https://github.com/SBoudrias/Inquirer.js.
