### ISSUE TITLE
fuzzy completion for zsh 

### ISSUE THREAD

**Issue by sktrinh12** [junegunn/fzf#1818]
- [ X] I have read through the manual page (`man fzf`)
- [ X] I have the latest version of fzf
- [ X] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [ X] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ X] zsh
    - [ ] fish
    
## Problem / Steps to reproduce
`brew install fzf`
added lines to .zshrc:
```
export FZF_BASE='/usr/local/opt/fzf'
plugins=(
  git
  fzf
)
```
tried:
```
nvim **<TAB>
cd **<TAB>

```
i just get a print-out of all the possible files in the current directory on one line. when I press <TAB> again I get the option to select (from zsh). 

I also tried to change:
`export FZF_COMPLETION_TRIGGER='~~'`
...but the issue persists.

**Comment by junegunn** [comment]
Follow the installation instruction in the README page:
- https://github.com/junegunn/fzf#using-homebrew-or-linuxbrew
