### ISSUE TITLE
Vim navigation in fzf preview window

### ISSUE THREAD

**Issue by kumaran-14** [junegunn/fzf#1819]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues
#### Information
A feature to use hjkl keys to navigate file list in fzf preview window command. Allow users to enable this feature on/off, i.e by default input in fzf widow does not search for file name matching.
Allowing users to switch focus to preview window and uses hjkl bindings to scroll files would also be great.

**Comment by junegunn** [comment]
Thanks for the suggestion, but I'm not interested in adding mode switching to fzf to keep it simple. 

You can bind `j` and `k` to `down` and `up` although you can't turn it off.

```sh
fzf --preview 'cat {}' --bind 'j:down,k:up,ctrl-j:preview-down,ctrl-k:preview-up'
```

**Comment by devcharted** [comment]
Wery nice, but this is what I end up using:

```
fzf --preview 'cat {}' --bind 'ctrl-j:down,ctrl-k:up,alt-j:preview-down,alt-k:preview-up'
```
so you can actually type `j` and `k`

**Comment by Kardelio** [comment]
possibly a dumb dumb noob question...
BUT...

I use the FZF preview like this:
```
    command! -bang -nargs=* FzfListOut
      \ call fzf#vim#files(<q-args>,fzf#vim#with_preview({'source':'ag --hidden -u -U --ignore .git -g "" }))
```
using the `fzf#vim#with_preview` instead...

So my dumb question is how can i use the bind args ` --bind 'ctrl-j:down,ctrl-k:up,alt-j:preview-down,alt-k:preview-up'` within that function? is there a way or am i using the fzf preview functionality all wrong?

Many thnaks <3

**Comment by junegunn** [comment]
> So my dumb question is how can i use the bind args ` --bind 'ctrl-j:down,ctrl-k:up,alt-j:preview-down,alt-k:preview-up'` within that function? is there a way or am i using the fzf preview functionality all wrong?

You can pass it as `options` value in the dictionary.

```vim
command! -bang -nargs=* FzfListOut
  \ call fzf#vim#files(<q-args>,
  \   fzf#vim#with_preview({
  \     'source': 'ag --hidden -u -U --ignore .git -g ""',
  \     'options': '--bind "ctrl-j:down,ctrl-k:up,alt-j:preview-down,alt-k:preview-up"'}))
```

**Comment by Kardelio** [comment]
amazing! thank you @junegunn !! and thank you for all you do <3

**Comment by junegunn** [comment]
Or if you want it globally across all fzf commands, just put it in your `$FZF_DEFAULT_OPTS` like so.

```vim
" In vim configuration file
let $FZF_DEFAULT_OPTS = '--bind "ctrl-j:down,ctrl-k:up,alt-j:preview-down,alt-k:preview-up"'
```
