### ISSUE TITLE
Ignoring certain patterns

### ISSUE THREAD

**Issue by firedev** [junegunn/fzf#182]
Splitting this from #181 

>fzf is a command line filter that can be used with anything, so it doesn't have the notion of ignored files and folders.
```
ps -ef | fzf
seq 1 100 | fzf
```
>When the input is not specified (fzf w/o STDIN pipe), it will use find command as the default input. You can set $FZF_DEFAULT_OPTS environment variable to a command that lists the files as you like.

Sorry my knowledge is limited, how can I supply a list of ignored patterns for FZF?

**Comment by junegunn** [comment]
It's not the responsibility of fzf. You have to feed the right input to fzf, and for vim plugin, setting up `$FZF_DEFAULT_COMMAND` will do. You can set it to some command or your own script that lists the files under the current directory.
Please refer to: https://github.com/junegunn/fzf#respecting-gitignore-hgignore-and-svnignore

**Comment by junegunn** [comment]
Note that you can also set the environment variable inside vim:

```vim
let $FZF_DEFAULT_COMMAND = 'ag -l -g ""'
```

**Comment by mikedfunk** [comment]
For googlers - you can also add `--skip-vcs-ignores` to use `.agignore` but not `.gitignore`. This allowed me to also search in my vendor folder but ignore code coverage files, generated documentation, etc.
