### ISSUE TITLE
Fuzzy completion in bash does not work for `vim **<TAB>`

### ISSUE THREAD

**Issue by themightyoarfish** [junegunn/fzf#1822]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

1. Install fzf and bash integration
2. Type `vim **<TAB>`
3. No fuzzy completion, for me it just expands to the alphabetically first file in the current directory

On the other hand, it seems to be working for ssh, for instance.

**Comment by themightyoarfish** [comment]
I found the culprit: https://github.com/scop/bash-completion is incompatible with fzf it seems.

**Comment by junegunn** [comment]
I have no experience with the project, so I can't be sure, but make sure to load fzf completion file after you load that project.

**Comment by LuRsT** [comment]
If you figured out the issue @themightyoarfish and it's not related to `fzf`, could you close this issue please?
