### ISSUE TITLE
Match ranking behaves weirdly in presence of character swaps

### ISSUE THREAD

**Issue by Apromixately** [junegunn/fzf#1823]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

I have a `~/projects` for work related stuff. When I do `cd ~**<TAB>` and then type `projects` I can select folders but if I accidentally type `porjects` I get something really deep in the hierarchy that contains the word `projector` twice highlighted as `(p)roject(or)/pro(ject)or`. This is more true to the order of the letters I typed but the editing distance is much bigger than to `project` so I would expect that to be rated higher.

**Comment by junegunn** [comment]
fzf doesn't use a typical approximate string matching algorithm and out-of-order letters within a search term are not allowed. I believe this is true for most of the other similar programs. In essence, `foo` translates to a regular expression `/f.*o.*o/`.

**Comment by pvonmoradi** [comment]
@junegunn 
I'm seeing a similar issue:
```console
$ cat a
meticulous 
metric ton 
metrication 
metallic 
meteoric 
methodical 
metaphysics 
melodramatic 
magnetic north 
mimetic 
cosmetic 
hermetic

$ cat a | fzf --filter=meticol
(nothing)
$ cat a | fzf --filter=meticuls
meticulous
```
In short, fzf can't detect the spelling error of "meticolous" in presence of a list containing "meticulous"
