### ISSUE TITLE
Don't stretch current buffer when using fzf

### ISSUE THREAD

**Issue by tmpm697** [junegunn/fzf#1825]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [x] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

Current implementation of fzf with vim will stretch current buffer above. How to keep the buffer that used with fzf separated or don't impact current/any buffer?

There's `clap.vim` but I don't like the way of `clap.vim` -- use much more resources and appear in center of screen.

I like the way fzf appear at the bottom and has less distraction compare to `clap.vim`.

The stretch issue with fzf+vim also cause distraction and not clean but more acceptable than `clap.vim` way.

**Comment by junegunn** [comment]
I'm not completely sure what you mean by "stretching", but does this patch help?

```diff
diff --git a/plugin/fzf.vim b/plugin/fzf.vim
index 21b7d66..f88f03a 100644
--- a/plugin/fzf.vim
+++ b/plugin/fzf.vim
@@ -412,7 +412,7 @@ try
   let has_vim8_term = has('terminal') && has('patch-8.0.995')
   let has_nvim_term = has('nvim-0.2.1') || has('nvim') && !s:is_win
   let use_term = has_nvim_term ||
-    \ has_vim8_term && !has('win32unix') && (has('gui_running') || s:is_win || !use_height && s:present(dict, 'down', 'up', 'left', 'right', 'window'))
+    \ has_vim8_term && !has('win32unix') && (has('gui_running') || s:is_win || s:present(dict, 'down', 'up', 'left', 'right', 'window'))
   let use_tmux = (!use_height && !use_term || prefer_tmux) && !has('win32unix') && s:tmux_enabled() && s:splittable(dict)
   if prefer_tmux && use_tmux
     let use_height = 0
```

**Comment by junegunn** [comment]
If it helps, you can apply the solution beforehand by adding the following setting, which forces fzf to open in a terminal buffer inside a Vim window of 40% height.

```vim
let g:fzf_layout = { 'window': "execute 'botright' float2nr(ceil(0.4 * &lines)) 'new'" }
```

**Comment by tmpm697** [comment]
Thanks for the repy.

I think I need it in a pop-up windows so it doesn't scroll the current buffer up a bit.

The patch put result in a terminal that `still` push current buffer up. @junegunn

**Comment by tmpm697** [comment]
I'm using vim8.2, not nvim.

**Comment by tmpm697** [comment]
example:

vi test.diff
```
diff --git a/plugin/fzf.vim b/plugin/fzf.vim
index 21b7d66..f88f03a 100644
--- a/plugin/fzf.vim
+++ b/plugin/fzf.vim
@@ -412,7 +412,7 @@ try
   let has_vim8_term = has('terminal') && has('patch-8.0.995')
   let has_nvim_term = has('nvim-0.2.1') || has('nvim') && !s:is_win
   let use_term = has_nvim_term ||
-    \ has_vim8_term && !has('win32unix') && (has('gui_running') || s:is_win || !use_height && s:present(dict, 'down', 'up', 'left', 'right', 'window'))
+    \ has_vim8_term && !has('win32unix') && (has('gui_running') || s:is_win || s:present(dict, 'down', 'up', 'left', 'right', 'window'))
   let use_tmux = (!use_height && !use_term || prefer_tmux) && !has('win32unix') && s:tmux_enabled() && s:splittable(dict)
   if prefer_tmux && use_tmux
     let use_height = 0
```
Now I press `:History` to open recenty buffers, the layout as below:
```
--- a/plugin/fzf.vim
+++ b/plugin/fzf.vim
@@ -412,7 +412,7 @@ try
   let has_vim8_term = has('terminal') && has('patch-8.0.995')
   let has_nvim_term = has('nvim-0.2.1') || has('nvim') && !s:is_win
   let use_term = has_nvim_term ||
-    \ has_vim8_term && !has('win32unix') && (has('gui_running') || s:is_win || !use_height && s:present(dict, 'down', 'up', 'left', 'right', 'window'))
+    \ has_vim8_term && !has('win32unix') && (has('gui_running') || s:is_win || s:present(dict, 'down', 'up', 'left', 'right', 'window'))
   let use_tmux = (!use_height && !use_term || prefer_tmux) && !has('win32unix') && s:tmux_enabled() && s:splittable(dict)
   if prefer_tmux && use_tmux
     let use_height = 0
/a/path/to/something
/ab/pathb/to/somethingelse
```

You'd notice that two lines are push up for fzf to have some spaces to print out two lines of its result:
```
diff --git a/plugin/fzf.vim b/plugin/fzf.vim
index 21b7d66..f88f03a 100644
``

**Comment by LuRsT** [comment]
There's a pop-up function now which may help be helpful for what you're trying to do. Have you managed to try the latest version of `fzf`?

**Comment by tmpm697** [comment]
@LuRsT how to setup `fzf` to always use pop-up feature instead of stretch screen? I always have up-to-date system and fzf.

**Comment by LuRsT** [comment]
@tmpm697, 

Yes, and Yes!

With this line below, you can keep the popup on the bottom of your screen (you will need to play with the width setting tho.

```
let g:fzf_layout = {  'window': { 'yoffset': 1 ,'width': 0.6, 'height': 0.5 } }
```

**Comment by tmpm697** [comment]
With this line in vim:
```
let g:fzf_layout = { 'window': { 'width': 0.9, 'height': 0.6 } }
```

I've got this error when try to use `:History`:
```
Error detected while processing function <SNR>38_history[7]..fzf#vim#history[1]..<SNR>79_fzf[18]..fzf#run[64]..<SNR>17_execute_term[3]..<SNR>17_split:
line    9:
E731: using Dictionary as a String
Error detected while processing function <SNR>38_history:
line    7:
E171: Missing :endif
```

I have fzf and fzf.vim up-to-date in vim's plugins. @LuRsT

**Comment by LuRsT** [comment]
What's your neovim/vim version? I use `NVIM v0.4.3`

**Comment by tmpm697** [comment]
I use vim 8.2 - vim-git from aur.

**Comment by LuRsT** [comment]
@tmpm697, try reproducing the problem using _only_ the fzf with that configuration by itself, I'm suspecting it's something else in your vimrc
