### ISSUE TITLE
Better experience on handhelds

### ISSUE THREAD

**Issue by jarun** [junegunn/fzf#1826]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

Hi,

I might have missed it but I couldn't find a way to do the following with `fzf` when a list of files is passed as input:

- match only the filename and not the path to the file
- trim or fold the path

These would greatly improve the usability on smaller form factors like handhelds.

**Comment by junegunn** [comment]
> match only the filename and not the path to the file

```sh
find * -type f | fzf --delimiter / --nth -1
```

> trim or fold the path

It doesn't make sense to implement builtin trimming functionality to fzf, a general-purpose text filter, so you have to find a program that trims the path and preprocess the input using it before feeding to fzf. Then you can use `--with-nth` option to hide the original path.

```sh
find * -type f | awk '{print $0 "\t" "trimmed"}' |
  fzf --delimiter "\t" --with-nth 2 | awk -F"\t" '{print $1}'
```

**Comment by jarun** [comment]
> find * -type f | fzf --delimiter / --nth -1

shows me the shorter path and when I try to open a match I get a shorter path which the editor program cannot resolve.
