### ISSUE TITLE
Binding of second enter key

### ISSUE THREAD

**Issue by lonix1** [junegunn/fzf#1828]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
- Shell
    - [x] bash
    - [x] zsh
    
## Problem / Steps to reproduce

I choose an option in a list (up and down keys), and then want to select it using the "small" enter key (the one on the right hand side of the keyboard, in the numeric keypad part).

But it doesn't do anything. I need to press the big/main enter key.

Unsure how to diagnose or fix this problem.

**Comment by junegunn** [comment]
Can you execute `ruby -e 'c = gets; p [c, c.ord]'` and see if your small and large enter keys give different result?

**Comment by lonix1** [comment]
In both cases I get `["\n", 10]`.

**Comment by junegunn** [comment]
So they're identical. Yes, they should both work just fine.
