### ISSUE TITLE
Ubuntu: "command failed" error with FZF_DEFAULT_COMMAND="rg --files"

### ISSUE THREAD

**Issue by pckilgore** [junegunn/fzf#1830]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

1. Pipe in `rg --files | fzf` => Works fine.
2. set/export `FZF_DEFAULT_COMMAND='rg --files'` => Error
![image](https://user-images.githubusercontent.com/2559043/72667681-035d6300-39e4-11ea-8211-c9ced88f8682.png)

```console
(✓) 11:17:08 [~]
$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Pop!_OS 18.04 LTS"
(✓) 11:17:42 [~]
$ uname -a
Linux p5520 5.3.0-7625-generic #27~1576774585~18.04~c7868f8-Ubuntu SMP Thu Dec 19 20:37:47 UTC  x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by junegunn** [comment]
Does `$SHELL -c 'rg --files'` work?

**Comment by pckilgore** [comment]
```console
(✓) 14:22:15 [~]
$ echo $SHELL
/bin/bash
(✓) 14:15:07 [~]
$ $FZF_DEFAULT_COMMAND
(✓) 14:15:11 [~]
$ $SHELL -c 'rg --files' | head -n 3
macos-guest-virtualbox.sh
1
2
(✓) 14:15:32 [~]
$ echo "That worked"
That worked
```

Piping also works:
```console
(✓) 14:21:51 [~]
$ $SHELL -c 'rg --files' | fzf
```

Thank you for assisting!

**Comment by hkennyv** [comment]
Hey there @pckilgore, did you get this working? I am having the same issue on Mac OS Mojave (10.14.6).

* vim --version
```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Dec  3 2019 04:38:39)
Included patches: 1-503, 505-680, 682-1283, 1365
Compiled by root@apple.com
Normal version without GUI.  Features included (+) or not (-):
+acl             +file_in_path    -mouse_sgr       +tag_old_static
-arabic          +find_in_path    -mouse_sysmouse  -tag_any_white
+autocmd         +float           -mouse_urxvt     -tcl
-balloon_eval    +folding         +mouse_xterm     -termguicolors
-browse          -footer          +multi_byte      -terminal
+builtin_terms   +fork()          +multi_lang      +terminfo
+byte_offset     -gettext         -mzscheme        +termresponse
+channel         -hangul_input    +netbeans_intg   +textobjects
+cindent         +iconv           +num64           +timers
-clientserver    +insert_expand   +packages        +title
-clipboard       +job             +path_extra      -toolbar
+cmdline_compl   +jumplist        -perl            +user_commands
+cmdline_hist    -keymap          +persistent_undo +vertsplit
+cmdline_info    +lambda          +postscript      +virtualedit
+comments        -langmap         +printer         +visual
-conceal         +libcall         -profile         +visualextra
+cryptv          +linebreak       +python/dyn      +viminfo
+cscope          +lispindent      -python3         +vreplace
+cursorbind      +listcmds        +quickfix        +wildignore
+cursorshape     +localmap        +reltime         +wildmenu
+dialog_con      -lua             -rightleft       +windows
+diff            +menu            +ruby/dyn        +writebackup
+digraphs        +mksession       +scrollbind      -X11
-dnd             +modify_fname    +signs           -xfontset
-ebcdic          +mouse           +smartindent     -xim
-emacs_tags      -mouseshape      +startuptime     -xpm
+eval            -mouse_dec       +statusline      -xsmp
+ex_extra        -mouse_gpm       -sun_workshop    -xterm_clipboard
+extra_search    -mouse_jsbterm   +syntax          -xterm_save
-farsi           -mouse_netterm   +tag_binary
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H   -DMACOS_X_UNIX  -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: gcc   -L/usr/local/lib -o vim        -lm -lncurses  -liconv -framework Cocoa
```

* `$SHELL -c 'rg -i'

```
error: The following required arguments were not provided:
    <PATTERN>

USAGE:

    rg [OPTIONS] PATTERN [PATH ...]
    rg [OPTIONS] [-e PATTERN ...] [-f PATTERNFILE ...] [PATH ...]
    rg [OPTIONS] --files [PATH ...]
    rg [OPTIONS] --type-list
    command | rg [OPTIONS] PATTERN

For more information try --help
```

* `fzf`

```
[Command failed: rg -i]
```

**Comment by junegunn** [comment]
You might want to check the stderr output of the process.

```sh
FZF_DEFAULT_COMMAND='rg --files 2> /tmp/error-log' fzf
```

**Comment by LuRsT** [comment]
@pckilgore, did you run the above command, or is this not an issue anymore? :point_up:

**Comment by pckilgore** [comment]
I missed @junegunn 's comment but I cannot test until I return to the machine in a few days.

**Comment by LuRsT** [comment]
Let us know when you can @pckilgore :+1:

**Comment by henrebotha** [comment]
I'm seeing this error as well. Latest version (0.24.3), shell is Zsh 5.8. @junegunn's suggestion of sending errors to a file doesn't work either (no file is produced).

**Comment by rayiik** [comment]
This might get you your log file (what i use when redirection isn't working)
```bash
FZF_DEFAULT_COMMAND='rg --files 2> /tmp/error-log' tee -a logfile <<<$(fzf)
```
Pretty sure zsh heresting syntax is the same

**Comment by henrebotha** [comment]
@rayiik I just get an empty file. Assuming the command you posted is correct (I had to fix a curly apostrophe), it must mean Fzf is not producing any error output.

**Comment by junegunn** [comment]
@rayiik Please avoid posting code snippets with curly quotes.

- https://github.com/junegunn/fzf/issues/1830#issuecomment-728921781
- https://github.com/junegunn/fzf/issues/2243#issuecomment-725413275

You probably have an OS option enabled that automatically converts quotes on paste. (e.g. "Use smart quotes and dashes" in macOS).

@henrebotha Please post the output of the following commands to better understand the situation.

```sh
echo $SHELL

$SHELL -c 'echo it works'

type fzf

FZF_DEFAULT_COMMAND='echo it works' fzf -f works

# Does it show "it works"?
FZF_DEFAULT_COMMAND='echo it works' fzf
```

**Comment by rayiik** [comment]
Hey sorry yea the curly quotes are an  issue when i post from my phone all mu singles are under the same popup menu and it tries to guess some times

**Comment by henrebotha** [comment]
@junegunn Here are the results from those commands. A red prompt icon indicates a non-zero exit from the previous command.

![image](https://user-images.githubusercontent.com/5593874/99458681-3686c080-292d-11eb-8e5e-59eaa08a609e.png)

The last command looks like this when it's running.

![image](https://user-images.githubusercontent.com/5593874/99458760-57e7ac80-292d-11eb-8cf1-029d7fc78e4d.png)

**Comment by junegunn** [comment]
That's strange. Let's check a few more things.

```sh
file $(command -v fzf)

command -v sh

SHELL=sh FZF_DEFAULT_COMMAND='echo it works' fzf -f works
```

**Comment by henrebotha** [comment]
@junegunn 

![image](https://user-images.githubusercontent.com/5593874/99525174-c1050980-2999-11eb-8932-e85d4be8449e.png)

**Comment by junegunn** [comment]
So it works with `sh` but not with `zsh`. Interesting. Any clue?

```sh
SHELL=sh FZF_DEFAULT_COMMAND='echo it works' fzf -f works

SHELL=zsh FZF_DEFAULT_COMMAND='echo it works' fzf -f works

SHELL=/bin/zsh FZF_DEFAULT_COMMAND='echo it works' fzf -f works

type zsh

type $SHELL

$SHELL --version

export | grep SHELL

export | grep $(dirname $SHELL)

sh -c "zsh -c 'echo it works'"

sh -c "$SHELL -c 'echo it works'"
```

**Comment by henrebotha** [comment]
Ah, interesting! I have no `/bin/zsh` (verified with `which` & `ls`), so the third command fails. Looks like somewhere my `$SHELL` is being set to `/bin/zsh`, which doesn't exist; but that doesn't explain to me why commands like `/bin/zsh --version` don't fail. :thinking: 

![image](https://user-images.githubusercontent.com/5593874/99531575-3d501a80-29a3-11eb-8d77-6b72f6bd7277.png)

![image](https://user-images.githubusercontent.com/5593874/99531592-42ad6500-29a3-11eb-9620-d220290b29b5.png)

**Comment by henrebotha** [comment]
`export SHELL=$(which zsh)` does fix the issue. I still don't understand how `/bin/zsh` is able to execute when there is no `/bin/zsh` file…

**Comment by junegunn** [comment]
Maybe that's an alias? 🤔 

```sh
alias | grep zsh
```

**Comment by henrebotha** [comment]
It's not an alias.

I think I've found the root cause here. From https://github.com/termux/termux-exec:

> A lot of Linux software is written with the assumption that `/bin/sh`, `/usr/bin/env`
and similar file exists. This is not the case on Android where neither `/bin/` nor `/usr/`
exists.
>
> When building packages for Termux those hard-coded assumptions are patched away - but this
does not help with installing scripts and programs from other sources than Termux packages.

I'm using the Termux terminal environment on Android, so this explains why `/bin/zsh` both does and does not exist, and why things that rely on such shebangs might be breaking. Installing the linked package & fully restarting Termux fixed the issue permanently for me.

I consider my issue resolved, but @pckilgore was on Linux, not Android, and so I don't think we can say the same for their problem.

**Comment by pckilgore** [comment]
And my fault, this was fixed for me when the machine in question was upgraded to 20.04, unfortunately without me really understanding *why*, but at this point I suspect the universe of people who need to be on 18.04 and need to have FZF installed is pretty small.

Since @henrebotha 's issue is resolved I'll close.

**Comment by pckilgore** [comment]
Oh, and thanks @junegunn, FZF is pretty much at the heart of my env, awesome piece of software.

**Comment by rayiik** [comment]
hey just a though as to why (being on ubuntu) did you check update-alternatives --all might shed some clues, im not sure how the "alternatives are set (dont their not aliases) but they replace your default command with another of your choices thats in i believe /etc/alternatives

**Comment by rayiik** [comment]
so the alternatives are symbolic links it looks like but i think its more likely the answer is more likely to do with the configuration of the package (dpkg-reconfigure) which isnt limited to symlinks as mentioned in the linked post, or at least the behavior sounds pretty close to package diversion behavior mentioned @pckilgor @henrebotha

**Comment by lioaslan** [comment]
Thanks @rayiik, I have met this issue but with `fd` , after I ran those commands It worked
