### ISSUE TITLE
Got “unexpected rune” with --preview

### ISSUE THREAD

**Issue by alexherbo2** [junegunn/fzf#1833]
Hello,

I got this error while using `--preview` as a script.

The error is reproducible with:

``` sh
cat <<'EOF' | fzf --preview 'text=$(echo {})'
1
2
3
EOF
```

Output:

```
Parse error: unexpected rune ')'
code from -c, line 1: text=$(echo '1')
```

[Here][yank-ring.kak] is the complete example.

[yank-ring.kak]: https://github.com/alexherbo2/yank-ring.kak/blob/master/rc/yank-ring.kak

**Comment by junegunn** [comment]
What is your `$SHELL`?

**Comment by alexherbo2** [comment]
`dash`

**Comment by junegunn** [comment]
You might want to see if this gives you any clue:

https://github.com/search?q=%22Parse+error%3A+unexpected+rune%22&type=Issues

Looks like "Parse error: unexpected rune" message is coming from elvish?

**Comment by LuRsT** [comment]
Did you manage to fix it @alexherbo2?
