### ISSUE TITLE
Using fd instead of find

### ISSUE THREAD

**Issue by nomasprime** [junegunn/fzf#1839]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

I've put this together from the docs.

```
fzf_compgen_path() {
  fd --exclude ".git" --follow --hidden . "$1"
}

fzf_compgen_dir() {
  fd --exclude ".git" --follow --hidden --type d . "$1"
}

FZF_ALT_C_COMMAND=fd --type d --exclude .git --follow --hidden
FZF_DEFAULT_COMMAND=fd --type f --exclude .git --follow --hidden
FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
```

When I look into the code though the default find commands are really long. Am I missing something? Is this the best way to switch to fd?

**Comment by LuRsT** [comment]
It looks good @nomasprime, the advantage of using `fd` is that it has good defaults and very useful flags that work better than find for 80% of what people do. I don't think you're missing anything.

Are you running into any trouble or are you just double checking?

**Comment by junegunn** [comment]
Because `$FZF_DEFAULT_COMMAND` cannot handle `vim /foo/bar/baz**`. You can't just append `/foo/bar` to an arbitrary command, which can be anything, and expect it to search inside the directory.

**Comment by MartenBE** [comment]
@junegunn , I see, thanks for the answer. The documentation is rather confusing in regards of using `fd` for the keybinds vs. using `fd` for the `**<Tab>` completion. E.g. I didn't know that the `FZF_..._COMMAND` variables don't apply to `**<Tab>` completion. Is my edited comment then the best way to have `fd` used for all possible ways fzf can be called? Is there a shorter way?

**Comment by MartenBE** [comment]
I see, thank you!

> FWIW, I removed all those configs and just use the defaults since [0.48.0](https://github.com/junegunn/fzf/blob/master/CHANGELOG.md#0480).

Unfortunately, Fedora 40 is still stuck on https://packages.fedoraproject.org/pkgs/fzf/fzf/ :/ , so I'll use this for a while.

**Comment by junegunn** [comment]
I see, but nothing stopping you from downloading [the latest binary](https://github.com/junegunn/fzf/releases) and putting it in one of the directories in `$PATH`.
