### ISSUE TITLE
Pressing `Insert` crashes to terminal

### ISSUE THREAD

**Issue by Hunter-Github** [junegunn/fzf#184]
fzf version 0.8.9 (Dec 24, 2014)

Pressed Insert key. Crashed not so gently to terminal.

    /home/AUser/bin/fzf:992:in `pack': no implicit conversion of Symbol into Integer (TypeError)
    	from /home/AUser/bin/fzf:992:in `get_input'
    	from /home/AUser/bin/fzf:1155:in `start_loop'
    	from /home/AUser/bin/fzf:307:in `start'
    	from /home/AUser/bin/fzf:1345:in `<main>'

**Comment by junegunn** [comment]
Hi, thanks for the report, but I currently do not maintain the legacy Ruby version (< 0.9). Is there a reason you have to use the old version? Windows?

**Comment by Hunter-Github** [comment]
ruby 2.2.1p85 (2015-02-26 revision 49769) [i686-linux]

**Comment by Hunter-Github** [comment]
Actually, can choose any ruby, am running `rvm`.

**Comment by Hunter-Github** [comment]
ruby 2.2.1p85 (2015-02-26 revision 49769) [i686-linux]

Actually, can choose any ruby, am running rvm.

**Comment by junegunn** [comment]
No, I meant fzf version, not Ruby version. fzf was completely rewritten in Go earlier this year, and no longer requires Ruby. See: https://github.com/junegunn/fzf/blob/master/src/README.md

**Comment by Hunter-Github** [comment]
Ok. Seems like i686 isn't supported, either. Thanks anyway.

**Comment by junegunn** [comment]
No, they are supported.
https://github.com/junegunn/fzf/blob/master/install#L76-L79

What is the output of `uname -sm` on your machine?

**Comment by Hunter-Github** [comment]
Linux i686. I compiled the binary by tweaking the Makefile:

     #ifneq ($(shell uname -m),x86_64)
     #$(error "Build on $(UNAME_M) is not supported, yet.")
     #endif

    #BINARY64  := fzf-$(GOOS)_amd64
    #VERSION    = $(shell fzf/$(BINARY64) --version)
   #RELEASE64  = fzf-$(VERSION)-$(GOOS)_amd64

    release: build
    	cd ../fzf && \
    	cp $(BINARY32) $(RELEASE32) && tar -czf $(RELEASE32).tgz $(RELEASE32) && \
    	rm $(RELEASE32)

     build: test fzf/$(BINARY32) 

    #test:
   #	go get
   #	go test -v ./...

and eliding other lines dealing with 64-bit arch.

**Comment by junegunn** [comment]
Hey, did you read the installation guide? If you use the attached install script it will download the right binary for your platform, or, as mentioned there, you can download a prebuilt binary (linux_386) from here: https://github.com/junegunn/fzf-bin/releases

**Comment by Hunter-Github** [comment]
I prefer to build executables from the source, BTW thanks for the great utility.

**Comment by junegunn** [comment]
I see, thanks.
