### ISSUE TITLE
is "AND" operator supported?

### ISSUE THREAD

**Issue by alfonz19** [junegunn/fzf#1842]
I was searching in documentation/stackoverflow and I did not find mention of `and` operator. There is or search operator `^core go$ | rb$ | py$`, allowing to search matches matching any of given patterns, but I did not find any `and` operator.

Motivation: there is say a lot of java processes running on my system, and I want to kill all but named, so I would be able to type: `^java && !idea` for example.

Is it possible? If not, is there a workaround? If not, could this be somehow introduced?

Thanks!

**Comment by junegunn** [comment]
Without `|`, the terms are by default "and".

**Comment by alfonz19** [comment]
thanks a lot, I did not realise that, sorry.
