### ISSUE TITLE
Shell completion fails in CentOS

### ISSUE THREAD

**Issue by sivaswami** [junegunn/fzf#1843]
- [X ] I have read through the manual page (`man fzf`)
- [X ] I have the latest version of fzf
- [ X] I have searched through the existing issues

## Info

- OS
    - [ X] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ X] bash
    - [ ] zsh
    - [ ] fish
    
## Problem / Steps to reproduce
 source ${FZF}/shell/completion.bash
bash: complete:  default -o bashdefault: invalid option name
bash: complete:  default -o bashdefault: invalid option name
bash: complete:  default -o bashdefault: invalid option name
bash: complete:  default -o bashdefault: invalid option name
bash: complete:  default -o bashdefault: invalid option name
bash: complete:  default -o bashdefault: invalid option name
bash: complete:  default -o bashdefault: invalid option name
bash: complete:  default -o bashdefault: invalid option name
bash: complete:  nospace -o dirnames: invalid option name
bash: complete:  default -o nospace -v: invalid option name
bash: complete:  default -o nospace -v: invalid option name
bash: complete:  default -o bashdefault: invalid option name
bash: complete:  default -o bashdefault: invalid option name

Possible reason: if constructs like this
 if ! declare -f _fzf_compgen_dir > /dev/null; then

**Comment by LuRsT** [comment]
Hi @sivaswami,

Could you add some more information to your problem? I'm finding it hard to understand what you mean by that, maybe by now you've fixed it?

**Comment by junegunn** [comment]
It's probably because your bash version is too low. Make sure to use bash 3 or above (preferably 4 or above).

**Comment by tarjanm-movidius** [comment]
I had the same issue on an up-to-date Arch Linux, bash v5.1.16
It's an IFS issue I believe, the whole shebang after -o is interpreted as one string. Solved it with eval:

diff --git a/shell/completion.bash b/shell/completion.bash
index 9474ea0..6096a05 100644
--- a/shell/completion.bash
+++ b/shell/completion.bash
@@ -337,7 +337,7 @@ __fzf_defc() {
     printf -v def "$orig" "$func"
     eval "$def"
   else
-    complete -F "$func" $opts "$cmd"
+    eval "complete -F \"$func\" $opts \"$cmd\""
   fi
 }
