### ISSUE TITLE
Nesting FZF with preview

### ISSUE THREAD

**Issue by sirupsen** [junegunn/fzf#1846]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

`fzf` is my favorite command-line utility, thanks Junegunn! This morning I've been indulging in levelling up a few scripts (unrelated, but `--phony` and the change event changed the game for some CLI full-text index search scripts I use).

I noticed that I think it's _not_ possible to nest `fzf` with `--preview`. `{}` will be default in the `--bind` be replaced with whatever was selected (if unescaped), even if it's another `fzf` command.

Simple, reproducible command:

```bash
fzf --bind "enter:execute[echo {} | fzf --preview 'less {}']"
```

I wanted this for a file-manager script I was doing, where I first browse some files by tags (`grep` matches for `#<word>`), hit enter, and then browse all files that have that tag, previewing them. In my local script, the `echo` is a ` grep`.

**Comment by 0ion9** [comment]
.. per what you've presented, it's possible.

a) Environment variable

```
export NESTEDPREVIEW="less {}"
fzf --bind "enter:execute[echo {} | fzf --preview \"\$NESTEDPREVIEW\"]"
```

b) script
Just put a script containing 

```#!/bin/sh
fzf --preview 'less {}'
```
in the PATH, and pipe into that instead.

All that said, why can't you just escape it?

`fzf --bind "enter:execute[echo {} | fzf --preview 'less \{}']"` seems to me to produce the expected result.

**Comment by sirupsen** [comment]
@0ion9 you're absolutely right. I had escaped with `\{\}`, not `\{}`. That worked, thanks a lot, really appreciate it! 👏 🥇
