### ISSUE TITLE
Result of 'fzf' pasted to prompt/command line instead of stdout

### ISSUE THREAD

**Issue by Empyreans** [junegunn/fzf#1849]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

This is not an issue, more of a question.
My plan is to have keybindings for the following:

* search for directories at home
* search for files at home
* search for directories at current directory
* search for files at current directory

I want to bind keys to commands like `fd -t d | fzf`, select the one I want, and want it to be printed to my prompt for flexibility.
This is exactly what CTRL + T does, and I have also looked up the function that is triggered to see how this is achieved, but sadly, it goes completely over my head. It seems to use functions from `vi-insert` and `emacs-standard`.
Google searches have also left me without answers. I'm not sure I'm phrasing the question correctly.

**Comment by arkku** [comment]
If you're willing to switch to `zsh`, the solution is trivial: `print -z -- my new command-line`.

**Comment by Empyreans** [comment]
> If you're willing to switch to `zsh`, the solution is trivial: `print -z -- my new command-line`.

Thanks for the tip! Forgive me the newbie question, but how would I go about implementing this with `fd -t d | fzf` ?

**Comment by arkku** [comment]
> > If you're willing to switch to `zsh`, the solution is trivial: `print -z -- my new command-line`.
> 
> Thanks for the tip! Forgive me the newbie question, but how would I go about implementing this with `fd -t d | fzf` ?

Something like this works:

``` zsh
fz() {
    local sels=( "${(@f)$(fd --color=always . "${@:2}" | fzf -m --height=25% --reverse --ansi)}" )
    [ -n "$sels" ] && print -z -- "$1 ${sels[@]:q:q}"
}
```

Usage is: `fz <somecommand> [args to fd]`, e.g., `fz cd -t d` would make the command-line be `cd chosendirectory`. Since the command is not executed, you can type additional arguments for the command before pressing return.

Another way to use fzf is with autocompletion, for example:

```
func ffd() {
    fd --color=always "$@" | fzf --ansi
}
```

Then you would use it like: <code>$ git add `ffd -t d`<kbd>Tab</kbd></code> and the autocompletion would run the fzf and expand the selection onto the command-line.

**Comment by LuRsT** [comment]
@Empyreans, did you manage to get the function to work?

**Comment by junegunn** [comment]
@Empyreans You might want to read through https://junegunn.kr/2016/07/fzf-git/ to learn how to make bash and zsh bindings that paste selected items to the command line.

**Comment by pete-may** [comment]
@Empyreans You can achieve what you want by wrapping `fd -t d | fzf` with command substitution e.g. `$(fd -t d | fzf)`. Then using @arkku's suggestion you can run `print -z -- $(fd -t d | fzf)` to get it to print nicely to the console. I use `alias v='print -z -- nvim $(fzf)'` in a similar way.

**Comment by optio50** [comment]
Maybe this is what you are looking for? https://www.freecodecamp.org/news/fzf-a-command-line-fuzzy-finder-missing-demo-a7de312403ff/
fuzzy completion can be triggered with TAB if the word before the cursor ends with the trigger sequence which is by default ** TAB
type nano ~/path/**
fzf will insert the selection on the current line at position
