### ISSUE TITLE
Feature request: FZF_PATH_COMPLETION_OPTS and FZF_DIR_COMPLETION_OPTS

### ISSUE THREAD

**Issue by jannes** [junegunn/fzf#1850]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [x] zsh
    - [x] fish
    
## Problem / Steps to reproduce

At the moment it is not possible to pass `--preview` option specific to files/directories in the FZF_COMPLETION_OPTS because it is used for both path and dir completion.

By adding FZF_PATH_COMPLETION_OPTS and FZF_DIR_COMPLETION_OPTS one could pass specific options in the `_fzf_path_completion` and `_fzf_dir_completion` routines letting the user have custom `--preview` options for path and directory completion.

**Comment by izaakm** [comment]
Kind of related #1647

**Comment by junegunn** [comment]
Related: #1809

However, I'm against the idea of adding FZF_PATH_COMPLETION_OPTS and FZF_DIR_COMPLETION_OPTS. Because then we would have to add FZF_KILL_COMPLETION_OPTS,  FZF_SSH_COMPLETION_OPTS,  FZF_WHATEVER_COMPLETION_OPTS, and it becomes quickly unmanageable.

For now, your best option is to redefine `_fzf_path_completion` with additional fzf options in your configuration file.

**Comment by junegunn** [comment]
But `_fzf_path_completion` and `_fzf_dir_completion` are exceptional cases.

We need a generic solution for [`_fzf_complete_*`](https://github.com/junegunn/fzf/wiki/Examples-(completion)#writing-custom-fuzzy-completion).  I'll think about it when I get some time.

**Comment by jannes** [comment]
Okay, I understand.

> ```shell
> _fzf_path_completion() {
>   __fzf_generic_path_completion _fzf_compgen_path "-m --preview 'cat {}'" "" "$@"
> }
> ```

I have tried this, but it does not work. For your example I am getting `**unknown option: {}` when trying to do the completion. I think it may have something to do with how the single quote within the string variable, but I don't know any bash scripting. Could you check what goes wrong there?

**Comment by junegunn** [comment]
Please check out https://github.com/junegunn/fzf/commit/52154153150d0014a76ef8b429b73c590cb7f755 instead.

If `_fzf_comprun` function is defined, fuzzy completion will use it to launch fzf, so you can specify whatever options you want in the implementation.

**Comment by jannes** [comment]
very cool, thank you so much!
