### ISSUE TITLE
cause error when execute fzf fucntion with popwin 

### ISSUE THREAD

**Issue by jiahut** [junegunn/fzf#1851]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

1.  configure the `g:fzf_layout` , eg: 
```
let g:fzf_layout = {  'window': { 'width': 0.8, 'height': 0.6 } } 
```
2. execute the command

> vim  -c History 

or

>vim -c Files

it will report :

```
Error detected while processing function <SNR>84_VimEnter:

E994: Not allowed in a popup window

```
but after Press Enter or any other key twice, it will show popup window

**Comment by LuRsT** [comment]
Hi @jiahut, what's your vim version? My guess would be that your vim version doesn't support the pop up, but you do see it after pressing any key.

Could it be another config in your vimrc? I reproduced your line on my config and it worked perfectly (I might steal it :wink: )

**Comment by jiahut** [comment]
@LuRsT  Sorry to reply to you now, I have been busy recently。

the relevant code is as follows：

``` vimscript

Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
Plug 'junegunn/fzf.vim'

let g:fzf_layout = { 'window': { 'width': 0.8, 'height': 0.6 } }

```

**Comment by LuRsT** [comment]
Hi @jiahut 
That's exactly how I tried to reproduce your issue, and I couldn't if you still have this issue, what are your vim/neovim and fzf version you're using? (Also, run `:PlugUpdate` to get the up to date version for fzf and the plugin)

**Comment by jiahut** [comment]
Hi @LuRsT  
I make a docker image to feedback my problem.

> cd /tmp/ 

> curl -LOk  https://gist.githubusercontent.com/jiahut/ce6b03f0f0167037e2e6526e70dd4945/raw/d068a241539115c37e4df5c06cd876b6715be5f6/vimrc 

> docker run  -it --rm -v $PWD/vimrc:/root/.vimrc --entrypoint bash jiahut/vim8

after inside docker , type vim and  `:PlugInstall`   then back to bash: 

> vim -c Files

The following error message will be displayed. 

![Not allowed in Popwin](https://user-images.githubusercontent.com/1067691/75622705-4c592780-5bde-11ea-9cf6-7d7860c0e2aa.png)

**Comment by junegunn** [comment]
Errors are printed only when you open a pop-up window during Vim startup (`-c Files`). It works fine after Vim is started. i.e. `:Files`. This is probably an issue of Vim and I'm doubtful that fzf can do anything about it. https://github.com/vim/vim/issues/5666 seems related.

A workaround would be to defer running the command using VimEnter autocmd:

```vim
vim -c 'autocmd! VimEnter * Files'
```

**Comment by LuRsT** [comment]
On the docker environment, there's something odd going with either the CTRL_T binding or ALT_C where there's an error, so I don't think it's a good enviroment to test, I couldn't get it work even after vim initialised, so I don't think it's the right way to reproduce the problem.

**Comment by jiahut** [comment]
@junegunn  thinks, it works great.

**Comment by jiahut** [comment]
@junegunn  after the upgrade `fzf`

the blew workaround encounter　failure

> vim -c 'autocmd! VimEnter * Files'
