### ISSUE TITLE
fzf started in Vim's popup window does not work

### ISSUE THREAD

**Issue by doums** [junegunn/fzf#1852]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [x] fish
    
## Problem / Steps to reproduce
After I added `let g:fzf_layout = { 'window': { 'width': 0.9, 'height': 0.6 } }` to my `.vimrc` I get the following error when I enter the `:Files` command and fzf is not opened:
```
Error occured fzf#vim#files[15]..<SNR>86_fzf[18]..fzf#run[64]..<SNR>42_execute_term[3]..<SNR>42_split :
ligne    9 :
E731: Using a dictionary as a string
press ENTER or type any command
```
However I use vim 8.2 with the popup window feature enabled.
fzf version 0.20.0.

**Comment by douglarek** [comment]
Maybe you should update fzf to the latest not homebrew version.

**Comment by doums** [comment]
I'm on Linux, I don't use the crappy homebrew, I installed fzf via pacman, the archlinux "package" manager:
```
$ pacman -Qs fzf
local/fzf 0.20.0-1
    Command-line fuzzy finder
```

**Comment by junegunn** [comment]
`s/homebrew/pacman/` and the comment is relevant.

You need to use the latest Vim plugin file on GitHub master, not the one in 0.20.0. If you use vim-plug, then it's `Plug 'junegunn/fzf'`.

**Comment by doums** [comment]
I don't understand you very well,

> s/homebrew/pacman/ and the comment is relevant.

What does it mean ?

In my `.vimrc` I have
```
Plug '/usr/bin/fzf'
Plug 'junegunn/fzf.vim' 
```
If I replace the first by `Plug 'junegunn/fzf'` this will install fzf through vim-plug if I'm not mistaken, then duplicate fzf on my system.
Maybe I have to wait the new release? (may be can I ask you why you have not released it yet ?)

**Comment by ebj-autoproff** [comment]
I had the same problem on one of my computers, but not the other. 
For me the solution was to update the plugins by running a `:PlugUpdate` from within Vim and then either source the config or restart Vim.

**Comment by esbenboye** [comment]
I had the same problem on one of my computers, but not the other.
For me the solution was to update the plugins by running a `:PlugUpdate` from within Vim and then either source the config or restart Vim.
