### ISSUE TITLE
Popup window doesn't work as expected fzf not inside popup

### ISSUE THREAD

**Issue by ApplicationDeveloper** [junegunn/fzf#1853]
- [ ] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

Compiled vim from source v8.2.0210. 
Tried with :Files , :Ag and :FZF  buffer does now show inside popup window. 
The border doesn't show if you start vim with a file and then execute :Files / :Ag. But when you start vim with opening a file then execute :Files then the border shows.

![image](https://user-images.githubusercontent.com/10027925/73813803-19f51e00-481c-11ea-9211-0175a8884f72.png)

I use VimPlug. with these config in .vimrc. I also tried to use NeoVim with .vimrc copied to init.vim and it works fine.

Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
Plug 'junegunn/fzf.vim

let g:fzf_layout = { 'window': { 'width': 0.5, 'height': 0.6 } }

com! -bar -bang Ag call fzf#vim#ag(<q-args>, fzf#vim#with_preview({'options': '--delimiter=: --nth=4..'}, 'right'), <bang>0)

Already did PlugUpdate all are already up to date.
https://github.com/junegunn/fzf/commit/0896036266dc951ac03c451f1097171a996eb412

**Comment by junegunn** [comment]
Can you reproduce the problem with [a minimal configuration file](https://gist.githubusercontent.com/junegunn/6936bf79fedd3a079aeb1dd2f3c81ef5/raw)?

```sh
vim -Nu <(curl https://gist.githubusercontent.com/junegunn/6936bf79fedd3a079aeb1dd2f3c81ef5/raw)
```

**Comment by ApplicationDeveloper** [comment]
Thank you! I found the culprit. Sorry for leaving out the plugins I used.
For some reason this plugin doesn't work with fzf in Vim but not does in NeoVim.
Plug 'tadaa/vimade' 
It fade's / darken onfocused windows
