### ISSUE TITLE
How to make `ccat **<TAB>` work?

### ISSUE THREAD

**Issue by yanzhang0219** [junegunn/fzf#1854]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish
    
## Problem / Steps to reproduce
How to make fzf support ccat? When I run `ccat **<TAB>`, fzf will work.
I have tried execute in Bash `_fzf_setup_completion ccat`, but it seems that it doesn't work. 
Thank you very much

**Comment by junegunn** [comment]
```sh
_fzf_setup_completion path ccat
```

should work.

**Comment by yanzhang0219** [comment]
Thank you so much!
