### ISSUE TITLE
fzf not in /bin

### ISSUE THREAD

**Issue by holzboa** [junegunn/fzf#1855]
- [x ] I have read through the manual page (`man fzf`)
- [ x] I have the latest version of fzf
- [ x] I have searched through the existing issues

## Info

- OS
    - [x ] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x ] bash
    - [ ] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

I followed the git-method to install as fzf is no longer available via apt. I did this before on Feren OS without problems.
Install finishes without errors but **fzf is not in /bin**.
I did it again and i got this:

 ./install
Downloading bin/fzf ...
  - Already exists
  - Checking fzf executable ... 0.20.0
Do you want to enable fuzzy auto-completion? ([y]/n) y
Do you want to enable key bindings? ([y]/n) y

Generate /home/deep/.fzf.bash ... OK

Operating System: Deepin 15.11
Kernel: Linux 4.15.0-30deepin-generic
Architecture: x86-64

**Comment by junegunn** [comment]
Install script doesn't put fzf binary inside `/bin`. It downloads the file inside `bin` directory relative to the script. e.g. If you cloned fzf in `~/.fzf`, fzf will be downloaded as `~/.fzf/bin/fzf`.

And `~/.fzf.bash` will add the directory to your `$PATH`, so fzf becomes available.

**Comment by holzboa** [comment]
Thanks a lot - i forgot to run 
$ source ~/fzf.bash

Now it works.
