### ISSUE TITLE
Floating windows not respecting `g:fzf_colors`?

### ISSUE THREAD

**Issue by jesseleite** [junegunn/fzf#1858]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

With the following [floating window](https://github.com/junegunn/fzf.vim/issues/821) `fzf_layout` and `fzf_colors` settings, it's not rendering colours within the same as if I had not setup a floating window...

```vim
let g:fzf_layout = { 'window': { 'width': 1, 'height': 0.5, 'yoffset': 1, 'border': 'horizontal' } }

let g:fzf_colors = {
  \ 'fg':      ['fg', 'Normal'],
  \ 'bg':      ['bg', 'Normal'],
  \ 'hl':      ['fg', 'Label'],
  \ 'fg+':     ['fg', 'CursorLine', 'CursorColumn', 'Normal'],
  \ 'bg+':     ['bg', 'CursorLine', 'CursorColumn'],
  \ 'hl+':     ['fg', 'Label'],
  \ 'info':    ['fg', 'Comment'],
  \ 'border':  ['fg', 'Ignore'],
  \ 'prompt':  ['fg', 'Function'],
  \ 'pointer': ['fg', 'Statement'],
  \ 'marker':  ['fg', 'Conditional'],
  \ 'spinner': ['fg', 'Label'],
  \ 'header':  ['fg', 'Comment'] }
```

Example without floating window:

![Screen Shot 2020-02-06 at 1 27 42 PM](https://user-images.githubusercontent.com/5187394/73966711-8dfaf900-48e4-11ea-8f48-60420f25f8d1.png)

Example with floating window:

![Screen Shot 2020-02-06 at 1 28 12 PM](https://user-images.githubusercontent.com/5187394/73966720-92271680-48e4-11ea-88d7-eefebc89292b.png)

And my current `highlight` settings for `Label` there:

![Screen Shot 2020-02-06 at 1 30 06 PM](https://user-images.githubusercontent.com/5187394/73966848-cef30d80-48e4-11ea-8704-ec90a23c4da5.png)

**Comment by jesseleite** [comment]
@junegunn, The thing that confuses me most is the color inconsistency between the new `window` layout, and the default layout 🤔  Any thoughts to why this might be?

**Comment by junegunn** [comment]
No idea, it works for me. Have you tested it on both Vim and Neovim? Is `&termguicolors` 0 or 1?

**Comment by jesseleite** [comment]
Just Vim, not a Neovim user.  Also `&termguicolors` is `0` for me.

**Comment by jesseleite** [comment]
Fwiw, [these are my fzf vim customizations](https://github.com/jesseleite/dotfiles/blob/master/vim/plugin-config/fzf.vim).  Not sure if the way I'm configuring my colours sheds any light?

**Comment by jesseleite** [comment]
@junegunn Could it have something to do with fzf's buffer filetype/syntax differing between the default layout and floating window layout?  (Not sure if that's a thing, or if I'm out in left field)

**Comment by jesseleite** [comment]
@junegunn Could it have something to do with fzf's buffer filetype or colorscheme differing between the default layout and floating window layout?  (Not sure if that's a thing, or if I'm out in left field)

**Comment by junegunn** [comment]
Open up a terminal buffer (`:terminal`) inside Vim, start fzf (or any other program that prints colors) and see if the colors look different when you run it outside of Vim.

**Comment by jesseleite** [comment]
@junegunn Weird, in `:terminal`, fzf is rendering different colours than even the two above examples.  Here's a gif screencast of all three...

![Screen Capture on 2020-02-14 at 08-54-27](https://user-images.githubusercontent.com/5187394/74537411-088ccf80-4f08-11ea-9de8-0fba017e2fde.gif)

Notice the highlighted search term is yellow in the default fzf layout, brownish-orange in the floating window layout, and light green within `:terminal`.

**Comment by junegunn** [comment]
Yeah, for some reason, built-in terminals of Vim and Neovim both use their own palette for ANSI base colors. See `:help terminal-size-color` to find out how to configure the colors to match the colors of your terminal emulator theme. But better yet, you might want to this as an opportunity to set up 24-bit colors for the terminal (`&termguicolors`) so fzf looks identical regardless of the color palette.

```vim
:set termguicolors
:echo fzf#wrap()
{'options': '''--color=bg+:#3F3F3F,bg:#4B4B4B,border:#6B6B6B,spinner:#98BC99,hl:#719872,fg:#D9D9D9,header:#719872,info:#BDBB72,pointer:#E12672,marker:#E17899,fg+:#D9D9D9,prompt:#98B
EDE,hl+:#98BC99''  --expect=ctrl-v,ctrl-x,ctrl-t', 'sink*': function('129'), 'window': {'width': 0.9, 'height': 0.6}, '_action': {'ctrl-v': 'vsplit', 'ctrl-x': 'split', 'ctrl-t': 't
ab split'}}

:set notermguicolors
:echo fzf#wrap()
{'options': '''--color=bg+:236,bg:237,border:240,spinner:108,hl:65,fg:252,header:65,info:143,pointer:161,marker:168,fg+:252,prompt:110,hl+:108''  --expect=ctrl-v,ctrl-x,ctrl-t', 'si
nk*': function('131'), 'window': {'width': 0.9, 'height': 0.6}, '_action': {'ctrl-v': 'vsplit', 'ctrl-x': 'split', 'ctrl-t': 'tab split'}}
```

**Comment by jesseleite** [comment]
@junegunn Forget terminal for a moment though.  It does not bother me that fzf in Vim renders differently than fzf in my terminal, I'm totally fine with that.  I'm specifically wondering why with these `g:fzf_colors` settings:

```
let g:fzf_colors = {
  \ 'fg':      ['fg', 'Normal'],
  \ 'bg':      ['bg', 'Normal'],
  \ 'hl':      ['fg', 'Label'],
  \ 'fg+':     ['fg', 'CursorLine', 'CursorColumn', 'Normal'],
  \ 'bg+':     ['bg', 'CursorLine', 'CursorColumn'],
  \ 'hl+':     ['fg', 'Label'],
  \ 'info':    ['fg', 'Comment'],
  \ 'border':  ['fg', 'Ignore'],
  \ 'prompt':  ['fg', 'Function'],
  \ 'pointer': ['fg', 'Statement'],
  \ 'marker':  ['fg', 'Conditional'],
  \ 'spinner': ['fg', 'Label'],
  \ 'header':  ['fg', 'Comment'] }
```

I see different colors with and without the following `g:fzf_layout` floating window config:

```
let g:fzf_layout = { 'window': { 'width': 1, 'height': 0.5, 'yoffset': 1, 'border': 'top' } }
```

For example, everywhere else in Vim, `Label` renders as yellow, including where I'm using it within `g:fzf_colors`.  However, as soon as I enable the new floating `window` mode on `g:fzf_layout`, not all of my `g:fzf_colors` settings are respected?  And how is `termguicolors` relevant?

**Comment by junegunn** [comment]
`:echo fzf#wrap()` and you'll see the `--color` options generated according to `g:fzf_colors`. An ANSI color code less than 16 is a base color that can be rendered differently.

fzf on regular Vim by default doesn't start in a terminal buffer. It starts below Vim using `--height` option (related #1860). When you configure it to use a pop-up window, however, it's no longer possible to use `--height` option, and fzf has to start in a terminal buffer. So that's where the color palette matters.

If `&termguicolors` is used, it will generate 24-bit colors (e.g. `--color=bg+:#3F3F3F`), which should appear the same regardless of the color palette.

**Comment by jesseleite** [comment]
@junegunn Ah this is starting to make more sense.  That said, why would my fzf `hl` render as green when fzf is run manually in a `:Terminal` window, but orangey-brown when fzf is running via a terminal buffer for floating popups.  Shouldn't those at least render colors consistently with each other, as both are terminal output within Vim?
