### ISSUE TITLE
Inconsistent behavior with cyrillic

### ISSUE THREAD

**Issue by schmooser** [junegunn/fzf#186]
Hi Junegunn,

I found that `fzf` works strange with cyrillic.

This example works as expected:

    $ printf "roW1\nROW2\nrow3\nRow4\n" | fzf

![screen shot 2015-04-13 at 23 32 39](https://cloud.githubusercontent.com/assets/480160/7124916/7e650762-e235-11e4-933e-6f8a5a98ff77.png)
![screen shot 2015-04-13 at 23 32 24](https://cloud.githubusercontent.com/assets/480160/7124918/7e6cd9ec-e235-11e4-84de-cb917c7e16a9.png)

But this one ("row" translated to Russian "строка") behaves differently (it fails to find capital letters):

    $ printf "строКА1\nСТРОКА2\nстрока3\nСтрока4\n" | fzf

![screen shot 2015-04-13 at 23 34 37](https://cloud.githubusercontent.com/assets/480160/7124954/ba49afb2-e235-11e4-8b1d-d9bf97ab3e82.png)
![screen shot 2015-04-13 at 23 33 07](https://cloud.githubusercontent.com/assets/480160/7124917/7e69108c-e235-11e4-93a0-27f650fedfb5.png)

Environment: OS X Mavericks, zsh/bash, fzf 0.9.7, LANG="ru_RU.UTF-8".

**Comment by junegunn** [comment]
Thanks for the report. The cause of the problem is that fzf uses `strings.ToLower()` function to make the query lowercase, but it does not use it and instead manually processes english alphabets only during search for much better performance. I'll see what I can do.

**Comment by schmooser** [comment]
Maybe then do also string.ToLower() to a search string? Now fzf lose some results :-(.

**Comment by junegunn** [comment]
Well, just fixing it is trivial. But in order to fix it without performance regression, I'll have to evaluate several options. I'll let you know of the progress.

**Comment by schmooser** [comment]
Ok, thank you! `fzf` rocks!

**Comment by junegunn** [comment]
Hey, I fixed the bug and released 0.9.8. Performance overhead of the fix is around 5%, but it won't be really noticeable. (e.g. +0.3 second for filtering 3 million lines. Of course, correctness is much more important than minor slowdown.)

**Comment by schmooser** [comment]
I checked version 0.9.8. Everything works just fine! Thanks for blazingly fast fix.
