### ISSUE TITLE
fzf shows no results in tab-completion of command expansion in zsh and fish

### ISSUE THREAD

**Issue by expipiplus1** [junegunn/fzf#1863]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
- Shell
    - [x] zsh
    - [x] fish
    
## Problem / Steps to reproduce

- Enter a zsh or fish shell
- observe that tab-completing a command expansion works
  - type `$(echo hello)<Tab>`
  - observe that the prompt now contains `hello`
- observe that tab-completing with fzf works for explicit input 
  - type `$(echo hello | fzf)<Tab>`
  - observe that fzf shows `hello`
  - select `hello`
  - observe that the prompt now contains `hello`
- observe that fzf on its own does not allow you to select any results
  - type `$(fzf)<Tab>`
  - observe that there are no items to select in fzf
  
For the final case I would expect to be able to select from the files under the current directory.

A workaround is to run `$(find . | fzf)`.

It's not clear to me if this is:
  - expected behavior
  - a bug in fzf
  - bugs in zsh and fish

**Comment by LuRsT** [comment]
Hi @expipiplus1,

What's your `$FZF_DEFAULT_COMMAND`? I managed to almost reproduce your scenario, and if I'm in a directory that's empty, then no files show up, but if there are, I most certainly can see the files to pick, this is my `$FZF_DEFAULT_COMMAND`: `rg --files --no-ignore --hidden --follow --glob "!.git/*"`.

Try changing the environment variable and try again.

Also, the way you wrote your commands is a bit odd, does `$(fzf)<Tab>` mean

```sh
$ fzf
<tab>
```

Meaning, running the command fzf by itself, and pressing tab afterwards? This syntax is more intuitive to me.

**Comment by expipiplus1** [comment]
Hi @LuRsT,

`FZF_DEFAULT_COMMAND` isn't set, there's no change in behavior when it is set.

By `$(fzf)<TAB>` I meant tab completing the command substitution, i.e. having entered `$(fzf)` into the terminal (and not pressing CR) press the `Tab` key to trigger zsh's or fish's completion (replacing `$(fzf)` with the standard output of running `fzf`).

**Comment by junegunn** [comment]
I've never used fzf that way, because I'm a bash user and bash doesn't expand command substitution on tab. So I am not completely sure what is going on under the hood.

Anyway, it looks like in that case, the standard input for the command is not the tty device, so fzf reads from that non-tty input zsh injects instead of launching the default command.

```sh
[ -t 0 ] || echo "stdin is not tty"
  #

: | ([ -t 0 ] || echo "stdin is not tty")
  # stdin is not tty

$([ -t 0 ] || echo "stdin is not tty")<TAB>
  # command-line becomes "stdin is not tty"
```

So in order to use fzf in this scenario, you'll have to manually feed in some input to fzf through pipe. I wouldn't say that this is a bug of fzf or a bug of zsh. It's just how zsh and fzf operates.

**Comment by expipiplus1** [comment]
Makes sense, thanks!

**Comment by expipiplus1** [comment]
For posterity, psprint on #zsh suggested using https://raw.githubusercontent.com/psprint/zsh-navigation-tools/master/znt-usetty-wrapper. Indeed `$(zsh znt-usetty-wrapper fzf)<Tab>` works exactly as expected.

**Comment by AndydeCleyre** [comment]
I'll note here that in Zsh, `$(<$TTY fzf)` will tab-complete.
