### ISSUE TITLE
FZF How To Install Keybindings

### ISSUE THREAD

**Issue by jrock2004** [junegunn/fzf#1866]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

I just did `sudo apt-get install fzf`. But how do I enable keybinding so I can do ctrl+r to bring up fzf search? I know when I git clone there is an install script. I cannot find where the install.sh file is or is there another way?

**Comment by currybullen** [comment]
There are several files containing keybindings for different shells, find the appropriate one and source it. For example, to enable the bindings for bash:

```
$ dpkg -L fzf | grep bindings
/usr/share/doc/fzf/examples/fish_user_key_bindings.fish
/usr/share/doc/fzf/examples/key-bindings.bash
/usr/share/doc/fzf/examples/key-bindings.fish
/usr/share/doc/fzf/examples/key-bindings.zsh
/usr/share/fish/vendor_functions.d/fzf_key_bindings.fish
$ . /usr/share/doc/fzf/examples/key-bindings.bash
```

**Comment by jrock2004** [comment]
Thank you. This make sense.

**Comment by wlad** [comment]
THIS

>There are several files containing keybindings for different shells, find the appropriate one and source it. For example, to enable the bindings for bash:
>    ```
>    $ dpkg -L fzf | grep bindings
>    /usr/share/doc/fzf/examples/fish_user_key_bindings.fish
>    /usr/share/doc/fzf/examples/key-bindings.bash
>    /usr/share/doc/fzf/examples/key-bindings.fish
>    /usr/share/doc/fzf/examples/key-bindings.zsh
>    /usr/share/fish/vendor_functions.d/fzf_key_bindings.fish
>    $ . /usr/share/doc/fzf/examples/key-bindings.bash
>    ```
> Stick . /usr/share/doc/fzf/examples/key-bindings.bash in ~/.bashrc to make it permanent.

ought to be in the README

**Comment by pyaf** [comment]
It'd be great if this is added to the readme. @jrock2004 What do you suggest? I'd like to contribute if you'd say so.

**Comment by jrock2004** [comment]
I would think a section to enable keybindings when installing via sudo would be nice

**Comment by SoftwareApe** [comment]
It is mentioned in the readme to use `apt-cache search fzf`, wherein you find and additional readme. It could be more prominent though, maybe with an example for Ubuntu.

**Comment by paulsammut** [comment]
`apt-cache search fzf` doesn't help with this. This info should be in the docs.

Here's the output: 
```
➜  examples apt-cache show fzf
Package: fzf
Architecture: amd64
Version: 0.29.0-1
Built-Using: golang-1.17 (= 1.17.3-1ubuntu1), golang-github-mattn-go-isatty (= 0.0.14-1), golang-github-mattn-go-runewidth (= 0.0.13-2), golang-github-mattn-go-shellwords (= 1.0.10-2), golang-github-rivo-uniseg (= 0.2.0-1), golang-github-saracen-walker (= 0.1.2-1), golang-golang-x-sync (= 0.0~git20210220.036812b-1), golang-golang-x-sys (= 0.0~git20211216.1d35b9e-1), golang-golang-x-term (= 0.0~git20210615.6886f2d-1)
Priority: optional
Section: universe/utils
Origin: Ubuntu
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Debian Go Packaging Team <team+pkg-go@tracker.debian.org>
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Installed-Size: 2428
Filename: pool/universe/f/fzf/fzf_0.29.0-1_amd64.deb
Size: 926252
MD5sum: f057f689bbb6410236a670011efc1763
SHA1: 9720aac30c222270586bffb8e2c287f11f314260
SHA256: d5b31167ee4ac4a2e1cc18a583b65b66fe122631a7a5b2bec0b6a53aa03c22eb
SHA512: ee1a85897c466f77790ea234f603009c372df9e73514fd229ac912dabcd97d1983fc2f758dbeb05f710e0d8d2c09a89865e6af9a7fd86c3a1b97fcffce233b65
Homepage: https://github.com/junegunn/fzf
Description: general-purpose command-line fuzzy finder
Description-md5: a0bfeecf96a19354d63fcb504b7530c9
```

**Comment by shmerl** [comment]
It would be good to add this detail to the readme indeed. Installing it with Debian package doesn't enable any key bindings by default, only provides a script for it like above which has to be sourced to enable them.

**Comment by salim-b** [comment]
To manually install the latest version of the Bash key bindings:

```sh
mkdir -p $HOME/.local/share/fzf
wget --directory-prefix=$HOME/.local/share/fzf https://raw.githubusercontent.com/junegunn/fzf/master/shell/key-bindings.bash
chmod +x $HOME/.local/share/fzf/key-bindings.bash
```

Then add the following line to your `~/.bash_rc` file:

```sh
# source fzf key bindings script
command -v fzf > /dev/null && [ -f ~/.local/share/fzf/key-bindings.bash ] && . ~/.local/share/fzf/key-bindings.bash || true
```

Make sure to use the latest fzf version in combo with the above.

**Comment by httpete** [comment]
Thank you @salim-b - but wow there has to be a nicer / more documented way to do that. I like using dnf to install and maintain, but the install script was not available on my Rocky.

**Comment by dulearnaux** [comment]
`source key-bindings.bash` doesn't seem to work for me on Ubuntu 22.04.   Pressing `Ctrl+t` just results in the output: `not a valid integer: 20+`.  The ** <TAB> doesn't do anything either.

**Comment by insidexino** [comment]
In my case, the problem was due to invalid executable. 

If I just run `fzf`, then I got the `not a valid integer: 20+`.
I just reinstall fzf executable with `install` command in repository, and solved the problem.
