### ISSUE TITLE
Cannot brew upgrade fzf

### ISSUE THREAD

**Issue by jesseleite** [junegunn/fzf#1870]
When I try to `brew upgrade fzf` on mac, I get `Warning: fzf 0.20.0 already installed`.  I know there are other ways to install fzf on mac, but curious if you think another fzf release will be tagged again soon? 🙂

**Comment by junegunn** [comment]
Hopefully soon, but there are some outstanding issues and pull requests I'd like to include in the next release. Note that brew formula of fzf supports `--HEAD` option, so you can build and install fzf from the latest source.

**Comment by jesseleite** [comment]
Ah good call, will use the HEAD option, thanks!
