### ISSUE TITLE
Integrate fzf with Überzug 

### ISSUE THREAD

**Issue by linxed** [junegunn/fzf#1871]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

I love the preview option it lets me easily chose the right file to open. It would be much appreciated if we could do the same with images.

https://github.com/seebye/ueberzug

Do you think it would be possible to implement ?

**Comment by junegunn** [comment]
Have you tested this?

https://github.com/seebye/ueberzug/blob/master/examples/fzfimg.sh

**Comment by linxed** [comment]
I have seen it but i did not understand what to do. 

As i think about it it should be the other way around instead of asking you for help with the integration i should have asked the author of that pluggin.
