### ISSUE TITLE
End standout escape sequence not working in preview.

### ISSUE THREAD

**Issue by MaienM** [junegunn/fzf#1877]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

The start standout escape sequence works fine in the preview, but the corresponding end sequence appears to not be working. The reset-all sequence works fine, and does end the standout mode.

``` bash
echo "AAA $(tput smso)BBB$(tput rmso) CCC$(tput sgr0) DDD"
echo foo | fzf --preview='echo "AAA $(tput smso)BBB$(tput rmso) CCC$(tput sgr0) DDD"' --height=5
```

![2020-02-17-151522_955x186_scrot](https://user-images.githubusercontent.com/583129/74661501-5ddf1000-5198-11ea-8009-9d7b645d40c3.png)

**Comment by junegunn** [comment]
Thanks for the report. It should be fixed now.
