### ISSUE TITLE
fzf-select on fish having trouble with bigger data

### ISSUE THREAD

**Issue by aleprovencio** [junegunn/fzf#1879]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [x] fish
    
## Problem / Steps to reproduce
Hello,
I have the wiki's suggested `fzf-select` function that is triggered by a binding on my `fish` configuration. I have noticed that it is crashing when many entries are processed, like:

`pacman -Qlq fzf<fzf-select bind>` will work fine while `pacman -Qlq linux<fzf-select bind>` will crash.

**Comment by 0ion9** [comment]
Define "crash" more explicitly. What exactly happens?

My immediate thought was that this might be a symptom of [this fish 3.10 bug](https://github.com/fish-shell/fish-shell/issues/6624)  , in which fzf will 'crash' with the error `Failed to read /dev/tty` in some difficult-to-quantify, timing-dependent way.

**Comment by aleprovencio** [comment]
After the <fzf-select bind> is pressed it will just hang in there forever, no error messages and even `Control+C` won't work (at least it prints a 'Interrupt signal received'), so I'm forced to kill the process or the whole terminal.

I'm using `fish-git` from `archlinux's AUR`, so I guess this is not 3.10 version yet.

**Comment by aleprovencio** [comment]
Update: the AUR version of fish updated to 3.1, and I just made the jump. Issue stays :/

**Comment by 0ion9** [comment]
uh, yeah, if you were using fish-git that probably would have been newer than the 3.1 release, which was made [17 days ago](https://github.com/fish-shell/fish-shell/releases).
Anyway it was a bug that appeared in 3.1, not one that was fixed in 3.1, I might have given you the wrong impression.

**Comment by aleprovencio** [comment]
Hello, @0ion9 
now I'm running `fish 3.1.1` and issue stays :/

Anything I could do to help ?

**Comment by junegunn** [comment]
fish 3.1.1 is broken. See #2008.
