### ISSUE TITLE
reload support for Vim list source?

### ISSUE THREAD

**Issue by myitcv** [junegunn/fzf#1883]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf - 9c293bb
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

I notice in https://github.com/junegunn/fzf/issues/1750 support for reload which is extremely useful. The example at https://github.com/junegunn/fzf.vim#example-advanced-ripgrep-integration shows how to pass a command to `reload`:

```vim
function! RipgrepFzf(query, fullscreen)
  let command_fmt = 'rg --column --line-number --no-heading --color=always --smart-case %s || true'
  let initial_command = printf(command_fmt, shellescape(a:query))
  let reload_command = printf(command_fmt, '{q}')
  let spec = {'options': ['--phony', '--query', a:query, '--bind', 'change:reload:'.reload_command]}
  call fzf#vim#grep(initial_command, 1, fzf#vim#with_preview(spec), a:fullscreen)
endfunction

command! -nargs=* -bang RG call RipgrepFzf(<q-args>, <bang>0)
```

I also note from https://github.com/junegunn/fzf/blob/master/README-VIM.md#fzfrun that it's possible to start `fzf` with a `source` that is a Vim list, e.g.:

```vim
call fzf#run({'source': map(split(globpath(&rtp, 'colors/*.vim')),
            \               'fnamemodify(v:val, ":t:r")'),
            \ 'sink': 'colo', 'left': '25%'})
```

What we would like to be able to do however is reload `fzf` with an updated Vim source list, specifically to use the value returned by a Vim function parameterised by the value input to `fzf`.

The actual use case here is the [LSP workspace symbol](https://microsoft.github.io/language-server-protocol/specifications/specification-3-15/#workspace_symbol) method. The usage we are imaging here is that a value typed in the `fzf` finder would act as a query to the symbol method, and then `fzf` would be used to select the result.

Does this make sense as a use case for `reload`? Could it be make to support a `source` that is an input list?

Many thanks

cc @findleyr

**Comment by junegunn** [comment]
https://github.com/junegunn/fzf.vim/issues/948 should answer your question.

**Comment by myitcv** [comment]
Apologies, my issue search failed to uncover that. Thank you for linking to it.

**Comment by junegunn** [comment]
No worries. People creating issues across two repos, it's rather hard to find actually.
