### ISSUE TITLE
_fzf_complete function can not be interrupted

### ISSUE THREAD

**Issue by doubleloop** [junegunn/fzf#1887]
- [x ] I have read through the manual page (`man fzf`)
- [x ] I have the latest version of fzf
- [x ] I have searched through the existing issues

## Info

- OS
    - [ x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x ] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

Define custom completin:
```zsh
_foo() {
    for i in {1..5}; do
        echo "completion$i"
    done
}

_bar() {
    # this is some slower command, or command that may hang
    sleep 10
    for i in {6..10}; do
        echo -e "bar completion$i"
    done
}

_fzf_complete_foobar() {
    _fzf_complete "--multi --ansi -n 2" "$@" < <(
        _foo
        _bar
    )
}
```

This completion, when triggered, will allow to select foo completions instantly, but the shell is not responding until `_bar` finishes.

**Comment by junegunn** [comment]
Thanks, I've done some research and here's what I've found.

### bash

bash has the same problem, but it is trivial to fix it. All I need to do is to remove unnecessary `cat`

```diff
diff --git a/shell/completion.bash b/shell/completion.bash
index b953cc8..bd94c51 100644
--- a/shell/completion.bash
+++ b/shell/completion.bash
@@ -200,7 +200,7 @@ _fzf_complete() {
   if [[ "$cur" == *"$trigger" ]]; then
     cur=${cur:0:${#cur}-${#trigger}}
 
-    selected=$(cat | FZF_DEFAULT_OPTS="--height ${FZF_TMUX_HEIGHT:-40%} --reverse $FZF_DEFAULT_OPTS $FZF_COMPLETION_OPTS $1" __fzf_comprun "$2" -q "$cur" | $post | tr '\n' ' ')
+    selected=$(FZF_DEFAULT_OPTS="--height ${FZF_TMUX_HEIGHT:-40%} --reverse $FZF_DEFAULT_OPTS $FZF_COMPLETION_OPTS $1" __fzf_comprun "$2" -q "$cur" | $post | tr '\n' ' ')
     selected=${selected% } # Strip trailing space not to repeat "-o nospace"
     if [ -n "$selected" ]; then
       COMPREPLY=("$selected")
```

And we can even kill the running processing with its process ID bash reports, `$!`.

```sh
_fzf_complete_f() {
  _fzf_complete "--multi" "$@" < <(
    echo foo
    sleep 5
    echo bar
  )
  pkill -P $!
}
```

💯 

### zsh

However, this approach doesn't work with zsh, probably for the same reason we can't remove FIFO from the code (see https://github.com/junegunn/fzf/issues/494).

An alternative approach with a minimal change to the API is to pass the file descriptor as the argument instead of feeding it as the standard input and do not use `|`.

```diff
diff --git a/shell/completion.zsh b/shell/completion.zsh
index d5fccad..a378729 100644
--- a/shell/completion.zsh
+++ b/shell/completion.zsh
@@ -115,8 +115,8 @@ _fzf_complete() {
   post="${funcstack[2]}_post"
   type $post > /dev/null 2>&1 || post=cat
 
-  _fzf_feed_fifo "$fifo"
-  matches=$(cat "$fifo" | FZF_DEFAULT_OPTS="--height ${FZF_TMUX_HEIGHT:-40%} --reverse $FZF_DEFAULT_OPTS $FZF_COMPLETION_OPTS" __fzf_comprun "$cmd" ${(Q)${(Z+n+)fzf_opts}} -q "${(Q)prefix}" | $post | tr '\n' ' ')
+  [ $# -lt 3 ] && _fzf_feed_fifo "$fifo"
+  matches=$(FZF_DEFAULT_OPTS="--height ${FZF_TMUX_HEIGHT:-40%} --reverse $FZF_DEFAULT_OPTS $FZF_COMPLETION_OPTS" __fzf_comprun "$cmd" ${(Q)${(Z+n+)fzf_opts}} -q "${(Q)prefix}" < "${3:-$fifo}" | $post | tr '\n' ' ')
   if [ -n "$matches" ]; then
     LBUFFER="$lbuf$matches"
   fi
```

We have to slightly change how we use the function:

```sh
_fzf_complete_f() {
  # Remove '<' before '<('
  _fzf_complete "--multi" "$@" <(
    echo foo
    sleep 5
    echo bar
  )
  # $! is zero, so we can't kill the process
  # pkill -P $!
}
```

It works, but the problem here is that zsh doesn't report the process ID as `$!`, so there's no easy way to kill the still-running process.

### So where do we go from here?

I'd like to do some more research to see if there's a way to fix the problem without changing the API (for zsh). But if it turns out to be not possible, we'll have to extend the API. Among the two suggestions you made, I prefer #1895 though I'd choose `_source` suffix instead of `_func` which seems a little too general.

**Comment by junegunn** [comment]
It looks like we can use `coproc` to avoid the blocking with a minor change to the code (https://github.com/junegunn/fzf/commit/baf882ace741e4d279b6a6d2da467e00f94642f5, still in devel branch)

```sh
_fzf_complete_f() {
  setopt localoptions nomonitor
  coproc (
    echo foo
    sleep 5
    echo bar
  )
  _fzf_complete "--multi" "$@" <&p
  pkill -P $!
}
```

What do you think?

**Comment by junegunn** [comment]
Let me know if this doesn't work for you.

**Comment by doubleloop** [comment]
Hi,
Thx for reply and for the fix!
I just tested the `coproc` solution with zsh and it almost works, the only issue is the extra job controll msg:

```
$ foobar foo
[7]  + 26076 done       ( echo foo; sleep 10; echo bar; )
$ foobar foo
```

I tested with:
```
_fzf_complete_foobar() {
    setopt localoptions nomonitor
    coproc (
        echo foo
        sleep 10
        echo bar
    )
    _fzf_complete "--multi" "$@" <&p
    pkill -P $!
}
```
I tried to fix this but I am not sure how to properly suspend job control messages in this case. Not sure how `nomonitor` works. In this example:
```
_fzf_complete_foobar() {
    setopt localoptions nomonitor
    sleep 10 &
    kill $!
}
```
Output is:
```
$ foobar **
[4]  + terminated  sleep 10
$ foobar **
```

On the other hand with:
```
_fzf_complete_foobar() {
    (sleep 10 &)
    kill $!
}
```
no `terminated` msg is shown.
No msg is also shown when I do global `setopt nomonitor`.

**Comment by junegunn** [comment]
What's your `zsh --version`? I'm using 5.7.1 and `setopt localoptions nomonitor` effectively removes the message.

```sh
setopt interactivecomments

# Note that I appended `|| true` to pkill command to suppress beep
# when the process is already completed.
_fzf_complete_foobar() {
    setopt localoptions nomonitor
    coproc (
        echo foo
        sleep 10
        echo bar
    )
    _fzf_complete "--multi" "$@" <&p
    pkill -P $! || true
}
```

**Comment by doubleloop** [comment]
```
% zsh --version
zsh 5.8 (x86_64-debian-linux-gnu)
% cat ~/.zshrc
path=(~/src/fzf/bin $path)
source ~/src/fzf/shell/key-bindings.zsh
source ~/src/fzf/shell/completion.zsh

setopt interactivecomments

_fzf_complete_foobar() {
    setopt localoptions nomonitor
    coproc (
        echo foo
        sleep 10
        echo bar
    )
    _fzf_complete "--multi" "$@" <&p
    pkill -P $! || true
}
% foobar **
[4]  + done       ( echo foo; sleep 10; echo bar; )
floydd% foobar **
```
note: this is the output with #1921 applied

**Comment by junegunn** [comment]
Can you test it on a clean Docker container?

```sh
# From fzf project root
make docker

# Start zsh
zsh

_fzf_complete_foobar() {
    setopt localoptions nomonitor
    coproc (
        echo foo
        sleep 10
        echo bar
    )
    _fzf_complete "--multi" "$@" <&p
    pkill -P $! || true
}
```

**Comment by doubleloop** [comment]
Just tested, same issue

```
cb7492f61de6# foobar **
[4]  + done       ( echo foo; sleep 10; echo bar; )
cb7492f61de6# foobar **
```
note: here I interrupted completion using `ctrl-c` before `bar` is shown:

```
[4]  + done       ( echo foo; sleep 10; echo bar; )
cb7492f61de6# foobar foo
```
here: I just select `foo` and click enter (before `bar` is shown):

When I just wait with selection until `bar` is shown, it works as expected (no job control msg).

**Comment by junegunn** [comment]
That's strange. I can't reproduce.

https://asciinema.org/a/C5U9dANv00Oo3KyNqACKB9MSa

**Comment by doubleloop** [comment]
We have different versions of zsh inside docker. Maybe you did not update your docker base container for a while (after `docker pull archlinux/base` zsh should be in 5.8):
```
$ docker images | grep archlinux | grep latest
archlinux/base            latest              0f7f9102731f        10 days ago         500MB
```

Here is my rec, I use `ctrl-c` to break completions and in 2 last cases I did select foo with enter. 
There is some non determinism, 1st and 3rd `ctrl-c` did not print ms.
 
![fzf2](https://user-images.githubusercontent.com/2602750/76447918-d5841180-63c9-11ea-96bf-b0a6986f5e4d.gif)

**Comment by junegunn** [comment]
Very interesting. Even after I pulled the latest `archlinux/base:latest`, I still can't reproduce the problem with its zsh 5.8.

**Comment by junegunn** [comment]
Adding `wait` at the end fixes the issue.

```sh
_fzf_complete_foobar() {
    setopt localoptions nomonitor
    coproc (
        echo foo
        sleep 1
        echo bar
    )
    _fzf_complete "--multi" "$@" <&p
    pkill -P $! || true
    wait
}
```

**Comment by doubleloop** [comment]
:+1: just tested and it works as expected. Thx for investigation!
