### ISSUE TITLE
Bash Tab Completion not working

### ISSUE THREAD

**Issue by Jab2870** [junegunn/fzf#1889]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

I have removed my bashrc so am running vanilla bash. I source the two files key-bindings.bash and completion.bash

I try to use the tab completion to complete the kill command. FZF starts and gives me the option to choose a process. After choosing a process, my shell shoes only the process ID, not the whole command or my prompt.

I'm not sure how best to show you what I mean so here is an asciinema recording.

https://asciinema.org/a/0t3KjEEJMLVia41XlS6xscjI6

**Comment by junegunn** [comment]
It looks like a rendering issue though I can't reproduce. Does pressing `CTRL-L` after selecting a process fixes the command line?

**Comment by Jab2870** [comment]
It clears the screen and I am left with the full kill command and my selection

**Comment by junegunn** [comment]
Yeah, that's expected. Anyway, I can't reproduce the problem myself, tested both on bash 3 and bash 5.

```sh
bash --noprofile --norc
source ~/.fzf.bash
```

What's your bash version? Can you test again with another version?

**Comment by Jab2870** [comment]
Hi, thanks for checking

What is `.fzf.bash`? Is that a local file you have?

I am still getting the same issue with bash 5.0.16 and bash 4.4.23

**Bash 5**

```
$ bash --noprofile --norc
bash-5.0$ cd /usr/share/
Display all 366 possibilities? (y or n)
bash-5.0$ cd /usr/share/fzf/
bash-5.0$ ls
completion.bash  completion.zsh  key-bindings.bash  key-bindings.zsh
bash-5.0$ source *.bash
302334 ^C
bash-5.0$ bash --version
GNU bash, version 5.0.16(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
bash-5.0$
```

**Bash 4.4**

```
$ bash4 --noprofile --norc
bash4-4.4$ cd /usr/share/fzf
bash4-4.4$ ls
completion.bash  completion.zsh  key-bindings.bash  key-bindings.zsh
bash4-4.4$ source *.bash
302334 ^C
bash4-4.4$ bash4 --version
GNU bash, version 4.4.23(1)-release (x86_64-unknown-linux-gnu)
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
bash4-4.4$
```

**Comment by junegunn** [comment]
It's a script generated by [the install script](https://github.com/junegunn/fzf/blob/master/install). Nothing particular. It injects fzf into $PATH and loads two bash files.

You might want to check if the problem is still reproducible with the latest source code on GitHub master.

**Comment by Jab2870** [comment]
Hi, thanks. I have just installed the master version and I am still having the issue, however, I just tried a different terminal emulator and it appears to be working in xterm so I assume the issue isn't with fzf now.

Thanks for your help
