### ISSUE TITLE
No Cons in README

### ISSUE THREAD

**Issue by youngtrashbag** [junegunn/fzf#1896]
- [ ] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [x] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [x] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

No Steps Requred, its a Question about the Docs.

### Question

So I noticed you listed Pros, but are there any Cons; and if so would you mind listing them ?

**Comment by youngtrashbag** [comment]
I hope this is not a stupid question, but if so I apologize.

**Comment by junegunn** [comment]
For me, there are no Cons, because I wrote it for myself. YMMV of course.
