### ISSUE TITLE
Missing `=` breaks CTRL+R in bash.

### ISSUE THREAD

**Issue by dterhorst** [junegunn/fzf#1898]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

1. Hit `ctrl+r` in bash.

## Expected

<img width="2551" alt="Screen Shot 2020-02-28 at 2 19 50 PM" src="https://user-images.githubusercontent.com/410570/75580267-73c0c080-5a35-11ea-905b-e487b0b7a49c.png">

## Actual

<img width="2558" alt="Screen Shot 2020-02-28 at 2 18 44 PM" src="https://user-images.githubusercontent.com/410570/75580174-4e33b700-5a35-11ea-9da7-563d4071dbe0.png">

## The Problem

There is a missing `=` after `--query` in the definition of `FZF_DEFAULT_OPTS` in `shell/key-bindings.bash`:

## Patch

```
diff --git a/shell/key-bindings.bash b/shell/key-bindings.bash
index fa485d2..578ae66 100644
--- a/shell/key-bindings.bash
+++ b/shell/key-bindings.bash
@@ -56,7 +56,7 @@ __fzf_history__() {
   output=$(
     builtin fc -lnr -2147483648 |
       last_hist=$(HISTTIMEFORMAT='' builtin history 1) perl -p -l0 -e 'BEGIN { getc; $/ = "\n\t"; $HISTCMD = $ENV{last_hist} + 1 } s/^[ *]//; $_ = $HISTCMD - $. . "\t$_"' |
-      FZF_DEFAULT_OPTS="--height ${FZF_TMUX_HEIGHT:-40%} $FZF_DEFAULT_OPTS --tiebreak=index --bind=ctrl-r:toggle-sort $FZF_CTRL_R_OPTS +m --query $(printf %q "$READLINE_LINE") --read0" $(__fzfcmd)
+      FZF_DEFAULT_OPTS="--height ${FZF_TMUX_HEIGHT:-40%} $FZF_DEFAULT_OPTS --tiebreak=index --bind=ctrl-r:toggle-sort $FZF_CTRL_R_OPTS +m --query=$(printf %q "$READLINE_LINE") --read0" $(__fzfcmd)
   ) || return
   READLINE_LINE=${output#*$'\t'}
   if [ -z "$READLINE_POINT" ]; then
```

**Comment by Jeansen** [comment]
I reverted to the develop branch. Seems to be introduced with commit: 7c447bbdc7adb1fe0c848e171780f68cacf3e80e

**Comment by junegunn** [comment]
Do you always have the issue? I can reproduce the problem, but only when the command-line contains `"` or `'`. An easy fix is to pass the query argument directly to fzf instead of putting it in temporary FZF_DEFAULT_OPTS.

**Comment by Jeansen** [comment]
My history is quite long. And I just tried on another system with a similar long history. There I do not have these problems and I DO have command lines that containg `"` or ''`. For instance

```
 8481  cd i915/
 8482  ls
 8483  cp demoCA/cacert.pem shared
 8484  help test
 8485  vi shared/add_cert_to_apps.sh 
 8486  ls
 8487  sudo lvs
 8488  cd shared
 8489  ls
 8490  cat add_cert_to_apps.sh 
 8491  ./add_cert_to_apps.sh cacert.pem "OMPH Root CA"
 8492  ls ~/.thunderbird/
```
