### ISSUE TITLE
fzf can't preview string with nul byte

### ISSUE THREAD

**Issue by Aloxaf** [junegunn/fzf#1899]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

fzf can't preview strings with nul byte

```zsh
> fzf --preview='echo {}' <<<$'abc\0abc'
```

The nul byte may prevent fzf from spawning new process.

**Comment by junegunn** [comment]
I don't think this is an issue of fzf.

```sh
echo $'abc\0abc'
```

You might want to take a look at https://unix.stackexchange.com/a/174017

**Comment by Aloxaf** [comment]
But in zsh I can have a string that contains NUL byte. So I use NUL as a delimiter, then I came across this problem.
![图片](https://user-images.githubusercontent.com/17017672/75625561-33f70600-5bfa-11ea-80ca-87c8c474145d.png)

**Comment by junegunn** [comment]
I see. But it seems there's no way around it; https://groups.google.com/d/msg/golang-nuts/3aKF5NonPUc/szfZG3kzBwAJ

**Comment by Aloxaf** [comment]
I find I can use `$(<{+f})`, it can bypass this bug.

Thanks for your help.
