### ISSUE TITLE
rg with --hidden causes a glitch

### ISSUE THREAD

**Issue by doums** [junegunn/fzf#1901]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [x] fish
    
## Problem / Steps to reproduce

If I use
`rg --files | fzf` it works fine.
but if I add the --hidden options (to take into account dotfile as well)
`rg --files --hidden | fzf` a graphic glitch happens: the "spinner" is duplicated (one remains static) and all lines are offset by one.

fzf version 0.20.0

Note: the bug does not happen always, for example if I test in my home directory it happens but not if I'm under a subdirectory which does not contain a big amount of files.

**Comment by junegunn** [comment]
It's quite likely that ripgrep is printing error messages to STDERR. See if redirecting it helps:

```sh
# Redirect error messages to /tmp/errors
rg --files --hidden 2> /tmp/errors | fzf

# Or just suppress error messages
rg --files --hidden 2> /dev/null | fzf

**Comment by doums** [comment]
Yes, nice catch, thank you!
