### ISSUE TITLE
fzf-history-widget not appers for bindkey '^R'

### ISSUE THREAD

**Issue by Ruslang** [junegunn/fzf#1902]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [ x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ x] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

When i press Ctrl+R
Then i see widget *bck-i-search: _* 
Insted of fzf-history-widget >

How disable bash widget and replace it with fzf?

**Comment by junegunn** [comment]
I don't know how you installed fzf but generally, key bindings are not enabled by default. See https://github.com/junegunn/fzf#using-homebrew-or-linuxbrew

**Comment by Ruslang** [comment]
Okay
<img width="1390" alt="Screenshot 2020-03-02 at 17 18 33" src="https://user-images.githubusercontent.com/1322225/75684610-331dad00-5caa-11ea-889f-0cf00cfd1453.png">

**Comment by junegunn** [comment]
`source ~/.zshrc`?

**Comment by Ruslang** [comment]
Yes, i restarted iterm and no effect. 
Remapped to CTRL+E.

**Comment by junegunn** [comment]
This definitely looks like a configuration issue which I can't help you with. See if you can reproduce the problem with a minimal configuration file.

https://github.com/junegunn/fzf/issues/1767#issuecomment-593368039

**Comment by Ruslang** [comment]
I found solution:

1. rm -rfv ~/.fzf
2. git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
3. ~/.fzf/install
4. At this point widget appears by CTRL+R
5. sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
6. At this point widget broken by CTRL+R
7. cd ~/.fzf && git pull && ./install
8. PERFECTLY WORKING! GREAT!

**Comment by Ruslang** [comment]
If you have to edit .zshrc, this string must to be latest:
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

**Comment by curtisault** [comment]
If you wind up here because `CTRL + r` stops working after you install oh-my-zsh:

I had `[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh` in my `.zshrc` but this functionality still did not work for me.

The issue is a key-bindings file in the `.oh-my-zsh/` dir. I changed it to the following:
<img width="1375" alt="Screen Shot 2021-03-22 at 4 07 34 PM" src="https://user-images.githubusercontent.com/7681962/112058545-b8c80100-8b28-11eb-8e80-b5b1c14e16bb.png">

**Comment by mareksuscak** [comment]
In my case, I had to (re)install `fzf` via homebrew. None of the above solutions worked.

**Comment by pr0b3r7** [comment]
Having migrated my home folder from another environment I just had to go into my ~/.fzf folder and run (./Install) and all my customization were present including zsh fzf history widget
