### ISSUE TITLE
Change options according to type of use.

### ISSUE THREAD

**Issue by ftpd** [junegunn/fzf#1904]
- [x] I have read through the manual page (`man fzf`)
- [ x I have the latest version of fzf
- [ x I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

I have my FZF_DEFAULT_OPTS set for something, especially I'm using --preview there - and it's great. Sometimes, however, I would like not to have preview - for example when using fzf for searching history (auto binded to ctrl-r). Is it possible to change options just for this 'method' of running fzf?

**Comment by junegunn** [comment]
There is a warning in https://github.com/junegunn/fzf#preview-window that you shouldn't put `--preview` option in your FZF_DEFAULT_OPTS.

> for example when using fzf for searching history

You can set FZF_CTRL_R_OPTS. Please read through the README page before opening an issue.
