### ISSUE TITLE
Change command for invoking fzf via '**'.

### ISSUE THREAD

**Issue by ftpd** [junegunn/fzf#1905]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

I have fd set as my FZF_DEFAULT_COMMAND and FZF_CTRL_T_COMMAND. When I'm using something like `vim **<tab>`, it still uses find, which is slow and doesn't respect my .fdignore file. Is it possible to do so?

**Comment by junegunn** [comment]
Yes, please read through the README page before opening an issue.

**Comment by Userbit** [comment]
I had the same problem. This help everyone as me https://github.com/junegunn/fzf#settings
