### ISSUE TITLE
Option for 'startup dir'.

### ISSUE THREAD

**Issue by ftpd** [junegunn/fzf#1906]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish
    
## Problem / Steps to reproduce
I would like to sometimes starts my fzf with pre-selected 'startup directory'. Let's have vim as example here: I'm starting it in some directory and later I want to invoke fzf (by fzf.vim and :Files command) to search and edit other files. It works, but fzf starts with directory I've stared vim from. Is it possible to pass an option for having, for example, ~ as my basedir in this case, so I can quickly edit any file I have?

**Comment by junegunn** [comment]
Yes, you can learn how to define custom Vim commands from https://github.com/junegunn/fzf/blob/master/README-VIM.md

**Comment by ftpd** [comment]
I know, how to write custom command - I just doesn't know how to tell fzf to start in directory other than it/vim was issued from.

**Comment by LuRsT** [comment]
@ftpd, if you want to have a similar behaviour but in a different folder, you can pass a folder to the commands being executed by `fzf`, for example, `rg --files` in one directory, will return you a list of all the files (most files), so if you run `rg --files | fzf` you get to select the files in your current dir, but if you want a different folder like: `/home/ftpd/code/tf-scripts`, you can run `rg --files ~/code/tf-scripts | fzf`. Does this help?

**Comment by ftpd** [comment]
@LuRsT yes, but I've found a simpler solution - you can just run :Files <startpath>. I haven't tried it before, as I was not able to find an option to manually run non-vim fzf wity start path, so I've assumed it's impossible in vim too ;-)
