### ISSUE TITLE
Feature Request: read from input file

### ISSUE THREAD

**Issue by marcotrosi** [junegunn/fzf#1908]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

I searched the help and the open issues but couldn't find anything.
Would it be possible to read from input file instead from pipe?
Instead of 
cat filename | fzf
to have something like
fzf --input filename

If I missed it, can you tell me what the parameter name is?
If it's not possible, is introducing something like --input a possibility?

thank you

--marco

**Comment by relastle** [comment]
@marcotrosi

```bash
fzf < filename
```

Does the command above meet your need?

**Comment by wookayin** [comment]
IMHO I feel `cat ... | fzf` and `fzf < ...` are more than sufficient.

**Comment by marcotrosi** [comment]
> @marcotrosi
> 
> ```shell
> fzf < filename
> ```
> 
> Does the command above meet your need?

Thanks for the quick answer <3 . If it works on Windows and inside gVim with the system() function, then this could be fine. I will try today when I'm back at work. thank you, thank you. :-)

But even if | and < work on Windows and Unixoids, I think it's just clean to have such parameter. To me it feels like the basis and reading from | and < are at least to me the super cool extra features I get on top of that basis. Of course that's a bit philosophical and not worth to discuss here when the proposed < works in all kind of situations like weirdly nested system calls. So thanks again and I'm looking forward to try it out today at work. Bye bye.

**Comment by marcotrosi** [comment]
Hello again.

I tried the < way to read from file. This works. 

And now I have to start it like this which luckily solves 2 problems and now I can use again also the | (pipe)

:call system('start cmd /c "fd | fzf > output"')

Unfortunately the "start" command seems not to forward the output stream back to Vim, which is why I need to redirect into an output file.

I hate Windows

Thanks for helping me

I wish you a great day


p.s. Still convinced that --input and --output are fundamentals :-)
Same for $FZF_DEFAULT_COMMAND, it looks like it is the only thing that can be configured only through the environment variable, while everything else can be configured with program parameters.
A --default-command parameter would be very appreciated ;-)

**Comment by junegunn** [comment]
> Still convinced that --input and --output are fundamentals

I don't agree. Standard input and standard output are the fundamental concepts of Unix toolchain. They are standards, so users can reliably use them without having to look up the manual page to see if a tool supports the functionality via `--input` or `--input-file` or `-i`, or as the first argument or as the last argument(s).

> Same for $FZF_DEFAULT_COMMAND

fzf, a Unix filter, is perfectly fine without it. The variable is purely for minor convenience. Functions and aliases can easily replace it with much more flexibility.

```sh
alias files='find . -type f | fzf'
alias dirs='find . -type d | fzf'
alias processes="ps -ef | fzf | awk '{print $2}'"
```

> Unfortunately the "start" command seems not to forward the output stream back to Vim, which is why I need to redirect into an output file.

You probably want to check out the official Vim plugin. https://github.com/junegunn/fzf/blob/master/README-VIM.md

**Comment by marcotrosi** [comment]
Thank you @junegunn for your point of view.

this is my fault, bad description from my side, --input was only an example and was the representant for any input flag name like -i or whatever one can come up with. sorry for that misunderstanding.
