### ISSUE TITLE
Customizable sort criteria

### ISSUE THREAD

**Issue by junegunn** [junegunn/fzf#191]
fzf lists the matches using the following sort criteria:

1. First by the sum of the lengths of matched substrings (plural because of extended-search mode)
2. Then by the length of the line
3. Lastly by line index (line number)

From my experience, this default scheme works pretty well for most of the cases, especially for files. I know there can be a wide variety of different needs but it is practically impossible to meet every requirement, and no, I'm not going to invent a DSL for unlimited customization. However, I think it's still desirable that we provide a small room for customization in sort criteria if it doesn't bring too much complication.

```sh
# Default scheme (line index is implied)
--sort-by=match,len

# When the length of the string doesn't matter
# (This I think is the #1 reason to want customization)
--sort-by=match

# It doesn't make sense to bring line index to the front,
# it effectively invalidates the ones that follow
# --sort-by=index,match,len

# We can think of another sort criterion. Distance from the beginning/end
--sort-by=match,begin
--sort-by=match,end

# Nobody would possibly want this
# --sort-by=-match

# Shorter names?
--sort-by=mb
--sort-by=mel

# Are we ever going to NOT want "m"?
# If it's always the first criterion, we could simplify the option a bit:
# Just choose one from length, begin, end, and index
--tiebreak=begin
```

Unwanted side effects:
- Complication (also from the user's perspective)
- Increased memory footprint and performance overhead

**Comment by qiemem** [comment]
Another idea:

It could take in a executable/function name that is passed the query string and matching line (and possibly other information like match lengths) and returns a key. This would allow total customization while keeping fzf itself as simple as possible.

This is probably prohibitively slow, of course, since it would have to call out to an external process on every line. Something like that would be pretty neat though.

**Comment by junegunn** [comment]
@qiemem That's an interesting idea, thanks, and yeah, it's true that it'll be prohibitively slow. It should allow total customization, but at the same time, it'll be be much harder to user for ordinary users.

I'm leaning towards adding `--tiebreak` option. Simpler and does the job. Also no increase in memory footprint or sorting cost.

**Comment by junegunn** [comment]
- `--tiebreak`
    - `length` - Good default when the meaning of the input is not known
    - `begin` - Nice for columnar input. e.g. Chrome [history](http://junegunn.kr/2015/04/browsing-chrome-history-with-fzf/) / [bookmark](http://junegunn.kr/2015/04/browsing-chrome-bookmarks-with-fzf/)
    - `end` - Useful when searching for file names. File name > Dir name
    - `index` - `history` where the recency of the command is more important than the length of if
