### ISSUE TITLE
pipes and spaces - how to avoid accidentally splitting output?

### ISSUE THREAD

**Issue by ColinKennedy** [junegunn/fzf#1910]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

I want to pipe rg into fzf and do a multiple-selection, then capture that output and loop over it, in a script. 

e.g.

```sh
SELECTED_OPTIONS=`rg $1 --vimgrep | fzf --multi --exit-0 --print0`

for item in $SELECTED_OPTIONS
do
	echo $item
done
```

If I select 3 items, I would expect the for loop to iterate over those 3 items. But if one of the selections contains spaces, it gets messed up and prints each word as its own. I think I'm missing something basic here. Could you please direct me to the relevant docs / solution?

**Comment by junegunn** [comment]
This is a general shell scripting question, you'll find better answers on stackoverflow.

https://stackoverflow.com/questions/8677546/reading-null-delimited-strings-through-a-bash-loop
