### ISSUE TITLE
'weird characters' (color sequences) on first result

### ISSUE THREAD

**Issue by MasterMedo** [junegunn/fzf#1913]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [x] fish
- Terminal
    - [x] st
    - [x] urxvt

fzf 0.20.0
fd 7.4.0
## Problem / Steps to reproduce
Fresh installation of `fzf` and `fd` via pacman:
Running `fzf` with `fd` as the default command yields:
![](https://i.imgur.com/nhT5r5g.png)

`fd` alone works flawlessly.
I read and tried #1578 and #1453 but it didn't solve the issue.
I also tried `set -gx FZF_DEFAULT_COMMAND 'fd --type f -c never'` but to no avail.
Same with `fzf --no-color`.
Any help is appreciated.

## Edit
The full line is:
<pre>]4;0;#10161c\]4;1;#E4A80F\]4;2;#F3D409\]4;3;#B89F49\]4;4;#0F5E8E\]4;5;#E07C87\]4;6;#069E9C\]4;7;#a6d0ca\]4;8;#74918d\]4;9;#E4A80F\]4;10;#F3D409\]4;11;#B89F49\]4;12;#0F5E8E\]4;13;#E07C87\]4;14;#069E9C\]4;15;#a6d0ca\]10;#a6d0ca\]11;#10161c\]12;#a6d0ca\]13;#a6d0ca\]17;#a6d0ca\]19;#10161c\]4;232;#10161c\]4;256;#a6d0ca\]708;#10161c\FILENAME</pre>
That giberish before the FILENAME is my full colorscheme, content of `~/.cache/wal/sequences`.
Deleting my colorscheme file completely makes `fzf` run as expected without any errors.
I'm creating my colorscheme with the following command:
`wal -i files/images/wallpapers/pattern/$RAND_BG -q`

**Comment by MasterMedo** [comment]
## Solution
According to [wal-wiki](https://github.com/dylanaraps/pywal/wiki/Getting-Started#applying-the-theme-to-new-terminals) one should put `cat ~/.cache/wal/sequences` in their shell configuration file.
For fish that would make it go in `~/.config/fish/config.fish` which seems reasonable given the config file should be executed only on shell start as stated [here](https://fishshell.com/docs/current/tutorial.html#startup-where-s-bashrc).
Though for some reason, removing the line `cat ~/.cache/wal/sequences` from `~/.config/fish/config.fish` makes the `fzf` problem go away and what's more the colorscheme in the terminal still works for some reason (even on new terminals).

**Comment by junegunn** [comment]
Related: https://github.com/junegunn/fzf/issues/1415

You should fix your setup, but from https://github.com/junegunn/fzf/commit/dd49e41c424ad0cbef6ca0a0f52d918053f329ea fzf will ignore the sequences.
