### ISSUE TITLE
FZF not opened in TMUX pane

### ISSUE THREAD

**Issue by kuntau** [junegunn/fzf#1914]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

Previously when I'm in TMUX, FZF always open tmux split for search but not anymore. I know fzf search have improved to inline search recently instead of taking full screen. Is there any way I can make default keybindings (`CTRL+T`, `CTRL-R`) open fzf in tmux pane when I'm in tmux and inline when not in tmux?

_Sorry for bad englando_

**Comment by junegunn** [comment]
See https://github.com/junegunn/fzf#key-bindings-for-command-line
