### ISSUE TITLE
Slight improvement in the default 'ALT-C', 'CTRL-T' & compgen functions.

### ISSUE THREAD

**Issue by iddinev** [junegunn/fzf#1915]
- [x] I have read through the manual page (man fzf)

- [x] I have the latest version of fzf

- [x] I have searched through the existing issues
## Info
* Category

- [ ] fzf binary

- [ ] fzf-tmux script

- [x] Key bindings

- [x] Completion

- [ ] Vim

- [ ] Neovim

- [ ] Etc.

* Shell

- [x] bash

- [x] zsh

- [x] fish
## Problem / Steps to reproduce
While messing around and customizing my fzf I saw that the default bash compgen_dir & compgen_path functions are using **sed** to remove the leading './':
https://github.com/junegunn/fzf/blob/7c40a424c0bf5a8967816d51ead6a71a334f30bb/shell/completion.bash#L28
https://github.com/junegunn/fzf/blob/7c40a424c0bf5a8967816d51ead6a71a334f30bb/shell/completion.bash#L20
Whereas the default 'ATL_C' command is using **cut**:
https://github.com/junegunn/fzf/blob/7c40a424c0bf5a8967816d51ead6a71a334f30bb/shell/key-bindings.bash#L7
While not a big issue per se, the **cut** approach is probably faster and I'd suggest to also include it in the compgen functions.

P.S. Looking through the files for the other shells, I also saw inconsistent use of **sed**:
https://github.com/junegunn/fzf/blob/7c40a424c0bf5a8967816d51ead6a71a334f30bb/shell/completion.zsh#L20
https://github.com/junegunn/fzf/blob/7c40a424c0bf5a8967816d51ead6a71a334f30bb/shell/completion.zsh#L28
https://github.com/junegunn/fzf/blob/7c40a424c0bf5a8967816d51ead6a71a334f30bb/shell/key-bindings.fish#L17
https://github.com/junegunn/fzf/blob/7c40a424c0bf5a8967816d51ead6a71a334f30bb/shell/key-bindings.fish#L67

**Comment by junegunn** [comment]
Thanks for the suggestion.

The two commands are not identical. `sed` only removes `./` while cut removes any two characters.

```sh
# sed here removes `./`
ls **<tab>

# Each line of find output starts with /tmp, so sed does nothing
ls /tmp/**<tab>
```

**Comment by iddinev** [comment]
My bad, didn't pay enough attention, to actually properly test this and see why it was using **sed** in the first place.
At least I bothered checking the other shells key-bindings, so my issue was not a complete waste of everybody's time.
