### ISSUE TITLE
Invoking fzf from Vim raises E994 when a terminal popup is already open and forces you to quit Vim entirely

### ISSUE THREAD

**Issue by lacygoill** [junegunn/fzf#1916]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

## Problem / Steps to reproduce

In Vim, open a popup terminal via `term_start()` and `popup_create()`.
Then invoke `fzf#run()` to filter some output.
fzf opens a second popup terminal.
After it's closed the focus gets back to the original popup, but:

   - these errors are raised:

         Error detected while processing function 2[5]..1:
         line    3:
         E994: Not allowed in a popup window
         Error detected while processing BufWipeout Autocommands for "*":
         E994: Not allowed in a popup window

   - the terminal buffer in the first popup is no longer displayed

   - the popup window can't be closed anymore (`:q!`, `bw!`, `:close!`, `:call popup_close(win_getid())`, `:call popup_clear()` ...), and the focus can't be changed; the only command which seems to work is `:qa!`

---

Here's a minimal example.  Write this in `/tmp/vimrc`:

    let g:loaded_netrwPlugin = 1
    let g:fzf_layout = {
        \ 'window': {
        \     'width': 0.9,
        \     'height': 0.6,
        \     'xoffset': 0.5,
        \     'yoffset': 0.5,
        \     'highlight': 'Title',
        \     'border': 'sharp',
        \ }}
    set rtp^=~/.fzf rtp-=~/.vim rtp-=~/.vim/after hidden lines=24 columns=80
    au VimEnter * call popup_create(term_start(&shell, #{hidden: v:true}), {'highlight': 'Normal', 'border': [], 'line': 6, 'borderhighlight': ['Title'], 'borderchars': ['─', '│', '─', '│', '┌', '┐', '┘', '└'], 'minheight': 12, 'minwidth': 68, 'col': 5, 'maxwidth': 68, 'zindex': 1, 'padding': [0, 1, 0, 1], 'maxheight': 12})
    nno cd :call fzf#run(fzf#wrap('test', {'source': ['foo', 'bar', 'baz'], 'sink': {line -> execute('echom '..string(line), '')}}))<cr>

Open an xterm terminal, and inside run this shell command:

    $ vim -Nu /tmp/vimrc

You should see a terminal buffer in a popup window.
Press `C-\ C-n` to enter Terminal-Normal mode.
Press `cd` to trigger the custom mapping: fzf opens a popup terminal to filter the lines `foo`, `bar` and `baz`.

Finally, press `Escape` twice to make fzf quit.
As reported earlier, several errors are raised, including `E994`.
The original popup doesn't display a terminal buffer anymore, and there is no way to close the window aside from `:qa!`.

![gif](https://user-images.githubusercontent.com/8505073/76204379-9488d300-61f8-11ea-83d9-91571315e6f4.gif)

---

Regarding the issue about the popup window which can't be closed anymore, I reported it [here](https://github.com/vim/vim/issues/5744).
It seems it's due to the  [`:enew`](https://github.com/junegunn/fzf/blob/d9c6a0305b8c7f83a21fa583ae662660b940b1b6/plugin/fzf.vim#L714) command.
I don't know what is its purpose.  However, even after commenting it, the Vim errors are still raised, and the terminal buffer is still lost.

## Cause

I think the issue starts from this line:
https://github.com/junegunn/fzf/blob/d9c6a0305b8c7f83a21fa583ae662660b940b1b6/plugin/fzf.vim#L710

It is currently forbidden to load a different buffer while in a popup terminal, so `:b` fails.

## Solution

One solution would be to wrap the command inside a `:try` conditional, and invoke `popup_close(win_getid())` to close the popup terminal where fzf is running:

    try
      execute 'keepalt b' self.pbuf
    catch /^Vim\%((\a\+)\)\=:E994:/
      execute 'autocmd BufEnter * ++once autocmd BufHidden <buffer> ++once bwipeout! '..self._buf
      silent! return popup_close(win_getid())
    endtry

The tricky part is to wipe out the `!sh` buffer which was displayed originally in the fzf popup window.

In the previous snippet, I do it with this autocmd:

      execute 'autocmd BufEnter * ++once autocmd BufHidden <buffer> ++once bwipeout! '..self._buf

This can be read as: "the next time you focus a buffer, install an autocmd which wipes out `!sh` the next time the current buffer becomes hidden".  The goal is to delay `:bw` until it's allowed; i.e. as soon as the user doesn't focus a popup terminal.

Note the variable `self._buf` at the end:

      execute 'autocmd BufEnter * ++once autocmd BufHidden <buffer> ++once bwipeout! '..self._buf
                                                                                        ^^^^^^^^^

It must refer to the number of the `!sh` buffer.  Currently, it doesn't exist.  It could be created right before this line: https://github.com/junegunn/fzf/blob/d9c6a0305b8c7f83a21fa583ae662660b940b1b6/plugin/fzf.vim#L768

By writing:

    let fzf._buf = fzf.buf

Here's a patch which fixes this issue:

    diff --git a/plugin/fzf.vim b/plugin/fzf.vim
    index 6fa3d14..966881d 100644
    --- a/plugin/fzf.vim
    +++ b/plugin/fzf.vim
    @@ -707,7 +707,12 @@ function! s:execute_term(dict, command, temps) abort
       function! fzf.switch_back(inplace)
         if a:inplace && bufnr('') == self.buf
           if bufexists(self.pbuf)
    -        execute 'keepalt b' self.pbuf
    +        try
    +          execute 'keepalt b' self.pbuf
    +        catch /^Vim\%((\a\+)\)\=:E994:/
    +          execute 'autocmd BufEnter * ++once autocmd BufHidden <buffer> ++once bwipeout! '..self._buf
    +          silent! return popup_close(win_getid())
    +        endtry
           endif
           " No other listed buffer
           if bufnr('') == self.buf
    @@ -765,6 +770,7 @@ function! s:execute_term(dict, command, temps) abort
           if !len(&bufhidden)
             setlocal bufhidden=hide
           endif
    +      let fzf._buf = fzf.buf
           let fzf.buf = term_start([&shell, &shellcmdflag, command], {'curwin': 1, 'exit_cb': function(fzf.on_exit)})
           if !has('patch-8.0.1261') && !has('nvim') && !s:is_win
             call term_wait(fzf.buf, 20)

## Limitation

I don't submit a PR for this fix, because the autocmd looks brittle; in particular, I think it wouldn't work as expected if the user has more than one popup terminal.  The current autocmd works under the assumption that when the user closes their popup terminal, `:bw` will be allowed; that won't be the case if they have yet another popup terminal open, because the focus will switch to the latter, and thus `:bw` will still be forbidden.

## Alternative

Alternatively, I think the issue could be reliably fixed if fzf didn't create 2 terminal buffers:

https://github.com/junegunn/fzf/blob/d9c6a0305b8c7f83a21fa583ae662660b940b1b6/plugin/fzf.vim#L768
https://github.com/junegunn/fzf/blob/d9c6a0305b8c7f83a21fa583ae662660b940b1b6/plugin/fzf.vim#L840

1 terminal buffer should be enough.  For example, this command creates only 1 terminal buffer to start fzf in a popup window:

    call popup_create(term_start('fzf', #{hidden: v:true}), {'highlight': 'Normal', 'border': [], 'line': 6, 'borderhighlight': ['Title'], 'borderchars': ['─', '│', '─', '│', '┌', '┐', '┘', '└'], 'minheight': 12, 'minwidth': 68, 'col': 5, 'maxwidth': 68, 'zindex': 1, 'padding': [0, 1, 0, 1], 'maxheight': 12})

When fzf is finished, all you have to do is to run:

    :call popup_close(win_getid())

So, you would still need the `:try` conditional from the previous patch, but you wouldn't need to worry about the `!sh` buffer hanging around, and you wouldn't need the complex autocmd, nor the `fzf._buf` variable.

Unfortunately, I don't understand the code of the plugin well enough to perform this refactoring.

**Comment by lacygoill** [comment]
If the code was refactored to create only 1 terminal buffer, and if the borders were drawn natively (as suggested in the PR #1912), then I think you could get rid of the 2 one-shot autocmds listening to `BufWipeout`.

**Comment by junegunn** [comment]
I have mixed feelings about #1912 because it actually increases the amount of the code we have to maintain, two very different mechanisms for Vim and Neovim, while it doesn't really improve the user experience. But if it fixes this issue, I should just merge it. So if I merge #1912, everything's gonna be okay?

**Comment by lacygoill** [comment]
Yeah, actually I understand your point of view; I was hesitant before submitting #1912.  Imo it's cleaner, but as you said, it gives you 2 different mechanisms to maintain which is probably not worth it.
I'm going to close the PR.  If one day you're interested, you may still have a look at the code to implement your own version of Vim's native border.

Unfortunately, even if you merged the PR, it would not fix the current issue.
But I thought about something else, which would avoid any work on your part; I could ask bram to allow `:b` to work in a popup terminal (on the condition that `:b` loads a terminal buffer, not a regular buffer).  After all, you can already change a buffer terminal with `term_start()` + `'curwin': 1`.  If he refuses, I could ask him to allow `:bw`.  I could then fix the issue with a small patch (just a `:try` conditional), but it would be reliable.  If he refuses that too, then I don't know how to fix the issue.

I'll ask him later, and let you know what is his response.  [I'm not sure he will agree](https://github.com/vim/vim/issues/5585#issuecomment-582583719):

> I'm a bit careful to not allow too much, because it can open can of worms... We'll see if there are valid use cases that require more flexibility.

But we'll see.
