### ISSUE TITLE
How to convery fzf's output to cmd's command?  

### ISSUE THREAD

**Issue by BSDxxxx** [junegunn/fzf#1918]
- [ ] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [ ] Mac OS X
    - [x] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [ ] fish
    - [x] cmd
    
## Problem / Steps to reproduce

How to convery fzf's output to cmd's command?  
```nvim **``` with ```<TAB>```  won't work in cmd(win10).  
Wish you can put some more usage about windows in README.

**Comment by junegunn** [comment]
The key bindings and fuzzy completion code we provide here are for Unix systems.
However, there are some third-party projects for Windows that you might want to try.
See: https://github.com/junegunn/fzf/wiki/Windows#powershell-support
