### ISSUE TITLE
Put current command line contents into fzf search

### ISSUE THREAD

**Issue by kovasap** [junegunn/fzf#1919]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

I frequently run into a situation where I start typing a command at the command line and only after I start typing it do i want to check to see if it exists already in my history.  So, what I do is I start the fzf history search, but this requires that I re-type whatever I started typing again.  Is there a way to take the current command line and pre-populate the fzf search with it?  This would make it so that I wouldn't need to type the same start of a command twice.

**Comment by junegunn** [comment]
We implemented this in #1886.

For example, `git add<CTRL-R>` will start fzf with `git add` as the initial query. But you should note that fzf has its own [search syntax](https://github.com/junegunn/fzf#search-syntax), so `git add` will not only match `git add ...` but also something like `... add ... git ...`.
