### ISSUE TITLE
Enter open only the first file on neovim

### ISSUE THREAD

**Issue by tfmoraes** [junegunn/fzf#192]
Hi,

I'm using neovim (NVIM 0.0.0-alpha (compiled Apr 15 2015 06:36:24), from Ubuntu PPA ). When I try to open a file using :FZF with the enter key, the first file open right. But when I try to open other files in the same way (:FZF and enter key) it doesn't work, and shows this message:

[Program exited, press any key to close]

 if I use the Ctrl-V it opens all right. The fzf version is the last one from github. I tried with this simple .nvimrc:

   call plug#begin('~/.nvim/plugged')
   Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': 'yes \| ./install' }
   call plug#end()

But in vim, using the same .vimrc, same fzf version, it works all right.

Thanks!

**Comment by junegunn** [comment]
Hi, thanks for the report.
I also noticed that the problem randomly occurs, must be some kind of a race condition in Neovim. I [reported the problem](https://github.com/junegunn/fzf/issues/137#issuecomment-91604555) to @tarruda, and [he replied](https://github.com/junegunn/fzf/issues/137#issuecomment-93317025) that he'll be fixing the problem.

**Comment by tfmoraes** [comment]
Thanks! I'll close this issue.
