### ISSUE TITLE
prefix-exact-match (^) syntax does not work in 0.21.0

### ISSUE THREAD

**Issue by dongsibo** [junegunn/fzf#1923]
- [ ] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish
    
## Problem / Steps to reproduce
 
1. Download and install `fzf 0.21.0`.
2. Open a new Bash shell.
3. Try to search through your history for a previously ran command with the prefix-exact-match search syntax (with `CTRL-R` or `history | fzf`), e.g. `^vim`.
4. Observe that results that should appear do not, e.g. commands like `vim some_file.txt` will not appear in the results.

I've ran `git bisect` and it tells me that the "[[bash] Multiline C-r without histexpand (#1837)](https://github.com/junegunn/fzf/commit/5cae8ea733e8663eae96480b5e6d4c94afcdb3bd)" commit is the first commit where this issue arises.

**Comment by junegunn** [comment]
Thanks for the report. I missed that in the review process.

**Comment by junegunn** [comment]
Fixed in 14f90502a49b868b6c9fed4a86d413427052fb81
