### ISSUE TITLE
Searching result including directory item

### ISSUE THREAD

**Issue by mrvon** [junegunn/fzf#1926]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Windows 10 1909

- Shell
    - [x] Powershell

- FZF Version

```sh
>  .\bin\fzf.exe --version
0.21.0 (b0673c3)
```

## Problem / Steps to reproduce

```sh
./bin/fzf.exe 
```
Input bin, Result will be:

```sh
  shell\key-bindings.fish
  shell\key-bindings.bash
  shell\key-bindings.zsh
  bin\fzf-tmux
  bin\fzf.exe
> bin
  6/99
> bin
```

## Expectation

Searching result shouldn't including directory *bin*，just like this。

```sh
  shell\key-bindings.fish
  shell\key-bindings.bash
  shell\key-bindings.zsh
  bin\fzf-tmux
> bin\fzf.exe
  5/99
> bin
```

**Comment by junegunn** [comment]
c39113e should fix the problem. I uploaded a Windows binary in case you have trouble building one from the source.

- https://github.com/junegunn/fzf-bin/releases/download/alpha/fzf-0.21.1-alpha-windows_amd64.zip

/cc @mattn
