### ISSUE TITLE
Add action to modify query by piping it through external program

### ISSUE THREAD

**Issue by LiteracyFanatic** [junegunn/fzf#1930]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

I have an fzf script which I use to select Japanese kanji and words from a custom list. It basically serves a similar purpose to something like ibus, but it has some extra features that make it much faster to find what I'm looking for. For example, if I am looking for the kanji 田 (rice paddy) I search for it using the hiragana た (ta), since that is how the word is pronounced. The issue is that I actually still need to use ibus to input the character た when I type "ta". There is a python library called romkon which I can use to do this conversion instead. `romkan.to_hiragana("ninj")` outputs `にんｊ`. `romkan.to_hiragana("ninja")` outputs `にんじゃ`. I would like to be able to do something like this `fzf --bind='change:modify-query(convert-to-hiragana.py $QUERY_TEXT)'` so that I can have my characters automatically be converted as I type them.

**Comment by dicktyr** [comment]
an action to modify the query would indeed be useful
but perhaps a shorter name is better

`set-query(...)`

and maybe simplify the issue title
*Add action to set query by external command*
