### ISSUE TITLE
Support --color=always

### ISSUE THREAD

**Issue by astoilkov** [junegunn/fzf#1932]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

I am running `fzf` with the following command: `rg . | fzf --filter=query` through a Node.JS process. I want to make `fzf` output ANSI codes so I can parse them and determine where the matches are.

Have you considered adding a `--color=always` option?

**Comment by junegunn** [comment]
```
rg --color=always . | fzf --filter=query
```

**Comment by astoilkov** [comment]
This doesn't work if you run it from a Node.JS process like the example below:
```typscript
const result = execSync('rg --color=always . | fzf --filter=query').toString()

// result here doesn't have ANSI codes inside of it
```

**Comment by astoilkov** [comment]
If you want I can write a longer explanation and reasons why I think this flag can be useful. Just let me know.

**Comment by junegunn** [comment]
> This doesn't work if you run it from a Node.JS process

In this case, without `--ansi` option, fzf simply bypasses any ANSI escape sequences in the original string. They are printed unmodified. So maybe it's `execSync` stripping the codes. I don't know.

```sh
# Colored
rg .

# No color
rg . | cat

# Colored
rg --color=always . | cat

# Colored
rg --color=always . | fzf --filter=query

# Still colored
rg --color=always . | fzf --filter=query | cat
```

> fzf matches are still not wrapped with ANSI codes

Coloring of `--filter` output was not implemented. Since I never use `--filter` option (I don't find it useful without UI), I'm not interested in implementing it.

**Comment by astoilkov** [comment]
> This doesn't work if you run it from a Node.JS process

The way most other CLI tools I have seen written in Node.JS the program checks for `process.stdout.isTTY` and if it is true only then they return ANSI codes. Maybe there is some type of check in `fzf` somewhere?

> fzf matches are still not wrapped with ANSI codes

Thanks, I understand. Do you have ideas on how can I use `fzf` outside of the terminal some other way? `fzf` has such a powerful searching algorithm that it is very sad it can't be used outside of the terminal for querying big amounts of data.
