### ISSUE TITLE
[Feature] Add shift-pgup and shift-pgdn keybinds

### ISSUE THREAD

**Issue by anasbouzid** [junegunn/fzf#1933]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [x] zsh
    - [x] fish

I'd like to use `shift-pgup (shift-page-up)` and `shift-pgdn (shift-page-down)` key bindings to have preview scrolling by page. `fzf` already supports `shift-down` and `shift-up`, but scrolling by page would be a useful feature.

**Comment by 0ion9** [comment]
`--bind`.

**Comment by junegunn** [comment]
My terminal doesn't recognize shift-pgdn or shift-pgup. Maybe they are not part of the standard? Run this Ruby script and see what escape sequences those key chords generate.

```ruby
#!/usr/bin/env ruby

require 'io/console'

loop do
  chars = $stdin.getch + ($stdin.read_nonblock(1024) rescue '')
  break if [3, 4, 26].map(&:chr).include?(chars)

  p chars
end
```

**Comment by 0ion9** [comment]
Oh, that's a fair point, perhaps I misunderstood OP.

In xterm, which doesn't consume shift+pg[up][down], `fish_key_reader` ( a `fish` builtin tool designed to do approximately the same as your snippet, junegunn) does not register shift+pgup /shift+pgdn

In sakura, these keys are just consumed by the terminal (to scroll the terminal up/down).
Sakura is libvterm based;I also tested another libvterm-based terminal, `pangoterm`. That has the same behaviour as sakura, so possibly libvterm-based terminals bind these key combos by default. Lilyterm (using the legacy version, libvte) also captured these keys.

I took the time to survey a few more:

* lxterminal (libvterm based)  : Captures these keys
* evilvte (libvte legacy): Captures these keys
* gnome-terminal (libvte3): Captures these keys
* konsole (kpty based): Captures these keys

So I suspect these cannot normally be read, although possibly emulators with a rebinding option might change that.

**Comment by junegunn** [comment]
@0ion9 Thanks for the investigation! FYI, I have tested these on iTerm2 and Terminal.app on macOS. iTerm2 doesn't recognize them at all, and Terminal.app reads them as plain pgup and pgdn.

So it looks like there's no universal way to support shift-pgup/dn across different terminal emulators. I'll have to close this as wontfix.
