### ISSUE TITLE
Return query if no match?

### ISSUE THREAD

**Issue by d0minikt** [junegunn/fzf#1937]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [x] Mac OS X
    - [x] Windows
    - [x] Etc.
- Shell
    - [x] bash
    - [x] zsh
    - [x] fish
    
## Problem / Steps to reproduce

Is it possible to the query string if the search query wasn't found?
Something like `--exit-0` but instead of exitting, return the search query...
If it's not an available flag option, can it be done with `--bind` and actions?

Thanks.

**Comment by junegunn** [comment]
You can use `--print-query` option.

**Comment by spjspjspj** [comment]
curious how to make this change in shell key bindings eg in 
```
source "/opt/homebrew/opt/fzf/shell/key-bindings.zsh"
```
thanks

**Comment by LangLangBart** [comment]
> curious how to make this change in shell key bindings eg in

I assume you want to print the query when no matching history entry is found. Try the following[^1]:

```sh
# You can make CTRL-R paste the current query when there's no match
export FZF_CTRL_R_OPTS='--bind enter:accept-or-print-query'
```

[^1]: [fzf/CHANGELOG.md 0.45.0](https://github.com/junegunn/fzf/blob/master/CHANGELOG.md#0450)
