### ISSUE TITLE
fzf-completion() breaks when global alias `tail` is defined

### ISSUE THREAD

**Issue by marlonrichert** [junegunn/fzf#1938]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish
    
## Problem / Steps to reproduce
When I have the following line in my `.zshrc`:
```shell
alias -g tail="multitail -Cs --follow-all"
```
then when I try to use `fzf-completion()`, it fails with the following error message:
```shell
fzf-completion:local:1: not valid in this context: -Cs
```

The solution is probably just to add `setopt no_aliases`, like you did here: https://github.com/junegunn/fzf/issues/1708#issuecomment-543000287

**Comment by junegunn** [comment]
Please send a pull request.

**Comment by marlonrichert** [comment]
I tried, but I could not get it to work. `setopt noaliases` doesn't seem to have any affect on global aliases. It seems to disable normal aliases only.

I will just use a non-global alias or a function instead.

**Comment by junegunn** [comment]
It should work with global aliases:

```sh
$ alias -g foo=bar
$ echo foo
bar
$ setopt no_aliases
$ foo
foo
```

I'm not sure but it's probably a bug of zsh that it's not working as expected in that particular context.

**Comment by junegunn** [comment]
```sh
alias -g tail="multitail -Cs --follow-all"

f() {
  setopt localoptions no_aliases
  local tail
  tail=1
  echo $tail
}

g() {
  setopt localoptions no_aliases
  local tail=1
  echo $tail
}
```

```
$ type -f f
f () {
        setopt localoptions no_aliases
        local multitail -Cs --follow-all
        tail=1
        echo $tail
}

$ type -f g
g () {
        setopt localoptions no_aliases
        local tail=1
        echo $tail
}
```

🤷‍♂ 🤷‍♀

**Comment by marlonrichert** [comment]
That does indeed look like a bug in `zsh` to me. I sent a bug report to zsh-workers@zsh.org. I'll let you know if I get a reply.

**Comment by marlonrichert** [comment]
OK, here's the full reply: http://www.zsh.org/mla/workers/2020/msg00456.html

If I'm going to rewrite fzf's zsh code to use autoloading functions (which I think is by far the best option presented), then I would also like to rewrite it as a zsh plugin, which would make the code much more convenient to use. But then we're not talking pull request anymore, because a zsh plugin is required to live in its own repo: https://github.com/zdharma/Zsh-100-Commits-Club/blob/master/Zsh-Plugin-Standard.adoc#what-is-a-zsh-plugin

**Comment by romkatv** [comment]
> But then we're not talking pull request anymore, because a zsh plugin is required to live in its own repo: https://github.com/zdharma/Zsh-100-Commits-Club/blob/master/Zsh-Plugin-Standard.adoc#what-is-a-zsh-plugin

That document isn't a standard in any meaningful sense. Take it with a (massive) grain of salt.

**Comment by junegunn** [comment]
Do you think this approach is valid?

```diff
diff --git a/shell/completion.zsh b/shell/completion.zsh
index b6aec33..4f0281f 100644
--- a/shell/completion.zsh
+++ b/shell/completion.zsh
@@ -10,6 +10,7 @@
 # - $FZF_COMPLETION_OPTS    (default: empty)
 
 if [[ $- =~ i ]]; then
+if [[ -n "$__fzf_sourcing" ]]; then
 
 # To use custom commands instead of find, override _fzf_compgen_{path,dir}
 if ! declare -f _fzf_compgen_path > /dev/null; then
@@ -241,4 +242,11 @@ fzf-completion() {
 zle     -N   fzf-completion
 bindkey '^I' fzf-completion
 
+else
+  __fzf_sourcing=1
+  [[ ! -o noaliases ]] && setopt noaliases && __reset_aliases=1
+  source "$0"
+  [[ -n "$__reset_aliases" ]] && setopt aliases && unset __reset_aliases
+  unset __fzf_sourcing
+fi
 fi
```

**Comment by romkatv** [comment]
> Do you think this approach is valid?

This will break in many cases.

The following should work well:

```diff
diff --git a/shell/completion.zsh b/shell/completion.zsh
index b6aec33..ac02309 100644
--- a/shell/completion.zsh
+++ b/shell/completion.zsh
@@ -9,7 +9,23 @@
 # - $FZF_COMPLETION_TRIGGER (default: '**')
 # - $FZF_COMPLETION_OPTS    (default: empty)
 
-if [[ $- =~ i ]]; then
+if 'zmodload' 'zsh/parameter' 2>'/dev/null'; then
+  __fzf_restore_options="options=(${(j: :)${(kv)options[@]}})"
+else
+  () {
+    'local' 'on' 'off' '__fzf_opt'
+    for __fzf_opt in "${(@)${(@f)$(set -o)}%% *}"; do
+      [[ -o "$__fzf_opt" ]] && on+=" $__fzf_opt" || off+=" $__fzf_opt"
+    done
+    __fzf_restore_options="${on:+setopt$on}; ${off:+unsetopt$off}"
+  }
+fi
+
+'emulate' 'zsh' '-o' 'no_aliases'
+
+{
+
+[[ -o interactive ]] || return 0
 
 # To use custom commands instead of find, override _fzf_compgen_{path,dir}
 if ! declare -f _fzf_compgen_path > /dev/null; then
@@ -241,4 +257,6 @@ fzf-completion() {
 zle     -N   fzf-completion
 bindkey '^I' fzf-completion
 
-fi
+} always {
+  eval $__fzf_restore_options
+}
```

This should work with any shell options -- the meat of `completions.zsh` will always be parsed with the standard zsh options (those marked with `<Z>` in `man zshoptions`) sans `aliases`.

It should have no effect on loading or execution speed. In virtually all setups (except a few very ancient or broken Zsh installations) the first branch of the `if` will be taken. That's the fast branch. The `else` branch does the same thing but it's orders of magnitude slower due to a fork.

Note: Many words are quoted to prevent alias expansion. Some words cannot be quoted so they use ugly names instead (e.g., `__fzf_opt`).

The only way to break this code is by defining crazy aliases like this:

```zsh
alias if='}'
alias -g do='}'
```

And of course you can also break it with crazy functions:

```zsh
function emulate() { exit 1 }
```

**Comment by romkatv** [comment]
I've updated the patch in my previous comment. Please reapply if you've already applied it.

**Comment by junegunn** [comment]
Thanks for the patch. Care to open a pull request? And should we do the same in `key-bindings.zsh`?

**Comment by romkatv** [comment]
> Thanks for the patch. Care to open a pull request? And should we do the same in `key-bindings.zsh`?

Sent https://github.com/junegunn/fzf/pull/1944.

**Comment by marlonrichert** [comment]
Thanks, @romkatv!
