### ISSUE TITLE
--bind command breaks running fzf command

### ISSUE THREAD

**Issue by micakce** [junegunn/fzf#1942]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish
    
## Problem / Steps to reproduce
Hi, I am working on my own functions to improve my docker workflow, I created this function:

```zsh
# Select one or more docker container(s) to remove
function dcrm() {
    local inspect="--bind=ctrl-o:execute(docker inspect \$(echo {} | awk '{print "'$1'"}') | jq -C . |less -R)"
    for s in $(docker ps -a | fzf $inspect --header="Remove container(s)" --header-lines=1 -m -q "$1" | awk '{print $1}');
    do docker rm $s;
    done;
}
```
It allowed me to delete one or more containers at once, now I was trying to implement a bind command (inspect) that would allow me to get more info about the container on the fly, but when I execute it, it does not work as expected and generates output that breaks the function.

Now, if I do this:

```zsh
function dct() {
    local inspect="--bind=ctrl-o:execute(docker inspect \$(echo {} | awk '{print "'$1'"}') | jq -C . |less -R)"
    local enter="--bind=enter:execute(docker container rm \$(echo {} | awk '{print "'$1'"}'))+abort"
    docker ps -a | fzf $inspect $enter --header="FZF docker test command" --header-lines=1 -m -q "$1"
}
```

the "inspect" bind works fine, but I don't know how to go to from there, take the selected item(s) and delete the containers. With the "enter" bind, I get to delete one container but doesn't seem the best way to do it. Thanks in advance.

**Comment by junegunn** [comment]
- You can write `{1}` instead of `$(echo {} | awk ..`
- This should work (redirecting the output of less to `/dev/tty`):
```sh
function dcrm() {
    local inspect="--bind=ctrl-o:execute(docker inspect {1} | jq -C . | less -R > /dev/tty)"
    for s in $(docker ps -a | fzf $inspect --header="Remove container(s)" --header-lines=1 -m -q "$1" | awk '{print $1}');
    do docker rm $s;
    done;
}
```
