### ISSUE TITLE
search completion for exact matches (request)

### ISSUE THREAD

**Issue by nkh** [junegunn/fzf#1943]
- [x ] I have read through the manual page (`man fzf`)
- [ x] I have the latest version of fzf
- [ x] I have searched through the existing issues

- OS
    - [ x] Linux
- Shell
    - [x ] bash

## Problem 

I have thousands of exact matches for: DISPLAY_ 
there are hundreds of different DISPLAY_XXX strings

to find which XXX I can use I need to scroll in the matches but the information about XXX is already available and It would be great if the list of XXX to pick from was accessible

is there a way to take the current search, run it through another program (in this case making a word search | uniq | fzf) and give that back to fzf?

**Comment by LuRsT** [comment]
Hi @nkh,

That's exactly what fzf was born to do. If you figure out a way to get your "DISPLAY_XXX" strings, when you pipe it into `fzf`, it gives you a list of them (split by \n). It will then output what you select, so you can do something else with it.

![hi](https://user-images.githubusercontent.com/263583/77826559-0f625100-7108-11ea-8fc7-dfd03b7544bd.png)

**Comment by nkh** [comment]
I am afraid I haven't explained well enough. So let me use bash completion as an example to refine this one.

say I have 100 git related commands (which we all see to have these day). if I type git + tab Iget the 100 possible completions.

Now back to my example above, I have 60 000 lines, I type DISPLAY_, I still have 20 000 lines, somewhere in the begining of that list there is DISPLAY_A, 300 lines down DISPLAY_B, 1000 lines down DISPLAY_C. I know nothing about A, B, or C yet, I am discovering them, going through 20 000 lines is not an option, sure I can get out of fzf, who already has the necessary data, grep -r DATA_ | sort -u > my possible DISPLAY. reopen fzf for the 60 000 lines, open my possible display list, type one of them in fzf, look at where they are used. bleahh.

Sure I can execute a command from fzf (maybe even piped to fzf) but I'd like the result of that command to become the current search. Does it make more sense or did I misunderstand your comment and it gave a solution for that?

**Comment by misuzu** [comment]
@nkh try this:

`export FZF_CTRL_R_OPTS="--no-extended --exact"`

https://github.com/junegunn/fzf/wiki/Configuring-shell-key-bindings
