### ISSUE TITLE
Add man pages to pre-built tarballs

### ISSUE THREAD

**Issue by ngirard** [junegunn/fzf#1945]
Could you please add the man pages as well as the `fzf-tmux` script to the pre-built tarballs at https://github.com/junegunn/fzf-bin/releases ?
Thanks in advance !

**Comment by junegunn** [comment]
fzf-bin only provides binaries. I don't want to change it because there can be user scripts out there that rely on that structure. Source code tarballs can be separately downloaded from https://github.com/junegunn/fzf/releases.
