### ISSUE TITLE
:FZF is not quitting by ESC

### ISSUE THREAD

**Issue by schmooser** [junegunn/fzf#195]
Hy Junegunn,

:FZF stopped quitting by ESC, only C-c is available to exit. ESC now turns it into Normal mode.

Is this intended behavior?

Environment: latest nvim and fzf, OS X Mavericks.

**Comment by schmooser** [comment]
If it's intended behavior, then the problem is the following: If I do ESC and :q in FZF buffer then on next run :FZF will say that it's already running (works as designed here). As I also use it as buffer switcher it's frustrating.  The only way remaining is manual buffer switching.

**Comment by junegunn** [comment]
No, in my case, fzf split is closed when I press ESC key. I tested with nothing but fzf.

```vim
nvim -Nu <(echo set rtp+=~/.vim/plugged/fzf)
```

**Comment by schmooser** [comment]
Ok, I'll recheck it. Thanks.

**Comment by schmooser** [comment]
I found what caused the problem, I added

    tnoremap <Esc> <c-\><c-n>

to escape from Terminal nvimrc.

Sorry for interrupting.
