### ISSUE TITLE
doesn't list the right files on a directory with multi-line filename.

### ISSUE THREAD

**Issue by rmNULL** [junegunn/fzf#1950]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish
 
No i have not overwritten `FZF_CTRL_T_COMMAND` or `$FZF_CTRL_T_OPTS`

## Problem
Invoking CTRL-T on a directory with multi-line filename, shows wrong number of filenames.

##  Steps to reproduce
1) `touch "a
file with newline"`
2) rm `CTRL-T`

## Screenshot
![2_000](https://user-images.githubusercontent.com/8173131/78180996-3ced2880-7481-11ea-98b0-e5060c5de280.png)

## personal opinion
FZF must be able to select such filenames, it must present the escaped filename(like how it does when there's a space or other special character). 
Having a multi-line filename is a rare scenario of course(with me it was an accident case of un closed shell quotes).

**Comment by junegunn** [comment]
I'm aware of the limitation. But you can configure the command for CTRL-T to print items with null separator and fzf to read accordingly, for example:

```sh
FZF_CTRL_T_COMMAND='find . -print0'
FZF_CTRL_T_OPTS='--read0'
```

But we are not going to make this default since doing so will break any current user configuration that only sets one of the two.
