### ISSUE TITLE
Feature req: Allow binding to ALT key press/release

### ISSUE THREAD

**Issue by salmankhilji** [junegunn/fzf#1953]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [x] Mac OS X
    - [x] Windows
    - [x] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish
    
I would like to mimic the same behavior within fzf that is prevalent within macOS where pressing and holding the ALT key down changes the contents of a given menu.  (If you are not running macOS, please see the attached animation for an example.)  When the user presses and _holds_ the ALT key down, the some menu items change to their alternate form.  Releasing the ALT key reverts menu items to their defaults.

We could implement this within fzf if `--bind` allowed something like `alt-hold` and `alt-release`.  Though I could bind to `alt-a`, the end user experience would not be as nice as in macOS.

![macos-alt-key](https://user-images.githubusercontent.com/40219235/78436421-795c8800-762b-11ea-9f84-296c08764064.gif)

**Comment by junegunn** [comment]
That is not possible for terminal applications since standard terminals are not capable of recognizing alt key alone.

Related: https://github.com/junegunn/fzf/issues/1933#issuecomment-603061623.
