### ISSUE TITLE
fzf-tmux -p => add support for -x R -y S args (feature)

### ISSUE THREAD

**Issue by mckellyln** [junegunn/fzf#1956]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [x] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

This is not a problem, just a feature request.

fzf-tmux -p -x R -y S ...  the -x and -y args are expected to be col/row but tmux allows -R, -S

Cool if we could accept these values below as well.  Do you want me to create a PR for it ?

-x and -y give the position of the menu.  Both may be a row or column number, or one of the following special values:
                   Value    Flag    Meaning
                   C        Both    The centre of the terminal
                   R        -x        The right side of the terminal
                   P        Both    The bottom left of the pane
                   M        Both    The mouse position
                   W        Both    The window position on the status line
                   S        -y         The line above or below the status line

thx for awesome fzf/fzf.vim and others ..
-m

**Comment by junegunn** [comment]
Due to the way fzf-tmux parses the arguments, this works (no space):

```sh
fzf-tmux -p -xR -yS

# -p can be omitted
fzf-tmux -xR -yS
```

But we can easily make fzf-tmux support `-x R` as well

```diff
diff --git a/bin/fzf-tmux b/bin/fzf-tmux
index 290ce87..4b3e497 100755
--- a/bin/fzf-tmux
+++ b/bin/fzf-tmux
@@ -77,7 +77,7 @@ while [[ $# -gt 0 ]]; do
       if [[ ${#arg} -gt 2 ]]; then
         size="${arg:2}"
       else
-        if [[ "$1" =~ ^[0-9%,C]+$ ]]; then
+        if [[ "$1" =~ ^[0-9%,]+$ ]] || [[ "$1" =~ ^[A-Z]$ ]]; then
           size="$1"
           shift
         else
```

**Comment by mckellyln** [comment]
Awesome, thx
