### ISSUE TITLE
FZF breaking Tmux zoom

### ISSUE THREAD

**Issue by shkm** [junegunn/fzf#196]
Assuming I have a multi-pane window and vim is zoomed, executing FZF takes the window out of zoom.

Is this fixable? Perhaps via a tmux config change, if nothing else?

Thanks!

**Comment by junegunn** [comment]
I don't think it's possible. You'll notice that a zoomed pane shrinks when you `tmux split`. You can try Neovim where fzf uses native vim splits instead of tmux panes.

**Comment by shkm** [comment]
Yeah, thanks for responding.

I closed the issue because I realised that this just works in NeoVim :-). Unfortunately I'm having other issues with NeoVim, but I'll try to get around them because I really love FZF and the whole zoom-breaking thing is killing me right now.

**Comment by DestyNova** [comment]
This seems to have been fixed recently...

**Comment by junegunn** [comment]
Yeah, kind of. Now it does not split the window if it's zoomed, that's the best we can do.

**Comment by DestyNova** [comment]
It's much better this way! :+1:
