### ISSUE TITLE
exact match that is also case-sensitive

### ISSUE THREAD

**Issue by mckellyln** [junegunn/fzf#1960]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [x] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

This is not a problem, but a question/enhancement request.

When using fzf (with fd) to get a listing of files and dirs I can use 'wild for an exact match, but this still seems to be smart-case.
I can add +i but it is nice to have smart-case most of the time and have a single cmd that works for all types of searches.
Does it make sense that 'wild means exact + case-sensitive match ?  If not then perhaps a new ` or some other way to make it a true exact + case-sensitive match ?

thx for awesome fzf.
-m

**Comment by dagadbm** [comment]
yes pls. this is very helpful specially when browsing through code using fzf.vim !

**Comment by mckellyln** [comment]
Closing issue, but pull request is still active.
