### ISSUE TITLE
`link_fzf_in_path` blocking recent fzf versions

### ISSUE THREAD

**Issue by srfraser** [junegunn/fzf#1966]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

As a consequence of #373 when the installer is run and a local copy of fzf is found in $PATH, the installer doesn't download a new version. This means that on, for example, Ubuntu 19.10 the latest you can install using the system package manager is 0.18.0, and the fzf installer won't download or compile a newer version even if it will work. 

Would it be possible to have an installer option that lets you say "Ignore any currently installed fzf in the path" and skips the call to `link_fzf_in_path`? I'd like to get hold of a recent `fzf` without forking the install script.

**Comment by junegunn** [comment]
I think you're somehow mistaken. install scripts checks the output of `--version` and downloads the newer binary if the fzf in $PATH is not the latest.

```sh
$ fzf
fzf 0.18.0

$ ./install
Downloading bin/fzf ...
  - Found in $PATH
  - Creating symlink: bin/fzf -> /Users/jg/bin/fzf
  - Checking fzf executable ... fzf != 0.21.1
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   638  100   638    0     0   1797      0 --:--:-- --:--:-- --:--:--  1792
```
