### ISSUE TITLE
[neovim] Crash

### ISSUE THREAD

**Issue by edi9999** [junegunn/fzf#197]
Hi,

when using neovim inside a zsh session (not tmux), I always get the following error when running FZF:

    /build/buildd/neovim-0.0.0+git201504142149+8+9~ubuntu14.04.1/src/nvim/ui.c:445: 
    ui_cursor_left: Assertion `new_col >=0' failed

This doesn't happen if I'm inside a tmux session

**Comment by justinmk** [comment]
Please report to Neovim

**Comment by junegunn** [comment]
Yep, it's definitely a neovim issue, though I can't reproduce.
```
NVIM 0.0.0-alpha+201504111922 (compiled Apr 12 2015 13:02:55)
Commit: e4975f82c9704aa5d52e18e578a449268654ee37
```

**Comment by edi9999** [comment]
Hey @junegunn && @tarruda ,

after upgrading to the latest version of fzf on my second computer (which was not affected by this bug for now), I encountered the same issue again.

I suspect the issue comes from fzf rather than neovim, because both had the latest version of neovim, but different versions of fzf until today.

So after finding out that the version 0.9.7 worked well, I started a git bisect to find out where the problem comes from.

    ➜  .fzf git:(master) git bisect bad
    ➜  .fzf git:(master) git bisect good 0.9.7
    Bisecting: 49 revisions left to test after this (roughly 6 steps)
    [16ca9c688b6f6c5607ebf78f67ca66e7f250db7a] Revert "[fzf-tmux] Fix #204 - Escape command substitution"
    ➜  .fzf git:(16ca9c6) git bisect bad
    Bisecting: 24 revisions left to test after this (roughly 5 steps)
    [2d68cb8639a78ec6b7e88dd71e2ce1a638e5f8ea] Fix #185 - Terminate on RuneError
    ➜  .fzf git:(2d68cb8) git bisect bad
    Bisecting: 12 revisions left to test after this (roughly 4 steps)
    [797f42ecc614f732080de70b1006616f435de4f0] Update README
    ➜  .fzf git:(797f42e) git bisect bad
    Bisecting: 5 revisions left to test after this (roughly 3 steps)
    [4760bb7743955f4a40f4da3656fac751fcab9815] Merge pull request #180 from mhinz/check-if-already-running
    ➜  .fzf git:(4760bb7) git bisect bad
    Bisecting: 2 revisions left to test after this (roughly 2 steps)
    [68503d32df91ded701cf7ad07f340aade4aa2e1d] [vim] Code cleanup
    ➜  .fzf git:(68503d3) git bisect good
    Bisecting: 0 revisions left to test after this (roughly 1 step)
    [c1adf0cd3df8b6ce4724678976eac6d87318c38d] Check if :FZF is already executing
    ➜  .fzf git:(c1adf0c) git bisect bad
    Bisecting: 0 revisions left to test after this (roughly 0 steps)
    [622e69ff54f27363abc2ac18a5a69751f2b42f4a] [vim] Neovim compatibility (#137)

Here are the versions I use:

    tmux -V && fzf --version
    tmux 1.9
    0.9.11

I also use zsh, but I can reproduce the issue even without using zsh and without using tmux (just running neovim from a shell)

Hope that helps to find the origin of the bug

**Comment by junegunn** [comment]
> I suspect the issue comes from fzf rather than neovim

No, it's strictly Neovim's issue. What's crashing is the terminal emulator of Neovim, not fzf. It may be possible that some changes made in fzf somehow made its host more susceptible to crash, but that doesn't mean fzf is doing something wrong.

**Comment by edi9999** [comment]
Ok I think I understand it now : the new :terminal is not yet bug free so that's why that commit which uses it makes nvim crash.

**Comment by edi9999** [comment]
For those who are encountering the same issue, you can `fix` it by running :

    git checkout 68503d3 -- plugin/fzf.vim

68503d3 being the commit that introduces the new term usage

**Comment by lazywei** [comment]
Personally, I don't think we should chekcout to use old version of fzf.vim. Also, as @junegunn said, this is not the issue in fzf but in neovim. The correctly way to solve this is waiting neovim for fixing the bug.
That being said, I found there is a way to by pass this .. you can just use `<C-v>` to open a splited window, and then close the other windows by `<C-w> o`.

**Comment by edi9999** [comment]
Using C-v + C-w o seems a bit complicated, so I'm sticking with the old vim version for now, but will be happy to upgrade once the nvim bug has dissapeared

**Comment by junegunn** [comment]
@edi9999 @lazywei Try updating the vim plugin to the latest and see if it helps. I added a `redraw!` hoping that it would help avoid some race conditions and it does seem to help. It probably [isn't a perfect solution](https://github.com/junegunn/fzf/issues/205#issuecomment-101755075) to the problem, but I haven't run into an issue yet and feels pretty usable.

**Comment by lazywei** [comment]
it works like a charm!! :+1:

**Comment by edi9999** [comment]
It solves most of the problems for me, however, if I start neovim in a folder, than run fzf, the file will not open. 

Eg:

```
nvim .
:Fzf 
file.xml<cr>
```

I'm using NerdTree but I don't think it has any impact

**Comment by forbesmyester** [comment]
Perhaps wierdly, it always crashes / closes the buffer when I am editing Haskell files, but works flawlessly in markdown files.

**Comment by justinmk** [comment]
@forbesmyester @edi9999 @lazywei Is this still happening on latest Neovim?

**Comment by forbesmyester** [comment]
I have not updated my neovim but FZF has (probably) been updated. I can no longer replicate it. Sorry for not being able to give a definitive answer.

**Comment by edi9999** [comment]
I think the problem is gone for me now
