### ISSUE TITLE
Make `defaultOptions` into a public function

### ISSUE THREAD

**Issue by cipriancraciun** [junegunn/fzf#1971]
At the moment the `defaultOptions` function is private, as such it can't be used by other libraries:
* https://github.com/junegunn/fzf/blob/373c6d8d55066251dc7af58598de6af4ff4570cf/src/options.go#L224-L230

A simple patch like:
* https://github.com/cipriancraciun/fzf/commit/524c512952bcc8c8a53bde07691d3ea367b77823

, could allow users to prepare options with `fzf` upstream defaults, override what they need, and pass it to `fzf.Run`.  (This is especially useful for those wanting to embed `fzf` in their own tools.)

**Comment by cipriancraciun** [comment]
So I'm assuming this is a "wont' fix" also?

**Comment by junegunn** [comment]
Yes.
