### ISSUE TITLE
search for partially typed commands

### ISSUE THREAD

**Issue by b0x4it** [junegunn/fzf#1972]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

I am using fzf for searching in bash history using Ctrl+R. It works properly and is great. Thank you!

Sometimes I type several characters of a command and then decide to search it in history, so I press Ctrl+R to search. When I do that, fzf shows the list, but it does not have my partially types command. So, I need to type the command again. Is there a way to avoid this so that fzf pulls whatever already typed in command line already and searches for it in history?

**Comment by junegunn** [comment]
You just need to use the latest version. See #1886.
