### ISSUE TITLE
Add support for using `fzf` as an embedded library

### ISSUE THREAD

**Issue by cipriancraciun** [junegunn/fzf#1976]
As I've stated in #1971, `fzf` is a great console tool, and thus it would be similarly great to embed it in various other tools as a "menu" provider.

Therefore, I've tried looking in the code starting with the `Run` function:
* https://github.com/junegunn/fzf/blob/master/src/core.go#L46-L59

However the code uses a few `os.Exit` calls, which basically breaks any user code that would call that function.

Now, granted patching the code and replacing those with `return` would be quite easy, however I'm more concerned with the various programming assumptions that were taken regarding "cleanup".  Is the current code usable multiple times, or the assumption was that the process will be terminated after the run, thus no attempt of cleanup is made.

**Comment by junegunn** [comment]
Hi, this was suggested a few times in the past, but it's a non-goal. See my previous comment:

https://github.com/junegunn/fzf/pull/1053#issuecomment-330024275
