### ISSUE TITLE
Not all environment variables are documented

### ISSUE THREAD

**Issue by iFreilicht** [junegunn/fzf#1979]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

When searching for "Environment Variables" regarding fzf, whether in the `README.md`, `fzf --help` or `man fzf`, only two environment variables are documented:

`FZF_DEFAULT_COMMAND` and `FZF_DEFAULT_OPTS`. However, there's also at least `FZF_TMUX`, `FZF_TMUX_OPTS`, `FZF_COMPLETION_TRIGGER` and `FZF_COMPLETION_OPTS`, maybe even others as well that I don't know about.

These should be added to all three documentations mentioned above.

**Comment by junegunn** [comment]
> FZF_DEFAULT_COMMAND and FZF_DEFAULT_OPTS

These are the only variables that fzf binary itself recognizes.

The others are the ones used in the shell scripts which are optional, so they shouldn't appear on the man page or on `--help` output. They are documented separately on the README page. The ones that aren't mentioned on the page are deprecated and you should not rely on them.
