### ISSUE TITLE
s:build_quickfix_list_test never called

### ISSUE THREAD

**Issue by mangelozzi** [junegunn/fzf#1982]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf (just updated)
- [x] I have searched through the existing issues

## Info

- OS : Ubuntu 18.04
- Neovim 0.5

## Problem / Steps to reproduce

Can't get the [README.md example](https://github.com/junegunn/fzf/blob/master/README-VIM.md#examples) to work. If I press `CTRL+q`, any commands within the function are never run, and I get the exact same result as if I was just pressed `<ENTER>` (both cases open a populated quickfix window):
```
" An action can be a reference to a function that processes selected lines
function! s:build_quickfix_list_test789766(lines)
  " Delete the orginal code in the function, and see get the same result   
  " Can put anything here and it is always ignored, e.g. :qa! is never run
  :qa!
endfunction

let g:fzf_action = {
  \ 'ctrl-q': function('s:build_quickfix_list_test789766'),
  \ 'ctrl-t': 'tab split',
  \ 'ctrl-x': 'split',
  \ 'ctrl-v': 'vsplit' }
" When aborting fzf in Neovim, <Esc> does not work, so fix it:
tnoremap <expr> <Esc> (&filetype == "fzf") ? "<Esc>" : "<c-\><c-n>"
```
 The reason I came across this issue is because I added extra commands to `s:build_quickfix_list`, and they where just being ignored (commands to highlight the search term within the quickfix window).

This issue may seem close to (https://github.com/junegunn/fzf/issues/1885), but its a bit different in that for me quickfix window is being populated, but for him https://github.com/junegunn/fzf/issues/1885

**Comment by junegunn** [comment]
Works for me. Quite possibly you are expecting it to work with commands other than `:FZF` (or `:Files` from fzf.vim) that deal with simple file paths. I've updated the documentation.

- https://github.com/junegunn/fzf/blob/master/README-VIM.md#global-options-supported-by-fzfwrap
- https://github.com/junegunn/fzf.vim/issues/1131
