### ISSUE TITLE
Interactive Reverse search not working MacOS

### ISSUE THREAD

**Issue by ssvegeta96** [junegunn/fzf#1986]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish
    
## Problem / Steps to reproduce
When installing `fzf` on `macos` `10.1x.x` etc

![image](https://user-images.githubusercontent.com/9201991/79255858-d6321c80-7e3b-11ea-990f-aef306317e4d.png)

>brew install fzf 
> press y to update source files and update keybindings etc

The below line is added to `.bashrc`
> [ -f ~/.fzf.bash ] && source ~/.fzf.bash

Well for whatever reason that doesn't let you use the `ctrl + r` `reverse search` like so

![image](https://user-images.githubusercontent.com/9201991/79256084-4476df00-7e3c-11ea-9829-a56a8c89b54e.png)

maybe chnage that for the install or change the README to reflect that

**Resolution**
I fixed this by adding

> [ -f ~/.fzf.bash ] && source ~/.fzf.bash

to my `.bash_profile` NOT my `.bashrc`

![image](https://user-images.githubusercontent.com/9201991/79256553-1219b180-7e3d-11ea-9e43-4c9194198a98.png)

Thank you

**Comment by junegunn** [comment]
Thanks, you might want to read through https://apple.stackexchange.com/questions/51036/what-is-the-difference-between-bash-profile-and-bashrc to learn the difference between .bashrc and .bash_profile. So it's a very common practice to put everything in .bashrc and make .bash_profile simply load .bashrc as https://apple.stackexchange.com/a/51043/125495 suggests. But I can see that some users are not familiar with how things work. I'll think about clarifying that in the output message of the install script.

See my previous answer on the same question:
- https://github.com/junegunn/fzf/issues/282#issuecomment-116651487

**Comment by ssvegeta96** [comment]
im familiar with how it works.......
im simpling showing other how to resolve and issue with the way you implement or instruct in your read me
