### ISSUE TITLE
Variable completion not working

### ISSUE THREAD

**Issue by mklcp** [junegunn/fzf#1987]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

If I set

````
export FZF_COMPLETION_DIR_COMMANDS="cd"
````

then type

````
cd $HO<TAB>
````

the default variable completion doesn't work, the result should be

````
cd $HOME
````

after having hit TAB (supposing of course that only `HOME` is the only variable starting with `HOM`).

I'm using bash v5.0.16, and for what I've investigated, it's due to the lines

````
# Directory
for cmd in $d_cmds; do
  __fzf_defc "$cmd" _fzf_dir_completion "-o nospace -o dirnames"
done
````

in `shell/completion.bash`.

I've replaced `"-o nospace -o dirnames"` by `"-o default -o bashdefault -o dirnames"`, and it fixes the problem, while keeping fzf's trigger mechanism working.
 `-o nospace` seems to prevent variable completion totally, so I've removed it.

This is a very small issue, so I'vn't opened a pull request, but I can if you'd like to. I don't use zsh though, and for what I can glimpse of the source code it's totally different, I can't really help with that.

**Comment by junegunn** [comment]
I can't reproduce the problem.

```sh
$ complete | grep fzf_dir
complete -o nospace -F _fzf_dir_completion cd

$ cd $HO
$HOME      $HOSTNAME  $HOSTTYPE
```

I'm running bash 5.0.11 on macOS.

**Comment by melopee** [comment]
Well, I don't know what to do then. The problem is still present when I trim down my bashc to:

````
export PATH="$PATH:$HOME/.local/bin/fzf/bin"
export FZF_HOME="$BIN/fzf"
[[ $- == *i* ]] && source "$FZF_HOME/shell/completion.bash" 2> /dev/null
source "$FZF_HOME/shell/key-bindings.bash"
````
but it disappears when I add the line

````
__fzf_defc "cd" _fzf_dir_completion "-o default -o bashdefault -o dirnames"
````
I'm not knowledgeable at all about bash completion, but I don't really understand how

````
# Directory
for cmd in $d_cmds; do
  __fzf_defc "$cmd" _fzf_dir_completion "-o nospace -o dirnames"
done
````

build variable completion for the $d_cmds, I don't think it is included in `nospace` and `dirnames`.

**Comment by evanhorn** [comment]
I came here attempting to solve this same problem with Bash 5.0.17 on Ubuntu 20.04, and I can confirm that the solution presented here does, in fact, resolve the issue.

**Comment by Maxim4711** [comment]
The same issue here - bash 4.4.20(1),  Oracle Linux 8.9, fzf installed via git clone
Adding `__fzf_defc "cd" _fzf_dir_completion "-o default -o bashdefault -o dirnames"` resolvers the issue. Variable completion (without this line) doesn't work only for cd command, for other commands (like echo $HO) variables completion is working

**Comment by junegunn** [comment]
I can't reproduce the problem with the latest version of fzf (0.48.1). Please comment if you still have the issue with that version.

Possibly related: https://github.com/junegunn/fzf/commit/0740ef7ceb717676c7d8328a655e1554e1b0d366

**Comment by Maxim4711** [comment]
Yes, i can reproduce the problem with the latest version of fzf (0.48.1) - as i mentioned, at least on the oracle enterprise linux 8.9 with vanilla .bashrc

**Comment by junegunn** [comment]
Okay, I can reproduce the problem and I can confirm that the suggested fix works.

The reason I could not reproduce the problem was that I had bash_completion installed. Thanks @Maxim4711, your comment "with vanilla .bashrc" helped me find the cause.

**Comment by junegunn** [comment]
Oops, that breaks a test case.
