### ISSUE TITLE
How to remove preview window borders?

### ISSUE THREAD

**Issue by mahdix** [junegunn/fzf#1989]
- [ X] I have read through the manual page (`man fzf`)
- [ X] I have the latest version of fzf
- [ X] I have searched through the existing issues

## Info

- OS
    - [ X] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ X] bash
    - [ ] zsh
    - [ ] fish
    
## Problem / Steps to reproduce:

If you run fzf with a preview command like `cat` there will be dash lines around preview window. This makes it difficult to copy multi-line text from preview window because those dashes will be included into the selection. Is there an option to remove/disable these borders?

![image](https://user-images.githubusercontent.com/9294049/79621057-e97a0c00-8109-11ea-9fc1-c38da89bc4b4.png)

**Comment by junegunn** [comment]
`--preview-window noborder`

**Comment by Shamaoke** [comment]
@junegunn Is there any way to draw a border between the search area and the preview area, e. g. `--preview-window=border-left`?

**Comment by junegunn** [comment]
@Shamaoke Yes. That should work. Excerpt from the man page:

> * To change the style of the border of the preview window, specify one of the options for --border with border- prefix.  e.g. border-rounded (border with rounded edges, default), border-sharp (border with sharp edges), border-left, border-none, etc.

**Comment by Shamaoke** [comment]
@junegunn Thanks. That works. (I read an outdated manual. It wasn't there.).
