### ISSUE TITLE
bash: line 73: BASH_SOURCE[0]: unbound variable

### ISSUE THREAD

**Issue by grammy-jiang** [junegunn/fzf#1990]
- [X] I have read through the manual page (`man fzf`)
- [X] I have the latest version of fzf
- [X] I have searched through the existing issues

## Info

- OS
    - [X] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [X] bash
    - [ ] zsh
    - [ ] fish
    
## Problem / Steps to reproduce
I notice the `install` script is used to configure fzf in manual page, and I want to install fzf without running `git clone`, so I try to run this command:

```sh
curl -fsSL https://raw.githubusercontent.com/junegunn/fzf/master/install | bash -
```

Then I met this message:

```console
pi@raspberrypi:~ $ curl -fsSL https://raw.githubusercontent.com/junegunn/fzf/master/install | bash -                                                                                         
bash: line 73: BASH_SOURCE[0]: unbound variable
Downloading bin/fzf ...
  - Found in $PATH
  - Creating symlink: bin/fzf -> /home/grammy-jiang/.fzf/bin/fzf
main: line 115: cd: /home/pi/bin: No such file or directory
  - Checking fzf executable ... Error: main: line 92: /home/pi/bin/fzf: No such file or directory                                                                                            
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   636  100   636    0     0   1297      0 --:--:-- --:--:-- --:--:--  1297
100 1057k  100 1057k    0     0   381k      0  0:00:02  0:00:02 --:--:--  584k
  - Checking fzf executable ... 0.21.1

Generate /home/pi/.fzf.bash ... OK
Generate /home/pi/.fzf.zsh ... OK

Finished. Restart your shell or reload config file.
   source ~/.bashrc  # bash
   source ~/.zshrc   # zsh

Use uninstall script to remove fzf.

For more information, see: https://github.com/junegunn/fzf

```

## Why

I did some research and find some leads:

* [bash: GNU Bourne-Again SHell - Linux Man Pages (1)](https://www.systutorials.com/docs/linux/man/1-bash/):
  

> **BASH_SOURCE**
An array variable whose members are the source filenames where the corresponding shell function names in the FUNCNAME array variable are defined. The shell function ${FUNCNAME[$i]} is defined in the file ${BASH_SOURCE[$i]} and called from ${BASH_SOURCE[$i+1]}.

So executing the script from input does not have `BASH_SOURCE`, that's the reason.

**Comment by junegunn** [comment]
> I want to install fzf without running git clone

The script needs the whole directory structure. So you just can't run it like that.
