### ISSUE TITLE
Completion in zsh is always based on first command

### ISSUE THREAD

**Issue by RobSis** [junegunn/fzf#1992]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

In bash, you can invoke different completions in one line, e.g.:

    ssh **<Tab>; ls **<Tab>; unalias **<Tab>;

But in zsh, the ssh menu would be displayed everytime.

**Comment by MenkeTechnologies** [comment]
see my comments on how I solved partitioning the command line to get command word.

**Comment by RobSis** [comment]
Works great! Thanks.
