### ISSUE TITLE
defaultCommand does not work in shells without pipefail

### ISSUE THREAD

**Issue by minusf** [junegunn/fzf#1993]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [x] Etc. OpenBSD
- Shell
    - [ ] bash
    - [ ] zsh
    - [ ] fish
    - [x] ksh (public domain korn shell)
    
## Problem / Steps to reproduce

OpenBSD's default shell, `ksh` does not support `set -o pipefail` atm. As such, the built-in `defaultCommand` fails to run.  There are other shells that do not support this option (e.g. `csh`). i am not sure `pipefail` is in POSIX or not.

I was wondering if it was possible to make `defaultCommand` a bit more conservative, basically the "Windows" version below it, as that is likely to work in any shell, anywhere. Even though many people override the default command and pimp it up, i think it's nice if the default is not throwing an error on as many systems as possible...

**Comment by rjc** [comment]
@minusf OpenBSD's default `$SHELL` is `ksh` or, if you must, [`oksh`](/ibara/oksh) - **not** `mksh` (MirBSD Korn Shell), which is a _derivative_ of OpenBSD's `PDKSH` and **does** support `pipefail`.

**Comment by junegunn** [comment]
Shouldn't your shell run the subsequent find command even when `set -o pipefail` fails? 

```sh
# This works for me
FZF_DEFAULT_COMMAND='set -o foobar; ls' fzf
```

**Comment by minusf** [comment]
that fails in both openbsd `ksh` and `mksh`.

sorry about the typo in the report, indeed i meant openbsd `ksh` and not `mksh` (which i use on macOS).

**Comment by rjc** [comment]
@minusf

```
$ # oksh
$ set -o pipefail
oksh: set: pipefail: bad option
$ echo $?         
1
```
```
$ # mksh
$ set -o pipefail
$ echo $?
0
```

Are you sure it is related to pipefail?

**Comment by minusf** [comment]
my report says: if the shell has no option to pipefail, the command will fail.  it is not a fault of `pipefail` as such, but of any unknown option.  for `ksh`, `pipefail` is an unknown option.

i just reported back that while `mksh` has `pipefail`, it will also not execute commands after a faulty `set`...

**Comment by minusf** [comment]
> Shouldn't your shell run the subsequent find command even when `set -o pipefail` fails?

i think this is a bit of a philosophical question... should the shell continue when a behaviour changing command has just failed?  there is some logic in failing when it's not possible to set some desired/not desired option....

**Comment by junegunn** [comment]
```sh
$ ksh --version
  version         sh (AT&T Research) 2020.0.0
$ set -o pipefail
$ echo $?
0
```

**Comment by minusf** [comment]
```
$ set | grep VERSION
KSH_VERSION='@(#)PD KSH v5.2.14 99/07/13.2'
$ set -o pipefail
ksh: set: pipefail: bad option
$ echo $?
1
```

**Comment by emilysnow2477** [comment]
OpenBSD's ksh gained support for pipefail in 6.8 ([see this commit on 2020-07-07](https://marc.info/?l=openbsd-cvs&m=159411805503904&w=2)) so this issue should be closed.

```
$ uname -sr
OpenBSD 6.9
$ echo "${KSH_VERSION}"
@(#)PD KSH v5.2.14 99/07/13.2
$ set -o pipefail; echo "$?"
0
```
