### ISSUE TITLE
Ctrl+R issues with Fish Shell on Linux

### ISSUE THREAD

**Issue by terminator14** [junegunn/fzf#1998]
- [X] I have read through the manual page (`man fzf`)
- [X] I have the latest version of fzf
- [X] I have searched through the existing issues

## Info

- OS
    - [X] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [X] fish
    
I am running fzf, installed from git commit a6d3e3687ba2ee26266400db6c77a07bc4ff8fca, using the install script.

Running on CentOS 7.7.1908.
Using Fish shell version 2.3.1.

Hitting Ctrl+R doesn't always work.
Sometimes, it works as expected.
Other times, it just writes `[1;43R` on the terminal and does nothing else (doesn't bring up the fzf menu).
Other times, it does nothing.

To give you an idea of how often this happens, I ran Ctrl+R 25 times in my fish shell, hitting Esc between each time to close the fzf menu (if it opened), or deleting the `[1;43R` characters if they were written. These were the results:

- Worked as Expected - 13 times
- Nothing happened - 3 times
- `[1;43R` characters written to terminal - 9 times

If it helps, on the same system, FZF's Ctrl+R in bash works perfectly every time.
Also, if it matters, I'm remotely connected to the system with SSH.
Also, I am NOT running tmux or screen.

**Comment by junegunn** [comment]
You're using a very old version of fish. Fish has been changing/improving pretty fast for the past years and you definitely should consider upgrading your fish. Please report back if you still have the issue with the latest fish.

**Comment by terminator14** [comment]
Confirmed fixed. Upgrading to fish 3.1.0 resolved all issues.

For anyone else coming across this:

CentOS 7 Epel repo comes with fish 2.3.1, which is what I was using. It appears that FZF uses some features that are too new to work with that old version of fish.

Most of the RPMs and Repos for the latest fish appear to be geared towards CentOS 8, so I had some trouble installing it on CentOS 7, but it finally worked using fish-3.1.0-3.1.x86_64.rpm from https://software.opensuse.org/download.html?project=shells%3Afish%3Arelease%3A3&package=fish.

Note: Go under RHEL, which has the RHEL 7 RPM (compatible with CentOS 7) - NOT CentOS, which only has the CentOS 8 RPM.

Thanks @junegunn

**Comment by tjohnston-cd** [comment]
It seems like this is issue is happening for me with fish 3.1.1-1 (the latest archlinux package)..?

Anything I can check to debug it?

**Comment by tjohnston-cd** [comment]
Oh wow..that's a good catch. Thanks!
