### ISSUE TITLE
Windows Defender detects a virus

### ISSUE THREAD

**Issue by JekRock** [junegunn/fzf#2002]
- [ ] I have read through the manual page (`man fzf`)
- [ ] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [ ] Mac OS X
    - [x] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

Can't upgrade fzf from 0.21.0 to 0.21.1 on Windows via chocolatey because the Windows Defender detects a virus Trojan:Script/Wacatac.C!ml

**Comment by junegunn** [comment]
Related: #1110

**Comment by JekRock** [comment]
But the previous version  worked fine

**Comment by junegunn** [comment]
There's nothing I can do. Just ignore the warning from the defender.

https://golang.org/doc/faq#virus

**Comment by darkvertex** [comment]
FYI for Windows Defender you can submit your suspicious file saying you believe it's a false positive and they might readjust their definitions after it's reviewed:
https://www.microsoft.com/en-us/wdsi/filesubmission

One more tip: if you're in Linux and want to check what Windows antiviruses engines think of a file, http://virustotal.com is great for that.

**Comment by rayiik** [comment]
Thats weird i use fzf on windows all the time and its never been flagged but i run in wsl, have you considered using windows subsystem for linix? It works much better then a vm or chocolaty ive found (just a thought)
