### ISSUE TITLE
syntax error near unexpected token 

### ISSUE THREAD

**Issue by TH3xACE** [junegunn/fzf#2005]
- [x ] I have read through the manual page (`man fzf`)
- [x ] I have the latest version of fzf
- [ x] I have searched through the existing issues

## Info

- OS
    - [x ] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x ] bash
    - [ ] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

When I open a new terminal I get this error:

```
bash: /root/.fzf.bash: line 3: syntax error near unexpected token `then'
bash: /root/.fzf.bash: line 3: `if [[ ! "$PATH" == */root/.fzf/bin* ]]; then'
```

**Comment by TH3xACE** [comment]
just for information... I have remove/uninstall everything then install fzf again with apt-get install and
 add these in .bashrc.

Append this line to ~/.bashrc to enable fzf keybindings for 

   source /usr/share/doc/fzf/examples/key-bindings.bash

Append this line to ~/.bashrc to enable fuzzy auto-completio

   source /usr/share/doc/fzf/examples/completion.bash

bash: /usr/share/doc/fzf/examples/key-bindings.bash: line 14oken `then'
bash: /usr/share/doc/fzf/examples/key-bindings.bash: line 14
bash: /usr/share/doc/fzf/examples/completion.zsh: line 12: sn `then'
bash: /usr/share/doc/fzf/examples/completion.zsh: line 12: `

Which means there is most probably an issue somewhere.....


 $ bash --version
GNU bash, version 5.0.11(1)-release (x86_64-pc-linux-gnu)

**Comment by TH3xACE** [comment]
$ source key-bindings.bash
bash: /usr/share/doc/fzf/examples/key-bindings.bash: line 14: syntax error near unexpected token `then'
bash: /usr/share/doc/fzf/examples/key-bindings.bash: line 14: `if [[ $- =~ i ]]; then'

**Comment by junegunn** [comment]
This definitely looks like a configuration issue. I don't think we can help you.

```
bash: /usr/share/doc/fzf/examples/key-bindings.bash: line 14oken `then'
bash: /usr/share/doc/fzf/examples/key-bindings.bash: line 14
bash: /usr/share/doc/fzf/examples/completion.zsh: line 12: sn `then'
bash: /usr/share/doc/fzf/examples/completion.zsh: line 12: `
```

Why is there `zsh` in the output? There must be some misconfiguration.

**Comment by TH3xACE** [comment]
Sorry was just an example but similar issue... as you can see below

[13:21:30] [root@kaladm .../fzf/examples]  
$ source completion.bash 
bash: completion.bash: line 12: syntax error near unexpected token `then'
bash: completion.bash: line 12: `if [[ $- =~ i ]]; then'
[
13:21:43] [root@kaladm .../fzf/examples] 
 $ source key-bindings.bash
bash: key-bindings.bash: line 14: syntax error near unexpected token `then'
bash: key-bindings.bash: line 14: `if [[ $- =~ i ]]; then'

**Comment by TH3xACE** [comment]
if I install as this
git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
~/.fzf/install

then open a new terminal, I get this

bash: /root/.fzf.bash: line 3: syntax error near unexpected 
bash: /root/.fzf.bash: line 3: `if [[ ! "$PATH" == */root/.f
[13:31:18] [root@kaladm ~]

**Comment by TH3xACE** [comment]
and if I manually do the config refresh:

 $ source ~/.bashrc 
bash: /root/.fzf.bash: line 3: syntax error near unexpected token `then'
bash: /root/.fzf.bash: line 3: `if [[ ! "$PATH" == */root/.fzf/bin* ]]; then'

**Comment by junegunn** [comment]
The code blocks are not properly formatted, it's unreadable.

The files contain ordinary bash scripts. You should be able to read it and spot errors if they are somehow corrupted.
