### ISSUE TITLE
[Feature Request] Scriptable matching

### ISSUE THREAD

**Issue by mvrozanti** [junegunn/fzf#2007]
What I mean by that is: the user should be able to specify what items match given a certain filter. 

To more easily illustrate what I mean:

Suppose you have a list of names.

```
Mario Speedwagon
Petey Cruiser
Anna Sthesia
Paul Molive
Anna Mull
Wilma Mumduya
Gail Forcewind
Paige Turner
Bob Frapples
Walter Melon
Nick R. Bocker
```

I would like to be able to match "Walter Melon" and "Wilma Mumduya" by their initials: "wm". This is a _type_ of matching that while not everyone would like to have built into fzf as an option, they should be able to somehow script it through fzf. Something like a regex that takes into account each item and the user input.  For this example, I figure something like the following should suffice to describe _what_ should match:

`--regex-match='(\w)\w*'`

Is this a wanted feature? I never wrote a line of code in golang so I can't really contribute other than with the idea.

**Comment by junegunn** [comment]
> I would like to be able to match "Walter Melon" and "Wilma Mumduya" by their initials: "wm".

That's not a good example :) fzf already works that way.

![image](https://user-images.githubusercontent.com/700826/80344496-a571ce80-88a2-11ea-9983-c10d7ad38a4e.png)

> Is this a wanted feature?

No, this is beyond the scope of the project. I'd like to keep the matching algorithm as generic as possible.
