### ISSUE TITLE
fzf nondeterministically hangs, can't be interrupted or quit

### ISSUE THREAD

**Issue by wchargin** [junegunn/fzf#2009]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [X] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [X] bash
    - [ ] zsh
    - [ ] fish
    
## Problem / Steps to reproduce
Every once in a while, when I press Ctrl-R to trigger history completion
with fzf, the fzf process hangs and locks the whole shell.

What I see in my shell is:

```
$ `__fzf_history__`

```

(where `$` is my prompt). The text cursor is on the next line, and the
mouse cursor is in “pointer” mode (indicating that I can use the mouse
to click a selection), like it is when fzf is running properly, whereas
usually in a terminal the cursor is in “text” mode (looks like “工”).

![Screenshot of broken state][ss-1]

I can’t get out of this state with Ctrl-C or Ctrl-Backslash (SIGQUIT).
If I find the `fzf` process and send SIGKILL to it, then I recover my
shell session and there’s usually some gibberish in the command line:

![Screenshot after SIGKILLing fzf][ss-2]

(In the above screenshot, `'-web` was the start of an fzf query that I
had started typing; I don’t know what the rest is.)

I have to run `tput reset` or `reset` to get my shell fully back to its
normal state (e.g., mouse cursor).

This happens both on a local machine and over SSH, in case that matters.

Next time this happens I’ll try to remember to grab a dump with `gcore`
in case that’s helpful.

I invoke fzf probably hundreds of times per day, and this happens maybe
once every few days, so it’s not super common. It can happen in a shell
where Ctrl-R has just worked a moment before.

Other than this, I’m super happy with fzf and recommend it to lots of
people; thanks very much for your continued work on it. :-)

[ss-1]: https://user-images.githubusercontent.com/4317806/80434063-96444e00-88ad-11ea-979e-944b104b44f8.png
[ss-2]: https://user-images.githubusercontent.com/4317806/80434423-97c24600-88ae-11ea-9383-5892b0085ef9.png

**Comment by p-kolacz** [comment]
I have similar problem in fish shell. Ctrl-R or Alt-C hangs the shell every time. Ctrl-C works for me.

**Comment by matiaslindgren** [comment]
I'm seeing this in fish shell also, but not in bash. Running `fzf` works fine, but `fzf-history-widget` with `fish_trace` enabled hangs on `fzf --read0 --print0 -q ''`, which I think is this line: https://github.com/junegunn/fzf/blob/0.21.0/shell/key-bindings.fish#L50

**Comment by junegunn** [comment]
If you use fish 3.1.1, you should upgrade because it's broken. See #2008.

As for bash, I've never experienced the problem so I can't really tell what's going on. I'd suggest that you 1. use a different version of bash, 2. see if the problem is reproducible with a minimal shell configuration (i.e. nothing but fzf)

**Comment by zoj613** [comment]
@wchargin  This is almost exactly what I experience in this issue https://github.com/junegunn/fzf/issues/2289, except it happens only if I press CTRL-Z while the fzf histroy menu is active.
