### ISSUE TITLE
completion for tcsh/csh shell

### ISSUE THREAD

**Issue by justrajdeep** [junegunn/fzf#2011]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] fish
    
    - [ ] zsh
## Problem / Steps to reproduce

Could not find any command line completion framework for `tcsh`. Found it for `bash`/`zsh`? Can you please help with command line completion for `tcsh`?

**Comment by junegunn** [comment]
I don't use tcsh, so it's not something I can do. Are you interested in opening a pull request?

**Comment by justrajdeep** [comment]
I will try and see if I can do a PR. I have not worked on something like this before, might take me a bit of time.

**Comment by justrajdeep** [comment]
i took a look at it following how git completion script for tcsh internally uses the bash completion script. But could not get it to work. Unless i get some more pointers i dont think i will be able to do this.

**Comment by junegunn** [comment]
Okay, thanks for looking into it. I don't think I'm going to implement this either so I'm going to close this as wontfix.

**Comment by redesigndavid** [comment]
Late to the party, but I could actually help with this.

@junegunn, what constitutes a complete set of completions though?  Looking at completion.bash and completion.zsh, there are different sets of completions. 

From what I could tell we need completions that take care of:
1. proc
2. env variable
3. alias
4. fzf options
5. folder
6. filename.

Did I miss anything?

**Comment by niv280** [comment]
Hi, i am using tcsh and i would love to use fzf in tcsh too.
Any progress with that?

**Comment by TummanapallyAnuraag** [comment]
Would love to have it on `tcsh` too

**Comment by hellovimo** [comment]
Did anyone try using tcsh ? or anyone tried the fzf-csh ?
