### ISSUE TITLE
Highlighted substrings background

### ISSUE THREAD

**Issue by ipod825** [junegunn/fzf#2016]
# Problem / Steps to reproduce

Is it possible to have an option for highlighting the background of the searched substrings?

Context:
I am using `fzf.vim` (in neovim) and have this function to search word in file:
```vim

function! s:Line_handler(l)
    let keys = split(a:l, ':')
    exec keys[0]
    call feedkeys('zz')
endfunction

function! SearchWord()
    let s:fzf_ft=&ft
    augroup FzfSearchWord
        autocmd!
        autocmd FileType fzf if strlen(s:fzf_ft) && s:fzf_ft!= "man" | silent! let &ft=s:fzf_ft | endif
    augroup END
        silent call fzf#run(fzf#wrap({
                    \   'source':  map(getline(1, '$'), '(v:key + 1) . ": " . v:val '),
                    \   'sink':    function('s:Line_handler'),
                    \   'options': '+s -e --ansi',
                    \}))
    let s:fzf_ft=''
endfunction
```
The maor improvement over the default `:Lines` command is that it sets the filetype of the searching buffer to that of the original file. But if the searched word is highlighted by nvim, then the default fzf option `--color hl:1,hl+1` can't highlight the searched text. Maybe adding the ability to highlight the background could solve the problem?

**Comment by junegunn** [comment]
Since 0.24.0, you can set `reverse` attribute.

```sh
# Apply reverse attribute
rg --line-number --no-heading --color=always "" |
  fzf --ansi --color hl:reverse,hl+:reverse

# -1 means keeping the original foreground color
rg --line-number --no-heading --color=always "" |
  fzf --ansi --color hl:reverse:-1,hl+:reverse:-1
```

There are also `italic`, `underline`, etc. See `man fzf` for details.

**Comment by ipod825** [comment]
Awesome, I have this fancy line search now:

![DeepinScreenshot_xterm_20201030111919](https://user-images.githubusercontent.com/1246394/97742704-e0e39480-1aa1-11eb-8255-39e7e37606fb.png)
