### ISSUE TITLE
'execute()' is not executed if there is no match for current query

### ISSUE THREAD

**Issue by doak** [junegunn/fzf#2017]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

For `fzf --bind=alt-m:"execute(echo test)"` I expect that `fzf` executes the defined command (prints "test") every time `alt-m` is hit, regardless if there is a match for the current query.
But it only prints `test` if there is at least one match.

Is this intended?

Interestingly the command **is** executed if it its replaced by `execute(echo test {q})`.

**Comment by woefe** [comment]
I ran into the same issue (version 0.22.0). I think fzf should always execute commands without placeholders. But maybe there is a deeper reason why that's not allowed? 

Adding a `{q}` only executes the command if there is a non-empty query.

**Comment by junegunn** [comment]
> I think fzf should always execute commands without placeholders

Agreed, it's just that the use case wasn't considered when the code was initially written.
