### ISSUE TITLE
History Bindings Don't Work Until Command Issued

### ISSUE THREAD

**Issue by levouh** [junegunn/fzf#2022]
- [X] I have read through the manual page (`man fzf`)
- [X] I have the latest version of fzf
- [X] I have searched through the existing issues

## Info

- OS
    - [X] Linux (EL6 3.8.13-118.22.1)
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [X] bash (bash 4.1.2(2)-release)
    - [ ] zsh
    - [ ] fish
    
## Problem

`fzf` history bindings don't work until a command has been typed.

## Steps to reproduce

1. Install `fzf` and enable everything.
2. `~/.bash_profile` looks like:
```
[ -f ~/.bashrc ] && source ~/.bashrc
```
3. `~/.bashrc` looks like:
```
[ -f ~/.fzf.bash ] && source ~/.fzf.bash
```
4. Exit the current shell session and start a new one.
5. Press `<C-r>` for a history search, notice that the result list is empty.
6. Run:
```
$ echo hi
```
7. Press `<C-r>` again, now the result list is populated with entries from `history`.

`~/.inputrc` is non-existent, and the bash configuration files are only as shown above.

**NOTE:** This problem doesn't happen on my other EL7 machine running bash 4.2.46(2)-release, but I can't seem to figure out _why_. See the version information for the system having the problem above in the _Info_ section.

## Links

Versions of EL6 can be found [here](https://yum.oracle.com/repo/OracleLinux/OL6/UEKR3/latest/x86_64/index.html).

**Comment by junegunn** [comment]
This is not an issue of fzf and I can't help you. You should properly configure your shell to make the underlying command fzf executes (`fc -lnr -2147483648`) work as expected.

**Comment by levouh** [comment]
I understand that this is not likely an `fzf` problem, but what confuses me is that each of the commands work on their own if entered manually in a fresh shell session. Piping them together works. But for some reason the binding itself doesn't.

I should have mentioned the above statements in the original issue, but I'm not familiar with the nuances of read line and was more so looking for where to start with debugging this, as if all things appear to be working, I have no clue.
