### ISSUE TITLE
fzf change directory not working in pop-os (debian)

### ISSUE THREAD

**Issue by ehrktia** [junegunn/fzf#2024]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish
    
## Problem / Steps to reproduce
- install fzf `sudo apt-get install fzf`
- `cd ** <TAB>` as per manual is not giving list of directories with fuzzy search option. Instead is giving all directory list as default shell(zsh).
Please let me know if you require more details.

**Comment by junegunn** [comment]
See https://github.com/junegunn/fzf/issues/1866
