### ISSUE TITLE
Can not build custom fork

### ISSUE THREAD

**Issue by sergei-dyshel** [junegunn/fzf#2027]
I have my custom fork of fzf in [sergei-dyshel/fzf-abbrev](https://github.com/sergei-dyshel/fzf-abbrev). It's a valid fork (`junegunn/fzf` is replaced with `sergei-dyshel/fzf-abbrev` in imports/Makefile) and I successfully built in 2 years ago (last time I did rebase).

But today after rebasing on the latest release (0.21.1), I'm getting the following error:
```
$ make
GOARCH=amd64 go build -a -ldflags "-X main.revision=d5f0baf8 -w -extldflags=" -tags "" -o target/fzf-darwin_amd64
go: extracting github.com/sergei-dyshel/fzf-abbrev v0.0.0-20180928144848-aed6c046b9fb
go: finding github.com/sergei-dyshel/fzf-abbrev latest
build github.com/junegunn/fzf: cannot load github.com/sergei-dyshel/fzf-abbrev/src/protector: module github.com/sergei-dyshel/fzf-abbrev@latest found (v0.0.0-20180928144848-aed6c046b9fb), but does not contain package github.com/sergei-dyshel/fzf-abbrev/src/protector
make: *** [Makefile:103: target/fzf-darwin_amd64] Error 1
```

It looks like instead of building my worktree code it downloads an old module (`aed6c046b9fb` is 2-year old revision before rebase) and tries to build it instead. How can I make it to build the current code?

OS: MacOS
Go version: 1.13.7

**Comment by junegunn** [comment]
I have no idea, because I've never needed to do it :) What have you tried, and what didn't work?

**Comment by sergei-dyshel** [comment]
My bad, I forgot to rename in `go.mod` file :)
