### ISSUE TITLE
Force fzf-tmux to be used for CTRL-R (command history) usage

### ISSUE THREAD

**Issue by megalithic** [junegunn/fzf#203]
Hi there, is there a way (other than editing/overriding the function) to force fzf-tmux to be used when executing command history (CTRL+R) behaviors?

Thanks.

**Comment by junegunn** [comment]
Unfortunately, no. But it's one of the things I've been meaning to address. We currently have `$FZF_TMUX` and `$FZF_TMUX_HEIGHT`, but they only affect `CTRL-T`. I think we should instead make separate vars for each key binding. Also, `CTRL-T` was implemented before `fzf-tmux` was added so it does not leverage the script.

**Comment by junegunn** [comment]
I applied fzf-tmux to CTRL-R and ALT-C, so that all three key bindings now use tmux pane when available. I didn't try to add FZF_XXX_TMUX / FZF_XXX_TMUX_HEIGHT pairs for each one of them as it introduces too many configuration knobs.

**Comment by megalithic** [comment]
Thanks tons June, i'll give it a try here shortly.

**Comment by Tranquility** [comment]
The change broke CTRL-R for me. After using it a few times it stops working. When I hit ENTER the prompt is still empty and it no longer gets the text. 

After restarting the terminal it works a few times but the problem always comes back.

I am using zsh. Do you need any other information to find the bug?

**Comment by junegunn** [comment]
@Tranquility Can't reproduce. So you mean that tmux split correctly appears and you can select an item there, but the selected one does not update command line, right? And how many is "a few times"?  Did you try re-sourcing `~/.fzf.zsh` when that happens?

**Comment by Tranquility** [comment]
> So you mean that tmux split correctly appears and you can select an item there, but the selected one does not update command line, right?

Exactly!

> And how many is "a few times"?

I can't reproduce it reliably. Sometime it's two sometimes it's twenty. Sometimes it starts to work again after a few times. Sometimes it doesn't (or maybe I did not try enough times).

> Did you try re-sourcing ~/.fzf.zsh when that happens?

Yes, I doesn't help.


I changed the fzfcmd to back from fzf-tmux to fzf for now.

**Comment by junegunn** [comment]
@Tranquility I can't reproduce no matter how many times I try. I'm a bash user and there's nothing in my .zshrc. Maybe fzf conflicts with other parts of your zsh config.

**Comment by joaociocca** [comment]
I understand this one's failed..? I ended up here actually when looking for a solution to a different thing: I want to map pageup to, if on shell, roll history up (like prefix+pageup does). But this breaks pageup usage on fzf's history keybind for ctrl+r... any ideas on how to do both?

I currently have this on my `.tmux.conf`

```
bind -n Pageup if 'test "#{pane_current_command}" == "nano"' 'send Pageup' 'copy-mode -u'
bind -n S-Pageup copy-mode -u
bind -n S-Pagedown send-keys Pagedown
```

the if solved the pageup problem on `nano`, but no idea on how to solve it for fzf...
