### ISSUE TITLE
[FR] Add command to toggle selection of range

### ISSUE THREAD

**Issue by NightMachinary** [junegunn/fzf#2032]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

I want to be able to select a range of items easily. Sth akin to shift-selecting in Windows Explorer.

**Comment by junegunn** [comment]
You can just hold down tab or shift-tab until the cursor reaches the point. Or scroll your mouse with shift pressed. I don't want to add another option other than that.

**Comment by MikeLemo1** [comment]
I guess the intenstion is more to the mouse two click logic but with the keyboard vim style like with line selection mode ++shift+v++ with whatever motions are availabler for the user in the fzf menu
