### ISSUE TITLE
How do I bind ctrl+Y to copy the current selected path?

### ISSUE THREAD

**Issue by tifDev** [junegunn/fzf#2033]
- [ x] I have read through the manual page (`man fzf`)
- [ x] I have the latest version of fzf
- [ x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

After watching [your video](https://youtu.be/qgG5Jhi_Els) I saw an interesting custom keybinding ctrl+y to copy the current selected line. After searching i didn't came with the solution, only partial:
`
fzf --bind 'ctrl-y:copy-path-code-here'`

**How can i do this?**

**Comment by junegunn** [comment]
First of all, it's not my video, so I don't know exactly how he's done it. Probably with `execute-silent` action optionally followed by `abort` like so:

```sh
fzf --bind 'ctrl-y:execute-silent(pbcopy <<< {})+abort'
```

This is for macOS, you would need a different program than pbcopy on Linux, but you get the idea.

**Comment by tifDev** [comment]
Oh sorry, i mean the demo video in fzf main page. 
Do i need to put that in .bashrc or i just need to run that in terminal? 
I tried to run in terminal and it doesn't work...

**Comment by andres-lowrie** [comment]
Hey @tifDev not sure if this is the correct way but here's how I got it to work on mac.

The TLDR here is that you need to run `fzf` with those arguments to add your shortcuts at "runtime"

---

In order to persist the settings, what I did, was create a function that wraps the command junegunn posted

```zsh
myfzf() {
  fzf --bind 'ctrl-y:execute-silent(pbcopy <<< {})+abort'
}
```

and then I run `myfzf` instead of just fzf, which gives me the Ctrl-y binding to yank paths

**Comment by akharrou** [comment]
```
FZF_COPY_TO_CLIPBOARD_SPACE_SEPERATED_LIST="execute-silent(echo -n {+} | pbcopy)"
FZF_COPY_TO_CLIPBOARD_NEWLINE_SEPERATED_LIST="execute-silent(cat {+f} | perl -pe \"chomp if eof\" | pbcopy)"
```

**Comment by pnchinmay** [comment]
**Ubuntu 20.04**
I tried several options and these worked out for me in linux. This might help someone looking for these.

- Press CTRL-Y to copy path of selected option into clipboard
- Press CTRL-ALT-Y to copy contents of the selected option into clipboard'
```
--bind 'ctrl-y:execute(readlink -f {} | xclip -selection clipboard)'
--bind 'ctrl-alt-y:execute-silent(xclip -selection clipboard {})'
```
