### ISSUE TITLE
How do i change the default activator ** to ++ ?

### ISSUE THREAD

**Issue by tifDev** [junegunn/fzf#2034]
- [x ] I have read through the manual page (`man fzf`)
- [ x] I have the latest version of fzf
- [x ] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ x] bash
    - [ ] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

How do i change the default activator from `**` to `++` ?

**Comment by junegunn** [comment]
https://github.com/junegunn/fzf#settings
