### ISSUE TITLE
request: respect FZF_DEFAULT_COMMAND even when input not tty

### ISSUE THREAD

**Issue by smolin** [junegunn/fzf#2036]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

I have set FZF_DEFAULT_COMMAND to use fd, and it works as expected if I do

`    % fzf
`
but not if I do

`    % file $(fzf)
`
(or use ^t or **<tab> to bring up fzf). This is apparently by design because the manual says "command to use when input is tty" but it seems to me that it would be better if it worked regardless of the state of the tty.

If this is something you would entertain but not have time to do, I could possibly try to contribute code (though I'm not a Go programmer)

Thanks for the splendid fzf tool.

**Comment by junegunn** [comment]
> `% file $(fzf)`

It should use FZF_DEFAULT_COMMAND.


```sh
> echo $([ -t 0 ] && echo stdin is tty || echo stdin is not tty)
stdin is tty
> echo $([ -t 0 ] < /dev/null && echo stdin is tty || echo stdin is not tty)
stdin is not tty

> export FZF_DEFAULT_COMMAND='echo 100'
> fzf -f 1
100
> echo $(fzf -f 1)
100
```

You should note that CTRL-T binding or fuzzy completion doesn't use the variable. It's described in the README page.
