### ISSUE TITLE
fzf-tmux is broken in the latest commit 537d07c1e5133727dddbd6a345f5926719a3d7b4 with fish shell.

### ISSUE THREAD

**Issue by phongnh** [junegunn/fzf#204]
Hi junegunn,

I have just upgraded fzf to the latest commit, and it is broken with error:

```
fish: Could not expand string '"/Users/phongnh/.fzf/bin/fzf $(cat /tmp/fzf-args-3989) > /tmp/fzf-fifo2-3989; echo \$? > /tmp/fzf-fifo3-3989 "'
Standard input: cd /Users/phongnh/.zero; sh -c "/Users/phongnh/.fzf/bin/fzf $(cat /tmp/fzf-args-3989) > /tmp/fzf-fifo2-3989; echo \$? > /tmp/fzf-fifo3/3989 "
```

It worked fine before.

Thanks.

**Comment by junegunn** [comment]
Thanks for the report. I changed the script to use `bash` instead of `sh`. Can you update and test it?

**Comment by phongnh** [comment]
Hi junegunn,

The problem is still there. It seems that you need to escape $ at $(cat ...), change it to \$(cat ...)

![screen shot 2015-04-20 at 1 08 08 pm](https://cloud.githubusercontent.com/assets/438791/7224592/85705196-e75e-11e4-83d6-52a5a0895aa6.png)

**Comment by junegunn** [comment]
Ha, you're right. Fixed it. Thanks!

**Comment by phongnh** [comment]
Thank you.

**Comment by junegunn** [comment]
I'm sorry, but I'll have to revert the previous commit, as it makes `fzf-tmux` doesn't run on Vim. I'll look into it later in the day.

**Comment by phongnh** [comment]
Yes. I just realized that broken too. Now I sticked with 0.9.10 tag, this is the last commit fzf-tmux work in both vim and shell. 

Thanks.

**Comment by junegunn** [comment]
Could you test again? I've confirmed that the above commit fixes the problem when fish is the default shell (at least on OS X).

**Comment by phongnh** [comment]
It works like a charm. Thank you.
