### ISSUE TITLE
Ctrl +T does not trigger $FZF_DEFAULT_COMMAND.

### ISSUE THREAD

**Issue by LukaszBielsko** [junegunn/fzf#2044]
- OS
    - [ x] Mac OS X
- Shell
    - [x ] zsh
    
## Ctrl - T searches in node_modules. 
I've followed that instructions - [respecting .gitignore](https://github.com/junegunn/fzf#respecting-gitignore)

echo $FZF_DEFAULT_COMMAND prints `fd --type f`

`FZF_CTRL_T_COMMAND` is set to `$FZF_DEFAULT_COMMAND`
According to issues I found when Ctrl - T is pressed I should not be able to search files included in .gitignore file. But it does search through them. 

To my understanding Ctrl - T should trigger `$FZF_DEFAULT_COMMAND`, but it triggers "normal" fzf.  However when I type 'fzf' it does not search through ignored folders.

**Comment by junegunn** [comment]
Works for me.

```sh
export FZF_DEFAULT_COMMAND='echo foo'
export FZF_CTRL_T_COMMAND='echo bar'
# fzf shows foo
# CTRL-T shows bar
```
