### ISSUE TITLE
Incorrect shebang in documentation

### ISSUE THREAD

**Issue by Keating950** [junegunn/fzf#2049]
- [ ] I have read through the manual page (`man fzf`)
- [ ] I have the latest version of fzf
- [X] I have searched through the existing issues

The example script found in the wiki under "[fzf as dmenu replacement](https://github.com/junegunn/fzf/wiki/examples#fzf-as-dmenu-replacement)' uses the shebang `#!/usr/bin/env sh`. However, it also uses `disown`, which is undefined in POSIX sh. A `#!/usr/bin/env bash` would be more portable/compatible. (I noticed because I replaced the default `/bin/sh` symlink to bash with one pointing to the stricter `dash` shell.)

**Comment by junegunn** [comment]
Thanks for the heads up. The page is maintained by the community and I don't review or test the code people add to it. Write permission to the page is open to everyone, so feel free to edit the code if you think it's incorrect.
