### ISSUE TITLE
doesn't display properly on Linux console

### ISSUE THREAD

**Issue by notevenodd** [junegunn/fzf#2050]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [x] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

Fzf recently started to use a wider range of Unicode characters for its user interface (rounded corner preview, braille spinner indicator, others?). Those new characters may look great on a modern desktop, but may not display as intended on other systems (servers, embedded, etc...). 

As an example, the Linux console supports Unicode but only a maximum of 256 (or 512 with less colors) glyphs. Default glyphs (symbols from CP437) and virtually every console fonts have printable ASCII and simple-line drawing, but not rounded corners or braille.

Even in a desktop environment, traditional bitmap fonts or some modern minimal fonts may also not include those.

## Suggestions

1. existing `--border`(=`sharp`) could control border around the preview also (not just around the finder)
2. `--spinner=`... option, with possible values (`braille` [default], `ascii`, ...)

**Comment by junegunn** [comment]
`--no-unicode` is what you're looking for.

**Comment by notevenodd** [comment]
Hi, thanks @junegunn for the answer.
I still wouldn't mark the issue as _closed_ though!

Because dropping to ASCII is a **regression** being brought by version 0.21. Fzf 0.20 and earlier versions worked well on the Linux console _including_ all the line drawing! (as I explained, Linux console has some Unicode support)

**Comment by antofthy** [comment]
FYI...

I looked at a [unicode demo file](https://antofthy.gitlab.io/info/data/utf8-demo.txt) on my linux console
Only around half the standard unicode glyphs were defined. and None of though useful as a [heartbeat character](https://antofthy.gitlab.io/info/data/utf8-demo.txt).

In summery looks like your only real choice is to use `--no-unicode` as previously suggested.

**Comment by mb720** [comment]
I had the same issue. Running

    localectl set-locale en_US.UTF-8

fixed it in my case.

See other answers [here](https://stackoverflow.com/questions/12649896/why-doesnt-my-terminal-output-unicode-characters-properly/77100276).
