### ISSUE TITLE
Top and highlight current branch when use fzf to fuzzy list branches/tags?

### ISSUE THREAD

**Issue by tmpm697** [junegunn/fzf#2053]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

I'm using https://github.com/junegunn/fzf/wiki/Examples#git to fuzzy list all branches of a repository:
```

# fco - checkout git branch/tag
fco() {
  local tags branches target
  branches=$(
    git --no-pager branch --all \
      --format="%(if)%(HEAD)%(then)%(else)%(if:equals=HEAD)%(refname:strip=3)%(then)%(else)%1B[0;34;1mbranch%09%1B[m%(refname:short)%(end)%(end)" \
    | sed '/^$/d') || return
  tags=$(
    git --no-pager tag | awk '{print "\x1b[35;1mtag\x1b[m\t" $1}') || return
  target=$(
    (echo "$branches"; echo "$tags") |
    fzf --no-hscroll --no-multi -n 2 \
        --ansi) || return
  git checkout $(awk '{print $2}' <<<"$target" )
}
```

If I currently under branch/tag: `test1`, how to keep `test1` in top of candiate and add `*` in branch name to indicate that it's current branch/tag we're in:

Current behavior:
```
./fco
branch     master             <-- cursor here
branch     test1
branch     test3
```

expect:
```
./fco
branch*    test1              <-- cursor here
branch     master
branch     test3
```

Also how to color `*` in red for better visual?

**Comment by junegunn** [comment]
This is not an issue of fzf but a general question on shell scripting. Please consider asking these questions on more appropriate forums such as StackOverflow. Also, please note that the wiki page is maintained by the community and I don't test or review the code people add to it.
