### ISSUE TITLE
Invalid pointer character

### ISSUE THREAD

**Issue by griglab** [junegunn/fzf#2055]
- [ ] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [ ] I have searched through the existing issues

## Info

- OS
    - [X] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [X] bash
    - [ ] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

Hey.
When I change the "prompt", everything is fine.
But when I try to change the "pointer" and "marker", I get "invalid character".
![fzf](https://user-images.githubusercontent.com/64154656/82732029-54bf8b00-9d13-11ea-9b83-fc1c46a7e87e.png)

**Comment by junegunn** [comment]
https://github.com/junegunn/fzf/blob/f81feb1e69e5cb75797d50817752ddfe4933cd68/src/options.go#L1409-L1411

Looks like you're trying to use a character that does not satisfy [`IsGraphic`](https://golang.org/pkg/unicode/#IsGraphic) predicate provided by Go standard library, try using a different character.

**Comment by mbenford** [comment]
This constraint prevents special characters from patched fonts from being used with fzf. Is this open to change?

**Comment by siduck** [comment]
> This constraint prevents special characters from patched fonts from being used with fzf. Is this open to change?

hey, did you find any fix for this?

**Comment by mbenford** [comment]
@siduck I didn't. I was using fzf in neovim back then but I switched to Telescope shortly after. 

I guess you can fork fzf and remove that specific constraint. I don't know if it'll introduce bugs somewhere else, though.

**Comment by siduck** [comment]
> @siduck I didn't. I was using fzf in neovim back then but I switched to Telescope shortly after.
> 
> I guess you can fork fzf and remove that specific constraint. I don't know if it'll introduce bugs somewhere else, though.

oh no! btw i use fzf for tab/history completion in mksh, wish I could change the prompt BG color and the pointer character too ;(

![image](https://user-images.githubusercontent.com/59060246/158608446-f5bb681a-434f-4eda-9582-d610a9cfb1b2.png)
