### ISSUE TITLE
Store output from fzf in a variable in vim

### ISSUE THREAD

**Issue by itmecho** [junegunn/fzf#2056]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux (neovim)
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [ ] fish
    
## Problem / Steps to reproduce
I have the following keybind:
```
nnoremap <leader>cx :vs term://cargo test \| :norm i
```

This opens a new terminal buffer in a vertical split with the command `cargo test` and automatically enters Terminal mode (from terminal normal mode). 

What I'm trying to do with `fzf` is to select a coand from a list and then run it the same way as the keybinding.

This is what I have so far but I can't figure out how to automatically enter Terminal mode!

```
nnoremap <leader>cx :call s:icargo()<CR>

function! s:icargo()
    call fzf#run({'source': ['test', 'run'], 'sink': function('s:icargo_run')})
endfunction

function! s:icargo_run(cmd)
    execute ':vs term://cargo '.a:cmd.' | :norm i'
endfunction
```

The problem here is that fzf runs the function when it's still in the fzf buffer so it complains about the `:norm i` part of the command trying to enter insert mode when it's not modifiable. If I remove the `\| :norm i` part for the execute line, it does exactly what I want apart from entering Terminal Mode. 

The reason for entering Terminal mode is so that I can just press enter when the command to ishes to close the buffer. It works great for the keybinding with the hard coded command.

Is there a way to store the selection from the `fzf#run` command in a variable so I can run the command separately after the fzf buffer has closed? Or maybe another way to achieve what I'm after.

I have tried an autocmd to run startinsert on the `TermOpen` event but it didn't seem to work.

**Comment by junegunn** [comment]
Try replacing `norm i` with `call feedkeys('i', 'n')`, i.e.

```vim
execute 'vs term://cargo '.a:cmd
call feedkeys('i', 'n')
```

Related https://github.com/junegunn/fzf/issues/1566#issuecomment-495041470

**Comment by itmecho** [comment]
Thanks! That worked perfectly =]
