### ISSUE TITLE
Impossible to bind ctrl-bspace or ctrl-del

### ISSUE THREAD

**Issue by 3v1n0** [junegunn/fzf#2057]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [x] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

```sh
tricky ~                                                                                                     2 15:13:01
❯ fzf --bind=ctrl-del:kill-word                                      
unsupported key: ctrl-del

tricky ~                                                                                                     2 15:13:16
❯ fzf --bind=ctrl-bspace:backward-kill-word       
unsupported key: ctrl-bspace
```

**Comment by junegunn** [comment]
It's not possible to support those keys as they are not recognized by the standard terminals.
Related #1933
