### ISSUE TITLE
Multiline selection: reset query after TAB, undo, and current selection

### ISSUE THREAD

**Issue by aureooms** [junegunn/fzf#2062]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [x] fish
    
## Problem / Steps to reproduce

Sometimes, multiline selection is about lines that have nothing in common (for instance selecting email addresses). In that case it would be preferable for TAB to select the current item then reset the input automatically. This can be achieved with `fzf --bind 'tab:toggle+clear-query'`. However one issue to consider is that of undoing previous selections, since now the filter text is reset as soon as the `tab` key is pressed, we will have to repeat the previous query if we selected something by mistake (if we remember the previous query or if we know what was selected!). Maybe a way to view the current selection would partially solve that? Maybe I missed something in the manual that can achieve this easily...

**Comment by junegunn** [comment]
Since fzf implements many readline key bindings, you can do this, just like you do it in your shell:

```sh
fzf --multi --bind 'tab:toggle+end-of-line+unix-line-discard'
```
- Select the entry
- Move the cursor to the end (CTRL-E)
- Delete the line (CTRL-U)

Then you can paste the deleted text to the prompt by pressing CTRL-Y (yank)
