### ISSUE TITLE
fzf piped from ssh is skipping input chars while building result list

### ISSUE THREAD

**Issue by lowb1rd** [junegunn/fzf#2063]
- [X ] I have read through the manual page (`man fzf`)
- [X ] I have the latest version of fzf
- [X ] I have searched through the existing issues

## Info

- OS
    - [X ] Linux
    - [X ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ X] bash
    - [ ] zsh
    - [ ] fish
    
I have fzf on MacOS via homebrew. I'd like to search a remote filesystem and pipe the fd output to local fzf like so:

`ssh HOST 'fdfind . /var/www' | fzf`

When i start typing immediately while the result list is being build, some input chars I type are skipped, I have to type quite slowly to have it not miss some chars. Once the result list is complete, fast typing is possible.

Is my usecase wrong? The remote filesystem is also mounted via sshfs, but running fd on that mount is very slow. Thats why I'd like to search on the remote machine and just replace the path to point to my local mountpoint.

Running fzf remotely in an interactive shell works, but I am having trouble to get the ouput back to my local shell for further processing.

**Comment by junegunn** [comment]
To prevent ssh from consuming your keystrokes:

```sh
ssh HOST 'fdfind . /var/www' < /dev/null | fzf
```

And you might want to use command substitution instead so that fzf can terminate immediately without having to wait for ssh command to finish.

```sh
fzf < <(ssh HOST 'fdfind . /var/www' < /dev/null)
```
