### ISSUE TITLE
shell completions for fzf itself

### ISSUE THREAD

**Issue by b0o** [junegunn/fzf#2067]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] All OSes
- Shell
    - [x] bash
    - [x] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

I'm having a hard time understanding if the [`completion.{bash,zsh}`](https://github.com/junegunn/fzf/tree/master/shell) scripts are intended to provide completions *for* the `fzf` command *itself*, or are meant to enable the *use* of `fzf` as a means to interact with completions for *other* commands.

If the latter is true, I take it that there is currently no support for shell completions for `fzf` itself? If so, this is a request for that support to be added.

I am also having a hard time searching through issues to see if this has been brought up before, because there are a lot of questions about completions but which are asking about the latter case described above. If this has been asked before, I apologize.

**Comment by antofthy** [comment]
Actually I have a hard time understanding the instructions for even enabling fzf use for BASH completions... period!   Nor the VIM bindings.

It has a lot of stuff unsaid and undocumented, that seems to assume a deep knowledge of the systems involved when all I want to do is enable it and try it out.

Using the fedora v31 RPM for fzf  v0.21.1

**Comment by b0o** [comment]
@antofthy I agree, I think better documentation around this is needed.

I actually use a [separate zsh plugin](https://github.com/Aloxaf/fzf-tab) to achieve fzf tab-completion because I couldn't get the bundled one to work.

**Comment by junegunn** [comment]
I believe the README page already describes what this project provides:

Excerpt from https://github.com/junegunn/fzf#installation

> fzf project consists of the following components:
> - fzf executable
> - fzf-tmux script for launching fzf in a tmux pane
> - Shell extensions
>     - Key bindings (CTRL-T, CTRL-R, and ALT-C) (bash, zsh, fish)
>     - Fuzzy auto-completion (bash, zsh)
> - Vim/Neovim plugin

And there's https://github.com/junegunn/fzf#fuzzy-completion-for-bash-and-zsh section which elaborates on what *"fuzzy"* completion for bash and zsh is.

So to answer your question:

> no support for shell completions for fzf itself?

Correct. While `completion.bash` partially implements normal bash shell completion for fzf itself but the code hasn't been updated for a while and is not in sync with the latest version. I'm not interested in updating it or implementing it for zsh, but pull requests are welcome.

**Comment by b0o** [comment]
Thank you for the clarification @junegunn

**Comment by antofthy** [comment]
I was finally able to get fzf working partially for bash.
Further I was able to modify one of my own bash completion functions to make use of it.

Thank you @junegunn for the clarification, and look forward to its continued improvement and development.
