### ISSUE TITLE
Ignoring non-alphanumeric characters in fuzzy search

### ISSUE THREAD

**Issue by jbriales** [junegunn/fzf#2071]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [X] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish
    
## Problem / Steps to reproduce
I have the following situation:
My query in `fzf` is sth like `"foo bar"` (with quotes in it),
but I'd like it to do fuzzy search ignoring the quotes.
Currently it seems like due to quotes all entries are ignored?
Is this the expected behavior?
Is there any way to ignore non-alphanumeric characters?

**Comment by junegunn** [comment]
Since fzf is a fuzzy finder, you don't have to put a space between `foo` and `bar`, so just type in `foobar`. If you really want to ensure that there is a space somewhere between `o` and `b`, you can escape space with a backslash. i.e. `foo\ bar`.

**Comment by jbriales** [comment]
Ok that wasn't actually the question... But I take the answer is characters like `"` are not ignored by the fuzzy search and there is no way to ignore them?
What I provided was a foo example but not the key issue I was having. Just a way to showcase the behavior with `"`.
Put otherwise, if I have an entry with `foo`, querying for `"foo"` will return nothing. Is that the expected behavior?

**Comment by junegunn** [comment]
> Is that the expected behavior?

Yes. I don't understand why one would intentionally type in `"`s in the query prompt and expect fzf to ignore them.
