### ISSUE TITLE
Installing fuzzy auto-completion on Mac

### ISSUE THREAD

**Issue by iamshreeram** [junegunn/fzf#2076]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info
While trying to install auto-completion by following the [doc](https://github.com/junegunn/fzf#using-homebrew-or-linuxbrew), mac is throwing error. 

- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish
    
## Problem / Steps to reproduce
While trying to install auto-completion by following the [doc](https://github.com/junegunn/fzf#using-homebrew-or-linuxbrew), bash in mac is throwing below error. 

```
user:~ [4] ❯ (brew --prefix)/opt/fzf/install
-bash: syntax error near unexpected token `/opt/fzf/install'
```

Fix :
Below fixes the issue. Readme doc needs update. 
```
`(brew --prefix)`/opt/fzf/install
```

**Comment by junegunn** [comment]
You missed `$` at the front. `$(brew --prefix)/opt/fzf/install`
