### ISSUE TITLE
Sort: prioritise lines that match multiple times

### ISSUE THREAD

**Issue by OJFord** [junegunn/fzf#2078]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [x] fish
    
## Problem / Steps to reproduce

Particularly when using fzf on file paths in repos, I find myself looking for, for example `ser.rs`, at a location that includes the string `ser` earlier in the path, sharing it with multiple other files - such as `serde/**/{ser,deser,lib}.rs`

In such cases, it appears that the shortest paths are sorted first (`ser`, `lib`), and then alphabetical (`lib`).

My preferred outcome (`ser`) could be reached - I think reasonably and generally - as 'multiply-matching first'.

So, for this example, `serde/**/{de,}ser.rs` rank first on query `ser`, because they each match exactly twice, while `lib.rs` matches exactly only once, then `ser.rs` ranks first of the two, because it's shorter.

**Comment by junegunn** [comment]
The suggested approach is very different from the way the current algorithm works, so it's not easy to add such an option to fzf.

I would suggest that you add `.` to your query (i.e. `ser.`), it will definitely help in this particular case.
