### ISSUE TITLE
can't choose multiple files in fzf to open them in vim

### ISSUE THREAD

**Issue by vifm9** [junegunn/fzf#2079]
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish
    
## steps to reproduce 
fzf -m --print0 | tr '\000' ' ' | vim -p -
fzf -m --bind "enter:accept+execute(vim -p {})"

and a tried many more obscure workarounds but it just dont work

**Comment by junegunn** [comment]
```sh
fzf -m --print0 | xargs -0 -o vim
```

**Comment by vifm9** [comment]
> ```shell
> fzf -m --print0 | xargs -0 -o vim
> ``` this command return xargs error however i was able to run fzf -m --print0 | xargs -0 vim -p
but it makes my terminal unresponsive as soon as i close the files

**Comment by junegunn** [comment]
```sh
       -o, --open-tty
              Reopen stdin as /dev/tty in the child process before executing the command.  This is useful if you want xargs to run an interactive application.
```
