### ISSUE TITLE
Smart case seems to be for the whole query instead of separately for each words

### ISSUE THREAD

**Issue by edi9999** [junegunn/fzf#208]
If my list is:

```
Foo Bar
```

then the query `'foo 'Bar` will not match, but I would expect it to match (because I see the first word `foo` as being case insensitive). 

I think that it would probably require lots of work to do it, so I don't think the issue will be adressed, but maybe It's not that difficult.

**Comment by junegunn** [comment]
Well, that makes perfect sense. It's actually one of things that I forgot to address when I rewrote fzf in Go :)

**Comment by junegunn** [comment]
Fixed in master. I'll release fzf 0.9.11 after a couple more fixes/improvements.

**Comment by edi9999** [comment]
Awesome. Thanks
