### ISSUE TITLE
Allow for customization of CTRL-R history listing

### ISSUE THREAD

**Issue by pabloariasal** [junegunn/fzf#2080]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish
    
## Problem / Steps to reproduce
Currently the `CTRL-R` command used to print the history is hardcoded to `fc -rl 1`, which shows the default history listing containing the event number followed by a command.
The fact that the command is hardcoded and can't be modified hinders the ability to customize how history is displayed. For example, using `history -E` or `fc -rld` the history listing can be extended to show the time when the command was run and the corresponding exit code.

My suggestion is to introduce a `FZF_CTRL_R_COMMAND` variable (just like CTRL-T and ALT-C), that can be set by the users who want to customize history listing. I can create a PR if considered a valuable feature.

**Comment by junegunn** [comment]
Thanks for the suggestion, but I decided not to add more options to shell extensions. See my previous comment on the matter: https://github.com/junegunn/fzf/pull/1492#issuecomment-461670530

You might also want to see https://github.com/junegunn/fzf/search?q=FZF_CTRL_R_COMMAND&type=Issues
