### ISSUE TITLE
FZF Bash reverse I-search is autopopulated with unknown sequence of characters

### ISSUE THREAD

**Issue by kl2792** [junegunn/fzf#2081]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

I installed fzf using git, enabling bash key bindings. Initially, the keybindings worked wonderfully. Now, every time I type ctrl-R, 2-4 repetitions of `1R` or `;1R` are entered automatically.

![image](https://user-images.githubusercontent.com/7944969/84440457-07df1e00-ac08-11ea-984b-1bf9944c2071.png)

I have confirmed that the issue is not with the binary by running `seq 10000 | fzf`.

Do you know what might be causing this issue?

Thanks for creating fzf, and for your help in advance!

**Comment by junegunn** [comment]
I'm not sure what's going on. Does disabling mouse help? i.e. `export FZF_DEFAULT_OPTS='--no-mouse'`

**Comment by kl2792** [comment]
Only one `;1R` was printed out when I exported this option.

**Comment by junegunn** [comment]
What happens when you run `echo -e "\x1b[6n"`? What is printed on the screen? And have you tried using a different terminal emulator?

**Comment by kl2792** [comment]
In a Jupyter Lab terminal using Bash:

```
$ echo -e "\x1b[6n"

$ ;1R;1R;1R
```

I suppose that's the same output! The second and third `;1R` show up after a short delay.

Do you have any suggestions for other emulators I could try?

**Comment by junegunn** [comment]
> The second and third ;1R show up after a short delay.

They shouldn't. See "Device Status Report" in https://en.wikipedia.org/wiki/ANSI_escape_code.

What about this one? What do you see on the screen? Note that you should terminate cat with CTRL-C.

```sh
echo -e "\x1b[6n"; cat
```

**Comment by junegunn** [comment]
The sequence reports the cursor position on the screen. This is how it looks on my terminal.

```
> echo -e "\x1b[6n"; cat

^[[2;1R^C
> echo -e "\x1b[6n"; cat

^[[5;1R^C
> echo -e "\x1b[6n"; cat

^[[8;1R^C
> echo -e "\x1b[6n"; cat

^[[11;1R^C
```

**Comment by kl2792** [comment]
ctrl-C doesn't terminate `cat` for me, but hitting ctrl-D twice does. If I type something in cat, the first ctrl-D prints out what I just typed in, and the second ctrl-D terminates.

For `cat` alone, ctrl-D once terminates. 

```
$ echo -e "\x1b[6n"; cat

^[[2;1R^[[2;1R^[[2;1R^C^C^C^C$ 
$ echo -e "\x1b[6n"; cat

^[[25;1R^[[25;1R^[[25;1R$ 
$ echo -e "\x1b[6n"; cat

^[[21;1R^[[21;1R^[[21;1Rsometextsometext$ 
```

**Comment by kl2792** [comment]
ctrl-C doesn't terminate `cat` for me; two ctrl-Ds do, though. If I type some text, the first ctrl-D duplicates the text, and the second ctrl-D terminates.

With `cat` alone, one ctrl-D terminates.

```
$ echo -e "\x1b[6n"; cat

^[[2;1R^[[2;1R^[[2;1R^C^C^C$ 
$ echo -e "\x1b[6n"; cat

^[[5;1R^[[5;1R^[[5;1R$ 
$ echo -e "\x1b[6n"; cat

^[[8;1R^[[8;1R^[[8;1Rtexttext$ 
$ cat
$ 
```

**Comment by junegunn** [comment]
So for some reason, your terminal emulator is reporting the cursor position three times instead of one and they are fed into fzf prompt. Ideally, this should be fixed from your terminal emulator's side, but I can make fzf ignore those extra sequences.

**Comment by kl2792** [comment]
Thank you! The support is much appreciated.
