### ISSUE TITLE
Spinner Unicode does not work in xterm.

### ISSUE THREAD

**Issue by antofthy** [junegunn/fzf#2082]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

In reference to the use of Unicode for the 'input spinner'...
Related to https://github.com/junegunn/fzf/issues/2050

The unicode braille does not work for xterm's either. All that appears is a dotted box!
Which is weird as the xterm's can output braille characters.
Using  'fzf --no-mouse' I was able to copy the dotted box, and pasting into the same xterm later, and the xterm displayed the braille character that was grabbed without any problem! 
The various box characters however have no problem being displayed.

However I think what is happening is that the braille characters are being in **bold** which I discovered in another [project](https://antofthy.gitlab.io/software/#percent_utf) did not support many unicode glyphs!

The fonts being used by the xterm were...
Normal font...   "-misc-fixed-medium-r-*-*-15-*-75-75-c-90-iso10646-1"
Bold Font... "-misc-fixed-bold-r-*-*-15-*-75-75-c-90-iso10646-1"
The normal font has the unicode glyphs,  the bold font does not!

I suggest that if you are going to output a unicode spinner, you do NOT use a bold font.

ASIDE: Interesting use of the braille unicode, shame I wasn't able to tell it was even there until I saw the previously referenced issue.

**Comment by LuRsT** [comment]
Just to be clear @antofthy, is the issue xterm not allowing unicode symbols on bold, or that the font doesn't have the symbols in bold?

**Comment by antofthy** [comment]
More like the X window bold fonts do not have unicode characters defined (just blank)
As such turning in bold in xterms means any unicode does not appear.
They work just fine if you do NOT use bold when printing unicode characters.
Color is not an issue, only when using bold.

**Comment by junegunn** [comment]
Since 0.24.0, `--color` option allows you to "un-bold" the part:

```sh
sleep 10 | fzf --color spinner:regular
```

Also, note that you can suppress all Unicode characters by passing `--no-unicode`.

**Comment by antofthy** [comment]
Thanks junegunn.
