### ISSUE TITLE
Host name completion for ping command (feature request)

### ISSUE THREAD

**Issue by drws** [junegunn/fzf#2085]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [x] zsh
    - [x] fish
    
## Problem / Steps to reproduce

fzf provides fuzzy completion for ssh and telnet commands by including hosts from /etc/hosts and ~/.ssh/config. This is a small feature request to provide the same capability to the ping command (and possibly traceroute as well). It would be particularly useful that one is able to quickly ping SSH hosts defined in ~/.ssh/config.

**Comment by junegunn** [comment]
See https://github.com/junegunn/fzf#supported-commands

```sh
# Add this to your shell configuration file
_fzf_setup_completion host ping traceroute
```
