### ISSUE TITLE
Accented character normalization doesn't work for some Vietnamese characters

### ISSUE THREAD

**Issue by tkt028** [junegunn/fzf#2088]
- [X] I have read through the manual page (`man fzf`)
- [X] I have the latest version of fzf
- [X] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [X] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [X] zsh
    - [ ] fish
- My fzf version: 0.21.1 (brew)
    
## Problem / Steps to reproduce
I am aware of the issue #790 that fzf (by default) enables the normalization to support the search of accented characters. This feature works for some Vietnamese characters, and fails for others.

Example 1 (OK): I am able to respectively search the data with search terms: "a e i o u y"
`
$ echo "Á É Í Ó Ú Ý" | fzf
`

Example 2 (NOK): search fails with search terms: "a e o u". For details, 

- "Ắ Ấ" should correspond to "A", 
- "Ố Ớ" should correspond to "O", 
- "Ứ" should correspond to "U"

`
$ echo "Ắ Ấ Ế Ố Ớ Ứ" | fzf
`

I put here my experiment results 

```
Á É Í Ó Ú Ý     --> OK
á é í ó ú ý     --> OK
À È Ì Ò Ù Ỳ     --> OK
à è ì ò ù ỳ     --> OK
Ả Ẻ Ỉ Ỏ Ủ Ỷ     --> OK
ả ẻ ỉ ỏ ủ ỷ     --> OK
Ã Ẽ Ĩ Õ Ũ Ỹ     --> OK
ã ẽ ĩ õ ũ ỹ     --> OK
Ạ Ẹ Ị Ọ Ụ Ỵ     --> OK
ạ ẹ ị ọ ụ ỵ     --> OK

Ắ Ấ Ế Ố Ớ Ứ              --> NOT OK, should correspond to "A A E O O U"
ắ ấ ế ố ớ ứ              --> NOT OK, should correspond to "a a e o o u"
Ằ Ầ Ề Ồ Ờ Ừ              --> NOT OK, should correspond to "A A E O O U"
ằ ầ ề ồ ờ ừ              --> NOT OK, should correspond to "a a e o o u"
Ẳ Ẩ Ể Ổ Ở Ử              --> NOT OK, should correspond to "A A E O O U"
ẳ ẩ ể ổ ở ử              --> NOT OK, should correspond to "a a e o o u"
Ẵ Ẫ Ễ Ỗ Ỡ Ữ              --> NOT OK, should correspond to "A A E O O U"
ẵ ẫ ễ ỗ ỡ ữ              --> NOT OK, should correspond to "a a e o o u"
Ặ Ậ Ệ Ộ Ợ Ự              --> NOT OK, should correspond to "A A E O O U"
ặ ậ ệ ộ ợ ự              --> NOT OK, should correspond to "a a e o o u"
```

Goal: fzf normalization should support the search of above NOK examples.

## References
- For the full list of Vietnamse tone marks: https://vietnamesetypography.com/tone-marks/

**Comment by junegunn** [comment]
Can you open a pull request?

Take a look at https://github.com/junegunn/fzf/blob/master/src/algo/normalize.go

**Comment by tkt028** [comment]
Thank @junegunn. I just made a pull request and wait for your approval.
