### ISSUE TITLE
Commands not working in vim

### ISSUE THREAD

**Issue by marauderlabs** [junegunn/fzf#2091]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish
    
## Problem / Steps to reproduce
Install fzf vim plugin through Plug.
Confirm plugin installation.
'Plug' in vim says fzf is installed fine.
```
:PlugStatus
Finished. 0 error(s).
[========]
- fzf: OK
```

`:FZF` works
but any other command like
`:Files` and other commands mentioned in the [README](https://github.com/junegunn/fzf.vim) don't work.

**Comment by marauderlabs** [comment]
Searching in issues didn't help but Google search helped find the comment on another issue.
[This](https://github.com/junegunn/fzf.vim/issues/456#issuecomment-625189523) helped.
This should probably be clearly explained in the readme.

**Comment by junegunn** [comment]
It is: https://github.com/junegunn/fzf.vim#installation
