### ISSUE TITLE
fzf#run() term height issue when --preview and 'source' is a list

### ISSUE THREAD

**Issue by antoinemadec** [junegunn/fzf#2093]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish
    
### Problem
When calling ```fzf#run()``` and using term, ```s:split()``` fits exactly the number of lines of ```source``` when source is a list.
This does not work well when using preview, as the preview is not taken into account in the height size.

![fzf_height_issue](https://user-images.githubusercontent.com/10830594/85453772-1656ff00-b551-11ea-9374-10cb4e6f6169.png)

### To Reproduce
```vim
    let opt = {'options': '''--preview-window'' ''up:50%'' ''--preview'' ''''\''''/home/antoine/dotfiles/.vim/plugins/fzf.vim/bin/preview.sh''\'''' {}''', 'source': ['fibo.py:14:9 Warning [pylint W0612] Unused variable ''i'' (unused-variable)'], 'down': '~40%'}
    call fzf#run(opt)
```

### Dirty Workaround

Commenting out those lines in ```s:calc_size()```:
```vim
  " if type(get(a:dict, 'source', 0)) == type([])
  "   let srcsz = len(a:dict.source)
  " endif
```

![fzf_height_issue_fix](https://user-images.githubusercontent.com/10830594/85454046-5d44f480-b551-11ea-822b-e398df77efef.png)

### Clean Fix

Here are options I can think of:

1. do not make an exception for list sources and remove ```let srcsz = len(a:dict.source)``` completely
2. do not make an exception for list sources by default, add a dict option if you want to fit the source list size exactly
3. make exception for list sources by default, add a dict option if you don't want to fit the source list size exactly
4. do not make an exception for list sources only when --preview is detected

**What do you think?**
Personally, I like 1. and 2.

Thanks for this amazing plugin anyway!
Antoine

**Comment by junegunn** [comment]
I would also like to remove `srcsz` calculation as it's inherently inaccurate and the code is pretty sloppy. Let's just disable it when there's `preview` in the option string.

**Comment by antoinemadec** [comment]
@junegunn , thanks a lot.
This fixed it for me :smiley:
