### ISSUE TITLE
Mode to show/hide selected items

### ISSUE THREAD

**Issue by icalvin102** [junegunn/fzf#2095]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [x] Mac OS X
    - [x] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [x] zsh
    - [x] fish
    
## Feature request

It would be nice to have an action, mode or toggle that shows/hides only the selected items when `-m`-flag is set. Same for the unselected items.  

I could not find this feature on the manpage or on the web. Am i missing something?
Thanks for this amazing tool.

**Comment by junegunn** [comment]
No, we don't have such an option. fzf was optimized to handle very large input lists (e.g. 10s of millions of items) and unfortunately, that optimization makes it non-trivial to implement an option that affects the output list without hurting performance and increasing memory footprint. So we're going to pass on this one. But you can achieve a similar effect using `reload` action like so

```sh
fzf --multi --bind 'ctrl-r:reload:cat {+f}'
```
