### ISSUE TITLE
Bundling fzf as a library in a Go project

### ISSUE THREAD

**Issue by mislav** [junegunn/fzf#2097]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [x] Mac OS X
    - [x] Windows
    - [x] Etc.
- Shell
    - [x] bash
    - [x] zsh
    - [x] fish
    
## Problem / Steps to reproduce

Hi, I'd love to use fzf in our Go project, but we would prefer to bundle it as a runtime module rather than shelling out to `fzf` which is not guaranteed to be present on a person's system. Here's [a sketch of how we would use it](https://github.com/cli/cli/pull/1277) (note that we currently shell out).

It looks like right now, fzf is not designed to run as a library, since most of the implementation is in a giant function `Run()` that invokes `os.Exit` upon completion, effectively shutting down the parent process. Furthermore, there doesn't seem to be a way to instantiate the options struct with arbitrary args instead of `os.Args`.

Would this project accept contributions that make it possible for fzf to be used as a library in addition to being its own executable? Thank you!

**Comment by christopherfujino** [comment]
This would be awesome! I just came here looking for the ability to do just this, and would also be interested in helping.

**Comment by junegunn** [comment]
See:
- https://github.com/junegunn/fzf/pull/1053#issuecomment-330024275
- https://github.com/junegunn/fzf/issues/1270
- https://github.com/junegunn/fzf/issues/1220

I've made myself clear in the past that I'm not particularly interested or motivated in designing and maintaining the API because fzf was strictly designed to be an individual program like many other programs in the Unix toolchain and I personally don't see myself needing it as a library. However, as long as we keep the API undocumented, which frees me from the future maintenance burden, I'm open to the suggestion.

I understand that you want to avoid shelling out, but I think shelling out is not such a bad idea. It gives your users more flexibility to
- upgrade or modify fzf separately (e.g. using their own forks)
- choose between alternative implementations of the same idea (peco, percol, fzy, selecta to name a few)
- start fzf in a tmux popup window using fzf-tmux instead which is really great (https://github.com/junegunn/fzf/pull/1946)

And installing fzf as a dependency is trivial because more users these days use package managers such as Homebrew.

**Comment by christopherfujino** [comment]
> I'm not particularly interested or motivated in designing and maintaining the API because fzf was strictly designed to be an individual program like many other programs in the Unix toolchain and I personally don't see myself needing it as a library. However, as long as we keep the API undocumented, which frees me from the future maintenance burden, I'm open to the suggestion.

An undocumented API sounds like a fair compromise :)

**Comment by mislav** [comment]
@junegunn Thanks for chiming in! I see your point regarding maintenance. As a maintainer myself, I would definitely _not_ look forward to maintaining two separate APIs for this tool, especially if I don't ever use the 2nd one myself.

I also would not recommend breaking up the entire `Run()` function into discrete functions, since that would be risky and I don't even think I could pull it off, since I don't understand what most of it does 😅

The only thing I would try to accomplish in a fork would be to allow the code to accept inputs other than `os.Args` and `os.Stdin`, and to allow results other than to `os.Stdout` followed by an `os.Exit()`. This might be made possible without significant changes. If we come up with a set of changes that don't look overly risky, we might propose a PR to this project and see how you feel about it. In the meantime, feel free to close this issue per others that were closed before this.

**Comment by christopherfujino** [comment]
> The only thing I would try to accomplish in a fork would be to allow the code to accept inputs other than `os.Args` and `os.Stdin`, and to allow results other than to `os.Stdout` followed by an `os.Exit()`.

What about parsing arguments before invoking `Run()` and passing them in as an argument, in addition to stdin/stdout overrides?

**Comment by christopherfujino** [comment]
And instead of calling `os.Exit(code)` in `Run()`, have it instead return the code, and then have `main()` exit with the return value of `Run()`

**Comment by jesseleite** [comment]
😍 Yes please! Even if undocumented/unsupported, it would allow 3rd party utilities to hook into fzf (albeit without warranty, and that's okay).

**Comment by mislav** [comment]
Update: on and off I have now spent _days_ trying to make fzf operate in library mode, but I am hereby declaring defeat.

Here is the list of prerequisites that, in my view, would be needed for this codebase to operate in library mode:

* **There can be no `os.Exit()` on errors, cancellations, or successful matches.** Ideally, `Run()` should return an error type that communicates the exit status of fzf. The same goes for `Terminal.Loop()`, which makes liberal use of `os.Exit()` to avoid having to manually break out of loops, suspend goroutines, or unlock mutexes. To refactor all these constructs to communicate the exit status via channels/return values, more refactoring than I am comfortable with would be needed, and I have doubts that such a large and risky changeset would get accepted by the main maintainer.

  * There are 37 additional invocations of `os.Exit()` from `options.go`, but all those pertain to processing command-line flags, and since flags wouldn't be passed to fzf in library mode, all those can stay intact.

* There should be a way for the caller to **initialize an Options hash with default values**, tweak the values as necessary, and have `postProcessOptions()` run on it before passing the options to `Run()`. This is relatively easy to expose through minor tweaks to `options.go`.

* There should be a way to **control where the user-selected output goes** instead of hardcoding it to `os.Stdout`. This seems immediately available by setting `Options.Printer`.

* There should be a way to supply the input stream instead of hardcoding it to `os.Stdin`. Right now, `Reader.ReadSource()` only has capabilities to read from a subprocess (if stdin is a tty) or from `os.Stdin`. For fzf to be usable as a library, `Reader` would need to get extended so it's fully configurable as to where it reads from. This would require only moderate refactoring of Reader, but its call points would need to change as well.

These changes wouldn't just make fzf useful as a library— I believe it would also lead to a better codebase overall, since now many more functions would be unit-testable, as opposed to currently where they are only testable via integration tests. However, since it would need an enormous effort to get it there and potentially introduce bugs in the process, I am cancelling my feature request.

@junegunn Thanks for the fantastic tool! I've learned a lot by combing through its codebase. 🤘

**Comment by jesseleite** [comment]
Appreciate your effort digging into this! Heartbroken though, as [telescope.nvim](https://github.com/nvim-telescope/telescope.nvim) (and similar wrappers) could really benefit from a proper fzf API / library. I know this is open source, but it would be so much nicer if fzf provided an API / library layer, rather than someone having to fork, or use another tool altogether 💔

**Comment by reinhrst** [comment]
For those interested; I spent some time on extracting the fuzzy-search part from fzf and making it into a go library: https://blog.claude.nl/tech/making-fzf-into-a-golang-library-fzf-lib/ . It's very much in beta still, but it tentatively works in some small projects I've started with it :).

**Comment by Delapouite** [comment]
Improvements has been made last May to Fzf as a library : https://gist.github.com/junegunn/193990b65be48a38aac6ac49d5669170
