### ISSUE TITLE
Control + R history commands does not scroll with the mouse as all other fzf things do including Control + T

### ISSUE THREAD

**Issue by abhijitpjoshi** [junegunn/fzf#2101]
- [ ] I have read through the manual page (`man fzf`)
- [X] I have the latest version of fzf
- [X] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [X] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [X] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

While I do Control + R, I get a history search widget as expected. but the history commands does not scroll with the mouse as all other fzf things do including Control + T. Am I missing anything?

below does not scroll through with the mouse. I have to use up or down keys to scroll through

![image](https://user-images.githubusercontent.com/41492347/86071957-846a5d00-ba4e-11ea-864e-f8161dc49654.png)

below control + T scrolls through with the mouse wheel

![image](https://user-images.githubusercontent.com/41492347/86072037-af54b100-ba4e-11ea-9e80-2e1add7d7b79.png)

**Comment by junegunn** [comment]
Works for me. Can you reproduce the problem with a minimal config?

```sh
mkdir -p /tmp/fzf-test
cp ~/.fzf.zsh /tmp/fzf-test/.zshrc
ZDOTDIR=/tmp/fzf-test zsh
```

**Comment by abhijitpjoshi** [comment]
It's still an issue for me. I don't remember if something has changed with my iterm2. but then I wonder how does it work correctly with Control + T

With minimal configuration you provided, it's still the same issue for me.
![image](https://user-images.githubusercontent.com/41492347/86388238-6aa16380-bc62-11ea-864b-43c1f59a3c82.png)

Here is a working snippet with Control + T with minimal configuration.

![image](https://user-images.githubusercontent.com/41492347/86388331-a0dee300-bc62-11ea-8c9f-e7c25ee1bb9d.png)

**Comment by junegunn** [comment]
You seem to have configured the bindings with environment variables. Please post the output of

```sh
env | grep FZF
```

**Comment by abhijitpjoshi** [comment]
Please see below -

![image](https://user-images.githubusercontent.com/41492347/86474071-1359cc80-bd10-11ea-9a01-50d110f290f4.png)

**Comment by junegunn** [comment]
Are you using a non-official implementation of the key bindings? Because the screenshots show that you have non-default options enabled such as `--inline-info` and `--prompt`.

**Comment by junegunn** [comment]
```
$ seq 10 | FZF_DEFAULT_OPTS= fzf --height 50% --reverse
>
  10/10
> 1
  2
  3
  4
  5
  6
  7
  8
  9
  10
```
vs.

```
$ seq 10 | FZF_DEFAULT_OPTS= fzf --height 50% --reverse --inline-info --prompt '~ '
~   < 10/10
> 1
  2
  3
  4
  5
  6
  7
  8
  9
  10
```

**Comment by abhijitpjoshi** [comment]
I have a non-default options. But even if i comment that out and use default options, scrolling is still an issue with control + R.
Below are my key bindings. This is the snippet from my ~/.fzf.zsh which sources keybindings from "/usr/local/opt/fzf/shell/key-bindings.zsh". 

` 
# CTRL-R - Paste the selected command from history into the command line
fzf-history-widget() {
  local selected num
  #setopt localoptions noglobsubst noposixbuiltins pipefail no_aliases 2> /dev/null
  setopt localoptions pipefail no_aliases 2> /dev/null
 selected=( $(fc -rl 1 | perl -ne 'print if !$seen{($_ =~ s/^\s*[0-9]+\s+//r)}++' |
    FZF_DEFAULT_OPTS="--height ${FZF_TMUX_HEIGHT:-40%} $FZF_DEFAULT_OPTS -n2..,.. --tiebreak=index --bind=ctrl-r:toggle-sort $FZF_CTRL_R_OPTS --query=${(qqq)LBUFFER} +m" $(__fzfcmd)) )
  local ret=$?
  if [ -n "$selected" ]; then
    num=$selected[1]
    if [ -n "$num" ]; then
      zle vi-fetch-history -n $num
    fi
  fi
  zle reset-prompt
  return $ret
}
zle     -N   fzf-history-widget
bindkey '^R' fzf-history-widget

} always {
  eval $__fzf_key_bindings_options
  'unset' '__fzf_key_bindings_options'
}
`

**Comment by jnooree** [comment]
This also happens to me. I've tried several things such as ```--multi``` option for ctrl-r,  not using oh-my-zsh's fzf plugin but sourcing directly the functions in ```/usr/local/opt/fzf/shell```, etc., but still no mouse scroll support on the ctrl-r history viewer.

**Comment by lincheney** [comment]
I can reproduce the issue, but only if the history is large, if the input is small the problem does not appear.
```
mkdir -p /tmp/fzf-test
cp -f ~/.fzf.zsh /tmp/fzf-test/.zshrc
seq 100000 > /tmp/fzf-test/zsh_history
ZDOTDIR=/tmp/fzf-test HISTSIZE=100000 HISTFILE=/tmp/fzf-test/zsh_history zsh
```
