### ISSUE TITLE
CTRL-R and CTLR-S does not work to move around in the history of command as native shell behavior

### ISSUE THREAD

**Issue by avatar-lavventura** [junegunn/fzf#2103]
## Info

- OS
    - [X] Linux
    - [] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [X] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

When I press ctrl-r to see the history on command: ctrl-r was going previos on history when I keep press it (`bck-i-search:`) but it remains as it is instead I have to do ctrl-p. And ctrl-s also does not apply forward seatch at all too.

Here ctrl-r and ctrl-s does not work as its original behavior on native shell

<img width="649" alt="image" src="https://user-images.githubusercontent.com/18537398/86464479-41530700-bd38-11ea-927e-c1bfebeddd86.png">

-----

=> How to so cursor up with `Ctrl-r` and cursor down with `ctrl-s`?

**Comment by junegunn** [comment]
Put appropriate `--bind` options in your FZF_CTRL_R_OPTS. See `man fzf`.

**Comment by avatar-lavventura** [comment]
```
export FZF_DEFAULT_OPTS='--bind=ctrl-r:previous-history,ctrl-k:kill-line'
```

It does not overwrite into key `ctrl-r. On the template ctrl-k works but ctrl-r does not

**Comment by avatar-lavventura** [comment]
```
export FZF_DEFAULT_OPTS=' --bind=ctrl-r:up --bind=ctrl-s:down,ctrl-k:kill-line"
```

`Ctrl-k, Ctrl-s` works fine but `ctrl-r` does not apply to move up

**Comment by avatar-lavventura** [comment]
Thanks: `export FZF_CTRL_R_OPTS="--bind=ctrl-r:up"` solved it. I was using `FZF_CTRL_R_OPTS` instead thats why it didn't work.

**Comment by avatar-lavventura** [comment]
@junegunn 

`accept         enter   double-click`

```
> cat
  784/4158
>  6684  cat gecko.py
   6630  cat .welcome.txt
```

Also here when I press ctrl-m I want it to apply `cat gecko.py` but intead I have to press 2 times `ctrl-m` for that. Can I accomplish it with single key press?

export FZF_DEFAULT_OPTS=="--bind=ctrl-m:accept"
