### ISSUE TITLE
[feature request] make fzf stateful

### ISSUE THREAD

**Issue by herrsimon** [junegunn/fzf#2105]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

Hello,

in order to make fzf more suitable as a drop in replacement for dedicated ui frameworks (like ncurses), it would be nice to have the possibility to save and restore the line the cursor is on, as well as the lines which are selected when `--multi` is active. Together with the current query, this information can then be used to make fzf stateful and completely restore a session, given that the order of input lines is not modified between calls).

Use cases where this comes in handy is any command which modifies single lines of the input but leaves the order of lines intact, such as a database of notes, where each input line consists of the note title and the first few words of content. When the user notices a typo in some note title or wants to add a tag etc. but has already selected some lines, the title could be changed on the fly through a fzf-binding which calls a respective script and then reloads the input (restoring state afterwards). 

The functionality could be implemented by:
- adding a `reload_stateful()` action, which restores the active and selected lines after reloading input
- adding a `--print-state` option, which prints the numbers of the active line and the selected lines in the order they have been selected, so for example if line 8 is active and lines 3, 12 and 5 have been selected in this order, the ouput line would be '8,3,5,12';
- adding a `--restore-state` option which takes exactly the same input as --print-state outputs and silently discards line numbers which are larger than the number of input lines. If more than two numbers are given (i.e. the active line and at least two selected lines), `--multi` is implied

**Comment by junegunn** [comment]
Thanks for the suggestion, but

> In order to make fzf more suitable as a drop in replacement for dedicated ui frameworks (like ncurses)

this was never a goal of fzf, and trying to do so will make the code much more complex than it is now. So I'm going to close this.
