### ISSUE TITLE
weird output

### ISSUE THREAD

**Issue by martinshields** [junegunn/fzf#2109]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish
    
## Problem / Steps to reproduce
When i search with fzf or ctrl -t i get output that looks like this.
$'^['\[1\;34m.config$'^['\[0m$'^['\[1\;34m/$'^['\[0m$'^['\[1\;d34m neofetch$'^['\[0m$'^['\[1m\;34m/$'^['\[0m config.conf
i have many Linux setup with fzf using fd. Only one does this. Why?

**Comment by junegunn** [comment]
Looks like your FZF_DEFAULT_COMMAND or FZF_CTRL_T_COMMAND is set to print ANSI colors. (something like `--color=always`)
