### ISSUE TITLE
fzf alias ignored in tab completion

### ISSUE THREAD

**Issue by cdosborn** [junegunn/fzf#211]
I have the following alias `fzf='fzf --no-color'`.

When I run `$ fzf` no problems. However, when i try `$ ssh**<Tab>` I get colored results (my alias is ignored). I'm looking through `fzf/shell/completion.bash` to figure out what might be the cause. I thought I might be able to get a faster answer here.

**Note:** I edited my config so that a different file other than my ~/.bashrc would be sourced. However, it doesn't seem to be relevant because I'm getting the completion.

**Comment by cdosborn** [comment]
I realized I didn't read far enough into the instructions.
`export FZF_COMPLETION_OPTS='--no-color'` worked for me.

Would the project be interested in a pull request, s.t. these settings only have to be defined in one place? Right now an alias has to be set for fzf, along with the env. vars.

**Comment by noahfrederick** [comment]
> Right now an alias has to be set for fzf

You don't need an alias to provide default options. That's what `FZF_COMPLETION_OPTS` is for—unless I've misunderstood your use case.

**Comment by cdosborn** [comment]
If I don't set the alias, then `$ fzf`ignores `FZF_COMPLETION_OPTS`.

**Comment by noahfrederick** [comment]
I confused `FZF_COMPLETION_OPTS` with `FZF_DEFAULT_OPTS`. The latter is what I was thinking of.

**Comment by cdosborn** [comment]
Okay, thanks.

**Comment by junegunn** [comment]
`FZF_DEFAULT_OPTS` is built in to the binary (you can see it on `--help`) and applied regardless of the context. `FZF_COMPLETION_OPTS` is an extra set of options that is applied *in addition to* `FZF_DEFAULT_OPTS` for those who want to use different options just during bash completion.
