### ISSUE TITLE
Question: Is it possible to output the score for a line using `--filter` or similar

### ISSUE THREAD

**Issue by tjdevries** [junegunn/fzf#2113]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [x] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

Hi, I'm wondering if it's possible to get fzf to print out the score given a line and prompt combination.

Essentially what I'd like to do is to get the score using `--filter` or similar for just one line given a particular input. 

Example:

```
echo "foobar" | fzf --show-score "foo"
```

Reasoning:

Ideally FZF would print out the score that you calculate internally. The scores do not have to be consistent over different versions of FZF, I'm just looking to do some sorting and filtering in another program (non-interactively) one line at a time, so filter doesn't really work for me (because I don't want to wait til my long running program completes before doing the sorting and filtering).

Effectively, I would make several calls to FZF over the lifecycle of the program.

```
echo "foobar" | fzf --show-score "foo"
# Good score

echo "hello" | fzf --show-score "foo"
# Not good score

echo "foo" fzf --show-score "foo"
# Great score
```
Following this I would be able to do the sorting and filtering myself given the scores.

Thanks for an awesome project :)

**Comment by junegunn** [comment]
Hi, I assume that you requested this feature so that you can use it in telescope.nvim but you no longer need this, right? I'd rather not address this as it's quite niche and there are alternative fuzzy matching libraries.
