### ISSUE TITLE
Is it possible to jump to function definition with coc

### ISSUE THREAD

**Issue by himat** [junegunn/fzf#2124]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

If I know a function's name, is there a way to jump to its definition from anywhere?

When I used ctags before, I could do this with fzf by searching the tags file.

Is there a way to do this with coc? I've only been able to jump to definition of the current function name that my cursor is on.

**Comment by junegunn** [comment]
I have no idea. You might want to check out https://github.com/antoinemadec/coc-fzf (I haven't tried it)
