### ISSUE TITLE
No-filter / pager mode

### ISSUE THREAD

**Issue by noscript** [junegunn/fzf#2125]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues
    
## Problem / Steps to reproduce

Sometimes I want to see the context near the matching lines and select e.g. a line above the match or below. It would be great to have a no-filter mode, where the search query doesn't filter out the lines but only highlight the matches. There would be separate key bindings to jump between the matches.

Usage scenario examples:
* navigating git log with possibility to output a commit earlier or later than a matching one.
* interactive git rebase, where you have to use a commit earlier than the one in interest.
* music finder: jump to any song in an album or mix that contains the match.

It's like fzf being a pager which can also print selected lines to standard output.

**Comment by junegunn** [comment]
Thanks for the suggestion, but it's not something I want to add to fzf. I want to keep fzf simple and straightforward and I don't want to make it more complicated by introducing different "modes" of execution. I suppose there are different tools that are better suited for the use case.

**Comment by relastle** [comment]
@noscript 

>  It would be great to have a no-filter mode, where the search query doesn't filter out the lines but only highlight the matches

Such feature can be realized relatively easily without adding `mode` concept into fzf.

I'll show just an idea.

```bash
cat tmp.txt | fzf --phony --ansi --bind "change:reload:cat tmp.txt | python3 highlight.py {q}"
```

where 

***tmp.txt*** (which represents search target passed through fzf)

```txt
hoge hoge
hoge fuga
hogehoge
```

and 

***highlight.py*** (which is a tiny sketch implementation for highlighting regular expression matched region. It requires colorama installed.)

```python
import re
import argparse
from typing import List
from pprint import pformat

from colorama import Fore, Style


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument('query', type=str)
    args = parser.parse_args()
    lines: List[str] = []
    while(True):
        try:
            line = input()
        except Exception:
            break
        lines.append(line)
    for line in lines:
        ms = re.finditer(r'{}'.format(args.query), line)
        start_indices = []
        end_indices = []
        for m in ms:
            start_indices.append(m.start())
            end_indices.append(m.end())
        res = ''
        last_end_index = 0
        for start_index, end_index in zip(start_indices, end_indices):
            res += '{}{}{}{}'.format(
                line[last_end_index:start_index],
                Fore.RED,
                line[start_index:end_index],
                Style.RESET_ALL,
            )
            last_end_index = end_index
        res += line[last_end_index:]
        print(res)
    return


if __name__ == '__main__':
    main()
```


![fzf_highlight](https://user-images.githubusercontent.com/6816040/88826469-c0d2d980-d203-11ea-83df-d2b73aebf380.gif)


Here is the demo which incrementally highlights parts of lines matching the queried regular expression.

Of course, as the highlighting program is invoked every time query is changed, you should implement it with *Go*, *Rust* or something compiled language for better usability.

**Comment by noscript** [comment]
@relastle thank you for suggestion but unfortunately this has problems:
* requires something like rafms, as the data to be dumped first into a temporal file (slow storage + storage wear out), which is then re-read and reprocessed by both fzf and highlighter every time the query is changed (performance implication)
* jumping between matches cannot be implemented

**Comment by junegunn** [comment]
See #4534
