### ISSUE TITLE
[FR] Make `'word 'word` match only when there are two `word`s

### ISSUE THREAD

**Issue by NightMachinary** [junegunn/fzf#2126]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] fish
    
    - [x] zsh
    - [ ] bash
## Problem / Steps to reproduce

Related: https://github.com/junegunn/fzf/issues/2078

Currently, there is no way to make fzf match only lines that have multiple copies of sth. For example, I am looking for `uni` in this repository, which contains `uniborg` in its paths:
![image](https://user-images.githubusercontent.com/36224762/88927568-d93b0680-d28c-11ea-88b1-69fe510885c7.png)

As you see, specifying `'uni` two times has no effect. I think the way I am suggesting will be more intuitive to use, as we have little reason to specify duplicate conditions. It should also be hopefully easy to implement, unlike the linked issue's solution.

PS: In this particular case, using `!^uni 'uni` works, but that's not a general solution, and is not as elegant.

**Comment by junegunn** [comment]
See https://github.com/junegunn/fzf/issues/2127#issuecomment-666424405

(In this case, I would just type in `uni/uni`)

**Comment by junegunn** [comment]
FYI, I usually provide an initial query (in this case `uni`) to the search program like ag or rg and use fzf only as the secondary filter (`uni:`) and that works for me really well. It's much more efficient as those programs are much better at searching through file contents.
