### ISSUE TITLE
:Files command doesn't work on vim (but works well on macvim)

### ISSUE THREAD

**Issue by DongeunPaeng** [junegunn/fzf#2128]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

1) I've installed both the latest vim and the macvim via commands: ```brew install macvim``` and ```git clone ... vim/vim.git``` from the official vim website.

2) fzf works perfectly well in my terminal

3) I've installed fzf inside my ~/.vimrc with vim-plugin - my .vimrc file has these two lines:
- Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
- Plug 'junegunn/fzf.vim'

4) After PlugInstall, the console says "fzf: Already installed" and "fzf.vim: Already Installed" because I've repeated steps 1)~3) several times.

5) I open vim ~/.vimrc to test if the command works. (It doesn't have to be .vimrc file, I'm just opening any file.) --> :Files command doesn't work. (ERROR message is down below)

6) I repeat 5), but this time I open .vimrc file with macvim via 'mvim ~/.vimrc' --> not the :Files command works properly.

<ERROR message>

```
Error detected while processing function fzf#vim#files[15]..<SNR>69_fzf[18]..fzf#run[58]..<SNR>21_execute_term[3
]..<SNR>21_split:
line   12:
E605: Exception not caught: Nvim 0.4+ or Vim 8.2.191+ with popupwin feature is required for pop-up window
Press ENTER or type command to continue
```

Can I not use the same :File command in my vanilla vim?

**Comment by junegunn** [comment]
> Nvim 0.4+ or Vim 8.2.191+ with popupwin feature is required for pop-up window

The error message here is pretty clear. Upgrade your Vim or disable popup layout by unsetting `g:fzf_layout`.
