### ISSUE TITLE
Hangs on initialization

### ISSUE THREAD

**Issue by njordr** [junegunn/fzf#2129]
- [x ] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [ x] I have searched through the existing issues

## Info

- OS
    - [x ] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x ] bash
    - [ ] zsh
    - [ ] fish
    
## Problem / Steps to reproduce
Hi.

I just installed the latest version, including the init in .bashrc. At the fist login, it hangs and cannot get the terminal back until I pressed CTRL+C.

doing a little bit of debug (thanks echo :) ) I found this  line to go through all the files in my home dir grepping for something

```
eval "$(complete -p "$@" 2> /dev/null | grep -v "$fn" | __fzf_orig_completion_filter)"
```

It happens that I have a very big repository in my home, with thousands of files in it. fzf is grepping them from this morning (it started at 9.20AM and now it's 3.20PM, 6 hours grepping) and it doesn't finish yet.

Is that an expected behavior or did I miss some configuration to do?

**Comment by junegunn** [comment]
> fzf is grepping them from this morning

I don't see how that line of code can behave as you described.

> Is that an expected behavior

No. Run `bash -x` to see what's really happening.

**Comment by njordr** [comment]
Sorry, bad grep alias, no problems with fzf
