### ISSUE TITLE
Errors when opening a file that has an existing swap file

### ISSUE THREAD

**Issue by mikker** [junegunn/fzf#213]
Regular vim gives me this, then opens the file but the view is all messed up.

```
Error detected while processing function <SNR>65_cmd..fzf#run..<SNR>65_execute_tmux..<SNR>65_callb
ack..<SNR>65_cmd_callback:
```

Neovim on the other hand explodes

![](http://s3.brnbw.com/Screen-Shot-2015-04-23-10-23-56.png)

**Comment by junegunn** [comment]
The above two commits should fix the issues on Vim. I couldn't, however, reproduce the issue on Neovim in the first place, so I'm not sure if it helps or not. Could you update and try again?

**Comment by mikker** [comment]
Whatever it was it seems resolved in both vim and neovim. You're the best :pray:
