### ISSUE TITLE
fzf fails when calling from lf

### ISSUE THREAD

**Issue by n0ibe** [junegunn/fzf#2133]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

The steps to reproduce are the following:

1. have an `FZF_DEFAULT_COMMAND`, doesn't really matter what's in it, I have

```
export FZF_DEFAULT_COMMAND='fd'
```
in my `.zshenv` file;

2. open [lf](https://github.com/gokcehan/lf) via `$TERMINAL -e lf`, for example `alacritty -e lf`;

3. call fzf via `$fzf`. I get the error

![2020-08-11@22:45:15](https://user-images.githubusercontent.com/59321248/89947272-7c443680-dc24-11ea-85f9-70c57f168ad8.png)

Steps 1. and 2. are important: if I don't have a `FZF_DEFAULT_COMMAND` set everything works fine, same if I call `lf` from the command line instead of through `alacritty -e lf`.

I'm not sure if the issue is with `lf` or `fzf` so I'm posting this on both repos.

**Comment by junegunn** [comment]
I suspect fd is not in $PATH in that environment.

**Comment by n0ibe** [comment]
It's not just `fd`, the `FZF_DEFAULT_COMMAND` could even be `ls` and it still wouldn't work. To be sure I set it explicitely to `/usr/local/bin/fd` and the result was the same.

**Comment by junegunn** [comment]
You might want to check the value of $SHELL as fzf uses it to start processes when it's defined.

**Comment by n0ibe** [comment]
Ah, that might be it. For some reason `lf` sets `SHELL=lf` when I call it via `alacritty -e`.
