### ISSUE TITLE
Update caused all fzf scripts and commands to fail on WSL

### ISSUE THREAD

**Issue by raghavmallampalli** [junegunn/fzf#2134]
- [x] I have read through the manual page (`man fzf`)
- [ ] I have the latest version of fzf (unable to check version or update fzf)
- [x] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [ ] Mac OS X
    - [x] Windows (WSL)
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

After recent update all fzf scripts including uninstall fail due to some kind of line ending issue.
Running fzf update command:
```
Already up to date.
./install: line 2: $'\r': command not found
: invalid option3: set: -
set: usage: set [-abefhkmnptuvxBCHP] [-o option-name] [--] [arg ...]
./install: line 4: $'\r': command not found
./install: line 14: $'\r': command not found
./install: line 15: syntax error near unexpected token `$'{\r''
'/install: line 15: `help() {
```
Running the uninstall script:
```
./uninstall: line 2: $'\r': command not found
./uninstall: line 7: $'\r': command not found
./uninstall: line 8: syntax error near unexpected token `$'{\r''
'/uninstall: line 8: `help() {
```
Running fzf:
```
Command 'fzf' not found
```
Running fzf-tmux:
```
/home/raghav/.fzf/bin/fzf-tmux: line 4: $'\r': command not found
/home/raghav/.fzf/bin/fzf-tmux: line 5: syntax error near unexpected token `$'{\r''
'home/raghav/.fzf/bin/fzf-tmux: line 5: `fail() {
```

I have tried deleting the repository, setting line ending mode to auto, true and lf and reinstalling each time. It does not work.

**Comment by junegunn** [comment]
It doesn't sound like an issue of fzf. uninstall script, for example, hasn't been updated for the past two years.

**Comment by raghavmallampalli** [comment]
It could have been caused by an update in Windows. A recently released build introduced major changes in the WSL architecture. fzf did work for me on WSL before and now it no longer does. Does anyone else have this issue?

**Comment by raghavmallampalli** [comment]
Fixed the issue. Just had to set `git config --global core.autocrlf input` before cloning the repository.
