### ISSUE TITLE
Feature Request: Periodic Action (enables `fzf` to be like a better `watch`)

### ISSUE THREAD

**Issue by bigH** [junegunn/fzf#2135]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

NA

- OS
    - [x] Linux
    - [x] Mac OS X
    - [x] Windows
    - [x] Etc.
- Shell
    - [x] bash
    - [x] zsh
    - [x] fish
    
## Problem / Steps to reproduce

I would like to be able to `reload` `git status -s` or `kubectl get nodes` and more.

It would be nice to have `fzf` be able to periodically run the `reload`.
I understand certain commands take a long time to run and there are considerations there.

**Comment by junegunn** [comment]
Closing since #2136 discusses a more general approach to the use case.
