### ISSUE TITLE
Feature Request: External Triggering (listening to file system, etc.)

### ISSUE THREAD

**Issue by bigH** [junegunn/fzf#2136]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

NA

- OS
    - [x] Linux
    - [x] Mac OS X
    - [x] Windows
    - [x] Etc.
- Shell
    - [x] bash
    - [x] zsh
    - [x] fish
    
## Problem / Steps to reproduce

(somewhat related to #2135)

I would like to be able to trigger reload externally, like using `entr` or `fsnotify` or other event listeners.

**Comment by junegunn** [comment]
Closing as a duplicate of #2019.
