### ISSUE TITLE
Bash - Variable/Command substitution not updating when used with --bind flag

### ISSUE THREAD

**Issue by nordmagnus999** [junegunn/fzf#2137]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

I'm trying to launch a command through the `--bind` flag like so:
```bash
echo '' | fzf --bind ctrl-m:execute:"echo $RANDOM"
```
In this example, the variable doesn't get updated when entering the key (enter/ctrl-m) more than once, unless fzf close and i reopen again. The same problem occur when replacing the `$RANDOM` system variable with a command substitution:

```bash
echo '' | fzf --bind ctrl-m:execute:"echo $(cat /dev/urandom | head -c 3)"
```
Another example.

Is there any way with bash and/or fzf to make variable/command substitution update when used with the `--bind` flag?

**Comment by junegunn** [comment]
Use single-quotes to avoid immediate evaluation:

```sh
fzf --bind 'ctrl-m:execute:echo $RANDOM'
```
