### ISSUE TITLE
why ydiff not work in fzf preview

### ISSUE THREAD

**Issue by rmGFW** [junegunn/fzf#2142]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

 the cmd `ydiff -s --wrap src/App.vue` is work on my terminal 
the src/App.vue is the file name i want to diff

but this command not work ,and preview show noting

git status -s \
 | fzf --no-sort --reverse \
 --preview 'ydiff -s --wrap {+2}' \
 --preview-window=right:60%:wrap

**Comment by junegunn** [comment]
No idea. I'm not familiar with the problem. But redirecting `/dev/tty` seems to fix the problem.

```sh
git status -s | fzf --no-sort --reverse --preview 'ydiff -s -c always --wrap {2} < /dev/tty' --preview-window up

**Comment by rmGFW** [comment]
> No idea. I'm not familiar with the problem. But redirecting `/dev/tty` seems to fix the problem.
> 
> ```shell
> git status -s | fzf --no-sort --reverse --preview 'ydiff -s -c always --wrap {2} < /dev/tty' --preview-window up
> ```

this cmd can't deal such case when a file change and this file's path contains blank space. such as  'computer architecture/Coherence Basics.md' .
I have tried to replace {2} with  '{2}' or "{2}" . but both them not work

**Comment by junegunn** [comment]
Well, you'll have to figure out how to handle that using shell scripting.
