### ISSUE TITLE
Feature request: Allow us to change the keybinds

### ISSUE THREAD

**Issue by Zeioth** [junegunn/fzf#2144]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - Linux
- Shell
    - zsh
    
## Problem / Steps to reproduce
There's no env vars exposed to change the keyboard shortcuts for the methods in /usr/share/fzf/fzf-keybinds.sh

**Comment by dsimon28** [comment]
well I can give you an answer for bash
in file makred key-bindings.bash (found mine in /usr/share/fzf/) at the bottom you will see your alt c bindings (\ec)
```bash
# ALT-C - cd into the selected directory
bind -m emacs-standard '"\ec": " \C-b\C-k \C-u`__fzf_cd__`\e\C-e\er\C-m\C-y\C-h\e \C-y\ey\C-x\C-x\C-d"'
bind -m vi-command '"\ec": "\C-z\ec\C-z"'
bind -m vi-insert '"\ec": "\C-z\ec\C-z"'
```
in order to change to ctrl d you just replace the \ec with \C-d
```bash
# CTRL-D - cd into the selected directory
bind -m emacs-standard '"\C-d": " \C-b\C-k \C-u`__fzf_cd__`\e\C-e\er\C-m\C-y\C-h\e \C-y\ey\C-x\C-x\C-d"'
bind -m vi-command '"\C-d": "\C-z\ec\C-z"'
bind -m vi-insert '"\C-d": "\C-z\ec\C-z"'
```
in zsh its pretty easy too same folder key-bindings.zsh
```zsh
# ALT-C - cd into the selected directory
fzf-cd-widget() {
  local cmd="${FZF_ALT_C_COMMAND:-"command find -L . -mindepth 1 \\( -path '*/\\.*' -o -fstype 'sysfs' -o -fstype 'devfs' -o -fstype 'devtmpfs' -o -fstype 'proc' \\) -prune \
    -o -type d -print 2> /dev/null | cut -b3-"}"
  setopt localoptions pipefail no_aliases 2> /dev/null
  local dir="$(eval "$cmd" | FZF_DEFAULT_OPTS="--height ${FZF_TMUX_HEIGHT:-40%} --reverse $FZF_DEFAULT_OPTS $FZF_ALT_C_OPTS" $(__fzfcmd) +m)"
  if [[ -z "$dir" ]]; then
    zle redisplay
    return 0
  fi
  cd "$dir"
  unset dir # ensure this doesn't end up appearing in prompt expansion
  local ret=$?
  zle fzf-redraw-prompt
  return $ret
}
zle     -N    fzf-cd-widget
bindkey '^D' fzf-cd-widget
```
right here ^  you will find a \ec instead of a '^D' this one has already been swapped out and seems to be working fine, id recommend copying the file to somewhere and sourcing it from your initiaion file.

**Comment by Zeioth** [comment]
It would be cool to expose an env var, but I can live with that thanks.

**Comment by dsimon28** [comment]
i dont really use zsh but you can use variable substitution in bash for bindings
``` bash
${BIND=-bind -m vi-insert -x '"\en":"\C-a" sudo "\C-\ee"'}
bind -m vi-insert -x '"${KEY:=\en}":"\C-a" sudo "\C-\ee"'
```
im sure zsh has something similar

**Comment by dsimon28** [comment]
whats your goal? if you don't mind my asking what are you searching for and why?  Might help me see if i can come up with a solution (practice for me as im newish to scripting/programming in general)

**Comment by Zeioth** [comment]
Being able to change the keybinds without having to edit sudo files. I mean, personally I already fixed it but I think it would be good for the project.

**Comment by Zeioth** [comment]
Template applied to the issue.

**Comment by rayiik** [comment]
Also you shouldn’t need to edit Sudo files as far as I’m aware you should have a local .zshrc file that’s sourced on login that you can add your bindings to or even creat your own file and source it with your bindings but the command the file I showed you can copy to your home dir and change then source however if you’ve found a solution could you please post it so others looking for a similar answer can see what you’ve done

**Comment by Zeioth** [comment]
Thank you I'll look for it during this week hopefully.

**Comment by rayiik** [comment]
no worries for the file for fzf is called key-bindings.zsh mine was in usr/share/fzf but you can always download from here and then source it in your rc file if the ~/.zshrc doesnt exist you can create it and it should automatically source as a startup file

**Comment by Zeioth** [comment]
Rayiik solution works elegantly. Steps to reproduce:

    mv /usr/share/fzf/key-bindings.zsh ~/.fzf-keybinds
    
Now on ~/.vimrc add the next line

    source ~/.fzf-keybinds

Of course, you can name the file as you preffer.

**Comment by rayiik** [comment]
Excellent glad you got that going :)

**Comment by cmm** [comment]
https://github.com/junegunn/fzf/pull/2460, for Ctrl-T (don't see why anyone would object to Ctrl-R)

**Comment by muravjov** [comment]
> #2460, for Ctrl-T (don't see why anyone would object to Ctrl-R)

Ctrl-R in bash is 
```
$ bind -p | grep -E '"\\C-r'
"\C-r": reverse-search-history
```
and may be usable too for people using it before and so got accustomed to the way it works. So the wish is to have both features at the same time: classical readline C-r and fzf's one (right now the classical one is not accessible after installing fzf bash scripts)
