### ISSUE TITLE
fzf-tmux hangs when FZF_DEFAULT_OPTS is set

### ISSUE THREAD

**Issue by noahfrederick** [junegunn/fzf#215]
On OS X in fish and bash, invoking fzf-tmux directly or through other commands/shell key bindings results in the following:

- An empty tmux pane appears momentarily and then disappears
- The shell does not accept any input until fzf-tmux is killed with `C-c`.

*This only happens when `FZF_DEFAULT_OPTS` is set (to anything).* To reproduce in fish:

    $ set -x FZF_DEFAULT_OPTS --reverse
    $ fzf-tmux    # Hangs
    ^C⏎ 
    $ set -u FZF_DEFAULT_OPTS
    $ fzf-tmux    # Succeeds

# Environment

fzf version:

    0.9.11

bash version:

    GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin14)
    Copyright (C) 2007 Free Software Foundation, Inc.

tmux version:

    tmux 1.9a

**Comment by junegunn** [comment]
Can't reproduce. Can you check what's going on by replacing the she-bang line to `#!/bin/bash -x`?

**Comment by noahfrederick** [comment]
Here's the output up until it gets stuck:

```
+ args=()
+ opt=
+ skip=
+ swap=
+ close=
+ term=
+ '[' 0 -gt 0 ']'
+ '[' -z %17 ']'
+ set -e
+ id=9528
+ argsf=/tmp/fzf-args-9528
+ fifo1=/tmp/fzf-fifo1-9528
+ fifo2=/tmp/fzf-fifo2-9528
+ fifo3=/tmp/fzf-fifo3-9528
+ trap cleanup EXIT SIGINT SIGTERM
++ which fzf
+ fzf=/Users/nox/.fzf/bin/fzf
+ '[' -x /Users/nox/.fzf/bin/fzf ']'
+ envs=
+ '[' -n --reverse ']'
++ printf %q --reverse
+ envs=' FZF_DEFAULT_OPTS=--reverse'
+ '[' -n '' ']'
+ mkfifo /tmp/fzf-fifo2-9528
+ mkfifo /tmp/fzf-fifo3-9528
+ opts=
+ '[' -n '' -o -t 0 ']'
+ cat
++ printf %q /Users/nox/bin
+ tmux set-window-option -q synchronize-panes off ';' split-window 'cd /Users/nox/bin; FZF_DEFAULT_OPTS=--reverse bash /tmp/fzf-args-9528'
+ cat /tmp/fzf-fifo2-9528
```

I think I see the (fish-specific) problem. In the argument to `split-window`: `FZF_DEFAULT_OPTS=--reverse bash /tmp/fzf-args-9528` is not valid fish syntax. It could be changed to `env FZF_DEFAULT_OPTS=--reverse bash /tmp/fzf-args-9528`.

I was mistakenly under the impression that I tried the script under bash, but I was presumably still getting a fish shell when tmux created the new pane.

**Comment by junegunn** [comment]
Oh I see. Then we can simply prepend `env` as it works on other shells as well.

**Comment by junegunn** [comment]
Updated. Let me know if you still see the problem.

**Comment by noahfrederick** [comment]
> Then we can simply prepend env as it works on other shells as well.

Yeah, confirmed this fixes it for me.
