### ISSUE TITLE
trigger completion with only tab

### ISSUE THREAD

**Issue by blueray453** [junegunn/fzf#2155]
- [x] I have read through the manual page (`man fzf`)
- [ ] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish
    
Can I use `export FZF_COMPLETION_TRIGGER=''`. I mean I want to trigger completion with only tab. Is it possible?

**Comment by predmijat** [comment]
Was it really easier to create an issue than to try it yourself? :)

Yes, you can add it, but I don't think you want it - it will trigger it on a simple `cd proj<TAB>` when you just wanted it to complete `cd projects`, or similar.
What you probably want is to set it per command, which I didn't find how to do. There's a PR for it, but not merged: https://github.com/junegunn/fzf/pull/1299
