### ISSUE TITLE
Error running fzf via Vim's :Buffers (invalid arg to --preview-window)

### ISSUE THREAD

**Issue by yogan** [junegunn/fzf#2158]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux (Ubuntu 20.04 on WSL2)
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [x] fish
    
## Problem / Steps to reproduce

When running `:Buffers` in Vim, I get an error like this:

```
Error running cat '/tmp/vr6PlXi/11'|'/home/yogan/.fzf/bin/fzf' --history '/home/yogan/.local/share/fzf-hi
story/buffers'  '+m' '-x' '--tiebreak=index' '--header-lines=1' '--ansi' '-d' '\t' '--with-nth' '3..' '-n
' '2,1..2' '--prompt' 'Buf> ' '--query' '' '--preview-window' '+{2}-5' --expect=ctrl-v,ctrl-x,ctrl-t --he
ight=21 > /tmp/vr6PlXi/10
```

I can see that the error comes from ` '--preview-window' '+{2}-5'` (that `+{2}-5` is not a valid,
but I cannot say what causes this.

I haven't used fzf in Vim for quite some time, so this might be due to some update. I can't really
recall whether `:Buffers` is even supposed to show a preview window.

Note that `:Files` works just fine, with a preview window.

**Comment by junegunn** [comment]
Upgrade your fzf.

**Comment by yogan** [comment]
Of course. I'm an idiot. I pulled, but forgot to `./install`. Shame on me. 😔
