### ISSUE TITLE
The phony option allows typing

### ISSUE THREAD

**Issue by antiold** [junegunn/fzf#2159]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
- Shell
    - [x] bash
    
## Problem / Steps to reproduce
Using `ls | fzf --phony` allows typing. If the `phony` option makes fzf `becomes a simple selector` it should not allow any typing. Is there any combo with `--phony` that blocks typing?

**Comment by dsimon28** [comment]
what you want is -f / --filter (filter mode . do not start interactive finder. when used with --no-sort, fzf becomes a fuzzy-version of grep) phony you can still type in the query string which lets you do stuff like searching within the contents of highlighted file for specific matches {} and other nifty stuff.i feel this is working as intended.

**Comment by junegunn** [comment]
You might want to read #1750 to understand why we added `--phony` option in the first place.

Having said that, you could try something like this:

```sh
fzf --phony --bind change:clear-query
```

**Comment by DanBiscotti** [comment]
Hi, I had a question which I feel is relevant,
Is there a way to have phony mode without any prompt eg. for a simple yes/no select menu?
```
$ echo "yes\nno" --phony | fzf

  yes
> no
  (2/2) <<<< without these 2 lines
>|      <<<< without these 2 lines
```

**Comment by junegunn** [comment]
No. You might want to check out something like https://github.com/p-gen/smenu instead.

**Comment by ELMCLOSE** [comment]
Is there a way to copy/store the contents of the preview window? This would be useful when using {+} option and collecting chunks of text from various files.

**Comment by ELMCLOSE** [comment]
Have you removed change-prompt as a valid action? used in many of your examples and very useful too.

**Comment by junegunn** [comment]
> Using `ls | fzf --phony` allows typing. If the `phony` option makes fzf `becomes a simple selector` it should not allow any typing. Is there any combo with `--phony` that blocks typing?

See https://github.com/junegunn/fzf/commit/6c0ca4a64a4e2f8697dfa830dcae56c1d7ddca51
