### ISSUE TITLE
Deprecated __fzfcmd_complete?

### ISSUE THREAD

**Issue by jbriales** [junegunn/fzf#2160]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish
    
## Problem / Steps to reproduce
In the past, I was using `__fzfcmd_complete` which I think was provided in shell/completion.bash
After an update, this doesn't seem to exist anymore. Could you provide any pointer as to where this was deprecated to check the newer alternative?

**Comment by junegunn** [comment]
`__fzfcmd_complete` was never documented, and you shouldn't rely on an undocumented internal function. 

You might want to read through https://github.com/junegunn/fzf#fuzzy-completion-for-bash-and-zsh
