### ISSUE TITLE
Mouse-scrolling loses focus in zsh subshell after piped input completes

### ISSUE THREAD

**Issue by veloxo** [junegunn/fzf#2161]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

Tested with
- iTerm2 and MacOS Terminal
- [minimal `zsh` config](https://github.com/junegunn/fzf/issues/2101#issuecomment-651711230)
- all "FZF" environment variables unset
- not using `tmux`

Mouse-scrolling works in each of these cases except <span>#</span>3:
```shell
# ✅ 1. General invocation
find . -maxdepth 5 2> /dev/null | fzf --height 10

# ✅ 2. Subshell, full height
echo "$(find . -maxdepth 5 2>/dev/null | fzf)"

# ❌ 3. Subshell, partial height
echo "$(find . -maxdepth 5 2>/dev/null | fzf --height 10)"

# ✅ 4. Subshell, partial height, fzf-tmux
echo "$(find . -maxdepth 5 2>/dev/null | fzf-tmux --height 10)"
```

In the failure case, mouse-scrolling works until `find` completes, then the scroll target reverts to the parent terminal window. Also, this fails in `zsh` but succeeds in `bash`.

#2101 is a symptom of this general issue. The problem manifests in [`fzf-cd-widget`](https://github.com/junegunn/fzf/blob/0.21.1/shell/key-bindings.zsh#L85) and [`fzf-history-widget`](https://github.com/junegunn/fzf/blob/0.21.1/shell/key-bindings.zsh#L103-L104), which evaluate `fzf` in subshell.

Thanks!

**Comment by veloxo** [comment]
Simpler:

```shell
# ✅ 1b. General invocation
echo "1\n2\n3" | fzf
sleep 5 | echo '1\n2\n3' | fzf
{ sleep 1; echo '1\n2\n3' } | fzf

# ✅ 2b. Subshell, partial height, immediate
echo "$(echo '1\n2\n3' | fzf)"

# ❌ 3b. Subshell, partial height, delayed
echo "$(sleep 5 | echo '1\n2\n3' | fzf)"
echo "$({ sleep 1; echo '1\n2\n3' } | fzf)"

# ✅ 4b. Subshell, partial height, delayed, fzf-tmux
echo "$(sleep 5 | echo '1\n2\n3' | fzf-tmux)"
echo "$({ sleep 1; echo '1\n2\n3' } | fzf-tmux)"
```

**Comment by NightMachinary** [comment]
This reminds of this zsh bug https://www.zsh.org/mla/workers/2020/msg00649.html. The fact that it works fine in bash is suggestive that the problem is with zsh.

**Comment by lincheney** [comment]
I think this is related: https://github.com/junegunn/fzf/blob/3fe8eeedc5f5180f9c9db76fca26844f8c6acf37/src/tui/light.go#L604
I ran an strace over zsh and could see it send a SIGCONT to fzf, which bash does not do.
