### ISSUE TITLE
FZF Reload Ripgrep Not Working in both shell and neovim

### ISSUE THREAD

**Issue by monsonjeremy** [junegunn/fzf#2162]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

This problem manifests for me both on the command line and from within neovim:

Using the command from the man page:
```sh
RG_PREFIX="rg --column --line-number --no-heading --color=always --smart-case " \
INITIAL_QUERY="foobar" \
FZF_DEFAULT_COMMAND="$RG_PREFIX '$INITIAL_QUERY'" \
fzf --bind "change:reload:$RG_PREFIX {q} || true" --ansi --phony --query "$INITIAL_QUERY"
```

```vim
set nocompatible hidden laststatus=2

scriptencoding utf-8

if !filereadable('/tmp/plug.vim')
  silent !curl --insecure -fLo /tmp/plug.vim
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
endif

source /tmp/plug.vim
call plug#begin('/tmp/plugged')

Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'

call plug#end()

autocmd VimEnter * PlugClean! | PlugUpdate --sync

function! RipgrepFzf(query, fullscreen)
  let command_fmt = 'rg --trim --fixed-strings --hidden --line-number --no-heading --color=always --smart-case -- %s || true'

  let initial_command = printf(command_fmt, shellescape(a:query))
  let reload_command = printf(command_fmt, '{q}')
  let spec = {'options': ['--phony', '--query', a:query, '--bind', 'change:reload:'.reload_command]}
  call fzf#vim#grep(initial_command, 1, fzf#vim#with_preview(spec), a:fullscreen)

endfunction

command! -nargs=* -bang Rg call RipgrepFzf(<q-args>, <bang>0)
```

In both cases, when I use these commands I am unable to get results when I update the query. In neovim (in the floating window) I will occasionally get the results but it takes an incredibly long time to update (upwards of a minute or two)

**Comment by junegunn** [comment]
I can't reproduce the problem. Looks like your ripgrep is not producing the result fast enough.

**Comment by monsonjeremy** [comment]
Thanks @junegunn, I actually figured out the problem today. I noticed this error kept happening, and added the solution linked at it's fixed:
https://github.com/pyenv/pyenv/issues/1157#issuecomment-418446159
