### ISSUE TITLE
Incomplete clearing of the preview window in the presence of combining Unicode characters

### ISSUE THREAD

**Issue by vejkse** [junegunn/fzf#2163]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

Here’s the content of a very small text file, let’s call it [`combining_unicode.txt`](https://github.com/junegunn/fzf/files/5157724/combining_unicode.txt), where the « ă » is an « a » followed by a combining breve (U+0306):
```
xyz
ăb
uvw
ab
```

If I do `cat combining_unicode.txt | fzf --preview='echo {}'`, and move up in the list from `xyz` to `ăb` (or type `a`, so that `xyz` is filtered out), the preview window shows `ăbz` instead of `ab`, the `z` being the remains of `xyz` incompletely cleared from the screen.  No such problem arises further up when moving from `uvw` to `ab`.

This may be related to #1526.

**Comment by junegunn** [comment]
While 69dffd7 is not a proper fix to the problem, it fixes this particular case. Please let me know if you run into another similar issue.

**Comment by vejkse** [comment]
Thank you!   It works apparently perfectly.
