### ISSUE TITLE
OSC 8 support in preview window

### ISSUE THREAD

**Issue by edubxb** [junegunn/fzf#2165]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

I'm using a [mdcat](https://github.com/lunaryorn/mdcat) to show markdown files in the preview window, mdcat supports [terminal hyperlinks](https://gist.github.com/egmontkob/eb114294efbcd5adb1944c9f3cb5feda), but in fzf preview window hyperlinks aren't correctly rendered.

I'm using Tilix as terminal emulator, that supports (is VTE based) this feature, and mdcat works as expected when hyperlinks are found in Markdown files.

In the image, you can spot the difference, using the same file (fzf README), on the left, mdcat, on the right, fzf preview window, the cursor shape should change when a link is found:

![image](https://user-images.githubusercontent.com/1192339/92034536-aabdb900-ed6d-11ea-9354-ad6203665a13.png)

**Comment by dandavison** [comment]
Hi, thanks for `fzf`! Here are some examples of tools that emit OSC 8 hyperlinks and would be nice to use in fzf preview windows:

- GNU ls
- https://github.com/BurntSushi/ripgrep
- https://github.com/sharkdp/fd
- https://github.com/dandavison/delta

**Comment by edubxb** [comment]
Thanks a lot! 🤩
