### ISSUE TITLE
No package manager post-install instructions to enable key bindings

### ISSUE THREAD

**Issue by pknowles** [junegunn/fzf#2168]
Testing with debian 10, `apt install fzf -y` but ctrl-r is replaced afterwards. This is good IMO and it should be up to each user to enable it. I would expect to find instructions to do so in the readme here, or in `fzf --help` relating to how to set up key bindings. Or have I just missed it?

**Comment by junegunn** [comment]
Currently, we're stating that some additional steps may be required.

https://github.com/junegunn/fzf#using-linux-package-managers

> Shell extensions (key bindings and fuzzy auto-completion) and Vim/Neovim plugin may or may not be enabled by default depending on the package manager. Refer to the package documentation for more information.

We're not the maintainer of the packages, so we can't provide complete documentation for all of those packages here. That would make our documentation unnecessarily long.

**Comment by aug0stus** [comment]
For `Ubuntu 20.04.1 LTS`, I noticed the file `README.Debian` while going through the [list of files ](https://packages.ubuntu.com/focal/amd64/fzf/filelist)provided by the package manager, and it included post-install instructions. 

```
Bash
====

Append this line to ~/.bashrc to enable fzf keybindings for Bash:

   source /usr/share/doc/fzf/examples/key-bindings.bash

Append this line to ~/.bashrc to enable fuzzy auto-completion for Bash:

   source /usr/share/doc/fzf/examples/completion.bash

Zsh
===

Append this line to ~/.zshrc to enable fzf keybindings for Zsh:

   source /usr/share/doc/fzf/examples/key-bindings.zsh

Append this line to ~/.zshrc to enable fuzzy auto-completion for Zsh:

   source /usr/share/doc/fzf/examples/completion.zsh

Fish
====

Issue the following commands to enable fzf keybindings for Fish:

   mkdir -p ~/.config/fish/functions/
   echo fzf_key_bindings > ~/.config/fish/functions/fish_user_key_bindings.fish

Vim
===

The straightforward way to use fzf.vim is appending this line to your vimrc:

   source /usr/share/doc/fzf/examples/fzf.vim
```
