### ISSUE TITLE
feature-request: option to disable search pattern highlighting.

### ISSUE THREAD

**Issue by paxsali** [junegunn/fzf#2169]
- [X] I have read through the manual page (`man fzf`)
- [X] I have the latest version of fzf
- [X] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [ ] Mac OS X
    - [X] Windows
    - [ ] Etc.
- Shell
    - [X] bash
    - [ ] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

Hi all,

consider the following use case / scenario:

You have this (bash) shell function to be able to quickly "preview" the ansi color codes and standard attributes...

```
function show_all_attr_colors256_verbose {
    local attr
    local -A layer
    local color
    local -A attribute
    attribute+=([0]=normal)
    attribute+=([1]=bold)
    attribute+=([2]=faint)
    attribute+=([3]=italic)
    attribute+=([4]=underline)
    attribute+=([5]=blink)
    attribute+=([7]=reverse)
    layer+=([38\;5]=foreground)
    layer+=([48\;5]=background)
    for attr in 0 1 2 3 4 5 7; do
        for fgbg in 38\;5 48\;5; do
            for color in {0..255}; do
                echo -en "\E[${attr};${fgbg};${color}m${attribute[${attr}]} "
                echo -e  "${layer[${fgbg}]} color${color}\E[0m"
            done
        done
    done
}
```

It's safe to try it out like this: `show_all_attr_colors256_verbose | fzf --ansi`

Type in some combination of "attributes", "foreground|background" and "color{0..255}" to have the particular effect/coloring appear / poor man's preview (has nothing to do with `--preview` option btw)

It looks like this:

1. 
<img src="https://i.imgur.com/7EnoRBF.png">
2. 
<img src="https://i.imgur.com/k2lo2P5.png">

I am wondering if it's possible to disable the highlighting of **only** the search pattern (without disabling color/ansi all together, obviously). In the screenshots above I have colored in red what I mean by "the coloring/highlighting of the search pattern/matches".

Granted, this is a **VERY** particular use-case and scenario... I am very well aware of that.

Still, I'm happy to hear your thoughts and read your comments on whether you think it's a good idea.

Thank you in advance.

**Comment by junegunn** [comment]
Hi, thanks for the suggestion. As you have mentioned, this is a very specific, niche use case so I'm going to pass on this to avoid feature bloat. As a workaround, I would just print some additional sample text in each color.

```sh
function show_all_attr_colors256_verbose {
    local attr
    local -A layer
    local color
    local -A attribute
    attribute+=([0]=normal)
    attribute+=([1]=bold)
    attribute+=([2]=faint)
    attribute+=([3]=italic)
    attribute+=([4]=underline)
    attribute+=([5]=blink)
    attribute+=([7]=reverse)
    layer+=([38\;5]=foreground)
    layer+=([48\;5]=background)
    for attr in 0 1 2 3 4 5 7; do
        for fgbg in 38\;5 48\;5; do
            for color in {0..255}; do
                printf "%-30s " "${attribute[${attr}]} ${layer[${fgbg}]} color${color}"
                echo -e "\E[${attr};${fgbg};${color}mLorem ipsum dolor sit amet\E[0m"
            done
        done
    done
}
```

**Comment by paxsali** [comment]
Hello again,

after learning more about fzf I'd like to revisit and reopen this request.

The internal variables responsible for controling the highlighted (search-matching) text colors are `hl` and `hl+` as described in the man page under the `--color` section.

Unfortunatelly, the syntax is such that you have to specify valid color digits to control.

This isn't valid syntax: `fzf --ansi --color="hl:,hl+:"` and the error message is `invalid color specification: hl:`.

I think there should be a way for "disabling" the default `hl` and `hl+` colors without specifying them precisely, such that fzf just doesn't handle the search term (in the current line and it other lines) in any special way and just colors them normally with whatever the current defaults of the terminal/console are, like non-highlighted text.

And btw, since I already tried it, this also doesn't work: `fzf --ansi --no-info --color="hl:fg,hl+:fg+"`
error message: `invalid color specification: hl:fg`

Kindly asking you to reconsider.

**Comment by paxsali** [comment]
I just realized there is no "feature" to be added here.

The feature already exists and I figured out how to achive this, so I will update the OP.

However, maintainer should consider to updating the tags from `wontfix` to whatever is appropriate for a false feature request (where the feature was already present).
