### ISSUE TITLE
Option to invert the selection in --multi?

### ISSUE THREAD

**Issue by D630** [junegunn/fzf#217]
Hi,

How about an option to invert the selection, when using fzf with `--multi` interactively?

```sh
% p () { printf '%s\n' {1..10} ; }
% p | fzf --multi # select 1-5
10
9
8
7
6
```

Otherwise one need to workaround it with something like:

```sh
% p | fzf --multi | fgrep -vxf /dev/fd/0 <(p)
```

**Comment by junegunn** [comment]
Like `-v` option of grep? (which should apply even when `--no-multi`)

**Comment by D630** [comment]
Ja, that would be great! And it could be indicated with a less-than sign (<)...

**Comment by junegunn** [comment]
I've given some thought about it but realized that it's not as trivial as I first imagined and considering the added complexity I think I'm gonna pass on this.
- Given the asynchronous nature of fzf interface. We can finish fzf well before the input stream is complete. (e.g. `locate / | fzf`) The additional code for waiting for its completion is required.
- And then how should the result be sorted? Or should we sort the result? It's not really straightforward. The new option doesn't seem to play nicely with ranking algorithm.
- `--select-1` and `--exit-0` become very unintuitive and confusing.
- `--filter` will require different code path depending on the option. Sorting is also an issue here.

**Comment by D630** [comment]
Ok. Thanks
