### ISSUE TITLE
#feature Show a listing of bound keys from a running instance of fzf

### ISSUE THREAD

**Issue by avielsh** [junegunn/fzf#2171]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [x] Mac OS X
    - [x ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [x] zsh
    - [ ] fish
    
## Problem / Steps to reproduce
No problems, Fzf is great 👍 
I'm using fzf extensively both as a file manager and organizer and viewer on multiple OSs. 
I have many custom commands bound to shortcut keys (~10-20) for each use case and sometimes it's difficult remembering all that's configured for each use case.

It could be great if fzf could support during runtime a listing of all bound keys to functions - something like tmux's `<prefix>?`or vim's `:map`
Cheers 👍 
**Note**: A portable conf file for fzf - .fzf is a good feature to support that as the configuration variations become too big to maintain via aliases..

**Comment by junegunn** [comment]
Thanks for the suggestion but this seems like a niche use case so I don't want a new option for this.

I would instead provide a help file or a bind config file and allow users to see it using a `--bind` key.

```sh
$ fzf --header 'Press CTRL-H for help' --bind 'ctrl-h:execute:more HELPFILE'

$ cat fzf.bind
--bind a:up
--bind b:down
$ FZF_DEFAULT_OPTS=$(cat fzf.bind) fzf --bind 'ctrl-h:execute:more fzf.bind'
```

**Comment by avielsh** [comment]
Thanks for the quick reply
It's a good enough workaround for me 👍 
It does not include the default keybinds that come with fzf (which increase as time lapses) but still good workaround
thanks for this great app 🥇

**Comment by avielsh** [comment]
I might have spoken too soon
It seems this solution works fine when executing fzf by itself, but when redirecting the output to a command 
I.E 
`vim $(fzf) `
or 
`files=($(fzf)) 
`
which are my main use cases, pressing the ctrl-h binding for help would output the help info into the next command, spitting for example:
`vim: Unknown option argument: "--bind"`

Without actually showing the help..
Is there a way to get around this ?

**Comment by junegunn** [comment]
Redirecting the output to `/dev/tty` is the key.

```sh
vim "$(fzf --bind 'ctrl-h:execute:echo --bind foo > /dev/tty; read')"
```

**Comment by avielsh** [comment]
> Redirecting the output to `/dev/tty` is the key.
> 
> ```shell
> vim "$(fzf --bind 'ctrl-h:execute:echo --bind foo > /dev/tty; read')"
> ```
Yep! That solves it, thanks 👍 👍 

FWIW, here's a working config for the above method that worked for me:

When binding via external file:

`alias myfm='fzf $(cat ~/.fzf-bind)'`

would have issues because of quoting which is needed in case of using placeholders.

The solution is evaluating at compilation time instead of runtime:

`alias myfm='fzf '"$(cat ~/.fzf-bind)"`

This method requires every line ending would be prepended with backslash `\` and it works with quoting the entire bind:

`cat ~/.fzf-bind`
```shell
--bind "alt-a:execute-silent:qlmanage -p {+}  >& /dev/null" \
--bind "alt-d:select-all" \
--bind "alt-e:deselect-all" \
--bind "alt-enter:execute-silent:open {+}" \
--bind "alt-f:execute(~/finder.sh {+})" \
--bind "alt-h:execute:cat ~/.fzf-bind|less > /dev/tty" \
--bind "alt-l:execute:ls -lh {+}" \
--bind "alt-w:execute-silent:echo {+} >> ~/filelist" \
--bind "ctrl-b:execute-silent:open -a /Applications/MacVim.app {+}" \
--bind "ctrl-d:preview-page-down" \
--bind "ctrl-u:preview-page-up" \
--bind "shift-down:page-down" \
--bind "shift-up:page-up" 
```
**Note**: Github's MD Code highlight adds an extra whitespace after the backslash `\` , so take note if copying this snippet.

HTH
