### ISSUE TITLE
Link to fzf-bin releases from fzf README?

### ISSUE THREAD

**Issue by coolaj86** [junegunn/fzf#2173]
There's no mention of "releases", "binary", or `fzf-bin` in the README.

I've put `fzf` up on [webinstall.dev/fzf](https://webinstall.dev/fzf) linking to the homepage, but if a person checks on the FZF homepage to verify that the builds are unmodified, 1st party builds directly from the official releases, as promised, they will likely go to the `Releases` tab and see that nothing is there, which would be confusing.

And then there's nothing in the main README to indicate that the official releases are available, but that they're in the `fzf-bin` repo.

I don't remember how I found out about them myself, but when I came back here looking for "releases" and "binary", I found nothing.

- [ ] N/A
- [ ] N/A
- [x] I have searched through the existing issues

## Info

- OS - **N/A**

**Comment by junegunn** [comment]
The link in https://github.com/junegunn/fzf#installation points to the page.

**Comment by junegunn** [comment]
Update: Since 0.24.0, new realeses will be available in https://github.com/junegunn/fzf/releases
