### ISSUE TITLE
Make FZF respect current directory when startup directory is changed in fish.config

### ISSUE THREAD

**Issue by Brixy** [junegunn/fzf#2174]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [x] fish
    
## Problem / Steps to reproduce

FZF (fish shell; outside Vim) respects the current working directory.

Yet, when I add  `cd ~/Desktop/` to my `config.fish` in order to change my startup directory, start a shell, and `cd` to another directory, FZF only searches `~/Desktop/`—no matter which directory is the current:

Is there any way that FZF still respects the current directory?

**Comment by Brixy** [comment]
Update: The same issue happens within (Neo)Vim.

Thank you!

**Comment by junegunn** [comment]
Sounds like a configuration issue. What's the output of `echo "$FZF_DEFAULT_COMMAND"`?

**Comment by Brixy** [comment]
Thank you!

> What's the output of `echo "$FZF_DEFAULT_COMMAND"`?

`rg --files --hidden --follow --no-ignore-vcs`

You are right. With the default settings the problem described above does not occur.

**Comment by junegunn** [comment]
You might want to examine the output of `env | grep FZF` and see if there's a path hard-coded in one of the variables.

**Comment by Brixy** [comment]
Thank you very much for your help, although it is obviously not an fzf issue!

Output of `env | grep FZF` is

```
FZF_CTRL_T_COMMAND=rg --files --hidden --follow --no-ignore-vcs
FZF_DEFAULT_COMMAND=rg --files --hidden --follow --no-ignore-vcs
FZF_DEFAULT_OPTS=--height=50% --min-height=15 --reverse -e
```

**But, I got it to work:**

In `config.fish` replace

```
cd ~/Desktop/
```

with

```
if status is-interactive
  cd ~/Desktop/
end
```

Thanks again! I am closing this issue. Maybe these fish setting will help somebody.
