### ISSUE TITLE
[BUG] fork/exec invalid argument

### ISSUE THREAD

**Issue by NightMachinary** [junegunn/fzf#2176]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

When I run fzf via https://github.com/Aloxaf/fzf-tab, there is a strange bug with previewing:
![image](https://user-images.githubusercontent.com/36224762/92700684-56fe3180-f364-11ea-816c-4f2c27b14065.png)

I have tried setting `SHELL` to different commands, but the result is the same:
![image](https://user-images.githubusercontent.com/36224762/92700788-78f7b400-f364-11ea-9e99-9580efbc4921.png)

Unfortunately, fzf-tab's setup is rather complex, so I couldn't create a simple reproduction guide, but I thought perhaps you can shed some light on what is going wrong. As far as I understand, no matter the inputs, this `fork/exec /bin/dash: invalid argument` error should not happen?

PS: Obviously `/bin/dash` exists on my system:
```
p38 ❯ /bin/dash -c 'echo hi'
hi

p38 ❯ ll /bin/dash
.rwxr-xr-x 110k root 29 Sep  2019 /bin/dash
```

**Comment by rayiik** [comment]
actually ive been getting that too and not to sure why i know it happens in the preview window when i use {} or {+} but not {q} however i use replace-query it also errors out but not if i type out the query
```bash
fzfcmp () {
    local term
    local FZF_DEFAULT_COMMAND
    FZF_DEFAULT_COMMAND="infocmp $TERM -1"
    term="$(
    infocmp "$TERM" -1 | tr '=' '\n' | \
       tr '\t' '' | \
      sed 's/,$//' | fzf \
      --preview='man terminfo | rg -C10 -e {q}' \
        --preview-window='right:80:wrap' --phony \
        --bind="f9:replace-query+preview:man terminfo | rg -C1 -e {q}" \
            )"

READLINE_LINE="${READLINE_LINE:0:$READLINE_POINT} $(awk -F= '{print $1}' <<<"${term:-''}" \
    | sed 's/,$//') ${READLINE_LINE:$READLINE_POINT}"

    if test -n "$(rg -e 'echo' <<<"$READLINE_LINE")"; then
        READLINE_LINE=$READLINE_LINE; else
READLINE_LINE="echo -e \"$READLINE_LINE\""
    fi

  READLINE_POINT=$(( READLINE_POINT + ${#term} ))
unset term
}
bind -x '"\et": fzfcmp'
```
first preview gives the fork/exec error unless i use {q} and manually type query (tried with all other variations of place holder)

**Comment by junegunn** [comment]
I don't use the project so I can't really answer your question. You might want to ask this on the issue tracker of fzf-tab.

https://github.com/Aloxaf/fzf-tab/issues/77 looks related.

**Comment by rickalex21** [comment]
I am getting this issue as well. The funny thing about it is I'm having the problem on Linux
but not on Mac. When I remove `--null` it goes away. Why is that?

```bash
RG_PREFIX="/usr/bin/env rg --null --line-buffered --sortr=path --color=never "

	echo "R: $RG_PREFIX"

	INITIAL_QUERY="${*:-}"
	echo "Q: $INITIAL_QUERY"
	IFS=: read -ra selected < <(
	  FZF_DEFAULT_COMMAND="$RG_PREFIX $(printf %q "$INITIAL_QUERY")" \
	  fzf --ansi \
		  --color "hl:-1:underline,hl+:-1:underline:reverse" \
		  --disabled --query "$INITIAL_QUERY" \
		  --bind "change:reload:sleep 0.1; $RG_PREFIX {q} || true" \
		  --bind "ctrl-f:unbind(change,ctrl-f)+change-prompt(2. fzf> )+enable-search+clear-query" \
		  --prompt '1. ripgrep> ' \
		  --multi \
		  --delimiter : \
		  --preview 'bat --color=always {1} --highlight-line {2}' \
		  --preview-window 'up,75%,border-bottom,+{2}+3/3,~3' \
          --height "100%"
          # original
		  # --preview-window 'up,60%,border-bottom,+{2}+3/3,~3'
	)
	[ -n "${selected[0]}" ] && $NVIM "${selected[0]}" "+${selected[1]}"
```
