### ISSUE TITLE
How to remove the space in front of the matched content that transfered to sink?

### ISSUE THREAD

**Issue by Delayless** [junegunn/fzf#2177]
Fzf seems to automatically add spaces in front of the matched content, And then transfer it to sink.

```bash
let g:vimspector_json_path=$HOME . "/.config/vimspector_template/"
command! -bang -nargs=* LoadVimSpectorJson call fzf#run({
            \   'source': 'ls ' . vimspector_json_path,
            \   'sink': 'e .vimspector.json | 0r' . vimspector_json_path,
            \   'down': '25%',
            \   'options': '--preview-window=hidden'
            \ })
```
`Vim(read):E484: Can't open file /home/lee/.config/vimspector_template/ python.json`
Error because of the space before the filename `python.json` .
Is there any way to remove this space?

**Comment by junegunn** [comment]
`sink` can be a funcref. So you can implement a custom sink function that reformats the selected line.

```vim
function! TrimAndOpen(line)
  execute 'e' trim(a:line)
endfunction

call fzf#run(fzf#wrap({'sink': function('TrimAndOpen')}))
```
