### ISSUE TITLE
Idea/PR: match (no-sort) & select without filtering

### ISSUE THREAD

**Issue by mcint** [junegunn/fzf#2178]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [x] Mac OS X
    - [x] Windows
    - [x] Etc.
- Shell
    - [x] bash
    - [x] zsh
    - [x] fish
    
## Problem / Steps to reproduce

# Interactive use
fzf defaults are great for selecting a single line from a stream of lines. Filtering on match so far, and sorting on length, continuity of match, etc, makes it easy to iteratively move toward a best match.

## Pattern of capabilities / affordances
Uniquely well, **default** fzf behavior allows interactively sorting & filtering on multiple match attempts to select a line.

Uniquely well, **no-sort** fzf behavior supports maintaining sequential context of the lines while matching lines of a file to select one.

Uniquely well, **multi-select** with **no-sort** fzf behavior supports the same sequential context, with a richer, more meaningful output context (though also causes re-ordering of output based on selection order). _(Is there room for a feature/flag to ensure multi-select output lines retain the same relative order as input lines?)_

Uniquely well, fzf could support a **match without filtering** (convenient with _multi-select_, _no-sort_). Inspired by a workflow of search-and-read in e.g. less (in fzf terms, "match"-and-read), fzf could provide a capability to match patterns without filtering, jump to the matching line, and perform multi-select on and around matched lines (so, everywhere). This behavior would approximate a `less`-based reading of a file, while supporting output selection like `grep -C#`, but allowing interactive, richer selection of context of interest.

## Real-world use case
In my use case, I have a list of tabs, grouped by window, and in practical terms, they're grouped by topic relevance of the linked content. In order to select specific tabs of interest, and arbitrary groupings of neighboring tabs, `fzf` seems like it should be the right tool, because, unlike `grep`, it allows keypress-interactive filtering, and unlike `less`, it allows selection of lines to output. However I can't quite get the behavior I want from `fzf`.

# Question
Am I missing anything about the how fzf is written, or the limitations of conflicting with existing keyboard shortcuts and interactive commands in use?

Could some other feature help accomplish my goal, this interactive filtering?

Could fzf allow specifying separate filter-strings and sort-strings? Could it support separate match-strings to allow search-result-based navigation through filtered and sorted lines (in addition to arrows & cursor)?

Could regex (or some subset) be supported by fzf? (On filter or match strings)

**Comment by junegunn** [comment]
Thanks for the detailed suggestion. I can imagine this can be useful in certain scenarios, but fzf wasn't really designed for the use case. Implementing this new mode on fzf will require a major overhaul and make the code much more complicated, and I don't think it's worth it. I prefer to keep fzf simple and small. Making it a one-size-fits-all solution for a wide variety of problems is not my goal.

FWIW, I would consider using Vim, instead of less, for your problem, as you can implement any behavior you want with VimScript and you can leverage its builtin regex search functionality.

**Comment by GGCristo** [comment]
[Not related with FZF]
@mcint Did you find something?, I am seeking for the same behavior.
