### ISSUE TITLE
Making Alt-c begin at ~ rather than current dir?

### ISSUE THREAD

**Issue by ezuk** [junegunn/fzf#218]
Hi there,

Trying to [customize this](https://github.com/junegunn/fzf/blob/master/shell/key-bindings.fish#L35) so that Alt-c starts searching through directories relative to ~ rather than the current directory. Not quite sure how to go about it though... 

Any advice? Thank you!

**Comment by junegunn** [comment]
Start from replacing `find .` with `find ~`, the rest is basic shell scripting.

**Comment by mb720** [comment]
I too wanted to search from a custom directory. I added this function to my by `.bashrc`:

    fzf_cd () {
      local start_dir=$(realpath "$1")
      start_dir_len=${#start_dir}
      # Remove the start dir, only show sub dirs in fzf
      cut_start=$(( start_dir_len + 2 ))
      sub_dir=$(find -L $start_dir -type d |cut -b${cut_start}- | fzf")
      cd "$start_dir/$sub_dir"
    }

In Bash, I call it with `fzf_cd ~/.config` for example.

I also added a preview with the directory's content, toggleable with `?`:

    ... | fzf --bind "?:toggle-preview" --preview "tree -C $start_dir/{} | head -200")
