### ISSUE TITLE
feature request: preview window cycle / horizontal scroll

### ISSUE THREAD

**Issue by rayiik** [junegunn/fzf#2182]
- [ x I have read through the manual page (`man fzf`)
- [ x I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

Hey, so there are times when Im looking for specific things in config files and occasionally ill get output on a command (one line) that doesn't wrap or I know that is either at the top or somewhere near the bottom and I just thought it would be nice if instead of having to page down through 9000 lines of code I could just pop go up 2/3 pages using cycle or to the right a bit to see the line that didn't wrap.

**Comment by junegunn** [comment]
Added `--preview-window cycle` option. I decided not to implement horizontal scrolling as it's non-trivial. You might want to use `toggle-preview-wrap` action instead if you want to see past the right end of the window.

**Comment by rayiik** [comment]
Hey thanks yea was more interested In the cycle I had it on but for the use case it messed with the formatting was more of a niche request the second part but thanks 👍
