### ISSUE TITLE
Updating prompt line with the current selected candidate

### ISSUE THREAD

**Issue by EgorDuplensky** [junegunn/fzf#2185]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

I have implemented a function for searching over command arguments from bash history

```bash
#!/usr/bin/env bash
# fzf command line arguments (cla) history

FZF_CLA_HIST_SIZE=10
: "${FZF_CLA_DEFAULT_FZF_OPTS=${FZF_DEFAUL_OPTS}}"

function __fzf_cla_hist {
    local hist_buff=$(history | sed -n "${FZF_CLA_HIST_SIZE},$((${FZF_CLA_HIST_SIZE} - 1))p" | cut -d" " -f4- | tr ' ' '\n')
    local rl_prefix_substr=${READLINE_LINE:0:((${READLINE_POINT}))}
    local rl_suffix_substr=${READLINE_LINE:${READLINE_POINT}}

    # FZF_CLA_DEFAULT_FZF_OPTS="${FZF_DEFAUL_OPTS} --preview='setenv READLINE_LINE=${rl_prefix_substr}{}${rl_suffix_substr}' --preview-window hidden"

    local res_arg=$(echo -e "${hist_buff}" | FZF_DEFAUL_OPTS=${FZF_CLA_DEFAULT_FZF_OPTS} fzf)
    ((READLINE_POINT += ${#res_arg}))
    READLINE_LINE="${rl_prefix_substr}${res_arg}${rl_suffix_substr}"
}

bind -x '"\es":__fzf_cla_hist'
```
I wonder if it is possible to keep the current prompt line (like `cd **` does) and update it while iterating over candidates.
I guess updating READLINE_LINE using _--preview_ won't help here since it is already a forked process at this point.

**Comment by rayiik** [comment]
hey i think i know what your question is but just to clarify you want to take the readline_line (your initial input before the bind)  as the starting query for your search?  or are you looking to have it returned after your search is complete

**Comment by junegunn** [comment]
I haven't been able to find a way to keep the current prompt line when using `-x` bindings of bash 4+. CTRL-T and CTRL-R from `key-bindings.bash` also have the same problem, unlike ALT-C which is not an `-x` binding.
