### ISSUE TITLE
[Q] How does fzf determine if it should read from stdin or not?

### ISSUE THREAD

**Issue by NightMachinary** [junegunn/fzf#2187]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish
    
## Question

I am curious how fzf determines if it should read from stdin or run `FZF_DEFAULT_COMMAND`.

**Comment by rayiik** [comment]
hey so as i understand it (and i could be off and im sure someone will give a clearer answer) but this is less of a fzf and more of a shell/os determined but everything in Linux/Osx is a file there are 3 common file descriptors standard out standard in standard out and standard error  fd0 fd1 fd2 (file descriptor) with binary on-off. your shell can open and close these channels and the have predefined defaults but generally, your shell can override and change the flow direction with actions such as piping and redirecting so if standard in on fzf is closed it will read from the default command
![image](https://user-images.githubusercontent.com/32557211/93706714-bdf6b580-fadd-11ea-819d-8401f8afdc0e.png)
is my understanding

**Comment by mohkale** [comment]
Also worth mentioning most languages have a function `isatty` to determine whether a file descriptor (stdin,stdout,stderr) is an interactive tty or a regular stream (such as a file). I presume `fzf` uses that at startup to tell whether to read stdin or run FZF_DEFAULT_COMMAND.

**Comment by rayiik** [comment]
Didn’t know about isatty thanks :)
