### ISSUE TITLE
Color issue only when opening file directly from file manager

### ISSUE THREAD

**Issue by joe23rep** [junegunn/fzf#2188]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

i have issues with the colorscheme for fzf. i use fzf mostly in neovim in floating mode. ive set the colors i want to use in my .zshrc file. the syntax theme for example for :Rg or :Lines is generated threw bat (i think. i actually installed bet for ranger but fzf seems to go with it too). so when im opening my terminal and open files in vim and then use fzf its totally fine. 

however- when im opening files from my gui filemanager (dolphin) fzf changes its colors. it uses different colors for the little arrows and stuff but also uses a completely different colorscheme for the syntax. 

files get opened automatically via neovim threw a .desktop file i created for neovim. it uses the flags nvim %F

i tried setting the colors not only in my .zshrc but also manually in my fzf config file. i also tried adding --colors ... to the command i open fzf with. 

tried setting the init.vim to "set no termguicolors". i also tried opening it via different terminal emulators. 

its not a big issue but it always enoys me a little bit when im having everything in a nice color scheme and then i open fzf and it sticks out like a sore thumb. do you know if theres something else i could try?

**Comment by joe23rep** [comment]
here my fzf config:

`" FZF ---------------------------------------------------------------------------------------
"   _____ __________    ____             __ _
"  |  ___|__  /  ___|  / ___|___  _ __  / _(_) __ _
"  | |_    / /| |_    | |   / _ \| '_ \| |_| |/ _` |
"  |  _|  / /_|  _|   | |__| (_) | | | |  _| | (_| |
"  |_|   /____|_|      \____\___/|_| |_|_| |_|\__, |
"                                             |___/


let $FZF_DEFAULT_COMMAND = 'rg --files --ignore-case --hidden -g "!{.git,node_modules,vendor}/*"'


" Fzf statusbar config (lightline style)
" function! s:fzf_statusline()
"     " setlocal statusline=%#fzf1#\ \ %#fzf2#fzf%#fzf3#
" endfunction
"
" autocmd! User FzfStatusLine call <SID>fzf_statusline()
"
" " Colors for fzf statusbar
" hi fzf1 guifg=#292c33  guibg=#00eeff
" hi fzf2 guifg=#292c33  guibg=#00eeff
" hi fzf3 guifg=#00eeff  guibg=#292c33


" Add vim directory for shortcutting
command! -bang Vim call fzf#vim#files('~/.vim', <bang>0)


" All files
command! -nargs=? -complete=dir AF
            \ call fzf#run(fzf#wrap(fzf#vim#with_preview({
            \   'source': 'fd --type f --hidden --follow --exclude .git --no-ignore . '.expand(<q-args>)
            \ })))

let g:fzf_colors =
            \ { 'fg':      ['fg', 'Normal'],
            \ 'bg':      ['bg', 'Normal'],
            \ 'hl':      ['fg', 'Conditional'],
            \ 'fg+':     ['fg', 'CursorLine', 'CursorColumn', 'Normal'],
            \ 'bg+':     ['bg', 'CursorLine', 'CursorColumn'],
            \ 'hl+':     ['fg', 'Statement'],
            \ 'info':    ['fg', 'PreProc'],
            \ 'border':  ['fg', 'Comment'],
            \ 'prompt':  ['fg', 'Conditional'],
            \ 'pointer': ['fg', 'Exeption'],
            \ 'marker':  ['fg', 'Keyword'],
            \ 'spinner': ['fg', 'Label'],
            \ 'header':  ['fg', 'Comment'] }

" Terminal buffer options for fzf
autocmd! FileType fzf
autocmd  FileType fzf set noshowmode noruler nonu


" Hide status bar while using fzf commands
if has('nvim') || has('gui_running')
  autocmd! FileType fzf
  autocmd  FileType fzf set laststatus=0 | autocmd WinLeave <buffer> set laststatus=2
endif


command! -bang -nargs=? -complete=dir Files
            \ call fzf#vim#files(<q-args>, fzf#vim#with_preview(), <bang>0)

command! -bang -nargs=* Ag
            \ call fzf#vim#ag(<q-args>,
            \                 <bang>0 ? fzf#vim#with_preview('up:60%')
            \                         : fzf#vim#with_preview('right:50%:hidden', '?'),
            \                 <bang>0)


function! s:plug_help_sink(line)
    let dir = g:plugs[a:line].dir
    for pat in ['doc/*.txt', 'README.md']
        let match = get(split(globpath(dir, pat), "\n"), 0, '')
        if len(match)
            execute 'tabedit' match
            return
        endif
    endfor
    tabnew
    execute 'Explore' dir
endfunction

command! PlugHelp call fzf#run(fzf#wrap({
            \ 'source': sort(keys(g:plugs)),
            \ 'sink':   function('s:plug_help_sink')}))

" RipGrep-----------------------------------------------------------------------------------------

" Get text in files with Rg
command! -bang -nargs=* Rg
  \ call fzf#vim#grep(
  \   'rg --column --line-number --no-heading --color=always --smart-case '.shellescape(<q-args>), 1,
  \   fzf#vim#with_preview(), <bang>0)

" Ripgrep advanced
function! RipgrepFzf(query, fullscreen)
  let command_fmt = 'rg --column --line-number --no-heading --color=always --smart-case %s || true'
  let initial_command = printf(command_fmt, shellescape(a:query))
  let reload_command = printf(command_fmt, '{q}')
  let spec = {'options': ['--phony', '--query', a:query, '--bind', 'change:reload:'.reload_command]}
  call fzf#vim#grep(initial_command, 1, fzf#vim#with_preview(spec), a:fullscreen)
endfunction

command! -nargs=* -bang RG call RipgrepFzf(<q-args>, <bang>0)

" Git grep
command! -bang -nargs=* GGrep
  \ call fzf#vim#grep(
  \   'git grep --line-number '.shellescape(<q-args>), 0,
  \   fzf#vim#with_preview({'dir': systemlist('git rev-parse --show-toplevel')[0]}), <bang>0)


" Floating------------------------------------------------------------------------

fu s:snr() abort
    return matchstr(expand('<sfile>'), '.*\zs<SNR>\d\+_')
endfu
let s:snr = get(s:, 'snr', s:snr())
let g:fzf_layout = {'window': 'call '..s:snr..'fzf_window(0.9, 0.6, "Type")'}
" let g:fzf_layout = {'window': 'call '..s:snr..'fzf_window(0.9, 0.6, "Boolean")'}

fu s:fzf_window(width, height, border_highlight) abort
    let width = float2nr(&columns * a:width)
    let height = float2nr(&lines * a:height)
    let row = float2nr((&lines - height) / 2)
    let col = float2nr((&columns - width) / 2)
    let top = '┌' . repeat('─', width - 2) . '┐'
    let mid = '│' . repeat(' ', width - 2) . '│'
    let bot = '└' . repeat('─', width - 2) . '┘'
    let border = [top] + repeat([mid], height - 2) + [bot]
    if has('nvim')
        let frame = s:create_float(a:border_highlight, {
            \ 'row': row,
            \ 'col': col,
            \ 'width': width,
            \ 'height': height,
            \ })
        call nvim_buf_set_lines(frame, 0, -1, v:true, border)
        call s:create_float('Normal', {
            \ 'row': row + 1,
            \ 'col': col + 2,
            \ 'width': width - 4,
            \ 'height': height - 2,
            \ })
        exe 'au BufWipeout <buffer> bw '..frame
    else
        let frame = s:create_popup_window(a:border_highlight, {
            \ 'line': row,
            \ 'col': col,
            \ 'width': width,
            \ 'height': height,
            \ 'is_frame': 1,
            \ })
        call setbufline(frame, 1, border)
        call s:create_popup_window('Normal', {
            \ 'line': row + 1,
            \ 'col': col + 2,
            \ 'width': width - 4,
            \ 'height': height - 2,
            \ })
    endif
endfu

fu s:create_float(hl, opts) abort
    let buf = nvim_create_buf(v:false, v:true)
    let opts = extend({'relative': 'editor', 'style': 'minimal'}, a:opts)
    let win = nvim_open_win(buf, v:true, opts)
    call setwinvar(win, '&winhighlight', 'NormalFloat:'..a:hl)
    return buf
endfu

fu s:create_popup_window(hl, opts) abort
    if has_key(a:opts, 'is_frame')
        let id = popup_create('', #{
            \ line: a:opts.line,
            \ col: a:opts.col,
            \ minwidth: a:opts.width,
            \ minheight: a:opts.height,
            \ zindex: 50,
            \ })
        call setwinvar(id, '&wincolor', a:hl)
        exe 'au BufWipeout * ++once call popup_close('..id..')'
        return winbufnr(id)
    else
        let buf = term_start(&shell, #{hidden: 1})
        call popup_create(buf, #{
            \ line: a:opts.line,
            \ col: a:opts.col,
            \ minwidth: a:opts.width,
            \ minheight: a:opts.height,
            \ zindex: 51,
            \ })
        exe 'au BufWipeout * ++once bw! '..buf
    endif
endfu

"------------------------------------------------------------------------------
`

**Comment by rayiik** [comment]
hey  so ive tried opening it several different ways and haven't been able to reproduce (with my setup) but i tried using dolphin with Konsole tried extra term terminus terminator opening both into nvim and with nvim -c ':FZF' (even tried using visual studio code console) i can think of maybe two reasons why this is for some reason your setting different "TERM" values in your two instances or setting different filetypes (in vim)  id check thous, but id also consider setting my default fzf values externally from nvim (which might be why it doesnt change on mine Screenshot_2020-09-21_17-22-32
```bash
#!/bin/bash
export FZF_MOVEMENT="--bind='ctrl-s:preview-page-down' \
	--bind='ctrl-a:preview-page-up' \
	--bind='ctrl-u:half-page-up+refresh-preview' \
	--bind='alt-u:page-up+refresh-preview' \
	--bind='ctrl-d:half-page-down+refresh-preview' \
	--bind='alt-d:page-down+refresh-preview' \
  --bind='alt-y:yank' \
  --bind='ctrl-y:kill-line' \
  --bind='alt-g:ignore' \
  --bind='ctrl-g:top' \
	--bind='alt-a:toggle-all' \
  --bind='alt-s:toggle-sort' \
  --bind='alt-h:backward-char+refresh-preview' \
  --bind='alt-l:forward-char+refresh-preview' \
  --bind='ctrl-l:clear-screen'"
 export FZF_DEFAULT_COMMAND="rg -uu \
  --files \
  -H"
export FZF_ALT_COMMAND="fd -uu -t f"
export FZF_PREVIEW="nvimpager {}"
export FZF_DEFAULT_OPTS="$FZF_MOVEMENT \
	--bind='ctrl-h:execute(moreman {})' \
  --bind='ctrl-p:toggle-preview' \
  --bind='ctrl-v:execute(nvimpager {})' \
  --bind='f8:preview(nvimpager {})'
  --bind='f9:preview(moreman {} 2>/dev/null)' \
	--tiebreak='length,index' \
  --preview-window 'right:68:wrap'
  --height=100
	--exact \
	--info='inline' \
	--cycle \
  --reverse \
	--multi \
	--ansi"
if [[ -z "$DISPLAY" ]]; then
  FZF_DEFAULT_OPTS+="
	--color=info:#ffff00 \
  --color=prompt:#808080\
  --color=pointer:#c0c0c0 \
  --color=hl+:#ff00ff \
	--color=marker:#14f73e \
  --color=spinner:#ff0000 \
  --color=header:#0fffd7 \
  --color=border:#800000 \
  --color=hl:#000080 \
	--color=preview-fg:#22f040 \
  --color=preview-bg:-1 \
  --color=fg:-1 \
	--color=fg+:#000080 \
  --preview='${FZF_PREVIEW:+"cnat; $FZF_PREVIEW"}'";
    else
      source .fzfguirc
fi
```

**Comment by rayiik** [comment]
missed the part where you said you'd tried in your .zshrc sry

**Comment by joe23rep** [comment]
yeah- that was the first thing i did and that works great when im opening a terminal and then open neovim. however- as soon as i directly open the file from dolphin via neovim in my terminal (no matter which terminal i set it too) it seems to not read the config. wether the config in the zshrc file or the (basically same config) in my fzf.config file which automatically gets sourced by my init.vim. 

i know it reads the file cause i once copied the keybindings into that file to test it. 

it just doesnt seem to interpret the color settings.

**Comment by rayiik** [comment]
Try opening nvim from dolphin run :scriptname? Will list all sourced .vim files in the order they’re called then compare against a regular opening  Can’t remember if you need the ? But also what just my fzf setup I also have a repgrepconf

**Comment by rayiik** [comment]
sorry command is :scriptnames 
no ? but will print all your .vim files and where theyr'e soured from if you compare the two and theyre different then thats most likely the issue if not we can exclude nvim (aslo compare :set filetype)

**Comment by joe23rep** [comment]
they indeed source different files. they both source the files with the fzf config in it and all other config files i created. 

up too the 96th file theyre identical. then the differences start. in the end the number both source is also different. the neovim version opened in the terminal source 121 files. the one opened out of dolphin directly sources 116 files. its missing for example:

~/.vim/plugged/vim-polyglot/autoload/sleuth.vim

or 2 files from gitgutter. 

do u know the reason why its sourcing less files than the terminal version?

i have the gut feeling is based on the flags i use in my neovim.desktop file i created. it starts tliix with neovim opened using this command:

tilix -e nvim %f 

i also tried 

tilix -e nvim %F

do u know the reason why its sourcing less files than the terminal version?

i have the gut feeling is based on the flags i use in my neovim.desktop file i created. it starts tliix with neovim opened using this command:

tilix -e nvim %f 

i also tried 

tilix -e nvim %F

do u know the reason why its sourcing less files than the terminal version?

i have the gut feeling is based on the flags i use in my neovim.desktop file i created. it starts tliix with neovim opened using this command:

tilix -e nvim %f 

i also tried 

tilix -e nvim %F


but maybe im wrong. what i wonder tho- the .zshrc file wasnt in the list of sourced files. yet fzf sources the bat theme declared in my zshrc file when im opening neovim from the terminal. maybe since the colors and bat theme are declared in the zshrc file, it doesnt work since the tilix/ neovim .desktop application doesnt source the zshrc file while the terminal does source it once it is opened automatically so nvim doesn have to source it. would there be the possiblity to force the .desktop application to source the .zshrc file first?

or would it be possible to add something to the shortcut which opens fzf (inclusive :Lines :Rg :History etc)? in the describiton they write that we shouldnt do that.

**Comment by rayiik** [comment]
yea no idea but its interesting I believe that's where your problem might be but what you can do is go through those extra files and manually source the files you need at the end of the last one in dolphin add them 1 at a time but with conditions and your RC isn't sourced by vim the environment is already set it just builds on top (being a child process it inherits the environment and moves from that point). Try to find a variable that's only set when you open with dolphin and conditionally source the missing .vim files one at a time (you may ad one and it finishes the chain and fixes the problem) :)

**Comment by rayiik** [comment]
let me know if you find a solution or the cause :)

**Comment by rayiik** [comment]
Hmn you might want to try testing or forcing an interactive shell or login shell because that would change your load order of your scripts as im not sure if your file manager opens a login shell

**Comment by junegunn** [comment]
What is the output of `:echo $TERM` 1. when you start Neovim on your terminal, 2. and when you start it using your GUI tool?
