### ISSUE TITLE
FZF_DEFAULT_COMMAND resets on shell startup

### ISSUE THREAD

**Issue by 12-Seconds** [junegunn/fzf#2192]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

When using `export FZF_DEFAULT_COMMAND`, it resets on shell startup. For example, running `export FZF_DEFAULT_COMMAND='ag -g ""'` will work for the rest of the terminal session, but in the next terminal session, running `echo $FZF_DEFAULT_COMMAND` gives `rg --files --hidden`.

**Comment by junegunn** [comment]
Closing as this is not an issue of fzf but a generic question on shell behavior.

You might want to ask the question on https://unix.stackexchange.com/

**Comment by rayiik** [comment]
Hey so how are you using export? At the command line or In your .zshrc basically any environments variable you run on the cmd line is set per session and is only Available  to child processes (Command you run under your init file like a tree it connects downwards) when you restar it’s like generating a new tree if you want to keep the process it needs to be in your startup fia (for loca user your ~/.zshrc) it gets called at start up and then every process infer that will have the variable

**Comment by 12-Seconds** [comment]
I put it in my .zshrc, but I figured it out. There was another line that was changing FZF_DEFAULT_COMMAND, so I just removed that line, and it now works.

**Comment by rayiik** [comment]
Excellent thanks for posting your solution too
