### ISSUE TITLE
nothing with the TAB key works

### ISSUE THREAD

**Issue by nishantpratimdas** [junegunn/fzf#2199]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish
    
## Problem / Steps to reproduce
I have tried it on st, termite and alacritty with a vanilla bashrc. The output of complete | grep _fzf is empty. I installed through pacman.

**Comment by rayiik** [comment]
Hey could I get you to share your solution if you found one so others searching past topics can possibly get an answer if they have the same question?

**Comment by nishantpratimdas** [comment]
Yeah sure. It was completely my fault. I somehow overlooked this line: _Shell extensions (key bindings and fuzzy auto-completion) and Vim/Neovim plugin may or may not be enabled by default depending on the package manager. Refer to the package documentation for more information._

It's (very clearly) stated in the [archwiki](https://wiki.archlinux.org/index.php/fzf) that we have to source key-bindings.bash and completion.bash in our bashrc. After doing so, I had no trouble. I apologise for any inconvenience caused.
