### ISSUE TITLE
Error when updating fzf in vim

### ISSUE THREAD

**Issue by Linuus** [junegunn/fzf#220]
Hi!

I just updated fzf from vim, using vim-plug and got this error:
```
Error detected while processing /Users/linus/.fzf/plugin/fzf.vim:
line  211:
E706: Variable type mismatch for: s:launcher
```

Is this a known issue?

**Comment by junegunn** [comment]
Ah, yes, the type of the variable was recently changed. vim-plug reloads the plugin file after update, and in your case the variable was already defined as another type in the session, thus the error. It's a one-time error. But I'll make sure that the other users will not run into it. Thanks.

**Comment by Linuus** [comment]
Cool, thanks!
