### ISSUE TITLE
[BUG] fzf-tmux doesn't work when invoked from a noninteractive shell

### ISSUE THREAD

**Issue by NightMachinary** [junegunn/fzf#2201]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

1. Run `tmux new  bash -c 'echo 1 2 3 | fzf-tmux -p90'`. It exits without showing the popup. Running `eval 'echo 1 2 3 | fzf-tmux -p90'` on an interactive shell works as expected.

**Comment by junegunn** [comment]
Does `tmux new bash -c 'echo 1 2 3 | fzf-tmux -p90%'` work? (`90%` instead of `90`)

**Comment by NightMachinary** [comment]
[**@junegunn**](https://github.com/junegunn) commented on [Oct 5, 2020, 5:10 PM GMT+3:30](https://github.com/junegunn/fzf/issues/2201#issuecomment-703639534 "2020-10-05T13:40:31Z - Replied by Github Reply Comments"):
> Does `tmux new bash -c 'echo 1 2 3 | fzf-tmux -p90%'` work? (`90%` instead of `90`)  
> fzf-tmux may fail if the specified width and height exceed the actual screen size.

Seems to work. Thanks!
