### ISSUE TITLE
Execute files using fzf

### ISSUE THREAD

**Issue by Chaoticsys101** [junegunn/fzf#2202]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [ ] Mac OS X
    - [x] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish
    - [x] cmd (I use Windows, but I have access to bash sometimes) 

## Problem / Steps to reproduce
Is there an easy way to use fzf to execute the selected file? I think that would be a nice additional feature, a very useful one.

**Comment by rayiik** [comment]
What do you mean by execute? Because preview window generated its preview by executing the file and displaying the output and there’s the —bind=“execute:command {}” you can also do.
```Bash
Choice=“$(fd -t f . ./ | fzf)”
Eval”$Choice”
```

**Comment by Chaoticsys101** [comment]
I meant for example a video file. I search for it and then I want to play it.

**Comment by rayiik** [comment]
Here you go wrote this up and tested (works on mine) uses fd-find (rust rewrite of find) and ripgrep (rust rewrite of grep) but you can sub those out for find and grep if you prefer or ag or any search / filter command)
```bash
 FILE: vid.sh
#
#         USAGE: ./vid.sh
#
#         DESCRIPTION:
#
#         OPTIONS: ---
#         REQUIREMENTS: ---
#         BUGS: ---
#         NOTES: ---
#         AUTHOR: Rayiik (), dsimon_aas@hotmail.com
#         ORGANIZATION:
#         CREATED: 10/07/2020 10:53:50 AM
#         REVISION:  ---
#===============================================================================
vidvar="$1"
export vidvar
_TF='true'
echo "$_TF"
export _TF
truefalse () {
if [[ "$_TF" == 'true' ]];
then
    _TF='false';
        else
    _TF='true'
fi
echo "$_TF"
export _TF
   }


vidmain () {
    local choice
choice="$(fd -uu -t f -d 5 "${vidvar=-'.'}" | fzf)"
    echo "$_TF"
while [[ "$_TF" == 'true' ]]; do
    vlc "$choice" && disown -a &
    truefalse
done
unset _TF
unset choice
}
vidmain
```
first argument is your search query and runs from your current working directory i tested with mkv and mp4 as an example but when i have time ill update to add more video types in a single search and targeted directory search

**Comment by Chaoticsys101** [comment]
Thanks that's awesome!
