### ISSUE TITLE
fzf --preview-window hidden cannot be overwritten since 0.23.0

### ISSUE THREAD

**Issue by edi9999** [junegunn/fzf#2203]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

Hello,

I have been using the following FZF_DEFAULT_OPTS to have the preview-window hidden for most commands : 

```
FZF_DEFAULT_OPTS="--preview-window 'up:50%:hidden' --bind='?:toggle-preview'"
```

However, on some commands, I want to have the preview-window visible, so I was running : 

```
fzf --preview 'less <<< {}'  --preview-window 'down:50%'
```

In previous versions (fzf 0.22.0 for example), this made the preview window visible by default.

However, with version 0.23.0, it seems that the hidden parameter of the FZF_DEFAULT_OPTS can't get overwritten anymore.

**Comment by junegunn** [comment]
I see. It doesn't make much sense to keep `hidden` on a new `--preview-window`.

**Comment by junegunn** [comment]
Hmm, I'm not sure if it was the right approach. I'll just revert the change and add something like `nohidden`, so you can override it.

**Comment by edi9999** [comment]
What do you think about using "visible" instead of nohidden ?

**Comment by junegunn** [comment]
`visible` is fine for `hidden`, but we also need extra no-flags for `wrap` and `cycle`. So let's not expand the vocabulary.
