### ISSUE TITLE
Add "reload-cycle" action for cycling the source in dynamically updated input list

### ISSUE THREAD

**Issue by cibinmathew** [junegunn/fzf#2204]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [ ] fish
    
## Problem / Steps to reproduce
**Feature Request**
Would it be possible to add a functionality to cycle through the list of sources using a single key binding. Existing functionality #1750

eg: 
`
find . -type f |
  fzf --bind 'ctrl-d:reload-cycle(find . -type d; find . -type f; find .; source#n)'
`

Instead of separate key for each like below
`
find . -type f |
  fzf --bind 'ctrl-d:reload(find . -type d),ctrl-f:reload(find . -type f)'
`

list of sources could be delimited.

**Comment by junegunn** [comment]
I'm not going to add this to fzf because we can write a script that cycles through a list of commands by keeping its own state in an external file.

```sh
rm -f /tmp/script-state
my-script /tmp/script-state | fzf --bind 'ctrl-d:reload:my-script /tmp/script-state'
```

**Comment by cibinmathew** [comment]
Thanks @junegunn 
Does it make sense to add these snippets to wiki examples.
