### ISSUE TITLE
Feature request: Select multiple items multiple times

### ISSUE THREAD

**Issue by gergelyk** [junegunn/fzf#2207]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [x] Mac OS X
    - [x] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [x] zsh
    - [x] fish
    
## Problem / Steps to reproduce

I have come across [use cases](https://github.com/casey/just/issues/699) where it would be great to have an option of selecting items multiple times. I imagine displaying a window that would show currently created list of items (possibly with duplicates). E.g.:

`$ ls / | fzf --multi-with-duplicates`

![image](https://user-images.githubusercontent.com/11185582/95667503-67721980-0b67-11eb-9a81-c789df455730.png)

Additional features to consider:
- key binding for removing last item(s) from created list
- preventing highlight from proceeding to the following item after selecting highlighted item with <TAB>

**Comment by gergelyk** [comment]
Ok, it seems that my [use case](https://github.com/casey/just/issues/699) is not valid any more. Please consider this feature request with lower priority then.

**Comment by junegunn** [comment]
I'm going to close this as I'd like to keep the execution model of fzf as simple as it is now, an interactive Unix filter. If there's anyone who's still interested in this feature, please leave a comment describing your use case.
