### ISSUE TITLE
How to display an array as as a list

### ISSUE THREAD

**Issue by davoudarsalani** [junegunn/fzf#2209]
- [ ] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish
    
## Problem / Steps to reproduce
Say we have this array:
items=("aa" "bb" "cc" "dd")

When piped to fzf with echo ${items[@]} | fzf, the array is displayed in a single line. How can it be piped in a way each item is dispayed in a single line?

Also, this is what I have in my .bashrc:
export FZF_DEFAULT_COMMAND='find $HOME -type f ! -path "*/.git/*" ! -path "*/kaddy/*"'
export FZF_DEFAULT_OPTS='--no-bold --cycle --border=horizontal --prompt=: --marker=+ --height 70% --ansi --preview-window noborder:right:60% --bind backward-eof:abort,ctrl-k:preview-up,ctrl-j:preview-down,ctrl-w:toggle-preview,shift-tab:select-all --multi --layout=reverse --inline-info --color 'fg:#bbc7c9,fg+:#2988bc,hl+:#00cd00,hl:#00cd00,bg:#000000,bg+:#000000,preview-bg:#000000,border:#98971a,gutter:#000000,header:#b300b2''

**Comment by edi9999** [comment]
You could use printf for that, like this : 

```
items=("aa" "bb" "cc" "dd")
printf "%s\n" "${items[@]}"
```

**Comment by rayiik** [comment]
PrintF is almost always better than echo however dose your editor throw a flag useless echo? You should be able to do 
```bash
Fzf <<<${array[@]}
```
Should work as herestings as I understand it don’t technically generate a sub process this should be a more consistent result but if you really want to echo to pipe I’d recommend this if your getting one line result
```bash
Echo “${array[@]}” |  td ‘\s’ ‘\n’ | fzf
```
But if you want to know more about why you should use avoids echo if possible, https://webcache.googleusercontent.com/search?q=cache:YIJ_AGSai6UJ:https://www.infosecmatter.com/terminal-escape-injection/+&cd=7&hl=en&ct=clnk&gl=ca&client=safari the other concept is called shell shock

**Comment by junegunn** [comment]
This is not a question specific to fzf.

**Comment by davoudarsalani** [comment]
There is actually no preference.
Both printf "%s\n" "${items[@]}" and Fzf <<<${items[@]} did the job.
Thanks.

**Comment by QiangZiBro** [comment]
Solution:
```bash
items=("aa" "bb" "cc" "dd")
choice=$(printf "%s\n" "${items[@]}" | fzf)
echo "Your choice is $choice"
```
