### ISSUE TITLE
Feature request: highlighting the input 

### ISSUE THREAD

**Issue by sucrecacao** [junegunn/fzf#2210]
- [X] I have read through the manual page (`man fzf`)
- [X] I have the latest version of fzf
- [X] I have searched through the existing issues

## Info

- OS
    - [X] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [X] zsh
    - [ ] fish
    
## Feature

The global feature would be to add special highlight ( change color and/or add a character before the file name ) to some input regarding a certain rule.

This would help the user differentiate the input instantly.

#### example when using fzf with `ls | fzf`:

 - Adding  a `📄` character in next to file ending with `.txt`
 - Changing the color to dark grey if the file is listed in the gitignore. 

## implementation

It could look like:

` fzf --highlight 'if(echo {} | grep ".txt"):suffix=📄'  `

of 
` fzf --highlight 'if(cat .gitignore | grep {}):color=darkgrey'  `

meaning: 
if `cat .gitignore | grep {}` return good exit code ( `0` ), change the color of the given input to darkgrey. ( else do nothing )

## use cases

This would empowered application using fzf for more that a simple filter, like forgit.

With gitui ( https://github.com/extrawurst/gitui) you can press `enter` on a file to add it to the stage, or `i` to add it to the gitignore, which is very useful. 

This could be done easily with fzf with the following command:

`git add $( ls | fzf --bind 'ctrl-i:execute-silent( echo {} >> .gitignore )+reload(ls)' --highligh 'if(cat .gitignore | grep {}):color=darkgray+suffix=[i]`

**Comment by junegunn** [comment]
Formatting can be done outside of fzf, and we recommend that you do so with specialized programs that are far more capable than fzf in that regard.

```sh
FZF_DEFAULT_COMMAND="ls | my-cool-formatter" \
  fzf --bind 'ctrl-i:execute-silent( echo {} >> .gitignore )+reload($FZF_DEFAULT_COMMAND)' 
```
