### ISSUE TITLE
Documentation: Highlight key bindings not always installed

### ISSUE THREAD

**Issue by rr326** [junegunn/fzf#2211]
- [x ] I have read through the manual page (`man fzf`)
- [x ] I have the latest version of fzf
- [x ] I have searched through the existing issues

## Info

- OS
    - [ x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ x] zsh
    - [ ] fish
    
## Problem / Steps to reproduce
I installed this with `sudo apt-get install fzf` on my raspberry pi. It partially worked but Ctrl-R didn't . I searched, gave up, searched again, etc, and finally spent a while until I tracked it down. In your instructions there IS a line that says "Shell extensions (key bindings and fuzzy auto-completion) and Vim/Neovim plugin may or may not be enabled by default depending on the package manager. Refer to the package documentation for more information." So it's definitely there. 

But there are a LOT of instructions and many people might be like me and not see that and have a half-working install. 

So three easy suggestions:
1. Bold it
2. Have a separate section:
    ### Key Bindings Not Working? 
    Shell extensions (key bindings and fuzzy auto-completion) and Vim/Neovim plugin may or may not be enabled by default 
    depending on the package manager. 
    Do this to add keybindings manually:
    x,y,z

3. Add an `fzf-install` command that installs keybindings. (I reran the install package, per an issue suggestion, and it obviously didn't fix it.)

**Comment by junegunn** [comment]
Thanks, I have updated the documentation.
