### ISSUE TITLE
Preview loading

### ISSUE THREAD

**Issue by p-kolacz** [junegunn/fzf#2212]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [x] zsh
    - [x] fish
    
## Problem / Steps to reproduce

While a preview script/command is executing, preview from previous item is displayed. I'm assuming it's because fzf is waiting for script to execute and then echoes its output? Is it possible to show some "loading" indicator until preview script finishes (for example, quering database or caching remote data)?

**Comment by edi9999** [comment]
Yes, I agree with @p-kolacz , this would be a good improvement : 

When testing with the following : fzf --preview 'bash -c "echo $RANDOM; sleep 2; echo $RANDOM"'

You can see that the preview screen waits for the 3 commands to run to update the screen.

I think it would be cool to show the data as it appears (with some loading indicator indicating that the full command has not exited yet).
