### ISSUE TITLE
Allow multiline elements in selection list

### ISSUE THREAD

**Issue by expipiplus1** [junegunn/fzf#2216]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
- Shell
    - [x] zsh
    
## Problem / Steps to reproduce

- Run:

    ```
    echo "foo\nbar" | fzf --read0
    ```

- Observe that the newline in `foo\nbar` has been replaced with a space.

It would be amazing if fzf had the capability to display `foo\nbar` as-is, although spanning multiple lines in the terminal, it would act as a single element for selection. One particularly useful use-case would be when displaying multi-line error messages from a compiler.

I had a breeze through the issues but couldn't find this direct issue, I did find [this comment](https://github.com/junegunn/fzf/issues/660#issuecomment-247003781) which says

>the interface of fzf is not suitable for multi-line entries

But doesn't elaborate, perhaps things have changed since 2016.

Thank you for the amazingly useful tool!

**Comment by junegunn** [comment]
Hi, I'm going to have to repeat [my old comment](https://github.com/junegunn/fzf/issues/154#issuecomment-84503814) here:

> Thanks for the suggestion but it's non-trivial to implement multi-line entry display and it will make many parts of the code much more complex. Think about how we should handle long-line truncation and horizontal scroll, multi-part highlighting in extended-search mode possibly spanning multiple lines, page scroll, terminal resize, mouse clicks, ANSI color highlighting, etc. I have very limited time to work on fzf, so I can't say anything about it right now.

fzf has many more options than it has 5 years ago when I posted the comment, so it's even harder now than before to properly implement multi-line entry support without breaking things.

While I also would love to see fzf supporting multi-line entries, I don't think I can implement it in a near future.

**Comment by expipiplus1** [comment]
Thanks for the quick and understandable reply! Not sure how I missed that original issue!

**Comment by expipiplus1** [comment]
One, perhaps much easier, alternative would be being able to display the multiline string in the preview pane, could even support colors and everything there.

**Comment by junegunn** [comment]
FYI: https://github.com/junegunn/fzf/issues/2230#issuecomment-719133459

**Comment by expipiplus1** [comment]
Thanks!

**Comment by Delapouite** [comment]
For visitors stumbling on this issue after a search-engine query: https://junegunn.github.io/fzf/tips/processing-multi-line-items/
