### ISSUE TITLE
check_requirements fzf_version fails: "(eval):1: can't change option: zle"

### ISSUE THREAD

**Issue by rpuntaie** [junegunn/fzf#2219]
- [ x] I have read through the manual page (`man fzf`)
- [ x] I have the latest version of fzf
- [ x] I have searched through the existing issues

## Info

- OS
    - [x ] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ x] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

Calling
:History
in nvim
produces
E605: Exception not caught: You need to upgrade fzf. Found:     (/home/...). Required: 0.23.0 or above.

I have version 0.23.1.

The reason is this:

  systemlist(fzf#exec() .. ' --version')[0]

returns

 (eval):1: can't change option: zle

I don't know why this turns up in nvim. It does not turn up in the zsh itself.

The actual version is 3rd.
One could change [0] to [-1] as a workaround.

**Comment by junegunn** [comment]
> (eval):1: can't change option: zle

That indicates your shell configuration is somehow broken. You need to figure out why you're getting the message. When you run a shell command using system or systemlist, you should only get the output of the command.

```vim
:echo string(system('echo -n foo'))
  " 'foo'
```

**Comment by rpuntaie** [comment]
Yes. Same message "(eval)...)" in nvim, but not in vim.

**Comment by junegunn** [comment]
What's the output of `:echo &shell` on Vim and Neovim?

There are a lot of other places where `system` function is used to read the output of some command. So even if we make this specific code ignore the extra message, you'll run into another problem sooner or later.

**Comment by rpuntaie** [comment]
Neovim and Vim have the same output for `:echo &shell`:
/usr/bin/zsh

I agree  that the workaround is no good solution.

It seems to be an nvim issue.
I close this here and report it there.

**Comment by rpuntaie** [comment]
Link to commit that solves this issue:
https://github.com/junegunn/fzf.vim/commit/bd3a021ec11617c56e6aa95578fee619445b029d
