### ISSUE TITLE
Homebrew fzf 0.23 not available

### ISSUE THREAD

**Issue by j5shi** [junegunn/fzf#2220]
- [x] I have read through the manual page (`man fzf`)
- [ ] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

Homebrew fzf 0.23 not available

**Comment by junegunn** [comment]
https://formulae.brew.sh/formula/fzf

**Comment by j5shi** [comment]
Sorry for that, I didn't update brew (`brew update`) before trying to install fzf 0.23.
