### ISSUE TITLE
Missing options like -xdev or -nf (not following symlinks)

### ISSUE THREAD

**Issue by h8ohmh** [junegunn/fzf#2222]
- [ x] I have read through the manual page (`man fzf`)
- [ x] I have the latest version of fzf
- [ x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish
    
## Problem / Steps to reproduce
fzf is following all symlinks dirs. I had several looks on your site and web, but got no resolution like an option like -nf (don't follow sysmlinks) or even sometihing like "find's -xdev"

**Comment by junegunn** [comment]
You can write your own command for file traversal. See https://github.com/junegunn/fzf#environment-variables
