### ISSUE TITLE
broken --color=bw

### ISSUE THREAD

**Issue by quite** [junegunn/fzf#2229]
I have been running `fzf` with `--color=bw` for quite some time. It now crashes with:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xa0 pc=0x51982d]

goroutine 1 [running]:
github.com/junegunn/fzf/src.postProcessOptions(0xc000111400)
	/home/quite/src-scratch/fzf--junegunn/src/options.go:1523 +0x1ed
github.com/junegunn/fzf/src.ParseOptions(0x0)
	/home/quite/src-scratch/fzf--junegunn/src/options.go:1545 +0xd6
main.main()
	/home/quite/src-scratch/fzf--junegunn/main.go:16 +0x2c
```

I've done git bisect, and it is 11841f688bd12e56c11dc2ae71911a1e25213951 that caused this.

**Comment by junegunn** [comment]
Thanks, fixed on master. `--no-color` is equivalent to `--color=bw` and it's not broken, so you can use it instead for the time being as a workaround.
