### ISSUE TITLE
question or feature reuqest -- grouping resutls for multi - line entries

### ISSUE THREAD

**Issue by rayiik** [junegunn/fzf#2230]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish
    
## PROBLEM 
- Search query produces multi line parings
- Searching for keywords within the paring
- Primary result inst in that line but the line before it but line is cleared during the filtering for the keyword

## EXAMPLE
```bash
for commands in "$(atp search "$1" | fzf --preview="apt show {} -m -e")";
do
sudo apt install "$commands" || exit 1
done
```
# Results Produced
```

zfs-initramfs/focal-updates 0.8.3-1ubuntu12.4 amd64
  OpenZFS root filesystem capabilities for Linux - initramfs

zfs-test/focal-updates 0.8.3-1ubuntu12.4 amd64
  OpenZFS test infrastructure and support scripts

zfs-zed/focal-updates 0.8.3-1ubuntu12.4 amd64
  OpenZFS Event Daemon

zfsutils-linux/focal-updates 0.8.3-1ubuntu12.4 amd64
  command-line tools to manage OpenZFS filesystems
```
During the fzf search often what im searching for is located in the description but the results i want to act on are in the first line. when fzf searching i get my result and i can mark it, however, i then have to clear query and search for the mark.
So A. is there a way to group up multi lines as one "line" of (i don't really understand the --nth and --with-nth so this might be the solution but i suspect it wont produce a working group) . I'm hoping for a solution beyond this example as i don't use apt often but this is just the example that came to mind.

**Comment by junegunn** [comment]
I decided not to implement multi-line entry support due to technical difficulties. See #2174.

In this case, I'm not sure fzf is the best tool for your requirement, but if I had to use fzf which is strictly a line-based solution, I would consider squashing the lines in each entry so any text in the entry is searchable, while showing the original multi-line form in the preview window.

```sh
cat > /tmp/source << EOF
zfs-initramfs/focal-updates 0.8.3-1ubuntu12.4 amd64
  OpenZFS root filesystem capabilities for Linux - initramfs

zfs-test/focal-updates 0.8.3-1ubuntu12.4 amd64
  OpenZFS test infrastructure and support scripts

zfs-zed/focal-updates 0.8.3-1ubuntu12.4 amd64
  OpenZFS Event Daemon

zfsutils-linux/focal-updates 0.8.3-1ubuntu12.4 amd64
  command-line tools to manage OpenZFS filesystems
EOF

perl -pe 'BEGIN{undef $/;} s/\n\n/\x0/g; s/\n$//g' /tmp/source |
  fzf --height 50% --reverse --read0 --no-hscroll --preview 'echo {}' --preview-window up:2 |
  awk 'NR == 1 {print $1}'
```

**Comment by rayiik** [comment]
Hey thanks ill check that out I think upon consideration I might also be able to save each set into an array and call them ""line"" by line ill have to check it out and post back this weekend but for now thanks.

**Comment by rayiik** [comment]
I think actually i might have solved this as ive written a script that more or less reverses the functionality of the preview window main search i just need to figure out a way to extend it to this case use, currently you fuzzy query the content of files and it shows files that match the fzf query in the preview window and i think i could do it with process substitution 
```bash
fvar="$1"
echo "$fvar"
if test -n "$1"; then
  fvar="$1"
else fvar=''
fi
echo "$fvar" | \
  fd -uu -t f \
  -x rg . {} --heading --no-filename | \
  fzf --print-query \
  --preview="rg {+} --files-with-matches -H" \
  --bind="change:reload(export fvar={q} && echo \"$fvar\" | fd -uu -t f \
  -x rg . --no-filename --heading)"
```

**Comment by junegunn** [comment]
See https://junegunn.github.io/fzf/tips/processing-multi-line-items/
