### ISSUE TITLE
Weird space when using borderless preview window

### ISSUE THREAD

**Issue by LiteracyFanatic** [junegunn/fzf#2231]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

`fzf --reverse --preview 'echo {}' --preview-window=top:1:noborder` leaves a gap which isn't present with `fzf --reverse --preview 'echo {}' --preview-window=top:1`. Compare the attached images.

![2020-10-31T09:24:22-05:00](https://user-images.githubusercontent.com/18249574/97781661-f8328880-1b5a-11eb-9d58-cfaf898dc632.png)
![2020-10-31T09:24:45-05:00](https://user-images.githubusercontent.com/18249574/97781663-f963b580-1b5a-11eb-80d1-f31433685458.png)

**Comment by junegunn** [comment]
Thanks for the report. There was a hard-coded lower-limit of the window height. It should be fixed on master.

**Comment by LiteracyFanatic** [comment]
Great to hear. Thanks.
