### ISSUE TITLE
completion.bash and key-bindings.bash bug

### ISSUE THREAD

**Issue by wgmayer0** [junegunn/fzf#2234]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish
    
## Problem / Steps to reproduce
Operating system: Arch Linux
Pacman was used to install fzf, latest version

I first tried to source the 2 files:

**Input:**
`source /usr/share/fzf/completion.bash`

**Output:**
```
bash: /usr/share/fzf/completion.bash: line 183: syntax error near unexpected token `done'
bash: /usr/share/fzf/completion.bash: line 183: `    done'
```

**Input:**
`source /usr/share/fzf/key-bindings.bash`

**Output:**
```
bash: /usr/share/fzf/key-bindings.bash: line 23: syntax error near unexpected token `done'
bash: /usr/share/fzf/key-bindings.bash: line 23: `  done'
```

_I can't find any documentation online to get shell integration working and I have been searching for 4 hours now. Can't find anything so I assume this is a bug. Can someone guide me in the right direction?_

**Comment by junegunn** [comment]
I don't use ArchLinux, so I have no idea how they packaged fzf. First, you need to git clone this repository and see if the files are identical to the ones in `shell/` directory from this repo.

**Comment by junegunn** [comment]
And `set -x` will help you understand what's going on under the hood.
```sh
set -x; source /usr/share/fzf/key-bindings.bash; set +x
```

**Comment by wgmayer0** [comment]
Yes I should have mentioned that. I git cloned this repository and got the exact same error. Thanks for the quick response.

**Comment by wgmayer0** [comment]
Input:
`set -x; source /usr/share/fzf/key-bindings.bash; set +x
`
Output:
```
+ source /usr/share/fzf/key-bindings.bash
bash: /usr/share/fzf/key-bindings.bash: line 23: syntax error near unexpected token `done'
bash: /usr/share/fzf/key-bindings.bash: line 23: `  done'
```

**Comment by junegunn** [comment]
The syntax of the file is perfectly fine. I suspect you have strange aliases (such as `for`, `do`, `done`, etc, which clash with bash builtins) that interfere with the processing.

**Comment by junegunn** [comment]
Related: https://stackoverflow.com/questions/22969050/bash-syntax-error-near-unexpected-token-done-with-alias-named-do

**Comment by rayiik** [comment]
also if your wondering arch packages in var/cache/pacman/pkg is where source files are if you can seem to find an alias for done make one 
'''bash
alias done='\done'
'''
the slash in front of the done will prevent it from aliasing out to something else. unalias wont work as if your not setting it you probably don't know when its set but probably in your /etc/profile.d would be the first place i look. so if you unalias done and it doesn't work it means its being set after your aliases which means you need to alias it to \done. but the bindings used in the scripts are more or less readline functions so you might want to try updating your readline. But being on the main arch repo means that the install scripts have been verified and work or they get pulled (generally speaking) but you may also want to check your settings in /etc/pacman.conf

**Comment by wgmayer0** [comment]
Wow! Thanks for the help. You knew exactly what the problem was.

I had this line in my `bashrc`:

`alias do='xterm -hold -e vim ~/todo'`

**Comment by junegunn** [comment]
Yeah, that's a horrible idea 😄
