### ISSUE TITLE
Ctrl-R binding to execute selection (versus copy to command line)

### ISSUE THREAD

**Issue by ramrom** [junegunn/fzf#2235]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Feature Request

First off, I definitely ❤️ FZF! Integrated it into everything already.

My feature request is to have ctrl-R history search have a binding that will immediately execute the selection, the behavior currently is to just paste it to the command line.

**Comment by junegunn** [comment]
I decided not to add an option. Previous discussions can be found in #1492 and #477.
