### ISSUE TITLE
Missing scroll left/right or wrap results

### ISSUE THREAD

**Issue by elig0n** [junegunn/fzf#2236]
- [X] I have read through the manual page (`man fzf`)
- [X] I have the latest version of fzf
- [X] I have searched through the existing issues

## Info

- OS
    - [X] Linux
- Shell
    - [X] zsh
    
## Problem / Steps to reproduce

When a result list item is too long there is no way to scroll the display horizontally as if in a pager. 
Instead the long line is shortened with two dots shown at the truncated end.
I've no --no-hscroll in FZF_DEFAULT_OPTS

An option to wrap long lines can also help.

**Comment by junegunn** [comment]
I'm not going to implement the option because of technical difficulties.

FYI, there is `--keep-right` option if you're more interested in the right end of each entry.
