### ISSUE TITLE
CTRL-R (reverse-i-search)` fzf CentOS 8

### ISSUE THREAD

**Issue by Sk1llRex** [junegunn/fzf#2238]
- [ ] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

CentOS 8 - installed fzf via `git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
~/.fzf/install`

Inside `.bashrc` following data: 
`[ -f ~/.fzf.bash ] && source ~/.fzf.bash` (default)
`source /home/usr/.fzf/shell/key-bindings.bash` (added from .fzf.bash manually)

Inside the `.fzf.bash` following data: 

Setup fzf
`if [[ ! "$PATH" == */home/usr/.fzf/bin* ]]; then
  export PATH="${PATH:+${PATH}:}/home/usr/.fzf/bin"
fi`

Auto-completion
`[[ $- == *i* ]] && source "/home/usr/.fzf/shell/completion.bash" 2> /dev/null`

Key bindings
`source "/home/usr/.fzf/shell/key-bindings.bash"`

I tried for some time now `man fzf`gets `No manual entry for fzf`

Could anyone help me please? I'm very sure I'm doing something wrong - I'm new to Linux, but would like to have fzf here too. Thanks upfront.

**Comment by junegunn** [comment]
If `~/.fzf` is in your `$PATH`, `man` should have no problem locating the manual file.

```sh
$ man -d fzf
```

And you'll see something like below

```
...
path directory /Users/jg/.fzf/bin is not in the config file
but there is a man directory nearby
adding /Users/jg/.fzf/man to manpath
...
```

You can read more about how man searches for the files in `man man`.

**Comment by junegunn** [comment]
> added from .fzf.bash manually

There's nothing you have to do manually. `~/.fzf/install` script will set everything up and fzf will be available when you relaunch your shell.

**Comment by Sk1llRex** [comment]
Thank you very much for your quick help! As described, I deleted the manually added data record.
Via `source ~/.bashrc` everything is working now. Thanks! 

After I was on a server via SSH, `exit` and re-establishing the connection did not result in the shell being reloaded. 

Btw., awesome tool..

**Comment by junegunn** [comment]
Maybe your shell is not configured to load `.bashrc`. See https://github.com/junegunn/fzf/issues/282.

**Comment by Sk1llRex** [comment]
One question just came up: it seems like I have to run `source ~ / .bashrc` every time before CTRL-R works. 
If I don't run `source ~ / .bashrc` upfront, I get the `(reverse-i-search)`

Have I missed something here?

I restarted the server.

**Comment by Sk1llRex** [comment]
many thanks! 

"You should therefore always have source ~/.bashrc at the end of your .bash_profile in order to force it to be read by a login shell." - done!

**Comment by junegunn** [comment]
Yeah, install script also mentions that:

```
Finished. Restart your shell or reload config file.
   source ~/.bashrc  # bash  (.bashrc should be loaded from .bash_profile)
   source ~/.zshrc   # zsh
   fzf_key_bindings  # fish
```
