### ISSUE TITLE
--margin behaviour is different

### ISSUE THREAD

**Issue by numToStr** [junegunn/fzf#2241]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish
    
## Problem / Steps to reproduce
Today I updated from v0.22 to v0.24 and I found out that the behaviour of `--margin` is different. Previously it adds spacing inside the border, but now it applies around the border.

Below are some screenshots

#### Previous `v0.22.0`
![image](https://user-images.githubusercontent.com/24727447/98232788-1ac20880-1f84-11eb-9156-badb8f6db4c1.png)

#### Now `v0.24.1`
![image](https://user-images.githubusercontent.com/24727447/98232891-3cbb8b00-1f84-11eb-86c5-e736786c2880.png)

## Config
```vim
let $FZF_DEFAULT_OPTS = "--color=dark --reverse --keep-right --marker=+ --margin=1,1"
```

If this is a intentional change, then maybe introduce a `--padding` option similiar to `--margin`

**Comment by junegunn** [comment]
Is this a screenshot from Vim?
The behavior of `--margin` hasn't been changed since the beginning.
What's changed is how we draw the border on Vim.

**Comment by numToStr** [comment]
> Is this a screenshot from Vim?

Yeah, It's neovim.

### Full Screenshot
![image](https://user-images.githubusercontent.com/24727447/98241889-98d8dc00-1f91-11eb-9eee-57489b2f915f.png)

### Config
```lua
-- fzf.lua

local U = require 'utils'
local g = vim.g
local cmd = vim.cmd

U.setenv("FZF_DEFAULT_OPTS", "--color=dark --reverse --keep-right --marker=+ --margin=1,1")
U.setenv("FZF_DEFAULT_COMMAND", "fd --type f --type l --hidden --follow || git ls-files --cached --others --exclude-standard")

-- Customize fzf colors to match your color scheme
-- fzf#wrap translates this to a set of `--color` options
g.fzf_colors = {
    fg = { "fg", "Normal" },
    bg = { "bg", "Normal" },
    hl = { "fg", "Red" },
    ["fg+"] = { "fg", "MyWhite" },
    ["bg+"] = { "bg", "Normal" },
    ["hl+"] = { "fg", "Red" },
    info = { "bg", "Normal" },
    prompt = { "fg", "MyWhite" },
    pointer = { "fg", "MyWhite" },
    marker = { "fg", "Yellow" },
    spinner = { "fg", "MyWhite" },
    header = { "bg", "Normal" }
}

-- Enable per-command history
-- - History files will be stored in the specified directory
-- - When set, CTRL-N and CTRL-P will be bound to 'next-history' and
--   'previous-history' instead of 'down' and 'up'.
g.fzf_history_dir = "~/.local/share/fzf-history"

g.fzf_layout = {
    window = {
        width = 0.4,
        height = 0.25,
        yoffset = 0,
    },
}

cmd [[ command! -bang -nargs=? -complete=dir Files call fzf#vim#files(<q-args>, { "options": "--prompt '⯈ '"}, <bang>0) ]]

g.fzf_preview_window = ""
g.fzf_buffers_jump = 1

function FZFOpen(cmd_str)
    U.move_cursor_from_tree()
    cmd(cmd_str)
end

-- Ctrl-p = fuzzy finder
U.map("n", "<C-P>", "<CMD>lua FZFOpen(':Files')<CR>")

-- . = location of current file
U.map("n", "'.", "<CMD>lua FZFOpen(':FZF "..vim.fn.expand("%:h").."')<CR>")

-- z = FZF
U.map("n", "'z", "<CMD>lua FZFOpen(':FZF')<CR>")

-- b = buffers
U.map("n", "'b", "<CMD>lua FZFOpen(':Buffers')<CR>")

-- t = tags
U.map("n", "'t", "<CMD>lua FZFOpen(':Tags')<CR>")

-- i = history
U.map("n", "'i", "<CMD>lua FZFOpen(':History')<CR>")

-- h = home
U.map("n", "'h", "<CMD>lua FZFOpen(':FZF ~/')<CR>")
``
