### ISSUE TITLE
[Issue / FR] Preview window is executing commands with `sh -c` instead of default shell for user

### ISSUE THREAD

**Issue by ZalgoNoise** [junegunn/fzf#2242]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

First of all, thanks for the excellent tool! Great to see Go development such as this. Kudos to all contributors. 

This might be my own fault so please bare with me.

### Issue

Preview window does not execute commands as per default shell (`zsh`), and executes commands with `sh -c` instead. This causes issues with _less-POSIX-compliant_ `zsh` scripts, such as when streaming data into a program with command substitution: `--preview "cat <(echo string)"`. I've noticed this happening exclusively in Docker containers.

##### Issue

Key | Value
:--:|:--:
Kernel | `5.9.1-1`
OS | docker container - `alpine:edge`
`fzf` | `v0.24 (devel)`
`zsh` | `v5.8 (x86_64-alpine-linux-musl)`

1. Launch a Docker container (`alpine:edge`): `docker run --rm -ti --name fzf-test alpine:edge`
2. Install `zsh` and `fzf`: `apk add --update --no-cache zsh fzf`
3. Force `zsh` as default shell for `root` and in `/etc/shells`; confirm with /etc/passwd:

```
# usermod -s /bin/zsh root
# echo -e "# Pathnames of valid login shells.\n# See shells(5) for details.\n\n/bin/zsh" > /etc/shells
# cat /etc/passwd | grep -E "^root:" 
root:x:0:0:root:/root:/bin/zsh

```

4. Optionally, restart the container: `docker restart fzf-test` 
5. Go back into the container `docker exec -ti fzf-test zsh`
6. Test `fzf` preview:

```
# cat <(echo this)
this

# ls | fzf --preview "cat <(echo this)"
[preview window]
sh: syntax error: unexpected "("

# ls | fzf --preview "zsh -c 'cat <(echo this)'"
[preview window]
this

```

##### No issue

Key | Value
:--:|:--:
Kernel | `5.9.1-1`
OS | Manjaro (Arch Linux)
`fzf` | `v0.22.0`
`zsh` | `v5.8 (x86_64-pc-linux-gnu)`

For some reason, in my system I didn't detect this (prior to building a Docker container with a `jq`+`fzf` tool for JSON parsing). I am running Manjaro (Arch Linux) on kernel 5.9.1-1 (x86_64), in which I installed `fzf` v0.22.0 and `zsh` v5.8 via the system's package manager `pacman`. Docker host is installed on the same machine, so there are no kernel version differences, and Alpine Edge is powering `fzf` v0.24 (devel) and `zsh` v5.8 (x86_64-alpine-linux-musl).

When I run the same tests in my machine directly, I never have a problem with the default shell in the preview:

```
% cat <(echo this)
this

% ls | fzf --preview "cat <(echo this)"
[preview window]
this 
```

Similarly, in `/etc/passwd` has the user with `zsh` as default shell. In `/etc/shells` I have more shells installed/configured:

```
cat /etc/shells    
# Pathnames of valid login shells.
# See shells(5) for details.

/bin/sh
/bin/bash
/bin/zsh
/usr/bin/zsh
/usr/bin/git-shell
```

### Additional Info

I have also tried to mimic my system with a Docker container for `archlinux:latest`, and I found the results to be the same as in Alpine, where preview is using `sh -c` to execute the stated commands. 

This is also not `busybox` or `musl`, since even after installing `gcc` (or in Arch) didn't change the outcome either.

I have also tried to build the latest version of `fzf` locally and on the containers, which didn't change the outcome as well.

Finally, in the manual and even in `/src/options.go`, there wasn't any option to define the default execution interpreter / shell for the preview window:

```
type previewOpts struct {
	command  string
	position windowPosition
	size     sizeSpec
	scroll   string
	hidden   bool
	wrap     bool
	cycle    bool
	border   tui.BorderShape
}
```

### Workarounds

- Launching preview with `zsh -c` prefixed, to force `zsh` as interpreter. _e.g._`fzf --preview "zsh -c 'jq -C <(echo {})'"`

- Change logic to avoid _less-POSIX-compliant_ statements/commands. _e.g._ `fzf --preview "echo {} | jq -C"`

### Request

1. If you have any insight on what I am doing wrong in terms of Docker container configuration, I would definitely appreciate the help, to figure out what's forcing `sh -c` instead of the current or the user's configured default shell.

2. Otherwise, if nothing is wrong with the container configuration (which I would doubt as it runs as expected in my machine, directly), I'd like to propose a `shell` preview option, if possible to define (or to pickup the same default shell as the user's config/env variable) as a Feature Request.

Once again, thank you so much for your hard work, this tool is amazing and it deserves all the best recognition.

**Comment by junegunn** [comment]
fzf respects `$SHELL` value, so make sure that it's correctly set in your environment.

https://github.com/junegunn/fzf/blob/d099941360e061587bf7d42cd029c91650ef5a44/src/util/util_unix.go#L11-L18

```sh
docker run --rm -ti --name fzf-test alpine:edge

apk add --no-cache fzf zsh shadow

# Add user foo
useradd -m foo
usermod -s /bin/zsh foo

su foo
echo $SHELL
  # /bin/zsh
```
