### ISSUE TITLE
The preview action doesn't seem to work

### ISSUE THREAD

**Issue by ddnexus** [junegunn/fzf#2243]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

```sh
exa -l | fzf --preview 'exa -l {7}' --bind 'enter:preview(exa -la {7})'
unknown action: preview(exa -la {7})
```
I've tried also other commands, other keys and other syntax for the action, with no success.
Now sure whether I missed something fundamental or it's some other issue.

**Comment by rayiik** [comment]
Hey just a thought but try this format for preview
```bash
    fzf --preview=“exa -l {7}” --bind=‘enter:preview:exa -l {7}’
```

**Comment by ddnexus** [comment]
@rayiik Thanks, but it doesn't work. `unknown action: preview:exa -l {7}`

**Comment by ddnexus** [comment]
@rayiik did you try it with the current version?

**Comment by junegunn** [comment]
> I have the latest version of fzf

Are you sure about this? `fzf --version`?

**Comment by ddnexus** [comment]
0.21.1 (334a4fa)

**Comment by junegunn** [comment]
That's not the latest version. https://github.com/junegunn/fzf/blob/master/CHANGELOG.md

**Comment by ddnexus** [comment]
I've just discovered that regardless that zplug did just updated it, it was not the latest version... 
After removing and re-installing it with zplug, now the version is `0.23.1 (fc7630a)`. 
I will have to understand what happened, but now it doesn't raise the error anymore.
Do you have the official way to install it with zplug?
Sorry for the issue!

**Comment by ddnexus** [comment]
FYI: after investigating the reason for the old version:

- Since version 0.24 the repo url has been changed, hence with the old config zplug gets only 0.23
- It looks like zplug cannot install the binary and sourcing the completion/key-bindings 
- the config that works makes zplug use the install:

```
zplug "junegunn/fzf", from:github, as:command, rename-to:fzf, hook-build:"./install --all"
zplug "junegunn/fzf", from:github, as:plugin, use:"shell/*.zsh"
```
You may want to add it to the readme for the benefit of other users.
Thank you for your time!

**Comment by rayiik** [comment]
sorry for the late reply but yes i did but im glade you got it working :)
