### ISSUE TITLE
Reload preview window on SIGWINCH (resize of window)

### ISSUE THREAD

**Issue by edi9999** [junegunn/fzf#2248]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

Run the following : 

I run the following : 

```
printf "%s\n" "ls" "vim" | fzf --preview 'man {} 2>/dev/null' --preview-window 'right:50%:nohidden'
```

I can see the man page show up in the right.

However, when I resize the window having fzf, the resize event does not cause a redraw in the preview window, meaning that the preview window shows only half of its capacity.

I don't know whether this should be made automatic or optional with a flag.

![record_2020-11-13_103939](https://user-images.githubusercontent.com/2071336/99057836-99c6ca80-259c-11eb-9937-643dbff08fa8.gif)

**Comment by junegunn** [comment]
fzf doesn't re-run the preview command on resize, so it just prints the previous result formatted for the previous width by `man` itself. You can restart the preview command using `refresh-preview` command.

```sh
fzf --preview 'date; echo $FZF_PREVIEW_COLUMNS' --bind space:refresh-preview
```

**Comment by haakonstorm** [comment]
Related: can the preview command be restarted and somehow be input the current number of lines currently shown in the fzf list? This would enable the preview window to grow semi-dynamically; which is natural: the list of candidates shrinks, you want more details about each one. I don't know any clever way of persisting this, but for my use case I use three sets of fzf-lists that inform each other (ctrl+G: context -> list of candidates in that context etc).

**Comment by junegunn** [comment]
```sh
fzf --bind resize:refresh-preview --preview date
```
