### ISSUE TITLE
preview window does not support ansi code '\x1b[0K'

### ISSUE THREAD

**Issue by wfxr** [junegunn/fzf#2249]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

[delta](https://github.com/dandavison/delta) uses `'\x1b[0K'` (https://github.com/dandavison/delta/blob/master/src/ansi/mod.rs#L12) to render full line background. But seems fzf preview window doesn't support it.

(I find `less` with `-R` option also doesn't support this but with `-r` option it works perfectly. hope this can help).

See the difference of the following screenshots (note the background):

* `delta` directly output, background color is **ok**
![image](https://user-images.githubusercontent.com/6105425/99058558-59853d80-25d8-11eb-973c-dd08450f8280.png)

* `less -r`, background color is **ok**
![image](https://user-images.githubusercontent.com/6105425/99058698-89344580-25d8-11eb-8191-8b76fd40f136.png)

* `less -R`, background color is **not ok**
![image](https://user-images.githubusercontent.com/6105425/99058753-98b38e80-25d8-11eb-812c-72079625edc9.png)

* fzf preview with delta, background color is **not ok**
![image](https://user-images.githubusercontent.com/6105425/99058803-a49f5080-25d8-11eb-951d-34b80b975ade.png)

* fzf preview with delta and `less -r`, background color is **not ok**
![image](https://user-images.githubusercontent.com/6105425/99058849-b41e9980-25d8-11eb-97a8-0067e2e2c930.png)

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

**Comment by junegunn** [comment]
Fixed on master. Let me know if it doesn't work as expected. Thanks.

**Comment by wfxr** [comment]
Working perfectly now. Thank you @junegunn !
