### ISSUE TITLE
[neovim] FZF and startify not working

### ISSUE THREAD

**Issue by cHoco** [junegunn/fzf#225]
FZF seems to have some problem if started from startify windows. In particular the split opened by FZF doesn't close when selecting a file and the opened closes as soon as I type something.
Here's simple nvimrc to reproduce

```
call plug#begin('~/.vim/plugged')
Plug 'mhinz/vim-startify'
Plug 'junegunn/fzf', { 'do': 'yes \| ./install' }
call plug#end()
```

### Steps:
1. open nvim without argument
2. in startify window call fzf ```:FZF```
3. select a file to open and press enter
4. fzf split isn't closed and file split closes as soon as you press a key

**Comment by babygau** [comment]
@cHoco,

I suffered from the same issue. `fzf` default `enter` seems to act weird not only with `startify` plugin but with `fzf` itself in `neovim`. My only possibble workaround is to minimize the accident of typing `enter` out of habit by forcing `enter` to open new tab instead of new buffer windows.

```viml
"" My default `fzf` key is <c-p>
nnoremap <silent> <c-p> :<c-u>call fzf#run({
   \ 'options': '-m', " Allow multiple selection
   \ 'down': 20, " Open fzf at the bottom of window
   \ 'sink': 'tabe' " This will make `enter` to open new tab instead of new buffer
   \ })<cr>
```

Hope this help

**Comment by junegunn** [comment]
I didn't pay attention to this issue at first as I thought it was also caused by a bug of Neovim but it wasn't. Please update and let me know if it doesn't work as expected.

**Comment by cHoco** [comment]
Now it almost works! The only difference left now is in vim after opening a file che Startify buffer is closed, instead in neovim the startify buffer is closed but replaced by an empty buffer.

**Comment by junegunn** [comment]
@cHoco Hmm, can you update and try it again?

**Comment by babygau** [comment]
@junegunn 

I just checked. The problem has been fixed. kudos @junegunn :tada: 

Now there's only one nagging #206 left that causing misbehaving `default enter` key in `fzf`. Hope you and @tarruda could fix it one day :sparkles:
