### ISSUE TITLE
Feature request - print index of choice

### ISSUE THREAD

**Issue by YohananDiamond** [junegunn/fzf#2253]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [x] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

I've been making a program that would benefit quite a lot from this feature. Here's a brief example on how it would work:

```
$ echo $'choice 1\nchoice 2' | fzf --print-index
# choice 2 is selected
1 # "choice 2" is the second item on the list, so (using a base-0 index system) the number to be shown is 1.
```

This seemed quite simple to implement upon first thought but I later noticed the sorting system might make this harder to implement - the choice index should be based on the input order, so the type of sorting should have no effect on the output of a choice. So if the `--tac` (reverse order of choices) flag is used and "`choice 2`" is chosen again, the output should still be `1` even if it's now the first ("0th") on the fzf interface.

**Comment by wfxr** [comment]
@YohananDiamond I think you can do this:
```
echo $'choice 1\nchoice 2' | nl | fzf
```
If you only want to get the index:
```
echo $'choice 1\nchoice 2' | nl | fzf | cut -f1
```

**Comment by YohananDiamond** [comment]
@wfxr Hm.. that's a good way to do it, thanks! I'll start using it.

I'd still like to have a way to do it without showing the numbers on the left while selecting but if it's not possible it's not a big deal.

**Comment by junegunn** [comment]
@wfxr Thanks.

@YohananDiamond Try this:

```sh
echo $'choice 1\nchoice 2' | nl | fzf --with-nth 2.. | cut -f1
```

**Comment by YohananDiamond** [comment]
Thanks! This works quite well.
