### ISSUE TITLE
preview window shift-arrow sometimes echos 2A or 2B instead of scrolling

### ISSUE THREAD

**Issue by mckelly2833** [junegunn/fzf#2254]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [x] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

Open preview window and hold down shift-down or ctrl-down and sometimes you will get 2A or 2B (or 5A, 5B) chars instead of scrolling.

**Comment by mckelly2833** [comment]
This issue was originally reported in: https://github.com/junegunn/fzf.vim/issues/1146

**Comment by mckelly2833** [comment]
I have had success with this change. I am thinking there are more chars in the buffer when things happen quickly, and the length is > 6. Will keep testing and debugging.
@junegunn thank you for all your work, I use so much of it every day. Should I submit a PR ?
```
diff --git a/src/tui/light.go b/src/tui/light.go
index ad536f6..146b5cc 100644
--- a/src/tui/light.go
+++ b/src/tui/light.go
@@ -463,7 +463,7 @@ func (r *LightRenderer) escSequence(sz *int) Event {
                                        }
                                        return Event{Invalid, 0, nil}
                                case ';':
-                                       if len(r.buffer) != 6 {
+                                       if len(r.buffer) < 6 {
                                                return Event{Invalid, 0, nil}
                                        }
                                        *sz = 6
```

**Comment by mckelly2833** [comment]
Also, I get this and thought you should know -
```
% make install
/bin/sh: 1: Syntax error: redirection unexpected
```

**Comment by junegunn** [comment]
1. Thanks, I think the patch makes sense, I'll see if I can find a way to reliably reproduce the problem and test the patch.

2. I can't reproduce the second problem you reported.

```sh
$ make install
make: Nothing to be done for `install'.
```

**Comment by junegunn** [comment]
Patch pushed to master. Thanks!

**Comment by mckellygit** [comment]
@junegunn hi,

Just some info, I found out the warning:
```
/bin/sh: 1: Syntax error: redirection unexpected
```
is because /bin/sh on Ubuntu is really dash, not sh.  It can be resolved with adding:
```
SHELL          := bash
```
at the top of the Makefile.  Should we add this ?

Also - what do you think of me adding some more mappings to tui/light.go for some keys such as ?
ctrl-page-up
ctrl-home
etc.
I wish to add the ctrl/shift/alt keys of ins/del/home/end/page-up/page-down.
I would also like to add a goto top and goto bottom function for preview.

thank you for awesome fzf, fzf.vim and gv.
-m

**Comment by junegunn** [comment]
> Should we add this ?

Thanks. Done. 012ee9c

> goto top and goto bottom function for preview

151252e

> some keys such as ...

I don't know if those keys are supported in the standard terminal environment. Probably not. Please open a pull request if you can implement it. (You also have to update tcell.go for Windows).

Also, you might want to check out 7f8e0dbc408eff786865d0e2d9e3c62ec3ed4776

**Comment by mckellygit** [comment]
Hi,
I was thinking of something like:
```
fzfmap \e[5;5~ ctrl-page-up
```
etc. in a file to have these be terminal independent, but I see you are using tcell.go and so perhaps we can use that ?
I think tcell should define most of the ctrl/alt/shift ins/del home/end pageup/down combinations.

I'll try to code something soon.
-m

**Comment by mckellygit** [comment]
ok, I see you are using tcell for windows.
