### ISSUE TITLE
Failed to run "fzf --version": ['<be><f8><b7><c3><ce>?<a3>^M']

### ISSUE THREAD

**Issue by jiangjianshan** [junegunn/fzf#2256]
Hello, 

I'm using fzf which version is 0.24.3 on Vim 8.2.2000 on Windows 10. Recently I have got the following error when using 'noremap <silent> <leader>f :Rg <C-R><C-W><CR>' settings on _vimrc:

![image](https://user-images.githubusercontent.com/20179047/99508327-6c748500-29bf-11eb-89d3-dfed26c53a18.png)

To run 'fzf --version' on Command Prompt can got the correct version result, so I think fzf.exe hasn't been broken.
![image](https://user-images.githubusercontent.com/20179047/99509420-b1e58200-29c0-11eb-8b60-a470efc23403.png)

The settings for fzf.vim on _vimrc are here:
" ------------------------------------ start -------------------------
let g:fzf_tags_command = 'ctags -R'
let g:fzf_preview_window = 'right:60%'

" This is the default extra key bindings
let g:fzf_action = {
  \ 'ctrl-t': 'tab split',
  \ 'ctrl-x': 'split',
  \ 'ctrl-v': 'vsplit'
\}

let g:fzf_history_dir = '$HOME/.local/share/fzf-history'

let $FZF_DEFAULT_COMMAND = 'rg --files --ignore-case --hidden'
let $FZF_DEFAULT_OPTS = '--bind ?:toggle-preview --bind ctrl-j:down --bind ctrl-k:up --bind ctrl-d:half-page-down --bind ctrl-u:half-page-up'

let g:fzf_layout = { 'window': { 'width': 0.9, 'height': 0.8 } }

" Customize fzf colors to match your color scheme
let g:fzf_colors = {
  \ 'fg':      ['fg', 'Normal'],
  \ 'bg':      ['bg', 'Normal'],
  \ 'hl':      ['fg', 'Comment'],
  \ 'fg+':     ['fg', 'CursorLine', 'CursorColumn', 'Normal'],
  \ 'bg+':     ['bg', 'CursorLine', 'CursorColumn'],
  \ 'hl+':     ['fg', 'Statement'],
  \ 'info':    ['fg', 'PreProc'],
  \ 'border':  ['fg', 'Ignore'],
  \ 'prompt':  ['fg', 'Conditional'],
  \ 'pointer': ['fg', 'Exception'],
  \ 'marker':  ['fg', 'Keyword'],
  \ 'spinner': ['fg', 'Label'],
  \ 'header':  ['fg', 'Comment']
\}

" Get Files
command! -bang -nargs=? -complete=dir Files
    \ call fzf#vim#files(<q-args>, fzf#vim#with_preview({'options': ['--layout=reverse', '--info=inline']}), <bang>0)

" Get text in files with Rg
command! -bang -nargs=* Rg
  \ call fzf#vim#grep(
  \   'rg --column --line-number --no-heading --color=always --smart-case '.shellescape(<q-args>), 1,
  \   fzf#vim#with_preview(), <bang>0)

" Ripgrep advanced
function! RipgrepFzf(query, fullscreen)
  let command_fmt = 'rg --column --line-number --no-heading --color=always --smart-case %s || true'
  let initial_command = printf(command_fmt, shellescape(a:query))
  let reload_command = printf(command_fmt, '{q}')
  let spec = {'options': ['--phony', '--query', a:query, '--bind', 'change:reload:'.reload_command]}
  call fzf#vim#grep(initial_command, 1, fzf#vim#with_preview(spec), a:fullscreen)
endfunction

command! -nargs=* -bang RG call RipgrepFzf(<q-args>, <bang>0)

noremap <silent> <leader>p :Files<CR>
noremap <silent> <leader>f :Rg <C-R><C-W><CR>
" ------------------------------------ end -------------------------

I'm confusing what is the reason cause the error.

**Comment by junegunn** [comment]
What do you see when you run `:echom string(system(fzf#exec() . ' --version'))` ?

**Comment by jiangjianshan** [comment]
@junegunn ,  the result is here:
![image](https://user-images.githubusercontent.com/20179047/99534656-b7ec5a80-29e2-11eb-8cd7-baeb708a637b.png)

**Comment by junegunn** [comment]
That's strange. You'll have to figure out why you're getting those characters instead of the proper version number.

Also, what do you see on `:!fzf --version`?

**Comment by jiangjianshan** [comment]
@junegunn ,  the result is 
![image](https://user-images.githubusercontent.com/20179047/99535627-1d8d1680-29e4-11eb-844a-9984d4879bbc.png)

**Comment by jiangjianshan** [comment]
@junegunn , If I run 'echo string(system('rg --version'))', the result will be
![image](https://user-images.githubusercontent.com/20179047/99536377-3c3fdd00-29e5-11eb-9017-8e2885599b7c.png)
So I think this should not the issue of fzf but I will try to fix it and update the solution at here.

**Comment by jiangjianshan** [comment]
@junegunn , today I have found the solution for above issue.  It should be because the command “cmd /c fzf --version” are denied access. So on Command Prompt window, I type "cacls D:\Vim\vimfiles\plugged\fzf\bin\fzf.exe /p administrator:f" to give the access right for fzf.exe then the issue solved. I don't know why will denied access because previous it is running. But no matter what, if this issue happen again, just use the command I say should be solved the issue.

**Comment by jiangjianshan** [comment]
@junegunn , in order to fix this issue, I have just made a pull request which is #2308 two days ago.
