### ISSUE TITLE
CTRL-R show nothing before typing a command on a new bash

### ISSUE THREAD

**Issue by FabriceSh44** [junegunn/fzf#2260]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

1. run "bash"
2. press CTRL-R => preview shows 0/0 +S
3. CTRL-C
4. run "echo test"
5. press CTRL-R => preview show 1000 elements

If I run a new bash and "history" I see 1000 elements. It seems that I need to run at least one command to have something in CTRL+R.
Doesn't have this issue with[ key-bindings.bash version:9c293bb82b6be333c857d288d10aab730220a0e7](https://github.com/junegunn/fzf/blob/9c293bb82b6be333c857d288d10aab730220a0e7/shell/key-bindings.bash)

**Comment by junegunn** [comment]
We use `fc -lnr -2147483648` to generate the list. Check if you see an empty list when you run the command.

**Comment by FabriceSh44** [comment]
`fc -lnr -2147483648 `  shows the list alright

**Comment by junegunn** [comment]
You can try debugging the problem by starting bash with `-x`.

**Comment by FabriceSh44** [comment]
when pressing CTRL R, I get :
```
++ __fzf_history__                                             
++ local output                                                
+++ builtin fc -lnr -2147483648
++++ __fzfcmd                                                  
++++ HISTTIMEFORMAT=                                           
++++ builtin history 1                                         
++++ '[' -n %29 ']'                                            
++++ '[' 0 '!=' 0 ']'                                          
++++ '[' -n '' ']'                                             
++++ echo fzf                                                  
+++ FZF_DEFAULT_OPTS='--height 40% --height 50% --multi --preview '\''(bat --style=numbers --color=always {} || cat {}) 2> /dev/null | head -300'\'' --preview-window='\''right:hidden:wrap'\'' --bind='\''f2:toggle-preview,ctrl-d:preview-page-down,ctrl-u:p
review-page-up'\'' -n2..,.. --tiebreak=index --bind=ctrl-r:toggle-sort  +m --read0'                                            
+++ fzf --query ''                                             
+++ last_hist=' 1000  fc -lnr -2147483648'
+++ perl -n -l0 -e 'BEGIN { getc; $/ = "\n\t"; $HISTCMD = $ENV{last_hist} + 1 } s/^[ *]//; print $HISTCMD - $. . "\t$_" if !$seen{$_}++'

```

**Comment by junegunn** [comment]
I can't help you as I can't reproduce it on my machine. It's probably some configuration issue.

**Comment by FabriceSh44** [comment]
I understand. I've just updated on the HEAD and tried it with an empty bashrc + install and I have the same issue. 
```
bash-4.1$ cat ~/.bashrc
[ -f ~/.fzf.bash ] && source ~/.fzf.bash
bash-4.1$ bash
bash-4.1$ output=$(builtin fc -lnr -2147483648 | last_hist=$(HISTTIMEFORMAT='' builtin history 1) perl -n -l0 -e 'BEGIN { getc; $/ = "\n\t"; $HISTCMD = $ENV{last_hist}+ 1 } s/^[ *]//; print $HISTCMD - $. . "\t$_" if !$seen{$_}++' |  FZF_DEFAULT_OPTS="--height ${FZF_TMUX_HEIGHT:-40%} $FZF_DEFAULT_OPTS -n2..,.. --tiebreak=index --bind=ctrl-r:toggle-sort $FZF_CTRL_R_OPTS +m --read0" $(__fzfcmd) --query "$READLINE_LINE")
**=>NOTHING**
bash-4.1$ echo test
test
**If I run the same output command=>HISTORY OK**
```

**Comment by FabriceSh44** [comment]
Any clue on which configuration I should look?

**Comment by junegunn** [comment]
No idea, I'm not familiar with the problem. So `builtin fc -lnr -2147483648` gives you a non-empty list even when it's the first command you run on a new bash process?

**Comment by FabriceSh44** [comment]
Yes but 
`output=$(builtin fc -lnr -2147483648 | last_hist=$(HISTTIMEFORMAT='' builtin history 1) perl -n -l0 -e 'BEGIN { getc; $/ = "\n\t"; $HISTCMD = $ENV{last_hist}+ 1 } s/^[ *]//; print $HISTCMD - $. . "\t$_" if !$seen{$_}++' |   cat )`

return nothing in output in a new bash, all histo in a second run...

**Comment by FabriceSh44** [comment]
```
> bash
> output=$(builtin fc -lnr -2147483648 | last_hist=$(HISTTIMEFORMAT='' builtin history 1) perl -n -l0 -e 'BEGIN { getc; $/ = "\n\t"; $HISTCMD = $ENV{last_hist}+ 1 } s/^[ *]//; print $HISTCMD - $. . "\t$_" if !$seen{$_}++' |   cat)
> echo $output
> #NOTHING                                                                                                                                                                                                                                  
> output=$(builtin fc -lnr -2147483648 | last_hist=$(HISTTIMEFORMAT='' builtin history 1) perl -n -l0 -e 'BEGIN { getc; $/ = "\n\t"; $HISTCMD = $ENV{last_hist}+ 1 } s/^[ *]//; print $HISTCMD - $. . "\t$_" if !$seen{$_}++' |   cat)                        ()                                                                                                                                                                                                                                   
> echo $output                                                                                                                                                                                                                                                
1000 output=$(builtin fc -lnr -2147483648 | last_hist=$(HISTTIMEFORMAT='' builtin history 1) perl -n -l0 -e 'BEGIN { getc; $/ = "\n\t"; $HISTCMD = $ENV{last_hist}+ 1 } s/^[ *]//; print $HISTCMD - $. . "\t$_" if !$seen{$_}++' | cat)999 echo $output997 output=$(builtin fc -lnr -2147483648 | last_hist=$(HISTTIMEFO .....
> #NOT EMPTY
```
In this run for example, I reproduce the issue. just create a new bash, ran the output, echo the result (nothing) and did it again (things appeared). No fzf involves here. And I feel depending on what's in history, the issue can trigger or not..

**Comment by junegunn** [comment]
So it's not really an issue of fzf.

You might want to simplify the command to better understand the problem. How about `cat <(builtin fc -lnr -2147483648)` on a new bash?

**Comment by FabriceSh44** [comment]
```
> bash
> cat <(builtin fc -lnr -2147483648 | wc -l  )
999
> bash
> cat <(builtin fc -lnr -2147483648 | wc -l  )
0

```
ok no idea what is going on.. this command is really behaving strangely on my setup when piping. No issue when no piping

**Comment by FabriceSh44** [comment]
Ok so I found a workaround. It seems that the -r option on fc in (GNU bash, version 4.1.2(2))  is the source of my problem as it doesn't behave consistently on a new bash. I've removed it and added ` | tac ` instead in  __fzf_history__ and the command CTRL-R works again. Not super happy about the conclusion :\
Anyway, thanks @junegunn  for your help and time

**Comment by junegunn** [comment]
Well, that's unfortunate. tac will block until the completion and the delay is quite noticeable when your history is large. You might want to consider upgrading your baash.

**Comment by sambrightman** [comment]
I have the same Bash version but did not have this problem until an fzf upgrade a few months back. It may fit with commit 5cae8ea733e8663eae96480b5e6d4c94afcdb3bd when fzf changed to using `fc -r` in February 2020 (the increased performance is very noticeable but the bug is unfortunately frequent). However, although I can reproduce at the problematic prompt instance with repeated `C-r` `C-g` invocations I cannot then show a zero for `builtin fc -lnr -2147483648 | wc -l` at that very same prompt instance.
