### ISSUE TITLE
[FR] Don't truncate lines in layout view

### ISSUE THREAD

**Issue by rockandska** [junegunn/fzf#2261]
- [X] I have read through the manual page (`man fzf`)
- [X] I have the latest version of fzf
- [X] I have searched through the existing issues

## Info

- OS
    - [X] Linux
    - [X] Mac OS X
    - [X] Windows
    - [X] Etc.
- Shell
    - [X] bash
    - [X] zsh
    - [X] fish
    
## Problem / Steps to reproduce

Would be nice if there will be an option to wrap long lines instead of truncate them

Actual behavior (TERM=80x40)
```
$ { printf '=%.0s' {1..90}; echo;printf '+%.0s' {1..90}; } | fzf
  > ============================================================================..
    ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++..
```

Expected behavior example 1 (maybe confusing if there is no wrap indicator)

```
$ { printf '=%.0s' {1..90}; echo;printf '+%.0s' {1..90}; } | fzf
  > =============================================================================
    =============
    +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    +++++++++++++
```

Expected behavior example 2 (maybe better if there is a wrap indicator)

```
$ { printf '=%.0s' {1..90}; echo;printf '+%.0s' {1..90}; } | fzf
  > =============================================================================
  ..=============
    +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
  ..+++++++++++++
```

Regards

**Comment by junegunn** [comment]
See #2216

**Comment by rockandska** [comment]
what is the relationship between multiples lines entry and not truncating long lines @junegunn ?
It is not the same "problem" and is the reason of this feature request

**Comment by junegunn** [comment]
I've decided not to implement it but if you are willing to do it, feel free to open a pull request.

**Comment by junegunn** [comment]
See https://junegunn.github.io/fzf/releases/0.54.0/
