### ISSUE TITLE
Paste from clipboard into fzf prompt without Shift

### ISSUE THREAD

**Issue by artemave** [junegunn/fzf#2263]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

I am pasting things into terminal/vim with the mouse middle button. However, when pasting into fzf prompt, I have to also press Shift. Is there a way to change fzf to be just like everything else?

I didn't have that problem in the past (I've been using fzf for years), so I guess something has changed relatively recently.

Thank you for your help and for this amazing project!

**Comment by junegunn** [comment]
If I'm not mistaken, the behavior of the middle button, with or without the shift key, is not standardized and it depends on the terminal emulator. fzf doesn't implement any code for processing it, so if something has changed, it's probably your terminal emulator. You might want to test it with different terminal emulators and see how it behaves on different setups.

**Comment by artemave** [comment]
You're spot on - I've just tried another terminal (I am using Kitty normally) and it works as expected. Thank you!
