### ISSUE TITLE
CTRL-R not bringing up fzf after installing with Conda

### ISSUE THREAD

**Issue by jandono** [junegunn/fzf#2265]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

I am running "Red Hat Enterprise Linux Server 7.8 (Maipo)" on a ppc64le architecture.
I do not have sudo privileges and the only way I managed to install fzf was using conda. (If you know other ways please let me know)
However, after installing it with conda, CTRL-R does not bring up fzf, even tho simply typing fzf in the terminal works.
I checked one similar issue (https://github.com/junegunn/fzf/issues/1812), however as I installed with conda this does not work with me.

One other thing to add is that I cannot set zsh to be my default shell, so I start it from within bash, i.e. at the end of my .bashrc file I have: $HOME/bin/zsh. I am also using prezto (https://github.com/sorin-ionescu/prezto) to customize my zsh.

Fzf is easily one of my all time favorite packages and I would really appreciate some help!

**Comment by junegunn** [comment]
> ⚠️ Key bindings (CTRL-T / CTRL-R / ALT-C) and fuzzy auto-completion may not be enabled by default.
> Refer to the package documentation for more information. (e.g. apt-cache show fzf)

( https://github.com/junegunn/fzf#using-linux-package-managers)

Have you checked the Conda package documentation?

**Comment by jandono** [comment]
Yeah I checked that but `apt-cache show fzf` doesn't work when you install packages with Conda. I did a bit of a research and it seems like when installing with Conda, you don't get the widgets installed, i.e. the commands below aren't even recognized.

```
"^I" fzf-completion
"^R" fzf-history-widget
"^T" fzf-file-widget
"^[c" fzf-cd-widget
```

Do you know any other way of installing the complete `fzf` package without sudo privileges?

**Comment by junegunn** [comment]
I was not suggesting that you should try `apt-cache` command. It is just an example and of course it won't work with any package manager other than APT.

If the Conda package does install the extra script files (e.g. `key-bindings.zsh`, `completion.zsh`, ...), you can just source them in your shell configuration file.

> Do you know any other way of installing the complete fzf package without sudo privileges?

https://github.com/junegunn/fzf#using-git

**Comment by jandono** [comment]
Unfortunately, using git doesn't work as well. I get: 

`No prebuilt binary for Linux ppc64le ...`
