### ISSUE TITLE
How to wrap fzf in a terminal pop up to act like rofi ?  [question] [help]

### ISSUE THREAD

**Issue by sucrecacao** [junegunn/fzf#2268]
- [X ] I have read through the manual page (`man fzf`)
- [X ] I have the latest version of fzf
- [ X] I have searched through the existing issues

## Info

- OS
    - [ X] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ X] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

For the moment I use rofi and fzf for dynamic selection. I would love to only use fzf for everything, but I keep using rofi for the "pop up" behaviour. 

Is it possible to make a shell script that pop a terminal window with fzf, and close after the fzf command is terminated, so that fzf can act like rofi's menu ? 

Thanks

**Comment by junegunn** [comment]
Maybe something like https://medium.com/njiuko/using-fzf-instead-of-dmenu-2780d184753f?

If you use tmux, you might want to check out `fzf-tmux -p` though it's a tmux popup, not a terminal window.

**Comment by sucrecacao** [comment]
Thanks for the link that exactly what I was looking for :)

Should this be added somewhere in the readme or wiki ?

**Comment by junegunn** [comment]
Yeah, it's already on the wiki page: https://github.com/junegunn/fzf/wiki
