### ISSUE TITLE
Implement zsh autocompletion

### ISSUE THREAD

**Issue by tiziano88** [junegunn/fzf#227]
Similar to https://github.com/junegunn/fzf/blob/master/shell/completion.bash ... but for zsh!

**Comment by junegunn** [comment]
So, it's done. I'm not a zsh user and I don't know much about it. I only tested these with vanilla zsh. Let me know if you see any issues.

**Comment by tiziano88** [comment]
Wow that's awesome, I didn't expect you to implement it this quickly! I was actually going to do it myself (I should probably have mentioned that in my original message), but at this point I'll take a look at your version and possibly contribute to it. Thanks a lot!

**Comment by junegunn** [comment]
I pushed a few more commits after closing the issue. Please make sure that you have the latest revision. Thanks!

**Comment by tiziano88** [comment]
I can't seem to be able to use it yet, as ** expands to recursive file glob in my configuration, which I also thought is the default (see http://zsh.sourceforge.net/Doc/Release/Expansion.html#Recursive-Globbing ). I'll see if there is a way of disabling that (as I would much prefer trigger fzf rather than recursive globbing in general.

**Comment by tiziano88** [comment]
Never mind, found the culprit! I had `setopt extended_glob` in my .zshrc, removing that also disabled recursive globbing with **.

**Comment by junegunn** [comment]
Hmm, did it fix the problem? It doesn't seem to matter on my zsh. By the way, did you re-run the install script? Previously `~/.fzf.zsh` was generated with no auto-completion support.

**Comment by tiziano88** [comment]
I was sourcing `completion.zsh` directly, so I guess re-running the install script is not needed. Anyway you are right, even re-enabling `extended_glob` now does not seem to break fzf any more, so they may not be actually interfering after all... Failing everything else, changing the completion trigger to something other than ** seems to solve the issue in any case.

**Comment by junegunn** [comment]
Interesting, could you post the output of `setopt`? I'd like to compare it with mine.

**Comment by tiziano88** [comment]
Sure, here it is:

```
autopushd
nocaseglob
extendedglob
histfindnodups
histreduceblanks
histverify
incappendhistory
interactive
interactivecomments
login
sharehistory
shinstdin
vi
```

To clarify: it seems that the state of `extendedglob` does not actually affect fzf autocompletion; although I guess the interaction may be subtler than just enabling or disabling the option -- for instance it may only happen when  `extendedglob` is enabled before or after sourcing `completion.zsh`. I'll try some more combinations and report here if I find out anything useful.

**Comment by junegunn** [comment]
Looks like `setopt vi` is the cause of the problem. It resets CTRL-I (tab) binding.

```sh
> bindkey '^I'
"^I" fzf-zsh-completion

> setopt vi
> bindkey '^I'
"^I" expand-or-complete
```

So if you source completion.zsh *after* `setopt vi`, it'll work fine. But it would be better if we could find a more robust way to handle this.

**Comment by junegunn** [comment]
FYI, vi-mode of bash also has a similar problem.
https://github.com/junegunn/fzf#key-bindings-for-command-line

**Comment by balta2ar** [comment]
After updating to 34e5e2d my zsh completion broke:

``` bash
→ rm
No such widget `autosuggest-fzf-completion-orig'
```

What additional info can I provide to track the problem?

**Comment by junegunn** [comment]
@balta2ar I have no experience with it. Have you tried swapping the load order of the two?

**Comment by balta2ar** [comment]
@junegunn Hm, unexpectedly, putting `source ~/.fzf.zsh` after autosuggestions seems to have solved the problem. I'd give it a longer try, though, before concluding it works 100%.

**Comment by balta2ar** [comment]
Okay, a problem found. Autosuggestions show the rest of the line in gray, but to turn suggestion into flesh you have options: I usually use Alt-f, Right arrow or Tab. The latter one is the one which does show that error message.

**Comment by junegunn** [comment]
The zsh completion of fzf binds tab key to its completion widget which falls back to the previous widget that was mapped to TAB key. Probably the autosuggest plugin was not written to be compatible with such behavior. Can you look into the issue? I'm not a zsh user and I don't feel like looking into a zsh plugin that I'll never use. Or you can just disable fzf completion (say no to the install script) or [bind it to a different key](https://github.com/junegunn/fzf/wiki/Fuzzy-completion).

**Comment by junegunn** [comment]
@balta2ar The zsh completion of fzf binds tab key to its completion widget which falls back to the previous widget that was mapped to TAB key. Probably the autosuggest plugin was not written to be compatible with such behavior. Can you look into the issue? I'm not a zsh user and I don't feel like looking into a zsh plugin that I'll never use. Or you can just disable fzf completion (say no to the install script) or bind it to a different key.

**Comment by balta2ar** [comment]
@junegunn Thanks, I'll probably stick with disabling autocompletion for a while. Unfortunately, I have zero knowledge of how zsh plugins work, but I'll add problem investigation to my TODO list. Autosuggestions is a nice plugin but as it was mentioned many times in its issues, it requires someone with time and energy to fix all its problems.

Also, could you please expand that Wiki page to describe what value fzf zsh completion adds (maybe more pictures, GIFs or other visual demos of the awesomeness it brings)? Sorry if I sound stupid but I don't quite understand what I am missing here.

**Comment by junegunn** [comment]
@balta2ar What it does is described on the README page.
https://github.com/junegunn/fzf#fuzzy-completion-for-bash-and-zsh
You can disable it if you don't find it very useful, there's nothing wrong with that and I have no intention to persuade one to use it.

**Comment by SharkIng** [comment]
IS this issue solved? @balta2ar ?

**Comment by exAspArk** [comment]
> No such widget `autosuggest-fzf-completion-orig'

Probably it is related to https://github.com/zsh-users/zsh-autosuggestions/issues/108 and https://github.com/zsh-users/zsh-autosuggestions/issues/116. Just try to update https://github.com/zsh-users/zsh-autosuggestions. And replace in your `zshrc` file:
```
source path_to/zsh-autosuggestions/autosuggestions.zsh
zle-line-init() {
    zle autosuggest-start
}
zle -N zle-line-init
```

with:
```
source path_to/zsh-autosuggestions/zsh-autosuggestions.zsh
```
It helped me.

**Comment by balta2ar** [comment]
@SharkIng I disabled autosuggestions and get used to living without them.
