### ISSUE TITLE
Add action changing the prompt text

### ISSUE THREAD

**Issue by przepompownia** [junegunn/fzf#2270]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish
    
## Problem / Steps to reproduce
I have a wrapper for various grep commands with bindings to using fixed strings or not. I would like to pass information about it to the prompt text. I found that composing actions is possible but changing the prompt text seems to be still impossible. 
```vim
  call fzf#vim#grep(a:Cmd(shellescape(a:query), a:useFixedStrings), 0, fzf#vim#with_preview({
        \ 'dir': a:root,
        \ 'options': [
        \ '--phony',
        \ '--multi',
        \ '--query', a:query,
        \ '--bind', 'change:reload:' . a:Cmd('{q}', a:useFixedStrings),
        \ '--bind', 'ctrl-f:reload:' . a:Cmd('{q}', v:true),
        \ '--bind', 'ctrl-r:reload:' . a:Cmd('{q}', v:false),
        \ ]
        \ }), a:fullscreen)
```
It seems to be fzf, not fzf-vim specific.

**Comment by junegunn** [comment]
That is not currently possible. One thing you can do now is to utilize `--header-lines` option and print useful information as the header.

```sh
date | fzf --bind 'space:reload:date; seq 10' --header-lines 1
```

**Comment by junegunn** [comment]
🎉

**Comment by przepompownia** [comment]
Wow, thanks! :tada:
