### ISSUE TITLE
OSX build job on Travis CI seems too lenghty

### ISSUE THREAD

**Issue by VeryTastyTomato** [junegunn/fzf#2271]
- [x] I have read through the manual page (`man fzf`)
- [ ] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish
    
## Problem / Steps to reproduce
I recently opened pull request #2269. I noticed that the build job of Travis CI on OSX was taking much more time than the Linux one, and it eventually failed after 50 min. I checked a couple of other last PR build jobs and it seems that the OSX build job always take about 20 min to finish, if not failing after 50 min. Maybe my changes did introduce a bug on this platforme, but it think there is something wrong with this high duration, though I am not able to tell what.

**Comment by junegunn** [comment]
Thanks for the heads up. I've noticed that too and fixed it on master (disabling homebrew update).
