### ISSUE TITLE
suggestion consider the levenshtein distance the search

### ISSUE THREAD

**Issue by c33s** [junegunn/fzf#2272]
- [x] I have read through the manual page (`man fzf`)
- [x]  I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [ ] Mac OS X
    - [x] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

i use fzf in pet https://github.com/knqyf263/pet and searched for `medison` 

instead of finding the nearly full matching `madison` (i simply made a typo) the first hit was a complete fuzzy match of all letters scattered in the sentence. `the entry with madison wasn't in the result at all.

![image](https://user-images.githubusercontent.com/649209/100669281-71411d80-335d-11eb-8d7f-3aee67267c1b.png)

```
[acme issue a cert with multiple domains and one root (letsencrypt)]: /root/.acme.sh/acme.sh --issue -d example.com -d www.example.com -w /home/mywebroot
```
what i was looking for was:
```
[show all available versions of a package]: apt-cache madison <package name>
```
also tried `export FZF_DEFAULT_OPTS='--extended'` with no luck.

any chance to let fzf consider the levenshtein distance? or/and give words with many letter matches a higher weight than scattered matches?

https://en.wikipedia.org/wiki/Levenshtein_distance

**Comment by junegunn** [comment]
> any chance to let fzf consider the levenshtein distance? or/and give words with many letter matches a higher weight than scattered matches?

Thanks for the suggestion, but it's not going to happen. fzf is highly optimized for the current search/ranking algorithm and I'm not interested in adding, optimizing, and maintaining a different algorithm which is an awful lot of work.
