### ISSUE TITLE
How can I rebind TAB/SHIFT+TAB to CTRL+J/CTRL+P and vice versa?

### ISSUE THREAD

**Issue by irexiz** [junegunn/fzf#2273]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [x] fish
    
## Problem / Steps to reproduce
How can I swap binds for  multiple select with next/previous? It's very unergonomic for me to use ctrl+p/j, and ctrl+k doesnt work for "up"

**Comment by junegunn** [comment]
So you read through the man page. Found no clue?
