### ISSUE TITLE
Issue with preview for having white background on the highlighted line

### ISSUE THREAD

**Issue by nadeemkhedr** [junegunn/fzf#2274]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish
    
## Problem / Steps to reproduce
This is more of a question than an issue

I am using nvim with fzf, when running `Rg` with this binding:
```
command! -bang -nargs=* Rg
  \ call fzf#vim#grep(
  \   'rg --column --line-number --hidden --smart-case --no-heading --color=always '.shellescape(<q-args>), 1,
  \   <bang>0 ? fzf#vim#with_preview({'options': '--delimiter : --nth 4..'}, 'up:60%')
  \           : fzf#vim#with_preview({'options': '--delimiter : --nth 4.. -e'}, 'right:50%', '?'),
  \   <bang>0)
```

Getting this result:
![2020-12-01_15-27-36](https://user-images.githubusercontent.com/180256/100746896-00941280-33ea-11eb-872b-c417658b5326.png)

This only happens when running grep with fzf (white bg line highlight) tried to customize all terminal colors, nothing affected it 

I am sure there is a `--color` option I just have no idea which one (tried a lot of different options already)  

This is on `iterm2` with `xterm-256color` (also tried `Hyper` have the same result)

**Comment by junegunn** [comment]
- Do you have `bat` installed?
    - If so, do you see the same colors when you run `ls -al | bat --highlight-line=1 --pager=never --style=numbers` on your terminal?
    - If not, do you have any of `highlight`, `coderay`, or `rougify`?

**Comment by nadeemkhedr** [comment]
@junegunn the issue was from `bat` thanks so much man, now its fixed!
