### ISSUE TITLE
User defined placeholders

### ISSUE THREAD

**Issue by przepompownia** [junegunn/fzf#2276]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish
    
## Problem / Steps to reproduce
Let's assume that I would like to load to fzf a grep command with possible reloading only one of its parameters: case sensitivity or pattern matching:
```vim
  call fzf#vim#grep(a:Cmd(shellescape(a:query), a:useFixedStrings, a:ignoreCase), 0, fzf#vim#with_preview({
        \ 'dir': a:root,
        \ 'options': [
        \ '--phony',
        \ '--multi',
        \ '--query', a:query,
        \ '--bind', 'change:reload:' . a:Cmd('{q}', a:useFixedStrings, a:ignoreCase),
        \ '--bind', 'ctrl-f:reload:' . a:Cmd('{q}', a:useFixedStrings, a:ignoreCase), " toggle fixed strings/regex only
        \ '--bind', 'ctrl-i:reload:' . a:Cmd('{q}', a:useFixedStrings, a:ignoreCase), " toggle case sensitive/insensitive only
        \ ]
        \ }), a:fullscreen)
```
I did not found any way how to use any existing fzf feature to achieve this goal. 

It seems that we need to have user defined placeholders, something like 
```vim
  call fzf#vim#grep(a:Cmd(shellescape(a:query), a:useFixedStrings, a:ignoreCase), 0, fzf#vim#with_preview({
        \ 'dir': a:root,
        \ 'options': [
        \ '--phony',
        \ '--multi',
        \ '--query', a:query,
        \ '--user-placeholder', '{bool:user-ignoreCase='. a:ignoreCase ? 1 : 0 .'}'
        \ '--user-placeholder', '{bool:user-fixedStrings='.  a:useFixedStrings ? 1 : 0 .'}'
        \ '--bind', 'change:reload:' . a:Cmd('{q}', a:useFixedStrings, a:ignoreCase),
        \ '--bind', 'ctrl-f:reload:' . a:Cmd('{q}', '{user-fixedStrings=!user-fixedStrings}', '{user-ignoreCase}'), " toggle fixed strings/regex only
        \ '--bind', 'ctrl-i:reload:' . a:Cmd('{q}', '{user-fixedStrings}', '{user-ignoreCase=!user-ignoreCase}'), " toggle case sensitive/insensitive only
        \ ]
        \ }), a:fullscreen)
```
I am aware that it may be not easy to invent any good form.

**Comment by junegunn** [comment]
I don't think it's a good idea to implement this in fzf. You probably want to manage the variable states in an external file and make your script read and update it as your command progresses.
