### ISSUE TITLE
Command failed: ag -g

### ISSUE THREAD

**Issue by DMalladi** [junegunn/fzf#2278]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

1. Download and install Neovim
2. Install FZF on machine, from github. 
version that I installed is 0.24
3. Install FZF plugin using vim-plug 
4. open the nvim editor, and execute :FZF command 
![image](https://user-images.githubusercontent.com/41450470/101416475-911d9780-38af-11eb-9c91-0e5071816244.png)

Here are a few details, that could help us to know the issues
![image](https://user-images.githubusercontent.com/41450470/101416591-cc1fcb00-38af-11eb-9f14-d581c17d1c9b.png)

I am new to Linux environment, so apologies in advance if I ask you any silly questions.
Thank You in advance

**Comment by junegunn** [comment]
It means your `$FZF_DEFAULT_COMMAND` is set to `ag -g ""`, and it is not working. You should check if the command runs as expected on your shell.

**Comment by DMalladi** [comment]
Hello, 

Thank you for message, 
I tried it, executing fzf command from shell, and it is working, I have attached a screen below.
![image](https://user-images.githubusercontent.com/41450470/101535862-d9e05980-395e-11eb-9a26-c071768aae67.png)

**Comment by DMalladi** [comment]
I made below changes to my init.vim file, and it start working.
let $FZF_DEFAULT_COMMAND=""
![image](https://user-images.githubusercontent.com/41450470/101537666-828fb880-3961-11eb-92c6-7eef05d7c986.png)
it is working as per expected, now.

Thank you for your help!!!
