### ISSUE TITLE
Allow reading from files when in scripting mode?

### ISSUE THREAD

**Issue by thomasjm** [junegunn/fzf#2279]
- [X ] I have read through the manual page (`man fzf`)
- [X ] I have the latest version of fzf
- [X ] I have searched through the existing issues

## Info

- OS
    - [X ] Linux
- Shell
    - [X ] zsh
    
## Problem / Steps to reproduce

I would like to write a program that invokes `fzf` as a script by passing the "--filter" argument, and collects the output lines. Unfortunately, `fzf` checks if it is connected to a TTY and changes its behavior to not read from files anymore when there isn't one:

https://github.com/junegunn/fzf/blob/master/src/reader.go#L100-L114

This was surprising/seems like an unnecessary restriction that seriously hampers scripting. The manual says about `--filter` that `When used with --no-sort, fzf becomes a fuzzy-version of grep.` But grep doesn't stop working when not connected to a TTY. So I'm wondering if `fzf` could behave the same in either case.

**Comment by junegunn** [comment]
I don't understand what your problem is.

```sh
# Works as expected
seq 100 | fzf -f 55

# Works as expected
cat <(seq 100 | fzf -f 55)

# Let's define the default command that is used to generate the input list when fzf is not reading from STDIN
export FZF_DEFAULT_COMMAND='seq 100'

# Works as expected
fzf -f 55

# Works as expected
cat <(fzf -f 55)
```

**Comment by thomasjm** [comment]
Hi @junegunn -- all of those examples work properly because you're running them in a shell, which has a TTY.

But not every program running on your system is attached to a TTY. If I'm running some such process on my machine, and that process tries to launch `fzf` using normal system calls, then the `util.IsTty()` call I linked will return false and different behavior will result.

**Comment by junegunn** [comment]
Hmm, I guess you're in this situation:

```shell
# Works as expected
FZF_DEFAULT_COMMAND='seq 100' bash -c 'fzf -f 55'

# Empty result
FZF_DEFAULT_COMMAND='seq 100' bash -c 'fzf -f 55' < /dev/null
```

In the latter case, fzf sees that the standard input is not tty, so it decides to read from `/dev/null` which gives nothing.

This is unfortunate but we can't remove the existing TTY check as we have to differentiate between `fzf` and `some-command | fzf`. So you have to explicitly specify the source command to make it work.

```shell
# Works
bash -c 'seq 100 | fzf -f 55' < /dev/null
```

grep is not any different in this regard.

```shell
# Gives 55
bash -c 'seq 100 | grep -f 55' < /dev/null

# Empty result
bash -c 'grep 55' < /dev/null
```

**Comment by junegunn** [comment]
FYI, you can find the default command used here:

https://github.com/junegunn/fzf/blob/00f4551a7b9edda202f15f43e694f949f04927de/src/constants.go#L59-L65

**Comment by thomasjm** [comment]
Hmm, are you sure there's no other way to differentiate the case where reading from stdin is desired? I think that the `isatty` call is not really it...

For example, many tools I've seen pass a special flag like `--` to cause it to read from `stdin`.

`grep` is like this, it only reads from `stdin` if you pass a single dash `-`, or if no file arguments are given: https://linux.die.net/man/1/grep. This allows you to use grep normally from a non-TTY script.

**Comment by junegunn** [comment]
Technically, fzf is reading from STDIN just like grep, only that STDIN is `/dev/null`.

**Comment by junegunn** [comment]
Using a Unix filter without any input doesn't make much sense in scripting contexts.

```sh
#!/bin/bash

# What do we expect here?
head -10

# Grep foo from what?
grep foo
```

And fzf here is working just like other filter programs in non-TTY environments. The only thing we miss here is the default find command that many users override with a custom `$FZF_DEFAULT_COMMAND`.

```sh
$SHELL -c "$FZF_DEFAULT_COMMAND" | grep foo
$SHELL -c "$FZF_DEFAULT_COMMAND" | fzf -f foo
```

Like I said above, I don't think we can remove the TTY check, but if you have a better idea to address the different use cases without breaking backward compatibility, please open a pull request.

**Comment by thomasjm** [comment]
> Using a Unix filter without any input doesn't make much sense in scripting contexts.

Well, both `head` and `grep` "normally" accept command line arguments to tell them what file(s) to process, and they only use `stdin` when those are not provided. The difference with `fzf` is that it doesn't take a directory argument by default (or at all) --  the directory it uses is implicitly the current working directory. So it can't currently differentiate this way.

To be a good Unix-y tool, it should be possible to achieve the "normal behavior" even when a TTY isn't attached. In this case, the "normal behavior" seems to be searching the files in the current working directory.

If you don't want to change the default `--filter` behavior, what about a flag like `--nostdin` that forces it to read from files rather than stdin?

**Comment by junegunn** [comment]
> If you don't want to change the default --filter behavior

What exactly are you proposing here? Can you make `--filter` option still work as expected in the following scenarios?

```sh
export FZF_DEFAULT_COMMAND='echo foobar55'

# Should print foobar55
fzf --filter foo

# Shouls print 55, not foobar55
seq 100 | fzf --filter 55
```

**Comment by junegunn** [comment]
> they only use stdin when those are not provided.

I don't see what point you're trying to make here. You can provide any input to fzf using pipe or redirection.

```sh
ls -al | fzf
fzf < <(ls -al)

# or any file
fzf < ~/.bashrc
```

This is fundamentally not any different from how the other tools take path arguments. The only difference is that you want to omit input to fzf, while you don't expect to do so with the other tools.

You should see a bare "fzf" command just a shortcut for terminal users who don't want to repeatedly type input command, and fzf is just fine without it.

**Comment by junegunn** [comment]
> what about a flag like --nostdin that forces it to read from files rather than stdin?

That's an option, but it feels fairly niche to me, as the only benefit is that it saves you from typing the default command that generates the input. Is there any reason you don't want to write the input command? Can you elaborate on your use case?

```sh
fd --type f | fzf -f foo
```

**Comment by junegunn** [comment]
I agree that this inconsistency is unfortunate but I'd like to see if there's a smarter way to handle this without adding an esoteric option that very few will ever use.

```sh
# Works as expected
FZF_DEFAULT_COMMAND='seq 100' bash -c 'fzf -f 55'

# Empty result
FZF_DEFAULT_COMMAND='seq 100' bash -c 'fzf -f 55' < /dev/null
```

**Comment by thomasjm** [comment]
Well, for what it's worth, I think a good and Unix-like scripting mode would look like this:

```bash
# Important: none of these depend on a TTY being present or not

fzf --filter=foo . # Searches .
fzf --filter=foo DIR # searches DIR

fzf --filter=foo # Tries to search stdin, finds nothing and exits with code 1
search_command | fzf --filter=foo - # Searches stdin (note the dash)
search_command | fzf --filter=foo # Searches stdin
```

The proposal here would be to add a required directory command in scripting mode, and search stdin if it's not provided. This would bring it more in line with `head`, `grep`, etc. It would only take effect when scripting mode is activated with `--filter`.

Alternatively, if you want to change nothing about the current behavior, adding a new `--nostdin` flag would at least provide a way for non-TTY processes to get the normal file search behavior.

(You suggested pasting the default find command and then piping it to `fzf`, but that's pretty user-unfriendly, because it's super long and I'd have to dig through the code to find it. Imagine if you had to type a long find command before being able to use `grep`...)

Anyway, I ultimately decided not to use `fzf` from a script because of other issues (I need a way to limit results--in particular I'd like it to stop searching once it already finds N good candidates so it doesn't spend forever searching a large directory). But hopefully these comments can be helpful to you.

**Comment by junegunn** [comment]
>  I ultimately decided not to use fzf from a script

Good call. fzf was originally designed to be an interactive program and `--filter` option was an afterthought and I don't think it's really useful.

**Comment by junegunn** [comment]
> because it's super long and I'd have to dig through the code to find it.

I just want to point out that there's absolutely no reason you should use the exact command. You can just use `ls | fzf`, or `find . | fzf`.

> Imagine if you had to type a long find command before being able to use grep...

Well, you do have to type some kind of find command if you want to grep a "path".
