### ISSUE TITLE
Hosts completion: ignore null hosts

### ISSUE THREAD

**Issue by lucianf** [junegunn/fzf#228]
I think it would be good to configure the hosts completion (telnet/ssh) to ignore null hosts (`0.0.0.0`) from `/etc/hosts`, in case people are using them for ad blocking.  I can't see any reason why anyone would use this for anything else and would want them to work in a tool like `fzf`.

Obviously this doesn't apply to `127.0.0.1` since that one actually has lots of valid business cases :)

Sorry for not doing a pull request but I'm lazy to clone just for this.

So I'm suggesting:

`shell/completion.bash:`

```bash
_fzf_telnet_completion() {
  _fzf_list_completion '+m' "$@" << "EOF"
  \grep -v '^\s*\(#\|$\)' /etc/hosts | grep -v '^0\.0\.0\.0' | awk '{if (length($2) > 0) {print $2}}' | sort -u
EOF
}

_fzf_ssh_completion() {
  _fzf_list_completion '+m' "$@" << "EOF"
    cat <(cat ~/.ssh/config /etc/ssh/ssh_config 2> /dev/null | \grep -i ^host | \grep -v '*') <(\grep -v '^\s*\(#\|$\)' /etc/hosts | grep -v '^0\.0\.0\.0') | awk '{print $2}' | sort -u
EOF
}
```

**Comment by junegunn** [comment]
Thanks for the suggestion.
