### ISSUE TITLE
key-binding.zsh error message when source zshrc

### ISSUE THREAD

**Issue by chaosma** [junegunn/fzf#2280]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish
    
## Problem / Steps to reproduce
MacOS: Catalina 10.15.7
zsh: zsh 5.7.1 (x86_64-apple-darwin19.0)
fzf: 0.24.4 (00a3610)

I remove the old fzf and reinstall fzf again. After I run
`source ~/.zshrc`

I got the following error:
```
-bash: /Users/name/.fzf/shell/key-bindings.zsh: line 22: syntax error near unexpected token `)'
-bash: /Users/name/.fzf/shell/key-bindings.zsh: line 22: `  () {'
```

**Comment by junegunn** [comment]
> `-bash:`

You're loading zsh file from bash.

**Comment by chaosma** [comment]
Got it. Thanks! Although I use `chsh -s /bin/zsh`, but I need exit the terminal and open it again.
