### ISSUE TITLE
I would like to make fzf return the path/name of the file to use in a script 

### ISSUE THREAD

**Issue by ndavidpsi** [junegunn/fzf#2283]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [ ] Mac OS X
    - [x] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish
    - [x] cmd
    
## Problem / Steps to reproduce

It's self explanatory but suppose I'm writing a C++ script, how would I retrieve the path after using FZF

**Comment by rayiik** [comment]
it really depends on the command your using to populate the search parameter however you can export it as a variable you can redirect it to a tmp file save it as an array. 
```bash
search-command | filter-command | fzf >file.tmp;
command-that-uses-path file.tmp

search-command | filter-command | fzf | cat >> file.tmp
command-that-uses-path file.tmp
# if command is not able to read directly from file you can either
command </path/to/tmpfile
command <<<"$(command-that-reads-file-to-commandline file.tmp)"
command-that-reads-file-to-commandline | command

__tmpcommand="$(search-command | filter-command | fzf)"
export __tmpcommand
command-that-uses-path "${__tmpcommand}" 
```
those are the main things that come to mind

**Comment by ferdinandschober** [comment]
You could use the command dirname. It gives you the name of the directory for a given file.
So something like `cd $(fzf | xargs dirname)` could work though I don't know exactly what you are trying to do.

**Comment by junegunn** [comment]
The question isn't clear enough. You might want to read through the README page to better understand the concepts.
