### ISSUE TITLE
RFE[vim]: Could fzf be used even for spell suggestions?

### ISSUE THREAD

**Issue by mcepl** [junegunn/fzf#2284]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf (0.24.3, but I don’t think anything changed in this matter)
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish
    
## Problem / Steps to reproduce
I have this tiny plugin for vim, which uses fzf for spellchecking suggestions:
```vim
function! FzfSpellSink(word)
  exe 'normal! "_ciw'.a:word
endfunction
function! FzfSpell()
  let suggestions = spellsuggest(expand("<cword>"))
  return fzf#run({'source': suggestions, 'sink': function("FzfSpellSink"), 'down': 10 })
endfunction
nnoremap z= :call FzfSpell()<CR>
```
but I think it would be better to include it directly into fzf.vim plugin (so that it uses popup windows etc.). What do you think?

**Comment by junegunn** [comment]
> (so that it uses popup windows etc.)

It doesn't have to be included in fzf.vim to use popup windows. Try this:

```vim
return fzf#run(fzf#wrap({'source': suggestions, 'sink': function("FzfSpellSink")}))
```

You can learn what `fzf#wrap` does in https://github.com/junegunn/fzf/blob/master/README-VIM.md#fzfwrap

**Comment by mcepl** [comment]
That works as well, thank you. However, I thought that supporting spell-suggestions may be so widespread (and so simple for you), that it could very well be included in vim.fzf itself.

**Comment by junegunn** [comment]
Thanks for sharing the code. I'm not currently interested in adding more commands to fzf.vim project due to the maintenance burden, and I've been encouraging users to build their own commands or to publish third-party plugins.

See: https://github.com/junegunn/fzf.vim#rationale

**Comment by shmup** [comment]
@junegunn I know this is closed, but people will end up here looking for dictionary help, and there is one missing piece I think would be cool to solve.

Currently, the word list comes up in a popup but you have no context on what the word was you were trying to replace. The default `z=` shows this:

```
Change "Dafault" to:
 1 "Default"
 2 "DA fault"
 3 "Fault"
 4 "Defaults"
```

And the popup of course looks like:

![image](https://user-images.githubusercontent.com/118710/180247431-4fd1e435-74e0-4ece-8b9d-6d396cdd1809.png)

I _think_ a good "fix" here is to change the prompt, like how `:History` works:

![image](https://user-images.githubusercontent.com/118710/180247930-70163dc1-37cf-4372-80e0-10b1b9223a53.png)

Here's my attempt, with no luck:

`return fzf#run(fzf#wrap({'prompt': expand("<cword>"), 'source': suggestions, 'sink': function("FzfSpellSink")}))y`

I'm doing something wrong, I think. Any thoughts? Also open to an alternative idea, unsure if the popup can have a "title" up top, a makeshift "bar".
