### ISSUE TITLE
fzf waits for input stream to complete even after a selection has been made

### ISSUE THREAD

**Issue by lakshayg** [junegunn/fzf#2288]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [x] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

```
for i in `seq 1 10`; do echo $i; done > /tmp/numbers.txt
mkfifo /tmp/fifo.txt
cat /tmp/numbers.txt /tmp/fifo.txt | fzf
```
On selecting an option from the list, fzf will print it to the terminal but will not exit unless something is written to `/tmp/fifo.txt`. Naively, I expect that once the user has made a selection, fzf does not need to see the rest of the input. I'm not sure if this is a fzf problem of is this is a quirk of the shell.

**Comment by junegunn** [comment]
This is expected. Replace fzf with a different filter program and the same happens.

```sh
cat /tmp/numbers.txt /tmp/fifo.txt | head -1
```

A workaround would be to use process substitution:

```sh
fzf < <(cat /tmp/numbers.txt /tmp/fifo.txt)
```

**Comment by lakshayg** [comment]
Thanks for the response, however, this solution does not work as expected either. Although fzf exits, if I echo something to `/tmp/fifo.txt`, it does not appear in fzf for filtering

**Comment by junegunn** [comment]
Works for me.

**Comment by lakshayg** [comment]
I meant echoing to `/tmp/fifo.txt` after the fzf process has been started.

```
mkfifo /tmp/fifo.txt
fzf < <(cat /tmp/numbers.txt /tmp/fifo.txt)
echo hello > /tmp/fifo.txt
```

**Comment by junegunn** [comment]
Yes, that works as expected. It's a standard shell operation so I don't see why it wouldn't work with fzf.
