### ISSUE TITLE
FZF can't return to terminal prompt after pressing CTRL-Z during command history selection.

### ISSUE THREAD

**Issue by zoj613** [junegunn/fzf#2289]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

Fuzzy finder freezes the terminal indefinitely when I press CTRL-Z after opening the command history with CTRL-R. The only way to stop the freeze is to kill the fzf process.

I use termite, if that helps.

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish
    
## Problem / Steps to reproduce
1) do CTRL-R to open the command history
2) without selecting a command press CTRL-Z
3) terminal refuses to go back to the prompt

**Comment by junegunn** [comment]
Yes, I can reproduce the problem. And the only workaround I've found is to disallow CTRL-Z by setting `--bind ctrl-z:ignore`. Maybe it's something we should do?

**Comment by junegunn** [comment]
Couldn't find a better way, so I updated the code to disable CTRL-Z altogether. Thanks for the report.
