### ISSUE TITLE
Use fzf many times in the same query

### ISSUE THREAD

**Issue by poul1x** [junegunn/fzf#2294]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux (WSL)
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

I need to use fzf multiple times:
```
<some query> | fzf | <some actions> | fzf | <final actions>
```

The following queries work well:
```
echo "aaa" | fzf
echo "aaa\nbbb" | fzf
```
But this query works not as expected and breaks the view of my zsh

```
# Expected to work normally giving result of ('aaa' | 'bbb')
echo "aaa\nbbb" | fzf | fzf
```
Instead of normal result I get this (stucked):
![image](https://user-images.githubusercontent.com/31695750/102902594-46d81100-4480-11eb-933d-92406c2a4691.png)

Fzf is not supposed to be used like that?

**Comment by junegunn** [comment]
That's two fzf processes rendering simultaneously on the screen. You have to make the second fzf wait until the first one finishes.

```sh
# The second fzf will not start rendering until the input stream is complete
echo -e "aaa\nbbb" | fzf | fzf --sync

# --no-clear can be used to avoid flickering of the screen
echo -e "aaa\nbbb" | fzf --no-clear | fzf --sync
```

Or you can just start fzf one by one in your script.

```
RESULT=$(echo -e "aaa\nbbb" | fzf)
fzf <<< "$RESULT"
```
