### ISSUE TITLE
Different values of --nth for different lines?

### ISSUE THREAD

**Issue by srsudar** [junegunn/fzf#2297]
- [x] I have read through the manual page (`man fzf`)
- [?] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

Is there any way to get fzf to behave as if `--nth` had been passed different values for different lines?

I am trying to build a way to complete flags from previously run commands. Imagine that I have a history file like the following:

```
foo --foo_1 --foo_2 --foo_3=foo
bar --bar_1 --bar_2=bar --bar_3
```

I would like to generate the following lines from this file. fzf would be searching and outputting only the parts in `[[ ]]`:

```
foo [[--foo_1]] --foo_2 --foo_3=foo
foo --foo_1 [[--foo_2]] --foo_3=foo
foo --foo_1 --foo_2 [[--foo_3=foo]]
bar [[--bar_1]] --bar_2=bar --bar_3
bar --bar_1 [[--bar_2=bar]] --bar_3
bar --bar_1 --bar_2=bar [[--bar_3]]
```

I think that using some trickery (like `--nth` and `--with-nth`) and post processing I can get close to what I want. 

Ideally there would be some way that I could tell fzf to match on different field index expressions for different lines. That way I could set `--nth=X` for the line that I need.

Does anyone know how I might accomplish such a thing? I've considered prepending, something like:

```
[[--foo_1]] foo --foo_1 --foo_2 --foo_3=foo
etc
```

There I could just use `--nth=1`. I worry I lose the context there though. Is there a way to do such a thing?

**Comment by junegunn** [comment]
One way to achieve that is to reformat your input with non-breaking spaces that are visually indistinguishable from normal spaces like so:

```sh
echo $'foo\u00a0--bar\u00a0--baz --qux' | fzf --delimiter $'\u00a0' --nth 2 --query '^--bar$'
```

**Comment by srsudar** [comment]
That was helpful, thank you. I'm close to what I want, but I might be struggling to get the escaping right. I don't see a `--debug` or `--verbose` or `--dry-run` flag in the man pages, so I'm not sure what values `fzf` is getting. I could build my own binary and print it out, but in case I'm going wrong somewhere else I thought I'd try here first.

When piped to `fzf --delimiter $'\u00a0' --nth 1`, the delimiter behaves like you show above. For example, here only the word before the non-breaking space is searchable (I'm using `awk` and that format because this is what I have to do in my script):

```
awk 'BEGIN { print "searchable\xC2\xA0 this is not searchable" }' | fzf --delimiter $'\u00a0' --nth 1
```

When passed as `FZF_DEFAULT_OPTS`, which I'm trying to use inside a function, the whole print statement is searchable, as if the delimiter isn't applied:

```
awk 'BEGIN { print "searchable\xC2\xA0 also searchable but I would rather it were not" }' | FZF_DEFAULT_OPTS="--delimiter $'\u00a0'" fzf --nth 1
```

Anything obviously wrong there? I've tried numerous combinations of `\$\\\u00a0` etc with no luck. Is there anything special to consider with escaping that you've seen before? Alternatively, can I inspect what value fzf is getting somehow?

**Comment by junegunn** [comment]
`FZF_DEFAULT_OPTS=$'--delimiter \u00a0' fzf --nth 1` should work.

**Comment by srsudar** [comment]
Yikes, that seems obvious in retrospect. Sorry. That was the magic piece that I was missing, though. I'm putting this here in case anyone else goes searching through the issues for something like this. I can submit a PR to add this to the wiki if you think it would be of interest.

This binds (in `zsh`) `<c>-q` (which in my setup is useless afaict, because I've disabled `<c>-s` scroll lock) to insert previously used flags for the entered command.

This will be a big help on some of the test scripts my team runs, which have dozens of flags, none of which are obvious, most of which I've used at some point in the past. Another will be how to start vim without a vimrc file, which I know is something like `-U none` or `-u none` but can never remember without looking it up. Now I can do `vim <c-q>` , type `none`, and the magic of fzf reminds me that it is `-u NONE`. Enter inserts it into the command line.

Currently it only matches the first token on the command line, so `git checkout <c-q>` and `git remote <c-q>` will generate the same list of flags. I think it would be better if it did something where `<c-q>` matched the first token (eg `git checkout` -> `git`), `<c-q>` again matches two tokens (eg -> `git checkout`) etc, but I couldn't figure out how to do that with `--bind`. If I find myself missing it I might try again.

Another neat option might be `--bind 'ctrl-r'` somehow to select a different prefix to match against than the one you had previously typed. Maybe the same `--output=long/annoying-file` flag is shared across commands, eg. Beyond my abilities or needs for the moment, though.

```
# This generates a list of flags that have previously been used in history
# commands, trying to intelligently parse values for reuse on the prompt. For
# example, with the following history entry files (as shown on zsh):
#
# 1 foo --test --bar=val
# 2 foo -f 123 --bar val
#
# `_find_flags foo` should return:
#
# --test
# --bar
# --bar=val
# -f
# -f 123
# --bar val
_find_flags() {
  # $1 is passed to the function and should be the command.
  local match_prefix=$1
  fc -rl 1 | \
    # strip leading command number
      sed 's/^\s*[0-9]*\*\?\s*//' | \
      rg "^${match_prefix}" --color=never --no-line-number |
awk -v match_prefix=${match_prefix} ' { for (i = 1; i <= NF; i++) {
  flag = ""
  is_value = ""
  maybe_value = ""

  if ($i ~ /^--?[a-zA-Z0-9]/) {
    # Then it looks like a flag.
    split($i, parts, "=")
    if (parts[2] != "") {
      # It is something like --flag=value
      flag = parts[1]
      is_value = parts[2]
    } else {
      # It is something like -f, and might be -f val.
      flag = $i
      maybe_value = $(i+1)
      if (maybe_value ~ /^--?[a-zA-Z0-9]/) {
        # Then we probably consumed another flag, eg `--foo` from
        # `--foo --bar=val`. Reset to empty string so we do not print that as an
        # option, as if `-foo` took the value `--bar=val`.
        maybe_value = ""
      }
    }

    # Colorize the part that we will not match in the output to make clear
    # we are matching only the leading flags.
    cmd_with_color = "\033[0;35m" $0 "\033[0m"

    # A note on the \xC2\xA0 strings here: we want a nbsp before the command so
    # that we can split easily and pull out the flag rather than the entire
    # line. This also allows us to tell fzf --nth and select only the first
    # column to search on. This is the nbsp notation that awk is able to output.
    # Fzf wants a \u00a0 format, which we use elsehwere, but note that these are
    # the same character.
    if (flag != "") {
      # Then we parsed a flag.

      # Print the flag itself.
      if (seen_arr[flag] != 1) {
        seen_arr[flag] = 1
        print flag "\xC2\xA0" cmd_with_color
      }

      if (is_value != "") {
        # The whole token is a valid value.
        if (seen_arr[$i] != 1) {
          seen_arr[$i] = 1
          print $i "\xC2\xA0" cmd_with_color
        }
      }
      if (maybe_value != "") {
        # We guessed at a value.
        output_with_guessed_value = flag " " maybe_value
        if (seen_arr[output_with_guessed_value] != 1) {
          seen_arr[output_with_guessed_value] = 1
          print flag " " maybe_value "\xC2\xA0 " cmd_with_color
        }
      }
    }
  } else {
    continue
  }
}
}'

}

_fzf_complete_fooflag() {
  _fzf_complete --ansi --multi -- "" "$@" < <(_find_flags)
}

# CTRL-Q - Paste the selected flags into the command line. Copied from CTRL-T
# bindings shown here:
# https://github.com/junegunn/fzf/blob/master/shell/key-bindings.zsh
__flagsel() {
  local match_prefix=`echo ${BUFFER} | cut -d ' ' -f 1`
  local cmd="_find_flags ${match_prefix}"
  setopt localoptions pipefail no_aliases 2> /dev/null
  local item
  # Need to set this outside the surrounding string to enable $'' notation so
  # fzf is able to interpret the delimiter correctly.
  local delimiter_arg=$'--delimiter \u00a0'
  eval "$cmd" | FZF_DEFAULT_OPTS="--height ${FZF_TMUX_HEIGHT:-40%} --prompt='${match_prefix}> ' ${delimiter_arg} --nth 1 --reverse --multi --ansi $FZF_DEFAULT_OPTS $FZF_CTRL_T_O>
    echo -n "${item}" | awk -F '\xC2\xA0' '{print $1}'
  done
  local ret=$?
  echo
  return $ret
}

fzf-flag-widget() {
  LBUFFER="${LBUFFER}$(__flagsel)"
  local ret=$?
  zle reset-prompt
  return $ret
}
zle     -N   fzf-flag-widget
bindkey '^Q' fzf-flag-widget
```
