### ISSUE TITLE
[zsh-completion] Known issues

### ISSUE THREAD

**Issue by junegunn** [junegunn/fzf#230]
Bugs:
- [x] `~USERNAME**<TAB>`
- [x] `~INVALID_USERNAME**<TAB>`
    - nonomatch
- [x] Fall back to default completion
    - Need to see what is currently mapped to `^I`. it may not be `expand-or-complete`
    - `bindkey '^I' | awk '{print $2}'`
- [x] `foo\ bar**<TAB>`
- [x] `setopt vi` resets TAB binding from fzf
    - I can't think of any way to handle this. We'll just have to tell the users about it.
    - https://github.com/junegunn/fzf/wiki/Fuzzy-completion

Enhancements:
- [x] Empty trigger sequence #232
- [x] Custom bindkey #232
```sh
export FZF_COMPLETION_TRIGGER=''
bindkey '^T' fzf-completion
bindkey '^I' $fzf_default_completion
```

**Comment by tiziano88** [comment]
Thanks for all this @junegunn ! Also I think we should add support for configuring a different bound key and having no trigger at all. Specifically, the use case I'd like to support is: start writing a path name, use tab completion as usual up to a certain point, and then use a different shortcut (e.g. <kbd>CTRL</kbd>+<kbd>P</kbd>) to trigger fzf from that point on (without ever typing a specific trigger).
