### ISSUE TITLE
Delimiter not considered during preview unless default (tab character)

### ISSUE THREAD

**Issue by curiositycasualty** [junegunn/fzf#2301]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

Only when the `--delimiter` flag is omitted (and therefore the default, "tab") does `fzf` allow for tab-delimited field separation in the `--preview` command. Interestingly, neither other `-d` values nor explicitly setting `-d` to `$'\n'` work as expected.

- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

"CSV" and therefore newline delimited input with comma delimiter flag supplied to `fzf`.

```bash
echo -e 'header1,header2\nfield1,field2'                | fzf -d=','   --header-lines 1 --preview='echo {1}'
```

<img width="904" alt="Screen Shot 2020-12-28 at 12 30 42 PM" src="https://user-images.githubusercontent.com/310287/103241844-453b9c80-4909-11eb-9234-238ff568e8ab.png">

"CSV" / newline delimited input transformed to be tab separated, with tab delimiter flag supplied to `fzf`.

```bash
echo -e 'header1,header2\nfield1,field2' | tr ',' $'\t' | fzf -d=$'\t' --header-lines 1 --preview='echo {1}'
```

<img width="906" alt="Screen Shot 2020-12-28 at 12 31 08 PM" src="https://user-images.githubusercontent.com/310287/103241867-4ff63180-4909-11eb-9ce1-af6635d6ee78.png">

"CSV" / newline delimited input transformed to be tab separated, with no delimiter flag supplied to `fzf`.

```bash
echo -e 'header1,header2\nfield1,field2' | tr ',' $'\t' | fzf          --header-lines 1 --preview='echo {1}'
```

<img width="906" alt="Screen Shot 2020-12-28 at 12 31 27 PM" src="https://user-images.githubusercontent.com/310287/103241874-55537c00-4909-11eb-9da9-229f56b06c78.png">

**Comment by junegunn** [comment]
When you write `-d=,`, `=,` becomes the delimiter.

These are the correct ways to write it:

* `-d,`
* `-d ,`
* `--delimiter ,`
* `--delimiter=,`

**Comment by curiositycasualty** [comment]
Thanks for the prompt reply!

**Comment by phortonssf** [comment]
> When you write `-d=,`, `=,` becomes the delimiter.
> 
> These are the correct ways to write it:
> 
> * `-d,`
> * `-d ,`
> * `--delimiter ,`
> * `--delimiter=,`

I was not able to replicate this
FZF version:

![image](https://user-images.githubusercontent.com/23040285/150697264-abcaed8f-689b-43a0-875a-21dfeaf56758.png)
