### ISSUE TITLE
Feature request: Bindiable phony option (i know its been asked before but i thought i'd put it forward a different way with case uses)

### ISSUE THREAD

**Issue by rayiik** [junegunn/fzf#2303]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

I think this feature would be really beneficial (at least in my case and others im sure). I have a couple of scripts that generate lists of data that i don't want to manually scroll through (so regular search). The information i need is supplemented by the information in the context window. however my choices require additional imput beyond what the list generates. While i could replace query then type the additional information but this would cost me my spot in the preview information as i would no longer have a match. 

   Adding a bind-able option to toggle phony would give users the ability to manipulate the data execute:echo {q} to file while maintaining the information contained within the preview window without having to delete the query and retype the original query and  find their spot again. This would ad a whole new layer of scriptable manipulation that could have many case uses.

   **examples**

   You need to find an unknown piece of information in a log file, such as user name and time of access across several log files your list generates the log files based on matching types information and your previewing them and you want to send certain pieces of information out to another file or later use. the fuzzy search generates which logs to search and you can even sync and do a secondary search of each log file but say you need to pull several names out, but each name needs a not thats not produced by either populating search. --bind="key:execute(echo {q} >query.tmp)+phony+replace-query" add a note then call the query.tmp back and execute phony again to continue searching.

  Your using fzf a manpage viewer your searching topics you find what your looking for and you want to echo some items from a particular page out with additional information (ie doing research).

[![asciicast](https://asciinema.org/a/381783.svg)](https://asciinema.org/a/381783)

   You have a script that inverts fzf's functionality, your fzf search fuzzes the contents of preview and produces a list of files that match your fuzz search as it runs. before you print query our use you want to manipulate but as soon as you start typing your list disappears because there's no longer a match.

[![asciicast](https://asciinema.org/a/EE4PF7kBmQbWHFm3oHZEp4pjv.svg)](https://asciinema.org/a/EE4PF7kBmQbWHFm3oHZEp4pjv)

  My biggest case use though. I have a script that is populated by commands found in "$PATH" this is printed to the command line through a READLINE_LINE without executing my other binding generates flags that start with '-' based on manpages and help files i can print these to the command line, however some of these items require arguments on top of just the --command

[![asciicast](https://asciinema.org/a/lVahTHe08G5W9DjmukHsQ8oA3.svg)](https://asciinema.org/a/lVahTHe08G5W9DjmukHsQ8oA3)

   These are just a couple of the possibilities that could be achieved with a binding to switch phony on and off. If its not feasible manageable that's understandable i just thought I'd ask again but I think it would be a very useful feature that would add a lot of extra depth

**Comment by junegunn** [comment]
Some thoughts:

* If "phoniness" can be turned on and off dynamically, it may not be appropriate to call it "phony mode". It's more like pausing and resuming the search functionality. Pausing is actually what you need here. You don't want to lose the current search result when you turn on "phony" mode. You just want to pause the update. True "phony mode" would reset the current result and return the full input.
* Or "disabling" and "enabling" search update
* `pause`/`resume`/`--paused` or `disable`/`enable`/`--disabled`. I'm leaning towards the latter.
* We could render the query text in a different color when the search functionality is disabled.
     * e.g. `fzf --color input:#cccccc,disabled:#666666`

**Comment by rayiik** [comment]
yea pause defiantly sounds more like what im think something that could be bound to temporarily suspend the search filter would defiantly allow selecting something and manipulating it before sending it elsewhere :) thats a much better way to describe the functionality i was thinking of.

**Comment by rayiik** [comment]
Thanks incredible implementation time too

**Comment by kevinhwang91** [comment]
@junegunn I'm hoping fzf will add extra `disable-search` and `enable-search` event to rebind key on the fly, using `k` and `j` to up and down  is more comfortable than `ctrl-k` and `ctrl-j` when I regard fzf as a TUI selector, I know I'm lazy. :)

I'm not sure whether this request would broke the fzf's philosophy.

**Comment by NightMachinary** [comment]
@rayik Can you give me the code you use to browse manpages using this new feature? I didn’t quite understand you, but it seems interesting.

**Comment by rayiik** [comment]
@NightMachinary hey sorry missed this some how but it and many other examples are in my repo https://github.com/rayiik/Fzf-bash-ide-resource would be in the folder fzf/fzfscripts/fzf-man fmn and fzcom are the two main ones for man pages the ide that pulls commands from $PATH is the fzf-ide.bash and its in the fzf/ folder any questions my email is in most of the scripts so  shoot me a msg (school full time currently so i dont check git as often as id like but my email i do)
