### ISSUE TITLE
Specifying directory to search in.

### ISSUE THREAD

**Issue by rahul-goel** [junegunn/fzf#2310]
- [ x] I have read through the manual page (`man fzf`)
- [ x] I have the latest version of fzf
- [ x] I have searched through the existing issues

## Info

- OS
    - [x ] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ x] zsh
    - [ ] fish
    
## Problem / Steps to reproduce
I think this feature does not exist in fzf. I looked up the man page, stackoverflow and the issues over here but did not find a solution.

I am trying to use fzf inside a shell script by giving  the query as an argument `fzf --query="search_term"`. However, to make the search quick, I also wish to specify the directory in which to search for. Now, for the regular use of fzf(by calling it from the command line), it searches in the directory from which the call has been made. That is not the case with my shell script.

Could someone guide me on how to do this? Or if this functionality does not exist, could it be added?

**Comment by simaki** [comment]
Why don't you use this?

```
find [path] | fzf
```

**Comment by rahul-goel** [comment]
Okay!
The reason why I wanted to do this was to skip the use of the find command itself. That is because find command takes a lot of time to obtain the list of the directories. I guessed that fzf has some other mechanism internally to do this faster. However that isn't the case then.
