### ISSUE TITLE
unix-line-discard should be clear-query

### ISSUE THREAD

**Issue by lucmos** [junegunn/fzf#2311]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

The action `unix-line-discard` discards the previous characters, not the whole query line.
[![asciicast](https://asciinema.org/a/tbzBI0m29Vj1u1qKpmlD7IPvB.svg)](https://asciinema.org/a/tbzBI0m29Vj1u1qKpmlD7IPvB)

Actually while writing this issue I re-read the man page and found out about `clear-query`. That action seems to implement the unix-like behavior of `ctrl-u`, the feature I wanted to ask :)

I think the name of `unix-line-discard` is ambiguous

**Comment by junegunn** [comment]
The name came from bash:

```
$ bash -ci 'bind -p | grep discard'
"\C-u": unix-line-discard
```
