### ISSUE TITLE
Error during installation: Command substitutions not allowed

### ISSUE THREAD

**Issue by erickrf** [junegunn/fzf#2312]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [x] fish
    
## Problem / Steps to reproduce

When I run `(brew --prefix)/opt/fzf/install`, I get the error `fish: Command substitutions not allowed`
I have fish version 3.1.2; I just recently started using fish and I'm not very familiar with it yet.

**Comment by junegunn** [comment]
I'm not a fish user and I'm not familiar with it either. You can simply run the script with a POSIX compliant shell like so.

```sh
sh -c '$(brew --prefix)/opt/fzf/install'
```
