### ISSUE TITLE
[zsh completion] _fzf_complete corrupts prompt

### ISSUE THREAD

**Issue by KapJI** [junegunn/fzf#2317]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

When I close fzf completion windows for non paths e.g. for `kill`, `export` or `ssh` my prompt is corrupted.
It doesn't happen for paths completion though where `__fzf_generic_path_completion` is used.
This happens both for single and two line prompt.

https://user-images.githubusercontent.com/3767331/104121787-e2022f00-5338-11eb-9325-646dc40a76b2.mov

```
❯ zsh --version
zsh 5.8 (x86_64-apple-darwin19.6.0)
❯ fzf --version
0.25.0 (brew)
```
My antigen config:
```
antigen use oh-my-zsh
antigen bundle fzf
antigen theme romkatv/powerlevel10k
antigen apply
```

**Comment by junegunn** [comment]
I can reproduce the problem after installing antigen.

**Comment by csch0** [comment]
Thanks, it really solved it!!
