### ISSUE TITLE
Popup is transparent (not in a good way)

### ISSUE THREAD

**Issue by harris-chris** [junegunn/fzf#2319]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish
    
## Problem / Steps to reproduce
Any time I open the fzf search pop, I can see the file that I originally have open directly underneath it (see picture - the text of the open buffer underneath is intermingled with the fzf text). This makes it quite hard to use. I have previously used fzf successfully (with Arch) and this is something that has started since I moved to NixOs (with the same .vimrc). I've been told that it may be something to do with the terminal emulator, but it is occurring in all of my terminal emulators (xterm, alacritty and kitty). Thanks for any help!

![image](https://user-images.githubusercontent.com/46582472/104175909-3fd26c00-544a-11eb-9da2-31dd6745b9d4.png)

**Comment by junegunn** [comment]
I can't reproduce the problem. Can you check if you still have the issue with the following minimal vimrc?

```sh
vim -Nu <(curl https://gist.githubusercontent.com/junegunn/6936bf79fedd3a079aeb1dd2f3c81ef5/raw)
```

(https://gist.githubusercontent.com/junegunn/6936bf79fedd3a079aeb1dd2f3c81ef5/raw)

**Comment by harris-chris** [comment]
It works fine with your minimal vimrc, so I guess it's somehow being affected by another option/plugin in my vimrc - I can use a process of elimination to find out which. Thanks for your help!

**Comment by harris-chris** [comment]
Just in case anyone has the same problem the line `set winblend=30` was causing issues.
