### ISSUE TITLE
Its Possible Copy To Clipboard ?

### ISSUE THREAD

**Issue by pwndumb** [junegunn/fzf#2323]
- [x ] I have read through the manual page (`man fzf`)
- [ x] I have the latest version of fzf
- [ x] I have searched through the existing issues

## Info

- OS
    - [x ] Linux
    - [x ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ x] bash
    - [ x] zsh
    - [ x] fish
    
## Problem / Steps to reproduce

I cant copy select line in fzf to my clipboard. I Just try a lot of combinations but not work. The default key CTRL+R never work. . I use this option 
```bash
export FZF_DEFAULT_OPTS="
--layout=reverse
--info=inline
--height=80%
--multi
--preview-window=:hidden
--preview '([[ -f {} ]] && (bat --style=numbers --color=always {} || cat {})) || ([[ -d {} ]] && (tree -C {} | less)) || echo {} 2> /dev/null | head -200'
--color='hl:148,hl+:154,pointer:032,marker:010,bg+:237,gutter:008'
--prompt='∼ ' --pointer='▶' --marker='✓'
--bind '?:toggle-preview'
--bind 'ctrl-a:select-all'
--bind 'ctrl-y:execute-silent(echo {+} | xclip)'
--bind 'ctrl-e:execute(echo {+} | xargs -o vim)'
--bind 'ctrl-v:execute(code {+})'
"
```

**Comment by rogerdahl** [comment]
By default, `xclip` copies to X primary selection, `XA_PRIMARY` which is not where most apps expect to find clipboard data. To copy to the clipboard, `XA_CLIPBOARD`, with Ctrl-Y,  use `--bind 'ctrl-y:execute-silent(echo {+} | xclip -se c)'.

**Comment by imambungo** [comment]
[I use](https://github.com/imambungo/dotfiles/blob/b42292dccf566eec0e03479987b96774e9d6c11c/.functions#L198-L219) this:

```bash
# Use like normal fzf, but the output are copied to the clipboard
f()
{
	# https://stackoverflow.com/a/46726373/9157799
	if [ -p /dev/stdin ]  # if data was piped
	then
		stdin=$(</dev/stdin)
		echo "$stdin" | fzf "$@" | xclip
		fzo="$(xclip -o)"
	else
		fzo=$(fzf "$@")
	fi
	if [ "$fzo" != "" ]
	then
		echo -n "$fzo" | xclip -se c
		echo "$fzo"
	fi
}
```

You can use it like an alias of fzf e.g. `cat list | f`

**Comment by Sy3Omda** [comment]
@imambungo Thx for this tip but i mean here to high-lite desired text in terminal (terminator) and with key binding copy it or just `ctrl + shift + c` to copy it, all this by using only keyboard not mouse.

**Comment by imambungo** [comment]
@Sy3Omda I don't know how to do that in terminator but you can use tmux to do that.

**Comment by pnchinmay** [comment]
I tried several options and these worked out for me. This might help someone looking for these.

- Press CTRL-Y to copy path of selected option to clipboard
- Press CTRL-ALT-Y to copy contents of the selected option into clipboard'

```
--bind 'ctrl-y:execute(readlink -f {} | xclip -selection clipboard)'
--bind 'ctrl-alt-y:execute-silent(xclip -selection clipboard {})'
```

**Comment by dualfade** [comment]
Just adding here; Thank for all this !

This is working for me with xclip --
--bind 'ctrl-y:execute(readlink -f {} | echo -n {2..} | xclip -selection clipboard)'

**Comment by morags** [comment]
Similar to what @imambungo did, but for PowerShell:

```pwsh
function ffz {
    param (
        [Parameter(Mandatory, ValueFromPipeline)]
        [string]$Path
    )
    
    $res = Get-Content $Path | fzf
    if (-not [string]::IsNullOrEmpty($res)) {
        $res | Set-Clipboard
    }
}
```

You can add it to your PS profile and have it available throughout.
