### ISSUE TITLE
[Feature request] Add an option: always keep pattern 

### ISSUE THREAD

**Issue by jiming** [junegunn/fzf#2324]
For example I have an output
```
# pods in cluster prod
auth
email-3123412
...(very huge numbers of lines)
# pods in cluster dev
auth
email-xdjk322
...
```

I expect `fzf --alwaysKeep 'cluster' -q email` could filter result

```
# pods in cluster prod
email-3123412
# pods in cluster dev
email-xdjk322
```

Keep the `# cluster ...` will allow me to recognize the exact line I wanted to get.

Thanks a lot for this wonderful tool!

**Comment by junegunn** [comment]
This doesn't fit well with the execution model of fzf and it's really not trivial to implement it.
A common workaround is to reformat your input in a tabular layout.

```sh
fzf --reverse --height=10 --header-lines=2 --nth=-1 << EOF | awk '{print $NF}'
cluster | pod
--------------------------------
prod    | email-3123412
prod    | email-3123413
dev     | email-xdjk322
EOF
```

**Comment by jiming** [comment]
Thank you!
