### ISSUE TITLE
Allow custom exit code in actions

### ISSUE THREAD

**Issue by howardjohn** [junegunn/fzf#2327]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

I want to provide binds to execute various actions and exit fzf. This can be done with `ctrl-y:execute-silent(echo -n {} | xclip -selection c)+abort`, for example, to copy the selection. However, this exits with exit code 130 to the shell.

I would like these to not be treated as errors, so it would be nice to allow something like `abort(int exit code)` or a different action dedicated to 0 exit code (`exit`, `quit`, etc)

**Comment by junegunn** [comment]
A more traditional approach would be to use `--expect` option and have your script decide what to do with the output.

**Comment by howardjohn** [comment]
While I agree that would work for some cases, my idea was to have an action to open a file that would work everywhere I use fzf, by putting it in my default options. So --expect would work if I have a dedicated script and handle the output, but not on all calls to fzf.

This works pretty well today with the exception of the exit code - which is more of a minor annoyance for my exact use case

**Comment by junegunn** [comment]
That's a good point. Your execute binding isn't doing anything specific to a certain type of input, so having it in the default options makes sense.

**Comment by junegunn** [comment]
Hmm, on second thought, I don't think we need this.

Normally, fzf would print the selected entry and the script invoking it will proceed with the output. But when you do `execute-silent(echo -n {} | xclip -selection c)+abort`, fzf terminates without printing the current match. So it makes more sense that fzf exits with a non-zero code so that the caller knows that it shouldn't proceed. Not printing anything and exiting with 0 violates the protocol.

> a minor annoyance

Can you explain why that bothers you? And have you considered using `accept` instead of `abort`?

**Comment by magpie514** [comment]
This is probably a different use case, but the issue seemed apropos.
It'd be nice to have custom exit codes (with 1,2 and 130 reserved for fzf) so you can process the returning string in different ways.
For example wanting to configure a command runner to have enter (exit code 0) run the selected command, but have a bind to have tab exit with a different code (say 40) and the script processing the output can use that string differently. 
The command could be something like `exit(error_code)` and returning selection as an accept.

**Comment by bschlenk** [comment]
I think I need this too but maybe it can be solved in a different way?

I have a script that opens a list of git branches in one fzf window, and if you press the right arrow, it opens up a commit view for that branch in a sub fzf process using `execute`. When that sub fzf window exits, normally it would return control to the opening fzf process. I want to have additional controls in the sub fzf process, like binding ctrl-c to copy the commit sha. But it will always return control to the opening fzf process.

If I had custom exit codes, I could break out of both fzf processes and catch the custom code from the python script that controls the whole thing.

**Comment by junegunn** [comment]
Closing as this is currently possible using `become` action.
