### ISSUE TITLE
Will future releases support 32bit again?

### ISSUE THREAD

**Issue by alechstong** [junegunn/fzf#2328]
Or am I stuck at 0.22.0?

minimum requirement of current fzf.vim is 0.23.0, and I cannot find earlier releases. I'm using a patched fzf.vim for the moment.

I hope there would be a future 32bit version, or fzf.vim set the minimum requirement of fzf at 0.22.0.

**Comment by junegunn** [comment]
Go 1.15 dropped support for building 32-bit binaries, so, unfortunately, no.

Have you tried building fzf from source? You can just `git clone` this repository and `make install`, if you have Go installed on your system.

See https://github.com/junegunn/fzf/blob/master/BUILD.md

**Comment by alechstong** [comment]
Yeah, I should have tried this first. After adding a i686 target to Makefile, It works with go1.14.13.

Thank you for helping.

**Comment by junegunn** [comment]
Oh, right. I forgot that I removed 32-bit targets in https://github.com/junegunn/fzf/commit/dba14d26303297322dc4426d38ebfbf1d76a6011. I should probably restore them.

**Comment by junegunn** [comment]
Updated Makefile so you can build binaries without manually editing the file.
