### ISSUE TITLE
Add an action to close the preview window

### ISSUE THREAD

**Issue by sitaktif** [junegunn/fzf#2331]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues
    
## Problem / Steps to reproduce

fzf currently has an action to toggle the preview window (`toggle-preview`) but does not seem to have an action for closing it.

It would be nice to have a `close-preview` or `preview-close` action to allow that.

A workaround is to use `toggle-preview` but a subsequent key press will re-open the preview pane, which is not always desirable.

### Use case

Closing the preview pane is useful for use cases that pass `--preview-window=hidden --bind=<somekey>:preview:<someprogram> {}`.

One can create a command launcher with fzf allowing to run (expensive) one-time actions, such as building or testing or packaging a build target depending on the key that is pressed. Once the action has run, the user can check the logs in the preview window, and close it once that's done.

**Comment by rayiik** [comment]
Hey just an ideal if you have your preview unset or hidden you can
```bash
fzf --bind='preview:cat {}'
```
As long as you aren't refreshing the preview its a single instance of the preview command as i understand it, and is destroyed as soon as you switch target {}' which i believe why the refresh-preview flag/binding was added. (could be wrong on the technicalities there but that's my understanding)

**Comment by sitaktif** [comment]
@rayiik My use case is actually using the `preview` action but unfortunately moving the the next target does not close/hide the preview window.

Here's an example:

```bash
fzf --preview-window=hidden --bind "enter:preview: cat {}" --bind "esc:toggle-preview"
```

This is mostly what I want except for the fact that when pressing `enter` then `esc` then `esc` again, the preview windo re-appears.

Note: what would be absolutely amazing is if this new command (say `--bind "esc:close"`) the first `esc` closed the preview and the second `esc` closed `fzf`.

**Comment by junegunn** [comment]
So we have two options,

1. Add `close-preview` action and bind it to `change:close-preview`
2. Add `close` action for *incrementally* closing windows

I like both approaches, but the first one will not work well with the regular `--preview` option.

**Comment by sitaktif** [comment]
> the first one will not work well with the regular `--preview` option.

Are you saying that because moving up or down or changing the search terms will re-open it immediately?

**Comment by junegunn** [comment]
Yes. One thing I missed though is `change` event is only triggered when the query string is changed not on cursor move.

**Comment by junegunn** [comment]
Implemented `close` action on master. Thanks for the suggestion.

**Comment by sitaktif** [comment]
Amazing, thanks for implementing it! <3
