### ISSUE TITLE
--history <file> is not working

### ISSUE THREAD

**Issue by bhepple** [junegunn/fzf#2333]
- [ x] I have read through the manual page (`man fzf`)
- [ x] I have the latest version of fzf
- [ x] I have searched through the existing issues

## Info

- OS
    - [x ] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ x] bash
    - [ ] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

I'm not getting anything written to a history file:

```
$ rm -f ~/.cache/acd
$ fzf --history=$HOME/.cache/acd # I select a file 'config.sub'
config.sub
$ ll ~/.cache/acd
-rw-------. 1 bhepple bhepple 0 Jan 27 13:27 /home/bhepple/.cache/acd
```

I would have expected "config.sub" to be written there but it only creates the file without writing anything there.

I was hoping that it would also maintain a count of how many times that item had been selected and (next time) present the list with the most oft used item first (ie like 'rofi -show run' does it for commands)

**Comment by junegunn** [comment]
`--history` stores the search queries, not the selected items. Maybe the documentation is not clear enough. I'll see if I can clarify that a bit.

> I was hoping that it would also maintain a count of how many times that item had been selected and (next time) present the list with the most oft used item first (ie like 'rofi -show run' does it for commands)

This is beyond the scope of fzf, which is just an interactive version of "grep". One can however write scripts to count the selections and use the information to generate the input to fzf.

```sh
...
selected=$(sorted_list_using_book | fzf --no-sort) || return
update_book "$selected"
... 
```

Similarly to how we integrate fzf with [z](https://github.com/rupa/z).

```sh
# Z integration
source "$BASE/z.sh"
unalias z 2> /dev/null
z() {
  [ $# -gt 0 ] && _z "$*" && return
  cd "$(_z -l 2>&1 | fzf --height 40% --nth 2.. --reverse --inline-info +s --tac --query "${*##-* }" | sed 's/^[0-9,.]* *//')"
}
```

**Comment by bhepple** [comment]
Thanks for the clarification.
