### ISSUE TITLE
fzf change default depth

### ISSUE THREAD

**Issue by reportaman** [junegunn/fzf#2341]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

I am unable to change the default depth of fzf search while using `cd **`.  The only material I could find online is this https://github.com/junegunn/fzf.vim/issues/237#issue-187504488. And setting `export FZF_DEFAULT_OPTS=" -depth 4 "` gives this error: `cd **unknown option: 4`. Please let me know where I might be making a mistake, and what can be done about it.

**Comment by junegunn** [comment]
`FZF_DEFAULT_OPTS` sets the default options for fzf, and fzf doesn't have `-depth` option.

To customize the fuzzy completion, you need to override `_fzf_compgen_path` and/or `_fzf_compgen_dir`. 

See https://github.com/junegunn/fzf#settings

I know that this can be confusing. I'll see if I can clarify that in the documentation.
