### ISSUE TITLE
FZF doesn't exclude hidden directories

### ISSUE THREAD

**Issue by reportaman** [junegunn/fzf#2342]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

Lines in my `.zshrc`
```bash
export FZF_DEFAULT_COMMAND="fd -i -p -L -d 4 --type f -E '*Applications*' -E '*Library*'"
export FZF_DEFAULT_OP="--cycle --no-sort"
```

Here's the directory structure from which I am running `cd **<tab>` (that intern calls fzf), and `fd` (the `FZF_DEFAULT_COMMAND` flavor):

```bash
reportaman@reportaman's-Mac-mini temp % tree -a   
.
├── .foo
│   └── foo.txt
├── .foo.txt
├── foo
│   └── foo.txt
└── foo.txt

```

Output of `cd **<tab>` (isn't .foo in the listing a bug?):
<img width="201" alt="Screen Shot 2021-02-02 at 5 06 31 PM" src="https://user-images.githubusercontent.com/71736629/106683255-08eb0400-6579-11eb-9f2d-e46f47855a9a.png">

Output of `fd -i -p -L -d 4 --type f -E '*Applications*' -E '*Library*`:
```bash
foo/foo.txt
foo.txt
```

**System information**
```
OS: macOS 11.2 20D64 arm64
Host: Macmini9,1
Kernel: 20.3.0
Shell: zsh 5.8
CPU: Apple M1 (ARM64)
```

**Comment by junegunn** [comment]
For fuzzy directory completion, you need to implement `_fzf_compgen_dir`. It doesn't run `FZF_DEFAULT_COMMAND`. I'll update the README page hopefully to lessen the confusion.

**Comment by junegunn** [comment]
See

* https://github.com/junegunn/fzf#environment-variables
* https://github.com/junegunn/fzf#settings
