### ISSUE TITLE
how could I use Ctrl + T but hit return only once?

### ISSUE THREAD

**Issue by Jackiexiao** [junegunn/fzf#2344]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

`cp foo.txt <CTRL-T>`
> You can then use fzf to select the destination directory (as long as it’s somewhere in your home directory). Once you’ve selected it you can **hit return** to add it to the command line you’re working on, and then **hit return** again to execute the command.

how could I use Ctrl + T but hit return only once? (like `alt +c`, related pr?: https://github.com/junegunn/fzf/pull/1492)

**Comment by junegunn** [comment]
There is no such option.

Also see https://github.com/junegunn/fzf/pull/1492#issuecomment-461670530
