### ISSUE TITLE
(no bugs - just help) display one field of text but execute a command that uses another field as the argument.

### ISSUE THREAD

**Issue by 5c0tt-b0t** [junegunn/fzf#2350]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [x] Etc.
    **(linux & linux_android)**
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish
    
## No Bug! - just assistance.

First **THANK YOU!** `fzf` is amazing!
Can I have `fzf` display one field of text but execute a command (on `<ENTER>`) that uses another field (on the same line) as the argument?

**Example:**
I have a function, it outputs all the info I need to a file, that file looks kinda like this:
```bash
Title :: /A/Directory/A/File
Title2 :: /Another/Directory/File
```
Now I can either:
```bash
# get title:
cat $file | awk -F' :: ' '{print $1}'
# get directory:
cat $file | awk -F' :: ' '{print $2}'
# or assign values for each field:
title=$(cat $file | awk -F' :: ' '{print $1}')
directory=$(cat $file | awk -F' :: ' '{print $2}')
```
I would like to display only the "title" in `fzf` for people to select, but return each lines "directory" instead as the argument for my command. Lets say this is my command:
```bash
nvim $(bat $file | awk -F' :: ' '{print $1}' | fzf)
```
This displays all of the first field (the "titles") - perfect!
When I press enter (obviously) the argument to `nvim` is "title" but I would like this to be the line's second field that isnt being shown ("directory") as the argument to `nvim`.
Is this possible? better yet, can I supply `fzf` with the whole line instead `Title :: /A/Directory/A/File` and have it display field one only but use field 2 (the "directory") as the argument on pressing `<ENTER>`?
Or would `--execute` be best here used instead?
Sorry, you must be busy without me, but after a few hours or research I'm stuck still.
Thank you again, it really is appreciated, the more I learn of `fzf`'s capabilities, the more I find myself integrating it everywhere!

**Comment by junegunn** [comment]
If file paths don't contain any spaces, it's pretty simple.

```sh
echo -e 'Title :: /A/Directory/A/File\nTitle2 :: /Another/Directory/File' |
  fzf --with-nth=1..-3 --bind 'ctrl-x:execute:less {-1}' | awk -F' :: ' '{print $2}'
```

But if they do, you need to set `--delimiter` option as well.

```sh
echo -e 'Title :: /A/Directory/A/File\nTitle2 :: /Another/Directory/File' |
  fzf --delimiter=' :: ' --with-nth=1 --bind 'ctrl-x:execute:less {-1}' | awk -F' :: ' '{print $2}'
```

But the problem here is that fzf will print the delimiter as well (`> Title ::`) which is probably not what you want. A simple solution would be to use tab character as the delimiter.

```sh
echo -e 'Title\t/A/Directory/A/File\nTitle2\t/Another/Directory/File' |
  fzf --with-nth=1 --bind 'ctrl-x:execute:less {2}' | awk -F'\t' '{print $2}'
```
