### ISSUE TITLE
[regression] sink function calling fzf#run() puts vim in normal mode instead of terminal

### ISSUE THREAD

**Issue by antoinemadec** [junegunn/fzf#2352]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux

- Shell
    - [x] bash
 
## Env
```sh
NVIM v0.5.0-dev+1085-g52397aaa0
> nvim --version
NVIM v0.5.0-dev+1085-g52397aaa0
> vim --version
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Jan 20 2021 22:47:34)
Included patches: 1-2380
```

## Problem / Steps to reproduce
When the sink function calls ```fzf#run()```, **vim and neovim** switch to normal mode instead of terminal mode.

This regression comes from this commit: https://github.com/junegunn/fzf/commit/1a76bdf8914195ab26ebac7e49a3ed8752dd69bd

minimal_vimrc:
```vim
call plug#begin('~/.vim/plugins')
Plug 'junegunn/fzf', {'dir': '~/.fzf','do': './install --all'}
call plug#end()
```

testcase.vim:
```vim
function! s:list_handler(...) abort
  call s:run_testcase()
endfunction

function! s:run_testcase() abort
  let opts = {'sink*': function('s:list_handler')}
  call fzf#run(fzf#wrap(opts))
endfunction

call s:run_testcase()
```

Steps to reproduce the issue:

1. nvim -u minimal_vimrc
2. source testcase.vim
3. press Enter

**Comment by antoinemadec** [comment]
@ojroques what do you  think about this ?
Should your commit be kept, adapted or reverted ?

**Comment by junegunn** [comment]
Can you test if this patch fixes the problem?

```diff
diff --git a/plugin/fzf.vim b/plugin/fzf.vim
index 763747c..1069af8 100644
--- a/plugin/fzf.vim
+++ b/plugin/fzf.vim
@@ -764,6 +764,10 @@ function! s:split(dict)
   endtry
 endfunction
 
+noremap  <silent> <Plug>(fzf-normal) <Nop>
+noremap! <silent> <Plug>(fzf-normal) <Nop>
+tnoremap <silent> <expr> <Plug>(fzf-normal) &filetype == 'fzf' ? "\<C-L>" : "\<C-\>\<C-n>"
+
 function! s:execute_term(dict, command, temps) abort
   let winrest = winrestcmd()
   let pbuf = bufnr('')
@@ -793,7 +797,7 @@ function! s:execute_term(dict, command, temps) abort
     else
       if bufnr('') == self.buf
         " Exit terminal mode first (see neovim#13769)
-        call feedkeys("\<C-\>\<C-n>", 'n')
+        call feedkeys("\<Plug>(fzf-normal)")
         " We use close instead of bd! since Vim does not close the split when
         " there's no other listed buffer (nvim +'set nobuflisted')
         close
```

**Comment by antoinemadec** [comment]
@junegunn , the patch works like a charm on both vim and nvim.
Thanks a lot!

**Comment by antoinemadec** [comment]
@junegunn note that this commit created a weird condition where some commands executed after wait for a key to be pressed to be executed.

The minimal testcase I found is using CocList.
```CocList extensions``` won't execute before we press a key:
```vim
function! s:list_handler(...) abort
  let cmd = "CocList extensions"
  execute cmd
endfunction

function! s:run_testcase() abort
  let opts = {'sink*': function('s:list_handler')}
  call fzf#run(fzf#wrap(opts))
endfunction

call s:run_testcase()
```

**Comment by junegunn** [comment]
Does it help to add `x` flag to `call feedkeys("\<Plug>(fzf-normal)")`?

**Comment by kevinhwang91** [comment]
> Does it help to add `x` flag to `call feedkeys("\<Plug>(fzf-normal)")`?

I don't know what the issue of @antoinemadec , but wihtout `x` flag in the floating window layout, nvim can't fire a `WinEnter` event when fzf's window exits until I move the cursor.

**Comment by yuki-yano** [comment]
The behavior of [fzf-preview.vim](https://github.com/yuki-yano/fzf-preview.vim) when calling fzf#run again is also strange.
After running fzf#run for the second time, the floating window is not displayed, and fzf starts when some key is entered.

**Comment by junegunn** [comment]
> fzf starts when some key is entered

That's why I had to add `<C-L>` in the above patch.

Can you reproduce the problem with the minimal Vim configuration shown below?

```sh
vim -Nu <(cat << EOF
call plug#begin('~/.vim/plugged')
Plug 'junegunn/fzf'
call plug#end()

function! s:list_handler(...) abort
  call s:run_testcase()
endfunction

function! s:run_testcase() abort
  let opts = {'sink*': function('s:list_handler')}
  call fzf#run(fzf#wrap(opts))
endfunction

command! Run call s:run_testcase()
EOF
)
```

**Comment by yuki-yano** [comment]
The above minimal settings will not cause any problems.

I was just verifying that in fzf-preview.vim, regardless of the recursive invocation of fzf#run, sink is not running unless some key is entered after every operation.

This may be due to the fact that it is being executed via TypeScript with async.

**Comment by yuki-yano** [comment]
In this line, we are using RPC to run Node.
It doesn't work as it is, but you can fix it by inserting `call feedkeys('', 'x')` before the request.
https://github.com/yuki-yano/fzf-preview.vim/blob/0a9966475c5fcf3cad0798b3615089f7dac3bf9f/autoload/fzf_preview/rpc.vim#L57

**Comment by antoinemadec** [comment]
> Does it help to add `x` flag to `call feedkeys("\<Plug>(fzf-normal)")`?

@junegunn , adding the ```'x'``` flags in ```fzf.on_exit```'s ```feedkeys()``` was creating a lot of side effects when using ```:Buffers``` to jump in a terminal.

The cleanest way to do it was to add ```call feedkeys('', 'x')``` before invoking ```CocList```.
@yuki-yano code call RPC functions, like ```CocList```. Maybe this bug only happens with RPC?

**Comment by junegunn** [comment]
@antoinemadec @jakubgs @yuki-yano 

Please test if dea950c2c82b8c44a123a1eb7a7cfa9c08048d8c fixes all the issues we have discussed so far. `feedkeys` will be called only when the destination buffer is a terminal buffer; if it's another instance of fzf, it will start insert mode, otherwise, normal mode. There shouldn't be any side-effect in other cases.

**Comment by antoinemadec** [comment]
@junegunn , this is still not working for me.
It forces me to send a key between 2 terminal invocation before displaying the 2nd terminal.

Minimal **vimrc**:
```vim
call plug#begin('~/.vim/plugins')
Plug 'junegunn/fzf', {'dir': '~/.fzf','do': './install --all'}
call plug#end()

function! s:list_handler(...) abort
  call s:run_testcase()
endfunction

function! s:run_testcase() abort
  let opts = {'sink*': function('s:list_handler')}
  call fzf#run(fzf#wrap(opts))
endfunction

command! Run call s:run_testcase()
```

```sh
> nvim --version
NVIM v0.5.0-dev+1102-g595f6e4d6
Build type: RelWithDebInfo
```

**Comment by junegunn** [comment]
That's strange. Have you tested it on Neovim 0.4.4?

**Comment by junegunn** [comment]
I was able to reproduce the problem on Neovim HEAD (but not on Neovim 0.4.4 release). 29851c18aa47ad4b4cbf92358cfbe11935f0c033 will fix it.

**Comment by antoinemadec** [comment]
@junegunn , works like a charm. Thanks !
