### ISSUE TITLE
Piping into fzf doesn't work under Cygwin

### ISSUE THREAD

**Issue by mburz** [junegunn/fzf#2354]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf (0.25.1)
- [x] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [x] Cygwin 3.1.7
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

Used the following terminals, all show the same problem:
- Cygwin mintty
- urxvt via ssh
- urxvt via ssh + tmux

Given the following simple text file
```
~$ cat test.txt
line1
line2
line3
```

Simple piping such as `cat test.txt | fzf` is not usable. The lines are read and displayed by `fzf`, but filtering, navigation (e.g. `C-k`) and selection do not work. Same for `fzf <test.txt` and `echo -e 'line1\nline2\nline3' |fzf`

Things work as expected when using `FZF_DEFAULT_COMMAND`, for instance `FZF_DEFAULT_COMMAND='cat test.txt' fzf` works as expected.

In `ConEmu 210206` it works as expected.
`fzf 0.8.9 (Dec 24, 2014)` that is shipped with Cygwin also works as expected under `mintty` and via `ssh`

**Comment by Trismegistos84** [comment]
Piping works with current cygwin version. I have just installed fzf using cygwin installer. My version is:

```
<11:46:08>$ fzf --version
fzf 0.8.9 (Dec 24, 2014)
```

**Comment by qkl133217** [comment]
The original reported issue still exists in version 0.29.0 (dc975e8) using the steps provided above.  Piping into fzf does not work under Cygwin+current version of fzf.  Using the very old version that comes with cygwin (fzf 0.8.9 (Dec 24, 2014) does work as mburz & Trismegistos84 state, but many features/improvements have been added in 8 years which will be unavailable.

**Comment by elandorr** [comment]
Same here. Saw fzf/fd are available for win and gleefully tried to align my portable work environments - but in the current version (0.32.1) piping into fzf leads to a static frozen screen.

I might try the 2014 version, thanks for that tip!

**Comment by junegunn** [comment]
The latest version of fzf runs nicely on MSYS2, you might want to test it.
