### ISSUE TITLE
FZF considerably slower in vim compared to the shell

### ISSUE THREAD

**Issue by medwatt** [junegunn/fzf#2355]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [x] fish
    
## Problem / Steps to reproduce

I opened an [issue](https://github.com/junegunn/fzf/issues/2330) a few weeks back where I pointed out that running fzf in vim was much faster on windows than linux. It was suggested that I try `fd` instead of `find`. I did and while the speed improved slightly, it still didn't explain the huge discrepancy.

I installed the fish shell today together with the fzf plugin. I was surprised that fzf ran as fast as it did on my windows machine on the same drive I was complaining about the last time. I made a [video](https://streamable.com/3v0l00) to demonstrate this observation. Surely, there has to be a reason why fzf is so much faster from the shell than from within vim.

**Comment by charlie39** [comment]
it is quite fast in my nvim set up:
this is the function i am using:
`:call fzf#run(fzf#wrap({'source': 'fd  .  ~/{.config,.local/bin,packages/repos,projects/} -H','options': '-m  --preview "bat --color always {} -n" --preview-window=right:60%:border --color "fg:#bbccdd,fg+:#ddeeff,preview-bg:#000000,border:#332288"'}))<cr>`

NOTE: i am selecting few directories to seach for with fd,
