### ISSUE TITLE
tnoremap is not available in Vim 7.4

### ISSUE THREAD

**Issue by whonore** [junegunn/fzf#2357]
- [X] I have read through the manual page (`man fzf`)
- [X] I have the latest version of fzf
- [X] I have searched through the existing issues

## Info

- OS
    - [X] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [X] fish
    
## Problem / Steps to reproduce
Opening Vim 7.4 with fzf installed through vim-plug prints the following error:
```
Error detected while processing /path/to/fzf/plugin/fzf.vim:
line  769:
E492: Not an editor command: tnoremap <silent> <expr> <Plug>(fzf-normal) &filetype == 'fzf' ? "\<C-L>" :
 "\<C-\>\<C-n>"
```

I couldn't find in the documentation whether fzf is meant to support 7.4 or not. Feel free to close if it's 8.0+ only.

**Comment by junegunn** [comment]
It should work now. Thanks for the report.
