### ISSUE TITLE
Actions for 'select' and 'deselect'?

### ISSUE THREAD

**Issue by HenrikBengtsson** [junegunn/fzf#2358]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf (0.25.1)
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

Hi. Thanks for the wonderful fzf tool.  

I'd like to add bindings `shift-down:select+down` and `shift-up:select+up` so that I can quickly select a range of entries by holding down 'shift-down', scroll down a bit, and then continue selecting another range, and so on.  If there are no entries selected, `shift-down:toggle+down` would serve my needs.  However, if some of the entries are already selected, running 'shift-down' through them would toggle those entries to be unselected.   

So, I'm looking for actions `select` and `deselect` but AFAICT, they don't exist.  Is there another way to emulate `select` and `deselect`?

**Comment by junegunn** [comment]
Added `select` and `deselect`. Thanks for the suggestion.

**Comment by HenrikBengtsson** [comment]
Brilliant :pray:
