### ISSUE TITLE
zsh fuzzy(**) completion ignores ripgreprc

### ISSUE THREAD

**Issue by Gee19** [junegunn/fzf#2359]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf (0.25.1)
- [x] I have searched through the existing issues

## Info

- OS
Ubuntu 18.04

- Shell
zsh
    
## Problem / Steps to reproduce

1. create simple `.ripgreprc`:
```
--glob=!node_modules/*
```
2. `export RIPGREP_CONFIG_PATH=/home/jhaine/.config/.ripgreprc`
3. run fzf via `vim $(fzf)` and notice it ignores node_modules as expected
4. run zsh fzf fuzzy completion via `vim **<TAB>` and notice it doesn't ignore node_modules

(top right pane is via `bindkey -s '^o' 'vim $(fzf)\n'`)
![fzf](https://user-images.githubusercontent.com/5077424/108167822-4b0d5d00-70c4-11eb-9fd2-7b94b0e93288.PNG)

This may just be how the shell completion works but I'm not sure.

As always, thank you for this awesome piece of software <3

**Comment by junegunn** [comment]
fzf does not depend on ripgrep by default. Have you configured it to do so?

**Comment by Gee19** [comment]
Ah yes, I forgot to mention that.

I have this set in my `.zshrc`:
```
export FZF_DEFAULT_COMMAND='rg --files'
```

and manually running `rg --files | fzf` seems to work fine

**Comment by junegunn** [comment]
See:
* https://github.com/junegunn/fzf#environment-variables
* https://github.com/junegunn/fzf#settings

The reason fuzzy completion doesn't use `FZF_DEFAULT_COMMAND` is that it can behave differently depending on the prefix.

```sh
vim **<TAB>
vim /tmp/**<TAB>
```

And we can't be sure if it's appropriate to just append `/tmp/` to `FZF_DEFAULT_COMMAND`, which can be just anything.

```sh
export FZF_DEFAULT_COMMAND='seq 100'
```
