### ISSUE TITLE
[zsh] cursor moves to column zero after exiting fzf with ^C

### ISSUE THREAD

**Issue by tiziano88** [junegunn/fzf#236]
To reproduce:
 - type `vim `
 - trigger fzf expansion (I have this mapped to <kbd>Ctrl</kbd>+<kbd>P</kbd>)
 - hit <kbd>Ctrl</kbd>+<kbd>C</kbd>
 - the cursor is now moved to the beginning of the line rather than after the text entered earlier

**Comment by junegunn** [comment]
Hmm, not reproducible for me.

**Comment by pigmej** [comment]
@junegunn I can reproduce, `ls **<tab>` then `Ctrl + C` and it will be in column 0 with `ls **` in prompt.

**Comment by junegunn** [comment]
@pigmej @tiziano88 Aha, I was unable to reproduce it because I was on tmux, but I can see the prompt garbled when not on tmux. Actually the cursor is not moved to column 0, it just looks like so because `zle redisplay` is skipped. I'll fix it.

**Comment by junegunn** [comment]
Should be fixed now. Thanks.
