### ISSUE TITLE
Question: How to make a new preview permanent ?

### ISSUE THREAD

**Issue by E3D3** [junegunn/fzf#2360]
- [x ] I have read through the manual page (`man fzf`)
- [x ] I have the latest version of fzf
- [x ] I have searched through the existing issues

## Info

- OS
    - [x ] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x ] bash
    - [ ] zsh
    - [ ] fish
    
## Problem / Steps to reproduce
I have made a bash script where I use multiple times reload() and preview(). The only thing that doesn't work as expected/hoped for is that when I select another candidate the new preview is replaced by the preview that is set with --preview.
My question is; how can I make new previews permanent ?

**Comment by junegunn** [comment]
By not using `--preview` option and only setting manual preview bindings.

```sh
# Preview window is updated only when you hit CTRL-O/P
fzf --bind 'ctrl-o:preview(echo {}),ctrl-p:preview(date)'

# You can hide the preview window by default
fzf --bind 'ctrl-o:preview(echo {}),ctrl-p:preview(date)' --preview-window hidden
```

There is no option to dynamically change `--preview` argument.

**Comment by E3D3** [comment]
Thanks for your response, and of course very much for sharing the great fzf.

I don't understand the above given examples or comments well, but think that I should have formulated my question better. My excuse for this. English is not my native language.

What I want is that after changing the preview function, like in your example above, selecting a new candidate will update the preview the same as the --preview option normally does, instead of using the same key binding again & again to invoke the same preview function for new candidates. If the content of the preview window isn't updated after selecting other candidates then it doesn't matter if the preview-function changed permanently or not.
It seems that preview() doesn''t replace the full --preview functionality, but I'm no real programmer and don't understand why --preview (dynamically ?) updates the --preview argument {} when selecting another candidate, but that preview() doesn't.

The only possible solution I can think of is restarting fzf with a new --preview option but I hope there is another way to update the preview content automatically when selecting another candidate, e.g. by adding something to the down or up action.

**Comment by xeruf** [comment]
@E3D3 that is a very valid request! The only thing I could think of with the current featureset is to bind multiple keys to the up/down and the preview action, e.g.

    fzf --bind='down:down+preview(cat {}),up:up+preview(cat {}),shift-down:down+preview(date {}),shift-up:up+preview(date {})'

**Comment by xeruf** [comment]
It also shouldn't be hard to re-invoke fzf since you can extract query & state view braces.
But I would also appreciate a built-in functionality for that, maybe `preview-set(...)` in addition to `preview(...)`.
