### ISSUE TITLE
Please update to Go 1.16 and also release for macOS ARM64

### ISSUE THREAD

**Issue by dbast** [junegunn/fzf#2361]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

Go 1.16 was just released with macOS ARM64 support, see https://blog.golang.org/go1.16

**Comment by dbast** [comment]
Regarding signing and darwin_arm64 binaries ... go 1.16 automatically adds an add hoc signature, see the comment here https://github.com/git-lfs/git-lfs/issues/4403

**Comment by junegunn** [comment]
Thanks, I've updated the build script. Please note that the mac binaries I build and upload are signed but not "notarized" as I don't have an Apple Developer account. So users are probably better off installing fzf via Homebrew.

**Comment by dbast** [comment]
Thanks!
