### ISSUE TITLE
Make fzf inherit readline keybindings in .inputrc

### ISSUE THREAD

**Issue by mgarort** [junegunn/fzf#2365]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

I have customized the readline keybindings in `~/.inputrc` so that, for example, `<C-h>` moves the cursor left by one character rather than the default `<C-b>`. This works seamlessly in normal login shells. However, `fzf` doesn't seem to heed  `~/.inputrc`, and instead maintains the default readline keybindings (e.g. `<C-b>` for going back one character, `<C-f>` for going forward one character, `<C-h>` for backspacing, `<M-b>` for going one word backward, etc). This makes me think that `fzf` is executed in some kind of subshell.

Is there a way to make this subshell inherit the configuration of `~/.inputrc`, or to run the appropriate `bind` commands in it? Just to be clear, I don't want to create a custom `fzf` configuration, I just want it to have the same keybindings as the rest of the system it is working on.

Thanks a lot in advance.

**Comment by junegunn** [comment]
It's not possible since fzf doesn't use Readline library but implements its own set of key bindings in its own way.

Maybe one could implement a script that generates a set of `--bind` options for fzf from `bind -p` output.
