### ISSUE TITLE
fzf commands return error in gvim

### ISSUE THREAD

**Issue by zane131** [junegunn/fzf#2367]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish
    
## Problem / Steps to reproduce
Using `gvim` (v8.0.1453) on Ubuntu 18.04.5, I will get the following error when executing any of the fzf or fzf.vim commands (i.e. :FZF, :Files, :Buffers, etc.):

```
Error detected while processing function fzf#vim#files[15]..<SNR>58_fzf[20]..fzf#run[59]..<SNR>40_execute_term:
line   77:
E475: Invalid argument: term_kill
Press ENTER or type command to continue
```
Note that I do not have issues with `vim`. This only happens in `gvim`.

I was able to isolate the issue and found it starts with ab3937e and have confirmed it has not been fixed with the latest (at the time that is 29851c1).

If it helps, I am using the latest fzf.vim (at the time that is https://github.com/junegunn/fzf.vim/commit/02a192ea0bed22a015e005b281e55e0da2a8e496).

**Comment by zane131** [comment]
Looking around I see in `:help terminal` (in gvim v8.0):
```
WARNING: THIS IS ONLY PARTLY IMPLEMENTED, ANYTHING CAN STILL CHANGE
```
So I am guessing I will need to update `gvim` to at least gvim v8.2.

**Comment by junegunn** [comment]
Yeah, older versions of `term_start` would not accept `term_kill` argument. It should be fixed now. Thanks.

**Comment by zane131** [comment]
Thank you!
