### ISSUE TITLE
ctrl-r matches on history line number too

### ISSUE THREAD

**Issue by alexeymuranov** [junegunn/fzf#237]
Is there a reason someone would want to match the line number from history when using **fzf** with `ctrl-r`? Currently, if i use **fzf** with `ctrl-r` (in **zsh**) and type, for example, `123`, the returned list includes the item number 123 from the history, and may also include the item 12, or 192, containing `3`, etc. I wouldn't need them in the list, personally.

**Comment by junegunn** [comment]
https://github.com/junegunn/fzf/blob/master/shell/key-bindings.zsh#L39

Changing `-n2..,..` to `-n2..` will do. There is no variable to customize the behavior so you'll have to edit the source directly or manage your own version. The reason it is so is that it's not practical to make every aspect of the code configurable so I want the users to see the code as a reference implementation that they can refer to when they want to write their own key bindings. Thanks.

**Comment by alexeymuranov** [comment]
Thanks for the explanation.  However, IMO, a sensible default would be not to match the history line number.

**Comment by junegunn** [comment]
Okay, but I actually type in the index number to pinpoint the item when there are many very similar entries in the list. I find it especially helpful when in `--extended` search mode, where I can first type in a part of the command, then append a number to greatly narrow down the list. e.g. `git 55`
