### ISSUE TITLE
Completion trigger doesn't use configured default command

### ISSUE THREAD

**Issue by andweeb** [junegunn/fzf#2371]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Mac OS X
- Shell
    - [x] zsh

## Problem / Steps to reproduce
I'm using a custom completion trigger and `fd` for the default command via the following:
```sh
export FZF_COMPLETION_TRIGGER=",,"
export FZF_DEFAULT_COMMAND="fd"
```

`fd` by default excludes everything specified in a `.gitignore` file, so when I use my completion trigger (e.g. `$ vi ,,<Tab>`) I would expect the default command to be used and thus filter out any results that would fall under the `.gitignore` items, but they _do_ show up.

Interestingly, it looks like the default command _is_ used when I _don't_ use the custom completion trigger (e.g. `$ fzf` or `$ vi $(fzf)<Enter>`).

It seems as though the default command is not being used when a trigger is used. Are these two options not compatible with each other?

Here are more explicit steps:
* Add the `export`s mentioned above
* `cd` into a git repository with a `.gitignore`
* Run `vi ,,<Tab>`: should unexpectedly show results that should be filtered out
* Run `vi $(fzf)<Enter>`: should show results that should be filtered out as expected

**Comment by junegunn** [comment]
See
* https://github.com/junegunn/fzf#environment-variables
* https://github.com/junegunn/fzf/issues/2359#issuecomment-780367571
