### ISSUE TITLE
Change preview window location after startup

### ISSUE THREAD

**Issue by neerajbadlani** [junegunn/fzf#2376]
- [X] I have read through the manual page (`man fzf`)
- [X] I have the latest version of fzf
- [X] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [X] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [X] bash
    - [ ] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

I move around between portrait and landscape monitors , is it possible to provide action , which can change preview-window position to portrait / landscape via a key / automatically depending on terminal length ?

**Comment by nicedreams** [comment]
Exactly what I'm looking for.  Want to be able to toggle --preview-window to either right or bottom while inside FZF.  When split screen need to toggle preview from right to bottom without exiting FZF.

Something like:
    --bind 'ctrl-t:toggle-preview-window=top:right

Be nice to have ? for toggle preview-window [on:off] and ctrl-/ for toggle preview-window [right:bottom].
