### ISSUE TITLE
Strange window flickering

### ISSUE THREAD

**Issue by glepnir** [junegunn/fzf#2377]
- [ ] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [ ] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

I had these function in my `.zshrc` then  type `co` in command line . the fzf's window flickered once

```shell
export FZF_DEFAULT_COMMAND='rg --files --hidden'
export FZF_DEFAULT_OPTS='--height 90% --layout reverse --border --color "border:#b877db" --preview="bat --color=always {}"'

fo() {
  IFS=$'\n' out=($(fzf --query="$1" --multi))
  key=$(head -1 <<< "$out")
  file=$(head -2 <<< "$out" | tail -1)
  if [ -n "$file" ]; then
    [ "$key" = ctrl-o ] && open "$file" || ${EDITOR:-nvim} "$file"
  fi
}

# cd directory and open file
co() {
  local dir
  dir=$(fd ${1:-.} --hidden --type d 2> /dev/null | fzf --preview 'tree -C {}' +m) && cd "$dir" && fo
}
```

#### preview

https://user-images.githubusercontent.com/41671631/109656221-270b4a80-7b9f-11eb-9a80-15a398956ac9.mov

**Comment by junegunn** [comment]
That's strange. I can't reproduce the problem on my system.

Since we don't have the same set of files on our systems, it's not possible for me to run the exact same scenario as yours. 
 Can you simplify the case so I can reliably reproduce the problem on my system? For example, the following command will yield the same result anywhere.

```sh
# bat doesn't make sense with numbers though
seq 1000000 | FZF_DEFAULT_OPTS= fzf --height 90% --layout reverse --border --color "border:#b877db" --preview="bat --color=always {}"
```

**Comment by glepnir** [comment]
never mind .fixed.
