### ISSUE TITLE
error: recursive globbing on Android/Termux

### ISSUE THREAD

**Issue by nerd190** [junegunn/fzf#2380]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [x] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

**Problem:**
Completion not working properly on Android/Termux,
Args complete perfectly but recursive globbing with `**` doesnt.
I tried building from source to test if it was the apt pkg's fault but this happens still.
I've tried alot to fix this myself over the few hours, I atleast have some findings...
To test, I went through the ReadMe and modified some stuff, like the default trigger from `**` to `,,` etc, I found that adding `_fzf_setup_completion git` in my .bashrc gives an error:
```bash
_fzf_setup_completion: command not found
```
```bash
~ $ complete | grep _fzf
```
(nothing)
```bash
~ $ fzf -[TAB]
--algo            --jump-labels     --select-1
--ansi            --literal         --sync
--bind            --margin          --tabstop
--color           --marker          --tac
--cycle           --multi           --tiebreak
--delimiter       --no-bold         --with-nth
--exact           --no-hscroll      -0
--exit-0          --no-mouse        -1
--expect          --no-sort         -d
--extended        --nth             -e
--filter          --pointer         -f
--header          --preview         -i
--header-lines    --preview-window  -m
--height          --print-query     -n
--history         --prompt          -q
--history-size    --query           -x
--inline-info     --reverse
```
I have tried this on two different devices, clean Termux installations, minimal pkgs and minimal startup files.

**Steps to reproduce:**
- apt pkg:
  - apt install busybox coreutils bash-completion fzf -y
  - exit shell / enter shell
  - `ls **[TAB]`
- from source:
  - apt install busybox coreutils bash-completion git make build-essential util-linux golang -y
  - git clone https://github.com/junegunn/fzf
  - cd fzf
  - make
  - ./install (answer yes for everything)
  - `source ~/.bashrc`
  - `ls **[TAB]`

Note: For testing purposes, Termux has an emulator now for PC.

Note: The last few hours are a blur but if you do get `**` to work, exit the shell and try it, it wont work again. At some point whether it was the pkg or from source, but I had it work for me but exited the shell and then it no longer worked, 1 minute clip...

Edit: (clips too large, I will try to reproduce it and record using `asciicinema` instead)

**Comment by junegunn** [comment]
Sounds like an issue of the apt package.

Does manually sourcing https://github.com/junegunn/fzf/blob/master/shell/completion.bash fix the issue?

https://github.com/junegunn/fzf/blob/4f9a7f8c879ef625f3bec5946df9e7fe5768f9dd/shell/completion.bash#L356
