### ISSUE TITLE
Update header

### ISSUE THREAD

**Issue by pschmitt** [junegunn/fzf#2385]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

I'd like to be able to update the header after the initial launch, which comes in handy when updating the source with `reload()` to visually reflect the change. 

Here's my usecase:

In (n)vim I want to bind a key to open up FZF with `fd` as source, "$ fd" as header and bind `ctrl-p`to reload with `fd -uu`. The issue is that currently there is no straight-forward way to update the header, only the prompt can be updated.

```viml
nnoremap <silent><c-p> :Fd --hidden<cr>

command! -bang -nargs=? Fd
  \ call fzf#run(fzf#wrap({
  \   'source': 'fd --color=always ' . <q-args>,
  \   'options': '--reverse  --bind "ctrl-p:reload(fd --color=always -uu)" --header "$ fd' . (<q-args> != ''?' '.<q-args>:'') . '"',
  \   'sink': 'e'},
  \   <bang>0))
```

**Comment by junegunn** [comment]
You can use `--header-lines` option like so

```vim
command! -bang -nargs=? Fd
  \ call fzf#run(fzf#wrap({
  \   'source': printf('echo %s; fd --color=always %s', shellescape('$ fd ' . <q-args>), shellescape(<q-args>)),
  \   'options': '--reverse --bind "ctrl-p:reload(echo mode 2; fd --color=always -uu)" --header-lines 1',
  \   'sink': 'e'},
  \   <bang>0))
```
