### ISSUE TITLE
Preview with ansi colors interferes with list selection with arrows

### ISSUE THREAD

**Issue by ddnexus** [junegunn/fzf#2387]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

NOTICE: It is a problem that appears randomly and only in specific context, so it's not a terrible bug, but it would be nice to have your opinion at least about what may cause it, so I may try to isolate it better, or work around the issue. Thanks.

```
seq 1000 | fzf --preview 'exa -la --color always /'
```
Using up and down arrows to select in the list, may ignore the highlighting of the actually selected item. However the item is currently selected, just not visualized as such, because the highlight remained on the previous item. You can confirm that the item it is selected but not highlighted by pressing the arrow again or pressing enter.

It's not related to specific items or preview content: the same item can trigger it or not even if the preview is the same.

That happens randomly but only when all the following conditions are true:
1. The preview has to be active
2. The preview must contain ansi colors
3. The terminal cursor must not be blinking

It looks like the problem may be related to the trigger to refresh the screen, and the cursor blinking may force the refresh.

It might be related to #2346

**Comment by junegunn** [comment]
I can't reproduce the problem. Which terminal emulator do you use? Have you tried using a different one?

**Comment by ddnexus** [comment]
```sh
gnome-terminal --version
# GNOME Terminal 3.38.0 using VTE 0.62.0 +BIDI +GNUTLS +ICU  +SYSTEMD
```
Ubuntu 20.10

I just tried in iTerm and Terminal in MacOS and I couldn't reproduce it anymore (I tried like a week ago and I am quite sure I got it).

If you could try on Ubuntu / Terminal / zsh and if it would not happen, the problem would probably be related to some plugin or library in my local setup, so I will search it on my end and close the issue.

Thank you!

**Comment by ddnexus** [comment]
Closing this, it is definitely not a fzf issue, since I got the same in other contexts where fzf was not involved.
Sorry for the wrong report.
