### ISSUE TITLE
feature request: see context by marking an item and jumping to marked item in the full result list

### ISSUE THREAD

**Issue by windowswithoutborders** [junegunn/fzf#2388]
fzf is working great at helping me parse a 10,000 line file and select the line I need to act as an argument. The problem is I need context from the surrounding lines in the file so I can select the appropriate line to use as an argument.

The document I'm working with follows this format:
-- Description of item (including an easily identifiable name)
-- random-gibberish-representing-item-with-NO-identifying-information

Where every item in the document has a description followed by the actual information I want to use as an argument. I need the preceding description line to search off of and make the proper selection. Currently what I do to accomplish this is use the output of `$(grep -iA1 "$*" /path/to/file | fzf -m -e --reverse)` to select a result, passing in specific keywords to narrow down the selection fzf presents me with.

Maybe I can do this with awk or something, I'm not sure, but I think a very convenient feature to consider is being able to fuzzy find something, mark that item, and then jump to the marked item in the full context of results list, clearing away the search query. It would be great to simplify this task I'm doing to something like `cat /path/to/file | fzf --bind=ctrl-n:jump-to-mark`. Thanks.

**Comment by junegunn** [comment]
Have you tried using the preview window with the scroll offset option?

```sh
git grep --line-number '' |
  fzf --delimiter=: --layout=reverse --nth=3.. \
      --preview='bat --style=numbers --color=always --highlight-line {2} {1}' \
      --preview-window=+{2}-/2
```

(from https://github.com/junegunn/fzf/blob/master/CHANGELOG.md#0230)

**Comment by windowswithoutborders** [comment]
yes, but I believe it's limited to only serving as a more intermediate solution. My fzf will fuzzy search on the left, and the preview window (at least how I have it implemented) will present the results I want on the right, but I cannot select them from the right, I just have to keep a bit of information in mind and restart my search.

**Comment by junegunn** [comment]
The requirement is too specific, and I don't think fzf can provide a good abstraction for the use case. After all, fzf is an interactive version of `grep`.

What I would try is to take the line number with fzf, use sed or something to extract the lines I need, and relaunch fzf.

```sh
FILE=~/.bashrc
LNO=$(cat $FILE | nl -ba | fzf --reverse --with-nth 2.. | awk '{print $1}'); echo $LNO
sed -n "$LNO,$((LNO + 10))p" "$FILE" | fzf --reverse
```

**Comment by windowswithoutborders** [comment]
@junegunn 
Greatly appreciate your example. This accomplishes perfectly what I was trying to do, on top of being very educational for a me as a bash novice.
