### ISSUE TITLE
fzf's window has only half of the border in other encoding

### ISSUE THREAD

**Issue by ofseed** [junegunn/fzf#2389]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [ ] Mac OS X
    - [x] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [ ] fish
    
## Problem / Steps to reproduce
After Installed fzf, I found it's window has only a half the border like this. The screenshot is taken in nvim-qt, but the problem is same to fzf in console, the preview window also has only half of the border.
![image](https://user-images.githubusercontent.com/61115159/110931907-c382d900-8365-11eb-805b-f579943a41b3.png)
The reason might be my console is using GBK encoding. If I turn on the option 'Beta: Using UTF-8 provide global language support' in Windows, the window of fzf would display completely. But many of the programs in Windows is still using GBK encoding, including MSVC and JDK. If I change the encoding setting, they will output garbled characters.
It's very strange. Why half could display but the other half could not?

**Comment by junegunn** [comment]
https://github.com/junegunn/fzf/pull/3111 might help which includes fix to https://github.com/gdamore/tcell/issues/578.

This is a binary built from the latest source.

[fzf-0.35.1-devel-windows_amd64.zip](https://github.com/junegunn/fzf/files/10334231/fzf-0.35.1-devel-windows_amd64.zip)

**Comment by mzr1996** [comment]
> #3111 might help which includes fix to [gdamore/tcell#578](https://github.com/gdamore/tcell/issues/578).
> 
> This is a binary built from the latest source.
> 
> [fzf-0.35.1-devel-windows_amd64.zip](https://github.com/junegunn/fzf/files/10334231/fzf-0.35.1-devel-windows_amd64.zip)

I notice that fzf 0.35.1 doesn't have this problem, but fzf>=0.36.0 has this problem.
And the issue you mentioned helps. Adding `let $RUNEWIDTH_EASTASIAN=0` in my vim config fixed it when fzf>=0.36.0.

**Comment by menghuu** [comment]
I have the same problem and after add `RUNEWIDTH_EASTASIAN=0`, it is fixed 

the 0.39 version insalled by brew:
![image](https://user-images.githubusercontent.com/15952209/232319154-c7dcfcfa-63ae-42a0-92a8-94c8c9b2613a.png)



the 0.29 version installed by apt
![image](https://user-images.githubusercontent.com/15952209/232319122-6b11fe4c-b5ac-4919-a79e-c9b762f2bc06.png)



some environment variables are:
```bash
> echo $FZF_DEFAULT_COMMAND
fd --hidden --follow --type f --exclude .git

> echo $FZF_DEFAULT_OPTS
--height 40% --layout=reverse --border

> echo $FZF_CTRL_T_COMMAND
fd --hidden --follow --exclude .git

> echo $FZF_ALT_C_COMMAND
fd --hidden --follow --exclude .git --type d

> echo $FZF_CTRL_T_OPTS



> /home/linuxbrew/.linuxbrew/bin/fzf --version
0.39.0 (brew)

> /bin/fzf --version
0.29 (devel)
```


**I read the manpage, and test some case, actually `--no-unicode` or `RUNEWIDTH_EASTASIAN=0`(not 1 mentions in manpage) works** but why 0.29 version works well, and 0.39 is breaking?

![image](https://user-images.githubusercontent.com/15952209/232319747-39daea8a-42b5-4a73-b11e-f59c8828072e.png)

![image](https://user-images.githubusercontent.com/15952209/232319776-599888bd-cdd8-47af-8a98-b040acb94123.png)

AND, with `RUNEWIDTH_EASTASIAN=0` actually work (thanks https://github.com/junegunn/fzf/issues/2389#issuecomment-1414581508)
![image](https://user-images.githubusercontent.com/15952209/232322266-bc6fbcde-8328-4398-9419-50d0db730267.png)

**Comment by junegunn** [comment]
@menghuu See https://github.com/junegunn/fzf/commit/0c5956c43c1604d8e4364f08369dc4c58295ef3c.

I'll update the manual page to suggest `0` as well.
Unfortunately, there is no one-size-fits-all solution for this problem. 0.29 worked well for your environment but it didn't in some other environments.
