### ISSUE TITLE
Open in splits when using fzf#run

### ISSUE THREAD

**Issue by Linuus** [junegunn/fzf#239]
Hi!

I'm using `fzf#run` in my .vimrc because I want to have the tmux split at the top.
```viml
nnoremap <silent> <Leader>f :call fzf#run({
\   'up': '40%',
\   'sink': 'e' })<CR>
```

When using `:FZF` I can use `CTRL-V, CTRL-X` to open splits, but it does not work with `fzf#run`.

Can I get this functionality somehow? Can I pass the `up` option to `:FZF` instead?

**Comment by noahfrederick** [comment]
> Can I pass the up option to :FZF instead?

No, you'll have to create your own `:FZF` command. You can refer to the [existing implementation](https://github.com/junegunn/fzf/blob/master/plugin/fzf.vim#L345-375)—there isn't much to it.

**Comment by junegunn** [comment]
@noahfrederick Thanks.

@Linuus Yes, I want you to see `:FZF` just as an example implementation using `fzf#run()`. You'll have to write your own command. I know it can be frustrating if you don't know Vimscript well, but it'll pay off in the long run and give you the ultimate flexibility. 

`:FZF` looks at a few global variables that we can omit here. So this will do the trick.

```vim
function! s:my_fzf_handler(lines) abort
  if empty(a:lines)
    return
  endif
  let cmd = get({ 'ctrl-t': 'tabedit',
                \ 'ctrl-x': 'split',
                \ 'ctrl-v': 'vsplit' }, remove(a:lines, 0), 'e')
  for item in a:lines
    execute cmd escape(item, ' %#\')
  endfor
endfunction

nnoremap <silent> <leader>f :call fzf#run({
  \ 'options': '--expect=ctrl-t,ctrl-x,ctrl-v',
  \ 'up':      '40%',
  \ 'sink*':   function('<sid>my_fzf_handler')})<cr>
```

Hmm, but I just noted that `up` doesn't work nicely with horizontal splits.

**Comment by Linuus** [comment]
@noahfrederick @junegunn Thank you both! I just tried what @junegunn posted and it seems to work great. Yes, I'm not very good at vimscript but I agree this is more flexible :)
