### ISSUE TITLE
binnary is broken under Mac El Capitan (dyld: _clock_gettime not found)

### ISSUE THREAD

**Issue by m2habert** [junegunn/fzf#2391]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [x] Mac OS X   El Capitan 10.11.6
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

OS : El Capitan 10.11.6

Never had any problem with fzf until yesterday. That's when vim-plug, while updating, reported an error ( something to do with post hooks, don't really recall)

I tried to repeat the :PlugUpdate and it didn't work. So I tried reinstalling, which made fzf report errors with several functions.

I then proceed to do a total reinstall: (~/.fzf/uninstall + delete ~/.fzf) and follow the manual page.

The git cloning worked as usual, but since then ~/.fzf/install fails with:

`Error: dyld: Symbol not found: _clock_gettime` 

This "_clock_gettime" thing is a problem that have showed up here and there since forever, something to do with Xcode defining but not linking to the lib (which only High Sierra has), or something else that fails my grasp, but it has never been a problem to fzf...

Of course, upgrading to 10.12 would probably solve this, but I can't do it at the moment.

Any thing that I could do as temporary measure? Is there a way to fix this and keep it available to El Cap users?

Thanks.

**Comment by junegunn** [comment]
Probably because the latest binary was built using Go 1.16. I'll see what I can do.

**Comment by junegunn** [comment]
Have you tried installing fzf using `brew`?

**Comment by m2habert** [comment]
Nope.

I've tried using macports. And it didn't work. (macports have always been well behaved in my system while I had same "_clock_gettime" problem with some brew packages -- although I do not clame that I know what I'm talking about :-)  )

I was under the impression that home brew had abbanoned El Cap 10.11, no?

**Comment by m2habert** [comment]
> Probably because the latest binary was built using Go 1.16. I'll see what I can do.

macports outputted errors related to go-16 as well

**Comment by junegunn** [comment]
> I was under the impression that home brew had abbandoned El Cap 10.11, no?

I didn't know about that.

You can try building fzf from source with an older version of Go
* https://github.com/junegunn/fzf/blob/master/BUILD.md

**Comment by junegunn** [comment]
Closing as we're building fzf with Go 1.20, and it's not feasible to go back.
