### ISSUE TITLE
Feature request: complain if loaded after bash-completions

### ISSUE THREAD

**Issue by SuperSandro2000** [junegunn/fzf#2392]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf ``0.26.0 (34fe5ab)``
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

Loading fzf before bash_completion does not take over the current input when pressing Ctrl+R or hide the prompt. This should ideally be detected by fzf or be documented.

**Comment by junegunn** [comment]
Thanks for the suggestion but I don't think this is possible since bash_completion is an optional component of the system.
