### ISSUE TITLE
fzf not working in WSL Neovim

### ISSUE THREAD

**Issue by gabrielbeauchemin** [junegunn/fzf#2393]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [ ] Mac OS X
    - [x] Windows (WSL2)
- Category
    - [ ] vim
    - [x] nvim
    - [x] fzf-binary
    - [ ] completion
    
## Problem / Steps to reproduce
Good evening,

I am not able to use fzf in WSL Neovim. When I try to do :Files /mnt/, Files ~, :FZF /mnt/ or FZF ~, the fzf window open but has this error displayed: "Command failed: rg --files --hidden".

Steps to reproduce:
- Install WSL
- Install nvim on the WSL setup.
- Using Plug, install fzf (:PlugInstall with this line in the plug settings: Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }). Plug show fzf as well installed.
- I also tried installing fzf using git on WSL. The command fzf is working on the WSL bash, but not in nvim (I always get "Command failed: rg --files --hidden" displayed.

The other plugins are working well in my WSL setup. Not sure if I am doing something wrong or if it is a limitation of fzf.  Thanks for the help!

**Comment by junegunn** [comment]
You have configured fzf to use `rg --files --hidden` (because it's not the default), but the command is failing probably because `rg` is not installed on your system.

**Comment by gabrielbeauchemin** [comment]
Oh thanks I did not realize it. I remove from my fzf plug configs the references of rg, and now everything works fine!

**Comment by gabrielbeauchemin** [comment]
btw nice animals rights activist icon :)
