### ISSUE TITLE
[FR] word breaks

### ISSUE THREAD

**Issue by NightMachinery** [junegunn/fzf#2394]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

Having a way to mark a word as ended (words are by default all prefixes in fzf) is very useful. E.g., I am trying to find a function named `z`, and this is rather hard with prefixes:
![image](https://user-images.githubusercontent.com/36224762/111598010-03bddd80-87e4-11eb-9e5d-3eced04f7b5c.png)

Possible syntax choices: `word'`, `word\W`, `word$$`.

**Comment by junegunn** [comment]
> words are by default all prefixes in fzf

I don't understand what you mean by this. Can you elaborate?

> find a function named z

How about just typing `z()` or `z{`? It works pretty well for me.

![image](https://user-images.githubusercontent.com/700826/111895961-7c799f80-8a59-11eb-9a5a-7296e783c61c.png)

![image](https://user-images.githubusercontent.com/700826/111895962-84d1da80-8a59-11eb-8cc4-478fd537bad9.png)

I'm not interested in extending the search syntax of fzf as I want it to be very easy and straightforward to the users. I don't want them to spend some extra time learning a special syntax that can only be used within fzf.

**Comment by NightMachinary** [comment]
@junegunn How hard would it be for me to add this in a fork? Which function should I change?

**Comment by junegunn** [comment]
See https://junegunn.github.io/fzf/releases/0.55.0/#exact-boundary-match-type
