### ISSUE TITLE
[Question] Is there any sort of event I can tie into or a way to make it so a command can run upon having the fzf window no longer on screen?

### ISSUE THREAD

**Issue by MostHated** [junegunn/fzf#2397]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

It is not even remotely a problem, merely asking if anyone might have any suggestions. I am trying to find a way to run a command anytime the fzf window is no longer on the screen. It's stilly, but whenever it closes it leaves the cursor halfway up the screen as seen below.

![](https://i.imgur.com/9XI6pND.gif)

I then use the following `clear` alias to put the prompt back at the bottom.

```sh
alias clear='clear && tput cup 9999 0'
```
So really, I am just wondering if there is perhaps something built into fzf that I am just not seeing in which I can tell it to run `tput cup 9999 0` when it closes? If not, it is no big deal, I am sure I can figure out something another way.

Thanks,
-MH

**Comment by junegunn** [comment]
Nothing builtin for that. I suppose you could use a wrapper script like so.

```sh
#!/bin/sh
trap 'clear && tput cup 9999 0' EXIT
/path/to/original/fzf --height 50% "$@"
```

**Comment by MostHated** [comment]
I appreciate the reply. That seems like it should do nicely. Should I then just end up calling that script in place of fzf?
 If you don't mind, what about a situation such as this?

I currently have this setup in zsh.
```sh
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
export FZF_DEFAULT_COMMAND='fd --type file --color=always --follow --hidden --exclude .git'
export FZF_DEFAULT_OPTS="--ansi --height 60%"
```
Would I then do something like this instead? (Where fzf_closer is the script you shared above)
```sh
export FZF_DEFAULT_COMMAND='~/.zsh/scripts/fzf_closer.zsh $(fd --type file --color=always --follow --hidden --exclude .git)'
```
Thanks again,
-MH
