### ISSUE TITLE
Please enable GitHub Discussions

### ISSUE THREAD

**Issue by marcastel** [junegunn/fzf#2398]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

Firstly. I just stumbled across your repository. A great piece of software I wished I had learned about years ago :-)

So much so that I imagine a myriad ways in which I would like to use it. Many topics come to mind, but I don't believe they belong in the issues area of the repository, hence my suggestion to open a [discussions](https://docs.github.com/en/discussions) now available on private and public repositories.

The discussions I would immediately be tempted to initiate are, unsorted:

1. Borrow functionality from `rsync` such as `--exclude`, `--exclude-from`, `--include`,  `--include-from`, or `--files-from` to easily handle noisy directories such as `node_modules`, `vendor`, or tmp/swap directories, backup files, etc.
1. Borrow functionality from `find` to include file attributes (i.e. time, permissions, ownership)
1. Include caching possibly with a dedicated daemon and `make`-like algorithms
1. Offer as a shell extension (KornShell, Bash) managed through `set fzf on/off` such that `vim **` becomes automagically `vim $(fzf **)`
1. Include capabilities from `attr` to match tags in addition to file names
1. Have metrics on how performance scales (e.g. +60mn for 7mio files)
1. Set the functional boundaries of `fzf`? (aka UNIX philosophy for binaries)
1. Standardisation... with the possible end-goal of being POSIX-compliant

**Comment by junegunn** [comment]
Thanks for the suggestion. Done.

FYI, some of the items you mentioned were already discussed on the issue tracker. Here are a few pointers.

* https://github.com/junegunn/fzf#respecting-gitignore
* #2330
* #763
* #578

Simply put, fzf is more like `grep` not `find` so it doesn't want `find`-like tool's capabilities (Unix philosophy).

Regarding the performance, I think fzf is fast enough that its performance is no longer an issue for most common use cases. If someone is running into a performance problem, they should ask if fzf is the right tool for the job. For example, for searching the file contents, ripgrep is a much better fit. You still can use fzf to add interactivity to it.

```sh
RG() {
  RG_PREFIX="rg --column --line-number --no-heading --color=always --smart-case "
  INITIAL_QUERY="$1"
  local selected=$(
    FZF_DEFAULT_COMMAND="$RG_PREFIX '$INITIAL_QUERY' || true" \
      fzf --bind "change:reload:$RG_PREFIX {q} || true" \
          --ansi --disabled --query "$INITIAL_QUERY" \
          --delimiter : \
          --preview 'bat --style=full --color=always --highlight-line {2} {1}' \
          --preview-window '~3:+{2}+3/2'
  )
  [ -n "$selected" ] && $EDITOR "$selected"
}
```
