### ISSUE TITLE
fzf, Ag and current buffer

### ISSUE THREAD

**Issue by aliev** [junegunn/fzf#240]
I found the following piece of code for integration fzf and Ag:

function! s:escape(path)
  return substitute(a:path, ' ', '\\ ', 'g')
endfunction

function! AgHandler(line)
  let parts = split(a:line, ':')
  let [fn, lno] = parts[0 : 1]
  execute 'e '. s:escape(fn)
  execute lno
  normal! zz
endfunction

command! -nargs=+ Ag call fzf#run({
  \ 'source': 'ag "<args>"',
  \ 'sink': function('AgHandler'),
  \ 'options': '+m',
  \ 'tmux_height': '40%'
\ })

is it possible to search on the current buffer too?

for example :Ag % search_string

thanks!

**Comment by junegunn** [comment]
You might want to check out the recent version of the code here:
https://github.com/junegunn/fzf/wiki/Examples-(vim)#narrow-ag-results-within-vim

> is it possible to search on the current buffer too?

Check out the FZFLines example in the wiki page and see if you can adapt it to your needs.
https://github.com/junegunn/fzf/wiki/Examples-(vim)#search-lines-in-all-open-vim-buffers

**Comment by aliev** [comment]
@junegunn thank you very much! one more question: how to implement search for tags, without the tags file as in ctlpbuftag? for example: https://coderwall.com/p/x39gbg/use-ctrlp-s-ctrlpbuftag-to-quickly-jump-to-methods

**Comment by junegunn** [comment]
Looks like ctrlp.vim generates tags itself though I haven't checked the source. I just updated FZFTags example in the wiki page to generate tags file with simple `ctags -R` command. Maybe it's too simple, but you get the idea, you can use it as the starting point.

https://github.com/junegunn/fzf/wiki/Examples-(vim)#jump-to-tags

**Comment by vysakh0** [comment]
@junegunn Hey, thanks for the awesome project. I copied the https://github.com/junegunn/fzf/wiki/Examples-(vim)#narrow-ag-results-within-vim (AG results in vim) in my vimrc and 
I tried `:Ag my_pattern` in my directory, the tmux window quickly opens and closes down, before I could look through the files. 

The other functions like `FZFMru`, `FZFTags`, `FZFTagFile`, `FZFLines`, just works, wondering what I did wrong, can you please help?

**Comment by junegunn** [comment]
@vysakh0 Which version do you have? `fzf --version`

**Comment by vysakh0** [comment]
@junegunn Just updated fzf, it works :) Thanks :+1:

**Comment by vysakh0** [comment]
@junegunn I've another question, hope you won't mind. In Vim, 
- I did `:Ag mypattern`, it returned 4 results, 
- I chose the first result, and fzf window (tmux split) closes, 
- I've to do `:Ag mypattern` again to see the other results. 

Question: How to close the split window(fzf results) only on pressing escape, not on any selection of results?

**Comment by edi9999** [comment]
I think you could use the new `execute`action #265

However I don't know exactly how to implement it wit vimscript

**Comment by junegunn** [comment]
@vysakh0 It's one of the things that bothers me too, but there's no good solution to it. Since fzf is not a native vim plugin, the level of integration can be suboptimal. If the repository isn't too big so asynchronous search is not really necessary, it's better to just use `&grepprg`.

```vim
if executable('ag')
  let &grepprg = 'ag --nogroup --nocolor --column'
else
  let &grepprg = 'grep -rn $* *'
endif
command! -nargs=1 -bar Grep execute 'silent! grep! <q-args>' | redraw! | copen
```

**Comment by junegunn** [comment]
@vysakh0 I updated the ag example to use `--multi` and `--bind ctrl-a:select-all`, so now you can select multiple items (with tab/shift-tab and ctrl-a) and list them in quickfix window.

https://github.com/junegunn/fzf/wiki/Examples-(vim)#narrow-ag-results-within-vim

**Comment by vysakh0** [comment]
@junegunn :dancers: thank you :+1:

**Comment by sangwook** [comment]
:+1:
