### ISSUE TITLE
No prebuilt binary for Darwin arm64 ... go executable not found. Installation failed.

### ISSUE THREAD

**Issue by fahadshery** [junegunn/fzf#2401]
## Info

- OS
    - [ ] Mac OS Big Sur with M1 Chip
    - Shell
    - [ ] zsh
    
## Problem / Steps to reproduce
run in iterm2:
```git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
~/.fzf/install```

Getting the following error:
```No prebuilt binary for Darwin arm64 ...
go executable not found. Installation failed.```

**Comment by fahadshery** [comment]
had to install:
```
brew install golang
```
it then installs it fine

**Comment by junegunn** [comment]
Ah, we do provide Darwin arm64 binary now, but I forgot to update the Makefile accordingly.

https://github.com/junegunn/fzf/releases/download/0.26.0/fzf-0.26.0-darwin_arm64.tar.gz

**Comment by junegunn** [comment]
Related: #2400
