### ISSUE TITLE
vim matchparen highlight is drawn over fzf popup

### ISSUE THREAD

**Issue by adigitoleo** [junegunn/fzf#2406]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf (0.26.0 34fe5ab)
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

The vim matchparen highlight is drawn on fzf popup windows.

1. Use the provided minimal vimrc below, changing the runtimepath statement to point to the appropriate install directory of `fzf.vim`
2. Open vim (nvim) with `-u <vimrc>` pointing to the miminal vimrc
3. Enter insert mode and type a pair of brackets e.g. `[]`, return to normal mode and keep the cursor above one of the brackets (verify that the matchparen highlights are enabled)
4. If using neovim, hit semicolon `;` to open a rudimentary test popup, notice the lack of highlights in the popup window (close with `:q`)
5. Run `:FZF` from normal mode to open a fzf popup, notice that a highlight is drawn over the border at the first line of the border popup

```vim
if has("nvim")
    function! FloatwinTest() abort
        let l:buf = nvim_create_buf(0, 1)
        let l:width = &columns > 80 ? 78 : &columns * 2/3
        let l:height = &lines * 2/3
        let l:win = nvim_open_win(
                    \ l:buf,
                    \ 1,
                    \ {
                    \   'relative': 'editor',
                    \   'width': l:width,
                    \   'height': l:height,
                    \   'row': (&lines - l:height) / 2,
                    \   'col': (&columns - l:width) / 2,
                    \   'style': 'minimal',
                    \ }
                    \)
        call nvim_buf_set_lines(l:buf, 0, 1, 1, [repeat("test ", 10)])
    endfunction

    nmap ; <Cmd>call FloatwinTest()<Cr>
endif

let &runtimepath.=','..'/usr/share/vim/vimfiles'
```

It's especially noticable when filetype plugins make use of matchparen highlights in other ways, e.g. vimtex. I'm not sure that it is limited to the border buffer, or maybe it is bleeding through from below but I can see longer highlights in some cases. Let me know if you can repro or if I should include screenshots.

**Comment by junegunn** [comment]
It's probably a bug of Neovim. You can reproduce the problem without fzf like so:

```vim
if has("nvim")
    function! FloatwinTest() abort
        let l:buf = nvim_create_buf(0, 1)
        let l:width = &columns > 80 ? 78 : &columns * 2/3
        let l:height = &lines * 2/3
        let l:win = nvim_open_win(
                    \ l:buf,
                    \ 1,
                    \ {
                    \   'relative': 'editor',
                    \   'width': l:width,
                    \   'height': l:height,
                    \   'row': (&lines - l:height) / 2,
                    \   'col': (&columns - l:width) / 2,
                    \   'style': 'minimal',
                    \ }
                    \)
        " call nvim_buf_set_lines(l:buf, 0, 1, 1, [repeat("test ", 10)])
        call termopen('echo foo; echo bar', {})
        startinsert
    endfunction

    nmap ; <Cmd>call FloatwinTest()<Cr>
endif
```

![image](https://user-images.githubusercontent.com/700826/112609131-80912d00-8e5e-11eb-8b65-341346aaafcf.png)

**Comment by adigitoleo** [comment]
Hmm, somehow I can't repro using termopen:

![image](https://user-images.githubusercontent.com/34595875/112706238-22fcef00-8ef7-11eb-983b-0fa3c041021a.png)

My neovim version:

```
NVIM v0.4.4
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.4.4/src -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"
```

**Comment by adigitoleo** [comment]
I looked at this again and I can reproduce the bug using the minimal vimrc you provided, if the buffer with the brackets `[]` is still in the **modified** state. So I think that you are right and it's a neovim bug.
