### ISSUE TITLE
Codesigning Darwin Releases

### ISSUE THREAD

**Issue by ChefAustin** [junegunn/fzf#2408]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

Would be super great if `fzf` were codesigned. AFAICT, the latest darwin build isn't codesigned:
```
$ codesign -v ./fzf
$
$ spctl --assess --type execute --verbose=4 ./fzf
./fzf: rejected
```

**Comment by junegunn** [comment]
Yeah, but that would cost me [$99 a year](https://developer.apple.com/support/purchase-activation/).

**Comment by junegunn** [comment]
Thanks to [the great people](https://github.com/junegunn/junegunn/blob/main/BACKERS.md) who have financially supported me, I think I can consider getting an Apple developer ID.

**Comment by junegunn** [comment]
The next release will include signed and notarized binaries. You can test these archives:

* [fzf-0.26.0-devel-darwin_amd64.zip](https://github.com/junegunn/fzf/files/6263459/fzf-0.26.0-devel-darwin_amd64.zip)
* [fzf-0.26.0-devel-darwin_arm64.zip](https://github.com/junegunn/fzf/files/6263465/fzf-0.26.0-devel-darwin_arm64.zip)

```sh
$ spctl --assess --type install -vvv fzf
fzf: accepted
source=Notarized Developer ID
origin=Developer ID Application: Junegunn Choi (Y254DRW44Z)
```

**Comment by ChefAustin** [comment]
This is amazing. Thanks so much!
