### ISSUE TITLE
Using a command with sudo, it seems like fzf doesn't let me enter input to the password prompt

### ISSUE THREAD

**Issue by MostHated** [junegunn/fzf#2412]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

I was attempting to use a function to make things a bit easier but wasn't getting any results, after trying a few things, I realize that when trying to pipe a sudo'd ripgrep search to fzf hid the password prompt so it just sat there showing the fzf 0/0 results screen.

<details open>
<summary>Attempted Function</summary>

```sh
function srgx() {
    if [ $# -ne 0 ]; then
        if [ $# -eq 1 ]; then
            echo "Searching: $1"
           sudo rg "$1" /  --color ansi 2>/dev/null | fzf --ansi  
        fi
        if [ $# -eq 2 ]; then
            echo "Searching: $1 in $2"
           sudo rg "$1" $2 --color ansi 2>/dev/null | fzf --ansi  
        fi
    else
        echo "Must Include Search Parameters"
    fi
}
```

</details>

Just to be sure, I went to run the standalone command as well to be sure:

```sh
sudo rg 'test' / --color ansi 2>/dev/null | fzf --ansi  
```

You can see it in action below. It also seems to mess up my terminal until I close and reopen it:

![](https://i.imgur.com/Xq5IcBs.gif)

Does anyone have any suggestions on what I might do to remedy this?
Thanks,
-MH

**Comment by junegunn** [comment]
Both sudo and fzf are trying to read your keyboard input and print to STDERR. You might want to break it down into two commands.

```sh
sudo rg ... > /tmp/list
fzf --ansi < /tmp/list
```
