### ISSUE TITLE
fzf is not working on ubuntu 20.04 bash/terminal

### ISSUE THREAD

**Issue by seyeeet** [junegunn/fzf#2413]
- [x ] I have read through the manual page (`man fzf`)
- [x ] I have the latest version of fzf
- [x ] I have searched through the existing issues

## Info

- OS
    - [ x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

I have been using fzf just for searching stuff in terminal, like when I want to search a command after installing fzf I could find it easily via ctr+R like:
![image](https://user-images.githubusercontent.com/62394093/112744211-f6cf8580-8f6b-11eb-8378-d92d7f8642fe.png)
 but now on ubuntu 20.04 when I do ctr+R it does not show me the options anymore and it is like normal ctr+R in the terminal, what should I do?

**Comment by Gee19** [comment]
I noticed this in the readme:
```
    ⚠️ Key bindings (CTRL-T / CTRL-R / ALT-C) and fuzzy auto-completion may not be enabled by default.

    Refer to the package documentation for more information. (e.g. apt-cache show fzf)
```

You need the following in your `.bashrc` after `bash_completion`
```
[ -f ~/.fzf.bash ] && source ~/.fzf.bash
```

**Comment by seyeeet** [comment]
@Gee19 thanks for your help. 
I added `[ -f ~/.fzf.bash ] && source ~/.fzf.bash` to the `.bashrc` but nothing changed.
can you please explain what do you mean with `bash_completion`?
also if I do `apt-cache show fzf` , I will get 
```
 apt-cache show fzf
Package: fzf
Architecture: amd64
Version: 0.20.0-1
Built-Using: golang-1.13 (= 1.13.5-1ubuntu1), golang-github-mattn-go-isatty (= 0.0.8-2), golang-github-mattn-go-runewidth (= 0.0.4-1), golang-github-mattn-go-shellwords (= 1.0.6-1), golang-go.crypto (= 1:0.0~git20190701.4def268-2), golang-golang-x-sys (= 0.0~git20190726.fc99dfb-1ubuntu2)
Priority: optional
Section: universe/utils
Origin: Ubuntu
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Mo Zhou <cdluminate@gmail.com>
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Installed-Size: 3024
Filename: pool/universe/f/fzf/fzf_0.20.0-1_amd64.deb
Size: 954428
MD5sum: 4a244a587897b17ac60b9f14ddfb52fe
SHA1: d5bec179f3448f80e75234a2a26ec8a583cfb151
SHA256: ffb52c73fdf06d915ee8b3df14acb0583fcc445ae33891902301eabf546377fd
Homepage: https://github.com/junegunn/fzf
Description-en: general-purpose command-line fuzzy finder
 It's an interactive Unix filter for command-line that can be used with
 any list; files, command history, processes, hostnames, bookmarks, git
 commits, etc.
 .
 Refer /usr/share/doc/fzf/README.Debian for quick instructions on how to
 add keybindings for Bash, Zsh, Fish to call fzf.
Description-md5: a0bfeecf96a19354d63fcb504b7530c9
```

I am not sure what I should do after I finished installation, is there anything else I should do?

**Comment by Gee19** [comment]
Did you try reloading your session? Are you using zsh? You can check with `echo $SHELL`

**Comment by junegunn** [comment]
`~/.fzf.bash` file is only created when you manually run the `install` script in this repository. If the user installed fzf using a package manager, the file won't exist.

Please follow the package instruction as shown in the message.

>  Refer /usr/share/doc/fzf/README.Debian for quick instructions on how to
>  add keybindings for Bash, Zsh, Fish to call fzf.

**Comment by seyeeet** [comment]
Thanks 
ended up removing it and installing it from git and do `cd ~/.fzf && git pull && ./install` and now it seems working good

**Comment by gerbsen** [comment]
And this works for Ubuntu 20.04. 

```
source /usr/share/doc/fzf/examples/key-bindings.zsh
source /usr/share/doc/fzf/examples/completion.zsh
```

**Comment by islandmonkey** [comment]
> If someone is still looking for how to enable fzf for bash on Ubuntu 22.04, this command worked for me:
> 
> `source /usr/share/bash-completion/completions/fzf`

Adding this to the bottom of .bashrc also works for Ubuntu 24.04
