### ISSUE TITLE
Feature request / clarification: Event for when the current selected line is changed

### ISSUE THREAD

**Issue by vijaymarupudi** [junegunn/fzf#2414]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

I would like an event that would be called every time that user changes their selection position using either the up / down keybindings, page up / page down, adding / removing from the query, etc. Currently I can access adding and removing a query, but I would like the binding to be run only when the user moves to a different item. This is very similar to the preview functionality, except I don't want to show a preview within fzf, I'll take care of that using the action.

The use case is for [nvim-fzf](https://github.com/vijaymarupudi/nvim-fzf) where I would like to preview a buffer within neovim itself, since vim / neovim does not expose a mechanism to output syntax highlighted ansi sequences for a buffer. 

CORRECTION: 
The `--preview-window right:0` approach works, I guess my question is whether this is the best way to accomplish this.

**Comment by junegunn** [comment]
> The --preview-window right:0 approach works, I guess my question is whether this is the best way to accomplish this.

Yes, it is. Preview window of size 0 is for supporting such use cases. See #820.

Excerpt from the man page:

> * If size is given as 0, preview window will not be visible, but fzf will still execute the command in the background.

Let me know if this trick doesn't work for your case.
