### ISSUE TITLE
--ansi doesn't catch escape codes [?7h and [?7l

### ISSUE THREAD

**Issue by amjack100** [junegunn/fzf#2420]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [x] zsh
    - [x] fish
    
## Problem / Steps to reproduce

Encountered this when trying to pipe output from nb to fzf. All the other escape sequences work as expected except these. [This](https://stackoverflow.com/questions/30206271/unknown-ansi-escape-codes-0-7h-and-7l) describes what they are but the answer uses some terminology I'm not familiar with. First time submitting an issue so apologies if I'm missing something here.
```
nb list | fzf --ansi
```
![Screenshot from 2021-04-01 08-22-38](https://user-images.githubusercontent.com/46258320/113293270-8dc97400-92c3-11eb-9b98-428aafa51684.png)

**Comment by junegunn** [comment]
Thanks, I'm not familiar with those codes and I don't know how to properly process them, so I'm going to make simply ignore those sequences.
