### ISSUE TITLE
Add an optional timeout to change event

### ISSUE THREAD

**Issue by vredesbyyrd** [junegunn/fzf#2421]
-  [x] I have read through the manual page (`man fzf`)
-  [x] I have the latest version of fzf
-  [x] I have searched through the existing issues

## Info

- OS
    -  [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    -  [x] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

Using the example in #1750,  

> 
> 3. Ripgrep integration
> 
> The following example uses fzf as the selector interface for ripgrep. We bound reload action to change event, so every time you type on fzf, ripgrep process will restart with the updated query string denoted by the placeholder expression {q}. Also, note that we used --phony option so that fzf doesn't perform any secondary filtering.

```
RG_PREFIX="rg --column --line-number --no-heading --color=always --smart-case "
INITIAL_QUERY=""
FZF_DEFAULT_COMMAND="$RG_PREFIX '$INITIAL_QUERY'" \
  fzf --bind "change:reload:$RG_PREFIX {q} || true" \
      --ansi --phony --query "$INITIAL_QUERY"
```

I understand that fzf is first and foremost a unix filtering tool, but the combination of `change:reload` +  `--phony` opens up a lot of possibilities. 

With the current design the change event is triggered whenever the query string changes. I would love to use fzf as a 'gui' for the wonderful [gosearch](https://github.com/ozeidan/gosearch) in the same manner as the ripgrep example...but reloading on each keypress is a little too much.  

Would you consider adding a optional timeout/debounce to the `change` event, ie, timeout would default to `0`, but if set the change event would not be triggered until the user stops typing for {foo}ms. I am not sure this syntax follows the rest of fzf, but perhaps something like  `fzf --bind "change(0.5):reload:$RG_PREFIX {q} || true" `

The simplicity of fzf and its preview window are very enticing as opposed to writing something from scratch just because the source process is a little to heavy to be called on each keypress. An optional timeout could solve that. I imagine an option like this could be useful when processing any large data-set. 

Just an idea! Thanks for your time.

**Comment by junegunn** [comment]
I see your point. An easy workaround that comes to my mind is to add a little sleep to the reload command. 

```sh
RG_PREFIX="rg --column --line-number --no-heading --color=always --smart-case "
INITIAL_QUERY=""
FZF_DEFAULT_COMMAND="$RG_PREFIX '$INITIAL_QUERY'" \
  fzf --bind "change:reload:sleep 0.2; $RG_PREFIX {q} || true" \
      --ansi --disabled --query "$INITIAL_QUERY"
```

This seems to work well and I wouldn't worry too much about starting and killing sleep process on every keypress. What do you think?

**Comment by vredesbyyrd** [comment]
> An easy workaround that comes to my mind is to add a little sleep to the reload command. 

Ahhh, right on. Good call! l tested adding sleep to the reload command and imo this is an absolutely acceptable workaround that appears to work (surprisingly?) well. fzf is a command line tool after all so this approach also makes perfect sense to me. 

Much appreciate the pointer and quick response. Ill close this
