### ISSUE TITLE
Is it possible to setup fzf for easy jump to function def?

### ISSUE THREAD

**Issue by rahmatawaludin** [junegunn/fzf#243]
I'm new vim user. I've read the wiki. But, still can't understand how to setup fzf.

What I want to accomplish is similiar to Sublime goto symbol. Refer to http://www.sublimetext.com on slide 5.

Basically, when I start typing filename and use `@` it show function name and I could quickly jump there.

If I just type `@`, it will show all method in current file (or list of heading if its markdown file). Actually, for this I could use https://github.com/tacahiroy/ctrlp-funky

But, looking at fzf performance. I think it will be better implemented using fzf.

Is anyone know how to setup this?

Thanks.. :)

**Comment by justinmk** [comment]
Generate tags using ctags. Then pipe the tags to fzf. I'm not sure of the details, though.

**Comment by rahmatawaludin** [comment]
I have created ctags using https://github.com/xolox/vim-easytags. It created a `tags` file on save.

Then I use FZFTags like this example https://github.com/junegunn/fzf/wiki/Examples-(vim)#jump-to-tags

But, It won't showing what I expect.

**Comment by junegunn** [comment]
ctrlp-funky [uses regular expressions for every file type](https://github.com/tacahiroy/ctrlp-funky/tree/master/autoload/ctrlp/funky/ft) it supports, I don't think I quite like the approach. I'd rather use ctags as @justinmk suggested. But for listing functions and stuff in a single file (that's what ctrlp-funky does, right?), performance hardly matters, so fzf won't give you much benefit.

> But, It won't showing what I expect.

You mean it doesn't work? Or you mean it's not equivalent to ctrlp-funky? `:FZFTags` is just a small example that works, and it would require some effort to make it fancier.

**Comment by rahmatawaludin** [comment]
Thanks for your response @junegunn :)
Yes, i just use your sample `:FZFTags` as is. I'm new to Vim. 
The https://github.com/xolox/vim-easytags plugin allow me to create tag on read and save a file. Here is my conf:
```
" ----- xolox/vim-easytags settings -----
" Where to look for tags files
set tags=./tags;,~/.vimtags
" Sensible defaults
let g:easytags_events = ['BufReadPost', 'BufWritePost']
let g:easytags_async = 1
let g:easytags_dynamic_files = 2
let g:easytags_resolve_links = 1
let g:easytags_suppress_ctags_warning = 1
```

But, FZFTags seem to show all my tag. Not limit it to current active file

What I want to have is like this:
![image](https://cloud.githubusercontent.com/assets/1274849/7852372/b652f152-0526-11e5-8c93-71a18269582f.png)

Where I can easily jump to the method. This also allow me to filter the method like this:
![image](https://cloud.githubusercontent.com/assets/1274849/7852379/cffbb94a-0526-11e5-9e38-c406d4bd8c07.png)

As a new user in Vim world, I still can't modify your sample `:FZFTags`. Maybe I need to learn some vim scripting to modify your script..

**Comment by rahmatawaludin** [comment]
Anyway, here is what I try to achieve.

Goto symbol in current file:
![screen shot 2015-05-28 at 10 49 29 am](https://cloud.githubusercontent.com/assets/1274849/7852408/5811439a-0527-11e5-93ec-ae3ba9d79c27.png)

Goto symbol on fuzzy search to other file:
![screen shot 2015-05-28 at 10 48 53 am](https://cloud.githubusercontent.com/assets/1274849/7852420/6de02466-0527-11e5-9f6d-2bd997a59cce.png)

**Comment by junegunn** [comment]
What does `:echo tagfiles()` say?

**Comment by rahmatawaludin** [comment]
```
[app/controllers/admin/tags', 'app/tags', 'tags', '/User/rahmatawaludin/tags', '/Users/rahmatawaludin/.vimtags']
```

The current folder is `app/controller/admin`.

**Comment by junegunn** [comment]
Then changing `join(tagfiles())` to `tagfiles[0]` will do, I think.

**Comment by rahmatawaludin** [comment]
Yes it show all tags in current file (I modify it to `tagfiles()[0]`). Its shown like this:
![screen shot 2015-05-28 at 11 09 24 am](https://cloud.githubusercontent.com/assets/1274849/7852594/2a45034a-052a-11e5-9230-941b2aa836f3.png)

Is possible to limit it only show functions? I've used https://github.com/majutsushi/tagbar, it could do this:
![screen shot 2015-05-28 at 11 08 50 am](https://cloud.githubusercontent.com/assets/1274849/7852600/50c1e40c-052a-11e5-94d1-11d829105114.png)

I've check it Vim script, maybe because my lack vim scripting skill, can'f find any clue..

**Comment by rahmatawaludin** [comment]
Here is another of its feature:
![screen shot 2015-05-28 at 11 13 54 am](https://cloud.githubusercontent.com/assets/1274849/7852624/af6b6ece-052a-11e5-8e3a-e3a8e4110584.png)

**Comment by junegunn** [comment]
I don't think it's related to vimscript skill. You should figure out the format of the tags file and preprocess the content using grep or sed.

**Comment by rahmatawaludin** [comment]
ah.. ok. I'll learn some format of tags file..

**Comment by justinmk** [comment]
The code for tagbar would be a good place to look for clues...

**Comment by rahmatawaludin** [comment]
I'm reading this https://github.com/majutsushi/tagbar/blob/master/syntax/tagbar.vim

```
" File:        tagbar.vim
" Description: Tagbar syntax settings
" Author:      Jan Larres <jan@majutsushi.net>
" Licence:     Vim licence
" Website:     http://majutsushi.github.com/tagbar/
" Version:     2.6.1

scriptencoding utf-8

if exists("b:current_syntax")
    finish
endif

let s:ics = escape(join(g:tagbar_iconchars, ''), ']^\-')
let s:pattern = '\(^[' . s:ics . '] \?\)\@<=[^-+: ]\+[^:]\+$'
execute "syntax match TagbarKind '" . s:pattern . "'"

let s:pattern = '\(\S\@<![' . s:ics . '][-+# ]\?\)\@<=[^*(]\+\(\*\?\(([^)]\+)\)\? :\)\@='
execute "syntax match TagbarScope '" . s:pattern . "'"

let s:pattern = '\S\@<![' . s:ics . ']\([-+# ]\?\)\@='
execute "syntax match TagbarFoldIcon '" . s:pattern . "'"

let s:pattern = '\(\S\@<![' . s:ics . ' ]\)\@<=+\([^-+# ]\)\@='
execute "syntax match TagbarVisibilityPublic '" . s:pattern . "'"
let s:pattern = '\(\S\@<![' . s:ics . ' ]\)\@<=#\([^-+# ]\)\@='
execute "syntax match TagbarVisibilityProtected '" . s:pattern . "'"
let s:pattern = '\(\S\@<![' . s:ics . ' ]\)\@<=-\([^-+# ]\)\@='
execute "syntax match TagbarVisibilityPrivate '" . s:pattern . "'"

unlet s:pattern

syntax match TagbarHelp      '^".*' contains=TagbarHelpKey,TagbarHelpTitle
syntax match TagbarHelpKey   '" \zs.*\ze:' contained
syntax match TagbarHelpTitle '" \zs-\+ \w\+ -\+' contained

syntax match TagbarNestedKind '^\s\+\[[^]]\+\]$'
syntax match TagbarType       ' : \zs.*'
syntax match TagbarSignature  '(.*)'
syntax match TagbarPseudoID   '\*\ze :'

highlight default link TagbarHelp       Comment
highlight default link TagbarHelpKey    Identifier
highlight default link TagbarHelpTitle  PreProc
highlight default link TagbarKind       Identifier
highlight default link TagbarNestedKind TagbarKind
highlight default link TagbarScope      Title
highlight default link TagbarType       Type
highlight default link TagbarSignature  SpecialKey
highlight default link TagbarPseudoID   NonText
highlight default link TagbarFoldIcon   Statement
highlight default link TagbarHighlight  Search

highlight default TagbarAccessPublic    guifg=Green ctermfg=Green
highlight default TagbarAccessProtected guifg=Blue  ctermfg=Blue
highlight default TagbarAccessPrivate   guifg=Red   ctermfg=Red
highlight default link TagbarVisibilityPublic    TagbarAccessPublic
highlight default link TagbarVisibilityProtected TagbarAccessProtected
highlight default link TagbarVisibilityPrivate   TagbarAccessPrivate

let b:current_syntax = "tagbar"
```

Still learning the pattern..

**Comment by junegunn** [comment]
You can refer to http://ctags.sourceforge.net/FORMAT
And this should probably work:

```sh
awk -F$'\t' 'match($4, /[fm]/) {print $1}' [TAG FILES]
```

I suggest that you take some time to learn the basics of unix commands. What you can do with fzf is extremely limited if you don't know how to compose tools.

**Comment by edi9999** [comment]
Here's what I use to filter for tags in the current file only:

```
command! FZFTagFile if !empty(tagfiles()) | call fzf#run({
\   'source': "cat " . tagfiles()[0] . ' | grep "' . expand('%:@') . '"' . " | sed -e '/^\\!/d;s/\t.*//' ". ' |  uniq',
\   'sink':   'tag',
\   'options':  '+m',
\   'left':     60,
\ }) | else | echo 'No tags' | endif

nnoremap <silent> <Leader>v :FZFTagFile<cr>
```

**Comment by acornejo** [comment]
I've noticed a bug in this feature, at least if I use the source described in the examples, namely:

```
command! FZFTagFile if !empty(tagfiles()) | call fzf#run({
\   'source': "cat " . tagfiles()[0] . ' | grep "' . expand('%:@') . '"' . " | sed -e '/^\\!/d;s/\t.*//' ". ' |  uniq',
\   'sink':   'tag',
\   'options':  '+m',
\   'left':     60,
\ }) | else | echo 'No tags' | endif
```

Suppose my tag files contain multiple classes, and several of them define a method named "X". Then if I use the above command to jump to the definition of the method X of the current file, it will instead jump to the definition of the method X of "some file" (probably the first one, but not the current file).

I presume this is because the tag sink receives only the name of the method, but the remaining information of the tag files is lost. Ideas on how to fix this?

**Comment by acornejo** [comment]
Just to chime in here. It turns out fzf can handle this perfectly using the --with-nth and providing a custom sink that executes the EX command specified on the selected tag.

**Comment by aliev** [comment]
@junegunn 

I found a small solution (taken from CtrlPBufTag) without creating tagfile (works with current buffer):

```
command! FZFTag call fzf#run({
\   'source': "ctags -f - --sort=no --excmd=pattern --language-force=" . expand(&filetype) . " " . expand('%:@') . ' | grep "' . expand('%:@') . '"' . " | sed -e '/^\\!/d;s/\t.*//' ". ' |  uniq',
\   'sink':     'e ',
\   'options':  '+m',
\   'left':     60,
\ })

```

But go to line I can't realize. maybe you have a solution? (it would be great to display the expression type too like in ctlp). For example:

JSONField | 32 | class

Example usage:

```
➜  dj-stripe git:(feature/#22-#142-model-based-plans) ✗ ctags -f - --sort=no --excmd=pattern djstripe/forms.py --language-force=python
forms	djstripe/forms.py	/^from django import forms$/;"	i
djstripe_settings	djstripe/forms.py	/^from . import settings as djstripe_settings$/;"	i
PlanForm	djstripe/forms.py	/^class PlanForm(forms.Form):$/;"	c
plan	djstripe/forms.py	/^    plan = forms.ChoiceField(choices=djstripe_settings.get_plan_choices())$/;"	v	class:PlanForm
CancelSubscriptionForm	djstripe/forms.py	/^class CancelSubscriptionForm(forms.Form):$/;"	c
➜  dj-stripe git:(feature/#22-#142-model-based-plans) ✗
```

![fzf-ctags](https://dl.dropboxusercontent.com/u/5837324/fzfctag.png)

Thanks!

**Comment by junegunn** [comment]
@aliev 

Here be dragons!

```vim
" ----------------------------------------------------------------------------
" BTags
" ----------------------------------------------------------------------------
function! s:align_lists(lists)
  let maxes = {}
  for list in a:lists
    let i = 0
    while i < len(list)
      let maxes[i] = max([get(maxes, i, 0), len(list[i])])
      let i += 1
    endwhile
  endfor
  for list in a:lists
    call map(list, "printf('%-'.maxes[v:key].'s', v:val)")
  endfor
  return a:lists
endfunction

function! s:list_tags()
  let lines = map(split(system(printf(
    \ 'ctags -f - --sort=no --excmd=pattern --language-force=%s %s',
    \ &filetype, expand('%:S'))), "\n"), 'split(v:val, "\t")')
  if v:shell_error
    throw 'failed to extract tags'
  endif
  return map(s:align_lists(lines), 'join(v:val, "\t")')
endfunction

function! s:go_to_tag(line)
  execute split(a:line, "\t")[2]
endfunction

command! BTags
\ call fzf#run({'source':  s:list_tags(),
\               'down':    '40%',
\               'options': '--no-multi --delimiter "\t" --with-nth 1,4..',
\               'sink':    function('s:go_to_tag')})
```

**Comment by aliev** [comment]
@junegunn wow! thanks!!!! :)

**Comment by acornejo** [comment]
For posterity, here is my own solution:

~~~vim
command! FZFTagFile if !empty(tagfiles()) | call fzf#run({
\ 'source': "cat " . join(tagfiles()) . ' | grep -P "' . expand('%:t') . '"',
\ 'sink': function('<sid>tag_handler'),
\ 'options': '+m --with-nth=1',
\ 'down': '50%'
\ }) | else | echo 'No tags' | endif

function! s:tag_handler(tag)
    if !empty(a:tag)
        let token = split(split(a:tag, '\t')[2],';"')[0]
        let m = &magic
        setlocal nomagic
        execute token
        if m
            setlocal magic
        endif
    endif
endfunction
~~~

**Comment by edi9999** [comment]
Awesome job indeed ! I tried to implement it myself but wasn't very successful

**Comment by junegunn** [comment]
I realized that `--excmd=pattern` requires `nomagic` and tab character inside the pattern makes it harder to correctly parse the output. `--excmd=number` makes it much simpler. See the updated snippet here:

https://github.com/junegunn/fzf/wiki/Examples-(vim)#jump-to-tags-in-the-current-buffer

**Comment by liujoey** [comment]
the *jump to tags in the current buffer* example is relatively slow then the equivalence in Ctrlp. [Ctrlp BufferTag](https://github.com/kien/ctrlp.vim/blob/master/autoload/ctrlp/buffertag.vim) plugin popup the list instantly while your example above has 1 to 2 seconds delay before the list pops up. I'm not sure if the delay is caused by ctags or somewhat, but the ctrlp plugin also uses ctags. Any idea?

**Comment by junegunn** [comment]
@liujoey I've never noticed any delay. One possibility is that you mapped it to some key chord, and there's another mapping with the same prefix and Vim is waiting until it can be sure of your intention. Anyway, check out http://github.com/junegunn/fzf.vim which has a better implementation of the command.

**Comment by liujoey** [comment]
thanks. This is great and I wasn't aware that there is a separated plugin for vim. Will check it out tomorrow. Thank you.

**Comment by breerly** [comment]
Would love to see this packaged up in a plugin/wiki - a fzf-goto would be awesome to have, without deciphering this whole thread.

**Comment by junegunn** [comment]
@breerly Have a look at [fzf.vim project](https://github.com/junegunn/fzf.vim).

**Comment by AlexVKO** [comment]
https://github.com/AlexVKO/fzf-to-functions.vim
