### ISSUE TITLE
[feature request] make --nth independent of --with-nth

### ISSUE THREAD

**Issue by herrsimon** [junegunn/fzf#2432]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

Hello,

currently, it seems as if those fields given as arguments to "--nth" which are not contained in the arguments to "--with-nth" are ignored (i.e. not searched).

For example, when feeding the lines

```
test;tag1,tag2
test2;tag1
```

to `fzf --delimiter ';' --nth 2`, only the second fields (containing the tags) are searched correctly, but when feeding to `fzf --delimiter ';' --nth 2 --with-nth 1`, only the first fields (`test;` and `test2;`) are shown but typing `tag` doesn't select anything, i.e. it seems as if the second fields are treated as if they were not there.

Is this intended behavior? If so, one should maybe add an explaining remark to the man page.

In my opinion, it would be more reasonable to have fzf search the `--nth` fields independently of whether they are displayed (i.e. specified via `--with-nth`) or not. 

A specific use case would be files where the second fields are very long (a long list of tags) and would hence clutter the display, but where it is still useful to search them (do tag filtering). Again, as written above, the filtering can of course be achieved by preprocessing the input, but this would not be dynamic.

**Comment by haakonstorm** [comment]
I second this. It took some experimenting on my part understanding that only what is printed is actually searched.

**Comment by herrsimon** [comment]
Another remark, in case the behavior above is intended: A workaround would be topad the desired fields with whitespace until the screen is filled and then print the fields which should be searched but not shown. Then fzf would of course show two dots (`..`) in order to indicate that the line continues. In the past, I already asked whether these two dots could be made configurable (for example via an option `--line-continuation-string`) so that in particular the empty string could be chosen, but this was declined.

Could somebody please point me to the relevant place in the code where the two dots are configured, so that I can patch this (and offer the patch on the wiki if desired)? In fact, these two dots are rather annoying in my use case.

Thanks!

**Comment by 097115** [comment]
No progress here? We can't make `fzf` NOT to display those line continuation dots? :)

**Comment by kqvanity** [comment]
@junegunn  
Did that commit really solve this issue? appending `--ellipsis=''` doesn't really make much diff

```bash
 $ cat words
one 1
two 2
three 3
four 4
```
`$ nl words | fzf --nth=-1 --with-nth=2 --ellipsis=''`

Only searches the `2` field not the last one as specified in `nth`. I usually want to do a full-text search with `--nth=..`, but it only limits to the field specified in `--with-nth=`
