### ISSUE TITLE
[Feature Request] Add ability to hide text for the use of storing extra information

### ISSUE THREAD

**Issue by simonhughcom** [junegunn/fzf#2433]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish
    
## Problem / Steps to reproduce
Sometimes it would be useful to store extra information not presented to the user in the fzf window.

For example, I have a script that uses fzf to list the windows in my x session and to focus a window upon selection.
However this script is reliant on the window title to operate and it is plausible for two windows to have the exact same title.
A solution would be to include the window id with the title, but this is not information that the user really needs and is only useful programmatically. 

My proposed solution is to include a `--hidden-text` cli option allowing the user to give a delimiter that would hide all text before said delimiter.
For example: `echo "this text is hidden ; this text is displayed" | fzf --hidden-text=';'`

Once selected the full text would the printed to stdout for the user to parse in whichever way he wished.

**Comment by junegunn** [comment]
Have you tried using `--with-nth`?

**Comment by simonhughcom** [comment]
This is exactly what I need.
How did I  miss that?
Thank you
