### ISSUE TITLE
`--tiebreak=sublength` should be a thing

### ISSUE THREAD

**Issue by haakonstorm** [junegunn/fzf#2434]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Mac OS X
    - [x] Nintendo 64oooour
- Shell
    - [x] bash
    
## Problem

<img width="685" alt="Screenshot of iTerm2 (06-04-2021, 19-35-07)" src="https://user-images.githubusercontent.com/193781/113762552-004db000-9719-11eb-9846-0783bf546acd.png">

<img width="632" alt="Screenshot of iTerm2 (06-04-2021, 19-34-21)" src="https://user-images.githubusercontent.com/193781/113762562-0348a080-9719-11eb-82db-0475e1ff7eb0.png">

## User happiness

... dictates that "red_light.sh" should be rank higher and be sorted first in this case, right? 

## Just because I wanted to troll the CI

- [x] checklistspam
- [x] checklistspam
- [x] checklistspam
- [x] checklistspam
- [x] checklistspam
- [x] checklistspam
- [x] checklistspam
- [x] checklistspam
- [x] checklistspam
- [x] checklistspam
- [x] checklistspam
- [x] checklistspam
- [x] checklistspam
- [x] checklistspam
- [x] checklistspam
- [x] checklistspam
- [x] checklistspam
- [x] checklistspam
- [x] checklistspam
- [x] checklistspam
- [x] checklistspam
- [x] checklistspam
- [x] checklistspam
- [x] checklistspam
- [x] checklistspam
- [x] checklistspam
- [x] checklistspam
- [x] checklistspam
- [x] checklistspam
- [x] checklistspam
- [x] checklistspam
- [x] checklistspam
- [x] checklistspam
- [x] checklistspam
- [x] checklistspam
- [x] checklistspam
- [x] checklistspamforfun

**Comment by junegunn** [comment]
`--no-sort` disables sorting altogether. You probably don't want it unless you feed in an already sorted list.

**Comment by haakonstorm** [comment]
Well, that was embarrasing. Thank you and sorry for the bother. At least I provided some value over at #2423 and even in technicolor.
