### ISSUE TITLE
Add action to change preview height or width

### ISSUE THREAD

**Issue by przepompownia** [junegunn/fzf#2435]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish
    
## Problem / Steps to reproduce
Sometimes I would like to resize (horizontal) preview without quit from fzf. 
- `preview-zoom-in` would "almost maximize" (take the whole space except n lines of result list for horizontal split) and remember the preview height before this action
- `preview-zoom-out` to restore saved height.
- `preview-+`, `preview--` or something similar would change the preview size by one line. 

Maybe it is similar to https://github.com/junegunn/fzf/issues/2376

**Comment by xeruf** [comment]
I would propose `preview-enlarge` and `preview-shrink`.

And since this would require storing excess content anyways, I would like to add to this bindings for horizontal scrolling, `preview-left` and `preview-right`.
