### ISSUE TITLE
 Post-update hook for fzf ... /usr/share/vim/vimfiles/install not found

### ISSUE THREAD

**Issue by ralphee** [junegunn/fzf#2436]
- [ x ] I have read through the manual page (`man fzf`)
- [ x ] I have the latest version of fzf
- [ x ] I have searched through the existing issues

## Info

- OS
    - [x ] Arch Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x ] zsh
    - [ ] fish
    
## Problem / Steps to reproduce
after installing fzf with vimplug i get the following error message:

` Post-update hook for fzf ... /usr/share/vim/vimfiles/install not found`

[nvim init.vim](http://ix.io/2VpC)

when trying to launch :Files & :Buffers fzf pops up and immediately closes; however Gfiles works without any issues.

**Comment by komali2** [comment]
I'm having this issue too, how did you resolve it?
