### ISSUE TITLE
Allow FZF to complete Vim command arguments

### ISSUE THREAD

**Issue by przepompownia** [junegunn/fzf#2439]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish
    
## Problem / Steps to reproduce
Have anyone tried completion of Vim command arguments using FZF? Given defined
```vim
command -complete=customlist,Complete Foo echo ''
```
how to define `Complete` to return a list with only one element selected by FZF?

**Comment by junegunn** [comment]
It's not possible.
