### ISSUE TITLE
Unable to use fzf as global alias

### ISSUE THREAD

**Issue by raine** [junegunn/fzf#244]
I'm trying to get this work: `alias -g F="| fzf"`

`ps aux F`

However, `fzf` won't start until I hit `^C`.

`alias -g P="| peco"` works fine.

```
$ zsh --version
zsh 5.0.5 (x86_64-apple-darwin13.2.0)
$ fzf --version
0.9.12
```

Any ideas?

**Comment by edi9999** [comment]
I'm pretty sure that i have F aliased to | fzf on my machine.

Can you list your existing aliases ?

**Comment by junegunn** [comment]
Works for me too.

**Comment by raine** [comment]
I removed stuff from my zshrc until it started working and it seems the reason is

```
eval "$(fasd --init auto)"
```

For some reason it breaks any global alias to `"| fzf"`.

**Comment by junegunn** [comment]
Okay, then it's not an issue of fzf. I'll close this.

**Comment by kakulukia** [comment]
@raine did you find a solution for fasd init breaking the global fzf alias?
