### ISSUE TITLE
ctrl-T not working

### ISSUE THREAD

**Issue by maskalenkas** [junegunn/fzf#2448]
- [ ] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [ ] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish
   
------ 
Hi

While the other commands work, ctrl-t displays the following error:
```
(eval):1: command not found: fd

0/0 (0)
```
And apparently everything is set correctly...
An example is when I run bindkey.

```
➜ bindkey | grep fzf
"^I" fzf-completion
"^R" fzf-history-widget
"^T" fzf-file-widget
"^[c" fzf-cd-widget
```

.zshrc:

```
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
export FZF_DEFAULT_OPS="--extended"
export FZF_DEFAULT_COMMAND='fd --type f'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
export FZF_DEFAULT_COMMAND='fd --type f --hidden --follow --exclude .git'
```

**Comment by junegunn** [comment]
Apparently, `fd` is not installed in your system.

**Comment by maskalenkas** [comment]
> Apparently, `fd` is not installed in your system.

how do i install?
