### ISSUE TITLE
Is it possible to use <ctrl-e> as 'actUp' for 'colemak' keyboard layout? :)

### ISSUE THREAD

**Issue by wisonye** [junegunn/fzf#2449]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [x] fish
    
## Problem / Steps to reproduce

My boy is using `colemak` keyboard layout and he is studying `neovim`.
Of course, by using `fzf` and `fzf.vim` plugin:)

The problem is that the default keybinding is `<c-j><c-k>/<c-n><c-p>` to move the cursor up and down
in the preview window. But for `colemak` layout, it should be handle with `<c-n><c-e>` for moving up and down.

I have no idea how to set keybinding for that part, as it seems set in the source code:

```go
# Defined in `src/terminal.go`
add(tui.CtrlE, actEndOfLine)
add(tui.CtrlK, actUp)
```

He's already tried the mapping below, none of working:

```vim
nmap <c-e> <c-p>
imap <c-e> <c-p>
nmap <c-e> <c-k>
imap <c-e> <c-k>
```

Any work around without changing the source code? :)

**Comment by junegunn** [comment]
Have you read through the manual page? (`man fzf`)

**Comment by mikeye-888** [comment]
> Have you read through the manual page? (`man fzf`)

Oh, thanks for the tips, fixed already with the below settings:

```vim
let $FZF_DEFAULT_OPTS="--reverse --bind=ctrl-e:up"
```

Thank you so much:)
