### ISSUE TITLE
Tab completion not working in fish

### ISSUE THREAD

**Issue by Deshdeepak1** [junegunn/fzf#2451]
- [X] I have read through the manual page (`man fzf`)
- [X] I have the latest version of fzf
- [X] I have searched through the existing issues

## Info

- OS
    - [X] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [X] fish
    
## Problem / Steps to reproduce

1. Install fzf 
2. Type vim **<TAB>
3. Auto completion not showing.

**Comment by junegunn** [comment]
https://github.com/junegunn/fzf#fuzzy-completion-for-bash-and-zsh

As the title implies, it's not implemented for fish. Patches are welcome.
