### ISSUE TITLE
Using brew's fzf with vim

### ISSUE THREAD

**Issue by estk** [junegunn/fzf#246]
Hey @junegunn, I'm a big fan of fzf, I was wondering how you recommend using brew's fzf with vim-plug?

**Comment by junegunn** [comment]
I don't recommend using homebrew if your primary use of fzf is on vim. You can tell vim-plug to load homebrew-installed fzf like follows,

```vim
Plug '/usr/local/Cellar/fzf/0.9.12'
```

but then vim-plug does not know how to install/update fzf.

So I'd just let vim-plug install/update/load fzf as follows

```vim
Plug 'junegunn/fzf', { 'do': 'yes \| ./install' }
```

And you can change the directory with `dir` option.

```vim
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': 'yes \| ./install' }
```
