### ISSUE TITLE
Run fzf with regular expressions

### ISSUE THREAD

**Issue by TornaxO7** [junegunn/fzf#2475]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x ] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ x] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

I'd like to use some regular expression as in vim in order to filter my files. For example if I type `\<text\>` fzf should look after some files, which have the word ` text ` in their filename.

Reproducing steps:
1. Create a directory and run this command to create some test files:
```bash
for ((i=0; i<10; i++)) ; do touch "test$i.txt"; done
```

2. Use this as your fzf command:
```zsh
export FZF_DEFAULT_COMMAND="rg --files --hidden --glob \"!.git/*\" | rg --engine=pcre2 --"
```

3. Run fzf (and if you can, type `test\d`)

I'm getting the following error message:
```
[Command failed: rg --files --hidden --glob \"!.git/*\" | rg --engine=pcre2 --]
```

I wanted to filter the output of the first `rg` (which lists all files) by adding the second ripgrep. What am I doing wrong?

**Comment by rayiik** [comment]
hey are you willing to do it in phases? this is one of the reasons i wanted the toggle-search option. also add the glob to an rc file and set 
```bash
RIPGREP_CONFIG_PATH="${PGCONF}/ripgrep.conf"
```
as to just looking for a static you can do
```bash
#!/usr/bin/env bash -
DEFAULT='[-a-zA-Z0-9].*'
REGEX="${1:-'$DEFAULT'}"
shift 1
_rgquery () {
local REGEX="$1"
rg --files --hidden | rg -e "$REGEX"
}
_rgquery | fzf --flags --options --stuff
```
this should work most cases regex is defined twice possibly unnecessarily (its 3am) but it should get redefined when called 
./scriptname.sh 'regexpression' 
should run it but a more interesting case down below. 

```bash
REGEX="$1"
_origsearch="rg --files --hidden | rg -e ${REGEX:-'[-a-zA-Z0-9].*'}"
_origsearch | fzf --bind="ctrl-alt-o:reload:REGEX={q} _origsearch" --bind='ctrl-o:toggle-search+clear-query'
```
this lets you filter on the fly and reload interactively and filter down your list. this can also be fed into a text file and pulled into the script but some ideals for you.

**Comment by rayiik** [comment]
this is one i use fairly often 
```bash
declare gvar=''          
declare Fvar=''                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 rg__com_="rg '{q}' ./ --color=always --colors=match:fg:12 --no-filename"                                                
origcom () {                                                                                                                    
Fvar="${1:-'.'}"
gvar="${2:-'.'}"
fd -uu -t f "$Fvar" --header | rg "$gvar" --no-filename
}
"$origcom" | fzf --phony --preview="cat {} | $rg__com_"; \
rg --files-with-matches {q}" \
        --bind="ctrl-alt-r:reload:$rg__com_ {1q} {2q}"
```
this one isnt populated with a list however once you start typing it searches content of all files below you and show you the match text and the name of files that contain matches the reload will have to be changed because currently it prints the preview window to the reload command as the next set of data (which will eventually be a snippit caller but not relevant currently)

**Comment by TornaxO7** [comment]
I'm sorry for the late reply! Thank you for your answers!

So if I understood it right, I have to do the following:

`~/.zshrc`
```zsh
ecport FZF_DEFAULT_OPTS=
export RIPGREP_CONFIG_PATH=~/.config/ripgrep/ripgrep.conf
```

`~/.config/ripgrep/ripgrep.conf`
```
declare gvar=''          
declare Fvar=''
rg__com_="rg '{q}' ./ --color=always --colors=match:fg:12 --no-filename"                                                
origcom () {                                                                                                                    
Fvar="${1:-'.'}"
gvar="${2:-'.'}"
fd -uu -t f "$Fvar" --header | rg "$gvar" --no-filename
}
"$origcom" | fzf --phony --preview="cat {} | $rg__com_"; \
rg --files-with-matches {q}" \
        --bind="ctrl-alt-r:reload:$rg__com_ {1q} {2q}"
```

right?

**Comment by rayiik** [comment]
Couple things you dont wanr ti save in repgrep config path because rg appends line by line as flag options to ripgrep so anything that isnt a rg flag should error out just want as a script on your path the last preview command. Before the ; you want to get rid of the quote because were passing grouped commands output to the preview and looks like i missed giving you the rgcom function

**Comment by TornaxO7** [comment]
> Before the ; you want to get rid of the quote

So you mean it like that?
```
declare gvar=''          
declare Fvar=''
rg__com_="rg '{q}' ./ --color=always --colors=match:fg:12 --no-filename"                                                
origcom () {                                                                                                                    
Fvar="${1:-'.'}"
gvar="${2:-'.'}"
fd -uu -t f "$Fvar" --header | rg "$gvar" --no-filename
}
"$origcom" | fzf --phony --preview=cat {} | $rg__com_; \
rg --files-with-matches {q}" \
        --bind="ctrl-alt-r:reload:$rg__com_ {1q} {2q}"
```

**Comment by rayiik** [comment]
so the adding the glob exclusion to the ripgrep_configpath is correct this is my config file and im re writting the blocks with less error lol.
/home/username/.bin/rgrex.sh
```bash
#!/usr/bin/env bash -
DEFAULT='[-a-zA-Z0-9].*'
REGEX="${1:-'$DEFAULT'}"
shift 1
_rgquery () {
local REGEX="${1=-"DEFAULT"}"
rg --files --hidden | rg -e "${REGEX}"
}
_rgquery | fzf --flags --options --stuff
```
/home/username/.bin/rgrex2.sh
```bash
set_var () {
DEFAULTS='[-a-zA-Z0-9].*'
REGEX="${1:-"DEFAULTS"}"
export REGEX
}
origser () {
set_var "$@"
"rg --files --hidden | rg -e ${REGEX}"
}
origser | fzf --bind="ctrl-alt-o:reload:origser {q}" \
--bind='ctrl-o:toggle-search+clear-query'
```

*/ripgrep.conf
```bash
-uu
--no-line-number
--color=ansi
--colors=line:fg:15
--colors=column:style:intense
--colors=column:fg:13
--colors=match:style:intense
--colors=match:fg:12
--colors=path:fg:4
--type-add=shell:'*.sh *.bash'
--colors=path:style:intense
--type-add=picture:'*.jpg, *.png, *.jpeg, *.gif'
--type-add=conf:'*rc, *.conf, *.conig, init*'
--ignore='.git/*'
```

**Comment by rayiik** [comment]
sorry still rewriting parts of it almost done :) X)  but would be --preview="cat {} | $rg__com_;  rg --files-with-matches {q}" would load two data sets to the preview on the top would be the cat {} | rg__com and underneath would be the files with matches set but this as it is wont work because rg__com isnt a function and inst properly called.

**Comment by rayiik** [comment]
```bash
declare gvar=''
declare Fvar=''
if [[ -z "$1" ]]; then
  Fvar='.'; else
  Fvar="$1"
fi
if [[ -z "$2" ]]; then
  gvar='.'; else
  gvar="$2"
fi
grep_flag_available="rg -e '{q}' ./ --color=always --with-filename --colors=match:fg:12 "
fd -uu -t f "$Fvar" | rg "$gvar" --no-filename | fzf --phony \
  --preview="cat {} | $grep_flag_available" \
--bind="ctrl-alt-o:reload:rg --files-with-matches -e {q}"
unset gvar
unset Fvar
```
[![asciicast](https://asciinema.org/a/415619.svg)](https://asciinema.org/a/415619)

**Comment by rayiik** [comment]
so you just start typing out regular expression and once the format is complted with closed brackets it registers but you can also passs additional flags to rg using space --flag  though that prevents you from using the ctrl alt o which then populates fzf with a list of files that contain the regexp (not all regexp are captured 100% but its pretty close

**Comment by rayiik** [comment]
you can then script with it using rgft | command just make sure that you populate the left side select the files you want to work on and then accept :)

**Comment by TornaxO7** [comment]
Ok, so I think I've got it running now. Thank you!

**Comment by rayiik** [comment]
hey so couple things, still not working perfectly just so you know if you want to use special characters such as word boundaries you need to double escape them \\w \\W however this doesnt translate currently to the function that exports a new lest currently to get both to work you need to find the regex that matches what your looking for, remove the extra escape and then fire off the command, i will update once i have it working with out the double escapes or auto correcting if there are double escapes

**Comment by TornaxO7** [comment]
Ok, thanks for the information! :)

**Comment by miaLDN** [comment]
So fzf cannot do a PCRE3 regex?

**Comment by ccjmne** [comment]
@miaLDN, I'm not sure that this thread from half a decade ago is the best place to ask that question.

To answer it nonetheless, the project's `README` does outline its [search syntax](https://github.com/junegunn/fzf#search-syntax).
It can be perused in your Web browser using some plain-text exact matching algorithm, upon pressing and holding `Ctrl`, then tapping `f`.
Its manual page also collates the same sort of information, I find it instructive as well.

To summarise their contents w.r.t. your request, fzf does indeed not tout support for the specific flavour of regular expression you're inquiring about.

Some [other](https://github.com/skim-rs/skim) [tools](https://github.com/peco/peco) do support regular-expression matching, but as to whether their engines are PCRE3-compliant, I do not know: you'd have to go comment to closed issues there.

Or maybe try it out! I actually don't know for sure that the current syntax used by fzf doesn't match the PCRE3 syntax. In fact, I'm looking forward to PCRE3 actually being a thing having been mentioned anywhere other than in your comment: if its syntax were to match that of fzf, quite a few heads would turn—and some would most definitely roll.
