### ISSUE TITLE
FZF Preview in separate program

### ISSUE THREAD

**Issue by bcmertz** [junegunn/fzf#2479]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

I am piping in a list of fonts to fzf, and want to preview the highlighted font with a preview script I've written that looks like this:

```
convert -font $font -size $size -pointsize $font_size label:"$text" /tmp/$font.png
sxiv /tmp/$font.png
```

Even if I make it a separate script and source the script in preview the best I'm able to do is see "Loading..." and sxiv never appears. All the examples in the man page use builtin bash commands which can render in the preview window, is this a hard requriement or can I launch something external like sxiv? Any help is greatly appreciated

**Comment by junegunn** [comment]
I've tried

```sh
find . -name '*.png' | fzf --preview 'sxiv {}'
```

and it works as expected.

Tested on macOS, sxiv installed with Homebrew.

**Comment by bcmertz** [comment]
Ahhh thanks this works for me! One question remains, which is how to use a function in the preview subprocess? Ideally I could keep the preview function in the same file. Thank you for your help!

Example:
```

preview() {
      font=$1

      # https://unix.stackexchange.com/a/629096
      # convert text into image with font chosen
      convert -font $font -size $size -pointsize $font_size label:"$text" /tmp/$font.png
      # display the image of the text
      sxiv /tmp/$font.png
}

font=$(convert -list font |
                 awk -F: '/^[ ]*Font: /{print substr($NF,2)}' |
                 fzf --preview "preview {}"
          )

```

**Comment by junegunn** [comment]
You should export the function to a subprocess.

```
$ foo() {
> echo foobar
> }

$ fzf --preview 'foo'
  # /bin/bash: foo: command not found

$ export -f foo

$ fzf --preview 'foo'
  # Works
```

But a more reliable solution would be to put it as an executable script file in your $PATH.

**Comment by bcmertz** [comment]
Thank you @junegunn !
