### ISSUE TITLE
key-bindings files are not installed on ubuntu 21.04

### ISSUE THREAD

**Issue by roeniss** [junegunn/fzf#2480]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux (ubuntu 21.04)
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [x] zsh
    - [x] fish
    
### Expected

I tried to enable key-bindings with oh-my-zsh's fzf plugins, which enables `key-binding.zsh` by omz framework.

### Actual

error occurred: 
```sh
setup_using_debian_package:source:32: no such file or directory: /usr/share/doc/fzf/examples/key-bindings.zsh
```

I didn't specify that path. the fzf plugin finds key-binding file path by itself.

So I simplify the problem like this to see what's going on: 

```sh
docker run --rm -it ubuntu:21.04
apt update && apt install -y fzf tree
fzf --version
# 0.24 (devel)
dpkg -L fzf | grep binding
# /usr/share/doc/fzf/examples/key-bindings.bash
# /usr/share/doc/fzf/examples/key-bindings.fish
# /usr/share/doc/fzf/examples/key-bindings.zsh
# /usr/share/fish/vendor_functions.d/fzf_key_bindings.fish
cd /usr/share/doc/fzf/examples && tree
# .
# `-- plugin
#     `-- fzf.vim -> ../fzf.vim # looks like dangling link
```

### Conclusion

Don't know why, but seems key binding files are not installed correctly.

(I thought `dpkg -L` means "show all related and installed files". If I'm wrong please correct it)

### appendix

I came from https://github.com/junegunn/fzf/issues/1866#issuecomment-655104432 and https://github.com/junegunn/fzf/issues/1385#issuecomment-627095222. 

Abobe that, README doesn't mention what to do exactly on this case: https://github.com/junegunn/fzf#using-linux-package-managers
```markup
Key bindings (CTRL-T / CTRL-R / ALT-C) and fuzzy auto-completion may not be enabled by default.
```

**Comment by junegunn** [comment]
That's strange, you should report the issue to the maintainers of the APT package.

**Comment by roeniss** [comment]
It's in progress now. I'll add comments if something changed.

**Comment by alkoclick** [comment]
Hey, this appears to be still open, do we have an issue link for the APT package @roeniss ?

For some reason it works correctly in my Ubuntu 22.10 installation, but it fails in the Dockerized version running 22.04 (same as the error posted above for 21.04)

**Comment by roeniss** [comment]
@alkoclick I didn't contact to APT side because at the last moment I concluded that this is not a such problem.

can you try with `git clone` like this: https://github.com/junegunn/fzf/issues/2072#issuecomment-645862485

I guess some 'specific' machine/OS is not suited for `apt install fzf`, but don't have concrete grounds.

**Comment by alkoclick** [comment]
I get a working installation of fzf (0.24-devel) as in your original post on this thread, but without the key binding files installed. 

> can you try with git clone like this: #2072 (comment)

I can try that, but it'll work, not sure what that would achieve? 

Notably this is pretty low prio for me, because it works correctly on my main boxes, but fails to get these files in the containerized development environment that I have.

**Comment by roeniss** [comment]
Thank you @jaron-l. I'll close this one.

**Comment by zouguangxian** [comment]
It is most likely caused by the setting in /etc/dpkg/dpkg.cfg.d/excludes.
```ini
# Drop all man pages
path-exclude=/usr/share/man/*

# Drop all translations
path-exclude=/usr/share/locale/*/LC_MESSAGES/*.mo

# Drop all documentation ...
path-exclude=/usr/share/doc/*

# ... except copyright files ...
path-include=/usr/share/doc/*/copyright

# ... and Debian changelogs for native & non-native packages
path-include=/usr/share/doc/*/changelog.*
```
