### ISSUE TITLE
Lines not flushed correctly in presence of emoji

### ISSUE THREAD

**Issue by y0ast** [junegunn/fzf#2482]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

Relevant:
https://github.com/junegunn/fzf/issues/1526
https://github.com/junegunn/fzf/issues/2163

But different enough for its own issue.

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [x] fish
    
## Problem / Steps to reproduce
```
curl https://raw.githubusercontent.com/LukeSmithxyz/voidrice/master/.local/share/larbs/emoji | fzf
```

Search for something, then remove a character and see spurious `;` and other characters appear on lines. `ctrl+L` fixes it.

core problem is this:

```package main

import (
	"fmt"

	"github.com/mattn/go-runewidth"
)

func main() {
	fmt.Println(runewidth.StringWidth("☺️"))
	fmt.Println(runewidth.RuneWidth('☺')) // created from above but deleting the modifier
	fmt.Println(runewidth.RuneWidth('️')) // created from first line, but backspacing the emoji char leaving the modifier
}
```

```
$ go run main.go
1
1
1
```

Fzf computes width of line using `runewidth.Runewidth` instead of `runewidth.StringWidth`. The second takes into account zero width emoji modifiers:

RuneWidth of just emoji = 1, RuneWidth of the modier= 1, so fzf thinks length is 2
However StringWidth of emoji+modifier = 1 (which is correct)

When computing number of spaces to pad with, fzf misses 1 (or more) and random characters appear.

**Comment by junegunn** [comment]
Thanks for the repro and the suggested fix. I'll look into it when I get some time.

**Comment by y0ast** [comment]
Fix works! Thanks a lot :)
