### ISSUE TITLE
[question] Toggle shell command flag

### ISSUE THREAD

**Issue by monkoose** [junegunn/fzf#2484]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish
    
## Problem / Steps to reproduce
How to achieve toggling of some flag of the command fzf operates on with one key? Like toggling `--hidden` flag of `fd -t f`? 
I found some solutions (haven't tested them) that require shell script files to properly work, like creating some loop that constantly check if you change some variable, etc. Is there simpler solution that can be done in a oneliner shell command? Something like
```
fd -t f | fzf --bind=ctrl-space:reload('if <var>; then fd -t f --hidden (+ change state of the <var>); else fd -t f (+ change state of the <var>; fi)
```
 Can it be achieved right now somehow? If no, is it possible in the future releases let fzf know command that it operates on (not only list of entries) and keep it in something like placeholder {c}? So you then can easily check it with `reload(if {c} == 'fd -t f'; then ...`?

**Comment by junegunn** [comment]
No, I don't want to introduce any stateful programming constructs to fzf.

You should maintain the state in an external file.

```sh
echo 0 > /tmp/state
echo this | fzf --bind 'ctrl-space:reload:v=$(cat /tmp/state); echo $((v ^ 1)) > /tmp/state; if [ "$v" = 1 ]; then echo this; else echo that; fi'
```

But I would probably keep it simple and set up two reload bindings.

**Comment by monkoose** [comment]
@junegunn Thank you for reply. 
But it will not add any stateful programming constructs into fzf itself, no? It will be just possible to get the value of current command, all conditional statement redirected to shell part. Or i misunderstand something?

**Comment by junegunn** [comment]
1. There's no way to know which command is attached the STDIN pipe.
2. Even if it's possible know `fd -t f ` part from `fd -t f | fzf ...` and assign the value to `{c}`, you can't toggle between two commands since `{c}` will stay the same during the lifespan of fzf.
3. If that is enough for you, just use an environment variable to store and pass the command to fzf process.

**Comment by junegunn** [comment]
4. Updating `{c}` on `reload` won't help you solve the problem. The value of `{c}` will be `if {c} == 'fd -t f'; then ...`, but we can't use `{c}` in the command as it will expand recursively.

**Comment by monkoose** [comment]
Thank you for explanation.
