### ISSUE TITLE
Q: return similar file names in directory, non-interactive

### ISSUE THREAD

**Issue by atomGit** [junegunn/fzf#2485]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

perhaps fzf is not the tool for this job?

i want to feed fzf a list of file names in a specified directory and have it print those that are similar

what i'm actually doing is looking for music files which may be duplicates but which have slightly different file names, such as...

```
This - That
this - That
Tihs - Taht
This - That (and something else)
```

i'm assuming fzf will need to be piped from 'find' since it isn't path aware and then run in a loop where it is fed each file name to compare to the others but i haven't been able to figure out to make this work

ideally, i suppose, i could just feed fzf an array of file names for it to compare

**Comment by junegunn** [comment]
> perhaps fzf is not the tool for this job?

No.
