### ISSUE TITLE
Q: can be `change` action changed?

### ISSUE THREAD

**Issue by przepompownia** [junegunn/fzf#2486]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish
    
## Problem / Steps to reproduce
Suppose we have four files created as follow:
```sh
echo x>foo
echo x>bar
echo y>baz
echo y>faz
```
then I would like to filter them first by its content and then filter such result by filename. 
```sh
grep -lm1 'x' * | fzf --disabled '--bind' 'alt-s:toggle-search' '--bind' 'alt-s:+change-prompt:S> '    '--bind' 'change:reload:grep -lm1 {q} *' --query='x'
```
In the above example I would like to filter by filename only (i.e. with `f` query get `foo` only, like with `grep -lm1 'x' * | fzf`) but have not idea how to unbind `change` action.

**Comment by junegunn** [comment]
There is currently no way to dynamically add or remove a binding, and I haven't thought enough about it.

For the time being, consider
- starting fzf twice with different options in shell script
    - fzf is like an interactive version of "grep", you should lower your expectation. It cannot do everything in one invocation.
- or using something like https://github.com/junegunn/fzf/blob/master/ADVANCED.md#ripgrep-integration

**Comment by rayiik** [comment]
Yea the  - - sync flag might be just what your looking for, multi staged filtering this can also be done a couple ways, non very clean, using the fzf_default_option it needs to get exported to a seperate file and then sourced back in (defined in its own function) bind='key:execute:echo default=newdefault > file' bind='key:reload: source file && command'

**Comment by junegunn** [comment]
I decided to add `unbind(...)` action. See https://github.com/junegunn/fzf/blob/master/ADVANCED.md#switching-to-fzf-only-search-mode to learn how it's used.

**Comment by przepompownia** [comment]
Thank you! It is very useful feature. Thanks also for writing the example.

Independently, I tried to rebind the `change` action again 
```sh
grep -lm1 'x' * | fzf --disabled '--bind' 'alt-s:unbind(change)+change-prompt(Search by filenames: > )+enable-search+clear-query'    '--bind' 'change:reload:grep -lm1 {q} *' --query='x' --bind 'alt-q:disable-search+change-prompt(Search by query: > )+clear-query+change:reload(grep -lm1 {q} * || true)' --preview 'cat {}'
```
but with unpredictable results, e.g.
```
[Command failed: reload(grep -lm1 '' * || true)]
Search by query: > x 
```
(it sometimes works but I still cannot find why).

**Comment by junegunn** [comment]
Rebinding is not allowed.

**Comment by przepompownia** [comment]
> Rebinding is not allowed.

It didn't hurt to try.
