### ISSUE TITLE
NetBSD installation instructions

### ISSUE THREAD

**Issue by 0-wiz-0** [junegunn/fzf#2487]
pkgsrc provides a package for fzf[1]. Installation is as simple as:
````
pkgin in fzf
````

Please add this to the operating system-specific instructions. Thanks!

[1] http://cdn.netbsd.org/pub/pkgsrc/current/pkgsrc/sysutils/fzf/index.html

**Comment by junegunn** [comment]
Thanks for letting me know. But it looks like the package is not up-to-date (0.23 vs 0.27.0). I can't recommend it if it's not providing the latest release.

**Comment by 0-wiz-0** [comment]
That's a good point.

I've updated the (source) package to 0.27.0, the web page now shows this; binary packages will appear there when they're ready.

**Comment by junegunn** [comment]
* Is `in` short for `install`? If so, I'd like to show the full command, i.e. `pkgin install fzf`, so that it's more clear to the reader
* Do we need `sudo`?

```diff
diff --git a/README.md b/README.md
index 16a2ecd..4f5c470 100644
--- a/README.md
+++ b/README.md
@@ -122,6 +122,7 @@ git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
 | Pacman          | Arch Linux              | `sudo pacman -S fzf`               |
 | pkg             | FreeBSD                 | `pkg install fzf`                  |
 | pkg_add         | OpenBSD                 | `pkg_add fzf`                      |
+| pkgsrc          | NetBSD                  | `pkgin install fzf`                |
 | XBPS            | Void Linux              | `sudo xbps-install -S fzf`         |
 | Zypper          | openSUSE                | `sudo zypper install fzf`          |
 
```

**Comment by 0-wiz-0** [comment]
Yes, `pkgin install` will also work.

Like on FreeBSD and OpenBSD, you'll probably need to be root, but 'sudo' is not installed  by default, and you could set up pkgsrc to be for your user (and not need sudo). So we can argue either way :)
