### ISSUE TITLE
Move through recent search terms in Vim

### ISSUE THREAD

**Issue by padde** [junegunn/fzf#249]
I became quite used to nagivating through my recent search terms when I used CtrlP + Ack/Ag. Is this possible in FZF as well?

Thanks!

**Comment by junegunn** [comment]
No, fzf does not externally store the history of search terms. I'd never really thought about the idea, but I can see how it can be useful in some cases. I'll consider adding the feature in the future releases. We'll have to rebind the keys to make it available then since ctrl-p and ctrl-n are already synonyms to down and up.

```sh
fzf --bind ctrl-n:next-history,ctrl-p:previous-history --history ~/.fzf.history
```

**Comment by padde** [comment]
Ah I see, so fzf is really lightweight on the Vim side and handles input etc itself? As a heavy Vim user it would be perfect to be able to remap keys via Vim configuration, but I guess that is not an option, right?

**Comment by junegunn** [comment]
Maybe I'm stating the obvious again but you know fzf is not a native vim plugin but a command-line program that happens to ship with a simple vim wrapper. You can set up `$FZF_DEFAULT_OPTS` in your vimrc, but I don't see why one would do that, when one can put it in bashrc or zshrc and consistently use it on your shell and on vim running on it.

**Comment by padde** [comment]
I see, thanks for your explanation!

**Comment by junegunn** [comment]
I just added `--history HISTORY_FILE_PATH` option. See the commit message for the details. It will be available on 0.9.14, or you can just build the binary from the source. Thanks for your suggestion!

**Comment by padde** [comment]
@junegunn thank you! :heart:

**Comment by lompy** [comment]
Is it possible to cycle through history with Alt-N, Alt-P in order to keep current Ctrl-N Ctrl-P bindings?

**Comment by junegunn** [comment]
@lompy Have you tried `--bind alt-n:next-history,alt-p:previous-history`?

**Comment by lompy** [comment]
Yes, should've tried before ask. Thanks!

**Comment by lompy** [comment]
Actually no. With this setting a'm losing Ctrl-N Ctrl-P bindings to select match, as they also get bind to history cycling. A'm using Ubuntu with gnome-terminal.

**Comment by junegunn** [comment]
Hmm, you're right. You have to "re"-override the keys:

```
--bind alt-n:next-history,alt-p:previous-history,ctrl-n:down,ctrl-p:up
```

**Comment by lompy** [comment]
Yes, tried rebind too. Didn't work for me.

**Comment by junegunn** [comment]
Works for me.

**Comment by lompy** [comment]
Ok. I will try to figure out what messes with key bindings in my setup.
