### ISSUE TITLE
How do I sort the results alphabetically

### ISSUE THREAD

**Issue by nomad-software** [junegunn/fzf#2491]
- [ x ] I have read through the manual page (`man fzf`)
- [ x ] I have the latest version of fzf
- [ x ] I have searched through the existing issues

## Info

- OS
    - [ x ] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ x ] bash
    - [ ] zsh
    - [ ] fish

I have scoured the internet and I can't find a simple answer to how to sort the results of `fzf` alphabetically. There are options
```
+s, --no-sort         Do not sort the result
```
Which seem to be added by default but how to turn sorting on? There is another option `--toggle-sort` but that is undocumented.

So my question is simple, when I issue the `fzf` command how do i make sure it's results are sorted alphabetically?

**Comment by relastle** [comment]
First, you can pass sorted results to fzf by simply adding the `sort` command just before fzf.

Second, `--toggle-sort` is not a fzf option, but a kind of **action**.
Thus, you can use it as below.

```
echo "ccc foo\nbbbb foo\naaaaa foo" | sort | fzf --bind='ctrl-s:toggle-sort' -q 'foo'
```

Then, you can toggle

1. Results sorted by the fzf scores calculated by the query (:= `foo`)
2. Results sorted alphabetically (originally by `sort` command)

by hitting <kbd>Ctrl</kbd> + <kbd>s</kbd>.
