### ISSUE TITLE
Vim plugin overrides user $FZF_DEFAULT_COMMAND

### ISSUE THREAD

**Issue by dtcyganok** [junegunn/fzf#2495]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

After commit 7411da8d5a37b94b2171920c82c0dafe6f9115b6 vim plugin overrides env variable `let $FZF_DEFAULT_COMMAND` defined in vim config file.

**Comment by junegunn** [comment]
Yes, but it restores the original value at the end. Is it not working as expected?

**Comment by oedotme** [comment]
I'm using `linux` and `fish` shell.

I would like also to report that after this commit 7411da8 `FZF_DEFAULT_COMMAND` value is overridden _(becomes empty)_ after running `:Files` or `:FZF` for example once after vim startup, other `FZF_*` variables values are intact though.

**Comment by junegunn** [comment]
I don't see anything wrong with the code (7411da8) yet I can reproduce the problem on Neovim but not on Vim. This seems like a bug of Neovim that should be properly addressed, but I'll see what I can do in the meantime.

**Comment by junegunn** [comment]
```vim
let $FOO = "don't let me go"

if 0
  let $BAR = "i shouldn't be here"
  unlet $FOO
endif

echo string([$FOO, $BAR])
```

gives `['don''t let me go', '']` on regular Vim, `['', '']` on Neovim 😕

**Comment by junegunn** [comment]
Changing `unlet $FOO` to `execute 'unlet $FOO'` solves the problem.

**Comment by junegunn** [comment]
Changing `unlet $FOO` to `execute 'unlet $FOO'` fixes the problem.

**Comment by junegunn** [comment]
I can no longer reproduce the problem after upgrading Neovim from 0.4.4_1 to 0.4.4_2, but we'll keep the workaround code for a while.

**Comment by oedotme** [comment]
That works. Thanks for your time!
