### ISSUE TITLE
Q: How to correctly escape `{1}` in a quoted string?

### ISSUE THREAD

**Issue by przepompownia** [junegunn/fzf#2498]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish
   
## Problem / Steps to reproduce    
I know that the manual says something about escaping placeholder pattern but I cannot correctly do it. 

Initially I wanted to use an example with a git revision:
```sh
fzf --disabled --bind "change:reload:git diff --relative --name-only 'HEAD@{\1}...HEAD' -G {q}"
```
but (in bash) we can play with something simpler:
```sh
printArg() { echo "$@"; }
export -f printArg
echo x | fzf --preview 'printArg "{\1}"'
```
and then see that `ls -1 | fzf --preview 'printArg {\1}'` gives the expected result (we see `{1}` literally).

Let's then back to the source of the initial example. I cannot remove shell escaping because this string comes from user input (in practice, from a vim command). It would be then interpreted by the shell (`HEAD@{6 days ago}...HEAD` for example) and give unexpected (and potentially dangerous) results.

Do you have other idea than potential escaping each character separately?

**Comment by junegunn** [comment]
`\{1}`
