### ISSUE TITLE
Open fzf prompt as soon as user starts typing

### ISSUE THREAD

**Issue by taromero** [junegunn/fzf#250]
Maybe add a configuration variable to allow this, which I don't know if it's even possible. This should not be the default.

I think it would be nice to open fzf prompt as soon as I start typing, without having to press ctrl-r. Related SO post (by me): http://stackoverflow.com/questions/30666458/how-to-run-a-function-on-first-keystroke-in-bash-zsh.

**Comment by junegunn** [comment]
I don't know if it's possible nor have I tried to do it. By the way, in your SO post;

> Specifically I want to run the fzf-tmux function, for which I currently need to press ctrl-r to trigger it.

It's not an accurate description of fzf-tmux.

**Comment by taromero** [comment]
@junegunn thanks, I've just made a s/fzf-tmux/fzf.
