### ISSUE TITLE
Feature Request: Allow ANSI color names

### ISSUE THREAD

**Issue by benspaulding** [junegunn/fzf#2502]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [x] fish
    
## Problem / Steps to reproduce

Many programs allow theming by giving a color name, such as `blue` instead of having to pass an actual base-16 / ANSI 256 / 24-bit color code like `4`. That seems more user-friendly than having to find out what each of the numbers means; `--color prompt:blue` vs. `--color prompt:4`, or `--color query:brred` or `--color query:red:bright` vs. `--color query:9`.

Would it be possible to add that to `fzf`? I think future users would find it helpful. If not, adding the color names to the documentation at least would be nice.

```fish
set -gx FZF_DEFAULT_OPTS \
    "--color prompt:6:bold" \
    "--color query:7" \
    "--color disabled:8:italic" \
    "--color spinner:5" \
    "--color info:5" \
    "--color pointer:7:bold" \
    "--color marker:1:bold" \
    "--color fg+:bold:underline" \
    "--color bg+:-1" \
    "--color hl+:3:bold:italic" \
    "--color fg:-1" \
    "--color hl:1:bold:underline" \
    "--color gutter:-1" \
    "--color border:0:bold"

#   COLOR     NORMAL  BRIGHT
#   black     0       8
#   red       1       9
#   green     2       10
#   yellow    3       11
#   blue      4       12
#   magenta   5       13
#   cyan      6       14
#   white     7       15
```

Thanks for all your work on `fzf` — it is a wonderful tool!

**Comment by junegunn** [comment]
Thanks for the suggestion, that makes sense. Patch pushed to master.

I thought about making `bright` an attribute instead of adding `bright-*`, but decided not to, because it only applies to the base colors. i.e. `--color fg:bright:250` will not make `250` any brighter.
