### ISSUE TITLE
zsh: ctrl + R not working. shows the zsh history search

### ISSUE THREAD

**Issue by sant527** [junegunn/fzf#2503]
- [X ] I have read through the manual page (`man fzf`)
- [ ] I have the latest version of fzf
- [ ] I have searched through the existing issues

## Info

- OS
    - [ X] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ X] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

I have zsh and after that I have installed `fzf`

```
sudo pacman -S fzf
```

But now when i press CTRL+R its not using `fzf` search rather used `zsh` search

**Comment by sant527** [comment]
I found in the archlinux wiki

added to ~/.zshrc the following line

```
source /usr/share/fzf/key-bindings.zsh
source /usr/share/fzf/completion.zsh
```

**Comment by junegunn** [comment]
Excerpt from https://github.com/junegunn/fzf#using-linux-package-managers
> :warning: **Key bindings (CTRL-T / CTRL-R / ALT-C) and fuzzy auto-completion
> may not be enabled by default.**
>
> Refer to the package documentation for more information. (e.g. `apt-cache show fzf`)
