### ISSUE TITLE
fzf multiline command search

### ISSUE THREAD

**Issue by sant527** [junegunn/fzf#2504]
- [X ] I have read through the manual page (`man fzf`)
- [ ] I have the latest version of fzf
- [ X] I have searched through the existing issues

## Info

- OS
    - [X ] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ X] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

I am using zsh and zsh allows in histroy to have multiline commands

when i am trying to search for history using `ctrl + R` i see the multiline commands shows with `\n`

example

```
ls -al \\n.
```

I want it to seen as 
````
ls -al \
 .  
```

instead of `ls -al \\n.`

but zsh's `Ctrl + R` shows the commands as multiline

How to go about this in fzf

**Comment by junegunn** [comment]
You can't. Because fzf doesn't (and will not due to technical difficulties) support displaying a single item across multiple lines.
