### ISSUE TITLE
Toggle alternate preview back to default when pressing key-binding a second time

### ISSUE THREAD

**Issue by smhc** [junegunn/fzf#2505]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [ x] Linux
- Shell
    - [x ] bash
    
## Problem / Steps to reproduce

Is it possible to toggle the secondary preview 'mode' by using the same keystroke? i.e I would like to hit 'ctrl-d' to use the 'file' based preview, but then hit ctrl-d again to toggle back to the default preview of just 'cat'. e.g

```
--preview 'cat {}' --bind 'ctrl-d:preview:file {}'
```

(In reality my preview commands are lot more complicated).
It seems natural to be able to hit the same key again to turn off the alternate preview. The current workaround requires changing the item then back again to go back to the default preview command (is there another way to go back to the 'default' preview?).

Is it possible that when triggering a preview action fzf could check if that preview is already active, and if so, go back to using the default preview instead? Maybe a new 'preview-switch' command is needed?

**Comment by junegunn** [comment]
It's not supported. I've tried not to add more stateful actions to fzf to avoid feature bloat.

Why don't you set up another preview binding?

```sh
fzf --preview 'cat {}' --bind 'ctrl-d:preview:file {}' --bind 'ctrl-f:preview:cat {}'
```

**Comment by smhc** [comment]
Yes I could add another binding - but that would require repeating the command and it's rather long. I could use an env var, or fzf could add another action of 'preview-default' that shows the default preview command.

But the main issue is that it requires another key-binding to get back to the 'default' state. A single key to 'toggle' the alternate preview would be best. It does seem like desirable functionality for alternate previews.

>  stateful actions to fzf to avoid feature bloat.

I understand. Although I'd be inclined to think the default 'x:preview:y' behaviour should be to toggle an alternate preview. It somewhat already behaves this way because the alternate preview doesn't "stick" - it restores back to the default when you change an item. The proposal of 'preview-switch' is simply for backwards compatibility.

**Comment by junegunn** [comment]
> the default 'x:preview:y' behaviour should be to toggle an alternate preview

That depends. A user may want to repeatedly hit the same key to "refresh" the preview content.

**Comment by junegunn** [comment]
20b4e69 implements `change-preview` action which will permanently change the default preview command which might help in some scenarios. However, there is no "toggle" functionality here, but I imagine a preview program can be written to depend on a state externally managed.

```sh
fzf --preview 'path-to-my-preview-program-that-depends-on-an-externally-managed-state-file {}' \
  --bind 'space:execute-silent(rotate-state-in-the-state-file)+refresh-preview'
