### ISSUE TITLE
FZF showing matches with a % sign. How do I remove them?

### ISSUE THREAD

**Issue by kuttor** [junegunn/fzf#2506]
- [X ] I have read through the manual page (`man fzf`)
- [X ] I have the latest version of fzf
- [X] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [X ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ X] zsh
    - [ ] fish
    
## Problem / Steps to reproduce
When I press tab to autocomplete the fzf matches I get a line at the top I am trying to remove

~ ❯ z
> z
  138/138 (0)
  **%Bexternal command%b %Bbuiltin command%b  %Bshell function%b   %Balias%b            %Bparameter%b**
  ·zcat
  ·zcmp
  ·zdiff
  ·zdump
  ·zegrep
  ·zfgrep
  ·zforce
  ·zgrep
  ·zic
  ·zip
  ·zipcloak
  ·zipdetails
  ·zipdetails5.18
  ·zipdetails5.30
  ·zipgrep
  ·zipinfo
  ·zipnote
  ·zipsplit
  ·zless
  ·zmore
  ·znew
  ·zprint
> ·zsh

The line in question is:
  **%Bexternal command%b %Bbuiltin command%b  %Bshell function%b   %Balias%b            %Bparameter%b**

**Comment by junegunn** [comment]
> press tab to autocomplete the fzf matches

This doesn't look like an issue of fzf, because it doesn't activate on TAB. You might want to debug the completion script you're using.
