### ISSUE TITLE
[REGRESSION] some input can cause the UI to become 'weird'

### ISSUE THREAD

**Issue by NightMachinary** [junegunn/fzf#2508]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

```
typeset a=$'@lulu @firewall @export LuLu\'s rules are stored in /Library/Objective-See/LuLu/rules.plist. If one has root privileges, by design, the rules can be directly read, and/or modified\n\C-@@zip @rar arc\n\C-@@pdf2epub @finereader flexible layout loses content. formatted_html+cali is good (though epub then cali is probably the same). fine reader is better than all I have tried yet.\n\C-@@pdf2epub @epub @pdf @word word to epub sucks with libre, cali, pandoc\n\C-@@zsh zsh: $var1 posix: How can I expand a quoted variable to nothing if it\'s empty? ${var1:+"$var1"}\n\C-@@Zsh @quote\nIn zsh, you can omit the double quotes most of the times, with a few exceptions.\n\n$var never expands to multiple words, however it expands to the empty list (as opposed to a list containing a single, empty word) if the value of var is the empty string. Contrast:\n\nvar=\nprint -l $var foo        # prints just foo\nprint -l "$var" foo      # prints an empty line, then foo\nSimilarly, "${array[@]}" expands to all the elements of the array, while $array only expands to the non-empty elements.\n\nThe @ parameter expansion flag sometimes requires double quotes around the whole substitution: "${(@)foo}".\n\nCommand substitution undergoes field splitting if unquoted: echo $(echo \'a\'; echo \'*\') prints a * (with a single space) whereas echo "$(echo \'a\'; echo \'*\')" prints the unmodified two-line string. Use "$(somecommand)" to get the output of the command in a single word, sans final newlines. Use "${$(somecommand; echo _)%?}" to get the exact output of the command including final newlines. Use "${(@f)$(somecommand)}" to get an array of lines from the command\'s output.\n\C-@boy\n\C-@@magic @progressify @go \nmacOS: dtruss go get github.com/divan/gofresh 2>&1 |  pv -i 0.05 > /dev/null\nlinux: strace -f -e trace=network go get github.com/divan/gofresh 2>&1 | pv -i 0.05 > /dev/null\n\C-@A variable declared with typeset without -g in a function has the local scope of the function.\n\C-@'

echo "$a" | FZF_DEFAULT_OPTS= command fzf --read0 
```

![image](https://user-images.githubusercontent.com/36224762/120105527-82cd7b80-c16e-11eb-8407-e22b6dd88024.png)

In previous versions, things were fine:
![image](https://user-images.githubusercontent.com/36224762/120105546-9842a580-c16e-11eb-825b-6ab83e1d40a5.png)

My current version:
```
❯ fzf --version                                                                                         
0.27.1 (brew)
```

**Comment by Azenet** [comment]
Getting the same issue after upgrading to 0.27.1, bisected the issue to commit 3f75a8369f63f2bd6ac3686fc5d88f2bc128e610.

**Comment by junegunn** [comment]
Thanks for the report. I can easily reproduce the problem like so.

```sh
seq 1000 | fzf --read0
```

The problem is `runewidth.StringWidth` is seeing `\n` as a zero-width character.

```go
package main

import "fmt"
import "github.com/mattn/go-runewidth"

func main() {
	fmt.Println(runewidth.StringWidth("foo\nbar"))
}
```

```
$ GO111MODULE=auto go run main.go
6
```

**Comment by junegunn** [comment]
Should be fixed in 0.27.2.

**Comment by KashcheyMC** [comment]
> 
> 
> 
> 
> - [x] I have read through the manual page (`man fzf`)
> - [x] I have the latest version of fzf
> - [x] I have searched through the existing issues
> 
> ## Info
> 
> - OS
>     - [ ] Linux
>     - [x] Mac OS X
>     - [ ] Windows
>     - [ ] Etc.
> - Shell
>     - [ ] bash
>     - [x] zsh
>     - [ ] fish
>     
> ## Problem / Steps to reproduce
> 
> ```
> typeset a=$'@lulu @firewall @export LuLu\'s rules are stored in /Library/Objective-See/LuLu/rules.plist. If one has root privileges, by design, the rules can be directly read, and/or modified\n\C-@@zip @rar arc\n\C-@@pdf2epub @finereader flexible layout loses content. formatted_html+cali is good (though epub then cali is probably the same). fine reader is better than all I have tried yet.\n\C-@@pdf2epub @epub @pdf @word word to epub sucks with libre, cali, pandoc\n\C-@@zsh zsh: $var1 posix: How can I expand a quoted variable to nothing if it\'s empty? ${var1:+"$var1"}\n\C-@@Zsh @quote\nIn zsh, you can omit the double quotes most of the times, with a few exceptions.\n\n$var never expands to multiple words, however it expands to the empty list (as opposed to a list containing a single, empty word) if the value of var is the empty string. Contrast:\n\nvar=\nprint -l $var foo        # prints just foo\nprint -l "$var" foo      # prints an empty line, then foo\nSimilarly, "${array[@]}" expands to all the elements of the array, while $array only expands to the non-empty elements.\n\nThe @ parameter expansion flag sometimes requires double quotes around the whole substitution: "${(@)foo}".\n\nCommand substitution undergoes field splitting if unquoted: echo $(echo \'a\'; echo \'*\') prints a * (with a single space) whereas echo "$(echo \'a\'; echo \'*\')" prints the unmodified two-line string. Use "$(somecommand)" to get the output of the command in a single word, sans final newlines. Use "${$(somecommand; echo _)%?}" to get the exact output of the command including final newlines. Use "${(@f)$(somecommand)}" to get an array of lines from the command\'s output.\n\C-@boy\n\C-@@magic @progressify @go \nmacOS: dtruss go get github.com/divan/gofresh 2>&1 |  pv -i 0.05 > /dev/null\nlinux: strace -f -e trace=network go get github.com/divan/gofresh 2>&1 | pv -i 0.05 > /dev/null\n\C-@A variable declared with typeset without -g in a function has the local scope of the function.\n\C-@'
> 
> echo "$a" | FZF_DEFAULT_OPTS= command fzf --read0 
> ```
> 
> ![image](https://user-images.githubusercontent.com/36224762/120105527-82cd7b80-c16e-11eb-8407-e22b6dd88024.png)
> 
> In previous versions, things were fine:
> ![image](https://user-images.githubusercontent.com/36224762/120105546-9842a580-c16e-11eb-825b-6ab83e1d40a5.png)
> 
> My current version:
> ```
> ❯ fzf --version                                                                                         
> 0.27.1 (brew)
> ```

[]()

**Comment by KashcheyMC** [comment]
[]()

**Comment by KashcheyMC** [comment]
- [ ] []()@KashcheyMC

**Comment by Azenet** [comment]
Cannot reproduce with your example @KashcheyMC on master (or with the `seq 1000 | fzf --read0` example for that matter), however I agree this still happens in some cases. I've attached [a file](https://github.com/junegunn/fzf/files/7272437/file.txt) that reproduces with `cat file.txt | fzf --read0` on master (b8aa2d2c32e791c5d9dc97443f0c7e108b52a34c) and would ask for a reopen if you can reproduce.

**Comment by NightMachinary** [comment]
@azenet I can't reproduce on `fzf 0.27.2 (brew)`:

![](https://files.lilf.ir/tmp/tmp.e1JBmK8JYU.png)

**Comment by Azenet** [comment]
@NightMachinary thanks for testing, I'm assuming this might be a terminal-related issue then (I'm using konsole on archlinux, tested with `0.27.2 (e086f0b)` and master)
