### ISSUE TITLE
Feature Request: Append-Query

### ISSUE THREAD

**Issue by rayiik** [junegunn/fzf#2509]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [x] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish
    - [x] powershell
## Problem / Steps to reproduce

# Feature Request  #
Append query/QUERY variable:
So i don't know if theirs a way outside of fzf to achieve this, ive tried a couple different things with very low levels of success. However there are many times (at least for me) when i dont want to replace-query or clear-query but rather i want to take the first query toggle search add some data then add another line from query and ad some data to that as well before i reload command {q}.

  I think this change/addition wouldn't be a taxing change but would add much depth and many creative possibilities. I think having the ability to append query using a variable  QUERY="$QUERY {}" --bind="key:set-query" would be the most versatile as this would allow for process substitution and herestring magic and possibly --bind="key:execute:export QUERY=$othervar/$(somsubstitution {}}"
  
   Some examples would be pulling part of a line from the results into the query using awk, adding a password to a list of generated ssh files, minor changes in format of the data before piping to some other command, appending a value after a list of generated flags. just some ideals off the top of my head but very very open field of possibility.

**Comment by rayiik** [comment]
hey so i've made a pull request (not sure how to link) but basically i took the replace query function duplicated it but modified the the first action
terminal.go
```go
case actAppendQuery:
current := t.currentItem()
    if current != nil {
    t.input = append(t.input, current.text.ToRunes()...)
}
type acctionType int
const (
actAppendQuery
```
options.go
```go
case "append-query":
appendAction(actAppendQuery)
```

however if failed two checks (which upon research seems to be related to the version of the request from github end and not the golang itself) have tested both the install script and make install from kali and arch linux both in actual installs and wsl.

**Comment by SpicyLemon** [comment]
This looks similar to https://github.com/junegunn/fzf/issues/2465 ([FEATURE] dynamic `replace-query`). That one's for the more general ability to replace the query, but could also easily handle appending to it.

**Comment by rayiik** [comment]
i mean yea but the way ive set it up works, so for now ill just implement it in a custom build of fzf the problem with the dynamic replace is that it modifies the search upon update my case use would be for example producing a list of flags for a command and some of the flags need additional information command --flag=(additional information) *append query here for next flag
