### ISSUE TITLE
`FZF_DEFAULT_OPTS` doesn't work when `fzf` is invoked via `tmux`

### ISSUE THREAD

**Issue by h0adp0re** [junegunn/fzf#2510]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

Export `FZF_DEFAULT_OPTS`
```sh
export FZF_DEFAULT_OPTS="
  --color hl:011,fg+:015,bg+:-1,hl+:011
  --color info:008,prompt:003,spinner:011,pointer:006,marker:002
  --cycle
  --prompt='❯ '
  --pointer='▶'
  --marker='│'
"
```

Run a script via tmux.
```tmux
bind-key f run-shell -b "$HOME/.dotfiles/scripts/project-picker.sh"
```

minimal `project-picker.sh`
```sh
find "$HOME" -maxdepth 1 -mindepth 1 -type d | fzf-tmux &>/dev/null
```

## Result

`fzf` runs with default settings, `FZF_DEFAULT_OPTS` gets lost somewhere.

This might be reproducible, but might not be. See https://github.com/wfxr/tmux-fzf-url/issues/13

**Comment by junegunn** [comment]
I can't seem to reproduce the problem.

![image](https://user-images.githubusercontent.com/700826/120284840-a7089400-c2f7-11eb-8e4f-ac716e2bb882.png)

![image](https://user-images.githubusercontent.com/700826/120284868-ac65de80-c2f7-11eb-83b0-265aa3f7d7be.png)

You can try debugging the problem by running fzf-tmux with `bash -x fzf-tmux`.

Commenting out this line will help you analyze the temporary files fzf-tmux creates.

https://github.com/junegunn/fzf/blob/a4bc08f5a35da6e374a2ce0da4c931d7fd32fdf1/bin/fzf-tmux#L159

**Comment by h0adp0re** [comment]
Well yeah, running it all from the command line, it works for me as well. The problem arises with the file structure given in the OP. Any way to debug that? The `tmux` popup or even a pane closes immediately after fzf is done, `bash -x` doesn't help there.

**Comment by junegunn** [comment]
It sounds like an issue of your setup rather than fzf. You should check an environment variable (not just FZF_DEFAULT_OPTS) is properly propagated to the sub-shell started by `run-shell`.

**Comment by h0adp0re** [comment]
> You should check an environment variable is properly propagated to the sub-shell started by `run-shell`.

Sorry for asking, but how could I do that?

**Comment by h0adp0re** [comment]
I've moved all my exported environment variables to `.zshenv` instead of `.zshrc`. Now it works.
