### ISSUE TITLE
How do I use fzf programatically?

### ISSUE THREAD

**Issue by Explosion-Scratch** [junegunn/fzf#2513]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [x] zsh
    - [ ] fish
    
# Question:
How would I go about using fzf programatically? I want to do something like this:
```bash
echo $(fzf -i search_term) #Echo the first matching file for 'search_term', instead of doing the whole interactive stuff
```

**Comment by junegunn** [comment]
Have you read through the manual page (`man fzf`)?

**Comment by Explosion-Scratch** [comment]
> Have you read through the manual page (`man fzf`)?

yes, I did. I couldn't find anything related to using it programatically. I want it to echo a list of results, and not show the user the finder. Also sorry for the late reply, I'm not online all the time.

**Comment by junegunn** [comment]
```
       -f, --filter=STR
              Filter mode. Do not start interactive finder. When used with --no-sort, fzf becomes a fuzzy-version of grep.
```

**Comment by Explosion-Scratch** [comment]
> ```
>        -f, --filter=STR
>               Filter mode. Do not start interactive finder. When used with --no-sort, fzf becomes a fuzzy-version of grep.
> ```

Cool! Thanks! I thought that meant that it only searched files matching a regex or something, apologies!
