### ISSUE TITLE
Edit the current selection?

### ISSUE THREAD

**Issue by 097115** [junegunn/fzf#2517]
I may be missing something but is it possible by any chance to edit the currently selected entry?

Like, if I have `rez=$(printf "foo\nbar\ntest" | fzf)`, and the cursor is on `test`, but I want the final result, which will be assigned to var `$rez`, to be `test this`. Then, can I press some hotkey, which will select the currently highlighted entry, and will allow me to modify it?

Thanks.

**Comment by junegunn** [comment]
fzf doesn't provide that functionaity.

> can I press some hotkey

You can use `--expect` option to see if the user pressed a special key.

```sh
readarray -t lines < <(printf "foo\nbar\ntest" | fzf --expect ctrl-e)
if [ "${lines[0]}" = ctrl-e ]; then
  # Edit the value in ${lines[1]} using `read` or something
fi
```
