### ISSUE TITLE
Unable to use `:` as delimiter

### ISSUE THREAD

**Issue by x10an14** [junegunn/fzf#2524]
- [x] I have read through the manual page (`man fzf`)
- [ ] I have the latest version of fzf **<-- _I have version_** `0.20.0`
- [x] I have searched through the existing issues

## Info

- OS
    - [x ] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ x] bash
    - [ ] zsh
    - [ ] fish
    
## Problem / Steps to reproduce
```
[2021-06-12 23:19:44] 0 x10an14@laptop:~
-> $ export EH="myprogrampath:ourprogrampath:yourprogrampath"
[2021-06-12 23:19:51] 0 x10an14@laptop:~
-> $ echo "$EH"
myprogrampath:ourprogrampath:yourprogrampath
[2021-06-12 23:19:53] 0 x10an14@laptop:~
-> $ echo "$EH" | fzf -d ':' --filter="your"
myprogrampath:ourprogrampath:yourprogrampath
[2021-06-12 23:20:03] 0 x10an14@laptop:~
-> $ echo "$EH" | tr ':' '\n' | fzf --filter="your"
yourprogrampath
[2021-06-12 23:20:08] 0 x10an14@laptop:~
-> $
```

So, as you can see I've fixed it myself by using `tr`, but I'm making this issue to ask what I've misunderstood/overlooked after having read the section on `--delimiter` in the man page, and done a [general](https://github.com/junegunn/fzf/issues/1920) search [for](https://github.com/junegunn/fzf/issues/1792) delimiter [issues](https://github.com/junegunn/fzf/issues/1899).

This is me trying to write a program á la:
```bash
function pathrm() {
    # Taken from: https://unix.stackexchange.com/a/270558/119282
    PATH="$(echo $PATH | sed -e "s;\(^\|:\)${1%/}\(:\|\$\);\1\2;g" -e 's;^:\|:$;;g' -e 's;::;:;g')"
}

function move_path_segment_to_end_of_path() {
    for segment in $(tr ':' '\n' <<< "$PATH" | fzf --filter="${1}"); do
        pathrm "${segmen}t"
        PATH="${PATH}:${segment}"
    done
    export PATH
}
```

**Comment by vovcacik** [comment]
The way you solved it is the proper way. Note that the delimiter option merely splits a line in segments, but it will not split the line into more lines. The filter option filters lines and not the segments.

**Comment by x10an14** [comment]
Sorry for taking so long before coming back to this!
> The filter option filters lines and not the segments.

Aight, that was not clear for me after reading (and re-reading) the manpage/documentation. Will close now, thanks!
