### ISSUE TITLE
Removing The Preview Window's Line Counter

### ISSUE THREAD

**Issue by p0da** [junegunn/fzf#2525]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

    
## Problem / Steps to reproduce
Is there any way to remove the line counter that is displayed in the preview window for lengthy text. For example in the screenshot:

 ![image](https://user-images.githubusercontent.com/60058955/121800438-6119cd00-cc21-11eb-9242-dbba0ea194ea.png)

 '1/5461' is the text I would like to remove. Apologies if it is obvious I have looked through everything and I cant seem to find it.

**Comment by junegunn** [comment]
Added `noinfo` flag to `--preview-window`.

```sh
fzf --preview 'seq 1000' --preview-window noinfo
```

I'm not sure if it's the best name for the option, so I may change it to something else before releasing a new version.
