### ISSUE TITLE
Option to show newlines as \n

### ISSUE THREAD

**Issue by p00f** [junegunn/fzf#2529]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

I'd like to use fzf in a terminal as a clipboard picker with [clipman](https://github.com/yory8/clipman), if the text is
```
foo
bar
baz
```
and I do 
`clipman pick --print0 --tool=CUSTOM --tool-args="fzf --prompt 'clipboard > ' --read0 --layout=reverse --cycle"`,
I see this:
![image](https://user-images.githubusercontent.com/36493671/122024956-8c014e00-cde6-11eb-8afc-92287e49cedf.png)

wofi and rofi show newlines as \n: (`clipman pick -t wofi`)
![image](https://user-images.githubusercontent.com/36493671/122025272-dda9d880-cde6-11eb-904c-a4ee2e463d0c.png)

Can an option to show newlines as \n be added?

**Comment by jmcantrell** [comment]
Was anything done with this? I'm not seeing an option that seems relevant, but this says it was completed.

**Comment by p00f** [comment]
I closed this by mistake, sorry

**Comment by junegunn** [comment]
We could use something like ␤.
