### ISSUE TITLE
Extending the list of shortcuts

### ISSUE THREAD

**Issue by tamis-laan** [junegunn/fzf#2534]
The number of shortcuts that can be used with fzf is very limited. It looks like the primary modifier key is `Alt` which is often used with tilling window managers. It there a way to extend the number of possible shortcuts?

Problem we are running into:
https://github.com/pystardust/ytfzf/issues/275

**Comment by junegunn** [comment]
With ctrl-[a-z], alt-[a-z], and ctrl-alt-[a-z], 78 key chords, that's plenty for most use cases. Shift-enter or ctrl-enter are the key chords that are not supported by standard terminals, so fzf doesn't support them either.
