### ISSUE TITLE
[Feature Request] Add a `current-line-change` event

### ISSUE THREAD

**Issue by noib3** [junegunn/fzf#2535]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [x] fish
    
## Problem / Steps to reproduce
I'm trying to execute a custom `cleaner` script whenever the currently selected line changes. Missing the corrisponding event, I've sort of been able to do this with the following flags:

```
--bind "change:execute-silent(cleaner)" \
--bind "ctrl-k:execute-silent(cleaner)+up" \
--bind "ctrl-p:execute-silent(cleaner)+up" \
--bind "up:execute-silent(cleaner)+up" \
--bind "ctrl-j:execute-silent(cleaner)+down" \
--bind "ctrl-n:execute-silent(cleaner)+down" \
--bind "down:execute-silent(cleaner)+down" \
--bind "pgup:execute-silent(cleaner)+page-up" \
--bind "pgdn:execute-silent(cleaner)+page-down" \
--bind "enter:execute-silent(cleaner)+accept" \
--bind "double-click:execute-silent(cleaner)+accept" \
--bind "ctrl-c:execute-silent(cleaner)+abort" \
--bind "ctrl-g:execute-silent(cleaner)+abort" \
--bind "ctrl-q:execute-silent(cleaner)+abort" \
--bind "esc:execute-silent(cleaner)+abort" \
```

apart from being unnecessarily complex this doesn't even work 100% of the time, for example when the currently selected file is the first (last) one in the list and I press up (down), I'm still calling that script even though I shouldn't because the selected file hasn't changed.

Having something like a `current-line-change` event that triggers whenever the currently selected line changes would allow me to avoid all this mess.

**Comment by junegunn** [comment]
You can use `--preview` for that purpose.

```sh
fzf --preview 'say hi; cat {}'

# If size is given as 0, preview window will not be visible, but fzf will still execute the command in the background.
fzf --preview 'say hi' --preview-window 0
```

(The initial discussion can be found in #820)
