### ISSUE TITLE
Floating window sometime will hang during searching

### ISSUE THREAD

**Issue by jiangjianshan** [junegunn/fzf#2543]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [ ] Mac OS X
    - [x] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish
    
## Problem / Steps to reproduce
I have found sometimes the floating window will hang when fzf is searching using ':Rg' or ':Files' command with bat.
![fzf_hang](https://user-images.githubusercontent.com/20179047/123404770-c4b9d800-d5db-11eb-81f3-ea4baea386f3.png)

Here is my configuration for fzf & fzf.vim at gVim 8.2. The Git version is 'git version 2.31.1.windows.1'. The bat version is 0.18.1.
![vimrc](https://user-images.githubusercontent.com/20179047/123405006-00ed3880-d5dc-11eb-9332-2dc972a0fc37.png)
![vimrc2](https://user-images.githubusercontent.com/20179047/123405220-2e39e680-d5dc-11eb-9f12-60bbd91d03e7.png)

It was happen a lot of times and the project I'm searching on it is only 7857 files inside. Is there a debug way or some configuration is wrong for my _vimrc.

**Comment by junegunn** [comment]
I couldn't reproduce the problem. Please leave a comment if this is still an issue for you.
