### ISSUE TITLE
How to configure key binding for page down and page up

### ISSUE THREAD

**Issue by avatar-lavventura** [junegunn/fzf#2547]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [x ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

General usage for `fzf` to check command history via `ctrl+r`.

I am not able to do page-down and page-up operation in `fzf`, would it be possible to do it? In addition to that, I was wondering can we bind `Ctrl+v` for page down and `ALT-v` for page up?

**Comment by relastle** [comment]
Please try

```bash
history | fzf --bind='alt-v:page-up' --bind='ctrl-v:page-down'
```

or 

```bash
history | fzf --bind='alt-v:page-up,ctrl-v:page-down'
```

You can find the key binding help in `KEY/EVENT BINDINGS` section of `man fzf`.

**Comment by avatar-lavventura** [comment]
Would it be wise to do something like: ```alias history=$(history | fzf --bind='alt-v:page-up' --bind='ctrl-v:page-down')```
