### ISSUE TITLE
Support indexing, warm scans

### ISSUE THREAD

**Issue by jtagcat** [junegunn/fzf#2550]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues: 3-4 times

## Info
- OS: Linux
    
## Problem / Steps to reproduce
A 'simple' implementation would be to export and restore to-from a file.

From ncdu manpages:
```
       Since scanning a large directory may take a while, you can scan a directory and export the results for
       later viewing:

         ncdu -1xo- / | gzip >export.gz
         # ...some time later:
         zcat export.gz | ncdu -f-
```

Getting more advanced, indexing to a known location (say `.cache/fzf`, `AppData/Local/fzf`), and then using it on second searches.

**Comment by junegunn** [comment]
fzf is a text filter like grep. Caching is beyond the scope of the project.


```sh
my-smart-listing-program-that-implements-caching-mechanism | fzf

# or
export FZF_DEFAULT_COMMAND="my-smart-listing-program-that-implements-caching-mechanism"
fzf
```

#1872
