### ISSUE TITLE
Allow field index expression to use 'n'

### ISSUE THREAD

**Issue by xeruf** [junegunn/fzf#2552]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

I have multiple scripts that pipe into the same fzf alias with a predefined preview, but there is one issue:
In one of the scripts, I am now adding `--nth` to the fzf call, which means I have to adjust the preview as well.

What I would like is the option to specify `{n}` as a FIELD INDEX EXPRESSION in `--preview`, which means:
Take the part according to `--nth` or everything if the flag is not specified.

**Comment by junegunn** [comment]
I would use an environment variable to avoid repetition.

**Comment by xeruf** [comment]
I do use environment variables, but I don't understand how they would help here
