### ISSUE TITLE
`Rust` TUI Programs not Loading on macOS

### ISSUE THREAD

**Issue by lmburns** [junegunn/fzf#2565]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish
    
## Problem / Steps to reproduce
Output of my system
```sh
uname -a
Darwin void.local 20.5.0 Darwin Kernel Version 20.5.0: Sat May  8 05:10:33 PDT 2021; root:xnu-7195.121.3~9/RELEASE_X86_64 x86_64 i386 MacBookPro14,1 Darwin

zsh --version
zsh 5.8 (x86_64-apple-darwin20.1.0)
```

I am writing another program that uses `fzf` as sort of a TUI and have found that nearly all Rust TUI programs will not load on `macOS`. I use `iTerm` as my main terminal, though I've tested out `alacritty` and the default Terminal application. The following is a list of programs that I have tried and what their result is. 

The following programs were tested using the following syntax:
```sh
fzf --bind 'A:execute(_program_)'
```
And if that failed, the following syntax was used instead:
```sh
fzf --bind 'A:execute(_program_ < /dev/tty > /dev/tty 2>&1)'
```
| Program | Language | Works |
| -----|------|------|
| [ctop](https://github.com/bcicen/ctop)                         | `Go`     | Loads                             |
| [cointop](https://github.com/miguelmota/cointop)               | `Go`     | Loads                             |
| [dry](https://github.com/moncho/dry)                           | `Go`     | Loads                             |
| [glow](https://github.com/charmbracelet/glow)                  | `Go`     | Loads                             |
| [lazydocker](https://github.com/jesseduffield/lazydocker)      | `Go`     | Loads                             |
| [lazygit](https://github.com/jesseduffield/lazygit)            | `Go`     | Loads                             |
| [grv](https://github.com/rgburke/grv)                          | `Go`     | Loads                             |
| [lf](https://github.com/gokcehan/lf)                           | `Go`     | Loads                             |
| [gitbatch](https://github.com/isacikgoz/gitbatch)              | `Go`     | Loads                             |
| [tig](https://github.com/jonas/tig)                            | `C`      | Loads                             |
| [ncdu](https://github.com/Byron/dua-cli)                       | `C`      | Loads                             |
| [ncmpcpp](https://github.com/ncmpcpp/ncmpcpp)                  | `C++`    | Loads                             |
| [ranger](https://github.com/ranger/ranger)                     | `Python` | Loads                             |
| [glances](https://github.com/nicolargo/glances)                | `Python` | Loads                             |
| [rtv](https://github.com/michael-lazar/rtv)                    | `Python` | Loads                             |
| [xplr](https://github.com/sayanarijit/xplr)                    | `Rust`   | Loads (but freezes)               |
| [gpg-tui](https://github.com/orhun/gpg-tui)                    | `Rust`   | Doesn't load                      |
| [gitui](https://github.com/extrawurst/gitui)                   | `Rust`   | Doesn't load                      |
| [btm](https://github.com/ClementTsang/bottom)                  | `Rust`   | Loads (but freezes)               |
| [taskwarrior-tui](https://github.com/kdheepak/taskwarrior-tui) | `Rust`   | Doesn't load                      |
| [dua](https://github.com/Byron/dua-cli)                        | `Rust`   | Only one that loads               |

I wasn't sure if there was a particular Rust library that is being used to cause this, if there is something that is wrong with `fzf` that is preventing Rust-specific TUI's from working, or if the issue has something to do with `macOS` and/or the terminal that I am using.

I was submitting an issue for [`gpg-tui`](https://github.com/orhun/gpg-tui/issues/27#issuecomment-883726810) and the developer said that using their program within `fzf` worked, though I am unsure of their operating system.

Also, if there are other TUI's that you can list for me to try out then I can. 

Edit: Changed the title to `macOS` specific, because I tried `btm` on my Debian server and it worked just fine.

**Comment by eo1989** [comment]
Im running macOS Catalina 10.15.7 (early-2013 rMBP) and gitui runs for me. All my rust programs run. Did you install via rustup? do you have home-brew or cargo?

**Comment by lmburns** [comment]
Yes I installed it via rustup. I use iTerm and believe that I tried it in alacrity and the default terminal on `macOS`. I'm away from my computer now, but will check and see if a homebrew installation of rust is interfering with the program loading

**Comment by junegunn** [comment]
I can reproduce the problem, but it doesn't look like an issue of fzf because it's reproducible using different methods.

```sh
# Doesn't work
gitui < /dev/tty

# But this works fine
vim < /dev/tty

# This fails to capture key inputs
btm < /dev/tty
```
