### ISSUE TITLE
Select all matches action.

### ISSUE THREAD

**Issue by lompy** [junegunn/fzf#257]
It would be great to have an action to select all currently matching results. That action could be bound to some key. And in case you need to select all the results you can just hit one key instead of tabbing one by one the entire list.

Didn't find this feature in docs. Did I miss something?

**Comment by junegunn** [comment]
Thanks for the suggestion. Added three actions for `--bind`: select-all / deselect-all / toggle-all, which are unbound by default. So now you can write something like this:
```sh
fzf -m --bind ctrl-a:select-all,ctrl-d:deselect-all,ctrl-t:toggle-all
```
(or you could put it in your `$FZF_DEFAULT_OPTS`)
I'll update the man page as well when I release 0.9.14.

**Comment by lompy** [comment]
Wow, superfast response! Thanks for great work. Finally can get rid of Unite.vim for `global find -> narrow results -> replace in narrowed` with awesome `Ag` function example.

**Comment by Fixles** [comment]
Hi, I cloned the git repo today but none of this shortcuts do anything? I pasted the command exactly as you entered. I tried it in a few different terminals but just acts as if I'd just typed fzf -m?

fzf -m --bind ctrl-a:select-all,ctrl-d:deselect-all,ctrl-t:toggle-all

**Comment by junegunn** [comment]
@Fixles I haven't officially released the new version with this feature. You can download the prerelease binary or build from source if it's urgent but I'm planning to release 0.10.0 this weekend.

**Comment by Fixles** [comment]
haha ok thanks I can wait a couple of days :)
