### ISSUE TITLE
header ansi colors don't work unless preceded by a dollar sign -- update documentation to give an example

### ISSUE THREAD

**Issue by reportaman** [junegunn/fzf#2574]
- [X] I have read through the manual page (`man fzf`)
- [X] I have the latest version of fzf
- [X] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [X] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [X] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

As per documentation, the header should process (apply) ansi colors, but it doesn't unless preceded by a dollar sign as mentioned in https://github.com/junegunn/fzf/issues/2574#issuecomment-895198968. Please update the documentation :)

Test string to reproduce:
```
echo -e '\u1b[31mhello\u1b[33m world' | fzf --ansi --header='\u1b[31mhello\u1b[33m world'
```

Documentation:
```
       --header=STR
              The given string will be printed as the sticky header. The lines are displayed in the given order  from  top  to
              bottom  regardless  of  --layout option, and are not affected by --with-nth. ANSI color codes are processed even
              when --ansi is not set.
```

Screenshot:
![Screen Shot 2021-08-03 at 11 02 57 PM](https://user-images.githubusercontent.com/71736629/128130081-23dd86bf-4891-4acd-b203-ad5600047b01.png)

Neofetch:
```
❯ neofetch
                    'c.          reportaman@Mac-mini.local
                 ,xNMM.          ------------------------------
               .OMMMMo           OS: macOS 11.5 20G71 arm64
               OMMM0,            Host: Macmini9,1
     .;loddo:' loolloddol;.      Kernel: 20.6.0
   cKMMMMMMMMMMNWMMMMMMMMMM0:    Uptime: 3 hours, 57 mins
 .KMMMMMMMMMMMMMMMMMMMMMMMWd.    Packages: 1 (brew)
 XMMMMMMMMMMMMMMMMMMMMMMMX.      Shell: zsh 5.8
;MMMMMMMMMMMMMMMMMMMMMMMM:       Resolution: 3840x2160
:MMMMMMMMMMMMMMMMMMMMMMMM:       DE: Aqua
.MMMMMMMMMMMMMMMMMMMMMMMMX.      WM: Quartz Compositor
 kMMMMMMMMMMMMMMMMMMMMMMMMWd.    WM Theme: Blue (Dark)
 .XMMMMMMMMMMMMMMMMMMMMMMMMMMk   Terminal: iTerm2
  .XMMMMMMMMMMMMMMMMMMMMMMMMK.   Terminal Font: OperatorMonoNerdFontComplete-Light 22
    kMMMMMMMMMMMMMMMMMMMMMMd     CPU: Apple M1
     ;KMMMMMMMWXXWMMMMMMMk.      GPU: Apple M1
       .cooc,.    .,coo:.        Memory: 2128MiB / 16384MiB
```

Also: I am using a modified xterm-256color

**Comment by relastle** [comment]
You can use the command below.

```bash
echo -e '\u1b[31mhello\u1b[33m world' | fzf --ansi --header=$'\u1b[31mhello\u1b[33m world'
```

Note that `--header=$'...'` is used instead of `--header='...'`.

**Comment by reportaman** [comment]
@relastle Thanks! That worked!!

**Comment by slowpeek** [comment]
It is not an issue but a misunderstanding: ANSI sequences must be raw, not in escaped human-readable form. `$'...'` is a [shell thing](https://www.gnu.org/software/bash/manual/html_node/ANSI_002dC-Quoting.html) used to convert escaped sequences into raw chars, like `echo -e` does; it has no relation to `fzf`. Sample code:

```bash
echo '\e[31mhello\e[33m world\e[0m'
echo -e '\e[31mhello\e[33m world\e[0m'
echo $'\e[31mhello\e[33m world\e[0m'
```

Result:
![Screenshot_20210820_234731](https://user-images.githubusercontent.com/83845566/130291772-70bc8886-65be-422f-a18a-c0167943b4c0.png)


As you see the first line is the same junk you get when using human-readable sequences in `--header` value. As only you enclose the string in `$'...'`, the sequences are converted to raw chars **by shell**.

Summary:

```bash
# wrong, human-readable form
ls ~ | fzf --reverse --header '\e[31mred header\e[0m'

# correct, raw chars
ls ~ | fzf --reverse --header $'\e[31mred header\e[0m'
```

**Comment by junegunn** [comment]
@slowpeek Thanks for the excellent explanation!
