### ISSUE TITLE
Piping breaks preview

### ISSUE THREAD

**Issue by xeruf** [junegunn/fzf#2579]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

    fzf --bind='enter:execute(less {})' | cut -c2-

Simply execute this and hit enter on a file.

For me at least what happens is that the less window immediately closes and the output is send through `cut`, visible in the terminal upon quitting `fzf`. It does not seem to matter which pager I use or which configuration. This is definitely unexpected and took me hours to track down :/

**Comment by junegunn** [comment]
```sh
fzf --bind='enter:execute(less {} > /dev/tty)' | cut -c2-
```

This will help you understand the situation better

```sh
less README.md | wc -l
less README.md > /dev/tty | wc -l
```
