### ISSUE TITLE
0.10.0

### ISSUE THREAD

**Issue by junegunn** [junegunn/fzf#258]
- [x] Changelog
- [x] Update man page
    - ~~`--null`~~
    - `--history`
    - `--history-max`
    - `--cycle`
    - More actions for `--bind`
        - `ignore`, `select-all`, `deselect-all`, `toggle-all`, `previous-history`, `next-history`, `execute`
    - Key synonyms for `--bind` and `--toggle-sort` (not `--expect`)
- [x] Release binaries
- [x] Update install script
- [x] Homebrew (optional)

**Comment by edi9999** [comment]
Great ! Congrats on the new release.

**Comment by junegunn** [comment]
Thanks :)
