### ISSUE TITLE
Support to pass remaining arguments to a program

### ISSUE THREAD

**Issue by alexherbo2** [junegunn/fzf#2581]
There is currently no support for perfect forwarding of arguments to a program.

**Example**

``` sh
fzf --bind 'change:reload(rg -- {q} "$@")' -- "$@"
```

My use case is to be able to pass the buffer list from [Kakoune], so I can grep them.

[Kakoune]: https://kakoune.org

For reference, I use this command from [kakoune.cr]:

``` sh
fzf --phony --delimiter ':' --ansi --bind 'change:reload(rg --color=always --column --with-filename --fixed-strings -- {q} || true),enter:execute(kcr edit {1} +{2}:{3})+abort' --preview 'highlight_line={2} line_range_begin=$((line = highlight_line - (FZF_PREVIEW_LINES / 4) && line < 1 ? 1 : line)) line_range_end=$((line_range_begin + FZF_PREVIEW_LINES)) && bat --style=numbers --color=always --line-range "$line_range_begin:$line_range_end" --highlight-line {2} {1} 2> /dev/null' --header='Select a file to open' --prompt='(g)>' --query "$*"
```

[kakoune.cr]: https://github.com/alexherbo2/kakoune.cr

**Comment by junegunn** [comment]
I can imagine you can easily implement the scheme using an external script, function, or environment variables.

**Comment by alexherbo2** [comment]
Can you show me an example with the first example?  I don’t see how it is possible to forward the remaining arguments passed to `fzf` to the bindings.

For example, `jq` has something like that:

``` sh
jq --null-input '$ARGS.positional' --args -- a b c
```

**Comment by junegunn** [comment]
Something like this.

```
foo() {
  cmd="echo ${@@Q}" fzf --preview 'eval "$cmd"'
}
foo 'foo "bar"' 123 456
```
