### ISSUE TITLE
cert expired ;)

### ISSUE THREAD

**Issue by agilob** [junegunn/fzf#2582]
https://junegunn.kr/images/fzf-0.17.0.png

This server could not prove that it is junegunn.kr; its security certificate expired in the last day. This may be caused by a misconfiguration or an attacker intercepting your connection. Your computer's clock is currently set to Thursday, 12 August 2021. Does that look right? If not, you should correct your system's clock and then refresh this page.

**Comment by junegunn** [comment]
Thank yout. I had to restart the nginx process. I'd want to avoid doing that manually, but I haven't had time to investigate.
