### ISSUE TITLE
execute-multi is working but undocumented

### ISSUE THREAD

**Issue by henriquehbr** [junegunn/fzf#2586]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish
    
## Problem / Steps to reproduce

I've noticed that a `execute-multi` option was added in the past (https://github.com/junegunn/fzf/commit/0de7f16016fc694ea4c6bfbc87eec2fb5b667b1e), and it actually works on the current versions of `fzf`, looking at some of the old commits, it used to have it's entry on the man page, but currently, i couldn't find it on the docs, neither on the repo wiki

Is it intended, will this option be removed/replaced on the future? or it was just moved to another place of the documentation?

**Comment by junegunn** [comment]
It was deprecated and undocumented on purpose in favor of `{+}` syntax. See https://github.com/junegunn/fzf/commit/736344e151fd8937353ef8da5379c1082e441468.
