### ISSUE TITLE
fzf ctrl-r doesn't collect history commands inside tmux (ubuntu)

### ISSUE THREAD

**Issue by timfeirg** [junegunn/fzf#259]
when in tmux, `fzf-history-widget` doesn't seems to be collecting history commands from .zsh_history, and I can't reproduce on my mac book.

# to reproduce

```bash
echo 'random message'
^R
# fzf interface shows up, and the previous command didn't show up
```

here's inside tmux, or byobu:
(deleted the screenshot)

and here's outside tmux:
![cursor_and__mosh__timfeirg_10-6-10-13___](https://cloud.githubusercontent.com/assets/4319104/8063159/dbfae156-0f05-11e5-9097-5262089d54d7.gif)

**Comment by junegunn** [comment]
CTRL-R simply reads the output of `fc -l 1`. What do you get when you run the command?

**Comment by timfeirg** [comment]
thanks for the quick response, @junegunn I get the same output from terminal and within tumx

**Comment by junegunn** [comment]
That's weird. Can you compare the following two commands?
- `fc -l 1 | fzf --tac`
- `fc -l 1 | fzf-tmux --tac`

**Comment by timfeirg** [comment]
# within tmux

`fc -l 1 | fzf --tac` list all candidates, everything, 1969 results in total
`fc -l 1 | fzf-tmux --tac` has only 1861 results

# outside tmux

two commands has the exact same output

**Comment by junegunn** [comment]
Thanks. `fzf-tmux` was designed to work just the same as `fzf` when not on tmux, so you don't need to check it w/o tmux.

So for some reason, `fzf-tmux` is not receiving the entire input stream. Do you experience similar problem with other commands as well? Such as `seq 1000000 | fzf-tmux`

**Comment by junegunn** [comment]
Just to be sure. Do you have enough free space on your root partition?

**Comment by timfeirg** [comment]
`seq 1000000 | fzf-tmux` shows 1000000/1000000 results, no truncation.
I think I have enough free space, `df -h` says the following:
```
Filesystem      Size  Used Avail Use% Mounted on
/dev/vda1        20G   12G  7.5G  60% /
```

**Comment by junegunn** [comment]
Hmm, so then it's not about the size of the input and I'm clueless.
When you repeat `fc -l 1 | fzf-tmux --tac`, does it always show the exact 1861 results? Is there anything suspicious with the item 1862 or 1863?

**Comment by timfeirg** [comment]
so I went into tmux:

1. I ran `fc -l 1 | fzf-tmux --tac`, fzf shows 1862 results, they were just some commands I executed earlier today, but I won't be able to match the most recent ones.
2. I `echo`ed a few more garbages, and then `fc -l 1 | fzf-tmux --tac`, the results list were the same 1862 candidates.

**Comment by timfeirg** [comment]
I can't even reproduce this issue on a different ubuntu 14.04 server using the same version of fzf, it should be something wrong with that specific machine, I'll try to recall if I did something special on my problematic server today during sleep.

**Comment by timfeirg** [comment]
I really can't decide what's wrong with that server and how to reproduce anywhere else, so I changed `fzf-tmux` to `fzf` just to be able to continue use `fzf`, it's such a marvelous good tool and I absolutely can't live without it.

If there's anything I can do to continue troubleshooting this issue, please let me know, closing this issue for now.

**Comment by junegunn** [comment]
I see, thanks. Note that the key bindings will not use fzf-tmux when `$FZF_TMUX` is set to `0`.
https://github.com/junegunn/fzf#key-bindings-for-command-line
