### ISSUE TITLE
fzf command line search history

### ISSUE THREAD

**Issue by ssh352** [junegunn/fzf#2595]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

## Problem / Steps to reproduce

I ctrl-t, I see the file list, I type the substring I'd like to search. I ctrl-c to quit.

I ctrl-t again, how do I use the substring I used last time to search?

thanks for such a useful tool, a long time user.

**Comment by junegunn** [comment]
You can't. There is no option to persist cancelled queries.
