### ISSUE TITLE
Preview doesn't load in Kitty

### ISSUE THREAD

**Issue by sbaildon** [junegunn/fzf#2596]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [x] zsh
    - [x] fish

## Problem / Steps to reproduce

When `$TERM` is `xterm-kitty`, fzf's preview window is stuck `Loading ..`

The[ kitty terminal emulator](https://sw.kovidgoyal.net/kitty/binary/) sets `$TERM` to `xterm-kitty` by default

 ❌ `TERM=xterm-kitty fzf --query=readme.md --preview='bat {}'` |  ✅ `TERM=xterm-256color fzf --query=readme.md --preview='bat {}'`
------|-------
<img width="676" alt="image" src="https://user-images.githubusercontent.com/214264/129888037-6468f58a-d9a0-4634-b481-9a1c6d24524d.png">|<img width="676" alt="image" src="https://user-images.githubusercontent.com/214264/129888122-504fcd95-be13-446e-bfe0-874f1bdcfabc.png">

**Comment by junegunn** [comment]
Have you checked if running `TERM=xterm-kitty bat SOME_FILE` works?

**Comment by sbaildon** [comment]
Yeah—`bat` works fine inside kitty

**Comment by sbaildon** [comment]
Odd. I got to my keyboard this morning and everything is okay. I'll chalk it up to a spooky action at a distance. Thank you for checking in

**Comment by junegunn** [comment]
FWIW, you probably want to write `bat --color=always {}`.

**Comment by junegunn** [comment]
```sh
# ~3 for sticky header
fzf --preview 'bat --color=always {}' --preview-window '~3'
```

**Comment by sbaildon** [comment]
> ```shell
> # ~3 for sticky header
> fzf --preview 'bat --color=always {}' --preview-window '~3'
> ```
```
--preview-window '~3'
```

Useful for those using all of `bat`'s styling (default behaviour). I opt in for the `cat` experience with `--style=plain`
