### ISSUE TITLE
Space binding in FZF_DEFAULT_OPTS

### ISSUE THREAD

**Issue by sandric** [junegunn/fzf#260]
Is there a way to set space for keybinding via FZF_DEFAULT_OPTS variable? I tried this in my fish config:
`set -x FZF_DEFAULT_OPTS '--bind ctrl-a:abort, :accept'` and ``set -x FZF_DEFAULT_OPTS '--bind ctrl-a:abort,Space:accept'`` but it gives me an error.

P.S. I saw code for this and looks like its not hard to be added. Will this pr be appreciated?

**Comment by junegunn** [comment]
Escaping the space works for me (at least on bash):
```sh
fzf --bind ctrl-a:abort,\ :accept

export FZF_DEFAULT_OPTS="--bind ctrl-a:abort,\ :accept"
```

**Comment by sandric** [comment]
Oh, I forgot trying with escaping, silly me). thx them.
