### ISSUE TITLE
alt-enter key binding does not work on macos

### ISSUE THREAD

**Issue by sdondley** [junegunn/fzf#2607]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

## Problem / Steps to reproduce

Followed the instructions here for switching between rg search and fzf fuzzy search: https://github.com/junegunn/fzf/blob/master/ADVANCED.md#switching-to-fzf-only-search-mode

alt-enter activates siri by default on a mac, but even turning that hotkey off, the alt key does not appear to work well as a modifier key as I could not get it to work. Only changing it to `ctrl-x` could I switch to fzf searching.

This is an awesome feature, by the way!

**Comment by junegunn** [comment]
See #164

**Comment by sdondley** [comment]
Ah, yup. ctrl-enter works for alt-enter. Thanks. Really awesome program, by the way. Best utility ever. Hope you are making millions. :)
