### ISSUE TITLE
Bind two or more keys for the same action

### ISSUE THREAD

**Issue by mhrebenyuk** [junegunn/fzf#261]
It will be great if fzf could support multiple keys per an action for the bind option.

For example, 
fzf --bind=ctrl-j:accept,ctrl-m:accept,ctrl-k:kill-line

**Comment by junegunn** [comment]
It's already possible. And in this particular case, CTRL-M is mapped to "accept" by default, so just by `fzf --bind=ctrl-j:accept,ctrl-k:kill-line` both keys work
