### ISSUE TITLE
Call to bind in non-capable terminals

### ISSUE THREAD

**Issue by astoff** [junegunn/fzf#2618]
When I start bash in an Emacs dumb terminal, I see this:

```
bash: bind: warning: line editing not enabled
```

This warning is triggered by the line indicated below, which calls `bind` without checking the terminal type.

https://github.com/junegunn/fzf/blob/f4f47f5fe32db500765b47d937f5eb8fa27be130/shell/completion.bash#L35

**Comment by harrigan** [comment]
I check for the warnings in my .bashrc:

```
check_bind_warning() {
    if ! bind -v 2>&1 | grep -q "warning:"; then
        echo "bind command executed without warnings"
        return 0
    else
        echo "bind command returned a warning"
        return 1
    fi
}

if check_line_editing; then
    eval "$(fzf --bash)"
fi
```
