### ISSUE TITLE
Broke in OS X 10.11 El Capitan

### ISSUE THREAD

**Issue by firedev** [junegunn/fzf#262]
Just installed the developer beta and fzf is always empty:
```
  0/0
>
```

**Comment by firedev** [comment]
Sorry, I have probably messed something up with folders and paths. It is working fine.

**Comment by seanwash** [comment]
@firedev How did you fix this? Im having the same thing happening.

**Comment by junegunn** [comment]
@seanwash 
Do you have $FZF_DEFAULT_COMMAND set?
Do you still get empty list on `ls | fzf`?

**Comment by seanwash** [comment]
@junegunn So things seem to be working fine when outside of vim, but inside vim it's an empty list. However, :Tags works just fine. I have another laptop running with fzf + fzf.vim just fine so it's probably a config issue.

**Comment by junegunn** [comment]
@seanwash Make sure [this command](https://github.com/seanwash/dotfiles/blob/master/vimrc#L161) works fine. On my other laptop I think I had to reinstall ag after el capitan upgrade.

**Comment by seanwash** [comment]
@junegunn That was it. AG wasn't installed on this machine -____- sorry to waste your time! I'm really loving FZF and spreading the word as much as I can!

**Comment by junegunn** [comment]
@seanwash No problem!
