### ISSUE TITLE
[FR] add support for binding `ctrl` and the arrow keys

### ISSUE THREAD

**Issue by NightMachinary** [junegunn/fzf#2623]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

## Problem / Steps to reproduce
On my system, `ctrl-up` acts as though it was `shift-up` for fzf, and I don't see it as a bindable key in the manpage. Considering `cmd` doesn't work as a modifier either, it would be much appreciated if `ctrl` worked at least.

**Comment by NightMachinary** [comment]
(As a matter of fact, if you can just let us bind arbitrary escape sequences, that would be the best and easiest solution.)

**Comment by codethief** [comment]
@NightMachinary Should this ticket then be closed in favor of your earlier feature request, https://github.com/junegunn/fzf/issues/2478 ?

**Comment by NightMachinary** [comment]
@codethief Yes, I had forgotten that I had opened that issue :))
