### ISSUE TITLE
fzf ignores shebang `#!` when calling scripts?

### ISSUE THREAD

**Issue by joehillen** [junegunn/fzf#2627]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish
    - [x] MS cmd
    - [x] xonsh

## Problem / Steps to reproduce

I've built 2 Bash programs around fzf, [sysz](https://github.com/joehillen/sysz) and [paruz(https://github.com/joehillen/paruz).

They both have previews that call back on themselves:

https://github.com/joehillen/sysz/blob/master/sysz#L430
```bash
--bind "ctrl-v:preview('${BASH_SOURCE[0]}' _fzf_cat {})" 
```

https://github.com/joehillen/paruz/blob/52e2473e21f4b0b3815972cea324038d40cafa50/paruz#L86
```bash
--preview="'${BASH_SOURCE[0]}' __fzf_preview {1}"
```

They've both run into problems when running in an atypical shell, specifically these issues:

https://github.com/joehillen/paruz/pull/3
https://github.com/joehillen/sysz/issues/14

The problem is that fzf is somehow ignoring the shebang `#!` and running it with what is set in `SHELL`. I'm not sure how this is possible. Shouldn't fzf just be running it like a normal Unix program based on the shebang? 

The solution is to change the previews to `--preview="/usr/bin/env bash ${BASHSOURCE[0]} ...` or setting `SHELL` inside the script, but this shouldn't be necessary.

**Comment by vovcacik** [comment]
Yes, it does. I think the idea is that handling of shebang is offloaded to the shell.

https://github.com/junegunn/fzf/blob/179993f0cd79c6d1ec88981084ed04090e4f77f2/src/util/util_unix.go#L11-L18

**Comment by joehillen** [comment]
That's a weird choice. Why not just use [system()](https://man7.org/linux/man-pages/man3/system.3.html) like everything else. `SHELL` is used for knowing what the login shell is, not for running commands.

**Comment by aspieln3r** [comment]
I think its better to check availability of POSIX shells like bash or zsh separately and execute with them if the script expects a POSIX shell. In my case with using sysz, I got errors executing sysz as my $SHELL  was set to xonsh, which is not a POSIX shell.

**Comment by junegunn** [comment]
It has nothing to do with the shebang line.

```sh
cat > test.rb << EOF
#!/usr/bin/env ruby
puts 'Ruby script'
EOF
chmod +x test.rb

SHELL=/bin/bash            fzf --preview './test.rb' # Works
SHELL=/bin/zsh             fzf --preview './test.rb' # Works
SHELL=/bin/tcsh            fzf --preview './test.rb' # Works
SHELL=/usr/local/bin/fish  fzf --preview './test.rb' # Works
SHELL=/usr/local/bin/xonsh fzf --preview './test.rb' # Works
```

Most people use fzf in their favorite shell, most likely the login shell, and would expect fzf to be able to run some shell script in the syntax of their chosen shell, without having to repeat `mysh -c "..."` on every execute/reload/preview templates.

* https://github.com/junegunn/fzf/issues/481

So using `$SHELL` instead of `/bin/sh` makes it easier for the users to write scripts using fzf. I don't think this is an unusual design choice. Vim also uses `$SHELL` to run external commands.

```
						*'shell'* *'sh'* *E91*
'shell' 'sh'		string	(default $SHELL or "sh", Win32: "cmd.exe")
			global
	Name of the shell to use for ! and :! commands.
```

fzf implemented this behavior in 2016, so we won't change it and break user scripts all of a sudden.

I can see that this behavior can be problematic in certain scenarios like yours, but the behavior is already documented on the man page, and we have a trivial workaround.

https://github.com/junegunn/fzf/blob/2736a2f69e8e407bc3df38a43faab173f37e7c4c/man/man1/fzf.1#L934-L936

**Comment by joehillen** [comment]
@junegunn That you for the illustration. It turns out I was misattributing the bugs, which makes sense because ignoring shebang sounded completely crazy to me. The 2 bugs were semi-unrelated.

For the MSYS2 bug, Windows' `cmd` ignores shebang so that was breaking preview. 

For xonsh, it's that xonsh doesn't support single quotes so it was breaking [here](https://github.com/joehillen/sysz/blob/51da0ca012852ba02bcfc5dc1231b9b1fedcc3d9/sysz#L429) and not when the other previews call themselves.
```
      --bind "?:preview(echo '$(_sysz_keys)')" \
```

I'll just be sure to set `SHELL` from now on I'm my fzf interface scripts.

Thanks for your help and an awesome tool! :heart:

**Comment by qubidt** [comment]
@joehillen 

> That's a weird choice. Why not just use [system()](https://man7.org/linux/man-pages/man3/system.3.html) like everything else. `SHELL` is used for knowing what the login shell is, not for running commands. ExecCommand should be replaced with the body of ExecCommandWith without the shell argument. "shell" adds nothing but breakage.

This comment was very interesting to me. It led me to check POSIX standard. I learned that POSIX specifies:

> SHELL

> The SHELL variable names the preferred shell of the user; it is a guide to applications. There is no direct requirement that that shell conform to POSIX.1-2017; that decision should rest with the user. It is the intention of the standard developers that alternative shells be permitted, if the user chooses to develop or acquire one. An operating system that builds its shell into the "kernel" in such a manner that alternative shells would be impossible does not conform to the spirit of POSIX.1-2017.

The manpage for ex, for example, states:

> SHELL

> Determine the preferred command line interpreter for use as the default value of the shell edit option.

You can verify that both ex/vi/vim/nvim and less use `SHELL` for their respective `!` commands
