### ISSUE TITLE
Hide file scanning process

### ISSUE THREAD

**Issue by jamesgecko** [junegunn/fzf#263]
When I use FZF to open a file in NeoVim, there's a little X/9000 file scanning progress indicator at the bottom of the pane. It counts up very quickly whenever I open the pane, always completes before I can finish typing, and is kind of distracting. I'm certain I wouldn't care if I never saw it again.

Is there a way to disable it?

**Comment by junegunn** [comment]
> progress indicator at the bottom of the pane

Spinner at the bottem left, right? You could try dimming it down with `--color=spinner:<256 color ansi code>` option, see the man page for the details.

e.g. `(for i in $(seq 1000); do echo $i; sleep 0.1; done) | fzf --color=spinner:233`

**Comment by jamesgecko** [comment]
Excellent. I set the environment variable `FZF_DEFAULT_OPTS` to `--color=spinner:233,info:233`, and everything is gravy. Thank you!
