### ISSUE TITLE
Execute arbitrary command without leaving fzf

### ISSUE THREAD

**Issue by junegunn** [junegunn/fzf#265]
- Add `execute(...)` action for `--bind` option
- `{}` as the placeholder for the double-quoted string of the current item
```sh
fzf --bind "ctrl-m:execute(less {})"
fzf --bind "ctrl-t:execute(tmux new-window -d 'vim {}')"
```

**Comment by tiziano88** [comment]
Hey, this would be a super neat feature! Do you need help with this or do you have it implemented already?

**Comment by junegunn** [comment]
I already have prototype implementation, but there are still a few things to be sorted out.
- I'm not yet sure if `execute(...)` is the most pleasing syntax I can imagine :)
- What to do with `--multi`
    - Ignore `--multi` and just run the command for the current line only (I'm leaning towards this)
    - Execute the command multiple times for each selected line
    - Execute the command once with the selected lines concatenated (seems too complicated. separator?)
- The syntax works well for the simple commands like shown above, but it gets nasty when the user becomes too ambitious; commands with nested parens, unbalanced parens, commas, new lines ...
    - Just declare that as the limitation of the option and tell the users to write a wrapper script instead;
        - e.g. `execute(do-something.sh {})`

**Comment by junegunn** [comment]
Escaping issue can be greatly simplified if we allow different set of characters to surround command (a la `:s` of vim) 

- `execute(...)`
- `execute[...]`
- `execute/.../`
- `execute:...:`
- `execute;...;`
- `execute@...@`
- `execute~...~`
- `execute%...%`

**Comment by tiziano88** [comment]
Good questions; here are my personal thoughts:
 - What to do with `--multi`: just run the command for the current line only. For me the main use case of this feature is being in fzf in order to select one or more entries, and having to quickly do something different on one of the entries (e.g. delete history entry, look at the content of a file, etc.); if I am halfway a long multi-entry selection, I would definitely expect the "side action" to only apply to the element under the cursor. To be clear: this considers such actions "secondary" compared to the "primary" action which is the final output of fzf, and as such only the "primary" action can be affected by the `--multi` modifier.
 - Escaping: I don't have a good answer for this, but I think it would be easier to solve if key bindings must be specified as distinct arguments, e.g. `fzf --bind=ctrl-j:accept --bind=ctrl-k:kill-line --bind='ctrl-d:exec rm {}'` (which I believe could only possibly work here because you are parsing the arguments by hand, since otherwise normally only the last flag would be considered by the standard `flag` package -- but I may be wrong); this way you would basically just rely on normal shell string escaping and consume everything up to the end of the argument itself, and don't have to worry about inventing a new parallel syntax for sub-escaping.

**Comment by junegunn** [comment]
Thanks for the comment. I agree with what you said about `--multi` and this being "secondary" action.

>  I think it would be easier to solve if key bindings must be specified as distinct arguments

Yeah, it'll definitely make things much simpler, and I do hate having to come up with an arbitrary syntax, but I also don't like breaking backward compatibility and such limitation of the option may not look consistent with the other options that take comma-separated values.

I think I'm going to push the feature as described above as an experimental feature until I tag the next version. You can try it and give me some feedback. Thanks.

**Comment by junegunn** [comment]
A git commit browser:
```sh
  git log --graph --color=always \
      --format="%C(auto)%h%d %s %C(black)%C(bold)%cr" "$@" |
  fzf --ansi --no-sort --reverse --tiebreak=index --toggle-sort=\` \
      --bind 'ctrl-m:execute/
                echo {} | grep -o "[a-f0-9]\{7\}" |
                xargs -I % sh -c "git show --color=always % | less -R"
              /'
```

**Comment by tiziano88** [comment]
Note that you do not necessarily have to break backwards compatibility: AFAICT your option parser already supports both comma-separated options in the same argument (e.g. `fzf --bind=X,Y`) as well as multiple distinct argument for the same option (e.g. `fzf --bind=X --bind=Y`). My suggestion would be to enforce that each exec command needs to be specified in its own argument, and that the command to be executed extends until the end of the argument itself (following existing and well-known shell escaping rules). So for instance you could have `fzf --bind=X,Y --bind='exec Z'`, but not `fzf --bind=X,Y,exec Z` (which would produce an error instead). Note that backwards compatibility is preserved this way, and it would not be too hard to implement given that your option parser is already quite sophisticated (it would be much harder to do with the standard flag package alone).

**Comment by junegunn** [comment]
So it's not backward incompatible in the sense that it doesn't break any existing configuration since `execute` action is not publicly announced yet. I see your point. My viewpoint is that it's *kind of* backward incompatible since it changes the definition of `--bind` from
- comma-separated list of key:actions pairs
- to comma-separated list of key:actions pairs except for `execute` action which you have to write separately

So the users have to learn about the exception. `execute(...)` notation on the other hand is consistent and does not change the definition of `--bind`, but conversely, users have to learn about that syntax and its alternative notations for avoiding parse errors. In either way, no free lunch. But I'm leaning towards the latter since it feels more consistent especially if, although unlikely, we are going to add more actions with arguments in the future.

**Comment by tiziano88** [comment]
AFAICT the definition of `--bind` already supports both modes (comma-separated vs. separate args); if you wanted, you could gradually change the API to only support the latter, starting with `--bind` which should have to be on its own, and later on with other options too. The transition should not be too painful as long as you print a meaningful error message saying to separate the options in distinct arguments I think.
Also note that rolling your own escaping function may get really messy if shell variable substitution is added to the mix, e.g. `fzf --bind="ctrl-m:execute/somethingsomething$VAR/"` and `$VAR` contains `/`.

**Comment by junegunn** [comment]
> Also note that rolling your own escaping function may get really messy if shell variable substitution is added to the mix, e.g. fzf --bind="ctrl-m:execute/somethingsomething$VAR/" and $VAR contains /.

Yes, that's a valid point, but if the variable is exported, we can use single quotes since fzf internally executes the command with `sh -c`, so `VAR="..." fzf --bind='ctrl-m:execute/somethingsomething$VAR/'` will work regardless of the value of the variable. And if the expression gets really complicated we should probably tell the users to write an external script.

As I mentioned in the earlier comment, another point I like about parens notation is that it allows me to extend the existing actions to have optional arguments in a concise and consistent manner. For example, I prefer `--bind ctrl-j:accept,ctrl-f:page-down(3),ctrl-b:page-up(3)` over `--bind ctrl-j:accept,ctrl-f:page-down:3 --bind ctrl-b:page-up:3`

**Comment by junegunn** [comment]
We can also consider providing both methods, 1. concise parens notation, 2. and an alternative notation with which you don't have to worry about parse errors, something like `--bind ctrl-m:execute=COMMAND`

**Comment by junegunn** [comment]
Now this **also** works:

```sh
fshow() {
  git log --graph --color=always \
      --format="%C(auto)%h%d %s %C(black)%C(bold)%cr" "$@" |
  fzf --ansi --no-sort --reverse --tiebreak=index --toggle-sort=\` \
      --bind 'ctrl-m:execute:
                echo {} | grep -o "[a-f0-9]\{7\}" |
                xargs -I % sh -c "git show --color=always % | less -R"'
}
```

I'm thinking which one I like more

**Comment by balta2ar** [comment]
Speaking of `--multi`, here is my thought. You can add `execute-cursor` (or `execute-cursor-line`) action/binding to execute action on the current line only, and `execute-selected` action to execute the action on all the selected/marked lines. This way you leave it up to the user to decide which execute to use.

Another side and off-topic note, or rather a humble request is to keep the number of features in this wonderful piece of software under control. I really appreciate your work here and I absolutely can't live without fzf on a daily basis by now but at the same time I really don't want fzf to become too bloated and complicated. Thanks for the understanding.

**Comment by junegunn** [comment]
@balta2ar Thanks for your feedback. It's ironic that you're requesting another feature and at the same time expressing your concern on feature bloat :) But I also feel the same. Actually to my usual standard, fzf is already bloated. I'm thinking about hiding some exotic features from the `--help` output, having them only on man page, so that fzf feels simpler and friendlier to average users.

Regarding your idea on `execute-cursor`, it still leaves us with the question whether we should *also* support executing the command once for all selected items, e.g. `cat {} > concatenated`. Then why not `cat {2} {1} > {&}`, it's a rabbit hole of never-ending requirements. We should probably just keep it simple and not support it.

**Comment by balta2ar** [comment]
@junegunn I completely agree, this looks like the case where one can argue on the color of bike shed until the end of times. What comes into my mind is `man find`, specifically `-exec` option which supports both exec per one result and exec once with all results.

**Comment by wimstockman** [comment]
Why do you make it so complex  on my prompt in bash:  $(cat ~/.bash_history | sort | uniq | fzf)
if you use the $( it execute the return value of fzf no need to program it
