### ISSUE TITLE
Fzf keybind issue

### ISSUE THREAD

**Issue by RaZ0rr-Two** [junegunn/fzf#2650]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

## Problem / Steps to reproduce

I have the following keybind in fzf.bash

```
sff() {
  fdfind . $HOME --type f --color=never --hidden --follow --exclude .git --exclude node_modules |
  fzf-tmux -m --preview 'bat --color=always --line-range :100 {}' ${previewFzfFile[@]} --bind 'f2:execute(xdg-open {} 2> /dev/null &),ctrl-space:toggle-preview' --height=80% --layout=reverse "$@" | while read -r item; do 
		printf '%q ' "$item"
  done
	echo
}

sffw() {
  local selected="$(sff)"
  READLINE_LINE="${READLINE_LINE:0:$READLINE_POINT}$selected${READLINE_LINE:$READLINE_POINT}"
  READLINE_POINT=$(( READLINE_POINT + ${#selected} ))
}
bind -m emacs-standard -x '"FileSearch": fzf-file-widget'
bind -m emacs-standard '"\C-t": "FileSearch"'
bind -m emacs-standard -x '"HomeFileSearch": sffw'
bind -m emacs-standard '"\C-t\C-t": "HomeFileSearch"'
```

This keybinding disables my "\C-r" keybind with a :

`bash: bash_execute_unix_command: cannot find keymap for command`

However, the keybinding works when I change the 'C' in '\C-t' to lower case :

`bind -m emacs-standard '"\C-t": "FileSearch"'` 
                      
                         to

`bind -m emacs-standard '"\c-t": "FileSearch"'`

**Comment by rayiik** [comment]
Hey just a question, i see this is closed did you find your answer? if yes could you kindly post it so others having similar issue might be able to find the answer that worked for you so they can know if they need to open a new ticket or not :) thanks much appreciated. If you didnt find an answer and just decided to keep the ctrl-t binding then i suspect that something in your config files is getting sourced after this script which also uses the C-r and over writing that binding :) cheers.

**Comment by RaZ0rr-Two** [comment]
I never found an answer for this. This seems like a distro specific issue because I had it in MX Linux, Mint but not in Pop!_os.

As of now, I don't have any issue in Mint with the following

```
bind -m emacs-standard -x '"__FileSearch__": fzf-file-widget'
bind -m emacs-standard '"\C-t": "__FileSearch__"'
bind -x '"__HomeFileSearch__":"__sffw__"'
bind '"\C-t\C-t":"__HomeFileSearch__"'
```
The `-m emacs-standard` part might be unneccessary. For anyone else having this issue in the future, try out the following commands ( if in bash ) and figure out if there's any conficts first.
```

bind -p | fzf
bind -X | fzf
```

**Comment by shmerl** [comment]
Looks like Ctrl+t is broken in Ubuntu Jammy with the same error:

```
-bash: bash_execute_unix_command: cannot find keymap for comman
```

Ctrl+r works.
