### ISSUE TITLE
feature request: default text

### ISSUE THREAD

**Issue by UltiRequiem** [junegunn/fzf#2655]
I would like to be able to give it as an argument text that I should put as user input.

Something like:

```bash
ls | fzf --default "default"
```

![image](https://user-images.githubusercontent.com/71897736/141151592-b3fe1bca-333f-4ea7-89fa-311d094023f6.png)

**Comment by vovcacik** [comment]
You can set default query string for the fuzzy searcher with: <code>ls | fzf [--query][] "default"</code>.

[--query]: https://manpages.debian.org/unstable/fzf/fzf.1.en.html#Scripting

**Comment by UltiRequiem** [comment]
Thanks!
