### ISSUE TITLE
Jump from one end of the list to the other.

### ISSUE THREAD

**Issue by uvaes** [junegunn/fzf#266]
Hi! 

First, thank you for this program, it work really well! I was wondering if there was an option to go from the last match to the fist one and conversely? (a kind of circular list, to have a behaviour similar to vim autocompletion).  I noticed that CtrlP does not have that feature either, but I do think that it would be useful in some situations. Any thoughts?

**Comment by junegunn** [comment]
Thanks for the suggestion. I'm a bit worried about feature-bloat these day, too many options already, but I can see the appeal and it's kind of trivial to implement, so I'll add `--cycle` option.

**Comment by uvaes** [comment]
Awesome! That was fast!
