### ISSUE TITLE
Adding support for more readline keybindings : Support for Alt+Minus Control+k

### ISSUE THREAD

**Issue by edi9999** [junegunn/fzf#2660]
- [x] I have read through the manual page (`man fzf`)
- [ x I have the latest version of fzf
- [x]I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

## Problem / Steps to reproduce

I know you're not much into adding n features to fzf which are probably difficult to maintain all at the same time, so feel free to close if you think this will cost more than it will benefit.

In bash, when I have a long command, like this : 

```
ls -lah [] foobar --optiona --optionb
```

And `[]` denotes cursor position, when I want to drop the beginning to have : 

```
foobar --optiona --optionb
```

I hit : `Alt-Minus`, `Ctrl-k`, which will basically kill the whole line before the cursor. This is a bit faster than having to press backspace for a long time basically.

I would like to have the same behavior in fzf :)

At some point it would make sense to have some sort of readline library instead of coding this, maybe something like this : https://github.com/chzyer/readline

**Comment by edi9999** [comment]
As far as I know, `Alt+5` is a way to tell that the next command should be repeated 5 times.

For example, hitting `Alt+5` and then `a` will enter "aaaaa".

Or `Alt-2` and then `Ctrl-w` will kill 2 words.

`Alt-Minus` will do the opposite of the command.

**Comment by junegunn** [comment]
I'm not familiar with `ALT-minus` stuff, but is it any different from `CTRL-U` (`unix-line-discard`)? Am I missing something?

**Comment by edi9999** [comment]
Lol ok just learnt that ctrl-u exists, didn't know about that ...

Ok, I personally don't have the need for Alt-digit stuff then, I'm closing this then.
