### ISSUE TITLE
Add winget support

### ISSUE THREAD

**Issue by satvikpendem** [junegunn/fzf#2661]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [ ] Mac OS X
    - [x] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [ ] fish

## Problem / Steps to reproduce

Consider adding fzf to `winget` as that's the official Windows package manager now.

**Comment by sitiom** [comment]
Winget 1.4 now supports zip installation. PR:

- https://github.com/microsoft/winget-pkgs/pull/94701

After that, [Winget Releaser](https://github.com/vedantmgoyal2009/winget-releaser) has to be set up in this repo to automatically push manifest updates. @junegunn Are you willing to accept my PR for it?
