### ISSUE TITLE
Feature Request: Ability to Default Multi Items to Selected

### ISSUE THREAD

**Issue by hlipnick** [junegunn/fzf#2663]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

## Problem / Steps to reproduce
This is less a problem than a feature request.  I'd like to be able to specify certain (or all) items of the input to default to being 'checked' or selected when in multi mode.  Perhaps a regex run on each line of input to determine if it should be checked?  So could be lines starting with a 1 start as checked?

My apologies if there is already some way to achieve this but I was not able to determine how to do so by reading through the manual and other issues.

**Comment by vovcacik** [comment]
Duplicate #395, but I think there are more recent issues, where you might find junegunn's stance on this issue.

**Comment by junegunn** [comment]
No plan to support regex-based solution. But with the latest version of fzf, you can try using `start` or `load` event to perform actions to select the entries you want.

https://github.com/junegunn/fzf/issues/3548#issuecomment-1868433219

If writing down the list of actions is not feasible, you can perhaps write a script that performs multiple actions via HTTP server (`--listen`).
