### ISSUE TITLE
question: wait for input in (neo)vim plugin

### ISSUE THREAD

**Issue by p00f** [junegunn/fzf#2664]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [x] fish

## Problem / Steps to reproduce

When I call fzf#run it immediately forks and the main execution continues without waiting for user input. Is it possible to block until the user has made a choice?

**Comment by RaZ0rr-Two** [comment]
Isn't this better asked in the plugin repository [issues](https://github.com/junegunn/fzf.vim/issues)?

**Comment by junegunn** [comment]
@RaZ0rr-Two This repository provides `fzf#run`, so this is the right place to ask.

Having said that, I don't understand the question. It is not clear what you mean by `fork` and `main execution`? You should probably provide some code snippets or screenshots.

**Comment by p00f** [comment]
My vimscript isn't that great, please bear with me
```vim
let foo = 0
call fzf#run({'source' : {1,2,3} 'sink':{d->foo=d})
echo too " immediately echoes 0 without waiting for choice
```

**Comment by p00f** [comment]
fwiw I figured out how to do what I wanted, still nice to know how to block for simple tasks

**Comment by junegunn** [comment]
I see. fzf runs in a terminal buffer of Vim thus it is not possible to block the execution of Vimscript, which would block single-threaded Vim altogether. You have to reorganize your code so that the execution resumes in the sink callback function.

**Comment by p00f** [comment]
I see, thanks!
