### ISSUE TITLE
make _fzf_complete_COMMAND work for aliases of COMMAND

### ISSUE THREAD

**Issue by svenXY** [junegunn/fzf#2669]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

## Problem / Steps to reproduce

I'm trying to add _fzf_complete_COMMAND for timew (timewarrior), which works fine. 
Now I have a few aliases defined that spare me from typing "timew command" all the time (twa, twc, two and the like)

Following your suggestion in #1368, I could write functions for every  of these aliases and make them use the one for timew, but I wonder if there's a better option.

Is there any possibility to first expand the alias and then apply the completion function?

Thanks,
Sven

**Comment by junegunn** [comment]
Thanks for the suggestion. I guess it's possible, but I'm not going to implement it here, because of the added complexity and because it's unclear if the behavior is always desirable.

>  I could write functions for every of these aliases and make them use the one for timew, but I wonder if there's a better option.

Maybe you could write an `alias` wrapper that defines the alias AND the completion function for the alias.

```sh
alias_for_fzf 'twa' 'timewarriror something'
```
