### ISSUE TITLE
match pattern more than once

### ISSUE THREAD

**Issue by lucas-mior** [junegunn/fzf#2670]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

## Problem / Steps to reproduce

Currently FZF only matches a pattern a single time,
and if it is repeated on the list item, it will simply ignore,
making it hard to select a specific entry sometimes:
For instance, let's say I'm trying to select `Master of Puppets.flac`:

```
> masterofpupp
  8/8305
> musicas/Metallica/1986 - Master Of Puppets/Orion.flac
  musicas/Metallica/1986 - Master Of Puppets/Battery.flac
  musicas/Metallica/1986 - Master Of Puppets/Damage, Inc..flac
  musicas/Metallica/1986 - Master Of Puppets/Leper Messiah.flac
  musicas/Metallica/1986 - Master Of Puppets/Disposable Heroes.flac
  musicas/Metallica/1986 - Master Of Puppets/Master Of Puppets.flac
  musicas/Metallica/1986 - Master Of Puppets/Welcome Home (Sanitarium)...
  musicas/Metallica/1986 - Master Of Puppets/The Thing That Should Not ..
```

I would like if fzf would, in such case, select the one that has more matches,
which would be `Master of Puppets.flac` not `Orion.flac`

**Comment by junegunn** [comment]
You can append `.` at the end to get better ordering in this case. i.e. `masterofpupp.`

**Comment by lucas-mior** [comment]
The `/` aproach did prove to be what I needed.
Thanks.
