### ISSUE TITLE
Buffering of lines when using rg not displaying correctly

### ISSUE THREAD

**Issue by FilipeBento** [junegunn/fzf#2675]
- [X] I have read through the manual page (`man fzf`)
- [X] I have the latest version of fzf
- [ ] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [ ] Mac OS X
    - [X] Windows WSL2 (Ubuntu)
    - [ ] Etc.
- Shell
    - [X] bash
    - [ ] zsh
    - [ ] fish

## Problem / Steps to reproduce

https://capture.dropbox.com/gbefaS1G4DNzBi4S

I recorded the above to better show what exactly is happening in my screen. I don't know exactly if the issue is in my configurations or if it is an fzf problem.

Thank you in advance for your time. (Apologies if the issue is on my side. Let me know if you have Patreon.)

**Comment by junegunn** [comment]
The link is dead.

**Comment by FilipeBento** [comment]
Problem solved on my side. Apologies for the work caused. Merry Christmas!
