### ISSUE TITLE
slash is replaced with "C:/msys64" on MSYS2

### ISSUE THREAD

**Issue by Aloxaf** [junegunn/fzf#2680]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [ ] Mac OS X
    - [x] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

## Problem / Steps to reproduce

1. Install msys2
2. Install fzf according to https://github.com/junegunn/fzf#using-git
3. run `fzf /`

![image](https://user-images.githubusercontent.com/17017672/144796578-aa443db3-57ec-4391-b054-122968b136d7.png)

**Comment by junegunn** [comment]
Doesn't sound like an issue of fzf. What happens when you run `echo /`?

**Comment by junegunn** [comment]
How about `fzf --expect='/'`?

**Comment by Aloxaf** [comment]
@junegunn 


![image](https://user-images.githubusercontent.com/17017672/144812892-e13f2156-0cbe-44b7-b84e-9772d1f7fdd4.png)


This happens not only in zsh, but also bash and fish. So I think this may be a bug of fzf.

![image](https://user-images.githubusercontent.com/17017672/144813176-8b6fa150-2b6a-4bc5-9d3e-3e61131ccb42.png)

**Comment by Aloxaf** [comment]
more tests:

![image](https://user-images.githubusercontent.com/17017672/144813670-4aa0f5b4-6b16-44c0-bebd-a91c6708775e.png)

**Comment by junegunn** [comment]
Unlikely. fzf doesn't have any code that replaces given arguments.

* https://github.com/junegunn/fzf/blob/ce9af687bcc58b2005c5d3f92bbaa08e77755bb8/main.go#L13
* https://github.com/junegunn/fzf/blob/ce9af687bcc58b2005c5d3f92bbaa08e77755bb8/src/options.go#L1730
* https://github.com/junegunn/fzf/blob/ce9af687bcc58b2005c5d3f92bbaa08e77755bb8/src/options.go#L1283-L1284
* https://github.com/junegunn/fzf/blob/ce9af687bcc58b2005c5d3f92bbaa08e77755bb8/src/options.go#L1583

**Comment by Aloxaf** [comment]
Oh sorry, it's a bug of msys2
