### ISSUE TITLE
Action on startup or (Event: Startup)

### ISSUE THREAD

**Issue by fedoranvar** [junegunn/fzf#2684]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

Good day to you!

Is it possible to launch fzf with action on start up (for example, `jump`) ?

Maybe with event `startup` (if it exist) ?

`fzf --bind startup:jump`

Thank you!

**Comment by fedoranvar** [comment]
Currently found a workaround with `xdotool` or `wtype` (wayland):

```bash
wtype -s 100 ';' &; fzf
```

In my case, i've mapped `;` for`jump`-action

**Comment by junegunn** [comment]
I've considered this and I have a prototype implementation of the idea locally, but it turns out that there are a number of issues that are tricky to get right, mostly due to the asynchronous nature of fzf. I might revisit the idea in the future.
