### ISSUE TITLE
fzf-vim feature: navigate git root of the current tab's file path

### ISSUE THREAD

**Issue by ddevault** [junegunn/fzf#2687]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [ ] fish
    - [x] ash

## Problem / Steps to reproduce

I migrated from Ctrl-P to FZF, and I'm missing one feature in particular. I often work with several projects at once in the same vim process, opening files in `../other-project/...` in new tabs. When I hit my FZF binding, I would like it to find the root of the git repository within which the current tab or buffer's file resides, so that I can navigate appropriately for each project I'm working on at the same time.

**Comment by DevAtDawn** [comment]
@ddevault heres how you can implement this/my code:
```
function! Githubroot()
    " let path = system('pwd | tr -d "\n"') 
    let path = system('git rev-parse --show-toplevel | tr -d "\n"') 
    " echo path
    execute 'FZF ' . path
endfunction
command! Ghroot call Githubroot()
nnoremap <Leader><Leader>Fg :Ghroot<CR>

```

**Comment by ddevault** [comment]
That does not do exactly what I'm looking for, but thank you for sharing.

**Comment by DevAtDawn** [comment]
> That does not do exactly what I'm looking for, but thank you for sharing.

this "finds the root of the git repository within which the current tab or buffer's file resides" using `git rev-parse --show-toplevel` and then calls :FZF with the correct path

example: im editing setup.sh in ../public_dotfiles/root/ubuntu/setup.sh, the git root dir is ../public_dotfiles, so the cmd starts fzf at that folder

![image](https://user-images.githubusercontent.com/86164137/163050256-f8e2224f-c51c-4166-8fbd-6300a1db78b8.png)

what were you looking for? If you could give me a few more details im sure the code can be adjusted to do exactly what you want @ddevault

**Comment by ddevault** [comment]
>When I hit my FZF binding, I would like it to find the root of the git repository within which the current tab or buffer's file resides, so that I can navigate appropriately for each project I'm working on at the same time.

The key is to find the git repository not in vim's current working directory, but within which the current tab or buffer resides. I often reach out to open files outside of the current git repository, which are themselves in a *second* git repository, and want FZF rooted in this second repo.

**Comment by char101** [comment]
If you set `autochdir`, that commands above should work because vim current directory == current file directory.

**Comment by ddevault** [comment]
That doesn't exactly do what I want, either, I'm afraid: I don't want vim's entire cwd to be changed, especially because it would be relative to the current file's directory - not the git root.

**Comment by char101** [comment]
You can also modify the commands above to cd to the current file directory first:
```viml
function! Githubroot()
    let path = trim(system('cd '.shellescape(expand('%:p:h')).' && git rev-parse --show-toplevel'))
    exe 'FZF ' . path
endfunction
command! Ghroot call Githubroot()
nnoremap <Leader><Leader>Fg :Ghroot<CR>
```

**Comment by ddevault** [comment]
Works, thanks! Though I adjusted it to account for the fact that GitHub is not the same thing as Git, which you might do well to remember yourself.

```
function! GitFZF()
    let path = trim(system('cd '.shellescape(expand('%:p:h')).' && git rev-parse --show-toplevel'))
    exe 'FZF ' . path
endfunction
command! GitFZF call GitFZF()
nnoremap <C-p> :GitFZF<CR>
```

Cheers!

**Comment by camoz** [comment]
Btw this fails (in an ugly way) if there is no upper-level git root directory.

Not sure if this is the correct way to handle the error (I don´t really know vimscript), but I have modified it to:

```vim
function GitFZF()
	let path = trim(system('cd ' . shellescape(expand('%:p:h')) . ' && git rev-parse --show-toplevel'))
	if v:shell_error == 0
		exe 'FZF ' . path
	else
		echohl ErrorMsg
		echomsg "Error: Not in a git directory."
		echohl None
	endif
endfunction
```

Alternatively, in the else-block, you can just do `echo(path)` to print the error message from git verbatim. Kind of ugly but works.

**Comment by char101** [comment]
You can also use `isdirectory()`.

```viml
function! GitFZF()
  let path = trim(system('cd '.shellescape(expand('%:p:h')).' && git rev-parse --show-toplevel'))
  if !isdirectory(path)
    let path = expand('%:p:h')
  endif
  exe 'FZF ' . path
endfunction

command! GitFZF call GitFZF()
nnoremap <C-p> :GitFZF<CR>
```
