### ISSUE TITLE
NeoBundle command to manage fzf ?

### ISSUE THREAD

**Issue by collegeimprovements** [junegunn/fzf#269]
How can I manage this setting with Neobundle ? Is there any way for this to handle the following setting via NeoBundle ?
```
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': 'yes \| ./install' }
```

**Comment by junegunn** [comment]
I don't use NeoBundle so I have no idea. But it should be definitely possible. I believe the manual page of it should have enough information for you.

**Comment by collegeimprovements** [comment]
Thanks. I'll find it out.
I have one more question. Can we toggle(enable/disable) fzf from zsh?
Sometimes I find zsh-tab-completion more intuitive. Is there anyway to do so ?

**Comment by junegunn** [comment]
What do you mean? fzf does not override tab completion.

**Comment by collegeimprovements** [comment]
No. No. 
fzf is working as expected and it's super awesome. I'm just wondering if there is a way to disable it and reenable it with some command!

**Comment by junegunn** [comment]
You mean you want to toggle between the default tab completion of zsh and fuzzy completion of fzf that doesn't require trigger sequence (`**`) ? I haven't tried, but I don't think it'd be impossible. But I think it's better to just assign a dedicated key for fuzzy completion (w/o trigger sequence) as described in the following link.
https://github.com/junegunn/fzf/wiki/Fuzzy-completion#dedicated-completion-key

**Comment by collegeimprovements** [comment]
Thanks :)
