### ISSUE TITLE
Bad rendering of long queries with `--info=inline`

### ISSUE THREAD

**Issue by ibhagwan** [junegunn/fzf#2692]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

## Problem / Steps to reproduce

If you input a very long query (longer than available columns) with `--info=inline` you get the below rendering error (does not happen with `--info=default`):

![screenshot-1640053390](https://user-images.githubusercontent.com/59988195/146880308-a7561e3e-3e05-4fad-8833-acacc4f566aa.png)

**Comment by junegunn** [comment]
3f75a83

**Comment by ibhagwan** [comment]
> [3f75a83](https://github.com/junegunn/fzf/commit/3f75a8369f63f2bd6ac3686fc5d88f2bc128e610)

I just tested with `0.28.0 (e4c3ecc)` - was this commit supposed to fix this and is included in `0.28`?

**Comment by junegunn** [comment]
No, that's an old commit that introduced this regression. I left the comment for the refrerence.

**Comment by ibhagwan** [comment]
Tysm for the quick response!

FYI, I absolutely love `fzf` and depend on it for my daily activity, so much that I wrote [`fzf-lua`](https://github.com/ibhagwan/fzf-lua), the `fzf.vim` equivalent for neovim>0.5 in lua, check it out if you haven't :-)

This issue was reported by a user of my plugin: https://github.com/ibhagwan/fzf-lua/issues/271

**Comment by junegunn** [comment]
Thanks for the report. It should be fixed now. I'll release 0.28.0 in a few days.

> I wrote [`fzf-lua`](https://github.com/ibhagwan/fzf-lua)

Cool, keep up the good work!
