### ISSUE TITLE
zsh key bindings should work for `vicmd` and `viins` keymaps

### ISSUE THREAD

**Issue by mcornella** [junegunn/fzf#2694]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

## Problem / Steps to reproduce

When fzf is loaded before changing the binding keymap, the bindings aren't set up for the new keymap, so it doesn't work.

1. Load `key-bindings.zsh`
2. Change keymap to `viins`: `bindkey -v`
3. Bindings don't work.

----
[`key-bindings.zsh`](https://github.com/junegunn/fzf/blob/dc975e8974c4f569980676d9f605226368e20711/shell/key-bindings.zsh) only runs `bindkey` for the existing keymap, so if the keymap changes, the previous bindings aren't preserved. Instead, `bindkey` should be called for the keymaps: `emacs`, `vicmd` and `viins`. #2035 is possibly the reason for this bug.

As an example, for [CTRL-R](https://github.com/junegunn/fzf/blob/dc975e8974c4f569980676d9f605226368e20711/shell/key-bindings.zsh#L109):

Instead of doing
```zsh
bindkey '^R' fzf-history-widget
```
it should be done like
```zsh
bindkey -M emacs '^R' fzf-history-widget
bindkey -M vicmd '^R' fzf-history-widget
bindkey -M viins '^R' fzf-history-widget
```

And the same for the other 2 bindkey commands in the file.

Related: https://github.com/ohmyzsh/ohmyzsh/issues/10533

**Comment by junegunn** [comment]
Thanks for the pointer. Does this look good to you?
```diff
diff --git a/shell/key-bindings.zsh b/shell/key-bindings.zsh
index 72d66f5..141ed05 100644
--- a/shell/key-bindings.zsh
+++ b/shell/key-bindings.zsh
@@ -66,7 +66,9 @@ fzf-file-widget() {
   return $ret
 }
 zle     -N   fzf-file-widget
-bindkey '^T' fzf-file-widget
+bindkey -M emacs '^T' fzf-file-widget
+bindkey -M vicmd '^T' fzf-file-widget
+bindkey -M viins '^T' fzf-file-widget
 
 # ALT-C - cd into the selected directory
 fzf-cd-widget() {
@@ -87,7 +89,9 @@ fzf-cd-widget() {
   return $ret
 }
 zle     -N    fzf-cd-widget
-bindkey '\ec' fzf-cd-widget
+bindkey -M emacs '\ec' fzf-cd-widget
+bindkey -M vicmd '\ec' fzf-cd-widget
+bindkey -M viins '\ec' fzf-cd-widget
 
 # CTRL-R - Paste the selected command from history into the command line
 fzf-history-widget() {
@@ -106,7 +110,9 @@ fzf-history-widget() {
   return $ret
 }
 zle     -N   fzf-history-widget
-bindkey '^R' fzf-history-widget
+bindkey -M emacs '^R' fzf-history-widget
+bindkey -M vicmd '^R' fzf-history-widget
+bindkey -M viins '^R' fzf-history-widget
 
 } always {
   eval $__fzf_key_bindings_options
```

**Comment by mcornella** [comment]
That looks good yes, provided those are the only key bindings I think that would be enough.
