### ISSUE TITLE
FD integration relative path prefix

### ISSUE THREAD

**Issue by run2cmd** [junegunn/fzf#2698]
- [X] I have read through the manual page (`man fzf`)
- [X] I have the latest version of fzf
- [X] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [ ] Mac OS X
    - [X] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [ ] fish
    - [X] cmd

## Problem / Steps to reproduce

I'm getting `.\` prefix for all files when when using `fd` command for searching files. When using with VIM this might cause some of my plugins do not work as the path contains `.\` prefix in it and looks like this:  `c:\code\project\.\src\file.js`

Here is an example with Windows `dir` command and `fd` command. Take a look as the 1st one does not have `\.` prefix but with `fd` it does.

![fzf_fd_test](https://user-images.githubusercontent.com/9575150/147649734-22de5b07-72c0-4c53-901c-c3f29a366732.gif)

**Comment by junegunn** [comment]
fzf simply reads the output of fd. You should ask this to the maintainers of fd.

**Comment by charego** [comment]
This appears to be the default behavior since [fd v8.3.0](https://github.com/sharkdp/fd/releases/tag/v8.3.0):

> Always show the `./` prefix for search results unless the output is a TTY or `--strip-cwd-prefix` is set, see [#760](https://github.com/sharkdp/fd/issues/760) and [#861](https://github.com/sharkdp/fd/pull/861) (@jcaplan)

**Comment by run2cmd** [comment]
@charego this solved my issues. Thanks.
