### ISSUE TITLE
zle widget not working after fzf update

### ISSUE THREAD

**Issue by drewauff** [junegunn/fzf#2699]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

I cobbled together this zle widget and it worked perfectly until the recent fzf update (via Homebrew), now all it does
is open my editor (Micro Editor) with a blank/new file.

```sh
fzf-foe-widget() {

    IFS=$'\n' \
    out=("(ls -al \
    | grep '^-' \
    | awk '{print $9}' \
    | fzf \
        --border=none \
        --tac \
        --layout=default \
        --height=40% \
        --min-height=5 \
        --ansi \
        --query="$1" \
        --exit-0 \
        --expect=ctrl-r,ctrl-e)")
        
        key=$(head -1 <<< "$out")
        file=$(head -2 <<< "$out" | tail -1)
    if [ -n "$file" ]; then
        [ "$key" = ctrl-r ] && micro -readonly true "$file" || ${EDITOR:-micro} "$file"
    fi
zle reset-prompt
}
zle -N fzf-foe-widget
bindkey '\e[15~\e[15~' "fzf-foe-widget"
```

**Comment by drewauff** [comment]
Essentially that block of code has not changed in months, so if its not the code then the only reasonable deduction that remains is that is must be a bug in the fzf update.

**Comment by junegunn** [comment]
Fixed the formatting of the code.

The code doesn't look correct. Command substitution for fzf is missing. You're simply assigning the command string to `$out`.

```sh
out=("(ls -al | fzf)")

# vs.
out=("$(ls -al | fzf)")
```

**Comment by drewauff** [comment]
Thank you! 👍🏽
