### ISSUE TITLE
fzf-tmux session get stuck on tmux 3

### ISSUE THREAD

**Issue by mrdotb** [junegunn/fzf#2702]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

## Problem / Steps to reproduce
With tmux version >= 3 run
```
ctrl-b # or your custom tmux prefix
:run fzf-tmux
# tmux session get stuck until we kill process linked to fzf-tmux
```
On tmux version 2.9 the above work find.

https://user-images.githubusercontent.com/7212914/148109524-628b5de6-7c7f-4274-b620-4b9861282341.mp4

**Comment by junegunn** [comment]
See https://github.com/junegunn/fzf/issues/1841#issuecomment-580975759

You need to put `-b` since tmux 3.

**Comment by mrdotb** [comment]
Sorry I miss it searching with `stuck` instead of `lock` don't give any results.
Thanks again for fzf :+1:
