### ISSUE TITLE
Installing fzf keybindings for fish deletes fish user functions

### ISSUE THREAD

**Issue by adammarples** [junegunn/fzf#2703]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [x] fish

## Problem / Steps to reproduce

Following this prompt from brew
```bash
To install useful keybindings and fuzzy completion:
  /opt/homebrew/opt/fzf/install
```

Running the install script has deleted one of my fish functions files 

```bash
 ~  /opt/homebrew/opt/fzf/install                                                                                                                                                     8.4m  Wed  5 Jan 12:00:16 2022
Downloading bin/fzf ...
  - Already exists
  - Checking fzf executable ... 0.29.0
Do you want to enable fuzzy auto-completion? ([y]/n) y
Do you want to enable key bindings? ([y]/n) y

Generate /Users/adammarples/.fzf.bash ... OK
Generate /Users/adammarples/.fzf.zsh ... OK
Update fish_user_paths ... Failed
Remove unnecessary /Users/adammarples/.config/fish/functions/fzf.fish ... OK
Symlink /Users/adammarples/.config/fish/functions/fzf_key_bindings.fish ... OK
```

Now my fzf specific fish functions `/Users/adammarples/.config/fish/functions/fzf.fish` have just been deleted because fzf deemed then "unnecessary".

**Comment by junegunn** [comment]
Well, that's unfortunate. It's a very old code (3935aa84d8cc66c0371926c61afe89832f00df10) that was for cleaning up the file that the previous versions of the installer had created. Almost 7 years have passed, and we should get rid of it.

**Comment by junegunn** [comment]
Fixed on master. Thanks for the report.

FYI, you can install the latest version on master branch with `brew install --HEAD fzf`.

**Comment by adammarples** [comment]
Thank you very much
