### ISSUE TITLE
nerd font icon as pointer character

### ISSUE THREAD

**Issue by dripware** [junegunn/fzf#2709]
- [ x] I have read through the manual page (`man fzf`)
- [ x] I have the latest version of fzf
- [ x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

## Problem / Steps to reproduce
it seems like it is not possible to put a nerd font icons (``) as the pointer character in fzf
`fzf --pointer=''`
it gives this error:
`invalid character in pointer `

**Comment by kiran94** [comment]
There seems to be an intentional check in the source to prevent this:

- https://github.com/junegunn/fzf/blob/d56f605b6338842b415ac1ff578f4316455815fe/src/options.go#L1658-L1660
- https://pkg.go.dev/unicode#IsGraphic

Although I'm not really sure why. Maybe compatibility on certain platforms?
