### ISSUE TITLE
vim: `:Ag` does not respect `.agignore` or `ignore`

### ISSUE THREAD

**Issue by Ran4** [junegunn/fzf#2713]
- [X] I have read through the manual page (`man fzf`)
- [X] I have the latest version of fzf
- [X] I have searched through the existing issues

## Info

- OS
    - [X] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [ ] fish

## Problem / Steps to reproduce

1. Open vim, with a path that contains another folder with a file whose filename is also in a `.agignore` or `.ignore` file
2. Type `:Ag<cr>` and start typing the contents of that other file
3. Expected: Nothing is shown, since the file should be ignored due to it being in the `.agignore` or `.ignore` file. What actually happens: the contents are shown - the agignore/ignore file is not used. https://github.com/junegunn/fzf/blob/master/README-VIM.md doesn't mention these files or how to ignore specific files.

**Comment by junegunn** [comment]
Works for me. Please note that `.agignore` should be in your $HOME directory as mentioned in `man ag`

> Finally, ag looks in $HOME/.agignore for ignore patterns
