### ISSUE TITLE
Disable non-triggered 'kill' completion?

### ISSUE THREAD

**Issue by cpakkala** [junegunn/fzf#2716]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

## Problem / Steps to reproduce
The kill command is treated differently than all other completions in that it is triggered whether $FZF_COMPLETION_TRIGGER has been used or not.  I propose this no longer be the case (or at least be optional), as it's inconsistent with all other commands (which require the trigger) and conflicts with normal shell completion mechanisms.  In particular, I'm using Aloxaf's fzf-tab which integrates fzf with z shell's compsys completion engine.  It does not conflict with the fzf-completion widget, as long as  $FZF_COMPLETION_TRIGGER is not set to the empty string, with the one exception of the kill command.  I am unable to prevent fzf-completion from triggering the kill completion, so that compsys/fzf-tab can handle it's completion instead.  Looking at the widget code, there seems to be no way to disable the behavior without changing the widget itself.

**Comment by junegunn** [comment]
Related: https://github.com/junegunn/fzf/issues/385

**Comment by rayiik** [comment]
not a great solution and not sure if it will work with your use case but 
```bash
killvar=kill
alias kill=$killvar
kill -9 [tab] 
#shows default (directory) list
```
but might also maie what your trying to trigger missfire

**Comment by rayiik** [comment]
correction l calling $killvar works but kill even aliased ti a variable calling kill triggers

**Comment by Galicarnax** [comment]
Any chance of providing an option, or a code snippet to be placed into `zshrc`, to allow using `kill` without the `**` trigger as before (with `zsh`)?

**Comment by RouNNdeL** [comment]
Yea, I relied on this quite a lot, it was a bit faster then having to type `**`. Would love to see an option to choose either approach.

**Comment by cpakkala** [comment]
Everyone still asking for the easier trigger:
You realize you can still just set FZF_COMPLETION_TRIGGER="", right?

The point of the change was to make the behavior consistent for all commands; there should be nothing special about "kill"...
