### ISSUE TITLE
toggle whether to show hidden files on the fly

### ISSUE THREAD

**Issue by Martinits** [junegunn/fzf#2717]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

## Problem / Steps to reproduce

How can I toggle between show hidden files and not show hidden files on the fly?
I know I can set whether to show them in FZF_DEFAULT_COMMAND using `--hidden` flag (for `fd`)
But I think to toggle this on the fly is more useful.

**Comment by junegunn** [comment]
You can set up `reload` bindings to update the input list dynamically.

See https://github.com/junegunn/fzf/blob/master/ADVANCED.md#dynamic-reloading-of-the-list
