### ISSUE TITLE
Removing first column of the history.

### ISSUE THREAD

**Issue by pablospe** [junegunn/fzf#2722]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

## Problem / Steps to reproduce

Let's say we have a history of three commands:
```
> a
> b
> c
```
if you run `history` you will see:
```
 1  a
 2  b
 3  c
```
I would like to avoid seeing the first column when I do `Ctrl+R`. Basically doing:
    `history | awk '{$1="";$0=$0;$1=$1}1' FPAT='[^ ]+' OFS=' '`
somewhere in `__fzf_history__`. But I didn't manage to get it right.

Any ideas?

**Comment by pablospe** [comment]
For zsh, it is possible to use:

   > fc -ln 0

instead of `history | awk ...`

**Comment by junegunn** [comment]
```
export FZF_CTRL_R_OPTS='--with-nth 2..'
```

**Comment by pablospe** [comment]
Thanks, this helps! How much slower is fzf with `--with-nth` option?
