### ISSUE TITLE
fzf does not respond in 4 GB RAM nodes

### ISSUE THREAD

**Issue by avatar-lavventura** [junegunn/fzf#2725]
- [X] I have read through the manual page (`man fzf`)
- [X] I have the latest version of fzf
- [X] I have searched through the existing issues

## Info

- OS
    - [X] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [X] bash
    - [X] zsh
    - [ ] fish

## Problem / Steps to reproduce

I have created a Google Instance with following configuration (`1 CPU, 4GB RAM`):

<img width="493" alt="image" src="https://user-images.githubusercontent.com/18537398/152578603-104ee4bd-12cb-4563-b49e-03f59dc12b03.png">

I observe that `fzf` may not respond with low memory nodes such as 4 GB.  This does not happen all the time but once in a while `fzf` does not output anything within the shell.  

Would it be possible to run configure `fzf` as lighter process since it may not respond in low memory machines?

**Comment by junegunn** [comment]
I use fzf on a machine with 512MB of memory and it works just fine. It will of course stop working at some point if I keep putting more stuff into it. e.g. `yes | fzf`

How many entries do you feed to fzf?

**Comment by avatar-lavventura** [comment]
I was using `fzf` to check history using `ctrl+r`. Currently there is around 200 items in the history , but it keeps extended when I run new commands in my terminal

When it stops working in the shell it does not re-work again (`fzf` does not respond).  I was not able to re-run it in the tab that `fzf` hangs.

I have to close to current tab and open a new one.  I am not sure how can I fix this issue. Or is there any catch mechanism that if `fzf` does not work , can an alternative program run instead.

**Comment by junegunn** [comment]
fzf will not use lots of memory for just 200 entries, so it doesn't seem like a memory issue. Which version of fzf are you running?

**Comment by junegunn** [comment]
Yes, that is the latest version. 3000 items should be no problem for 4GB of RAM. What do you see when you run?

```sh
HISTTIMEFORMAT= builtin history | wc
```

**Comment by avatar-lavventura** [comment]
`fzf` works golden with 4GB of RAM, but I am having this issue with 2GB of RAM with 2 CPU.

```bash
$ nproc
2
$ HISTTIMEFORMAT= builtin history | wc
     16      43     319
```

**Comment by avatar-lavventura** [comment]
@junegunn Please note that I am having this issue with 4 GiB Memory instances as well.

**Comment by junegunn** [comment]
I've never had the problem even on a VM with 512MB of memory.

You might want to see what exactly is going on when that happens by examining CPU usage and memory usage of the process.

**Comment by avatar-lavventura** [comment]
@junegunn It is a really interesting case. `clear -x` does not help I won't be able to refresh the terminal for `fzf` to work, just opening new terminal was my only solution.

Would there be any way to refresh the terminal for `fzf` to work ? Since I won't able to get any output from `fzf` I was unable to debug it.

**Comment by avatar-lavventura** [comment]
@junegunn Please see my: `export FZF_DEFAULT_OPTS=" --ansi --height 50% --layout=reverse --bind=ctrl-j:accept --bind=ctrl-s:down,ctrl-k:kill-line --bind
change:top --color=16,bg+:#44475a --no-mouse --bind=alt-v:page-up --bind=ctrl-v:page-down "` and `export FZF_CTRL_R_OPTS="--bind=ctrl-r:up"`. Do you think this setup might have impact for this issue?

**Comment by junegunn** [comment]
No. Does CTRL-S binding work well? A new terminal user often gets perplexed by their terminal not responding after CTRL-S. (https://unix.stackexchange.com/questions/137842/what-is-the-point-of-ctrl-s)

**Comment by avatar-lavventura** [comment]
@junegunn I never used C-s binding, seems like it does not work at all. I just keep seeing:

```
$ 
fwd-i-search: _
```

**Comment by junegunn** [comment]
I was referring to `--bind=ctrl-s:down` you posted above. But nevermind, seems unrelated to the issue you're having.

> Would there be any way to refresh the terminal for fzf to work ? 

`reset` command might help. Type in `reset` and enter key even if the terminal is not responding and see if it helps.

> Since I won't able to get any output from fzf I was unable to debug it.

There are a number of programs that can help examine the state of the process, `ps`, `top`, etc. Are you not familiar with any of them?

Also please post a screenshot image (or preferably a screencast) of the situation.

**Comment by avatar-lavventura** [comment]
I think I am unable to explain the problem I am having. In `zsh` shell after a while `fzf` does not response and locks the shell for 20-30 seconds whenever I want to use `fzf`.  `reset` or `clean` does not help. When `fzf` does not response, it just does not work does not log any output, just freezes current shell.

Of course I am familiar with `ps` and `top`. But even I kill the ongoing processes on the background, if `fzf` does not reponse it does not response again within the same shell. I have to open a new shell to have a working `fzf`.
