### ISSUE TITLE
`C-h` not working in `:FZF!`

### ISSUE THREAD

**Issue by sloterplas** [junegunn/fzf#2726]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

## Problem / Steps to reproduce

note: in `vim`, this works fine.

In `neovim`, `:FZF!` can't handle `C-*`, where `*` is `(h|j|k|l)`. What happens is that cursor jumps, and neovim goes to normal mode.
Pressing `i` to go back to insert mode restores cursor, but for example `C-h` did not resolve to backspace (or anything that you've bind it to).

**Comment by junegunn** [comment]
I can't reproduce the problem. Can you check if you still have the issue with the following minimal init.vim?

```sh
nvim -Nu <(curl https://gist.githubusercontent.com/junegunn/6936bf79fedd3a079aeb1dd2f3c81ef5/raw)
```

(https://gist.githubusercontent.com/junegunn/6936bf79fedd3a079aeb1dd2f3c81ef5/raw)

**Comment by sloterplas** [comment]
> I can't reproduce the problem. Can you check if you still have the issue with the following minimal init.vim?
> 
> ```shell
> nvim -Nu <(curl https://gist.githubusercontent.com/junegunn/6936bf79fedd3a079aeb1dd2f3c81ef5/raw)
> ```
> 
> (https://gist.githubusercontent.com/junegunn/6936bf79fedd3a079aeb1dd2f3c81ef5/raw)

Thanks, this works. Looks like I'm going to have fun figuring out what plugin/setting is causing this.......
`verbose map C-h` returns nothing :/

**Comment by sloterplas** [comment]
Thanks @junegunn for prompt response.

Anyone else facing this; double check any terminal keybindings ....... 🤦 


```
-- don't do this:
keymap("t", "<C-h>", "<C-\\><C-N><C-w>h", term_opts)
keymap("t", "<C-j>", "<C-\\><C-N><C-w>j", term_opts)
keymap("t", "<C-k>", "<C-\\><C-N><C-w>k", term_opts)
keymap("t", "<C-l>", "<C-\\><C-N><C-w>l", term_opts)
```
