### ISSUE TITLE
ctrl-{v,t,x} is ignored when used with fzf#run()

### ISSUE THREAD

**Issue by justinmk** [junegunn/fzf#273]
Using the fzf Vim plugin, `:FZF` command works as expected. But when `:call fzf#run()` is used, `ctrl-v` and friends are ignored. Using `<enter>` to select an item *does* work, and `ctrl-g` escapes/cancels.

Steps to reproduce:

```
unset FZF_DEFAULT_OPTS
vim -N -u NONE --cmd 'so ~/.fzf/plugin/fzf.vim'
:call fzf#run({'source':'find .', 'sink':'e'}
```

**Comment by junegunn** [comment]
Actually, that's how it works. See #187.
Those key bindings of `:FZF` command are implemented with `--expect` option. `source` for `fzf#run` can be any list of stuff (e.g. names of color schemes), so such key bindings don't always make sense.

**Comment by junegunn** [comment]
Also #239.

**Comment by justinmk** [comment]
Oh, got it. Thanks!
