### ISSUE TITLE
[Feature Request] Support limit maxmium lines output when directory is matched

### ISSUE THREAD

**Issue by zyf0330** [junegunn/fzf#2731]
- [ x] I have read through the manual page (`man fzf`)
- [ x] I have the latest version of fzf
- [ x] I have searched through the existing issues

## Info

- OS
    - [ x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ x] zsh
    - [ ] fish

## Problem / Steps to reproduce
When I input keywords which matchs directory, files inside directory will be listed from top to bottom. I hope FZF can limit output number of files inside matched directory.
Current behavior is this.
![image](https://user-images.githubusercontent.com/11958657/153327848-ea5fb828-eb7b-4821-83a4-45029bf0c1f3.png)
And actually there are other matched directories but sqeezed down.
![image](https://user-images.githubusercontent.com/11958657/153327870-43745c49-1b5e-43da-a76d-9ac8c24ce8a3.png)

**Comment by junegunn** [comment]
fzf is a general-purpose text filter and it does not know what each line of input represents.

```sh
seq 1000 | fzf
echo foobar | fzf
ps -ef | fzf
```

So it's not right for fzf to implement special treatment for a specific type of input.

In this case, your best bet would be to change the query to `/proj`.

**Comment by zyf0330** [comment]
@junegunn `--tiebreak=length` without `index` is what I need, but it doesn't work sometimes. I search some issues and know #638 causes it, unfortunately!
