### ISSUE TITLE
Feature request: Expand to longest common substring

### ISSUE THREAD

**Issue by c4eater** [junegunn/fzf#2732]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux

- Shell
    - [x] zsh

## Problem / Steps to reproduce
Hi,

I'm using fzf / skim for so many tasks and in my case fzf is missing an important piece of functionality: expansion to longest common substring.
Formally, I'd like to request an additional action (like eg **accept**), lets call it **expand**.

This action, when executed, would expand the query string to the longest of the candidates' substrings that match the query string. "Match" could be the substring match or prefix match, anything is ok.
Alternative definition: **expand** should keep expanding the query string while this expansion does not narrow down the list of candidates. Expansion can be done at the end or from both sides of the query string.

Example: Candidates are paab, paac, and aapaaad. Query string is "a". The new operation would expand the query string to "aa". A nice to have feature is to expand to "paa".

How I suppose to use it:

I am using fzf / skim as a fuzzy file/directory selector. So my fzf input is acquired from "find .".
When fzf's return value is a file name, I send it to $EDITOR, and when it's a directory I "cd" to it.
Sometimes I don't remember the file name, and use this selector to navigate to this file top-down.
So eg if the file name is "src/main.rs" I'd like to open it with something like "sr TAB mai RET".
Without the common substring expansion feature, I have to type the complete directory names.

Thanks

**Comment by c4eater** [comment]
To open it with something like "srmai" should be:
To open it with something like "sr TAB mai ENTER".

For some reason I cannot edit the issue description, sorry for that.

**Comment by tg0h** [comment]
hmm, when searching for 'sr mai' ... won't src/main.rs already appear as a candidate?
<img width="516" alt="image" src="https://user-images.githubusercontent.com/7954426/164886605-7c4f7faa-36ca-4961-97b1-e4beb5e30a6f.png">

**Comment by c4eater** [comment]
OK, you have a point. Surprisingly, I didn't think of a multi-input with SPC because in my setup it is bound to "accept". I'll close the issue now.
