### ISSUE TITLE
Preserve colors outputted by rich in preview pane

### ISSUE THREAD

**Issue by khughitt** [junegunn/fzf#2736]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

## Problem / Steps to reproduce

- Colored output from [rich](https://github.com/Textualize/rich) appears uncolored in fzf preview pane
- [At first glace](https://github.com/Textualize/rich/blob/master/rich/color.py), rich appears to be using ansi colors for output
- Tested in several terminals with same effect: kitty, xterm, alacritty
- fzf 0.29.0

To reproduce (uses cli from [rich-cli](https://github.com/Textualize/rich-cli) package):

```
fzf --preview "rich '[cyan]test[/cyan]' --print"
```

**Comment by junegunn** [comment]
```sh
fzf --preview "rich '[cyan]test[/cyan]' --print --force-terminal"
```
