### ISSUE TITLE
[neovim] How to combine multiple sources?

### ISSUE THREAD

**Issue by PonderingGrower** [junegunn/fzf#274]
Hi,

It looks to me like FZF is the best fuzzy search option for neovim at the moment. And I do use it for all of my file searching, but one of the main things I loved about Unite is the fact that I could combine multiple sources.

To be exact I would combine open buffers, mru files, and current project root search (or if no such root exists then the home dir).

I'm not very well versed in vimscript so I tried and failed to do this. How would I go about combining these three sources in one FZF search in neovim?

**Comment by justinmk** [comment]
You can do it in vimscript or you could do it in bash (redirect 3 streams to 1) if you are more comfortable with that. Interleaving 3 streams into 1 stream in vimscript would be less convenient than bash, though it is definitely possible using job control (`:help jobstart()`).

Note that unite's source composition did not interleave streams, it just concatenated them (and it was quite slow, though I never tried vimproc). If you want to do that with fzf, you could, but fzf would not be able to seach the last stream until the previous 2 streams were completed.

**Comment by PonderingGrower** [comment]
>fzf would not be able to seach the last stream until the previous 2 streams were completed.

That's fine since the first two streams would be just open buffers and most recently opened files, so the lists shouldn't be very big.

So what you are saying is that in the `source` section of the dict passed onto `fzf#run()` I should combine for example two commands to get all their outputs in fzf like so:

    'source': '{echo -e "'.v:oldfiles.'"; ag -l -g "" }'

Does that make sense?

**Comment by justinmk** [comment]
> So what you are saying is that in the source section of the dict passed onto fzf#run() I should combine for example two commands to get all their outputs in fzf like so:

Yes, that's the idea. 

Note that fzf runs in a fully-interactive `:term` buffer, which will inherit all functions/settings/etc from your `.bashrc` (or .zshrc or whatever). So you could do all of this in a shell function instead of inlining it in vimscript...

**Comment by junegunn** [comment]
I think you do need to know some vimscript to achieve it :) `source` parameter of `fzf#run` can be an external command (string type), or a vimscript list. Since the latter cannot be asynchronously streamed into fzf, you might want to stick to the former. So what you need here is a vimscript function that writes the list of open buffers and stuff into a temporary file, and executes `fzf#run` with the source command that concatenates the temp file and ag output.

**Comment by PonderingGrower** [comment]
I don't think implementing it somewhere in my zsh configuration would work since the sources I want to add are vim specific, which are opened buffers and recently opened files.

And thanks junegunn for that tip. I wasn't aware you could pass just a command directly. I'll try that out.

I definitely have to work on my vimscript knowledge. I guess this is kinda off topic but is  (http://learnvimscriptthehardway.stevelosh.com/)[Larn Vimscript the Hard Way] a good source or do you have any other recommendations?

**Comment by PonderingGrower** [comment]
Okay, so I've built this:

    command! FZFMix call fzf#run({
                \'source':  'bash -c "'.
                \               'echo -e \"'.join(v:oldfiles, '\n').'\";'.
                \               'ag -l -g \"\"'.
                \           '"',
                \'sink' : 'e ',
                \'dir' : g:projectroot,
                \'options' : '-e -m --reverse',
                \'window' : 'enew',
                \})

And I'm getting the old files together with the result from `ag`, but when I select a file for some reason I lose all my vim windows and it gets opened in the main and only window. Also, the moment I do ANY action the window goes back to the previously opened buffer. I'm pretty confused.

**Comment by PonderingGrower** [comment]
Also, if I open a completely new neovim and I use `FZFMix` from above I get

    Error detected while processing function 42:
    line    5:
    E444: Cannot close last window

**Comment by junegunn** [comment]
@PonderingGrower Hmm, `fzf#run` was not written to handle `{'window': 'enew'}` correctly. I'll push a fix shortly and let you know.

**Comment by junegunn** [comment]
@PonderingGrower I have tested `:call fzf#run({'window': 'tabe', 'sink': 'e'})` works as expected in the following cases:

- `nvim`
    - Select file
    - Abort finder
    - Press enter with no match (empty output)
- `nvim +'set nobuflisted'`
    - Select file
    - Abort finder
    - Press enter with no match (empty output)
- `nvim SOMEFILE`
    - Select file
    - Abort finder
    - Press enter with no match (empty output)
- `nvim +'wincmd v|wincmd w'`
    - Select file
        - A short flash of `[Program exited, press any key to close]` is shown
    - Abort finder
    - Press enter with no match (empty output)

**Comment by PonderingGrower** [comment]
Looks like it seems to work in all the cases I tested. Awesome! Thanks a bunch.

The only weird thing I've noticed is that with `enew` I can notice for a second or less the `[Program exited, press any key to close]`. It's not a problem, just something I noticed.

**Comment by junegunn** [comment]
Yeah, it's something I also noticed in some cases (see the above comment). Anyway, as it looks like now you have the idea how things can be done, I'll close the issue. Let me know if you run into a bug of vim/nvim plugin.

**Comment by PonderingGrower** [comment]
Thanks man, you rock!
