### ISSUE TITLE
field index expressions are not updated after `change-preview` action

### ISSUE THREAD

**Issue by salmankhilji** [junegunn/fzf#2744]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

### Description

After dynamically reloading data and changing the preview window command using `change-preview`, `fzf` does not update the Field Index Expressions.  The user must manually press the arrow keys to force update the preview window.

### Step to Reproduce

1. Install `bat` and `ripgrep` if needed.

2. `cd` into a scratch directory.

3. Generate some sample files.

    ```sh
    for i in $(seq 10); do echo hello_$i >foo_$i.bar; done
    ```

4. Invoke `fzf` like this:

    ```sh
    FZF_DEFAULT_COMMAND="ls -1 *.bar | sed 's/\.bar$//'" \
    fzf \
      --ansi \
      --delimiter : \
      --bind "ctrl-f:reload(rg --column --line-number --no-heading --color=always --smart-case '')" \
      --bind 'ctrl-f:+change-preview(bat --color=always {1} --highlight-line {2})' \
      --bind "ctrl-f:+change-preview-window(up,70%,border-bottom,+{2}/2)" \
      --bind "ctrl-f:+clear-query" \
      --bind "ctrl-f:+clear-selection" \
      --bind "ctrl-f:+unbind(ctrl-f)" \
    | sed 's/\.bar:.*//'
    ```

5. CTRL+F.

### Observed Behavior

Preview window has:

```
[bat error]: Empty line range
```

### Expected Behavior

Preview window to show valid contents of the selected file.

### Notes

The user can force update the preview window by pressing the **Up** arrow key, followed by the **Down** arrow key.

The issue is that after the `reload` and `change-preview` commands, `fzf` does not properly revaluate the field index expression, `{2}`, which remains empty.

My workaround is to change the `--bind` like this:

```
--bind 'ctrl-f:+change-preview(bat() { [ -z $2 ] && true || command bat --color=always $1 --highlight-line $2; }; bat {1} {2})' \
```

### Version

0.29.0 (dc975e8)
Ubuntu Linux 20.04 LTS

**Comment by salmankhilji** [comment]
After upgrading to `0.30`, I can see that the issue is not completely fixed.

Immediately prior to showing the correct content, the preview window flashes with the `[bat error]: Empty line range` text for a fraction of a second.  (Though not a major problem, its just a fit-and-finish issue at this point.)

It appears that `bat` may still be called with the wrong arguments for the very first invocation.

**Comment by junegunn** [comment]
`reload` works asynchronously, while `change-preview` takes action immediately, so the behavior you see is normal and expected.

You might want to redirect the stderr of bat process so that the error message is not shown. i.e. `change-preview(bat --color=always {1} --highlight-line {2} 2> /dev/null)`

**Comment by salmankhilji** [comment]
> `reload` works asynchronously (e.g. `fzf --bind 'ctrl-r:reload:while true; do sleep 1; date; done'`), while `change-preview` takes action immediately, so the behavior you see is normal and expected.
> 
> You might want to redirect the stderr of bat process so that the error message is not shown. i.e. `change-preview(bat --color=always {1} --highlight-line {2} 2> /dev/null)`

Your suggestion to redirect stderr works.  Thank you!
