### ISSUE TITLE
[macOS] Started getting `Failed to read /dev/tty` after brew upgrade

### ISSUE THREAD

**Issue by Dentrax** [junegunn/fzf#2745]
- [X] I have read through the manual page (`man fzf`)
- [X] I have the latest version of fzf
- [X] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [X] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [X] zsh
    - [ ] fish

## Problem / Steps to reproduce

No error on `bash`.

1. Update the all Brew packages:
```
$ brew update && brew upgrade && brew upgrade --cask
```
2. Restart
3. See the error
```
$ fzf --version

0.29.0 (brew)
Failed to read /dev/tty
^[[30;1Rzoxide: fzf returned an error
```

`fzf` command just works normally but if you press <kbd>CTRL + C</kbd>, getting the following error:

![Screen Shot 2022-02-28 at 09 32 10](https://user-images.githubusercontent.com/16493751/155935392-3b67a2c2-573d-4f81-8836-938380d0a714.png)

OS: `macOS 12.1`

```
$ uname -a

Darwin 21.2.0 Darwin Kernel Version 21.2.0: Sun Nov 28 20:28:54 PST 2021; root:xnu-8019.61.5~1/RELEASE_X86_64 x86_64
```

```
$ zsh --version

zsh 5.8.1 (x86_64-apple-darwin21.3.0)
```

I did not upgrade the macOS or Kernel.

Any ideas?

**Comment by junegunn** [comment]
What's the output of `type fzf`?

**Comment by Dentrax** [comment]
After long time of debugging, commenting out the `eval "$(zoxide init zsh)"` in `~/.zshrc` fixed the issue.
