### ISSUE TITLE
[neovim] How to open FZF in current split/window and open selected file in it?

### ISSUE THREAD

**Issue by PonderingGrower** [junegunn/fzf#275]
Hi,

I'm trying to switch from Unite to FZF in neovim but I would like to have the FZF search window to be specific to the split from which I executed it. When it's opened as a separate split on the bottom it doesn't reflect which split it will affect once you select a file.

Is this doable?

I've been trying to achieve this by commenting `call s:split(a:dict)` in `s:execute_term()` and fiddle with the `fzf.on_exit()` function but I've encountered a number of issues:

1. `Can only call this function in an unmodified buffer.`
2. `E315: ml_get: invalid lnum: 778`
3. The term windows opening in all splits containing the same buffer.
4. Once selected file is open any action closes the split.

So yeah, I suck at vimscript and I have no idea how to get this working. Any suggestions?

**Comment by junegunn** [comment]
You might want to fiddle with `window` option of `fzf#run`. (https://github.com/junegunn/fzf#fzfrunoptions)

e.g. `call fzf#run({'sink': 'e', 'window': 'rightbelow new'})`

**Comment by PonderingGrower** [comment]
Thanks! Looks like `'window': 'enew'` does what I want. Thanks man!

**Comment by junegunn** [comment]
No problem.
