### ISSUE TITLE
Function with `fzf` to auto-select

### ISSUE THREAD

**Issue by MahbubAlam231** [junegunn/fzf#2750]
- [X] I have read through the manual page (`man fzf`)
- [X] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

## Problem / Steps to reproduce

I want to write a program, `select_file()` with an input of filename, that chooses the first option from `fzf` list and opens it.

For instance, running
```
    select_file alpha
```
in the terminal should open `fzf` and search for `"alpha"`, and the first result that pops up should be opened via `xdg-open {}`.

I tried to pipe `"alpha"` into `fzf` but of course, that doesn't work. I don't any functionality of `fzf` that allows this, then again I don't much I suppose.

I was wondering if there was any way of doing this. Thanks in advance.

**Comment by MahbubAlam231** [comment]
Hmm, I am not sure what I would need/like, cause I haven't tried them yet. I have thought about it again but didn't manage to solve the problem. I would love to see both approaches.

**Comment by zdykstra** [comment]
`ls | fzf --query config --bind "enter:execute-silent:xdg-open {}"`

**Comment by MahbubAlam231** [comment]
Great! Thanks a lot @zdykstra. I see that this function works with `sf alpha`. I surely didn't know much about `fzf`.
```
sf() {
    cd $HOME && fzf --query=$@ --bind "enter:execute(xdg-open {})"
}ls | fzf --query alpha --bind "enter:execute-silent:xdg-open {}"
```
I have been looking at `man fzf` and trying to figure out how to open the first file _automatically_, but I am stuck again. Clearly, I am not reading `man fzf` right.

**Comment by zdykstra** [comment]
To the best of my knowledge, you can only achieve this behavior if a single line matches in fzf (and then you'd need to pipe the output into xargs).  It seems like a `ls | fuzzy grep | head -1 | xargs xdg-open` pipeline would be a better tool for your specific goals.

**Comment by MahbubAlam231** [comment]
Do you mean `fgrep` by `fuzzy grep`? This sequence isn't working. Also, I don't know where to put the input.

**Comment by junegunn** [comment]
```sh
sf() {
  cd "$HOME" && fzf --query="$*" --preview 'xdg-open {}' --preview-window 0
}
```

Excerpt from man page

> If size is given as 0, preview window will not be visible, but fzf will still execute the command in the background

**Comment by MahbubAlam231** [comment]
@junegunn I tried your suggestion, but when I type `sf alpha.pdf`, not only does `alpha.pdf` open, sometimes a bunch of other files also open (in other terminals). I couldn't figure what was going on.

**Comment by mrcnski** [comment]
> trying to figure out how to open the first file automatically

@MahbubAlam231 not an fzf expert but seems like you can do this now with `--sync --bind 'start:accept'`.
