### ISSUE TITLE
After update, ctrl+r uses .sh_history instead of .bash_history

### ISSUE THREAD

**Issue by nyurik** [junegunn/fzf#2751]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

## Problem / Steps to reproduce

After updating to latest fzf and latest kitty, `ctrl+r` shows the content of the `.sh_history` shell even though bash is being used. If I ran a nested `bash`, `ctrl+r` starts using the correct file `.bash_history`.  I tried removing all .fzf settings from `.bashrc` and rerunning the install script but that didn't help.

**Comment by junegunn** [comment]
CTRL-R implementation doesn't directly access those files. It only runs the built-in `fc` command.

https://github.com/junegunn/fzf/blob/b88eb72ac29b92c82a0d7c7f8d7b65380720b02c/shell/key-bindings.bash#L47-L60

So this is not an issue of fzf.
