### ISSUE TITLE
Feature request: update the preview window even when placeholders are empty

### ISSUE THREAD

**Issue by carlfriedrich** [junegunn/fzf#2759]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

## Problem / Steps to reproduce

I have an issue where I see an empty preview window when there is no input for fzf (i.e. 0 lines), even if I have a preview command defined. Minimal example:

```
echo -n "" | fzf --preview "echo Input: {q}"
```

Gives me this output:

![grafik](https://user-images.githubusercontent.com/45259958/158608442-6f8bc179-439a-4f1f-9a9f-8abb0cea417b.png)

In fzf's man pages I saw that this is actually the defined behaviour:

```
--preview=COMMAND

      [...]

      Preview window will be updated even when there is no match for the current query if any of the
      placeholder expressions evaluates to a non-empty string.
``` 

I assume this is the most useful implementation for most use cases. However, in my specific case I would like to have my preview command called even when the placeholder expressions are empty. When I don't use any of the placeholders in my preview command, this is already working:

```
echo -n "" | fzf --preview "echo This is always shown!"
```

![grafik](https://user-images.githubusercontent.com/45259958/158609084-db3eb0e0-170b-4e2a-89f5-a59d13de5bc3.png)

I would like the same behaviour when I am using any of the placeholders. Can we have some kind of flag for this? Or is this even possible already somehow?

**Comment by junegunn** [comment]
> if any of the placeholder expressions evaluates to a non-empty string

With the current implementation, this is inaccurate because we always run the preview command if `{q}` is in the command template even when `{q}` is an empty string. I won't change it, I'll just fix the doc.

So, you can take advantage of the fact and put `{q}` in the command like so.

```sh
fzf --preview ': {q}; echo [PREVIEW]; if [ -z {} ]; then echo No match; else cat {}; fi'
```

**Comment by junegunn** [comment]
Wait, `echo -n "" | fzf --preview "echo Input: {q}"` not running the preview command is a different problem and it looks like a bug.

**Comment by junegunn** [comment]
Please ignore my previous (deleted) comment.

**Comment by carlfriedrich** [comment]
@junegunn Thanks for commenting on this. So the preview window not showing when using `{q}` while it's an empty string is indeed a bug? Will you take care of this then?

**Comment by carlfriedrich** [comment]
Ping @junegunn. Can I help with this issue anyhow? If this in indeed a bug, I would love to have it fixed.

**Comment by junegunn** [comment]
This is not a bug, the behavior matches the documentation.

> Can we have some kind of flag for this?

Maybe. I haven't thought enough about it. There can be a few different ways to achieve it.

**Comment by carlfriedrich** [comment]
@junegunn Thanks for your reply. So what are the different ways you see for this?

**Comment by junegunn** [comment]
One option would be to add a new placeholder expression for the match count for the current query. Something like `{#}` maybe? It will evaluate to `0`, a non-empty string, even when there's no match so it will always trigger a preview update.

**Comment by carlfriedrich** [comment]
That sounds reasonable and would work for my use case. Are only those placeholders evaluated which are used in the preview command?

**Comment by junegunn** [comment]
Yes.

**Comment by carlfriedrich** [comment]
Great, than this approach would totally make sense, without breaking anything. Can I help with the Implementation?

**Comment by carlfriedrich** [comment]
@junegunn Thanks a lot for the fix!
