### ISSUE TITLE
Usage example of fzf : fpp = pe + fzf + $EDITOR

### ISSUE THREAD

**Issue by edi9999** [junegunn/fzf#276]
Hi,

I just open-sourced a very small CLI because I liked the idea of [fpp](https://github.com/facebook/PathPicker) but didn't like that I was forced to use their picker.

The CLI extracts filepaths from stdin, so that you can write:

`git status | pe | fzf` to select between files that are in your staged area for example (but it would work with any command of course).

Here's a link to my project : https://github.com/edi9999/path-extractor

**Comment by junegunn** [comment]
That looks pretty neat, thanks for sharing. There was [a discussion on posting a list of related project](https://github.com/junegunn/fzf/pull/268) in the wiki page. I'll add path-extractor as well when I get to do that.
