### ISSUE TITLE
Unable to execute bash/zsh functions in --bind

### ISSUE THREAD

**Issue by callumacrae** [junegunn/fzf#2762]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [x] zsh
    - [ ] fish

## Problem / Steps to reproduce

I feel like this must have come up before but was unable to find an issue!

I'm trying to bind a key to execute a function set in the shell—set locally for demo purposes but the same happens in .zshrc files.

It fails in zsh:

![image](https://user-images.githubusercontent.com/472830/158826842-4b0954ba-a624-4d86-ad84-d8e63ab79eab.png)

It fails in bash too:

![image](https://user-images.githubusercontent.com/472830/158826909-c3acda35-38dc-42f7-aaec-474d17675564.png)

I've tried to look into the source to figure it out myself but am unfamiliar with how Go works so struggled to make any progress: https://github.com/junegunn/fzf/blob/cd2340141100e057005d31e653c0ce7a0f7a4af7/src/util/util_unix.go#L12

**Comment by junegunn** [comment]
```sh
foo() {
  echo foo
}

# You should export the function
export -f foo

fzf --preview 'foo'
```

**Comment by callumacrae** [comment]
Thanks!

For anyone else who finds this issue, the problem was that functions aren't available to child processes.

Unfortunately in ZSH, it looks like you can't export functions - the recommended alternative is to use autoloaded functions instead, or you could make a proper script and add it to your `$PATH`.

I just put all my scripts in big strings 🤷‍♂️
