### ISSUE TITLE
FZF is broken on fish 3.4.0 w/ Termux...

### ISSUE THREAD

**Issue by Dan1jel** [junegunn/fzf#2763]
Updated my fish on termux after that FZF don't work, when type 'fzf' i get this error 

[Command failed: set -o pipefail; command find -L . -mindepth 1 \( -path '*/\.*' -o -fstype 'sysfs' -o -fstype 'devfs' -o -fstype 'devtmpfs' -o -fstype 'proc' \) -prune -o -type f -print -o -type l -print 2> /dev/null | cut -b3-]

Edit: updated for correct code without " ".

**Comment by UncertaintySailor** [comment]
Broken for me aswell with same error as above on termux.

**Comment by 0ion9** [comment]
OP's command looks wrong to me ( parentheses are not escaped ). 
Regardless, it would be good to know whether the problem also occurs without termux or with FZF_DEFAULT_COMMAND unset.

**Comment by Dan1jel** [comment]
> OP's command looks wrong to me ( parentheses are not escaped ). 
> Regardless, it would be good to know whether the problem also occurs without termux or with FZF_DEFAULT_COMMAND unset.

I haven't set the default command to anything. This is right out of the box. In bash, it worked as intended but not in Fish shell.

**Comment by 0ion9** [comment]
hmm. Well, I also run fish (git/ pre-3.5) and don't run termux, so I suppose I could check that.

At the moment bin/fzf-tmux line 186 looks suspicious, I suspect 'printf %q' is a bash extension which quotes a string in a way appropriate to the bash shell. I think bash doesn't interpret ' ( ', but fish does. Adding some `sed s/` to this line to ensure that parentheses are single-quoted might be what is needed.

**Comment by junegunn** [comment]
See if this works:

```sh
bash -c "set -o pipefail; command find -L . -mindepth 1 \( -path '*/\.*' -o -fstype 'sysfs' -o -fstype 'devfs' -o -fstype 'devtmpfs' -o -fstype 'proc' \) -prune -o -type f -print -o -type l -print 2> /dev/null | cut -b3-"
```

**Comment by Dan1jel** [comment]
> See if this works under fish.
> 
> ```sh
> bash -c "set -o pipefail; command find -L . -mindepth 1 \( -path '*/\.*' -o -fstype 'sysfs' -o -fstype 'devfs' -o -fstype 'devtmpfs' -o -fstype 'proc' \) -prune -o -type f -print -o -type l -print 2> /dev/null | cut -b3-"
> ```

No luck unfortunately. 

![Screenshot_20220321-065358.png](https://user-images.githubusercontent.com/4266424/159211425-160daea5-3265-4f93-8691-a1af0acef195.png)

**Comment by 0ion9** [comment]
Works fine in just fish ( no termux, git 3e5284aaf) - returns a list of files as expected.
Unless I am misreading the screenshot above, that attempt also succeeded, but returned no files. It's unclear whether that would be wrong, as there is no indication of what the PWD is and what, if anything, it might contain.

**Comment by gustav-b** [comment]
I'm able to reproduce this issue with bash under Termux. If I run the command above without the stderr redirection:

```sh
$> bash -c "set -o pipefail; command find -L . -mindepth 1 \( -path '*/\.*' -o -fstype 'sysfs' -o -fstype 'devfs' -o -fstype 'devtmpfs' -o -fstype 'proc' \) -prune -o -type f -print -o -type l -print | cut -b3-"
find: Cannot read mounted file system list
```
If I remove the `-fstype` flags from the command it works as intended.

![Screenshot_20220321-083953](https://user-images.githubusercontent.com/368219/159221074-b3bc3547-0c1e-4e02-81a5-def06655be82.png)

**Comment by 0ion9** [comment]
ok, that's clearer.
What does `find -fstype devfs` do? It is noted in `find` man page that valid values for -fstype vary between systems, but it's unclear exactly what specifying an invalid one results in when -O levels is 0 or 1 (1 is default).

**Comment by Dan1jel** [comment]
> ok, that's clearer.
> What does `find -fstype devfs` do on your system? It is noted in `find` man page that valid values for -fstype vary between systems, but it's unclear exactly what specifying an invalid one results in when `-O` level is 0 or 1 (1 is default).

On my Android phone, i assume it trying to look up all mounted systems but I'm no genius.

All i do know is that FZF worked great on termux app before the fish update. After update i got this wired error message. But it must be something with termux/fish because it works well in bash.

**Comment by 0ion9** [comment]
> I'm able to reproduce this issue with bash under Termux. If I run the command above without the stderr redirection:
> 
> ![Screenshot_20220321-083953](https://user-images.githubusercontent.com/368219/159221074-b3bc3547-0c1e-4e02-81a5-def06655be82.png)

I just noticed, this might not be appropriate. It looks like you are running this from bash ( hence BASH_VERSION being set) and not fish. OP only has a problem within fish.

The answer to what `find -fstype SOMETHINGINVALID` does seems to be 'just matches no files, but doesn't return an error' on a normal Linux. By my reasoning the next thing is to find out if it does something different in Termux+Fish, and also whether its behaviour in those circumstances is provably different from it's behaviour under Termux+BASH.

**Comment by BufuWinner** [comment]
I get the same error, but with different dynamics. The issue occurs after performing an update of all installed packages (even with a fresh installation). I managed to narrow it down to the package 'findutils' that, after updating to version 4.9.0 from 4.8.0, generates the error... ( [Command failed: set -o pipefail; command find -L . -mindepth 1 \( -path '*/\.*' -o -fstype 'sysfs' -o -fstype 'devfs' -o -fstype 'devtmpfs' -o -fstype 'pr..).
Could it be the same problem? The package, even with the latest termux app, still needs updating along with 29 others...

**Comment by Dan1jel** [comment]
> I get the same error, but with different dynamics. The issue occurs after performing an update of all installed packages (even with a fresh installation). I managed to narrow it down to the package 'findutils' that, after updating to version 4.9.0 from 4.8.0, generates the error... ( [Command failed: set -o pipefail; command find -L . -mindepth 1 \( -path '*/\.*' -o -fstype 'sysfs' -o -fstype 'devfs' -o -fstype 'devtmpfs' -o -fstype 'pr..).
> Could it be the same problem? The package, even with the latest termux app, still needs updating along with 29 others...

I can't see that i have it installed, so i don't know it this is the case? 

Trying findutils and ```command -v findutils``` with no results.

**Comment by BufuWinner** [comment]
> I can't see that i have it installed, so i don't know it this is the case? 
> 
> Trying findutils and ```command -v findutils``` with no results. 

It's not a command... I think the package contains the "utilities" for the _find_ command which is used in fzf. Maybe the update changed a parameter of the command that breaks the fzf search. The dev probably needs to update the code... I really don't know.
If you want, just to be sure, try running `pkg search findutils` and see which version is installed. Even if it says 4.9.0, as of know I couldn't find an easy way to rollback, other then reinstalling termux. It could be possible to install it from source...

**Comment by gustav-b** [comment]
> > I can confirm that downgrading from `findutils` 4.9.0 to 4.8.0 fixes the issue for me.
> 
> Can I ask you how? Both `pkg` and `apt` can't find the package... I am trying to do it from the source tarball put it's really painful, there are lots of problems.

I found it in a backup of my APT cache:
```/data/data/com.termux/cache/apt/archives/findutils_4.8.0_aarch64.deb```

It's unfortunate that the termux package archive doesn't keep old package versions.

**Comment by gustav-b** [comment]
FYI: I opened a termux-packages `findutils` issue:
termux/termux-packages#9506

**Comment by junegunn** [comment]
I've tried to make the default command as portable as possible, but it may not work on some versions of find. 
You should note that you can always change the default via `$FZF_DEFAULT_COMMAND`.

**Comment by Dan1jel** [comment]
> I've tried to make the default command as portable as possible, but it may not work on some versions of find. 
> You should note that you can always change the default via `$FZF_DEFAULT_COMMAND`.

That is true, but always nice that thing works out-of-the-box without edits. 

But what would I need to type to get this working for now (also for others who might have this issue and need an answer) ? Also what to type to change it back if an update comes?

Would really be appreciated.

**Comment by junegunn** [comment]
> what would I need to type to get this working for now

Setting the environment variable to a working command. You don't have to use `find` ([FYI, I don't](https://github.com/junegunn/dotfiles/blob/fa339b3379b0f08b0fed711d3d413979db837e92/bashrc#L417). See https://github.com/junegunn/fzf#respecting-gitignore)

> what to type to change it back if an update comes

Unsetting the variable.

**Comment by Dan1jel** [comment]
> > what would I need to type to get this working for now
> 
> Setting the environment variable to a working command. You don't have to use `find` ([FYI, I don't](https://github.com/junegunn/dotfiles/blob/fa339b3379b0f08b0fed711d3d413979db837e92/bashrc#L417). See https://github.com/junegunn/fzf#respecting-gitignore)
> 
> > what to type to change it back if an update comes
> 
> Unsetting the variable.

Yes that is true. Thank you for the links. Been playing around with that and .bashed / config.fish. 

So you know why i get numbers to the left when pressing CTRL+R in bash but not in Fish? I would like to remove the numbers an just have the history command but i can't seem to find where the issue are or what the original ```export FZF_CTRL_R_OPTS``` should be. 

![Screenshot_20220323-162929.png](https://user-images.githubusercontent.com/4266424/159736284-806ab477-4124-45ad-8400-aa8e4293a04c.png)

![Screenshot_20220323-162851.png](https://user-images.githubusercontent.com/4266424/159736305-799b5515-f88a-4b35-8f0a-a6160a9d3c35.png)

**Comment by MyController** [comment]
bash -c "set -o pipefail; command find -L . -mindepth 1 \( -path '*/\.*' \) -prune -o -type f -print -o -type l -print 2> /dev/null | cut -b3-"

**Comment by gustav-b** [comment]
The Termux `findutils` package [has now been fixed](https://github.com/termux/termux-packages/pull/9541#event-6299519503) to work with `-fstype`. Please upgrade to `4.9.0-1` and retest.

This solved the issue for me. 🎉

**Comment by Dan1jel** [comment]
> The Termux `findutils` package [has now been fixed](https://github.com/termux/termux-packages/pull/9541) to work with `-fstype`. Please upgrade to `4.9.0-1` and retest.
> 
> This solved the issue for me. 🎉 

Can confirm, FZF is now working in fish again, thanks for the heads-up!

**Comment by gustav-b** [comment]
> Can confirm, FZF is now working in fish again with default settings. Thanks for the heads-up about the `4.9.0-1` update.

Great! Maybe the issue title should be updated to reflect that this was an issue with Termux `findutils` package `4.9.0` and not related to the shell?

**Comment by Dan1jel** [comment]
> > Can confirm, FZF is now working in fish again with default settings. Thanks for the heads-up about the `4.9.0-1` update.
> 
> Great! Maybe the issue title should be updated to reflect that this was an issue with Termux `findutils` package `4.9.0` and not related to the shell?

Sorry, my mistake but yes of course.
