### ISSUE TITLE
--disabled not work

### ISSUE THREAD

**Issue by javiermiras88** [junegunn/fzf#2767]
- [ ] I have the latest version of fzf

## Info

- OS

    - [ ] Mac OS X

- Shell

    - [ ] zsh

## Problem / Steps to reproduce

fzf --disabled

but not work , it keeps giving me the option to search

<img width="478" alt="image" src="https://user-images.githubusercontent.com/96594763/159174361-fa82a089-31b7-46c0-bace-b21cc949f0b3.png">

**Comment by junegunn** [comment]
It's working as expected. `a.sh` still showing even when the query string obviously doesn't match it proves that the search functionality is disabled.

You might want to check out https://github.com/junegunn/fzf/blob/master/ADVANCED.md#using-fzf-as-interative-ripgrep-launcher to see how `--disabled` can be used.

**Comment by javiermiras88** [comment]
> https://github.com/junegunn/fzf/blob/master/ADVANCED.md#using-fzf-as-interative-ripgrep-launcher

Can't remove the search bar?
