### ISSUE TITLE
Having two issues i can get to fix. Help is needed.

### ISSUE THREAD

**Issue by Dan1jel** [junegunn/fzf#2768]
Worry but don't know where to turn with these questions, didn't find any reddit channel or anything so my apologies beforehand for fluding GitHub. 

Issue #1. 

When I use CTRL-R, history numbers appears to the side of my historyz i don't know what I've done to achieve this or activated this. But this issue is only in BASH, not on FISH SHELL. How can I turn this off? 

![Screenshot_20220323-162851.png](https://user-images.githubusercontent.com/4266424/159842808-0f595134-a5bf-49fe-8dfa-f5431bab9ae9.png)

Issue #2. 

When I press ALT-C, my prompt shows ```'__fzf_cd__'``` in BASH and when cancelled, it jumps down one row. Is this a general error or is my code messed up/missing something? 

![Screenshot_20220323-203949.png](https://user-images.githubusercontent.com/4266424/159843013-c63f8e14-6cb3-44a3-aa3c-67d0fbf6ed83.png)

**Comment by junegunn** [comment]
> history numbers

See https://github.com/junegunn/fzf/issues/2722#issuecomment-1031000418

> Is this a general error or is my code messed up/missing something?

It's normal and expected. I don't see it as a problem.

**Comment by Dan1jel** [comment]
> > history numbers
> 
> See https://github.com/junegunn/fzf/issues/2722#issuecomment-1031000418
> 
> > Is this a general error or is my code messed up/missing something?
> 
> It's normal and expected. I don't see it as a problem.

Thanks for the answers. 

Didn't see it as a "problem" just if something was off and if there was a way to fix it, or what i might have done wrong. 

But thanks for the quick reply.
