### ISSUE TITLE
Wrong information in root Readme.md

### ISSUE THREAD

**Issue by Lompik** [junegunn/fzf#277]
https://github.com/junegunn/fzf#settings

I could not get the `export FZF_COMPLETION_OPTS="-m -x` as stated in the link above to work. However setting the `export FZF_DEFAULT_OPT="-m -x"` as stated in the man page worked.

**Comment by junegunn** [comment]
Well, it works for me. `FZF_COMPLETION_OPTS` only applies to auto-completion (`**<tab>`) and `FZF_DEFAULT_OPTS` applies globally.

**Comment by junegunn** [comment]
I think you're misguided since `FZF_DEFAULT_OPTS` is not explicitly mentioned on the README page, I'll consider adding it to the page. Thanks.

**Comment by Lompik** [comment]
Exactly what happend. Thanks.
