### ISSUE TITLE
How can I apply timeout if fzf does not response?

### ISSUE THREAD

**Issue by avatar-lavventura** [junegunn/fzf#2772]
## Info

- OS
    - [X] Linux
    - [X] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [X] zsh
    - [ ] fish

I observe that `fzf` may not respond with low memory nodes such as 4 GB. This does not happen all the time but once in a while `fzf` does not output anything within the shell. It just hangs like in an endless loop. Only fix is to open a new terminal windows, which requires additional time. In these cases is there any timeout mechanism, which will open native reverse history search of linux if `fzf` does not response in few seconds??

Related: [## Problem / Steps to reproduce](https://github.com/junegunn/fzf/issues/2725)

**Comment by junegunn** [comment]
> It just hangs like in an endless loop

Is it consuming CPU resources when that happens? 

> 4 GB

4 GB is a lot of memory for fzf. How much memory fzf process takes up when that happens?

**Comment by avatar-lavventura** [comment]
> Is it consuming CPU resources when that happens? 

No

--------

```
$ cat /proc/88662/status
Name:	fzf
Umask:	0002
State:	S (sleeping)
Tgid:	88662
Ngid:	0
Pid:	88662
PPid:	75318
TracerPid:	0
Uid:	1001	1001	1001	1001
Gid:	1002	1002	1002	1002
FDSize:	64
Groups:	4 20 24 25 27 29 30 44 46 110 114 1000 1001 1002
NStgid:	88662
NSpid:	88662
NSpgid:	88661
NSsid:	75318
VmPeak:	  704216 kB
VmSize:	  704216 kB
VmLck:	       0 kB
VmPin:	       0 kB
VmHWM:	    3164 kB
VmRSS:	    3164 kB
RssAnon:	     900 kB
RssFile:	    2264 kB
RssShmem:	       0 kB
VmData:	   41408 kB
VmStk:	     136 kB
VmExe:	    1100 kB
VmLib:	       8 kB
VmPTE:	      88 kB
VmSwap:	       0 kB
HugetlbPages:	       0 kB
CoreDumping:	0
THP_enabled:	1
Threads:	7
SigQ:	0/3839
SigPnd:	0000000000000000
ShdPnd:	0000000000000000
SigBlk:	fffffffc33f83a00
SigIgn:	0000000000000000
SigCgt:	fffffffc7fc3feff
CapInh:	0000000000000000
CapPrm:	0000000000000000
CapEff:	0000000000000000
CapBnd:	000001ffffffffff
CapAmb:	0000000000000000
NoNewPrivs:	0
Seccomp:	0
Seccomp_filters:	0
Speculation_Store_Bypass:	thread vulnerable
SpeculationIndirectBranch:	conditional enabled
Cpus_allowed:	3
Cpus_allowed_list:	0-1
Mems_allowed:	00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000000,00000001
Mems_allowed_list:	0
voluntary_ctxt_switches:	7
nonvoluntary_ctxt_switches:	0
```

**Comment by junegunn** [comment]
> VmRSS:	    3164 kB
So this is obviously not a memory issue.

Any output on CTRL-\?

**Comment by avatar-lavventura** [comment]
no output on `CTRL-` , `CTRL-r` , `CTRL-?`, `history | fzf` , `fzf`

**Comment by junegunn** [comment]
> no output on `CTRL-` , `CTRL-r` , `CTRL-?`, `history | fzf` , `fzf`

What is `CTRL-?`?

**Comment by avatar-lavventura** [comment]
That's the combination you wrote `CTRL-\?`. Just `ctrl` followed by any character does not return any output.
