### ISSUE TITLE
Is there a way to add some additional info to each item which cant be searched? 

### ISSUE THREAD

**Issue by woshichuanqilz** [junegunn/fzf#2778]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [x] fish

## Problem / Steps to reproduce
I want to add some info for each items. For example, I have some abbrev for urls. "gm" means gmail.
I want fzf show the info like `gm gmail`, but I dont want search it word gmail. "Gmail" is something like additional info to each item. 

I check the manual find the `preview` option may some thing like this. But the `preview` option still need to pass the word "gmail" to fzf.
So how to make it.

**Comment by bfrg** [comment]
It's described in the man page, see `-n, --nth=N[,..]` option. For example:
```bash
printf "%s\n%s\n" 'gm gmail long name' 'yh yahoo some other name' | fzf -n 1
```
will restrict the search to the first field.
