### ISSUE TITLE
Support json input and output

### ISSUE THREAD

**Issue by archiif** [junegunn/fzf#2779]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [x] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

## Problem / Steps to reproduce

We already have `--read0` and `--print0` which is useful for handling paths correctly, but if you want to handle an arbitrary list of strings that can contain arbitrary characters, this isn't quite enough. So supporting json-equivalents of  `--read0` and `--print0` (`--read-json` and `--print-json`?) can potentially improve correctness for workflows that need to handle arbitrary lists.

```shell
> echo '["foo", "bar", "foobar"]' | fzf --read-json --print-json
["foo", "foobar"]
```

**Comment by junegunn** [comment]
You can use `jq` for that purpose.

```sh
echo '["foo", "bar", "foobar"]' | jq -r .[] | fzf -m | jq -nR '[inputs | select(length>0)]'
```

Reference: https://github.com/stedolan/jq/issues/563#issuecomment-404955353

**Comment by archiif** [comment]
@junegunn 
Thanks for the suggestion, but this isn't exactly what I was asking.
What I wanted was a way for `jq` to handle structured data (JSON in this case), so that you don't need to rely on simple delimiters (whether it's a newline or null-byte). This will allow users to easily handle any kind of arbitrary list of strings correctly.
For example the example you provided would not work on strings that contains newlines:
```shell
echo '["foo\n", "bar", "foobar"]' | jq -r .[] | fzf -m 
```
Subtle bugs like this can be avoided if `fzf` can parse (and output) json directly.

**Comment by junegunn** [comment]
> Subtle bugs like this can be avoided if fzf can parse (and output) json directly.

I don't know if jq can print a list delimited by null-bytes. But even if it can't, one can easily write a tool that can support that and use it with fzf. This approach conforms to the Unix philosophy and it's way more flexible than adding some limited JSON support to fzf.

**Comment by junegunn** [comment]
I see. But fzf is strictly a text filter and it's not suitable for items that contain legit null bytes. So I don't think I'm going to add the option. fzf labels itself an "interactive grep"-like program and `grep` is perfectly usable without `--print-json` and I don't hear many complaints.

**Comment by pomdtr** [comment]
If anyone is interested in a fzf-like tool based around json input/output, take a look at https://pomdtr.github.io/sunbeam
