### ISSUE TITLE
Running tests

### ISSUE THREAD

**Issue by mcprentiss** [junegunn/fzf#278]
I have looked on how to run the tests.  It is not obvious to me.
It would be good to have a few lines in the docs to help people contribute.

**Comment by junegunn** [comment]
Good point. I'll consider providing the instruction.

1. `make test` inside `src` directory for running unit tests
2. `ruby test/test_go.rb` for running integration tests

By the way, I'm not looking for active contribution as I'm thinking of freezing the feature set for the time being.
