### ISSUE TITLE
Cursor isn't hidden during writes to terminal screen

### ISSUE THREAD

**Issue by monkoose** [junegunn/fzf#2781]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [x] fish

## Problem / Steps to reproduce
Not visible just for fzf in a terminal emulator, but some related issue shows that it happens in tmux #2588, and so at the same time it happens in vim in the popup terminal window.
Steps to reproduce:
- Open vim
- for better presentation what is going on 'slowdown vim' with setting writedelay to some value for me 2 is enough `:set writedelay=2`
- Open fzf `:Files` with a preview inside vim in a popup window
https://user-images.githubusercontent.com/6261276/161395203-6a461162-a114-4994-9add-c5f8c6d09965.mp4

Bram have said that vim just let terminal app to control cursor, so it hard to do something from vim side to reduce this cursor jumps.
This doesn't happen in neovim, but as far as i know neovim's terminal just uses virtual cursor.

This visible cursor jumps happens more ofter with preview window and with colorful output i guess because it should to paste some ANSI colorcodes at some places.

Can cursor be hidden during writes to the screen?

**Comment by junegunn** [comment]
I'm aware of this "flying cursor issue". It is especially visible when you do something that involves a major redraw of the screen such as scrolling the preview window. And I've thought there was no easy fix to the problem as we would have to greatly optimize the rendering performance of fzf, which is non-trivial.

> Can cursor be hidden during writes to the screen?

But this can be an easy and effective solution to the problem. I'll see what I can do.

**Comment by junegunn** [comment]
Right, I think it looks much better. Let me know what you think.

**Comment by monkoose** [comment]
Yes, can confirm it is fixed now. At least for me i don't see any flying cursor anymore.
Thanks for so fast response.
