### ISSUE TITLE
Feature Request: Default tab completion support

### ISSUE THREAD

**Issue by deep-freeze** [junegunn/fzf#2786]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

## Problem / Steps to reproduce

I would like to be able to set _fzf_path_completion as the default function for tab completion when nothing is defined for a particular command. I tried to do this with "complete -D" but it did not work.

**Comment by junegunn** [comment]
I've decided not to add any more features to the shell extension because of the increased maintenance burden, and I'm encouraging users to build third-party projects that can be installed separately.

https://github.com/Aloxaf/fzf-tab is a good example.
