### ISSUE TITLE
how to make ripgrep fzf integration command searching both file name and content

### ISSUE THREAD

**Issue by ccshao** [junegunn/fzf#2789]
- [X] I have read through the manual page (`man fzf`)
- [X] I have the latest version of fzf
- [X] I have searched through the existing issues

## Info

- OS
    - [X] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [X] fish

I found the integration commands of ripgrep and fzf is very handy, but one thing missing for me: it could NOT search patten in file name

The codes are simpliy copied from advanced.md
```
#!/usr/bin/env bash

# 1. Search for text in files using Ripgrep
# 2. Interactively narrow down the list using fzf
# 3. Open the file in Vim
IFS=: read -ra selected < <(
  rg --color=always --line-number --no-heading --smart-case "${*:-}" |
    fzf --ansi \
        --color "hl:-1:underline,hl+:-1:underline:reverse" \
        --delimiter : \
        --preview 'bat --color=always {1} --highlight-line {2}' \
        --preview-window 'up,60%,border-bottom,+{2}+3/3,~3'
)
[ -n "${selected[0]}" ] && vim "${selected[0]}" "+${selected[1]}"

```

I saw several posts about the opposite sides, that only matches in file content are desired with fzf.vim. 

How could I modify the bash command above to search the patten in file name **and** file content?
Thanks!

**Comment by tg0h** [comment]
I couldn't get @DevAtDawn's preview  to work either ...

This is what I have (this recipe uses rg, bat and fzf)

![Screenshot 2022-04-13 at 17 14 09 - kitty@2x](https://user-images.githubusercontent.com/7954426/163142893-f6ddee94-ec9f-4055-87c9-0b579acd8b16.jpg)

```
# rg
  # --field-match-separator ' ' - tell rg to separate the filename and linenumber with spaces to play well with fzf, (when recognizing index variables to use in the fzf preview command, fzf uses a default delimiter of space, see below)

# fzf
  # --preview window ~8,+{1}-5
  #   this is a fzf feature
  #   ~8 - show first 8 lines (header)
  #   +{1} - fzf delimits the input piped in to it and provides access via index variables {n}. 
  #   the default delimiter fzf uses is space but can be specified via --delimiter <delimiter>
  #   pass the second index variable from bat (which is the line number)
  #   the number is signed, you can show eg the +n row or the -n row (the nth row from the bottom)
  #   -5 subtract 5 rows (go up 5 rows) so that you don't show the highlighted line as the first line
  #   since you want to provide context by showing the rows above the highlighted line

rg --line-number --with-filename . --color=always --field-match-separator ' '\
  | fzf --preview "bat --color=always {1} --highlight-line {2}" \
  --preview-window ~8,+{2}-5
```

**Comment by matt-entrekin** [comment]
```sh
rg --color=always --line-number --no-heading --smart-case "${*:-}" ...
```

I had an issue with the parameters being passed to ripgrep as `"${*:-}"`. Using `"${@:-}"` or simply `"$@"` allowed me to pass a search string and a pattern such as `-g '*.sh'`

**Comment by aldevv** [comment]
The options above didn't work for me so I created one that works for me
```
#!/bin/sh

_file="$(rg --color=always --line-number --no-heading --smart-case "${@:-^[^\n]}" \
    | fzf -d ':' --preview 'bat --style=numbers --color=always $(cut -d: -f1 <<< {1}) --highlight-line {2}  --line-range={2}:+20' \
    --preview-window='50%' --height='50%' --with-nth 1,3.. --exact)"

_file="${_file%%:*}"
[ -z "$_file" ] && exit
exec nvim "$_file"
```

**Comment by LangLangBart** [comment]
> I got
> 
> > [bat error]: invalid digit found in string

Likely the filepath contains a space in its name.

You could try to remove the `--field-match-separator ' '` from `rg` and add the `--delimiter :` flag to `fzf`

```bash
rg --line-number --with-filename . --color=always |
  fzf --delimiter : --preview "bat --color=always {1} --highlight-line {2}" --preview-window ~8,+{2}-5
```

**or**

You could use a `Non-Breaking Space` as a delimiter; it's very unusual to have such a character in a file path.


```bash
rg --line-number --with-filename . --color=always --field-match-separator $'\u00a0' |
  fzf --delimiter $'\u00a0' --preview "bat --color=always {1} --highlight-line {2}" --preview-window ~8,+{2}-5
```

---

| Character          | Unicode                                                             |
| ------------------ | ------------------------------------------------------------------- |
| Space              | [U+0020](https://util.unicode.org/UnicodeJsps/character.jsp?a=0020) |
| Colon              | [U+003A](https://util.unicode.org/UnicodeJsps/character.jsp?a=003A) |
| Non-Breaking-Space | [U+00A0](https://util.unicode.org/UnicodeJsps/character.jsp?a=00A0) |

<img width="700" alt="space" src="https://github.com/junegunn/fzf/assets/92653266/e26f2927-92bd-4822-ad0b-6986be435d01">

**Comment by JohanChane** [comment]
To sum up:

```sh
# Usage: rgfzf [<rg SYNOPSIS>]
function rgfzf {
  command rg --color=always --line-number --no-heading --smart-case "${*:-}" \
  | command fzf -d':' --ansi \
    --preview "command bat -p --color=always {1} --highlight-line {2}" \
    --preview-window ~8,+{2}-5
}
```

**Comment by DivineMK** [comment]
Is it possible to make ripgrep interactive as well?

**Comment by mmerbes** [comment]
```bash
function rgfzf {
  local search=""
  if [[ $# -gt 0 ]]; then
    search="$1"
    shift
  fi
  command rg --color=always --line-number --no-heading --smart-case "$@" "$search" \
  | command fzf -d':' --ansi \
    --preview "command bat -p --color=always {1} --highlight-line {2}" \
    --preview-window ~8,+{2}-5 \
  | awk -F':' '{print $1}'
}
``` 
Small tweak to @JohanChane code to allow me to pass in additional options to rg
