### ISSUE TITLE
Feature request: Keep selection after `clear-query` (to see original context of filtered lines)

### ISSUE THREAD

**Issue by AXGKl** [junegunn/fzf#2792]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [x] Mac OS X
    - [x] Windows
    - [x] Etc.
- Shell
    - [x] bash
    - [x] zsh
    - [x] fish

## Problem / Steps to reproduce

Use Case:

- a) filter ('search') a list by entering a query
- b) have matches
- c) then I want to see the **context** of those matches within the **original** list.

With "context" I mean the items around, within the original list. Use cases where this is needed:

- git logs
- log file analysis
- (...)

c) is currently not possible, imho(?) - because whenever the filter is removed the original list is shown with different items in the viewport. If the filtered items had been selected, then that selection is kept after removing the filter - but there is no way to jump to them[^1]

## Suggested Solution

A new action, e.g. `toggle-query`, which:

- a) unapplies the current filter on the list, i.e. shows the original list (like `clear-query`) but
- b) jumps or keeps the item which was marked or even selected while the list was filtered 
- c) [user can move around normally with arrow keys to inspect the non matching items before and after]
- d) Invoking that toggle action again then reapplies the original filter
- e) Nice to have: If possible mark the item, which was marked while the toggle was applied the first time 

To illustrate:

![2022-04-15_](https://user-images.githubusercontent.com/9989548/163564404-87353015-0889-4a8e-b02b-52a71e05c499.png)

```bash
( echo -e 'start\nfoo\nbar\nfoobar\nbaz\nend' ) | fzf
```

![2022-04-15__000](https://user-images.githubusercontent.com/9989548/163564448-c1502229-dc42-461b-b70b-eb599a609d74.png)

user filtered and marked the second item, "foobar".

![2022-04-15__001](https://user-images.githubusercontent.com/9989548/163564497-6186bbf9-2477-44aa-b27a-d54d6fa471ce.png)

`toggle-query` action was invoked => filter was unapplied - **but fzf jumped to the marked item / kept the selection** (the new feature). Maybe the original query could be still shown - greyed out.

![2022-04-15__002](https://user-images.githubusercontent.com/9989548/163564608-fc745ec7-a308-4263-8672-d678619935d6.png)

`toggle-query` action was invoked again => original query applied.

Nice to have (e): Marked item marked in the filtered list (so user can inspect next one):

Imho, this would also solve a lot of problems where fzf is run multiple times in a loop - where one wants to recreate the selection state from the last run, so user can do something on the next item, w/o having the find the previous one first.

So the request might solve also these:

- https://github.com/junegunn/fzf/issues/2515 "*However often after finding the commits, I'd also like to know their positions in the log graph.*"
- https://github.com/junegunn/fzf/issues/924: fzf would be started with the query matching the wanted row(s) - then user toggles query  off and has the desired behaviour. 
- https://github.com/junegunn/fzf/issues/883: "*It will allow to process flawlessly list of fzf entries one by one.*"

[^1]: Edit: Skimming through PRs I see that this one provides the possibility to jump through selected items: https://github.com/junegunn/fzf/pull/2749.  With this and bindings for `select-all+clear-query` and `next-selected`, the process of inspecting matching items within their original context would be straight forward and efficient.

**Comment by junegunn** [comment]
To be honest, it's really hard for me to tell what the feature does and what it is for from its name `toggle-query`.

> then I want to see the context of those matches within the original list.

You can use `--preview-window` for that.

```sh
git log --oneline --color=always | nl |
  fzf --with-nth 2.. --ansi --reverse
        --preview 'bat --style=numbers --highlight-line={1} --color=always <(git log --oneline --color=always)' --preview-window '+{1}/2'
```

If you're running it on a repository with a long commit history, you might want to avoid running `git log` over and over again, so:

```sh
git log --oneline --color=always > /tmp/list

nl /tmp/list | fzf --with-nth 2.. --ansi --reverse \
    --preview 'bat --style=numbers --highlight-line={1} --color=always /tmp/list' \
    --preview-window '+{1}/2'
```

I believe this approach is good enough for your use case and we don't really need a sophisticated feature that isn't very straightforward.

**Comment by AXGKl** [comment]
Stumble over this one again, maybe you still see it, though closed.

**The** use case for the feature really is log analysis. You know some strange behaviour of an application is occurring around a certain message in the log, so you filter for it. Maybe it's only a timestamp which you have as original hint where to start your search.
The preview window is occupied already, with the full content of the log messages.
Then you want to understand what the app did next, i.e. go to next, next, next, (...) logline and always see the full logged data in the preview window.
That is currently not possible in fzf, imho.
