### ISSUE TITLE
Feature Request: --subheading-pattern

### ISSUE THREAD

**Issue by DanielHeath** [junegunn/fzf#2793]
- [X] I have read through the manual page (`man fzf`)
- [X] I have the latest version of fzf
- [X] I have searched through the existing issues

## Info

- OS
    - [X] Linux
- Shell
    - [X] bash

## Subheadings

`--header-lines` is useful to give context on the available options. 

However, when the available options can be naturally grouped into sub-sections, it would be nice to show the sub-sections (for context) without having them be selectable.

Example input:
```
Select target instance.
Version 3859 (current)
AZ us-east-1d (3 running)
 * 34.235.124.113 (i-08f6447df7733b864)
 * 3.80.53.196 (i-0a01082ee173f1124)
 * 54.86.100.119 (i-09e581b6e7a33b2ba)
AZ us-east-1a (3 running)
 * 3.91.40.165 (i-092d58f49ac915fe5)
 * 3.86.10.49 (i-0d00c27887a6e5c3b)
 * 54.145.188.24 (i-09d8fd3a690bb938b)
Version 3858 (past)
AZ us-east-1d (3 running)
 * 54.147.55.165 (i-03111cc05b623143b)
 * 54.221.180.250 (i-0b3e542f3e632b6f0)
 * 107.23.116.0 (i-00e064f54eca3e688)
AZ us-east-1a (3 running)
 * 3.93.43.222 (i-05b2d995f02e27d3a)
 * 34.235.141.17 (i-0a2418bf72677ab1a)
 * 18.209.105.87 (i-09ed131c2946e9a8c)
```

Example invocation: `fzf --no-sort --phony --header-lines 1 --subheading-pattern "(Version|AZ)"`

I'd like adding `--subheading-pattern` to prevent selection of the matching lines (as though they were headings), but keep them visible above any group of matching entries.

**Comment by junegunn** [comment]
fzf was strictly designed to be a high-performance, line-based text filter, trying to do anything beyond that will greatly increase the overall complexity of the implementation. So this is not something I would add to fzf.

An easy, straightforward solution would be to tabularize your input like so

```
  Version | AZ         | Address
  ------- | ---------- | ------------------------------------
* 3859    | us-east-1d | 34.235.124.113 (i-08f6447df7733b864)
* 3859    | us-east-1d | 3.80.53.196 (i-0a01082ee173f1124)
* 3859    | us-east-1d | 54.86.100.119 (i-09e581b6e7a33b2ba)
* 3859    | us-east-1a | 3.91.40.165 (i-092d58f49ac915fe5)
* 3859    | us-east-1a | 3.86.10.49 (i-0d00c27887a6e5c3b)
* 3859    | us-east-1a | 54.145.188.24 (i-09d8fd3a690bb938b)
  3858    | us-east-1d | 54.147.55.165 (i-03111cc05b623143b)
  3858    | us-east-1d | 54.221.180.250 (i-0b3e542f3e632b6f0)
  3858    | us-east-1d | 107.23.116.0 (i-00e064f54eca3e688)
```
