### ISSUE TITLE
complete | grep _fzf not working on zsh

### ISSUE THREAD

**Issue by 1Mark** [junegunn/fzf#2794]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

## Problem / Steps to reproduce
First issue
```
complete | grep _fzf
```
Returns nothing, unless I open a new bash shell using the bash command.

The reason why I was running this is that I wanted fzf support for `kubectl`

but running this command from [Fuzzy completion for bash and zsh -> Supported Commands](https://github.com/junegunn/fzf#supported-commands)
```
_fzf_setup_completion path ag git kubectl
```

returns 
```
zsh: command not found: _fzf_setup_completion
```

So how do I setup fzf for kubectl?

**Comment by junegunn** [comment]
> Supported commands
>
> **On bash**, fuzzy completion is enabled only for a predefined set of commands ...

It's only for bash.

On zsh, fuzzy completion is not enabled per command, but fzf-completion widget is bound to TAB key.

```
$ bindkey | grep fzf-completion
"^I" fzf-completion
```

So `kubectl **<tab>` will work, though it will just list file paths, not kubectl-specific options.
