### ISSUE TITLE
fzf not working in git bash windows 10

### ISSUE THREAD

**Issue by ghost** [junegunn/fzf#2798]
- [x ] I have read through the manual page (`man fzf`)
- [ x] I have the latest version of fzf
- [ x] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [ ] Mac OS X
    - [x ] Windows
    - [ ] Etc.
- Shell
    - [ x] bash
    - [ ] zsh
    - [ ] fish

## Problem / Steps to reproduce
Installation via scoop.
scoop install fzf
It's working out of box for cmd/powershell but on git bash all I can do is fzf --help
 When i use fzf in git-bash it seems to start but nothing happens.

**Comment by DanSM-5** [comment]
I saw that behavior on the default git bash terminal. I'd suggest you to use a different terminal like `windows terminal`.

**Comment by sindrom91** [comment]
I am also experiencing this issue.

**Comment by sakirmohammad** [comment]
I found the solution, fzf not wroking on git bash
but you can use
```sh
winpty fzf
```
or in .bashrc file for git bash (idk if it exist or not)
```sh
alias fzf  ="winpty fzf"
```

**Comment by knutze** [comment]
I am working on this issue in MSYS2 + mintty environment.

winpty solves the problem when stdin is a tty, but hangs when stdin is a pipe (same as #2255).
This means that the CTRL+R and CTRL+T functions provided by key-bindings.bash are not available.

I am trying the following wrappers and so far they are working fine in my environment.

```sh
fzf_winpty=~/.fzf/bin/fzf-winpty
cat >"${fzf_winpty}" <<'EOF'
#!/usr/bin/env bash
set -eo pipefail

prefix="$(basename "${BASH_SOURCE:-$0}")-${UID:-$(id -u)}"
tmpdir=$(mktemp -dp "${TMPDIR:-/tmp}" "${prefix}.XXXXX")
trap "rm -rf -- '${tmpdir}'" EXIT

args=
[[ $# -ge 1 ]] && args=$(printf ' %q' "$@")

if [[ -t 0 ]]; then
  winpty </dev/tty >/dev/tty -- bash -c \
    "command fzf${args} >'${tmpdir}'/output"
  cat "${tmpdir}"/output
else
  cat - >"${tmpdir}"/input
  winpty </dev/tty >/dev/tty -- bash -c \
    "command fzf${args} <'${tmpdir}'/input >'${tmpdir}'/output"
  cat "${tmpdir}"/output
fi
EOF
chmod +x "${fzf_winpty}"
fzf() { "${fzf_winpty}" ; }
```

**Comment by Konfekt** [comment]
Thank you @knutze. Could not a check such as 

```sh
if [ "$TERM_PROGRAM" = "mintty" ]; then
  fzf() { "${fzf_winpty}" "$@" ; }
fi
```

be made part of the shell setup of `fzf` ?
