### ISSUE TITLE
Does fzf have shell completion for itself?

### ISSUE THREAD

**Issue by Freed-Wu** [junegunn/fzf#2808]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

## Problem / Steps to reproduce

I press `fzf --<Tab>` in the terminal and found no completions. Does fzf have shell completion for itself?

**Comment by junegunn** [comment]
We only have that for bash. But even that is not well-maintained.

https://github.com/junegunn/fzf/blob/0d06c28b1943e820440cff9182a0ae3bdd5e3c59/shell/completion.bash#L65

**Comment by Freed-Wu** [comment]
Why not use <https://jmtirado.net/shell-completion-with-cobra-and-go/> to generate shell completion automatically? <https://github.com/cli/cli/blob/cf4b73ff958b272cf3c9c0cf9351459f76b793a0/pkg/cmd/completion/completion.go> is an example.

**Comment by Freed-Wu** [comment]
Why not use <https://jmtirado.net/shell-completion-with-cobra-and-go/> to generate shell completion automatically? <https://github.com/cli/cli/blob/cf4b73ff958b272cf3c9c0cf9351459f76b793a0/pkg/cmd/completion/completion.go> is an example.

Can we reopen this issue as a feature request?

Related issue: https://github.com/lotabout/skim/issues/439
