### ISSUE TITLE
how to remove the single-quoted of the placeholder expression ({q})

### ISSUE THREAD

**Issue by SadSock** [junegunn/fzf#2809]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [x] fish

## Problem / Steps to reproduce

```
RG_PREFIX="rg --column --line-number --no-heading --color=always --smart-case "
INITIAL_QUERY=""
FZF_DEFAULT_COMMAND="$RG_PREFIX '$INITIAL_QUERY'" \
  fzf --bind "change:reload:$RG_PREFIX {q} || true" \
      --ansi --phony --query "$INITIAL_QUERY"
```

I want to use parameter of rg, such as "--type", in interactive mode.

**Comment by junegunn** [comment]
You can use `eval` to build the command string. i.e. `eval "$RG_PREFIX" {q}`
