### ISSUE TITLE
[neovim] Terminal window fails to close with 'up'/'left' option

### ISSUE THREAD

**Issue by noahfrederick** [junegunn/fzf#281]
In Neovim, calling `fzf#run()` with the `'up'` or `'left'` options results in the terminal window not closing when fzf exits (either by accepting an item or hitting ESC). Using `'down'` or `'right'` instead works as expected.

I can reproduce the issue using [this example from the wiki](https://github.com/junegunn/fzf/wiki/Examples-%28vim%29#select-buffer) by changing `'down'` to either `'up'` or `'left'`.

https://github.com/junegunn/fzf/commit/355d004895eb8cb7e6ca7f8cf0b095f381d6e41b looks like it could be the culprit.

**Comment by junegunn** [comment]
Thanks for the report. I believe the above commit should fix the problem. Let me know if you see any issues.

**Comment by noahfrederick** [comment]
Confirmed fixed. Thanks.
