### ISSUE TITLE
Attaching metadata to strings

### ISSUE THREAD

**Issue by lukepighetti** [junegunn/fzf#2814]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

## Question

Is it possible to attach metadata to the strings being searched?

Consider a case where you have a bunch of key:value pairs, such as `uid`:`username`, and you're fuzzy finding for `username`, but what you really want is to get the `uid`

If we could attach `uid` as metadata to each `username`, and return the metadata upon selection, that would be very useful.

**Comment by junegunn** [comment]
Yes, with `--with-nth` (and/or `--nth`).

```sh
git log --oneline | fzf --with-nth 2.. | awk '{print $1}'

echo foo:bar | fzf --delimiter : --with-nth 2 | awk -F: '{print $1}'
```

**Comment by lukepighetti** [comment]
Works great, thank you for the assistance.
