### ISSUE TITLE
Feature request: work on old results while reload is not finished

### ISSUE THREAD

**Issue by jeanCarloMachado** [junegunn/fzf#2816]
First of all, thanks for this great tool, FZF is just awesome. 

I have a feature request for my specific [use-case](https://github.com/jeanCarloMachado/PythonSearch/blob/main/search_run/search_ui/fzf_in_terminal.py#L39). My `replace` call takes a while to finish and I would like to keep using fzf meanwhile. Nevertheless, if I try to change the query after issuing the reload it then performs the search on the new "empty still processing results" and then I get nothing. Is there a way to only do the replacement once the called process finishes?

- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

Thank you in advance!

**Comment by jeanCarloMachado** [comment]
Thank you for the feature! ❤️

**Comment by junegunn** [comment]
No problem. Please test it and let me know it doesn't work as expected.

**Comment by jeanCarloMachado** [comment]
It works! Thank you very much!
