### ISSUE TITLE
~/.bash_profile not updated on install

### ISSUE THREAD

**Issue by blakejennings** [junegunn/fzf#282]
Some developers use a ```~/.bash_profile``` instead of a ```~/.bashrc```. I think ```fzf``` should only append to the non-empty file so that the installation works automatically without manual changes needed.

**Comment by junegunn** [comment]
Thanks for the suggestion, but I'm going to keep it simple and leave it as it is. It's a common practice to source .bashrc from .bash_profile.

http://superuser.com/questions/789448/choosing-between-bashrc-profile-bash-profile-etc

> ~/.bash_profile should be super-simple and just load .profile and .bashrc (in that order)

http://superuser.com/questions/183870/difference-between-bashrc-and-bash-profile

> ~/.bashrc is the place to put stuff that applies only to bash itself, such as alias and function definitions, shell options, and prompt settings. (You could also put key bindings there, but for bash they normally go into ~/.inputrc.)

http://mywiki.wooledge.org/DotFiles

> You should therefore always have source ~/.bashrc at the end of your .bash_profile in order to force it to be read by a login shell.
> Why is .bashrc a separate file from .bash_profile, then? There are a couple reasons. The first is performance -- when machines were extremely slow compared to today's workstations, processing the commands in .profile or .bash_profile could take quite a long time, especially on machines where a lot of the work had to be done by external commands (before Korn/Bash shells). So the difficult initial set-up commands, which create environment variables that can be passed down to child processes, are put in .bash_profile. The transient settings and aliases/functions which are not inherited are put in .bashrc so that they can be re-read by every subshell.
