### ISSUE TITLE
FZF prompt - Pre-select first option instead of the last

### ISSUE THREAD

**Issue by snowman** [junegunn/fzf#2827]
- [X] I have read through the manual page (`man fzf`)
- [X] I have the latest version of fzf
- [X] I have searched through the existing issues

## Info

- OS
    - [X] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [X] zsh
    - [ ] fish

## Problem / Steps to reproduce
In the FZF prompt, is there a way to pre-select the first option instead of the last?

Current behavior:
![image](https://user-images.githubusercontent.com/16096559/169267921-dc94fec6-e718-41dc-a89e-3641befb0428.png)

Desired behavior:
![image](https://user-images.githubusercontent.com/16096559/169267983-2ad195ee-94e4-4bd1-a143-9f5598512064.png)

mirror issue: https://github.com/junegunn/fzf.vim/issues/858

**Comment by salmankhilji** [comment]
I too would like to do the same.  Perhaps either of the two may work:

1. A new command line option like `--initial-match=first,last`, where `first` is the current default.

1. A new action, similar to `change` and `backward-eof`, named `on-load` that executes whenever the finder reloads data.  This way, I could do: `--bind=on-load:last` or `--bind=on-load:first`.

**Comment by edi9999** [comment]
Any way to do this right now @junegunn ?

**Comment by junegunn** [comment]
Using `--tac`

```sh
seq 10 | fzf --tac --layout=reverse --height=~50%
seq 10 | fzf --tac --layout=reverse-list --height=~50%
```

**Comment by edi9999** [comment]
Ok thanks !! 

This issue can be closed then.
