### ISSUE TITLE
FZF preview window does not scroll a wrapped file if unwrapped file fits the screen

### ISSUE THREAD

**Issue by cpkio** [junegunn/fzf#2832]
- [X] I have read through the manual page (`man fzf`)
- [X] I have the latest version of fzf
- [X] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [ ] Mac OS X
    - [X] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [ ] fish

## Problem / Steps to reproduce

Create a file with many long strings that fit the preview window while unwrapped. No scrolling will work. Wrap the preview (by shortcut), the file will not scroll still.

Scrolling works perfectly when a file overflows preview window while unwrapped.

**Comment by junegunn** [comment]
See if b089bb5e7bdfbeb20b370731bd5ce14564df4318 helps.

**Comment by cpkio** [comment]
I cannot build from source, so I'll have to wait for the next release.
