### ISSUE TITLE
`--color=` option is bugged under certain circumstances

### ISSUE THREAD

**Issue by oredaze** [junegunn/fzf#2836]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

## Problem / Steps to reproduce

When using the alacritty terminal emulator the fzf background, that is supposed to be transparent, is not and the colors are weird. Read all of this:
It works fine under urxvt(I only use these 2 terminals). Funny part is it works fine under tmux with alacritty too, but not on bare alacritty. Under that tmux situation, the TERM variable is xterm-256color, outside it is the same. But setting different TERM variables does not help. (I think it only makes it worse, but I forgot).
Vim or no vim it makes no difference.
But wait for it, here is the most bizarre and important thing - if I remove `export FZF_DEFAULT_OPTS` from my .zprofile it is transparent, and then if I use the SAME options to launch fzf directly in the terminal it still has no issue. 
Only time I encounter the issue is when I put the options in the environment variable... AND use alacritty... AND not in tmux...
The offensive option is `-- color=`(any). It gets *ignored* under the aforementioned scenario, and the colors are neither the default, nor what I set them to.

This is as far as I could track the problem.
I REALLY want to use --color 16 because I have made my entire system adapt to my terminal colors and I am not sure if I want to use tmux or a tiling window manager. (I hop a lot)

**Comment by junegunn** [comment]
Please provide the minimal steps to reproduce the problem.
