### ISSUE TITLE
Add additional tiebreakers

### ISSUE THREAD

**Issue by mpldr** [junegunn/fzf#2837]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

## Problem / Steps to reproduce

It would seem sensible to me, to also allow the following tiebreakers:
- **beginword** Prefers lines with matching word starting letters
    - `Mozilla Thunderbird` is ranked higher than
    - `mumle-git` for input `mt`
- **sequence** Prefers lines where letters are sequential
    -  `Firefox` is ranked higher than
    -  `Forts of Iron` for input `fir`

**Comment by junegunn** [comment]
The scoring algorithm of fzf already handles both cases (the scores are not the same, so tiebreak has no effect).

```sh
$ printf 'Forts of Iron\nFirefox' | fzf -f fir | head -1
Firefox

$ printf 'Mozilla Thunderbird\nmumle-git' | fzf -f mt | head -1
Mozilla Thunderbird
```

See https://github.com/junegunn/fzf/blob/master/src/algo/algo.go
