### ISSUE TITLE
fzf - match whole word option

### ISSUE THREAD

**Issue by naviehuynh** [junegunn/fzf#284]
fuzzy search can sometimes be too easy-going and cannot filter out unwanted results, especially when the input set is large, of course we don't want extract match either because it is too strict in most cases. 
I suggest having a mode that is somewhere between fuzzy search and normal search, which will match whole words in fuzzy style:

For e.g.
`cat dog` will keep `cat and dog` but remove `can go with dog`

What do you think?

**Comment by junegunn** [comment]
For that purpose, I use [extended-search mode](https://github.com/junegunn/fzf#extended-search-mode) which allows me to selectively enable exact match by quoting search terms. e.g. `'cat dog`: exact match for `cat` and fuzzy match for `dog`. It's pretty good, you'll like it when you get used to it. (Try using it with `ALT-B`) I also suggest that you enable it by default with `export FZF_DEFAULT_OPTS='--extended'`.
