### ISSUE TITLE
Not able to use ALT-C in vim terminal with zsh

### ISSUE THREAD

**Issue by justrajdeep** [junegunn/fzf#2846]
- [ x ] I have read through the manual page (`man fzf`)
- [ x ] I have the latest version of fzf
- [ x  ] I have searched through the existing issues

## Info

- OS
    - [ x ] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ x ] zsh
    - [ ] fish

## Problem / Steps to reproduce

I am not able to get `ALT+C` to work in vim `:terminal`

vim version: 8.2.3582
zsh version: 5.7.1 (x86_64-pc-linux-gnu)

Steps:

- Launch gvim

- Open a terminal by using the command `:terminal`

- explicitly set zsh by running `zsh`

- `ALT+C` does not open the completion menu but prints ã

Output of `tmap` command attached

    t  <Plug>(fzf-normal) * <C-\><C-N>
    t  <Plug>(fzf-insert) * <C-\><C-N>i
    t  <C-W>l      * <C-\><C-N><C-W>l
    t  <C-W>k      * <C-\><C-N><C-W>k
    t  <C-W>j      * <C-\><C-N><C-W>j
    t  <C-W>h      * <C-\><C-N><C-W>h
    t  <M-Up>      * <C-W>k
    t  <M-Down>    * <C-W>j
    t  <M-Left>    * <C-W>l

**Comment by junegunn** [comment]
This is not an issue of fzf itself. You have to figure out how to make the built-in terminal of GVim send `Esacpe-*` instead of `Meta-*` when you press `ALT-*`.

(Distantly) related: https://github.com/junegunn/fzf/search?q=escape+meta+alt&type=issues
