### ISSUE TITLE
Selection is sometimes not cleared

### ISSUE THREAD

**Issue by salmankhilji** [junegunn/fzf#2849]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

## Problem / Steps to reproduce

With the `last` action executed, `fzf` fails to reset selection if a query is specified and then later cleared.

1. Launch `fzf` like this:
    ```sh
    { echo $'npm1\nnpm2\nnpm3'; seq 3; } | fzf --tac --bind=home:last
    ```

2. Press **Home** key to move selection to the first entry.

3. Type `npm` as the query.

4. Press **Delete** key 3 times (or `Ctrl+u`) to clear the query.

## Observed Behavior

Fourth line, i.e. **1** is selected.

## Expected Behavior

The very first (oldest input in this case) shall be selected.

## Notes

This issue also reproduces if the selection is changed using the arrow keys in **Step 2**.

```
$ fzf --version
0.30.0 (2093667)
```

**Comment by junegunn** [comment]
fzf wasn't designed to work that way. The cursor simply stays at the same vertical position if possible regardless of the query string.
