### ISSUE TITLE
Feature Request: Make fzf preview handle mime/file types

### ISSUE THREAD

**Issue by PlasmaHH** [junegunn/fzf#2855]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [ ] fish

## Problem / Steps to reproduce

My current fzf config contains for the preview reasons this abomination: 

```
FZF_DEFAULT_OPTS="--inline-info --bind page-up:preview-up,page-down:preview-down --height=60% --preview '[[ \$(file --mime {}) =~ image/ ]] && file -L {}; catimg -w 240 {} || ( [[ \$(file --mime {}) =~ binary ]] && echo {} is a binary file: \$(file -L {}) || ( bat --style=numbers,changes,header-filesize -f --line-range :${PREVIEWLINES} {} || cat {} ) ) 2> /dev/null | head -'$PREVIEWLINES "

```
which basically for text files invokes bat, for images invokes catimg and for all other binaries invokes file ...
Now I wanted to extend this but it quickly becomes a mess... now of course I could write me a script to wrap all this or something, but I thought it might be nicer for not too coplex cases if one could do this "natively" within fzf.

Ideas are that one could chose for file endings (or matches) like --preview-png <cmd> or --preview-jp*g <cmd> or so, or maybe silently invoke file to get a mime type and then --preview=image/ <cmd> to match the mime type substring?

**Comment by junegunn** [comment]
> now of course I could write me a script to wrap all this or something

This is the way to go. It conforms to the Unix philosophy; it is much more flexible, extensible, and customizable than fzf implementing a few options.
