### ISSUE TITLE
Ubuntu 20.04: Cannot build 0.30.0

### ISSUE THREAD

**Issue by inkarkat** [junegunn/fzf#2856]
- [X] I have read through the manual page (`man fzf`)
- [X] I have the latest version of fzf
- [X] I have searched through the existing issues

## Info

- OS
    - [X] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [X] bash
    - [ ] zsh
    - [ ] fish

## Problem / Steps to reproduce

I'm trying to upgrade from 0.29.0 to 0.30.0, on Ubuntu 20.04 64-bit.

The former compiles just fine:

    $ git co 0.29.0
    HEAD is now at dc975e8 0.29.0
    $ make
    fatal: ref HEAD is not a symbolic ref
    GOARCH=amd64 go build -a -ldflags "-s -w -X main.version=0.29.0 -X main.revision=dc975e8" -tags "" -o target/fzf-linux_amd64
    $ target/fzf-linux_amd64  --version
    0.29.0 (dc975e8)

But 0.30.0 reports errors in `src/tui/tcell.go`:

    $ git co 0.30.0
    Previous HEAD position was dc975e8 0.29.0
    HEAD is now at 2093667 0.30.0
    $ make
    fatal: ref HEAD is not a symbolic ref
    GOARCH=amd64 go build -a -ldflags "-s -w -X main.version=0.30.0 -X main.revision=2093667" -tags "" -o target/fzf-linux_amd64
    # github.com/junegunn/fzf/src/tui
    src/tui/tcell.go:18:6: HasFullscreenRenderer redeclared in this block
            previous declaration at src/tui/dummy.go:7:30
    src/tui/tcell.go:27:6: Attr redeclared in this block
            previous declaration at src/tui/dummy.go:5:6
    src/tui/tcell.go:75:2: Bold redeclared in this block
            previous declaration at src/tui/dummy.go:20:19
    src/tui/tcell.go:76:2: Dim redeclared in this block
            previous declaration at src/tui/dummy.go:21:24
    src/tui/tcell.go:77:2: Blink redeclared in this block
            previous declaration at src/tui/dummy.go:24:24
    src/tui/tcell.go:78:2: Reverse redeclared in this block
            previous declaration at src/tui/dummy.go:26:24
    src/tui/tcell.go:79:2: Underline redeclared in this block
            previous declaration at src/tui/dummy.go:23:24
    src/tui/tcell.go:80:2: Italic redeclared in this block
            previous declaration at src/tui/dummy.go:22:24
    src/tui/tcell.go:84:2: AttrUndefined redeclared in this block
            previous declaration at src/tui/dummy.go:16:23
    src/tui/tcell.go:85:2: AttrRegular redeclared in this block
            previous declaration at src/tui/dummy.go:17:28
    src/tui/tcell.go:85:2: too many errors
    make: *** [Makefile:130: target/fzf-linux_amd64] Error 2
    $ go version
    go version go1.13.8 linux/amd64

**Comment by inkarkat** [comment]
Just noticed that the `0.30.0` tag isn't contained in master, and that the `devel` branch was tagged - why do you do that? `0.30.0` is listed on the GitHub releases page, though.

Latest `devel` (https://github.com/junegunn/fzf/commit/70529878e20cf0367ca25b0aa9dbf1f51062f5e0) doesn't compile, neither.

**Comment by junegunn** [comment]
Can you try upgrading your Go version? 

https://github.com/junegunn/fzf/blob/master/BUILD.md#prerequisites

**Comment by inkarkat** [comment]
Ubuntu 22.04 provides golang 1.18; it compiles just fine there. Though I'm still mostly on Ubuntu 20.04, I can live with doing a fzf update in a VM; the binary also works on the older Linux distro.

So the only issue was that the dependency wasn't updated yet in the 0.30.0 version - but it's correct now. Closing; thanks for this useful tool!

**Comment by junegunn** [comment]
Thanks, and thank you for your contribution to Vim ecosystem. Your ReplaceWithRegister is one of my favorite Vim plugins that I use almost every day 👍
