### ISSUE TITLE
Make fzf-cd-widget not conflict with user defined functions

### ISSUE THREAD

**Issue by luis-guimaraes-exoawk** [junegunn/fzf#2859]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

## Problem / Steps to reproduce
The fzf-cd-widget uses `builtin cd` but still conflicts with custom functions called `cd`. I don't understand why, as when I ran `builtin cd -- $dir` manually, like in the `fzf_cd_widget`, it doesn't conflict...

Thanks

**Comment by obvionaoe** [comment]
Hey @junegunn , please reopen as that pull request did not actually fix the issue... My issue was created after that pull request was closed, and I'm still having the same problem
