### ISSUE TITLE
[bash] <Ctrl-R> not working

### ISSUE THREAD

**Issue by jpcirrus** [junegunn/fzf#286]
Using bash with either `set +o histexpand` or `set +H` to turn off csh style history substitution, fzf no longer expands the returned history item since b4a05ff. This is the same issue as with zsh in #214. Possibly a similar fix could be made by testing for `H` in the bash variable `$-`, something like:

    [[ $- == *H* ]]; oldH=$?  # Save -H state
    set -H                    # Enable ! history substitution
    # history expansion code
    (( $oldH )) && set +H     # Reset -H if necessary
    unset -v oldH             # Clean up

assuming `shopt -u nocaseglob`

**Comment by junegunn** [comment]
Thanks for the report. For zsh (#214), the code was later updated again to use `vi-fetch-history` instead of temporarily setting the option (see #272). I wonder if a similar trick is available for bash.

**Comment by jpcirrus** [comment]
`vi-fetch-history` is available in bash's readline, but in quick testing I couldn't get it to accept the history number as an argument. Interactively, with `set -o vi`, entering command mode, the history number and then `G` (it's default key-binding) it works.

**Comment by junegunn** [comment]
Hmm, that's unfortunate. Then I currently have no idea how we should restore the setting since in order to do that, we'll have to invoke another `shell-expand-line` which will cause unwanted expansion of the pasted command (e.g. `echo $PATH`)

We could fall back to the old method used before b4a05ff27ed8b1371dc3745ce02f48430345761b only when `histexpand` is not set, but then we'll not be able to handle multi-line commands.

**Comment by jpcirrus** [comment]
I'll have another look at trying to get `vi-fetch-history`working over the weekend when I have some time. Will come back with the result.

**Comment by jpcirrus** [comment]
I haven't been able to get `vi-fetch-history` to work in emacs mode, nor been able to set`histexpand`  without polluting the environment, so I think your suggestion when `histexpand` is not set to revert back to the behaviour prior to b4a05ff is the way to go, as at least recalling single-line history commands will work, which doesn't currently.

**Comment by junegunn** [comment]
Okay, thanks for looking into it. So what do you think about the following? Seems to do the trick.

```sh
__fzf_history__() {
  local line
  line=$(
    HISTTIMEFORMAT= history |
    $(__fzfcmd) +s --tac +m -n2..,.. --tiebreak=index --toggle-sort=ctrl-r |
    \grep '^ *[0-9]') &&
    if [[ $- =~ H ]]; then
      sed 's/^ *\([0-9]*\)\** .*/!\1/' <<< "$line"
    else
      sed 's/^ *\([0-9]*\)\** *//' <<< "$line"
    fi
}
```

**Comment by jpcirrus** [comment]
In `$-` lowercase "h" could be present for `hashall` so we need to make the pattern match case sensitive. We can either put the function body in a subshell with the 2 required shell options so we don't pollute the environment, or we could save their status, change to what we require, and restore at the end of the function.

```bash
__fzf_history__() (
  local line
  shopt -u nocaseglob nocasematch
  line=$(
    HISTTIMEFORMAT= history |
    $(__fzfcmd) +s --tac +m -n2..,.. --tiebreak=index --toggle-sort=ctrl-r |
    \grep '^ *[0-9]') &&
    if [[ $- =~ H ]]; then
      sed 's/^ *\([0-9]*\)\** .*/!\1/' <<< "$line"
    else
      sed 's/^ *\([0-9]*\)\** *//' <<< "$line"
    fi
)
```

```bash
__fzf_history__() {
  local line old_shopt
  old_shopt=$(shopt -p nocaseglob nocasematch)
  shopt -u nocaseglob nocasematch
  line=$(
    HISTTIMEFORMAT= history |
    $(__fzfcmd) +s --tac +m -n2..,.. --tiebreak=index --toggle-sort=ctrl-r |
    \grep '^ *[0-9]') &&
    if [[ $- =~ H ]]; then
      sed 's/^ *\([0-9]*\)\** .*/!\1/' <<< "$line"
    else
      sed 's/^ *\([0-9]*\)\** *//' <<< "$line"
    fi
  eval "$old_shopt"
}
```

I confirm that both work for various combinations of `hashall` and `histexpand`.

**Comment by junegunn** [comment]
Great point, thanks! I never knew about `nocasematch` nor `nocaseglob` :(
By the way, is `nocaseglob` required in this case?

**Comment by junegunn** [comment]
Nevermind, you're right that both need to be unset.

**Comment by junegunn** [comment]
I applied your patch and pushed to master. Thanks. Although we can't still handle multi-line commands properly, I'm going to close the issue as it seems unlikely to me that we'll find the perfect solution in a near future.

(I'm not quite sure yet why travis build is failing but it's unrelated to the change)
