### ISSUE TITLE
regex tokenizer bug: ^ interpreted repeatedly

### ISSUE THREAD

**Issue by pyglot** [junegunn/fzf#2861]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

## TLDR

In src/tokenize.go in func Tokenize() the FindStringIndex() method is reapplied to the text for every match. Therefore the caret character ^ is allowed to match again for every new match.

I suggest to use the FindAllStringIndex() method instead unless a rewrite does not impact performance too much. 

## Problem / Steps to reproduce

I found an unexpected behavior when trying to debug why my regex wasn't executing correctly. The full regex was `'(^\s*|\s+)'` which I intended to safely gobble up leading whitespace, or delimit on space otherwise. 

The following bash command lines show the issue :

```bash
# unexpected behavior 
history 5 | bin/fzf --delimiter '(^\s*|\s+)' --preview 'echo {1} - {2} - {3}'

# desired behavior of caret, but it shouldn't be so ... 
history 5 | bin/fzf --delimiter '(\^\s*|\s+)' --preview 'echo {1} - {2} - {3}'
```

I added a debug output statement to delimiterRegexp() in `src/options.go`, which confirmed that `'(^\s*|\s+)'` was compiled as a regex and not a str. 

By pure random guess I found that escaping the caret worked, so the expression `'(\^\s*|\s+)'` matches the start of the line and leading whitespace. I don't fully understand why. 

Looking at the goland regexp package it seems the syntax is specified here https://github.com/google/re2/wiki/Syntax however also here there is no mention of using an escaped \^. 

I found another anomaly in the following one-liner. Here the caret is at the start of the regex but it seemed to be simply ignored as this regex matches also on empty characters anywhere in the string :

```bash
# unexpected behavior 
history 5 | bin/fzf --delimiter '^\s*' --preview 'echo {1} - {2} - {3}'
```

Digging into Tokenize() from src/tokenizer.py I see that the method FindStringIndex() is used repeatedly, and this is probably the reason for the strange caret behavior.

https://github.com/junegunn/fzf/blob/51fdaad002a5ad827bd5ebfac43386592005d02c/src/tokenizer.go#L156-L169

I see there is a FindAllStringIndex() method that might help to resolve this issue ( https://pkg.go.dev/regexp#Regexp.FindAllIndex ). Perhaps it could lead to a performance benefit, but if it's detrimental another resolution might be to use it only if the regex string contains a '^' character.

**Comment by junegunn** [comment]
Thanks for the report. I updated the code to use FindAllStringIndex.
