### ISSUE TITLE
[FR] add support for ctrl-shift-[*]

### ISSUE THREAD

**Issue by mmahmoudian** [junegunn/fzf#2867]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues -> [example](https://github.com/junegunn/fzf/issues?page=2&q=is%3Aissue+ctrl-shift)

## Feature Request

At the moment in version 0.30.0 (latest) under the "AVAILABLE KEYS" section of the manpage there are many options listed (including `shift-[arrows]`, `ctrl-alt-[a-z]`, `alt-shift-[arrows]`, `alt-[*]` which is case sensitive), but I couldn't manage to find an answer for why, `ctrl-shift-[*]` is not accepted (perhaps not implemented). For example:

```console
❯ fzf --bind='ctrl-shift-n:half-page-down'
unsupported key: ctrl-shift-n
```

It would be super nice and handy if we can either have `ctrl-shift-[*]` or at least `ctrl-[a-zA-Z]`.

Thanks for this amazing software. It has really improved my workflow.

**Comment by junegunn** [comment]
Terminals can't differentiate between` ctrl-shift-*` and `ctrl-*`; they register identical byte sequences. This is a small Ruby code that confirms that.

```ruby
#!/usr/bin/env ruby
# frozen_string_literal: true

require 'io/console'

$stdout.sync = true

printf("\e[?1000h\e[?1006h")
loop do
  chars = $stdin.getch + ($stdin.read_nonblock(1024) rescue '')
  break if [3, 4, 26].map(&:chr).include?(chars)

  p chars
end
```

**Comment by bigH** [comment]
FYI, I have found this to not be true. For example, open `nvim` (I'm using iTerm2 to run it), and in insert mode:
- press `Ctrl-V`, then press `Alt-Shift-R` - `nvim` will show `<M-R>`
- press `Ctrl-V`, then press `Alt-R` - `nvim` will show `<M-r>`

Notice that the `r` and `R` in those outputs are different. Neovim is able to pick up the difference.

It's possible different terminal emulators support this differently and I understand the complexity that creates. However, this seems useful despite that complexity. It opens up more flexibility in `fzf` and enables better key-bindings when the relationship between a shifted and non-shifted key-stroke makes sense.

**Comment by pallaswept** [comment]
I don't want to necro, but I also don't want to dupe. I'll try here, before creating a new issue duplicating this one.

> Terminals can't differentiate between` ctrl-shift-*` and `ctrl-*`; they register identical byte sequences. This is a small Ruby code that confirms that.

I don't mean to argue, but my terminal (KDE's Konsole) does, and most of the big ones (kitty, wezterm, gnome, xterm, etc, etc) do these days. I hope you'll reconsider the 'wontfix' response to this. 

Here, I run your code, and press enter, shift+enter, ctrl+enter, etc, to demonstrate that nearly all combinations are functional.
```
> ./test.ruby
"\r"
"\e[13;2u"
"\e[13;5u"
"\e[13;1u"
"\e[13;3u"
"\e[13;6u"
"\e[13;4u"
"\e[13;7u"
"\e[13;8u"
"\r"
```

This is the behaviour described by the following proposals:
https://sw.kovidgoyal.net/kitty/keyboard-protocol
http://www.leonerd.org.uk/hacks/fixterms/

The former link is more recent and discusses the latter. I hope that will be helpful, and one day I can use ctrl+enter/shift+enter in fzf like I am enjoying elsewhere in the terminal. If I can assist in any way, please do let me know :)

**Comment by RichardFevrier** [comment]
Please consider reopening the issue @junegunn
