### ISSUE TITLE
Support reload action in g:fzf_action

### ISSUE THREAD

**Issue by lakshayg** [junegunn/fzf#2872]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [x] zsh
    - [ ] fish

## Problem / Steps to reproduce

The following command works as expected on the commandline

```
ls | fzf --height=10 --bind='ctrl-p:reload(ls -A)'
```

It has the effect of using ls until user pressed Ctrl-P which then also shows the hidden files. I want to be able to do the same thing in neovim with the basic fzf plugin instaled.

Modify neovim config to include:

```
nnoremap <silent> <C-p> :call fzf#run(fzf#wrap({'source': 'ls'}))<CR>

let g:fzf_action = {
      \ 'ctrl-p': 'reload(ls -A)',
      \ }
```

However, this does not work and just closes the FZF window.

Is there a way to accomplish this in neovim?

Note: ls and ls -A are just examples. I want to be able to do this with other commands too.

**Comment by junegunn** [comment]
`g:fzf_action` was not designed for that purpose.

You can do it like this.

```sh
nnoremap <silent> <C-p> :call fzf#run(fzf#wrap({'source': 'ls', 'options': ['--bind', 'ctrl-p:reload:ls -A']}))<CR>
```

**Comment by lakshayg** [comment]
Thanks! This worked great
