### ISSUE TITLE
Conflict with git completion

### ISSUE THREAD

**Issue by tonglil** [junegunn/fzf#288]
## Issue

In the command line, when I source the completion, it will make tabbing produce a space character.

If I type:
```
git add[tab]
```

I will get
```
git add [2 space characters here]
```

If there is a directory called "folder" and I type:
```
git add fol[tab]
```

I will get
```
git add folder/[space character here]
```

And cannot continue to tab for files in that folder because there is now a space separator there.

## Info

- fzf is installed via brew, installed HEAD today.
- OS X 10.10.4
- `git version 2.3.2 (Apple Git-55)` or `git version 2.4.5`

These are the other completes I am currently sourcing:
```sh
    # Bash Brew Completion
    if [ -f $(brew --prefix)/etc/bash_completion ]; then
      souce $(brew --prefix)/etc/bash_completion
    fi

    # Git Tab Complete
    source /usr/local/git/contrib/completion/git-completion.bash
```

**Comment by junegunn** [comment]
Thanks for the report. It's a compatibility issue with git completion. I'll see what I can do, but it may not be possible to fix it, in which case you'll have choose between the two. (install script will let you opt-out fuzzy completion)

For me `git add [2 space characters here]` is reproducible, but `git add folder/[space character here]` is not. No space is attached after the trailing slash.

**Comment by junegunn** [comment]
The fuzzy completion from fzf falls back to the original completion function that was defined on the command when the trigger sequence is not found. This works fine for most cases:

```sh
> complete | grep vim
complete -F _filedir_xspec rvim
complete -F _filedir_xspec gvim
complete -F _filedir_xspec vim
complete -F _filedir_xspec rgvim
> source ~/.fzf.bash
> complete | grep vim
complete -o bashdefault -o default -F _fzf_file_completion mvim
complete -F _filedir_xspec rvim
complete -o bashdefault -o default -F _fzf_file_completion gvim
complete -o bashdefault -o default -F _fzf_file_completion vim
complete -F _filedir_xspec rgvim
> echo $_fzf_orig_completion_vim
_filedir_xspec
```

However, this ticks doesn't work for git completion as they are defined with `-o nospace` option:

```sh
> complete | grep git
complete -o bashdefault -o default -o nospace -F __git_wrap__git_main git
complete -o bashdefault -o default -o nospace -F __git_wrap__gitk_main gitk
```

It might be possible, though it feels like a very over-engineered solution, that we remember all the previous options and dynamically restore the options using `compopt` when fzf has to fall back to the original. However, it looks like `compopt` is not available on OS X.

**Comment by tonglil** [comment]
You are right, the case you are unable to reproduce I think may come from a different type. If I can reproduce, I will update.

The thing is, the fuzzy completion (`vi FILE**`) is actually the thing I want the most when using fzf :p

**Comment by platzhirsch** [comment]
Would be really good to get that fixed, is there a customized solution/hack that I can apply locally?

**Comment by junegunn** [comment]
@platzhirsch

> For me `git add [2 space characters here]` is reproducible, but `git add folder/[space character here]` is not. No space is attached after the trailing slash.

Which problem are you having? The former (2 spaces) can be annoying but benign as it does not break the workflow, but the latter can be really problematic but I was unable to reproduce it.

I'm currently not aware of any workaround.

**Comment by platzhirsch** [comment]
Only the former one.

**Comment by junegunn** [comment]
In that case, you can simply source `git-completion.bash` after `.fzf.bash`.

**Comment by junegunn** [comment]
Hey guys, please check if the latest commit fixes the issue. Make sure to reload your whole .bashrc, not just ~/.fzf.bash.

**Comment by wzyboy** [comment]
@junegunn Nice! I tried the latest commit and trailing space no longer appears! :+1:

**Comment by tonglil** [comment]
Just wanted to say thank you @junegunn!

**Comment by octol** [comment]
I just installed fzf on all my Debian machines (3) and I'm seeing exactly this issue on all of them. Including on latest 'unstable' Debian.
