### ISSUE TITLE
"[Command failed: $FZF_DEFAULT_COMMAND]" when reloading and the variable contains spaces

### ISSUE THREAD

**Issue by matatk** [junegunn/fzf#2887]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

I found #1830 and #1408 but this seems to be a different issue.

I'm running on macOS with `zsh`, and `fzf` 0.31.0 (brew). I have run the install script and sourced `~/.fzf.zsh`.

**Summary:** when using `reload()` in conjunction with the `$FZF_DEFAULT_COMMAND` variable, I get an error if the command contains spaces. However, I can use commands that contain spaces inside `reload()` if I hard code them. I accept this may be a config issue on my end, though I am not aware of having changed any settings that might cause this to break. I also tried running these examples using `/bin/sh` and had the same problem.

I've just discovered `fzf` and it looks awesome so far; thanks!

---

When FZF_DEFAULT_COMMAND contains spaces, I get the "[Command failed: $FZF_DEFAULT_COMMAND]" when I try to reload. The [`ps` example](https://github.com/junegunn/fzf#1-update-the-list-of-processes-by-pressing-ctrl-r) fails with that error message:

```shell
FZF_DEFAULT_COMMAND='ps -ef' \
  fzf --bind 'ctrl-r:reload($FZF_DEFAULT_COMMAND)' \
      --header 'Press CTRL-R to reload' --header-lines=1 \
      --height=50% --layout=reverse
```

But if I take out the ` -ef` part, it works (in the output from `ps` I can see the time creep up for the `fzf` command, so it really is re-running the command):

```shell
FZF_DEFAULT_COMMAND='ps' \
  fzf --bind 'ctrl-r:reload($FZF_DEFAULT_COMMAND)' \
      --header 'Press CTRL-R to reload' --header-lines=1 \
      --height=50% --layout=reverse
```

I tried the same thing with `ls` just to check the problem relates to the space characters in the variable. This causes the "[Command failed: $FZF_DEFAULT_COMMAND]" error on reload:

```shell
FZF_DEFAULT_COMMAND='ls -a' \
  fzf --bind 'ctrl-r:reload($FZF_DEFAULT_COMMAND)' \
      --header 'Press CTRL-R to reload' \
      --height=50% --layout=reverse
```

...but this works:

```shell
FZF_DEFAULT_COMMAND='ls' \
  fzf --bind 'ctrl-r:reload($FZF_DEFAULT_COMMAND)' \
      --header 'Press CTRL-R to reload' \
      --height=50% --layout=reverse
```

In the `man` page, the invocation example for `reload` takes the form `<key|event>:reload:` as opposed to `<key|event>:reload()` and I'm not entirely clear on why, but trying the colon syntax didn't affect the behaviour. However the docs there referred me to this example, from #1750:

```shell
ps -ef | fzf --bind 'ctrl-r:reload(ps -ef)' --header 'Press CTRL-R to reload' \
             --header-lines=1 --layout=reverse
```

...and this one worked fine! So it must be something to do with variable expansion?

Please let me know if you need any more info.

**Comment by junegunn** [comment]
I'm a bash user, and I didn't realize that the example only works on bash.

```sh
# Works
SHELL=bash FZF_DEFAULT_COMMAND='ps -ef' \
  fzf --bind 'ctrl-r:reload($FZF_DEFAULT_COMMAND)' \
      --header 'Press CTRL-R to reload' --header-lines=1 \
      --height=50% --layout=reverse

# Fails
SHELL=zsh FZF_DEFAULT_COMMAND='ps -ef' \
  fzf --bind 'ctrl-r:reload($FZF_DEFAULT_COMMAND)' \
      --header 'Press CTRL-R to reload' --header-lines=1 \
      --height=50% --layout=reverse
```

So it boils down to

```sh
# On bash
SOME_COMMAND='echo foo'
$SOME_COMMAND
  # foo
```

vs. 

```sh
# On zsh
SOME_COMMAND='echo foo'
$SOME_COMMAND
  # zsh: command not found: echo foo
```

The solution is simple; use eval.

```sh
eval $SOME_COMMAND
  # foo
```

So you can do this:

```sh
FZF_DEFAULT_COMMAND='ps -ef' \
  fzf --bind 'ctrl-r:reload(eval "$FZF_DEFAULT_COMMAND")' \
      --header 'Press CTRL-R to reload' --header-lines=1 \
      --height=50% --layout=reverse
```

I'll consider updating the examples.
