### ISSUE TITLE
All search commands in vim fail because shellescape outputs a path incompatible with powershell

### ISSUE THREAD

**Issue by Kamholtz** [junegunn/fzf#2888]
- [ ] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [ ] Mac OS X
    - [x] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [ ] fish
    - [x] Powershell

## Problem / Steps to reproduce

All commands invoking the fzf binary except for FZF (e.g. Rg, Files, Buffers, History) cause an exception (shown below) due to not being able to determine the fzf version. 

```
Error detected while processing function fzf#vim#grep[24]..<SNR>152_fzf[1]..<SNR>152_check_requirements[11]..fzf#exec:
line   31:
E605: Exception not caught: Failed to run "fzf --version"
```

This appears to have been introduced in #2877 as it does not occur in the previous commit 3b7a962dc6db227d18faecb25c793431ce7e8640.  #2877 uses `fzf#shellescape` in `s:get_version(bin)` to produce the binary path for checking the version which seems to incompatible with powershell.

To demonstrate, the command `:echo fzf#shellescape('fzf')` produces `"^\"fzf^\""`, and `:echo systemlist(fzf#shellescape('fzf') . ' --version')` produces the following error:

```ps1
['^fzf^ : The term ''^fzf^'' is not recognized as the name of a cmdlet, function, script file, or operable program. Check \r', 'the spelling of the name, or if a path was included, verify that the path is correct and try again.\r', 'At line:1 char:82\r', '+ ... onsole]::OutputEncoding=[System.Text.Encoding]::UTF8; ^\"fzf^\" --versi ...\r', '+                                                           ~~~~~~~\r', '    + CategoryInfo          : ObjectNotFound: (^fzf^:String) [], CommandNotFoundException\r', '    + FullyQualifiedErrorId : CommandNotFoundException\r', ' \r']
```

**Comment by junegunn** [comment]
I see. What do you think we should do?

**Comment by chh-wang** [comment]
I don't understand why it need symbol ^ in the fzf#shellescape. But if I remove such symbol, it works. 

```
diff --git a/plugin/fzf.vim b/plugin/fzf.vim
index b80b7d7..412be05 100644
--- a/plugin/fzf.vim
+++ b/plugin/fzf.vim
@@ -88,7 +88,7 @@ function! s:shellesc_cmd(arg)
   let escaped = substitute(escaped, '%', '%%', 'g')
   let escaped = substitute(escaped, '"', '\\^&', 'g')
   let escaped = substitute(escaped, '\(\\\+\)\(\\^\)', '\1\1\2', 'g')
-  return '^"'.substitute(escaped, '\(\\\+\)$', '\1\1', '').'^"'
+  return '"'.substitute(escaped, '\(\\\+\)$', '\1\1', '').'"'
 endfunction
 
 function! fzf#shellescape(arg, ...)
@@ -143,7 +143,7 @@ function! fzf#install()
     if !filereadable(script)
       throw script.' not found'
     endif
-    let script = 'powershell -ExecutionPolicy Bypass -file ' . script
+    let script = 'powershell -ExecutionPolicy Bypass -file ' . fzf#shellescape(script)
   else
     let script = s:base_dir.'/install'
     if !executable(script)
```

**Comment by Kamholtz** [comment]
I was also unsure of the purpose of the `^` symbols too. From a bit of research it seems that it is an escape character in batch, but I don't think it's an escape character in powershell. I would consider conditionally including them if the shell is not powershell. I'm not really familar with viml so the following likely isn't correct, but to provide some pseudo code to demonstrate the idea:

```
let escaped = substitute(escaped, '%', '%%', 'g')
let escaped = substitute(escaped, '"', '\\^&', 'g')
let escaped = substitute(escaped, '\(\\\+\)\(\\^\)', '\1\1\2', 'g')
let quoteStr= '^"'
if (&shell == 'powershell' || &shell == 'pwsh):
  quoteStr= '"'
endif
return quoteStr.substitute(escaped, '\(\\\+\)$', '\1\1', '').quoteStr
```

That or look at a way to escape characters that is compatible in both `cmd.exe` and `powershell`.

**Comment by Kamholtz** [comment]
@chh-wang I saw this error when I removed `^` and ran `:echo systemlist(fzf#shellescape('fzf') . ' --version')`. It appears that the quotes around `fzf` are problematic. Which version of powershell are you using?

```
['At line:1 char:90
', '+ ... onsole]::OutputEncoding=[System.Text.Encoding]::UTF8; "fzf" --version
', '+                                                                   ~~~~~~~
', 'Unexpected token ''version'' in expression or statement.
', 'At line:1 char:82
', '+ ... [Console]::OutputEncoding=[System.Text.Encoding]::UTF8; "fzf" --versi ...
', '+                                                             ~~~~~
', 'The ''--'' operator works only on variables or on properties.
', '    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
', '    + FullyQualifiedErrorId : UnexpectedToken
', ' 
']
"['At line:1 char:90\r', '+ ... onsole]::OutputEncoding=[System.Text.Encoding]::UTF8; \"fzf\" --version\r', '+                                                                   ~~~~~~~\r', 'Unexpected token ''version'' in expression or statement.\r', 'At line:1 char:82\r', '+ ... [Console]::OutputEncoding=[System.Text.Encoding]::UTF8; \"fzf\" --versi ...\r', '+                                                             ~~~~~\r', 'The ''--'' operator works only on variables or on properties.\r', '    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException\r', '    + FullyQualifiedErrorId : UnexpectedToken\r', ' \r']"

```

**Comment by chh-wang** [comment]
I'm sorry, I used 'cmd' but not 'powershell' before, so I haven't notice it. 

Regarding to powershell, if the command is quoted, the command line need to change. like the format: `&'fzf' --version `, so you should be OK if you run `:echo systemlist("&'" . fzf#shellescape('fzf') . "' --version")`

The `fzf#shellescape` need to change for powershell, however, such function seems also used to escape command parameters, which is not the same rule with command. It makes a little complex to modify it, and out of my capablility right now.

**Comment by junegunn** [comment]
Does it help to use the normal `shellescape` like so?

```diff
diff --git a/plugin/fzf.vim b/plugin/fzf.vim
index b80b7d7..efae254 100644
--- a/plugin/fzf.vim
+++ b/plugin/fzf.vim
@@ -164,7 +164,7 @@ function s:get_version(bin)
   if has_key(s:versions, a:bin)
     return s:versions[a:bin]
   end
-  let command = fzf#shellescape(a:bin) . ' --version --no-height'
+  let command = shellescape(a:bin) . ' --version --no-height'
   let output = systemlist(command)
   if v:shell_error || empty(output)
     return ''
```

**Comment by chh-wang** [comment]
According to my environment, it should use `let command = '&' . shellescape(a:bin) . ' --version --no-height'` for powershell. Because shellescape return the command quoted by `'`, so it need append `&` at the beginning. 

So in my opinion, if we modify here, we'd better judge the shell first, like:
```vim
if shell == 'powershell'
  let command = '&' . shellescape(a:bin) . ' --version --no-height'
else
  let command = shellescape(a:bin) . ' --version --no-height'
endif
```

**Comment by Kamholtz** [comment]
I have confirmed that the suggestion by @chh-wang works with a small change (`&shell` instead of `shell`) for both powershell and cmd.exe on my computer. I have created pull request #2894 implementing this.

**Comment by Freedzone** [comment]
Unfortunately, the fix actually broke my fzf commands on Windows. I noticed it is related to the `shellslash` flag. If I set it in .vimrc, commands fail. If it's set after the plugin loads, it works.
