### ISSUE TITLE
fzf vim plugin prompting when swp file exists but open the file as empty in error

### ISSUE THREAD

**Issue by Masquue** [junegunn/fzf#2895]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

## Problem / Steps to reproduce

I'm still experiencing issues similar to #1365 when opening a file whose swp file already exists, but the behavior is different in that there is prompting but after choosing the option, the file is opened as empty and results in error state. `:ls` gives `x` flag on that buffer.

I guess the error may come from here:
https://github.com/junegunn/fzf/blob/ecc418ba77e52660ffdd9ed84727b12c3f377680/plugin/fzf.vim#L306-L316

The action key outputted at first line from fzf has been removed at line 306, but line 311 is still checking if `a:lines` 's length is greater than 1. Thus when selecting only 1 file, the `augroup` definition is skipped and prompting is showed to ask user for a `swapchoice`. However I don't know why after manually giving the choice, the file is opened in error state (maybe because of my other plugins).

Having tried commenting out the greater than 1 check, file can be opened successfully in read only mode.

**Comment by junegunn** [comment]
> Thus when selecting only 1 file, the `augroup` definition is skipped and prompting is showed to ask user for a `swapchoice`.

Yes, that's the intended behavior. See https://github.com/junegunn/fzf/commit/c4e5ee63bb4f68a80efd7f931b65c766281fbdea

> However I don't know why after manually giving the choice, the file is opened in error state

I can't reproduce the problem. 

> (maybe because of my other plugins).

Probably. Can you check if you still have the issue with the following minimal vimrc?

```sh
vim -Nu <(curl https://gist.githubusercontent.com/junegunn/6936bf79fedd3a079aeb1dd2f3c81ef5/raw)
```

(https://gist.githubusercontent.com/junegunn/6936bf79fedd3a079aeb1dd2f3c81ef5/raw)

**Comment by Masquue** [comment]
Using that minimal vimrc, it does successfully open a file with swp file. But there is no SwapExists prompting and the file is not opened in readonly mode. Is that expected?

**Comment by Masquue** [comment]
It seems the problem is the [coc.nvim](https://github.com/neoclide/coc.nvim) plugin. Don't really know how it interacts with fzf and causes this bug though.

**Comment by Emilv2** [comment]
I have exactly the same issue, it seems to be caused by  [vim-airline](https://github.com/vim-airline/vim-airline)  in my case.
