### ISSUE TITLE
Issues with rebinding fish keybinds and **<TAB> completion

### ISSUE THREAD

**Issue by NemoSomnium** [junegunn/fzf#2896]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [x] fish

## Problem / Steps to reproduce

Hi all, I'm trying to find a way to bind the history search function to another key combination but editing the binds in the sourced example file at /usr/share/doc/fzf/examples/key-bindings.fish with no success.
The reason for this is I'm also using mcfly for command history and I wish to have both functions available.
Also, I would appreciate help with using the **<TAB> functionality because as of now it simply prints out a lot of text and a lot of empty lines with no way to browse through them.
My third question is about adding the show hidden files and dirs function into the keybinded functions for fzf.

Thanks a lot in advance.

**Comment by junegunn** [comment]
> using the ** functionality

We don't provide that for fish. Only bash and zsh.

> adding the show hidden files and dirs function into the keybinded functions for fzf

See https://github.com/junegunn/fzf#key-bindings-for-command-line.
Also related: https://github.com/junegunn/fzf/issues/337
