### ISSUE TITLE
Latest update breaks mouse input in zsh backward search

### ISSUE THREAD

**Issue by manfred3000** [junegunn/fzf#2900]
- [ ] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

## Problem / Steps to reproduce

Arch Linux with `zsh` v5.9 and `fzf` v0.31

After the latest update of `fzf` mouse input is "off" without a predictable pattern.
Sometimes I have to click right above the line that I want to select, other times the input is recognized a few lines beneath or above the cursor, or I cannot make a selection at all.

Downgrading `fzf` to v0.30 fixes the issue.

Thanks for any insight and most of all for this great tool!

**Comment by junegunn** [comment]
This was obviously a bug. Thanks for the report.
