### ISSUE TITLE
I have a perl script named fish

### ISSUE THREAD

**Issue by shmup** [junegunn/fzf#2905]
It is silly and is just an aquarium full of moving fish in my terminal.

Installing fzf and it sees I have an executable `fish` and so it ran it, and that was funny because I have this set to open a new shell in full screen. I was confused at first. IDK that this is a bug, but I figured I'd let you know: not all fish are a shell fish

**Comment by shmup** [comment]
For posterity: https://github.com/cmatsuoka/asciiquarium

**Comment by junegunn** [comment]
Oh.
