### ISSUE TITLE
Get the last output of `fzf`

### ISSUE THREAD

**Issue by sjwsl** [junegunn/fzf#2907]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

## Problem / Steps to reproduce

Say I want to delete some files and directories  in the current directory, but forget passing `-r` to `rm`

```zsh
ls | fzf | xargs rm
```

I'll get several ``rm: cannot remove 'xxx': Is a directory``. Now I want to run something like 

```zsh
fzf --last | xargs rm -r
```

to avoid selecting the same directories again. But I didn't find a similar command in the doc. Is there a way to do that?

**Comment by junegunn** [comment]
fzf is a stateless filter. You can redirect its output to a file and reuse it.

```sh
ls | fzf | tee -o /tmp/fzf-last | xargs rm

cat /tmp/fzf-last | xargs rm -r

fzf-remember-last() {
  fzf "$@" | tee /tmp/fzf-last
}
fzf-last() {
  cat /tmp/fzf-last
}
```
