### ISSUE TITLE
New scoring weights should prefer beginning of line words more

### ISSUE THREAD

**Issue by quyykk** [junegunn/fzf#2909]
- [ ] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

## Problem / Steps to reproduce

As stated in the release notes for 0.32.0, the scoring weights were updated. However, this changed the behavior in previous versions that preferred words at the beginning:

```bash
fzf --query=bar --height=4 << EOF
foo bar.sh
foo/bar.sh
EOF
```

gives:

```
foo/bar.sh
foo bar.sh
```

whereas in previous versions it would be the other way around. I definitely prefer it to match `foo/bar.sh` first. The current behavior makes it a pain to search for files whose names are also part of other files' name, like in the example posted above where I want to search for `bar.sh`.

Thanks!

**Comment by junegunn** [comment]
fzf is a general-purpose text filter, so the scoring algorithm isn't specifically designed for file paths. In this particular context, `foo bar.sh` may be the better match, but in other contexts, for example with a list of commands (e.g. `CTRL-R`), it may make sense to prefer `git add something` over `rm foo/add` on `add`.

```sh
fzf --query=add --height=4 << EOF
rm doc/addendum/patch1
git add somedir/patch1
EOF
```

What I presumed was that file paths with whitespace are not very common. Do you have many files with spaces in their paths?

**Comment by quyykk** [comment]
Yeah I do have many files with spaces. Makes sense though. So how about this: A special "path" mode for fzf that enables specific path behavior. For example, it would also be useful if files were sorted before folders (since you usually always search for files)

**Comment by junegunn** [comment]
> For example, it would also be useful if files were sorted before folders (since you usually always search for files)

fzf, being a text filter, does not know which entry is a file or a directory. The user should just feed a list of files excluding directories to fzf.

```sh
# Only files
fd --type f --strip-cwd-prefix | fzf
```

> Yeah I do have many files with spaces.

Can you post a few screenshots where the scoring algorithm of fzf isn't working as desired?

**Comment by quyykk** [comment]
> The user should just feed a list of files excluding directories to fzf.

Ah thanks that works.

![image](https://user-images.githubusercontent.com/85879619/183346306-9dc6c688-28dc-40f9-b5c9-a3bbd7feb1e6.png)

![image](https://user-images.githubusercontent.com/85879619/183346629-0ea7bb5f-18b1-400d-9079-d3c7b690b41f.png)

![image](https://user-images.githubusercontent.com/85879619/183346710-27dc7507-c069-4ecd-b521-2d120a1fd13d.png)

In each case I'm looking for the source files. While I could filter out the image files, I can't filter the text files because I might want to open them too.

**Comment by junegunn** [comment]
I see. The bonus points for the boundary characters are currently hard-coded.

https://github.com/junegunn/fzf/blob/779d8e16273a9ca776bef4136b3ff1886e10d19a/src/algo/algo.go#L115-L127

But maybe we could consider adding an option to tweak the scores.

A workaround for now would be to prefix your query with `/` (e.g. `/weap`). You can even start fzf with `/` as the default query. (`fzf --query=/`)

**Comment by noxafy** [comment]
Same problem on MacOS, fzf 0.32.0.

An easy solution would be to give the same additional bonus for both cases (lines 124 & 127 in the snippet above), no?

**Comment by james64** [comment]
I do not consider this a bug. But I would love the option to disable bonus points for boundary characters.

Among other things I use fzf for bash history. There I sometimes find myself in situation where I am looking for command where I remember only part of it. For simple example let's say I have forgot exact name of `tcpdump`. I just know its something with `dump` in it. Searching for `dump` gives me a lot of other entries like `less dump_file`, `pr_restore smthg smthg smthg product_dev_dump_date.tar` or `rm dump.tgz` etc. These are relevant but I need to revert to `less .bash_history` for simpler search to find it. I tried `fzf --exact` but bonus points for boundary seem to be used there as well.

If I can dream a bit then ability to toggle this boundary bonus points on/off during search session would be amazing. Then I can switch between "prefer older exact matches" and "prefer newer substring matches" live... but feel free to ground me back to earth.

**Comment by junegunn** [comment]
@james64 Have you tried (dynamically) disabling sort as suggested above when that happens? Still not satisfied with the result?

**Comment by james64** [comment]
@junegunn I have not found this feature so far and ou man yes it helps. Together with using or not using `'` in front of query this gives me all the flexibility I want. Thanks a lot!
