### ISSUE TITLE
Incomplete support for 256 color code

### ISSUE THREAD

**Issue by gnachman** [junegunn/fzf#2913]
- [x] I have read through the manual page (`man fzf`)
- [ x I have the latest version of fzf
- [ x I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

## Problem / Steps to reproduce

The following is parsed incorrectly:

```
printf "\e[38:5:208mOption 1\e[m\nOption 2" | fzf --ansi
```

Producing this output:
```
  Option 2
> e[38:5:208mOption 1e[m
  2/2
>
```

At first I thought "oh well it does say ANSI and SGR 38:5:x is not ANSI" but then I saw this test:

https://github.com/junegunn/fzf/blob/261d3d3340a9afa9925ec693a47ebe632d6870cb/src/ansi_test.go#L80

Which suggested you want to support this code! But the version with semicolons is based on a misinterpretation and colons are what the standard actually calls for. And it actually doesn't work with semicolons either. Anyway, it'd be nice to clear up the intent around this particular code for the benefit of https://gitlab.com/gnachman/iterm2/-/issues/10510 and https://github.com/Bhupesh-V/ugit/issues/41.

**Comment by junegunn** [comment]
Thanks for the report. I've thought that `;` was the right, the only delimiter, after going through a few documents on the internet, such as https://github.com/termstandard/colors.

So fzf should also see `:` as the delimiter?

> And it actually doesn't work with semicolons either

Can you please elaborate? Everything seems to work as expected once we replace colons with semicolons

```sh
printf "\e[38;5;208mOption 1\e[m\nOption 2"
printf "\e[38;5;208mOption 1\e[m\nOption 2" | fzf --ansi --height=4

printf "hello \x1b[34;48;5;233;1mwo\x1b[38;5;161mr\x1b[0ml\x1b[38;5;161md"
printf "hello \x1b[34;48;5;233;1mwo\x1b[38;5;161mr\x1b[0ml\x1b[38;5;161md" | fzf --ansi --height=4
```

**Comment by gnachman** [comment]
When I run it on my system here's what I see:

```
% fzf --version
0.32.1 (brew)
% printf "\e[38;5;208mOption 1\e[m\nOption 2" | fzf --ansi --height=4
  Option 2
> e[38;5;208mOption 1e[m
  2/2
>
```

> So fzf should also see : as the delimiter?

Yes, this is the "right" way to do it per the standard and it's been supported by many terminals for years now. There's some background here in the links below; they mostly talk about the 24-bit color code 38;2;xxx but the same applies to 38;5;xxx.

* https://gitlab.com/gnachman/iterm2/-/issues/6377
* https://bugzilla.gnome.org/show_bug.cgi?id=791456
* https://gitcode.net/btwise/iTerm2/-/blob/master/sources/VT100Terminal.m#L760

**Comment by junegunn** [comment]
That's strange, I can't reproduce the problem.

<img width="801" alt="image" src="https://user-images.githubusercontent.com/700826/184038799-254595c9-14ec-4ea9-b30f-ca7a724de9d0.png">

<img width="976" alt="image" src="https://user-images.githubusercontent.com/700826/184039039-246fa5e7-2fd5-4652-b6a0-4034159e2c6f.png">

> Yes, this is the "right" way to do it per the standard 

Thanks for the pointers.

**Comment by gnachman** [comment]
Maybe `export TERM=xterm-256color` will change the behavior? That's all I can think of tho

**Comment by junegunn** [comment]
fzf simply prints the escape sequences unchanged, so it doesn't really affect the end result when fzf can parse the code (`;`-delimited). 

<img width="840" alt="image" src="https://user-images.githubusercontent.com/700826/184264036-660a8031-36cf-4bf2-bbc3-78ef3ad42f5e.png">

TERM affects the color palette of fzf itself though.

<img width="840" alt="image" src="https://user-images.githubusercontent.com/700826/184264176-5a1a0da5-f884-4c0b-8e6f-669a0033afcd.png">

**Comment by junegunn** [comment]
A few observations.

```sh
# Tested with Terminal.app, iTerm2, Kitty, and Hyper

# Semi-colon. Supported by all terminal emulators.
echo $'\x1b[38;5;208mOption 1\x1b[m\nOption 2\n'

# Colon. NOT supported by Terminal.app
echo $'\x1b[38:5:208mOption 1\x1b[m\nOption 2\n'

# Mixed case. Only supported by Hyper.
echo $'\x1b[38;5:208mOption 1\x1b[m\nOption 2\n'

# Another mixed case, Hyper prints grey text
echo $'\x1b[38:5;208mOption 1\x1b[m\nOption 2\n'
```

Anyway, I'm going to make `--ansi` option of fzf properly understand the colon-only version.

**Comment by gnachman** [comment]
I was mistaken about handling of semicolons; as long as you provide `--ansi` it does the right thing. So the fix should completely solve the problem. Thank you!
