### ISSUE TITLE
`fzf#run` does not return selections

### ISSUE THREAD

**Issue by 3N4N** [junegunn/fzf#2916]
- [ ] I have read through the manual page (`man fzf`)
- [X] I have the latest version of fzf
- [X] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [X] WSL Ubuntu on Windows 11
- Shell
    - [X] bash
    - [ ] zsh
    - [ ] fish

## Problem / Steps to reproduce

https://github.com/junegunn/fzf/blob/4993d19466d5f3ac127de5c0c461cde7ef1894d7/plugin/fzf.vim#L928

Why is it returning an empty table? It should return the content of the tempfile.

In function `fzf.on_exit` (defined inside `s:execute_term`), we handle the fzf selection.

https://github.com/junegunn/fzf/blob/4993d19466d5f3ac127de5c0c461cde7ef1894d7/plugin/fzf.vim#L874

But it's not returned ultimately. Is that deliberate?

**Update**: I'm using neovim. And in a previous commit, the README had this to say:

https://github.com/junegunn/fzf/blob/622e69ff54f27363abc2ac18a5a69751f2b42f4a/README.md?plain=1#L327-L328

But it's erased in currrent master. Presumably because that shortcoming was handled. But it's not handled. I get an empty table for the following command.

```
:let xxx = fzf#run({'source': 'ls'})
```

**Comment by junegunn** [comment]
> But it's erased in currrent master.

Because it's also true on regular Vim now, and there's no point in mentioning it specifically for Neovim. fzf#run opens a terminal buffer running fzf both in Vim and Neovim, and returns immediately. There's no way we can block the code execution and get the return value synchronously.

https://github.com/junegunn/fzf/blob/master/README-VIM.md does not mention anything about the return value of `fzf#run`.

**Comment by 3N4N** [comment]
Then why is it returning an empty table instead of returning nothing? @junegunn

**Comment by junegunn** [comment]
Because of backward compatibility at the moment. Please just ignore it.

**Comment by junegunn** [comment]
Oh, let me correct myself. fzf#run may or may not return values depending on the way it opens.

* On regular Vim
    * Fullscreen mode (`echo fzf#run()`) ✅ 
    * Terminal window (`echo fzf#run({ 'window': { 'width': 0.9, 'height': 0.6 } })`) ❌ 
    * Tmux (`echo fzf#run({ 'tmux': '-p70%' })`) ✅ 
* Neovim
    * Fullscreen mode (`echo fzf#run()`) ❌ 
    * Terminal window (`echo fzf#run({ 'window': { 'width': 0.9, 'height': 0.6 } })`) ❌ 
    * Tmux (`echo fzf#run({ 'tmux': '-p70%' })`) ✅ 

So if you want to write a portable code, do not rely on its return value but use sink function.

**Comment by 3N4N** [comment]
Thanks for the explanation. I opened this issue according to [this stackoverflow question][1]. Leaving it here for reference.

[1]: https://vi.stackexchange.com/q/38206/16280

**Comment by Aster89** [comment]
> There's no way we can block the code execution and get the return value synchronously.

Why?

And why do I get an output when I run `:let xxx = fzf#run({'source': 'ls'})`, unlike what reported by @3N4N ? I'm too on 4993d19, with Vim 9.0.135.

**Comment by junegunn** [comment]
> doesn't it mean it runs synchronously

Only when you run fzf in fullscreen mode on regular Vim where fzf doesn't run inside a terminal buffer but is started with `:!fzf`, which blocks Vim until completion.

But `:!fzf` doesn't work on Neovim. https://github.com/junegunn/fzf/issues/137

And you can use different screen layouts with `:!fzf`.

```vim
" fzf opens in a terminal buffer on a split window
echo fzf#run({'source': 'ls', 'left': '40%'})
```

So why bother? If you rely on the return value of `fzf#run`, the code will not run on Neovim, and you can only use fullscreen mode.
