### ISSUE TITLE
suggestion to use v prefix for tags

### ISSUE THREAD

**Issue by kamilsk** [junegunn/fzf#2917]
Hi! Based on this approach https://github.com/golang/go/wiki/Modules#how-can-i-track-tool-dependencies-for-a-module to track tool dependencies for a module, as [an example](https://github.com/kamilsk/dotfiles/blob/004fb27edfffb68e5aa63bda249c9ba55cbbef1b/toolset/tools.go#L36), I found a slight inconvenience when working with `fzf`, because `fzf` uses a different style to name tags. For `go mod`, it's recommended by this https://go.dev/ref/mod#versions

> Each version starts with the letter v, followed by a semantic version

As a result, I have a pseudo-version [like this](https://github.com/kamilsk/dotfiles/blob/004fb27edfffb68e5aa63bda249c9ba55cbbef1b/toolset/go.mod#L13) instead of `v0.32.0`. It's challenging to understand which version is under the hood, actually. Is it possible to change the naming convention for tags?

**Comment by junegunn** [comment]
Interesting. Any reason you don't use brew to get the latest stable version of fzf?
