### ISSUE TITLE
Executing shell history entry requires hitting Enter twice

### ISSUE THREAD

**Issue by dwuertz** [junegunn/fzf#2918]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

## Problem / Steps to reproduce
When choosing a shell history item via Ctrl-R, I need to hit Enter once in order to insert it into the shell command line, and another time in order to execute it. It would improve the workflow if the shell integration could follow the behavior of the shell's built-in history handling which is something like this:
Hitting Enter once directly executes the search entry.
Hitting any command line navigation button such as left/right/home etc., the entry is inserted without immediate execution and cursor moved accordingly.

**Comment by junegunn** [comment]
It is by design. It gives us a chance to edit the command.

Related: https://github.com/junegunn/fzf/pull/1492

**Comment by phil294** [comment]
would be great if we could do this:

`export FZF_DEFAULT_OPTS="--ansi --bind 'right:accept,enter:execute'"`

doesn't work right now.

**Comment by nenahp** [comment]
no this can be only achieved in shell integration
