### ISSUE TITLE
Colon character as key

### ISSUE THREAD

**Issue by D630** [junegunn/fzf#292]
Hey :smile:

How can I set the colon as key inside `--bind`?

```sh
% ps | fzf --bind='::forward-char' 2> >(head -n +1)
key name required
```

**Comment by junegunn** [comment]
Ha, good question. You can't! :hankey: 
The current option parser blindly applies split function with colons and commas as delimiters, so they're "lost in translation". An easy fix that comes to my mind is to assign special key names for colon and comma so one can write: `--bind colon:forward-char,comma:backward-char`. What do you think?

**Comment by D630** [comment]
:+1:

**Comment by junegunn** [comment]
I just fixed the parser code to handle `:` and `,` correctly.
`fzf --bind='::forward-char,,:backward-char'` will work just fine.
