### ISSUE TITLE
hyperlink error on Windows page

### ISSUE THREAD

**Issue by harriott** [junegunn/fzf#2920]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [ ] Mac OS X
    - [x] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [ ] fish

## Problem / Steps to reproduce
[Windows](https://github.com/junegunn/fzf/wiki/Windows) page, first sentence, hyperlinked word "here" points to a dead link - needs to be changed to point to [Releases](https://github.com/junegunn/fzf/releases).

**Comment by junegunn** [comment]
Thanks for the report. Fixed it. Looks like someone, possible a spammer, vandalized the page :(

https://github.com/junegunn/fzf/wiki/Windows/_history
