### ISSUE TITLE
fzf-history-widget doesn't work properly.

### ISSUE THREAD

**Issue by zgqq** [junegunn/fzf#2924]
- [ ] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

## Problem / Steps to reproduce
1. Pressing Ctrl + r to show widget and pressing ENTER to select any item.
2. Pressing Ctrl + u (Delete whole line)  to clear the command.
3. Pressing Ctrl + r to show widget and pressing ENTER to select any item again.
4. Now terminal will not show the selected item (not show anything).

**Comment by junegunn** [comment]
Cannot reproduce the problem.
