### ISSUE TITLE
Installing via scoop is getting blocked showing trojan

### ISSUE THREAD

**Issue by MostHated** [junegunn/fzf#2928]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [ ] Mac OS X
    - [x] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [ ] fish
    - [x] pwsh

## Problem / Steps to reproduce

I just wanted to bring this to your attention. I am assuming that this is a false positive?

```log
Get-Content: C:\Users\dant\scoop\apps\scoop\current\lib\core.ps1:1139
Line |
1139 |          return Get-Content $file -AsByteStream -TotalCount 8
     |                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Operation did not complete successfully because the file contains a virus or potentially unwanted software. :
     | 'C:\Users\myuser\scoop\apps\fzf\0.32.1\fzf-0.32.1-windows_amd64.zip'

ERROR Hash check failed!
App:         main/fzf
URL:         https://github.com/junegunn/fzf/releases/download/0.32.1/fzf-0.32.1-windows_amd64.zip
First bytes:
Expected:    fba5bac1a61f6f26237f628c7cce9bd5e87f55c34e06348deaf27f627b126aa7
Actual:
```

Windows Defender is showing the following:

![](https://img.instance.id/IYIGoRLglVf2/direct)

**Comment by junegunn** [comment]
> I am assuming that this is a false positive?

I believe so. See https://go.dev/doc/faq#virus
Not sure if there's anything I can do about it.

**Comment by MostHated** [comment]
Yeah, no worries, I mostly just wanted to bring it to your attention. I figured whether it was something you could do anything about or not, you might want to at least know about it in case you end up getting other issues about it.
