### ISSUE TITLE
0.32.1 sorting issue 

### ISSUE THREAD

**Issue by pldubouilh** [junegunn/fzf#2930]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

## Problem / Steps to reproduce

hi - and thank you so much for `fzf`, this is probably the tool that enhanced my productivity the most over the past few years :)

I'm having a sorting issue with 0.32.1, for instance taking as an example the history plugin with zsh

```zsh
% cat ~/.zsh_history | grep "git commit --amend" | wc -l
47
% cat ~/.zsh_history | grep "amend" | wc -l             
54

# 47 git amend commmands, 7 other (non git) amend commands

% fzf --version                                                            
0.32.1 (19f9bbc)             
% 
  13474  git commit --amend                                                  
  13953  git commit --amend --reset-author                                   
  14014  git commit --amend --reset-author --no-edit                         
   9221  xmodmap -pke > /tmp/amend                                           
   9222  diff /tmp/amend .xmodmap.orig                                       
    437  ls some/path\ with\ space/amendment.docx\ \(1\).pdf                
    437  cp some/path\ with\ space/amendment.docx\ \(1\).pdf somewhere
    437  rm some/path\ with\ space/amendment.docx\ \(1\).pdf                
  526/11390 +S                                                               
> amend             

# 0.32.1 returns a first result a command only used once a long time ago
# heavy-hitter git amend command is 6th result

% fzf --version                                                                   
0.30.0 (tarball)                                                                    
%                                                                                 
   6711  git add -p && git commit --amend --no-edit && git push -f                  
   8224  git commit --amend --no-edit                                               
   9221  xmodmap -pke > /tmp/amend                                                  
   9222  diff /tmp/amend .xmodmap.orig                                              
  13020  git add -p && git commit --amend --reset-author --no-edit && gp -f         
  13474  git commit --amend                                                         
  13953  git commit --amend --reset-author                                          
> 14014  git commit --amend --reset-author --no-edit                                
  526/11390 +S                                                                      
> amend                                                 

# 0.30.0 returns appropriately the most common command first
```
 
I understand it's probably the outcome of https://github.com/junegunn/fzf/commit/c3a7a24eeaa5b7451e652df68683b5e8b24cde6b - but the result really feel backwards since the update. Would it be possible to only toggle this feature through an option ?

Thank you !

**Comment by junegunn** [comment]
The algorithm is working as expected here (` amend `> `/amend` > `-amend`). It's unfortunate though that we're learning that it's not always working as desired, which is not unexpected because fzf is used with all types of input with vastly different requirements.

Anyway, on the other hand, there are cases where the new ordering yields better (subjective?) results.

* https://github.com/junegunn/fzf/issues/2909#issuecomment-1207199984

I could just add a bunch of options for tweaking the algorithm, but I think it's a cop-out. Most users won't be able to understand how to use them properly. So instead, I'm going to put more thought into coming up with better ways to meet different requirements.

For the time being, you can press `CTRL-R` again to switch sort off and get the most recent match. You can even put `--no-sort` to `$FZF_CTRL_R_OPTS` to disable sort by default.

**Comment by farid-fari** [comment]
I would say that changing the fish completion to have the `--no-sort` option by default would be a sane choice. It is really confusing as is, as a super old but non-relevant suggestion keeps coming up.

**Comment by pldubouilh** [comment]
v0.33.0 fixes my issue - thank you very much for the super fast turnaround :rocket:
