### ISSUE TITLE
Set preview for widgets

### ISSUE THREAD

**Issue by flippy1345** [junegunn/fzf#2933]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

## Problem / Steps to reproduce
I'm currently trying to adjust the fzf-cd-widget and fzf-file-widget to use my `--preview` argument already in use in my -zshrc.
My alias using `bat` for files and `tree` for directories:

```bash
alias fzf="fzf --preview 'bat --color=always --style=numbers --line-range=:500 {} 2> /dev/null || tree -C {} | head -200'"
````
Is it possible to set `--preview` for fzf-cd-widget and fzf-file-widget ?

**Comment by RayZ0rr** [comment]
Can't you use the following options?
```bash
# for fzf-file-widget 
export FZF_CTRL_T_OPTS="--preview 'bat --color=always --line-range :100 {}' --preview-window 'down,50%,+{2}+3/3,~3'"

# for fzf-cd-widget
export FZF_ALT_C_OPTS="---preview 'tree -C {} | head -100' --preview-window 'down,50%,~1'"

```

**Comment by junegunn** [comment]
See https://github.com/junegunn/fzf#key-bindings-for-command-line
