### ISSUE TITLE
support key value data-sets

### ISSUE THREAD

**Issue by acornejo** [junegunn/fzf#294]
This would allow fzf to process data-sets of the form:

```
KEY1 SEPARATOR VALUE1
KEY2 SEPARATOR VALUE2
KEY3 SEPARATOR VALUE3
...
```

fzf would present the list of values to the user, and allow the user to do fuzzy finding on this list. The output of fzf would be the key(s) of the corresponding selected values.

This would be particularly useful to handle tags inside vim, but there might be other legitimate use cases.

**Comment by junegunn** [comment]
What you have in mind (and more) is already possible with `--with-nth`, `--delimiter`, and a post-processor. See the man page for the details.

```sh
ls -al | fzf --with-nth 6.. | awk '{print $1}'
```

**Comment by acornejo** [comment]
great! closing this issue!

I had seen the man page, but somehow the description led me to believe this wasn't what I wanted (somehow `Transform each item using index expressions within finder` didn't quite explain to me that this would only print certain fields.. make sense now though).
