### ISSUE TITLE
completion.bash is missing from fzf/jammy,now 0.29.0-1 amd64

### ISSUE THREAD

**Issue by pjgoodall** [junegunn/fzf#2940]
- [ X] I have read through the manual page (`man fzf`)
- [ X] I have the latest version of fzf
- [ X] I have searched through the existing issues

## Info

- OS
    - [ X] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ X] bash
    - [ ] zsh
    - [ ] fish

## Problem / Steps to reproduce
sudo apt update && sudo apt install fzf
instructions for keyboard integration says:

```
warning Key bindings (CTRL-T / CTRL-R / ALT-C) and fuzzy auto-completion may not be enabled by default.
Refer to the package documentation for more information. (e.g. apt-cache show fzf)

This asks you to read `/usr/share/doc/fzf/README.Debian`

```
extract from `/usr/share/doc/fzf/README.Debian`:

```
Bash
====

Append this line to ~/.bashrc to enable fzf keybindings for Bash:

   source /usr/share/doc/fzf/examples/key-bindings.bash

Note, since fzf 0.29.0-1, the bash completion is installed for bash
by default. Feel free to ignore the following instruction for fzf >= 0.29.0-1.
Append this line to ~/.bashrc to enable fuzzy auto-completion for Bash:

   source /usr/share/doc/fzf/examples/completion.bash

```

` /usr/share/doc/fzf/examples/completion.bash` is not installed by the package

**Comment by junegunn** [comment]
Please see #2790
