### ISSUE TITLE
[Feature Request] Add option to support updating history file even with <C-c>

### ISSUE THREAD

**Issue by hiberabyss** [junegunn/fzf#2942]
Sometimes,  just run `fzf` for previewing without do any action. While still want to record the query into history file.

**Comment by hiberabyss** [comment]
If query could be exposed like `{}`, could use `execute` to accomplish this.

**Comment by junegunn** [comment]
> If query could be exposed like {}

It's `{q}`.

```sh
fzf --history /tmp/fzf --bind 'ctrl-c:execute(echo {q} >> /tmp/fzf)+abort'
```
