### ISSUE TITLE
ctrl-r causes unknown option: --scheme=history

### ISSUE THREAD

**Issue by rngoodner** [junegunn/fzf#2943]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

When installing using the "[using git](https://github.com/junegunn/fzf#using-git)" instructions I get `unknown option: --scheme=history` after pressing ctrl-r in the bash shell.

I suspect the error comes from this commit: 6fb41a202a97ad3f2437f6e5aee8890268560412

I manually changed `--scheme=history` back to `--tiebreak=index` in my `key-bindinds.bash` file and now everything is working perfectly.

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

## Problem / Steps to reproduce

See "Info" section.

**Comment by theEndBeta** [comment]
Can confirm this issue on zsh as well after updating via the vim plugin.

**Comment by gsilvapt** [comment]
Installed and tested 0.32.1 and still happens the same on a fresh Fedora installation. Interestingly enough, `fzf` runs just fine, but `CTRL-R` returns that odd error.

**Comment by junegunn** [comment]
I've just released 0.33.0, it will work once you get that latest binary.

**Comment by diohabara** [comment]
same here.
I'm using bash on the aarch64 GNU/Linux.

```bash
uname -a
<confidential> aarch64 GNU/Linux
```

The version is expected to `0.34.0` but I got `0.24(devel)`.

```bash
:~/.fzf $ ./install 
Downloading bin/fzf ...
  - Already exists
  - Checking fzf executable ... 0.34.0
Do you want to enable fuzzy auto-completion? ([y]/n) y
Do you want to enable key bindings? ([y]/n) y

Generate /home/username/.fzf.bash ... OK
Generate /home/username/.fzf.zsh ... OK

Do you want to update your shell configuration files? ([y]/n) y

Update /home/username/.bashrc:
  - [ -f ~/.fzf.bash ] && source ~/.fzf.bash
    + Added

Update /home/username/.zshrc:
  - [ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
    + Added

Finished. Restart your shell or reload config file.
   source ~/.bashrc  # bash
   source ~/.zshrc   # zsh

Use uninstall script to remove fzf.

For more information, see: https://github.com/junegunn/fzf
:~/.fzf $ source ~/.bashrc 
:~/.fzf $ fzf --version
0.24 (devel)
```

**Comment by gsilvapt** [comment]
Ensure you checkout to the proper tag before building the binary (not sure where master is pointing at). Adidtionally, it's not clear if you're using the global `fzf` binary (that should be somewhere like `/usr/bin/fzf` or `/bin/fzf`) or the one in your local build. What do you get with `which fzf`?

**Comment by diohabara** [comment]
@gsilvapt 
Oh, you're right. I was using `/usr/bin/fzf`, not the local one. Thanks!

**Comment by jeffkni** [comment]
Same problem here. Solved with

```shell
sudo rm /usr/bin/fzf
sudo ln -s ~/.fzf/bin/fzf /usr/bin/fzf
```

CTRL + R, happy days.

**Comment by diohabara** [comment]
I think most of you are Ubuntu users. If so, just delete the old `fzf` from your pacakge manager.

```shell
sudo apt remove fzf
```

**Comment by smallfishzzz** [comment]
> Same problem here. Solved with
> 
> ```shell
> sudo rm /usr/bin/fzf
> sudo ln -s ~/.fzf/bin/fzf /usr/bin/fzf
> ```
> 
> CTRL + R, happy days.

nice

**Comment by rahulranjansah** [comment]
Problem: --scheme=history
Cause of error: installed fzf both manually (using GitHub link) and sudo apt install fzf

How did I solve it?
$ which fzf      
/usr/bin/fzf

sudo rm /usr/bin/fzf

which fzf
/home/ror/.fzf/bin/fzf  --> showed manual location to my fzf manually installed (ror is random folder I created)

whereis fzf
fzf: /home/ror/.fzf/bin/fzf  /usr/share/man/man1/fzf.1.gz

fzf: /home/ror/.fzf/bin/fzf  >>> This is the path to the fzf executable. This means that when you type fzf in your terminal, the shell will run the fzf executable located at this path. This fzf is likely the one you installed manually in your home directory

/usr/share/man/man1/fzf.1.gz >>> This is the path to the manual page for fzf. Manual pages, or man pages, are a form of software documentation usually found on a Unix or Unix-like system. You can view this manual page with the command man fzf.
