### ISSUE TITLE
Mouse clicks out of fzf's border insert text

### ISSUE THREAD

**Issue by timsu92** [junegunn/fzf#2949]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf (I'm using [0.33.0](e03ac31))
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux (Ubuntu 22.04.1 on WSL2)
    - [ ] Mac OS X (not using it)
    - [ ] Windows (not using it)
    - [ ] Etc.
- Shell
    - [x] bash
    - [x] zsh
    - [ ] fish (not using it)

## Problem / Steps to reproduce
1. Open fzf in any way with mouse support (eg. `fzf`, `ctrl-r`, `ctrl-t`...)
2. Click out of fzf\'s border or click inside right after clicking outside. Left, right, middle buttons are all triggering this.
3. Click info about the click is inserting in the search pattern.

**Comment by junegunn** [comment]
Fixed on master, thanks for the report!

**Comment by timsu92** [comment]
Thanks for fixing!
