### ISSUE TITLE
Problems on older zsh

### ISSUE THREAD

**Issue by rlpowell** [junegunn/fzf#295]
On my zsh 4 machine, this line:

  tail=${LBUFFER:$(( ${#LBUFFER} - ${#trigger} ))}

in ".fzf/shell/completion.zsh" gives this error on tab completion attempts:

rlpowell@shell01> ls /
fzf-completion:17: unrecognized modifier

I changed the : to :- ; no idea if that's a good fix, but it shut the error up.

**Comment by junegunn** [comment]
Thanks for the suggestion, but it's not a valid fix.

```vim
> A="foobar"
> echo ${A:2}
obar
> echo ${A:-2}
foobar
> echo ${UNDEFINED_VAR:-2}
2
```

And sorry but I don't think I can afford time to make the code compatible with old versions of zsh (same goes to those of fish) especially considering that zsh 5 has been around for 3 years by now. If you can't upgrade for some reason, install script will allow you to disable fuzzy completion.
