### ISSUE TITLE
Version 33 has graphical glitches on cmder and conemu

### ISSUE THREAD

**Issue by vctls** [junegunn/fzf#2954]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [ ] Mac OS X
    - [x] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [ ] fish
    - [x] cmder/conemu

## Problem / Steps to reproduce

The main text color is the same as the background color, and the whole thing flickers during search:  
![2022-09-03_13-26-48_ConEmu64](https://user-images.githubusercontent.com/18054077/188268341-9afa9c4a-e755-4420-9ca6-dc8fbb6e0157.gif)

This happens only on conemu and cmder with version 33. The actual shell doesn't seem to matter.
All other terminals work fine, as well as previous versions.

**Comment by junegunn** [comment]
Possibly because of the tcell upgrade. https://github.com/junegunn/fzf/commit/4bef330ce15d3ae80959415c24aba4700f5cbe35

**Comment by junegunn** [comment]
Anyone else having this issue?

**Comment by dogancelik** [comment]
@junegunn Yes I also have the same issue with `0.33.0`

**Comment by trungking** [comment]
Only current selected line is visible for me. Had to revert to [0.32.1](https://github.com/junegunn/fzf/releases/tag/0.32.1)
