### ISSUE TITLE
Add to wiki: gh-f

### ISSUE THREAD

**Issue by gennaro-tedesco** [junegunn/fzf#2955]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [x ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

## Problem / Steps to reproduce

Not sure if an issue is the right place to propose, but I would like to suggest to add to the Wiki (in the git section) the `gh` plugin [gh-f](https://github.com/gennaro-tedesco/gh-f), that uses `fzf` to run all things git :)

**Comment by junegunn** [comment]
Hi, the write access to the wiki is open to the public, so feel free to add the project to the page.

(Actually, I haven't monitored the pages for quite a while.)
