### ISSUE TITLE
unknown option: --scheme=history

### ISSUE THREAD

**Issue by gtzo-anchorage** [junegunn/fzf#2957]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

## Problem / Steps to reproduce
Pressing CTRL-R results in `unknown option: --scheme=history`.
I found an existing issue [here](https://pullanswer.com/questions/ctrl-r-causes-unknown-option-scheme-history), but I've updated to the newest binary and still have the issue.

**Comment by palcalde** [comment]
Same

**Comment by junegunn** [comment]
You must be still using an old binary. See `fzf --version` to confirm.
