### ISSUE TITLE
Add actions for changing order of results

### ISSUE THREAD

**Issue by hotsphink** [junegunn/fzf#2958]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

## Problem / Steps to reproduce

This is a feature request.

I am using multi-select to choose a set of items, but I would like to also allow reordering those items (from within fzf). My model for this is mercurial's interactive (curses-based) implementation of histedit, where I can move a highlight around then use a key to "drag" an entry up or down in the list. In chistedit, those actions are bound to shift-J/shift-K.

This might be a little bit of an awkward fit for fzf because the highlight applies to the available options, not just the results. It would still work well enough for me, though (the order of the options would be reflected in the results, as it is now, and reordering unselected options just wouldn't do anything).

My full use case, if it helps:

I am choosing a set of pushes to our continuous integration system that I want to compare the results from. I use fzf to select the subset of pushes that I care about, which my tool then scans through to download each one and extract numeric scores from that I feed into a graphing tool. I generally want to arrange things so that there's a base version, then one with an initial change, then a follow-on change, etc. But sometimes I made the pushes in a different order, and it's confusing to remember which is which.

But I imagine there are other applications where the order of the results matters and it would be useful for the user to control them.

**Comment by junegunn** [comment]
Thanks for the suggestion, but I don't think the suggested feature would be a good fit for fzf, which is fundamentally an interactive grep program that doesn't mutate the input.
