### ISSUE TITLE
Parse error on `shell/keybindings.zsh`

### ISSUE THREAD

**Issue by Feliconut** [junegunn/fzf#2959]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

## Problem / Steps to reproduce

I get the following message:
```
[2022-09-08 08:30:29.150] [error] [console_user_server] shell_command stderr:/opt/homebrew/opt/fzf/shell/key-bindings.zsh: line 22: syntax error near unexpected token `)' /opt/homebrew/opt/fzf/shell/key-bindings.zsh: line 22: `  () {'
```

It seems the problem is related to the file [shell/key-bindings.zsh](https://github.com/junegunn/fzf/blob/master/shell/key-bindings.zsh)

Here are version details:
```
xiaoyu@Xiaoyus-MBP ~ % fzf --version
0.33.0 (brew)
```
```
MacOS Monterey 12.5.1
MacBook Pro (14-inch, 2021)
Apple M1 Pro Silicon
```

**Comment by junegunn** [comment]
Since you checked `[x] bash`; it looks like you're loading the zsh version from bash. Load `key-bindings.bash` instead.
