### ISSUE TITLE
[Feature request/question] select the 1st match.

### ISSUE THREAD

**Issue by RESDXChgfore9hing** [junegunn/fzf#2960]
- [windows no man*] I have read through the manual page (`man fzf`)
- [ x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [ ] Mac OS X
    - [ x] Windows
    - [ ] Etc.
- Shell
    - [ x] cmd

## Problem / Steps to reproduce
after spending sometime in a certain project,most people will have some basic muscle and brain memory that xxx file/folder is uniquely named and we want to navigate too it directly.

In most modern search engine also has this *try my luck function of just directly visiting the 1st link when searched.

Is it possible with fzf?do we need to add a new flag?or is it a another responsibility for other app?like find?fd?

Any guide will be appreciated.

**Comment by timsu92** [comment]
Did you mean as same as:
1. Type what you want
2. Press `enter`

**Comment by RESDXChgfore9hing** [comment]
maybe a -1 flag could be used

**Comment by junegunn** [comment]
```sh
fzf --bind one:accept
```
