### ISSUE TITLE
Keeping queries between mode

### ISSUE THREAD

**Issue by nkh** [junegunn/fzf#2961]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

## Problem / Steps to reproduce

I'm using  https://github.com/junegunn/fzf/blob/master/ADVANCED.md#switching-between-ripgrep-mode-and-fzf-mode, adapted to my needs.

when changing to fzf mode the query is empty at first, as I expect, after changing the query I switch back to Ripgrep mode, the query is the "global" query. Is it possible to save the query when changing mode so each mode has its own query?

**Comment by junegunn** [comment]
This is now possible with `transform-query` action. See the updated example.

**Comment by junegunn** [comment]
FYI, we can further simplify the script using `become` action that is going to be included in the upcoming version.

```sh
# Switch between Ripgrep launcher mode (CTRL-R) and fzf filtering mode (CTRL-F)
rm -f /tmp/rg-fzf-{r,f}
RG_PREFIX="rg --column --line-number --no-heading --color=always --smart-case "
INITIAL_QUERY="${*:-}"
FZF_DEFAULT_COMMAND="$RG_PREFIX $(printf %q "$INITIAL_QUERY")" \
fzf --ansi \
    --color "hl:-1:underline,hl+:-1:underline:reverse" \
    --disabled --query "$INITIAL_QUERY" \
    --bind "change:reload:sleep 0.1; $RG_PREFIX {q} || true" \
    --bind "ctrl-f:unbind(change,ctrl-f)+change-prompt(2. fzf> )+enable-search+rebind(ctrl-r)+transform-query(echo {q} > /tmp/rg-fzf-r; cat /tmp/rg-fzf-f)" \
    --bind "ctrl-r:unbind(ctrl-r)+change-prompt(1. ripgrep> )+disable-search+reload($RG_PREFIX {q} || true)+rebind(change,ctrl-f)+transform-query(echo {q} > /tmp/rg-fzf-f; cat /tmp/rg-fzf-r)" \
    --bind "start:unbind(ctrl-r)" \
    --bind "enter:become:[ x{} = x ] || vim {1} +{2}" \
    --prompt '1. ripgrep> ' \
    --delimiter : \
    --header '╱ CTRL-R (ripgrep mode) ╱ CTRL-F (fzf mode) ╱' \
    --preview 'bat --color=always {1} --highlight-line {2}' \
    --preview-window 'up,60%,border-bottom,+{2}+3/3,~3'
```

**Comment by meinzer1899** [comment]
How do you use this script inside of vim? Is it possible to have a switch between ripgrep and fuzzy find matching as well inside vim?

**Comment by nkh** [comment]
@meinzer1899 

> How do you use this script inside of vim? Is it possible to have a switch between ripgrep and fuzzy find matching as well inside vim?

What do you mean? There's no FZF in vim, the script are run as any external scripts and if you have your own script you can just execute it yourself.

**Comment by junegunn** [comment]
https://github.com/junegunn/fzf/releases/tag/0.38.0

**Comment by nkh** [comment]
@junegunn 

I think that the example, if to be shared with other, should handle the possibility of two instances running at the same time (I often do).

TMP_DIR=/tmp/rg-fzf
mkdir -p "$TMP_DIR" 

PID=$$
frf_f="$TMP_DIR/frf_f_$PID"
frf_r="$TMP_DIR/frf_r_$PID"


and then used like this:
	--bind "ctrl-f:unbind(change,ctrl-f)+change-prompt(2. fzf> )+enable-search+rebind(ctrl-r)+transform-query(echo {q} >$frf_r; cat $frf_f)" \
	--bind "ctrl-r:unbind(ctrl-r)+change-prompt(1. rg> )+disable-search+reload(frl {q} $frf_max_depth || true)+rebind(change,ctrl-f)+transform-query(echo {q} >$frf_f; cat $frf_r)" \
