### ISSUE TITLE
 wrap the file name passed to the preview command with quotes so it's not processed as multiple arguments,

### ISSUE THREAD

**Issue by moisestohias** [junegunn/fzf#2962]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [x] zsh
    - [x] fish

## Problem 
Is there a way to wrap the file name passed to the preview command with quotes so it's not processed as multiple arguments,  for instance how I can wrap the file name here. 
```bash
grep -r . | fzf --preview="less {}" | cut -d ":" -f 1 | awk '{print "\x27" $0 "\x27" }' | xargs nvim
```

**Comment by junegunn** [comment]
> wrap the file name passed to the preview command with quotes

fzf does that by default. Excerpt from `man fzf`:

>  Preview
>      --preview=COMMAND
>             Execute the given command for the current line and display the result on the preview window.
>             {} in the command is the placeholder that is replaced to the single-quoted string of the
>             current line.

You probably want to set the delimiter to `:`

```sh
grep -r . | fzf --delimiter : --preview="less {1}"
```

**Comment by moisestohias** [comment]
Thanks ❤️
