### ISSUE TITLE
[Feature Request] additional confirmation for potentially destructive commands

### ISSUE THREAD

**Issue by miclill** [junegunn/fzf#2968]
- [x] I have read through the manual page (`man fzf`)
- [ ] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

## Problem / Steps to reproduce
User searches for something,  e.g. `sudo rm -Rf /somename` matches and is then accidentally selected.
=> It would be nice to have some extra protection for a handful of potentially destructive commands like: rm, mv, cp etc.

**Comment by dwyart** [comment]
By default, Ctrl+L feature for shell history doesn't run the command after first ENTER but after a second ENTER action.
(some issues explain how to change this to run the command after its selection, but it is not the default)

**Comment by RESDXChgfore9hing** [comment]
why should anyone search:sudo rm -Rf /somename

shouldnt the sudo be the final protection?

So,in the end,sudo rm -Rf /somename will be executed?how is that dangerous?
Isnt that the same as>sudo rm -Rf /somename&fzf

wouldnt that be a fundamental problem in your bash env setup itself?
