### ISSUE TITLE
[Feature request] shorten_path option

### ISSUE THREAD

**Issue by boydkelly** [junegunn/fzf#2969]
In notational velocity fzf, (and Telescope), the file/directory listing shows (can show) only the first letter of a directory and the full filename.    Checking in velocity-fzf.vim points to a python script used for this(attached).  However I would love to see this available on the command line.   In my usage what is most important is the file name and preview as big as possible.  The actual path is not essential. Is it possible to make this an option directly in fzf?   Thanks for this most awesome utility!

[shorten_path (notational velocity)](https://github.com/alok/notational-fzf-vim/blob/master/shorten_path_for_notational_fzf.py)

**Comment by junegunn** [comment]
fzf follows the Unix philosophy and it does not implement input/output transformation that can be done by other programs.

>  I would love to see this available on the command line

You might want to ask the author of the plugin to expose the feature as a standalone executable binary so you can use it with fzf.

```sh
# fzf is just a filter
ls -al | nl | fzf --with-nth 2.. | awk '{print $1}'
```
