### ISSUE TITLE
To release 0.10.1

### ISSUE THREAD

**Issue by junegunn** [junegunn/fzf#297]
### New features

- Added options for sticky header
    - `--header-file`
    - `--header-lines`
- Added `--margin` option
- Added `cancel` action which clears the input or closes the finder when the
  input is already empty
    - e.g. `export FZF_DEFAULT_OPTS="--bind esc:cancel"`
- Added `delete-char/eof` action to differentiate `CTRL-D` and `DEL`

### Minor improvements/fixes

- Fixed to allow binding colon and comma keys
- Fixed ANSI processor to handle color regions spanning multiple lines

**Comment by junegunn** [comment]
phew.

**Comment by edi9999** [comment]
Great work !

**Comment by junegunn** [comment]
Thanks, please let me know if you find any regression.
