### ISSUE TITLE
Preprocessing the input virtually before displaying?

### ISSUE THREAD

**Issue by psprint** [junegunn/fzf#2971]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

## Problem / Steps to reproduce

I have an input that has fields separated by `\001` (i.e. `^A`) and would like to hide them from display but preserve them in the final output. How to do this?

**Comment by junegunn** [comment]
Using `--with-nth`:

```sh
printf 'foo\001bar\001baz' | fzf --delimiter '\001' --with-nth 1..2
```
