### ISSUE TITLE
Set, alter or unset envionment variable in `execute`

### ISSUE THREAD

**Issue by Kabouik** [junegunn/fzf#2976]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [x] fish

## Problem / Steps to reproduce
This may not be an issue but I haven't been able to find any hit in my searches in the existing issues or in the manual.

My `fzf` selection goes into a variable named `$selection`, which I later re-use in another command. However, I would be interested in having a choice between that command and an alteration of it with an extra argument, and ideally I would like that to be bound to a secondary `fzf` keybinding instead of forcing the user to add an extra argument beforehand when executing the script. Is it possible to use something like the following?
- `--bind="ctrl-s:execute(extraarg='toto')+accept"`
- `--bind="ctrl-s:execute(extraarg='')+accept"`
- `--bind="ctrl-s:execute(unset extraarg)+accept"`

And then run `mycommand $extraarg $selection`?

I have tried creating the variable in the `execute` function, altering a pre-existing variable, using in `execute` a Bash function defined in the script that sets the variable, or `unset extraarg`, but so far all my attempts have failed.

My use case here would be a script for `password-store`, with `Return` to copy the password to clipboard, and `ctrl-s` to show it (*i.e.*, `pass show --clip $selection` *vs.* `pass show $selection`). It could also be useful for environment variables that may only be useful for some uses, like `LD_LIBRARY_PATH` or `GDK_SCALE`.

**Comment by junegunn** [comment]
`execute` starts the command as a child process. Any environment variable set in a child process is lost once it terminates. You'll have to store the state externally. e.g. `--bind="ctrl-s:execute-silent(echo toto > /tmp/extraarg)+accept"`

**Comment by Kabouik** [comment]
Thanks @junegunn, that works. For reference, below is the `passfzf` script I came up with:

```bash
#!/usr/bin/env bash
# This scripts unlocks the pass tomb, if any, and then relies on fzf to either
# copy the password to the clipboard or show the content of the .gpg file.
# Author: Kabouik
# Dependencies: fzf, fd, pass

store="$HOME/.password-store/"

# Open pass tomb, if any
if [[ -e "$HOME/.password.tomb" ]]; then
    pass open 2> /dev/null
fi

# Select pass entry
clear
selection=$(fd .gpg ~/.password-store/ -d 8 \
              | fzf --prompt="# " \
                    --ansi \
                    --extended \
                    --no-border \
                    --with-nth 5.. \
                    --delimiter "/" \
                    --layout=reverse-list \
                    --no-multi \
                    --cycle \
                    --header='
Copy (Ret) or show (C-s)' \
                    --margin='1,2,1,2' \
                    --color='16,gutter:-1' \
                    --bind="tab:down" \
                    --bind="btab:up" \
                    --bind="ctrl-s:execute(echo '' > /tmp/passfzfarg)+accept")

if [[ -f "/tmp/passfzfarg" ]]; then
    arg=$(cat /tmp/passfzfarg)
    rm /tmp/passfzfarg
else
    arg="--clip"
fi

if [[ -n "$selection" ]]; then
    tmp=${selection::-4} && tmp=${tmp#"$store"}
    clear
    pass show "${tmp}" ${arg}
    pkill -P $$
fi

# Close pass tomb, if any
if [[ -e "$HOME/.password.tomb" ]]; then
    pass close
fi
```

There are already some `pass` extensions that do similar things, but they are not available for all distributions and I prefer using a simple shell script I can customize instead of depending on an extension. It seems to work well so far.
