### ISSUE TITLE
Request: use negation, exact sigils after search text

### ISSUE THREAD

**Issue by nkh** [junegunn/fzf#2977]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

## Problem / Steps to reproduce

say you want to search for 'very_long_word', fzf shows a lot matches but you realize that it's an exact match you want, you now have to scroll back, add a quote, scroll to the end to add further elements to the search. This happens daily to me, often enough so I wrote this request.

having the possibility to add the quote or the exclamation mark after 'very_long_word' would be great.

**Comment by junegunn** [comment]
> you now have to scroll back, add a quote, scroll to the end

I'm pretty used to pressing <kbd>ALT-B</kbd> <kbd>'</kbd> <kbd>ALT-F</kbd> in that case. It won't take more than a second once you get used to it. 

Allowing `'` or `!` at the end of a word is basically changing the search syntax of fzf thus breaking backward compatibility, 
suddenly disallowing users to search `foo!`, so I'm reluctant to make this change.

Having said that, the closest thing you can do at the moment is something like this.

```sh
fzf --bind "':backward-word+put+forward-word"
```
