### ISSUE TITLE
can we treat --query as placeholder?

### ISSUE THREAD

**Issue by haolian9** [junegunn/fzf#2979]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

## Problem / Steps to reproduce

my usecase in steps
*  `$ fzf --query='hello' --query-as-placeholder` 
* user input `w`
* fzf removes "hello" from the input, and set it to "w"

this is really convenient when fzf is used in nvim repeatly: first time user input something and got their result, second time the fzf nvim plugin will start fzf with `--query='previous-input'`, and if user dont want `previous input`, user can simple type what they want without `c-u` first.

` --query-as-placeholder` (or whatever name) indicates once user input a rune firstly, fzf will reset `terminal.input`before processing `tui.GetChar()`.
this usecase is just like [html input tag's placeholder attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#placeholder)

(yeah, i scratched a just-work [commit](https://github.com/haolian9/fzf/commit/551aefe2c0280fab5868a4e696455f6e3500e58e) to do this, hope it can make myself more clear)

**Comment by junegunn** [comment]
I'm not sure if I want this feature in fzf (I think it can be confusing), but you can emulate the behavior like so.

```sh
fzf --query foo --bind 'change:clear-query+unbind(change)'
```

**Comment by junegunn** [comment]
Oh, that will consume the first key press.

**Comment by haolian9** [comment]
wow, nice to know that approach. though it have a little downside, it will not keep the rune/key i just pressed after clear.

> it can be confusing
to me, it's just a standard behavior of html `<input placeholder="foo">`

**Comment by haolian9** [comment]
well, this does bring in additional complex: user may want to custom its fg, bg, style ... (i dont need that so far)

**Comment by junegunn** [comment]
> to me, it's just a standard behavior of html `<input placeholder="foo">`

Well, fzf is not an HTML `<input>`, so.

> custom its fg, bg, style

That is required if we are really going to do this. There must be a visual cue to let the user know if the text on the prompt is going to be cleared or not.

**Comment by junegunn** [comment]
> i just found it while writing a reply using text area, haha

But in that case, you can't press `Comment` button and "Leave a comment" message is not posted as a message.

**Comment by haolian9** [comment]
yeah, you are right on this case. but if you put it in a `search box`, then this placeholder do have a meaning when you dont type anything just click the submit button.

**Comment by junegunn** [comment]
This partly works,

```sh
fzf --query foo --bind 'change:unbind(change)+backward-char+unix-line-discard+forward-char'
```

except it breaks when the user presses a non-character key such as backspace. So a more general approach would be to add `char` event in addition to `change` that is triggered when the user types in a "character".

```sh
fzf --query foo --bind 'char:unbind(char)+clear-query+put'
```

**Comment by haolian9** [comment]
i'm fine with both of them, i can do some logic on (n)vim side.

**Comment by haolian9** [comment]
and yes, i really like this event+action approach, it avoid adding various cli flags and is more flexible.

**Comment by haolian9** [comment]
(i'm not familiar to ruby, so i can't easily add a test and run it locally, but this `Char` event is rather easy to [implement](https://github.com/haolian9/fzf/commit/0faff8ab46b7e0e2490f4bed9c96502324c20bca) :) )

thanks for your time! do you think this issue can be closed? it's done on my side.

**Comment by junegunn** [comment]
I haven't decided if I want to add the event to fzf. It feels like a niche feature that few users will find useful, I'd like to hear what others think.

**Comment by haolian9** [comment]
another week passed. i think you are right, not much users need it.

thanks for your help about the event+action solution, and thanks for your time.
