### ISSUE TITLE
Non-selectable lines (a workaround to multi-line)

### ISSUE THREAD

**Issue by jbriales** [junegunn/fzf#2980]
Multi-line support has been brought up many times before,
and there is good reasons from the main author why this won't be done in fzf:
- https://github.com/junegunn/fzf/issues/154#issuecomment-84503814
- https://github.com/junegunn/fzf/issues/2216#issuecomment-711131555

There might be an intermediate (simpler?) mechanism that provides users
with a path to manually emulate that multi-line scenario is really wanted:
Enable having "comment" or non-selectable entries
(e.g. by providing a `--comment-lines-with-prefix='//'` option),
which the cursor skips when moving over entries.
This would unblock e.g. showing additional information from a certain normal item line
by having the user preprocess the lines and splitting into several lines, properly prefixed.

The idea came partly from the dynamic header lines,
but applying to in-the middle of the list
(which seems definitely more complicated than headers).

Fine details would need to be discussed for this feature,
but I would love to hear some early thoughts from maintainer(s)
wrt if this kind of behavior could fit into the current core logic of the TUI.

One challenge that comes to mind is e.g. how to deal with these lines
when filtering via a query:
If a normal line before the comments is filtered out (i.e. not shown),
the corresponding comments line should not be shown either.

**Comment by junegunn** [comment]
https://junegunn.github.io/fzf/tips/processing-multi-line-items/
