### ISSUE TITLE
Using fzf --filter inside xargs

### ISSUE THREAD

**Issue by silcowitz** [junegunn/fzf#2983]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [x] zsh
    - [ ] fish

## Problem / Steps to reproduce
I came across this admittedly rare use case of using fzf --filter  inside an xargs command. My specific command is more complicated, but essentially this should work:

`echo "somefile" | xargs -I@ fzf --filter=@` 

I was expecting this to result in the output of just fzf --filter=somefile, **but the command just returns nothing**. Yes, I've checked that xargs is actually running the expected command. The same thing happens on both a Linux/Ubuntu server and on OSX/zsh.  

I tried wrapping in a shell, but still no luck:

`echo "somefile" | xargs -I@ sh -c "fzf --filter=@"` 

Strangely, it works if I pipe in a list of files to fzf instead of letting it scan the dir itself:

`echo "somefile" | xargs -I@ sh -c "find . -type f | fzf --filter=@"`

This returns 

`./somefile.txt`

What am I missing here? Is this supposed to work or is there a reason it shouldn't?

**Comment by haolian9** [comment]
i see no need in this command `echo "somefile" | xargs -I@ fzf --filter=@`
have you tried `filter="myfilter"; echo "somefile" | fzf --filter="$filter"`?

**Comment by silcowitz** [comment]
I know it's a simple example but I didn't want to include a ton of details on my specific use-case. The reason for using xargs is that I have a large number of search queries that are each being mapped to a specific file. Something like this:

`cat large_amount_of_lines.txt | xargs -I@ sh -c "fzf --filter=@ | head -1"`

This will return the best match for each line in the file. It's not efficient or anything, but it was just what I needed to get done. However like I said in my first post, `fzf --filter` seem to do something that makes xargs return without any output, which would seem to be a bug.

**Comment by junegunn** [comment]
fzf is a filter program (like grep) so it expects an input list its standard input stream.

```sh
seq 10 | fzf
```

But if fzf is started with no output stream attached to its standard input, in other words, its standard input is attached to a tty device, it will start `$FZF_DEFAULT_COMMAND` to generate the input list.

```sh
export FZF_DEFAULT_COMMAND='seq 100'
fzf
```

So if you run fzf like above, fzf will try to read its standard input stream instead of starting `$FZF_DEFAULT_COMMAND` but xargs produces nothing, so the input list is empty.

`xargs` provides `-o` option you can use in this scenario.

```sh
     -o      Reopen stdin as /dev/tty in the child process before executing the command.  This is useful if
             you want xargs to run an interactive application.
```

```sh
export FZF_DEFAULT_COMMAND='seq 100'
echo "5" | xargs -o -I@ fzf --filter=@
```

**Comment by silcowitz** [comment]
Ah, thanks for clarifying that. Yeah I was confused by the fact that running `fzf --filter=` on the cmd line would actually work, but I see now that only works because it's attached to tty in that case
