### ISSUE TITLE
Feature request: Remember line position

### ISSUE THREAD

**Issue by bitcoinmeetups** [junegunn/fzf#2987]
- [x ] I have read through the manual page (`man fzf`)
- [ x] I have the latest version of fzf
- [ x] I have searched through the existing issues

## Info

- OS
    - [x ] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x ] bash
    - [ ] zsh
    - [ ] fish

## Problem / Steps to reproduce

Feature request:

Hello,

I'm MB. A very nice and polite guy.

I have this feature request: remembering line position.

Sometimes I use fzf to go through documents manually and pick out URL's for example.

But every time I re-open the document like this for example (see below) I have to start at the top of the document again.

cat txtfile | fzf

It would be useful if there was a flag and a line history file to enable this feature.

So for example if last time I used fzf on the txtfile I finished on line 33 fzf will automatically display line 33 as the first line instead of line 1 for that document. 

Or something like that. Especially if it's a long document it gets almost impossible to go through it with fzf because every time I re-load I have to start from the beginning again. I can't use the search function because I want to scroll through the document vertically.

**Comment by bitcoinmeetups** [comment]
I think one way of accomplishing something like what I'm looking for is by letting fzf do things with lines in the background. 

Current behavior:

When user selects line fzf closes and does something with the line

Desirable behavior with flag --background:

When user selects line fzf does something with the line in the _background_. User can continue working with fzf and it does not close down.

**Comment by junegunn** [comment]
See https://github.com/junegunn/fzf#executing-external-programs
