### ISSUE TITLE
Checksums of darwin aren't included in GitHub Releases' checksum file

### ISSUE THREAD

**Issue by suzuki-shunsuke** [junegunn/fzf#2989]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [ ] fish

## Problem / Steps to reproduce

Thank you for your great project.

I found that the checksum of darwin aren't included in the checksum file.

[fzf_0.34.0_checksums.txt](https://github.com/junegunn/fzf/releases/download/0.34.0/fzf_0.34.0_checksums.txt)

https://github.com/junegunn/fzf/releases/tag/0.34.0

```
0655c27556d082641d501314737659b92318157e7ee675f15f7ed0fa1e9ccce4  fzf-0.34.0-windows_armv6.zip
10e9b70f1edf892c5e1893305685f15c43c79497a8033489dce77e707501689c  fzf-0.34.0-linux_arm64.tar.gz
15123c793b047fda466e48cb1aeeb152e70526c72292ce2bc8e8742eff516d49  fzf-0.34.0-linux_armv6.tar.gz
28e138eee33ea0e349812f5cae5ee72c00527feb7a949909a056bc79e846953c  fzf-0.34.0-freebsd_amd64.tar.gz
312739b4774b0edbe1b83c971e3c6bb902b90773d3331553753e3eba34c684c9  fzf-0.34.0-linux_amd64.tar.gz
3321da5e43598e30fe70416d879bc7ed712ca0631963ac6ee490446b4e3ef475  fzf-0.34.0-windows_armv7.zip
53f0c3c2df7598570cf8e66f39bb4e56987c5f924823a33c872380690fc7320d  fzf-0.34.0-linux_armv5.tar.gz
7355c60b3578abefdc1f129593961a76b950df94b4b6ac229db3cd2a20f407d4  fzf-0.34.0-windows_armv5.zip
74f281ed289d63ca4f65c9bbe6a4e1c61af8d0241264fcb8dd38736b44a3a736  fzf-0.34.0-linux_armv7.tar.gz
875151b30c39e17f9a74229d73463225dbea1444f414099b624ac1bd38262207  fzf-0.34.0-windows_arm64.zip
8fb01d13587fb1e240129ce11b5814ea2b7e08a9f014b363d3e79cec595b80e5  fzf-0.34.0-windows_amd64.zip
d94bf6c0f7c0aca09cc8932269bdb1d8404a07243f5d6ff1aca19f5cc891b85f  fzf-0.34.0-openbsd_amd64.tar.gz
```

[fzf_0.33.0_checksums.txt](https://github.com/junegunn/fzf/releases/download/0.33.0/fzf_0.33.0_checksums.txt) also doesn't include checksums for darwin.

**Comment by suzuki-shunsuke** [comment]
I'm not sure but maybe [.goreleaser.yml](https://github.com/junegunn/fzf/blob/master/.goreleaser.yml) is wrong. 🤔

**Comment by suzuki-shunsuke** [comment]
I checked some version's checksum files.

- 0.24.0, 0.25.1, 0.26.0: ⭕ include checksums for darwin
- 0.27.0, 0.27.1, 0.27.2, 0.33.0, 0.34.0: :x: don't include checksums for darwin

**Comment by junegunn** [comment]
Thanks for the report, I'll see what I can do.

**Comment by junegunn** [comment]
Will be fixed in the next release. Thanks.
