### ISSUE TITLE
0.34.0 breaks for Vim on Windows

### ISSUE THREAD

**Issue by AceofSpades5757** [junegunn/fzf#2992]
- [ ] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [ ] Mac OS X
    - [x] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [ ] fish
    - [x] cmd.exe

## Problem / Steps to reproduce

fzf 0.34.0 doesn't work on Vim 8.2 or 9.

1. Install Vim 8.2 or 9
2. Add `fzf.vim` and `fzf`. You can leave the latest version for the moment.
3. Run `fzf/install/install.ps1`
    * Using vim-plug: `powershell.exe -ExecutionPolicy Bypass -file "$Env:USERPROFILE\vimfiles\plugged\fzf\install.ps1"` 
    * I get errors using `fzf#install()`. Probably due to execution policy issues.
5. Try to use any of the Vim commands associated with `fzf.vim`. e.g. `:Commands`

A new buffer briefly pops up, but no errors pop up. All related Vim command quietly fail.

Following the same steps, but using version 0.33.0 works as expected.

**Comment by AceofSpades5757** [comment]
Yes, `0.34.0 (04d0b02)` located at `$HOME\.fzf\bin\fzf.exe` on path.

It looks like Vim commands will only mostly work when `0.34.0` is installed on the system, but the `fzf` plugin is set to tag `0.33.0`.

**Comment by junegunn** [comment]
Can you check the output of the following commands in Vim?

* `:echo fzf#exec()`
* `:echo system(fzf#exec() .. ' --version')`

> 2\. Add `fzf.vim` and `fzf`.

So you're using vim-plug, what are the exact `Plug` statements you use for them?

**Comment by AceofSpades5757** [comment]
`:echo fzf#exec()`

* `C:\Users\Kyle L. Davis\.vim\plugged\fzf/bin/fzf`
* If I remove that bin directory, it'll use the `fzf` on `PATH` and simply out `fzf`.

`:echo system(fzf#exec() .. ' --version')`

* `'C:\Users\Kyle' is not recognized as an internal or external command, operable program or batch file.`

`echo system(shellescape(fzf#exec()) .. ' --version')` (to fix the space issue)

* `0.34.0 (04d0b02)`

**Plug Statements**

```vimL
Plug 'junegunn/fzf',
    \ {'do': {-> fzf#install()}}
    \ | Plug 'junegunn/fzf.vim'
```

**Comment by junegunn** [comment]
Can you check if it's fixed on master?

**Comment by AceofSpades5757** [comment]
@junegunn Seems to work great now. Thanks!
