### ISSUE TITLE
fzf works with Cygwin

### ISSUE THREAD

**Issue by Elger9** [junegunn/fzf#2994]
- [ ] I have read through the manual page (`man fzf`)
- [ ] I have the latest version of fzf
- [ ] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [ ] Mac OS X
    - [x] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [x] zsh
    - [ ] fish

## Problem / Steps to reproduce

Not really an issue but information. 

fzf works very nicely with Cygwin mintty and Windows Terminal (via ssh) if you use https://github.com/junegunn/fzf/issues/2798#issuecomment-1229376159 

I suggest adding this information in https://github.com/junegunn/fzf/wiki/Cygwin

**Comment by junegunn** [comment]
Thanks for letting me know. Anyone can edit the wiki page, so would you be willing to add the information to it?

**Comment by Elger9** [comment]
Update the wiki
