### ISSUE TITLE
unknown option: --scheme=history

### ISSUE THREAD

**Issue by vimalk78** [junegunn/fzf#2996]
- [X] I have read through the manual page (`man fzf`)
- [X] I have the latest version of fzf
- [X] I have searched through the existing issues

## Info

- OS
    - [X] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [X] bash
    - [ ] zsh
    - [ ] fish

## Problem / Steps to reproduce
press `Ctrl-r` , the key binding for history, i get the error
```
unknown option: --scheme=history
```
fzf version :
```
$ ~/.fzf/bin/fzf --version
0.34.0 (04d0b02)
```

bash version:
```
 $ bash --version
GNU bash, version 5.1.8(1)-release (x86_64-redhat-linux-gnu)
```

what did i do which (perhaps) messed it up?
```
executed :PlugUpdate in neovim
```

**Comment by vimalk78** [comment]
reverting change to file (`shell/key-bindings.bash`) in commit https://github.com/junegunn/fzf/commit/6fb41a202a97ad3f2437f6e5aee8890268560412 fixed the issue for me

**Comment by Madcat148** [comment]
@vimalk78 is correct, I'll keep it here to simplify the fix for others:
```
git reset 6dcf5c3 shell/key-bindings.bash
./install
```

**Comment by junegunn** [comment]
Make sure that `which fzf` is pointing to the right version.

**Comment by nairobi02** [comment]
> 

hello, i did 
git reset 6dcf5c3 shell/key-bindings.bash
./install
but im still having this issue, how do i make sure ```which fzf``` is pointing to the right version?

**Comment by nairobi02** [comment]
> reverting change to file (`shell/key-bindings.bash`) in commit [6fb41a2](https://github.com/junegunn/fzf/commit/6fb41a202a97ad3f2437f6e5aee8890268560412) fixed the issue for me

hey i did 
git reset https://github.com/junegunn/fzf/commit/6dcf5c3d7d6c321b17e6a5673f1533d6e8350462 shell/key-bindings.bash
./install

it still doesn't seem to be working, is there anything else that you did post this?

**Comment by junegunn** [comment]
You shouldn't revert changes. There is no bug. The problem is that you're using an out-dated version of fzf.

```sh
which fzf
$(which fzf) --version
```

Adjust your $PATH so that your shell picks up the latest version of fzf.

**Comment by nairobi02** [comment]
> You shouldn't revert changes. There is no bug. The problem is that you're using an out-dated version of fzf.
> 
> ```shell
> which fzf
> $(which fzf) --version
> ```
> 
> Adjust your $PATH so that your shell picks up the latest version of fzf.

I do not understand, eveytime i try to pull, it says im on the the latest version, 
```fzf --version``` outputs ```0.29 deval``` , how do i upgrade to 0.3+? 
Also it is only the ```ctrl+r``` command that doesnt work, ```ctrl+t``` and ```alt+c``` work fine. 



```

unknown option: --scheme=history
╰─❯ cd ~/.fzf && git pull && ./install
Already up to date.
Downloading bin/fzf ...
  - Already exists
  - Checking fzf executable ... 0.34.0
Do you want to enable fuzzy auto-completion? ([y]/n) y
Do you want to enable key bindings? ([y]/n) y

Generate /home/nair/.fzf.bash ... OK

Do you want to update your shell configuration files? ([y]/n) y

Update /home/nair/.bashrc:
  - [ -f ~/.fzf.bash ] && source ~/.fzf.bash
    - Already exists: line #171

Finished. Restart your shell or reload config file.
   source ~/.bashrc  # bash

Use uninstall script to remove fzf.

For more information, see: https://github.com/junegunn/fzf


╰─❯ fzf --version
0.29 (devel)
```

**Comment by vimalk78** [comment]
pls try `whereis fzf`

**Comment by nairobi02** [comment]
> 

Thank you for your reply, 

╰─❯ whereis fzf
fzf: /usr/bin/fzf /home/nair/.fzf/bin/fzf /usr/share/man/man1/fzf.1.gz

**Comment by 4DRIAN0RTIZ** [comment]
### In case it serves to someone:
I had installed the fzf via apt in Lubuntu (**sudo apt-get install fzf**) but it didn't work for me, so what I did was clone it to install it and that's when the error "unknown option: --scheme=history" appeared. What I did was uninstall the fzf (**sudo apt-get remove --purge fzf**) immediately I pressed CRTL + R and it worked.

**Comment by kimme** [comment]
> ### In case it serves to someone:
> I had installed the fzf via apt in Lubuntu (**sudo apt-get install fzf**) but it didn't work for me, so what I did was clone it to install it and that's when the error "unknown option: --scheme=history" appeared. What I did was uninstall the fzf (**sudo apt-get remove --purge fzf**) immediately I pressed CRTL + R and it worked.

This fixed my troubles with the keybinding "Ctrl-R" in any shell (Alacritty, Bash) in my daily driver Linux Mint 21.1.

**Comment by niedzielski** [comment]
This got me too. I had built fzf locally (`make clean && make build`) and somehow was linking to fzf/bin/fzf instead of fzf/target/fzf-linux_amd64. The former was not cleaned by make so I was always referencing a very old version, v0.21.1 (334a4fa). The easiest way to debug is to check version (`fzf --version`).

**Comment by vim345** [comment]
> 28/08/2023 for debian/ubuntu user, don't install the package from repository manager (apt), it's an outdated version, just install it from github repo to point to the latest version

++ on this.

Also if you're like me and cannot uninstall the fzf that's installed using apt or other package management system, you need to update PATH in `!/.fzf.sh` so that it will use your local version of fzf. Something similar to this:

```
if [[ ! "$PATH" == */home/<YOUR NAME>/.fzf/bin* ]]; then
  PATH="/home/<YOUR NAME>/.fzf/bin:${PATH:+${PATH}:}"
fi
```

**Comment by pvarin-figure** [comment]
This issue came back for me in `0.45.0`

**Comment by rfletchr** [comment]
I had this issue because I had a system version of fzf previously installed. Once I removed my system fzf

`sudo apt remove fzf -y` 

the problem went away.

**Comment by radutomy** [comment]
I uninstalled the apt version of fzf. However, now I'm getting:

> Command 'fzf' not found, but can be installed with:                                                                                                root@box
apt install fzf
~/.config/fish/functions/_fzf_wrapper.fish (line 20):
    fzf $argv
    ^~^
in function '_fzf_wrapper' with arguments '--read0 --print0 --multi --scheme=history --prompt=History\>\  --query= --preview=string\ replace\ --regex\ \'^.\*\?\ │\ \'\ \'\'\ --\ \{\}\ \|\ fish_indent\ --ansi --preview-window=bottom:3:wrap'
        called on line 2 of file ~/.config/fish/functions/_fzf_search_history.fish
in command substitution
        called on line 18 of file ~/.config/fish/functions/_fzf_search_history.fish

**Comment by 4DRIAN0RTIZ** [comment]
> I uninstalled the apt version of fzf. However, now I'm getting this when pressing `CTRL + R`:
> 
> > Command 'fzf' not found, but can be installed with:                                                                                                
> apt install fzf
> ~/.config/fish/functions/_fzf_wrapper.fish (line 20):
>     fzf $argv
>     ^~^
> in function '_fzf_wrapper' with arguments '--read0 --print0 --multi --scheme=history --prompt=History\>\  --query= --preview=string\ replace\ --regex\ \'^.\*\?\ │\ \'\ \'\'\ --\ \{\}\ \|\ fish_indent\ --ansi --preview-window=bottom:3:wrap'
>         called on line 2 of file ~/.config/fish/functions/_fzf_search_history.fish
> in command substitution
>         called on line 18 of file ~/.config/fish/functions/_fzf_search_history.fish

Did you install fzf with the git command that is in the repository?

**Comment by 4DRIAN0RTIZ** [comment]
> I uninstalled the apt version of fzf. However, now I'm getting this when pressing `CTRL + R`:
> 
> > Command 'fzf' not found, but can be installed with:                                                                                                
> apt install fzf
> ~/.config/fish/functions/_fzf_wrapper.fish (line 20):
>     fzf $argv
>     ^~^
> in function '_fzf_wrapper' with arguments '--read0 --print0 --multi --scheme=history --prompt=History\>\  --query= --preview=string\ replace\ --regex\ \'^.\*\?\ │\ \'\ \'\'\ --\ \{\}\ \|\ fish_indent\ --ansi --preview-window=bottom:3:wrap'
>         called on line 2 of file ~/.config/fish/functions/_fzf_search_history.fish
> in command substitution
>         called on line 18 of file ~/.config/fish/functions/_fzf_search_history.fish

Did you install fzf with the git command that is in the repository?

**Comment by rfletchr** [comment]
> > I uninstalled the apt version of fzf. However, now I'm getting this when pressing `CTRL + R`:
> > > Command 'fzf' not found, but can be installed with:
> > > apt install fzf
> > > ~/.config/fish/functions/_fzf_wrapper.fish (line 20):
> > > fzf $argv
> > > ^~^
> > > in function '_fzf_wrapper' with arguments '--read0 --print0 --multi --scheme=history --prompt=History>\  --query= --preview=string\ replace\ --regex\ '^.*?\ │\ '\ ''\ --\ {}\ |\ fish_indent\ --ansi --preview-window=bottom:3:wrap'
> > > called on line 2 of file ~/.config/fish/functions/_fzf_search_history.fish
> > > in command substitution
> > > called on line 18 of file ~/.config/fish/functions/_fzf_search_history.fish
> 
> Did you install fzf with the git command that is in the repository?

yeah it seems like the new fzf is not in the PATH.
