### ISSUE TITLE
How to built from source?

### ISSUE THREAD

**Issue by Hubbitus** [junegunn/fzf#300]
Hello.
I'm new in go language. I want built rpm package of fzf (and possible propogate it into Fedora).

But can't find instruction how to do not download binaries (what by default) and build from source go-version (ruby version marked a deprecated in source header).

So far I on just start:
```
$ pwd
/home/pasha/SOFT/rpmbuild/BUILD/fzf-0.10.0/src
[pasha@hubbitus src]$ make
Makefile:2: *** GOPATH is undefined.  Stop.
[pasha@hubbitus src]$ GOPATH=/home/pasha/SOFT/rpmbuild/BUILD/fzf-0.10.0 make
go get
go install: no install location for directory /home/pasha/SOFT/rpmbuild/BUILD/fzf-0.10.0/src outside GOPATH
Makefile:36: recipe for target 'test' failed
make: *** [test] Error 1
```

Could you please provide detailed instruction or enhance makefile to do so straight forward?

With best wishes, Pavel Alexeev.

**Comment by junegunn** [comment]
Set up Go development environment with proper $GOPATH and just type in `go get github.com/junegunn/fzf/src/fzf` which will clone the repository inside $GOPATH and build fzf executable. From then on, Makefile in the cloned repository will work as expected.

> Could you please provide detailed instruction or enhance makefile to do so straight forward?

I do not guarantee that the latest code on the master branch is stable or backward-compatible, so building fzf from source is not recommended at the moment unless you know exactly what you're doing, which is, however, not the case for most users. So I have no plan to make it more accessible at the moment.

**Comment by Hubbitus** [comment]
Auto cloning repository is not the option because build on farm happened without network support and source tarball should be verified for reproducible build.

Ok, thanks for the answer. Now I then will try percol which have similar functionality and use standard python build system.
