### ISSUE TITLE
Ctrl-r for fresh search

### ISSUE THREAD

**Issue by HiroshiMatsumoto** [junegunn/fzf#3003]
- [x ] I have read through the manual page (`man fzf`)
- [x ] I have the latest version of fzf
- [ x] I have searched through the existing issues

## Info

- OS
    - [x ] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ x] zsh
    - [ ] fish

## Problem / Steps to reproduce

It is about ctr-r incremental history search.
Is it possible to customize/tweak a configuration file to start a fresh search whenever you ctrl-r on command line ?

The trouble with current, default setup, is whenever you ctrl-r you search for query with commands in the prompt.
But I would prefer a fresh search.

Let's say having command like below, 
```
$ mkdir workdir && cd wor
```
and want to look for the folloing command query previously written.

```
mkcd test
```
But when you `ctrl-r`  there, then it starts searching with `mkdir workdir` preinput in the search prompt.

There I would prefer having nothing in search prompt, and search for new query, `mkc` to inquire `mkcd test` quicker.

Thanks in advance,

**Comment by junegunn** [comment]
There is no such option, but you can hit CTRL-U to clear the fzf prompt just like you do it in your shell.

Alternatively, you can hit CTRL-U first to clear the shell prompt, then press CTRL-R to start fzf.
