### ISSUE TITLE
Alt-c keeps triggering fzf even the bind is removed

### ISSUE THREAD

**Issue by Aster89** [junegunn/fzf#3008]
At the time of my last comment I abandoned fzf, but recently I've been using the Vim plugin and I've been very happy with it, which made me want to reuse it even in command line, so I've looked at your suggestion

> ```shell
> set -o vi
> [ -f ~/.fzf.bash ] && source ~/.fzf.bash
> 
> # Re-bind it to CTRL-Q
> bind "$(bind -s | grep '^"\\ec"' | sed 's/ec/C-q/')"
> [[ $- =~ i ]] && bind '"\ec": nop'
> ```

but I observe a strange behavior, where <kbd>Alt</kbd>+<kbd>c</kbd> keeps triggering fzf, as the GIF below shows.

Do you have any clue?

![altc](https://user-images.githubusercontent.com/20521900/194089250-b3b98c18-d8ff-4441-9811-d5fd6b3e0c18.gif)

I'm not sure what could trigger this behavior, so please, tell me if more information is needed to understand what's going on.

For now, I can think of the following info:

  - I've added these two lines at the end of my `~/.bashrc` (I'm trying to map fzf to <kbd>Alt</kbd>+<kbd>d</kbd> instead of <kbd>Ctrl</kbd>+<kbd>q</kbd>)
    ```bash
    bind "$(bind -s | command grep '^"\\ec"' | sed 's/ec/ed/')"
    [[ $- =~ i ]] && bind '"\ec": nop'
    ```
    leaving the other two because
    1. I don't have an `~/.fzf.bash` file
    2. I set the vi mode via `~/.inputrc`
  - `~/.inputrc` has the following content
    ```inputrc
    $include /etc/inputrc
    set editing-mode vi
    set show-mode-in-prompt on
    set vi-ins-mode-string \1\e[36;1m\2 \1\e[0m\2
    set vi-cmd-mode-string \1\e[32;1m\2☻ \1\e[0m\2
    set skip-completed-text on
    "\t": menu-complete
    "\e[Z": menu-complete-backward
    set completion-ignore-case on
    "\C-e": shell-expand-line
    set colored-stats on
    set visible-stats on
    ```

_Originally posted by @Aster89 in https://github.com/junegunn/fzf/issues/1238#issuecomment-1268548662_

**Comment by junegunn** [comment]
Bindings have changed since #1238 (2018)

https://github.com/junegunn/fzf/blob/d56fe74e247dc3c5e70a3f6482ff1ece8b5f638a/shell/key-bindings.bash#L97-L100

So you would need to do something like this:

```sh
bind -m vi-command '"\ec": nop'
```

**Comment by Aster89** [comment]
Thanks for pointing out how I should disable <kbd>Alt</kbd>+<kbd>c</kbd>.

But as regards how to enable <kbd>Alt</kbd>+<kbd>d</kbd> instead, the following seem to only apply to insert mode:
```bash
bind "$(bind -s | command grep '^"\\ec"' | sed 's/ec/ed/')"
```
and things like the following just don't work
```bash
bind -m vi-command,vi-insert "$(bind -s | command grep '^"\\ec"' | sed 's/ec/ed/')" # errors, wrong syntax
bind -m vi-command -m vi-insert "$(bind -s | command grep '^"\\ec"' | sed 's/ec/ed/')" # the latter -m replaces the former
```

Well, apprently the following seems to work (clearly _before_ disabling <kbd>Alt</kbd>+<kbd>c</kbd>, just like the original solution):
```bash
bind -m vi-command '"\ed": "\C-z\ec\C-z"'
bind -m vi-insert '"\ed": "\C-z\ec\C-z"'
```

---

Incidentally, upon looking a bit into `man bash`, maybe
```bash
bind -m vi-command -r '\ec'
bind -m vi-insert -r '\ec'
```
is more idiomatic for disabling <kbd>Alt</kbd>+<kbd>c</kbd>
