### ISSUE TITLE
FZFMru freshens only after restarting vim?

### ISSUE THREAD

**Issue by regedarek** [junegunn/fzf#301]
This is my fzf configuration: https://github.com/regedarek/fzf-configuration/blob/master/plugin/fzf-configuration.vim

```
" fzf mru
command! FZFMru call fzf#run({
            \'source': v:oldfiles,
            \'sink' : 'e ',
            \'options' : '-m',
            \})
```

I open a file then I call ``:FZFMru``. And at the bottom of my list I don't see my last opened file.
It appears when I restart vim and call ``:FZFMru``

Is there a chance to change that behaviour?

**Comment by netei** [comment]
Probably you should add this to your .vimrc :  

    set viminfo='100,<50,s10,h,f1
 > 9. The viminfo file : *viminfo* *viminfo-file* *E136*
 > *E575* *E576* *E577*

 > If you exit Vim and later start it again, you would normally lose a lot of
 > information.  The viminfo file can be used to remember that information, which
 > enables you to continue where you left off.
 >
 > This is introduced in section |21.3| of the user manual.
 >
 > The viminfo file is used to store:
 > - The command line history.
 > - The search string history.
 > - The input-line history.
 > - Contents of non-empty registers.
 > - Marks for several files.
 > - File marks, pointing to locations in files.
 > - Last search/substitute pattern (for 'n' and '&').
 > - The buffer list.
 > - Global variables.
 >
 > The viminfo file is not supported when the |+viminfo| feature has been
 > disabled at compile time.

**Comment by regedarek** [comment]
Unhappily adding viminfo does not help. Maybe these is related to neovim which I am using?

This is my nvimrc: https://github.com/regedarek/dotfiles/blob/master/nvimrc

**Comment by junegunn** [comment]
According to `:help v:oldfiles`, it is the expected behavior of `v:oldfiles`:

> v:oldfiles	List of file names that is loaded from the |viminfo| file **on startup**.

So you'll have to merge v:oldfiles with the list of open buffers using some vimscript.

**Comment by regedarek** [comment]
Right now I am using FZFMru as here:

```
command! FZFMru call s:fzf_wrap({
    \'source':  'bash -c "'.
    \               'echo -e \"'.s:old_files().'\";'.
    \               'ag -l -g \"\"'.
    \           '"',
    \})

function! s:fzf_wrap(dict)
    let defaults = {
    \'sink' : 'edit',
    \'options' : '-m --no-sort -x',
    \   'tmux_height': '40%',
    \}
    call extend(a:dict, defaults, 'keep')
    call fzf#run(a:dict)
endfunction

function! s:old_files()
    let oldfiles = copy(v:oldfiles)
    call filter(oldfiles, 'v:val !~ "fugitive"')
    call filter(oldfiles, 'v:val !~ "NERD_tree"')
    call filter(oldfiles, 'v:val !~ "^/tmp/"')
    call filter(oldfiles, 'v:val !~ ".git"')
    return join(oldfiles, '\n')
endfunction
```

I tried to add there also buffers:

```
function! s:buflist()
  redir => ls
  silent ls
  redir END
  return split(ls, '\n')
endfunction
```
but without success, there is some string/list problem.

**Comment by junegunn** [comment]
```vim
command! FZFMru call fzf#run({
\ 'source':  reverse(s:all_files()),
\ 'sink':    'edit',
\ 'options': '-m --no-sort -x',
\ 'down':    '40%' })

function! s:all_files()
  return extend(
  \ filter(copy(v:oldfiles),
  \        "v:val !~ 'fugitive:\\|NERD_tree\\|^/tmp/\\|.git/'"),
  \ map(filter(range(1, bufnr('$')), 'buflisted(v:val)'), 'bufname(v:val)'))
endfunction
```

**Comment by regedarek** [comment]
Thanks a lot, that is exactly what I expected.
