### ISSUE TITLE
How to set keybinding to accept and execute

### ISSUE THREAD

**Issue by tjx666** [junegunn/fzf#3010]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

## Problem / Steps to reproduce

I want to using one keybing to accept the current item and execute the result after fzf paste.

The following example using fzf + fzf-tab.

<img width="1040" alt="image" src="https://user-images.githubusercontent.com/41773861/196000196-532fb153-2e53-4083-bb24-6d296f4392e8.png">

**Comment by junegunn** [comment]
You should do it in your script. `execute` bindings are for running external programs *without* quitting fzf.

```sh
output=$(fzf) && echo "Do something with $output"
```
