### ISSUE TITLE
Vim plugin, `:FZF` and buffers

### ISSUE THREAD

**Issue by carlescufi** [junegunn/fzf#3013]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

## Problem / Steps to reproduce

I have installed both FZF and fzf.vim. The issue I have is that using `:FZF` and then selecting a file and pressing "Enter" seems to "replace" the contents of my current buffer. Instead, I'd like FZF to perform the equivalent of `:e <file>` when pressing "Enter", so that I can then list all files I've opened with FZF using `:ls`.

Note, the fzf.vim `:Files` option seems to do what I want, but I am still puzzled as to why `:FZF` does not.

**Comment by junegunn** [comment]
I can't reproduce the problem. Can you check if you still have the issue with the following minimal vimrc?

```sh
vim -Nu <(curl https://gist.githubusercontent.com/junegunn/6936bf79fedd3a079aeb1dd2f3c81ef5/raw)
```

(https://gist.githubusercontent.com/junegunn/6936bf79fedd3a079aeb1dd2f3c81ef5/raw)

**Comment by carlescufi** [comment]
Me neither, cannot reproduce it any longer. Thanks for checking, closing now.
