### ISSUE TITLE
ESC - does not return the root directory/path anymore

### ISSUE THREAD

**Issue by OilSubjectLoss7** [junegunn/fzf#3014]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [x] fish

## Problem / Steps to reproduce
so, i was using the 30 build. it was working fine then.
then i updated it to the most recent one.

i have this set up
`
fd . -a -t d -p |fzf --ansi
`
before the update, if i press ESC key it returns `.` or the given or current root directory/path.

but after the update it returns nothing or an empty string.

**Comment by junegunn** [comment]
I think you're confused somehow. fzf shouldn't print anything on ESC. It has always been so.

**Comment by OilSubjectLoss7** [comment]
is there a way to make the root or current path/directory as a selection then?

**Comment by junegunn** [comment]
Well, something like `fd . -a -t d -p | fzf --ansi || echo $PWD`?

**Comment by OilSubjectLoss7** [comment]
> Well, something like `fd . -a -t d -p | fzf --ansi || echo $PWD`?

thanks

**Comment by OilSubjectLoss7** [comment]
> Well, something like `fd . -a -t d -p | fzf
--ansi || echo $PWD`?

another query, how about the target path root
path/directory though?

i.e.  
` fd . -a -t d -p 'foo/bar' | fzf --ansi `

so if i push `ESC` it will default to `foo/bar`
path/directory instead of its subdirectories
i.e. `foo/bar/cat` or `foo/bar/dog`
