### ISSUE TITLE
[Bug] Preview option "--preview-window=right,60%" display error "Illegal character <'>" in neovim

### ISSUE THREAD

**Issue by DanSM-5** [junegunn/fzf#3018]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

## Problem / Steps to reproduce
I noticed that on neovim calling the function `fzf#vim#files` with the option `--preview-window` will display an error if the value for the preview-window argument contains a coma `(,)`.

I can reproduce with the following code:
First add some helper functions in vimrc
```
func! GetCurrentBufferPath () abort
   return trim(expand('%:p:h'))
endf

func! g:TestFZF () abort
  let gitpath = trim(system('cd '.shellescape(expand('%:p:h')).' && git rev-parse --show-toplevel'))

  if isdirectory(gitpath)
    return gitpath
  else
    return GetCurrentBufferPath()
  endif
endf
```
Now try calling the commands
```
:call fzf#vim#files(g:TestFZF(), { 'options': [ '--preview-window=right,60%', '--info=inline', '--preview', 'bat --color=always {}' ] }, 0)
```
It will show an error before and after showing the fzf window.
![image](https://user-images.githubusercontent.com/49035812/197317372-21232500-ff0c-42bf-abf9-5665e9bff8cf.png)
![image](https://user-images.githubusercontent.com/49035812/197317388-427850d2-594a-4f5b-8492-7ad0e22cf424.png)

If removed the `,` from the --preview-window option, it will work
```
:call fzf#vim#files(g:TestFZF(), { 'options': [ '--preview-window=right', '--info=inline', '--preview', 'bat --color=always {}' ] }, 0)
```
![image](https://user-images.githubusercontent.com/49035812/197317441-02b10826-5f83-42a5-bdfd-0bfadcc17a21.png)

**NOTE**: Simply using './' as the first argument of `fzf#vim#files` will produce the same result. I added the functions I tested because I noticed I took the screenshots with them.

Additional details:
 - fzf v0.34.0 (dad26d8)
 - neovim
```
nvim --version
NVIM v0.8.0
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by linuxbrew@04d933e5bf3e

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/home/linuxbrew/.linuxbrew/Cellar/neovim/0.8.0/share/nvim"
```
This seems to occur only on neovim from brew as the same option won't trigger an error on regular vim. 
I'm running neovim on WSL2 (Ubuntu). Out of curiosity I tried the same on neovim on windows (executed from powershell) and the issue didn't happened. Both vim (wsl2) and neovim (windows) were run with the same configuration files and same version of fzf.

- Vim on wsl2
  - VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Sep 13 2022 09:35:02)
- Neovim windows
```
NVIM v0.8.0-1210-gd367ed9b2
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compiled by runneradmin@fv-az177-603

Features: -acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM\sysinit.vim"
  fall-back for $VIM: "C:/Program Files (x86)/nvim/share/nvim"
```
Any suggestion to add a 60% preview width without using --preview-window option would be helpful.

**Comment by junegunn** [comment]
I can't reproduce the problem. Maybe you're running an outdated version of fzf on that machine?

* https://github.com/junegunn/fzf/commit/da1f64567064de34bc26fd3b6390fb80f0054319

See if it's picking up the right version by running `:echo system(shellescape(fzf#exec()) .. ' --version')`

**Comment by DanSM-5** [comment]
It is picking the right version.
![image](https://user-images.githubusercontent.com/49035812/197897092-6cb03d6e-48dd-4f7f-ac06-f2616922f8f4.png)

At first I thought it was the comma but other options with comma `,` seems to work just fine (e.g. bindings):
`'--bind', 'ctrl-/:toggle-preview,alt-up:preview-page-up,alt-down:preview-page-down'`

Something that I can confirm is that it reproduces with neovim from brew. I tested today on a mac pre update (neovim 0.7.2) and post update (neovim 0.80) and I could reproduce the same issue with the `,` all with fzf v0.34.0.

If you have the chance, could you try to reproduce with neovim from brew's source?

**Comment by junegunn** [comment]
Built the latest neovim from source (`brew install --HEAD neovim` / `NVIM v0.9.0-dev-163+gec33edc7b-dirty`), and your code runs without any problem.

**Comment by DanSM-5** [comment]
Yes, I tried today with only fzf and fzf.vim plugins and it works on neovim 0.9.0. There must be something else that is causing the issue.
I'll continue investigating on my side. Thanks for the help.
