### ISSUE TITLE
FZFMru should ignore NERDTree buffer

### ISSUE THREAD

**Issue by regedarek** [junegunn/fzf#302]
Right now in on my mru list i see often NERD_tree_1. How to ignore these buffer name?

```
command! FZFMru call fzf#run({
            \'source': v:oldfiles,
            \'sink' : 'e ',
            \'options' : '-m',
            \})
```

**Comment by junegunn** [comment]
I think `filter(copy(v:oldfiles), 'v:val !~ "NERD_tree"')` should do. But you might want to write an external sink function if you want to fine-tune the list.
