### ISSUE TITLE
Ctrl+T is not observing .rgignore (but 'fzf' is)

### ISSUE THREAD

**Issue by raph90** [junegunn/fzf#3026]
- [x ] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

## Problem / Steps to reproduce

Steps to reproduce: 
- Install fzf with brew on Macos
   (also run the script to set up the keybindings)
- install rg
- put the folllowing lines in zshrc and source: 
```
[ - f ~/.fzf.zsh ] && source ~/.fzf.zsh

export FZF_DEFAULT_COMMAND='rg --files --hidden'
```
- create `.rgignore` at ~/ and put Library/ inside it

run fzf in the terminal - everything works as expected, but Ctrl+T and Library files are not ignored.

**Comment by junegunn** [comment]
See https://github.com/junegunn/fzf#environment-variables
