### ISSUE TITLE
Info separator

### ISSUE THREAD

**Issue by junegunn** [junegunn/fzf#3029]
Notice the horizontal separator after the info (`95/95 ────────`)

<img width="565" alt="image" src="https://user-images.githubusercontent.com/700826/198840259-257278cc-cc96-48cd-a958-703c78d5ab79.png">

<img width="565" alt="image" src="https://user-images.githubusercontent.com/700826/198840277-6d388315-2d4b-453a-9c6e-4b5aecea4026.png">

<img width="565" alt="image" src="https://user-images.githubusercontent.com/700826/198840589-9d14987a-57d7-4f4a-ae2d-4deeb58044d2.png">

<img width="565" alt="image" src="https://user-images.githubusercontent.com/700826/198840517-18f024f4-83a3-4554-8fd5-a3e226ccef2e.png">

* Like it or not?
* Need something like`--no-info-separator` or `--info=nosep`?

**Comment by BlueFalconHD** [comment]
love it!

**Comment by laktak** [comment]
PSA: the option to disable the separator is now called `--no-separator`
