### ISSUE TITLE
While tmux is zoomed, invoke fzf in vim will make tmux unzoomed 

### ISSUE THREAD

**Issue by trungphan** [junegunn/fzf#303]
Steps:
* Open tmux with multiple pane
* Open vim in one of the panes
* Zoom the pane (ctrl+b z)
* call fzf#run in vim => the tmux is unzoomed.

Maybe fzf should detect if tmux is in zoomed mode and use the current pane for fzf instead of creating a new one.

**Comment by junegunn** [comment]
That is actually a very nice idea.

**Comment by junegunn** [comment]
Patch pushed to master. I also applied the same trick to `fzf-tmux` script. Thanks.

**Comment by junegunn** [comment]
Oops, I was in a haste and forgot that the result of `s:tmux_enabled()` is cached. Pushed another commit.

**Comment by trungphan** [comment]
Perfect. Thanks
