### ISSUE TITLE
Modes like in vim

### ISSUE THREAD

**Issue by timsofteng** [junegunn/fzf#3032]
Hello. It's not an issue so I've decide not to fill form.

Is it possible to implement modes into fzf like in vim? I mean for example I used to use g and G to navigate form top to bottom in vim's normal mod. Could I achieve something similar with fzf?

**Comment by Delapouite** [comment]
Hi. I think you may find some answers in this recent thread https://github.com/junegunn/fzf/issues/3015

**Comment by timsofteng** [comment]
@Delapouite got it. I'm closing it as duplicated.
