### ISSUE TITLE
fzf-vim: Neovim 0.8.0 breaks FZF colors

### ISSUE THREAD

**Issue by BourgondAries** [junegunn/fzf#3035]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

## Problem / Steps to reproduce

This is using alacritty as the terminal emulator:
`useradd --create-home -d /home/test test` -- Create a test user
`sudo passwd test` -- Give it a login password
`su -l test` -- Log into test with a clean environment
`mkdir -p ~/.config/nvim/pack/bundle/start`
`git clone https://github.com/junegunn/fzf ~/.config/nvim/pack/bundle/start/fzf`
`nvim`
`:FZF`
`fzf executable not found. Download binary? (y/n) y`
FZF downloads... then the resulting window pops up.

On the left side is the working case with nvim 0.7.2, on the right side is the faulty case with nvim 0.8.0.

![Fri Nov  4 02:32:39 PM GMT 2022](https://user-images.githubusercontent.com/4683721/200004978-f6056fb3-5ea6-497d-b3e9-869d962f1fa4.png)

**Comment by junegunn** [comment]
This was reported before: https://github.com/junegunn/fzf.vim/issues/1431

There are workarounds, but I'll see what I can do.

**Comment by BourgondAries** [comment]
I only searched for "faulty colors neovim 0.8", so did not find this already filed issue. For future visitors: It appears that `vim.api.nvim_set_hl(0, 'NormalFloat', {fg='LightGrey'})` works, but I'm not sure if that's the correct thing to issue in all cases (if it interferes with anything else).

**Comment by tomtomjhj** [comment]
@junegunn  With https://github.com/junegunn/fzf/commit/0881a6bc17d970d2833be21fafc8de69fe468631, the fzf window uses `NormalFloat` defined by colorscheme the user is using.

If the intended behavior is to use `Normal` for fzf window (which seems to be true for vim), then I think this should be like this, based on https://github.com/neovim/neovim/pull/9722#discussion_r264777602
```diff
-    silent! call setwinvar(win, '&winhighlight', 'Pmenu:')
+    silent! call setwinvar(win, '&winhighlight', 'Normal:')
```

**Comment by junegunn** [comment]
@tomtomjhj Thanks for the comment, actually I'm aware of that.

> This commit makes the colors of fzf window default to those of 'Normal'
> group **(or 'NormalFloat' if defined)**, by ignoring Pmenu group.

 I felt that it makes sense to respect `NormalFloat`, while choosing `Pmenu` for fzf is most likely a mistake. Do you think we should only choose `Normal` and not `NormalFloat`? I'm not a Neovim user so I don't know how most Neovim users configure their `NormalFloat`.

**Comment by tomtomjhj** [comment]
> actually I'm aware of that.
> 
> > This commit makes the colors of fzf window default to those of 'Normal'
> > group **(or 'NormalFloat' if defined)**, by ignoring Pmenu group.

Sorry, my bad.

> Do you think we should only choose `Normal` and not `NormalFloat`?

At first, I didn't like this change because it changed the behavior I was used to, but now I think the new behavior is the best option, because
* `Normal:` seems to be buggy: when `winblend` is non-zero and the user switches to another colorscheme, the fzf window's highlighting is broken, so we can't use this;
* we don't want to reintroduce the behavior fixed by 0881a6bc17d970d2833be21fafc8de69fe468631; and
* users can override `winhighlight` in `FileType fzf` anyway.

> I'm not a Neovim user so I don't know how most Neovim users configure their `NormalFloat`.

I set bg of `NormalFloat` to dark gray in `bg=dark` and to light gray in `bg=light`, so `NormalFloat` for fzf window works well for me.
But I can't say for sure for other users because I use my custom colorscheme.
Let's see if someone else complains.

**Comment by Frederick888** [comment]
May I know how I can have transparent background now without changing `NormalFloat` for everything?

```vim
highlight Normal ctermbg=NONE guibg=NONE
let g:fzf_colors = { 'bg': [ 'bg', 'Normal' ] }
```

doesn't work probably due to https://github.com/junegunn/fzf/blob/01ae621f116bd4a3ef951a3816e11615c61b8c36/plugin/fzf.vim#L348

**Comment by tomtomjhj** [comment]
```vim
augroup fzf-custom
    autocmd!
    if has('nvim')
        autocmd FileType fzf setlocal winhighlight+=Normal:Normal
    endif
augroup END
```

**Comment by Frederick888** [comment]
@junegunn Yes. I'm using [gruvbox-material](https://github.com/sainnhe/gruvbox-material) in my [vimrc](https://git.tsundere.moe/Frederick888/frederick-settings/blob/07f934f6b009c2e00c9a08720434c77bd5ad6bc3/.vimrc#L202-237), and after 0881a6b the default background became opaque.

Here's a minimal vimrc to reproduce this issue:
```vim
set runtimepath^=~/.vim runtimepath+=~/.vim/after
let &packpath = &runtimepath

call plug#begin('~/.vim/plugged')
Plug 'junegunn/fzf'
Plug 'junegunn/fzf.vim'
call plug#end()

set nobackup
set nowritebackup
set cmdheight=2
set updatetime=300

set background=dark
highlight Normal      ctermfg=223 ctermbg=NONE guifg=#ebdbb2 guibg=NONE
highlight NormalFloat ctermfg=223 ctermbg=237  guifg=#ebdbb2 guibg=#45403d
highlight Pmenu       ctermfg=223 ctermbg=237  guifg=#ebdbb2 guibg=#45403d
```

(I'm a little confused by the commit message. It says 'Do not use Pmenu group colors' but actually replaced Normal with Pmenu?)

---

@tomtomjhj Thank you that worked! Though it looks a little hacky at a glance (haven't got time to go through the whole thread)?

**Comment by junegunn** [comment]
@Frederick888 

> I'm a little confused by the commit message

See `:help 'winhighlight'` for the explanation. However, it seems there are some rough edges and I still haven't been able to fully comprehend its behavior.

Anyway, if you use the fzf plugin prior to 0881a6bc17d970d2833be21fafc8de69fe468631, and comment out `highlight` lines in the given vimrc, you'll see that fzf will have the hideous magenta background, which is from `Pmenu`. 0881a6bc17d970d2833be21fafc8de69fe468631 is an attempt to fix the problem.

In addition to that, we can try adding `NormalFloat:Normal` (replacing `NormalFloat` with `Normal`) to make fzf use `Normal` even when `NormalFloat` is defined. But to my surprise, `set winhighlight=Pmenu:,NormalFloat:Normal` fails to handle the magenta problem. 

On the other hand, `set winhighlight=Pmenu:,Normal:Normal` suggested by @tomtomjhj works, but what does that even mean? Replacing `Normal` with `Normal`? It's very confusing.

@tomtomjhj Any idea why `Normal:Normal` works in this scenario? Should we add it to `winhighlight` by default?

```diff
diff --git a/plugin/fzf.vim b/plugin/fzf.vim
index a56f23c..7d4d8fe 100644
--- a/plugin/fzf.vim
+++ b/plugin/fzf.vim
@@ -977,7 +977,7 @@ if has('nvim')
     let buf = nvim_create_buf(v:false, v:true)
     let opts = extend({'relative': 'editor', 'style': 'minimal'}, a:opts)
     let win = nvim_open_win(buf, v:true, opts)
-    silent! call setwinvar(win, '&winhighlight', 'Pmenu:')
+    silent! call setwinvar(win, '&winhighlight', 'Pmenu:,Normal:Normal')
     call setwinvar(win, '&colorcolumn', '')
     return buf
   endfunction
```

**Comment by tomtomjhj** [comment]
I tried `Normal:Normal` based on https://github.com/neovim/neovim/pull/9722#discussion_r264777602 and my assumption that the right hand side of `:` is interpreted as usual. 

I agree on adding `Normal:Normal` by default. It works well for my use cases and seems to be an established practice:
* https://github.com/hrsh7th/nvim-cmp/blob/9bb8ee6e2d6ab3c8cc53323b79f05886bc722faa/lua/cmp/config/window.lua#L7
* fzf-lua
  * initial version: https://github.com/ibhagwan/fzf-lua/blob/36d850b29b387768e76e59799029d1e69aee2522/lua/fzf-lua/config.lua#L245
  * curent version (`Normal:FzfLuaNormal`): https://github.com/ibhagwan/fzf-lua/blob/b1f1f76c13d6040b9b9b6ccdb59129c6c4885124/lua/fzf-lua/win.lua#L308
