### ISSUE TITLE
FZF output on multiple lines for data passed by pipeline through find command

### ISSUE THREAD

**Issue by lamyergeier** [junegunn/fzf#3036]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x ] bash
    - [ ] zsh
    - [ ] fish

## Problem / Steps to reproduce

Hey I checked the issues but I am not sure if this is answered, as it was mentioned that fzf doesn't support multiline command history.

But I wanted to ask if its possible to print long items in 2 lines instead of the ellipsis (2 dots) at the end, please see the following image: 

![image](https://user-images.githubusercontent.com/42092626/200257295-c6345e9a-f531-4b92-adaf-74886514eb34.png)

I am doing something like this: `File="$(find | fzf)"`

If its not possible to print in multi line, is it possible to go to the end of each line to see the filename? This occurs when file path is too big to fit on one line!

**Comment by LangLangBart** [comment]
>  is it possible to go to the end of each line to see the filename?
```zsh
fzf --keep-right
```

---

#### Alternative show the name in the preview
```zsh
fzf --preview "echo {}" --preview-window 'nohidden:wrap'
```
<img width="665" alt="SCR-20221115-16a" src="https://user-images.githubusercontent.com/92653266/201792475-67eda9fc-4d42-43bb-aa53-f58134c66aa7.png">


```zsh
# just the filename
fzf --preview "basename {}" --preview-window 'nohidden:wrap'
```
<img width="665" alt="SCR-20221115-17j" src="https://user-images.githubusercontent.com/92653266/201792480-882b42b4-83cd-42e9-a2ca-50716dc9264a.png">

---

see the man page for more infos about `--preview-window`

**Comment by LangLangBart** [comment]
Maybe you could test if that works for you, otherwise maybe `junegunn` has a better idea.

```zsh
fzf --preview "basename {} | grep {q} -i --color=always" --preview-window 'nohidden:wrap'
# {q}  is  replaced to the current query string
# -i : ignore case
# --color=always 
```
<img src="https://user-images.githubusercontent.com/92653266/201986231-14b7a556-11f9-4648-8b9b-0ffeb0c165fc.png" width="600">

**Comment by junegunn** [comment]
The latest version of fzf can print multi-line entries:

https://junegunn.github.io/fzf/tips/processing-multi-line-items/

And it can wrap long items:

https://junegunn.github.io/fzf/releases/0.54.0/
