### ISSUE TITLE
fzf clears typed command when no match is found on pressing Enter

### ISSUE THREAD

**Issue by gnufied** [junegunn/fzf#304]
I am using fzf with zsh when I press `Control-R` and start typing a command not seen previously and press Enter then entire input (typed so far) is wiped out and I am taken to zsh prompt with nothing typed.

It kinda slows down the workflow and I am wondering if I am missing something obvious.

**Comment by junegunn** [comment]
It's possible to implement the behavior you want with `--print-query` option. However, I'm not sure pasting the typed query onto the command-line is the "right" behavior since fzf is a "fuzzy finder" where users do not type in the exact command. For example one might type `gtcln` to search for `git clone ...`, and it doesn't really make sense to put `gtcln` onto your command-line when the match is not found.

What I suggest is that you type in a prefix to the command to your command-line first, then press `CTRL-R` to start fzf, if you find a match press enter, or if you can't, terminate the finder with `CTRL-C` or `ESC`.

**Comment by yueyingjuesha** [comment]
I think this function maybe needed, like using another shortcut to preserve already typed command

**Comment by nguyentranbao-ct** [comment]
> It's possible to implement the behavior you want with `--print-query` option. However, I'm not sure pasting the typed query onto the command-line is the "right" behavior since fzf is a "fuzzy finder" where users do not type in the exact command. For example one might type `gtcln` to search for `git clone ...`, and it doesn't really make sense to put `gtcln` onto your command-line when the match is not found.
> 
> What I suggest is that you type in a prefix to the command to your command-line first, then press `CTRL-R` to start fzf, if you find a match press enter, or if you can't, terminate the finder with `CTRL-C` or `ESC`.

@junegunn Can we re-open this? I also find this feature/option useful, and also found a good usecase for this behavior like "Trigger history search with fzf first on every command prompt".
So I don't have to `CTRL-R` to start fzf everytime enter new command. History search mode will start by default,
if there are matches, i can select and execute them directly, if there is none, i will type the entire command and execute it like normal prompt.

**Comment by danztran** [comment]
> It's possible to implement the behavior you want with `--print-query` option. However, I'm not sure pasting the typed query onto the command-line is the "right" behavior since fzf is a "fuzzy finder" where users do not type in the exact command. For example one might type `gtcln` to search for `git clone ...`, and it doesn't really make sense to put `gtcln` onto your command-line when the match is not found.
> 
> What I suggest is that you type in a prefix to the command to your command-line first, then press `CTRL-R` to start fzf, if you find a match press enter, or if you can't, terminate the finder with `CTRL-C` or `ESC`.

@junegunn Can we re-open this? I also find this feature/option useful, and also found a good usecase for this behavior like "Trigger history search with fzf first on every command prompt".
So I don't have to `CTRL-R` to start fzf everytime enter new command. History search mode will start by default,
if there are matches, i can select and execute them directly, if there is none, i will type the entire command and execute it like normal prompt.

**Comment by junegunn** [comment]
See #3528
