### ISSUE TITLE
Autocompletion: Commands that end with linebreak are auto-executed

### ISSUE THREAD

**Issue by klieret** [junegunn/fzf#3042]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x]  I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

## Problem

If the history contains commands that end with a new line, selecting them with `fzf`'s `Ctrl-R` (reverse history search) autocompletion executes them directly without giving an opportunity to edit the commands.

Usually commands in the history that end with a line break should be escaped properly when the history is saved (so this definitely points to a bug somewhere else), but because this can be potentially dangerous, I propose that `fzf` also addresses this.

## History example

This is what it looks in ``~/.zsh_history`` if the line break is not properly escaped (`fzf` auto-executes)

```
: 1667316223:0;g ca
: 1667316230:0;l
: 1667316232:0;bundle exec jekyll serve --incremental\

: 1667316239:0;bundle install
: 1667316250:0;bundle update
```

Whereas this is what should happen (`fzf` behaves correctly):

```
: 1668013792:0;vim ~/.zsh_history
: 1668013881:0;echo "I end with a line break"\n
: 1668013887:0;vim ~/.zsh_history
```

## Proposed solution

Avoid select commands to auto-execute/strip any trailing line break.

**Comment by junegunn** [comment]
I can't reproduce the problem on zsh.

```
$ tail -2 ~/.zsh_history
ls \\

$ ls \
--still-editable
ls: unrecognized option `--still-editable'
```

**Comment by klieret** [comment]
Hmm, after starting a new shell session I can also no longer reproduce this... Very strange, because I could repeatedly trigger the behavior in the original session.

Let me close this though. If noone else ran into this, it was probably some trouble on my side.

And thanks a lot for developing this awesome piece of software!
