### ISSUE TITLE
"syntax error near unexpected token `standard'"

### ISSUE THREAD

**Issue by Aster89** [junegunn/fzf#3044]
- [x] I have read through the manual page (`man fzf`)
- [ ] I have the latest version of fzf. Well, not really, Debian 11 comes 0.24 (my computer at work, so can't to much about it)
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux, Debian 11
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

## Problem / Steps to reproduce

When I `source /usr/share/doc/fzf/examples/completion.bash` (yeah, I found `completion.bash` and `key-bindings.bash` in `/usr/share/doc/fzf/` in the system in question, whereas on my personal system they are in `/usr/share/fzf/`; I think this is a detail related to how `apt` vs `pacman` have packaged fzf), I get the following error:
```
-bash: eval: line 326: syntax error near unexpected token `standard'
-bash: eval: line 326: `(standard input):complete -F _fzf_host_completion telnet #_known_hosts'
```
if that `source` line is in my `~/.bashrc`, then when I start `bash` I get two additional lines:
```
-bash: __35m__K_standard: command not found
-bash: __35m__K_standard: command not found
-bash: eval: line 326: syntax error near unexpected token `standard'
-bash: eval: line 326: `(standard input):complete -F _fzf_host_completion telnet #_known_hosts'
```

**Comment by junegunn** [comment]
I don't know what `__35m__K_standard` is. It's not in the source code of fzf. Anyway, the whole problem looks to be an issue of your shell configuration, and I can't help you with that.
