### ISSUE TITLE
Preview windows cannot display in the end

### ISSUE THREAD

**Issue by newyorkthink** [junegunn/fzf#3047]
the fzf preview windows cannot display in the end.
![image](https://user-images.githubusercontent.com/87791643/201818257-a23d50c4-0b98-4b69-ada8-9644087ff5b8.png)

some font not display.

maybe need info change in the second line.

**Comment by lime-desu** [comment]
*Long lines are truncated by default. Line wrap can be enabled with wrap flag. 

`--preview=wrap`

**Comment by LangLangBart** [comment]
> *Long lines are truncated by default. Line wrap can be enabled with wrap flag.
> 
> `--preview=wrap`

:ghost:

`--preview-window wrap`

---

But it would be good to have an `ellipsis` for the preview window as well.
