### ISSUE TITLE
enhance preview-label

### ISSUE THREAD

**Issue by LangLangBart** [junegunn/fzf#3053]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] macOS
- Shell
    - [x] zsh

### 1. Coloring independent of `--border-label`.
```zsh
# Example
# both labels get the same color
fzf --border rounded --border-label " 124 red " --preview-label " 124 red " --preview-window "nohidden:right:border" --color 'label:124:bold'
``` 

<img src="https://user-images.githubusercontent.com/92653266/202160177-837c2cb3-d29a-470d-89fa-1b900f3dfd80.png" width="600">

### 2. dynamic updating 
- this request was discussed in ticket #3022.
> However, after toying around with it for a little while, I think in most cases, printing the title inside the preview window is good enough and looks better. 

- possible use cases:
 
🔥 file counter, see screenshot from [extrawurst/gitui](https://github.com/extrawurst/gitui) below:
<img src="https://user-images.githubusercontent.com/92653266/202162180-101f3a9d-68df-4410-927f-c2ff09ef9e4b.png" width="600">
🔥 index based naming, see screenshot from [meiji163/gh-notify](https://github.com/meiji163/gh-notify/pull/31) below:
<img src="https://user-images.githubusercontent.com/92653266/202163869-2efa0544-1f3c-4cd3-b3a2-1b2b2a3f0d6b.png" width="600">

---

PS: The new title/labeling feature added with version [0.35.0](https://github.com/junegunn/fzf/releases/tag/0.35.0) is great.

**Comment by junegunn** [comment]
> 1. Coloring independent of `--border-label`

I figured most users won't care much about customizing each color, so I felt it was good enough to support ANSI color sequences in the label if you really need different colors.

```sh
fzf --border --border-label " 124 red " \
    --preview 'cat {}' --preview-label $' 124 and \x1b[33;125m125 ' --color 'label:124:bold'
```

> 2. dynamic updating

This is not trivial to implement and I don't think it's worth the effort. Just supporting field index expressions in the labels will not be good enough. For example, with `--border-label=' Current: {} '`, the label will look `── Current: ──` if there's no match for the current query. The users will definitely want to display different messages in that case. So what do we do? We need to fall back to starting up external processes to generate the labels. And now we'll have to start 3 asynchronous processes in the background (including the preview command) very frequently. Constantly updating the labels will also require more careful code that should avoid any flickering of the region given that the length of the label can constantly change.

**Comment by LangLangBart** [comment]
> I felt it was good enough to support ANSI color sequences in the label if you really need different colors

The idea was to dim the preview label  and add it as configuration to my `FZF_DEFAULT_OPTS`, like `hl` is dimmed. But the workaround you suggested also works quite well. Ty.
```zsh
# .zshrc
export FZF_DEFAULT_OPTS=" \
--layout=reverse \
--info=inline \
--multi \
--preview '([[ -f {} ]] && (bat --style=numbers --color=always {} || cat {})) || ([[ -d {} ]] && (tree -C {} | less)) || echo {} 2> /dev/null | head -200' \
--preview-window 'right,50%,border-left' \
--no-separator \
--ellipsis='' \
--border horizontal \
--height 85% \
--color 'bg+:233,fg+:255,fg:regular:250,hl+:40,hl:dim:40' \
--color 'prompt:80,info:40,header:25,border:dim' \
--color 'pointer:9,spinner:92,marker:46' \
--pointer='▶' --marker='✓' \
--bind 'change:first' \
--bind '?:toggle-preview' \
--bind 'ctrl-a:select-all' \
--bind 'ctrl-w:preview-half-page-up,ctrl-s:preview-half-page-down' \
--bind 'ctrl-y:execute-silent:([[ -f {} ]] && $EDITOR {1} --reuse-window) || ([[ -d {} ]] && $EDITOR {1} --new-window)'"
```

---

> This is not trivial to implement and I don't think it's worth the effort.

Ok.

**Comment by junegunn** [comment]
> The idea was to dim the preview label and add it as configuration to my `FZF_DEFAULT_OPTS`

Yeah, that makes sense.

**Comment by LangLangBart** [comment]
- `preview-label` color name was added
- dynamic labels is currently not planned, will close the ticket for now

**Comment by mckellygit** [comment]
Hi,
Just a comment here - I am able to get a hacky dynamic preview window title of the filename by using the options: preview-window with '~1' along with adding --style=header,numbers to the bat cmd and also adding "--header=1 --no-number-headers --no-search-headers" args to my LESS env var.
thx,
-m
