### ISSUE TITLE
Vim plugin: weird path behavior

### ISSUE THREAD

**Issue by akhilsbehl** [junegunn/fzf#306]
Hi, There is a feature in Ctrl-P where it finds the git root if the current file is in a git directory. I tried to emulate this behavior using this function:

```
function FuzzyFind()
  " Contains a null-byte that is stripped.
  let gitparent=system('git rev-parse --show-toplevel')[:-2]
  if empty(matchstr(gitparent, '^fatal:.*'))
    silent execute ':FZF ' . gitparent
  else
    silent execute ':FZF .'
  endif
endfunction

nnoremap <silent> <LocalLeader>fz :call FuzzyFind()<CR>
```
While this correctly brings up the finder, selecting a file opens a new file (in the current directory) instead of in it's own directory.

Am I understanding FZF wrong? Is the vim function doing something wrong (I have limited knowledge of vimscript). Can someone please explain the problem? I am happy to submit a patch if I understand what's going on.

Thanks.

**Comment by junegunn** [comment]
For me, the code you posted seems to work as expected. I have no problem opening a file inside a git repo regardless of where I am. Maybe some other config or plugins in your .vimrc are getting in the way?

**Comment by justinmk** [comment]
@akhilsbehl What's the value of 

    :set autochdir?

**Comment by akhilsbehl** [comment]
@Junegunn: Let me try to provide a replicable example of provide some
pictures to explain the problem.
@Justin: autpchdir is set.


--
ASB (akhilsbehl.github.io)

*'Personally, I am always ready to learn, although I do not always like
being taught*...', Churchill.

**Comment by akhilsbehl** [comment]
Hi, I can confirm that this is not a problem with FZF. Just tried this behavior with a clean vimrc with only FZF installed and it works fine. So, will close this issue.

But does anyone have a clue what may be interfering so I can get correct behavior?

Thanks.

**Comment by akhilsbehl** [comment]
Just realized, this problem only happens if vim is running inside tmux.

**Comment by junegunn** [comment]
So it's basically a configuration issue, but we can take this as a chance to make fzf more robust.

> But does anyone have a clue what may be interfering so I can get correct behavior?

Well, there's no easy way. You may need start with only a small part of your vimrc (with `finish`), and incrementally extend the region until the problem is reproducible.

**Comment by akhilsbehl** [comment]
For now I can get the correct behavior if I use `:FZF!` instead of `:FZF` since that avoids tmux splits. I do however get this warning everytime in vim:

```
W13: Warning: File "..." has been created after editing started             
[O]K, (L)oad File:
```

Does anyone else see this?

I will try to debug this (since I will really like this working, but that will take some time). Thanks for all help.

**Comment by akhilsbehl** [comment]
The warning with `:FZF!` has something to do with `buftype` being emtpy. Not sure why it is being set empty even though there is content in the buffer.

**Comment by akhilsbehl** [comment]
Hey, sorry, turns out this is an FZF problem. The problem was not solved because of the clean vimrc but because I had added `'cd'. gitdir` to the `FuzzyFind()` function.

I have a question: does the plugin work by opening a buffer and pasting the contents of the actual file into that buffer? Because if so, I think that is the part where the problem lies.

Also, I think the fact that tmux can't seem to find the file and the W13 above are related to each other. I am not going to reopen this since I can not give you a reproducible example. But it will probably help if you can give a high-level overview of how the vim plugin works.

Thanks.

**Comment by junegunn** [comment]
> I have a question: does the plugin work by opening a buffer and pasting the contents of the actual file into that buffer? Because if so, I think that is the part where the problem lies.

Nope.

As @justinmk mentioned, I think `autochdir` can be the culprit. Can you try again with the option unset and see if the problem still persists?

I actually found an issue with `autochdir` when selecting multiple files. When multiple files are selected, `fzf#run()` will open files one by one, but the directory is changed after the first file is open, so the rest of the files are not properly open.

**Comment by akhilsbehl** [comment]
Busy with something just now. Will get back to you after testing.

Thanks.

**Comment by junegunn** [comment]
I pushed the fix to the problem I mentioned above. It will temporarily disable &autochdir when opening multiple files. The fix only applies to `:FZF` command, not `fzf#run()`.

**Comment by akhilsbehl** [comment]
I can confirm that this solved my problem too. :) Any reason we should not do this for `fzf#run` too?

**Comment by junegunn** [comment]
Because `fzf#run` does not know the context of the call and to disable the setting is beyond the scope of its responsibility. I mean, we cannot assume that the caller is using `fzf#run` for opening files. Something like `:call fzf#run({'source': range(100), 'sink': 'echom'})` is totally valid. I know that most users will be using `fzf#run` for opening files and it probably wouldn't hurt to apply the fix to `fzf#run` as well, but in principle, it's not pertinent to what `fzf#run` is supposed to do.

**Comment by maple-leaf** [comment]
:GitFIles will fail to get the correct pwd for opening file when `set autochdir`

**Comment by junegunn** [comment]
@maple-leaf I can't reproduce the problem. Please create a new issue on fzf.vim project (not here) if you still have the issues with the latest versions of fzf and fzf.vim.
