### ISSUE TITLE
[Feature Request] Syntactic sugar for binding enter and double-click

### ISSUE THREAD

**Issue by Prince-Mandor** [junegunn/fzf#3061]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [x] zsh
    - [ ] fish

## Problem / Steps to reproduce

There are often used idiom

`--bind "enter:execute(echo {2})+abort,double-click:execute(echo {2})+abort"`

Is it possible to add some virtual key or event, reacting to both enter and double-click?
So, instead of "enter:do_something,double-click:do_something" we write (for example) "activate:do_something"?

**Comment by junegunn** [comment]
> There are often used idiom

I'm not so sure about that. It feels more natural to post-process the output rather than relying on `execute` action.

```sh
fzf | awk '{print $2}'
```

If I had to bind a lengthy action to multiple keys, I would just use a shell variable not to repeat myself.

```sh
A='preview(date; echo hello)'
fzf --bind "enter:$A,double-click:$a"
```

**Comment by Prince-Mandor** [comment]
> > There are often used idiom
> 
> I'm not so sure about that. It feels more natural to post-process the output rather than relying on `execute` action.

I, personally, had a one case where third field for `awk` gives different result than `{3}` of `fzf`, and couple of cases where `awk` wasn't installed.
And, Yes, we know you are adamant about not adding {N} functionality to `fzf` output, this is exactly why this idiom became idiom :)
But my feature request was about different part

> 
> If I had to bind a lengthy action to multiple keys, I would just use a shell variable not to repeat myself.
> 
> ```shell
> A='preview(date; echo hello)'
> fzf --bind "enter:$A,double-click:$A"
> ```

This is possible, but cause minor problems. Especially if this is not direct call of `fzf`, but some nontrivial construction with several `if`s  and `sh -c` ; and creating global variable is frowned upon. So, yes it is possible to solve this by some additional code, this is why I call it "syntactic sugar".
Really, there are not many circumstances where separation of 'enter' and 'double-click' have any meaning, Mostly `double-click` just ignored for simplicity, and only `enter` binding used. Fzf supports mouse by default already, so why not making binding a bit simpler? 
Another way, is it possible to add option like `--process-double-click-as-enter`?
Or even better, always consider `double-click` as `enter`, unless `double-click` was bind specifically?

**Comment by junegunn** [comment]
> had a one case where third field for `awk` gives different result than `{3}`

If that's true, that's a bug of fzf. Please file an issue.


> couple of cases where `awk` wasn't installed.

Which distro? I haven't seen a modern Linux distro that doesn't come with awk by default.

> Especially if this is not direct call of `fzf`, but some nontrivial construction with several `if`s and `sh -c` ; and creating global variable is frowned upon.

Can you show me the code? Global variables are never really an issue in short shell scripts. For functions, you can just put `local` or put the function body in parens so that it runs in a subshell. I wouldn't see that as "some additional code".

> there are not many circumstances where separation of 'enter' and 'double-click' have any meaning

I suppose so, though I don't have any stats to back it up. It would make sense to match the behavior of `double-click` to that of `enter` iff `doubler-click` is left unbound.

**Comment by junegunn** [comment]
> It would make sense to match the behavior of `double-click` to that of `enter` iff `doubler-click` is left unbound.

I'm going to implement this scheme.

**Comment by Prince-Mandor** [comment]
> > had a one case where third field for `awk` gives different result than `{3}`
> If that's true, that's a bug of fzf. Please file an issue.

No, it wasn't fzf fault. It was a 'specific' version of busybox emulating awk and having only space as default field separator

> > couple of cases where `awk` wasn't installed.
> Which distro? I haven't seen a modern Linux distro that doesn't come with awk by default.

As long as we are talking about world of big computers and Linux distros -- You entirely right. But there are world of embedded systems and single-board computers, where on some no-name board some hand-patched version 3.12 kernel works fine and even have a working golang, and this is another story entirely. 

> > It would make sense to match the behavior of `double-click` to that of `enter` iff `doubler-click` is left unbound.
> I'm going to implement this scheme.

Thank you very much!

**Comment by junegunn** [comment]
The patch pushed to master. Please let me know if it doesn't work as expected. Thanks.

**Comment by Prince-Mandor** [comment]
Thank you very much! It works perfectly!
