### ISSUE TITLE
sh: `fzf-file-widget': not a valid identifier when sourcing fzf

### ISSUE THREAD

**Issue by tianrui-wei** [junegunn/fzf#3063]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

## Problem / Steps to reproduce

Using an archlinux fresh installation with the latest fzf, add the following lines to `~/.bashrc`

```bash
source /usr/share/fzf/key-bindings.bash
source /usr/share/fzf/completion.bash
```

When starting a new shell, `sh: fzf-file-widget: not a valid identifier when sourcing fzf` appears in the command line.

Bash version: GNU bash, version 5.1.16(1)-release (x86_64-pc-linux-gnu)
fzf version: 0.35.1 (a38b63b)

**Comment by junegunn** [comment]
The error message is reporting `sh:`, not `bash:`, so it looks like a non-bash shell (`/bin/sh`) is trying to load the file, and it will not succeed of course.

```sh
$ bash
$ foo-bar() { echo foo; }
$ foo-bar
foo

$ /bin/sh
sh-3.2$ foo-bar() { echo 1; }
sh: `foo-bar': not a valid identifier
```

So this is not an issue of this project. You have to fix your shell configuration.

**Comment by ackvf** [comment]
For reference

Had the same problem after repeatedly tweaking my aliases and sourcing `.bashrc`. Strangely, it worked for the first ~hour or so and suddenly I noticed this error. No idea why all of a sudden, but apparently, I've been using `sh` the whole time without even knowing??

Anyway, this solved my problems for good. Put this inside your `~/.profile`:

```
# If not already in bash, and bash exists, re-exec as a login bash
if [ -z "$BASH_VERSION" ] && command -v bash >/dev/null 2>&1; then
  exec bash -l
fi
```
