### ISSUE TITLE
[feature] modify the reload binding that is bound to event change

### ISSUE THREAD

**Issue by jean-santos** [junegunn/fzf#3066]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

## Problem / Steps to reproduce

I was trying to use fzf with the flags

```
--bind "change:reload:SOME_COMMANDS"
--bind "alt-n:...something to change reload:SOME_COMMANDS"
```

I've tryed:

- ```--bind "alt-n:change:reload:SOME_OTHER_COMMANDS```
- ```--bind "alt-n:rebind(change:reload:SOME_OTHER_COMMANDS)```
- ```--bind "alt-n:unbind(change)+rebind(change:reload:SOME_OTHER_COMMANDS)```

**Comment by junegunn** [comment]
Changing the binding is not supported. See https://github.com/junegunn/fzf/pull/2564

You can instead make your reload command react to an external state that is updated in a different binding. It's a sketchy example, but you get the idea.

```sh
echo 10 > /tmp/limit
cmd='seq $(cat /tmp/limit)'
eval "$cmd" | fzf --bind "change:reload:$cmd" --bind "alt-n:execute-silent(echo 20 > /tmp/limit)+reload($cmd)" --disabled
```

**Comment by jean-santos** [comment]
> Changing the binding is not supported. See #2564
> 
> You can instead make your reload command react to an external state that is updated in a different binding. It's a sketchy example, but you get the idea.
> 
> ```shell
> cmd='seq $(cat /tmp/limit)'
> echo 10 > /tmp/limit
> eval "$cmd" | fzf --bind "change:reload:$cmd" --bind "alt-n:execute-silent(echo 20 > /tmp/limit)+reload($cmd)" --disabled
> 
> # or
> echo 10 > /tmp/limit
> eval "$cmd" | fzf --bind "change:reload:$cmd" --bind "alt-n:reload(echo 20 > /tmp/limit; $cmd)" --disabled
> ```

Extending the [ripgrep 'Switching to fzf-only search mode' example](https://github.com/junegunn/fzf/blob/master/ADVANCED.md#switching-to-fzf-only-search-mode)

for instance
```
RG_PREFIX_COLOR="rg --column --line-number --no-heading --color=always --smart-case "
RG_PREFIX_NO_COLOR="rg --column --line-number --no-heading --color=never --smart-case "
INITIAL_QUERY="${*:-}"
IFS=: read -ra selected < <(
  FZF_DEFAULT_COMMAND="$RG_PREFIX $(printf %q "$INITIAL_QUERY")" \
  fzf --ansi \
      --disabled --query "$INITIAL_QUERY" \
      --bind "change:reload:sleep 0.1; $RG_PREFIX_NO_COLOR {q} || true" \
      --bind "alt-enter:unbind(change,alt-enter)+change-prompt(2. rgcolor> )+rebind("change:reload:sleep 0.1; $RG_PREFIX_COLOR {q} || true" \
)
[ -n "${selected[0]}" ] && vim "${selected[0]}" "+${selected[1]}"
```

In this scenario, I can't use the strategy you mention, right? This is a lousy example, but you get my point.

**Comment by junegunn** [comment]
Why not? You can write a reload command that works differently depending on the existence of a file that is written or deleted on a key event.

**Comment by jean-santos** [comment]
> 

When I specify the reload action on the second bind
```
 --bind "alt-enter:unbind(change,alt-enter)+change-prompt(2. rgcolor> )+reload($SOME_DIFFERENT_COMMAND" )
```

When I press alt-enter the correct reload run once and update the output all fine. But once I press a key it's trigger the change event, and runs first defined reload (change:reload, defined on the first bind)

It's this the normal behavior, or it's a bug?

**Comment by jean-santos** [comment]
Oh, I see!
I understand now what you meant earlier! Thanks!!!
