### ISSUE TITLE
Feature request: cursor starting line

### ISSUE THREAD

**Issue by lbrayner** [junegunn/fzf#3069]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

## Problem / Steps to reproduce

It'd be very useful to supply the cursor's starting line. My use case is the Neovim [fzf-lua](https://github.com/ibhagwan/fzf-lua#buffers-and-files) plugin's `tabs` command. Let's say I have 50 tabs open and am currently on tab 45, I'd like the cursor to be positioned there.

This is the default behavior:

![tab_1](https://user-images.githubusercontent.com/5733531/205134695-7d43cad1-98a1-4601-b553-d612a50b8f2d.png)

This is what I'd like to happen on startup:

![tab_2](https://user-images.githubusercontent.com/5733531/205134819-22e8ca5b-dcb3-4e36-95c7-41b6d259b84e.png)

**Comment by lbrayner** [comment]
This combined with https://github.com/junegunn/fzf/issues/2515 would be great.

**Comment by junegunn** [comment]
One workaround would be to reorder the input and use `--cycle` option to enable cyclic scrolling.

```sh
(seq 5 10; seq 1 4) | fzf --cycle --reverse
```

**Comment by lbrayner** [comment]
I see, that's an option!

**Comment by lbrayner** [comment]
Thank you @junegunn :)

**Comment by hi2u** [comment]
For anyone wondering what the CLI argument is to do this, here's how you'd start with the 5th line selected by default:

```
fzf --bind="load:pos(5)"
```

**Comment by Bellavene** [comment]
> For anyone wondering what the CLI argument is to do this, here's how you'd start with the 5th line selected by default:
> 
> ```
> fzf --bind="load:pos(5)"
> ```

But how to load position after binded reload?

**Comment by iconoclasthero** [comment]
> For anyone wondering what the CLI argument is to do this, here's how you'd start with the 5th line selected by default:
> 
> ```
> fzf --bind="load:pos(5)"
> ```

Thanks for this, it saved me a ton of time.
