### ISSUE TITLE
[Feature Request] Make fzf insert path

### ISSUE THREAD

**Issue by khalidchawtany** [junegunn/fzf#307]
Is it possible to make **FZF** finder insert the selected file's **path** instead of opening it in **vim/neovim**.

If it is already implemented could you point me to the right place as I could not find it anywhere :)

Thanks

**Comment by junegunn** [comment]
It should be possible. All you need to know is [`fzf#run` function](https://github.com/junegunn/fzf#fzfrunoptions) (and some knowledge on vimscript of course). The purpose of this project is not to deliver concrete implementation of specific features, but to provide building blocks that can be used to implement those ideas. You might want to take a look at the examples here: https://github.com/junegunn/fzf/wiki/Examples-(vim)

**Comment by khalidchawtany** [comment]
Thanks for such a great tool :+1:  You are awesome :)
