### ISSUE TITLE
[suggestion] Remove --no-separator

### ISSUE THREAD

**Issue by balta2ar** [junegunn/fzf#3071]
From 0.35.0 release notes:
```
Info panel (match counter) will be followed by a horizontal separator by default
    Use --no-separator or --separator='' to hide the separator
````
from a perspective of a user who prefers minimalism it seems a little odd that a release adds something to the UI and then I need to extend `FZF_DEFAULT_OPTS` to counter the effect and remove what I don't need. I suggest not showing the separator by default and only adding it if specified with `--separator=xxx`, so those who need it can enable it. Fewer surprises for users after updates, and one less CLI argument to maintain.

I might be missing some bigger discussion or context about that. Just sharing my surprise.

**Comment by junegunn** [comment]
I liked the look of it so I added it to my project, but I'm a benevolent guy so I added a flag for those who don't like it :) Try living it with for a while, you may end up liking it.
