### ISSUE TITLE
`--exact` breaks `--scheme=path`

### ISSUE THREAD

**Issue by camoz** [junegunn/fzf#3073]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

## Problem / Steps to reproduce

Summary: When using `--scheme=path --exact` and typing `fo`, then `bar/foo` gets higher scoring than `foo`, which seems counterintuitive.

### Examples

```
user@host:~$ cat <<EOF | FZF_DEFAULT_OPTS= fzf --scheme=path
foo
foo/bar
/foo
bar/foo
EOF
```
When typing `fo`, then `foo` gets selected (as expected).

```
user@host:~$ cat <<EOF | FZF_DEFAULT_OPTS= fzf --scheme=path --exact
foo
foo/bar
/foo
bar/foo
EOF
```
When typing `fo`, then `/foo` and `bar/foo` get higher scoring than `foo` (not expected).

Am I misunderstanding the meaning of `--exact`, or is this a bug?

**Comment by junegunn** [comment]
Can you update your examples with `-ffo` and paste the results so that it's easier to see the difference here?

**Comment by camoz** [comment]
Of course!

```
user@host:~$ cat <<EOF | FZF_DEFAULT_OPTS= fzf -ffo --scheme=path
foo
foo/bar
/foo
bar/foo
EOF
foo
/foo
foo/bar
bar/foo
```

```
user@host:~$ cat <<EOF | FZF_DEFAULT_OPTS= fzf -ffo --scheme=path --exact
foo
foo/bar
/foo
bar/foo
EOF
/foo
bar/foo
foo
foo/bar
```

After `EOF` comes the output of fzf.

**Comment by junegunn** [comment]
Fixed on master, thanks for the report.

**Comment by camoz** [comment]
Thank you for the quick fix! :)
