### ISSUE TITLE
Making fzf keybindings not scroll the terminal after exiting

### ISSUE THREAD

**Issue by MrMino** [junegunn/fzf#3078]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [ ] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

FZF works great for me, but my pet peeve is that every time I use ctrl+key binding I end up with a bunch of empty lines at the bottom of my terminal screen.

I'm using tmux, but I don't like starting FZF in another pane, because it messes up other things for me. I figured out I'd make the life easier for myself:

```
# Make fzf NOT scroll the output
fzf-file-widget () {                 
    TMUX_BUFFER="fzf-capture"
    tmux capture-pane -e -b $TMUX_BUFFER
    tput smcup
    tmux show-buffer -b $TMUX_BUFFER | sed -e :a -e '/^\n*$/{$d;N;ba' -e '}'
    LBUFFER="${LBUFFER}$(__fsel)"
    tput rmcup
    local ret=$?
    zle reset-prompt
    return $ret
}
```

With the above change, fzf is executed inside an alternate screen buffer, so the normal terminal remains untouched.

@junegunn Is this UX improvement something you would like to explore further?
I would make PRs for this, but I'm not sure where to put it, whether to edit existing widgets, etc., so I figured I would discuss this first.

Feel free to outright close this if not interested.

**Comment by junegunn** [comment]
> I'm using tmux, but I don't like starting FZF in another pane, because it messes up other things for me.

If you're running tmux 3.2 or above, you can configure the bindings to use tmux popups. Here's what I'm using.

```sh
export FZF_TMUX_OPTS='-p80%,60%'
```

I like this solution not only because it doesn't have the scroll problem you mentioned but also because it opens fzf in a large popup window even when I'm triggering the bindings on a small split pane.

**Comment by junegunn** [comment]
I tried your patch, it's a clever trick and it works great when I'm triggering the bindings on the lower part of the screen, but it works a little weird when I use it on the upper part of the screen after clearing the screen.

```sh
clear
seq 5
<CTRL-T>
```

Also, we shouldn't use the approach when we're not running tmux, so it's more code to maintain, and I'm not sure if it's worth it.

**Comment by MrMino** [comment]
> This works better IMHO, I didn't knew about this.

Although... 

![image](https://user-images.githubusercontent.com/6691643/207036420-736b0aa7-71ec-4b9a-b596-9b4769aa2cfc.png)

Since the popups are done outside the pane, they obscure the output. The reason I'm using the trick thing is so that I can look at the output of the last command, e.g. when grepping a code base:

![image](https://user-images.githubusercontent.com/6691643/207036958-05c8377e-e936-4cfe-85c0-9dd2f6158f0d.png)

I'm not sure how much maintenance burden this entails, so I won't insist on this.

**Comment by MrMino** [comment]
Using this helps with the pop-up obscuring the output:

```
export FZF_TMUX=1
export FZF_TMUX_OPTS='-d70%'
```
