### ISSUE TITLE
simpler key bindings

### ISSUE THREAD

**Issue by azag0** [junegunn/fzf#308]
Hi, I had a weird problem with the ctrl-T bash binding in os x and terminal.app (there was ~1s delay between pressing the key and fzf having appeared), so I wrote myself my own bindings using the `$READLINE_LINE` variable. Looking at the original, I think this is a simpler approach, so I thought I would share it here.

```
insertinreadline() {
    READLINE_LINE=${READLINE_LINE:0:$READLINE_POINT}$1${READLINE_LINE:$READLINE_POINT}
    READLINE_POINT=`expr $READLINE_POINT + ${#1}`
}

bind -x '"\C-t": insertinreadline "`locate . | fzf`"'
bind -x '"\C-r": insertinreadline \
    "`HISTTIMEFORMAT= history | \
    fzf --tac --no-sort -n 2.. --tiebreak=index --toggle-sort=ctrl-r | \
    sed \"s/^ *[0-9]* *//\"`"'
```

**Comment by junegunn** [comment]
Hi, thanks for the tip. I didn't know about `$READLINE_LINE/POINT` and they seem to allow much more elegant solution to the problem. However, the code doesn't seem to work reliably on OS X for some reason. I'll look into it when I get some time.

**Comment by azag0** [comment]
This appears to be bash version issue, I guess. I have a recent (Homebrew) bash (4.3), OS X ships with 3.2 (2007) which does not have the `READLINE_*` variables. So I guess if you want to support the default OS X bash, you need to stick to the current solution.

**Comment by edi9999** [comment]
I think it is more reasonable to stay with the more compatible version (the existing one), even if it is much more complicated.

**Comment by junegunn** [comment]
@edi9999 Agreed. I wonder which part of the current implementation caused the delay @azag0 experienced.

**Comment by azag0** [comment]
@junegunn If someone submits a similar issue, feel free to ping me, I can look into it. Until then, I'll stick to my own key bindings
