### ISSUE TITLE
Fzf illogically changing directory when using :Files or :Rg

### ISSUE THREAD

**Issue by hatemets** [junegunn/fzf#3082]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] (Arch) Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish
- Editor
    - [x] Neovim

## Problem / Steps to reproduce
When I'm inside `~/projects/project1/` and type `:Files` to navigate to `~/projects/project1/App.js`, fzf will open the correct file, *but* sets the current working directory in vim to `~/projects/project2`, which is undesired behavior. The desired behavior would be for fzf not to change the current working directory *at all*.
I tried reinstalling fzf, but to no avail. What could be the problem?

**Comment by junegunn** [comment]
I don't think fzf is doing that as the problem is not reproducible with a minimal Vim configuration file.

```sh
nvim -Nu <(curl https://gist.githubusercontent.com/junegunn/6936bf79fedd3a079aeb1dd2f3c81ef5/raw)
```

(https://gist.githubusercontent.com/junegunn/6936bf79fedd3a079aeb1dd2f3c81ef5/raw)

You need to investigate which of your configuration (or plugin) is causing the problem.
