### ISSUE TITLE
[ Feature Request ] Add options that can change `--info inline`'s prompt

### ISSUE THREAD

**Issue by NEX-S** [junegunn/fzf#3084]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [x] fish

## Problem / Steps to reproduce

does fzf have any options that can change `--info inline`'s prompt?

![image](https://user-images.githubusercontent.com/97107165/207053525-82dc0c73-3b03-43e9-b75c-41d02bcedb05.png)

the `man fzf` only give us these options
```
       --prompt=STR
              Input prompt (default: '> ')

       --pointer=STR
              Pointer to the current line (default: '>')

       --marker=STR
              Multi-select marker (default: '>')
```

**Comment by Delapouite** [comment]
Related issue where the user could also benefit to have more control on the ` <` char of the info prompt and remove the extra space : https://github.com/junegunn/fzf/issues/2030
