### ISSUE TITLE
Clean exit fzf from within `--execute`

### ISSUE THREAD

**Issue by lgersman** [junegunn/fzf#3089]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

## Problem / Steps to reproduce

I use fzf as a command launcher with integrated documentation view (using fzf preview for markdown rendering). 

![Screenshot from 2022-12-15 14-32-41](https://user-images.githubusercontent.com/81591/207872003-e221122b-900d-4521-893a-3080ac06ac2d.png)

The commands are executed on `Enter` using fzf `--execute` option

```
--bind "Enter:execute('${BASH_SOURCE[0]}' execute '{}' >/dev/tty)"
```

where I call my script with an CLI option ("execute") to execute the action. 

Now the question :-) 

The "exit" command should exit my script. Right now I kill the script executing fzf 

```
kill -INT $SCRIPT_PID
```

This works fine but the following error occurs after exit on the terminal : 

```
Failed to read /dev/tty
``` 

I assume its a result of my fzf config `--bind "Enter:execute('${BASH_SOURCE[0]}' execute '{}' >/dev/tty)"` option. 

How can I signal fzf to do a clean exit ? 

And if that's not possible - how can I suppress the `Failed to read /dev/tty` error message ? 

Thanks in advance,

Lars

PS: Complete script : https://github.com/lgersman/pnpmkambrium/blob/develop/packages/docker/shaunch/bin/shaunch.sh#L195

**Comment by junegunn** [comment]
How about killing fzf itself, instead of its parent process?

```sh
echo $'vim\ntop\nexit' | fzf --reverse --bind 'enter:execute:[ {} = exit ] && kill $PPID || {}'
```

**Comment by lgersman** [comment]
Ouch - I was not aware of PPID :-)

Thank you 👌

Junegunn Choi ***@***.***> schrieb am Do., 15. Dez. 2022,
15:13:
