### ISSUE TITLE
~/.fzf/install didn't finish installing in fish shell

### ISSUE THREAD

**Issue by benekastah** [junegunn/fzf#309]
I had to do this in my config.fish to get it working:

```
set PATH $PATH ~/.fzf/bin
```

**Comment by junegunn** [comment]
Isn't the [path added](https://github.com/junegunn/fzf/blob/master/install#L220-L221) to `$fish_user_paths`?

**Comment by benekastah** [comment]
Yes, it is.

**Comment by junegunn** [comment]
Hmm, then why setting PATH is required? I never had to do that.

https://github.com/fish-shell/fish-shell/issues/527

**Comment by benekastah** [comment]
Ah, figured it out. I was resetting `PATH` in ~/.config.fish instead of building on it. I don't remember why I needed to do that in the past, but I don't think I need to anymore so problem solved.

**Comment by junegunn** [comment]
Okay, thanks for quick response.

**Comment by benekastah** [comment]
You too!
