### ISSUE TITLE
View non-whitespace special characters as word boundaries

### ISSUE THREAD

**Issue by xeruf** [junegunn/fzf#3090]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [z] zsh
    - [ ] fish

## Problem / Steps to reproduce

<img width="634" alt="image" src="https://user-images.githubusercontent.com/13354331/208097014-b8b37759-4546-4d35-a791-818386f84e4b.png">

I am not quite sure about this, but I think I'd like to be `<>` and other non-alphanumeric characters to be treated as or similar to spaces, thus that the above, shorter matches would be prioritised higher.
Also, it might be worth considering repeated matches.

**Comment by junegunn** [comment]
I think the new `exact-boundary-match` will help in this particular case. i.e. `'ggf'`.

https://junegunn.github.io/fzf/releases/0.55.0/#exact-boundary-match-type

**Comment by xeruf** [comment]
what I'm saying is that in this, the third match should be the second one:

` printf 'ggf\nggfs\n<ggf>' | fzf --query=ggf --height=5`
![image](https://github.com/user-attachments/assets/a7dea673-9408-4fef-9da4-270d1ff33bdc)
