### ISSUE TITLE
fuzzy completion `**` doesn't preview files

### ISSUE THREAD

**Issue by lime-desu** [junegunn/fzf#3092]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

## Problem / Steps to reproduce
Here's what it look like on the left side It does showing the preview of a directory (.mozilla) and on the right side it is selected a file (.Iceauthority) which doesn't show preview.
![Screenshot from 2022-12-17 17-31-43](https://user-images.githubusercontent.com/114978689/208236053-77b8a19e-db94-4ded-a57b-8465ad12623c.png)

And this is my preview configuration on `FZF_DEFAULT_OPTS`
```
--preview '
    ([[ -f {} ]] && (bat --style=numbers --color=always --language=sh || cat {})) ||
    ([[ -d {} ]] && (exa --all --tree --links --icons {} | less)) || echo {} 1> /dev/null | head -500'
```

Also tried it on a minimal distro with a minimal configuration no (no .*rc config) and I am experiencing the same issue
![Screenshot_2022-12-17_17-21-18](https://user-images.githubusercontent.com/114978689/208236117-1e327ee2-7c9d-4b04-9642-23a170213369.png)

**Comment by demostanis** [comment]
You need to pass the file to `bat` like you do for `exa`:
```
--preview '
    ([[ -f {} ]] && (bat --style=numbers --color=always --language=sh **{}** || cat {})) ||
    ([[ -d {} ]] && (exa --all --tree --links --icons {} | less)) || echo {} 1> /dev/null | head -500'
```

**Comment by lime-desu** [comment]
> You need to pass the file to `bat` like you do for `exa`:

Thank you very much tried to simplify it this one works im using too much logical operator
```
--preview '(
    bat --style=numbers,header,changes --color=always --language=sh --line-range :500 {} ||
    exa --tree --links --icons {}) 2> /dev/null | head -500'
"
```
