### ISSUE TITLE
Vim installation

### ISSUE THREAD

**Issue by bouseman** [junegunn/fzf#3095]
- [ x] I have read through the manual page (`man fzf`)
- [ x] I have the latest version of fzf
- [ x] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [x ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ x] zsh
    - [ ] fish

## Problem / Steps to reproduce

I see in instructions:

```
If installed using Homebrew
set rtp+=/usr/local/opt/fzf

```
but  I have installed fzf by homebrew and don't have folder /usr/local/opt/fzf at all. How I can install fzf in vim?

**Comment by junegunn** [comment]
If you're using a MacBook with Apple silicon, the directory is different. It's `/opt/homebrew/opt/fzf`. I'll have to update the instruction.
