### ISSUE TITLE
feature request: scroll info

### ISSUE THREAD

**Issue by hydrargyrum** [junegunn/fzf#3096]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

## Problem / Steps to reproduce

Sometimes fzf is used for browsing without filtering (with `--disabled`). In these cases, knowing where we are on in the whole buffer (how much scrolling) is even more important than ever.

fzf has an info bar showing `<number of matches>/<number of input lines> (<number of marked items>)`. It would be nice if it also displayed the percentage of current scrolling, or the current line number. The maximum would be the number of matches, not the number of input lines.
If not using the info bar for that, current scrolling could also be shown using a custom scrollbar margin.

**Comment by hydrargyrum** [comment]
Thank you a lot!

There seems to be a little bug though, at start, sometimes the scrollbar is too big.

To reproduce:
- testing in a `docker.io/golang:latest` container
- no `$FZF_*` vars
- 272x65 terminal (actually width doesn't matter, but it seems important to have a high terminal)
- `seq 100000 | ./bin/fzf  --scrollbar --color scrollbar:red` (whatever the color)
- the scrollbar seems more than 1 character high (sometimes 2, sometimes 6, sometimes more)
- when scrolling a few pages
- the scrollbar is now only 1 character high
- it seems a bit random, maybe need to run fzf several times

Also, is it normal that by default, scrollbar is enabled (no need `--scrollbar`) but it has an invisible color?

**Comment by hydrargyrum** [comment]
@junegunn

Another bug that doesn't occur at ec20dfe312fb31dca2ebf7aa0caa05cd582cf131 and before, but occurs after one of the 3 scrollbar commits (didn't dig which one):

- run fzf (with or without scrollbar)
- just press escape
- left click mouse in terminal
- without the bug, nothing happens
- with the bug:
    - something is typed in shell prompt, for example ` 3<#3<`, the string differs after every fzf run
    - it's needed to type command `reset` to "repair" the terminal

**Comment by hydrargyrum** [comment]
Do you prefer separate issue tickets?

**Comment by junegunn** [comment]
Thanks for testing it.

> the scrollbar seems more than 1 character high (sometimes 2, sometimes 6, sometimes more)

As the list grows, the scrollbar shrinks, but fzf doesn't re-render it unless you move your cursor around. Let me fix that.

> is it normal that by default, scrollbar is enabled

Yes.

> but it has an invisible color?

The color should be identical to that of the border. Not sure what you mean by "invisible", can you show me a screenshot of `seq 50 | fzf --border --height 20 --preview 'echo {}'`

> * it's needed to type command `reset` to "repair" the terminal

It looks like I forgot to restore the terminal state after changing it to capture mouse drag action. I'll push a fix shortly.

**Comment by hydrargyrum** [comment]
And a happy new year!

**Comment by junegunn** [comment]
Thanks for the confirmation. Happy new year!
