### ISSUE TITLE
utilize git for finding relevant files

### ISSUE THREAD

**Issue by ilAYAli** [junegunn/fzf#31]
traversing e.g large git repositories with find is suboptimal, so it would be nice if fzf had to option to automatically use the fastest method available.
Something like this seems to work ~ an order of magnitude faster for me:

```
f()
{
    if [ -z $(git rev-parse --abbrev-ref HEAD 2>/dev/null) ]; then
        fzf $*
    else
        FZF_DEFAULT_COMMAND="git ls-tree -r --name-only $(git rev-parse --abbrev-ref HEAD)" fzf $*
    fi
}
```

**Comment by ebkalderon** [comment]
Sorry to necro this very old post, but I noticed that the use of `git ls-tree` isn't recommended in the `README.md` anymore, as of commit 684bfff. Does this mean that `fzf` is now fast enough, overall, that this strategy is no longer necessary? Would greatly appreciate some clarification!
