### ISSUE TITLE
0/0 matches in directory containing files beginning with -

### ISSUE THREAD

**Issue by gregory-nisbet** [junegunn/fzf#310]
When I use fzf (ruby script and go version) anywhere except for my home directory, I get the desired behavior (list of files, responsive filter as I type, etc.)

However for my home directory `/Users/gregory.nisbet` and only my home directory, fzf immediately shows 0/0 files and never updates.

I figured it out. I had a folder named `-r` I was using to test an unrelated shell script and that interfered with
`find * -path '*/\.*' -prune -o -type f -print -o -type l -print 2> /dev/null`.
I recommend replacing it with
`find . -path './.*' -prune -o -path '*/.*' -prune -o -type f -print -o -type l -print 2> /dev/null | sed 's/^..//'`
or something similar which preserves the behavior (no hidden files or ugly leading "./") but handles files with leading dashes.

**Comment by junegunn** [comment]
Ah, thanks for the report and the investigation. I'll try to come up with a better default command and apply it to the next release of fzf. Until then, you can override it with `$FZF_DEFAULT_COMMAND`.

**Comment by junegunn** [comment]
Fixed in 0.10.2. Thanks.
