### ISSUE TITLE
unable to read /sys, /dev

### ISSUE THREAD

**Issue by kazzmir** [junegunn/fzf#3100]
- [X ] I have read through the manual page (`man fzf`)
- [X ] I have the latest version of fzf
- [X ] I have searched through the existing issues

## Info

- OS
    - [ X ] Linux (ubuntu 20.04)
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ X ] bash
    - [ ] zsh
    - [ ] fish

## Problem / Steps to reproduce

```
cd /dev
fzf
```
or
```
cd /sys
fzf
```
In either case fzf shows
```
0/0
>
```

I haven't dug into the code too much, but is this expected to work?

**Comment by junegunn** [comment]
Yes, the default find command filters out those types of files.

https://github.com/junegunn/fzf/blob/fd1f7665a77f3bd062586f0f3b54d4ff9863dd4b/src/constants.go#L61

If you want to include them and you don't want to directly feed in the input via pipe, you can override the default using `$FZF_DEFAULT_COMMAND`.

```sh
cd /dev
find . | fzf


export FZF_DEFAULT_COMMAND='find .'
fzf
```
