### ISSUE TITLE
FZF reverse search key binding does not work on Linux Mint 21

### ISSUE THREAD

**Issue by wellsjo** [junegunn/fzf#3102]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

## Problem / Steps to reproduce
Clean install using `sudo apt-get install fzf` then adding `source /usr/share/doc/fzf/examples/key-bindings.zsh` to my zshrc

ctrl t works
ctrl r does not

**Comment by junegunn** [comment]
I'm not the maintainer of the apt package.  Please use the issue tracker of it instead.
