### ISSUE TITLE
Printing image in `--preview` option of PDF images

### ISSUE THREAD

**Issue by tapyu** [junegunn/fzf#3103]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

## Problem / Steps to reproduce

I'm trying to get an image preview of PDF files while looking for them. This approach is highly inspired in what is done in [this example](https://github.com/junegunn/fzf/wiki/Examples#search-for-academic-pdfs-by-author-title-journal-institution), but it prints an image of the first page instead of showing texts.

My humble try to do so is
```shell
function fpp()
{
  # open PDF using fuzzy finder with preview
  rg --type 'pdf' --files | fast-p | fzf  --read0 --reverse -e -d $'\t'  \
      --preview-window down:80% --preview '
        pdftoppm -f 1 -l 1 -singlefile -jpeg -tiffcompression jpeg -- {1} | viu -
        '
}
```

where I am using the [viu](https://github.com/atanunq/viu) program to print the image and pdftoppm to corvert the cover of the pdf file to jpg. The result is

![image](https://user-images.githubusercontent.com/22801918/209252517-6bec5cf4-d457-4f7a-b4dd-52f3b2d02133.png)

If a replace `viu` by `viu -b`, I get

![image](https://user-images.githubusercontent.com/22801918/209252751-59ce3b8a-699f-4bde-8a30-be7758624da5.png)

Which is okay but I looking for a non-pixel image. Is it possible? If it is, how can I do that?

PS: `viu` program prints seamlessly on terminal, which is `kitty`.

**Comment by junegunn** [comment]
No, it is not possible. fzf doesn't just print the output of the program, but it extracts ANSI escape sequences for colors, and trims or wraps the long lines so that the output fits on the preview window of fzf, whose dimension and position are unknown to the terminal emulator.
