### ISSUE TITLE
Using a Fish function in --preview fails with `/bin/sh : 1: __my_fn not found` 

### ISSUE THREAD

**Issue by marko911** [junegunn/fzf#3105]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [x] fish

## Problem / Steps to reproduce

Fzf is somehow not able to execute my fish function when adding it to the preview command. 
![Screenshot from 2022-12-25 09-19-36](https://user-images.githubusercontent.com/15694731/209461386-25583c11-ac02-4d94-8967-6a6c0ba3aa2e.png)

**Comment by junegunn** [comment]
The error message indicates that fzf is using `/bin/sh` to execute the command.

Excerpt from `man fzf`:

> On *nix systems, fzf runs the command with `$SHELL -c` if `SHELL` is set, otherwise with `sh -c`, so in this case make sure that the command is POSIX-compliant.

And your fish function is not available in `sh`. Try setting `$SHELL` to the path of your fish executable and see if it helps.
