### ISSUE TITLE
Problem with transform-query when testing the upcoming version 0.36.0

### ISSUE THREAD

**Issue by LangLangBart** [junegunn/fzf#3107]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Mac OS X
- Shell
    - [x] zsh
- Version
  - latest GIT version  6c37177cf5ce24dc4664ea32a6764987fb631f15

# Feedback from testing upcoming 0.36.0 version
## transform-query action
I can't get the `transform-query(...)` action to work, tried all of your examples from the [CHANGELOG](https://github.com/junegunn/fzf/blob/master/CHANGELOG.md) without success.

### example 1 
```sh
# Press space to convert the query to uppercase letters
fzf --bind 'space:transform-query(tr [:lower:] [:upper:] <<< {q})'
```
- the query string gets deleted when pressing <kbd>space</kbd>

https://user-images.githubusercontent.com/92653266/210028797-82165dac-a825-4838-8c02-36afa2e671cc.mp4

### example 2
```sh
# Bind it to 'change' event for automatic conversion
fzf --bind 'change:transform-query(tr [:lower:] [:upper:] <<< {q})'
```
- nothing happens

https://user-images.githubusercontent.com/92653266/210028767-296743ca-4b07-4175-8a2b-c5f0e96ef8fd.mp4

### example 3
```sh
# Can only type numbers
fzf --bind 'change:transform-query(sed 's/[^0-9]//g' <<< {q})'
```
- nothing happens

https://user-images.githubusercontent.com/92653266/210028900-647484e4-187b-4ddc-ac16-6acaa0749408.mp4

## load event

If I would have a reload hotkey, the string for changing the prompt  to   "⏰ Loading >"  would need to be added twice.
```sh
gh issue list -L 100 | bin/fzf --prompt '⏰ Loading >' --bind 'ctrl-r:change-prompt(⏰ Loading >)+reload:gh issue list -L 100 -R cli/cli' --bind 'load:change-prompt:👻 > '
```

https://user-images.githubusercontent.com/92653266/210029512-390e81ba-323f-4a21-b4bc-3a1fff1fe317.mp4

Wouldn't it be better to also have a `loading` event? 
```sh
gh issue list -L 100 | bin/fzf --bind 'ctrl-r:reload:gh issue list -L 100 -R cli/cli' --bind 'loading:change-prompt:⏰ Loading >' --bind 'load:change-prompt:👻 >'
```

--- 

## PS
- the other actions (` pos(...)`, `reload-sync(...)`, `next-selected`, `prev-selected`) did work nicely
- thanks for adding the color name `preview-label` #3053
  - should I close the ticket since the other feature of the ticket is not planned? 

<img src="https://user-images.githubusercontent.com/92653266/210030324-fef48846-7135-40af-9cba-44b973a7b644.png" width="500">

**Comment by junegunn** [comment]
> ```shell
> fzf --bind 'space:transform-query(tr [:lower:] [:upper:] <<< {q})'
> ```

It works for me fine. Does `$SHELL -c "tr [:lower:] [:upper:] <<< 'hello'"` work as expected on your shell?

**Comment by LangLangBart** [comment]
```sh
$SHELL -c "tr [:lower:] [:upper:] <<< 'hello'"
# zsh:1: no matches found: [:lower:]

$SHELL -c "tr "e" "a" <<< 'hello'"
# hallo
```

**Comment by LangLangBart** [comment]
Ok, i got it, it was the use of single quotes.

```sh
# this will work
bin/fzf --bind 'change:transform-query(sed "s/[^0-9]//g" <<< {q})'

# this will not work
bin/fzf --bind 'change:transform-query(sed 's/[^0-9]//g' <<< {q})'
```

everything else in this ticket was just feedback, can be closed

**Comment by junegunn** [comment]
> it was because of the quotes.

```sh
$ zsh -c 'tr [:lower:] [:upper:] <<< foo'
zsh:1: no matches found: [:lower:]
$ bash -c 'tr [:lower:] [:upper:] <<< foo'
FOO
```

I wasn't aware of it as I'm a bash user. I'm going to update the examples not to confuse zsh users.

> ```shell
> bin/fzf --bind 'change:transform-query(sed "s/[^0-9]//g" <<< {q})'
> ```

Let me fix this as well.

> Wouldn't it be better to also have a loading event?

Maybe, but I'd prefer not to include non-essential shortcut features at this time.



> * should I close the ticket since the other feature of the ticket is not planned?

Doesn't matter. Up to you. Maybe I decide to implement dynamic labels in the future.
