### ISSUE TITLE
Bash: How do I escape execute-silent(nvim {}) in multi-line FZF_DEFAULT_OPTS?

### ISSUE THREAD

**Issue by eggbean** [junegunn/fzf#3114]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues
- OS - [X] Linux
- Shell- [X] bash

I have `FZF_DEFAULT_OPTS` set like this, which has always worked fine, but I want to add `--bind=ctrl-o:'execute-silent(nvim {})'`, but I do not know how to escape the `{}` or whatever that needs to be escaped, as it this doesn't work:

    export FZF_DEFAULT_OPTS=" \
      --ansi \
      --reverse \
      --bind=ctrl-a:toggle-all \
    ..........
      --bind=ctrl-u:preview-page-up \
      --bind=ctrl-o:execute-silent(nvim {})+abort \  <----How do I fix this?
      --bind=alt-bs:clear-query \
    ..........
      --color spinner:#8BE9FD \
      --color header:#8BE9FD \
    "
The introduction of this new key binding breaks the whole variable.

**Comment by junegunn** [comment]
* You don't need trailing `\`s because the whole string is quoted.
* `fzf --bind=ctrl-o:execute-silent(nvim {})+abort` won't work in your command-line. You're passing two arguments, `--bind=ctrl-o:execute-silent(nvim` and `{})+abort`, which fzf cannot understand.
* Use `execute` instead of `execute-silent` because you want to use nvim interactively.
* I'd advise against this binding because fzf isn't just for files. e.g. `history | fzf`
* I'd advise against putting `--ansi` to the default. See https://github.com/junegunn/fzf#performance

```sh
export FZF_DEFAULT_OPTS="
  --ansi
  --reverse
  --bind=ctrl-a:toggle-all
  --bind=ctrl-u:preview-page-up
  --bind='ctrl-o:execute(nvim {})+abort'
  --bind=alt-bs:clear-query
  --color spinner:#8BE9FD
  --color header:#8BE9FD
"
```

**Comment by eggbean** [comment]
Thank you for replying, but using your line above now nvim does execute, it seems to immediately exit, and fzf doesn't abort, so needs to be cancelled.

Also, my variable doesn't work at all without the trailing backslash line endings.

**Comment by junegunn** [comment]
Works for me fine without backslashes. Try changing the command to `$EDITOR {} > /dev/tty`.

https://github.com/junegunn/fzf/issues/1360#issuecomment-966054123

**Comment by eggbean** [comment]
Thanks, that works. However, the text editor opens in the tmux popup window instead of in the original pane. I suppose I should have expected this. Cheers.

**Comment by junegunn** [comment]
> opens in the tmux popup window

fzf is a filter program that is designed to be used in shell scripts and this is what I would do.

```sh
# This should work well
result=$(fzf-tmux -p) && vim "$result"
```
IMO, relying on `execute+abort` instead feels a bit like a hack. And like I mentioned above, fzf isn't just for files so setting up a global binding that opens an entry in the editor is not recommended.

But if you really want, you can do something like `tmux new-window $EDITOR {}`.

**Comment by eggbean** [comment]
That works great. I won't use this keybinding when I am not using fzf to show text files, so I think it will be okay.

Thanks for your help.
