### ISSUE TITLE
Feature request: Multiple filter windows

### ISSUE THREAD

**Issue by mihaigalos** [junegunn/fzf#3116]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

## Problem / Steps to reproduce

I would like to have multiple filter windows in `fzf`.

Currently, I'm using it to filter commits in `git log` with a preview (sources [`here`](https://github.com/mihaigalos/config/blob/baaba026ed57b16b5cee738680489c65362df55b/.zshrc#L56-L69)):
![image](https://user-images.githubusercontent.com/16443090/211259169-935b36be-31da-4dce-874c-b35c7b85d4dc.png)

I would like to optionally filter files _after_ applying the 1st commit filter.

If the 1st filter is empty, the 2nd one would match everything initially. 

This sounds like a separate filter window feature request, I am therefore opening it up here.

**Comment by junegunn** [comment]
It's a lot of work and I don't think it's worth it. You might want to start another instance of fzf process in your script for subsequent filtering.
