### ISSUE TITLE
no CTRL-T CTRL-X in vim

### ISSUE THREAD

**Issue by buchuki** [junegunn/fzf#312]
This is probably a configuration issue, but when I use fzf in vim everything works perfectly until I find the entry I want to open and press ctrl-T to open it in a new tab. Nothing happens (no visible errors). If I press enter the file opens in the current window as expected.

I'm using vim inside tmux on a remote host, so there may be a conflict here. I've heard of fzf-tmux but I have no idea how to tell if I am or should be using it; I just let the fzf installer set things up.

Fzf was installed a couple days ago. Is it a bug or config issue?

**Comment by junegunn** [comment]
Have you checked #273?

`fzf` and its vim wrapper `fzf#run()` do not know what to do on CTRL-T and CTRL-X and such keys are not bound to any action by default. The reason `:FZF` command can take those keys is that it was implemented to [pass `--expect` option](https://github.com/junegunn/fzf/blob/0.10.2/plugin/fzf.vim#L384) to fzf. You can find more examples on `--expect` on the wiki page.
e.g. https://github.com/junegunn/fzf/wiki/Examples-(vim)#narrow-ag-results-within-vim

**Comment by buchuki** [comment]
Ah, I wasn't specific enough; I am actually using :FZF but not getting the ctrl-T, etc behavior. I haven't defined my own function. How can I debug why :FZF isn't behaving as expected?

**Comment by junegunn** [comment]
`fzf --version`.

**Comment by buchuki** [comment]
It's ancient! I thought I had pulled from master:

fzf 0.8.9 (Dec 24, 2014)

**Comment by buchuki** [comment]
ok, I ran ./install again and it still hasn't updated; it looks like it's downloading the executable instead of using the one from master that I have pulled in. How best to live dangerously?

**Comment by junegunn** [comment]
What does the install script say? Please attach the full log.

**Comment by buchuki** [comment]
Thanks for the quick responses.

I've solved the issue; the script was not able to escape from my proxy; for some reason it wasn't honouring the https_proxy env variables I had exported from my shell. I exported them inside the install script and it worked correctly.

Dunno if you want to make the script more robust against proxies, but one thing you could do is fail explicitly if it can't download the new version for any reason. It went on to show me the rest of the install procedure and I missed the fact the download had failed.

**Comment by junegunn** [comment]
Yeah, that's a good point, there's really no reason to fall back to the old Ruby version when the binary is available for the platform.
