### ISSUE TITLE
[feature request] fzf support for executables under `$PATH`

### ISSUE THREAD

**Issue by tigerinus** [junegunn/fzf#3122]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

## Problem / Steps to reproduce

[Ctrl]-[R] is great. However it's limited to `history` only.

It'd be great to

- add a shortcut to search for an executable under `$PATH`. 
- OR, add fzf support to `exec` command.

Thanks!

**Comment by junegunn** [comment]
You can of course implement such things in shell scripts using fzf. Please read through the documentation.
