### ISSUE TITLE
--max-height

### ISSUE THREAD

**Issue by jaggzh** [junegunn/fzf#3124]
- [x] I have read through the manual page (`man fzf`)
- [o] I have the latest version of fzf
- [x] I have searched through the existing issues
- [x] I have searched the source-code :)

## Info

- OS
    - [x ] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x ] bash
    - [ ] zsh
    - [ ] fish

## Problem / Steps to reproduce
I think we're missing a --max-height option.  It's nice to not clear the screen but not wipe out everything on it, while having the list be only the size of the input items if they're short.

For example, you send in 5 items. fzf shows only 5 at the bottom of the screen, but if you send it 200 items, --maxheight='50%' prevents it from gobbling up all your recent commands.

**Comment by junegunn** [comment]
See https://github.com/junegunn/fzf/commit/22cbd9fa58512ffdcc975bab37a55467d5e10968

```sh
seq 1 | fzf --height ~50%
seq 10 | fzf --height ~50%
seq 100 | fzf --height ~50%
seq 1000 | fzf --height ~50%
```
