### ISSUE TITLE
Make fzf-tmux default instead of fzf

### ISSUE THREAD

**Issue by dagadbm** [junegunn/fzf#3125]
- [X] I have read through the manual page (`man fzf`)
- [X] I have the latest version of fzf
- [X] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [X] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [X] zsh
    - [ ] fish

## Problem / Steps to reproduce

This is a feature suggestion.
I would like to know if it is possible for fzf by default to just use the tmux popup window if available.
If I use ctrl-f it will always default to using fzf.
I even tried replacing the fzf binary with fzf-tmux but it didnt work.

**Comment by dagadbm** [comment]
it was very hidden away in the documentation

export FZF_TMUX=1

**Comment by junegunn** [comment]
Excerpt from https://github.com/junegunn/fzf#key-bindings-for-command-line

> If you're on a tmux session, you can start fzf in a tmux split-pane or in a tmux popup window by setting `FZF_TMUX_OPTS` (e.g. `-d 40%`). See `fzf-tmux --help` for available options.

`export FZF_TMUX_OPTS='-p80%,60%'` is what I'm using.
