### ISSUE TITLE
0.36 fails tests on 32-bit

### ISSUE THREAD

**Issue by nekopsykose** [junegunn/fzf#3127]
- [ ] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [ ] fish
    - [x] busybox ash

## Problem / Steps to reproduce

running go test fails with

```
# github.com/junegunn/fzf/src/util [github.com/junegunn/fzf/src/util.test]
src/util/util_test.go:118:14: cannot use math.MaxUint32 (untyped int constant 4294967295) as int value in argument to AsUint16 (overflows)
```

this is probably because `int` is 32-bit on 32-bit platforms and 64 on 64-bit platforms, but the test passes math.MaxUint32 which overflows a signed 32-bit int when ran on a 32-bit platform

**Comment by junegunn** [comment]
Please note that fzf no longer officially supports 32-bit platforms. But I can make a small adjustment so that the test case doesn't fail.

```diff
diff --git a/src/util/util_test.go b/src/util/util_test.go
index ca12aa7..6b1293e 100644
--- a/src/util/util_test.go
+++ b/src/util/util_test.go
@@ -2,6 +2,7 @@ package util
 
 import (
 	"math"
+	"strconv"
 	"strings"
 	"testing"
 	"time"
@@ -115,7 +116,7 @@ func TestAsUint16(t *testing.T) {
 	if AsUint16(math.MinInt16) != 0 {
 		t.Error("Expected", 0)
 	}
-	if AsUint16(math.MaxUint32) != math.MaxUint16 {
+	if strconv.IntSize == 64 && AsUint16(math.MaxUint32) != math.MaxUint16 {
 		t.Error("Expected", math.MaxUint16)
 	}
 }
```

Is this good enough?

**Comment by junegunn** [comment]
Okay, that doesn't compile. But we don't really need to use `math.MaxUint32`.

**Comment by nekopsykose** [comment]
> Okay, that doesn't compile. But we don't really need to use math.MaxUint32 to validate the logic.  

yeah, the `uint16 + 1` was the pick downstream too (by someone else), i forgot to then send it back up here too, apologies.

looks good to me, thanks :)
