### ISSUE TITLE
  [neovim] :FZF crashes when mapping 'open in new tab' to enter

### ISSUE THREAD

**Issue by jgkamat** [junegunn/fzf#313]
I've mapped 'enter' when using fzf to opening in a new tab rather than opening in the current pane. This seems to cause some of the symptoms of #206. When removing this custom config, everything seems to work as intended (showing #206 seems to be getting better?). Opening tabs seems to still induce this problem, with the config off, the config seems to make it more pronounced? It all seems very flakey, but I think this config will help you reproduce the problem more(?) accurately

1. When opening a new file (pressing enter to open a new tab), the mode changes to 'TERMINAL' and waits there with the file open.
2. When pressing any key, the newly opened tab will crash, and bring you back to the old tab.

Here is the configuration I used to make this behavior happen, see the line starting with 'ctrl-m':
```
let g:fzf_action = {
  \ 'ctrl-m': 'tabedit',
  \ 'ctrl-o': 'e',
  \ 'ctrl-t': 'tabedit',
  \ 'ctrl-h':  'botright split',
  \ 'ctrl-v':  'vertical botright split' }
```

@tarruda this issue was indeed a different issue from #206, as this occurs almost all the time for me even with python off.

**Comment by jgkamat** [comment]
I figured out a little bit of more information, this happens when the tab is created at the right end (where there are no other tabs). Inserting tabs in the middle (between two other tabs) seems to be ok.

**Comment by zenbro** [comment]
After trying a build from neovim/neovim#3309 this issue is no longer present:
> 1. When opening a new file (pressing enter to open a new tab), the mode changes to 'TERMINAL' and waits there with the file open.
> 2. When pressing any key, the newly opened tab will crash, and bring you back to the old tab.

In rare cases this message is shown when opening files from fzf by pressing `Enter`:

    [Program exited, press any key to close]

**Comment by tarruda** [comment]
> In rare cases this message is shown when opening files from fzf by pressing Enter:

I'm looking into this

**Comment by zenbro** [comment]
Thanks for your hard work @tarruda!

**Comment by tarruda** [comment]
@zenbro can you give neovim/neovim#3309 another shot?

**Comment by zenbro** [comment]
@tarruda
Build from tarruda/neovim@c0f4b56c9f80678f4c37f658db40ffdbd61b7e76

This issue is returned:
> 1. When opening a new file (pressing enter to open a new tab), the mode changes to 'TERMINAL' and waits there with the file open.
> 2. When pressing any key, the newly opened tab will crash, and bring you back to the old tab.

This issue is no longer present:
> In rare cases this message is shown when opening files from fzf by pressing Enter: [Program exited, press any key to close]

**Comment by tarruda** [comment]
@zenbro / @jgkamat can you two send me the vimrc that causes the tabedit/crash bug? I'm unable to reproduce with my current config.

**Comment by jgkamat** [comment]
[This is my current vimrc](https://github.com/jgkamat/dotfiles/blob/master/vim/.vimrc), its failing on the current distrubted one. I haven't been able to build it properly for some reason, but I'll figure out what I'm doing wrong and let you know if I can still reproduce this...

**Comment by zenbro** [comment]
[My vimrc](https://github.com/zenbro/dotfiles/blob/master/.nvimrc)
I try to minimize it for testing purpose as I get more time.

**Comment by zenbro** [comment]
I found plugin that cause this problem - [vim-airline](https://github.com/bling/vim-airline) with enabled tabline feature.
Here is minimal vimrc version:

```vim
let g:mapleader = "\<Space>"

" Autoinstall vim-plug {{{
if empty(glob('~/.nvim/autoload/plug.vim'))
  silent !curl -fLo ~/.nvim/autoload/plug.vim --create-dirs
 --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall
endif
" }}}
call plug#begin('~/.nvim/plugged') " Plugins initialization start {{{
" }}}

Plug 'bling/vim-airline'
" {{{
  let g:airline_left_sep  = '▓▒░'
  let g:airline_right_sep = '░▒▓'
  let g:airline_section_z = '%2p%% %2l/%L:%2v'
  let g:airline#extensions#syntastic#enabled = 0
  let g:airline#extensions#whitespace#enabled = 0
  let g:airline_exclude_preview = 1

  " Tabline
  let g:airline#extensions#tabline#enabled = 1
  let g:airline#extensions#tabline#show_buffers = 1
  let g:airline#extensions#tabline#show_tabs = 0
  let g:airline#extensions#tabline#buffer_idx_mode = 1
  let g:airline#extensions#tabline#fnamecollapse = 1
  let g:airline#extensions#tabline#show_close_button = 0
  let g:airline#extensions#tabline#show_tab_type = 0
  let g:airline#extensions#tabline#buffer_min_count = 2
" }}}
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': 'yes \| ./install' }
Plug 'junegunn/fzf.vim'
" {{{
  nnoremap <silent> <leader><space> :Files<CR>
" }}}
call plug#end() " Plugins initialization finished {{{
" }}}
```

**Comment by zenbro** [comment]
Same problem with [lightline.vim](https://github.com/itchyny/lightline.vim):

```vim
let g:mapleader = "\<Space>"

" Autoinstall vim-plug
if empty(glob('~/.nvim/autoload/plug.vim'))
  silent !curl -fLo ~/.nvim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall
endif

call plug#begin('~/.nvim/plugged') " Plugins initialization start
Plug 'itchyny/lightline.vim'
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': 'yes \| ./install' }
Plug 'junegunn/fzf.vim'
nnoremap <silent> <leader><space> :Files<CR>

" Plugins initialization finished
call plug#end()
```

**Comment by jgkamat** [comment]
Huh, I never suspected airline, nice job!

**Comment by cHoco** [comment]
Actually I can reproduce the problem with different plugins but not with your example vimrc.
So I don't think it's related to airline or lightline.

**Comment by jgkamat** [comment]
I'm only able to reproduce this with airline on (I haven't tried light-line).

**Comment by tarruda** [comment]
@zenbro / @jgkamat I still can't reproduce it with #3309 after a few tries. Does the crash happen consistently? I used this vimrc:

```vim
let g:mapleader = "\<Space>"
let g:fzf_action = {
  \ 'ctrl-m': 'tabedit',
  \ 'ctrl-o': 'e',
  \ 'ctrl-t': 'tabedit',
  \ 'ctrl-h':  'botright split',
  \ 'ctrl-v':  'vertical botright split' }

" Autoinstall vim-plug
if empty(glob('~/.nvim/autoload/plug.vim'))
  silent !curl -fLo ~/.nvim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall
endif
call plug#begin('~/.nvim/plugged')

Plug 'bling/vim-airline'
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': 'yes \| ./install' }
Plug 'junegunn/fzf.vim'
nnoremap <silent> <leader><space> :Files<CR>

call plug#end() " Plugins initialization finished
```

And then followed these steps:

- execute build/bin/nvim (from nvim source root)
- type `:FZF<cr>`
- select a file(eg: README.md)
- press enter
- the file opens normally in a new tab.

Can you give some more detailed steps on how I can reproduce with the above vimrc? Also, can you paste the output of `nvim --version`?

**Comment by jgkamat** [comment]
Oh, sorry for not making this clear, disabling airline fixed the issue for me on a stock nvim. After building your branch, I can't seem to reproduce it anymore (even with arline)! :+1:  (however, I've seen this problem only after opening a couple of files). I'll let you know if I see any issues with the new build as I continue using it a bit more.

Just in case you need it, here is my nvim --version on the one I built!
```
NVIM 0.0.0-alpha+201509171417 (compiled Sep 18 2015 01:05:47)
Commit: a1ac68ad9f43c1e388fc8ff9d987481ce22148db
Build type: Debug
Compilation: /usr/bin/cc -Wconversion -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/tmp/neovim/build/config -I/tmp/neovim/src -I/tmp/neovim/.deps/usr/include -I/tmp/neovim/.deps/usr/include -I/tmp/neovim/.deps/usr/include/luajit-2.0 -I/tmp/neovim/.deps/usr/include -I/tmp/neovim/.deps/usr/include -I/tmp/neovim/.deps/usr/include -I/tmp/neovim/.deps/usr/include -I/usr/include -I/tmp/neovim/build/src/nvim/auto -I/tmp/neovim/build/include
Compiled by jay@ike

Optional features included (+) or not (-): +acl   +iconv    +jemalloc 
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/nvimrc"
     user vimrc file: "~/.nvimrc"
 2nd user vimrc file: "~/.nvim/nvimrc"
      user exrc file: "~/.exrc"
  fall-back for $VIM: "/usr/local/share/nvim"
```

**Comment by zenbro** [comment]
@tarruda 
```
NVIM 0.0.0-alpha+201509171417 (compiled Sep 18 2015 08:10:20)
Commit: a1ac68ad9f43c1e388fc8ff9d987481ce22148db
Build type: RelWithDebInfo
Compilation: /usr/bin/cc -Wconversion -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/home/i/github/neovim/build/config -I/home/i/github/neovim/src -I/home/i/github/neovim/.deps/usr/include -I/home/i/github/neovim/.deps/usr/include -I/home/i/github/neovim/.deps/usr/include/luajit-2.0 -I/home/i/github/neovim/.deps/usr/include -I/home/i/github/neovim/.deps/usr/include -I/home/i/github/neovim/.deps/usr/include -I/home/i/github/neovim/.deps/usr/include -I/usr/include -I/home/i/github/neovim/build/src/nvim/auto -I/home/i/github/neovim/build/include
Compiled by i@x59sl
```

With this vimrc:
```vim
let g:mapleader = "\<Space>"

if empty(glob('~/.nvim/autoload/plug.vim'))
  silent !curl -fLo ~/.nvim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall
endif
call plug#begin('~/.nvim/plugged')

Plug 'bling/vim-airline'
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': 'yes \| ./install' }
Plug 'junegunn/fzf.vim'
nnoremap <silent> <leader><space> :Files<CR>
call plug#end()
```
Note: there is no `g:fzf_action overriding`.

Steps:

1. execute nvim
2. cd into neovim source root
3. press `<space><space>`, type something, press `enter`
4. Repeat step 3 few times.

**Comment by tarruda** [comment]
@zenbro now I can reproduce, will investigate and push a fix #3309

**Comment by tarruda** [comment]
@zenbro can you try neovim/neovim#3309 again?

**Comment by zenbro** [comment]
@tarruda
With neovim:
```
NVIM 0.0.0-alpha+201509181345 (compiled Sep 18 2015 20:11:18)
Commit: 7c5b2c684c9fcadc85b88c5c5c67d257da781dcf
Build type: RelWithDebInfo
Compilation: /usr/bin/cc -Wconversion -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/home/i/github/neovim/build/config -I/home/i/github/neovim/src -I/home/i/github/neovim/.deps/usr/include -I/home/i/github/neovim/.deps/usr/include -I/home/i/github/neovim/.deps/usr/include/luajit-2.0 -I/home/i/github/neovim/.deps/usr/include -I/home/i/github/neovim/.deps/usr/include -I/home/i/github/neovim/.deps/usr/include -I/home/i/github/neovim/.deps/usr/include -I/usr/include -I/home/i/github/neovim/build/src/nvim/auto -I/home/i/github/neovim/build/include
Compiled by i@x59sl
```
I can no longer reproduce this problem. Thank you so much! :smiley:

**Comment by tarruda** [comment]
neovim/neovim#3309 is merged, @jgkamat can you confirm the problem is fixed(on neovim master) and if so close the issue?

**Comment by jgkamat** [comment]
It looks good to me! Thanks so much for all your help! :tada: :smile:
