### ISSUE TITLE
Microsoft Defender on Windows 10 is flagging v0.36.0 as malware

### ISSUE THREAD

**Issue by gwojan** [junegunn/fzf#3131]
- [X] I have read through the manual page (`man fzf`)
- [X] I have the latest version of fzf
- [X] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [ ] Mac OS X
    - [X] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [ ] fish
    - [X] powershell

## Problem / Steps to reproduce

Attempting to run `fzf --version` results in Windows Defender scanning and quarantining `fzf.exe` as being infected with malware. VirusTotal also shows 0.36.0 as failing a Defender scan.

[Trojan:Win32/Wacatac.F!ml](https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?name=Trojan%3aWin32%2fWacatac.F!ml&threatid=2147749375)

**Comment by junegunn** [comment]
Thanks for the heads up. It's a well-known issue with Golang binaries and there's nothing I can do. You'll have to just ignore the warning.

* https://go.dev/doc/faq#virus
