### ISSUE TITLE
A way to change a variable that's expanded in query in order to toggle flags

### ISSUE THREAD

**Issue by quicknir** [junegunn/fzf#3132]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

## Problem / Steps to reproduce

I'm using `fd` to populate an fzf widget, very similar to the default Ctrl-t widget that's provided. fd has all kinds of flags of interest that could control how that list is populated: whether to show hidden files, ignored ones, whether to follow symlinks, and so on. It would be nice to have keybindings that toggle individual options. However, I dont' really see a way to do this in fzf. You can have bindings to change between different commands, but obviously there's a fair number of flags, so being able to toggle N flags lets you potentially have 2^N different queries, so this is much more robust.

It seems to me like this can be solved relatively easily if we had a way to modify shell variables. One would have query `fd --color always $MAYBE_HIDDEN_FLAG $MAYBE_IGNORED_FLAG` and so on. Individual keybindings would just be bound to "flip" the value of the variable, and then reload. The obvious place to look for something like this is execute, but since execute runs in a subshell, I can't seem to hang onto any state from it, unless I literally stored things in a file. 

Is there a way to do this that I'm missing? Note that even to toggle between two behaviors, e.g. hidden or not, with a single shortcut, I found quite awkward. Or at least, the only way I can see to do it is to bind both of the commands you want to two different shortcuts, and then use unbind and rebind to swap the shortcuts between them. In this case, you're forced to bind a second shortcut even though you have no plans of using it (although, again, I could easily be missing something).

**Comment by quicknir** [comment]
Edit: I think I do see how to do it, by basically using expect. I do think this is a lot more painful than it could be, it could be as easy as `--bind 'ctrl-i:execute_in(flip_hidden_flag)+reload'`, unless I'm missing something. But I suppose if expect is the sanctioned way to do this and this is considered okay then I can close my issue.

**Comment by junegunn** [comment]
> unless I literally stored things in a file

I feel state management is a little beyond the scope of this interactive "grep" program, so using an external state store (file, database, API service, etc.) is the recommended way to do it.

```sh
echo space to pingpong | fzf --height '~10' --bind 'space:reload:
  if [ -f /tmp/ping ]; then
    rm -f /tmp/ping
    echo pong
  else
    touch /tmp/ping
    echo ping
  fi
'
```

You are probably better off using an external script yet this is just an example.

**Comment by quicknir** [comment]
Would you implement something like this with temporary files over expect + loop? That seems to be the approach of extrakto, a tmux plugin. It has a single shortcut that cycles between types of filters. Just curious for your perspective.

Also: wanted to say thank you for fzf, it's been incredibly useful.

**Comment by junegunn** [comment]
I'm not familiar with the project, but `reload` can be a better fit for the use case because we can avoid the flickering of the screen from fzf restarts. One thing to note is that `reload` is a relatively recent addition to fzf. It was added in November 2019, while `--expect` was added in 2015.

* https://github.com/junegunn/fzf/commit/78da9287272a0bfa183498c5b2e9fde10a3663a0
* https://github.com/junegunn/fzf/commit/2a167aa030b244060fc479d2b88fdb9b9171d026
