### ISSUE TITLE
Hide scrollbar automatically if --no-mouse is specified

### ISSUE THREAD

**Issue by ArtAndreev** [junegunn/fzf#3133]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [x] fish

## Problem / Steps to reproduce

After updating to v0.36.0 scrollbar appeared at window and at preview window. I wanted to hide it, because I don't use mouse and I have `--no-mouse` enabled in my `FZF_DEFAULT_OPTS`. I added `--no-scrollbar`, as it was described in release notes, but I think, it will be better to automatically hide scrollbars, if `--no-mouse` is enabled, because scrollbars are inactive and don't to anything. Also they don't give useful visual information about position, because there are already an entry counter at bottom of window and a line counter at top of preview window.

**Comment by junegunn** [comment]
> Also they don't give useful visual information about position

That's subjective. I find it easier to find the position by looking at the size and position of the scrollbar than by reading the numbers. Actually, I really considered removing the line counter of the preview window after adding the scrollbar but now I know someone prefers it over the scrollbar :)

Wonder why you disable mouse support, it's quite useful for scrolling the preview window.

**Comment by ArtAndreev** [comment]
Thanks for the detailed answer!

I have an other question. The preview window has a line counter, but the main window doesn't. I mixed up the entry counter (filtered/all at the bottom of the entry window) with a cursor position (pos/filtered). Is there a way to show a cursor position like showing a line counter? It will help to understand a relative position of cursor, so it will fit my workflow.

**Comment by junegunn** [comment]
No. The two windows have very different purposes and it's natural they provide different UI elements. The main search window presents the results sorted by their relevance, and the user normally wouldn't have to scroll far away from the top position. (i.e. Narrow down the list by typing in the query until the best match appears, then press enter to select it. No cursor movement during the process.) I believe the additional scroll info panel will likely confuse the users without much benefit.

**Comment by ArtAndreev** [comment]
Okay, I understand now. Thank you, have a nice day!
