### ISSUE TITLE
"unknown action" when action argument contains a newline

### ISSUE THREAD

**Issue by AviKav** [junegunn/fzf#3138]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [x] fish

## Problem / Steps to reproduce

Works on 0.35.1:
```sh
$ fzf --bind alt-e:execute[echo\ \n\ q]
```
0.36.0:
```sh
$ fzf --bind alt-e:execute[echo\ \n\ q]
unknown action: execute[echo
 q]
```

**Comment by junegunn** [comment]
I changed the option parser to fix some other problems, but it looks like the new parser doesn't allow new lines in an action argument in this form. I should probably fix this, but for now, you can write it in `action-name:...` form and it should work fine (see `ACTION ARGUMENT` section of the man page). This form is simpler and less prone to parse errors.

```sh
fzf --bind alt-e:execute:echo\ \n\ q
```
