### ISSUE TITLE
How to disable fzf-tmux script?

### ISSUE THREAD

**Issue by ronakg** [junegunn/fzf#314]
I'm using iTerm2 with tmux integration (so every tmux window is an iTerm2 tab). When I open FZF, the new tmux pane doesn't have focus by default. I have to change focus to the fzf pane to be able to type my query.

Is there a way to disable the fzf-tmux script? I don't mind the full screen fzf window that appears outside tmux.

**Comment by junegunn** [comment]
In vim?

**Comment by ronakg** [comment]
In bash. All the fzf commands result in a new tmux pane, which isn't working that well with iterm2 tmux integration. So I'd like to use default fzf instead of fzf-tmux.

**Comment by junegunn** [comment]
> All the fzf commands

I guess you mean key bindings and fuzzy completion, right? Then try `export FZF_TMUX=0` as described in https://github.com/junegunn/fzf#key-bindings-for-command-line.

**Comment by ronakg** [comment]
Okay, that worked for bash. Inside Vim, it's still opening the fzf window in a tmux pane.

FZF_TMUX setting doesn't apply to vim?

**Comment by junegunn** [comment]
See https://github.com/junegunn/fzf#fzf

```vim
cnoreabbrev FZF FZF!
```

**Comment by ronakg** [comment]
Thanks. I'm now using `FZF!` in my key-binding to open fzf window.

**Comment by ronakg** [comment]
Need some more help!

`cnoreabbrev FZF FZF!` isn't working when I'm calling any of the fzf functions like `fzf#run()` for going through open buffers.

I've added `nnoremap <leader>f :FZF! -x<CR>` to my vimrc for invoking fzf.

**Comment by junegunn** [comment]
They're unrelated. (`:help cnoreabbrev`)

FZF[!] is a command that is based on `fzf#run()`. And `fzf#run()` does not open tmux pane by default unless you pass some options. Please read through the manual page.
