### ISSUE TITLE
Preview window doesn't scroll after interactive external command

### ISSUE THREAD

**Issue by mklein994** [junegunn/fzf#3141]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

## Problem / Steps to reproduce

A bit of background: I like to use `fzf` together with `jq` to interactively filter and manipulate JSON as I type.

```bash
#!/bin/bash
#
# Inspired by this gist: https://gist.github.com/reegnz/b9e40993d410b75c2d866441add2cb55
#
# Usage:
#
#   cat foo.json | jq-repl.sh [-]
#   jq-repl.sh <FILE>

# Save stdin so it can be read from multiple times, if necessary.
if [[ -z $1 ]] || [[ $1 == "-" ]]; then
	input=$(mktemp)
	trap 'rm -f $input' EXIT
	cat /dev/stdin >"${input}"
else
	input="$1"
fi

# Rely solely on the preview command, not on a list piped in.
echo | fzf \
	--disabled \
	--preview-window='up,99%' \
	--preview="jq {q} ${input}" \
	--bind="alt-enter:execute:jq {q} ${input} | nvim -" \
	--bind="alt-l:execute:jq {q} ${input} | less"
```

This is a stripped-down version to make the issue easier to replicate; the full version is a bit more DRY and has more key bindings.

Anyways, this setup works great: I can scroll the preview with my mouse, and when I press <kbd>alt</kbd>+<kbd>l</kbd>, I can scroll the transformed JSON in `less` too. When I quit `less`, scrolling still works.

Here's the problem: when I press <kbd>alt</kbd>+<kbd>enter</kbd> (which launches `nvim` in much the same way), then `:quit!` and come back to `fzf`, I can't use my mouse to scroll the preview window. Scrolling with <kbd>ctrl</kbd>+<kbd>up</kbd> and <kbd>ctrl</kbd>+<kbd>down</kbd> still works, though.

I've tried this with various terminal emulators (kitty, Gnome Terminal, and Alacritty), and they all have the same behavior, i.e. show the same bug.

I figured that this was an issue with Neovim, however the same thing happens if I use another program, such as [VisiData](https://www.visidata.org/). `less` somehow doesn't have this problem. I'm not very familiar with "terminfo" and so on, but I suspect the issue is with how the alternate buffer is handled (perhaps by the external program).

**Comment by junegunn** [comment]
> This is a stripped-down version to make the issue easier to replicate

We can go further and we're left with this.

```sh
# Mouse disabled afterwards
fzf --bind="enter:execute:nvim"

# Mouse still works
fzf --bind="enter:execute:read"
```

But we can easily fix this by reenabling mouse mode when coming back to fzf.

**Comment by mklein994** [comment]
Wow, thanks! It took me longer to write up this issue than you did to fix it. Much appreciated. 🎉

**Comment by junegunn** [comment]
No problem, thanks for the report!
