### ISSUE TITLE
brew installed 0.37 segfaults

### ISSUE THREAD

**Issue by indigoviolet** [junegunn/fzf#3143]
- [ ] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

## Problem / Steps to reproduce

`brew upgrade fzf`; run fzf; segfaults

**Comment by indigoviolet** [comment]
I just had another upgraded recipe also segfault, so perhaps this is not a general issue. Feel free to close if you don't receive any other reports.

**Comment by indigoviolet** [comment]
Turned out to be https://github.com/Homebrew/homebrew-core/issues/116841

**Comment by junegunn** [comment]
Thanks for the update.
