### ISSUE TITLE
Consider Adding printenv to shell completion

### ISSUE THREAD

**Issue by salmankhilji** [junegunn/fzf#3145]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

## Feature Request

Please considering adding the `printenv` command to shell completion of environment variables.  Currently, we have:

```
_fzf_setup_completion 'var'   export unset
```

We can change this to:

```
_fzf_setup_completion 'var'   export unset printenv
```

### Workaround

Add the following to `~/.bashrc`:

```
_fzf_setup_completion var printenv
```

**Comment by junegunn** [comment]
SGTM, thanks for the suggestion.
