### ISSUE TITLE
How to change the default color of fzf input match character output

### ISSUE THREAD

**Issue by wangmings** [junegunn/fzf#3146]
- [ ] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

### problem
![截屏2023-01-26 下午6 30 03](https://user-images.githubusercontent.com/44308153/214815966-b56f81b0-4398-43b2-ac43-bbb129da7571.png)

> When fzf searches by entering characters, the matching characters are white by default, which leads to that I can't see the matching string clearly when the terminal is set to white. I find relevant problems! No color has been found to set the output color for this matching character

```BASH
# This setting also does not set the output color of this matching character
export FZF_DEFAULT_OPTS='--color=bg+:#D9D9D9,bg:#E1E1E1,border:#C8C8C8,spinner:#719899,hl:#719872,fg:#616161,header:#719872,info:#727100,pointer:#E12672,marker:#E17899,fg+:#616161,preview-bg:#D9D9D9,prompt:#0099BD,hl+:#719899'
```

**Comment by junegunn** [comment]
`hl+` is for that.


> ```shell
> # This setting also does not set the output color of this matching character
> export FZF_DEFAULT_OPTS='--color=bg+:#D9D9D9,bg:#E1E1E1,border:#C8C8C8,spinner:#719899,hl:#719872,fg:#616161,header:#719872,info:#727100,pointer:#E12672,marker:#E17899,fg+:#616161,preview-bg:#D9D9D9,prompt:#0099BD,hl+:#719899'
> ```



The colors look good on my terminal.

<img width="880" alt="image" src="https://user-images.githubusercontent.com/700826/215013565-486ee067-c353-45a2-86d2-64da184250cd.png">

**Comment by junegunn** [comment]
Does your terminal support 24-bit colors?

https://gist.github.com/sindresorhus/bed863fb8bedf023b833c88c322e44f9

**Comment by wangmings** [comment]
I am using an iTerm2 terminal on a Mac OS
tried hl+ and couldn't add a background color to all the characters I matched

**Comment by wangmings** [comment]
Can you tell me all the color parameter names associated with fzf --color
> export FZF_DEFAULT_OPTS="--color *"
###Here's what I found, not comprehensive
```bash
fzf supports multiple color settings, and the default color settings are as follows:
fg : foreground color
bg : background color
hl : highlight foreground color
fg+: set foreground color,
bg+: set the background color of the highlight
hl+: set foreground color for highlights
query: Enter search color
gutter: sidebar color
header: title bar color
info: Information bar color
pointer: pointer color
marker: marker color
spinner: rotating load bar color
header-fg: title bar foreground color
header-bg: title bar background color
border: border color
```

**Comment by junegunn** [comment]
See man page.
