### ISSUE TITLE
Show hidden files

### ISSUE THREAD

**Issue by abrendtro** [junegunn/fzf#3150]
- [X] I have read through the manual page (`man fzf`)
- [X] I have the latest version of fzf
- [X] I have searched through the existing issues

## Info

- OS
    - [X] Linux
- Shell
    - [X] bash

## Problem / Steps to reproduce

Hidden files are not included in FZF's file list. No `$FZF_*` environment variables have been modified, except for [`FZF_DEFAULT_OPTS`](https://github.com/catppuccin/fzf)

**Comment by junegunn** [comment]
See #337.

**Comment by abrendtro** [comment]
This affected neither Vim nor Bash. I remember reading that this has to do with shell/editor integration, but either way, `FZF_DEFAULT_COMMAND` did not solve the issue

**Comment by junegunn** [comment]
See https://github.com/junegunn/fzf#environment-variables
