### ISSUE TITLE
-color is not producing colors in Terminal.app

### ISSUE THREAD

**Issue by wlonkly** [junegunn/fzf#3151]
- [X] I have read through the manual page (`man fzf`)
- [X] I have the latest version of fzf
- [X] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [X] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [X] bash
    - [ ] zsh
    - [ ] fish

## Problem / Steps to reproduce

I suspect this is an environment issue and not an `fzf` issue but I am at a loss for tracking it down and could use the help of people who know `fzf` well!

As of very recently (possibly a homebrew world upgrade), `fzf` is no longer respecting my colors, and I can't figure out why. For example, if I run

```
env fzf --color=fg:#ff0000,bg:#ffff00
```

(which you might recognize as classic Hot Dog 🌭) then I see: 

<img width="726" alt="image" src="https://user-images.githubusercontent.com/1545955/215505210-981c57de-a00c-4ceb-b163-e37f21ec76f4.png">

instead of the expected eye-searing yellow and red. That said, it's trying to do _something_, because if I use my usual color scheme:

```
export FZF_DEFAULT_OPTS="--color=fg:#ffffff,bg:#252c31,hl:#c678dd,fg+:#ffffff,bg+:#4b5263,hl+:#d858fe,info:#98c379,prompt:#61afef,pointer:#be5046,marker:#e5c07b,spinner:#61afef,header:#61afef"

fzf
```

then I get non-default colors, but not my specified colors: 

<img width="726" alt="image" src="https://user-images.githubusercontent.com/1545955/215506050-0054127d-96b6-4881-a11c-3cb5610d563b.png">

It's reproducible in ~both iterm2 and~ _(no, iTerm2 is fine, sorry)_ Terminal.app, and on fresh builds of fzf 0.20.0, 0.30.0, and 0.37.0. If I run fzf 0.20.0 on a remote Linux box in the same terminal, the colors work as normal, so I don't believe it's an issue with my terminal app.

The built-in schemes (`--color=dark`) and so on _do_ work correctly.

Help? :) Thanks!

**Comment by wlonkly** [comment]
I have another weird data point: the "Solarized" color scheme from [tinted-theming](https://github.com/tinted-theming/base16-fzf) which is supposed to look like 

![image](https://user-images.githubusercontent.com/1545955/215508256-f21dcb3a-81db-4f65-961a-2c2dd50d63c0.png)

actually looks like

<img width="726" alt="image" src="https://user-images.githubusercontent.com/1545955/215508368-d1961636-12bc-4a79-bb97-3137e590ad28.png">

I am at a loss for what's happening.

**Comment by wlonkly** [comment]
Oh no -- I was just looking at that last screenshot and thought "Hey, that's Terminal.app, not  iTerm." I was not using the expected terminal. 

My problem is not reproducible in iTerm, sigh. If it's worth figuring out what's wrong in Terminal.app, happy to help out here but otherwise I think this can be closed. Sorry about that!

**Comment by junegunn** [comment]
If I'm not mistaken terminal.app doesn't support 24-bit colors (https://github.com/termstandard/colors#not-supporting-truecolor), so `fzf --color=fg:#ff0000,bg:#ffff00` will not work as expected. But it support 256 ANSI colors fine, you can get identical colors with `fzf --color=fg:196,bg:226`

> The built-in schemes (`--color=dark`) and so on _do_ work correctly.

They use 256 ANSI colors, not 24-bit true colors.

https://github.com/junegunn/fzf/blob/f7447aece12f9b95133b803d5c4f71815bee8ca6/src/tui/tui.go#L584-L608

**Comment by wlonkly** [comment]
Ah! Appreciate the explanation, thanks.
