### ISSUE TITLE
Fuzzy completion

### ISSUE THREAD

**Issue by kdurant** [junegunn/fzf#3152]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

## Problem / Steps to reproduce
```bash
# Files under the current directory
# - You can select multiple items with TAB key
vim **<TAB>
```
I run command, but it display nothing

**Comment by junegunn** [comment]
Please follow the installation instruction: https://github.com/junegunn/fzf#installation

You probably have missed to install the completion script which is not installed by default, or you may be running into #1119.
