### ISSUE TITLE
fzf force selection of one of available options

### ISSUE THREAD

**Issue by paololazzari** [junegunn/fzf#3154]
- [✔] I have read through the manual page (`man fzf`)
- [✔ ] I have the latest version of fzf
- [ ✔] I have searched through the existing issues

## Info

- OS
    - [✔ ] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ✔] bash
    - [ ] zsh
    - [ ] fish

## Problem / Steps to reproduce

Consider the following:

```bash
arr=("foo" "bar")
printf "%s\n" "${arr[@]}" | fzf
```

this will present me with two options, `foo` and `bar`. 
However, if I enter a non-existing option, such as `foobar`, I can still press enter and fzf will close.

I would like for fzf to not exit unless one of the available options is chosen, so in this case fzf would exit only if `foo` or `bar` is selected, and not otherwise.

Something like:

```bash
arr=("foo" "bar")
printf "%s\n" "${arr[@]}" | fzf --force-selection-choice
```

**Comment by junegunn** [comment]
This will do

```sh
fzf --bind enter:accept-non-empty
```

**Comment by paololazzari** [comment]
@junegunn sure, thanks, that works, but I still think it would be useful as an option.

What if I want to force the selection of two options when using --multi?
Let's say I have:

```bash
arr=("foo" "bar" "baz")
printf "%s\n" "${arr[@]}" | fzf --multi --bind enter:accept-non-empty
```

and let's say I want to force the selection of two of those options, no more no less. If there was such a flag, I could do:

```bash
printf "%s\n" "${arr[@]}" | fzf --multi --force-selection 2
```
