### ISSUE TITLE
Returning value from preview

### ISSUE THREAD

**Issue by paololazzari** [junegunn/fzf#3155]
- [ ✓] I have read through the manual page (`man fzf`)
- [ ✓] I have the latest version of fzf
- [ ✓] I have searched through the existing issues

## Info

- OS
    - [✓ ] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [✓ ] bash
    - [ ] zsh
    - [ ] fish

## Problem / Steps to reproduce

Consider the following:

```bash
echo "abc" | fzf --preview=$'l={};new=$(echo "$l" | sed s/ab/cc/); echo "$new"'
```

how can I bind the enter key so that when I press enter, `ccc` is returned instead of `abc` ?

**Comment by junegunn** [comment]
Not sure what you're trying to achieve, but there is no such functionality.

* fzf is a filter program, data transformation should be handled by another program in the command pipeline.
  ```sh
  echo "abc" | fzf | sed s/ab/cc/
  echo "abc ccc" | fzf --with-nth 1 | awk '{print $2}'
  ```
* `--preview` wasn't really designed for the purpose.
* `--preview` works asynchronously and there's no guarantee that the final output of the preview command is ready when you hit enter.

**Comment by ycd** [comment]
Hey @junegunn, here is a more realistic scenario:


```sh
aws secretsmanager list-secrets \
--query "SecretList[*].Name" --output text | fzf --height 40% --layout=reverse \
--prompt="Select the SSM Configuration to be used: " \
--preview="aws secretsmanager get-secret-value --secret-id {} --query SecretString --output text"
``` 

It would be great to have this, but I understand your points, it should be handled by another process.

**Comment by paololazzari** [comment]
@ycd and for future readers, I found a way to achieve this:

```bash
echo "abc" | fzf --multi --bind "enter:execute(cat foo.txt)+abort" --preview=$'l={};new=$(echo "$l" | sed s/ab/cc/); echo "$new" | tee foo.txt'
```

**Comment by paololazzari** [comment]
@Daghall funny you say "DRY", since you're running the sed command twice..

**Comment by junegunn** [comment]
@Daghall You might want to replace `execute(...)+abort` with the new `become(...)` action so that the exit status of the command is preserved.

See https://github.com/junegunn/fzf#turning-into-a-different-process

@paololazzari Looks like you misread the comment.

**Comment by Daghall** [comment]
> @Daghall funny you say "DRY", since you're running the sed command twice..

@paololazzari, what I meant was storing the `sed` in a variable to make it less repetitive. 🙂

@junegunn, cool! Great improvement!

**Comment by paololazzari** [comment]
@junegunn That's awesome. I wonder if the docs should mention that the exit code is preserved? It seems to be somewhat implied but I think it would be worth mentioning, as preserving the exit code will likely be the main use case for that action

**Comment by junegunn** [comment]
> as preserving the exit code will likely be the main use case for that action

For me, it's more like a shortcut. You can see a lot of script can be simplified using `become` even when they don't care about the exit codes.

https://github.com/junegunn/fzf/commit/27018787afb398f362c6e15bcfe7a8a149c82f76
