### ISSUE TITLE
fzf-history-widget not opening

### ISSUE THREAD

**Issue by iomari** [junegunn/fzf#3156]
Greetings,
my fzf widget (ctrl-R) suddenly stopped working. It just flashes quickly.
This started yesterday after I did a system update on kubuntu 22.10 (apt update ; apt upgrade).
To resolve the issue, I've tried reinstalling zsh many times fro apt and from source and I also tried copying my configuration from another machine running the same configuration but still no luck.
I'm lost without this functionality :-).
Any help will be greatly appreciated.

**Comment by iomari** [comment]
anyone?????

**Comment by junegunn** [comment]
Please carefully read the installation instruction and follow the steps correctly.

* https://github.com/junegunn/fzf#installation

**Comment by mikob** [comment]
Had this issue. Turns out there was two binaries on my system. More details here: https://github.com/junegunn/fzf/issues/2943
