### ISSUE TITLE
[Feature Request] Group by column

### ISSUE THREAD

**Issue by qoomon** [junegunn/fzf#3158]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

## Feature Request
It would be great to have the option to group results by column like the `--with-nth` option e.g. `--group-nth`.

**Source File**
```
[groupA] element1
[groupB] element2
[groupB] element3
[groupA] element4
[groupA] element5
```

**fzf Command**
`cat source | fzf --group-nth=1 --with-nth=2..`

**Expected Output**
```
> foo
   5/5 ----------------------------
   [groupA]
     element1
     element4
     element5
   [groupB]
     element2
     element3
```

**Comment by junegunn** [comment]
This is not achievable without a significant rework of the code which I don't think is worth it, so I'm going to close this as wontfix, but pull requests are welcome.

**Comment by qoomon** [comment]
That is a pity. @junegunn However could you give me a hint in which file the display of the results is happening?

**Comment by junegunn** [comment]
terminal.go
