### ISSUE TITLE
Fuzzy cmdline completion fails in neovim

### ISSUE THREAD

**Issue by khalidchawtany** [junegunn/fzf#316]
I have installed FZF and everything works, except the [Fuzzy cmdline completion](https://github.com/junegunn/fzf/wiki/Examples-(vim)#fuzzy-cmdline-completion) example. Whenever, the shortcut is pressed the following errrors are produced:
```
Error detected while processing function GetCompletions..fzf#run..<SNR>201_execute_term..<SNR>201_split:
line   21:
E523: Not allowed here:       tabnew
Error detected while processing function GetCompletions:
line   17:
E171: Missing :endif
```

I have tried with a **minimal nvimrc**, and the same problem occurs.

**Comment by junegunn** [comment]
I didn't write the part and I haven't tried if it works. Someone added it to the wiki page before I reorganized the pages. I think I'm going to remove it as it seems too complicated as an example.

**Comment by junegunn** [comment]
Removed it, thanks.
