### ISSUE TITLE
fzf-tmux with `--color=bg:` doesn't cover the sides of the border fully

### ISSUE THREAD

**Issue by ibhagwan** [junegunn/fzf#3162]
- [X] I have read through the manual page (`man fzf`)
- [X] I have the latest version of fzf
- [X] I have searched through the existing issues

## Info

- OS
    - [X] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [X] zsh
    - [ ] fish

## Problem / Steps to reproduce

Hi again @junegunn and ty for maintaining this amazing project.

When using `fzf-tmux` in conjunction with the background color option `--color=bg:...` the right and left sides of the border within the tmux popup have a narrow border colored by the terminal `bg` color (rather than the one specified by the `--color` flag).

Example: when calling `fzf-tmux` without a background color uses the terminal `bg` color for background:

> `fzf-tmux -p80%,60%`
![image](https://user-images.githubusercontent.com/59988195/218268033-484939a2-3160-4cd6-94c7-a69a4c9ac21f.png)
> Note that the different background color in my tmux panes comes from having neovim open with a different colorscheme than the terminal one.

But when adding a background color, there are visible narrow columns to the sides of the border with the incorrect color (the terminal `bg` color):
> `fzf-tmux -p80%,60% -- --color=bg:red`
![image](https://user-images.githubusercontent.com/59988195/218268124-51655fe0-ff28-4ca5-ab5d-389f4ffd6b7b.png)

Another example when using `fzf-tmux` inside neovim where you can clearly see the issue:
![image](https://user-images.githubusercontent.com/59988195/218268345-db0f537e-9d6b-4491-833e-5ed5168d5148.png)

**Comment by junegunn** [comment]
Can't reproduce the problem.

```sh
FZF_DEFAULT_OPTS= fzf-tmux -p80%,60% --color bg:\#663300 --preview 'cat {}'
```

<img width="1471" alt="image" src="https://user-images.githubusercontent.com/700826/218299388-f184d07e-7f56-4c12-be83-fbb5a1cf0dff.png">

I'm on tmux 3.3a.

Not reproducible on Vim/Neovim either.

```vim
colo blue
call fzf#run({'window': {'width': 0.5, 'height': 0.5}, 'options': '--color bg:red'})
```

<img width="1031" alt="image" src="https://user-images.githubusercontent.com/700826/218299490-c62f6dc5-f7fc-4a8a-a3e3-47308f2e270d.png">

**Comment by ibhagwan** [comment]
> Can't reproduce the problem.

Alright let me do some more digging about the exact combo to reproduce, will keep you posted.

**Comment by ibhagwan** [comment]
Did some digging and I'm now even more confused than before.

No need for neovim, I set tmux popup background color to something visible (green) with:
```sh
tmux setw -g popup-style bg=colour2
```

I added debug output of the `tmux popup` commaind to line `fzf-tmux:212`:
```sh
echo "tmux popup -d \"$PWD\" $opt \"bash $argsf\" > /dev/null 2>&1"  # << ADDED LINE
tmux popup -d "$PWD" $opt "bash $argsf" > /dev/null 2>&1
```

Now I ran:
```sh
fzf-tmux -p50%,50% --ansi --height=100% --color=bg:red
```
And this was the result has the border issue:
![image](https://user-images.githubusercontent.com/59988195/218344724-13e4cf25-4b1c-4805-a82a-121753f762f5.png)

I then ran (almost) the same command (output by `fzf-tmux` debug print) directly and the result does not have the border issue:
![image](https://user-images.githubusercontent.com/59988195/218344840-e1674e56-f7f6-4a7a-907f-7a57e74851ac.png)

I'll keep on digging, any hints as to why this is happening only with the `fzf-tmux` script would be appreciated :-)

**Comment by ibhagwan** [comment]
Ok, I was able to find the culprit, it seems that `fzf-tmux` adds `--margin` at the sides:
https://github.com/junegunn/fzf/blob/96c3de12eb717e33b175fd01a9aaaac84ea8d6af/bin/fzf-tmux#L181-L182

Which I'm then able to override by appending `--margin=0,0` at the end of the command so I guess that solves it.

Any particular reason this is hardcoded into `fzf-tmux`?

**Comment by junegunn** [comment]
I think that's because fzf-tmux used to use the border from tmux, because back then it was not possible to create a popup without borders.

But since tmux 3.3, we're using `--border` instead, we can get rid of it. 

* https://github.com/junegunn/fzf/commit/d826f9e72f4849c43525d7196ecc7adfe3a50a9d
* https://github.com/tmux/tmux/blame/master/CHANGES#L155

**Comment by junegunn** [comment]
What do you think?

```diff
diff --git a/bin/fzf-tmux b/bin/fzf-tmux
index 44c6051..fd3258f 100755
--- a/bin/fzf-tmux
+++ b/bin/fzf-tmux
@@ -179,9 +179,10 @@ trap 'cleanup' EXIT
 
 envs="export TERM=$TERM "
 if [[ "$opt" =~ "-E" ]]; then
-  FZF_DEFAULT_OPTS="--margin 0,1 $FZF_DEFAULT_OPTS"
   tmux_version=$(tmux -V)
-  if [[ ! $tmux_version =~ 3\.2 ]]; then
+  if [[ $tmux_version =~ ^3\.2[a-z]?$ ]]; then
+    FZF_DEFAULT_OPTS="--margin 0,1 $FZF_DEFAULT_OPTS"
+  else
     FZF_DEFAULT_OPTS="--border $FZF_DEFAULT_OPTS"
     opt="-B $opt"
   fi
```

**Comment by ibhagwan** [comment]
> ```diff
> if [[ $tmux_version =~ ^3\.2[a-z]?$ ]]; then
> ```

Just tested, works great, ty @junegunn!
