### ISSUE TITLE
Feature Request, right align filename if its truncated

### ISSUE THREAD

**Issue by mangelozzi** [junegunn/fzf#3167]
- [ x] I have read through the manual page (`man fzf`)
- [ x] I have the latest version of fzf
- [ x] I have searched through the existing issues

## Info

-  Ubuntu 22.04
- Bash

## Problem / Steps to reproduce

If one has lots of long file names, I think it would be better to right align (only those long files that would be truncated). Most of time it's the end of the filename whichis of interest. If the file is short enough to fit in the window, then left align it as usual, see below (PS the preview is only 30% in my setup):

![image](https://user-images.githubusercontent.com/19764314/218460823-6fd62ced-b144-4fbc-83fc-87191e92c2a6.png)

I understand I could start typing to narrow down the list, but when its late, sometimes its nice to just arrow down and select the option.

**Comment by junegunn** [comment]
There's `--keep-right` flag you can use. Also, you might want to set up bindings for dynamically changing the size of the preview window (`change-preview-window`). e.g. https://github.com/junegunn/fzf-git.sh/blob/f36662f603095a66fd0af83409eca36b94607021/fzf-git.sh#L109

**Comment by mangelozzi** [comment]
Sorry, I missed that option, I must have been searching for the wrong phrases, thank you!

**Comment by grepsuzette** [comment]
I had also missed it. I searched for `/trunc` within `man fzf`.
