### ISSUE TITLE
Custom Fuzzy Search with Sub-commands?

### ISSUE THREAD

**Issue by AdamNSmith** [junegunn/fzf#3169]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

## Problem / Steps to reproduce
First off, great utility! FZF is such a blessing. 

I've been playing with the custom fuzzy completion options, and ran into a minor issue. Custom fuzzy completions work fine for base commands, but as far as I can tell, there's not currently a way to provide a custom fuzzy completion for specific sub-commands. This would be very useful for certain complex commands like `git`.

For example: it would be nice to have `git checkout **<TAB>` complete to a list of branches whereas `git show **<TAB>` complete to a list of commits.

I see on the README that custom fuzzy commands are experimental and changing, so it's totally understandable that this feature hasn't been implemented yet -- but would be super cool to see in the future. 

Thanks!

**Comment by junegunn** [comment]
Related: https://github.com/junegunn/fzf/issues/1518

You can access the whole command on the command line via "$@".

```sh
_fzf_complete_git() {
  echo
  echo ---
  echo "$@"
  echo ---
  echo
}
```

```
$ git add **<tab>
---
git add
---

```

Which means it is possible to write a completion function that handles different sub-commands by looking at the elements in `$@`. It's a lot of work though.

I personally recommend that you try https://github.com/junegunn/fzf-git.sh which I think is more versatile and flexible than completion.

**Comment by ebkalderon** [comment]
To any future readers: I found a solution which seems to work on `bash` but is _absurdly_ hacky. It works Use at your own risk:

```bash
# Custom completion for `git checkout **` (WARNING: Very hacky)
_fzf_complete_git() {
    if [[ "${COMP_WORDS[1]}" = checkout && "${COMP_WORDS[2]}" = "**" ]]; then
        local branches
        branches="$(git branch -vv --all)"
        _fzf_complete --reverse --multi -- "$@" < <(echo "$branches")
    else
        # Forward to standard `git` bash completion...
        _completion_loader git
        __git_wrap__git_main
        # ... and restore our FZF bash completion when done.
        complete -F _fzf_complete_git -o default -o bashdefault git
    fi
}

_fzf_complete_git_post() {
    cut -c 2- | awk '{print $1}'
}

[ -n "$BASH" ] && complete -F _fzf_complete_git -o default -o bashdefault git
```

Usage works about how you would expect:

![Screenshot from 2024-02-23 23-45-45](https://github.com/junegunn/fzf/assets/322831/8d0a2cea-4c62-4e03-a074-0f860a8f3357)

You can modify this FZF completion to be trigger-less by removing the `&& "${COMP_WORDS[2]}" = "**"` conditional check and prepending `FZF_COMPLETION_TRIGGER=''` to the `_fzf_complete` invocation.
