### ISSUE TITLE
Vim plugin installation instructions are unclear 

### ISSUE THREAD

**Issue by M0M097** [junegunn/fzf#3171]
- [ ] I have read through the manual page (`man fzf`) -> running the install script does not create a man page 
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [ ] fish

## Problem / Steps to reproduce
clone the git repo 
run install and answer all questions with y
follow the instruction in [README-VIM.md](https://github.com/junegunn/fzf/blob/master/README-VIM.md) and add `set rtp+=~/.fzf` to your `vimrc`
restart vim
type `:FZF` 
You get "Not an editor command :FZF"

**Comment by M0M097** [comment]
Vim is indeed not loading ` :scriptnames `.  I think the the issue is the following: The README-VIM.md mentions `set rtp+=~/.fzf` if I installed it fzf via git. However, after installation I have `~/.fzf.bash`  and `~/.fzf.zsh` but no `~/.fzf`

**Comment by M0M097** [comment]
Ok, copying the plugin folder from the git repository to my ~/.vim directory solved the issue. If this is necessary, it should be added to README-VIM.md

**Comment by junegunn** [comment]
Oh, I get it. The instruction assumes that you have cloned the repository on `~/.fzf` directory because that's what README.md suggests (https://github.com/junegunn/fzf#using-git). It looks like you chose another directory.
