### ISSUE TITLE
SIGINT to fzf results in exit 0 when --preview is used

### ISSUE THREAD

**Issue by rieje** [junegunn/fzf#3173]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [x] zsh

## Problem / Steps to reproduce

With the following:

    FZF_DEFAULT_COMMAND="rg --files" fzf \
      --bind "ctrl-a:select-all" \
      --bind "f12:execute-silent:($EDITOR {})" \
      --bind "change:reload:$RG_DEFAULT_COMMAND {q}" \
      --preview "rg --ignore-case --pretty --context 2 {q} {}" | cut -d":" -f1,2
    ) || exit

    "$EDITOR" "$file"

sending SIGINT (Ctrl-C) to fzf results in exit status 0, causing `$EDITOR`  to run on no selections. Removing the `--preview` argument results in non-zero exit status, exiting the script as expected.

**Comment by junegunn** [comment]
The code has an unmatched closing parenthesis.

Anyway, you're likely seeing `0` coming from `cut`, not from `fzf`. Check out `pipefail`.
