### ISSUE TITLE
For information: Windows Defender detect virus on fzf 0.38 (amd64.zip)

### ISSUE THREAD

**Issue by Warfall** [junegunn/fzf#3174]
- [x ] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x ] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [ ] Mac OS X
    - [x ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [ ] fish
    - [X] WIN64/CMD

## Problem / Steps to reproduce

Hello,

Windows Defender (Windows 10 pro x64 build 19045.2604, this is really a fresh release: yesterday) detect the following virus: 

https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?name=Trojan%3aWin32%2fWacatac.H!ml&threatid=2147814523&enterprise=0

in file:
https://github.com/junegunn/fzf/releases/download/0.38.0/fzf-0.38.0-windows_amd64.zip

This file being checked as correct SHA256 signature comparing with the one fzf provides itself:
https://github.com/junegunn/fzf/releases/download/0.38.0/fzf_0.38.0_checksums.txt

Virus Total also complains about:
https://github.com/junegunn/fzf/releases/download/0.38.0/fzf-0.38.0-windows_amd64.zip

Virus total URL:
https://www.virustotal.com/gui/file/32804b243e117dbf1b317fdd32f24c23c047642a394fa9ac7dabf50540dbb759

To complete information: Windows Defender is happy with the 0.37 (and below) release of fzf.

Would you mind to take corrective action as soon as possible?

Thank you

**Comment by Warfall** [comment]
Complement: probably false positive.

Jotti also complains:
https://virusscan.jotti.org/en-US/filescanjob/czfoem09oe

but like for Virus Total, it is only 'Ikarus' anti-virus doing so, all other anti-virus being ok with fzf 0.38.

The file (fzf 0.38 windows/amd64) is already sent to Microsoft (www.microsoft.com/en-us/wdsi), in hope Microsoft can modify the detection.

**Comment by rashil2000** [comment]
I installed the latest release some days ago but Defender quarantined fzf today, so this is still getting flagged. 

I wonder what triggered Defender when it says "This program executes commands from an attacker". Does it have anything to do with the new `become` action (even though it doesn't work on Windows) or the `--listen` feature from the previous release?

**Comment by junegunn** [comment]
It's most likely a false positive. See

* https://github.com/junegunn/fzf/search?q=defender&type=issues
* https://go.dev/doc/faq#virus

**Comment by rashil2000** [comment]
Yes yes, that's my belief too :) 

I was just wondering what caused it to flag _now_ - I've been using fzf since ages...

**Comment by thisismygitrepo** [comment]
I just downloaded it again, and it was not caught. :/
