### ISSUE TITLE
Typing across the right border stops fuzzy matching

### ISSUE THREAD

**Issue by ibhagwan** [junegunn/fzf#3176]
- [X] I have read through the manual page (`man fzf`)
- [X] I have the latest version of fzf
- [X] I have searched through the existing issues

## Info

- OS
    - [X] Linux
    - [X] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [X] zsh
    - [ ] fish

## Problem / Steps to reproduce

When typing characters across the right border (with or without preview) and then deleting said characters causes fzf to stop displaying results.

Notes:
- May or may not be related to `--info=inline`
- Using `ctrl-u` to clear the prompt solves the issue

![Peek 2023-02-17 10-09](https://user-images.githubusercontent.com/59988195/219745492-aabda4bc-25c7-45df-b871-1d38b4b086e8.gif)

**Comment by junegunn** [comment]
Thanks for the report. The problem here is the horizontal scrolling offset isn't properly updated so the query string before the cursor is left hidden. That's why CTRL-U, or equivalently, holding down backspace long enough will clear the hidden part. You'll also see CTRL-A will reveal the hidden part of the query.

**Comment by ibhagwan** [comment]
> Thanks for the report. The problem here is the horizontal scrolling offset isn't properly updated so the query string before the cursor is left hidden. That's why CTRL-U, or equivalently, holding down backspace long enough will clear the hidden part. You'll also see left key or CTRL-A will reveal the hidden part of the query.

Ty for the explanation :)

**Comment by TroySigX** [comment]
It still hasn't fixed to problem.

**Comment by ibhagwan** [comment]
> It still hasn't fixed to problem.

I don’t think this was released yet, did you compile fzf from source to test this?

**Comment by TroySigX** [comment]
Yes.

**Comment by junegunn** [comment]
It is working as expected. Please make sure your system is picking up the right binary when testing it.

**Comment by TroySigX** [comment]
I use packer nvim to update the package, and I'm sure that packer has already download the latest commit, still it doesn't work.

**Comment by junegunn** [comment]
I'm not familiar with packer, but I don't think it will build fzf binary from the source.

**Comment by TroySigX** [comment]
I recently switched to lazy.nvim, and I'm using the main branch of fzf, but the bug still persists.

**Comment by TroySigX** [comment]
If it helps, my kernel is 6.1.12-arch1

**Comment by ibhagwan** [comment]
@TroySigX, these are neovim plug-in managers, they download ready made binaries, not compile from source, monitor [fzf releases](https://github.com/junegunn/fzf/releases) for a new binary release, then update with whatever package manager you use, run `fzf --version` and check that your version > 0.38, it will then be solved (not possible ATM without compiling from source).
