### ISSUE TITLE
Question: How can I search the hidden file in Windows pwsh.

### ISSUE THREAD

**Issue by hungpham3112** [junegunn/fzf#3179]
## Info

- OS
    - [ ] Linux
    - [ ] Mac OS X
    - [X] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [ ] fish
    - [X] pwsh

## Problem / Steps to reproduce

1.Download fzf and fzf.vim with
```
Plug 'https://github.com/junegunn/fzf.git', { 'dir': '~/.fzf', 'do': { -> fzf#install() } }
Plug 'https://github.com/junegunn/fzf.vim.git'
```
2. Use fzf in pwsh(7.1) with dot directories(e.g `.julia`) and not see the result.
3. Use :FZF in vim with dot directories and not see the expected result.

**Comment by junegunn** [comment]
Hidden files are included by default since 0.47.0.

https://github.com/junegunn/fzf/blob/master/CHANGELOG.md#0470
