### ISSUE TITLE
Is it possible to add a shortcut for `cd **Tab`?

### ISSUE THREAD

**Issue by zhangchiqing** [junegunn/fzf#319]
Great tool first! Love it.

I want to use `cc` as `cd **Tab`, and search for a folder. And as soon as I hit "Enter", I can go into the folder directly instead of completing `cd <fildername>` first, and press another "Enter" to cd that folder. 

Is it possible to do?

**Comment by junegunn** [comment]
You can try something like this:
```sh
cc() {
  local dir=$(
    find . -path '*/\.*' -prune -o -type d -print |
    sed '1d;s/^..//' | fzf-tmux +m) && cd "$dir"
}
```

**Comment by zhangchiqing** [comment]
Awesome! Thanks @junegunn
