### ISSUE TITLE
Disable popup option if tmux is too old aka doesn't support popup.

### ISSUE THREAD

**Issue by SamuelLarkin** [junegunn/fzf#3198]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

## Problem / Steps to reproduce

I'm using `tmux`-3.1, `fzf`, `fzf-tmux`, fzf-git.sh.  I configured `FZF_TMUX_OPTS='-p80%,60%'` but since `tmux` does  not support popup in 3.1 it hangs the terminal.  `fzf-tmux` should only offer `-p` if `tmux` supports popup otherwise it should either warn about it or silently disable popup.  As a temporary solution, which user shouldn't have to implement, I have a conditional define in by `~/.bashrc`
```
{ man tmux | grep display-popup; } &> /dev/null && export FZF_TMUX_OPTS='-p80%,60%'
```

**Comment by junegunn** [comment]
Thanks for the suggestion.
