### ISSUE TITLE
fzf causing shell to hang before displaying red prompt

### ISSUE THREAD

**Issue by jkemp814** [junegunn/fzf#3206]
- [+] I have read through the manual page (`man fzf`)
- [+] I have the latest version of fzf
- [+] I have searched through the existing issues

## Info

- OS
    - [+] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [+] bash
    - [+] zsh
    - [ ] fish

## Problem / Steps to reproduce
Shell hangs before displaying red prompt in ZSH. Simply launch a terminal. While ZSH is sourcing all the lines, it finanly finishes but the prompt is red.

When I comment out this line: `[ -f ~/.fzf.sh ] && source ~/.fzf.sh` the shell loads as normal, but complains it cannot find the plugin.

When I change the commented out line to: `[[ ! -f ~/.fzf.zsh ]] || source ~/.fzf.zsh` it loads fine.

That first line was added by the installation script.

**Comment by junegunn** [comment]
> That first line was added by the installation script.

No. The file extension is invalid. It should be either `.bash` or `.zsh`

https://github.com/junegunn/fzf/blob/1116e481bef4f63abe0e506ce20469e244c505e6/install#L9

https://github.com/junegunn/fzf/blob/1116e481bef4f63abe0e506ce20469e244c505e6/install#L349-L353

**Comment by jkemp814** [comment]
Hmmm. Why would it add the .sh extension? I did not add that. Thank you for the quick follow up.

**Comment by junegunn** [comment]
There is no possibility that the exact line was added by the install script.
