### ISSUE TITLE
Preview window “wraps” line ending with ANSI color code by adding an extra blank line

### ISSUE THREAD

**Issue by vejkse** [junegunn/fzf#3209]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

## Problem / Steps to reproduce
If I execute
```bash
echo | fzf --preview-window wrap --preview 'printf $"\e[7m%s\e[0m" title; printf "─%.0s" $(seq 1 "$((FZF_PREVIEW_COLUMNS - 5))"); echo; echo something'
```
I get first ‘title’ in inverse colours, then an horizontal line that exactly fills the rest of the preview width.  As expected, on the immediate next line is the content ‘something’.

If I reverse the order of the `printf` statements, so that the ANSI colour code is at the end, an unwanted empty line appears between the “title” row and the “content” row.  This happens only when wrapping.
```bash
echo | fzf --preview-window wrap --preview 'printf "─%.0s" $(seq 1 "$((FZF_PREVIEW_COLUMNS - 5))"); printf $"\e[7m%s\e[0m" title; echo; echo something'
```

This seems to be somewhat the reverse of issue #2346, so maybe it was introduced when solving the latter.

**Comment by junegunn** [comment]
Thanks for the report. It should be fixed. Let me know if you see any other problems. Thanks.
