### ISSUE TITLE
Can't remove `bold` from several color names when using `bw` base scheme

### ISSUE THREAD

**Issue by kotfu** [junegunn/fzf#3222]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

## Problem / Steps to reproduce
When you use `bw` as the base scheme, there are several color names that you can't remove the `bold` ansi attribute from.

I have checked my environment variables, and `FZF_DEFAULT_OPTS` is not set. Reproduced on macos 13.2.1 using fzf 0.38.0 installed via homebrew. I have replicated the issue using both `iTerm.app` and `Terminal.app` as terminal emulators.

```
$ echo "line one\nline two\nline three" | fzf --color='bw,query:regular,fg+:red:regular,hl+:green:regular'
```
At the query prompt, type `li`.

I observe that the bold attribute is still applied to the query, the text of the current line (`fg+`), and the highlight on the current line (`hl+`) as shown here in iTerm:
<img width="320" alt="iTerm.app" src="https://user-images.githubusercontent.com/218536/227725669-ee2f8c5a-92c3-42ad-aa56-9bb0fd5698de.png">

and here in Terminal:
<img width="320" alt="Terminal.app" src="https://user-images.githubusercontent.com/218536/227726199-12405b09-b0a4-4d82-9973-92d8a06d38f6.png">

I also observe that by changing the base scheme to `dark`, or omitting the specification of the base scheme from the `--color` specification, thereby causing `fzf` to use the default of `dark` on my true color terminal, that the `regular` ansi attribute appears to work properly, ie it disables bold.

**Comment by junegunn** [comment]
Thanks for the report. An easy workaround at the moment is to use `--no-bold` option, which prevents "boldification" of any element.

```sh
fzf --color=bw --no-bold
```

https://github.com/junegunn/fzf/blob/d7daf5f72411f29eca3ab398c7a8a951ca230cad/src/options.go#L2002-L2019
