### ISSUE TITLE
Fish shell: The placeholder {} does not escape backslashes

### ISSUE THREAD

**Issue by Korkman** [junegunn/fzf#3224]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [x] Mac OS X
- Shell
    - [x] fish

## Problem / Steps to reproduce

```
echo "test\\" | fzf --preview 'echo {} | less'
```

This effectively produces something along

```
echo 'test\' | less
```

fish supports escaping single quotes, the other shells don't. Therefore, fish exits with

> Unexpected end of string, quotes are not balanced

Unfortunately this means backslashes have to be escaped for fish only (unless other shells are known to support backslash escapes in single quotes).

**Comment by junegunn** [comment]
I tried to fix the issue by applying a different escaping rule when `$SHELL` is set to fish. Let me know if it doesn't help.
