### ISSUE TITLE
Customise info line

### ISSUE THREAD

**Issue by supercrabtree** [junegunn/fzf#323]
Hi June,

I've written quite a few scripts that use fzf, and I often use the --expect and --bind options. As much as I try and use mnemonics it's often hard to remember them all. Is it possible to add an --info option, so that I could write notes to myself that would appear after the numbers in the info bar?

Thanks for fzf, it's awesome!

**Comment by junegunn** [comment]
You might want to check out `--header-lines` and `--header-file` (they are mutually exclusive)

**Comment by supercrabtree** [comment]
Worked perfectly, thanks :)
