### ISSUE TITLE
[Feature Request] Option to allow new entry (i.e. not present in input)

### ISSUE THREAD

**Issue by SpaceshipOperations** [junegunn/fzf#3232]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

## Problem / Steps to reproduce

I would like to use FZF to allow the user to choose an item from a menu, but if the item does not exist, then allow the user to enter a new item manually. It'd be nice to have a CLI option (e.g. `--allow-new`) to allow the user to enter arbitrary text, not present in the input, and have FZF return it.

It's easy to work around the lack of this feature by having some placeholder item, then if the placeholder item is returned by FZF, prompting the user after FZF enter arbitrary text using some other tool. But I feel that it would make an excellent addition to FZF, both providing a more consistent user experience to the end user and making developers' (of apps that use FZF) lives easier. The lack of this feature necessitates extra flow control outside of FZF for going back and forth between the two modes (selecting from existing entries using FZF vs adding a new entry with some other tool).

My idea of returning new text is that the user simply types the new value in the same search box and presses enter. This capability would be enabled by a command line option like `--allow-new`. However, when enabled this way, it would conflict with certain existing capabilities (e.g. the whole `--tiebreak` part), and therefore enabling this option would implicitly disable them.

As such, it might be desirable for some people to have an alternate mode for entering the arbitrary text. e.g. Offering some shortcut like `Ctrl-X` which would make FZF display a dialog for entering an arbitrary value, which would also guarantee that new values (which might imply creation) are not returned by accident. For me personally, the first method is preferred over this one, but it really works either way.

A few more ideas would be constraining what arbitrary input is allowed, e.g. by matching it against a regular expression or piping it to an arbitrary command and allowing or forbidding it based on that command's exit code. However, those are just some extra ideas for the future and the feature could totally be implemented without them at first.

Thank you in advance.

**Comment by junegunn** [comment]
Sounds like you're looking for `--print-query`.

> e.g. by matching it against a regular expression or piping it to an arbitrary command and allowing or forbidding it based on that command's exit code.

That is already possible with existing options. See https://github.com/junegunn/fzf/blob/master/CHANGELOG.md#0360

**Comment by SpaceshipOperations** [comment]
Oh, not sure how I missed these. Thank you for the answer!

**Comment by Quicksilver151** [comment]
how would i go about allowing the 'new query' to display something in preview?

**Comment by skepticspriggan** [comment]
In case you _only_ want the `new query` or `existing item without query`, you can get the last line using `fzf --print-query | tail -1`.
