### ISSUE TITLE
fzf-tmux -p not working on tmux 3.3a-3

### ISSUE THREAD

**Issue by ConnorWay32** [junegunn/fzf#3235]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

## Problem / Steps to reproduce
After upgrading to fzf 0.39.0, the command `fzf-tmux -p` gives the following error message.
```
/usr/bin/fzf-tmux: line 183: bc: command not found
fzf-tmux: tmux 3.2 or above is required for popup mode
```

`tmux -V` gives `tmux 3.3a`, so there shouldn't be an issue with my tmux version.

**Comment by junegunn** [comment]
I assumed `bc` is installed on most systems by default, but it looks like I was wrong.

**Comment by junegunn** [comment]
Please test if f1a9629 fixes your problem.

**Comment by junegunn** [comment]
Thanks for confirmation. Maybe we should try with awk first? What do you think?

**Comment by ConnorWay32** [comment]
Given that awk is a coreutil I think it would be generally safer to assume that people have it than bc. What was the reasoning behind the use of bc? I'm not particularly well-versed on either choice so I wouldn't be able to say which is the better one.

**Comment by junegunn** [comment]
> What was the reasoning behind the use of bc?

Because it's usually the go-to choice for arithmetic operations. But what we're doing here is very simple, and awk is capable of doing it. I'll think about it. Thanks.
