### ISSUE TITLE
feature request: change-header action

### ISSUE THREAD

**Issue by DanielFGray** [junegunn/fzf#3237]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [x] Mac OS X
    - [x] Windows
    - [x] Etc.
- Shell
    - [x] bash
    - [x] zsh
    - [x] fish

## Problem / Steps to reproduce

we have actions to `change-preview()` and `change-query()` but it would also be great to have a `change-header()` action (especially with the new `--listen` option)

**Comment by junegunn** [comment]
What's the use case? `--header-lines` and `reload` can be used in some cases.

```sh
(date; ps -ef) | fzf --header-lines 1 --bind 'space:reload:date; ps -ef'
```

**Comment by DanielFGray** [comment]
for example, i have a music player script, where i show the current playlist, and then in the header the current playing song

using `--listen` i could subscribe to changes to the playlist and update that using `reload` and when the current song changes, id like to update the header, but those require separate subscriptions from the media player and are updated in separate events
