### ISSUE TITLE
feature request: field expressions in preview labels (and text alignment)

### ISSUE THREAD

**Issue by DanielFGray** [junegunn/fzf#3238]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [x] Mac OS X
    - [x] Windows
    - [x] Etc.
- Shell
    - [x] bash
    - [x] zsh
    - [x] fish

## Problem / Steps to reproduce
preview labels are a great feature, it would also be great to have it parsed for field expressions, eg
```
--preview='cat {+}' --preview-label='cat {+}'
```
---
 separately (and forgive me for not filing a separate issue) it would also be nice to optionally left/right align the preview label, eg `--preview-label-pos='top,right'` or `--preview-label-pos='bottom,left'`

**Comment by junegunn** [comment]
```sh
fzf --multi --preview 'cat {}' --bind 'focus:transform-preview-label:echo {+}'
```

> left/right align the preview label

> --preview-label-pos[=N[:top|bottom]]
>    Position of the border label on the border line of the preview window. Specify a positive integer as the column position from the left. Specify a negative integer to right-align the label. Label is printed on the top border line by default, add :bottom to put it on the border line on the bottom. The default value 0 (or center) will put the label at the center of the border line.


```sh
fzf --multi --preview 'cat {}' --bind 'focus:transform-preview-label:echo {+}' --preview-label-pos top,2

fzf --multi --preview 'cat {}' --bind 'focus:transform-preview-label:echo {+}' --preview-label-pos top,-2
```
