### ISSUE TITLE
fzf outputs marker display width should be up to 2

### ISSUE THREAD

**Issue by zolrath** [junegunn/fzf#3239]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux (via WSL2 on Windows)
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [x] fish

## Problem / Steps to reproduce

When attemping to run `fzf` it has begun outputting `marker display width should be up to 2`. 
I've checked my default options and they set `--marker="*"`, so I tried removing the default marker setting and the message was still output.

I've tried with both fish and bash to check if it was an issue with my shell configuration but the same issue occurs in both shells.
This is running on Ubuntu 22.04.2 LTS through WSL2 on Windows, and has worked in the past.

The error occurred both on 0.29.0 via apt as well as the latest version installed from GitHub.

```bash
$ fzf --version
0.39.0 (2023040)

$ fzf
marker display width should be up to 2

$ fzf --marker=">"
marker display width should be up to 2
```

Thank you very much for the project, no faster way to appreciate something than having it not work!

## Solution??
By running `fzf --marker ">"` a single time, I can now run fzf again.
It now works, even without supplying a `--marker` option, so it seems that fzf got into a weird state and was unable to recover on its own.

**Comment by junegunn** [comment]
> fzf got into a weird state 

fzf is stateless. It's probably caused by your FZF_DEFAULT_OPTS.
