### ISSUE TITLE
FZF doesn't work. It doesn't open any file

### ISSUE THREAD

**Issue by gianarb** [junegunn/fzf#324]
Hi! This is my first experience with FZF and I known it because I'm migrating my [dotfiles](https://github.com/gianarb/dotfiles/pull/5) to neovim. I'm working to use this tool with neovim but it doesn't work.

I installed it with Plug.
```vim
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': 'yes \| ./install' }
Plug 'junegunn/fzf.vim'
```
> https://github.com/gianarb/dotfiles/blob/feature/neovim-migration/nvimrc#L12-L13

In vim after `:FZF` I search the file and I press `ENTER` but won't open nothing.

Into the terminal the problem is in this screenshot.
![zfzissue](https://cloud.githubusercontent.com/assets/1630267/9423381/e453f072-48c1-11e5-9dfe-6e7e20638e2e.png)
After `ENTER` it prints the path of searched file.

Thanks for your feedback! :)

**Comment by junegunn** [comment]
Cannot reproduce with your nvimrc. `:FZF` works just fine. The terminal emulator of neovim is known to have issues; see https://github.com/junegunn/fzf/labels/neovim. Maybe you're running into the problem and upgrading neovim to the latest might help, but I'm not sure.

> Into the terminal the problem is in this screenshot.
> After ENTER it prints the path of searched file.

It's the expected behavior. fzf is just a filter, like grep, it doesn't take any action instead it just prints the selected lines.

**Comment by gianarb** [comment]
Perfetct! :) THanks for your feedback! I close this issue :)

**Comment by junegunn** [comment]
So upgrading neovim solved the issue?

**Comment by gianarb** [comment]
I installed neovim from github repo yesterday.. There are 5 new commits I'm compiling them :)

**Comment by junegunn** [comment]
Hmm, I have much older version of neovim than you, so I don't think those 5 commits will solve the problem. You might want to check if the `:FZF` command (and the other commands from `fzf.vim` repo) work on plain Vim.

**Comment by gianarb** [comment]
mmm this is magic.. but into the last 5 commits of neovim there is the resolution of my problem o.O..

It works! o.O

**Comment by junegunn** [comment]
Ha!
/cc @tarruda @justinmk

**Comment by tarruda** [comment]
This bug was introduced and fixed yesterday, you got unlucky and cloned between the bug/fix :smile:

**Comment by gianarb** [comment]
I'm very lucky!
