### ISSUE TITLE
How can I get fzf to be "repeat" friendly (replay from history)

### ISSUE THREAD

**Issue by benlieb** [junegunn/fzf#3245]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

I did search the docs but couldn't figure this out. 

If I want to open multiple files into tabs for vim I can do this for example: `vim -p $(fzf -m)`. This works GREAT!

However when I go back through my command history I just see `v -p $(fzf -m)` and so I can't really "repeat" the command in the future. It would be really helpful if I could some how access the actual command that was run when exiting `fzf` in my history. 

Is this feasible? Is this built in already?

Thank you!

**Comment by junegunn** [comment]
That is not possible. Instead, I recommend that you use CTRL-T binding or fuzzy completion.

* https://github.com/junegunn/fzf#key-bindings-for-command-line
* https://github.com/junegunn/fzf#fuzzy-completion-for-bash-and-zsh

They will put selected paths to your command line, and you press enter, so the full command will be registered to your command history.

**Comment by benlieb** [comment]
Too bad. Wouldn't it be theoretically possible for fzf to write to the shell history file?

**Comment by junegunn** [comment]
I don't know. Even if it's possible, not everyone would want the behavior.
