### ISSUE TITLE
Allow hiding of line numbers in preview

### ISSUE THREAD

**Issue by Araaha** [junegunn/fzf#3253]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

## Problem / Steps to reproduce

I have the following opts in my zshrc:

``
export FZF_CTRL_T_OPTS='--preview-window 'up,50%' --preview "bat --wrap=auto --style=plain --color=always --line-range=1:15 {} "'

export FZF_CTRL_T_COMMAND="rg --files --hidden  --follow --no-messages --no-ignore"

export FZF_DEFAULT_COMMAND="rg --files --hidden --follow --no-messages --no-ignore"

export FZF_DEFAULT_OPTS="--no-scrollbar --border=bold --no-separator  --padding 0% --margin 0% --multi --reverse --preview-window=border-none --height=50% color=bg+:-1,spinner:#fb4934,hl:#928374:bold,fg:#8abeb7,header:#928374,info:#8ec07c,pointer:#fb4934,marker:#fb4934,fg+:regular:reverse:#83a598,prompt:#9cd365,hl+:reverse:reverse:#83a598,gutter:-1,query:regular,border:#87afaf
	--bind home:first --bind end:last --bind ctrl-d:abort --bind ctrl-p:abort"
``

In the preview, I see the following line number range: 
![2023-04-15-19:17:12-screenshot](https://user-images.githubusercontent.com/76860315/232257905-c44ee34f-c89c-498e-b605-0b3ef3ab3c6c.png)

I was wondering if it was possible to remove this from the preview.

**Comment by junegunn** [comment]
No, it's not possible.
