### ISSUE TITLE
[Feature Request] -T option to set the format for the popup title for fzf-tmux

### ISSUE THREAD

**Issue by sei40kr** [junegunn/fzf#3262]
I want `-T` option for fzf-tmux that sets the format for the popup title.

https://man7.org/linux/man-pages/man1/tmux.1.html
> display-popup [-BCE] [-b border-lines] [-c target-client] [-d
> ...
> -T is a format for the popup title (see FORMATS).

**Comment by junegunn** [comment]
Can you explain why you want to set it? What is the benefit of setting the title?
