### ISSUE TITLE
[Feature] Allow coloring of each item 

### ISSUE THREAD

**Issue by mcint** [junegunn/fzf#3264]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

#3153, at least, seems like it could be helped by this request

## Problem / Steps to reproduce
I would like to use fzf as a color picker, for shell and tmux. I have successfully used it, with the `--preview` option, but I would like to be able to see different colors without having to select each in turn.

I think my wish would require a `--list-preview` or `--item-format` flag, which processes the option like `--preview` does. I would just like to output some ANSI color codes.

```
$ echo -e "\e[3"{0..7}"mcolors\n" | fzf  --reverse --height 20%
```
```
$ echo -e "\e[3"{0..7}"mcolors\n"
```

It would be nice to use this facility in other cases as well. For example, looking through newline-delimited JSON log lines, it would be nice to color the messages by severity, or by service.

In general, I think there are many uses that make styling of text in fzf's list/selection view worth some pursuit.

**Comment by damnskippy** [comment]
Maybe --ansi  option is what you're looking for?
