### ISSUE TITLE
How to use both the completions and key-binding files when they cannot both be renamed to fzf.bash?

### ISSUE THREAD

**Issue by eggbean** [junegunn/fzf#3265]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [x] zsh
    - [ ] fish

## Problem / Steps to reproduce
I install fzf and other binaries using stow, not in the way suggested in the docs.
When file completion files are placed in `/usr/local/share/bash-completion/completions/` they need to be named after the command, as they are only loaded once the command is used (I think this is called lazy-loading). Because they are two files, they cannot both have the same name `fzf.bash`, so I source them directly from `.bashrc`.

Now I am translating my bash configuration to zsh and I am faced with the same problem again and would like to know what the intended way to use these files is. How can I rename them so that I can use them both and have the lazy loading work, and not have to directly source them?

**Comment by junegunn** [comment]
> lazy-loading

I'm not familiar with the exact mechanism, but I doubt that it will work well with the fuzzy completion we provide.

The completion file this repository provides is not for "fzf" itself, but for other commands, for example `kill **<tab>` or `vim **<tab>`. Will lazy loading mechanism decide to load `fzf.bash` when the command is not `fzf` but `kill` or `vim`? I doubt it.

**Comment by eggbean** [comment]
I see. So the solution with zsh is probably to directly source the files through `.zshrc` just like I do with bash, although I am not sure if lazy loading is the default in zsh like it is with bash when using locations other than the legacy `/etc/bash_completion.d/` directory.
