### ISSUE TITLE
dirname returning incorrect value within the execute(...) command

### ISSUE THREAD

**Issue by Dyredhead** [junegunn/fzf#3267]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

## Problem / Steps to reproduce
I have this fzf function with which I want to be able cd into the parent directory of the accepted file. 
```bash
 function cdf() {
     export FZF_DEFAULT_COMMAND="fd --hidden --type f"
 
      fzf  \
      --bind "enter:execute[cd $(dirname {})]" \
      --bind "alt-enter:execute[xdg-open $(dirname {})]" \
      --preview "bat --color=always --style=numbers --line-range=:500 {}" \
      --query "$1"
 }
```
For some reason pressing enter or alt-enter is failing to work. I might not be understanding how to nest commands inside of execute(...) correctly, and if there is a resource I can consult, please let me know. I have tried replacing $(...) with pipes instead, but that is also not working. Any help is appreciated.

**Comment by junegunn** [comment]
Use single quotes around the bind arguments so that `$(...)` are not evaluated immediately when you run the command.

i.e. `--bind 'enter:...'`

**Comment by Dyredhead** [comment]
That worked, thank you!
