### ISSUE TITLE
Ability to disable rendering CR in the preview

### ISSUE THREAD

**Issue by LangLangBart** [junegunn/fzf#3269]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] macOS
- Shell
    - [x] zsh

## Problem / Steps to reproduce
- since version [0.39.0](https://github.com/junegunn/fzf/releases/tag/0.39.0) carriage returns/ line feed character are rendered as ␍/␊
- when running the following commands, the carriage return characters are visible in the preview

```sh
# minimal setup
fzf --preview 'echo "\r\n\r\n"'

# there is nothing special about #1221, it is just a demo
fzf --preview "gh api repos/junegunn/fzf/issues/1221 --jq '.body'"

```

- see image below for more clarity

<img src="https://raw.githubusercontent.com/LangLangbart/ImagePool/91c85a2ef8ff3416f0df8f4e5881ee79ac2759f6/storage/2023-04-30_02-29-51_fzf_0.39.0.png" width="800">

### expected behavior
- not to render in the preview or the possibility to disable the rendering of these characters

### related ticket/commit
- ticket: #2529
- commit: d7daf5f72411f29eca3ab398c7a8a951ca230cad

**Comment by junegunn** [comment]
Interesting, old issues don't seem to have carriage returns. They are showing since #726.

```sh
seq 700 800 | fzf --preview "gh api repos/junegunn/fzf/issues/{} --jq '.body'"
```

**Comment by junegunn** [comment]
I'd like to avoid adding an option just for this. How about if you remove the trailing CRs only? Do you have issues also with non-trailing CRs?

**Comment by LangLangBart** [comment]
> Interesting, old issues don't seem to have carriage returns. They are showing since #726.
> 
> ```shell
> seq 700 800 | fzf --preview "gh api repos/junegunn/fzf/issues/{} --jq '.body'"
> ```

This ticket was written with `gh` from the command line and also does not have this problem, since all my other tickets were made in this repo through the web interface, the problem is reproducible there as well.

```sh
gh api repos/junegunn/fzf/issues/725 --jq '{body: .body[0:150], Date: .created_at}'

{
  "Date": "2016-10-29T19:47:53Z",
  "body": "<!-- Check all that apply [x] -->\n- Category\n  - [x] fzf binary\n  - [ ] fzf-tmux script\n  - [x] Key bindings\n  - [x] Completion\n  - [ ] Vim\n  - [ ] Ne"
}
gh api repos/junegunn/fzf/issues/726 --jq '{body: .body[0:150], Date: .created_at}'

{
  "Date": "2016-10-31T09:02:06Z",
  "body": "<!-- Check all that apply [x] -->\r\n- Category\r\n    - [ ] fzf binary\r\n    - [ ] fzf-tmux script\r\n    - [ ] Key bindings\r\n    - [ ] Completion\r\n    - [ "
}
gh api repos/junegunn/fzf/issues/3269 --jq '{body: .body[0:150], Date: .created_at}'

{
  "Date": "2023-04-30T00:33:09Z",
  "body": "<!-- ISSUES NOT FOLLOWING THIS TEMPLATE WILL BE CLOSED AND DELETED -->\n\n<!-- Check all that apply [x] -->\n\n- [x] I have read through the manual page ("
}
```

- related: [Stackoverflow - What is the difference between \r\n, \r, and \n? [duplicate]](https://stackoverflow.com/questions/15433188/what-is-the-difference-between-r-n-r-and-n)
```sh
\r = CR (Carriage Return) → Used as a new line character in Mac OS before X
\n = LF (Line Feed) → Used as a new line character in Unix/Mac OS X
\r\n = CR + LF → Used as a new line character in Windows
```

---

> I'd like to avoid adding an option just for this. How about if you remove the trailing CRs only? Do you have issues also with non-trailing CRs?

Tested the latest version `0.39.0 (88d812fe)` and the carriage returns (␍) are not rendered anymore, it looks like in `0.38.0`. Thanks for the quick solution.
