### ISSUE TITLE
get E315 error while open a file from the quick fix window

### ISSUE THREAD

**Issue by ycavatars** [junegunn/fzf#327]
Sometimes I get E315 error when I use `:FZF -m -x` to open a quick fix window to search file. I also install the fzf.vim so I use <c-t> to open files in new tab. I try to reproduce with the following steps:

1. search files using fzf and use <c-t> to open each file into new tab
2. switch to any one of the new tabs
3. use fzf to search file again, but use *enter* to open the file (in the attach image, I opened `Button.js`) in the current tab
4. *Part of* the `Button.js` are shown in the screen, and the content of the step 2 are also in the screen (previous file block).
5. There're also an error code: `E315: ml_get: invalid lnum: 21`.

![fzf](https://cloud.githubusercontent.com/assets/1477617/9483862/5d6f9584-4bd7-11e5-9ff9-6dacd761edaf.jpg)

Is there any idea to fix the problems? Thanks.

**Comment by junegunn** [comment]
It's a known bug of neovim, see https://github.com/junegunn/fzf/labels/neovim

**Comment by ycavatars** [comment]
thanks for the quick reply :)
