### ISSUE TITLE
fzf-completion:15: parse error: condition expected

### ISSUE THREAD

**Issue by slonka** [junegunn/fzf#328]
When I type "cd " and press tab i get:

fzf-completion:15: parse error: condition expected: =
fzf-completion:19: parse error: condition expected: =

I just did a pull in ".fzf" directory and my version is 8fb31e1b4d25ef20d039e919e8d7712d2ad6a96c

I'm on OSX 10.10.3

**Comment by junegunn** [comment]
Which shell?

**Comment by slonka** [comment]
zsh

**Comment by junegunn** [comment]
Can't reproduce on my machine, are you running the latest zsh?

**Comment by slonka** [comment]
zsh --version                                                                                                                                                                                                                           
zsh 5.0.8 (x86_64-apple-darwin14.4.0)

oh-my-zsh: 192de6bcffb0294e19f4203f6f7dc1a7f3e427be

**Comment by junegunn** [comment]
Hmm, I also have the exact same version of zsh. Since I use bash, my zshrc is pretty minimal and the problem is not reproducible with it.

```zsh
# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
```

Do you have any clue what might cause this? It's probably something in your config.

**Comment by danieljl** [comment]
I had the same problem. The problem arose because of `setopt shwordsplit` in my .zshrc. After I deleted that option, the problem's gone. I think fzf should handle it when zsh using `setopt shwordsplit` option.

**Comment by junegunn** [comment]
@danieljl Thanks for the hint. I'll give a look.

**Comment by junegunn** [comment]
@danieljl The reported error is not reproducible for me but I have a different problem when `shwordsplit` is set: `vim **<TAB>` expands to `vimREADME.md `. So I fixed it anyway.

@slonka Please update and see if your problem is resolved.

**Comment by slonka** [comment]
@junegunn The problem is not resolved. My config (i replaced my home path with ~):

```
export ZSH=~/.oh-my-zsh

ZSH_THEME="ys"

plugins=(git git-extras gitfast gitignore)

source $ZSH/oh-my-zsh.sh

if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vim'
else
  export EDITOR='mvim'
fi

export SSH_KEY_PATH="~/.ssh/dsa_id"

alias zshconfig="vim ~/.zshrc"
alias ohmyzsh="vim ~/.oh-my-zsh"

bindkey -v

bindkey '^P' up-history
bindkey '^N' down-history
bindkey '^?' backward-delete-char
bindkey '^h' backward-delete-char
bindkey '^w' backward-kill-word

function zle-line-init zle-keymap-select {
    VIM_PROMPT="%{$fg_bold[yellow]%} [% NORMAL]%  %{$reset_color%}"
    RPS1="${${KEYMAP/vicmd/$VIM_PROMPT}/(main|viins)/}$(git_prompt_status) $EPS1"
    zle reset-prompt
}

zle -N zle-line-init
zle -N zle-keymap-select
export KEYTIMEOUT=1

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

PATH=$PATH:~/.local/lib/aws/bin/:~/bin/

#THIS MUST BE AT THE END OF THE FILE FOR GVM TO WORK!!!
[[ -s "~/.gvm/bin/gvm-init.sh" ]] && source "~/.gvm/bin/gvm-init.sh"
```

**Comment by junegunn** [comment]
@slonka Did you find out which line causes the problem?

**Comment by slonka** [comment]
@junegunn I don't know how to do that. If you post a link how to debug this I will try.

**Comment by junegunn** [comment]
@slonka Nothing fancy, incrementally commenting out lines until it works :)

**Comment by junegunn** [comment]
@slonka I even tried you zshrc and the problem is not reproducible.

**Comment by slonka** [comment]
Isn't there a more sophisticated way? If it's hard to reproduce I don't want to spend 4 hours on that.

**Comment by junegunn** [comment]
Since you're the only one having the problem, it's pretty likely that something's wrong with your env. If you are not willing to provide enough information, there's nothing I can do.

**Comment by slonka** [comment]
After today's oh-my-zsh update the error is gone.
