### ISSUE TITLE
Preview window does not respect --color fg bg values

### ISSUE THREAD

**Issue by kerma** [junegunn/fzf#3283]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

## Problem / Steps to reproduce

I'm not sure whether this is a regression, or by design change (MAN page is not clear on this), but --color no longer respects values set in fg, bg. 

The following example used to produce the desired result:

```
fzf -n 1 --preview 'echo {}' --preview-window wrap --ansi --color dark,fg:246,bg:235,bg+:236 --no-height --border=rounded
```

With the latest version (0.4.0) it no longer does, and the following is required:

```
fzf -n 1 --preview 'echo {}' --preview-window wrap --ansi --color dark,preview-fg:246,preview-bg:235,bg+:236 --no-height --border=rounded
```

Here's an example how this used to work in vim-go: https://github.com/fatih/vim-go/blob/master/autoload/fzf/decls.vim?plain=1#L137

Please close if it's expected behavior. I'll file an issue to vim-go then.

**Comment by kerma** [comment]
I went as far back as 0.26.0 which might have been the first version where build was supported on arm64. Did not manage to reproduce the original behavior. So I'm quite confused now about how this ever worked (in which I'm pretty sure it did).

**Comment by junegunn** [comment]
> The following example used to produce the desired result:

What do you expect from the command? What is different from your expectation?

The two commands work as expected. I don't see anything strange.

<img width="861" alt="image" src="https://user-images.githubusercontent.com/700826/237007487-40759f54-1bb7-4176-bada-2cb38c24c934.png">

<img width="861" alt="image" src="https://user-images.githubusercontent.com/700826/237007516-2e4d0412-8248-42d2-afc7-a277c3790a58.png">

**Comment by kerma** [comment]
This is what I see:
![image](https://user-images.githubusercontent.com/735108/237060978-1ffd0062-452d-4104-839a-096beff95edf.png)

This is what I expect:
![image](https://user-images.githubusercontent.com/735108/237061368-e596ae96-231b-4351-853c-c4d07733adfd.png)

And if I set `--color dark,fg:246,bg:235,preview-fg:246,preview-bg:235,bg+:236` I see (having toggled the preview window on):
![image](https://user-images.githubusercontent.com/735108/237062949-7cb84216-cd58-49fd-9c9e-521066149362.png)

**Comment by kerma** [comment]
I've figured out that the colors passed to the fzf command are actually wrong. When I post hex values I get the expected result. So all good with fzf, sorry (:
