### ISSUE TITLE
CR chars in preview after fzf update

### ISSUE THREAD

**Issue by FallenGameR** [junegunn/fzf#3290]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info
- OS
    - [x] Windows
- Shell
    - [x] pwsh

## Problem / Steps to reproduce
After a recent fzf update to 0.39.0 the preview window shows CR chars on every line. It is annoying. These chars are supposed to be invisible. Happens only in the preview window. I couldn't find how to make them invisible again.

`fzf  --preview 'echo {}'`
![repro](https://github.com/junegunn/fzf/assets/711295/9a288b6f-65fd-40ca-8483-9866d6eb97b5)

**Comment by Delapouite** [comment]
Hello. Did you try the 0.40.0 version? It includes this commit  https://github.com/junegunn/fzf/commit/88d812fe8247310efdcc6365ea68738e469b2076

**Comment by FallenGameR** [comment]
Thanks!  The commit seems to address exactly this issue.

Github release version is ahead of the latest one available via chocolatey
(0.39). I usually install and update fzf through it. Do you publish
releases to chocolatey and could publish be version or is it done by
somebody else and I should ping them?

**Comment by FallenGameR** [comment]
Contacted the choco package maintainer to publish the new release.
Thank you! I confirm that 0.40 fixes the CR chars in preview window.
