### ISSUE TITLE
[Feature Request] :add multiple preview window

### ISSUE THREAD

**Issue by zonta00001** [junegunn/fzf#3297]
fzf is already an amazing tool for general data filtering purposes, with different processing options, but I'm more into data visualization and bemoan the fact that fzf doesn't have the ability to display more than one preview window (which would be a real time saver if you are looking for specific content), there is no possibility to launch an interactive program in a preview window (which would be very practical if you want to have a task selector, for example watching btop running in the background through a preview window; or having the progress of a compilation process that we would have cut with "&").

Thank you.

**Comment by junegunn** [comment]
> display more than one preview window

> launch an interactive program in a preview window

This is beyond the scope of fzf, a filter program. A proper terminal multiplexer such as tmux (perhaps paired with fzf) will better suit your needs.

**Comment by vlappa** [comment]
I see this issue has a wontfix label. Anyway, I had the same idea.

I'm launching a music production session (on Linux). Such a session is just a folder where all applications that are part of such session store their data. 

There is a sessionfile, which is just a text file containing the binary names and some additional metadata of the applications that are part of the session. There is also a notes file where the user is able to enter general notes/ info about the session.

I would to like to filter the sessionfile for a specific application and then not only preview the sessionfile, but also the notes file of the session, containing information about the session, before I launch the session.

This would be possible if fzf would be able to display two preview windows.
