### ISSUE TITLE
Add action to toggle fullscreen

### ISSUE THREAD

**Issue by bew** [junegunn/fzf#3298]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
- Shell
    - [x] zsh

## Problem / Steps to reproduce

The user story is similar to #2953, except that the behavior I'm looking for is a way to toggle fullscreen mode on demand.
My usage of `fzf` is always with `--height=40%` but sometimes I trigger fzf and realize I need to see more results or more of the preview, for that execution.

My wish would be to bind a key like `ctrl-f` to a `toggle-fullscreen` action or similar, that would switch fzf to use all the vertical space, ignoring the `--height` parameter (hide the scrollback).
Repeating the action would go back to use `--height` parameter from the CLI (and show again the scrollback).
Current state should be retained though, what I already (multi-)selected, etc..

The action would have no effect if `--height` is not used on start.

**Comment by junegunn** [comment]
This is not trivial to implement, if not impossible to implement, so I'm not going to try. But if you're willing to contribute, I'd be happy to review the code.

I'd suggest that you use fzf-tmux instead, and tmux will allow you to zoom and unzoom the fzf pane via `bind-key z`. I believe this is a much cleaner, simpler, and more flexible solution.
