### ISSUE TITLE
fish shell support - installer / keybindings

### ISSUE THREAD

**Issue by junegunn** [junegunn/fzf#33]
Regardless of on whatever shell it may be, fzf is installable simply by placing fzf in a directory included in `$PATH`. However, the install script generates an optimal function wrapper for fzf and defines some useful key bindings. It would be nice if it supports fish as well.

**Comment by da99** [comment]
In case other Fish users read this, here is an alternative:

    fzf | read  MYRESULT; and vim $MYRESULT

That's good when the result is one line. For multiple selections, `fzf -m`, the best solution so far is the one you posted using a temp file.
