### ISSUE TITLE
:FZF Does not work in gvim/mvim, works in console vim on OSX

### ISSUE THREAD

**Issue by letit-bee** [junegunn/fzf#331]
Nothing happens at all.
I have latest fzf, vim, macvim and no strange stuff in .bashrc like the gentelman with zsh had.
Looking at fzf.vim, might be related to the fact that there is no xterm in newer osx...

**Comment by letit-bee** [comment]
Yep, install XQuartz solves the issue, though it looks like a completely separate window that can even be alt-tabbed to separately. Is  this how it's supposed to work?

**Comment by junegunn** [comment]
Yes, it's the best we can do with GVim. fzf is a command-line program that runs on a *terminal*, so there's no way to start it without a terminal emulator. A GUI-version of neovim, once released, will be able to embed fzf inside Vim split.
