### ISSUE TITLE
[question] About match order

### ISSUE THREAD

**Issue by sentriz** [junegunn/fzf#3314]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
- Shell
    - [x] fish

## Problem / Steps to reproduce

consider the input

```
II I
II II
```

and the query `II II`, 

the highest rank result seems to be `II I`, not `II II` as in the query

```bash
$ printf "%s\n" "II I" "II II" | fzf --filter "II II" | head -n 1
II I # why not II II?
```

it seems to work with `--tiebreak=end`, but I'm not sure that's suitable for some other cases. could you explain a bit why there is a tiebreak between the two lines? thanks!

**Comment by junegunn** [comment]
> the query `II II`

In the default ["extended-search" mode](https://github.com/junegunn/fzf#search-syntax), each word in the query string is a separate, independent search term. So this means "find the intersection of 1. the items that contain `II` and 2. the items that contain `II`". So the second term is completely redundant. `II II` is effectively the same as `II`.

Thus, both `II II` and `II I` are matched with the exact same score, and the default tiebreak=length prefers `II I`, which is shorter.

---

In this particular example, you can either

* Omit space and type `III`
* Or escape space `II\ I`

**Comment by sentriz** [comment]
thanks!
