### ISSUE TITLE
fzf doesn't find file in CWD when using ./ (dot slash) with the filepath

### ISSUE THREAD

**Issue by danielb2** [junegunn/fzf#3315]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf    ( 0.41.1 )
- [x] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [x] fish

## Problem / Steps to reproduce

1. touch foo
2. fzf -q ./foo

Exepected:

find the file foo

Actual:

doesn't find the file foo unless `./` is removed

Thoughts:

./ is a valid filepath for the file in the local dir. other commands such as `ls ./foo` will work

**Comment by junegunn** [comment]
fzf is an interactive filter program. So what you're doing here is similar to

```sh
touch foo
ls | grep ./foo
```

which also will not print `foo`.

If you want fzf to list `foo` as `./foo` instead of `foo`, you should change the input acccordingly.

```sh
find . | fzf -q ./foo

# or
export FZF_DEFAULT_COMMAND='find .'
fzf -q ./foo
```

**Comment by danielb2** [comment]
ohhh, I was using `fd` to not have the noice of the .gitrepo and ignored files. looks like there's no option to turn `./` currently. I opened an issue with `fd` instead. thanks
