### ISSUE TITLE
[question/feat] Mapping items to a custom string

### ISSUE THREAD

**Issue by WhyNotHugo** [junegunn/fzf#3316]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Problem / Steps to reproduce

I have a directory full of email files, and I want to run `fzf` over them. However, instead of showing the filenames in fzf (these filenames have little meaning to a human), I want to show the subject for them.

Once a n entry is selected in fzf, I need to determine which file was picked. Note that multiple messages might have the same subject, so the mapping subject->file is not 1:1.

I've so far though of two approaches, but I don't really now how to make either with `fzf` (if even possible).

The first option is to have a tool that feeds `fzf` lines which each contain `filename|subject`, then somehow configure `fzf` to only show the portion after the `|`, but print the portion before the `|` once an entry is selected.

The second option would be to feed `fzf` the filenames, and provide `fzf` a command, e.g.: `--display eml-to-subject`, where `eml-to-subject` is a tiny helper that takes a filename as input and prints the subject for an email. Obviously, nothing like this `--display` flag exists.

I guess this might be a feature request? Although maybe there are existing features that I can use for this scenario?

**Comment by jaggzh** [comment]
I just encountered this issue myself.  I am listing directories+files but want to have the listing internal, then something like --preview {cmd} to prepare the line for the user display.  You can see, in my project here https://github.com/jaggzh/linux-browsing-tools/tree/main how it can be useful.

**Comment by jaggzh** [comment]
(Point is, it would be a lot more convenient to have the internal listing retained, and process it for output, than to try to pass in a formatted listing, possibly with color codes and stuff, and then try to UNparse that for processing for the preview and such.)

**Comment by junegunn** [comment]
Use `--with-nth`, and make sure to check out "FIELD INDEX EXPRESSION" section of the man page.

```sh
echo 'filename|subject' | fzf --delimiter '\|' --with-nth 2
```

**Comment by WhyNotHugo** [comment]
Thanks!
