### ISSUE TITLE
Errors after updating this morning

### ISSUE THREAD

**Issue by craigp** [junegunn/fzf#332]
I updated all vim my plugins this morning, and now I'm getting:

`Unknown function: fzf#run`

**Comment by junegunn** [comment]
Show me your vimrc

**Comment by craigp** [comment]
this is the relevant section .. pretty sure i copied it straight out of the examples:
```
nnoremap <silent> <Leader>bb :call fzf#run({
\   'source':  reverse(<sid>buflist()),
\   'sink':    function('<sid>bufopen'),
\   'options': '+m',
\   'down':    len(<sid>buflist()) + 2
\ })<CR>

nnoremap <leader>rr :call fzf#run({
\  'source':  v:oldfiles,
\  'sink':    'e',
\  'options': '-m -x +s',
\  'down':    '40%'})<CR>
```

**Comment by craigp** [comment]
Nevermind, I figure it out ... messed up my vim-plug config, it wasn't loading until I'd used `:FZF`

Sorry for the trouble, and thanks for all the great plugins :)
