### ISSUE TITLE
ANSI processing seems broke in listing area

### ISSUE THREAD

**Issue by jaggzh** [junegunn/fzf#3320]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [X] I have searched through the existing issues

## Info

- OS
    - [x ] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x ] bash
    - [ ] zsh
    - [ ] fish

## Problem / Steps to reproduce
1. include ansi codes in main listing input to fzf
* POSSIBLY it's the alternating sequences that reveal the issue (i'm feeding a directory listing with different color for the directories than the files)
* POSSIBLY it's the mid-line color sequences revealing it (i'm feeding in a number followed by the color-coded path for directories). Alternately, I'm feeding in spaces followed by a color-coded path (filepath)

My "line" is as follows (full script at  https://github.com/jaggzh/linux-browsing-tools/blob/main/dirbrief#L48).
You'll  note the printf with $bcya is a directory line. It has a count of its files preceding it, but the directory paath itself should be cyan.
As a test, when trying to solve it, I made the files yellow (the more-indented printf with $yel in it). Oddly, the yellow makes adjacent line's file-count (back at the directory printf) yellow, and nothing else.  Below the following code is a snapshot:
```bash
find "$dir" -type d -print0 | while IFS= read -r -d '' dir; do
	total_files=$(find "$dir" -maxdepth 1 -type f | wc -l)
	depth=$(tr -dc '/' <<< "$dir" | awk '{ print length }')
	indent=$(printf '%*s' $((2 * (depth - base_depth - 1))))
	printf "%-4d $bcya%s%s$rst\0" "$total_files" "$indent" "$dir"
	find "$dir" -maxdepth 1 -type f | head -n "$num_files" | while IFS= read -r file; do
		printf "      $indent$yel%s$rst\0" "$file"
	done
done | fzf --tabstop 3 \
           --preview "$preview_cmd" \
           --preview-window "up,$prev_lines" \
           --read0 \
           --ansi \
           --scroll-off 2 \
           --layout reverse-list
```
![image](https://github.com/junegunn/fzf/assets/20318973/ae8a5945-54c2-4445-b14f-0568be750eb3)

**Comment by junegunn** [comment]
Can you simplify the command without any variable references so I can run it without downloading and reading your whole script?

**Comment by jaggzh** [comment]
Had to deal with family health stuff. Will handle this as soon as I can.

**Comment by junegunn** [comment]
No hurries. Best wishes.

**Comment by jaggzh** [comment]
Colors not displaying:
color=$'\033[33;1m'; rst=$'\033[;m'; find / -maxdepth 1 -type d -print0 | while IFS= read -r -d '' dir; do printf "0123 $color%s test$rst\0" "$dir"; done | fzf --ansi --read0

Colors displaying:
color=$'\033[33;1m'; color2=$'\033[34;1m'; rst=$'\033[;m'; find / -maxdepth 1 -type d -print0 | while IFS= read -r -d '' dir; do printf "0123 $color%s ${color2}hello$rst\0" "$dir"; done | fzf --read0 --ansi

**Comment by junegunn** [comment]
Thanks. Changing `rst=$'\033[;m'` to `rst=$'\033[m'` fixes the issue. I'll look into it.
