### ISSUE TITLE
complete names of executable scrips

### ISSUE THREAD

**Issue by Vasiliy-Bondarenko** [junegunn/fzf#3321]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

## Problem / Steps to reproduce
let's say i have executable shell scripts in the current directory
```
-rwxr-xr-x aa-something.sh
-rwxr-xr-x aa-something-else.sh
...lots of other files and dirs...
```

when i type 
`> ./aa [Ctrl-T]`
i expect to see a list of my scripts, but fzf shows anything but the scripts. am i doing something wrong? How do i make fzf complete a path to executable scripts? now it takes to type almost full filename for the scripts to show up in search even though i expect them to be on top of the list because i have indicated my intention to run it with `./` and it starts with the same chars.

**Comment by junegunn** [comment]
> when i type
> `> ./aa [Ctrl-T]`
> i expect to see a list of my scripts

Why do you expect it to do so? CTRL-T is not an ordinary shell completion. I suggest that you re-read https://github.com/junegunn/fzf#key-bindings-for-command-line
