### ISSUE TITLE
timestamp

### ISSUE THREAD

**Issue by iomari** [junegunn/fzf#3323]
- [ x] I have read through the manual page (`man fzf`)
- [x ] I have the latest version of fzf
- [x ] I have searched through the existing issues

## Info

- OS
    - [ x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ x] zsh
    - [ ] fish

Greetings,
Is there any way to format the search output so that the time stamp is human readable?

**Comment by junegunn** [comment]
No. Use another program to post-process the output.
