### ISSUE TITLE
undefined method `getc' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by slhck** [junegunn/fzf#333]
I just installed the latest version of [Babun](http://babun.github.io/), and then installed the latest version of fzf by cloning from Git. I then re-opened the Babun terminal window.

When I press `Ctrl-R`, I get:

```
/home/robitza.werner/.fzf/fzf:929:in `get_input': undefined method `getc' for nil:NilClass (NoMethodError)                              ~
        from /home/robitza.werner/.fzf/fzf:1157:in `start_loop'
        from /home/robitza.werner/.fzf/fzf:309:in `start'
        from /home/robitza.werner/.fzf/fzf:1347:in `<main>'
{ ~ }  » which ruby                                                                                                                     ~
/cygdrive/c/cygwin64/bin/ruby
{ ~ }  » ruby -v                                                                                                                        ~
ruby 2.0.0p598 (2014-11-13) [x86_64-cygwin]
```

Apparently, `@tty` is never set, and fzf doesn't check that.

Not sure if it's a Babun issue or fzf, but perhaps there's an easy fix.

**Comment by junegunn** [comment]
I'm sorry but Windows support is now discontinued. I tried to build the new Go version on Windows platform, but hasn't been successful. I'm looking for some help in that. #147

**Comment by slhck** [comment]
Ah, I see. Too bad, but thanks for the quick reply!
