### ISSUE TITLE
Dynamic reload command, toggled by single bind key

### ISSUE THREAD

**Issue by sanderbongers** [junegunn/fzf#3330]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [x] fish

## Problem / Steps to reproduce

I've been trying to create a toggle bind key, that switches hidden files on/off during the fzf-cd-widget command with a single bind key (ctrl-h). It looks like the reload action gets evaluated on start, so altering $FZF_ALT_C_COMMAND during runtime or passing a function will not change the reload function.

I figured the only way it's possible is to abuse the query string {q} as that one is variable. This is my working solution:
```fish
# fzf.fish

set -gx FZF_ALT_C_COMMAND "fd --ignore-file=$HOME/.rgignore --type directory"
set -gx FZF_ALT_C_OPTS "--header 'Toggle hidden: ⌃h' --bind 'start:execute-silent(fzf_cd_toggle init)' --bind 'ctrl-h:transform-query(fzf_cd_toggle pre {q})+reload(eval {q})+transform-query(fzf_cd_toggle post)'"

function fzf_cd_toggle
    set -f query_file /tmp/fzf-alt-c-query
    set -f toggle_file /tmp/fzf-alt-c-toggle
    set -f command_a "$FZF_ALT_C_COMMAND"
    set -f command_b "$FZF_ALT_C_COMMAND --hidden"

    switch $argv[1]
        case init
            # Reset state
            rm $toggle_file &>/dev/null
        case pre
            # Temporarily store the query string
            echo $argv[2] >$query_file

            if rm $toggle_file &>/dev/null
                # Toggle state was on
                set -f command $command_a
            else
                # Toggle state was off
                # Turn it on by creating the file
                touch $toggle_file
                set -f command $command_b
            end

            # Return the applicable command
            # This will temporarily override the query string {q} and gets evaluated in the reload action
            echo $command

            # ^ That is the sole purpose of this function: to have a dynamic reload command during fzf's lifetime on a single key binding
        case post
            # Restore the query string
            echo (cat $query_file)
    end
end
```

It temporarily stores the query string to a file, changes the query to the toggle command, that gets evaluated during reload, and then the query string is restored. The existence of $toggle_file determines the on/off state (I tried setting a global variable first but that didn't work).

<img width="910" alt="Screenshot" src="https://github.com/junegunn/fzf/assets/14151411/8235891f-8d76-4551-8ac0-ffc34345dbd5">
(still image)

Any suggestions?

**Comment by junegunn** [comment]
I was able to do it like this on bash

```sh
export FZF_ALT_C_COMMAND_TOGGLE="
  if [[ ! -e /tmp/alt-c ]]; then
    touch /tmp/alt-c
    echo foo
  else
    rm -f /tmp/alt-c
    echo bar
  fi
"
export FZF_ALT_C_COMMAND='rm -f /tmp/alt-c; eval "$FZF_ALT_C_COMMAND_TOGGLE"'
export FZF_ALT_C_OPTS="
  --header 'Toggle hidden: ⌃h'
  --bind 'ctrl-h:reload:eval \"$FZF_ALT_C_COMMAND_TOGGLE\"'
"
```

FYI, there is an open discussion on how we can achieve this without using a temp file by exposing some internal states of fzf. See #3354.
