### ISSUE TITLE
--info=right missing in the man page

### ISSUE THREAD

**Issue by nkh** [junegunn/fzf#3333]
- [x ] I have read through the manual page (`man fzf`)
- [ x] I have the latest version of fzf
- [ x] I have searched through the existing issues

## Info

- OS
    - [x ] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ x] bash
    - [ ] zsh
    - [ ] fish

## Problem / Steps to reproduce

version 0.42 brought "--info=right" but it's missing from the man page

I usually pull and build with Makefile which lets me test the local build first, I copy the binaries manually. It would be nice if build did also tar the man pages, maybe a local_install target?

**Comment by junegunn** [comment]
Thanks, fixed it.



> It would be nice if build did also tar the man pages, maybe a local_install target?

I'm not completely sure if I follow you here. I'll take a look if you open a pull request.
