### ISSUE TITLE
bash dependency?

### ISSUE THREAD

**Issue by thyssentishman** [junegunn/fzf#3339]
Hi,

While installing fzf on OpenBSD, I noticed that bash was being pulled as a dependency. The mantainer of the port pointed me to [this line](https://github.com/junegunn/fzf/blob/4cd621e877cb3a8e44b12ba3a7ce58709862922f/src/reader.go#L101) where bash seems to be hardcoded. Now since fzf claims to have no dependencies in the README, I wonder if this is how it's supposed to be.

Most linux distros include bash as the default shell, so having it as a dependency doesn't really make a difference. However for OpenBSD for example that includes ksh as its default shell, having bash installed becomes useless (in my opinion) and redundant.

Would anyone please care to explain why bash is required? Are there any plans to have this dependency removed? Should the README maybe be updated?

Thank you.

**Comment by junegunn** [comment]
You can use fzf without bash just fine. bash is only required when

* You don't pass input list via standard input
* And you don't have `$FZF_DEFAULT_COMMAND`

```sh
# 1. This works without bash
find . | fzf

# 2. This works without bash
export FZF_DEFAULT_COMMAND='find .'
fzf

# 3. This is the only case where fzf fails to start the find command for populating the list
unset FZF_DEFAULT_COMMAND
fzf
```

The hard-coded default command used in case 3 uses a bash construct (`pipefail`)

https://github.com/junegunn/fzf/blob/a7c41f3fcd6c6db4ff25828218bea281439dd1ba/src/constants.go#L61

If you can come up with an equivalent command, then we can stop requiring bash in that particular case.

**Comment by thyssentishman** [comment]
Hi @junegunn, thanks for the quick reply.

> The hard-coded default command used in case 3 uses a bash construct (`pipefail`)

This doesn't seem to be bash specific. OpenBSD's ksh supports it and apparently most common shells as well (see [here](https://unix.stackexchange.com/questions/654885/who-is-responsible-for-providing-set-o-pipefail)).

> If you can come up with an equivalent command, then we can stop requiring bash in that particular case.

Perhaps it is better to have these shells as optional dependencies and require at least one. Or even better we could be POSIX compliant with the alternative suggested by shellcheck [here](https://www.shellcheck.net/wiki/SC3040) or maybe something like this:

``` go
defaultCommand = `{ command find -L . -mindepth 1 \( -path '*/\.*' -o -fstype 'sysfs' -o -fstype 'devfs' -o -fstype 'devtmpfs' -o -fstype 'proc' \) -prune -o -type f -print -o -type l -print 2> /dev/null || kill $$; } | cut -b3-`
```

**Comment by junegunn** [comment]
Unfortunately the suggested command isn't identical to the current one.

```sh
$ { command find no-such-path || kill $$; } | cut -b3-
find: no-such-path: No such file or directory
$ echo $?
0

$ { set -o pipefail; find no-such-path | cut -b3-; }
find: no-such-path: No such file or directory
$ echo $?
1
```

It's not possible for fzf to know if the find command failed without using `pipefail`.

**Comment by thyssentishman** [comment]
> Unfortunately the suggested command isn't identical to the current one.

You're right, sorry. Don't know how I missed that. 

Can we perhaps rely on the error that `set -o pipefail` returns if its not available?

e.g. in the dash shell
```sh
$ set -o pipefail; find no-such-path | cut -d3-
dash: 1: set: Illegal option -o pipefail
$ echo $?
2
```

And since most shells already support `set -o pipefail`, instead of having bash as a dependency, we could inform the user about his/her shell not being compatible. 

```sh
[ $? -ne 0 ] && echo "fzf: FZF_DEFAULT_COMMAND: the $SHELL shell is currently not supported"
```

**Comment by thyssentishman** [comment]
When bash is installed and the current directory doesn't exist or can't be read and `FZF_DEFAULT_COMMAND` is unset, fzf fails with the following message:
```
[Command failed: set -o pipefail; command find -L . -mindepth 1 \( -path '*/\.*'..
>
```
Based on this error message the user has no idea what went wrong and has to debug the command to find out that the current directory doesn't exist or can't be read. 

When bash is not installed and `FZF_DEFAULT_COMMAND` is unset, fzf fails with the following message:
```
[Command failed: set -o pipefail; command find -L . -mindepth 1 \( -path '*/\.*'..
>
```
We get the exact same message and the user will have to debug the command to find out that the bash shell needs to be installed because it is hardcoded. So what difference does it make if we do the following:

```diff
diff --git a/src/reader.go b/src/reader.go
index 06e9b73..c1af2f2 100644
--- a/src/reader.go
+++ b/src/reader.go
@@ -99,7 +99,7 @@ func (r *Reader) ReadSource() {
        var success bool
        if util.IsTty() {
-               // The default command for *nix requires bash
-               shell := "bash"
+               shell := os.Getenv("SHELL")
                cmd := os.Getenv("FZF_DEFAULT_COMMAND")
                if len(cmd) == 0 {
                        if defaultCommand != "" {
```

We would get the same error message we got above if the shell being used doesn't support `set -o pipefail`. 

If I understand  correctly, the only purpose of `set -o pipefail` is to exit with an error if the `find` command fails. Without it, fzf would run as if no error had happened and would show no results leaving the user confused. Allowing other shells would not interfere with this behavior and no errors would be hidden from the user.

**Comment by junegunn** [comment]
> ```diff
> +               shell := os.Getenv("SHELL")
> ```

There are users whose primary shell doesn't support `pipefail`, for example, `fish`. With the suggested change, the default command will stop working for them. But we can't just tell them to change `$SHELL` to bash, because `$SHELL` is used to execute external programs in many different actions, `execute`, `preview`, `reload`, and `transform-query`, to name a few.

```sh
# If you change $SHELL to bash, commands like this will no longer work
fzf --preview 'some script in fish syntax' --bind 'ctrl-r:reload:another script in fish syntax'
```

**Comment by thyssentishman** [comment]
I understand. In that case can we perhaps check if the current shell supports `pipefail` and only if not, fallback to bash?

```diff
diff --git a/src/reader.go b/src/reader.go
index 06e9b73..037e29f 100644
--- a/src/reader.go
+++ b/src/reader.go
@@ -98,8 +98,10 @@ func (r *Reader) ReadSource() {
        r.startEventPoller()
        var success bool
        if util.IsTty() {
-               // The default command for *nix requires bash
-               shell := "bash"
+               // Check if current shell supports 'set -o pipefail', fallback to bash if not
+               shell := os.Getenv("SHELL")
+               if ! r.readFromCommand(&shell, `set -o pipefail`) { shell = "bash" }
                cmd := os.Getenv("FZF_DEFAULT_COMMAND")
                if len(cmd) == 0 {
                        if defaultCommand != "" {
```

**Comment by junegunn** [comment]
I feel it's a bit overkill to start another process just to check the feature.

What is your `$SHELL`? Is it something like `/bin/ksh`?

Here's what I'm thinking

* Check `$SHELL`, if it's one of `ksh`, `bash`, `zsh`, or any of the known shells that supports `pipefail`, use it
* Otherwise, use `bash`

---

Another approach would be to just use `sh`

* https://github.com/koalaman/shellcheck/issues/2555

**Comment by thyssentishman** [comment]
> What is your `$SHELL`? Is it something like `/bin/ksh`?

Yes, exactly.

> Here's what I'm thinking
> 
> * Check `$SHELL`, if it's one of `ksh`, `bash`, `zsh`, or any of the known shells that supports `pipefail`, use it
> * Otherwise, use `bash`

This sounds reasonable to me. We could perhaps use [this list](https://unix.stackexchange.com/a/654932) as a reference for which shells to check for.

> Another approach would be to just use `sh`

This would be even better I think, but I agree on that it might be a bit too early for that. I could create another issue for it for future reference/discussion if you want :)
