### ISSUE TITLE
Execute doesn't correctly read `""`

### ISSUE THREAD

**Issue by netei** [junegunn/fzf#334]
```
$ fzf --version
0.10.3
```

Here is an excerpt of my .bashrc:

```
export FZF_DEFAULT_OPTS="-1 -0 -x --no-mouse --margin 5%,5% --multi --bind 'f4:toggle-all,"
 FZF_DEFAULT_OPTS="$FZF_DEFAULT_OPTS"'f2:execute@echo "{}" > /tmp/test@'
FZF_DEFAULT_OPTS="$FZF_DEFAULT_OPTS""' --history $HOME/.fzfhistory"
```

which at the end gives me the following : 

```
$ echo $FZF_DEFAULT_OPTS
-1 -0 -x --no-mouse --margin 5%,5% --multi --bind 'f4:toggle-all,f2:execute@echo "{}" > /tmp/test@' --history /home/edgar/.fzfhistory
```

However, when I do `f2` on the text `ls 'test'` (basically anything containing a single quote), the real thing that is echoed is `ls test` (without the double quotes).

Any ideas why this is happening ?

**Comment by junegunn** [comment]
According to the man page:

> {} is the placeholder for the double-quoted string of the current line.

So try it again without the quotes.

**Comment by netei** [comment]
Oh thanks, my error. It works now !
