### ISSUE TITLE
fzf not highlighting all occurences of a word in filename

### ISSUE THREAD

**Issue by faxotherapy** [junegunn/fzf#3340]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf: 0.42
- [x] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

## Problem / Steps to reproduce

Doing a search on following keywords : _retour_, _famille_

fzf forgot to highlight the other _retour_ and _famille_ at the end of the filename.

<img width="998" alt="fzf-not-highlighting-all" src="https://github.com/junegunn/fzf/assets/6538008/61f37ef1-96e1-45d6-86d7-1a17cd21fcd7">

**Comment by junegunn** [comment]
This is by design. fzf only highlights the first occurrence with the highest matching score. Because highlighting all occurrences can be computationally expensive and it's not really a good idea for a fuzzy finder. There can be more matches than you expect because of the fuzzy nature.
