### ISSUE TITLE
Can't get trigger to work. All other fzf commands and keys work as expected

### ISSUE THREAD

**Issue by jcaffey** [junegunn/fzf#3344]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Mac OS X

- Shell
    - [x] zsh

## Problem / Steps to reproduce

I can't get the completion trigger to work. Ctrl+R, ctrl+t, alt+c all work fine.

**<TAB> gives me an ugly list of directory contents as just plain white strings
~~<TAB> shows nothing

Things I have tried:
1. fresh install from both git and homebrew
2. attempt with only fzf settings in .zshrc
3. multiple terminals (alacritty and iterm)
4. changing trigger to ~~
5. multiple variations of zshrc are as follows:

With options:
```shell
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

export FZF_COMPLETION_TRIGGER='~~'
export FZF_DEFAULT_OPTS="
--color='hl:148,hl+:154,pointer:032,marker:010,bg+:237,gutter:008'
--prompt='∼ ' --pointer='▶' --marker='✓'
--bind '?:toggle-preview'
--bind 'ctrl-a:select-all'
--bind 'ctrl-e:execute(echo {+} | xargs -o nvim)'
--layout=reverse
--info=inline
--height=80%
--multi
--preview-window :hidden
--preview '([[ -f {} ]] && (bat --style=numbers --color=always {} || cat {})) || ([[ -d {} ]] && (tree -C {} | less)) || echo {} 2> /dev/null | head -200'
"
export FZF_DEFAULT_COMMAND="fd --hidden --follow --exclude '.git' --exclude 'node_modules'"
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
export FZF_ALT_C_COMMAND="$FZF_DEFAULT_COMMAND --type d"

source /usr/local/opt/fzf/shell/key-bindings.zsh
source /usr/local/opt/fzf/shell/completion.zsh
``` 

without options:
```shell
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

source /usr/local/opt/fzf/shell/key-bindings.zsh
source /usr/local/opt/fzf/shell/completion.zsh
```

I've spent more than 2 hours on this, so please forgive me if I have missed something stupid. I haven't slept for 2 days so I'm not going to be surprised if I did something stupid and you yell at me. I can take it.

Thanks for the help!

**Comment by junegunn** [comment]
> 1. both git and homebrew

You don't need both. You just need to choose one way to install fzf. Homebrew is recommended because it's easier to update fzf. See `brew info fzf` for instructions.





> I can't get the completion trigger to work. Ctrl+R, ctrl+t, alt+c all work fine.
> 
> ** gives me an ugly list of directory contents as just plain white strings ~~ shows nothing

What does `bindkey | grep fzf` show? You should see `"^I" fzf-completion` in the output if you have properly loaded completion.zsh file.

**Comment by jcaffey** [comment]
> > 1. both git and homebrew
> 
> You don't need both. You just need to choose one way to install fzf. Homebrew is recommended because it's easier to update fzf. See `brew info fzf` for instructions.
>
Yeah, I was trying installs separately.

> > I can't get the completion trigger to work. Ctrl+R, ctrl+t, alt+c all work fine.
> > ** gives me an ugly list of directory contents as just plain white strings ~~ shows nothing
> 
> What does `bindkey | grep fzf` show? You should see `"^I" fzf-completion` in the output if you have properly loaded completion.zsh file.

I do have that now and it does work, but I have no idea what my problem was with my zsh setup. I switched to fish last night and everything works fine for me now. I wish I had figured it out with zsh, but I'm happier on fish, so ... thank you for your time and taking a look.

And thank you for this wonderful project!

**Comment by AyaanAhmed25** [comment]
I had the same issue. The problem was I had enabled zsh vi mode emulation(`bindkey -v`). This remapped `"^I"` to `expand-or-complete`.  To solve this problem I put `bindkey '^I' fzf-completion` after `bindkey -v` in my zshrc. Or you can also initialize fzf itself after `bindkey -v`
