### ISSUE TITLE
Read input stream from execute/become

### ISSUE THREAD

**Issue by catern** [junegunn/fzf#3347]
- [X] I have read through the manual page (`man fzf`)
- [X] I have the latest version of fzf
- [X] I have searched through the existing issues

## Info

- OS
    - [X] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [X] bash
    - [ ] zsh
    - [ ] fish

## Problem / Steps to reproduce

I have lots of programs which send input to fzf to let me select an option.  I'd like to be able to swap fzf out with other programs sometimes, without modifying the script. Unfortunately, many of my scripts use /usr/bin/fzf so I can't simply put a different `fzf` on PATH.

I can set `FZF_DEFAULT_OPTS="start:become(other_program)"`, but in `become` and `execute` and `execute-silently` I don't have access to the input stream (that is, stdin), so `other_program` doesn't get a chance to read the input stream and handle it.

Is there a way to tell fzf to invoke a different program to handle the input stream?

**Comment by junegunn** [comment]
No. It's not possible. It's a very niche use case so I don't think fzf will add an option or mode for that.
