### ISSUE TITLE
Piping input from man gives weird title behaviour

### ISSUE THREAD

**Issue by vedant-pandey** [junegunn/fzf#3348]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

## Problem / Steps to reproduce
When piping stream from man the characters in titles are repeated

https://github.com/junegunn/fzf/assets/25723331/99bdcd80-8796-430b-8bbb-b813c5177723

**Comment by LangLangBart** [comment]
- try with `--ansi`

```sh
man git | fzf --ansi --layout=reverse
```

- to see invisible characters on the `man` page, you can use `man git | cat -et` or `man git | cat -v`

```sh
man cat
# ...
#     -e      Display non-printing characters (see the -v option), and display a dollar sign (`$') at the end of each line.
# ...
#      -t      Display non-printing characters (see the -v option), and display tab characters as `^I'. 
#      -v      Display non-printing characters so they are visible.  Control characters print as `^X' for control-X; the delete character (octal 0177) prints as `^?'.  Non-ASCII characters (with the high bit set) are printed as `M-' (for meta) followed by the character for the low 7 bits.
```

---

- or try with `col -b`

```sh
man git | col -b | fzf --layout=reverse
```

```sh
man man 
# ...
#        To get a plain text version of a man page, without backspaces and underscores, try man foo | col -b > foo.mantxt

man col
# ...
#      -b      Do not output any backspaces, printing only the last character written to each column position.
```
