### ISSUE TITLE
ESC no longer closes FZF in Neovim

### ISSUE THREAD

**Issue by brandoniffert** [junegunn/fzf#335]
I could've swore this was working a couple days ago but when I open FZF in Neovim I can no longer press ESC to have FZF close. Now it just puts the Neovim terminal buffer into normal mode. Ctrl-Q/C still works as long as the terminal buffer is in insert mode.

Neovim
NVIM 0.0.0-alpha+201508280302 (compiled Aug 28 2015 10:22:02)
Commit: 82296510879d6e18036ba45447d348bba41be52e

FZF 0.10.3

**Comment by junegunn** [comment]
I think you should post this on the neovim's issue tracker instead.
