### ISSUE TITLE
Feature request: Include alt-j and alt-k as default finder keybinds along with ctrl-j and ctrl-k

### ISSUE THREAD

**Issue by kungfubeaner** [junegunn/fzf#3350]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [x] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

## Problem / Steps to reproduce

I'm aware that this can be done with --bind "alt-j;down,alt-k:up" but since it is easier to reach the alt key than it is to reach the ctrl key can this be added as default keys for the finder (along with existing ones)?  I'm also aware that an alias for my shell can do this but windows doesn't have a way to make an alias other than a batch file and that feels cheap.

**Comment by junegunn** [comment]
You can put the options in FZF_DEFAULT_OPTS environment variable. It should work find on Windows.

https://github.com/junegunn/fzf#environment-variables
