### ISSUE TITLE
`reload` doesn't work with interactive commands (user prompted)

### ISSUE THREAD

**Issue by mpasa** [junegunn/fzf#3351]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [x] fish

## Problem / Steps to reproduce

I would like to reload the candidate list interactively. For that, I need `reload` to have a similar behavior as `execute`. Right now, it seems as if `reload` is using always empty stream for the standard input of the specified command. This behavior can be reproduced with the following command:

```
fzf --bind 'ctrl-a:reload-sync(read a; echo $a)'
```

The expected result for this would be to get a prompt, and then reload the candidate list with the text that was introduced. The actual result is a single empty line. The same command with `execute-sync` works as expected, although the output is not used for anything.

```
fzf --bind 'ctrl-a:execute(read a; echo $a)'
```

If this is the expected behaviour for `reload`, is there any other way of achieving what I want to do? Thank you

**Comment by mpasa** [comment]
The only workaround I have found is to use a swap temporary file, although this is not safe if running multiple instances of the same program.

```
fzf --bind 'ctrl-a:execute(read a; echo $a > /tmp/fzf_var)+reload(cat /tmp/fzf_var)'
```

**Comment by mpasa** [comment]
Another workaround seems to be to start fzf to listen into an http port and communicate with it from the subshell on `execute`:

```
fzf --listen --bind 'ctrl-a:execute(read a; curl -XPOST localhost:$FZF_PORT -d"reload(echo $a)")'
```

**Comment by junegunn** [comment]
Those are good approaches and I suggest that you use either of them.


> I would like to reload the candidate list interactively.

While tempting to do so, you don't have to do everything inside one fzf process.

```sh
lines=$(fzf --expect ctrl-a)
if [ "$(head -1 <<< "$lines")" = ctrl-a ]; then
  read a
  fzf --prompt "$a: "
else
  sed 1d <<< "$lines"
fi
```

**Comment by mpasa** [comment]
@junegunn Thank you. Using `--print-query` and a different `fzf` process was my previous approach, but I need to keep track of the cursor instead of it resetting to the initial position. In that case, I think `reload` is my only option.
