### ISSUE TITLE
Possibility to access the current prompt through a placeholder

### ISSUE THREAD

**Issue by LangLangBart** [junegunn/fzf#3354]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] macOS
- Shell
    - [x] zsh

## Problem / Steps to reproduce

- could the current prompt be exposed as a placeholder, for example `{p}` ?
- the idea would be to use it as a `state` 
  - Example: switch between the list of `Files` and `Directories` with a single hotkey <kbd>⌃ Control</kbd> + <kbd>A</kbd>

```sh
# this command is just a demo, it doesn't work, because there is no '{p}' placeholder
fzf --prompt "Files > " \
    --bind 'ctrl-a:transform-prompt([[ {p} =~ F ]] &&
            echo "Directories > " ||
            echo "Files > ")+reload:[[ {p} =~ F ]] &&
            fd --type directory ||
            fd --type file'
```

#### Demo with the {q} placeholder

```sh
# this will work as a demo by using the '{q}' placeholder and the '--disabled' flag
fzf --disabled --prompt "Files > " \
    --bind 'ctrl-a:transform-prompt([[ {q} =~ F ]] &&
            echo "Directories > " ||
            echo "Files > ")+reload:[[ {q} =~ F ]] &&
            fd --type directory ||
            fd --type file'
```

<img src="https://github.com/junegunn/fzf/assets/92653266/08264ebe-6231-4aaf-ab48-8710dabd40d1" width="800">

### Benefit
- you could use the current prompt `{p}` to manage a state; instead of managing it through an external file, as described in this comment https://github.com/junegunn/fzf/issues/2484#issuecomment-841788780

```sh
# command by @junegunn
echo 0 > /tmp/state
echo this | fzf --bind 'ctrl-space:reload:v=$(cat /tmp/state);
                        echo $((v ^ 1)) > /tmp/state;
                        if [ "$v" = 1 ]; then echo this; else echo that; fi'
```

### Related tickets
- new placeholders
  - #1482  (21/Jan/19)
  - #1719 (18/Oct/19)
- there are several tickets with similar requests to use only one command to toggle between two actions
  - #2505 (27/May/21)
  - #2484 (16/May/21)
  - ...

**Comment by junegunn** [comment]
Makes sense. It will affect the users who already have `{p}` in their commands, but I wouldn't worry too much about it.

> ```shell
> # this command is just a demo, it doesn't work, because there is no '{p}' placeholder
> fzf --prompt "Files > " \
>     --bind 'ctrl-a:transform-prompt([[ {p} =~ F ]] &&
>             echo "Directories > " ||
>             echo "Files > ")+reload:[[ {p} =~ F ]] &&
>             fd --type directory ||
>             fd --type file'
> ```

The commands are run in order and `transform-query` works synchronously, so when `reload` is evaluated, `{p}` is already changed by `transform-query`. This can become a source of user confusion.

**Comment by LangLangBart** [comment]
> > _This can become a source of user confusion._
> 
> _Yes_

Would it be possible to write several commands for the same hotkey and evaluate only those that are true for a `when` action? If numerous with the same key binding are true, only the last one would be used.

```sh
fzf \
	--prompt 'Files > ' \
	--bind 'ctrl-a:when([[ {p} =~ F ]])+transform-prompt(echo "Directories > ")+reload:fd --type directory' \
	--bind 'ctrl-a:when([[ ! {p} =~ F ]])+transform-prompt(echo "Files > ")+reload:fd --type file'
```

---

- inspired by `VSCode's  keybindings.json`
  - ref: [when clause contexts](https://code.visualstudio.com/api/references/when-clause-contexts) 
- when you in the editor and you press <kbd>⌘ Command</kbd> + <kbd>W</kbd> close the editor and close the current terminal tab when you in the terminal.

```json
[
    {
        "command": "workbench.action.closeActiveEditor",
        "key": "cmd+w",
        "when": "editorTextFocus"
    },
    {
        "command": "workbench.action.terminal.kill",
        "key": "cmd+w",
        "when": "terminalFocus"
    }
]
```

**Comment by junegunn** [comment]
> If numerous with the same key binding are true, only the last one would be used.
> 
> ```shell
> fzf
> ```

It contradicts the current behavior where the latter binding expression overrides the former.

```sh
# Will go up only one row
fzf --bind up:up+up --bind up:up
```

To append the action, we need `+` prefix.

```sh
# Up 3 rows
fzf --bind up:up+up --bind up:+up
```

(I just realized that this behavior is not documented on the man page, only can be found on [CHANGELOG](https://github.com/junegunn/fzf/blob/master/CHANGELOG.md#0200))

So, it seems to me that the suggested approach with the `when` action does not really help with the confusion we've talked about, though I think such an action for conditionally terminating the following action chain can be useful on its own.

**Comment by junegunn** [comment]
It feels a bit arbitrary that we use "prompt" to manage and expose an internal state. Why not use border label, preview label, or header string? If we expose them all using terse names like `{p}`, we increase the risk of breaking the existing scripts that contain `{p}`, `{l}`, `{h}`, or something like that.

One idea is to expose them all, but use longer names like `{fzf:prompt}` or `{fzf:header}` that are less likely to cause problems.

**Comment by LangLangBart** [comment]
> but use longer names like {fzf:prompt} or {fzf:header}

It’s a bit more typing, but it makes it much clearer.

---

The first thought was consistency among placeholders.
Would existing placeholders get an alias?  

| Placeholder | Alias |
|  :----: |  :----: |
| `{f}` | `{fzf:temporary_file}` |
| `{n}` | `{fzf:line_number}` |
| `{q}` | `{fzf:query}` |
| `{s}` | `{fzf:whitespace}`|

**Comment by junegunn** [comment]
Unlike `{q}` and `{n}`, `s`, `f`, and `+` are flags that can be used with a placeholder expression, e.g. `{+sf1..3}`, so I'm not sure how we should name those. Maybe something like `{fzf:all:whitespace:file:1..3}`?

**Comment by LangLangBart** [comment]
> Maybe something like `{fzf:all:whitespace:file:1..3}`?

Yes, `git` seems to do this very similar.  For example

```sh
git tag \
	--sort="creatordate" \
	--format="%(color:white)%(creatordate:format:%d/%b/%y) - %(color:bold yellow)%(refname:short)" \
	--color=always
# 01/May/23 - 0.40.0
# 26/May/23 - 0.41.0
# 27/May/23 - 0.41.1
# 15/Jun/23 - 0.42.0
```

**Comment by junegunn** [comment]
Added `{fzf:prompt}`. Let me know if it doesn't work as expected.

Also, for conditional execution of actions, you might want to experiment with the new `transform` action.

**Comment by LangLangBart** [comment]
> Added `{fzf:prompt}`.

Transformed the example in the **ADVANCED.md**[^1] with this new possibility.

Now, one can seamlessly switch between listed files and directories using a **single** key. 

```bash
fd | fzf --header 'CTRL-T: Switch between Files/Directories' \
	--bind 'ctrl-t:transform:[[ ! {fzf:prompt} =~ Files ]] &&
		echo "change-prompt(Files > )+reload(fd --type file)" ||
		echo "change-prompt(Directories > )+reload(fd --type directory)"'
```

[^1]: [ADVANCED.md#toggling-between-data-sources](https://github.com/junegunn/fzf/blob/master/ADVANCED.md#toggling-between-data-sources)

---

This is a significant quality of life enhancement.

**Comment by junegunn** [comment]
Thanks, I added the example to the page. I'll be releasing 0.45.0 soon.

**Comment by evbo** [comment]
What about supporting multiple states?

For instance, say I want to be able to toggle `fd --hidden` independently from `fd --max-depth #`?

In that case I'd store a boolean ("hidden") as well as integer ("depth"). Currently I'd need to encode both states into prompt, which gets messy. Is that my only option?
