### ISSUE TITLE
Reload command does not use the SHELL

### ISSUE THREAD

**Issue by avdv** [junegunn/fzf#3355]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf (`0.42.0 (d471067)`)
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

## Problem / Steps to reproduce

From reading the man page and looking at https://github.com/junegunn/fzf/issues/1750 I got the idea that one could use `FZF_DEFAULT_COMMAND` in the reload action, but that does not work like advertised:

```bash
export FZF_DEFAULT_COMMAND='echo "test"' SHELL=bash

fzf  --bind 'ctrl-r:reload:$FZF_DEFAULT_COMMAND' --preview 'echo $FZF_DEFAULT_COMMAND'
```

When run, this displays `test` in the result list. When hitting <kbd>ctrl-r</kbd> it displays `"test"` (including the quotes).

So in order to use the `FZF_DEFAULT_COMMAND` in reload you would have to pass it to the SHELL explicitly:
```bash
export FZF_DEFAULT_COMMAND='echo "test"' SHELL=bash

fzf  --bind 'ctrl-r:reload:$SHELL -c "$FZF_DEFAULT_COMMAND"' --preview 'echo $FZF_DEFAULT_COMMAND'
```

**Comment by LangLangBart** [comment]
> When run, this displays `test` in the result list. When hitting ctrl-r it displays `"test"` (including the quotes).

- try with `eval`
  - ref: [bash manual - eval](https://www.gnu.org/software/bash/manual/bash.html#index-eval)
  - ref: https://github.com/junegunn/fzf/issues/2887#issuecomment-1199258039 (29/Jul/22)

```sh
fzf  --bind 'ctrl-r:reload:eval $FZF_DEFAULT_COMMAND'
```



---

> So in order to use the `FZF_DEFAULT_COMMAND` in reload you would have to pass it to the SHELL explicitly:
> 
> ```shell
> export FZF_DEFAULT_COMMAND='echo "test"' SHELL=bash
> 
> fzf  --bind 'ctrl-r:reload:$SHELL -c "$FZF_DEFAULT_COMMAND"' --preview 'echo $FZF_DEFAULT_COMMAND'
> ```

- seems to be superfluous, because `fzf` already does that by using `$SHELL -c COMMAND`

```sh
man fzf
# FZF_DEFAULT_COMMAND
#   Default command to use when input is tty. On *nix  systems,  fzf runs the command
#   with $SHELL -c if SHELL is set, otherwise with sh -c, so in this case make sure
#   that the command is POSIX-compliant.
```
