### ISSUE TITLE
Feature Request: toggle-header

### ISSUE THREAD

**Issue by iloveitaly** [junegunn/fzf#3358]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

## Problem / Steps to reproduce
I'd love to be able to toggle the info line via a keyboard shortcut. Something like:

```
--bind='ctrl-i:toggle-info'"
```

**Comment by junegunn** [comment]
Can you explain why you need it?

**Comment by iloveitaly** [comment]
I'm using `git-fuzzy` and generally don't want the info section displayed because it takes up too much space. However, some times I _do_ want to be reminded of what shortcuts are bound to which keys and would like to hit a shortcut to see the info.

**Comment by junegunn** [comment]
> what shortcuts are bound to which keys

I'm not familiar with git-fuzzy, but what you're describing is not `info`, but `header`.

```sh
# Info: match counters, etc.
fzf
fzf --info inline
fzf --info right
```

```sh
# Header: arbitrary string to display
fzf --header hello
seq 100 | fzf --header-lines 5 --header-first
```

fzf provides `change-header` and `transform-header` actions, but no `toggle-header` at the moment.

**Comment by iloveitaly** [comment]
Got it, would be great if there was a `toggle-header`
