### ISSUE TITLE
ctrl-v paste from clipboard

### ISSUE THREAD

**Issue by 0xrz** [junegunn/fzf#3376]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

## Problem / Steps to reproduce

I cant understand how to make a keybinding for pasting data from the clipboard to the fzf prompt. Tried looking at man pages, as i understood it should look like something like this: `fzf --bind 'ctrl-v:transform‐query(xclip -o -selection clipboard)'`, but it says `unknown action: transform‐query(xclip -o -selection clipboard)`
Can you please hint me on how can i create this binding?

**Comment by LangLangBart** [comment]
- you are using a `HYPHEN (‐)` in `transform‐query`
  - Unicode character **U+2010**
  - https://util.unicode.org/UnicodeJsps/character.jsp?a=2010
- try again with a `HYPHEN-MINUS (-)` 
  - Unicode character **U+002D**
  - https://util.unicode.org/UnicodeJsps/character.jsp?a=002D

**Comment by 0xrz** [comment]
@LangLangBart oh yeah, that was the problem. I copied `transform‐query(...)` string from the man page, it had the wrong encoding.
Nevertheless, is `transform‐query` the only way to paste from clipboard to prompt? As it can't paste from clipboard the same content several times

**Comment by junegunn** [comment]
> As it can't paste from clipboard the same content several times

You can access the current query string via `{q}`, so you can append to it like so.

```sh
fzf --bind 'ctrl-v:transform-query:echo -n {q}; xclip -o -selection clipboard'
```

**Comment by masmu** [comment]
Just leaving this here for others to find.

The above-mentioned approach has the problem that you always append, regardless of where the cursor is currently located.

The following solutions insert your clipboard's content at the position where your cursor is currently located.

For X11 (untested):
```bash
fzf --bind 'ctrl-v:transform(echo "put($(xclip -o -selection clipboard))")'
```

For wayland (tested):
```bash
fzf --bind 'ctrl-v:transform(echo "put($(wl-paste))")'
```
