### ISSUE TITLE
I can't use fzf in autojump

### ISSUE THREAD

**Issue by lintiancheng01** [junegunn/fzf#3378]
- [ ] I have read through the manual page (`man fzf`)
- [ ] I have the latest version of fzf
- [ ] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [ ] fish

## Problem / Steps to reproduce
I install autojump and fzf. and i can use autojump and fzf in my terminal. but i can's use j() function, when i use the function, there is no directory in my terminal.
<img width="1249" alt="image" src="https://github.com/junegunn/fzf/assets/129168041/9e2b2cfb-2c1a-4c6a-93e6-4badfd11632e">

```sh
j() {
    local preview_cmd="ls {2..}"
    if command -v exa &> /dev/null; then
        preview_cmd="exa -l {2}"
    fi

    if [[ $# -eq 0 ]]; then
                 cd "$(autojump -s | sort -k1gr | awk -F : '$1 ~ /[0-9]/ && $2 ~ /^\s*\// {print $1 $2}' | fzf --height 40% --reverse --inline-info --preview "$preview_cmd" --preview-window down:50% | cut -d$'\t' -f2- | sed 's/^\s*//')"
    else
        cd $(autojump $@)
    fi
}
```

**Comment by junegunn** [comment]
It looks like you're asking for help debugging your script, but this issue tracker is for discussing the issues of fzf itself.

**Comment by eyalk5** [comment]
Out of scope, may help others.
```
cd $(autojump -s | sort -k1gr | awk -F : '$1 ~ /[0-9]/ && $2 ~ /^\s*\// {print $2}' | tr -d '\t' | fzf)
```
