### ISSUE TITLE
fzf-tmux rendered incomplete borders 

### ISSUE THREAD

**Issue by skyf0cker** [junegunn/fzf#3385]
<img width="1512" alt="image" src="https://github.com/junegunn/fzf/assets/32331521/8342f29a-1a85-431a-ad2e-24f71fbb019a">

- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

## Problem / Steps to reproduce

```shell
 ls | fzf-tmux -p
```

**Comment by skyf0cker** [comment]
https://github.com/sainnhe/tmux-fzf/issues/68

**Comment by junegunn** [comment]
* Try using a different font
* Or setting `RUNEWIDTH_EASTASIAN` environment variable to 0 or 1.

**Comment by skyf0cker** [comment]
Thanks for your prompt reply.
I tried both two methods, but neither works.
Is there a font that you recommand?

**Comment by junegunn** [comment]
Strange.

```sh
# Which version are you running?
fzf --version

# Is the border rendered correctly?
RUNEWIDTH_EASTASIAN=0 fzf --border

# Is the border rendered correctly?
RUNEWIDTH_EASTASIAN=1 fzf --border
```

**Comment by skyf0cker** [comment]
> Strange.
> 
> ```shell
> # Which version are you running?
> fzf --version
> 
> # Is the border rendered correctly?
> RUNEWIDTH_EASTASIAN=0 fzf --border
> 
> # Is the border rendered correctly?
> RUNEWIDTH_EASTASIAN=1 fzf --border
> ```

version: 0.42.0 (brew)
RUNEWIDTH_EASTASIAN=0: rendered correctly
RUNEWIDTH_EASTASIAN=1: rendered wrong

**Comment by skyf0cker** [comment]
<img width="1512" alt="image" src="https://github.com/junegunn/fzf/assets/32331521/94d8a9e3-4340-4ca4-86ec-0f7eb365aaf6">

<img width="1512" alt="image" src="https://github.com/junegunn/fzf/assets/32331521/9d21b2c0-2b71-4031-8705-8b9e904deaf8">
It rendered correctly with just fzf command but rendered wrong with fzf-tmux -p

**Comment by junegunn** [comment]
By doing so, the variable is not exported to fzf-tmux

```sh
ls | RUNEWIDTH_EASTASIAN=0 fzf-tmux -p

# Or
export RUNEWIDTH_EASTASIAN=0
ls | fzf-tmux -p
```

**Comment by skyf0cker** [comment]
> ```shell
> ls | RUNEWIDTH_EASTASIAN=0 fzf-tmux -p
> ```
<img width="881" alt="image" src="https://github.com/junegunn/fzf/assets/32331521/0570e236-4cd9-44a8-97a3-4b5f55c15294">
Looks like same

**Comment by junegunn** [comment]
Try adding `export RUNEWIDTH_EASTASIAN=0` to your shell configuration file and restart tmux altogether.

**Comment by skyf0cker** [comment]
> Try adding `export RUNEWIDTH_EASTASIAN=0` to your shell configuration file and restart tmux altogether.

<img width="1512" alt="image" src="https://github.com/junegunn/fzf/assets/32331521/66b9f9ef-ac74-4036-9268-42c9a52d3034">
alreay write `export RUNEWIDTH_EASTASIAN=0` to my `.zshrc` and create a new tmux session after killing all sessions, but still cannot work.

**Comment by junegunn** [comment]
Hmm, that's strange. Not sure why the variable is not propagated in your setup.

Well then, we can explicitly pass the variable like so in `fzf-tmux` script. Does this help in your case?

```diff
diff --git a/bin/fzf-tmux b/bin/fzf-tmux
index e891b78..ed255fc 100755
--- a/bin/fzf-tmux
+++ b/bin/fzf-tmux
@@ -192,6 +192,7 @@ if [[ "$opt" =~ "-E" ]]; then
 fi
 [[ -n "$FZF_DEFAULT_OPTS"    ]] && envs="$envs FZF_DEFAULT_OPTS=$(printf %q "$FZF_DEFAULT_OPTS")"
 [[ -n "$FZF_DEFAULT_COMMAND" ]] && envs="$envs FZF_DEFAULT_COMMAND=$(printf %q "$FZF_DEFAULT_COMMAND")"
+[[ -n "$RUNEWIDTH_EASTASIAN" ]] && envs="$envs RUNEWIDTH_EASTASIAN=$(printf %q "$RUNEWIDTH_EASTASIAN")"
 [[ -n "$BAT_THEME" ]] && envs="$envs BAT_THEME=$(printf %q "$BAT_THEME")"
 echo "$envs;" > "$argsf"
 
```

**Comment by skyf0cker** [comment]
> ```diff
> [[ -n "$RUNEWIDTH_EASTASIAN" ]] && envs="$envs RUNEWIDTH_EASTASIAN=$(printf %q "$RUNEWIDTH_EASTASIAN")"
> ```
<img width="1269" alt="image" src="https://github.com/junegunn/fzf/assets/32331521/9780975f-bc36-4527-b70b-052182ff375a">

This actually works. Thanks @junegunn

**Comment by dj1020** [comment]
I have exactly the same issue for a long while... Thanks god there is a solution now.
Thank U ❤️

**Comment by Mike20403** [comment]
how to fix this in Window
