### ISSUE TITLE
WSL ALT+C Ubuntu does not work

### ISSUE THREAD

**Issue by AddictArts** [junegunn/fzf#3388]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Windows
- Shell
    - [x] bash

## Problem / Steps to reproduce

Ubuntu 22.04
WIndows 11
WSL2

`$ fzf` then use ALT+C and nothing, does not change directory or anything else.

Used `source /usr/share/bash-completion/..../fzf` no change
Used `source /usr/share/doc/fzf/examples/key-bindings.bash` no change

**Comment by blayz3r** [comment]
ALT+C is ESC+C on windows, check bindkey | grep fzf

**Comment by AddictArts** [comment]
Thanks @blayz3r however ESC leaves or exits fzf. No bindkey command either.

**Comment by junegunn** [comment]
I answered to your question here: https://github.com/junegunn/fzf/discussions/3391#discussioncomment-6654517

It seems to me that you're not quite sure what fzf really is. I recommend that you read through the README page again, or watch this video: https://www.youtube.com/watch?v=qgG5Jhi_Els

**Comment by AddictArts** [comment]
Thanks @junegunn I appreciate the response. The video hardly shows this feature, also it seems to be an old version.

From the main page it says: Key bindings for command-line, CTRL+T, ALT+C, ...

I have tried Ubuntu and Debian, nothing works. I have read the README in /usr/share/doc/fzf. The README makes this all seem like it is fzf builtin. I can't get any of it to work though. The only thing that works is the ENTER key. So, yes I am way confused on how these advance elements are supposed to work. Thanks again.

**Comment by AddictArts** [comment]
Thanks @junegunn I appreciate the response.  I don't know how I missed that this is outside `fzf`. Use these key-bindings from the shell prompt. Also be sure to include them like sourcing the example in `/usr/share/doc/fzf/examples/key-bindings.<shell>`.

The wiki is likely fine, just confusion on how to use these key bindings.  I now have it, thanks again.
