### ISSUE TITLE
[Feature-request] Ability to change some options at run time

### ISSUE THREAD

**Issue by Guy-Shaw** [junegunn/fzf#339]
Some fzf command-line options would be really handy to be able to change at run-time, using some key binding.  The pager, 'less', has that ability for many of of its options, at least the ones that make sense to change in the middle of a session.  For example, I could start fzf and find out I have thousands of lines to select from, and only then do I realize that maybe I should have specified --extended so that I could use the more powerful expressions to winnow the results.  As fast as fzf is, I would rather change behavior right then, without leaving fzf.  Just about anything that controls search behavior might be appropriate to change on the fly.

-- Guy Shaw

**Comment by junegunn** [comment]
Why don't you just always use `--extended` mode? I personally don't see any reason not to use it :)
So I have this line in my .bashrc:

```sh
export FZF_DEFAULT_OPTS='--extended'
```

**Comment by Guy-Shaw** [comment]
Thanks, I think I will do that.
But that would lead one to wonder why it is an option, at all.

The option, '--extended', was offered merely as an example.
Another would be case-sensitive vs case-insensitive match.
I may realize, once I see what comes up on my screen, that I really could use case-insensitive matching.  But, no.  I didn't think of it, ahead of time.  Is there a notation, such as '(i:)' as in perl regular expressions to govern case-sensitivity per search?  It does not look like it.  Is there a way to toggle that option on the fly, even if it is for all matches?  It doesn't look like it.  So, either I run fzf, again, or I live with the options I got.  fzf is fast, but nothing is that fast.

**Comment by junegunn** [comment]
> But that would lead one to wonder why it is an option, at all

The option was added after the initial version of fzf was released. I just didn't want to break backward-compatibility, though I also believe it makes sense to make it a default.

Regarding case-sensitivity, fzf by default performs "smartcase" matching (inspired by "smartcase" option of vim). If a search term contains an uppercase character, it will become a case-sensitive term, if it doesn't, case-insensitive. This term-wise case-sensitivity of course works best when `--extended` is set. (e.g. `foo Bar` matches `Bar FOO`, but not `bar FOO`)

**Comment by junegunn** [comment]
Note that `--extended` became the default since 0.10.9 :)
I'm closing this as I don't think it's crucial to support dynamic change of options at the moment.

**Comment by davidsierradz** [comment]
Hi. Another interesting option to toggle is `--nth`. For example I start fzf with `--delimiter : --nth 4..` to perform a search only after a file name, like:
```
path/to/some.json:1:1: foo
another/path/to/other.json:1:1: foo
another/path/foo/other.json:1:1: bar
```
If I search for `foo`, this allows me to exclude the last line.

Maybe after launching fzf I decide to include the file path to better narrow (or expand) the search and would like to update options to `--nth ..` and be able to search all line. Do you think this is a valid use case? If not, feel free to ignore this. Thank you.
