### ISSUE TITLE
Include man pages in Linux release tarball? 

### ISSUE THREAD

**Issue by bfxfer** [junegunn/fzf#3390]
- [ ] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [ ] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

## Problem / Steps to reproduce

Is it possible to include the `man/` directory as part of the github release tarball?

In my typical environment, I don't have `sudo` access to install packages, and thus I use a script to download the latest release tarball from github, and stash the binary in `~/local/bin/`, and the man pages in `~/local/share/man/`.

But, `fzf` github releases only contains the exectuable, and not the man pages. It will be really useful if the `man/` directory from the source code is included the release tarball.

Thanks!

**Comment by bfxfer** [comment]
Perhaps [`files:`](https://goreleaser.com/customization/archive/#deep-diving-into-the-globbing-options) option in GoReleaser could help?

``` diff
diff --git .goreleaser.yml .goreleaser.yml
index 7f670da..cd509b1 100644
--- .goreleaser.yml
+++ .goreleaser.yml
@@ -100,6 +100,8 @@ archives:
       - goos: windows
         format: zip
     files:
+      - src: man/**
+        dst: man
       - non-existent*

 checksum:
```

**Comment by chdiza** [comment]
Yes, please.  For years now I've had to download not just the linux/macos compiled binary tarball, but also the source code tarball---the latter solely to get the man page.

**Comment by junegunn** [comment]
Simply replacing `non-existent` with `man` in the `files` list

```yaml
    files:
      - man/
```

generates tarballs with the man directory

```
$ tar -tf dist/fzf-0.42.0-devel-linux_arm64.tar.gz
man/man1/fzf-tmux.1
man/man1/fzf.1
fzf
```

However, I'm concerned that changing the structure of the tarballs after all these years might break user scripts that assume that it only contains the executable.

**Comment by nkh** [comment]
Just get the man page (and any other files you want) if you don't want to clone the repo. This way you can put that in your own makefile.


```
curl https://raw.githubusercontent.com/junegunn/fzf/master/man/man1/fzf.1 -o ~/local/share/man/fzf.1
```

**Comment by junegunn** [comment]
FWIW, you can put the version number in the URL.

```sh
curl "https://raw.githubusercontent.com/junegunn/fzf/$(fzf --version | awk '{print $1}')/man/man1/fzf.1"
```

**Comment by bfxfer** [comment]
> FWIW, you can put the version number in the URL.
> 
> ```shell
> curl "https://raw.githubusercontent.com/junegunn/fzf/$(fzf --version | awk '{print $1}')/man/man1/fzf.1"
> ```

Nice, wasn't aware of this. This trick is good enough for me. So, closing the issue.
