### ISSUE TITLE
Bind sequence of commands

### ISSUE THREAD

**Issue by ggVGc** [junegunn/fzf#340]
Currently, as far as I understand it's only possible to map a key to one command at a time. For my current use case, I need to do an `execute` followed by an `abort` from one keypress. Is this currently possible?

**Comment by junegunn** [comment]
Nope.

>  I need to do an execute followed by an abort

It's not what `execute` action is for. It's for executing some command **without leaving** fzf interface.
Any particular reason you don't want to do in the way we normally do with fzf?
```
out=$(some_input_command | fzf) && do_something_with "$out"
```

**Comment by ggVGc** [comment]
Well, actually the use case is that I need to exit fzf knowing which key was used to exit. So, actually what I am looking for is an `exit_with_output` or similar action. But sequence chaining would be useful anyway, I think.

**Comment by ggVGc** [comment]
Thanks, that's what I actually needed! :)
