### ISSUE TITLE
Remember last cursor's position?

### ISSUE THREAD

**Issue by tmpm697** [junegunn/fzf#3404]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

## Problem / Steps to reproduce

I have this setup for git tag `**`:
```
git --no-pager tag | awk '{print "\x1b[35;1mtag\x1b[m  " $1}' | fzf --expect=ctrl-u,ctrl-l,ctrl-m,ctrl-y,ctrl-h --bind=ctrl-u:accept,ctrl-h:abort
```
When I press `ctrl-u` to accept, I do:
```
git show $tag --color=always | less -R
```
Then after press `q` to exit `less` --> I call the script again `***` that would call the git with `fzf` from `**` again.

This time fzf will reset cursor position but --> I want it to put me to the last cursor position from `**`

I saw some potential option from fzf, but not success to get this to work basically I want to `execute(...)` a command to save the pos number (how to get this number?) when select candidate from `**` to a file, and then having `pos(...)` to bring the cursor pos back when I press q to exit less in `***`

Anyone have experience to achive this? Many thanks.

**Comment by LangLangBart** [comment]
> _command to save the pos number (how to get this number?)_

```sh
man fzf
# Also, {q} is replaced to the current query string, and {n} is replaced to  zero-based
# ordinal index of the line. Use {+n} if you want all index numbers when multiple lines
# are selected.
```

- save the current line number in a temporary file, e.g. `/tmp/line_no`

```sh
git --no-pager tag |
	awk '{print "\x1b[35;1mtag\x1b[m  " $1}' |
	fzf --bind 'ctrl-u:execute-silent:echo $(({n} + 1)) >/tmp/line_no'
```

- `load` the line position number 

```sh
if [[ -f /tmp/line_no ]]; then
	line_no=$(cat /tmp/line_no)
else
	line_no=1
fi
git --no-pager tag |
	awk '{print "\x1b[35;1mtag\x1b[m  " $1}' |
	fzf \
		--bind 'ctrl-u:execute-silent:echo $(({n} + 1)) >/tmp/line_no' \
		--bind "load:pos:$line_no"
```

- add a mechanism to delete the file when you are done with your script, e.g. 

``` sh
trap 'rm -f /tmp/line_no' EXIT
```

---

### execute


- it will be easier with `execute/execute-silent` and `FIELD INDEX EXPRESSION`

```sh
git --no-pager tag |
	awk '{print "\x1b[35;1mtag\x1b[m  " $1}' |
	fzf --bind 'ctrl-u:execute:git show {2} --color=always | less -R'
```

- if your window closes immediately when you press <kbd>⌃ Control</kbd> + <kbd>U</kbd>, this may be due to the LESS option `-F / --quit-if-one-screen` defined in your shell setup

<details>
 <summary><b>LESS example</b></summary>

```sh
# .zshrc

# <--------- Less---------- >
# g/ hilite-search - Highlight results when searching with slash key (/)
# w/ hilite-unread - Highlight first line after PgDn
# I/ IGNORE-CASE - Case insensitive search
# j/ jump-target=n - line/percent on the screen where the target line is to be positioned
# M/ LONG-PROMPT - Long prompts ("Line X of Y")
# mouse - Enables mouse input
# X/ no-init - prevent clearing the screen
# F/ quit-if-one-screen - auto exit if the file can be displayed on the screen
# K/ quit-on-intr - quit less immediately with ^C
# q/ quiet - be more quiet
# R/ RAW-CONTROL-CHARS - Raw color codes in output (don't remove color codes)
# s/ squeeze-blank-lines - Squeeze empty lines to one
# ~/ tilde - Don't show ~ symbols on lines after EOF
export LESS="--hilite-search \
--hilite-unread \
--IGNORE-CASE \
--jump-target=.5 \
--LONG-PROMPT \
--mouse \
--no-init \
--quit-if-one-screen \
--quit-on-intr \
--quiet \
--RAW-CONTROL-CHARS \
--squeeze-blank-lines \
--tilde"
```

- if this is the case you can `unset` your `LESS` environment variable

```sh
unset LESS; git --no-pager tag |
	awk '{print "\x1b[35;1mtag\x1b[m  " $1}' |
	fzf --bind 'ctrl-u:execute:git show {2} --color=always | less -R'
```

---

</details>

- instead of ` git --no-pager tag | awk ...`  consider using `git for-each-ref` (looks cleaner), e.g.

```sh
# see 'man git-for-each-ref' for more details
git for-each-ref --format='%(color:bold magenta)tag%(color:reset) %(refname:short)' refs/tags
```

---

> _Anyone have experience to achieve this? Many thanks._


- more resources: 
  - [ADVANCED.md](https://github.com/junegunn/fzf/blob/master/ADVANCED.md)
  - [junegunn/fzf-git.sh](https://github.com/junegunn/fzf-git.sh/blob/main/fzf-git.sh#L164)

--- 

> **Note**
If there is no real issue, just a problem of understanding, it is usually better to open a discussion.

**Comment by tmpm697** [comment]
Nice, thanks, side question: How can I do like `--bind 'ctrl-h:execute:LBUFFER="$LBUFFER{2}";{abort};zle redisplay'` --> I want to execute `ctrl-h` to execute `LBUFFER="$LBUFFER{2}"` then drop from fzf by `{abort}` and then do `zle redisplay`

Can I do that with `fzf`? Thanks.
@LangLangBart

**Comment by tmpm697** [comment]
I nee to preserve the output of that git command but if I put it to a variable like: `var=$(git <..> | fzf)` --> press `ctrl-u` won't work.

I can think of this issue dues to git will be spawn in  subshell and need smth to have it work? Any idea?

**Comment by LangLangBart** [comment]
>  _press ctrl-u won't work_ 

- `/dev/tty` does the trick

```sh
var=$(
	git for-each-ref --format='%(color:bold magenta)tag%(color:reset) %(refname:short)' refs/tags |
		fzf \
			--bind 'ctrl-u:execute:git show {2} --color=always | less -R  > /dev/tty'
)
```

- ref: #2579

**Comment by tmpm697** [comment]
> > _press ctrl-u won't work_
> 
> * `/dev/tty` does the trick
> 
> ```shell
> var=$(
> 	git for-each-ref --format='%(color:bold magenta)tag%(color:reset) %(refname:short)' refs/tags |
> 		fzf \
> 			--bind 'ctrl-u:execute:git show {2} --color=always | less -R  > /dev/tty'
> )
> ```
> 
> * ref: [Piping breaks preview #2579](https://github.com/junegunn/fzf/issues/2579)

Thanks, but when I try to press `ctrl-c` after `ctrl-u` --> very slow to go back to shell prompt --> expect to instant exit `fzf` and display shell prompt.

I tried to padding ` || zle redisplay` --> but this has no effect.

**Comment by tmpm697** [comment]
@LangLangBart If I have these lines:
```
vi test.txt
4 test1
3 test2
2 test3
1 test4
```
So when I do `cat test.txt | fzf --bind 'ctrl-u:execute-silent:echo $(({n} + 1)) >/tmp/line_no'` when I'm at line contain `test2` I'm at line number 2.

How can I instead using `$(({n} + 1)) ` --> how can I use the first number of the line, here is `3` in `3 test2` to save to `/tmp/line_no` --> assume all candidates numbered like above.

I can think of smth like:
```
cat test.txt | fzf --bind 'ctrl-u:execute-silent:'echo $current_line | awk -F' ' '{print $1}' >/tmp/line_no'
```
But I don't know if we how we can get content of line under current cursor? Many thanks.

**Comment by LangLangBart** [comment]
- you could use  positional replacement strings, for example `{2..}`

| Placeholder | Alias |
|  :----: |  :----: |
| `{}` |  current line  |
| `{2}` |  current line with positional field 2  |
| `{2..}` |  current line from the 2nd field to the last field |
| `{n}` |  zero-based ordinal index of the line |
| `{q}` | current query string |

```sh
# command below requires 'parallel', it is just for creating the sample input
# but you can see that 'parallel' also uses positional replacement with the '{1}'
# https://www.gnu.org/software/parallel/
parallel echo {1} test {2} ::: 1 2 3 :::+ 3 2 1
# 1 test 3
# 2 test 2
# 3 test 1

parallel echo {1} test {2} ::: 1 2 3 :::+ 3 2 1 | fzf --preview 'echo {2..}'
```

<img src="https://github.com/junegunn/fzf/assets/92653266/26d2a966-d8ad-4976-a311-fc8e4c9d6534" width="600">

**Comment by tmpm697** [comment]
I'm currently use fzf with `--bind 'load:+jump-accept'` --> I'm not able to save current post due to this option.

Is there a way to use jump-accept and save current option when user select use left keys?
