### ISSUE TITLE
Feature request: jump to specific line base on field number?

### ISSUE THREAD

**Issue by tmpm697** [junegunn/fzf#3406]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

## Problem / Steps to reproduce

Say I have 10000 lines of text and having this command:
```
cat file | nl -p | fzf -n 2..
```
This uses `nl` to numbering the first field, then search for a patern as normal, in the list returned by fzf that contains number `23` of the 1st field but current cursor is pretty far to nevigate it using `j/k`
```
19    pick me not
23    pick me       --> want to ctrl-23 to jump to this line directly
1229 pick me not
4322 pick me not
2212 pick me not
5831 pick me not
3322 pick me not
5112 pick me not
2266 current cursor --> cursor current on this pattern
```

--> So let user keep pressing `ctrl` key and have them to `ctrl-23` (keep pressing control and press 2 and then 3) to go to the line that contain `23` in its 1st field.

I think this is provide more way to quickly nevigate the correct line, we can have an option like:
```
--bind:load(jump<by-1st-field>)
```
1st field will be triggered combined with pressing `ctrl`, so when you release `ctrl` to type a searching pattern it should not affect at all.
1st should be number but can be what-ever-on-keyboard to nevigate line base on it.

**Comment by LangLangBart** [comment]
- have you experimented with `jump/ jump-accept` actions?
  - they allow to quickly jump to a desired line that is far from the current cursor position
  - some GIFs in this discussion [3281](https://github.com/junegunn/fzf/discussions/3281) (6/Jul/23)

**Comment by tmpm697** [comment]
> * have you experimented with `jump/ jump-accept` actions?
>   
>   * they allow to quickly jump to a desired line that is far from the current cursor position
>   * some GIFs in this discussion [3281](https://github.com/junegunn/fzf/discussions/3281) (6/Jul/23)

Thanks, very nice keybinding there, but how can I `--expect=ctrl-g --bind=ctrl-g:jump-accept`? --> This will not show any `jump` char. 

The case is I want to jump but need to do smth with the jump that accepted.

**Comment by junegunn** [comment]
I'd advise you to just type in the number to your query prompt

```sh
fzf --nth 2..,.. --tac --scheme=history --query 'pick 23' << EOF
19    pick me not
23    pick me
1229 pick me not
4322 pick me not
2212 pick me not
5831 pick me not
3322 pick me not
5112 pick me not
2266 current cursor
EOF
```

* Type `pick` to narrow down the list
* Add ` 23` to get the one you want
* Because `--nth` is set to `2..` and `1`, you can type in something like `^pick ^23` for better filtering.
    * If you want to allow queries like `23pick` as well, you'll have to change `--nth` to something like `2..,..`
        * `2..` for `^pick`
        * `..` for `23pick`

> Thanks, very nice keybinding there, but how can I `--expect=ctrl-g --bind=ctrl-g:jump-accept`? --> This will not show any `jump` char.

Looks like `jump-accept` is not compatible with `expect`; you have to "jump", then press ctrl-g `--expect=ctrl-g --bind=ctrl-g:jump`.

**Comment by tmpm697** [comment]
but how can i `jump` and `execute`? i want to select and if i press char to select candiate, i want to also `execute` a command, can i do that?

**Comment by tmpm697** [comment]
maybe another related question: how can i always show jump motion char? like always keep this `-bind 'load:jump-accept'` avail for user ready to jump.

and then support like above comment --> jump and execute.

you can exclude some chars that preserve for navigation like ^n/^p/^f/^b/^a/^e from motion to make it work?

I really want to quick navigate the candidate.
