### ISSUE TITLE
preview window text selection

### ISSUE THREAD

**Issue by maikelmeyers** [junegunn/fzf#3409]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

## Problem / Steps to reproduce

I know this is a duplicate from an issue (#1591) that was labeld with "wontfix" because it seems not to be needed for an interactive grep tool to select text in the preview window. But perhaps it becomes clearer how good this interactive grep feature is if you consider the following use case:

When you have integrated ripgrep for interactive live grepping (https://github.com/junegunn/fzf/blob/master/ADVANCED.md#ripgrep-integration), it often happens that you see something in the preview that you want to grep next. But this cannot be copied to the clipboard in order to copy it to the query-line. You have to enter it by hand. That is extremely awkward. The possibility to select text in the preview window would make interactive grepping much more comfortable.

**Comment by nkh** [comment]
@maikelmeyers

This may be due to the mouse taking over, you can use it to scroll the preview.

But I can grab text with the keyboard (I run Tmux over konsole) as you can see below. Interestingly I can select with the mouse in vim+fzf!

![screenshot_2023-08-24_03-41-52](https://github.com/junegunn/fzf/assets/45409/46f768d4-25ab-43f4-b99d-60f85192b756)

**Comment by junegunn** [comment]
* Disabling mouse support is one option (`--no-mouse`)
* If you're on tmux or screen, you can select the text in copy mode
* Open an editor using an execute binding without leaving fzf and copy the text inside it
```sh
rg --color=always --line-number --no-heading --smart-case "${*:-}" |
  fzf --ansi \
      --color "hl:-1:underline,hl+:-1:underline:reverse" \
      --delimiter : \
      --preview 'bat --color=always {1} --highlight-line {2}' \
      --preview-window 'up,60%,border-bottom,+{2}+3/3,~3' \
      --bind 'enter:become(vim {1} +{2})' \
      --bind 'ctrl-e:execute(vim {1} +{2})' # NEW
```

**Comment by maikelmeyers** [comment]
Great. Thanks! :)
