### ISSUE TITLE
Expose the default command or otherwise easily fall back to it

### ISSUE THREAD

**Issue by tupton** [junegunn/fzf#341]
It'd be great to expose the default command so you could define a default command that falls back to it easily:

``` zsh
export FZF_DEFAULT_COMMAND="git ls-tree -r --name-only HEAD || $FZF_INITIAL_COMMAND"
```

Or maybe even better: make it so that if the default command fails (has a non-zero exit status) it falls back to the initial default command?

The impetus behind this is so that if the default command changes (e.g. #310), we don't have to update our custom default commands.

**Comment by junegunn** [comment]
Thanks for the suggestion, but I'm not sure if it's really needed considering that the default command almost never changes. The only change in almost two years is the one you linked above, and even the change is not necessary if you don't have files in the current directory that start with dash. It's just a simple find command anyway and there's no reason to strictly follow it.

If we are going to do it, there are some things to consider.

> `export FZF_DEFAULT_COMMAND="git ls-tree -r --name-only HEAD || $FZF_INITIAL_COMMAND"`

1. This means that `$FZF_INITIAL_COMMAND` must be defined before `$FZF_DEFAULT_COMMAND`. Which can be confusing to the users. One more thing to learn.
1. `fzf.bash`, `fzf.zsh`, and `fzf.fish` will have to include the code for defining the variable. Then we have duplicates in the code base. One in go source, one for bash and zsh, and another for fish.
1. Instead, it is conceivable that we tell the user to define `$FZF_DEFAULT_COMMAND` with single-quotes and let fzf inject the variable. But that can also be a source of confusion. "Why is $FZF_INITIAL_COMMAND not working?" "Oh, you should have used single-quotes." Believe me, things like this happen quite often.

**Comment by junegunn** [comment]
Another thing, the default command is `find . -path '*/\.*' -prune -o -type f -print -o -type l -print 2> /dev/null | sed s/^..//` and you need `eval`.

```
> CMD="find . -path '*/\.*' -prune -o -type f -print -o -type l -print 2> /dev/null | sed s/^..//"
> $CMD
find: 2>: unknown primary or operator
> "$CMD"
-bash: find . -path '*/\.*' -prune -o -type f -print -o -type l -print 2> /dev/null | sed s/^..//: No such file or directory
> eval $CMD
```

**Comment by tupton** [comment]
You had me at "the only change in almost two years". :)

Thanks for the detailed description of what's going on here. I agree that a command that almost never changes is not worth all this hassle for, and your explanation of that hassle is clear to understand.

Thanks for taking a look!
