### ISSUE TITLE
Bug: --bind 'load:jump-accept' to respect --bind "load:pos:$num"

### ISSUE THREAD

**Issue by tmpm697** [junegunn/fzf#3414]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

## Problem / Steps to reproduce

just use two above options and you'll see that `jump-accept` will always display for the `head` of the list of candidates.

what to expect? the `position` is loaded before `jump-accept` to display.

Is this a bug? if not how to archive that?

**Comment by junegunn** [comment]
```sh
seq 1000 | fzf --bind 'load:pos:500' --bind 'load:+jump-accept'
```

https://github.com/junegunn/fzf/blob/11e56403dda81b2226c138606f02fd49a31a6cf4/man/man1/fzf.1#L1161-L1167
