### ISSUE TITLE
Fzf command with popup window in vim changes jumplist

### ISSUE THREAD

**Issue by Emilv2** [junegunn/fzf#3415]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues
- [x] I have fzf 0.30.0 or above
- [x] I have read through https://github.com/junegunn/fzf.vim/blob/master/README.md
- [x] I have read through https://github.com/junegunn/fzf/blob/master/README-VIM.md

## Info

- OS
    - [X] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] vim

## Problem / Steps to reproduce

When using a popup window with any fzf command the jumplist is modified, using full screen fzf commands with ! works correct. I tried looking into the `fzf.vim` code, but I can't pin it down. Is it an issue with fzf.vim or with vim itself?
```
:jumps
 jump line  col file/text
   6     1    0 .zsh_history
   5     1    0 code/linux/crypto/async_tx/Kconfig
   4 10544    0 .zsh_history
   3    12    0 code/linux/crypto/async_tx/Kconfig
   2     1    0 code/linux/certs/blacklist.c
   1    27    0 code/linux/crypto/async_tx/Kconfig
>  0     1    0 /* SPDX-License-Identifier: GPL-2.0-or-later */
   1     1    0 .vimrc
   2   350    0 .vimrc
   3   372    0 code/linux/certs/blacklist.c
   4     2    0 .vimrc
```
```
:Maps "or any other fzf.vim command
```
```
:jumps
 jump line  col file/text
  12     1    0 .zsh_history
  11     1    0 code/linux/crypto/async_tx/Kconfig
  10 10544    0 .zsh_history
   9    12    0 code/linux/crypto/async_tx/Kconfig
   8     1    0 code/linux/certs/blacklist.c
   7    27    0 code/linux/crypto/async_tx/Kconfig
   6     1    0 /* SPDX-License-Identifier: GPL-2.0-or-later */
   5     1    0 .vimrc
   4   350    0 .vimrc
   3   372    0 code/linux/certs/blacklist.c
   2     2    0 .vimrc
   1     2    0 /* Internal definitions for asymmetric key type
>
```

**Comment by junegunn** [comment]
Thanks, I can reproduce. This only seems to happen when we open fzf in a popup window.

```vim
" Jumplist unaffected
let g:fzf_layout = { 'down': '40%' }
let g:fzf_layout = { 'tmux': '-p90%,60%' }
```

**Comment by junegunn** [comment]
The problem is reproducible with `:FZF`, so you don't need to look into the code of fzf.vim project.

**Comment by junegunn** [comment]
This fixed it for me, but let me know if you still have the issue.
