### ISSUE TITLE
Context aware completion for ssh command

### ISSUE THREAD

**Issue by rebrendov** [junegunn/fzf#3416]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

## Problem / Steps to reproduce
1) Extend completion for ssh command so it offers matches based on the flags provided. 
2) Change completion behavior when username is provided as mentioned in [this](https://github.com/junegunn/fzf/discussions/3277) discussion.

Here's some demonstration of the old vs new behavior
***Old***
[![asciicast](https://asciinema.org/a/MAPO0csRAQ2Oo8IEpFrqt4af4.svg)](https://asciinema.org/a/MAPO0csRAQ2Oo8IEpFrqt4af4)
***New***
[![asciicast](https://asciinema.org/a/fIOUO20N8yRjDZnwuDLrBgbsM.svg)](https://asciinema.org/a/fIOUO20N8yRjDZnwuDLrBgbsM)

I already wrote a zsh implementation for personal use. If you think this behavior worth adding to the main repo I'll add implementations for bash and fish and create a pull request. Otherwise feel free to close this issue (I've read your comments on other PRs and know that you aim to keep complexity as low as possible).

**Comment by junegunn** [comment]
That looks great. Thanks for sharing.

> If you think this behavior worth adding to the main repo

It depends on the complexity of the code. Can you show me your code?

**Comment by junegunn** [comment]
This one?

https://github.com/rebrendov/fzf/commit/e243f87ccf27685d1a754f92abc3bdfa5908ca67

The code looks not too complicated and quite manageable. I think we can give it a try.
