### ISSUE TITLE
gvim xterm automatic same colors as colorscheme is broken

### ISSUE THREAD

**Issue by lydell** [junegunn/fzf#342]
The nice xterm customizations added in #212 are partly broken since commit 8fb31e1.

If you run `:FZF<cr>`, the xterm window opens as expected, with correct size, position and title, but the background color and text color are missing. Instead of getting the same colors as my colorscheme in vim I get xterm’s default colors. I suspect this has to do with there being a `#` in the hex color codes, but it might be a red herring.

**Comment by junegunn** [comment]
Ah, thanks for the report. Please update and try again.

**Comment by lydell** [comment]
Splendid! Thanks for the extremely quick fix.

**Comment by charlton1** [comment]
I think colours are still broken (at least for non-hex code colours). Please see the comment here:

https://github.com/junegunn/fzf/commit/ac160f98a8f5aa9ad148a7c6e694b10586652824?_pjax=%23js-repo-pjax-container

**Comment by junegunn** [comment]
This is old code. fzf no longer starts an external terminal emulator on the latest versions of GVim which can open terminal buffers inside it.

**Comment by charlton1** [comment]
Understood. I was just suggesting that a fix to this code would allow it to work (properly) with more versions of gvim.

**Comment by junegunn** [comment]
@charlton1 I see, thanks for the suggestion. Would you care to open a pull request?

**Comment by charlton1** [comment]
Hi Junegunn, I've issued a pull request as requested here: https://github.com/junegunn/fzf/pull/1634.

Thanks!
Charlton
