### ISSUE TITLE
Border label is not correctly centered when it includes unicode characters

### ISSUE THREAD

**Issue by carlfriedrich** [junegunn/fzf#3421]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

## Problem / Steps to reproduce

When I include unicode characters in my border label, it is not correctly centered:

```shell
echo -e "one\ntwo\nthree" | fzf --border=bottom --color=label:grey --border-label=' FOO ─── BAR ─── BAZ '
```

![grafik](https://github.com/junegunn/fzf/assets/45259958/358c5c74-de1c-4d9a-a138-b18c3acd5fda)

When I replace the unicode `─` with a simple hypen `-`, it is centered correctly:

```shell
echo -e "one\ntwo\nthree" | fzf --border=bottom --color=label:grey --border-label=' FOO --- BAR --- BAZ '
```

![grafik](https://github.com/junegunn/fzf/assets/45259958/013cc879-5de5-4c57-961a-b3e1658d3efc)

**Comment by junegunn** [comment]
Should be fixed now, thanks for the report.

**Comment by carlfriedrich** [comment]
@junegunn Thanks a lot for the quick fix! 🚀
