### ISSUE TITLE
Horizontal orientation of intermediate results

### ISSUE THREAD

**Issue by oxo-real** [junegunn/fzf#3423]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

## Problem / Steps to reproduce
 
Hi,

Is it possible to present the intermediate search results of fzf in transposed 'cells' in one line? 
Like how the default of [dmenu](https://tools.suckless.org/dmenu/) places its 'menus' in a horizontal bar?

Thank you!

oxo

**Comment by junegunn** [comment]
No, it's not possible. Adding support for horizontal display is a hell of a lot of work, so we don't have any plans to do it.
