### ISSUE TITLE
fe() example doesn't edit file when EDITOR contains option

### ISSUE THREAD

**Issue by Praful** [junegunn/fzf#3432]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

## Problem / Steps to reproduce
This is not an issue with fzf but one of the examples in the wiki. I appreciate they're maintained by the community. Please let me know where I should raise this question if it's not here.

There's an example of opening a file:
```
fe() {
  IFS=$'\n' files=($(fzf-tmux --query="$1" --multi --select-1 --exit-0))
  [[ -n "$files" ]] && ${EDITOR:-vim} "${files[@]}"
}
```
If EDITOR is set to 'gvim --remote', the follwing error occurs after picking a file:
```
fe:3: command not found: gvim --remote
```
This is fixed if I hardcode the editor in line 3:
```
[[ -n "$files" ]] && gvim --remote "${files[@]}"
```
My Linux scripting is not good enough to fix this to use the $EDITOR properly! What is the fix to stop me having to hardcode the editor and option?

**Comment by LangLangBart** [comment]
> This is not an issue with fzf but one of the examples in the wiki. 

- relevant comment by the maintainer ([link to comment](https://github.com/junegunn/fzf/issues/3367#issuecomment-1635457013) (14/Jul/23))
> [!IMPORTANT]  
> _**junegunn:**  ... the wiki needs an overhaul. The pages are written by the community, and sadly, there has been no quality control at all. I don't know which ones are working and which ones are not. But I just don't have time to go through the code._   

---

> _If EDITOR is set to 'gvim --remote', the follwing error occurs after picking a file:_
> fe:3: command not found: gvim --remote

-  `gvim --remote` is being treated as a single command, rather than `gvim` as a command and `--remote` as an option

---

#### idea 1:  set `EDITOR`  as an array
```sh
export EDITOR=(gvim --remote)

fe() {                            
  IFS=$'\n' files=($(fzf-tmux --query="$1" --multi --select-1 --exit-0))
  [[ -n $files ]] && "${EDITOR[@]:-vim}" -- "${files[@]}"                                    
}                          
```

#### idea 2: read `EDITOR` as string and create an `editor`  array
```sh
export EDITOR='gvim --remote'
# works in zsh, bash works with 'read -ra'
fe() {
 IFS=' ' read -rA editor <<< "${EDITOR:-vim}"
 IFS=$'\n' files=($(fzf-tmux --query="$1" --multi --select-1 --exit-0))
 [[ -n "$files" ]] && "${editor[@]}" -- "${files[@]}"
}
```

**Comment by Praful** [comment]
Thanks for the two ideas. The first one produces the same error. The second one is more hopeful. It opens, in gvim, the file selected but also a new (blank) buffer, which has the focus.

**Comment by junegunn** [comment]
Thanks @LangLangBart for the reply.

Regarding the wiki, maybe we should remove the pages so as not to confuse users and migrate the examples to a new separate repository (something like fzf-examples?) and start over with a tighter review process.

**Comment by LangLangBart** [comment]
> The complete function is now:
> 
> ```
> fe() {
>  IFS=' ' read -rA editor <<< "${EDITOR:-vim}"
>  IFS=$'\n' files=($(fzf-tmux --query="$1" --multi --select-1 --exit-0))
>  [[ -n "$files" ]] && "${editor[@]}" "${files[@]}"
> }
> ```

- adjusted with the use of:
  - [eval](https://www.gnu.org/savannah-checkouts/gnu/bash/manual/bash.html#index-eval),
  - `become` action introduced in version [0.38.0](https://github.com/junegunn/fzf/blob/master/CHANGELOG.md#0380) and 
  - the placeholder expression for all selected lines `{+}` 
- should work on `zsh/bash` 🍀 

```sh
export EDITOR='gvim --remote'
fe() {
  fzf-tmux --query "$1" --multi --select-1 --exit-0 \
    --bind "enter:become:$(eval echo "${EDITOR:-vim}") {+}"
}
```

**Comment by Praful** [comment]
Thanks again @LangLangBart for the updated function. I'm constantly surprised at FZF's features - it's a fantastic piece of software! 

Is it worth updating the wiki with your improved version?

There is an `fo()` function on the wiki which edits the file by default (like `fe()`) or opens the selection if `ctrl-o` is pressed.

```
# Modified version where you can press
#   - CTRL-O to open with `open` command,
#   - CTRL-E or Enter key to open with the $EDITOR
fo() {
  IFS=' ' read -rA editor <<< "${EDITOR:-vim}"
  IFS=$'\n' out=("$(fzf-tmux --query="$1" --exit-0 --expect=ctrl-o,ctrl-e)")
  key=$(head -1 <<< "$out")
  file=$(head -2 <<< "$out" | tail -1)
  if [ -n "$file" ]; then
    [ "$key" = ctrl-o ] && open "$file" || ${editor[@]} "$file"
  fi
}
```
Could this be updated using the new method?

**Comment by junegunn** [comment]
@Praful

> Is it worth updating the wiki with your improved version?

I think so, but then again I think we should find a better way to manage examples.

> Could this be updated using the new method?

Yes with an additional binding like so. The new `become` action can replace many simple use cases of `--expect`.

```sh
export EDITOR='gvim --remote'
fe() {
  fzf-tmux --query "$1" --multi --select-1 --exit-0 \
    --bind "enter:become:$(eval echo "${EDITOR:-vim}") {+}" \
    --bind "ctrl-o:become:open {+}"
}
```
