### ISSUE TITLE
Use "path" scoring scheme in the cd shell shortcut

### ISSUE THREAD

**Issue by astoff** [junegunn/fzf#3433]
I was struggling with some suboptimal sorting of candidates in the `Alt-c` shell shortcut until I added `FZF_ALT_C_OPTS='--scheme=path'` to my configuration. I would like to suggest to make this the default, i.e., add it here:

https://github.com/junegunn/fzf/blob/dc97d4849156f555ebdcf9f1703a5d3594468120/shell/key-bindings.bash#L47

Probably the same applies to `Ctrl-T`, but I don't use this one very often.

**Comment by junegunn** [comment]
> I was struggling with some suboptimal sorting of candidates

Interesting. Do you have many directories with spaces in their names?

**Comment by astoff** [comment]
I have a music folder, for instance.
