### ISSUE TITLE
Allow command history numbers to be hidden with Ctlr-R

### ISSUE THREAD

**Issue by Wilfred** [junegunn/fzf#3435]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

## Problem / Steps to reproduce

Press Ctrl-R, and observe numbers in the output:

```
> ls
  284/1646 +S
>  2011 ls
    1764  ls -a
```

These numbers seem to be output by `fc` here:

https://github.com/junegunn/fzf/blob/eb4bbf32948303e326a2791c6a875f32d7b5c97f/shell/key-bindings.zsh#L100

Would it be possible to opt-out of displaying these numbers? It feels like it's rarely useful, and it takes up precious horizontal screen space.

**Comment by LangLangBart** [comment]
```sh
man fzf
# ...
#       --with-nth=N[,..]
#              Transform  the  presentation  of  each  line  using  field index
#              expressions
# ...
# FIELD INDEX EXPRESSION
#       A field index expression can be a non-zero integer or a  range  expres-
#       sion ([BEGIN]..[END]). --nth and --with-nth take a comma-separated list
#       of field index expressions.
#
#   Examples
#       2..    From the 2nd field to the last field
# ...
      
export FZF_CTRL_R_OPTS="--prompt 'History > ' --with-nth 2.."
```

**Comment by Wilfred** [comment]
Thanks, I missed that option.

For future reference, this version gives the same prompt as the default Ctrl-R command:

```
export FZF_CTRL_R_OPTS="--prompt '> ' --with-nth 2.."
```

**Comment by LangLangBart** [comment]
> For future reference, this version gives the same prompt as the default Ctrl-R command:

- the command had not the desired effect for you ?

<img src="https://raw.githubusercontent.com/LangLangbart/ImagePool/812b7600238b009f41c917972e8837327b836fc6/storage/2023-09-13_02-22-33_ctrl_r.gif" width="800">

**Comment by junegunn** [comment]
You don't need to set `--prompt '> '` because that's the default. I think @LangLangBart was just trying to show you the possibilities of what you can do with the variable.

```sh
export FZF_CTRL_R_OPTS="--with-nth 2.."
```

This is what I have in my configuration.

```sh
export FZF_CTRL_R_OPTS="
  --preview 'echo {}' --preview-window up:3:hidden:wrap
  --bind 'ctrl-/:toggle-preview'
  --bind 'ctrl-t:track+clear-query'
  --bind 'ctrl-y:execute-silent(echo -n {2..} | pbcopy)+abort'
  --color header:italic
  --header 'Press CTRL-Y to copy command into clipboard'"
```

**Comment by junegunn** [comment]
@a-pav 

> I expect that `249 cd vsftpd` entry should remain pointed-at-to but within a new list which has 250 as its next, and 248 as its previous entry.

That's exactly how it's supposed to work. Not sure you're not getting the same result.

Here is a simpler example for demonstrating the behavior. Can you test if it works as expected?

```sh
# After you press space, 55 should still be pointed at.
seq 100 | FZF_DEFAULT_OPTS= fzf --query 55 --bind 'space:track+clear-query'
```
