### ISSUE TITLE
Feature request: provide way to self-update FZF 

### ISSUE THREAD

**Issue by Praful** [junegunn/fzf#3437]
- [X] I have read through the manual page (`man fzf`)
- [X] I have the latest version of fzf
- [X] I have searched through the existing issues

## Info

- OS
    - [X] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [X] zsh
    - [ ] fish

## Problem / Steps to reproduce

In the repo for the latest version of Linux Mint (21.2), the version of FZF is 0.29 - much older than the latest version. 

To update FZF, I download it then overwrite the Mint version. It's not burdensome but not as fast as something I came across recently. In `rclone` there is an option, `--selfupdate` and I thought that would be useful in other apps where updating using the native method of your chosen OS wouldn't work.

I appreciate there are lots of things to do but a `--selfupdate` would be a useful addition. Then when someone is logging an issue you could say "Make sure you have run `fzf --selfupdate` to reproduce the problem with the latest version`.

**Comment by junegunn** [comment]
Thanks for the suggestion.

rclone is quite different from fzf in that it can easily become obsolete and stop working if not kept up to date so having an option like `--selfupdate` makes sense. It's an exception in this CLI tool world. And I don't think such an option in fzf is a necessity.

If you want to manage fzf in your system without using a package manager, you can get it using `git clone` as shown on the README page.

```sh
git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
~/.fzf/install --all
```

To update,

```sh
cd ~/.fzf && git pull && ./install --all
```

You can define a shell function if you find yourself doing this often.

**Comment by Praful** [comment]
Thank you for taking the time to reply.

I'm sorry - I did read the README but missed the install bit. 

Thank you for providing an amazing utility - and vim-plug!

**Comment by jacobrreed** [comment]
```
# Auto update FZF
if git -C "$HOME/.fzf" rev-parse &gt;&gt; /dev/null 2&gt;&amp;1; then
    git -C "$HOME/.fzf" fetch &gt;&gt; /dev/null 2&gt;&amp;1
    commits_behind=$(git -C "$HOME/.fzf" log ..origin/master --oneline | wc -l)
    if [ "$commits_behind" -gt 0 ]; then
      git -C "$HOME/.fzf" pull &gt;&gt; /dev/null 2&gt;&amp;1
    fi
fi

```
I have this in my shell startup
