### ISSUE TITLE
Add --no-bin to the install script

### ISSUE THREAD

**Issue by hanoii** [junegunn/fzf#3438]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

## Problem / Steps to reproduce

I am adding fzf as part of a Dockerfile where I want the binary and the codebase as part of the image and not something that has to be downloaded lateron. The setup of the shell, however, has to be done when the container runs and the image is ussed.

I would like to have a --no-bin command that would allow me to avoid downloading the binary and only setup the shell.

**Comment by junegunn** [comment]
With the suggested option, there is a risk of setting up a version of the script that is not compatible with the binary the user separately maintains.

I suggest that you take a different approach.

* Put `./install --no-rc` in your Dockerfile. It will download the binary and create `~/.fzf.bash` file, but it won't touch the shell configuration files.
* Add `source ~/.fzf.bash` to your shell configuration file when the container starts

**Comment by hanoii** [comment]
Only if you update repo, in which case you wouldn't use the `--no-bin` option. It's an optional usage so those who uses it will know what todo with it. 

It's unfortunate you won't consider it, but thanks!

`./install --no-rc` in a Dockerfile will work for root, the user is created when the image starts as it can change per host. I still can work something out, I just figured it was a nice addition.

**Comment by junegunn** [comment]
I see, thanks for understanding.

If you actually read the file created by the install script (i.e. ~/.fzf.bash or ~/.fzf.zsh), you'll see that it's really simple. It modifies $PATH so that fzf binary is found, and loads two script files. That's it. The gist of it hasn't changed in years and is unlikely to change in the future. So you probably don't really need to rely on the install script.
