### ISSUE TITLE
fzf --ansi doesn't seem to respect 22m code

### ISSUE THREAD

**Issue by bschlenk** [junegunn/fzf#3441]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

## Problem / Steps to reproduce

`fzf --ansi` seems to ignore an escape code of 22m, which normally would [disable any previous bold/dim type codes](https://gist.github.com/fnky/458719343aabd01cfb17a3a4f7296797#colors--graphics-mode).

With this python script:

```py
def dim(s):
    return f'\033[2m{s}\033[22m'


def bold(s):
    return f'\033[1m{s}\033[22m'


for i in range(10):
    print(f'{dim("hello")}/{bold("brian")} something else')
```

If I run `python3 color-test.py` I get

<img width="202" alt="Screen Shot 2023-09-15 at 10 05 08 AM" src="https://github.com/junegunn/fzf/assets/1390303/cd88d187-c0a1-4258-a56b-85089697747e">

But if I run `python3 color-test.py | fzf --ansi`, each line is dim

<img width="216" alt="Screen Shot 2023-09-15 at 10 06 05 AM" src="https://github.com/junegunn/fzf/assets/1390303/1b436316-7aca-4754-8f59-22a803d8c9dd">

If I instead change dim to use `0m`, then the dim part works but the rest of the line is bold.

```py
def dim(s):
    return f'\033[2m{s}\033[0m'
```

<img width="219" alt="Screen Shot 2023-09-15 at 10 07 32 AM" src="https://github.com/junegunn/fzf/assets/1390303/6d5cd72b-5e80-477d-a22d-d9a9c855823b">

I'd rather not use `0m` because sometimes I'm using these formatting functions to bold text in the middle of a line that's already using a color, and `0m` will also cancel the color, while `22m` only cancels the bold.

**Comment by junegunn** [comment]
Thanks for the report. It should be fixed now.

**Comment by bschlenk** [comment]
Wow thank you for fixing so fast!
