### ISSUE TITLE
Error when using popup window layout

### ISSUE THREAD

**Issue by Hello-Linux** [junegunn/fzf#3442]
I have the same error with https://github.com/junegunn/fzf.vim/issues/1028

My fzf.vim is the newest for master and the vim version is 9.0,and has this problem not been fixed yet?
```
git log for fzf.vim
commit 937f430ce3cbba4afd17ae6209dd6f7f200ebf01 (grafted, HEAD -> master, origin/master, origin/HEAD)
Author: Junegunn Choi <junegunn.c@gmail.com>
Date:   Thu Sep 14 22:45:00 2023 +0900

    Add :Changes command
    
    Close #1478
    Close #1479
```

- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
   -  Linux for centos7

- Shell
    -  bash
## Problem / Steps to reproduce
![000](https://github.com/junegunn/fzf/assets/17851645/5bda500a-9624-44e1-aa40-0eb80b1fa185)

**Comment by junegunn** [comment]
Looks like some other plugin is getting in the way causing the problem. What is "AutoUpdate"?

Is the problem reproducible with the minimal configuration without other plugins?

```sh
vim -Nu <(curl https://gist.githubusercontent.com/junegunn/6936bf79fedd3a079aeb1dd2f3c81ef5/raw)
```

(https://gist.githubusercontent.com/junegunn/6936bf79fedd3a079aeb1dd2f3c81ef5/raw)
