### ISSUE TITLE
shell script interactiveness checks

### ISSUE THREAD

**Issue by calestyo** [junegunn/fzf#3445]
- [X] I have read through the manual page (`man fzf`)
- [X] I have the latest version of fzf
- [X] I have searched through the existing issues

## Info

- OS
    - [X] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [X] bash
    - [ ] zsh
    - [ ] fish

## Problem / Steps to reproduce

I've looked at the code of `completion.bash` and `key-bindings.bash`. Both (but AFAICS also the ones for the other shells) contain checks for whether the shell is interactive or not.

- Are these checks even necessary at all?<br>Completion should anyway only happen when the shell is interactive, so when a package installs `completion.bash` e.g. into `/usr/share/bash-completion/completions/fzf`, it should never get sourced anyway, when not interactive.<br>The same IMO for `key-bindings.bash`, which is probably sourced by `.bashrc`, which in turn is only executed for interactive non-login shells.
- One could argue that people might source it from `.profile`, which is also souced for non-interactive login shells. But then,... why does e.g. `key-bindings.bash` define `__fzf_select__()` before the check for interactiveness? Shouldn't that also only be defined if the shell is interactive?

I could try to provide a patch, if you tell me what you think should be done.

Cheers,
Chris.

**Comment by junegunn** [comment]
> Are these checks even necessary at all?

Probably not in most setups. But I don't think having another safety net is a problem. fzf is an extremely popular program that is used by many users with different skill levels with vastly different setups, so yeah, I think it helps.

> why does e.g. key-bindings.bash define __fzf_select__() before the check for interactiveness?

We needed to define it even in non-interactive shells so that the early tmux integration would work without having to load the scripts for interactivity. (`-ci` -> `-c`)

https://github.com/junegunn/fzf/commit/77d45cb17372045fb52e9d32562349d3fa083117

However, that is no longer the case because we use fzf-tmux script instead.

**Comment by calestyo** [comment]
> However, that is no longer the case because we use fzf-tmux script instead.

So… shouldn't we then move everything under the safety net?

**Comment by calestyo** [comment]
And as said… I think at least for the bash completion scripts it's likely unnecessary in practise... I mean it makes only sense to protect people from shooting into their own foot up to some certain level ;-)

**Comment by junegunn** [comment]
> So… shouldn't we then move everything under the safety net?

Yes. I just found it too. I had to dig through the git history to find out why it's bypassing the check. Would you mind opening a PR?

> I mean it makes only sense to protect people from shooting into their own foot up to some certain level ;-)

Fair enough. Please note that fzf can be installed by manually cloning the repo, so the files can be placed anywhere the user wants and they can make any mistake they want :)
