### ISSUE TITLE
use find's -type d,f,l

### ISSUE THREAD

**Issue by calestyo** [junegunn/fzf#3446]
- [X] I have read through the manual page (`man fzf`)
- [X] I have the latest version of fzf
- [X] I have searched through the existing issues

## Info

- OS
    - [X] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [X] bash
    - [ ] zsh
    - [ ] fish

## Problem / Steps to reproduce

I've looked at the code of `completion.bash` and `key-bindings.bash`. Both use e.g.:
```
find … -o \( -type d -o -type f -o -type l \) 
```
and the likes.

I think these could be shortened to `-type d,f,l`, which is however a GNU extension (to POSIX `find`). But I think you anyway use many GNU extensions, so that shouldn't matter.

If you agree, I could make a PR once you've merged #3444.

Cheers,
Chris.

**Comment by junegunn** [comment]
Thanks, but we can't do this because the find on macOS doesn't support that.

```
jg@:~/github/fzf (master)> find . -type d | wc -l
     342
jg@:~/github/fzf (master)> find . -type f | wc -l
    5149
jg@:~/github/fzf (master)> find . -type l | wc -l
       0
jg@:~/github/fzf (master)> find . -type d,f,l | wc -l
     342
jg@:~/github/fzf (master)> find . -type f,d,l | wc -l
    5149
jg@:~/github/fzf (master)> find . -type l,f,d | wc -l
       0
```
