### ISSUE TITLE
Non-zero exit status when no match is found

### ISSUE THREAD

**Issue by siadat** [junegunn/fzf#345]
I have written a [Tmux session finder](https://github.com/siadat/session-finder). It uses fzf to search for sessions and switch to them. If no session is found it will create a new session and uses the fzf's query to name it.

At the moment, the exit status is 0. I use `--print-query`, if the output of fzf is 2 lines then a match has been found (the query and the result), if the output is 1 line then no match has been found (only the query).

I thought it would be a good idea if fzf returns a non-zero status when user enters a query and presses Enters, but no match is found. Status 1 is used for Ctrl-C interrupts, I think we could use status 2 to indicate that no match has been found.

I would be glad to submit a patch for this. Let me know what you think.

**Comment by junegunn** [comment]
I like the idea of exit status 2. As you might have already guessed, the reason I made fzf exit with status zero in such case was to make it possible to tell if it was aborted or not. Exit status 2 still allows us to tell the difference and make it easier to write small scripts like `val=$(fzf) && vim "$val"` as we don't have to worry about getting an empty value. Technically, we are breaking backward compatibility here, but I think this is the right direction. The patch should be trivial so I'll do it myself later in the day.

- Interactive mode
- Filtering mode (`--filter`)
- Test cases

**Comment by junegunn** [comment]
I just checked the exit codes from `grep`, and realized that it exits with 1 when no match is found, and 2 on invalid options. Maybe we should follow the convention.

**Comment by junegunn** [comment]
Pushed the fix. I'll release the next version in a couple of weeks. Let me know if you have further comments. Thanks.

**Comment by siadat** [comment]
Thank you @junegunn!

**Comment by junegunn** [comment]
Hmm, I think we also should be able to differentiate between interrupt and error. Not sure which code should be used, but anything other than 2 will do at the moment.

**Comment by siadat** [comment]
I haven't run into a situation where it would be necessary yet, but that would be nice. Perhaps it could be used for debugging scripts that set fzf flags dynamically.
