### ISSUE TITLE
Please document --phony option

### ISSUE THREAD

**Issue by timkgh** [junegunn/fzf#3451]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [x] zsh
    - [ ] fish

## Problem / Steps to reproduce

The `--phony` option is not documented in either `fzf --help` or `man fzf`.

**Comment by lunar-starlight** [comment]
From the changelogs I found:
- In 0.19.0 `--phony` was added:
> - Added `--phony` option which completely disables search functionality.
>  Useful when you want to use fzf only as a selector interface. See below.
- In 0.25.0 it was renamed to `--disabled`

**Comment by timkgh** [comment]
Ah, this explains it, thanks. 
https://github.com/junegunn/fzf/blob/master/src/options.go#L1593

I was confused because I've seen scripts that use `--phony` and couldn't find much on what it meant.
