### ISSUE TITLE
Feature request: mouse scrolling pans the whole viewport

### ISSUE THREAD

**Issue by jez** [junegunn/fzf#3456]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Mac OS X
- Shell
    - [x] zsh

## Problem / Steps to reproduce

```
seq 1 1000 | fzf
```

If you run this (on a screen shorter than 1,000 lines :sweat_smile:) and use your mouse to scroll through the results, the effect will be that scrolling the mouse moves the selected item line by line:

Before scrolling:

```
  4
  3
  2
> 1
  1000/1000
>
```

After scrolling:

```
> 4
  3
  2
  1
  1000/1000
>
```

## Feature request

I would appreciate a feature like that moves the whole viewport when scrolling the mouse. It would work like how it works when clicking and dragging the scroll bar right now, where dragging the scrollbar leaves the `>` cursor at the same row, but pans the whole viewport:

```
  24
  23
  22
> 21
  1000/1000
>
```

^ This is what I imagine it would look like when scrolling with this option turned on.

I don't have any strong opinions on the option name. Maybe something like `--mouse-scroll-immediate` but again, I don't have a strong opinion.

- - - - -

As always, thank you for your work on this wonderful project.

**Comment by junegunn** [comment]
```sh
fzf --bind scroll-up:offset-up,scroll-down:offset-down --scroll-off=3
```

Please test it and let me know what you think.

**Comment by jez** [comment]
It's great thanks!
