### ISSUE TITLE
--listen server: curl invalid request method

### ISSUE THREAD

**Issue by step-** [junegunn/fzf#3466]
Linux with curl 8.2.1. After starting the fzf listen server with `fzf --listen 6266 2> /dev/null` I tried a `GET` request, which failed with 400 Bad Request.
Can someone please show me a working trace so I can understand if this is a local configuration issue or something else?  Thank you.

```
curl -v localhost:6266
* processing: localhost:6266
*   Trying [::1]:6266...
* connect to ::1 port 6266 failed: Connection refused
*   Trying 127.0.0.1:6266...
* Connected to localhost (127.0.0.1) port 6266
> GET / HTTP/1.1
> Host: localhost:6266
> User-Agent: curl/8.2.1
> Accept: */*
>
< HTTP/1.1 400 Bad Request
< Content-Length: 23
<
invalid request method
* Connection #0 to host localhost left intact
```

**Comment by junegunn** [comment]
Did you build fzf from the source?

**Comment by step-** [comment]
No, I just upgraded with vim-plug.

**Comment by step-** [comment]
fzf --version: 0.42.0 (d471067)

**Comment by step-** [comment]
I see.

**Comment by junegunn** [comment]
Some testing from users would be great before I release the new version. Not much feedback from #3372.

**Comment by step-** [comment]
I'm sorry but I can't help much with testing this feature. However, I can offer the following simple script to interactively query a server running in a terminal from a client running in another terminal. Maybe someone will be inspired and build a better tool.

Start the server in terminal 1: `fzf -m --listen localhost:4266`  
Start the script in terminal 2: `client-server.sh`  
Type your query and watch `client-server.sh` output JSON results interactively. The interface is rough:
- `<backspace>` deletes the previous character
  `<tab>` toggles selections (requires `-m` on server side)
- `<enter>` accepts selections, end server and client
  any other character is sent to the server.

Script `client-server.sh` (bash, curl, jq)

```sh
#!/usr/bin/env bash

while curl -s localhost:4266 && IFS= read -r -n1 c; do
	case $c in
		''        ) rq=accept ;;
		$'\u007f' ) rq=backward-delete-char ;;
		$'\t'     ) rq=toggle ;;
		*         ) rq="put($c)" ;;
	esac
	curl -XPOST -s localhost:4266 -d "$rq"
done | jq '{matches , selected , current, query} | .matches |= reverse'
```
