### ISSUE TITLE
fzf as an imported package?

### ISSUE THREAD

**Issue by siadat** [junegunn/fzf#347]
Hi. Is it possible to use the functionality of fzf directly inside my Go code, instead of running fzf externally and capturing its output?

**Comment by junegunn** [comment]
No. The code was written with the assumption that it will run as a short-lived standalone process, so there is no well-defined public API and there are stateful singletons that are not designed to be reused multiple times. It would be of course possible if we do some work, but I personally don't need it and want to keep fzf simple so it's not my priority.

**Comment by siadat** [comment]
@junegunn Thanks for the clarification!
