### ISSUE TITLE
FoxitReader can't use fuzzy completion

### ISSUE THREAD

**Issue by kdurant** [junegunn/fzf#3472]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

## Problem / Steps to reproduce
Running `FoxitReader **<Tab>`  can't prompt anything.

**Comment by junegunn** [comment]
See https://github.com/junegunn/fzf#supported-commands

**Comment by kdurant** [comment]
@junegunn Thank you very much.
I also want to ask you a related question.
```bash
_fzf_complete_notrigger() {
    FZF_COMPLETION_TRIGGER='' _fzf_complete
}
complete -o bashdefault -o default -F _fzf_complete_notrigger FoxitReader
```
How to display only files with pdf suffix when pressing <Tab>？

**Comment by junegunn** [comment]
Well, in that case, you have to follow the instructions in https://github.com/junegunn/fzf#custom-fuzzy-completion

You have to write a command that only lists pdf files. Something like this.

```sh
_fzf_complete_notrigger_pdf() {
  FZF_COMPLETION_TRIGGER='' _fzf_complete -- "$@" < <(
    find . -name '*.pdf'
  )
}
complete -o bashdefault -o default -F _fzf_complete_notrigger_pdf FoxitReader
```
