### ISSUE TITLE
fzf-tmux: empty command

### ISSUE THREAD

**Issue by acamso** [junegunn/fzf#3474]
- [x ] I have read through the manual page (`man fzf`)
- [x ] I have the latest version of fzf
- [x ] I have searched through the existing issues

## Info

- OS
    - [ x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x ] zsh
    - [ ] fish

## Problem / Steps to reproduce

fzf: `0.42.0 (d471067)`
tmux: `tmux 3.2a`

When executing `fzf-tmux`:

Line 154 creates empty var `tmux_win_opts`. Line 155 in `fzf-tmux` sets `tmux_win_opts` to `\;`. On line 166, `tmux \;` is evaluated which returns `empty command` and exit code 1.

**Comment by junegunn** [comment]
Thanks for the report. I can reproduce the problem on tmux 3.2.

FYI, this works fine on tmux 3.3.

```sh
$ tmux -V
tmux 3.3a

$ tmux \; ; echo $?
0

$ eval 'tmux \;' ; echo $?
0
```

**Comment by junegunn** [comment]
It should be fixed now. Please let me know if it doesn't work as expected. Thanks.

**Comment by acamso** [comment]
Works well - thanks!
