### ISSUE TITLE
[neovim] FZF command always reuses same window

### ISSUE THREAD

**Issue by azure-satellite** [junegunn/fzf#348]
When the fzf terminal window is closed, it always reuses the bottom right window, not the last one.

**Comment by junegunn** [comment]
Not reproducible for me. You might want to try again with a minimal vimrc with no other plugins or sophisticated configs.

**Comment by tarruda** [comment]
@azure-satellite can you also try the neovim/neovim#3309 branch with your current config? That PR fixes some problems with `termopen()` and could fix yours too.

**Comment by azure-satellite** [comment]
Sorry yeah @tarruda @junegunn it was my config
