### ISSUE TITLE
Ctrl-T binding for bash and zsh should optionally use the current command-line as the root directory for the recursive search

### ISSUE THREAD

**Issue by mcepl** [junegunn/fzf#3480]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [x] zsh
    - [ ] fish

## Problem / Steps to reproduce

This is basically reverse of https://github.com/junegunn/fzf/issues/2562

When I am in some random directory (e.g., `build/`) and I write on the command line:

```
$ ls ~/Books<Ctrl-T>
```

I would expect that fzf completion mechanism starts searching through `~/Books/` directory. It does in fish, but not in bash (and according to https://github.com/junegunn/fzf#fish-shell not in `zsh` as well), where it still searches through `pwd`.

Would it be possible to optionally make this completion work in bash in the same manner as described here (and how it works with `fish`), please?

For me currently it is the only reason why I cannot switch back to `bash`.

**Comment by junegunn** [comment]
[Like I said earlier](https://github.com/junegunn/fzf/issues/2562#issuecomment-1028488834), I don't know how to implement it on bash. If you know how to do it and if you think it doesn't significantly increase the complexity of the code, please open a pull request. Otherwise, `ls ~/Books**<tab>` is the way.

**Comment by junegunn** [comment]
Or you can,

```sh
bind -m emacs-standard '"\C-t": "**\C-i"'
```

(Granted, fuzzy completion on bash is limited in that it doesn't work for all commands)

**Comment by mcepl** [comment]
> [Like I said earlier](https://github.com/junegunn/fzf/issues/2562#issuecomment-1028488834), I don't know how to implement it on bash. If you know how to do it and if you think it doesn't significantly increase the complexity of the code, please open a pull request. Otherwise, `ls ~/Books**<tab>` is the way.

That just doesn’t display the fzf dialogue at all (and yes, I source `/usr/share/bash-completion/completions/fzf-key-bindings` from openSUSE fzf package `fzf-bash-completion-0.45.0-1.1.noarch`), but `cd ~/build ; ls ~/Knihy/fanfiction/**<Ctrl-I>` just gives me the standard bash message `Display all 3096 possibilities? (y or n)`.

**Comment by junegunn** [comment]
Closing because fuzzy completion handles the case as explained above and no one is opening a pull request.

https://github.com/junegunn/fzf?tab=readme-ov-file#setting-up-shell-integration
