### ISSUE TITLE
Bash completion for ssh hostname not working in version 0.43

### ISSUE THREAD

**Issue by georgexsh** [junegunn/fzf#3484]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

## Problem / Steps to reproduce

fzf is installed from homebrew, bash completion enabled by 

```
source "/usr/local/opt/fzf/shell/completion.bash"
source "/usr/local/opt/fzf/shell/key-bindings.bash"
```

after upgrade from 0.42 to 0.43, bash completion for ssh command  stop functioning:

given there is an `database.example.com` entry in `.ssh/known_hosts`, when entering:
```bash
ssh data<TAB>
```
expect bash complete to:
```bash
ssh database.example.com
```
but nothing happens.

however, this still works:
```bash
ssh **<TAB>
```

all works again when downgrading to 0.42.

**Comment by junegunn** [comment]
Thanks for the report. https://github.com/junegunn/fzf/commit/70c461c60bb1e2165a378e8ba0451b511c29b5cb should fix the issue.
