### ISSUE TITLE
Kitty protocol image support not working in wezterm

### ISSUE THREAD

**Issue by mgpinf** [junegunn/fzf#3486]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

## Problem / Steps to reproduce
* Open `wezterm`
* Run the following command in a directory containing images:
```
fzf --preview 'kitty icat --clear --transfer-mode=memory --stdin=no --place=${FZF_PREVIEW_COLUMNS}x${FZF_PREVIEW_LINES}@0x0 {}'
```
* Images do not get displayed in `wezterm` (which supports kitty protocol) while they get displayed in `kitty`

**Comment by kovidgoyal** [comment]
wezterm does not support the full kitty image protocol, in particular for this case it will be the lack of support for unicode placeholders.

**Comment by mgpinf** [comment]
Ok. Thanks for explanation. Closing the issue.
