### ISSUE TITLE
adapt to history file change

### ISSUE THREAD

**Issue by greg0ire** [junegunn/fzf#349]
I have [a tool](https://github.com/greg0ire/switch), that, among other things changes the history file when I switch from a project to another, using the `zsh` built in `fc -p`. When I do that, <kbd>Ctrl</kbd>+<kbd>R</kbd> does not work until I start a new terminal. Can this be fixed ? If not, how can I restart / reload fzf ?

**Comment by junegunn** [comment]
Hi, I use bash and I'm not familiar with `fc -p` from zsh. Can you provide a simple steps to reproduce the problem on vanilla zsh?

**Comment by greg0ire** [comment]
I tried but I can't… guess there must be something else in my tool that is reponsible for this bug. I'll reopen this if I find, sorry for the noise.

**Comment by junegunn** [comment]
No problem.
