### ISSUE TITLE
Visual Interruption in fzf Border Display

### ISSUE THREAD

**Issue by hasefumi23** [junegunn/fzf#3499]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux - WSL2(Ubuntu 22.04.3 LTS)
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

## Problem / Steps to reproduce

I've noticed a visual discrepancy when using fzf. Specifically, there appears to be an interruption in the border display during its execution. This is particularly evident in certain sections of the border.

![image](https://github.com/junegunn/fzf/assets/18630999/24de2090-9e39-4f18-8cf3-168a1ae1dc9d)

**Expected Behavior:** 
The border lines produced by fzf should present as continuous, without any interruptions.

**Actual Behavior:** 
The border lines manifest visible interruptions at particular junctions.

**Steps to Reproduce:**
1. Execute fzf in the terminal.
2. Observe the border lines and note the disruptions.

**Additional Context:**
I've undertaken various troubleshooting measures, such as changing the terminal font and ensuring fzf is updated to the latest version, but the issue persists.

**Comment by junegunn** [comment]
Have you tried setting `RUNEWIDTH_EASTASIAN` environment variable as suggested in the `--border` section of the man page?

Related: https://github.com/junegunn/fzf/issues/3258

**Comment by hasefumi23** [comment]
@junegunn Worked fine! Thanks for the quick reply!

![image](https://github.com/junegunn/fzf/assets/18630999/9b499f4b-3b2b-4007-81e0-52e2dc307e6b)
