### ISSUE TITLE
Slow indexing after login 

### ISSUE THREAD

**Issue by pietro-coretto** [junegunn/fzf#3500]
- [x] I have read through the manual page (`man fzf`)
- [x ] I have the latest version of fzf
- [ x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

## Problem / Steps to reproduce

The first time I use fzf after a fresh login it takes time to index files and dirs. This only happen the first time I use it in a login session. Then even if I shut down the terminal, the next time I open a terminal and I do 'CTRL + T' it immediately starts to find stuff. There is any method to ensure that this indexing is performed at login?

**Comment by junegunn** [comment]
See:
- #763
- #1284
- #2550

It's faster on the second run, not because fzf caches the result, but because your operating system has cached the structure of the file system.
