### ISSUE TITLE
Sending signal SIGTSTP (CTRL+Z) while running from a script causes hang

### ISSUE THREAD

**Issue by telychko** [junegunn/fzf#3501]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

## Problem / Steps to reproduce

When fzf operating from a script, CTRL-Z leads to hang terminal.

## Steps to reproduce:
1. Run script `test.sh` below from the home directory.
2. Hit CTRL-Z

Terminal will hang

$ fzf --version
0.43.0 (d3311d9f)

\>\>\> test.sh
```
#!/bin/bash

fzf
```

**Comment by junegunn** [comment]
Thanks, I can reproduce the problem. FWIW, you can press CTRL-Z again to unfreeze the terminal.

**Comment by telychko** [comment]
> Thanks, I can reproduce the problem. FWIW, you can press CTRL-Z again to unfreeze the terminal.

Good to know. Double CTRL-Z works. Thank you.

**Comment by junegunn** [comment]
70c19ccf16a0f8ef2d0ef8ef44f69dd72aa210b1 fixes the problem.
