### ISSUE TITLE
`--bind=ctrl-i` and `--bind=tab` always conflict, binding one seems to also bind the other

### ISSUE THREAD

**Issue by Kache** [junegunn/fzf#3502]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

## Problem / Steps to reproduce

```sh
fzf --bind=ctrl-i:toggle-preview,tab:up --preview="cat {}"
```

Expect to be able to toggle preview with `ctrl-i` and move selection up with `tab`, but both binds do `up`.

The inverse happens with:

```sh
fzf --bind=ctrl-i:up,tab:toggle-preview --preview="cat {}"
```

Have repro'd this with both 0.42.0 (latest on osx homebrew) and 0.43.0 arm binary for osx from releases page.

**Comment by LangLangBart** [comment]
occurs also with <kbd>⌃ Control</kbd> + <kbd>M</kbd> and <kbd>⏎ Enter</kbd> bindings

```bash
fzf --bind=ctrl-m:up,enter:toggle-preview
```

**Comment by Kache** [comment]
Oh, I didn't realize `tab` and `^i` were terminal synonyms. Unfixable, then?

**Comment by junegunn** [comment]
Nothing we can do about it.

https://unix.stackexchange.com/questions/563469/conflict-ctrl-i-with-tab-in-normal-mode
