### ISSUE TITLE
Feature request: support fzf init <shell> initialization

### ISSUE THREAD

**Issue by akdevservices** [junegunn/fzf#3505]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

## Feature request

Support `fzf init <shell>` initialization (like in starship, zoxide, navi etc) to facilitate fzf integration with other tools (file managers, utilities etc) because this style of initialization doesn't require knowledge about key-bindings and completion file paths (which can vary in different packages), fzf will generate apropriate files by itself. Such an approach also cleans up shell rc files. Instead of:
```
source /usr/share/fzf/completion.bash
source /usr/share/fzf/key-bindings.bash
```
only one line of code is required:
```
eval "$(fzf init bash)"
```
For backward compatibility reasons, the feature implementation can just output existing key-bindings and completion files to stdout. `completion` and `keybindings` parameters can be supported to get `completion.<shell>` or `key-bindings.<shell>` implementations separately:
```
eval "$(fzf init bash completion)"
eval "$(fzf init bash keybindings)"
```

**Comment by mcepl** [comment]
Hasn’t this been actually accomplished in https://github.com/junegunn/fzf/tree/0.48.0 with `fzf --fish` command?

**Comment by akinomyoga** [comment]
For cross reference, I've partially answered to the questions in https://github.com/akinomyoga/ble.sh/discussions/441#discussioncomment-9209074.

> Hasn’t this been actually accomplished in https://github.com/junegunn/fzf/tree/0.48.0 with `fzf --bash` command?

Yes, I guess this issue can be closed now.

> And related question: what is the purpose of these files in `shell/` directory at all?

For the *finer control* mentioned in README, cf

- https://github.com/junegunn/fzf?tab=readme-ov-file#setting-up-shell-integration
- https://github.com/junegunn/fzf/pull/3722#issuecomment-2048594050
