### ISSUE TITLE
how to use fzf-tmux --bind 'enter:become' in bash script ?

### ISSUE THREAD

**Issue by lauccode** [junegunn/fzf#3506]
- [ X] I have read through the manual page (`man fzf`)
- [ X] I have the latest version of fzf
- [ X] I have searched through the existing issues

## Info

- OS
    - [ X] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ X] bash
    - [ ] zsh
    - [ ] fish

## Problem / Steps to reproduce

I'm looking to use script with `--bind 'enter:become(echo {1} {2})'`  
{1} is for path of file {2} is for line number.  
The script is called from editor (kakoune) and the previous command of script allow to retrieve the information of fzf to be retrieved in the editor.  

It is working well with only one argument `--bind 'enter:become(echo {1})'`.  Because with editor, it doesn't care to have the command `:e 'path_n_fileName'` rather that `:e path_n_fileName`  
With both arguments, it is the same, I can see that the command is sending `'path_n_fileName 13'` rather that `path_n_fileName 13`. But because of that, the editor can not work with several arguments sent.  
It is not working because of the extra character added `'`.  
I tested just in the editor that it is working by hand with `:e path_n_fileName 13` and not with `:e 'path_n_fileName 13'`.  

Is there a way to do it working without the extra character added ?

**Comment by LangLangBart** [comment]
- it may work with `eval` (I dind not test it with kakoune)
	- Ref: https://github.com/junegunn/fzf/issues/3432#issuecomment-1712095646

**Comment by lauccode** [comment]
I tested with `--bind 'enter:become(eval echo "{1} {2}")'` or `--bind 'enter:become(eval echo {1} {2})'` but I get the same issue.  
Also with `--bind 'enter:become:$(eval echo "{1}") {2}'` and `--bind 'enter:become:$(eval echo "{1} {2}")'`  

Here I just need to get the echo of `path + line`. No need to manage the editor. I just have very basic knowledge of bash. Please, let me know correct syntax if you have an idea.

**Comment by junegunn** [comment]
> With both arguments, it is the same, I can see that the command is sending `'path_n_fileName 13'` rather that `path_n_fileName 13`.

`echo {1} {2}` evaluates to `echo 'first' 'second'`. You can confirm this by quoting the whole command like so.

```sh
$ echo foo bar | fzf-tmux -p --bind 'enter:become(echo "echo {1} {2}")'
echo 'foo' 'bar'
```

I think you can use printf here to reformat the arguments.

```sh
echo foo bar | fzf-tmux -p --bind 'enter:become(printf "%s %s" {1} {2})'
```

**Comment by lauccode** [comment]
with 'enter:become(printf "%s %s" {1} {2})' I get : `'hello.cpp 3'`
with 'enter:become(echo "echo {1} {2}")' : `'echo 'hello.cpp' '3''`
with 'enter:become(echo "{1} {2}")' : `''hello.cpp' '3''`

**Comment by junegunn** [comment]
It looks like your script is not properly handling the output of fzf. I can't help you with that.
