### ISSUE TITLE
Local compile should not fetch from ustream repo!

### ISSUE THREAD

**Issue by alerque** [junegunn/fzf#351]
If I checkout the repo and build the source from my working directory there is no excuse for the makefile and other related scripts to make a bunch of requests to download files out of a hard coded github path to the upstream repo. The files are sitting there local to my working directory and I may have modifications I want them to use. Changing the source code locally and recompiling only to find that it's using source code from the upstream github repo is disturbing to say the least.

**Comment by junegunn** [comment]
See:
- http://golang.org/doc/code.html#Organization
- https://golang.org/cmd/go/#hdr-Relative_import_paths
    - `To avoid ambiguity, Go programs cannot use relative import paths within a work space.`

**Comment by alerque** [comment]
I'm not very familiar with Go as a language but I believe you are reading the documentation wrong. Higher up on the page it states:

> The toolchain supports relative import paths as a shortcut in two ways.

Then it goes on to detail those two ways. Those ways cover what needs to be fixed in this project.

The line you quoted is not related to the issue I am raising here. I am not asking for relative paths _within a workspace_, I am suggesting that paths be relative _to_ the current workspace. They can be full/absolute paths relative to the workspace root as required by that documentation, but they should not include an absolute path to an online copy of the repository when referencing from inside that repository.

**Comment by junegunn** [comment]
Nah, you're still not getting the point. Try to be familiar with how usual Go projects are laid out first. By "workspace", they mean $GOPATH which holds all the go projects that can point to each other, not just the current repository, which is clearly stated in the first link I gave you.

> Those ways cover what needs to be fixed in this project.

No.
1. `can be used as a shorthand on the command line.` - Not relevant
2. `compiling a Go program not in a work space`, `such programs cannot be installed with "go install"`

Using relative import path is strongly discouraged and it breaks go toolchain. Like it or not, it's Go.

Check out some other go projects:
- https://github.com/docker/docker
- https://github.com/pingcap/tidb
- https://github.com/spf13/hugo
