### ISSUE TITLE
zero event causes a hang when pasting a long string that triggers multiple events

### ISSUE THREAD

**Issue by ibhagwan** [junegunn/fzf#3516]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

## Problem / Steps to reproduce

Bind the zero event (I added the `mkdir` part as an attempt to make the operation atomic):
```sh
fzf --bind="zero:execute-silent(mkdir '/tmp/fzf-lua-zero' && echo foo)"
```

Paste a long string  **which has no matches and triggers the zero event**, in the example below I attemp to paste `verylongstring1234567890verylongstring1234567890`, more often than not, the interface will hang randomly and will require a process kill:
![image](https://github.com/junegunn/fzf/assets/59988195/52ea1d09-25ae-495c-874e-bb7594698c47)

ref issue: https://github.com/ibhagwan/fzf-lua/issues/909

**Comment by junegunn** [comment]
Thanks, cd6788a should fix the issue.
