### ISSUE TITLE
Using vim list as source in pwsh will cause 'Command failed: type .....'

### ISSUE THREAD

**Issue by kevyuu** [junegunn/fzf#3517]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [ ] Mac OS X
    - [x] Windows
    - [ ] Etc.
- Shell
    - [x] pwsh
    - [ ] bash
    - [ ] zsh
    - [ ] fish

## Problem / Steps to reproduce

Type :call fzf#run({'source':['test1', 'test2']}) in neovim. 
Error output:
![fzf](https://github.com/junegunn/fzf/assets/7076807/9c0de207-daad-42a4-8712-f60158cc080f)

**Comment by kevyuu** [comment]
setting $env:SHELL to cmd.exe fix the issue. Seems like there is logic error when escaping the path.

**Comment by harshad1** [comment]
This happens to me _intermittently_. Closing vim and reopening it sometimes fixes the issue. (Perhaps something to do with the temp file name?)

I have as yet not found a way to consistently 

- [ ] reproduce it.

**Comment by junegunn** [comment]
Can you update fzf and fzf.vim to the latest and check if it helps?
