### ISSUE TITLE
How to customize prompt color?

### ISSUE THREAD

**Issue by cohml** [junegunn/fzf#3527]
Is it possible to change the default color of the prompt only? I'm seeing a nice blue, but wondering if others are possible, and can't find this addressed anywhere. Here is what I see currently:

![image](https://github.com/junegunn/fzf/assets/62400541/45797ed3-6688-4e21-aadb-d33116b61c8a)

- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [x] Mac OS X

- Shell
    - [x] zsh

**Comment by junegunn** [comment]
See `--color` section of the man page.

```sh
fzf --color prompt:red
```
