### ISSUE TITLE
Requesting special history search feature: If matching zero, upon entry don't nuke my command, emit it.

### ISSUE THREAD

**Issue by unphased** [junegunn/fzf#3528]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [x] Mac OS X
    - [x] Windows
    - [x] Etc.
- Shell
    - [x] bash
    - [x] zsh
    - [x] fish

## Problem / Steps to reproduce
Typical workflow is I first hit Ctrl+R to do a history search. I type a command, and it _turns out after all_ that i've never run that particular command yet on the system (or it hasn't made its way into that particular shell instance's history buffer). At this point I have lost the work I've put into typing this buffer if I'm not careful. Hitting enter on a fzf search with 0 results yields nothing, which nukes my command I typed. Same thing happens if we cancel instead of accept by hitting ctrl+c, query is nuked.

So i hope to implement a special behavior in the case of acceptance on zero results to just emit the query instead of nothing. Can this be done? 

I am aware that semantically speaking this is sloppy because we're in a history search buffer and why are we typing a whole command intended for execution, well I've accepted that humans aren't naturally driven by logic truly, which is why we all have jobs as software makers anyhow. So this has become a bit of a rough edge for me. Couldn't have gotten here without fzf being such an essential part of the workflow too.

**Comment by junegunn** [comment]
Would it help to have an `accept-or-print-query' action (tentative naming) so you could bind it to the Enter key?

```shell
export FZF_CTRL_R_OPTS='--bind enter:accept-or-print-query`

**Comment by unphased** [comment]
for sure that should work! Thank you so much for looking into this :D

**Comment by junegunn** [comment]
Hmm, on second thought, I realized that this is already possible with `become`.

```sh
export FZF_CTRL_R_OPTS='--bind "enter:become:if [[ -n {} ]]; then echo {}; else echo {q}; fi"'
```

However, `become` is not supported on Windows, so I'm going to keep the new action. The implementation is quite simple so it doesn't hurt to have it.

**Comment by AlexanderYastrebov** [comment]
The suggested snippet works when there are no matches in the history.
I often find that there are wrong matches only and I want to cancel search but keep the input.
Is it possible to do that?

I think CTRL+C should keep the input by default if possible - user may hit CTRL+C once again to clean if they want to.

**Comment by unphased** [comment]
@AlexanderYastrebov Agreed, this would be the next sharpest edge to polish. In my experience though it's been fluid enough for me to hit enter to take one of those choices and edit it. Reason being at least 85% of the time the way I got those results surfaced involved a fuzzy entry into the query box. So there is usually incentive to grab one full command and edit it. 

It does look like enhancing the ctrl+c behavior would be ideal though. We can keep Esc to do as it does now. Or flip them around, which would make ctrl+c more consistent at wiping out what you typed.

**Comment by junegunn** [comment]
Why don't use just bind `CTRL-C` to `become`?

```sh
export FZF_CTRL_R_OPTS='--bind "ctrl-c:become:echo {q}"'
```

However, I keep thinking that I don't want to suggest this approach to the users because as @unphased mentioned above, we're typing in a special fuzzy matching syntax instead of a full command in the prompt, something like`gitch-b !comm`. 

Also, https://junegunn.github.io/fzf/search-syntax/#how-to-get-better-results

**Comment by AlexanderYastrebov** [comment]
@unphased @junegunn Thanks for replies. `bind ctrl+c` snippet does what I wanted but I also get the point of fuzzy syntax.

**Comment by unphased** [comment]
nice. I take it we would be able to do what I suggested above by binding `become` to Esc.
