### ISSUE TITLE
can someone explain --nth and --with-nth. It (seemingly?) does not behave as documented.

### ISSUE THREAD

**Issue by alfonz19** [junegunn/fzf#3529]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

## Problem / Steps to reproduce

Can someone explain --nth and --with-nth as it does not seem to work as documented, or I totally don't understand it. I read several issues on this topic, still have no clue, why it behaves like this.

- --n-th

-n, --nth=N[,..]
              Comma-separated  list  of  field  index expressions for limiting
              search scope.  See FIELD INDEX EXPRESSION for the details.

`echo "1,2,3,4,5" | fzf -d "," --nth 1` --> single selection `1,2,3,4,5`
`echo "1,2,3,4,5" | fzf -d "," --nth 2` --> single selection `1,2,3,4,5`
`echo "1,2,3,4,5" | fzf -d "," --nth 2,3` --> single selection `1,2,3,4,5`
`echo "1,2,3,4,5" | fzf -d "," --nth 666` --> single selection `1,2,3,4,5`

should this behave like this?

--with-nth

`echo "1,2,3,4,5" | fzf -d "," --with-nth "2"` --> single selection `2,`
`echo "1,2,3,4,5" | fzf -d "," --with-nth "2..3"` --> single selection `2,3,`

if comma is delimiter, why it's part of output??? I understood, that it was said somewhere that delimiter is regex and not single char as explanation, but I don't understand how is this relevant. It was also explained that this is intended for simple cases only, where I asked for single column, but this is my case actually, I want only single column without delimiter.

IIUC documentation correctly, command:

`echo "1,2,3,4,5" | fzf -d "," --with-nth "-2"` should return single selection of `4`.

If not, what it should return and why is delimiter not behaving like delimiter? If this is valid, I think the documentation should give explanation what is expected to be returned and why.

If there is know workaround, please suggest. `tr ',' ' '` is not sufficient, as this causes information loss or expected expensive `tr ' ' '<forbiddenSymbol>' | tr ',' ' ' | fzf ... | tr ' ' ',' | tr '<forbiddenSymbol>' ' '`

**Comment by junegunn** [comment]
@LangLangBart Thanks for the detailed answer.

---

`--nth` doesn't affect how the items are displayed inside fzf. It only affects the search scope.

---

> if comma is delimiter, why it's part of output???

`--with-nth` can be used to reorder the columns.

```sh
echo "1,2,3,4,5" | fzf -d "," --with-nth 2,1,5
  # Prints "2,1,5"
```

In this case, we can't simply remove the delimiters. One would argue that we can just put `,` characters between the tokens, but we can't take the same strategy when `--delimiter` is specified as a regular expression. 

I know the situation is not ideal, but I couldn't find a better solution that doesn't complicate the option or break the backward compatibility.

Anyway, pre-processing the list gives you the most flexibility.

```sh
# Use awk to preprocess the input while retaining the original text before the tab character
# Use --with-nth not to display the original text before the tab character
echo "1,2,3,4,5" | awk -F, -v OFS=, '{print $0 "\t" $3, $1, $2}' | fzf -d "\t" --with-nth 2.. --bind 'enter:become:echo {1}'
```
