### ISSUE TITLE
Integrating with plugins that expect autochdir to not be altered

### ISSUE THREAD

**Issue by ianks** [junegunn/fzf#353]
I also use the Vim-Filer plugin to browse a source tree (nerdtree like behavior). However, it does not work if the `autochdir` option is set. Are there any known workarounds for this issue?

**Comment by junegunn** [comment]
`:FZF` command does unset `autochdir` when opening files but it *restores* the original value immediately. So what exactly is the problem?

**Comment by ianks** [comment]
```
[vimfiler] Detected autochdir!                                                                                                                                                
[vimfiler] vimfiler don't work if you set autochdir option. 
```

This is the error message I get from vim-filer.

Here are the conditions which make this error display:

```vim
  if exists('+autochdir') && &autochdir
    call vimfiler#util#print_error(
          \ 'Detected autochdir!')
    call vimfiler#util#print_error(
          \ 'vimfiler don''t work if you set autochdir option.')
    return
  endif
```

EDIT: Update, it was not FZF that caused this condition. I grepped my plugin dir for any references to autochdir and fzf was the only plugin that used that code. However, apparently neovim has set autochdir somehow, but vim does not. Sorry for the confusion.

**Comment by justinmk** [comment]
Neovim does not set autochdir. What does `:verbose set autochdir?` report?

**Comment by ianks** [comment]
@justinmk It reports `autochdir`

For some reason, everything works fine on Vim, but not Neovim.

**Comment by justinmk** [comment]
That doesn't make sense. The vim-filer code you mentioned applies to Vim and Neovim: https://github.com/Shougo/vimfiler.vim/blob/b1e5417b1ad351a69dd66027c8b521fe83246634/autoload/vimfiler/init.vim#L373

Are you intentionally setting the option in your n/vimrc, or not?

**Comment by ianks** [comment]
No I am not @justinmk. It appears nowhere in my code (confirmed by grepping).

**Comment by justinmk** [comment]
@ianks Did you also grep for `acd` (the short version of `autochdir`)?

**Comment by saulhoward** [comment]
@ianks @justinmk I see the same problem with the latest neovim-git -- it reports autochdir to be set, although it is not. I must manually run `set noautochdir` before using vim-filer every time, no matter what is in my `.nvimrc`.

**Comment by zhujinxuan** [comment]
```vim
" set autochdir
autocmd BufEnter * silent! lcd %:p:h
```
If you really want `autochdir` @ianks
