### ISSUE TITLE
Preview fail running inside bash on Windows

### ISSUE THREAD

**Issue by Dominiquini** [junegunn/fzf#3531]
- [X] I have read through the manual page (`man fzf`)
- [X] I have the latest version of fzf
- [X] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [ ] Mac OS X
    - [X] Windows
    - [ ] Etc.
- Shell
    - [X] bash
    - [ ] zsh
    - [ ] fish

## Problem / Steps to reproduce

Running fzf inside bash on Windows (either running directly bash.exe or inside MSYS2 environment), the preview doesn't work!
If I run this command: `fzf --preview 'cat {}'`, the preview window shows for any selected file:

`exec : "C:\\Users\\Rafael Dominiquini\\bash": file does not exist`

My bash is located on '`/usr/bin/bash`' or '`C:\Developing\MSYS2\usr\bin\bash.exe`'

Everything works fine inside powershell, pwsh, cmd! It works even inside zsh (Running on Windows provided by MSYS2)!

Thanks.

**Comment by Dominiquini** [comment]
Found the bug! Some script was overwriting the `SHELL` variable!

**Comment by bambam01** [comment]
@Dominiquini I'am running into the same problem, can you explain how you fixed it?
