### ISSUE TITLE
Is there a "history file" for fzf patterns?

### ISSUE THREAD

**Issue by cohml** [junegunn/fzf#3533]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [x] Mac OS X
- Shell
    - [x] zsh

## Inquiry

Say I run `fzf`, enter the pattern `!foo ^bar baz$`, and find what I want. Then later I run `fzf` again and want to relocate the same file.

Is there some way I can access that earlier pattern without retyping it all from scratch? Like, are my previous patterns logged somewhere, like search patterns in e.g., `less`? Or does `fzf` basically "forget" all patterns as soon as the program exits?

If forget, this might be a nice thing to add.

**Comment by junegunn** [comment]
Yes, take a look at `History` section of the man page.
