### ISSUE TITLE
Tmux not opening in correct directory after fzf execute

### ISSUE THREAD

**Issue by mmottl** [junegunn/fzf#3534]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

## Problem / Steps to reproduce

Assume I'm in directory `~/tmp` and have a file `foo` there. I execute the following:

```
echo foo | fzf --bind "enter:execute(vim {})"
```

Now I press `enter` to open `foo` in `vim`. If I now create a new Tmux window or pane, e.g. with `CTRL-A %`, it won't open in `~/tmp`, but in my home directory. Usually, Tmux will open a new shell with the working directory being taken from the previous process. If I use `become` instead of `execute`, the problem is the same. Vim does report the correct working directory with `:pwd`. But `fzf` apparently prevents this information from being passed on to Tmux.

**Comment by junegunn** [comment]
Interesting. I have no idea why that is happening. What's more interesting is that it's reproducible without using fzf.

```sh
echo foo | sleep 60
```

**Comment by mmottl** [comment]
Interesting indeed! I guess I'll have to file a bug report with Tmux instead. Thanks for your help!
