### ISSUE TITLE
Can the example rfv command use a starting directory? (Help request)

### ISSUE THREAD

**Issue by Praful** [junegunn/fzf#3535]
In the `fzf` [advanced examples](https://github.com/junegunn/fzf/blob/master/ADVANCED.md#using-fzf-as-the-secondary-filter), there is a command defined (`rfv`):
```
#!/usr/bin/env bash

# 1. Search for text in files using Ripgrep
# 2. Interactively restart Ripgrep with reload action
# 3. Open the file in Vim
RG_PREFIX="rg --column --line-number --no-heading --color=always --smart-case "
INITIAL_QUERY="${*:-}"
: | fzf --ansi --disabled --query "$INITIAL_QUERY" \
    --bind "start:reload:$RG_PREFIX {q}" \
    --bind "change:reload:sleep 0.1; $RG_PREFIX {q} || true" \
    --delimiter : \
    --preview 'bat --color=always {1} --highlight-line {2}' \
    --preview-window 'up,60%,border-bottom,+{2}+3/3,~3' \
    --bind 'enter:become(vim {1} +{2})'
```
This is very useful and allows me to type:
```
rfv <search>
```
How can this be extended to start searching from a different directory? This would search subdirectories too. I'd like to have:
```
rfv <search> <start directory>
```
At the moment, I'm having to change directory first.

Ideally, I'd like to get the same working in the [Switching between Ripgrep mode and fzf mode](https://github.com/junegunn/fzf/blob/master/ADVANCED.md#switching-between-ripgrep-mode-and-fzf-mode) script as well.

Many thanks.

**Comment by LangLangBart** [comment]
It's possible to use `getopts` to allow for flags like `-l` (location), `-i` (ignore case), or other tailored customizations.


```bash
rfv() {
	local case="--case-sensitive"
	local location="$PWD"
	while getopts il: cmd_arg; do
		case "$cmd_arg" in
			i) case="--ignore-case" ;;
			l) location="${OPTARG}" ;;
			*)
				echo "Invalid flag provided"
				return 1
				;;
		esac
	done
	shift "$((OPTIND - 1))"
	RG_PREFIX="rg --column --line-number --no-heading --color=always $case "
	INITIAL_QUERY="${*:-}"
	: | fzf --ansi --disabled --query "$INITIAL_QUERY" \
		--bind "start:reload:$RG_PREFIX {q} -- $location" \
		--bind "change:reload:sleep 0.1; $RG_PREFIX {q} -- $location || true" \
		--header "Search Directory: $location" \
		--delimiter : \
		--preview 'bat --color=always {1} --highlight-line {2}' \
		--preview-window 'up,60%,border-bottom,+{2}+3/3,~3' \
		--bind 'enter:become(vim {1} +{2})'
}
```

<img src="https://github.com/junegunn/fzf/assets/92653266/11dbeddd-5323-4e1d-a1e7-f65589778701" width="600">

**Comment by Praful** [comment]
@LangLangBart Perfect! Thank you very much for taking the time to answer and demonstrate the solution.
