### ISSUE TITLE
Adding border property makes FZF show one line less than possible

### ISSUE THREAD

**Issue by anandbibek** [junegunn/fzf#3540]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

## Problem / Steps to reproduce

Set below FZF options

```
export FZF_DEFAULT_OPTS="--border rounded \
--prompt '∷ ' \
--pointer ▶ \
--marker ⇒"
```

Adding any kind of border causes FZF to show one line less in the search results box. Here we have two results which can be easily shown, but it's showing only one line.

<img width="1513" alt="SCR-20231215-uhpq" src="https://github.com/junegunn/fzf/assets/1944248/4e845233-57fa-46f7-b0d8-376428fcfff5">

**Comment by junegunn** [comment]
What are you running here? How did you trigger fzf?

**Comment by anandbibek** [comment]
I'm typing `cd de` and pressing tab

**Comment by junegunn** [comment]
fzf doesn't open in that case by default. Did you install a third-party plugin?

**Comment by anandbibek** [comment]
I see. This is coming from https://github.com/Aloxaf/fzf-tab . Does this mean I should log a bug on this repo instead?

**Comment by junegunn** [comment]
No. I was just trying to figure out what the exact situation is.

I'm not familiar with the internals of fzf-tab, but it must be using `--height` option of fzf, and the value determines the entire space fzf takes, not just the number of items, so using `--border' is expected to decrease the number of items displayable.

```sh
unset FZF_DEFAULT_OPTS

seq 1000 | fzf --height 50%

# Two less items displayed
seq 1000 | fzf --height 50% --border

# This will further decrease the maximum number of items displayed on screen
seq 1000 | fzf --height 50% --border --padding 2 --margin 2
```

Looks like the plugin allows you to change the height via [an option variable](https://github.com/Aloxaf/fzf-tab/blob/c2b4aa5ad2532cca91f23908ac7f00efb7ff09c9/lib/-ftb-fzf#L32), so you might want to fiddle with it.

**Comment by anandbibek** [comment]
Found the perfect solution here https://github.com/Aloxaf/fzf-tab/wiki/Configuration#fzf-pad
