### ISSUE TITLE
Can commands executed by fzf actions be logged in the shell histfile?

### ISSUE THREAD

**Issue by cohml** [junegunn/fzf#3545]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

## Problem

`^R` will fetch the contents of my shell's history file. If I run a command like `cd some/dir`, it will show up in that file, and thus in fzf's `^R` output.

However, commands executed by fzf's "actions" will *not* be logged to the history file. For example, when you make a selection using [the amazing example of `fzf`/`rp` integration](https://github.com/junegunn/fzf/blob/master/ADVANCED.md#ripgrep-integration), the `become` action executes a command that opens the selected file in vim at the selected line. That command then gets lost forever.

Is there some way - or could there be - to record those commands in the history file so that they can be found later by `^R` and rerun manually?

**Comment by junegunn** [comment]
I think the question here is not just about fzf, but is more of a general one. If you have a shell function (or a shell script file) and you run the function, your shell will not record the commands the function internally runs.

```sh
foo() {
  echo bar
  echo baz
}

foo
  # no "echo bar/baz" on your shell history
```

You need a way to manually edit your command history.

**Comment by LangLangBart** [comment]
A solution could be to define a function, 'run_and_save', that saves the command to the history and executes it. This function should be run interactively using `zsh -ic`.



```bash
# .zshrc
run_and_save() {
  print -s "$@"
  eval "$@"
}
```

```bash
print -D $PWD
# ~/Developer/fzf
history -1
# 5514  print -D $PWD

fzf --bind 'start:become:zsh -ic "run_and_save wc -c README.md"'
# 31995 README.md

history -1
# 5513  fzf --bind 'start:become:zsh -ic "run_and_save wc -c README.md"'
# 5514* wc -c README.md
```
