### ISSUE TITLE
Bug: keybindings not active by default in openSUSE Tumbleweed

### ISSUE THREAD

**Issue by j-lakeman** [junegunn/fzf#3547]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux openSUSE Tumbleweed
- Shell
    - [x] bash
    - [x] zsh
    - [x] fish

## Problem / Steps to reproduce

1. install fzf
2. keybindings not working by default

**Comment by junegunn** [comment]
It depends on how you installed fzf. If you install fzf using a package manager, you may need to set them up manually.

https://github.com/junegunn/fzf?tab=readme-ov-file#using-linux-package-managers
