### ISSUE TITLE
[new feature] ask for `select-n` feature

### ISSUE THREAD

**Issue by marslo** [junegunn/fzf#3548]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

## Problem / Steps to reproduce

according to manpage of `fzf`, to select all listed items can use command ( screenshot as below ):
```bash
$ seq 10 | fzf --multi --sync --bind start:last+select-all
```

<img width="1095" alt="image" src="https://github.com/junegunn/fzf/assets/5822057/f05d511b-79ea-48f9-a5ca-01d627412726">

how to automatic select with first `N` items ?
i.e. something like:
```bash
$ seq 10 | fzf --multi --sync --bind start+select-N 2
# or
$ seq 10 | fzf --multi --sync --bind start:second+select-all
# or
$ seq 10 | fzf --multi --sync --bind 1:2+select-all
```
for result as below
<img width="703" alt="image" src="https://github.com/junegunn/fzf/assets/5822057/30569dd2-ae01-4896-90e3-214f48b5f5c3">

**Comment by junegunn** [comment]
What exactly is your use case?

You can do something like this.

```sh
seq 10 | fzf --multi --sync --reverse --bind start:select+down+select+down
```

**Comment by marslo** [comment]
thanks @junegunn !!

**Comment by junegunn** [comment]
Cool, thanks for sharing. I'll close the issue then.
