### ISSUE TITLE
Fish key bindings do not support 'become(vim)' action

### ISSUE THREAD

**Issue by edosrecki** [junegunn/fzf#3549]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [x] fish

## Problem / Steps to reproduce
Fish key bindings do not support `become(vim {})` action. This is because `vim` cannot be piped to some other command, and if you take a look at key bindings, this is exactly the case:

* https://github.com/junegunn/fzf/blob/d7b61ede07ab20ba106191968f12aaf600b6ede4/shell/key-bindings.fish#L39

I am sure if there is a way around this to keep the same functionality. I am opening this issue to discuss possibilities to improve key bindings to support this.

## Workaround
I personally edited the `fzf-file-widget` function so that it does not support existing input on the command line, but instead it simply launches `fzf` with empty query string and then you can enter your query. For me this is sufficient since it aligns well with how I work, and it is more important to me to be able to switch into `vim` from `fzf`.

```diff
diff --git a/shell/key-bindings.fish b/shell/key-bindings.fish
index 69f7697..74c708c 100644
--- a/shell/key-bindings.fish
+++ b/shell/key-bindings.fish
@@ -36,20 +36,9 @@ function fzf_key_bindings
     test -n "$FZF_TMUX_HEIGHT"; or set FZF_TMUX_HEIGHT 40%
     begin
       set -lx FZF_DEFAULT_OPTS "--height $FZF_TMUX_HEIGHT --reverse --scheme=path --bind=ctrl-z:ignore $FZF_DEFAULT_OPTS $FZF_CTRL_T_OPTS"
-      eval "$FZF_CTRL_T_COMMAND | "(__fzfcmd)' -m --query "'$fzf_query'"' | while read -l r; set result $result $r; end
-    end
-    if [ -z "$result" ]
-      commandline -f repaint
-      return
-    else
-      # Remove last token from commandline.
-      commandline -t ""
-    end
-    for i in $result
-      commandline -it -- $prefix
-      commandline -it -- (string escape $i)
-      commandline -it -- ' '
+      eval "$FZF_CTRL_T_COMMAND | "(__fzfcmd)' --multi'
     end
+    commandline -t ""
     commandline -f repaint
   end
```

**Comment by junegunn** [comment]
I don't think this is a problem. CTRL-T is used to complete the command line.

```sh
$ vim <CTRL-T>
```

The calling script expects fzf to print the file path so that it can paste the result onto the command line. If you turn fzf into something else that doesn't do what it's supposed to do, the script will surely break no matter what.

It's not clear where the become action you described is coming from, but if you have it in your `$FZF_DEFAULT_OPTS`, I'd say that's not a good idea because fzf is a general-purpose text filter that can be used with any kind of text that will not work with `vim {}`. e.g. `seq 1000 | fzf`

**Comment by edosrecki** [comment]
Thanks. Sorry for confusion, I misused CTRL-T command. I didn't have it in my `FZF_DEFAULT_OPTS`, but in  `FZF_CTRL_T_OPTS`. However, I removed it now, and defined a separate binding which allows me to open different kinds of files.
