### ISSUE TITLE
Bind multiple actions to one key (execute, then abort)

### ISSUE THREAD

**Issue by netei** [junegunn/fzf#355]
My script is  

```sh
#/bin/sh

session=$(tmux list-sessions -F "#S" | fzf +s --tac +m --tiebreak=index --toggle-sort=ctrl-r --bind='ctrl-t:execute(tmux kill-session -t {})')
tmux switch-client -t "$session"
```

I'd like to be able to abort the fzf command after the execute has been done. Is it possible ?

I've tried `--bind='ctrl-t:execute(tmux kill-session -t {})'),abort` but that doesn't work

**Comment by junegunn** [comment]
How about using `--expect=ctrl-t` instead? There was a similar request: https://github.com/junegunn/fzf/issues/340

**Comment by netei** [comment]
Strangely if I do that, and quit with ctrl-t, the session variable contains a `\n` at the beginning of the element.

```sh
#/bin/sh

session=$(tmux list-sessions -F "#S" | fzf +s --tac +m --tiebreak=index --toggle-sort=ctrl-r --bind='ctrl-t:execute(tmux kill-session -t {})' --expect=ctrl-t)
printf "%s" "$session" > /tmp/tsession
tmux switch-client -t "$session"
```

If I look at /tmp/session, it contains a "\n" when I have the `--expect=ctrl-t` and exit fzf with enter, but I don't have a "\n" if I remove the `--expect=ctrl-t`

**Comment by netei** [comment]
It seems that it is the expected behaviour of --expect 

> --expect=KEY[,..]
       Comma-separated list of keys that can be used to complete fzf in  addition  to  the  default
       enter  key. When this option is set, fzf will print the name of the key pressed as the first
       line of its output (or as the second line if --print-query is also used). The line  will  be
       empty if fzf is completed with the default enter key.
       e.g. fzf --expect=ctrl-v,ctrl-t,alt-s,f1,f2,~,@

**Comment by netei** [comment]
I finally achieved what I want : 

```sh
#/bin/sh

session=$(tmux list-sessions -F "#S" | fzf --no-sort --tac --tiebreak=index --toggle-sort=ctrl-r --bind='ctrl-t:execute(tmux kill-session -t {})' --expect=ctrl-t)

tmux list-sessions -F "#S" | grep -v "dot"

while read -ra LINES; do
    for i in "${LINES[@]}"; do
        [ "$i" == "ctrl-t" ] && fzf-list-session && return 1
        tmux switch-client -t "$i"
    done
done <<< "$session"
```

**Comment by junegunn** [comment]
Hmm, you don't want/need `execute` in this case:

```sh
lines="$(seq 100 | fzf --expect=ctrl-t,alt-t)"
key="$(head -1 <<< "$lines")"
rest="$(sed 1d <<< "$lines")"

case "$key" in
  ctrl-t)
    echo "you pressed ctrl-t on $rest"
    ;;
  alt-t)
    echo "you pressed alt-t on $rest"
    ;;
  *)
    echo "enter key or mouse click on $rest"
    ;;
esac
```

You see the point?

**Comment by netei** [comment]
Ok, I've removed ctrl-t from my binding.

Thanks for the tip
