### ISSUE TITLE
Temporary "Loading..." in the header

### ISSUE THREAD

**Issue by edosrecki** [junegunn/fzf#3551]
Is it possible to temporarily print out "Loading..." in the `fzf` results while long-running command is executing and then replace it with the result of that command?

For example:

```sh
echo -ne "Loading...\r"

# Fetch data that is piped to fzf or loaded with reload() function

echo -ne "\033[0K\r" # Delete "Loading..."

# Output results
```

What I get is literal `Loading...␍␍` printed out.

**Comment by edosrecki** [comment]
I see I can do:

```sh
  --bind="change:change-header(Loading...)+reload(my_func {q})" \
  --bind="load:transform-header()"
```

but then I get empty header line after `load`. Can I make it disappear fully?

**Comment by edosrecki** [comment]
Generally speaking, I am looking for a way to provide info to user that results are loading, it would be nice if I could implement a spinner, too, for which I need ability to write and replace chars.

**Comment by junegunn** [comment]
> Can I make it disappear fully? 

There is `toggle-header` you can use, although there is no `show-header` or `hide-header` at the moment. An alternative would be to set the header to something like `Loading complete` message or to use `change-prompt` instead of `change-header`.

> implement a spinner

fzf does have a spinner, so I'm not sure why you need another one.

Anyway, here's my suggestion. Space to reload the list.

```sh
(echo 'loading'; sleep 1; date; ls) |
  fzf --header-lines 1 \
      --bind 'start:unbind(space),load:toggle-header+rebind(space)' \
      --bind 'space:unbind(space)+toggle-header+reload-sync(echo loading again; sleep 1; date; ls)'
```

**Comment by LangLangBart** [comment]
The example above works great, but if you want to spice things up, you could try using the `--listen`[^1] option and utilize `curl` within your `my_func` function to send updates to `fzf`. Exemplary `bash` script below.

```bash
#!/usr/bin/env bash
set -o allexport -o errexit -o nounset -o pipefail
# https://www.gnu.org/software/bash/manual/bash.html#The-Set-Builtin

fzf_port=7196

# =================== helper functions ====================

# Send a POST request to fzf
curl_fzf() {
	command curl --request POST --data "$1" "localhost:$fzf_port"
}

my_func() {
	if [[ -z $1 ]]; then
		curl_fzf "transform-header:echo 'Please enter a number'"
	elif ! [[ $1 =~ ^[[:space:]0-9]+$ ]]; then
		curl_fzf "transform-header:echo 'Only positive numbers and spaces are allowed'"
	else
		curl_fzf "transform-header:echo 'Loading…'"
		sleep 1
		curl_fzf "reload(seq $1)+transform-header:echo \"Command: 'seq $1' \""
	fi
}

# ===================== let's begin ========================

SHELL=bash fzf --ansi \
	--bind $'start:reload:my_func {q} || true' \
	--bind "change:reload:sleep 0.25;my_func {q} || true" \
	--disabled \
	--listen $fzf_port \
	--query "${*-}" \
	--reverse
```


<img src="https://github.com/junegunn/fzf/assets/92653266/653bd138-3b11-4001-a21b-e3a651269b35" width="600">

[^1]: [Release notes 0.36.0](https://github.com/junegunn/fzf/blob/master/CHANGELOG.md#0360)
