### ISSUE TITLE
Feature Suggestion: Auto-accept mode

### ISSUE THREAD

**Issue by knu** [junegunn/fzf#3552]
New option: `--auto-accept` (or give it a better name)

It makes fzf immediately accept what is selected when all candidates are loaded and the query has narrowed them down to only one.

This option will work well with options like `--query=^` and `--exact` and allows for using fzf like menu selection UI.
I can't think of a good use case with `--multi`, so it may be just for single-selection mode.

- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

## Problem / Steps to reproduce

You are always required to press Enter when you see there's only one matching candidate.

I tried to achieve enter-less acceptance by using key bindings like `--bind 'x:change-query(^x)+accept'` but it did not seem to work.

**Comment by junegunn** [comment]
Have you tried `--bind one:accept`?

**Comment by knu** [comment]
I haven't.  And aw, I guess this is what I wanted. 😳
