### ISSUE TITLE
Preview not working - "Pseudo-terminal will not be allocated because stdin is not a terminal." - Ubuntu 23.10/Kitty/ZSH 

### ISSUE THREAD

**Issue by MasterOfTheJuice** [junegunn/fzf#3553]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

## Problem / Steps to reproduce
Preview never works on Ubuntu 23.10 running zsh in kitty. 
the preview window is filled with the below error message regardless of the preview command (screenshot below)

> Pseudo-terminal will not be allocated because stdin is not a terminal.

i've tried disabling all zsh plugins and even using bash and different terminals, but this behavior is consistent.

![image](https://github.com/junegunn/fzf/assets/40400831/d903b062-cb3c-4e54-b40f-4ee2fac02b3d)

the only way i could get it to work is by running fzf with "sudo -S"
```
sudo -S fzf  --preview "batcat --color=always {}"
```

couldn't find any information online or anyone else facing similar issues.
any help would be greatly appreciated.
thanks.

**Comment by junegunn** [comment]
What happens when you change the preview command to a simpler one?

```sh
fzf --preview 'cat {}'
```

**Comment by MasterOfTheJuice** [comment]
> What happens if you change the preview command to a simpler one?
> 
> ```shell
> fzf --preview 'cat {}'
> ```

doesnt make any difference, unfortunately.

**Comment by junegunn** [comment]
What about this one? (fzf uses $SHELL to start child processes.)

```sh
SHELL=/bin/bash fzf --preview 'cat {}'
```

**Comment by MasterOfTheJuice** [comment]
> ```shell
> SHELL=/bin/bash fzf --preview 'cat {}'
> ```
thanks for helping with this.

works fine with /bin/bash
so i assume it's related to my zsh config?
i did try to disable all plugins, but it made no difference.
any idea what the problem could be with zsh?

**Comment by junegunn** [comment]
> i assume it's related to my zsh config

It seems so. You should fix your configuration so that something like `zsh -c 'echo hello'` works as expected.

**Comment by MasterOfTheJuice** [comment]
> zsh -c 'echo hello'

this works fine actually
![image](https://github.com/junegunn/fzf/assets/40400831/75925488-b754-4a25-bff0-7347b8ad4763)

but the preview windows doesnt work still
