### ISSUE TITLE
Feature request: an event triggered when query string is emptied or killed

### ISSUE THREAD

**Issue by lbrayner** [junegunn/fzf#3560]
Similar to backward-eof, I'd like to have an event that triggers when the query string is emptied or killed, so I can reposition the cursor to a specific line that represents the current state, such as a Vim buffer or tab.

**Comment by LangLangBart** [comment]
Ref: [CHANGELOG.md 0.40.0](https://github.com/junegunn/fzf/blob/master/CHANGELOG.md#0400)

```bash
fzf --bind 'tab:track+clear-query'
```

or 

Ref: [CHANGELOG.md 0.45.0](https://github.com/junegunn/fzf/blob/master/CHANGELOG.md#0450)
```bash
fzf --bind 'change:transform:[[ -z {fzf:query} && {fzf:action} =~ ^(backward|clear|delete|kill|unix) ]] && echo "track"'
```

**Comment by lbrayner** [comment]
@LangLangBart  since change triggers at every change, isn't it inefficient?

Also, this doesn't work:

```shell
echo -n "hello\nthere" | fzf --bind 'change:transform:[[ -z {fzf:query} && {fzf:action} =~ ^(backward|clear|delete|kill|unix) ]] && echo "pos(2)"'
```

**Comment by lbrayner** [comment]
@LangLangBart Also tried this and it doesn't work:

```shell
 echo -e "hello\nthere" | fzf --bind 'backward-eof:pos(2),change:transform:[[ -z "{fzf:query}" ]] && echo "backward-delete-char"'
``` 

If do a backspace when the query is empty, it positions cursor at line 2, however the transform doesn't work. What I believe is happening is that change triggers before the original list is restored.

**Comment by LangLangBart** [comment]
> @LangLangBart since change triggers at every change, isn't it inefficient?
> 
> Also, this doesn't work:
> 
> ```shell
> echo -e "hello\nthere" | fzf --bind 'change:transform:[[ -z {fzf:query} && {fzf:action} =~ ^(backward|clear|delete|kill|unix) ]] && echo "pos(2)"'
> ```

I tried a bigger list and it worked. If the number of entries is small, the position doesn't change. It works for lists over 12 entries, but not for smaller ones. Can you confirm this?

```bash
seq 13 | fzf --query 3 --bind 'change:transform:[[ -z {fzf:query} && {fzf:action} =~ ^(backward|clear|delete|kill|unix) ]] && echo pos:2'
```

---

The `focus` event works.

```bash
seq 4 | fzf --query 3 --bind 'focus:transform:[[ -z {fzf:query} && {fzf:action} =~ ^(backward|clear|delete|kill|unix) ]] && echo pos:2'
```

**Comment by junegunn** [comment]
`change` or `backward-eof` event is triggered when the user changes the query string. The reason that `pos(2)` at the moment doesn't reliably work is that the filtering is done asynchronously by another thread **after** the event.

```sh
# Try deleting the query string

# Position 2 is currently available, so we can immediately move to it on 'change'.
# The result list will be updated, and we just stay there.
seq 100 | fzf --bind 'load:pos(5),change:pos(2)' --query '1'

# We can't move to position 2 on 'change', because the position is unavailable.
seq 100 | fzf --bind 'load:pos(5),change:pos(2)' --query 'x'
```

So even if we add a new event that is only triggered when the query string is emptied, it will have the exact same problem.

---

> The `focus` event works.

Yes, that seems to be the only option at the moment.

**Comment by lbrayner** [comment]
> So I think I actually need an event that triggers after the original list is restored.

This is what I mean, @junegunn, I need an event that triggers when the original list is restored.

**Comment by junegunn** [comment]
> when the original list is restored

I feel the requirement is too specific to be useful in various cases. We could add an event for when the filtering is complete for the current query whether it's empty or not.

```sh
# Use --sync as we don't want to start with an incomplete list,
fzf --sync --bind 'result:transform:[[ -z {fzf:query} ]] && echo "pos(2)"'
```

**Comment by lbrayner** [comment]
> > when the original list is restored
> 
> I feel the requirement is too specific to be useful in various cases. We could add an event for when the filtering is complete for the current query whether it's empty or not.
> 
> ```shell
> # Use --sync as we don't want to start with an incomplete list,
> fzf --sync --bind 'result:transform:[[ -z {fzf:query} ]] && echo "pos(2)"'
> ```

That's perfect!

**Comment by junegunn** [comment]
Added the event. However, I'm not yet sure of its usefulness, I may decide to drop it before releasing a new version.

**Comment by lbrayner** [comment]
Thanks @junegunn , @LangLangBart 



> Added the event. However, I'm not yet sure of its usefulness, I may decide to drop it before releasing a new version.

I understand, @junegunn . One use is indicating state, which can be represented by the cursor position, or multiple selection. I specifically want to use this to move between Neovim tabs, I'm a heavy tab user.
