### ISSUE TITLE
Rg search preview window does not show complete text of the file. Text missing.

### ISSUE THREAD

**Issue by mindentropy** [junegunn/fzf#3561]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [ x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ x] bash
    - [ ] zsh
    - [ ] fish

## Problem / Steps to reproduce

1. Open vim in shell
2. Search the directory with Rg
3. Scroll through the results and see the preview pane on the right

Text is missing in the preview pane on the right as per the screenshot attached.

![rg](https://github.com/junegunn/fzf/assets/2458664/5159c8f8-343d-4381-9c1c-a979b6fa625a)

**Comment by LangLangBart** [comment]
Could it simply be a setup issue with your colors, as they appear to be white on a white background?

Try a dark background. 
![SCR-20240104-kgrx](https://github.com/junegunn/fzf/assets/92653266/e9eec520-e762-4960-a6df-33a925765290)

**Comment by mindentropy** [comment]
@LangLangBart : I set `export FZF_DEFAULT_OPTS='--color dark'` in my `.bashrc` and it did not have any effect. How can I match my present color scheme with the preview pane window?

**Comment by LangLangBart** [comment]
does this have any effect ?

```bash
export FZF_DEFAULT_OPTS="--color 'preview-bg:235'"
```

---

Otherwise, I assume you are using `bat` to preview your file; you could experiment with a different `BAT_THEME`.

```bash 
bat --list-themes
…

export BAT_THEME="Coldark-Cold"
```

**Comment by LangLangBart** [comment]
> `.bashrc`

I am not a `vim` user, but don't you have to define these values in `.vimrc`?

**Comment by LangLangBart** [comment]
Ref: https://github.com/junegunn/fzf.vim/issues/1509

**Comment by mindentropy** [comment]
@LangLangBart : Looks like bat is being used. I set the bat_theme to `Coldark-Cold` which is a light theme and it seems to be working now. Thanks for the help.
