### ISSUE TITLE
Command failed: find -L

### ISSUE THREAD

**Issue by IntelligentFunction** [junegunn/fzf#3566]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

## Problem / Steps to reproduce
fzf no longer runs in zsh or in nvim. if you type 'fzf' in the terminal the window opens, but the above message happens. I have tried to uninstall it and install it again, but the issue is still there.

**Comment by junegunn** [comment]
Do you have `$FZF_DEFAULT_COMMAND` set?

**Comment by IntelligentFunction** [comment]
Yes I have this:
 export FZF_DEFAULT_COMMAND="find -L"
in .zshrc file. Removing that has got it working again on this occasion. Though I would still like to be able to find hidden files which I have not found a solution for. I added this from seeing a reddit post, but it did not work for me. 
However, my initial issue has been solved by removing this line.

**Comment by junegunn** [comment]
`find -L` is not a valid command.

See https://github.com/junegunn/fzf?tab=readme-ov-file#respecting-gitignore

**Comment by IntelligentFunction** [comment]
Thank you very much, that explains a lot too. Also thank you for your contribution to the vim world :)
