### ISSUE TITLE
Doge

### ISSUE THREAD

**Issue by junegunn** [junegunn/fzf#357]
![2015-09-24 11 13 51](https://cloud.githubusercontent.com/assets/700826/10075679/f76521c6-6311-11e5-812c-beadbebc7f84.png)

such sorry.
very much apologize.

**Comment by justinmk** [comment]
:+1:

**Comment by junegunn** [comment]
http://invisible-island.net/ncurses/ncurses.faq.html#xterm_16MegaColors

> Using the ncurses 5 ABI, you have available 16 colors, or 256 pairs of colors. Using the ncurses 6 ABI, you would have 256 colors, or 32767 pairs (the limit for a signed 16-bit number).
