### ISSUE TITLE
"Advanced" fzf + rg integration - Can the preview grow/shrink dynamically based on the number of results?

### ISSUE THREAD

**Issue by cohml** [junegunn/fzf#3572]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

## Question

I have implemented [the `fzf` + `rg` integration found in `ADVANCED.md`](https://github.com/junegunn/fzf/blob/master/ADVANCED.md#ripgrep-integration). It is amazing.

However, it wastes a lot of screen real estate, with the results/preview split fixed at 40%/60%. When almost all the results have been filtered out, this means 40% of the screen is wasted.

Can this "dead space" be dynamically taken up by the preview? For example, by setting the size of the preview window to equal something like `max(60%, 100% - results%)`? So if there are tons of matches, the results would take up 40% and the preview would take up 60%, but if I add to the query such that the number of matches decreases and takes up less than 40%, the preview window will grow to pick up the slack.

Is this currently possible? I know `preview-window` takes a "threshold", however the man page also says "only one alternative layout is allowed", which sounds like dynamic resizing is not possible. But I wanted to confirm.

**Comment by LangLangBart** [comment]
In `fzf`, there isn't a pre-existing variable to get the total number of listed items. However, a
workaround exists, although it's somewhat lengthy. This method involves using the `--listen` flag to
query `fzf` about the `totalCount` and `matchCount`, and then sending an update to `fzf` to modify
the preview size whenever the `matchCount` changes. Writing this as a bash script is should be
doable.

The image below displays two terminals. The top one shows the standard `fzf` list with a query,
while the bottom terminal queries `fzf` in a headless manner[^1].

<img src="https://github.com/junegunn/fzf/assets/92653266/4f463843-c028-4bc5-a6b0-4f5f2b2c6e53"
width="600">

The maintainer recently provided a related response[^2].

[^1]: [Preview window sizing - specify size of finder list instead of preview window · Issue #3570 ·
    junegunn/fzf · GitHub ](https://github.com/junegunn/fzf/issues/3570#issuecomment-1884109346)

[^2]: [CHANGELOG.md 0.43.0](https://github.com/junegunn/fzf/blob/master/CHANGELOG.md#0430)

---

Alternatively, I often assign a unique keyboard shortcut to change the size of the preview window,
allowing me to toggle through the size that suits best.

```bash
man fzf
…
     CHANGE PREVIEW WINDOW ATTRIBUTES
         change-preview-window action can be used to change the properties of the
         preview window. Unlike the --preview-window option, you can specify mul-
        tiple sets of options separated by '|' characters.

         e.g.
              # Rotate through the options using CTRL-/
              fzf   --preview   'cat   {}'   --bind   'ctrl-/:change-preview-win-
         dow(right,70%|down,40%,border-horizontal|hidden|right)'

              # The default properties given by `--preview-window` are inherited,
          so an empty string in the list is interpreted as the default
```

**Comment by cohml** [comment]
@LangLangBart That is brilliant, thanks for the idea! I have taken a stab at implementing this, and here's what I've got:

```zsh
--bind="change:execute($SHELL -c 'MATCHCOUNT=$(curl -qs localhost:\$FZF_PORT | jq .matchCount) && curl -qs localhost:\$FZF_PORT -d change-preview\(\' \$(( 100 * (\$LINES - \$MATCHCOUNT) / \$LINES ))%\'\)')"
```

But when I run `fzf` and trigger the `change` event, I see the following error:

```zsh
zsh:1:unmatched '
```

So obviously there is an issue with my quoting, always a pain point for me with complex commands like this.

However, even after running `MATCHCOUNT=$(curl -qs localhost:$FZF_PORT | jq .matchCount)` within the keybinding, `$MATCHCOUNT` seems empty.

I'm pretty sure I'm close, and just need a helping hand. Do you see what is wrong with my attempt to implement your idea?

**Comment by LangLangBart** [comment]
### Prototype for dynamically adjusting the preview window
1. Save the file as `rfv`.
2. Make it executable by running `chmod +x rfv`.
3. Execute it by running `./rfv`.

>[!NOTE]
> The **minimum** size of the `preview-window` is set inside the `jq` query to `$rows/3`,
> and the **maximum** size is `$rows - $buffer_space`.


<details>

<summary>Script</summary>

---

```bash
#!/usr/bin/env bash
set -o allexport -o errexit -o nounset -o pipefail
# https://www.gnu.org/software/bash/manual/bash.html#The-Set-Builtin

SHELL=$(which bash)

# Set rows to the number of lines in the terminal
rows=$(tput lines)
buffer_space="5"

# =================== helper functions ====================

die() {
	echo ERROR: "$*" >&2
	exit 1
}

# Function to send GET/POST request to fzf with optional data load
curl_fzf() {
	command curl --silent --request "$1" --data "${2-}" "localhost:$FZF_PORT"
}

spin_me() {
	local old_size=""
	# Loop as long 'fzf' (parent process) is alive
	while command kill -0 "$PPID" 2>/dev/null; do
		# Calculate the new size of the preview window based on the number of matches and rows in
		# the terminal
		new_size="$(
			curl_fzf GET |
				jq --raw-output --argjson rows "$rows" --argjson buffer_space "$buffer_space" \
					'[
					([($rows/3), ($rows - .matchCount - $buffer_space) ] | max),
					($rows - $buffer_space)
				] | min | floor'
		)"
		# If new size is different from old size, update the preview window size and header
		if [ "$new_size" != "$old_size" ]; then
			curl_fzf POST "change-header(Preview Window Size: $new_size/ ∑ Rows: $rows)+change-preview-window:$new_size"
			old_size=$new_size
		fi
		sleep 0.5
	done
}

# =================== check requirements ====================

if ((rows <= 1)); then
	die "'rows' must be higher than 1."
fi

for tool in curl fzf jq; do
	if ! type -p $tool >/dev/null; then
		die "'$tool' was not found."
	fi
done

# ===================== let's begin ========================

# https://github.com/junegunn/fzf/blob/master/ADVANCED.md#ripgrep-integration
rg --color=always --line-number --no-heading --smart-case "${*:-}" |
	FZF_DEFAULT_OPTS="" fzf \
		--ansi \
		--bind 'start:execute-silent:spin_me &' \
		--color "hl:-1:underline,hl+:-1:underline:reverse" \
		--delimiter : \
		--listen \
		--preview 'bat --color=always {1} --highlight-line {2}' \
		--preview-window 'up,border-bottom,+{2}+3/3,~3' \
		--bind 'enter:become(vim {1} +{2})'
```

---

</details>

#### Exemplary GIF:

<img src="https://github.com/junegunn/fzf/assets/92653266/50c9cde2-3325-48a6-8a4b-fe91c9593629" width="800">

**Comment by cohml** [comment]
Amazing, thanks! This is exactly the behavior I had in mind.

However, your implementation is completely different from mine (and may be Bash-specific?)? Why is that? Is there some fatal flaw with the way I attempted to do it [above](https://github.com/junegunn/fzf/issues/3572#issuecomment-1887302488)?

```bash
--bind="change:execute($SHELL -c 'MATCHCOUNT=$(curl -qs localhost:\$FZF_PORT | jq .matchCount) && \
        curl -qs localhost:\$FZF_PORT -d change-preview\(\' \$(( 100 * (\$LINES - \$MATCHCOUNT) / \$LINES ))%\'\)')"
```

If possible, I'd love to define how this works all within the binding, no need for e.g., an extra executable. Though if that's the only way, I can certainly capitulate.

**Comment by cohml** [comment]
@LangLangBart Following up - For some reason I can't replicate your GIF, even using the code you shared exactly: create `rfv` file, make executable, run it. No matter how I execute it, or whether with bash or zsh, the preview window remains fixed (and incidentally, so does the header).

Can you assist? I would absolutely kill to have what you've shown via your GIF (though personally I'd like to run it via keybinding (`bindkey "\e/" fzf-ripgrep`), not a dedicated executable).

**Comment by LangLangBart** [comment]
> If possible, I'd love to define how this works all within the binding, no need for e.g., an extra executable.

Could you try this minimal working example on a directory with some files for example the `fzf` repo ?

```bash
find . -type f -maxdepth 1 | FZF_DEFAULT_OPTS="" fzf \
	--listen \
	--preview 'bat --color=always {}' \
	--preview-window 'up,border-bottom' \
	--bind $'change:execute-silent:(new_size=$(curl -s localhost:$FZF_PORT | jq --raw-output --argjson rows "$LINES" \'[([($rows/3), ($rows - .matchCount - 5) ] | max),($rows - 5)] | min | floor\'); curl -s localhost:$FZF_PORT -d "change-header(Preview Window Size: $new_size / Rows: $LINES)+change-preview-window:$new_size") &'
```

<img src="https://github.com/junegunn/fzf/assets/92653266/8e1f35bc-1823-4040-8792-1bcb8d965661" width="600">

**Comment by cohml** [comment]
From the `fzf` repo, as directed:

![Untitled2](https://github.com/junegunn/fzf/assets/62400541/07514107-1d3f-4ec9-b844-0a290b5e8927)

Again, the preview window size remains fixed. I wonder why the difference between you and me?

For context:
- Apple Silicon M1 Pro
- MacOS Sonoma 14.2.1
- iTerm2 3.4.23
- zsh 5.9 (x86_64-apple-darwin23.0)
- fzf 0.45.0 (202401011)

**Comment by LangLangBart** [comment]
> Again, the preview window size remains fixed. I wonder why the difference between you and me?

Thank you for testing. We could attempt to debug it using `set -x`, and save the contents to a file named `~/test_debug.txt`. Hopefully, this will help us identify where things are going wrong.

```bash
# Try this debug command: Enter a few characters in the FZF query, then inspect the contents of '~/test_debug.txt'.
find . -type f -maxdepth 1 | FZF_DEFAULT_OPTS="" fzf --listen --preview 'bat --color=always {}' --preview-window 'up,border-bottom' --bind $'change:execute-silent:(set -x; { new_size=$(curl -s localhost:$FZF_PORT | jq --raw-output --argjson rows "$LINES" \'[([($rows/3), ($rows - .matchCount - 5) ] | max),($rows - 5)] | min | floor\'); curl -s localhost:$FZF_PORT -d "change-header(Preview Window Size: $new_size / Rows: $LINES)+change-preview-window:$new_size" }  2>&1 | tee -a ~/test_debug.txt ) &'
```

Exemplary result of '~/test_debug.txt'
```log
+zsh:1> new_size=+zsh:1> curl -s localhost:50332
+zsh:1> new_size=+zsh:1> jq --raw-output --argjson rows 28 '[([($rows/3), ($rows - .matchCount - 5) ] | max),($rows - 5)] | min | floor'
+zsh:1> new_size=11 
+zsh:1> curl -s localhost:50332 -d 'change-header(Preview Window Size: 11 / Rows: 28)+change-preview-window:11'
+zsh:1> new_size=+zsh:1> curl -s localhost:50332
+zsh:1> new_size=+zsh:1> jq --raw-output --argjson rows 28 '[([($rows/3), ($rows - .matchCount - 5) ] | max),($rows - 5)] | min | floor'
+zsh:1> new_size=15 
+zsh:1> curl -s localhost:50332 -d 'change-header(Preview Window Size: 15 / Rows: 28)+change-preview-window:15'
```

**Comment by cohml** [comment]
Thanks so much for that minimal command!

Redirecting to a file helped me find the issue myself: I had set `FZF_API_KEY` elsewhere, but wasn't passing it into the server via `curl`. Hence the requests were being silently rejected and `change-preview-window` was never being triggered.

In the end, the following keybinding works for me and now she's purring like a kitten!

```bash
  --bind=$'change:execute-silent:(
    PREVIEW_SIZE=$(
      curl -qsH "x-api-key: $FZF_API_KEY" localhost:$FZF_PORT \|
        jq -r --argjson LINES $LINES \'[([($LINES/3), ($LINES - .matchCount - 5) ] | max),($LINES - 5)] | min | floor\'
    );
    curl -qsH "x-api-key: $FZF_API_KEY" localhost:$FZF_PORT -d "change-preview-window:$PREVIEW_SIZE"
  ) &'
```

Thanks again for all your help!

**Comment by cohml** [comment]
I'll close the issue now as it's been resolved. However, @LangLangBart, since I have the individual attention of a board-certified shell+`fzf` wizard like you, I'd like to briefly co-opt this thread with a loosely-related question that's stumped me for weeks.

The following snippet gets sourced from my .zshrc and attempts to configure `fzf`'s `CTRL-T` keybinding in a nice, readable manner:

```bash
export FZF_DEFAULT_COMMAND="fd --color=always --hidden"

FZF_CTRL_T_PREVIEW_COMMAND="bat --color=always --line-range=:500 {}"
FZF_CTRL_T_KEYBINDINGS_ARRAY=(
  "alt-b:become(bat {})"
  "alt-l:become(${${BAT_PAGER}:-less} {})"
  "alt-n:become(${EDITOR:-vim} {})"
)
FZF_CTRL_T_KEYBINDINGS=$(echo "${FZF_CTRL_T_KEYBINDINGS_ARRAY}" | sed 's/) a/),a/g')
FZF_CTRL_T_OPTS_ARRAY=(
  "--bind='${FZF_CTRL_T_KEYBINDINGS}'"
  "--header-first"
  "--no-height"
  "--preview='${FZF_CTRL_T_PREVIEW_COMMAND}'"
  "--preview-window=hidden"
)
FZF_CTRL_T_COMMAND_ARRAY=(
  "${FZF_DEFAULT_COMMAND}"
  "--exclude=.git"
  "--follow"
  "--type=file"
  "--type=symlink"
)
export FZF_CTRL_T_OPTS=$(echo "${FZF_CTRL_T_OPTS_ARRAY}")
export FZF_CTRL_T_COMMAND=$(echo "${FZF_CTRL_T_COMMAND_ARRAY}")
```

I'd like to draw your attention to these lines specifically:

```bash
FZF_CTRL_T_KEYBINDINGS_ARRAY=(
  "alt-b:become(bat {})"
  "alt-l:become(${${BAT_PAGER}:-less} {})"
  "alt-n:become(${EDITOR:-vim} {})"
)
FZF_CTRL_T_KEYBINDINGS=$(echo "${FZF_CTRL_T_KEYBINDINGS_ARRAY}" | sed 's/) a/),a/g')
```

Their ultimate purpose is to populate a string of keybindings that pipe the selected file into the appropriate program (e.g., `bat`, `less`). This string then get passed to `--bind` when setting `FZF_CTRL_T_OPTS`.

After sourcing everything, `FZF_CTRL_T_OPTS` looks like this:

```bash
❯ echo "${FZF_CTRL_T_OPTS}"
--bind='alt-b:become(bat {}),alt-l:become(less --chop-long-lines --header=1 --jump-target=3 --line-num-width=0 --LONG-PROMPT --no-number-headers --shift=4 --status-column --use-color --color=HGk --color=NGk {}),alt-n:become(nvim {})' --header-first --no-height --preview='bat --color=always --line-range=:500 {}' --preview-window=hidden
```

Seems fine, right? In fact, when I copy that string and pass it into `fzf` directly (i.e., `fzf --bind= [...] --preview-window=hidden`), my `alt-{b,l,n}` keybindings all work as intended. Here's an illustration using `alt-l` (`less`) and `alt-b` (`bat)`:

![Untitled](https://github.com/junegunn/fzf/assets/62400541/3d1b0ba6-13b1-4c25-88de-aa813126bbfe)

**But here's where things get weird:** When I activate `fzf` via the `CTRL-T` keybinding and attempt `alt-{b,l,n}`, something completely different happens. Rather than opening the file with the desired program, it just `cat`s the file to stdout with all these escaped characters. Here's an example where I show this, first with `alt-b` then with `alt-l`:

![Untitled](https://github.com/junegunn/fzf/assets/62400541/c12feb40-0e38-484e-8dbd-2c828788cc09)

In the end, this strange behavior prevents me from using my keybindings despite that they seem free of syntax errors.

Can you speculate what the issue might be? Note that I set all my `fzf` keybindings in the same way shown in my snippet, and everything has worked out until now.

Many thanks in advance for your ongoing discussions and support!

**Comment by cohml** [comment]
I'll close the issue now as it's been resolved. However, @LangLangBart, since I have the individual attention of a board-certified shell+`fzf` wizard like you, I'd like to briefly co-opt this thread with a loosely-related question that's stumped me for weeks.

The following snippet gets sourced from my .zshrc and attempts to configure `fzf`'s `CTRL-T` keybinding in a nice, readable manner:

```bash
export FZF_DEFAULT_COMMAND="fd --color=always --hidden"

FZF_CTRL_T_PREVIEW_COMMAND="bat --color=always --line-range=:500 {}"
FZF_CTRL_T_KEYBINDINGS_ARRAY=(
  "alt-b:become(bat {})"
  "alt-l:become(${${BAT_PAGER}:-less} {})"
  "alt-n:become(${EDITOR:-vim} {})"
)
FZF_CTRL_T_KEYBINDINGS=$(echo "${FZF_CTRL_T_KEYBINDINGS_ARRAY}" | sed 's/) a/),a/g')
FZF_CTRL_T_OPTS_ARRAY=(
  "--bind='${FZF_CTRL_T_KEYBINDINGS}'"
  "--header-first"
  "--no-height"
  "--preview='${FZF_CTRL_T_PREVIEW_COMMAND}'"
  "--preview-window=hidden"
)
FZF_CTRL_T_COMMAND_ARRAY=(
  "${FZF_DEFAULT_COMMAND}"
  "--exclude=.git"
  "--follow"
  "--type=file"
  "--type=symlink"
)
export FZF_CTRL_T_OPTS=$(echo "${FZF_CTRL_T_OPTS_ARRAY}")
export FZF_CTRL_T_COMMAND=$(echo "${FZF_CTRL_T_COMMAND_ARRAY}")
```

I'd like to draw your attention to these lines specifically:

```bash
FZF_CTRL_T_KEYBINDINGS_ARRAY=(
  "alt-b:become(bat {})"
  "alt-l:become(${${BAT_PAGER}:-less} {})"
  "alt-n:become(${EDITOR:-vim} {})"
)
FZF_CTRL_T_KEYBINDINGS=$(echo "${FZF_CTRL_T_KEYBINDINGS_ARRAY}" | sed 's/) a/),a/g')
```

Their ultimate purpose is to populate a string of keybindings that pipe the selected file into the appropriate program (e.g., `bat`, `less`). This string then get passed to `--bind` when setting `FZF_CTRL_T_OPTS`.

After sourcing everything, `FZF_CTRL_T_OPTS` looks like this:

```bash
❯ echo "${FZF_CTRL_T_OPTS}"
--bind='alt-b:become(bat {}),alt-l:become(less --chop-long-lines --header=1 --jump-target=3 --line-num-width=0 --LONG-PROMPT --no-number-headers --shift=4 --status-column --use-color --color=HGk --color=NGk {}),alt-n:become(nvim {})' --header-first --no-height --preview='bat --color=always --line-range=:500 {}' --preview-window=hidden
```

Seems fine, right? In fact, when I copy that string and pass it into `fzf` directly (i.e., `fzf --bind= [...] --preview-window=hidden`), my `alt-{b,l,n}` keybindings all work as intended. Here's an illustration using `alt-l` (`less`) and `alt-b` (`bat)`:

![Untitled](https://github.com/junegunn/fzf/assets/62400541/3d1b0ba6-13b1-4c25-88de-aa813126bbfe)

**But here's where things get weird:** When I activate `fzf` via the `CTRL-T` keybinding and attempt `alt-{b,l,n}`, something completely different happens. Rather than opening the file with the desired program, it just `cat`s the file to stdout with all these escaped characters. Here's an example where I show this, first with `alt-b` then with `alt-l`:

![Untitled](https://github.com/junegunn/fzf/assets/62400541/c12feb40-0e38-484e-8dbd-2c828788cc09)

In the end, this strange behavior prevents me from using my `alt-{b,l,n}` keybindings despite that they seem free of syntax errors.

Can you speculate what the issue might be? Note that I set all my `fzf` keybindings in the same way shown in my snippet, and everything has worked out until now.

Many thanks in advance for your ongoing discussions and support!

**Comment by LangLangBart** [comment]
> In the end, the following keybinding works for me and now she's purring like a kitten!
> 
> ```shell
>   --bind=$'change:execute-silent:(
>     PREVIEW_SIZE=$(
>       curl -qsH "x-api-key: $FZF_API_KEY" localhost:$FZF_PORT \|
>         jq -r --argjson LINES $LINES \'[([($LINES/3), ($LINES - .matchCount - 5) ] | max),($LINES - 5)] | min | floor\'
>     );
>     curl -qsH "x-api-key: $FZF_API_KEY" localhost:$FZF_PORT -d "change-preview-window:$PREVIEW_SIZE"
>   ) &'
> ```
> 
> Thanks again for all your help!


Before setting `PREVIEW_SIZE=`, one can consider adding a check to ensure `progress` has reached 100.

```bash
--bind=$'change:execute-silent:(while (($(curl -s localhost:$FZF_PORT | jq -r \'.progress\') < 100));do; ! command kill -0 "$PPID" 2>/dev/null && break || sleep 0.1;done || exit ; PREVIEW_SIZE=…
```

---


> individual attention of a board-certified shell+`fzf` wizard like you

I'll do my best to assist you, but for more complex issues, you might want to reach out to experts like `junegunn`.

---

> When I activate fzf via the CTRL-T keybinding and attempt alt-{b,l,n}, something completely different happens. Rather than opening the file with the desired program, it just cats the file to stdout with all these escaped characters.

I assume your <kbd>⌃ Control</kbd> + <kbd>T</kbd> hotkey is assigned to the unmodified `fzf-file-widget`?

```bash
bindkey | grep fzf-file-widget
# "^T" fzf-file-widget
```

Your response is then passed through the `__fsel` and assigned to the `LBUFFER`, which significantly
alters the output. This occurs because the widget is attempting to place the command on the command
line while escaping special characters. See related discussion[^1].


https://github.com/junegunn/fzf/blob/952b6af4454ed55626d78e3845c6b5b640ac831d/shell/key-bindings.zsh#L63-L68

https://github.com/junegunn/fzf/blob/952b6af4454ed55626d78e3845c6b5b640ac831d/shell/key-bindings.zsh#L42-L56

### Possible options:
1. You would need to create your own widget or modify the existing one. 
2. Instead of using `"alt-b:become(bat {})"`, consider using `"alt-b:execute(bat {} >/dev/tty)"` [^2]

---

>[!NOTE]
> This line appears to be a _hacky_ workaround:
> ```bash
> FZF_CTRL_T_KEYBINDINGS=$(echo "${FZF_CTRL_T_KEYBINDINGS_ARRAY}" | sed 's/) c/),c/g')
> ```
> The following format may be a better alternative in `zsh` [^3]
> ```bash
> FZF_CTRL_T_KEYBINDINGS="${(j:,:)FZF_CTRL_T_KEYBINDINGS_ARRAY}"
> ```

[^1]: [Manual output on enter, no linebreak. · Discussion #3514](https://github.com/junegunn/fzf/discussions/3514)
[^2]: ['>/dev/tty' Issue #2579](https://github.com/junegunn/fzf/issues/2579#issuecomment-919770417)
[^3]: [zsh: 14 Parameter-Expansion-Flags](https://zsh.sourceforge.io/Doc/Release/Expansion.html#Parameter-Expansion-Flags)

**Comment by junegunn** [comment]
That's pretty impressive @LangLangBart, thanks for sharing your solution.

I was curious how you got it to work when accessing the `GET /` endpoint from `execute-*` or `transform-*` action would put fzf into a deadlock, but I noticed `&` at the end. That's clever. But at the same time, it's unfortunate that someone would need a deep knowledge of the inner workings of fzf to use such a workaround. I suppose it would be very helpful to expose counters, right? i.e. `{fzf:total-count}`, `{fzf:match-count}`, etc. What do you think? I have also thought about exposing the information via environment variables instead. e.g. `$FZF_TOTAL_COUNT`, but I haven't really thought through the pros and cons of both methods.

**Comment by marslo** [comment]
Hi @LangLangBart , seems this command is not working in `fzf v0.68.0`:

```
find . -type f -maxdepth 1 | FZF_DEFAULT_OPTS="" fzf --listen --preview 'bat --color=always {}' --preview-window 'up,border-bottom' --bind $'change:execute-silent:(set -x; { new_size=$(curl -s localhost:$FZF_PORT | jq --raw-output --argjson rows "$LINES" \'[([($rows/3), ($rows - .matchCount - 5) ] | max),($rows - 5)] | min | floor\'); curl -s localhost:$FZF_PORT -d "change-header(Preview Window Size: $new_size / Rows: $LINES)+change-preview-window:$new_size" }  2>&1 | tee -a ~/test_debug.txt ) &'
```

screenshot as below:

<img width="1331" height="884" alt="Image" src="https://github.com/user-attachments/assets/bc42369d-2d65-41ee-8937-31f7e862b38e" />

details:
![Image](https://github.com/user-attachments/assets/5c5226dc-d90d-4429-a79f-cd2e9b30fd19)

**Comment by LangLangBart** [comment]
> Hi [@LangLangBart](https://github.com/LangLangBart) , seems this command is not working in `fzf v0.68.0`:

Right, in Bash it wont work for me either; it should work with `--with-shell 'zsh -dfc'`

**BUT**, since this demo was created, the maintainer has introduced new
`FZF_*` environment variables that make this _"hack"_ outdated.

Could you take a look at the `0.46.0` CHANGELOG[^1]? The maintainer provided a
**transformer** example that may work out of the box for you, or with slight
adjustments if needed, maybe u would use different values or other trigger
events (`focus`, `change`, ...).

```bash
# Script to dynamically resize the preview window by 'junegunn'
transformer='
# 1 line for info, another for the prompt, and 2 more lines for the preview window border
lines=$(( FZF_LINES - FZF_MATCH_COUNT - 4 ))
if [[ $FZF_MATCH_COUNT -eq 0 ]]; then
  echo "change-preview-window:hidden"
elif [[ $lines -gt 3 ]]; then
  echo "change-preview-window:$lines"
elif [[ $FZF_PREVIEW_LINES -ne 3 ]]; then
  echo "change-preview-window:3"
fi'

find . -type f -maxdepth 1 | FZF_DEFAULT_OPTS="" fzf \
  --preview 'bat --color=always {}' \
  --preview-window 'up,border-bottom' \
  --bind "result:transform:$transformer" \
  --bind "resize:transform:$transformer"
```


[^1]: https://github.com/junegunn/fzf/blob/master/CHANGELOG.md#0460

**Comment by marslo** [comment]
Hi @LangLangBart, great appreciate for your professional answer !! Works like a charm !!!

![Image](https://github.com/user-attachments/assets/39170a38-1b5a-4d0f-bea6-12a32e806b27)
