### ISSUE TITLE
Temporary file for {+f} placeholder not created after transform action

### ISSUE THREAD

**Issue by LangLangBart** [junegunn/fzf#3575]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Mac OS X
- Shell
    - [x] zsh

## Problem / Steps to reproduce

I encountered an issue where the temporary file for the `{+f}` placeholder is not being created
following a `transform` action. It functions correctly upon initialisation, but after using the <kbd>⌃Control</kbd> + <kbd>T</kbd>
hotkey twice, the preview displays an error indicating that it cannot locate the temporary file. 

```bash
fzf --version
# 0.45.0 (brew)

seq 12 |  FZF_DEFAULT_OPTS="" fzf --multi --preview-window 'nohidden' \
	--preview 'cat {+f}' \
	--preview-window 'top' \
	--prompt "Multi preview > " \
	--bind 'ctrl-t:transform:[[ ! {fzf:prompt} =~ Multi ]] &&
		echo "change-prompt(Multi preview > )+change-preview:cat {+f}" ||
		echo "change-prompt(Single preview > )+change-preview:echo {}"'
```

<img src="https://github.com/junegunn/fzf/assets/92653266/128f4044-8af9-4537-9825-5dccafdec392" width="600">

---

PS: The placeholder `{+}` functions correctly instead of using `{+f}`.

**Comment by junegunn** [comment]
Oh, in this case, the placeholders must be escaped so that they are not immediately expanded at the time of `transform`.
i.e. `cat \{+f}` and `echo \{}`

Does this answer your question?
