### ISSUE TITLE
`fzf` install via homebrew not working with fish integration

### ISSUE THREAD

**Issue by mxaddict** [junegunn/fzf#3578]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [x] fish

## Problem / Steps to reproduce

install fzf via homebrew (version 0.45.0)
use fish as default shell
add fish hooks into config.fish
don't get the commands available in fish

<img width="296" alt="Screenshot 2024-01-12 at 8 12 25 PM" src="https://github.com/junegunn/fzf/assets/1060905/a8f06b41-a5b5-4044-a1de-663757e544f1">

<img width="398" alt="Screenshot 2024-01-12 at 8 13 39 PM" src="https://github.com/junegunn/fzf/assets/1060905/e6d32452-6c8a-4c68-aa93-afff4623ad5e">

NOTES:
* Fish is working fine
* fzf is also working fine when called standalone
* But the fish integration seems to be borked

**Comment by LangLangBart** [comment]
> * But the fish integration seems to be borked

I switched my shell from `zsh` to `fish` and it worked by following these instructions:

1. set `fish`
```bash
# get fish
brew install fish

# add fish to the list of valid shells
echo /usr/local/bin/fish | sudo tee -a /etc/shells

# make fish the default shell
chsh -s /usr/local/bin/fish
```

2. check `brew` infos for `fzf`

```bash
 brew info fzf
==> fzf: stable 0.46.1, HEAD
Command-line fuzzy finder written in Go
https://github.com/junegunn/fzf
/usr/local/Cellar/fzf/0.46.1 (17 files, 3.9MB) *
  Built from source on 2024-02-02 at 09:58:33
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/f/fzf.rb
License: MIT
==> Dependencies
Build: go ✔
==> Options
--HEAD
        Install HEAD version
==> Caveats
To install useful keybindings and fuzzy completion:
  /usr/local/opt/fzf/install

To use fzf in Vim, add the following line to your .vimrc:
  set rtp+=/usr/local/opt/fzf
```

3. run the `install`[^1] script 

```bash
/usr/local/opt/fzf/install --no-zsh --no-bash
Downloading bin/fzf ...
  - Already exists
  - Checking fzf executable ... 0.46.1
Do you want to enable fuzzy auto-completion? ([y]/n) y
Do you want to enable key bindings? ([y]/n) y

Update fish_user_paths ... OK
Symlink /Users/paria/.config/fish/functions/fzf_key_bindings.fish ... OK

Do you want to update your shell configuration files? ([y]/n) y

Create /Users/paria/.config/fish/functions/fish_user_key_bindings.fish:
    function fish_user_key_bindings
      fzf_key_bindings
    end

Finished. Restart your shell or reload config file.
   fzf_key_bindings  # fish
```

4. check setup

<img src="https://github.com/junegunn/fzf/assets/92653266/57222917-5a31-408d-a83e-bbb318518965" width="600">

<details>

5. and now back to `zsh` 👻 

</details>

[^1]: [junegunn/fzf/blob/master/install](https://github.com/junegunn/fzf/blob/master/install)

**Comment by mxaddict** [comment]
Thanks, that worked!

**Comment by dhoppe** [comment]
I had a similar issue and according to the output of the command `/opt/homebrew/opt/fzf/install --no-bash --no-zsh`, I had to move the command `fzf --fish | source` from `conf.d` to `functions` to make sure that fzf gets integrated after homebrew, otherwise I would get a message like `fzf was not found in path`.

~/.config/fish/conf.d/fzf.fish
```
/opt/homebrew/bin/fzf --fish | source
```

~/.config/fish/functions/fish_user_key_bindings.fish
```
function fish_user_key_bindings
  /opt/homebrew/bin/fzf --fish | source
end
```

Maybe this should be mentioned at the README.md?
