### ISSUE TITLE
Change-preview action not permanently updating in fzf when triggered through a transform action

### ISSUE THREAD

**Issue by LangLangBart** [junegunn/fzf#3579]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] macOS
- Shell
    - [x] zsh

## Problem / Steps to reproduce

The preview will not permanently change when the `change-preview` action is triggered through a
`transform` action.

For instance, if the user presses the <kbd>⌃ Control</kbd> + <kbd>T</kbd> key once, one might expect
the preview to be set to `echo {}`. However, the preview does not update when the focus is shifted.

```bash
seq 12 | FZF_DEFAULT_OPTS="" fzf --multi --preview 'echo {+}' \
	--bind 'load:select-all' \
	--prompt 'First Preview > ' \
	--bind 'ctrl-t:transform:[[ ! {fzf:prompt} =~ First ]] &&
        echo "change-prompt(First Preview > )+change-preview:echo {+}" ||
        echo "change-prompt(Second Preview > )+change-preview:echo {}"'
```

After the user presses the <kbd>⌃ Control</kbd> + <kbd>T</kbd> key followed by the <kbd>↑</kbd> key, the
 preview remains unchanged in the **GIF** below. 

<img src="https://github.com/junegunn/fzf/assets/92653266/f613edf4-7bdf-4b32-a8af-1f678efb40b6" width="600">

**Comment by junegunn** [comment]
This is the same issue as #3575. You should escape the placeholders so that they're not immediately evaluated.

```
seq 12 | FZF_DEFAULT_OPTS="" fzf --multi --preview 'echo {+}' \
	--bind 'load:select-all' \
	--prompt 'First Preview > ' \
	--bind 'ctrl-t:transform:[[ ! {fzf:prompt} =~ First ]] &&
        echo "change-prompt(First Preview > )+change-preview:echo \{+}" ||
        echo "change-prompt(Second Preview > )+change-preview:echo \{}"'
```

I can see that this can be quite confusing, but I don't have a better idea at the moment.

**Comment by LangLangBart** [comment]
> I can see that this can be quite confusing, but I don't have a better idea at the moment.

Thank you once again. At first, I misunderstood and only applied it to the filename placeholder `\{+f}`.

---

Escaping all the placeholder now also resolves the final issue I encountered when applying the
`transform` action to the _Switching between Ripgrep mode and fzf mode_ function[^1]. Previously,
the function would always strip the quotes from a string when reverting back to `ripgrep` mode.
However, using `\{q}` seems to solve this problem.

Take note of the changes to the string `"sync"` when using `{q}` and `\{q}` in the GIF below.


**modified function**

```bash
rm -f /tmp/rg-fzf-{r,f}
RG_PREFIX="rg --column --line-number --no-heading --color=always --smart-case "
INITIAL_QUERY="${*:-}"
: | fzf --ansi --disabled --query "$INITIAL_QUERY" \
	--bind "start:reload:$RG_PREFIX {q}" \
	--bind "change:reload:sleep 0.1; $RG_PREFIX {q} || true" \
	--bind "ctrl-t:transform:[[ ! {fzf:prompt} =~ fzf ]] &&
		echo 'unbind(change)+change-prompt(2. fzf> )+enable-search+transform-query:echo \{q} > /tmp/rg-fzf-r; cat /tmp/rg-fzf-f' ||
		echo 'rebind(change)+change-prompt(1. ripgrep> )+disable-search+transform-query:echo \{q} > /tmp/rg-fzf-f; cat /tmp/rg-fzf-r'" \
	--color "hl:-1:underline,hl+:-1:underline:reverse" \
	--prompt '1. ripgrep> ' \
	--delimiter : \
	--header 'CTRL-T: Switch between ripgrep/fzf' \
	--preview 'bat --color=always {1} --highlight-line {2}' \
	--preview-window 'up,60%,border-bottom,+{2}+3/3,~3' \
	--bind 'enter:become(vim {1} +{2})'
```


<img src="https://github.com/junegunn/fzf/assets/92653266/3ce8ed55-df00-4d40-a41c-3f0adf48ec50" width="800">

[^1]: [ADVANCED.md Switching between Ripgrep mode and fzf mode](https://github.com/junegunn/fzf/blob/master/ADVANCED.md#switching-between-ripgrep-mode-and-fzf-mode)
