### ISSUE TITLE
fzf-emacsbuffers

### ISSUE THREAD

**Issue by dingmingxin** [junegunn/fzf#358]
Here I wrote an util with fzf for quick access emacs(daemon mode) opening buffers.

https://github.com/dingmingxin/fzf-emacsbuffers

**Comment by junegunn** [comment]
Hi, that's nice. Feel free to add you project to the wiki page. Also, you might want to check out [fzf.el](https://github.com/bling/fzf.el) which integrates fzf with emacs. Thanks.
