### ISSUE TITLE
Tab Completion results with error unknown option: --scheme=path

### ISSUE THREAD

**Issue by sk3l10x1ng** [junegunn/fzf#3580]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

## Problem / Steps to reproduce

1. Install latest version of fzf
2. Type `cd **`  and press tab in bash terminal.
3. Receives a error `unknown option: --scheme=path`

Please see the attached screenshot

![image](https://github.com/junegunn/fzf/assets/58649792/b355ccae-1699-4377-ab65-293900f29959)

**Comment by LangLangBart** [comment]
Could you please check if you have any other versions of `fzf` installed? It's possible that an
older version of `fzf` is being used within `key-bindings.bash`. The `--scheme=path` was added to
`fzf` in version `0.033.0`[^1]. You might also want to look at related issues, such as #2996, for any
additional insights.


```bash
type -a fzf
# fzf is /usr/local/bin/fzf
# fzf is /Users/paria/.cache/zsh4humans/v5/fzf/bin/fzf

/usr/local/bin/fzf --version
# 0.45.0 (brew)

/Users/paria/.cache/zsh4humans/v5/fzf/bin/fzf --version
# 0.33.0 (e03ac31)
```

[^1]: [CHANGELOG.md 0.33.0](https://github.com/junegunn/fzf/blob/master/CHANGELOG.md#0330)

**Comment by sk3l10x1ng** [comment]
You are right , the currently installed fzf was running on low version 0.29 . I have replaced the binary in `/usr/bin/fzf` with new fzf ( Version 0.45.0 ). 

The issued is fixed

Thank you so much. @LangLangBart

**Comment by LangLangBart** [comment]
> You are right , the currently installed fzf was running on low version `0.29` . I have replaced the binary in `/usr/bin/fzf` with new fzf Version `0.45.0 `.

Adjusting the `PATH`, a colon-separated list of directories where the shell searches for executable
commands, is generally advisable.

Example:
- When added to the end of the `PATH`, the shell will prioritize searching all other directories
  first.
    - `export PATH="$PATH:/usr/local/bin"`
- Adding the directory to the beginning of the `PATH` variable gives it higher precedence.
    - `export PATH="/usr/local/bin:$PATH"`
