### ISSUE TITLE
fzf#run not able to open the file when filename and contents are passed.

### ISSUE THREAD

**Issue by justrajdeep** [junegunn/fzf#3583]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [x] zsh
    - [ ] fish

## Problem / Steps to reproduce

Hi 

I have this mapping in my `.vimrc`

    command! -bang -complete=file -nargs=1 LS  call fzf#run(fzf#wrap('ls_filelist', {'source': '\bat <q-args> | \xargs \awk ''NF {print FILENAME " :"NR":"$0 }'' '}, <bang>0))

from my vim i pass `:LS <<filelist>>` 

`filelist` is a list of filenames ... I can search for name/contents of a file using FZF. 

But when i try to open it, vim does not realize what is the name and cant open the file.

Any suggestion as to how to tell FZF what is the name of the file and open the filat at that line number?

**Comment by justrajdeep** [comment]
I tried changing the mapping to something like this 

    command! -bang -complete=file -nargs=1 LS  call fzf#run(fzf#wrap('ls_filelist', {'source': '\bat <q-args> | \xargs \rg --line-number --no-heading --color=never --smart-case --follow --hidden "[A-Za-z0-9]" ' }, <bang>0))


sometimes it works ... sometimes it does not ... i am not sure what is breaking it

**Comment by junegunn** [comment]
You didn't specify your `sink` function, so `fzf#run` chooses [the default implementation](https://github.com/junegunn/fzf/blob/1a9ea6f738cfafab83a5e0e828e60f0bf68bffee/plugin/fzf.vim#L302-L342) that doesn't understand `FILENAME:LINE:COL` format. It can only process `FILENAME`s.

In short, you need to provide your own `sink` (or `sink*`) function.

Or, you can have a global autocmd in your Vim configuration that handles the format.

This is what I have in my .vimrc

```vim
" ----------------------------------------------------------------------------
" Open FILENAME:LINE[:COL]
" ----------------------------------------------------------------------------
function! s:goto_line()
  let tokens = matchlist(expand('%'), '^\([^:]\+\):\(\d\+\)\%(:\(\d\+\)\)\?$')
  if empty(tokens) || !filereadable(tokens[1])
    return
  endif

  bd!
  silent execute 'e' tokens[1]
  execute printf('normal! %sG%s|', tokens[2], tokens[3])
endfunction

autocmd vimrc BufNewFile * nested call s:goto_line()
```

**Comment by justrajdeep** [comment]
Thanks
