### ISSUE TITLE
Visual Glitch in Selected Line with Custom Pointer on Master Branch

### ISSUE THREAD

**Issue by LangLangBart** [junegunn/fzf#3588]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] macOS
- Shell
    - [x] zsh
- Terminal
    - [x] macOS default terminal
## Problem / Steps to reproduce

A noticeable visual glitch can be observed in the selected line on the `master` branch when
executing the following command. The issue is not present in the latest release `0.45.0`.

```bash
seq 5 | FZF_DEFAULT_OPTS="" fzf --pointer '▶'
```

The character used as a pointer is this one:

| Character                     | Unicode                                                             |
| ----------------------------- | ------------------------------------------------------------------- |
| BLACK RIGHT-POINTING TRIANGLE | [U+25B6](https://util.unicode.org/UnicodeJsps/character.jsp?a=25B6) |

The GIF below runs the same command once for the `0.45.0` build version and the `master` branch,
highlighting the visual issue.

<img src="https://github.com/junegunn/fzf/assets/92653266/0269a57f-4b8f-4842-aa57-b121a7f3abad" width="600">

After conducting a `git bisect`, it was determined that commit 91bea9c5b311aa6a9919b814adc2fbb9405df2a5
is the source of the issue.

```bash
git bisect start HEAD 0.45.0

# keep repeating until bisecting identifies the commit
make clean
make && make install

git bisect good/bad

# 91bea9c5b311aa6a9919b814adc2fbb9405df2a5 is the first bad commit
# commit 91bea9c5b311aa6a9919b814adc2fbb9405df2a5
# Author: Junegunn Choi <junegunn.c@gmail.com>
# Date:   Sun Jan 7 15:08:56 2024 +0900

#     Use forked version of go-runewidth

#     Fix #3558

#       go get github.com/junegunn/go-runewidth@fzf

#  go.mod | 2 ++
#  go.sum | 2 ++
#  2 files changed, 4 insertions(+)
```

**Comment by junegunn** [comment]
I fixed the issue in my fork of go-runewidth, but I'm far from an expert in the emoji/Unicode department, so the fix is probably incomplete. So please let me know if you see any other problems. Thanks.

https://github.com/junegunn/go-runewidth/commit/7d2ea235ec542c955caf1e38e01ab0655c854fb6
