### ISSUE TITLE
Behavior of sink* when match not found

### ISSUE THREAD

**Issue by jebaum** [junegunn/fzf#359]
I'm attempting to create a fzf.vim function which will either load a session (managed by https://github.com/manuel-colmenero/vim-simple-session) or create a new one. vim-simple-session contains a function called `s:SwitchSession` which, given a string, will switch to a session if it exists or create a new one by that name if it doesn't. I would expect the below code to work, but from what I can tell due to the commented out `echom` lines, the sink isn't getting called in the case that the exit status of fzf is 1 (a query was entered but there was no match). So the function works for switching to an existing session, but not for creating a new one.

related: https://github.com/junegunn/fzf/issues/345

```
function! Fzfvimsessions()
  let sessions = session#list()
  " call add(sessions, 'idk')
  " call add(sessions, 'bro')
  " echom join(sessions, "::")

  call fzf#run({
  \ 'source':   sessions,
  \ 'sink*':    function('CallSimpleSessionSwitch'),
  \ 'window':  '10new',
  \ 'options': '--print-query -x --tiebreak=index --ansi --prompt="Sessions> "',
  \})
endfunction

function! CallSimpleSessionSwitch(name)
  " echom 'wrapper to SwitchSession called'
  " echom join(a:name, "--")
  " due to --print-query, first item in list will be the typed query
  let session_name = a:name[-1]
  call SCall('plugin/session.vim', 'SwitchSession', [session_name])
endfunction
```

**Comment by jebaum** [comment]
problem is around line 238 of fzf.vim where it checks v:shell_error. not sure what the proper behavior should be. I don't see why an exit status of 1 shouldn't continue on to call the callback function, but the comment there makes it pretty explicit so I'm guessing you have a reason. perhaps a new option should be accepted in the dictionary you can pass to `fzf#run()` to determine how exit status 1 should be handled?

**Comment by jebaum** [comment]
actually after a little more investigation this definitely seems like a bug. if calling the tmux or neovim execute funcions, if fzf exits with status 1 it still calls the sink function. so my code from my original comment works fine if you open fzf in a tmux pane or a neovim `:term`. it's just the case of vim with fzf not in tmux where the behavior is different.

**Comment by junegunn** [comment]
Cool, thanks. Exit status of 1 was a recent change, and I think I forgot to update the vim plugin accordingly.

**Comment by junegunn** [comment]
So it should be:
- 0 or 1 -> sink
- 130 -> cancel, ignore
- rest -> error message

**Comment by junegunn** [comment]
Hmm, looks like tmux and term version also need update.

**Comment by jebaum** [comment]
I just finished updating `s:execute()`, I'm happy to do those too but I'm not sure what you're referring to since they work fine for me

**Comment by junegunn** [comment]
There are some corner cases, please send me the PR, I'll do the rest.

**Comment by junegunn** [comment]
Merged your fix and updated the other ones too. Thanks!
