### ISSUE TITLE
CTRL-R history search inserting `number*` in zsh

### ISSUE THREAD

**Issue by deathbeam** [junegunn/fzf#3591]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

## Problem / Steps to reproduce

I think this is regression as I found this pull request:

https://github.com/junegunn/fzf/pull/2140

```
$ fzf --version
0.45.0 (202401011)
```

When i use ctrl-r:

![image](https://github.com/junegunn/fzf/assets/5115805/ee41cfc4-8ee1-4eb9-a123-279134cdebe7)

When i select it:

![image](https://github.com/junegunn/fzf/assets/5115805/d82acf27-2599-46bd-8204-af8e563357d2)

When i select history without * (e.g not shared):

![image](https://github.com/junegunn/fzf/assets/5115805/adad6b16-2518-49e5-8947-f7c445559e26)

To reproduce simply:

```
setopt SHARE_HISTORY
```

then have some shared history (from running command in diff shell) and then use ctrl-r

**Comment by deathbeam** [comment]
Looks like reverting this commit fixes it: https://github.com/junegunn/fzf/commit/2671259fdb3094a5eac528f291c1fdadbcf9eda9

But obviously not ideal

**Comment by junegunn** [comment]
Does this patch fix the problem?

```diff
diff --git a/shell/key-bindings.zsh b/shell/key-bindings.zsh
index 8a77047..492cac3 100644
--- a/shell/key-bindings.zsh
+++ b/shell/key-bindings.zsh
@@ -103,8 +103,8 @@ fzf-history-widget() {
   local ret=$?
   if [ -n "$selected" ]; then
     num=$(awk '{print $1}' <<< "$selected")
-    if [[ "$num" =~ ^[1-9][0-9]*$ ]]; then
-      zle vi-fetch-history -n $num
+    if [[ "$num" =~ '^[1-9][0-9]*\*?$' ]]; then
+      zle vi-fetch-history -n ${num/\*}
     else # selected is a custom query, not from history
       LBUFFER="$selected"
     fi
```

**Comment by deathbeam** [comment]
> ```diff
> if [[ "$num" =~ '^[1-9][0-9]*\*?$' ]]; then
> +      zle vi-fetch-history -n ${num%\*}
> ```

It does:

![image](https://github.com/junegunn/fzf/assets/5115805/a20cae91-9654-4bbd-a14c-f78308a22cac)

![image](https://github.com/junegunn/fzf/assets/5115805/bfc6890b-ae2e-4429-b907-418f146439a4)

**Comment by junegunn** [comment]
Thanks, is there any other pattern we should handle?

**Comment by LangLangBart** [comment]
>  zle vi-fetch-history -n ${num%\*}

Is this truly necessary? In my testing, `zle vi-fetch-history` appears to handle the optional asterisk correctly. It was primarily the above regex that was overly strict and send the line to the `LBUFFER`.

**Comment by junegunn** [comment]
> Is this truly necessary?

Probably not. But the official document for `vi-fetch-history` doesn't mention anything about allowing non-numeric suffixes, so I think it's safer to do it even though it's not needed now.

> vi-fetch-history (unbound) (G) (unbound)
> Fetch the history line specified by the numeric argument. This defaults to the current history line (i.e. the one that isn’t history yet).

**Comment by LangLangBart** [comment]
> Probably not. But the official document for `vi-fetch-history` doesn't mention anything about
> allowing non-numeric suffixes, so I think it's safer to do it even though it's not needed now.

Indeed, you're correct. The argument is definitely intended to be a number.

```bash
man 1 zshzle
#  widget [ -n num ] [ -f flag ] [ -Nw ] [ -K keymap ] args ...
# 	Invoke  the  specified widget.  This can only be done when ZLE is active; nor-
# 	mally this will be within a user-defined widget.

# 	With the options -n and -N, the current numeric argument  will  be  saved  and
# 	then  restored  after  the  call to widget; `-n num' sets the numeric argument
# 	temporarily to num, while `-N' sets it to the default, i.e. as if  there  were
# 	none.
# …
```

Although, the `-n` argument's parsing appears to take place in the `zle_thingy.c` file [^1],
`vifetchhistory` utilizes this argument[^2].  This process uses the Standard C Library function
`atoi`[^3].


```bash
man 3 atoi
# atoi, atoi_l -- convert ASCII string to integer
# …
```

```c
zmod.mult = atoi(num);
```

| Input     | Output |
| --------- | ------ |
| `12`      | `12`   |
| `34*`     | `34`   |
| `*56`     | `0`    |
| `-78`     | `-78`  |
| `+9`      | `9`   |
| `'hello'` | `0`    |

[^1]: [sourceforge.net - Src/Zle/zle_thingy.c](https://sourceforge.net/p/zsh/code/ci/master/tree/Src/Zle/zle_thingy.c#l762)
[^2]: [sourceforge.net - Src/Zle/zle_hist.c](https://sourceforge.net/p/zsh/code/ci/master/tree/Src/Zle/zle_hist.c#l1783)
[^3]: [opensource.apple.com - atoi.c](https://opensource.apple.com/source/Libc/Libc-1439.40.11/stdlib/FreeBSD/atoi.c.auto.html)

**Comment by dam5h** [comment]
I am on zsh and still getting the number asterisk pattern on version `0.46.1` when selecting failed commands.

Example:
```
~ 
❯ fzf --version
0.46.1 (3c0a6304)

~ 
❯  1754* cargo test

Is this config related or should it be fixed, as I noticed the commit that addresses this for zsh is tagged 0.46.1?

**Comment by LangLangBart** [comment]
> I am on zsh and still getting the number asterisk pattern on version `0.46.1` when selecting
> failed commands.

I couldn't reproduce the issue. Could you please confirm that the correct `key-bindings.zsh` file is
being sourced from your `.zshrc`, and that <kbd>⌃ Control</kbd> + <kbd>R</kbd> is assigned to
`fzf-history-widget`?

```bash
bindkey | grep -F '^R'
"^R" fzf-history-widget
```

The function should match the one you see in the link when you run the `whence -c …` command:

```bash
 whence -c fzf-history-widget
```

https://github.com/junegunn/fzf/blob/1833670fb91dfa17047af320ce7f015e0d500ba6/shell/key-bindings.zsh#L97-L118


The environment variables `FZF_CTRL_R_OPTS` and `FZF_DEFAULT_OPTS` are being read for other
configurations. You could also share these assignments.


---


After confirming all the above steps, let's attempt to debug the issue. Open the `key-bindings.zsh`
file and enabling `xtrace`, which prints commands and their arguments as they are executed. Trigger
this by pressing the hotkey combination <kbd>⌃ Control</kbd> + <kbd>R</kbd>. This should provide us
with some insight into the problem.


```diff
--- a/key-bindings.zsh
+++ b/key-bindings.zsh
@@ -101,6 +101,7 @@ fzf-history-widget() {
   selected="$(fc -rl 1 | awk '{ cmd=$0; sub(/^[ \t]*[0-9]+\**[ \t]+/, "", cmd); if (!seen[cmd]++) print $0 }' |
     FZF_DEFAULT_OPTS="--height ${FZF_TMUX_HEIGHT:-40%} ${FZF_DEFAULT_OPTS-} -n2..,.. --scheme=history --bind=ctrl-r:toggle-sort,ctrl-z:ignore ${FZF_CTRL_R_OPTS-} --query=${(qqq)LBUFFER} +m" $(__fzfcmd))"
   local ret=$?
+  set -o xtrace
   if [ -n "$selected" ]; then
     num=$(awk '{print $1}' <<< "$selected")
     if [[ "$num" =~ '^[1-9][0-9]*\*?$' ]]; then
@@ -110,6 +111,7 @@ fzf-history-widget() {
     fi
   fi
   zle reset-prompt
+  set +o xtrace
   return $ret
 }
 zle     -N            fzf-history-widget
```

```bash
# example result after enabling 'xtrace'
+fzf-history-widget:4> selected=' 8280* cargo test'
+fzf-history-widget:6> local ret=0
+fzf-history-widget:7> [ -n ' 8280* cargo test' ']'
+fzf-history-widget:8> num=+fzf-history-widget:8> awk '{print $1}'
+fzf-history-widget:8> num='8280*'
+fzf-history-widget:9> [[ "$num" -regex-match '^[1-9][0-9]*\*?$' ]]
+fzf-history-widget:10> zle vi-fetch-history -n 8280
+fzf-history-widget:15> zle reset-prompt
```

**Comment by aDogCalledSpot** [comment]
I'm experiencing the same issue (but a year later). Also in zsh and running Arch with fzf version 0.64.0 (0076ec2e).

**Comment by LangLangBart** [comment]
> I'm experiencing the same issue (but a year later). Also in zsh and running Arch with fzf version 0.64.0 

Do you remember if this started happening recently, such as after upgrading to a new version of fzf?

Please post the line how u enable fzf's zsh setup or if possible a link to your zshrc setup.

Could you try running the commands below when it happens again and post the results here?

```bash
# Improved trace prompt
PS4='%B%F{0}+ %D{%T:%3.} %2N:%i%f%b '
# Enable tracing for the fzf zsh functions
typeset -fT fzf-history-widget __fzf_exec_awk
# Press Ctrl-R, then Enter
```

Copy and paste the last 10–20 lines here. The output should look similar to the example below.

```bash
+ 12:29:49:777 fzf-history-widget:12 selected='  427* ls' 
+ 12:29:51:863 fzf-history-widget:16 local ret=0
+ 12:29:51:863 fzf-history-widget:17 [ -n '  427* ls' ']'
+ 12:29:51:863 fzf-history-widget:18 [[ $(__fzf_exec_awk '{print $1; exit}' <<< "$selected") -regex-match ^[1-9][0-9]*+ 12:29:51:866 fzf-history-widget:18 __fzf_exec_awk '{print $1; exit}'
+ 12:29:51:866 __fzf_exec_awk:1 [[ -z '' ]]
+ 12:29:51:867 __fzf_exec_awk:2 __fzf_awk=awk 
+ 12:29:51:867 __fzf_exec_awk:3 [[ darwin24.2.0 == solaris* ]]
+ 12:29:51:868 __fzf_exec_awk:6 local n x y z d
+ 12:29:51:870 __fzf_exec_awk:7 mawk -W version
+ 12:29:51:874 __fzf_exec_awk:7 IFS=' .' + 12:29:51:874 __fzf_exec_awk:7 read n x y z d
+ 12:29:51:874 __fzf_exec_awk:8 [[ '' == mawk ]]
+ 12:29:51:875 __fzf_exec_awk:11 LC_ALL=C awk '{print $1; exit}'
+ 12:29:51:863 fzf-history-widget:18 [[ $(__fzf_exec_awk '{print $1; exit}' <<< "$selected") -regex-match ^[1-9][0-9]* ]]
+ 12:29:51:878 fzf-history-widget:19 zle vi-fetch-history -n 427
+ 12:29:51:878 fzf-history-widget:24 zle reset-prompt
```

**Comment by aDogCalledSpot** [comment]
Thank you for taking the time to look into this!

> Do you remember if this started happening recently, such as after upgrading to a new version of fzf?

I just double-checked by reinstalling some older versions of the Arch package. The newest version apart from 0.64.0 that I have installed is 0.62.0 in which I **do not** have the issue.
[Looks like a version 0.63 was never published](https://archive.archlinux.org/packages/f/fzf/).

[Link to zshrc](https://gitlab.com/aDogCalledSpot/dotfiles/-/blob/master/zsh/.config/zsh/.zshrc?ref_type=heads#L16)

```text
+ 19:28:03:526 fzf-history-widget:7 selected=$'5730\ttypeset -fT fzf-history-widget __fzf_exec_awk'
+ 19:28:05:654 fzf-history-widget:16 local ret=0
+ 19:28:05:654 fzf-history-widget:17 [ -n $'5730\ttypeset -fT fzf-history-widget __fzf_exec_awk' ']'
+ 19:28:05:654 fzf-history-widget:18 [[ $(__fzf_exec_awk '{print $1; exit}' <<< "$selected") -regex-match ^[1-9][0-9]*+ 19:28:05:655 fzf-history-widget:18 __fzf_exec_awk '{print $1; exit}'
+ 19:28:05:655 __fzf_exec_awk:1 [[ -z '' ]]
+ 19:28:05:655 __fzf_exec_awk:2 __fzf_awk=awk
+ 19:28:05:655 __fzf_exec_awk:3 [[ linux-gnu == solaris* ]]
+ 19:28:05:655 __fzf_exec_awk:6 local n x y z d
+ 19:28:05:656 __fzf_exec_awk:7 mawk -W version
+ 19:28:05:719 __fzf_exec_awk:7 IFS=' .' + 19:28:05:719 __fzf_exec_awk:7 read n x y z d
+ 19:28:05:719 __fzf_exec_awk:8 [[ '' == mawk ]]
+ 19:28:05:719 __fzf_exec_awk:11 LC_ALL=C awk '{print $1; exit}'
+ 19:28:05:654 fzf-history-widget:18 [[ $(__fzf_exec_awk '{print $1; exit}' <<< "$selected") -regex-match ^[1-9][0-9]* ]]
+ 19:28:05:720 fzf-history-widget:21 LBUFFER=$'5730\ttypeset -fT fzf-history-widget __fzf_exec_awk'
+ 19:28:05:720 fzf-history-widget:24 zle reset-prompt
+ 19:28:05:721 fzf-history-widget:25 return 0
```

Let me know if there is anything else I can help you with!

**Comment by LangLangBart** [comment]
> Let me know if there is anything else I can help you with!

Thanks, perfect information.

I believe #4468 will fix it. The issue was likely that `$(__fzf_exec_awk '{print $1; exit}' <<< "$selected")` produces an empty string, which then causes the 'if' test to fail. If you can download and source the updated `key-bindings.zsh` file from the linked PR and test it, that would be helpful.

**Comment by aDogCalledSpot** [comment]
Unfortunately, that didn't work. The output looks pretty much the same

```
+ 19:57:46:016 fzf-history-widget:7 selected=$'5738\ttypeset -fT fzf-history-widget __fzf_exec_awk'
+ 19:57:46:941 fzf-history-widget:16 local ret=0
+ 19:57:46:941 fzf-history-widget:17 [ -n $'5738\ttypeset -fT fzf-history-widget __fzf_exec_awk' ']'
+ 19:57:46:941 fzf-history-widget:18 [[ $(__fzf_exec_awk '{print $1; exit}' <<< "$selected") -regex-match ^[1-9][0-9]*+ 19:57:46:941 fzf-history-widget:18 __fzf_exec_awk '{print $1; exit}'
+ 19:57:46:942 __fzf_exec_awk:1 [[ -z '' ]]
+ 19:57:46:942 __fzf_exec_awk:2 __fzf_awk=awk
+ 19:57:46:942 __fzf_exec_awk:3 [[ linux-gnu == solaris* ]]
+ 19:57:46:942 __fzf_exec_awk:6 local n x y z d
+ 19:57:46:942 __fzf_exec_awk:7 mawk -W version
+ 19:57:47:005 __fzf_exec_awk:7 IFS=' .' + 19:57:47:005 __fzf_exec_awk:7 read n x y z d
+ 19:57:47:005 __fzf_exec_awk:8 [[ '' == mawk ]]
+ 19:57:47:005 __fzf_exec_awk:11 LC_ALL=C awk '{print $1; exit}'
+ 19:57:46:941 fzf-history-widget:18 [[ $(__fzf_exec_awk '{print $1; exit}' <<< "$selected") -regex-match ^[1-9][0-9]* ]]
+ 19:57:47:007 fzf-history-widget:21 LBUFFER=$'5738\ttypeset -fT fzf-history-widget __fzf_exec_awk'
+ 19:57:47:007 fzf-history-widget:24 zle reset-prompt
+ 19:57:47:007 fzf-history-widget:25 return 0
```

Also seeing the same issue with the key-bindings.zsh from the newest master branch.

**Comment by LangLangBart** [comment]
I believe you don't have `mawk` installed, right? The patch in #4468 made sure that the following line is no longer called:

```bash
> + 19:57:46:942 __fzf_exec_awk:7 mawk -W version
```

Could you try again with the command below, the link is the raw URL from the PR?

```bash
source <(curl https://raw.githubusercontent.com/LangLangBart/fzf/09548514e330366d9e4ebe5e09ec789c647a2698/shell/key-bindings.zsh)
typeset -fT fzf-history-widget __fzf_exec_awk
PS4='%B%F{0}+ %D{%T:%3.} %2N:%i%f%b '
# Press Ctrl-R, then Enter
```

**Comment by aDogCalledSpot** [comment]
That fixes it! Strange that it wasn't working before when I manually downloaded the file. So I assume this will be fixed in the next version?
