### ISSUE TITLE
[question] is it possible to combined both `__fzf_select__` and `__fzf_cd__` into `FZF_CTRL_T_COMMAND` dynamically 

### ISSUE THREAD

**Issue by marslo** [junegunn/fzf#3597]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

## Problem / Steps to reproduce

I would like to using some shortcut key, i.e. `CTRL-T` to handle `cd` and `vim` dynamically according to different type, which 
- when current type is directory << completely no clue  on this
  - before <kbd>Enter</kbd> key pressed, show tree in preview
  - after hit <kbd>Enter</kbd> key, cd to selected path

- when current type is file: << tried with `--bind` but no lucky
  - before <kbd>Enter</kbd> key pressed: show bat in preview ( i.e.: `FZF_CTRL_T_OPTS=" --preview 'bat -n --color=always {}'"` ) 
  - after hit <kbd>Enter</kbd> key, open editor ( i.e.: `--bind="enter:become(command nvim {})"` ) for selected item 

So, I've tried to `export FZF_CTRL_T_OPTS=--height 80% --preview 'bat -n --color=always {}' --bind 'ctrl-/:change-preview-window(down|hidden|)' --bind 'ctrl-p:preview-up,ctrl-n:preview-down' --header 'CTRL-N/CTRL-P to view contents' --bind="enter:become(command nvim {})"` to open editor for selected files. It's not what I expected, after analysis the process ( `$ ps aux | grep nvim | grep -v grep` ), I got: `nvim --embed <path/to/file>`, it should no `--embed` after `nvim`, what I should do ?

Here are details :

https://github.com/junegunn/fzf/assets/5822057/4e3bd161-1fa5-42ed-9ec9-c957bb67db44

**Comment by LangLangBart** [comment]
> * --bind="enter:become(command nvim {})"

Consider trying it with `/dev/tty` [^1], you can also use `execute` instead of `become` to be able to return to your list.

```bash
--bind "enter:become:command nvim {} >/dev/tty"
```

[^1]: [Issue #2579](https://github.com/junegunn/fzf/issues/2579#issuecomment-919770417)

**Comment by marslo** [comment]
> > * --bind="enter:become(command nvim {})"
> 
> Consider trying it with `/dev/tty` [1](#user-content-fn-1-cb12321043549a6a387bdfb7091e8400)[2](#user-content-fn-2-cb12321043549a6a387bdfb7091e8400), you can also use `execute` instead of `become` to be able to return to your list.
> 
> ```shell
> --bind "enter:become:command nvim {} >/dev/tty"
> ```
> 
> ## Footnotes
> 1. [Issue #2579](https://github.com/junegunn/fzf/issues/2579#issuecomment-919770417) [↩](#user-content-fnref-1-cb12321043549a6a387bdfb7091e8400)
> 2. https://reddit.com/r/bash/comments/wm4kir/fzf_repl/ijxmzbl/ [↩](#user-content-fnref-2-cb12321043549a6a387bdfb7091e8400)

Hey @LangLangBart,

Thanks for your comments, it's working for vim/nvim now. How to handle for `cd` if type is directory, can I have some where to define `[[ -d ... ]] && cd ... || nvim ...` ?

**Comment by LangLangBart** [comment]
> I tried:
>
> * `ctrl-e:execute(cd {} > /dev/tty)`
> * `ctrl-e:execute(cd {})`
> * `ctrl-e:become:cd {} > /dev/tty`
> * `ctrl-e:become:cd {}`

The `FZF_CTRL_T_OPTS`/ `CTRL-T` command pastes the selected file path into the command line. The
command `nvim {} > /dev/tty` is used to display the output to the terminal. However, this doesn't
work with `cd {} >/dev/tty`.


https://github.com/junegunn/fzf/blob/beb2de2dd995ae261084ead9903d7fa7c08da7af/shell/key-bindings.bash#L38-L42

https://github.com/junegunn/fzf/blob/beb2de2dd995ae261084ead9903d7fa7c08da7af/shell/key-bindings.bash#L19-L31

Have you considered using the `ALT-C` widget with the environment variables `FZF_ALT_C_COMMAND` and
`FZF_ALT_C_OPTS`?


https://github.com/junegunn/fzf/blob/beb2de2dd995ae261084ead9903d7fa7c08da7af/shell/key-bindings.bash#L44-L50

You can assign the `FZF_ALT_C_COMMAND` with a command to display both files and directories and the
`FZF_ALT_C_OPTS` with your preferred keybindings. However, I'm not fond of this approach as the
widget may also try to cd into a file when selected with enter, which is not ideal.

---

The best approach would be to create your own widget in `bash`. This could be based on the
`__fzf_cd__` command, with a command to list both files and directories. You can then handle the
cases in there. If it's a directory, then `cd` into it, and if it's a file, open it in `nvim`.

**Comment by marslo** [comment]
Hey @LangLangBart,

thanks for your detailed explanation.

Yes, I do have <kbd>alt</kbd>+<kbd>c</kbd>, and it works well. Just want to know whether if `__fzf_cd__` and `__fzf_select__` can be merge into single shortcut, and identify automatically `cd` or `vim`

anyway, thanks again, please help to close this question.

**Comment by LangLangBart** [comment]
> Just want to know whether if `__fzf_cd__` and `__fzf_select__` can be merge into single shortcut, and identify automatically `cd` or `vim` ( It doesn’t have to be ctrl+t )

The maintainer would need to make the call. 
Based on this related comment[^1], I don't think so.

> btw, is there any solution can avoid show folder type in bat as :
> 
> ```shell
> [bat error]: 'vimrc.d' is a directory
> ```
> 
> I mean, using `tree` as tool to previous for folder, and `bat` as tool to preview for file ?

this version is very popular 
```bash
--preview '([[ -f {} ]] && (bat --style=numbers --color=always {} || cat {})) || ([[ -d {} ]] && (tree -C {} | less)) || echo {} 2> /dev/null | head -200'
```

[^1]: https://github.com/junegunn/fzf/issues/3450#issuecomment-1732823841

**Comment by marslo** [comment]
> 
> > btw, is there any solution can avoid show folder type in bat as :
> > ```shell
> > [bat error]: 'vimrc.d' is a directory
> > ```  
> >   
> > I mean, using `tree` as tool to previous for folder, and `bat` as tool to preview for file ?
> 
> this version is very popular
> 
> ```shell
> --preview '([[ -f {} ]] && (bat --style=numbers --color=always {} || cat {})) || ([[ -d {} ]] && (tree -C {} | less)) || echo {} 2> /dev/null | head -200'
> ```
> 
> ## Footnotes
> 1. https://github.com/junegunn/fzf/issues/3450#issuecomment-1732823841 [↩](#user-content-fnref-1-9ce5ae76391a7d3f6fe97dd6f4ceb90f)

nice !! thanks !!

**Comment by backpropper** [comment]
I was looking for this exact functionality. Is there any update to support this? @junegunn @LangLangBart
