### ISSUE TITLE
Fzf on Windows doesn't accept keyboard input

### ISSUE THREAD

**Issue by LolnationCH** [junegunn/fzf#3598]
- [X] I have read through the manual page (`man fzf`)
- [X] I have the latest version of fzf
- [X] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [ ] Mac OS X
    - [X] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [ ] fish
    - [X] Powershell

## Problem / Steps to reproduce

I just updated to 0.46.0, and fzf doesn't accept any input (arrow keys, letters).

Version 0.45.0 works, I downgraded and tested.

I am using the Windows terminal with the latest powershell version.

Installed using the `winget install fzf` command.

### Steps to reproduce

Any query with fzf (even just the directory search, fzf with no args doesn't work.)

**Comment by junegunn** [comment]
Thanks for the report. Though I don't have a Windows PC to test it, I think da753fc should fix it.

I have replaced the binaries on https://github.com/junegunn/fzf/releases/tag/0.46.0, can you manually download the one for your platform and test if the problem is fixed?

**Comment by seshonaar** [comment]
I also encountered the issue, it now works with the updated binaries, thank you!

**Comment by LolnationCH** [comment]
@junegunn I confirm it works, thanks a lot!

**Comment by thorstenkampe** [comment]
@junegunn I can confirm it's fixed; thanks!
