### ISSUE TITLE
No Keyboard Input Accepted on Windows with version .46

### ISSUE THREAD

**Issue by cubanx** [junegunn/fzf#3600]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [ ] Mac OS X
    - [x] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [ ] fish
    - [x] Windows Terminal with PowerShell (but it behaves the same in cmd.exe as well)

## Problem / Steps to reproduce
I upgraded to `.46` and basically, when I run `fzf` it shows the list, but then I cannot enter any input.  It seems to not accept any keys, including escape, Ctrl-C, Ctrl-Break, etc.

The only way out is to kill that terminal.

I know `fzf` is primarily a Linux tool, but it has worked fantastically on Windows Terminal and PowerShell up until this version.

I downgraded to `.45` and it started working again.

I'm both looking to see if other Windows users have the issue and if there is any way at all I can help diagnose.

Thanks!

**Comment by junegunn** [comment]
The problem was identified and fixed in #3598. Subsequently, the broken binaries in https://github.com/junegunn/fzf/releases/tag/0.46.0 were replaced. The checksums for the winget package have also been corrected. https://github.com/microsoft/winget-pkgs/pull/135963/files

What method did you use to upgrade fzf? Can you try installing the new version again?

**Comment by jamesonBradfield** [comment]
I used scoop, the winget version seems to work, but the scoop one doesn't

**Comment by cubanx** [comment]
I used winger so we should be all good.

I'm so sorry I did t find the other issue.

I promise I looked but I guess my searching prowess was not great

**Comment by junegunn** [comment]
No problem, I shouldn't have released broken binaries in the first place. I'll probably have to release a patch version soon so that other package managers can catch up.
