### ISSUE TITLE
Error runtime.asmstdcall()

### ISSUE THREAD

**Issue by goxselenium** [junegunn/fzf#3601]
- [ ] I have read through the manual page (`man fzf`)
- [ x] I have the latest version of fzf
- [ ] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [ ] Mac OS X
    - [x] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [ ] fish

## Problem / Steps to reproduce
I upgraded to .46 and i have this error

when sending any command, example "fzf --version" or any other command

Exception 0xc0000005 0x8 0x0 0x0
PC=0x0

runtime.asmstdcall()
        /Users/jg/.asdf/installs/golang/1.21.6/go/src/runtime/sys_windows_amd64.s:65 +0x75 fp=0x22fca0 sp=0x22fc80 pc=0x468015
rax     0x0
rbx     0x7eb580
rcx     0x83e080
rdi     0x7fffffde000
rsi     0x22fea0
rbp     0x22fde0
rsp     0x22fc78
r8      0x0
r9      0x22fee0
r10     0x80feb8
r11     0x21
r12     0x22fec0
r13     0x1
r14     0x7eace0
r15     0x0
rip     0x0
rflags  0x10293
cs      0x33
fs      0x53
gs      0x2b

I run with cmder in windows 7 64 bits

Thanks!

**Comment by junegunn** [comment]
What method did you use to upgrade fzf? Can you test if the official binary in https://github.com/junegunn/fzf/releases/tag/0.46.0 works?

**Comment by junegunn** [comment]
Ah, it looks like it's because Go 1.21 dropped support for Windows 7.

* https://tip.golang.org/doc/go1.20#windows

And I built 0.46.0 with Go 1.21

* https://github.com/junegunn/fzf/commit/532274045e719b51979a063d696ce3b6ea6cf376

There is no absolute reason to use Go 1.21, so I can downgrade Go and build new binaries with it.

**Comment by junegunn** [comment]
Here are the binaries built with Go 1.20.

[fzf_0.46.0_checksums.txt](https://github.com/junegunn/fzf/files/14059952/fzf_0.46.0_checksums.txt)
[fzf-0.46.0-windows_amd64.zip](https://github.com/junegunn/fzf/files/14059953/fzf-0.46.0-windows_amd64.zip)
[fzf-0.46.0-windows_arm64.zip](https://github.com/junegunn/fzf/files/14059954/fzf-0.46.0-windows_arm64.zip)
[fzf-0.46.0-windows_armv5.zip](https://github.com/junegunn/fzf/files/14059955/fzf-0.46.0-windows_armv5.zip)
[fzf-0.46.0-windows_armv6.zip](https://github.com/junegunn/fzf/files/14059956/fzf-0.46.0-windows_armv6.zip)
[fzf-0.46.0-windows_armv7.zip](https://github.com/junegunn/fzf/files/14059957/fzf-0.46.0-windows_armv7.zip)
