### ISSUE TITLE
ALT-C doesn't respect .ignore

### ISSUE THREAD

**Issue by thebl1985** [junegunn/fzf#3602]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

## Problem / Steps to reproduce

CTRL-T, CTRL-R etc. all work as expected - they respect the .gitignore.

When I use ALT-C it still searches things in the .gitignore.

I have set fd as the default find command.

I tried both .gitignore and .ignore files.

Here is my config in .zshrc

```
export FZF_DEFAULT_COMMAND='fd --type f --strip-cwd-prefix'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
export FZF_ALT_C_OPTS="--preview 'tree -C {}'"
```

**Comment by LangLangBart** [comment]
The used widget can be found at the following location:

https://github.com/junegunn/fzf/blob/a34e8dcdc99d1509667f74a5e24a41ace172757e/shell/key-bindings.zsh#L74-L95

It utilizes the `FZF_ALT_C_COMMAND` environment variable for the command and defaults to the command you see in line 76, if it is not assigned. Could you try assigning it and then try again?


```bash
# Example assignment
export FZF_ALT_C_COMMAND="$FZF_DEFAULT_COMMAND --type directory"
```

**Comment by thebl1985** [comment]
Fixed, thanks.

**Comment by LangLangBart** [comment]
> Fixed, thanks.

That's great! I thought I'd share another handy tip that you might find useful.

In one of the most recent versions[^1] of `fzf`, the feature to toggle between two states using the `transform` action was introduced.

The configuration below allows the optional display of hidden directories by pressing <kbd>⌃ Control</kbd> + <kbd>T</kbd>.
```bash
export FZF_ALT_C_COMMAND="fd --color=always --type directory"
export FZF_ALT_C_OPTS='
--ansi
--header "CTRL-T: Toggle hidden directories"
--bind "ctrl-t:transform:[[ ! $FZF_PROMPT =~ Unrestricted ]] &&
	echo \"change-prompt(Unrestricted > )+reload($FZF_ALT_C_COMMAND --unrestricted)\" ||
	echo \"change-prompt(> )+reload($FZF_ALT_C_COMMAND)\""
--preview "tree -C {}"'
```
The functionality of this setup is explained here - [ADVANCED.md - Toggling with a single key binding](https://github.com/junegunn/fzf/blob/master/ADVANCED.md#toggling-with-a-single-key-binding)

[^1]: [CHANGELOG.md 0.45.0](https://github.com/junegunn/fzf/blob/master/CHANGELOG.md#0450)
