### ISSUE TITLE
--reverse and --preview not work

### ISSUE THREAD

**Issue by ZreXoc** [junegunn/fzf#3603]
- [-] I have read through the manual page (`man fzf`)
- [-] I have the latest version of fzf
- [-] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

## Problem / Steps to reproduce

`fzf`: 
![image](https://github.com/junegunn/fzf/assets/61901461/9fd2a54f-da4f-46c1-b64f-2aac6e09729b)

`fzf --preview='head -$LINES {}'`
![image](https://github.com/junegunn/fzf/assets/61901461/e6936b92-082a-48bf-acff-71ccbe7200ba)

`fzf --reverse`
![image](https://github.com/junegunn/fzf/assets/61901461/5164a454-a544-4937-adbd-1b8878360bbd)

no difference between them

**Comment by LangLangBart** [comment]
Have you assigned the environment variable `FZF_DEFAULT_OPTS` [^1]?
```bash
printenv FZF_DEFAULT_OPTS
# --ansi --reverse --preview-window 'hidden'
```

Do you notice a difference when running:
```bash
FZF_DEFAULT_OPTS="" fzf --preview='head -$LINES {}'
```

[^1]: [junegunn/fzf: README - Environment Variables](https://github.com/junegunn/fzf?tab=readme-ov-file#environment-variables)

**Comment by junegunn** [comment]
What's the output of `type fzf`?

**Comment by ZreXoc** [comment]
> What's the output of `type fzf`?
```
$ type fzf
fzf is /usr/bin/fzf
```

**Comment by ZreXoc** [comment]
> All the tests are passing, so it's clear that there is no issue regarding the options.
> 
> > $ type fzf
> > fzf is /usr/bin/fzf
> 
> Make sure that the file is a valid fzf binary. Not some shell script that calls fzf without properly passing the arguments.

you're right. It's the problem with https://github.com/unixorn/fzf-zsh-plugin. It automatically installs the fzf and add it to $PATH, which causes the problem
