### ISSUE TITLE
fzf, CTRL+R view whole command 

### ISSUE THREAD

**Issue by fekir** [junegunn/fzf#3606]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

## Problem / Steps to reproduce

I'm currently using `fzf` with `zsh`, and bound it to CTRL+R, so far everything works nicely.

The main issue I have, is that I have some long commands in my history (usually a chain of commands), one line is not long enough to display them.

Without `fzf`, I normally just iterate over those long command until I find the one I'm searching for (type Ctrl+r the first time, then the begin of the long command, then multiple times ctrl+r until I find the right one), since the whole command is displayed, I can read it until the end.

But when using `fzf`, only the beginning of the command is available.

Is there a way to overcome this limitation?

I think the best possible feature would be to be able to use CTRL+R with fzf, and when searching a long command, use another keyboard shortcut to change the behavior, like

 * using the builtin ctrl+r functionality
 * fzf showing long results on multiple line
 * something else

**Comment by LangLangBart** [comment]
> But when using `fzf`, only the beginning of the command is available.
> 
> Is there a way to overcome this limitation?

Have you considered displaying the command in the preview?

```bash
FZF_CTRL_R_OPTS="--height 50% --preview 'echo {2..} | bat --color=always -pl sh' --preview-window 'wrap,up,5'"
```

<img src="https://github.com/junegunn/fzf/assets/92653266/49e6c4e6-9e9a-4bbf-bb4f-92c4615ae2c7" width="600">


---

> fzf showing long results on multiple line

- related issue(s)
  - #2216
  - #2230
  - likely more …

**Comment by fekir** [comment]
Thank you; the related issues are about entries containing newline, while mine is one so long that  the whole line is not long enough, this is why I've overlooked them

Currently one search looks like

![fzf](https://github.com/junegunn/fzf/assets/11912465/f8e7bdf2-3969-4d4c-8867-4ef4e6340dd8)

Thus it is much better, but for very long commands still not ideal.

Without using tmux popoup

![fzf 2](https://github.com/junegunn/fzf/assets/11912465/ed26c5bc-d773-44d6-b5b6-3d0c87973e96)

I find using ctrl+r bound to fzf in general more practical, and the proposed `FZF_CTRL_R_OPTS` help in some cases, yet I think that being able to fall back to the "builtin search" would be a nice feature.
I do not always search for long commands, thus having a --height hardcoded to 50% or even bigger value does not make sense.

I've currently have two workarounds.
The first is to leave my config as is, and define an alias that calls fzf with those parameters (and a greater height) on the history, when I need to search for a long command.

The second one is to leaver ctrl+r mapped to the search builtin, and define an alias for using fzf when not searching for long commands.

**Comment by junegunn** [comment]
@LangLangBart Highlighting the item with `bat` is such a nice idea.

Here's my version. The preview window is hidden by default.

```sh
export FZF_CTRL_R_OPTS="
  --preview 'echo {2..} | bat --color=always -pl sh'
  --preview-window up:3:hidden:wrap
  --bind 'ctrl-/:toggle-preview'
  --bind 'ctrl-t:track+clear-query'
  --bind 'ctrl-y:execute-silent(echo -n {2..} | pbcopy)+abort'
  --color header:italic
  --header 'Press CTRL-Y to copy command into clipboard'"
```

If 3 lines are not enough, you can make the binding incrementally enlarge the window or set up a binding that opens the command in an editor.

```sh
export FZF_CTRL_R_OPTS="
  --preview 'echo {2..} | bat --color=always -pl sh'
  --preview-window up:hidden:wrap
  --bind 'ctrl-/:change-preview-window(30%|60%|90%|)'
  --bind 'ctrl-v:execute(echo {2..} | view - > /dev/tty)'
  --bind 'ctrl-t:track+clear-query'
  --bind 'ctrl-y:execute-silent(echo -n {2..} | pbcopy)+abort'
  --color header:italic
  --header 'Press CTRL-Y to copy command into clipboard'"
```

---

> I think the best possible feature would be to be able to use CTRL+R with fzf, and when searching a long command, use another keyboard shortcut to change the behavior

Yeah, you can set up additional bindings in your shell configuration file if you think that's the best way.

**Comment by junegunn** [comment]
https://junegunn.github.io/fzf/releases/0.54.0/

You can now press CTRL-/ or ALT-/ to toggle line wrapping.

**Comment by fekir** [comment]
Thank you; is it possible to define an alternative keybinding? The `/` is not very practical on some keyboards.

**Comment by junegunn** [comment]
Yes, you can bind `toggle-wrap` to any key of your preference.
