### ISSUE TITLE
`fzf-tmux -p` outside `tmux` does not show a popup window

### ISSUE THREAD

**Issue by spring-haru** [junegunn/fzf#3607]
- [x ] I have read through the manual page (`man fzf`)
- [x ] I have the latest version of fzf
- [x ] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [x ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x ] zsh
    - [ ] fish

## Problem / Steps to reproduce
* install `fzf` using homebrew
* execute `fzf-tmux -p` NOT inside `tmux` using Kitty or iTerm2
* The result is as if `fzf` is executed

(note)
* executing `fzf-tmux -p` INSIDE `tmux` DOES show a popup window.
* executing `fzf` with `export FZF_TMUX=1` has the same problem, i.e. no popup window.
* reinstalling `fzf` and `tmux` did not help

fzf 0.46.0 (brew)
tmux 3.3a

The result of excuting `bash -x fzf-tmux -p` outside `tmux` is (after cancelling the fzf window)
```
++ command -v fzf
+ fzf=/opt/homebrew/bin/fzf
+ [[ -x /opt/homebrew/bin/fzf ]]
+ args=()
+ opt=
+ skip=
+ swap=
+ close=
+ term=
+ [[ -n '' ]]
++ tput lines
+ lines=39
+ [[ -n '' ]]
++ tput cols
+ columns=120
+ [[ 1 -gt 0 ]]
+ arg=-p
+ shift
+ [[ -z '' ]]
+ case "$arg" in
+ [[ -p =~ ^-[pwhxy] ]]
+ [[ '' =~ -E ]]
+ opt=-E
+ [[ 2 -gt 2 ]]
+ [[ '' =~ ^[0-9%,]+$ ]]
+ [[ '' =~ ^[A-Z]$ ]]
+ continue
+ [[ 0 -gt 0 ]]
+ [[ -z '' ]]
+ /opt/homebrew/bin/fzf
+ exit 130
```

**Comment by junegunn** [comment]
This is the expected behavior. There is no way to open a popup window outside of tmux, so fzf-tmux falls back to normal fzf.
