### ISSUE TITLE
Latest FZF fails due to interaction with Oh-my-zsh

### ISSUE THREAD

**Issue by purplefishies** [junegunn/fzf#3616]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [ ] Mac OS X
    - [x] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

## Problem / Steps to reproduce

1. Cygwin system with zsh installed **but not fzf**
2. Install fzf from https://github.com/junegunn/fzf   (  to ~/.fzf  per the instructions ) 
3. Run standard fzf install ( installs both Bash and Zsh bindings to ~/.bashrc and ~/.zshrc )
4. source ~/.zshrc
5. Type ctrl-r to start searching # triggers FZF
Arrow keys select works
6. Install oh-my-zsh 
7. source $ZSH/oh-my-zsh.sh
8. Type ctrl-r to start searching
9.  Up and Down arrow keys don't work however 
     ControlP and ControlN allow you to move around .

Notes: 
1. Bash arrow keys work perfectly for history search
2. I can run  
    `find . -type f -maxdepth 1 | fzf`    # and arrow keys work 
3. Just the history search part of zsh seem to ignore the arrow keys.

**Comment by junegunn** [comment]
Is it an issue of fzf or oh-my-zsh? I don't think we've changed any code that would cause the described problem recently.
