### ISSUE TITLE
How to enable wrap in normal window not preview window?

### ISSUE THREAD

**Issue by bitcoinmeetups** [junegunn/fzf#3619]
- [ x] I have read through the manual page (`man fzf`)
- [ x] I have the latest version of fzf
- [ x] I have searched through the existing issues

## Info

- OS
    - [x ] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ x] bash
    - [ ] zsh
    - [ ] fish

## Problem / Steps to reproduce

Hello,

I'm Mr. Bacgi, a very friendly person.

How do I enable word wrap in the normal window? This is not the preview window, I think, with your terminology.

I just have a simple txt file, catting it and piping to fzf. But then all the long ilnes end with ... which is not ideal for my purposes because i need to see the end of the line.

--wrap doesn't work
--preview-window wrap doesn't work

Any advice?

**Comment by LangLangBart** [comment]
Try the `--keep-right`[^1] flag.

```bash
man fzf
# …
#    --keep-right
#           Keep  the  right  end  of  the  line visible when it's too long.
#           Effective only when the query string is empty.
```

[^1]: [junegunn/fzf@373c6d8](https://github.com/junegunn/fzf/commit/373c6d8d55066251dc7af58598de6af4ff4570cf)

**Comment by junegunn** [comment]
Wrapping in the main window is not supported.

>  i need to see the end of the line.

As @LangLangBart mentioned you can try `--keep-right` in that case.
