### ISSUE TITLE
Can't use `:FZF --expect=!` from neovim on windows

### ISSUE THREAD

**Issue by adigitoleo** [junegunn/fzf#3620]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [ ] Mac OS X
    - [x] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [ ] fish
    - [ ] pwsh.exe (PowerShell 7.4.1)

## Problem / Steps to reproduce

- Install fzf on Windows 11 Home 23H2 using `winget install --id junegunn.fzf`
- Launch PowerShell 7.4.1 (current version available on winget)
- Launch neovim 0.9.5 (also on winget) with `nvim -u NORC`
- Run `:FZF --expect=!`

On Linux, this works as expected (when `!` is pressed, `:FZF` exits and opens the selected entry). On windows, using the above setup, fzf exits with an error:

```
key names required
```

This must come from `fzf#run`, the low-level interface used for the `:FZF` command.

**Comment by junegunn** [comment]
Seems like an escaping issue. Does `fzf --expect=!` work on PowerShell?

**Comment by adigitoleo** [comment]
Yes, it works in PowerShell, but not inside neovim.

**Comment by junegunn** [comment]
Can you check if `:call fzf#run({'options': '--expect=!'})` works?

**Comment by adigitoleo** [comment]
No, that doesn't work. This was my original use case since I have a wrapper around `fzf#run` in my vimrc. The command fails and briefly displays "key names required" as the error message.

**Comment by junegunn** [comment]
I don't have a Windows PC to test it now. Does https://github.com/junegunn/fzf/pull/3189 help in your case?

**Comment by adigitoleo** [comment]
Unfortunately that patch does not fix the issue. Same error.

I tried a few variants with different kinds of escaping e.g. `--expect=\!` and the like but no luck. Apparently `!` is a boolean NOT operator in pwsh, but I couldn't find out exactly why it isn't getting escaped properly. To be more specific about the use case, I have this as an expected key so that (in linux) pressing `!` selects the current match and appends `!` allowing me to conveniently run vim shebang commands like `:make!`. It's only a minor inconvenience that this doesn't work, but I thought I should report it anyway.

**Comment by junegunn** [comment]
https://github.com/junegunn/fzf/commit/835d2fb98cedbb6384dfbeb41e4ba48c3c0a8081 should fix the problem. Let me know if it doesn't work for you.

**Comment by adigitoleo** [comment]
Thanks, this is indeed fixed for me on fzf 0.5.1 (PowerShell 7.4.2).
