### ISSUE TITLE
fzf-tmux not installed by conda install

### ISSUE THREAD

**Issue by Minyus** [junegunn/fzf#3627]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

## Problem / Steps to reproduce

Running `conda install -c conda-forge fzf` can install only fzf and fzf-tmux is missing in the python bin directory in CentOS 7.

Conda is used as sudo is not available.

**Comment by junegunn** [comment]
Thanks, you might want to report the issue to https://github.com/conda-forge/fzf-feedstock instead. It wouldn't be too hard to change the recipe.

**Comment by Minyus** [comment]
Ok, I reported the issue at https://github.com/conda-forge/fzf-feedstock/issues/52 . 
Thanks for an awesome tool!

**Comment by junegunn** [comment]
FYI, fzf 0.53.0 has native `--tmux` option that can replace fzf-tmux.

https://github.com/junegunn/fzf/blob/master/ADVANCED.md#--tmux
