### ISSUE TITLE
[feature request] add distinction between multi and single mode for FZF_DEFAULT_* vars

### ISSUE THREAD

**Issue by paxsali** [junegunn/fzf#3634]
- [X] I have read through the manual page (`man fzf`)
- [X] I have the latest version of fzf
- [X] I have searched through the existing issues

## Info

- OS
    - [X] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [X] bash
    - [ ] zsh
    - [ ] fish

## Problem / Steps to reproduce

No problem. Just a feature request.

---

Hi all,

currently there is only `FZF_DEFAULT_COMMAND` and `FZF_DEFAULT_OPTS` and both are the only and primary variables that control `fzf` operation.
However, `fzf` has two fundamentally different modes of operation:

- single selection mode (the default)
- multi-selection mode (via `--multi`)

In order to better control the behavior of `fzf`, consider adding two new variables that distinct the different modes of operation.

- `FZF_DEFAULT_COMMAND_MULTI`:  
   if `fzf` is invoked with `--multi` option (and **only** if), and stdin is not open, use this command for initial input. if this variable is not set, but `FZF_DEFAULT_COMMAND` is, use it as the command for initial input. (meaning that `FZF_DEFAULT_COMMAND_MULTI` takes precedence over `FZF_DEFAULT_COMMAND` in multi-selection mode, if both variables are set.)
- `FZF_DEFAULT_OPTS_MULTI`:  
   if `fzf` is invoked with `--multi` option (and **only** if), then automatically add those options per default. if this variable is not set, but `FZF_DEFAULT_OPTS` is, use it for the default options. (meaning that `FZF_DEFAULT_OPTS_MULTI` takes precedence over `FZF_DEFAULT_OPTS` in multi-selection mode, if both variables are set.)

Please discuss.

Thank you.

**Comment by junegunn** [comment]
fzf is a general-purpose filter program that can work with any type of list, and a set of options that works well with a specific type of list (e.g. file paths) is not guaranteed to work well with other types of list (e.g. command history, git branches, etc.). So it's better to keep FZF_DEFAULT_OPTS simple and only put options that affect the visual elements.

> However, `fzf` has two fundamentally different modes of operation:

I don't think the situation is that simple. The "mode" is defined by the type of the input and the way you deal with the output.

```sh
ps -ef | fzf | awk '{print $2}' | xargs kill
ls | fzf --multi --bind 'enter:become:vim {+}'
git branch | fzf | cut -c3-
```

> consider adding two new variables that distinct the different modes of operation

Also, some users may want different sets of options depending on the type of `--layout`. Some users may want different sets of `--color` options depending on `--color=light` or `--color=dark`. There can be so many wildly different requirements and addressing them using a fixed set of environment variables is not scalable.

If you want the dynamic behavior, you should instead write a wrapper script or function like so.

```sh
fzf() {
  if [[ "$*" =~ --multi ]]; then
    FZF_DEFAULT_OPTS=xxx FZF_DEFAULT_COMMAND=xxx command fzf "$@"
  else
    ..
  fi
}
```

**Comment by paxsali** [comment]
Hi,

I think your example function didn't really capture the scope of my request.

What I was talking about is essentially the equivalent of the following function (,but instead I counted on it being "natively" implemented in the source code):

```bash
function fzf-multi {
    local fzf_default_command
    local fzf_default_opts
    if [[ -v FZF_DEFAULT_COMMAND_MULTI ]]; then
        fzf_default_command="${FZF_DEFAULT_COMMAND_MULTI}"
    else
        if [[ -v FZF_DEFAULT_COMMAND ]]; then
            fzf_default_command="${FZF_DEFAULT_COMMAND}"
        fi
    fi
    if [[ -v FZF_DEFAULT_OPTS_MULTI ]]; then
        fzf_default_opts="${FZF_DEFAULT_OPTS_MULTI}"
    else
        if [[ -v FZF_DEFAULT_OPTS ]]; then
            fzf_default_opts="${FZF_DEFAULT_OPTS}"
        fi
    fi
    FZF_DEFAULT_COMMAND="${fzf_default_command}" \
    FZF_DEFAULT_OPTS="${fzf_default_opts}" \
    command fzf --multi "$@"
}

# example
FZF_DEFAULT_OPTS_MULTI='--height=99% --reverse' \
FZF_DEFAULT_COMMAND_MULTI='man -k . | sort -u' \
fzf-multi
```

However, this workaround is still "feasible enough" for my purposes, so I guess that's fine.

Thank you.
