### ISSUE TITLE
key-bindings.zsh scripts are hanging when used with fzf-tmux and tmux 3.4

### ISSUE THREAD

**Issue by alanoliveira** [junegunn/fzf#3635]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [x] zsh
    - [ ] fish

## Problem / Steps to reproduce

It actually a bug on tmux, but it seems there is some issue on fzf-tmux script.

The easiest way to reproduce is running the script below in a tmux 3.4 session
```sh
#!/bin/bash
$(echo 1 | fzf-tmux -u 40%)
```
It hangs instead return any result.

### Details

Tmux 3.4 is returning a 'size is missing' error when we run `tmux split-window -p 30%`  [due to this bug](https://github.com/tmux/tmux/blob/9ae69c3795ab5ef6b4d760f6398cd9281151f632/cmd-split-window.c#L97-L98)

The error makes fzf-tmux execute this fallback https://github.com/junegunn/fzf/blob/425deadca944de5a92093e881a1410dd2df1571a/bin/fzf-tmux#L239

I didn't get why, but inside a subshell it hangs instead of return the fallback result.

**Comment by alanoliveira** [comment]
About the tmux issue, a workaround I am using for now is changing https://github.com/junegunn/fzf/blob/425deadca944de5a92093e881a1410dd2df1571a/bin/fzf-tmux#L97-L101 to
```diff
         if [[ -n "$swap" ]]; then
-          opt="$opt -p $(( 100 - size ))"
+          opt="$opt -l $(( 100 - size ))%"
         else
-          opt="$opt -p $size"
+          opt="$opt -l $size%"
         fi
```

**Comment by junegunn** [comment]
Thanks for the report. I've just upgraded tmux and I can reproduce the problem.

Related: https://github.com/tmux/tmux/pull/3840

---

> About the tmux issue, a workaround I am using for now is changing

Does it work on older versions of tmux as well? If so, we should just change it. If not, hmm.

**Comment by alanoliveira** [comment]
@junegunn I tested on tmux 3.2a (from Jun 10, 2021) it worked fine.
As the fzf-tmux requires 3.2 or above I believe it is safe to change

**Comment by junegunn** [comment]
Applied your patch. Thanks!

**Comment by junegunn** [comment]
Please test if https://github.com/junegunn/fzf/commit/230cc6acc35681b9142ddb397d1fccf9cf2c4511 fixes the problem on old tmux.
