### ISSUE TITLE
Supports quick selection of target item like alfred.

### ISSUE THREAD

**Issue by QianChenglong** [junegunn/fzf#3637]
Supports quick selection of target item like alfred.
![image](https://github.com/junegunn/fzf/assets/1881126/f41c07f4-037c-4952-999c-ddd531476f20)
<img width="521" alt="image" src="https://github.com/junegunn/fzf/assets/1881126/8f9a1d39-cde6-4bfd-af5c-26bd7d2f07ea">

**Comment by LangLangBart** [comment]
There is a lesser-known feature in `fzf` named `jump`/`jump-accept`, which closely resembles what is
depicted in your screenshots.

To use it, type the command below and press either <kbd>;</kbd> or <kbd>:</kbd>, followed by the
number next to the item you wish to select.

```bash
# '--jump-labels'  is optional
fzf --jump-labels '123456789' --bind ';:jump' --bind '::jump-accept'
```

Here are some GIFs in a related discussion[^1].

---

>[!NOTE]
> The maintainer's opinion regarding `jump` can be found in a related issue.[^2]


[^1]: [Discussion on keeping jump characters visible · Discussion #3281](https://github.com/junegunn/fzf/discussions/3281)
[^2]: [Ctrl-c to exit jump and fzf? · Issue #3412](https://github.com/junegunn/fzf/issues/3412#issuecomment-1901740347)

**Comment by QianChenglong** [comment]
> There is a lesser-known feature in `fzf` named `jump`/`jump-accept`, which closely resembles what is depicted in your screenshots.
> 
> To use it, type the command below and press either ; or :, followed by the number next to the item you wish to select.
> 
> ```shell
> # '--jump-labels'  is optional
> fzf --jump-labels '123456789' --bind ';:jump' --bind '::jump-accept'
> ```
> 
> Here are some GIFs in a related discussion[1](#user-content-fn-1-959607cd1b29db94b66e053eb37d3dab).
> 
> Note
> 
> The maintainer's opinion regarding `jump` can be found in a related issue.[2](#user-content-fn-2-959607cd1b29db94b66e053eb37d3dab)
> 
> ## Footnotes
> 1. [Discussion on keeping jump characters visible · Discussion #3281](https://github.com/junegunn/fzf/discussions/3281) [↩](#user-content-fnref-1-959607cd1b29db94b66e053eb37d3dab)
> 2. [Ctrl-c to exit jump and fzf? · Issue #3412](https://github.com/junegunn/fzf/issues/3412#issuecomment-1901740347) [↩](#user-content-fnref-2-959607cd1b29db94b66e053eb37d3dab)

Thank you very much for your answer. It is very close to the desired function. Can fzf execute the action jump-accept by default?

**Comment by QianChenglong** [comment]
> There is a lesser-known feature in `fzf` named `jump`/`jump-accept`, which closely resembles what is depicted in your screenshots.
> 
> To use it, type the command below and press either ; or :, followed by the number next to the item you wish to select.
> 
> ```shell
> # '--jump-labels'  is optional
> fzf --jump-labels '123456789' --bind ';:jump' --bind '::jump-accept'
> ```
> 
> Here are some GIFs in a related discussion[1](#user-content-fn-1-959607cd1b29db94b66e053eb37d3dab).
> 
> Note
> 
> The maintainer's opinion regarding `jump` can be found in a related issue.[2](#user-content-fn-2-959607cd1b29db94b66e053eb37d3dab)
> 
> ## Footnotes
> 1. [Discussion on keeping jump characters visible · Discussion #3281](https://github.com/junegunn/fzf/discussions/3281) [↩](#user-content-fnref-1-959607cd1b29db94b66e053eb37d3dab)
> 2. [Ctrl-c to exit jump and fzf? · Issue #3412](https://github.com/junegunn/fzf/issues/3412#issuecomment-1901740347) [↩](#user-content-fnref-2-959607cd1b29db94b66e053eb37d3dab)

Thank you very much for your answer. It is very close to the function I want, but the cursor movement and marking cannot be displayed at the same time, which is a bit inconvenient to use.

**Comment by junegunn** [comment]
Standard terminals don't support `CMD-[0-9]` or `CTRL-[0-9]` key chords, but `ALT-[0-9]` chords are available. The closest you can do is something like this.

```
ls | awk '{ if (NR <= 5) { print "A-" NR " " $0 } else { print "    " $0 } }' |
  fzf --bind 'alt-1:pos(1),alt-2:pos(2),alt-3:pos(3),alt-4:pos(4),alt-5:pos(5)' | cut -c5-
```

[As per my previous comment](https://github.com/junegunn/fzf/issues/3412#issuecomment-1901740347), I'm not looking to add a different navigation mode to fzf or to extend the jump mode.
