### ISSUE TITLE
builtin cd cluttering HISTFILE

### ISSUE THREAD

**Issue by avidseeker** [junegunn/fzf#3641]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

## Problem / Steps to reproduce
This could be a limitation in shell, but I think there should be a way to prevent outputting "builtin cd" on every invocation of `fzf-cd-widget`. This is basically the same question as this (https://stackoverflow.com/questions/35852061/) but unlike commands like `fg`, the `builtin cd` wouldn't work in a subshell.

```sh
# ALT-C - cd into the selected directory
fzf-cd-widget() {
  local cmd="${FZF_ALT_C_COMMAND:-"command find -L . -mindepth 1 \\( -path '*/.*' -o -fstype 'sysfs' -o -fstype 'devfs' -o -fstype 'devtmpfs' -o -fstype 'proc' \\) -prune \
    -o -type d -print 2> /dev/null | cut -b3-"}"
  setopt localoptions pipefail no_aliases 2> /dev/null
  local dir="$(eval "$cmd" | FZF_DEFAULT_OPTS="--height ${FZF_TMUX_HEIGHT:-40%} --reverse --scheme=path --bind=ctrl-z:ignore ${FZF_DEFAULT_OPTS-} ${FZF_ALT_C_OPTS-}" $(__fzfcmd) +m)"
  if [[ -z "$dir" ]]; then
    zle redisplay
    return 0
  fi
  zle push-line # Clear buffer. Auto-restored on next prompt.
  BUFFER="builtin cd -- ${(q)dir}"
  zle accept-line
  local ret=$?
  unset dir # ensure this doesn't end up appearing in prompt expansion
  zle reset-prompt
  return $ret
}
zle     -N             fzf-cd-widget
bindkey -M emacs '\ec' fzf-cd-widget
bindkey -M vicmd '\ec' fzf-cd-widget
bindkey -M viins '\ec' fzf-cd-widget
```

**Comment by junegunn** [comment]
We can just run `cd` directly  in the function so that the command is not registered.

```diff
diff --git a/shell/key-bindings.zsh b/shell/key-bindings.zsh
index 7d0a14d..3eb4f41 100644
--- a/shell/key-bindings.zsh
+++ b/shell/key-bindings.zsh
@@ -81,11 +81,8 @@ fzf-cd-widget() {
     zle redisplay
     return 0
   fi
-  zle push-line # Clear buffer. Auto-restored on next prompt.
-  BUFFER="builtin cd -- ${(q)dir}"
-  zle accept-line
+  builtin cd -- ${(q)dir}
   local ret=$?
-  unset dir # ensure this doesn't end up appearing in prompt expansion
   zle reset-prompt
   return $ret
 }
```

This doesn't print the `builtin cd` command to the console so some users may find it confusing.

Another option would be to prefix the `builtin cd` command with a space and `setopt histignorespace`.

```diff
diff --git a/shell/key-bindings.zsh b/shell/key-bindings.zsh
index 7d0a14d..db587c4 100644
--- a/shell/key-bindings.zsh
+++ b/shell/key-bindings.zsh
@@ -82,7 +82,7 @@ fzf-cd-widget() {
     return 0
   fi
   zle push-line # Clear buffer. Auto-restored on next prompt.
-  BUFFER="builtin cd -- ${(q)dir}"
+  BUFFER=" builtin cd -- ${(q)dir}"
   zle accept-line
   local ret=$?
   unset dir # ensure this doesn't end up appearing in prompt expansion
```

**Comment by junegunn** [comment]
I can understand that you don't want `cd`s to be added to the command history. But at the same time, I really don't want to add a new option for this...

**Comment by junegunn** [comment]
> I don't see why this would be confusing.

Because the working directory changes without explicit visual cues.

**Comment by avidseeker** [comment]
Oh, I see. Yes I noticed my powerlevel10k doesn't update the path in PS1 unless I press enter or enter a command e.g: `pwd`. I thought this was just related to the plugin.

Then I think the confusion would be resolved if there is a way to reload PS1 when the function exits.

**Comment by LangLangBart** [comment]
> _I see. Yes I noticed my powerlevel10k doesn't update the path in PS1…_

Does it work if you add the following lines above `zle reset-prompt`?

```bash
if typeset -f _p9k_precmd > /dev/null; then
  _p9k_precmd &>/dev/null || true
fi
```

[internal/p10k.zsh/_p9k_precmd - romkatv/powerlevel10k](https://github.com/romkatv/powerlevel10k/blob/master/internal/p10k.zsh?plain=1#L7123)

**Comment by avidseeker** [comment]
No. Both solutions don't work for some reason. The prompt still updates after I press enter.

It's not a big deal for me, and at any case, it's more suitable to be reported to the prompt plugin not fzf.

Thank you for your help.

**Comment by LangLangBart** [comment]
> No. Both solutions don't work for some reason. The prompt still updates after I press enter.

Thank you for testing. A few iterations back in `key-bindings.zsh`, `fzf` utilized a
`fzf-redraw-prompt` function inside `zle`. This was removed in #2340.

https://github.com/junegunn/fzf/blob/37708ad9cd5d6f37cee63a1ee1a8308f60283c3d/shell/key-bindings.zsh#L71-L79

If you reintroduce the `fzf-redraw-prompt` into your file and substitute `zle reset-prompt` with
`zle fzf-redraw-prompt` in your setup, it should update the prompt. This approach is quite similar
to my previous one, but it uses zle to execute it.

```diff
--- a/shell/key-bindings.zsh
+++ b/shell/key-bindings.zsh
@@ -71,6 +71,15 @@ bindkey -M emacs '^T' fzf-file-widget
 bindkey -M vicmd '^T' fzf-file-widget
 bindkey -M viins '^T' fzf-file-widget
 
+# Ensure precmds are run after cd
+fzf-redraw-prompt() {
+  local precmd
+  for precmd in $precmd_functions; do
+    $precmd
+  done
+  zle reset-prompt
+}
+zle -N fzf-redraw-prompt
 
 fzf-cd-widget() {
 	local cmd="${FZF_ALT_C_COMMAND:-"command find -L . \
@@ -85,7 +94,7 @@ fzf-cd-widget() {
 	builtin cd -- ${(q)dir}
 	local ret=$?
 	unset dir # ensure this doesn't end up appearing in prompt expansion
-	zle reset-prompt
+	zle fzf-redraw-prompt
 	return $ret
 }
```

**Comment by wind0204** [comment]
> Another option would be to prefix the `builtin cd` command with a space and `setopt histignorespace`.
> 
> diff --git a/shell/key-bindings.zsh b/shell/key-bindings.zsh
> index 7d0a14d..db587c4 100644
> --- a/shell/key-bindings.zsh
> +++ b/shell/key-bindings.zsh
> @@ -82,7 +82,7 @@ fzf-cd-widget() {
>      return 0
>    fi
>    zle push-line # Clear buffer. Auto-restored on next prompt.
> -  BUFFER="builtin cd -- ${(q)dir}"
> +  BUFFER=" builtin cd -- ${(q)dir}"
>    zle accept-line
>    local ret=$?
>    unset dir # ensure this doesn't end up appearing in prompt expansion

I applied this to my fzf but it would be nice if I didn't have to maintain a separate git repository for this one feature. 😅

**Comment by wind0204** [comment]
> > * BUFFER=" builtin cd -- ${(q)dir}"> 
>
> I applied this to my fzf but it would be nice if I didn't have to maintain a separate git repository for this one feature. 😅

Another related idea: A feature that automatically inserts a blank space in front of the selected command sequence from `Ctrl-R` (histfile search)

**Comment by wind0204** [comment]
> > I applied this to my fzf but it would be nice if I didn't have to maintain a separate git repository for this one feature. 😅
> 
> Another related idea: A feature that automatically inserts a blank space in front of the selected command sequence from `Ctrl-R` (histfile search)

I've achieved it by adding one line in `key-bindings.zsh`:
```patch
@@ -146,6 +146,7 @@ fzf-history-widget() {
     else # selected is a custom query, not from history
       LBUFFER="$selected"
     fi
+    LBUFFER=" $LBUFFER"
   fi
   zle reset-prompt
   return $ret
```
