### ISSUE TITLE
The select box is not cleaned after making a selection.

### ISSUE THREAD

**Issue by 520521mayuan** [junegunn/fzf#3642]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

## Problem / Steps to reproduce
1. fzf --version
    0.44.1 (debian)
3. Ctrl-t select current dirctory files
4. type 'enter'
5. The select box always show even though the selection already completed.
![1](https://github.com/junegunn/fzf/assets/7332357/a139735e-1633-4ca7-8299-4edca18648c3)

  I'm curious if it's accurate in bash? if not, How to fix it? Thanks in advance!

**Comment by junegunn** [comment]
That doesn't look right. Have you tried it on different terminal emulators?

**Comment by 520521mayuan** [comment]
Thanks for your reply!

yeah, I'm using the alacritty now, and I tried the xterm and stterm, get the same result.
