### ISSUE TITLE
[zsh] `CTRL-R` inserting number and binding with FZF_DEFAULT_OPTIONS set 

### ISSUE THREAD

**Issue by aravance** [junegunn/fzf#3644]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

#### Case 1
1. `export FZF_DEFAULT_OPTS="--expect=ctrl-y"`
2. `<ctrl-r>`
3. _select an option with `<enter>`_

expected: 
```
$ echo $FZF_DEFAULT_OPTS
```
actual:
```
$ 
 5613  echo $FZF_DEFAULT_OPTS
```
#### Case 2
1. `export FZF_DEFAULT_OPTS="--expect=ctrl-y"`
2. `<ctrl-r>`
3. _select an option with `<ctrl-y>`_

expected: 
```
$ echo $FZF_DEFAULT_OPTS
```
actual:
```
$ ctrl-y
 5613  echo $FZF_DEFAULT_OPTS
```

**Comment by aravance** [comment]
Likely related: #3591

**Comment by junegunn** [comment]
You should never put `--expect` in your FZF_DEFAULT_OPTS. When `--expect` is given and you press enter or any of the specified keys, fzf will print the name of the key as the first line. This will break every script that doesn't expect an extra line.
