### ISSUE TITLE
Unexpected reordering when using --scheme=history

### ISSUE THREAD

**Issue by romkatv** [junegunn/fzf#3645]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

## Problem / Steps to reproduce

Run:

```sh
printf '%s\n' '/a/b' '/b' | fzf --scheme=history --query='/b'
```

Expected: no reordering of elements:

```text
  /b
> /a/b
  2/2 ─────────────────
> /b
```

Actual: the elements are reordered:

```text
  /a/b
> /b
  2/2 ─────────────────
> /b
```

Output of `fzf --version`: 0.46.1 (3c0a630).

Alternative reproduction steps:

1. Run: `HISTFILE= FZF_DEFAULT_OPTS= bash --norc`
2. Run: `source shell/key-bindings.bash`
3. Run: `/b`
4. Run: `/a/b`
5. Press: <kbd>Ctrl-R</kbd>

Expected: history entries are ordered by their number: 1 2 3.

Actual: history entries are out of order: 1 3 2.

![image](https://github.com/junegunn/fzf/assets/1282067/7461d4a2-25b9-40a9-b6dd-8b2018ca18e3)

**Comment by junegunn** [comment]
Thanks for the report. Should be fixed now.

fzf was giving a higher score on `/` of `/b` because it is on the boundary, but it was giving zero bonus point to the second `/` of `/a/b`, which caused fzf to prefer the first `/`, resulting in a lower score in total. But this was a bug. `/` should be given the bonus point for non-word characters.

**Comment by romkatv** [comment]
Thanks for the quick fix!

Do I understand correctly that `--scheme=history` is sufficient to disable reordering in all circumstances? If not, what is the right combination of commandline options to disable reordering?

**Comment by junegunn** [comment]
No, if you do not want fzf to sort the list at all, you should use `--no-sort` option.

**Comment by junegunn** [comment]
When you use the CTRL-R binding, you can press CTRL-R again to toggle sorting.

> If you want to see the commands in chronological order, press CTRL-R again which toggles sorting by relevance

**Comment by romkatv** [comment]
Thank you for the helpful answers.
