### ISSUE TITLE
Strange sorting

### ISSUE THREAD

**Issue by ggVGc** [junegunn/fzf#365]
Probably not a bug, but I find I find this behaviour strange and would like to have an explanation. Why are the results sorted like this for this input?
![image](https://cloud.githubusercontent.com/assets/207377/10250509/79e8d2b8-692b-11e5-994c-40a26a57a4cd.png)

**Comment by junegunn** [comment]
Both have the matched substring of the same length (`Player` and `player`), so they're tied. fzf then compares the whole lengths of the items, the first one is shorter so it comes first. If those lengths are again the same, the items are listed in FIFO manner. In SQL-like term, it's `order by len(substring) asc, len(item) asc, index asc`. You can change the rule by setting `--tiebreak` option. See the man page for the details.
