### ISSUE TITLE
Strange behavior for `CTRL+T` binds with `become(cmd {})`

### ISSUE THREAD

**Issue by PandaScience** [junegunn/fzf#3650]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux / Arch
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [x] zsh
    - [ ] fish

## Problem / Steps to reproduce

I'd like to configure the CTRL+T shortcut to open the selected file(s) in vim instead of just printing the filename(s) to the prompt buffer.

As I understand from the README, this should be possible with a bind like so
```
export FZF_CTRL_T_OPTS="--bind='enter:become(nvim {})'"
```

After putting this line in my shell config, hitting enter on a selection will just freeze the terminal. The behavior is identical for zsh and bash with plain configs containing only this very fzf setting and sourcing the completions and key bindings shipped with the Arch Linux fzf package.

I've experimented a bit with different commands but still have no clue why this is not working. For instance, with `become(less {})` it will just paste the file contents into the prompt buffer with whitespaces and some special characters  escaped. 
E.g. this file

```
hello:
#world

```
will become
```
hello: \#world '' 
```

With `become(echo cmd {})` it will print `cmd\ filename` instead.

However, when passing the same option directly to a CLI call via

```
fzf --bind 'enter:become(less {})'
```
everything works as expected. :exploding_head: 

As workaround I've defined this zsh widget:
```zsh
zsh_widget-fzf_ctrl_t() {
  BUFFER="fzf --bind 'enter:become(nvim {})'"
  zle accept-line
}
zle -N zsh_widget-fzf_ctrl_t
bindkey "^t" zsh_widget-fzf_ctrl_t
```

Not sure if I'm just being stupid and missing sth. obvious here or if this is really a bug... :thinking:

**Comment by LangLangBart** [comment]
> No, you can't do it that way.


Is it possible to use the `/dev/tty`[^1] workaround with `become` as one would with the `execute` action?

```bash
export FZF_CTRL_T_OPTS="--bind='enter:become:vim {} >/dev/tty'"
```

The loop does not run because nothing is assigned to `item` in the `__fsel` helper function.

https://github.com/junegunn/fzf/blob/1833670fb91dfa17047af320ce7f015e0d500ba6/shell/key-bindings.zsh#L43-L56

And, `LBUFFER` stays the same.

https://github.com/junegunn/fzf/blob/1833670fb91dfa17047af320ce7f015e0d500ba6/shell/key-bindings.zsh#L63-L68

[^1]: https://reddit.com/r/bash/comments/wm4kir/fzf_repl/ijxmzbl

**Comment by junegunn** [comment]
@LangLangBart Good point. I think that will work though it feels a bit hacky.

**Comment by PandaScience** [comment]
Just for the sake of completeness:

The zsh widget from above,
```zsh
widget() {
  BUFFER="fzf --bind 'enter:become(nvim {})'"
  zle accept-line
}
```
will leave an ugly entry in zsh's history. 

For a clean history, use for instance 
```zsh
setopt HIST_IGNORE_SPACE
widget() {
  # note the leading whitespace
  BUFFER=" fzf --bind 'enter:become(nvim {})'"
  zle accept-line
}
```
This will still show the fzf command in the prompt(-history) though.

For a completely 'silent' widget, use instead
```zsh
widget() {
  fzf --bind 'enter:become(nvim {})' <"${TTY}"
  zle reset-prompt
}
```
Note the stdin redirection. Its necessity is explained here: #2167
