### ISSUE TITLE
[Windows] Preview window adds double slashes for all interior folders except the last one

### ISSUE THREAD

**Issue by eblis** [junegunn/fzf#3651]
- [X] I have read through the manual page (`man fzf`)
- [X] I have the latest version of fzf
- [X] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [ ] Mac OS X
    - [X] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [ ] fish
    - [X] Windows Batch with [clink](https://github.com/chrisant996/clink) and [clink-fzf](https://github.com/chrisant996/clink-fzf) 

## Problem / Steps to reproduce
I'm seeing double slashes `\\` for all folders inside preview window. This is happening with both [eza](https://github.com/eza-community/eza) and [dirx](https://github.com/chrisant996/dirx) as preview commands.

# Dirx
`dirx` preview is `set FZF_ALT_C_OPTS=--preview-window "right:40%,border-left" --bind "ctrl-/:change-preview-window(right:70%|hidden|)" --preview "dirx -b -s --bare-relative --utf8 --level=3 --icons=always {2..}`
![image](https://github.com/junegunn/fzf/assets/540188/f77202a7-a6c2-4a96-8712-4b9d8c5ae935)

# Eza
`eza` preview is `set FZF_ALT_C_OPTS=--preview-window "right:40%,border-left" --bind "ctrl-/:change-preview-window(right:70%|hidden|)" --preview "eza --tree --level=3 --icons=always {2..}`
![image](https://github.com/junegunn/fzf/assets/540188/72b09c1f-cd3e-40f0-8cc3-a645fb490ea4)

I have originally raised https://github.com/chrisant996/clink-fzf/issues/14, but from the looks of it this is a problem in `fzf` itself, probably here https://github.com/junegunn/fzf/blob/1833670fb91dfa17047af320ce7f015e0d500ba6/src/terminal_windows.go#L32

The issue **does not reproduce** on Linux (tested with eza).

**Comment by junegunn** [comment]
Is it because you use cmd.exe with clink? (I'm not familiar with it) Is the problem reproducible without clink? And what do you suggest fzf should do?

**Comment by eblis** [comment]
The issue occurs even if I run just `fzf` itself with the following command `fzf --preview-window "right:40%,border-left" --bind "ctrl-/:change-preview-window(right:70%|hidden|)" --preview "eza --tree --level=3 --icons=always {2..}"` (before that I've configured `FZF_DEFAULT_COMMAND` with `set FZF_DEFAULT_COMMAND=dirx.exe /s /a:d-s --icons=always --utf8 --bare-relative` to get folders in the list of suggestions)

So the issue is reproducible with just `fzf` and `eza`.

FZF should display paths with a single `\` character, so in the examples above it should be `.git\logs\refs\remotes\origin\HEAD`

**Comment by DanSM-5** [comment]
I just tried this as I've been exploring the use of `eza`.

This happens when calling from powershell too, so clink may be unrelated.
```powershell
fd -H --no-ignore -td -d 4 |
  fzf --preview-window "right:40%,border-left" `
    --bind "ctrl-/:change-preview-window(right:70%|hidden|)" `
    --preview "eza --color=always --tree --level=3 --icons=always {}"
```
![image](https://github.com/junegunn/fzf/assets/49035812/39127cd1-7a44-4b22-b290-d6c00d73c522)

Though I seems to me that the parsing may be a `eza` thing. If I provide a list of files with forward slash `/`, `eza` will still change the last one to a single back slash `\`

```powershell
fd -H --no-ignore -td -d 4 --path-separator "/" |
  fzf --preview-window "right:40%,border-left" `
    --bind "ctrl-/:change-preview-window(right:70%|hidden|)" `
    --preview "eza --color=always --tree --level=3 --icons=always {}"
```
![image](https://github.com/junegunn/fzf/assets/49035812/e8e7896c-d2ef-4db7-8754-9b4e3bc0dc00)

If I just echo the path, it looks like `fzf` is escaping the backlashes fine
```powershell
fd -H --no-ignore -td -d 4 |
  fzf --preview-window "right:40%,border-left" `
    --bind "ctrl-/:change-preview-window(right:70%|hidden|)" `
    --preview "echo {}"
```
![image](https://github.com/junegunn/fzf/assets/49035812/8d826d78-2958-4439-a853-a4937939159c)

I don't have dirx but it may be doing something similar

**Comment by junegunn** [comment]
I think it has to do with our escaping mechanism, but unfortunately I don't have a good understanding of it as I'm not a Windows user.

* Related: https://github.com/junegunn/fzf/issues/2609#issuecomment-1008055449
* Also see https://github.com/junegunn/fzf/pull/2624

Using powershell to execute the command seems to help, as the entry is escaped differently, either by setting `SHELL` environment variable to `powershell` or by using not-yet released `--with-shell` option.

```sh
fd -H --no-ignore -td -d 4 | fzf --with-shell "powershell -NoProfile -Command" --preview ".\eza.exe --color=always --tree --level=3 --icons=always {}"
```

**Comment by junegunn** [comment]
8d74446 is an attempt to fix the issue and I think it works. Please build and test if it works for you and check if it breaks anything.

**Comment by junegunn** [comment]
Also 194a763c469e4fdbf31c0f71b1846add607477de
