### ISSUE TITLE
.gitignore pattern is not interpreted correctly

### ISSUE THREAD

**Issue by osa1** [junegunn/fzf#3652]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

## Problem / Steps to reproduce

The .gitignore pattern `**/foo` is not interpreted by fzf correctly. For example, in this repo https://github.com/zed-industries/zed, `.gitignore` has this line: `**/target`. However if I to `ctrl + t` and run the fzf from the master branch (1833670), the target directory is indexed.

Relevant git documentation says: (https://git-scm.com/docs/gitignore#_pattern_format) (emphasis mine)

>Two consecutive asterisks ("\*\*") in patterns matched against full pathname may have special meaning:
>
>   A leading "\*\*" followed by a slash means match in all directories. **For example, "\*\*/foo" matches file or directory "foo" anywhere, the same as pattern "foo"**. "\*\*/foo/bar" matches file or directory "bar" anywhere that is directly under directory "foo".
 
fzf does not interpret `**/foo` the same way as `foo`.

**Comment by junegunn** [comment]
fzf doesn't know anything about `.gitignore`. If you want CTRL-T binding to respect `.gitignore` files, you need to install an external program such as fd or rg that understands them and set `FZF_CTRL_T_COMMAND`.

See https://github.com/junegunn/fzf?tab=readme-ov-file#respecting-gitignore
