### ISSUE TITLE
fzf Removing Terminal Prompt When Using `CTRL+R`

### ISSUE THREAD

**Issue by Anvesh9652** [junegunn/fzf#3668]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

## Problem / Steps to reproduce

I have been using zsh-vi-mode for a long time, and I recently started using fzf. Whenever I use `CTRL + R` for command search in my history, and if I select and enter one of the suggested commands, fzf removes my terminal prompt. I tried turning off different settings, but nothing worked. However, when I commented out the sourcing of the zsh-vi-mode script, fzf worked fine. I noticed that the default terminal `CTRL + R` (bck-i-search:) is working fine with zsh-vi-mode enabled. Can someone help me figure out what is wrong with my config?

## .zshrc config
https://gist.github.com/Anvesh9652/ea36fb6185a9bf1f7e5457bc33d884e1

https://github.com/junegunn/fzf/assets/83718454/b6418e06-0661-4757-a4f8-1e28ab41ab57

**Comment by junegunn** [comment]
* Are you using the latest version of fzf and its scripts?
* Can you still reproduce the problem when you comment out p10k?

**Comment by Anvesh9652** [comment]
1. Yes
2. Yes

**Comment by LangLangBart** [comment]
> when I commented out the sourcing of the zsh-vi-mode script, fzf worked fine

The issue might be more appropriate for the `jeffreytse/zsh-vi-mode` plugin repo  where similar
issues[^1][^2] have already been filed.

[^1]: [Inserting completions erases prompt · Issue #237 · jeffreytse/zsh-vi-mode](https://github.com/jeffreytse/zsh-vi-mode/issues/237)

[^2]: [Prompt got eaten and move up a line on certain actions · Issue #124 · jeffreytse/zsh-vi-mode](https://github.com/jeffreytse/zsh-vi-mode/issues/124)

**Comment by Anvesh9652** [comment]
@LangLangBart Thank you for helping me out. I found a workaround from the comments of linked issues.

@junegunn Thank you for this wonderful tool. It's only been a few days, and I have been using fzf very extensively, and I am really loving it.
