### ISSUE TITLE
Feature request: Non-invasive version of the install script

### ISSUE THREAD

**Issue by jokogr** [junegunn/fzf#367]
Hello,

Great utility, many thanks for developing it! Is it possible to use the install script just for downloading new versions of fzf? I maintain my dotfiles on my own and I don't like fzf to do unattended modifications on them.

**Comment by junegunn** [comment]
Undocumented, but it's there: `./install --bin`

**Comment by junegunn** [comment]
I modified the title so it's easier for other users to find. Thanks.

**Comment by netei** [comment]
Great, didn't know that. Always had to undo the changes of the install script by hand before when updating a version
