### ISSUE TITLE
Executing shell command with toggle preview problem on Kitty terminal

### ISSUE THREAD

**Issue by mjekrami** [junegunn/fzf#3672]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x ] I have searched through the existing issues

- OS
    - [x] Linux

- Shell
    - [x] zsh

- Terminal
    - [x] kitty: 0.31.0 

fzf version: 0.46.1 (3c0a6304)

## Problem / Steps to reproduce
I have plenty of pdf files scatted on my hard drives. I'm trying to make a script that searches trough all of my PDFs and by using fzf i want the preview of the first page.
this is what i came up with (with the help of one of the issues in this repo)

`fd --glob '*.pdf' --type file /mnt/D/Down* | fzf --preview=' pdftoppm -singlefile {} -tiffcompression jpeg  2>/dev/null | kitten icat --transfer-mode=stream --clear --place=${FZF_PREVIEW_COLUMNS}x${FZF_PREVIEW_LINES}@20x1' --bind 'ctrl-x:toggle-preview' --ansi --delimiter / --with-nth -1`

and this is the result which is fine:

![image](https://github.com/junegunn/fzf/assets/82811963/1a74fedc-954e-4ba9-a696-b6ab75d7ed34)

how ever when i toggle preview to off the problem arises:
 
![image](https://github.com/junegunn/fzf/assets/82811963/2c9e37a3-8074-4461-9db9-24e6db6598a4)

**Comment by mjekrami** [comment]
found a solution
--bind 'ctrl-/:toggle-preview+execute(kitten icat --clear)

**Comment by junegunn** [comment]
Adding `--unicode-placeholder` to `kitten icat` fixes the issue. When you use the option and hide the preview window, the special unicode characters on the preview window that kitty uses to place the image are erased, so the image is cleared.

The option has an added benefit that you can display text after the image. `fzf --preview 'seq 5; icat ... {}; seq 5'`
