### ISSUE TITLE
SSH completion results in error

### ISSUE THREAD

**Issue by Gh0stExp10it** [junegunn/fzf#3674]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

## Problem / Steps to reproduce
When I try to force the auto completion for ssh (e.g. ```ssh vm-``` ```<TAB>```), I'm getting the following error:
```sh
bash: warning: programmable_completion: ssh: possible retry loop
```

If fzf is temporarily uninstalled, it works as expected.

**Comment by johnredberg** [comment]
Thanks @Gh0stExp10it . Found this by googling the warning text. 

I can confirm the same on
- macOS Sonoma 14.3.1
- bash version 5.2.26(1)-release (aarch64-apple-darwin23.2.0)
- Homebrew 4.2.12-19-gb1990ed
- fzf 0.47.0 (brew)

Additional info for the maintainers: This seems to be unrelated to any particular `ssh` setup. For example,
```
ssh kajsldjfalsjflaksjdflkajsldfkjasldfj<TAB>
```
results in the same warning. (Obviously, I don't have any host configs for that string.)

**Comment by junegunn** [comment]
Thanks, it seems to have been caused by #3667. Let me look into it.

@akinomyoga Any idea?

**Comment by junegunn** [comment]
```sh
diff --git a/shell/completion.bash b/shell/completion.bash
index dae8b21..fc5965a 100644
--- a/shell/completion.bash
+++ b/shell/completion.bash
@@ -382,7 +382,7 @@ _fzf_complete() {
     rest=("$@")
   fi
 
-  local cur selected trigger cmd post
+  local cur selected trigger post
   post="$(caller 0 | command awk '{print $2}')_post"
   type -t "$post" > /dev/null 2>&1 || post='command cat'
 
@@ -401,7 +401,7 @@ _fzf_complete() {
     printf '\e[5n'
     return 0
   else
-    _fzf_handle_dynamic_completion "$cmd" "${rest[@]}"
+    _fzf_handle_dynamic_completion "${COMP_WORDS[0]}" "${rest[@]}"
   fi
 }
 
```

**Comment by junegunn** [comment]
@akinomyoga No problem, I should have spotted that in the review process.

**Comment by Gh0stExp10it** [comment]
I've successfully tested the changes. Thank you very much! :)
