### ISSUE TITLE
Version 0.47.0 does no work on Windows

### ISSUE THREAD

**Issue by ppasieka** [junegunn/fzf#3676]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [ ] Mac OS X
    - [x] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [ ] fish
    - [x] Powershell

## Problem / Steps to reproduce
After updating to the fzf@0.47.0 the process is not working

I use scoop to manage tools:
fzf             0.47.0  main              2024-03-12 11:59:39

fzf --version                                                                                                                                                        
Could not create process with command '"C:\Users\XXXX\scoop\apps\fzf\current\fzf.exe"  --version'.

when downgrading to 0.46.1, fzf works again.

**Comment by ppasieka** [comment]
Microsoft Windows 10 Enterprise, Version 10.0.19045 Build 19045
And you can **close** this ticket as I'm pretty sure what is happening.

A few weeks ago, our IT department contacted me about fzf's suspicious behavior (clearing the history file). They then whitelisted the application. 
With the new version (0.47.0), the file is physically deleted when I try to run it for the first time, which leads to the error I posted. I have to contact IT again 😅. 

Sorry for the false alarm.

**Comment by junegunn** [comment]
I see, thanks for the confirmation.
