### ISSUE TITLE
cd to sub directory of directory with spaces does not work as slash gets removed

### ISSUE THREAD

**Issue by overtomanu** [junegunn/fzf#3677]
- [ ] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

## Problem / Steps to reproduce

![output](https://github.com/junegunn/fzf/assets/4481775/3d5d764f-ade6-4ed8-88fd-2c73968cc255)

**Comment by overtomanu** [comment]
I have following things in the bashrc file

```sh
source "$HOME/fzf-tab-completion-master/bash/fzf-bash-completion.sh"
bind -x '"\t": fzf_bash_completion'
export FZF_COMPLETION_AUTO_COMMON_PREFIX=true
[ -f ~/.fzf.bash ] && source ~/.fzf.bash
```

**Comment by junegunn** [comment]
I think you should report the issue to https://github.com/lincheney/fzf-tab-completion
