### ISSUE TITLE
[feature-request] Vim plugin should provide option to search through currently open buffers

### ISSUE THREAD

**Issue by natemara** [junegunn/fzf#368]
I really enjoy using FZF. It is blazingly fast, even faster than CtrlP paired with Ag. It would be nice if we could duplicate CtrlP's ability to list out the open buffers and search through them fuzzily. I am talking about CtrlP's `:CtrlPBuffer` command. It is very useful for working with large projects and having lots of files open at once.

**Comment by khalidchawtany** [comment]
I think there is already such a functionality. look at ```Buffers``` command [here](https://github.com/junegunn/fzf.vim), it is provided by **fzf.vim**.

**Comment by junegunn** [comment]
@khalidchawtany Thanks.

Yes, check out https://github.com/junegunn/fzf.vim

**Comment by natemara** [comment]
Wow, this provides significantly more functionality than the main project
docs are letting on. Thank you.
