### ISSUE TITLE
`execute-silent` slight delay on apple silicon

### ISSUE THREAD

**Issue by samsze0** [junegunn/fzf#3683]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf (homebrew. which is on 0.48.0. But looks like 0.48.1 doesn't address this issue)
- [x] I have searched through the existing issues

## Info

- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

## Problem / Steps to reproduce

Run `fzf --bind='start:execute-silent(pwd)+pos(0),change:execute-silent(pwd),focus:execute-silent(pwd)+execute-silent(pwd)'` in zsh shell and `execute-silent` has a slight delay

https://github.com/junegunn/fzf/assets/86842365/dd47a987-bf64-45bc-acc7-ae20436a7141

**Comment by samsze0** [comment]
Confirmed just this is still an issue for me if I clone and built the binary myself ;( I am guessing this is probably due to being on my company's laptop.

**Comment by junegunn** [comment]
`execute-silent` runs synchronously so it blocks the UI until the `$SHELL` process for the command finishes. Maybe you thought it was non-blocking because of its `-silent` suffix? It just means that you won't see the output of the command unlike `execute`, it doesn't mean the command runs in the background.

**Comment by samsze0** [comment]
I think the delay is abnormally long tho. I don't have this issue on my older macbook 🤔

**Comment by samsze0** [comment]
I will close this issue as I think this issue is solely caused by my shell
