### ISSUE TITLE
Issue with nested `fzf` usage in bash script causing script to halt

### ISSUE THREAD

**Issue by LangLangBart** [junegunn/fzf#3685]
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] macOS
- Shell
    - [x] bash (in the script)
    - [x] zsh (default shell)

## Problem / Steps to reproduce

I am encountering an issue when trying to use `fzf` within `fzf` in a bash script. The script stops
when I make a second selection from <kbd>⌃ Control</kbd> + <kbd>H</kbd>, and continues only when <kbd>⌃ Control</kbd> + <kbd>C</kbd> 
is pressed.

The idea I am pursuing is using the `--history` flag read from my past queries and make a selection,
this selection will then replace my current query. For simplicity, the script has been reduced to
the following:

```bash
#!/usr/bin/env bash
set -o errexit -o nounset -o pipefail

export FZF_DEFAULT_OPTS=""
export FZF_DEFAULT_COMMAND=""
SHELL=$(which bash)

curl_custom() {
	command curl --request POST "localhost:$FZF_PORT" --silent --data "$@"
}

query() {
	for i in {1..100}; do
		curl_custom "change-header:$i"
	done
}

view_history_commands() {
	command fzf --no-multi <<<$'A\nB' | while read -r item; do
		curl_custom "change-query:$item"
	done
}

export -f curl_custom query view_history_commands

: | command fzf \
	--bind "change:reload:query {q}" \
	--bind 'ctrl-h:execute:view_history_commands' \
	--listen
```

Here is the GIF of the script in action:
1. First, I press <kbd>⌃ Control</kbd> + <kbd>H</kbd> and select `A`.
2. While the `query` is still running, I press <kbd>⌃ Control</kbd> + <kbd>H</kbd> again and select `B`.
3. The script is blocked and only continues when I press <kbd>⌃ Control</kbd> + <kbd>C</kbd>.
<img src="https://github.com/junegunn/fzf/assets/92653266/51e25bb3-9491-4096-94df-d57c7f321386" width="600">

---

#### Alternatives
The idea worked when modifying the script using the `--expect` flag.

---

#### Related issue(s):
- #3291

**Comment by LangLangBart** [comment]
Adopting a `stop_loop` check appears to be effective. Would you recommend that?


```bash
#!/usr/bin/env bash
set -o errexit -o nounset -o pipefail

export FZF_DEFAULT_OPTS=""
export FZF_DEFAULT_COMMAND=""
SHELL=$(which bash)

export stop_loop="/tmp/stop_loop"
trap 'rm -rf $stop_loop' EXIT

curl_custom() {
	command curl --request POST "localhost:$FZF_PORT" --silent --data "$@"
}

query() {
	for i in {1..100}; do
		[[ -s $stop_loop ]] && break
		curl_custom "change-header:$i"
	done
}

view_history_commands() {
	echo "stop" >"$stop_loop"
	item=$(command fzf --no-multi <<<$'A\nB')
	curl_custom "change-query:$item"
	: >"$stop_loop"
}

export -f curl_custom query view_history_commands

: | command fzf \
	--bind "change:reload:query {q}" \
	--bind 'ctrl-h:execute:view_history_commands' \
	--listen
```

<img src="https://github.com/junegunn/fzf/assets/92653266/5ded7b67-e0a6-47dc-aa18-517ec4709138" width="600">

**Comment by LangLangBart** [comment]
> The reason that the curl command in view_history_commands doesn't finish is that fzf uses a bounded buffer for server requests.

Thank you, increasing the buffer size does work.

> Can you share what you were trying to implement?

The script is designed to search GitHub code and list the results. The header updates to reflect the
progress of file retrieval.

The hotkey <kbd>⌃ Control</kbd> + <kbd>H</kbd> allows viewing of past queries and select one.

Refer to the GIF below for further clarity.

<img src="https://github.com/junegunn/fzf/assets/92653266/edfe68c6-4d9e-47f2-ada8-c7c2f5929bd5" width="800">

The code is present here. For the time being, I have implemented the `stop_loop` workaround.


[interactive history by LangLangBart · Pull Request #2 · LangLangBart/gh-find-code · GitHub](https://github.com/LangLangBart/gh-find-code/pull/2)

**Comment by junegunn** [comment]
I'm thinking of increasing the buffer size to 1K. Do you think this will be enough? We can't make it absurdly large because that would waste memory.

**Comment by junegunn** [comment]
I'm also going to put a timeout on POST requests. So with the channel size 10,

```sh
$ fzf --listen --bind 'start:execute(for i in $(seq 1000); do curl -if localhost:$FZF_PORT -d up || break; done)+abort'
HTTP/1.1 200 OK

HTTP/1.1 200 OK

HTTP/1.1 200 OK

HTTP/1.1 200 OK

HTTP/1.1 200 OK

HTTP/1.1 200 OK

HTTP/1.1 200 OK

HTTP/1.1 200 OK

HTTP/1.1 200 OK

HTTP/1.1 200 OK

HTTP/1.1 503 Service Unavailable

curl: (22) The requested URL returned error: 503
```

**Comment by LangLangBart** [comment]
> Do you think this will be enough? 

Indeed, tests with 100 as the parameter (`serverInputChan` in `src/terminal.go`) were successful on
the script in the issue description. Therefore, 1k should be more than adequate.

> I'm also going to put a timeout on POST requests.

A timeout feature would indeed be a valuable addition.

**Comment by junegunn** [comment]
> Therefore, 1k should be more than adequate.

Alright, let's settle with 100 with 2-second timeout. 1K does seem a bit too much to be honest. We'll see if anyone hits the limit.
