### ISSUE TITLE
Bind completion to a bindkey (not **tab)

### ISSUE THREAD

**Issue by Hypn0sis** [junegunn/fzf#3700]
### Checklist

- [X] I have read through the manual page (`man fzf`)
- [X] I have searched through the existing issues

### Output of `fzf --version`

0.48.1 (d579e33)

### OS

- [X] Linux
- [ ] macOS
- [ ] Windows
- [ ] Etc.

### Shell

- [ ] bash
- [X] zsh
- [ ] fish

### Problem / Steps to reproduce

Hi, thanks for your great work. I've searched all around the web but I didn't find anything that fits.
I would like to know if there is an alternative way to trigger autocompletion that is not **tab. I want (supposing) to bind it to ^E for example.
Thanks again and bye.

**Comment by junegunn** [comment]
See https://github.com/junegunn/fzf/wiki/Configuring-fuzzy-completion#dedicated-completion-key
