### ISSUE TITLE
Image preview not working properly

### ISSUE THREAD

**Issue by dr3mro** [junegunn/fzf#3701]
### Checklist

- [X] I have read through the manual page (`man fzf`)
- [X] I have searched through the existing issues

### Output of `fzf --version`

0.42 (2023012)

### OS

- [ ] Linux
- [ ] macOS
- [ ] Windows
- [X] Etc.

### Shell

- [ ] bash
- [X] zsh
- [ ] fish

### Problem / Steps to reproduce

Hello

I use FreeBSD 14  with st-terminal with sixel support 

image preview works in LF and in the terminal 
when using FZF preview shell script (https://raw.githubusercontent.com/junegunn/fzf/master/bin/fzf-preview.sh) it shows images as escape characters 

![2024-03-28-163738_609x315_scrot](https://github.com/junegunn/fzf/assets/1246089/78a494a4-f42c-4e10-b6a0-f83666f2fdf8)
![2024-03-28-163746_954x521_scrot](https://github.com/junegunn/fzf/assets/1246089/9842dcd4-5625-44af-aba0-e7270f366a00)
![2024-03-28-163827_518x86_scrot](https://github.com/junegunn/fzf/assets/1246089/b4fc72c6-c9f3-4b10-8411-377df83e4473)
![2024-03-28-163854_928x313_scrot](https://github.com/junegunn/fzf/assets/1246089/3238fbd6-47fe-4a25-bc38-0ac08c18726b)
![2024-03-28-163937_940x331_scrot](https://github.com/junegunn/fzf/assets/1246089/30b8f522-4c49-47a5-a3a4-3e681ac2af40)

any Idea how to fix this ?
Thanks

**Comment by junegunn** [comment]
You need 0.44.0 or later.

https://github.com/junegunn/fzf/blob/master/CHANGELOG.md#0440

**Comment by dr3mro** [comment]
oh, Thanks 
I did contact the package maintainer so he might update the package to a newer version
have a nice day
