### ISSUE TITLE
After updating fzf - I get an error: .bashrc: unknown option: --bash - .zshrc: unknown option: --zsh

### ISSUE THREAD

**Issue by jkemp814** [junegunn/fzf#3703]
### Checklist

- [X] I have read through the manual page (`man fzf`)
- [X] I have searched through the existing issues

### Output of `fzf --version`

0.38.0 (debian)

### OS

- [X] Linux
- [ ] macOS
- [ ] Windows
- [ ] Etc.

### Shell

- [X] bash
- [X] zsh
- [ ] fish

### Problem / Steps to reproduce

Open a terminal. Throws error in both Bash and ZSH.

Opening .fzf.bash and .fzf.zsh show line: 7
eval "$(fzf --bash)"
eval "$(fzf --zsh)"

Both shells have a problem with those eval lines.

The same error occurs on my Fedora Linux 39 Silverblue machines also. Not just this Debian machine. (MX Linux 23.2)

**Comment by LangLangBart** [comment]
> 0.38.0 (debian)

Could you try version `0.48.0`[^1] or later?
[^1]: [fzf/CHANGELOG.md at master · junegunn/fzf · GitHub](https://github.com/junegunn/fzf/blob/master/CHANGELOG.md#0480)

**Comment by jkemp814** [comment]
I pulled using Git. How do I get version? I did notice fzf --version shows 0.38.0

**Comment by jkemp814** [comment]
Okay, I got it and that fixed it. Thanks for the help.

I had to purge the old one.

**Comment by jkemp814** [comment]
@LangLangBart 

Thanks for the help.

**Comment by bdellaterra** [comment]
Here's my code to avoid the `unknown option: --bash` error appearing when I start a new shell:

```
if command -v fzf &>/dev/null; then
  # Don't source FZF shell integrations if version is older than 0.48 (Avoids `unknown option: --bash`)
  # Version comparison technique courtesy of Luciano Andress Martini:
  # https://unix.stackexchange.com/questions/285924/how-to-compare-a-programs-version-in-a-shell-script
  FZF_VERSION="$(fzf --version | cut -d' ' -f1)"
  if [[ -f ~/.fzf.bash && "$(printf '%s\n' 0.48 "$FZF_VERSION" | sort -V | head -n1)" = 0.48 ]]; then
    . ~/.fzf.bash
  fi
fi
```

I clone my .bashrc down to different Linux boxes or containers and sometimes the Debian ones will print that error before every command prompt. Note that Ctrl-R and other shell integrations are skipped when the FZF version is <0.48, so upgrading is preferable. This is mainly about keeping error noise away.

**Comment by bolorkhuu** [comment]
in my case i had a preinstall fzf, workaround
`PATH=$HOME/.fzf/bin:$PATH`
