### ISSUE TITLE
unknown option: --walker=file,dir,follow,hidden

### ISSUE THREAD

**Issue by ismayeelanver** [junegunn/fzf#3704]
### Checklist

- [ ] I have read through the manual page (`man fzf`)
- [X] I have searched through the existing issues

### Output of `fzf --version`

0.29 (devel)

### OS

- [X] Linux
- [ ] macOS
- [ ] Windows
- [ ] Etc.

### Shell

- [ ] bash
- [X] zsh
- [ ] fish

### Problem / Steps to reproduce

unknown option: --walker=file,dir,follow,hidden

**Comment by ismayeelanver** [comment]
when I press ^T (ctrl+t or fzf-file-widget) it is not working.

if youve fixed it please push it to repo for setup for new machine

thank you

**Comment by LangLangBart** [comment]
> 0.29 (devel)
> unknown option: --walker=file,dir,follow,hidden

Could you try version `0.48.0`[^1] or later?


For more information on sourcing shell files in older `fzf` versions, read the README[^2], as the
`--walker` flag has only been added recently.

[^1]: [fzf/CHANGELOG.md at master · junegunn/fzf · GitHub](https://github.com/junegunn/fzf/blob/master/CHANGELOG.md#0480)
[^2]: [README.md - Setting up shell integration  · junegunn/fzf ](https://github.com/junegunn/fzf?tab=readme-ov-file#setting-up-shell-integration)

**Comment by ismayeelanver** [comment]
its now working. first i had the old version downloaded (from apt). now i put
