### ISSUE TITLE
fish ctrl-t doesn't respect the relative directory with user defined $FZF_CTRL_T_COMMAND

### ISSUE THREAD

**Issue by kpskp77** [junegunn/fzf#3705]
### Checklist

- [X] I have read through the manual page (`man fzf`)
- [X] I have searched through the existing issues

### Output of `fzf --version`

0.48 (devel)

### OS

- [X] Linux
- [ ] macOS
- [ ] Windows
- [ ] Etc.

### Shell

- [ ] bash
- [ ] zsh
- [X] fish

### Problem / Steps to reproduce

```fish
> echo $FZF_CTRL_T_COMMAND
fd --follow --exclude tags --exclude .svn --exclude .git . $dir 2>/dev/null
```
I think the problem is the variable `$dir` is not exported in key-bindings.fish

```fish
function fzf_key_bindings

  # Store current token in $dir as root for the 'find' command
  function fzf-file-widget -d "List files and folders"
    set -l commandline (__fzf_parse_commandline)
    set -l dir $commandline[1] ## <--- should be `set -lx` here?
    set -l fzf_query $commandline[2]
    set -l prefix $commandline[3]
```

**Comment by junegunn** [comment]
Maybe you're running into #3684?

**Comment by junegunn** [comment]
Thanks for the report, your analysis is spot on. It should be fixed now.
