### ISSUE TITLE
Never quit / interactive mode

### ISSUE THREAD

**Issue by jondot** [junegunn/fzf#372]
Hi,
I'm using a hacked up fzf fork that I modified to run always as an interactive console. I run it in a window forever, based on an index I choose.
Upon selection, it will execute an OS 'open' command and it will *not* exit.
Do you think such a thing will be useful for fzf itself as a CLI option?

Thanks!

**Comment by justinmk** [comment]
What is the purpose? What is the advantage of being always-open (and needing to focus that window) vs. being always-available (invoked at any time, from anywhere).

**Comment by jondot** [comment]
Think of how Spotlight search works. For my use case, I:

- Use the same index all the time
- Don't mind having a dedicated terminal window just for this
- Perform action when accepting a result, which is mostly the OS 'open'
- I'd like to go back and do the same thing quickly

**Comment by junegunn** [comment]
Hi, have you checked "execute" action? I think it's equivalent to what you're describing.

`fzf --bind "enter:execute(open {})"`

I use it to implement a commit browser function as follows:
```sh
# fshow - git commit browser
fshow() {
  git log --graph --color=always \
      --format="%C(auto)%h%d %s %C(black)%C(bold)%cr" "$@" |
  fzf --ansi --no-sort --reverse --tiebreak=index --toggle-sort=\` \
      --bind "ctrl-m:execute:
                echo '{}' | grep -o '[a-f0-9]\{7\}' | head -1 |
                xargs -I % sh -c 'git show --color=always % | less -R'"
}
```

**Comment by jondot** [comment]
Yes! amazing stuff, thanks!
I didn't see this behavior while going over the source, is there a chance you can point me to it? just for learning purposes
Thanks
