### ISSUE TITLE
When sending reload(...) + preview(...) during the same event, the preview is reset

### ISSUE THREAD

**Issue by noahmayr** [junegunn/fzf#3723]
### Checklist

- [X] I have read through the manual page (`man fzf`)
- [X] I have searched through the existing issues
- [ ] For bug reports, I have checked if the bug is reproducible in the latest version of fzf

### Output of `fzf --version`

0.49.0 (brew)

### OS

- [X] Linux
- [X] macOS
- [ ] Windows
- [ ] Etc.

### Shell

- [X] bash
- [X] zsh
- [ ] fish

### Problem / Steps to reproduce

Reproduction:
1. Run the following example
```sh
SHELL=/bin/sh LIST="a\nb\nc" fzf --preview 'echo {}'  --bind 'start:reload(echo $LIST)' --bind 'ctrl-p:reload(echo $LIST)+preview(echo "Hello World")
```
2. Press `ctrl-p` to switch to a temporary preview showing "Hello World"

Expected:
The list is reloaded and the preview shows "Hello World" and goes back to the configured preview when navigating through the list

Actual:
The list is reloaded, the preview quickly flashes "Hello World" before showing the preview configured by `--preview`

**Comment by junegunn** [comment]
Both reload and preview actions run asynchronously, so there is no guarantee that they finish in the specified order.

To give a better example:

```sh
echo alice | fzf --preview 'echo Hello {}' --bind 'space:reload(sleep 1; echo bob)+preview(echo Hi {})'
```

I'm not sure what you're trying to achieve with the actions, but it looks like you need a different strategy.
