### ISSUE TITLE
[NixOS] ~/.fzf/bin/fzf: No such file or directory (even though it exists)

### ISSUE THREAD

**Issue by mayhewluke** [junegunn/fzf#373]
Trying to install `fzf-0.10.8` gives the following error:

```
$ ~/.fzf/install
...
  - Creating symlink: bin/fzf-0.10.8-linux_amd64 -> bin/fzf
  - Checking fzf executable ... Error: .fzf/install: line 25: /home/mayhewluke/.fzf/bin/fzf: No such file or directory
  - Invalid binary !!!
```

I downloaded the file manually and verified that the file exists, but trying to execute it gives the same error. The releases page says that the 64-bit binary is statically linked, but when I run `file` it appears to be dynamically linked:

```
$ file fzf-0.10.8-linux_amd64
fzf-0.10.8-linux_amd64: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.18, BuildID[sha1]=01989a613062d635dd053c9a2ac668697d9563ae, not stripped
```

Installing using `fzf-0.10.5` (ie. prior to [this change in 0.10.6](https://github.com/junegunn/fzf/commit/d980e00961e64c12c28fe6adb209a6c0a652efd1#diff-19ad89bc3e3c9d7ef68b89523eff1987L83)) works just fine (it downloads the static binary).

Note: I don't even know what a static or dynamically linked binary is, so I really don't know what's going on here - just trying to provide what information I can.

**Comment by junegunn** [comment]
Linux 64-bit binary is now ["partially static"](https://github.com/junegunn/fzf/commit/6bc3fe6e67e1a9f6d80d47c03dc6f4f3f4453380).
- Does the binary work? You mean running `./fzf-0.10.8-linux_amd64` gives "No such file or directory" error? That's strange.
- What is the output of `ldd fzf-0.10.8-linux_amd64`?

**Comment by mayhewluke** [comment]
```
> curl -fL https://github.com/junegunn/fzf-bin/releases/download/0.10.8/fzf-0.10.8-linux_amd64.tgz | tar -xz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   589    0   589    0     0   1881      0 --:--:-- --:--:-- --:--:--  1881
100 1072k  100 1072k    0     0   618k      0  0:00:01  0:00:01 --:--:-- 1415k
> ls -lA
total 3.6M
drwxr-xr-x  2 mayhewluke users 4.0K Oct  9 23:15 .
drwxrwxrwt 42 root       root  4.0K Oct  9 23:15 ..
-rwxr-xr-x  1 mayhewluke users 3.6M Oct  8 21:21 fzf-0.10.8-linux_amd64
> ./fzf-0.10.8-linux_amd64
zsh: no such file or directory: ./fzf-0.10.8-linux_amd64
> ldd fzf-0.10.8-linux_amd64   
/run/current-system/sw/bin/ldd: line 117: ./fzf-0.10.8-linux_amd64: No such file or directory
```

I'm using NixOS 15.09, which I've found tends to be a lot more barebones than the other distros I've tried, so perhaps I'm missing something that I should have installed?

**Comment by junegunn** [comment]
That is the strangest error message I've seen in a while. I have no experience with NixOS, but I'll see if I can set up a VM and test it when I get some time.

**Comment by mayhewluke** [comment]
Thanks! Let me know if there's anything else I can do to help :)

**Comment by junegunn** [comment]
I can reproduce the problem on a NixOS VM.
A quick googling directed me to this link:
http://unix.stackexchange.com/questions/91577/cannot-execute-binary-in-nixos-no-such-file-or-directory

> You can't usually run binary files in NixOS, they will either need some environment variables set or to be patched with patchElf.

... what?

Looks like NixOS is radically different from other distros and so there's not much I can help. I'll leave this up to someone familiar to NixOS.

**Comment by xconstruct** [comment]
I just encountered the same problem. NixOS does not have a traditional /lib folder, so it doesn't find the correct linker path. PatchELF fixes this.

    patchelf --set-interpreter /run/current-system/sw/lib/ld-linux-x86_64.so.2 ~/.fzf/bin/fzf-0.10.8-linux_amd64`

Still not sure if this is the best way. We should probably make use of NixOS' own build system - fzf is packaged in nixpkgs, but currently does not automate the whole shell install.

**Comment by junegunn** [comment]
@xconstruct Thanks for the tip. Do you think it makes sense for fzf installer to do it automatically on NixOS (for those who don't want/need to use nixpkgs) ?

**Comment by xconstruct** [comment]
Looks like `patchelf` is missing on a clean install, so people would have to install it, too. And NixOS unique architecture basically forces everyone to use the Nix package manager - it is expected that every binary from the internet will break sooner or later.

I'd suggest:

1. Folks on NixOS have to install fzf via package manager beforehand (e.g. `nix-env -iA nixos.fzf`)
2. The installer checks for an existing fzf (should be in `$PATH` by then) and then continues with the shell setup.

Maybe the installer can also execute step 1. It doesn't need root privileges and would install fzf into the users current profile, not system wide. Though I myself would still like to see a way to skip the download and just do the shell install - this may also be useful in later nixpkgs install automation.

**Comment by junegunn** [comment]
Thanks for the feedback. Yes, it makes sense to skip downloading if the right version is found on path.

**Comment by wedens** [comment]
I've had the same problem on NixOS. ended up installing it from nixpkgs (nixos package repository). you need to add keybindings/completions manually though

**Comment by tupton** [comment]
I see this same error on Ubuntu 14.04! It has been driving me absolutely bonkers.

```
❯ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.3 LTS
Release:        14.04
Codename:       trusty
❯ git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
Cloning into '/home/thomas/.fzf'...
remote: Counting objects: 72, done.
remote: Compressing objects: 100% (66/66), done.
remote: Total 72 (delta 1), reused 19 (delta 0), pack-reused 0
Unpacking objects: 100% (72/72), done.
Checking connectivity... done.
❯ ~/.fzf/install
Downloading bin/fzf ...
  - Found in $PATH
  - Creating symlink: ./fzf -> bin/fzf
  - Checking fzf executable ... Error: /home/thomas/.fzf/install: line 73: /home/thomas/.fzf/bin/fzf: Too many levels of symbolic links
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   603    0   603    0     0   2862      0 --:--:-- --:--:-- --:--:--  2857
100 1086k  100 1086k    0     0   677k      0  0:00:01  0:00:01 --:--:-- 1471k
  - Creating symlink: bin/fzf-0.11.0-linux_amd64 -> bin/fzf
  - Checking fzf executable ... Error: /home/thomas/.fzf/install: line 73: /home/thomas/.fzf/bin/fzf: No such file or directory
  - Invalid binary !!!
❯ cd ~/.fzf/bin
❯ ls -al
total 3652
drwxrwxr-x 2 thomas thomas    4096 Nov  9 22:56 ./
drwxrwxr-x 9 thomas thomas    4096 Nov  9 22:55 ../
-rwxr-xr-x 1 thomas thomas 3720790 Nov  9 16:55 fzf-0.11.0-linux_amd64*
-rwxrwxr-x 1 thomas thomas    3257 Nov  9 22:55 fzf-tmux*
❯ ./fzf-0.11.0-linux_amd64
zsh: no such file or directory: ./fzf-0.11.0-linux_amd64
❯ file ./fzf-0.11.0-linux_amd64
./fzf-0.11.0-linux_amd64: ELF 64-bit LSB  executable, x86-64, version 1 (SYSV), dynamically linked (uses shared libs), for GNU/Linux 2.6.18, BuildID[sha1]=5f45f78d7c811dff7e64efafd30e0bf66a046c6a, not stripped
❯ ldd ./fzf-0.11.0-linux_amd64
        not a dynamic executable
```

**Comment by junegunn** [comment]
Anyone else having this problem on Ubuntu 14? I tested fzf 0.11.0 on Ubuntu 14.04 and had no issues.

**Comment by tupton** [comment]
I wonder if the fact that this is a VPS on Linode has anything to do with this? I wouldn't have thought so, but I'm running out of reasons this could be happening or other things to look into.

**Comment by junegunn** [comment]
I don't know. If you have Go development environment, i.e. installed Go, try building the binary from source with `go get github.com/junegunn/fzf/src/fzf`.

**Comment by tupton** [comment]
```
❯ go get github.com/junegunn/fzf/src/fzf
# github.com/junegunn/fzf/src/curses
src/github.com/junegunn/fzf/src/curses/curses.go:263: cannot use *_Cvar_stderr (type *_Ctype_struct__IO_FILE) as type *_Ctype_FILE in function argument
src/github.com/junegunn/fzf/src/curses/curses.go:263: cannot use *_Cvar_stdin (type *_Ctype_struct__IO_FILE) as type *_Ctype_FILE in function argument
```

**Comment by junegunn** [comment]
Hmm, did you try [`patchelf`](https://github.com/junegunn/fzf/issues/373#issuecomment-150803995) suggested above? (The actual path to ld-linux should differ though)

**Comment by tupton** [comment]
```
❯ patchelf --set-interpreter /lib/i386-linux-gnu/ld-2.19.so ~/.fzf/bin/fzf-0.11.0-linux_amd64
❯ ./bin/fzf-0.11.0-linux_amd64
zsh: accessing a corrupted shared library: ./bin/fzf-0.11.0-linux_amd64
```

Thanks for taking a look at this. I admit I am in way over my head here. I'm not exactly sure what `patchelf` even does, but I understand it was a shot in the dark.

Is the fact that I can't build the binary on this machine related to this issue?

**Comment by junegunn** [comment]
No idea, I should be able to reproduce the problem for proper investigation.
But wait, `i386`? You might want to check if [the 32-bit binary works](https://github.com/junegunn/fzf-bin/releases/download/0.11.0/fzf-0.11.0-linux_386.tgz). And what does `uname -a` say?

**Comment by tupton** [comment]
> But wait, i386?

Yeah, that is super weird. But:

```
❯ ls -al /lib | grep ld-linux
lrwxrwxrwx  1 root root    25 Feb 25  2015 ld-linux.so.2 -> i386-linux-gnu/ld-2.19.so*
❯ uname -a
Linux upton 4.1.5-x86_64-linode61 #7 SMP Mon Aug 24 13:46:31 EDT 2015 x86_64 x86_64 x86_64 GNU/Linux
```

I have no idea why I would need a 32-bit binary...

I eventually got it working by:

* Cloning the repo into `~/.fzf`
* Manually downloading the 32-bit binary to `bin/`
* Manually creating the `bin/fzf` symlink
* Running `~/.fzf/install` (because `.` is in my `$PATH` and `~/.fzf` has a file called `fzf`)

```
❯ git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
Cloning into '/home/thomas/.fzf'...
remote: Counting objects: 72, done.
remote: Compressing objects: 100% (66/66), done.
remote: Total 72 (delta 1), reused 19 (delta 0), pack-reused 0
Unpacking objects: 100% (72/72), done.
Checking connectivity... done.
○ thomas@upton ~
❯ cd ~/.fzf/bin
❯ curl -fL https://github.com/junegunn/fzf-bin/releases/download/0.11.0/fzf-0.11.0-linux_386.tgz | tar xz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   601    0   601    0     0   3367      0 --:--:-- --:--:-- --:--:--  3395
100  939k  100  939k    0     0   759k      0  0:00:01  0:00:01 --:--:-- 1297k
❯ ln -s fzf-0.11.0-linux_386 fzf
❯ cd
❯ ~/.fzf/install
Downloading bin/fzf ...
  - Already exists
  - Checking fzf executable ... 0.11.0
Do you want to enable fuzzy auto-completion? ([y]/n) y
Do you want to enable key bindings? ([y]/n) y

Generate ~/.fzf.bash ... OK
Generate ~/.fzf.zsh ... OK

Update /home/thomas/.bashrc:
  - [ -f ~/.fzf.bash ] && source ~/.fzf.bash
    + Added

Update /home/thomas/.zshrc:
  - [ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
    + Added

Finished. Restart your shell or reload config file.
   source ~/.bashrc  # bash
   source ~/.zshrc   # zsh

Use uninstall script to remove fzf.

For more information, see: https://github.com/junegunn/fzf
```

**Comment by junegunn** [comment]
@tupton Hmm, I wonder if there's a better way to determine the right binary than uname. Anyway I added `--32` and `--64` options to install script. So you can use it.

**Comment by tupton** [comment]
Thanks so much for taking the time to look at and help me out with this crazy issue.

I have no idea why my VM needs 32-bit binaries. I do have a *ton* of i386-architecture packages installed, which seems related, but that's definitely not your or `fzf`'s problem.

Thanks again.
