### ISSUE TITLE
[Feature Request] Customizable shell command flag for command execution

### ISSUE THREAD

**Issue by LangLangBart** [junegunn/fzf#3732]
### Checklist

- [X] I have read through the manual page (`man fzf`)
- [X] I have searched through the existing issues
- [X] For bug reports, I have checked if the bug is reproducible in the latest version of fzf

### Output of `fzf --version`

0.50.0 (brew)

### OS

- [ ] Linux
- [X] macOS
- [ ] Windows
- [ ] Etc.

### Shell

- [ ] bash
- [X] zsh
- [ ] fish

### Problem / Steps to reproduce

This report was created from a discussion on a discarded PR: #3726

---

### Issue

`fzf` currently executes commands with `$SHELL` and a hardcoded `-c` flag.

https://github.com/junegunn/fzf/blob/f97d2754134607b24849fc4a2062dbfcaafddd6a/src/util/util_unix.go#L22-L29

If a user wants to use a different tool with a different flag to execute commands, they must prepend the desired command to each string, making proper quoting more cumbersome and leading to repetitive addition of the command.

```bash
# [bun] https://github.com/oven-sh/bun
fzf --bind "start:reload:bun --print \"Object.keys(Bun.env).sort().join('\n')\""
```

---

### Feature Proposal

Ability to change the flag that is passed to the `$SHELL` command.

If the flag would be subject to change, then one would only need to write the string.

```bash
# Syntax example, not actual usage
SHELL=$(which bun) FZF_SHELL_FLAG="--print" \
  fzf --bind "start:reload:Object.keys(Bun.env).sort().join('\n')"

# Different syntax example proposed by the maintainer
fzf --with-shell "bun --print" \
  --bind "start:reload:Object.keys(Bun.env).sort().join('\n')"
```

Here are a few examples of tools with their corresponding flags to illustrate the variety of flags that might be used:
- `jsc -e`: a short, single-letter option [^1]
- `bun --print`: a long, word-based option [^2]
- `osascript -l JavaScript -e`: multiple short, single-letter options and an argument [^3]

---

### Workaround
The maintainer provided a workaround [^4].

```bash
fzf2() (
  export SHELL=/tmp/fzfsh
  if ! [[ -x $SHELL ]]; then
    echo '#!/bin/sh' > "$SHELL"
    echo 'shift; echo "$@"' >> "$SHELL"
    chmod +x "$SHELL"
  fi
  command fzf "$@"
)

fzf2 --preview 'run this command: {}'
```

[^1]: [JSC – WebKit](https://trac.webkit.org/wiki/JSC)
[^2]: [Bun — A fast all-in-one JavaScript runtime](https://bun.sh/)
[^3]: [JXA - JavaScript for Automation](https://developer.apple.com/library/archive/releasenotes/InterapplicationCommunication/RN-JavaScriptForAutomation/Articles/Introduction.html)
[^4]: [PR #3726 (comment)](https://github.com/junegunn/fzf/pull/3726#issuecomment-2054007955)

**Comment by junegunn** [comment]
The suggestion here is to add an option similar to `shellcmdflag` of Vim: https://vimdoc.sourceforge.net/htmldoc/options.html#'shellcmdflag'

Personally, I don't like having to set two environment variables (or options) to make it work. It doesn't feel much more ergonomic than writing a wrapper script. I'd prefer to add an option that looks like `fzf --with-shell "$SHELL -c"` as [commented in the previous pull request](https://github.com/junegunn/fzf/pull/3726#issuecomment-2054035293) though it has it's own issue.

**Comment by LangLangBart** [comment]
Sure, using `--with-shell` is much clearer and simpler to write than using two environment variables.

---


It's **important** to mention in the **documentation** that, if this feature is implemented, one should not set
the flags to `-ic` for the typical `SHELL` (`zsh`, …), as it usually ends badly. Below are some instances where
doing so has caused issues:




- [Ctrl-r for shell history but also bulk select and remove from history · Discussion #3629 · junegunn/fzf](https://github.com/junegunn/fzf/discussions/3629#discussioncomment-8476288)
- [View mode crash with bat %c %q and shellcmdflag=-ic · Issue #471 · vifm/vifm](https://github.com/vifm/vifm/issues/471)
