### ISSUE TITLE
[Feature Request] Integrate fzf into Gnome Search

### ISSUE THREAD

**Issue by Polydynamical** [junegunn/fzf#3735]
I regularly use the Gnome Search in Ubuntu simply because of its ease of access ("Super" key). Yet these results are painstakingly slow and doesn't seem very "super". Thus an idea is born! What if we could implement the fzf querier directly as the engine for Gnome's Search? Is this feasible?

**Comment by junegunn** [comment]
Closing, as this is not a feature request on fzf itself. I'm not an Ubuntu user so I'm not sure what you're trying to do, but I'm pretty sure you can use fzf to implement it. Some pointers.

https://junegunn.github.io/fzf/tips/ripgrep-integration/
https://github.com/junegunn/fzf/blob/master/ADVANCED.md

**Comment by lukitsche** [comment]
Another pointer:
https://developer.gnome.org/documentation/tutorials/search-provider.html
