### ISSUE TITLE
Make it possible to custom-bind an action to mouse click

### ISSUE THREAD

**Issue by junegunn** [junegunn/fzf#374]
You can start a never-ending fzf browser with the following command.

```
fzf --bind "enter:execute(open {})"
```

However, this closes as usual when you double-click an item as the action is only mapped to `enter` key.

**Comment by junegunn** [comment]
```sh
fzf --bind "enter:execute(less {}),double-click:ignore"
```

What if we want double-click to behave the same as enter?

```sh
A="execute(less {})" sh -c 'fzf --bind "enter:$A,double-click:$A"'
```

No magic.

**Comment by netei** [comment]
> No magic.

Great !
