### ISSUE TITLE
Command failed on starting fzf

### ISSUE THREAD

**Issue by Yair-Ziv** [junegunn/fzf#3759]
### Checklist

- [X] I have read through the manual page (`man fzf`)
- [X] I have searched through the existing issues
- [ ] For bug reports, I have checked if the bug is reproducible in the latest version of fzf

### Output of `fzf --version`

0.50.0 (f97d275)

### OS

- [X] Linux
- [ ] macOS
- [ ] Windows
- [ ] Etc.

### Shell

- [ ] bash
- [X] zsh
- [ ] fish

### Problem / Steps to reproduce

When I run fzf I get the output [Command failed: fd --hidden --strip-cwd-prefix --exclude .git] as attached: (those are the arguments to my FZF_DEFAULT_COMMAND)
![image](https://github.com/junegunn/fzf/assets/17926038/a40df3b0-335c-4864-93fd-d7c338f60816)

Not sure why it started happening as it didn't happen before.

When running that command separately it says: 
unknown option: fd

I've also noticed it says that for every argument if passed first
fzf --hidden --strip-cwd-prefix --exclude .git 
outputs:
unknown option: --hidden

Installed from git using ./install, I did remove the .fzf.zsh and just symlinked the binary to /usr/bin to make the system more reproducable but even without that and using the fzf.zsh it still outputs the same error.

Please advice ❤️

**Comment by hitaishi2222** [comment]
Did you solve the issue?
please let us know the steps to solve this?

**Comment by Yair-Ziv** [comment]
Well, awkwardly enough I didn't know fd was a different package I needed to install, after installing fd everything worked perfectly

**Comment by faximan** [comment]
For someone else coming here: this is because on linux the command is called `fdfind`
