### ISSUE TITLE
Binary version of fzf is unable to handle CJK characters

### ISSUE THREAD

**Issue by wzyboy** [junegunn/fzf#376]
It seems that the binary version of fzf (https://github.com/junegunn/fzf-bin/releases) has some issues when handling CJK characters.

In a directory containig filenames with CJK characters, the binary version of fzf lists them as garbled text:

```bash
  고�~Z~T
  ��~I��~W
> 漢��~W
  3/3
> 
```

However, with fzf compiled from source code, it works fine:

```bash
  고요
  汉字
> 漢字
  3/3
> 
```

I am using fzf version 0.10.8. All my locales (system, enviroment variables, termianl, etc) are `en_US.UTF-8`.

**Comment by wzyboy** [comment]
Ah, forgot to mention, the binary version I tested is `fzf-0.10.8-linux_amd64.tgz`.

**Comment by junegunn** [comment]
Ah, thanks for the report. I should probably release a new version, but I simply replaced the binary on GitHub. Please check if the problem's resolved.

**Comment by wzyboy** [comment]
Affirmative. Problem sovled. :+1:

**Comment by junegunn** [comment]
Thanks!
