### ISSUE TITLE
fzf on android?

### ISSUE THREAD

**Issue by acornejo** [junegunn/fzf#377]
I am happy fzf user in linux and os x. Today I tried to install it inside my android tablet (inside a terminal prompt provided by termux) and realized there is no linux armv71 version. Given that go supports cross compiling to other architectures, perhaps we could fzf here too?

**Comment by junegunn** [comment]
Unfortunately, ncurses makes cross compilation impossible (or at least non-trival). I haven't been successful so instead I'm currently building [linux binaries using VM](https://github.com/junegunn/fzf/blob/0.10.8/src/Makefile#L80-L82) on OS X.

I have no experience or knowledge on the android platform you mentioned, but I suppose it's possible in a similar manner given that ncurses is available there.

**Comment by acornejo** [comment]
Ahh, of course, for some reason I thought fzf was pure go, but it does make sense that it links to ncurses for term stuff.

Given that you are already using docker, I'll look into creating a Dockerfile that builds fzf from source. I already have a Dockerfile to build other ncurses based android programs, so I just need to figure out how to get ncurses to link statically in android. I'll try to work on this latter and put up a pull-request for adding a Dockerfile.android

**Comment by junegunn** [comment]
Sound good!

**Comment by acornejo** [comment]
ok, so i've made some progress on the dockerfile and building the cross compiler toolchain for android inside. However, I am getting the following error (looking for ideas):

curses/curses.go: In function 'swapOutput':
curses/curses.go:9:10: error: lvalue required as left operand of assignment
   stdout = stderr;
          ^
curses/curses.go:10:10: error: lvalue required as left operand of assignment
   stderr = temp;

Error seems pretty clear, the android C compiler doesn't like writing to stdout and stderr; presumably because they are defined as const. Can we do without this?

**Comment by junegunn** [comment]
Yo, I think you're looking at an old revision.

**Comment by acornejo** [comment]
Ok, just to give some updates. I got that older revision to compile by removing the swapOutput function (probably it broke functionality, but I just wanted it to see if that would work). After compiling I copied the binary over to my android device and tested it, and it worked!!

Next I saw your message and tried to compile the latest version. Here I am facing a slightly different problem, the error I get is:

/tmp/go-build054928491/github.com/junegunn/fzf/src/curses/_obj/_cgo_main.o:_cgo_main.c:_cgohack_stdin: error: undefined reference to 'stdin'
/tmp/go-build054928491/github.com/junegunn/fzf/src/curses/_obj/_cgo_main.o:_cgo_main.c:_cgohack_stderr: error: undefined reference to 'stderr'

The fact that the word "hack" is in there makes me uneasy, since it seams the golang folks knew they were doing something nasty with stdin and stderr, and the android NDK doesn't like it. Not sure what to try out next, let me know if you have any ideas, I'll post an updated when I manage to get past this.

PS: The docker image is ready and works well, it seems clear now that the pull-request will also need to add a couple of lines to the curses.go file to change the CFLAGS and LDFLAGS for android. Good news is that go supports switching those flags based on the GOOS environment variable, so we can keep the android settings in the master branch without changing the flags for other OS'es.

**Comment by acornejo** [comment]
ok, got it to build.

turns out that if you use C.{stdin,stdout,stderr} then those things have to be resolved at compile time, and if you instead refer to them inside a C function, they are resolved at runtime.

I compiled using that trick and not only it compiled, but the binary worked beautifully on my tablet.

Also, here is the script I was using to build inside the container: (the -pie ld flags are necessary for the binary to work on android 5+)

```
export CC=/ndk/bin/arm-linux-androideabi-gcc
export GOROOT=/go1.4
export GOPATH=/go
export GOOS=android
export GOARCH=arm
export GOARM=7
export CGO_ENABLED=1

GO="$GOROOT/bin/go"

$GO build -x -ldflags="-extldflags=-pie"
```

**Comment by junegunn** [comment]
Closing as we now can build android binaries thanks to your effort. Let me know if you think it makes sense to extend the install script as well.
