### ISSUE TITLE
Preserve fzf fuzzy list view?

### ISSUE THREAD

**Issue by tmpm697** [junegunn/fzf#3779]
### Checklist

- [X] I have read through the manual page (`man fzf`)
- [X] I have searched through the existing issues
- [X] For bug reports, I have checked if the bug is reproducible in the latest version of fzf

### Output of `fzf --version`

0.51.0

### OS

- [ ] Linux
- [X] macOS
- [ ] Windows
- [ ] Etc.

### Shell

- [ ] bash
- [X] zsh
- [ ] fish

### Problem / Steps to reproduce

i'm using this `      --preview 'echo $(({n} + 1)) >~/.cache/fzf/my_no_file' \` to save current cursor's position in the list, but i will lose the `view` of it, how to preserve the `view` also?

check two images below:
the last view before close fzf:
![Screenshot 2024-05-07 at 10 43 14 PM](https://github.com/junegunn/fzf/assets/48467427/3cda4fff-3d3f-4a62-849b-74ee6e30e6c4)

now after re-open fzf, the view of current line drop to last line:
![Screenshot 2024-05-07 at 10 43 26 PM](https://github.com/junegunn/fzf/assets/48467427/f48a29b3-0caf-4102-b63f-34c1a582a9bc)

why i want to preserve the last `view`? because human brain or my brain will fix thinking the last image of what i see fzf, but when re-open, i am a bit `surprise` with the `view` change, the position still correct (10) though.

**Comment by kuremu** [comment]
I suggest something like `fzf --bind $'focus:execute-silent(echo {n} > last.pos)' --bind $'load:transform(echo pos\(5\))+unbind(load)'`

**Comment by kuremu** [comment]
I would suggest something like `seq 50 | fzf --bind $'focus:execute-silent(echo $(({n} + 1)) > last.pos)' --bind $'load:transform(echo pos\($(cat last.pos)\))+unbind(load)'`

**Comment by tmpm697** [comment]
> seq 50 | fzf --bind $'focus:execute-silent(echo $(({n} + 1)) > last.pos)' --bind $'load:transform(echo pos\($(cat last.pos)\))'

it does not load up last post and not keep the `view`

**Comment by kuremu** [comment]
If you mean you want to reopen fzf with 10 still selected, and also 11 and 12 still visible at the bottom of the list, I don't think there is functionality for this. The scrolling and view position is sorted out automatically by pos(). You might find `--scroll-off=n` useful, which will at least keep a buffer of `n` items between the top/bottom edges of the list and the cursor.

**Comment by tmpm697** [comment]
> If you mean you want to reopen fzf with 10 still selected, and also 11 and 12 still visible at the bottom of the list, I don't think there is functionality for this. The scrolling and view position is sorted out automatically by pos(). You might find `--scroll-off=n` useful, which will at least keep a buffer of `n` items between the top/bottom edges of the list and the cursor.

yeah, `--scroll-off=LINES` helped but it feel less natural than usual.

and why u suggest save and restore `pos` with this? `seq 50 | fzf --bind $'focus:execute-silent(echo $(({n} + 1)) > last.pos)' --bind $'load:transform(echo pos\($(cat last.pos)\))'` --> i tried and it does not work, `pos` is saved to file but cursor not restored at last `pos`.

**Comment by kuremu** [comment]
> and why u suggest save and restore `pos` with this? `seq 50 | fzf --bind $'focus:execute-silent(echo $(({n} + 1)) > last.pos)' --bind $'load:transform(echo pos\($(cat last.pos)\))'` --> i tried and it does not work, `pos` is saved to file but cursor not restored at last `pos`.

Sorry didn't notice you were using zsh. This looks like it works:

`seq 50 | fzf --bind 'focus:execute-silent(echo $(({n} + 1)) > last.pos)' --bind 'load:transform:echo pos\($(cat last.pos)\)'`

**Comment by tmpm697** [comment]
> seq 50 | fzf --bind 'focus:execute-silent(echo $(({n} + 1)) > last.pos)' --bind 'load:transform:echo pos\($(cat last.pos)\)'

ty, so via `--bind` is more preferred than via `--preview` to save/restore `pos` is what u mean?

**Comment by kuremu** [comment]
> ty, so via `--bind` is more preferred than via `--preview` to save/restore `pos` is what u mean?

Yeah, specifically `--bind 'focus:...` for saving and `--bind 'load:...` for loading. But there are quite a few ways you could do it. Check `man fzf` **AVAILABLE KEYS** and **AVAILABLE EVENTS** for what you can bind to, and **AVAILABLE ACTIONS** for what can be performed on a bind.

**Comment by tmpm697** [comment]
@junegunn @LangLangBart any idea for this issue?

**Comment by junegunn** [comment]
What exactly are you trying to implement here?

fzf doesn't support persisting and restoring its internal states between processes, because of its asynchronous nature and because there are just too many dynamic states that affect the user interface. If you want to quickly come back to fzf after running some other interactive tasks, use `execute` action.

**Comment by tmpm697** [comment]
i just realized that this feature may need to bring a daemon and db to persist some states which is not standalone exe fzf can solve.

**Comment by tmpm697** [comment]
for someone who stumble to this issue later, we can save current post with `fzf` and restore it later, then i wonder if we can able to saving the current top line pos (below header if has) and the bottom one --> so we can restore the current pos relative to two top and bottom pos.

this theoretically possible, when we restore the last pos, say we can make it relative (last pos + last bottom) = current relative pos. or (last pos + last top) = relative pos.
