### ISSUE TITLE
Preserve color output of `kubecolor get pods -A | fzf --ansi`?

### ISSUE THREAD

**Issue by tmpm697** [junegunn/fzf#3782]
### Checklist

- [X] I have read through the manual page (`man fzf`)
- [X] I have searched through the existing issues
- [X] For bug reports, I have checked if the bug is reproducible in the latest version of fzf

### Output of `fzf --version`

0.51.0

### OS

- [ ] Linux
- [X] macOS
- [ ] Windows
- [ ] Etc.

### Shell

- [ ] bash
- [X] zsh
- [ ] fish

### Problem / Steps to reproduce

I have this:
```
kubecolor get pods -A | fzf --ansi
```
expect color output of `kubecolor` preserved but in fact, the color is lost.

**Comment by LangLangBart** [comment]
Usually, there is an extra option to retain the escape sequences when piped into another command.

See: [kubecolor/kubecolor - Dynamic tty support](https://github.com/kubecolor/kubecolor?tab=readme-ov-file#dynamic-tty-support)

```bash
KUBECOLOR_FORCE_COLORS=true kubecolor ... | fzf ...
# or
kubecolor --force-color ... | fzf ...
```


```bash
# Enables colors automatically when outputting to the terminal; otherwise, it disables them.
command grep --color=auto '^foo' /usr/share/dict/words
command grep --color=auto '^foo' /usr/share/dict/words | fzf

# vs

# Always enables colorized output.
command grep --color=always '^foo' /usr/share/dict/words | fzf
```
