### ISSUE TITLE
`{q}` isn't escaped properly on Windows

### ISSUE THREAD

**Issue by ibhagwan** [junegunn/fzf#3789]
### Checklist

- [X] I have read through the manual page (`man fzf`)
- [X] I have searched through the existing issues
- [X] For bug reports, I have checked if the bug is reproducible in the latest version of fzf

### Output of `fzf --version`

0.52.0 (bcda25a)

### OS

- [ ] Linux
- [ ] macOS
- [X] Windows
- [ ] Etc.

### Shell

- [ ] bash
- [ ] zsh
- [ ] fish

### Problem / Steps to reproduce

Follwing up on #3626, we now have a different issue.

I found the current escaping sequence isn't yet working properly, while the command described in #3626 (basically, "live grep") is working it will only work when `{q}` is the last argument of the command.

Consider we want to display `rg` error messages inside fzf, we have to redirect the error stream to stdout by adding `2>&1`:
```sh
fzf --ansi --disabled --bind="change:reload:rg --line-number --column --color=always {q} 2>&1"
```
Now if we have an open `\` we see the error inside fzf (instead of "Command failed: ... "):
![image](https://github.com/junegunn/fzf/assets/59988195/90aa58cc-29fc-4e40-94dd-6858c5869839)

But since `{q}` isn't escaped properly if we try to search for a single `"` , the command fails:
![image](https://github.com/junegunn/fzf/assets/59988195/d1f0f562-e234-4f1d-9674-61bdec6efa8c)

Another use-case where this fails is if we want to silently fail `rg` and never display "Command failed", we could do that by adding `|| break` (similar to `|| true` on UNIX):
```sh
fzf --ansi --disabled --bind="change:reload:rg --line-number --column --color=always {q} || break"
```

Again, if we search for `"` the command will fail:
![image](https://github.com/junegunn/fzf/assets/59988195/c623ce23-a3a4-4103-bd1f-943d152b1a1f)

**Comment by ibhagwan** [comment]
FYI, the last working version is `0.50`, due to the fact the `"` is prefixed with a caret `^`.

Using the below command we fail on purpose so we can look at the escaping sequence:
```sh
fzf --ansi --disabled --bind="change:IF {q}"
```

> `0.52` escape sequence
![image](https://github.com/junegunn/fzf/assets/59988195/4599acb3-d202-449d-a7be-517d508ea625)

> `0.50` escape sequnece
![image](https://github.com/junegunn/fzf/assets/59988195/e2a13cc8-6a85-4f34-a4e2-bfa937553af3)

**Comment by ibhagwan** [comment]
@junegunn, you didn't test my use-case properly, I can see the command you ran in the screenshot:

> **THIS WORKS**
```sh
fzf --disabled --preview-window up --preview "rg --line-number --column --color=always -- {q}"
```

> **BOTH WORK ON `0.50` AND FAIL ON `0.52`**
```sh
fzf --disabled --preview-window up --preview "rg --line-number --column --color=always -- {q} 2>&1"
fzf --disabled --preview-window up --preview "rg --line-number --column --color=always -- {q} || break"
```

The reason I need to add `2&1 || break` is explained in the OP.

**Comment by ibhagwan** [comment]
@junegunn, the current escape sequnce also fails when searching for special characters prefixed by `"`, try:
```sh
fzf --disabled --preview-window up --preview "rg --line-number --column --color=always -- {q}"
```


> Search for `"\|`

![image](https://github.com/junegunn/fzf/assets/59988195/a30dccfb-0989-4a08-90db-de56d8e85e5b)


> Search for `".*&`, the `&` part of the regex is ignored, effectively searching for `".*` only
![image](https://github.com/junegunn/fzf/assets/59988195/c543149a-ebf3-4a3b-a67f-f7dc07e85df3)

> Similarly serching for `"\^` ignores the caret
![image](https://github.com/junegunn/fzf/assets/59988195/30d2f7c5-584c-4995-8ec4-73d81c019903)

> Searching for `"<` or `">`
![image](https://github.com/junegunn/fzf/assets/59988195/8dec9ecc-4a37-45e6-83b5-ee116baca606)

**Comment by junegunn** [comment]
Thanks for the input. Will check again later, for some reason I can't connect to a Windows EC2 instance. 🤷

**Comment by junegunn** [comment]
Thanks for reporting this serious issue. 0.52.1 is an attempt to fix the issue. Please test if it helps. I'm sure there are some other issues lurking, but at least it should be safer than what we had in 0.52.0.

**Comment by ibhagwan** [comment]
@junegunn, everything seems to be in order at first glance, but I think that `;` also needs to be escaped with a caret.

Consider the following which attempts to run `rg` only when the user  inputs a non-empty string (to avoid feeding all project lines unnecessarily):
```cmd
fzf --ansi --disabled --bind="change:reload:IF {q} NEQ \^"^^\" rg --line-number --column --color=always {q}"
```

The condition works fine in all special characters I tested aside from `;`, using `^;` (in the code) solves the issue:
![image](https://github.com/junegunn/fzf/assets/59988195/ccbd557b-b71f-435c-9578-e887904491f3)

I believe `;` should be added to the list of special characters in:
https://github.com/junegunn/fzf/blob/6432f00f0d026c61f683c83ded4d2e15317e927e/src/util/util_windows.go#L24

So that it will later be preceded by `^` in:
https://github.com/junegunn/fzf/blob/6432f00f0d026c61f683c83ded4d2e15317e927e/src/util/util_windows.go#L137-L139

**Comment by junegunn** [comment]
So I guess the problem with `;` is relatively benign compared to the previous flaw, which would allow all kinds of crazy stuff?
Didn't know `;` needed escaping. I'll address it in the next release. But I'm not going to rush it and take some time to hear from other Windows users (https://github.com/junegunn/fzf/issues/3790).

In the meantime, maybe you could work around it by using a batch file and not directly writing conditionals in the binding expression? Just guessing.

**Comment by ibhagwan** [comment]
> So I guess the problem with `;` is relatively benign compared to the previous flaw, which would allow all kinds of crazy stuff? Didn't know `;` needed escaping. I'll address it in the next release. But I'm not going to rush it and take some time to hear from other Windows users (#3790).

I also had no idea `;` was a meta character, definitely no rush in this it’s totally benign.

> In the meantime, maybe you could work around it by using a batch file and not directly writing conditionals in the binding expression? Just guessing.

I already have this handled in the lua wrapper this was just something that was popping up in the `native` versions of the pickers, it’s an edge case of an edge case.

**Comment by junegunn** [comment]
Good to hear that, thanks.
