### ISSUE TITLE
FZF ignores nested files from $FZF_DEFAULT_COMMAND='fd' but not when piping fd into FZF

### ISSUE THREAD

**Issue by 64-bitman** [junegunn/fzf#3796]
### Checklist

- [X] I have read through the manual page (`man fzf`)
- [X] I have searched through the existing issues
- [X] For bug reports, I have checked if the bug is reproducible in the latest version of fzf

### Output of `fzf --version`

0.52.0 (bcda25a5)

### OS

- [X] Linux
- [ ] macOS
- [ ] Windows
- [ ] Etc.

### Shell

- [X] bash
- [ ] zsh
- [ ] fish

### Problem / Steps to reproduce

Download this source archive and extract [test.tar.gz](https://github.com/junegunn/fzf/files/15315219/test.tar.gz)  [test.tar.gz.sig.gz](https://github.com/junegunn/fzf/files/15315370/test.tar.gz.sig.gz)

change directory to src/rxvt-unicode-9.31/

export FZF_DEFAULT_COMMAND=fd and run `fzf`
Enter something like xdefaults.c (located in the src/ directory)
There should be no matches

run `fd | fzf`
Do the same thing above
There should be matches

If you run `fd` alone it should list the files located in the src/ directory, but FZF for some reason ignores those files when using `$FZF_DEFAULT_COMMAND`.

The only thing that fixed this is by deleting .gitignore in the top level folder,
but I couldn't find anything about FZF handling .gitignore in the man page.

**Comment by LangLangBart** [comment]
Not reproducible so far.

When you execute `fd | grep 'xdefaults.C'`, do you see the file?

Please share your `FZF_DEFAULT_OPTS` as well, if set.

**Comment by 64-bitman** [comment]
> Not reproducible so far.
> 
> When you execute `fd | grep 'xdefaults.C'`, do you see the file?
> 
> Please share your `FZF_DEFAULT_OPTS` as well, if set.

`FZF_DEFAULT_OPTS`: `-bind=alt-k:up,alt-j:down,tab:accept,alt-e:abort,ctrl-e:abort,alt-x:cancel,ë:up,ê:down,ø:cancel`

Setting it to nothing doesn't do anything either

**Comment by LangLangBart** [comment]
`fzf` is essentially an interactive `grep` tool, with the search performed solely by `fd`. Since deleting `.gitignore` in the top-level folder resolved the issue, the command below should also reveal the file.

```sh
FZF_DEFAULT_COMMAND="fd --unrestricted" fzf --filter 'xdefaults.C'
# src/xdefaults.C
```

I assume your `.gitignore` contains a line to ignore `.C` files or the entire `src/` folder?
