### ISSUE TITLE
Hang on SIGSTP when session leader

### ISSUE THREAD

**Issue by telychko** [junegunn/fzf#3802]
### Checklist

- [X] I have read through the manual page (`man fzf`)
- [X] I have searched through the existing issues
- [X] For bug reports, I have checked if the bug is reproducible in the latest version of fzf

### Output of `fzf --version`

0.48.1 (9ffe951f)

### OS

- [X] Linux
- [ ] macOS
- [ ] Windows
- [ ] Etc.

### Shell

- [X] bash
- [ ] zsh
- [ ] fish

### Problem / Steps to reproduce

STEPS TO REPRODUCE
1. Run following command (you can use any terminal)
`xterm -e fzf`
2. Hit `ctrl+z`

ACTUAL RESULTS
fzf is disappear and blank terminal window shown. Nothing to do then.

EXPECTED RESULT
No hangs expected. Expected behavior like on nvim or less:
`xterm -e less /etc/fstab`
`xterm -e nvim`

**Comment by junegunn** [comment]
Thanks, it should be fixed now.
