### ISSUE TITLE
Update fedora repository version (Rawhide and Fedora 40)

### ISSUE THREAD

**Issue by egor-denysenko** [junegunn/fzf#3827]
### Checklist

- [X] I have read through the manual page (`man fzf`)
- [X] I have searched through the existing issues
- [ ] For bug reports, I have checked if the bug is reproducible in the latest version of fzf

### Output of `fzf --version`

0.44.1 (Fedora)

### OS

- [X] Linux
- [ ] macOS
- [ ] Windows
- [ ] Etc.

### Shell

- [ ] bash
- [ ] zsh
- [ ] fish

### Problem / Steps to reproduce

Hi, I currently drive FZF on my personal machine, and I'm using Fedora. 

I have noticed from the [fedora packages website](https://packages.fedoraproject.org/) that the current Rawhide and Fedora 40 versions of fzf are quite behide in comparison to the actual releases. Currently, fedora packages has [0.44.1](https://packages.fedoraproject.org/pkgs/fzf/fzf/fedora-rawhide.html) as the latest version, and the latest is [0.52.1](https://github.com/junegunn/fzf/releases/tag/0.52.1);

Is there any way I can help and update the current package version, or is it something that a maintainer can do?

**Comment by junegunn** [comment]
Not sure why the version is so lagging behind. You should probably ask for an update on https://bugzilla.redhat.com/.

With shell integration scripts embedded in the binary (i.e. `--bash`, `--zsh`, and `--fish`), and with native tmux integration and `man` page inclusion in [the upcoming release](https://github.com/junegunn/fzf/pull/3807), it's getting easier to use the latest version of fzf simply by downloading the binary from the releases page and putting in your `$PATH`.

**Comment by egor-denysenko** [comment]
Thanks I didn't know that fedora tracked packages update on bugzilla.

It seems that it's a stale bug from [here](https://bugzilla.redhat.com/show_bug.cgi?id=2256379)

I'm going to try to push it or somehow figure out how to help there.
I specifically pushed for dnf since I didn't want to manage the binary myself but let it be managed by dnf.
I will post some updates if I'm able to figure out something or update the package on the dnf registry.

**Comment by QuLogic** [comment]
These updates are now in testing:
- F40: https://bodhi.fedoraproject.org/updates/FEDORA-2024-9f26b3eb12
- F39: https://bodhi.fedoraproject.org/updates/FEDORA-2024-7d3cf57455

**Comment by egor-denysenko** [comment]
I think that this issue can be closed since these updates got in both F40 and F39 releases https://packages.fedoraproject.org/pkgs/fzf/fzf/ 
Thanks @QuLogic!
