### ISSUE TITLE
Ignore some dirs

### ISSUE THREAD

**Issue by fundon** [junegunn/fzf#383]
How to ignore some dirs? Likes `node_modules` in Node.js project.

**Comment by junegunn** [comment]
Filtering irrelevant entries is not a responsibility of fzf since fzf is just a dumb filter and does not know the context. You can use something like `ag` for that.

See https://github.com/junegunn/fzf#respecting-gitignore-hgignore-and-svnignore

**Comment by jdsimcoe** [comment]
@junegunn Regarding the `.gitignore` settings you mention above... where I do I set/run the commands you list?

```shell
# Feed the output of ag into fzf
ag -g "" | fzf

# Setting ag as the default source for fzf
export FZF_DEFAULT_COMMAND='ag -g ""'

# Now fzf (w/o pipe) will use ag instead of find
fzf

# To apply the command to CTRL-T as well
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
```

**Comment by junegunn** [comment]
@jdsimcoe Set up FZF_DEFAULT_COMMAND in your shell configuration file (e.g. .bashrc, .zshrc, etc.)

**Comment by jdsimcoe** [comment]
@junegunn Did that and it worked. Thanks!

**Comment by Kutsan** [comment]
How not responsible? Is that really hard to implement?

**Comment by samiralajmovic** [comment]
You can also just use :GFiles instead of :Files.

```
nnoremap <c-p> :GFiles<cr>
```

**Comment by Lesik** [comment]
@samiralajmovic Keep in mind that `:GFiles` is not equivalent to setting `$FZF_DEFAULT_COMMAND`. See https://github.com/junegunn/fzf.vim/issues/121#issuecomment-466056060 for more information.

**Comment by tuxsisir** [comment]
install ripgrep with your package manager:
`$ brew install ripgrep`

update your env variable:
export FZF_DEFAULT_COMMAND='rg --files'

had issues with GFiles, worked with it for a while, but everytime the need to add files was a bummer...

**Comment by Lilja** [comment]
I find that `:GFiles` doesn't take into account unchecked files. Does anyone have a solution to that?

**Comment by Lesik** [comment]
@Lilja If with "unchecked files" you mean files not added to git, see the comment 2 above yours.

**Comment by IzaGz** [comment]
I have the following config for fzf in my .vimrc
```
  let g:fzf_nvim_statusline = 0 " disable statusline overwriting

  nnoremap <silent> <leader><space> :Files<CR>
  nnoremap <silent> <leader>a :Buffers<CR>
  nnoremap <silent> <leader>A :Windows<CR>
  nnoremap <silent> <leader>; :BLines<CR>
  nnoremap <silent> <leader>o :BTags<CR>
  nnoremap <silent> <leader>O :Tags<CR>
  nnoremap <silent> <leader>? :History<CR>
  nnoremap <silent> <leader>/ :execute 'Ag ' . input('Ag/')<CR>
  nnoremap <silent> <leader>. :AgIn 

  nnoremap <silent> K :call SearchWordWithAg()<CR>
  vnoremap <silent> K :call SearchVisualSelectionWithAg()<CR>
  nnoremap <silent> <leader>gl :Commits<CR>
  nnoremap <silent> <leader>ga :BCommits<CR>
  nnoremap <silent> <leader>ft :Filetypes<CR>

  " https://vi.stackexchange.com/questions/31012/what-does-plug-do-in-vim
  imap <C-x><C-f> <plug>(fzf-complete-file-ag)
  imap <C-x><C-l> <plug>(fzf-complete-line)
  imap <C-x><C-w> <plug>(fzf-complete-word)

  function! SearchWordWithAg()
    execute 'Ag' expand('<cword>')
  endfunction

  function! SearchVisualSelectionWithAg() range
    let old_reg = getreg('"')
    let old_regtype = getregtype('"')
    let old_clipboard = &clipboard
    set clipboard&
    normal! ""gvy
    let selection = getreg('"')
    call setreg('"', old_reg, old_regtype)
    let &clipboard = old_clipboard
    execute 'Ag' selection
  endfunction

  function! SearchWithAgInDirectory(...)
    call fzf#vim#ag(join(a:000[1:], ' '), extend({'dir': a:1}, g:fzf#vim#default_layout))
  endfunction
  command! -nargs=+ -complete=dir AgIn call SearchWithAgInDirectory(<f-args>)

```

how should i fix this to ignore the `node_modules` and `dist`, `build` folders every time i am doing search with for example this command
`  nnoremap <silent> <leader>/ :execute 'Ag ' . input('Ag/')<CR>` ?
