### ISSUE TITLE
Can't bind C-z to a readline function without getting 'readline: maximum macro execution nesting level exceeded' with fzf-cd - Alt-C

### ISSUE THREAD

**Issue by excited-bore** [junegunn/fzf#3838]
### Checklist

- [X] I have read through the manual page (`man fzf`)
- [X] I have searched through the existing issues
- [X] For bug reports, I have checked if the bug is reproducible in the latest version of fzf

### Output of `fzf --version`

0.52.1 (6432f00)

### OS

- [X] Linux
- [ ] macOS
- [ ] Windows
- [ ] Etc.

### Shell

- [X] bash
- [ ] zsh
- [ ] fish

### Problem / Steps to reproduce

```
bind -m emacs-standard  '"\C-z": vi-undo'
bind -m vi-command      '"\C-z": vi-undo'
bind -m vi-insert       '"\C-z": vi-undo'
```
<Alt-C>

```
$: readline: maximum macro execution nesting level exceeded
```

This only seems to happen with readline functions for whatever reason. 
'bind -x '"\C-z": exit' works without a hitch

**Comment by excited-bore** [comment]
Upon further inspection it seems like it had something to do with the order that i sourced my ~/.bashrc files more then an fzf bug.

First readline (bind) keybinds, then fzf, then 'complete -F _complete_alias "${!BASH_ALIASES[@]}"' 

Closing

**Comment by junegunn** [comment]
Can't reproduce.

```sh
bash --noprofile --rcfile <(fzf --bash)

bind -m emacs-standard  '"\C-z": vi-undo'
bind -m vi-command      '"\C-z": vi-undo'
bind -m vi-insert       '"\C-z": vi-undo'
```

**Comment by excited-bore** [comment]
After some more testing it I found out there was another line related to this.

Setting
```
# Unset suspend signal shortcut (Ctrl+z)
stty susp undef

bind -m emacs-standard  '"\C-z": vi-undo'
bind -m vi-command      '"\C-z": vi-undo'
bind -m vi-insert       '"\C-z": vi-undo'

[ -f ~/.fzf.bash ] && source ~/.fzf.bash
```
gives me `'readline: maximum macro execution nesting level exceeded'` when using Alt-C.
These go away when I remove the line `stty susp undef`, but vi-undo stops working afterwards.

**Comment by excited-bore** [comment]
I forgot a relevant line. Also set this in your .bashrc (bash --noprofile --rcfile <(fzf --bash) isn't completely similar):
```
[ -f ~/.fzf.bash ] && source ~/.fzf.bash

# Unset suspend signal shortcut (Ctrl+z)
stty susp undef

bind -m emacs-standard  '"\C-z": vi-undo'
bind -m vi-command      '"\C-z": vi-undo'
bind -m vi-insert       '"\C-z": vi-undo' 
```
in your .bashrc gives the 'readline: maximum macro execution nesting level exceeded' when using Alt-C

Sourcing `[ -f ~/.fzf.bash ] && source ~/.fzf.bash` after these lines will fix this *mostly*
```
# Unset suspend signal shortcut (Ctrl+z)
stty susp undef

bind -m emacs-standard  '"\C-z": vi-undo'
bind -m vi-command      '"\C-z": vi-undo'
bind -m vi-insert       '"\C-z": vi-undo' 

[ -f ~/.fzf.bash ] && source ~/.fzf.bash
```
Now Alt-C works, but Ctrl-z will now be bound to changing editing-modes (vi/emacs).
Removing `stty susp undef` stops this behaviour but also breaks `vi-undo

**Comment by sebastiancarlos** [comment]
I'm having the exact same issue.

**Comment by excited-bore** [comment]
I've been trying to find a fix for this every so often and I finally understand where I went wrong which looking back, I really should've noticed sooner.
 
Now I understand that when installing fzf by cloning the repo to ```~/.fzf```  and running  ```~/.fzf/install``` it generates ```~/.fzf.bash``` for bash but instead of putting a line in the file that sources ```~/.fzf/shell/key-binding.bash``` (which is what I was constantly modifying) to setup keybindings, it generates preconfigured keybindings/completions on the fly using ```eval "$(fzf --bash)"```

So in order to unbind **'Ctrl-z'** wich the fzf binds to switching from and back **vi and emacs** mode, the best course of action is the choose a 'Ctrl+<key>' binding (because vi-mode doesn't support all _modifier keys_, like 'Alt+<key>' ) that isn't already used/relatively useless. 
I choose **'Ctrl-o'** to replace **Ctrl-z** with since at default its bound to execute commands from (search)/(reverse-search) ([Link](https://ss64.com/bash/syntax-keyboard.html)) which doesn't matter anylonger since those are already replaced '__fzf_history__ '.

```bash
~/.fzf.bash

#eval "$(fzf --bash)"
source ~/.fzf/shell/key-bindings.bash 


~/.fzf/shell/keybindings.bash

# Required to refresh the prompt after fzf
bind -m emacs-standard '"\er": redraw-current-line'

bind -m vi-command '"\C-o": emacs-editing-mode'
bind -m vi-insert '"\C-o": emacs-editing-mode'
bind -m emacs-standard '"\C-o": vi-editing-mode'

if (( BASH_VERSINFO[0] < 4 )); then
  # CTRL-T - Paste the selected file path into the command line
  if [[ "${FZF_CTRL_T_COMMAND-x}" != "" ]]; then
    bind -m emacs-standard '"\C-t": " \C-b\C-k \C-u`__fzf_select__`\e\C-e\er\C-a\C-y\C-h\C-e\e \C-y\ey\C-x\C-x\C-f"'
    bind -m vi-command '"\C-t": "\C-o\C-t\C-o"'
    bind -m vi-insert '"\C-t": "\C-o\C-t\C-o"'
  fi

  # CTRL-R - Paste the selected command from history into the command line
  bind -m emacs-standard '"\C-r": "\C-e \C-u\C-y\ey\C-u`__fzf_history__`\e\C-e\er"'
  bind -m vi-command '"\C-r": "\C-o\C-r\C-o"'
  bind -m vi-insert '"\C-r": "\C-o\C-r\C-o"'
else
  # CTRL-T - Paste the selected file path into the command line
  if [[ "${FZF_CTRL_T_COMMAND-x}" != "" ]]; then
    bind -m emacs-standard -x '"\C-t": fzf-file-widget'
    bind -m vi-command -x '"\C-t": fzf-file-widget'
    bind -m vi-insert -x '"\C-t": fzf-file-widget'
  fi

  # CTRL-R - Paste the selected command from history into the command line
  bind -m emacs-standard -x '"\C-r": __fzf_history__'
  bind -m vi-command -x '"\C-r": __fzf_history__'
  bind -m vi-insert -x '"\C-r": __fzf_history__'
fi

# ALT-C - cd into the selected directory
if [[ "${FZF_ALT_C_COMMAND-x}" != "" ]]; then
  bind -m emacs-standard '"\ec": " \C-b\C-k \C-u`__fzf_cd__`\e\C-e\er\C-m\C-y\C-h\e \C-y\ey\C-x\C-x\C-d"'
  bind -m vi-command '"\ec": "\C-o\ec\C-o"'
  bind -m vi-insert '"\ec": "\C-o\ec\C-o"'
fi

fi
```
or for a quick sed edit

```bash
sed -i 's|^eval "$(fzf --bash)"|#eval "$(fzf --bash)"|g' ~/.fzf.bash 
echo 'source ~/.fzf/shell/key-bindings.bash' >> ~/.fzf.bash
sed -i 's|\\C-z|\\C-o|g' ~/.fzf/shell/key-bindings.bash
````
