### ISSUE TITLE
How to find file from zoxide result ?

### ISSUE THREAD

**Issue by soluty** [junegunn/fzf#3840]
### Checklist

- [X] I have read through the manual page (`man fzf`)
- [X] I have searched through the existing issues
- [ ] For bug reports, I have checked if the bug is reproducible in the latest version of fzf

### Output of `fzf --version`

0.50.0 (f97d275)

### OS

- [ ] Linux
- [ ] macOS
- [X] Windows
- [ ] Etc.

### Shell

- [X] bash
- [ ] zsh
- [ ] fish

### Problem / Steps to reproduce

I want to interactively  find  a dir,  then in that dir ,  i want find  interactively  find file by fzf,   so i use this script
```zoxide query -l | fzf --no-sort -m | xargs find | fzf```
then fzf stucked,   how can i do double interactive find?  find a dir or multi dir, then use that dirs to find some files?

**Comment by junegunn** [comment]
Add `--sync` to the second fzf.
