### ISSUE TITLE
last commit broke fzf.vim integration

### ISSUE THREAD

**Issue by drzhivago420** [junegunn/fzf#3842]
### Checklist

- [X] I have read through the manual page (`man fzf`)
- [X] I have searched through the existing issues
- [x] For bug reports, I have checked if the bug is reproducible in the latest version of fzf

### Output of `fzf --version`

0.29 (devel)

### OS

- [X] Linux
- [ ] macOS
- [ ] Windows
- [ ] Etc.

### Shell

- [X] bash
- [ ] zsh
- [ ] fish

### Problem / Steps to reproduce

Was updating my work machine plugins and noticed fzf stopped working. Checked my home machine and same thing after updating.

BREAKS ON:
"fzf": { "branch": "master", "commit": "590060a16b85270c19c605e8758cda16c4517086" },

WORKS AFTER REVERTING TO:
fzf": { "branch": "master", "commit": "124cd70710cb7c94ef2282773494bb0d727598d8" },

![fzf](https://github.com/junegunn/fzf/assets/110633694/9650222d-145f-40c6-9bbe-d08b7a0ec831)

**Comment by junegunn** [comment]
> 0.29 (devel)

You should upgrade your fzf binary. `:call fzf#install()` will do.
