### ISSUE TITLE
code **<TAB> doesn't execute fzf

### ISSUE THREAD

**Issue by griiid** [junegunn/fzf#3843]
### Checklist

- [X] I have read through the manual page (`man fzf`)
- [X] I have searched through the existing issues
- [X] For bug reports, I have checked if the bug is reproducible in the latest version of fzf

### Output of `fzf --version`

0.53.0 (brew)

### OS

- [ ] Linux
- [X] macOS
- [ ] Windows
- [ ] Etc.

### Shell

- [X] bash
- [ ] zsh
- [ ] fish

### Problem / Steps to reproduce

Type `code **` and then press `<TAB>`, it doesn't execute fzf?
The result is: `code \*\*`

How can I check what's the problem?

**Comment by junegunn** [comment]
https://github.com/junegunn/fzf?tab=readme-ov-file#supported-commands should answer your question.

We may add `code` to the default list in the future.

**Comment by griiid** [comment]
Sorry, but I don't know how to show all directories like when I type `cd **<TAB>`

I don't know what should I put in `<()`

Here's my .bashrc settings:

```sh
_fzf_complete_code() {
  _fzf_complete --multi --reverse --prompt="code> " -- "$@" < <(
  )
}
[ -n "$BASH" ] && complete -F _fzf_complete_code -o default -o bashdefault code
```

**Comment by junegunn** [comment]
I was suggesting that you just add `_fzf_setup_completion path code` to your .bashrc.

But we may add `code` to the list of the commands for which fuzzy completion is enabled by default so that is no longer necessary.

**Comment by griiid** [comment]
@junegunn oh, I see, thank you!!

**Comment by thyeun** [comment]
May i know how should i using ```cd **<tab>``` in fish shell?
