### ISSUE TITLE
Inconsistent `kill -9` completion behaviour

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [junegunn/fzf#385]
Why are `unset`, `export`, `unalias`, `ssh`, `telnet`, and `cd` all configured to do special-case completion on the otherwise-general `**` suffix … but `kill` is configured to complete on a simple `⇥`, without any `**`? Is there a rationale behind this, or was it an accident?

**Comment by junegunn** [comment]
Both, I guess. I initially thought that I was never going to use the default shell completion for kill command, so I made the decision which I kind of regret now. But I haven't tried to rectify the inconsistency not to break backward compatibility. Note that kill completion still uses the default completion if there's prefix (e.g. `kill -9 $(cat <TAB>`), so it's probably okay in most situations, but I should probably make it consistent with the other ones.

**Comment by ELLIOTTCABLE** [comment]
Glad to hear you're aware. It doesn't bother me at all; if you need to keep it for backwards-compat, that's fine.

**Comment by bag-man** [comment]
I was going to raise this as a question too. Luckily it is pretty trivial to get the same behaviour for ssh as it is with kill. It makes sense to me to not have to ad the ** to get the auto completion. I would definitely +1 for making this the default behaviour. 

```
_fzf_complete_ssh() {
  fzf="$(__fzfcmd_complete)"
  cat <(cat ~/.ssh/config /etc/ssh/ssh_config 2> /dev/null | command grep -i '^host' | command grep -v '*') \
      <(command grep -oE '^[a-z0-9.,-]+' ~/.ssh/known_hosts | tr ',' '\n' | awk '{ print $1 " " $1 }') \
      <(command grep -v '^\s*\(#\|$\)' /etc/hosts | command grep -Fv '0.0.0.0') |
      awk '{if (length($2) > 0) {print $2}}' | sort -u | $fzf
}
```

**Comment by allixsenos** [comment]
this is as easy as adding this in your bashrc after `source ~/.fzf.bash`

```
_fzf_complete_ssh_notrigger() {
    FZF_COMPLETION_TRIGGER='' _fzf_complete_ssh
}

complete -o bashdefault -o default -F _fzf_complete_ssh_notrigger ssh
complete -o bashdefault -o default -F _fzf_complete_ssh_notrigger mosh
complete -o bashdefault -o default -F _fzf_complete_ssh_notrigger my_ssh_like_command
```

**Comment by lanza** [comment]
Any idea how to get the notrigger variant to work in zsh?

**Comment by pasteley** [comment]
> Any idea how to get the notrigger variant to work in zsh?
`compdef _fzf_complete_ssh_notrigger ssh scp sftp mosh rsync`

**Comment by carlosedp** [comment]
@junegunn any idea on how to do same behavior on Zsh?
Thanks!
