### ISSUE TITLE
Merge fish history before showing history widget

### ISSUE THREAD

**Issue by ismay** [junegunn/fzf#3851]
### Checklist

- [X] I have read through the manual page (`man fzf`)
- [X] I have searched through the existing issues
- [X] For bug reports, I have checked if the bug is reproducible in the latest version of fzf

### Output of `fzf --version`

0.52.1

### OS

- [X] Linux
- [ ] macOS
- [ ] Windows
- [ ] Etc.

### Shell

- [ ] bash
- [ ] zsh
- [X] fish

### Problem / Steps to reproduce

In this function: https://github.com/junegunn/fzf/blob/master/shell/key-bindings.fish#L59-L86 we're currently only showing the changes from the current session. If we call `history merge` beforehand commands from other sessions will be available as well.

Docs on `history merge`:

> Immediately incorporates history changes from other sessions. Ordinarily fish ignores history changes from sessions started after the current one. This command applies those changes immediately.

from: https://fishshell.com/docs/current/cmds/history.html

We could do it similar to this widely used plugin: [PatrickF1/fzf.fish](https://github.com/PatrickF1/fzf.fish/blob/main/functions/_fzf_search_history.fish#L4-L6), which also incorporates a check for private mode.

**Comment by junegunn** [comment]
Sounds good. Are you interested in opening a pull request?

**Comment by adamsb6** [comment]
Would you entertain a PR to make this configurable? This is leading to lots of confusion for me, I typically have dozens of sessions open and I expect that when I arrow up in one of them, or search, I get the most recent for that session unless I've explicitly merged history.

It's especially pernicious when the command is super long and one arg is just slightly different, I'll end up breezing past it.

**Comment by junegunn** [comment]
Looks like you can set `$fish_private_mode`. See  https://github.com/junegunn/fzf/pull/3852/files

**Comment by adamsb6** [comment]
I thought so at first, but that variable will cause zero history to be
written. I still want my history, I just don’t want it merged with every
fzf invocation.
