### ISSUE TITLE
Cannot exclude symbolic links from search

### ISSUE THREAD

**Issue by rudvfaden** [junegunn/fzf#3857]
### Checklist

- [X] I have read through the manual page (`man fzf`)
- [X] I have searched through the existing issues
- [X] For bug reports, I have checked if the bug is reproducible in the latest version of fzf

### Output of `fzf --version`

0.53.0 (c4a9ccd)

### OS

- [X] Linux
- [ ] macOS
- [ ] Windows
- [ ] Etc.

### Shell

- [ ] bash
- [X] zsh
- [ ] fish

### Problem / Steps to reproduce

fzf still seems to follow symbolic links. I have several links to large folders that are searched. 

I also tried to add the folders to --walker-skip, but that still does not work.

**Comment by junegunn** [comment]
> fzf still seems to follow symbolic links.

Yes, that's the default.

```
   Directory traversal
       --walker=[file][,dir][,follow][,hidden]
              Determines the behavior of the built-in directory walker that is used when
              $FZF_DEFAULT_COMMAND is not set. The default value is file,follow,hidden.

              * file: Include files in the search result
              * dir: Include directories in the search result
              * hidden: Include and follow hidden directories
              * follow: Follow symbolic links
```

>I also tried to add the folders to --walker-skip, but that still does not work.

And please provide the exact steps to reproduce the problem.

**Comment by rudvfaden** [comment]
Thanks for a very quick reply.

I add this to .zhsrc

```
export FZF_CTRL_T_OPTS="
  --walker-skip .git,node_modules,target,o_drev_da1943,analyse,batch,Dataudveksling,eg_source
  --preview 'bat -n --color=always {}'
  --bind 'ctrl-/:change-preview-window(down|hidden|)'"
```

When i pres CTRL + T i still get results for e.g. analyse in my results. the folder `analyse` is a symbolig link.

**Comment by junegunn** [comment]
Do you also have `FZF_CTRL_T_COMMAND`? If the variable is defined, fzf will use it instead of its built-in walker.

**Comment by rudvfaden** [comment]
Ahh. Thanks. Now it works.

Can you apply --walker skip to FZF_DEFAULT_COMMAND so that it works an all fzf commands?

I tried  `export FZF_DEFAULT_OPTS="--walker-skip .git,node_modules,target,o_drev_da1943,analyse,batch,Dataudveksling,eg_source` but that does not seem to work.
Sorry for asking, but I could not find anythin in th

**Comment by junegunn** [comment]
Okay, I can see what's going on. `--walker-skip` is applied to directories, and currently, it is not applied to a "symlink" to a directory. I agree that this is confusing. I'll look into it.

Anyway, if you don't want fzf to follow symlinks, consider setting `--walker` instead of `--walker-skip`.

```sh
export FZF_DEFAULT_OPTS='--walker file,hidden
```

**Comment by rudvfaden** [comment]
So that `file` is a list of folders that should be included? Think that will be hard to maintian. 

But thanks for your reply. Cool if it can be implemented in a comming release.

**Comment by junegunn** [comment]
> Directory traversal
>        --walker=[file][,dir][,follow][,hidden]
>               Determines the behavior of the built-in directory walker that is used when
>               $FZF_DEFAULT_COMMAND is not set. The default value is file,follow,hidden.
> 
>               * file: Include files in the search result
>               * dir: Include directories in the search result
>               * hidden: Include and follow hidden directories
>               * follow: Follow symbolic links

**Comment by rudvfaden** [comment]
So If I set it to file,dir,hidden it will not follow symbolic links?

**Comment by junegunn** [comment]
Correct.

**Comment by Sanatani-Dhruv** [comment]
See What I Want is Follow Symlinks, How to do that?

Like I Have Folder `~/Desktop/B-Tech CSE/`
but `B-Tech CSE` is Symlink of 
`/media/username/New Volume/B-TECH CSE`

Now When in Home I try to navigate to B-Tech CSE i can't,

is there some thing i can do
