### ISSUE TITLE
Double-star bug in bash

### ISSUE THREAD

**Issue by tom-adsfund** [junegunn/fzf#386]
(Ubuntu, Bash)

xdg-open dir/**<tab>

Doesn't go into fzf and instead completes first file name in directory.

**Comment by junegunn** [comment]
Unfortunately due to the limitation of bash completion, the list of supported commands is hard-coded.

https://github.com/junegunn/fzf/blob/0.10.8/shell/completion.bash#L241-L252

I'll consider adding `xdg-open` to the list. In the mean time, you can add something like this to your bashrc.

```sh
# there are also _fzf_path_completion and _fzf_dir_completion
complete -F _fzf_file_completion -o default -o bashdefault xdg-open
```

**Comment by tom-adsfund** [comment]
OK, thanks for the info. And great tool! I've been hoping for something just like this for a long time. Thanks very much.
