### ISSUE TITLE
 make CTRL-T work with directories outside the current one

### ISSUE THREAD

**Issue by backpropper** [junegunn/fzf#3860]
### Checklist

- [X] I have read through the manual page (`man fzf`)
- [X] I have searched through the existing issues
- [x] For bug reports, I have checked if the bug is reproducible in the latest version of fzf

### Output of `fzf --version`

0.52.1

### OS

- [ ] Linux
- [X] macOS
- [ ] Windows
- [ ] Etc.

### Shell

- [ ] bash
- [X] zsh
- [ ] fish

### Problem / Steps to reproduce

Let's assume I am in directory /dirA. There is also a /dirB.

Very often there are case where I want to use FZF's CTRL-T to search relative to dirB although I am currently inside dirA.

For example,

cd /dirA
...
cd /dirB
<CTRL-T>
(search for /dirA/foo/)
How on earth can I achieve that?

My CTRL-T is set to toggling with single key as described [here](https://github.com/junegunn/fzf/blob/master/ADVANCED.md#toggling-with-a-single-key-binding).

P.S.: I'm able to search for Files outside of dirB here but not directories.

**Comment by LangLangBart** [comment]
I assume you're relying on `fd` to list entries in `fzf`. Did you experiment with the `--search-path` flag in `fd`?

```sh
print -D $PWD
# ~/Developer/fzf/bin

fd --search-path ../doc --search-path .
./fzf-preview.sh
./fzf-tmux
../doc/fzf.txt
```

Combined with the `reload` action, you should be able to accomplish your goal.

```sh
fzf --bind 'ctrl-b:reload:fd --search-path ../doc --search-path .'
```

**Comment by junegunn** [comment]
I suggest that you use fuzzy completion instead for that purpose.

```sh
vim /dirA/**<TAB>
```

See https://github.com/junegunn/fzf?tab=readme-ov-file#fuzzy-completion-for-bash-and-zsh

Since you're using zsh, also see https://github.com/junegunn/fzf/wiki/Configuring-fuzzy-completion#dedicated-completion-key

**Comment by backpropper** [comment]
Yes, I've tried the above setting. Your suggestion requires one to exit fzf -> then reopen it with dirA which is my current workflow anyway. I was wondering if it is possible to achieve this without leaving fzf in the first place.

**Comment by Bellavene** [comment]
Yeah, I am also curious. I want CTRL-T to navigate folders within itself, this makes common sense, no need to perform additional actions. And CTRL-T could replace file managers at all for me then.

**Comment by mieubrisse** [comment]
@Bellavene does this actually work? I've been trying to use `become(cd {})`, but it's not doing anything (I think because the `cd` is running in a subprocess)

**Comment by Bellavene** [comment]
@mieubrisse 

https://github.com/user-attachments/assets/870b9a8b-a998-4037-9b21-96254ce71f82
