### ISSUE TITLE
Feature request: Ability to display current line position and matched item count in fzf info

### ISSUE THREAD

**Issue by LangLangBart** [junegunn/fzf#3866]
### Checklist

- [X] I have read through the manual page (`man fzf`)
- [X] I have searched through the existing issues
- [X] For bug reports, I have checked if the bug is reproducible in the latest version of fzf

### Output of `fzf --version`

0.53.0 (brew)

### OS

- [ ] Linux
- [X] macOS
- [ ] Windows
- [ ] Etc.

### Shell

- [ ] bash
- [X] zsh
- [ ] fish

### Intro

Currently, the **info** looks like in the image below, displaying the matched count and the total count, as well as the number of selections in multi mode.

<img src="https://github.com/junegunn/fzf/assets/92653266/18eb9d2b-e592-49b4-9ea1-4bad4b269a69" width="250">
---

### Feature Description

Ability to display the current line position and the number of matched items.

The request can be _hacked_ together with the current flags by using the `--border` or the `--header` to display the desired infos.

```sh
FZF_DEFAULT_COMMAND= FZF_DEFAULT_OPTS="" fzf \
  --bind 'result:transform-border-label:echo "[$FZF_POS/$FZF_MATCH_COUNT] ($FZF_SELECT_COUNT)"' \
  --bind 'focus:transform-border-label:echo "[$FZF_POS/$FZF_MATCH_COUNT] ($FZF_SELECT_COUNT)"' \
  --border-label-pos 3 \
  --border bottom \
  --multi \
  --no-info \
  --no-separator \
  --prompt 'Filter: '
```

<img src="https://github.com/junegunn/fzf/assets/92653266/a1e86409-fdd2-4a3d-934c-2eb75a8086e0" width="250">

> [!NOTE]
> The above image is just to better illustrate the request and not a good solution, as the _matched_ count doesn't incrementally update itself in batches in the same way as the current **info** does on large inputs.
> 
> <img src="https://github.com/junegunn/fzf/assets/92653266/a2e941c6-5a17-46e6-a7f9-09ad5578254d" width="250">

The name of the flag could be `--info2=STYLE`. 

### Related

Projects which inspired this request.

- https://github.com/zsh-users/zaw

<img src="https://github.com/junegunn/fzf/assets/92653266/368a9672-843b-49b0-9765-35969f655d01" width="250">

- https://github.com/zdharma-continuum/history-search-multi-word

<img src="https://github.com/junegunn/fzf/assets/92653266/07d17b01-6831-4380-a6a0-f64c87a99486" width="400">

**Comment by junegunn** [comment]
> _matched_ count doesn't incrementally update itself in batches in the same way as the current **info** does on large inputs.

This made me realize that we're not firing `result` event if the input stream is not complete. 

https://github.com/junegunn/fzf/blob/ed12925f7dbceaedae58b2e202f1b1f443b04ab5/src/terminal.go#L1241-L1259

But there's no reason that it should be this way. I can't remember why I made that decision. Maybe I was worried about ending up with too many events? Maybe it was just an oversight.



> The name of the flag could be `--info2=STYLE`.

While I agree that an alternative representation is desirable in some cases, we should think through how to implement it and
not rush into a decision.

Something like `--info-format="#{match_count}/#{total_count} #{sort} #{track} [#{multi}] (#{progress})"` (similar to git format and tmux format) would give the maximum flexibility, but obviously, it isn't simple to get it right.

e.g. How to hide surrounding parentheses and brackets when the inner element evaluates to an empty string? We don't want to see `()` or `[]`. And how to handle multiple spaces around empty element, etc.

**Comment by LangLangBart** [comment]
> junegunn added the feature label yesterday

Thanks for considering this a feature.

> How to hide surrounding parentheses and brackets when the inner element evaluates to an empty string?

So, some kind of conditional syntax would be needed? Below are some syntax examples  for conditionals:

#### zsh: ternary expression
In `zsh`, the syntax for a conditional string would be `%(x.true-text.false-text)`. For example:
```bash
# Display a different string based on whether the hour is six
print -Pr -- "%(6T.Breakfast is ready.No Breakfast)"
# Print a Thumbs Up emoji or a Cross Mark emoji based on the exit status of the last command
print -Pr -- "%(?.👍.❌)"
```

#### go: if…end
Or maybe `go`[^1] templates, but the syntax is a bit more uncommon, because of the double curly braces. The `gh` tool has a `--template` flag that allows writing `go` templates, for example, to show me the `stargazers_count` of a repo only when it is not `private`.


```sh
gh api repos/junegunn/fzf \
  --template '{{ if not .private }}Stars: {{ .stargazers_count }}{{ end }}'
```

---

But a state for multi mode would be needed to check if it is enabled or not. However, the longer and more complex it becomes to write, the less likely anyone will actually use it. What do you think about some kind of conditional syntax for strings?




[^1]: [template package - text/template - Go Packages](https://pkg.go.dev/text/template)

**Comment by junegunn** [comment]
On second thought, I'm afraid we would end up with a very complex solution for little demand. Shelling out seems like the most practical solution for now. Now that the `result` event is fixed, one can use `transform-border-label` or `transform-header` to display more information on screen, but yeah, it's not an exact substitute for the `info` panel.

How about adding something like `--info-command='echo "[$FZF_POS/$FZF_MATCH_COUNT] ($FZF_SELECT_COUNT)"'`, and exposing more information? An alternative would be `transform-info` action. In either way, we can pass the default info line as `$FZF_INFO` so that the user can extract information from it.

**Comment by LangLangBart** [comment]
> How about adding something like `--info-command='echo "[$FZF_POS/$FZF_MATCH_COUNT] ($FZF_SELECT_COUNT)"'`

It would allow for customizing the info, and the syntax is predictable and easy to use. I like it.

**Comment by junegunn** [comment]
Added `--info-command`. It supports ANSI color codes in the output and `$FZF_INFO` is exported to the command. I've tested it with all info layouts (default, inline, right, inline-right) and everything seems to work as expected. Please test it and let me know if there's a problem.

**Comment by LangLangBart** [comment]
> everything seems to work as expected.

Works well. Thank you for your effort in implementing it.

It allows for some custom info commands, as described in the issue, and even some less common ones, such as transforming numbers into Roman numerals.

<img src="https://github.com/junegunn/fzf/assets/92653266/7b1db224-11cb-4d53-ae0b-9152c27f21ad" width="800">

---

> Please test it 

Should there be an additional sentence in the `man` page under the `--info-command` option? This sentence could direct the user to another section containing a list of variables. For instance:

```md
For additional environment variables available to the command, see the section ENVIRONMENT VARIABLES EXPORTED TO CHILD PROCESSES.
```

If a user hasn't read the `man` page and assigns a loop to it, the typical <kbd>⌃ Control</kbd> + <kbd>C</kbd> keybind has no effect to cancel it. One has to close the tab. An issue or user fault ?

```sh
fzf --info-command='while : ;do echo "Time: $(date +%H:%M:%S), Matches: $FZF_MATCH_COUNT"; sleep 1;done'
```

**Comment by junegunn** [comment]
> the typical ⌃ Control + C keybind has no effect to cancel it.

All transform actions have the same problem. To allow CTRL-C, we should restore the terminal state to receive user input, but immediately doing so would cause unwanted artifacts to be rendered on screen during the execution. For example, if you hold down CTRL-K or up arrow during a transform action, you would see:

```sh
> ^K^K^K^[[A^[[A^[[A
```

One idea is to receive user input when a certain amount of time has elapsed, e.g. 1 second, assuming that most transform commands finish within the period.
