### ISSUE TITLE
Switching to a dir outside of current dir with ALT-C

### ISSUE THREAD

**Issue by backpropper** [junegunn/fzf#3868]
### Checklist

- [X] I have read through the manual page (`man fzf`)
- [X] I have searched through the existing issues
- [X] For bug reports, I have checked if the bug is reproducible in the latest version of fzf

### Output of `fzf --version`

0.52.1

### OS

- [ ] Linux
- [X] macOS
- [ ] Windows
- [ ] Etc.

### Shell

- [ ] bash
- [X] zsh
- [ ] fish

### Problem / Steps to reproduce

I'm trying to navigate the file system with ALT-C. I would like to switch to a dir outside of the scope of the current dir using this shortcut. In particular, I want to modify the ALT-C FZF command to something like `fd --type directory --follow --hidden --color=always --exclude '.git' . $HOME` and combine it with `__fzf_cd__`. Can you please guide me on who to achieve this? Thanks a lot!

**Comment by junegunn** [comment]
What have you tried? What did and didn't work? Have you tried reading through [ADVANCED.md](https://github.com/junegunn/fzf/blob/master/ADVANCED.md) to learn how to script with fzf?

**Comment by backpropper** [comment]
I fixed it by specifying the options `--walker-root $HOME` in `FZF_ALT_C_OPTS`.

I wanted to ask if there is any plan to support the feature request mentioned in #3597 I'm trying to build the exact same functionality on my end but have to rely on `CTRL-T` for opening files and `ALT-C` for switching directories.

**Comment by junegunn** [comment]
No, I'm not interested in doing that. I'd like to focus on improving fzf itself. Such additional functionality can be provided by third-party projects.
