### ISSUE TITLE
Large input with `--tac` option

### ISSUE THREAD

**Issue by Komosa** [junegunn/fzf#387]
Hi,
I just decided to finally start using fuzzy finders, so far, it seems cool for me, especially with yor fzf :+1: 

But I hit following issue with `--tac` switch:
when searching through resonably big input (eg 200k+ lines) with --tac option, some time at begining is 'wasted' for constantly refreshing terminal window (actually I can typing query during this, but it is quite distracting).
The problem (obviously) don't appear without tac.
I also use `--cycle --no-sort` during my experiments.

My scenario was to search through all lines in source files.
What I would expect to see instead is static preview of some (even random) block of lines.
What do you think about it?

**Comment by junegunn** [comment]
`fzf --tac --sync` can be helpful if the input stream finishes quickly.

**Comment by junegunn** [comment]
Other than that, it's a matter of how you prepare the input (no `--tac`).

**Comment by Komosa** [comment]
Actually i use `ack .` to just print all lines of all files recursively.

**Comment by junegunn** [comment]
Anyway, it's not something fzf can do for you. You'll have to write a script that prepares the input.

```sh
(foo; bar | tac) | fzf
```

**Comment by Komosa** [comment]
Unfortunately, in the way you described, I can't do anything until all data is prepared...

**Comment by junegunn** [comment]
I see, but I'm not sure you want to use `--tac` for that command. If the bottom-up layout is the issue you can consider using `--reverse`.

> What I would expect to see instead is static preview of some (even random) block of lines.

This is a very vague description of the desired behavior that I can't consider adding to fzf. I don't think there's any filter that does something like that.

**Comment by Komosa** [comment]
Thanks!
Reverse looks great. Can I additionaly move prompt to the bottom?

**Comment by junegunn** [comment]
No, it's not supported. Simply moving the cursor to the bottom will make a huge blank space in the center of the screen as you narrow down the list and I don't like it. We could try to pull down the result but it's more complex to implement and may not look very natural, so I'm not thinking of implementing it.

**Comment by Komosa** [comment]
Your other suggestion seems good, (and natural for me). I will try to implement it and maybe sent pull request.
