### ISSUE TITLE
Using bind with an echo output, the variable assignment no longer works

### ISSUE THREAD

**Issue by cmaahs** [junegunn/fzf#3872]
### Checklist

- [X] I have read through the manual page (`man fzf`)
- [X] I have searched through the existing issues
- [X] For bug reports, I have checked if the bug is reproducible in the latest version of fzf

### Output of `fzf --version`

0.53.0 (brew)

### OS

- [ ] Linux
- [X] macOS
- [ ] Windows
- [ ] Etc.

### Shell

- [ ] bash
- [X] zsh
- [ ] fish

### Problem / Steps to reproduce

With version 0.53.0 this is the behavior I am experiencing:

% KUBE_CLUSTER=$(echo "HEADER\n------\ncluster1\ncluster2" | fzf --header-lines=2 --bind 'enter:execute(echo {+1})+abort'); echo "\n~${KUBE_CLUSTER}~\n"
cluster1

~~

% KUBE_CLUSTER=$(echo "HEADER\n------\ncluster1\ncluster2" | fzf --header-lines=2 --bind 'enter:execute(echo {+1})+abort'); echo "\n~${KUBE_CLUSTER}~\n"
cluster2

~~

I rolled back to 0.52.1 and tested with the same:

% KUBE_CLUSTER=$(echo "HEADER\n------\ncluster1\ncluster2" | fzf --header-lines=2 --bind 'enter:execute(echo {+1})+abort'); echo "\n~${KUBE_CLUSTER}~\n"

~cluster1~

% KUBE_CLUSTER=$(echo "HEADER\n------\ncluster1\ncluster2" | fzf --header-lines=2 --bind 'enter:execute(echo {+1})+abort'); echo "\n~${KUBE_CLUSTER}~\n"

~cluster2~

As you can see, under 0.52.1, the selected line is being assigned to the varible, and with 0.53.0, the value is being outputted directly, which feels a bit like it is being outputted on stderr, and the variable ends up empty.

**Comment by junegunn** [comment]
See #3865

**Comment by cmaahs** [comment]
I swear to you that I searched open and closed issue for `bind`, perhaps I was too restrictive in my search terms.  Thanks for the push in the right direction.
