### ISSUE TITLE
Manually triggering events

### ISSUE THREAD

**Issue by jdujava** [junegunn/fzf#3874]
### Checklist

- [X] I have read through the manual page (`man fzf`)
- [X] I have searched through the existing issues
- [ ] For bug reports, I have checked if the bug is reproducible in the latest version of fzf

### Output of `fzf --version`

0.53.0 (c4a9ccd6)

### OS

- [X] Linux
- [ ] macOS
- [ ] Windows
- [ ] Etc.

### Shell

- [ ] bash
- [X] zsh
- [ ] fish

### Problem / Steps to reproduce

Is there a way to manually trigger an event?

_Just wondering, I don't need it for anything specific. Having action `trigger(<event>)` could maybe be handy sometimes (e.g. to avoid code duplication, when the same code is to be called on a given event, or alternatively manually called via binding._

**Comment by junegunn** [comment]
No, there isn't.

A common practice to avoid code duplication is to put the code in shell variables. See https://junegunn.github.io/fzf/tips/ripgrep-integration/#4-fix-initial-list
