### ISSUE TITLE
fzf-completion doesn't work on fresh archlinux install

### ISSUE THREAD

**Issue by pjhfggij** [junegunn/fzf#3886]
### Checklist

- [X] I have read through the manual page (`man fzf`)
- [X] I have searched through the existing issues
- [ ] For bug reports, I have checked if the bug is reproducible in the latest version of fzf

### Output of `fzf --version`

0.53.0 (c4a9ccd6)

### OS

- [X] Linux
- [ ] macOS
- [ ] Windows
- [ ] Etc.

### Shell

- [ ] bash
- [X] zsh
- [ ] fish

### Problem / Steps to reproduce

invoking fzf-completion yields zsh's vanilla menu instead of fzf fuzzy search menu. fzf-history-widget and fzf-file-widget work fine.

for example, `cd <TAB>` doesn't invoke fzf, but `ctrl r`
 and `ctrl t` do.
.zshrc:

```zsh
# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# Enable colors and change prompt:
autoload -U colors && colors

PROMPT='%~ >'
RPROMPT='%*'

# History in cache directory:
HISTSIZE=99999999
SAVEHIST=$HISTSIZE
HISTFILE=/home/user/.zsh_history

setopt auto_pushd
autoload -Uz compinit
zstyle ':completion:*' menu select
# Auto complete with case insenstivity
zstyle ':completion:*' matcher-list '' 'm:{a-zA-Z}={A-Za-z}' 'r:|[._-]=* r:|=*' 'l:|=* r:|=*'

zmodload zsh/complist
compinit
_comp_options+=(globdots)		# Include hidden files.

# Edit line in buffer ctrl-v
autoload -z edit-command-line
zle -N edit-command-line
bindkey '^v' edit-command-line

# remove duplicates in zsh_history
setopt HIST_EXPIRE_DUPS_FIRST
setopt HIST_IGNORE_DUPS
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_IGNORE_SPACE
setopt HIST_FIND_NO_DUPS
setopt HIST_SAVE_NO_DUPS

# Use vim keys in tab complete menu:
bindkey -M menuselect 'h' vi-backward-char
bindkey -M menuselect 'j' vi-down-line-or-history
bindkey -M menuselect 'k' vi-up-line-or-history
bindkey -M menuselect 'l' vi-forward-char
bindkey -M menuselect 'left' vi-backward-char
bindkey -M menuselect 'down' vi-down-line-or-history
bindkey -M menuselect 'up' vi-up-line-or-history
bindkey -M menuselect 'right' vi-forward-char

source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.plugin.zsh 2>/dev/null
source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.plugin.zsh 2>/dev/null
source /usr/share/fzf/completion.zsh
source /usr/share/fzf/key-bindings.zsh
````

**Comment by LangLangBart** [comment]
> for example, `cd <TAB>` doesn't invoke fzf

Try 
```sh
cd ** <TAB>
```

or  modify `FZF_COMPLETION_TRIGGER`[^1]

```sh
export FZF_COMPLETION_TRIGGER="" 
cd <TAB>
```

https://github.com/junegunn/fzf/blob/c4a9ccd6afc3698a57a6b938ebba6d85238033e2/shell/completion.zsh#L322-L326

[^1]: [junegunn/fzf - README -Settings](https://github.com/junegunn/fzf#settings)

**Comment by pjhfggij** [comment]
Thank you @LangLangBart that works. I came across [this video](https://youtu.be/MvLQor1Ck3M?si=_W6KJoomRh-V09eD&t=220) in the meantime that mentions `FZF_COMPLETION_TRIGGER` as well, but I would struggle to find out whether setting it to an empty string is a supported use case. I couldn't find it set explicitly in my current zsh framework ([z4h](https://github.com/romkatv/zsh4humans)), so thank you.

Can I ask you by the way if you know how to set it to also fuzzy search completion of command line arguments? It doesn't seem to work right now when I try to get information on `ls` flags for example:
 `ls -<TAB>`

**Comment by pjhfggij** [comment]
also is there a list of completions that fzf-completion supports? it's a bit confusing as kill is supported for example, but variables  (`echo $FZF_<TAB>` doesn't work for example)

**Comment by LangLangBart** [comment]
> zsh framework ([z4h](https://github.com/romkatv/zsh4humans)),

I use `zsh4humans` as well, what is the output of the following command ?

```sh
bindkey | grep -F '^I'
```

try 

```sh
z4h bindkey z4h-fzf-complete Tab 
```

**Comment by pjhfggij** [comment]
sorry for any confusion, I've used z4h on the previous machine, but I'm trying to write .zshrc from scratch now (hence confusion)

on z4h Tab triggers fzf completion out of the box, but when sourcing fzf zsh scripts without any framework `export FZF_COMPLETION_TRIGGER=""` doesn't seem to complete in some contexts that worked in z4h (e.g. `echo $FZF_<TAB>` mentioned above)

**Comment by LangLangBart** [comment]
The completion widget from `zsh4humans` goes much further with its functionality, allowing for the things you desire, like completion of env variables and CLI arguments.

<img src="https://github.com/junegunn/fzf/assets/92653266/246bce43-6529-4f34-bece-ee2f08d05cb8" width="400">

---

The `fzf` completion widget is kept minimal for a reason.

Related comment by the maintainer:
- https://github.com/junegunn/fzf/pull/3476#issuecomment-1760579771

There is some customization one can easily do for additional commands, for example `doge`[^1].

<img src="https://github.com/junegunn/fzf/assets/92653266/4f02df9e-5c3d-4ee2-a5fc-abbd05b444f2" width="400">

But completion of environment variables or CLI arguments seems to require more changes to the actual `*zsh` file. Usually, one has to write it themselves or use popular plugins.

[^1]: [junegunn/fzf - README - Custom fuzzy completion](https://github.com/junegunn/fzf#custom-fuzzy-completion)

**Comment by pjhfggij** [comment]
I've decide to give [fzf-tab](https://github.com/Aloxaf/fzf-tab) a try - the author seems to have thought the problem through well and the first attempts at running it showed a lot of desirable properties (straightforward frontend to the zsh's default compsys; simple zsh codebase). Maybe it will turn out not to be as "robust" as completion integration in zsh4humans, but fingers crossed it will work for my use cases.
