### ISSUE TITLE
--marker '═' --marker-multi-line '╔║╚' does not take effect?

### ISSUE THREAD

**Issue by tmpm697** [junegunn/fzf#3888]
### Checklist

- [X] I have read through the manual page (`man fzf`)
- [X] I have searched through the existing issues
- [X] For bug reports, I have checked if the bug is reproducible in the latest version of fzf

### Output of `fzf --version`

0.53

### OS

- [ ] Linux
- [X] macOS
- [ ] Windows
- [ ] Etc.

### Shell

- [ ] bash
- [X] zsh
- [ ] fish

### Problem / Steps to reproduce

I'm kinda confuse, I have:
```
export FZF_DEFAULT_OPTS=

declare -f |
  perl -0 -pe 's/^}\n/}\n\0/gm' |
  bat --plain --language bash --color always |
  fzf --read0 --ansi --layout reverse --multi --highlight-line
  ```
  which is code from https://junegunn.github.io/fzf/tips/processing-multi-line-items/#all-bashzsh-functions-highlighted
  but i didn't see two marks as below image in the same link, i only see the red one (outer one), not the pink one(inner or right one).
![Screenshot 2024-06-23 at 3 52 14 AM](https://github.com/junegunn/fzf/assets/48467427/0f5fdffd-be3f-4e1e-aa5f-9f7c598390f3)

image from my pc
![Screenshot 2024-06-23 at 3 54 22 AM](https://github.com/junegunn/fzf/assets/48467427/2aba94b3-6ccd-42a4-a043-e0a003870b57)

**Comment by junegunn** [comment]
Markers are for `--multi`. They appear when you select items using TAB or SHIFT-TAB.
