### ISSUE TITLE
"panic: runtime error" if tty is 1 line high

### ISSUE THREAD

**Issue by sturob** [junegunn/fzf#3889]
### Checklist

- [X] I have read through the manual page (`man fzf`)
- [X] I have searched through the existing issues
- [X] For bug reports, I have checked if the bug is reproducible in the latest version of fzf

### Output of `fzf --version`

0.53.0 (brew)

### OS

- [ ] Linux
- [X] macOS
- [ ] Windows
- [ ] Etc.

### Shell

- [X] bash
- [X] zsh
- [ ] fish

### Problem / Steps to reproduce

1. Use tmux (or similar) to set the active TTY to 1 line high - `tmux resize-pane -y 1`
2. Run `fzf`
3. Result: fzf exits with "panic: runtime error: index out of range [1] with length 1"

See attachment for full error message: [20240621-fzf-macos-1-line-bug.txt](https://github.com/user-attachments/files/15942126/20240621-fzf-macos-1-line-bug.txt)

I believe this is a regression from 0.52.1 but I haven't downgraded to test that.

**Comment by junegunn** [comment]
Thanks for the report. Fixed on master.
