### ISSUE TITLE
Feature request: option to return input string if there are zero results

### ISSUE THREAD

**Issue by rf-** [junegunn/fzf#389]
For some use cases, it might be helpful if the user could type in a search string that has zero results, hit Enter, and have fzf return the search string (with exit status 0 or 1, whichever makes more sense to you). The specific use case I have in mind is a Notational Velocity-style interface where the user can either find an existing note or create a new one with a given title.

**Comment by junegunn** [comment]
Have you checked `fzf --print-query`? The flag makes fzf always print the query as the first line of the output so I'd say it's more consistent and easier to reason about.

**Comment by rf-** [comment]
Argh, thanks. Missed it somehow.
