### ISSUE TITLE
fzf `CTRL+R` only working in zsh `vicmd` mode

### ISSUE THREAD

**Issue by carettt** [junegunn/fzf#3891]
### Checklist

- [X] I have read through the manual page (`man fzf`)
- [X] I have searched through the existing issues
- [X] For bug reports, I have checked if the bug is reproducible in the latest version of fzf

### Output of `fzf --version`

0.53.0 (0.53.0)

### OS

- [X] Linux
- [ ] macOS
- [ ] Windows
- [ ] Etc.

### Shell

- [ ] bash
- [X] zsh
- [ ] fish

### Problem / Steps to reproduce

Hooked fzf into zsh with `eval "$(fzf --zsh)"`, then `source ~/.zshrc`. When trying to reverse search with `CTRL+R`, the default zsh backwards incremental history search is run, with the following prompt:
```
bck-i-search: _
```
However, when exiting the prompt and pressing `CTRL+R` again, the fzf history search is executed with the expected prompt and UI.

EDIT: I have just realized that the issue isn't the amount of times `CTRL-R` is triggered, but instead that when i exit the regular history search prompt with `ESC` the terminal goes into `vicmd` mode instead of `viins`. This seems to be the same issue as #2694

**Comment by carettt** [comment]
fixed by hooking fzf *after* `zsh-vi-mode`. my bad ...

**Comment by dkarter** [comment]
This helped me: https://github.com/jeffreytse/zsh-vi-mode/issues/242#issuecomment-1721033298
