### ISSUE TITLE
Re-evaluate --bind each time bindkey pressed

### ISSUE THREAD

**Issue by tmpm697** [junegunn/fzf#3896]
### Checklist

- [X] I have read through the manual page (`man fzf`)
- [X] I have searched through the existing issues
- [X] For bug reports, I have checked if the bug is reproducible in the latest version of fzf

### Output of `fzf --version`

0.53.0

### OS

- [ ] Linux
- [X] macOS
- [ ] Windows
- [ ] Etc.

### Shell

- [X] bash
- [X] zsh
- [ ] fish

### Problem / Steps to reproduce

take below example:
```
export test=true
fd --type file |
  fzf --bind 'ctrl-t:transform:[[ $test ]] &&
              echo "execute(echo hehe >./hehe; export test=false)+transform-query(echo $test)" ||
              echo "execute(echo kaka >./hehe; export test=true)+transform-query(echo $test)"'

```

press ctrl-t will always change query to `true`, but expect true or false between each press.

here the whole text after `--bind` and in single quote evaluate only one time so `$test` always `true` and somehow `export test=false` didn't work

expect something we can dynamically update query with fzf each time press keys, not just one.

**Comment by junegunn** [comment]
See #2976 #2299

Also related: https://github.com/junegunn/fzf/pull/3593/files
