### ISSUE TITLE
CTRL+T in tmux with powerline : problem when putting vim in a background process

### ISSUE THREAD

**Issue by fpietka** [junegunn/fzf#390]
It doesn't happen without powerline, and I have it for both my bash and tmux.
Also I'm on OSX.

This is a weird problem that occurs when doing the following:
* being on a tmux session
* ctrl+t to find a file name
* vim my_file
* ctrl+z to put vim in background

After that point, I have to do a `reset` to have my prompt back.

**Comment by junegunn** [comment]
Hmm, I don't use powerline so I'm not sure if I can help. How about the other key bindings (ctrl-r, alt-c) ? Do they work fine?

**Comment by fpietka** [comment]
ctrl-r does the same, alt-c doesn't seem to work for me (it outputs `ç`, so not related to fzf).
It is working fine with powerline outside of tmux though...

**Comment by junegunn** [comment]
> it outputs ç, so not related to fzf

http://superuser.com/questions/496090/how-to-use-alt-commands-in-a-terminal-on-os-x

> ctrl-r does the same

So then I suppose `fzf-tmux` script also has the issue, can you check? If it does, I'm not sure if the problem is something I can fix from my side.

**Comment by fpietka** [comment]
When I'm in my tmux session it launches `fzf-tmux`, so I guess it is strictly related to it. I can't reproduce launching manually `fzf` (also it doesn't insert result in my prompt then).

**Comment by junegunn** [comment]
I know, but I was trying to make sure that it's reproducible even when you manually run `fzf-tmux`, so that we don't have to look at the source code of key bindings.
