### ISSUE TITLE
Constraint to only exit fzf if processes base on key press are done?

### ISSUE THREAD

**Issue by tmpm697** [junegunn/fzf#3903]
### Checklist

- [X] I have read through the manual page (`man fzf`)
- [X] I have searched through the existing issues
- [X] For bug reports, I have checked if the bug is reproducible in the latest version of fzf

### Output of `fzf --version`

0.53

### OS

- [ ] Linux
- [X] macOS
- [ ] Windows
- [ ] Etc.

### Shell

- [X] bash
- [X] zsh
- [ ] fish

### Problem / Steps to reproduce

So I found out why fzf causes prompt flick issue, especially with `fzf --expect 'ctrl-h,ctrl-m'`,
this dues to users will run other processes base on the key press later after fzf already exit:
```
test=$(echo "1\n2\n3\n" | fzf --expect 'ctrl-h,ctrl-l')

key=$(head -1 $test)

if [[ $key == 'ctrl-h' ]]; then
  sleep 2 # this represents multiple processes which cause the slowness
  # this 100% cause prompt flick in which it will disappear and re-appear again when the processes are done.
fi
```

To fix this, fzf need methods to monitor processes after keys pressed with `--expect`, and make sure only exit fzf if they're all done.

I think this is better than requires all shells to give some kind of constraint for a special process (fzf) to aware of others before exit/return.

**Comment by tmpm697** [comment]
I simply can't put `sleep 2` out of `if [[ $key == 'ctrl-h' ]]` dues to I'm processing `result` base on the key pressed.

If it's `ctrl-h` then do something with `result` but else do other things.

**Comment by junegunn** [comment]
I'm not suggesting that you add "sleep" to your script, it doesn't make any sense. I was trying to demonstrate the effect of `--no-clear`.

**Comment by tmpm697** [comment]
If `sleep 2` does not make sense then check this:
```
test=$(echo "1\n2\n3\n" | fzf --expect 'ctrl-h,ctrl-l')

key=$(head -1 <<< $test)

if [[ $key == 'ctrl-h' ]]; then
  cat ./test.txt # this file is 10MB text file
fi
```

`--no-clear` will cause prompt swallow which fzf takes whole prompt and after fzf exit, prompt still black until user manually redraw screen, is there a way to use it without `swallow` prompt?

**Comment by tmpm697** [comment]
For those who are banging your head against wall about prompt flickering issue TUI program like fzf and shells:
```
Stay away from bash/zsh/sh

Start to use elvish shell
```

That's the solution.

Also note, you can't completely remove `flick` because whatever text display on a screen always need a redraw, obviously under terminal the `redraw` can cause a lookalike `flick` but `zsh/bash/sh` with its way to spawn new program each time you need to do a small things would give you a big flick that drag you into hell. Good luck.

**Comment by tmpm697** [comment]
> For those who are banging your head against wall about prompt flickering issue with TUI program like fzf and shells:
> 
> ```
> Stay away from bash/zsh/sh
> 
> Start to use elvish shell
> ```
> 
> That's the solution.
> 
> Also note, you can't completely remove `flick` because whatever text display on a screen always need a redraw, obviously under terminal the `redraw` can cause a lookalike `flick` but `zsh/bash/sh` with its way to spawn new program each time you need to do a small things would give you a `big flick` that drag you into hell. Good luck.

A bit misinfo, you can still use `zsh/bash/sh` but be aware of using external tools.
