### ISSUE TITLE
`--bind=… execute` works differently in 0.53.0, breaks functionality

### ISSUE THREAD

**Issue by mooreye** [junegunn/fzf#3917]
### Checklist

- [X] I have read through the manual page (`man fzf`)
- [X] I have searched through the existing issues
- [X] For bug reports, I have checked if the bug is reproducible in the latest version of fzf

### Output of `fzf --version`

0.53.0 (Fedora)

### OS

- [X] Linux
- [ ] macOS
- [ ] Windows
- [ ] Etc.

### Shell

- [X] bash
- [ ] zsh
- [ ] fish

### Problem / Steps to reproduce

I have something like this in some of my scripts:
`v=$( seq 10 | fzf --bind='alt-x:execute(echo o)+accept' )`
It used to work like this:

- If you select the entry just by pressing Enter, only the entry will be in `v` variable.
- If you select the entry with `Alt+X`, two lines will be in `v` variable: the letter `o`, and the entry. In later part of the script, I do a `case` checking the content of the first line and decide what to run then.

In the recent version `0.53.0`, this stopped working. the `o` just outputs on the terminal, and does not place itself into the variable. I tried redirecting `2>&1` but it still doesn't work. 

What stream does this `o` output to? And how to replicate this functionality in the new version?

**Comment by junegunn** [comment]
See https://github.com/junegunn/fzf/issues/3865
