### ISSUE TITLE
Asking first: auto appending to `.bashrc`

### ISSUE THREAD

**Issue by wspurgin** [junegunn/fzf#392]
Disclaimer, this is more of an installation configuration request.

Recently started using `fzf` and I'm really liking it! However, I've got one issue with the installation process: auto appending to .bashrc

In my case, I have my own set of bash configuration files where I store all the aliases, path additions, general configuration and etc. These files a organized in a particular matter and within a `~/.bash` directory. The only thing my bashrc files does is determine if the shell is interactive then `source` all my configuration files in `~/.bash`.

Therefore the line that the installation process adds is in the "wrong" place :frowning:  (for me anyway). I'd rather just add it myself if the correct file where I want it! 

So I propose that there be some sort of choice or configuration as part of the install process. Maybe something like this:

```
Do you want to add auto-completion support? ([y]/n) y
Do you want to add key bindings? ([y]/n) y
Do you want to auto-append to .bashrc and .zshrc to enable fzf? ([y]/n) n

You should add the following line to your bash/zsh configuration (like .bashrc).
Otherwise you won't be able to use fzf like you want to! :O
  [ -f ~/.fzf.bash ] && source ~/.fzf.bash
```

Maybe a flag or something in the install process would be better (since by default I imagine most people would just say `y` to that question anyway).

Let me know your thoughts

**Comment by junegunn** [comment]
Adding another y/n prompt as you suggested is the most straightforward way to address the requirement, however since the install script is usually run after a git pull, it can be problematic to the users who have lines like follows in their scripts.

- `yes n | ./install`
- `(echo y; echo n) | ./install`

So it's probably safer to add flags, I'll think about it and let you know.

**Comment by wspurgin** [comment]
:+1: Awesome thanks

**Comment by junegunn** [comment]
Added flags as follows:

```
usage: ./install [OPTIONS]

    --help               Show this message
    --bin                Download fzf binary only
    --all                Download fzf binary and update configuration files
                         to enable key bindings and fuzzy completion
    --[no-]key-bindings  Enable/disable key bindings (CTRL-T, CTRL-R, ALT-C)
    --[no-]completion    Enable/disable fuzzy completion (bash & zsh)
    --[no-]update-rc     Whether or not to update shell configuration files
```

In your case,  `./install --all --no-update-rc` should do the trick.

**Comment by wspurgin** [comment]
:+1: Much appreciated.
