### ISSUE TITLE
Repository tag name

### ISSUE THREAD

**Issue by rafa-martin** [junegunn/fzf#3920]
Hi,

I have an automation script that uses GitHub archives to download repositories. Previously, the tags followed a specific naming convention (e.g., 0.39.0, 0.30.0), but the latest release is named v0.54.0.

Did you change the naming convention for any reason? Will future releases include the 'v' prefix?

**Comment by junegunn** [comment]
Yes, it is noted in the CHANGELOG.

See https://github.com/junegunn/fzf/commit/9e92b6f11e0f59272de410f56493893334071e6e
