### ISSUE TITLE
Allow filtering on un-rendered fields. 

### ISSUE THREAD

**Issue by seivan** [junegunn/fzf#3921]
### Checklist

- [X] I have read through the manual page (`man fzf`)
- [X] I have searched through the existing issues
- [ ] For bug reports, I have checked if the bug is reproducible in the latest version of fzf

### Output of `fzf --version`

0.54.0 (brew)

### OS

- [ ] Linux
- [X] macOS
- [ ] Windows
- [ ] Etc.

### Shell

- [ ] bash
- [X] zsh
- [ ] fish

### Problem / Steps to reproduce

Can't filter on fields that aren't being rendered (to keep things less cluttered).
```sh
echo  "1:John:Smith:Developer\n2:Jane:Doe:Designer\n3:Joe:Bloggs:Manager" | fzf --delimiter=: --nth=2..4 --with-nth=2..3
```
Searching for `Developer` should select `John..`

Related issue: https://github.com/junegunn/fzf/issues/102

There's a comment there https://github.com/junegunn/fzf/issues/102#issuecomment-988441368 that claims 
```sh
echo foo bar baz qux foo | fzf --with-nth 3,2,4 --nth ..
```

should match with `fofo` but it doesn't. Doesn't match `foo` either. 

I'd consider this a bug, but not sure if the project does. That being said, it really should be possible to filter based on fields not rendered in the search list because certain things would clutter it. Imagine description fields with larger bodies of text or tags. You'd render the "name" in the search but should be able to search text or tags that are shown in the preview.

**Comment by junegunn** [comment]
> There's a comment there [#102 (comment)](https://github.com/junegunn/fzf/issues/102#issuecomment-988441368) that claims
> 
> ```shell
> echo foo bar baz qux foo | fzf --with-nth 3,2,4 --nth ..
> ```
> 
> should match with `fofo` but it doesn't. Doesn't match `foo` either.

You're reading it the other way around, probably missed "Suppose we're ..." part. The point of the comment is that it's confusing, and I don't want fzf to behave like that. I still feel exactly the same because fzf is essentially a line filter, like grep.

If you really want fzf to match parts that are not visible, you could manually format the input and place the part beyond the screen width.

```sh
printf "%s%1000s" foo bar | fzf --nth -1 --no-hscroll --ellipsis ''
```

**Comment by seivan** [comment]
I resorted to abusing tabs. I gotta say it's an ugly method, I don't understand the hesitance to allow search over words that are not in the search panel, but say in the preview panel instead? There's limited space, so shoving everything in there via clumsy hacks instead of just allowing it seems weird.

```sh
selected=$(echo "Description:::desc:::name:::john:::surname:::smith" | \
awk -F ":::" '{print $2 " [" $4 "]\t" $0 "\t\t\t\t\t\t\t\t\t\t\t\t\t\t" $6}' | \
fzf --delimiter="\t" --with-nth=1,3..-1 --preview 'echo {} | awk -F "\t" '\''{split($2,a,":::"); print a[1]":\n  " a[2] "\n\n"a[3]":\n  " a[4] "\n\n" a[5]":\n  " a[6] "\n\n"}'\''' --preview-window=right:65%)


# Extract the command from the selected output
cmd=$(echo "$selected" | awk -F "\t" '{print $NF}')

# Run the command
print -z "$cmd"
```

Just from a user UX PoV it's just a tad too much.

**Comment by kqvanity** [comment]
Subscribing over here as well!

**Comment by kqvanity** [comment]
I keep coming across more and more usecases for when this feature would be extremely useful.
