### ISSUE TITLE
Cygwin reports ps: unknown option -- o for wildcard completion

### ISSUE THREAD

**Issue by JaroslawPokropinski** [junegunn/fzf#3924]
### Checklist

- [X] I have read through the manual page (`man fzf`)
- [X] I have searched through the existing issues
- [X] For bug reports, I have checked if the bug is reproducible in the latest version of fzf

### Output of `fzf --version`

0.53.0 (c4a9ccd)

### OS

- [ ] Linux
- [ ] macOS
- [X] Windows
- [ ] Etc.

### Shell

- [X] bash
- [X] zsh
- [ ] fish

### Problem / Steps to reproduce

When trying to complete command using `kill -9 **` and pressing TAB i get the following error
```
kill **ps: unknown option -- o
```
This seems to be caused by incompatibility / lack of the -o feature in ps command. For context I use Windows Cygiwin and I tried with bot bash and zsh. The output of `ps --help` is the following:
```
Usage: ps [-aefls] [-u UID] [-p PID]

Report process status

 -a, --all       show processes of all users
 -e, --everyone  show processes of all users
 -f, --full      show process uids, ppids
 -h, --help      output usage information and exit
 -l, --long      show process uids, ppids, pgids, winpids
 -p, --process   show information for specified PID
 -s, --summary   show process summary
 -u, --user      list processes owned by UID
 -V, --version   output version information and exit
 -W, --windows   show windows as well as cygwin processes

With no options, ps outputs the long format by default
```

Are you planning to add support for such case (eg. fallback some combination of ps -p $$ and awk command)?

**Comment by JaroslawPokropinski** [comment]
I get the same error on the MSYS2
![image](https://github.com/user-attachments/assets/50cefaa3-4c7c-48a3-8e38-8d3957199b7d)

I think the issue with those is that cygwin version of ps does not support -o option (and it seems that msys2 also uses the same ps binary)
![image](https://github.com/user-attachments/assets/04cdc63a-9b2a-41e6-aa81-da9b0f500ec4)

I should specify that most of the functionalities of fzf work fine this is specifically competition of kill command.

**Comment by JaroslawPokropinski** [comment]
Also WSL does not really meet my needs and this issue is not dealbreaker for me, I will just keep using fzf for ctrl+R reverse search.

**Comment by DanSM-5** [comment]
I can confirm that the issue happens in bash from git for windows as well (which I understand it is based on MSYS2). It uses the same ps as cygwin:

```bash
ps --version
ps (cygwin) 3.4.10
Show process statistics
Copyright (C) 1996 - 2024 Cygwin Authors
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by junegunn** [comment]
We already use an alternative `ps` command for BusyBox. Similarly, we can add another fallback command for Cygwin. Interested in opening a pull request?

https://github.com/junegunn/fzf/blob/4e85f72f0ee237bef7a1617e0cf8c811a4091d72/shell/completion.bash#L410-L415

https://github.com/junegunn/fzf/blob/4e85f72f0ee237bef7a1617e0cf8c811a4091d72/shell/completion.zsh#L300-L305

**Comment by DanSM-5** [comment]
From a quick test I can see that using the options `-ef` gives an output similar closer to the `-eo`.

```bash
$ ps -ef
     UID     PID    PPID  TTY        STIME COMMAND
    user    2140       1 cons1    01:50:49 /usr/bin/bash
    user     903       1 cons0      Aug  1 /usr/bin/zsh
    user    2256     903 cons0    02:09:34 /usr/bin/ps
    ...
```

It also has an option `-W` to include all windows processes not only cygwin's (probably better for windows users).

```bash
$ ps -efW
     UID     PID    PPID  TTY        STIME COMMAND
    user    2140       1 cons1    01:50:49 /usr/bin/bash
    user     903       1 cons0      Aug  1 /usr/bin/zsh
    user    2256     903 cons0    02:09:34 /usr/bin/ps
       0   66412       0 ?          Jul 29 C:\Windows\System32\smss.exe
       0   67452       0 ?          Jul 29 C:\Windows\System32\svchost.exe
    ...
```

I can open a PR tomorrow if this is fine.
