### ISSUE TITLE
Winget: latest version is v0.54.0 instead of 0.54.0

### ISSUE THREAD

**Issue by jathek** [junegunn/fzf#3927]
### Checklist

- [X] I have read through the manual page (`man fzf`)
- [X] I have searched through the existing issues
- [X] For bug reports, I have checked if the bug is reproducible in the latest version of fzf

### Output of `fzf --version`

0.53.0 (c4a9ccd) [before `--force` upgrade]

### OS

- [ ] Linux
- [ ] macOS
- [X] Windows
- [ ] Etc.

### Shell

- [ ] bash
- [X] zsh
- [ ] fish

### Problem / Steps to reproduce

The most recent release was pushed to winget as `v0.54.0`, not `0.54.0`. As a result, although searching for fzf lists the new version, the winget install process does not believe there is a new version to upgrade to. Specifying `v0.54.0` to winget doesn't work. I was finally able to get it upgraded with the `--force` command, but wanted to file the issue in case there is something wrong with the winget release workflow.

![image](https://github.com/user-attachments/assets/4251f82e-e10a-4715-b242-7425a429b8ac)

**Comment by junegunn** [comment]
Thanks for the report. We did change the tagging strategy.

https://github.com/junegunn/fzf/commit/9e92b6f11e0f59272de410f56493893334071e6e

And Winget release is done via a GitHub Actions workflow.

https://github.com/junegunn/fzf/blob/4ef1cf5b35ca492154a6785281d334b909a24035/.github/workflows/winget.yml#L13

I didn't know it would disturb upgrades, it looks like I should have changed the spec to drop `v` prefix. Is there anyway I can make it right?

**Comment by junegunn** [comment]
https://github.com/vedantmgoyal9/winget-releaser?tab=readme-ov-file#configuration-options-%EF%B8%8F

I can just remove `version` from the spec, but I'm not sure if it's okay to re-release `0.54.0`.

**Comment by junegunn** [comment]
Fixed in #163342.

According to https://github.com/microsoft/winget-pkgs/issues/163342#issuecomment-2233264951, the upgrade issue is fixed on the preview version of the client. You might want to check it out.
