### ISSUE TITLE
arrow up keybinding is showing no scrollable list

### ISSUE THREAD

**Issue by pkpg** [junegunn/fzf#3931]
### Checklist

- [X] I have read through the manual page (`man fzf`)
- [X] I have searched through the existing issues
- [X] For bug reports, I have checked if the bug is reproducible in the latest version of fzf

### Output of `fzf --version`

0.53.0 (brew)

### OS

- [ ] Linux
- [X] macOS
- [ ] Windows
- [ ] Etc.

### Shell

- [ ] bash
- [X] zsh
- [ ] fish

### Problem / Steps to reproduce

When I user <c-r> I get a nice scrollable list. If I press arrow up, I get a similar list, but it is showing just some items depending on my terminal height. The issue is, that this list is not scrollable. The <c-r> list has a scroll indicator on the left and I can scroll through it. The arrow up list jumps to the buttom again when I hit the highest item instead of scrolling through the list.
```
❯ echo $HISTSIZE
50000
❯  echo $SAVEHIST
10000
```

Using `history | fzf` shows the scrollable list.

If I run `fzf-history-widget` I get the scrollbar and I have `bindkey "${key[Up]}" fzf-history-widget` in my `.zshrc`

**Comment by pkpg** [comment]
> Could you share an image, GIF, video, or asciinema recording to point out the issue?

https://asciinema.org/a/p0z0jJ3g8uwsm4Gk3RvEmFjH0

When I run `command env -i HISTSIZE=50000 HOME=$HOME TERM=$TERM USER=$USER PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin $SHELL -f`, the command fzf is not found.

**Comment by LangLangBart** [comment]
> the command fzf is not found.

Can you run `type -a fzf` and then add the path of your `fzf` installation to the `PATH` variable in the `command env` command?


```sh
type -a fzf
# fzf is /Users/paria/Developer/fzf/bin/fzf
# fzf is /usr/local/bin/fzf
# fzf is /Users/paria/.cache/zsh4humans/v5/fzf/bin/fzf
```

```sh
command env -i HISTSIZE=50000 HOME=$HOME TERM=$TERM USER=$USER PATH= /Users/paria/Developer/fzf/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin /usr/local/bin/zsh -f
```

Alternatively, assigning `PATH` with `$PATH` should work as well.

---

> https://asciinema.org/a/p0z0jJ3g8uwsm4Gk3RvEmFjH0

Thanks for the information. It appears that you use a plugin that relies on fzf, but it is not the default `fzf-history-widget` that comes with `source <(fzf --zsh)`. Could you share the output of the following two commands?

```sh
bindkey | grep -F '^[[A'
# and 
whence -c fzf-history-widget
```

**Comment by pkpg** [comment]
> type -a fzf
```shell
❯ type -a fzf
fzf is /opt/homebrew/bin/fzf
fzf is /Users/phil/.fzf/bin/fzf
```

in the minimal setup
```shell
❯ command env -i HISTSIZE=50000 HOME=$HOME TERM=$TERM USER=$USER PATH=$PATH $SHELL -f
PGREG-MAC01% source <(fzf --zsh)
PGREG-MAC01% bindkey '^[[A' fzf-history-widget
PGREG-MAC01% for i in {1..100};do print -s "echo $i";done
```
it works and gives me the scrollbar as expected

> ```shell
> bindkey | grep -F '^[[A'
> # and 
> whence -c fzf-history-widget
> ```

```shell
❯ bindkey | grep -F '^[[A'
"^[^[[A" history-search-backward
"^[[A" up-line-or-search
❯ whence -c fzf-history-widget
fzf-history-widget () {
        local selected num
        setopt localoptions noglobsubst noposixbuiltins pipefail no_aliases 2> /dev/null
        if zmodload -F zsh/parameter p:history 2> /dev/null && (( ${#commands[perl]} ))
        then
                selected="$(printf '%1$s\t%2$s\000' "${(vk)history[@]}" |
      perl -0 -ne 'if (!$seen{(/^\s*[0-9]+\**\s+(.*)/, $1)}++) { s/\n/\n\t/gm; print; }' |
      FZF_DEFAULT_OPTS=$(__fzf_defaults "" "-n2..,.. --scheme=history --bind=ctrl-r:toggle-sort --highlight-line ${FZF_CTRL_R_OPTS-} --query=${(qqq)LBUFFER} +m --read0") \
      FZF_DEFAULT_OPTS_FILE='' $(__fzfcmd))" 
        else
                selected="$(fc -rl 1 | awk '{ cmd=$0; sub(/^[ \t]*[0-9]+\**[ \t]+/, "", cmd); if (!seen[cmd]++) print $0 }' |
      FZF_DEFAULT_OPTS=$(__fzf_defaults "" "-n2..,.. --scheme=history --bind=ctrl-r:toggle-sort --highlight-line ${FZF_CTRL_R_OPTS-} --query=${(qqq)LBUFFER} +m") \
      FZF_DEFAULT_OPTS_FILE='' $(__fzfcmd))" 
        fi
        local ret=$? 
        if [ -n "$selected" ]
        then
                if num=$(awk '{print $1; exit}' <<< "$selected" | grep -o '^[1-9][0-9]*') 
                then
                        zle vi-fetch-history -n $num
                else
                        LBUFFER="$selected" 
                fi
        fi
        zle reset-prompt
        return $ret
}
```

**Comment by LangLangBart** [comment]
> ```shell
> ❯ command env -i HISTSIZE=50000 HOME=$HOME TERM=$TERM USER=$USER PATH=$PATH $SHELL -f
> PHIL-MAC01% source <(fzf --zsh)
> PHIL-MAC01% bindkey '^[[A' fzf-history-widget
> PHIL-MAC01% for i in {1..100};do print -s "echo $i";done
> ```
>   
> it works and gives me the scrollbar as expected

Good, that means somewhere in your `zsh` setup, the assignment to the <kbd>↑</kbd> key is overwritten by another widget. This widget looks similar to `fzf` but probably just takes advantage of the numerous possibilities offered by the Zsh Line Editor (ZLE), which allows for interactive editing of the command line.

As seen in your `asciinema` recording, the plugin can alter the buffer stack as you move your keys up and down, which is something the `fzf-history-widget` doesn't do.

> ❯ bindkey | grep -F '^[[A'
> "^[^[[A" history-search-backward
> "^[[A" up-line-or-search

These are just standard `zsh` widgets[^1]. Sometimes, the binding can also be `"^[OA"`. Can you run `bindkey | grep A`?

```sh
bindkey | grep A
"^A" beginning-of-line
"^[A" accept-and-hold
"^[OA" fzf-history-widget
"^[[A" up-line-or-beginning-search
```

Alternatively, try running:
```sh
zmodload zsh/zprof
# press the Up key to trigger your plugin
# press Esc
zprof | head -n 10
```

This should show recent function calls and likely include the call for the unknown widget on the top.

---

So it is very likely not a bug in `fzf`, but I am curious about the name of the plugin you use.

[^1]: [zsh: 18 Zsh Line Editor - History Control](https://zsh.sourceforge.io/Doc/Release/Zsh-Line-Editor.html#History-Control)

**Comment by pkpg** [comment]
> Can you run `bindkey | grep A`?
```shell
❯ bindkey | grep A
"^A" beginning-of-line
"^[^[OA" history-search-backward
"^[^[[A" history-search-backward
"^[A" accept-and-hold
"^[OA" up-line-or-search
"^[[1;3A" history-search-backward
"^[[A" up-line-or-search
```

> Alternatively, try running:
> ```shell
> zmodload zsh/zprof
> ```
```shell
❯ zmodload zsh/zprof
❯ 
```

**Comment by LangLangBart** [comment]
> ```shell
> ❯ zmodload zsh/zprof
> ❯ 
> ```

I assume the <kbd>⎋ Escape</kbd> key did not close the plugin? A bit more textual communication would have been helpful.



Anyway, I believe you are using the `zsh-autocomplete`[^1] plugin. 

```shell
Paria% zmodload zsh/zprof 
Paria% zprof | head -n 10 
num  calls                time                       self            name
-----------------------------------------------------------------------------------
 1)    7       17545.57  2506.51   90.66%  17500.84  2500.12   90.43%  .autocomplete__up-line-or-search__zle-widget
 2)   77         288.22     3.74    1.49%    288.22     3.74    1.49%  .autocomplete:async:start
 3)  770         375.15     0.49    1.94%    271.88     0.35    1.40%  _description
 4)   77         140.84     1.83    0.73%    111.46     1.45    0.58%  _path_files
 5)  850         105.65     0.12    0.55%    105.65     0.12    0.55%  _setup
 6)  979          88.83     0.09    0.46%     82.56     0.08    0.43%  _tags
 7)   44        1269.71    28.86    6.56%     78.32     1.78    0.40%  autocomplete:_main_complete:old
 8)   37          71.65     1.94    0.37%     71.65     1.94    0.37%  _expand
```

<img src="https://github.com/user-attachments/assets/81aa079a-40b5-49cb-9731-58fced564db1" width="800">

---

Try to locate the line where you source this plugin, and one line below, add the following if you want to use `fzf's` history widget:

```sh
source <(fzf --zsh)
bindkey "${key[Up]}" fzf-history-widget
```

Otherwise, contact the plugin maker and ask for help there.


[^1]: [GitHub - marlonrichert/zsh-autocomplete: 🤖 Real-time type-ahead completion for Zsh. Asynchronous find-as-you-type autocompletion.](https://github.com/marlonrichert/zsh-autocomplete)

**Comment by pkpg** [comment]
Sorry for the lag of communication. I appreciate your support very much, but I did not know what to type instead of following your instructions to find the issue. Sorry.

You're right, I'm using `zsh-autocomplete`:
```shell
❯ zmodload zsh/zprof
❯ zprof | head -n 10
num  calls                time                       self            name
-----------------------------------------------------------------------------------
 1)    1         587,79   587,79   93,53%    557,19   557,19   88,66%  bracketed-paste-magic
 2)   16          17,77     1,11    2,83%     14,26     0,89    2,27%  -fast-highlight-process
 3)    3           7,08     2,36    1,13%      7,04     2,35    1,12%  .autocomplete:async:start
 4)   27          24,87     0,92    3,96%      4,69     0,17    0,75%  _zsh_highlight
 5)   26           3,33     0,13    0,53%      3,33     0,13    0,53%  -fast-highlight-main-type
 6)    1           3,05     3,05    0,49%      3,05     3,05    0,49%  omz_termsupport_cwd
 7)   21         595,04    28,34   94,68%      2,96     0,14    0,47%  _zsh_highlight_call_widget
 8)    5           2,59     0,52    0,41%      2,52     0,50    0,40%  .autocomplete:async:wait
```
I source it very hight in my `.zshrc` in line 8 like this:
```
 source ~/Repos/zsh-autocomplete/zsh-autocomplete.plugin.zsh
```
in my plugins I have:
```
plugins=(git zsh-autosuggestions zsh-syntax-highlighting fast-syntax-highlighting zsh-autocomplete zsh-fzf-history-search)
````

If I remove `zsh-autocomplete` from the plugins, source the `.zshrc` again and hit the up key, fzf is completely gone and I just get the last coommand and the following outoput and more up arrow hits do nighting:
```shell
❯ source ~/.zshrc
file
.zshrc                .zshrc.pre-oh-my-zsh
```

If it helps, this is my full `.zshrc`:
```
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

source ~/Repos/zsh-autocomplete/zsh-autocomplete.plugin.zsh

source <(fzf --zsh)
bindkey "${key[Up]}" fzf-history-widget

export ZSH=$HOME/.oh-my-zsh

ZSH_THEME="robbyrussell"

plugins=(git zsh-autosuggestions zsh-syntax-highlighting fast-syntax-highlighting zsh-autocomplete zsh-fzf-history-search)

source $ZSH/oh-my-zsh.sh

alias art="php artisan"
alias pint="./vendor/bin/pint"
alias dep="./vendor/bin/dep"
alias lg="lazygit"

source /opt/homebrew/share/powerlevel10k/powerlevel10k.zsh-theme

[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
[ -f /opt/homebrew/etc/profile.d/autojump.sh ] && . /opt/homebrew/etc/profile.d/autojump.sh

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# bun
[ -s "/Users/phil/.bun/_bun" ] && source "/Users/phil/.bun/_bun"
export BUN_INSTALL="$HOME/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"

# Herd
export PATH="/Users/phil/Library/Application Support/Herd/bin/":$PATH
export HERD_PHP_82_INI_SCAN_DIR="/Users/phil/Library/Application Support/Herd/config/php/82/"
export NVM_DIR="/Users/phil/Library/Application Support/Herd/config/nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[[ -f "/Applications/Herd.app/Contents/Resources/config/shell/zshrc.zsh" ]] && builtin source "/Applications/Herd.app/Contents/Resources/config/shell/zshrc.zsh"
export HERD_PHP_83_INI_SCAN_DIR="/Users/phil/Library/Application Support/Herd/config/php/83/"
```

**Comment by LangLangBart** [comment]
> If it helps, this is my full `.zshrc`:

Move it after initiating `oh-my-zsh.sh`.

```diff
---.zshrc
+++.zshrc
@@ -6,5 +6,4 @@ source ~/Repos/zsh-autocomplete/zsh-autocomplete.plugin.zsh
 
 source <(fzf --zsh)
-bindkey "${key[Up]}" fzf-history-widget
 
 export ZSH=$HOME/.oh-my-zsh
@@ -15,4 +14,5 @@ plugins=(git zsh-autosuggestions zsh-syntax-highlighting fast-syntax-highlightin
 
 source $ZSH/oh-my-zsh.sh
+bindkey "${key[Up]}" fzf-history-widget
 
 alias art="php artisan"
@@ -26,6 +26,4 @@ source /opt/homebrew/share/powerlevel10k/powerlevel10k.zsh-theme
 [ -f /opt/homebrew/etc/profile.d/autojump.sh ] && . /opt/homebrew/etc/profile.d/autojump.sh
 
-[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
-
 # bun
 [ -s "/Users/phil/.bun/_bun" ] && source "/Users/phil/.bun/_bun"

```

PS: The line `source ~/.fzf.zsh` is not really needed anymore since fzf 0.48.0. You can just call `source <(fzf --zsh)`. Optionally, you can check if `fzf` is on your `PATH` with the following:


```sh
if (( ${+commands[fzf]} )); then
  source <(fzf --zsh)
fi
```

**Comment by pkpg** [comment]
I moved it as recommended and sourced it again, but it does not have any noticeable effect on the up key behavior. This is my updated `.zshrc`:
```
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

source ~/Repos/zsh-autocomplete/zsh-autocomplete.plugin.zsh

if (( ${+commands[fzf]} )); then
  source <(fzf --zsh)
fi

export ZSH=$HOME/.oh-my-zsh

ZSH_THEME="robbyrussell"

plugins=(git zsh-autosuggestions zsh-syntax-highlighting fast-syntax-highlighting zsh-autocomplete zsh-fzf-history-search)

source $ZSH/oh-my-zsh.sh

bindkey "${key[Up]}" fzf-history-widget

alias art="php artisan"
alias pint="./vendor/bin/pint"
alias dep="./vendor/bin/dep"
alias lg="lazygit"

source /opt/homebrew/share/powerlevel10k/powerlevel10k.zsh-theme

[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
[ -f /opt/homebrew/etc/profile.d/autojump.sh ] && . /opt/homebrew/etc/profile.d/autojump.sh

# bun
[ -s "/Users/phil/.bun/_bun" ] && source "/Users/phil/.bun/_bun"
export BUN_INSTALL="$HOME/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"

# Herd
export PATH="/Users/phil/Library/Application Support/Herd/bin/":$PATH
export HERD_PHP_82_INI_SCAN_DIR="/Users/phil/Library/Application Support/Herd/config/php/82/"
export NVM_DIR="/Users/phil/Library/Application Support/Herd/config/nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[[ -f "/Applications/Herd.app/Contents/Resources/config/shell/zshrc.zsh" ]] && builtin source "/Applications/Herd.app/Contents/Resources/config/shell/zshrc.zsh"
export HERD_PHP_83_INI_SCAN_DIR="/Users/phil/Library/Application Support/Herd/config/php/83/"
```

**Comment by pkpg** [comment]
`bindkey '\eOA' fzf-history-widget` is an acceptable solution for me. Thank you very much @LangLangBart for your detailed support. As a side effect I lerned a lot new.
