### ISSUE TITLE
unknown option --no-tmux error

### ISSUE THREAD

**Issue by ndvo** [junegunn/fzf#3932]
### Checklist

- [X] I have read through the manual page (`man fzf`)
- [X] I have searched through the existing issues
- [X] For bug reports, I have checked if the bug is reproducible in the latest version of fzf

### Output of `fzf --version`

b4ddffdc6167d23077139f5a24a2709097bc660c

### OS

- [X] Linux
- [ ] macOS
- [ ] Windows
- [ ] Etc.

### Shell

- [X] bash
- [ ] zsh
- [ ] fish

### Problem / Steps to reproduce

Problem started after a git pull.

I am also using Fugitive. I got the error when running `GFiles` command.

The changes bellow got rid of the error and it worked as expected.

```
:$ fzf --version
0.38.0 (debian)
```

```vim
M plugin/fzf.vim
@@ -543,10 +543,10 @@ try
     let use_term = 0
   endif
   if use_term
-    let optstr .= ' --no-height --no-tmux'
+    let optstr .= ' --no-height '
   elseif use_height
     let height = s:calc_size(&lines, dict.down, dict)
-    let optstr .= ' --no-tmux --height='.height
+    let optstr .= ' --height='.height
   endif
   " Respect --border option given in $FZF_DEFAULT_OPTS and 'options'
   let optstr = join([s:border_opt(get(dict, 'window', 0)), s:extract_option($FZF_DEFAULT_OPTS, 'border'), optstr])
```

**Comment by junegunn** [comment]
You're running an outdated, incompatible version of fzf with the latest Vim plugin.

You can `:call fzf#install()` to get the latest binary. But it's better to configure your plugin manager to call it upon update. https://github.com/junegunn/fzf.vim?tab=readme-ov-file#using-vim-plug
