### ISSUE TITLE
consider adding `--head` option?

### ISSUE THREAD

**Issue by tw4452852** [junegunn/fzf#3933]
As the supplement to `--tail`, this might be used when user only care about the first nth elements in the result.
Although, I can use `| head -n | fzf` to archieve the same goal, but a bit of verbose, any thought?

**Comment by junegunn** [comment]
It isn't that verbose.

```sh
| head -n | fzf
| fzf --head=n
```

fzf follows the Unix philosophy and tries not to implement features that can be outsourced to other programs. 

`--tail` is a different story. `... | tail -n | fzf` isn't identical to `... | fzf --tail=n`. With `--tail`, fzf can show the last entries at the moment before the stream is complete.

https://junegunn.github.io/fzf/tips/browsing-log-streams/
