### ISSUE TITLE
 Security Alert: Potential Trojan Detected in Windows Release v0.54.1

### ISSUE THREAD

**Issue by LexSong** [junegunn/fzf#3937]
### Checklist

- [X] I have read through the manual page (`man fzf`)
- [X] I have searched through the existing issues
- [X] For bug reports, I have checked if the bug is reproducible in the latest version of fzf

### Output of `fzf --version`

0.54.1

### OS

- [ ] Linux
- [ ] macOS
- [X] Windows
- [ ] Etc.

### Shell

- [ ] bash
- [ ] zsh
- [ ] fish

### Problem / Steps to reproduce

Hi,

I recently downloaded the Windows release version 0.54.1 (https://github.com/junegunn/fzf/releases/download/v0.54.1/fzf-0.54.1-windows_amd64.zip). During the installation process, the Windows Defender flagged the downloaded file as potentially malicious and removed the file.

Windows Defender Detection: Trojan/Wacatac.B!ml

VirusTotal: 
1/94 security vendor flagged this URL as malicious (Antiy-AVL)

VirusTotal Report Link :
https://www.virustotal.com/gui/url/377142320e072b3943a62e6305c8a55ec3288f5d81e1d7e1da15963a987a6c39/

Could you please investigate this issue and verify if the flagged detection is a false positive or if there might be a security vulnerability within the release? Thank you.

**Comment by junegunn** [comment]
I'm pretty confident that this is a false positive. This has alrealy happened several times in the past.

https://github.com/search?q=repo%3Ajunegunn%2Ffzf+trojan&type=issues

Also see https://github.com/golang/go/commit/1be58dcda8f31eb0ed77fd5e33fb3f5fe47f33ab

**Comment by LexSong** [comment]
Thank you for your response. I will keep this issue open until the next release or Windows Defender resolves the false positive.

**Comment by LexSong** [comment]
Close this issue as Windows Defender no longer reports any threats.
