### ISSUE TITLE
Using `FZF_POS` has a high impact on performance

### ISSUE THREAD

**Issue by Kabouik** [junegunn/fzf#3940]
### Checklist

- [X] I have read through the manual page (`man fzf`)
- [X] I have searched through the existing issues
- [X] For bug reports, I have checked if the bug is reproducible in the latest version of fzf

### Output of `fzf --version`

0.54.1 (50fa90d)

### OS

- [X] Linux
- [ ] macOS
- [ ] Windows
- [ ] Etc.

### Shell

- [X] bash
- [ ] zsh
- [X] fish

### Problem / Steps to reproduce

While writing a script based on `fzf` and running it on a machine with relatively low performance (a Linux smartphone), I noticed a severe performance impact when using `$FZF_POS`. Scrolling through the list with up/down is just much slower than when not using the following parameters:

   ```sh
                 --info-command='echo -e "\x1b[33;1m$FZF_POS\x1b[m/$FZF_INFO"' \
		      --bind='up:up+execute-silent(echo "$FZF_POS" > /tmp/fzp-line)' \
		      --bind='down:down+execute-silent(echo "$FZF_POS" > /tmp/fzp-line)' \
		      --bind='left-click:execute-silent(echo "$FZF_POS" > /tmp/fzp-line)' \
		      --bind='tab:toggle+down+execute-silent(echo "$FZF_POS" > /tmp/fzp-line)' \
		      --bind='btab:toggle+up+execute-silent(echo "$FZF_POS" > /tmp/fzp-line)' \
```

Note that in further tests, I found that the first argument (`--info-command`) has a noticeable impact on its own, even when the other options below are not used. I kind of expected that writing to a file could have an impact, albeit not a big one, but was surprised that the `info-command` alone also reduces performance significatively.

I need to write the position to a file because I am re-using the value after closing `fzf` (it runs in a while loop), and haven't found how to make it inherit the variable otherwise.

Is that a known issue?

**Comment by junegunn** [comment]
Yes, these actions will run an external command and block fzf until completion.

How long does it take to run a command using your `$SHELL`?

```sh
echo $SHELL

time $SHELL -c 'echo foo > /tmp/bar'
```

**Comment by Kabouik** [comment]
On my computer:

```
________________________________________________________
Executed in    6.97 millis    fish           external
   usr time    3.06 millis    0.00 millis    3.06 millis
   sys time    4.07 millis    1.00 millis    3.06 millis
```

On my Linux phone (where it's very noticeable, even when just using `info-command`):
```
________________________________________________________
Executed in    638.65 millis    fish           external
   usr time    100.00 millis     0.00 millis    100.00 millis
   sys time    420.00 millis    10.00 millis    410.00 millis
```

It's variable of course, but that's the order of magnitude.

It is much (much) faster to just run `time echo foo > /tmp/bar` without `$SHELL` on the phone, though:

```
________________________________________________________
Executed in    1.42 millis    fish           external
   usr time     0.00 millis     0.00 millis    0.00 millis
   sys time    10.00 millis    10.00 millis    0.00 millis
```

**Comment by junegunn** [comment]
Is `sh` (or `bash`) faster than fish on that phone?

```sh
time sh -c 'echo foo > /tmp/bar'
```

**Comment by Kabouik** [comment]
es, that seems to be much faster with ~45 ms. I guess it's due to my Fish plugins and config, but it usually is a non issue because that time is taken only when opening the terminal emulator.

Would there be a way to make fzf only rely on sh for FZF_POS, with say `"execute(sh  -c 'echo FZF_POS > /tmp/fzp-line')"`?

**Comment by junegunn** [comment]
If I were you, I would restructure my fish config so that those plugins are not loaded in non-interactive sessions.

https://github.com/junegunn/fzf/issues/3016#issuecomment-1286526019

> Would there be a way to make fzf only rely on sh

* `SHELL=bash fzf`
* `fzf --with-shell 'bash -c'`

**Comment by Kabouik** [comment]
Great, thanks, for both answers (`--with-shell`, which I missed, and `status is-interactive`)!
