### ISSUE TITLE
Change tagline

### ISSUE THREAD

**Issue by chad-fossa** [junegunn/fzf#3941]
### Checklist

- [X] I have read through the manual page (`man fzf`)
- [X] I have searched through the existing issues
- [X] For bug reports, I have checked if the bug is reproducible in the latest version of fzf

### Output of `fzf --version`

0.50.0 (brew)

### OS

- [ ] Linux
- [X] macOS
- [ ] Windows
- [ ] Etc.

### Shell

- [ ] bash
- [X] zsh
- [ ] fish

### Problem / Steps to reproduce

When I go to your github page, I do not see this awesome tagline:

"Ctrl-R never tasted so good"

Expected behavior: your github is updated to prominately display this new tagline.

**Comment by junegunn** [comment]
Thanks! fzf is much more than a CTRL-R booster, you end up using it for all kinds of things :)
