### ISSUE TITLE
Request: Add a match whole word option

### ISSUE THREAD

**Issue by fiso64** [junegunn/fzf#3943]
I often find that fzf keeps results which are almost surely unwanted. When I search for `hello` it will display any line that contains these characters even if they appear separately in distinct words along the entire line. While these results are deprioritized they still clutter the list and slow me down, especially if I'm looking for something that doesn't actually exist in the list (in which case I need to be able to quickly tell at a glance that it in fact does not exist).

When I search `cat dog`, I'd like to match `cat and dog` but not `can go with dog` or `c/a/t`

This has already been requested in #284, but I found the answer unsatisfying for the following reasons:

1. I have to remember to add an apostrophe `'`, and I have to put it at the start of every word in my query. Instead, I would like to configure this mode to be on by default.
2. It does not allow me to match whole words ignoring case, which is what I want 9 times out of 10.

**Comment by junegunn** [comment]
That's the point of a "fuzzy finder". You don't have to type in the whole `cat dog`, instead you can quickly type in `cado` and bring the most relevant match to the top position, press enter, done. No vertical cursor movement. The whole process takes less than a couple of seconds most of the time. Yes, the list will contain many irrelevant matches, but does that matter? It's similar to how we use a search engine. No one clicks on pages on page 13.

> configure this mode to be on by default

You can add `--exact` to your `$FZF_DEFAULT_OPTS`.

https://github.com/junegunn/fzf?tab=readme-ov-file#search-syntax

**Comment by junegunn** [comment]
> Do people really search `cado` without a space when they want to find `cat dog`?

Yes, I do it all the time, and it's better to **not** type a space in many cases.

https://junegunn.github.io/fzf/search-syntax/#how-to-get-better-results

> it does not ignore case

What do you mean? The default is smart-case match.

> Maybe `--exact-ignore-case`?

Please read `man fzf`.
