### ISSUE TITLE
FZF + interactive RipGrep deadlock

### ISSUE THREAD

**Issue by widogg** [junegunn/fzf#3944]
### Checklist

- [X] I have read through the manual page (`man fzf`)
- [X] I have searched through the existing issues
- [X] For bug reports, I have checked if the bug is reproducible in the latest version of fzf

### Output of `fzf --version`

0.54.1 (50fa90d)

### OS

- [X] Linux
- [ ] macOS
- [ ] Windows
- [ ] Etc.

### Shell

- [X] bash
- [ ] zsh
- [ ] fish

### Problem / Steps to reproduce

I've been using a slightly modified function of [this command](https://github.com/junegunn/fzf/blob/master/ADVANCED.md#switching-to-fzf-only-search-mode), I have this bash function
```bash
fif () {
  local RG_PREFIX INITIAL_QUERY

  RG_PREFIX="rg --column --line-number --no-heading --color=always --smart-case "
  INITIAL_QUERY="${*:-}"

  fzf --disabled --layout=reverse --query "$INITIAL_QUERY" \
    --bind "start:reload:$RG_PREFIX {q}" \
    --bind "change:reload:sleep 0.1; $RG_PREFIX {q} || true" \
    --color "hl:-1:underline,hl+:-1:underline:reverse" \
    --delimiter : \
    --preview 'batcat --style=header,numbers --wrap=never --color=always {1} --highlight->
    --preview-window 'right,60%,+{2}+3/3,~1' \
    --bind 'enter:become(subl -n {1}:{2})'
}
```

So I can, while in bash, either do `fif` or `fif <string>` to start a find-in-files with ripgrep.

This has been working for a while, but now fails catastrophically:
```
fatal error: all goroutines are asleep - deadlock!

goroutine 1 [sync.Cond.Wait]:
sync.runtime_notifyListWait(0xc00002e950, 0x0)
	runtime/sema.go:527 +0x14c
sync.(*Cond).Wait(0xc0000106c0?)
	sync/cond.go:70 +0x8c
github.com/junegunn/fzf/src/util.(*EventBox).Wait(0xc0000106c0, 0xc0000e3d80)
	github.com/junegunn/fzf/src/util/eventbox.go:31 +0x5d
github.com/junegunn/fzf/src.Run(0xc0000c2000)
	github.com/junegunn/fzf/src/core.go:310 +0x1996
main.main()
	github.com/junegunn/fzf/main.go:99 +0x405

goroutine 6 [sync.Cond.Wait]:
sync.runtime_notifyListWait(0xc00002e9d0, 0x0)
	runtime/sema.go:527 +0x14c
sync.(*Cond).Wait(0x0?)
	sync/cond.go:70 +0x8c
github.com/junegunn/fzf/src/util.(*EventBox).Wait(0xc000010708, 0xc000052768)
	github.com/junegunn/fzf/src/util/eventbox.go:31 +0x5d
github.com/junegunn/fzf/src.(*Matcher).Loop(0xc000072240)
	github.com/junegunn/fzf/src/matcher.go:66 +0xab
created by github.com/junegunn/fzf/src.Run
	github.com/junegunn/fzf/src/core.go:244 +0x13ea

goroutine 7 [chan receive]:
github.com/junegunn/fzf/src.(*Terminal).Loop(0xc0000e8800)
	github.com/junegunn/fzf/src/terminal.go:3351 +0x51
created by github.com/junegunn/fzf/src.Run
	github.com/junegunn/fzf/src/core.go:259 +0x150f
```

**Comment by junegunn** [comment]
> ```shell
>  --highlight->
> ```

The command you posted is broken. Please correct it. Also, do you have anything in your `$FZF_DEFAULT_OPTS`?

**Comment by junegunn** [comment]
Looks like you have adaptive height option in your `$FZF_DEFAULT_OPTS`. I can reproduce the problem with this simple command.

```sh
fzf --bind 'start:reload:ls' --height ~100%
```

**Comment by widogg** [comment]
Hi! I guess you were too fast to fix this and I didn't even managed to see what you were asking 😅 .

Thanks for fixing this bug, I'll wait until a new version is out to test and post back. I guess you no longer need me to post the full command (sorry, I didn't noticed it was truncated) or the defaults.

Have a nice week :)

**Comment by junegunn** [comment]
https://github.com/junegunn/fzf/releases/tag/v0.54.3

**Comment by widogg** [comment]
Just tried it, it works! bugfioxed, thanks a lot :)
