### ISSUE TITLE
`fzf --tmux bottom` opens tmux popup on the top

### ISSUE THREAD

**Issue by Song-Tianxiang** [junegunn/fzf#3948]
### Checklist

- [X] I have read through the manual page (`man fzf`)
- [X] I have searched through the existing issues
- [X] For bug reports, I have checked if the bug is reproducible in the latest version of fzf

### Output of `fzf --version`

0.54.3 (brew)

### OS

- [ ] Linux
- [X] macOS
- [ ] Windows
- [ ] Etc.

### Shell

- [ ] bash
- [ ] zsh
- [X] fish

### Problem / Steps to reproduce

`fzf --tmux bottom` open tmux popup on the top instead of bottom. It works just like `fzf --tmux top`.

**Comment by junegunn** [comment]
It works as expected for me. What's the version of your tmux? `tmux -V`

**Comment by Song-Tianxiang** [comment]
It's tmux 3.4

**Comment by Song-Tianxiang** [comment]
I have to comment two config lines in my .tmux.conf to make it work as expected.
```
set -g status-position top
set -g status off
```

If either setting is present in my .tmux.conf, `fzf --tmux bottom` will result in a popup appearing at the top.

**Comment by junegunn** [comment]
I see. `bottom` option translates to `-yS` option to put the fzf popup right above the status line, and I didn't know it was possible to change the location of the status line.

**Comment by junegunn** [comment]
Looks like I can replace `-yS` with something like `-y99999`.
