### ISSUE TITLE
Impossible to get "sudo su" to be prioritized

### ISSUE THREAD

**Issue by henriquebecker91** [junegunn/fzf#3949]
### Checklist

- [X] I have read through the manual page (`man fzf`)
- [X] I have searched through the existing issues
- [ ] For bug reports, I have checked if the bug is reproducible in the latest version of fzf

### Output of `fzf --version`

0.53.0 (c4a9ccd6)

### OS

- [X] Linux
- [ ] macOS
- [ ] Windows
- [ ] Etc.

### Shell

- [X] bash
- [ ] zsh
- [ ] fish

### Problem / Steps to reproduce

One of the most frequent things I search with CTRL+R (in bash) is `sudo su` so I get the last `sudo su some_user` command I inputted. However, since installing fzf and configuring it to work with bash, I perceived that fzf seems to not make any difference between the inputs `sudo` or `sudo su` (both give exactly the same results in the same order) and I have a LOT of lines starting with `sudo` that do not have `su` in the sequence, what basically renders the search completely useless to me.

I tried to fix it using the `'` operator at the start of the search line (`'sudo su`): it did not work.
I tried to change the tiebreaker to "begin" (because initially I thought that it was finding "su" at another point down the line, but in fact it finds "su" inside "sudo"): it did not work.

So my question is: is there a way to avoid this behaviour, or is fzf completely useless if it happens by chance that the command you are interested in is a substring of another more common command and both are used in the same line?

**Comment by junegunn** [comment]
Have you tried `sudosu`?

https://junegunn.github.io/fzf/search-syntax/#how-to-get-better-results

**Comment by henriquebecker91** [comment]
Ohhh, ok. That is a little counterintuitive, and I will need to unlearn the behavior of putting spaces between commands (what is kinda hard, as outside of fzf they are still needed), but I think this fixes my problem. There is no option that disallows distinct words from matching for the exact same substring in the history line? If it existed, I would prefer that, as I see it as a more robust option.

**Comment by junegunn** [comment]
There is an option to disable "extended-search mode", but I don't recommend that, because it's really powerful once you get the hang of it. `susucp !some_user jl$`
