### ISSUE TITLE
Wrong list scrolling with --read0 and --height

### ISSUE THREAD

**Issue by leo-arch** [junegunn/fzf#3950]
### Checklist

- [X] I have read through the manual page (`man fzf`)
- [X] I have searched through the existing issues
- [X] For bug reports, I have checked if the bug is reproducible in the latest version of fzf

### Output of `fzf --version`

0.54.3 (af4917db)

### OS

- [X] Linux
- [ ] macOS
- [ ] Windows
- [ ] Etc.

### Shell

- [X] bash
- [X] zsh
- [X] fish

### Problem / Steps to reproduce

The list of files is unnecessarily scrolled down when running with `--read0` and `--height`, even when `height` is set to the exact required number. Example:

```sh
printf "file1\0file2\0file3\0" | fzf --height=4 --read0 --inline-info --layout=reverse-list
```
This correctly generates the window:

```
>  file1
   file2
   file3
>   < 3/3
```
But, when you move down to the third entry, the list is scrolled down showing only `file2`, `file3`, **and an extra empty line**:

```
   file2
>  file3

>   < 3/3
```

The expected behavior would be rather:

```
   file1
   file2
>  file3
>   < 3/3
```
This only happens with `--read0`. When reading new line characters instead of NUL, it works as expected:

```sh
printf "file1\nfile2\nfile3\n" | fzf --height=4 --inline-info --layout=reverse-list
```

**Comment by junegunn** [comment]
Thanks for the report. It should be fixed now. Let me know if you still see the problem.

**Comment by leo-arch** [comment]
Thanks @junegunn! Working as expected now.
