### ISSUE TITLE
 Help creating custom fuzzy seach command script. 

### ISSUE THREAD

**Issue by mateo-covacho** [junegunn/fzf#3954]
### Checklist

- [X] I have read through the manual page (`man fzf`)
- [X] I have searched through the existing issues
- [X] For bug reports, I have checked if the bug is reproducible in the latest version of fzf

### Output of `fzf --version`

0.52.1 (0.52.1)

### OS

- [X] Linux
- [ ] macOS
- [ ] Windows
- [ ] Etc.

### Shell

- [ ] bash
- [X] zsh
- [ ] fish

### Problem / Steps to reproduce

I want to interactively query nix pkgs using the nix-search command provided by `nix-search-cli`
Not really experiaenced in cli tools any ideas to make this work ?

![image](https://github.com/user-attachments/assets/9381b577-3a85-4679-8b6f-bf8c333ce6a9)

I have tried setting the FZF_DEFAULT_COMMAND to nix-search and get 

![image](https://github.com/user-attachments/assets/e2fc2945-fc42-46f6-a053-fcc6f6fc257d)

**Comment by LangLangBart** [comment]
You could try working with `events`, e.g., the `change` event is triggered when the query string changes, and `{q}` is the query placeholder. See `man fzf` for more infos.

```sh
bsf(){
  : | fzf --bind "change:reload:brew search --formula {q}" \
    --disabled \
    --preview 'brew info {}' \
    --prompt 'Search for brew formula > '
}
```

---

The function can be enhanced with the ability to switch between searching for formulas and using `fzf` for filtering, which is `disabled`. See the explanation of the syntax in the **ADVANCED.md**[^1].

> [!NOTE]
> Also, check the **CHANGELOG.md**[^2] to see when a feature was added if you are using an older fzf version, e.g. the `FZF_PROMPT` variable only came with `0.46.0`.

```sh
bsf() {
  local src_cmd="reload:brew search --formula {q}"
  local default_prompt="Search for brew formula > "
  fzf --bind "change:$src_cmd" \
    --bind "start:$src_cmd" \
    --disabled \
    --bind "ctrl-t:transform:[[ \$FZF_PROMPT != \"$default_prompt\" ]] &&
      echo 'rebind(change)+change-prompt($default_prompt)+disable-search' ||
      echo 'unbind(change)+change-prompt(Filtering with fzf > )+enable-search'" \
    --preview 'brew info {}' \
    --query "${1:-fzf}" \
    --prompt "$default_prompt"
}
```

[^1]: [fzf/ADVANCED.md at master · junegunn/fzf · GitHub](https://github.com/junegunn/fzf/blob/master/ADVANCED.md#toggling-with-a-single-key-binding)
[^2]: [fzf/CHANGELOG.md at master · junegunn/fzf · GitHub](https://github.com/junegunn/fzf/blob/master/CHANGELOG.md#0460)

**Comment by 3timeslazy** [comment]
I also had the same idea and made a tool that does that: https://github.com/3timeslazy/nix-search-tv
