### ISSUE TITLE
[Feature Request] Handle pytest command the same as python

### ISSUE THREAD

**Issue by DavideCanton** [junegunn/fzf#3957]
Hi, thanks for this wonderful command!

Is there any chance that a completion for the command `pytest` could be included by default like the one for the `python` command? Since it's very common for pytest to be run using files/directories as inputs

**Comment by junegunn** [comment]
I'm assuming you're a bash user, and you can set it up as explained in https://github.com/junegunn/fzf?tab=readme-ov-file#supported-commands

**Comment by DavideCanton** [comment]
I know, what I suggested is to add it to the built-in command completions.

**Comment by junegunn** [comment]
I see, but if we add more commands to the default list, the time it takes to load the script increases accordingly, and it affects the other users who don't really use pytest (which I'm one of them), so I'm reluctant to grow the default list.

**Comment by DavideCanton** [comment]
I see, but then I don't understand why I'm having python and java already registered, since I don't use java either.

**Comment by junegunn** [comment]
Yeah, it's already not ideal, so let's not make it worse.

**Comment by junegunn** [comment]
Having said that, maybe we could provide `path` as the default completion.

https://stackoverflow.com/a/49069150/755334

**Comment by junegunn** [comment]
```sh
complete -D -F _fzf_path_completion -o default -o bashdefault 2> /dev/null
```

Hmm, unfortunately, this will likely break bash-completion, which sets its dynamic completion loader as the default completion function.

https://github.com/scop/bash-completion/blob/2dab63379b90619f93873976944f4f9ad338dc0d/bash_completion#L3260-L3271

**Comment by junegunn** [comment]
```sh
__fzf_default_completion() {
  __fzf_generic_path_completion _fzf_compgen_path "-m" "" "$@"
  if [[ $? -eq 124 ]]; then
    _fzf_setup_completion path "$1"
    return 124
  fi
}

complete -D -F __fzf_default_completion -o default -o bashdefault 2> /dev/null
```

This version works slightly better, that it handles dynamic completion loader.

```sh
# No completion is defined
complete | grep pytest

# Fuzzy completion works
pytest **<tab>

# Regular completion; triggers dynamic completion loader
pytest <tab>

# Completion function for pytest is loaded
complete | grep pytest
  # complete -F _comp_cmd_pytest py.test
  # complete -F _comp_cmd_pytest py.test-3
  # complete -F _comp_cmd_pytest py.test-2
  # complete -F _comp_cmd_pytest pytest-3
  # complete -F _comp_cmd_pytest pytest-2
  # complete -F _fzf_path_completion pytest

# Fuzzy completion still works
pytest **<tab>

# Regular completion also works
pytest <tab>

# However, fuzzy completion for pytest-2, pytest-3, etc stops working
pytest-2 **<tab>
```

**Comment by junegunn** [comment]
See #3958

**Comment by thiago4455** [comment]
Thank you very much for this patch. I was about to open a Issue, just to see that it was solved on this week release
