### ISSUE TITLE
Requires tmux 3.2 or above not only popup window

### ISSUE THREAD

**Issue by aropan** [junegunn/fzf#3959]
### Checklist

- [X] I have read through the manual page (`man fzf`)
- [X] I have searched through the existing issues
- [X] For bug reports, I have checked if the bug is reproducible in the latest version of fzf

### Output of `fzf --version`

0.54.3 (af4917d)

### OS

- [X] Linux
- [X] macOS
- [ ] Windows
- [ ] Etc.

### Shell

- [X] bash
- [ ] zsh
- [ ] fish

### Steps
* Use fzf inside tmux
```
export FZF_TMUX=1
```
* CTLR+R to call `__fzf_history__`
* Choose command with ENTER  or CTRL+C (or ESC)

### Expected

Return to terminal (tmux window) with command or empty command.

### Result

If using `tmux 3.0a` (latest version ubuntu 20.04) then process of return freezes (in both cases). After update tmux to `tmux 3.4` everything works as it should.

### Problem

I looked a little to see what the reason might be. And found problem with command:

```
tmux split-window -c /home/username -l 40% 'bash -c '\''exec -a fzf bash /tmp/fzf-args-3565'\''' ';' set-option -p synchronize-panes off ';' set-option -p remain-on-exit off
```

Here:

https://github.com/junegunn/fzf/blob/c423c496a15b96cfc3c3fbd09135bcdc0c8e6b6e/bin/fzf-tmux#L239-L242

For `tmux 3.4` works well, for `tmux 3.0.a`:

```
create pane failed: -l invalid
```

Without `%` for `-l` arg works well also (40 use as number of lines). So I think `tmux 3.0a` don't support percentage for `-l`.

**Comment by junegunn** [comment]
Probably caused by https://github.com/junegunn/fzf/commit/edee2b753cdd08b7927213af3899f7b6f455a606
