### ISSUE TITLE
Force fzf to tmux in Neovim

### ISSUE THREAD

**Issue by firedev** [junegunn/fzf#397]
Hi,

Is there a way to force FZF to open a tmux split in Neovim? I have mapped exit from terminal to `<esc><esc>` plus Neovim changes the size of buffes every time which is pretty annoying.

So I think I'd rather have it in Tmux as it was in Vim, but I can't seem to find a way to do it. Thanks.

**Comment by justinmk** [comment]
> I have mapped exit from terminal to <esc><esc>

You could do a buffer-local `:tnoremap` mapping for fzf, I think, which maps a single `<esc>` to quit fzf.

> Neovim changes the size of buffes every time

It changes them permanently, or only while fzf is showing?

**Comment by firedev** [comment]
Thanks @justinmk , any details on how to do the local terminal mapping? I would need some help here.

Each time FZF opens it shifts horizontal splits up. so after a while if I have quickfix and whatnot my work buffer shrinks up to a single line, then I do 'Ctrl-W-o` and start over.

**Comment by justinmk** [comment]
@firedev If the `setf fzf` suggestion is accepted the configuration would look like this:

    au FileType fzf tnoremap <buffer> <esc> [command to quit fzf/terminal]

> if I have quickfix and whatnot my work buffer shrinks up to a single line,

You're right, I never noticed that because I usually don't have more than 1 horizontal split (and I am not fastidious about windows staying the same size, I slap them around as needed). Looks like this is another case for providing an API to [save the window layout](https://github.com/neovim/neovim/issues/2006).

**Comment by firedev** [comment]
@justinmk Thanks, however it looks like there is no FileType fzf. It opens a new terminal window and filetype is empty for it.

**Comment by junegunn** [comment]
For some reason, neovim pane becomes blank while I'm running `:call system('echo hello | fzf-tmux')`, and `:!fzf` doesn't work on neovim. `:!fzf-tmux` might work, but it doesn't work nicely on ordinary vim. So terminal is the only sane option.

`setf fzf` sounds nice. Currently fzf.vim project sets statusline on `TermOpen`.  See: https://github.com/junegunn/fzf.vim/blob/master/plugin/fzf.vim#L104

**Comment by justinmk** [comment]
@junegunn system() cannot run interactive commands in Neovim.

**Comment by junegunn** [comment]
@justinmk Yeah, but fzf-tmux opens a new pane and all the interactivity will happen there.

**Comment by junegunn** [comment]
https://github.com/junegunn/fzf/commit/5769d3867dcb6a7b79549da7d3269140c1fc3332

**Comment by firedev** [comment]
Sorry guys, I can't seem to make it work. I mean any commands I add are just being typed into FZF prompt. I press `<esc>` then it waits a second and types whatever is after `<esc>` straight to FZF.

**Comment by justinmk** [comment]
@firedev I verified that this works:

    :au FileType fzf tnoremap <nowait><buffer> <esc> <c-g>

Notice that `<nowait>` will ignore any other `<esc>`-prefixed mappings you might have, while in fzf (this is  what you want). `<c-g>` is one of way exiting fzf, another way would be `<c-c>` and maybe others.

**Comment by firedev** [comment]
Thank you! Feels great so far.
