### ISSUE TITLE
fzf version for linux too outdated

### ISSUE THREAD

**Issue by KES777** [junegunn/fzf#3971]
### Checklist

- [X] I have read through the manual page (`man fzf`)
- [X] I have searched through the existing issues
- [ ] For bug reports, I have checked if the bug is reproducible in the latest version of fzf

### Output of `fzf --version`

0.29 (devel)

### OS

- [X] Linux
- [ ] macOS
- [ ] Windows
- [ ] Etc.

### Shell

- [X] bash
- [ ] zsh
- [ ] fish

### Problem / Steps to reproduce

```
$ sudo apt list -a fzf
Listing... Done
fzf/jammy,now 0.29.0-1 amd64 [installed]
```

**Comment by junegunn** [comment]
There's nothing I can do because I'm not the package maintainer. Consider downloading the official binary from the releases page and putting it in your `$PATH`.

https://github.com/junegunn/fzf/releases
