### ISSUE TITLE
"Error: Not support reporting screen sizes in pixels" when previewing images in kitty from tmux with `--tmux` option.

### ISSUE THREAD

**Issue by rockyzhang24** [junegunn/fzf#3972]
### Checklist

- [X] I have read through the manual page (`man fzf`)
- [X] I have searched through the existing issues
- [X] For bug reports, I have checked if the bug is reproducible in the latest version of fzf

### Output of `fzf --version`

0.54.3 (af4917d)

### OS

- [ ] Linux
- [X] macOS
- [ ] Windows
- [ ] Etc.

### Shell

- [ ] bash
- [X] zsh
- [ ] fish

### Problem / Steps to reproduce

1. Launch tmux
2. Run `fzf --tmux 80%,85% --preview "fzf-preview.sh {}"
3. When previewing an image, an error will pop up in the preview window. Please see the screenshot below. 
<img width="1728" alt="image" src="https://github.com/user-attachments/assets/ce9aa4a8-1a5e-41b9-9160-d4bf3c8244af">

The terminal I am using is kitty (the latest version 0.36.0). This issue happens only by giving `--tmux` option.

**Comment by rockyzhang24** [comment]
Update:
Found this is a bug from tmux (ref: https://github.com/kovidgoyal/kitty/issues/7165). @junegunn Do you have any workaround? Feel free to close this. Thank you so much.

**Comment by junegunn** [comment]
Unfortunately, no. No progress since [my last comment](https://github.com/kovidgoyal/kitty/issues/7165#issuecomment-1977967827).
