### ISSUE TITLE
feature request: add support for `-S fg=<color> -s fg=<color>` tmux popup flags in fzf-tmux

### ISSUE THREAD

**Issue by blacktop** [junegunn/fzf#3973]
### Checklist

- [X] I have read through the manual page (`man fzf`)
- [X] I have searched through the existing issues
- [X] For bug reports, I have checked if the bug is reproducible in the latest version of fzf

### Output of `fzf --version`

latest

### OS

- [ ] Linux
- [X] macOS
- [ ] Windows
- [ ] Etc.

### Shell

- [ ] bash
- [ ] zsh
- [X] fish

### Problem / Steps to reproduce

I'd love if you added support for `-S fg=<color> -s fg=<color>` tmux popup flags in fzf-tmux

**Comment by blacktop** [comment]
I noticed that if I just removed the `-B` arg from the `tmux popup` that I could at least set the boarder via a theme global setting etc as well

**Comment by junegunn** [comment]
fzf-tmux is being phased out in favor of `--tmux` option. You can use `--color` option to customize the colors.

```sh
fzf --tmux 70% --color 'bg:#000000,fg:#ffffff,border:green' --border thinblock
```

See https://github.com/junegunn/fzf/blob/master/CHANGELOG.md#0530
