### ISSUE TITLE
Support elvish shell condition in --bind

### ISSUE THREAD

**Issue by tmpm697** [junegunn/fzf#3974]
### Checklist

- [X] I have read through the manual page (`man fzf`)
- [X] I have searched through the existing issues
- [X] For bug reports, I have checked if the bug is reproducible in the latest version of fzf

### Output of `fzf --version`

0.54.3 (v0.54.3)

### OS

- [ ] Linux
- [X] macOS
- [ ] Windows
- [ ] Etc.

### Shell

- [ ] bash
- [ ] zsh
- [ ] fish

### Problem / Steps to reproduce

[Elvish ](https://github.com/elves/elvish) is non posix shell.

I tried to replace shell condition in `fzf --bind 'ctrl-d:<zsh shell here>` by elvish shell but can't

Any interest in supporting other popular shells?

**Comment by junegunn** [comment]
fzf uses `$SHELL` to start external processes. So you can either temporarily change it (i.e. `SHELL=zsh fzf ...`) or use `--with-shell` option. e.g. `fzf --with-shell 'zsh -c' ...`

**Comment by junegunn** [comment]
Your issue lacks the exact steps to reproduce the problem, so it's hard to understand what your real problem is.

Please don't forget to attach steps to reproduce the problem when you open an issue. And please don't assume that the maintainers know anything about the thing you mention, in this case, elvish. I mean, the steps should be easy to follow even for someone doesn't even know about elvish.

**Comment by tmpm697** [comment]
> Your issue lacks the exact steps to reproduce the problem, so it's hard to understand what your real problem is.
> 
> Please don't forget to attach steps to reproduce the problem when you open an issue. And please don't assume that the maintainers know anything about the thing you mention, in this case, elvish. I mean, the steps should be easy to follow even for someone doesn't even know about elvish.
> 
> That said, you'll likely get better answers from elvish issue tracker than here.

that was a bad assumption, here is produce steps:
```
elvish
var flag = $false
echo "1\n2\n3\n4" | fzf --bind 'ctrl-g:reload('(if $flag { set flag = $true; print "fd . -H" } else { set flag = $false; print "fd ." })')'
# press ctrl-g either one or two times
echo $flag
# always give output $false
```
--> expecting `$flags` should be updated to `$false` or `$true` base on number of press `ctrl-g`, meaning `(if $flag { set flag = $true; print "fd . -H" } else { set flag = $false; print "fd ." })` evaluated each time press `ctrl-g`.

**Comment by tmpm697** [comment]
@junegunn i also tried with 
```
echo "1\n2\n3\n4" | fzf --with-shell 'elvish -c' --bind 'ctrl-g:reload('(if $flag { set flag = $true; print "fd . -H" } else { set flag = $false; print "fd ." })')'
```
it gave same result as without `--with-shell 'elvish -c'`

**Comment by tmpm697** [comment]
it would be nice if this `'ctrl-g:reload(if $flag { set flag = $true; print "fd . -H" } else { set flag = $false; print "fd ." })'` (no `'` around elvish expression) can be eval by fzf using `elvish` shell

currently i have to `if-else` and write to file to get what i want which cost around 10-30ms

**Comment by junegunn** [comment]
I don't think your script is correct and it's not an issue of fzf.

You can't access the variable from a child process. And generally a child process has no direct way to alter the state of the parent process. You need to find other ways to pass the information, e.g. writing a new state to a temp file.

```elvish
~> var flag = $false

~> elvish -c 'set flag = $true'
Compilation error: cannot find variable $flag
  code from -c:1:5-8: set flag = $true
Exception: elvish exited with 2
  [tty 3]:1:1-28: elvish -c 'set flag = $true'

~> elvish -c 'echo $flag'
Compilation error: variable $flag not found
  code from -c:1:6-10: echo $flag
Exception: elvish exited with 2
  [tty 4]:1:1-22: elvish -c 'echo $flag'

~> elvish -c 'var flag = $true'

~> echo $flag
$false
```

**Comment by tmpm697** [comment]
> `'ctrl-g:reload(if $flag { set flag = $true; print "fd . -H" } else { set flag = $false; print "fd ." })'` (no `'` around elvish expression)

my issue is that even with this:
```
'ctrl-g:reload(if $flag { set flag = $true; print "fd . -H" } else { set flag = $false; print "fd ." })' (no ' around elvish expression)
```
--> I need the `elvish` expression evaluate, how to? do we need add a `support` for it to work as i tried with `--with-shell 'elvish -c'` it didn't work.

and yes, if above work, i can store state to a tempfile in that elvish expression in which i can still make it free cost get/store state file.

**Comment by junegunn** [comment]
`Print`ing command instead of executing it in `reload` is obviously a mistake.

```sh
fzf --bind 'start:reload:echo seq 100'
fzf --bind 'start:reload:seq 100'
```

**Comment by tmpm697** [comment]
> `Print`ing command instead of executing it in `reload` is obviously a mistake.
> 
> ```shell
> fzf --bind 'start:reload:echo seq 100'
> fzf --bind 'start:reload:seq 100'
> ```

can you try this? `echo "1\n2\n3\n4" | fzf --with-shell 'elvish -c' --bind 'ctrl-g:(use str; use re)'` --> which result error `unknown action: (use str; use re)` --> should it use `elvish` instead of bash/zsh here when run `use str; use re`?
