### ISSUE TITLE
unknown option: --bash

### ISSUE THREAD

**Issue by roukmoute** [junegunn/fzf#3975]
### Checklist

- [X] I have read through the manual page (`man fzf`)
- [X] I have searched through the existing issues
- [X] For bug reports, I have checked if the bug is reproducible in the latest version of fzf

### Output of `fzf --version`

0.38.0 (debian)

### OS

- [X] Linux
- [ ] macOS
- [ ] Windows
- [ ] Etc.

### Shell

- [X] bash
- [X] zsh
- [ ] fish

### Problem / Steps to reproduce

```
~$ eval "$(fzf --bash)"
unknown option: --bash
```

I've also tried with zsh shell and have the same things:

```
~$ source <(fzf --zsh)
unknown option: --zsh
```

Also tried with git clone and have the same things.

**Comment by junegunn** [comment]
0.38.0 (debian) is too old, and it doesn't have the option. 

> Also tried with git clone and have the same things.

You probably misconfigured it. See `fzf --version` or `which fzf`.
