### ISSUE TITLE
on windows, using gitbash/mintty, fzf reverse history search (ctrl-r) hangs the terminal indefinitely

### ISSUE THREAD

**Issue by tycobbb** [junegunn/fzf#3976]
### Checklist

- [X] I have read through the manual page (`man fzf`)
- [X] I have searched through the existing issues
- [X] For bug reports, I have checked if the bug is reproducible in the latest version of fzf

### Output of `fzf --version`

0.54.3 (af4917d)

### OS

- [ ] Linux
- [ ] macOS
- [X] Windows
- [ ] Etc.

### Shell

- [X] bash
- [ ] zsh
- [ ] fish

### Problem / Steps to reproduce

on windows, fzf reverse history search hangs the gitbash mintty terminal indefinitely, causing it to become unresponsive and have to be forced closed.

### expected behavior

the fzf reverse history search allows user input to search through history.

### actual behavior

the fzf reverse history search hangs the terminal program indefinitely, user input no longer works, signals can't be sent via ctrl-c or otherwise, and the terminal has to be forcibly closed.

### steps to reproduce
- on windows 11, git/bash 2.4.0 installed via choco
- install fzf via choco or winget
- open the gitbash terminal (mintty)
- invoke `fzf` directly, verify it responds to input and works fine
- source the fzf setup (`eval "$(fzf --bash)"`) via .bashrc or manually in session
- press ctrl+r

**Comment by Konfekt** [comment]
Oh, it's v.2.45.2.windows.1. Does updating from 2.40 solve this issue?

**Comment by Konfekt** [comment]
Pardon, 2.4.0 (seems rather old).

**Comment by tycobbb** [comment]
upgrading to 2.46,.0 the latest release of git for windows, fixed the problem :)
