### ISSUE TITLE
The `--txux` flag ignored when set from the config file

### ISSUE THREAD

**Issue by kfernandez31** [junegunn/fzf#3977]
### Checklist

- [X] I have read through the manual page (`man fzf`)
- [X] I have searched through the existing issues
- [X] For bug reports, I have checked if the bug is reproducible in the latest version of fzf

### Output of `fzf --version`

0.54.0 (brew)

### OS

- [ ] Linux
- [X] macOS
- [ ] Windows
- [ ] Etc.

### Shell

- [ ] bash
- [X] zsh
- [ ] fish

### Problem / Steps to reproduce

If I run `fzf --tmux=center` from within tmux with an empty config file, it works as expected, putting the program in a tmux popup. 

If I run `fzf` instead having the contents of my config file be just the `--tmux=center` argument, it does not, as if it's ignored, and so stays at the default location, the bottom of the screen. The remaining flags I tested work in both cases and removing them does not help, so it's not as if the `--tmux` flag conflicts with any other.

It would be nice to be able to rely on the config file completely instead of leaving out one flag to be passed manually.

**Comment by junegunn** [comment]
I'm not sure if I follow you. Please post the exact steps to reproduce the problem, so I can try reproducing the problem you're experiencing.

**Comment by kfernandez31** [comment]
1. Start a shell with tmux.
2. Run `fzf --tmux=center`. Observe `fzf` appearing as a tmux popup.
3. Place the line `--tmux=center` inside your `$FZF_DEFAULT_OPTS_FILE`, run `fzf`. Observe `fzf` appearing in the default location, below and not in the center. The flag is effectively ignored.

**Comment by kfernandez31** [comment]
The issue was due to using `--height` as well. Without it the behavior is correct. Thus closing.

**Comment by junegunn** [comment]
A good strategy is to have both `--height` and `--tmux`, but putting `--tmux` after `--height` so, when you're not on tmux, `--height` applies, but when you're on tmux, `--tmux` takes precedence over `--height`.
