### ISSUE TITLE
Stop the process being executed in readFromCommand when a completion is accepted

### ISSUE THREAD

**Issue by meboyce** [junegunn/fzf#398]
### Use Case

I've got a `$FZF_DEFAULT_COMMAND` which lists a small set of files which are actively being modified in my changelist and then starts a much longer listing of the project repository.

### Observed Behavior

I believe as a result of calling `defer listCommand.Wait()` FZF does not finish accepting my completion until after that command has returned.

### Desired Behavior

After I hit enter the completion should be accepted immediately and the command called to list files should be terminated.

**Comment by junegunn** [comment]
I don't think it is something that should be handled by fzf. What is your `$FZF_DEFAULT_COMMAND`? The program should terminate itself on SIGPIPE. You see, `find` or `ag` don't suffer the problem and stop immediately.

```sh
find / 2> /dev/null | fzf
ag -g "" / | fzf
```

`sleep` on the other hand, does not print to stdout, thus unaware if the pipe is closed.

```sh
sleep 60 | fzf
```

The following will terminate after 5 seconds with `Broken pipe` error.

```sh
ruby -e 'loop { puts :hello; $stdout.flush; sleep 5 }' | fzf
...
-e:1:in `flush': Broken pipe (Errno::EPIPE)
        from -e:1:in `block in <main>'
        from -e:1:in `loop'
        from -e:1:in `<main>'
```

**Comment by meboyce** [comment]
It's a bash script wrapping an internal utility which doesn't seem to handle SIGPIPE appropriately...

In my script I'm now using:
```shell
longrunningcommand 2> /dev/null | cut -c '2-' &
trap "kill -9 $!" SIGPIPE
```
which seems to have fixed it for me, thanks for the help :)
