### ISSUE TITLE
Sort by length with --disabled

### ISSUE THREAD

**Issue by CyberShadow** [junegunn/fzf#3985]
### Checklist

- [X] I have read through the manual page (`man fzf`)
- [X] I have searched through the existing issues
- [X] For bug reports, I have checked if the bug is reproducible in the latest version of fzf

### Output of `fzf --version`

0.54.3 (af4917db)

### OS

- [X] Linux
- [ ] macOS
- [ ] Windows
- [ ] Etc.

### Shell

- [ ] bash
- [ ] zsh
- [ ] fish

### Problem / Steps to reproduce

It doesn't look like there is any way to make `fzf` with `--disabled` sort entries in some way?

`--tiebreak=length` doesn't seem to have any effect.

For context, I have the following script to use `plocate` with `fzf`. It uses `plocate` for searching, so `--disabled` is being used, as `plocate` can search for substrings much faster than it would take it to dump and fzf to ingest a list of all files on the filesystem:

```bash
RG_PREFIX="plocate "
INITIAL_QUERY="${*:-}"
args=(
	fzf
	--disabled
	--query "$INITIAL_QUERY"
	--bind "start:reload:$RG_PREFIX {q}"
	--bind "change:reload:$RG_PREFIX {q} || true"
	--tiebreak=length  # no effect?
) ; "${args[@]}"
```

**Comment by junegunn** [comment]
No, with `--disabled`, fzf doesn't do any filtering or sorting. You have to feed the sorted list to fzf.

```sh
read -r -d '' SCRIPT <<'EOF'
grep {q} /usr/share/dict/words | awk '{ print length(), $0 }' | sort -n | awk '{print $2}'
EOF

fzf --disabled --bind "start:reload:$SCRIPT" --bind "change:reload:$SCRIPT"
```

**Comment by CyberShadow** [comment]
Thanks, though, it would be nice if it was possible to control sorting and filtering separately.
