### ISSUE TITLE
How to see the full content of a very long line?

### ISSUE THREAD

**Issue by lotabout** [junegunn/fzf#399]
In fzf, if a line(a file name for example) is very long, it will be showed with ellipsis. Is there a way to see the rest of the content?

<img width="406" alt="very long name" src="https://cloud.githubusercontent.com/assets/1527040/10863239/f76a6548-8001-11e5-968f-c4453c068631.png">

<img width="407" alt="ellipsis" src="https://cloud.githubusercontent.com/assets/1527040/10863240/fdf56f5c-8001-11e5-8c68-de5aa47c7585.png">

**Comment by junegunn** [comment]
Horizontal scrolling will occur if the end of the matched substring goes beyond the screen boundary. For example, if you type `oooooooo.....` or `.txt`, you'll notice fzf shows the end of the match by scrolling the entry. However, there's no manual way to scroll the entry horizontally.

It's really awkward, so I don't recommend, but one might consider doing something like `fzf --bind 'ctrl-p:execute(echo {} 1>&2; sleep 1)'`.

**Comment by Kabouik** [comment]
I don't intend to necropost that but since wrapping lines would be complicated (as discussed in other issues), I think your suggestion is actually not bad at all when combined with `read -rns1` instead of `sleep 1`, *i.e.*, `fzf --bind 'ctrl-p:execute(echo {} 1>&2; read -rsn1)'`.
