### ISSUE TITLE
Creating a bind that rebinds events / a way to toggle between 'rg --hidden' and 'rg' in ripgrep examples from fzf/ADVANCED.md

### ISSUE THREAD

**Issue by excited-bore** [junegunn/fzf#3998]
### Checklist

- [X] I have read through the manual page (`man fzf`)
- [X] I have searched through the existing issues
- [ ] For bug reports, I have checked if the bug is reproducible in the latest version of fzf

### Output of `fzf --version`

0.54.3 (af4917d)

### OS

- [X] Linux
- [ ] macOS
- [ ] Windows
- [ ] Etc.

### Shell

- [X] bash
- [ ] zsh
- [ ] fish

### Problem / Steps to reproduce

This might be not possible as for now, but if it is then I just have no idea how to achieve it.

From the snippets given in [fzf/ADVANCED.md](https://github.com/junegunn/fzf/blob/master/ADVANCED.md) I tried making something that would allow me to reset the binding for the 'change' event by invoking 'ctrl-t' in an attempt to create a toggle for showing/hiding hidden files from the results, but I failed horribly and I have no idea how to do this.

This is what I made from looking at the ripgrep examples in [fzf/ADVANCED.md](https://github.com/junegunn/fzf/blob/master/ADVANCED.md). It tries to 'rebind' the 'change' action by unbinding, attempting to change RG to RG_PREFIX/RG_PREFIX_HIDDEN and then rebinding 'change' in the hope that it would affect  ` --bind "change:reload:sleep 0.1; $RG {q} || true"`..

So my question is simply: is it even possible to create some kind of 'hidden file' toggle right now? And if so, how?

```
ripgrep-dir(){
    RG_PREFIX="rg --column --line-number --no-heading --color=always --smart-case"
    RG_PREFIX_HIDDEN="rg --column --line-number --hidden --no-heading --color=always --smart-case"
    RG=$RG_PREFIX
    INITIAL_QUERY="${*:-}"
    : | fzf --height 80% --ansi --disabled --query "$INITIAL_QUERY" \
        --bind "start:reload:$RG {q}" \
        --bind "ctrl-t:transform:[[ $RG =~ 'hidden' ]] && 
        echo \"unbind(change)+RG=$RG_PREFIX+rebind(change)\" ||
        echo \"unbind(change)+RG=$RG_PREFIX_HIDDEN+rebind(change)\"" \
        --bind "change:reload:sleep 0.1; $RG {q} || true" \
        --delimiter : \
        --preview 'bat --color=always {1} --highlight-line {2}' \
        --preview-window 'up,60%,border-bottom,+{2}+3/3,~3' \
        --bind "enter:become($EDITOR {1} +{2})"
}
```

**Comment by LangLangBart** [comment]
You could try to assign <kbd>⌃ Control</kbd> + <kbd>T</kbd> to check if the current `FZF_PROMPT` is not equal to the `DEFAULT_PROMPT`. If this is the case, change the prompt to the `DEFAULT_PROMPT` and reload normally with `RG_PREFIX`. Otherwise, change the prompt to a different prompt, e.g., `Dir (+hidden) > `, and reload the list with additional flags passed to your `RG_PREFIX`, for example, `RG_PREFIX --no-ignore --hidden`.

Then, in the `change` action, we can use the `FZF_PROMPT` to determine whether to execute the standard `RG_PREFIX` command or to include additional flags.

```sh
ripgrep-dir() {
  RG_PREFIX="rg --column --line-number --no-heading --color=always --smart-case"
  INITIAL_QUERY="${*:-}"
  DEFAULT_PROMPT="Dir > "
  fzf \
    --ansi \
    --bind "start:reload:$RG_PREFIX {q}" \
    --bind "ctrl-t:transform:[[  \$FZF_PROMPT != \"$DEFAULT_PROMPT\"  ]] &&
    echo \"change-prompt($DEFAULT_PROMPT)+reload:$RG_PREFIX {q} || true\" ||
    echo \"change-prompt(Dir (+hidden) > )+reload:$RG_PREFIX --no-ignore --hidden {q} || true\"" \
    --bind "change:transform:[[ \$FZF_PROMPT == \"$DEFAULT_PROMPT\"  ]] &&
    echo \"reload:sleep 0.1; $RG_PREFIX {q} || true\" ||
    echo \"reload:sleep 0.1; $RG_PREFIX --no-ignore --hidden {q} || true\"" \
    --bind "enter:become:$EDITOR {1} +{2}" \
    --delimiter : \
    --disabled \
    --height 80% \
    --preview 'bat --color=always {1} --highlight-line {2}' \
    --preview-window 'up,60%,border-bottom,+{2}+3/3,~3' \
    --prompt "$DEFAULT_PROMPT" \
    --query "$INITIAL_QUERY"
}
```

**Comment by excited-bore** [comment]
That works beautifully! That's also works as a great template for the fzf prompt in general. 
Many, many thanks for that!
