### ISSUE TITLE
.fzf.bash/__fsel doesn't use FZF_DEFAULT_COMMAND if set

### ISSUE THREAD

**Issue by stephenh** [junegunn/fzf#40]
It's hard-coded to use find, which surprised me because I'd set FZF_DEFAULT_COMMAND=ag -l -p "" and couldn't figure out why "cat <Ctrl-T>" was still including my .gitignore'd files. I assume this is not intentional?

**Comment by jez** [comment]
It'd be awesome if you added documentation for this variable at https://github.com/junegunn/fzf/blob/master/README.md#respecting-gitignore-hgignore-and-svnignore

Didn't realize this was a feature until I found this issue.

**Comment by junegunn** [comment]
@jez Will do, thanks.
