### ISSUE TITLE
Make --extended default

### ISSUE THREAD

**Issue by junegunn** [junegunn/fzf#400]
[Extended-search mode](https://github.com/junegunn/fzf#extended-search-mode) was added 2 years ago but is not enabled by default to this day which is a shame because it's just so good. I've always told people to put `-x` to their `$FZF_DEFAULT_OPTS`, but I'm afraid there are still a lot of users missing it out.

Therefore, I propose that we make it default. One should be able to disable it with `--no-extended` or `+x`.

Also, regarding `--extended-exact`, one might argue that "exactness" should be orthogonal to "extendedness". So I suggest the following changes:

- Replace `--extended-exact` (`-e`) with `--exact` (`-e`)
    - Since extended-search mode is now enabled by default. Using `-e` will have the same effect as before unless the user explicitly set `--no-extended`.
    - Leave `--extended-exact` for backward compatibility. It'll be the combination of `--extended` and `--exact`.

**Comment by netei** [comment]
Agree

**Comment by rgrinberg** [comment]
Thanks @junegunn I've been using fzf for quite a while and did not know about this :sob:

**Comment by junegunn** [comment]
@rgrinberg You'll like it :) Maybe I should rename the title of the section on the README page so that it's more prominent.
