### ISSUE TITLE
use fzf with commands like `fzf vim`

### ISSUE THREAD

**Issue by pvinis** [junegunn/fzf#401]
and if you do that, you get the fzf way of selecting a file, and when you press enter you open that file with vim. so basically add the file you found as the last arg of the command afterwards.
also check here https://getpicka.com/guide#install-cli
```
$ pi cd

Edit your selected file using vim

$ pi vim

Concatenate the file named “foo” and your selected file

$ pi cat foo

Count the number of lines matching the pattern “Info” in your selected file

$ grep Info "$(pi)" | wc -l 
```

**Comment by junegunn** [comment]
Isn't it something you can easily do with shell script?

```sh
pi() {
  local x
  x="$(fzf)" && "$@" "$x"
}
```

Though you'll have to adjust the source according to the command as different commands expect different things (`cd` expects directories not files).

And the last example doesn't even need any scripting:

```sh
grep Info "$(fzf)" | wc -l 
```
