### ISSUE TITLE
Question: `),` in options is not correctly parsed

### ISSUE THREAD

**Issue by phanen** [junegunn/fzf#4019]
### Checklist

- [X] I have read through the manual page (`man fzf`)
- [X] I have searched through the existing issues
- [X] For bug reports, I have checked if the bug is reproducible in the latest version of fzf

### Output of `fzf --version`

0.55.0 (fc693080)

### OS

- [X] Linux
- [ ] macOS
- [ ] Windows
- [ ] Etc.

### Shell

- [X] bash
- [X] zsh
- [X] fish

### Problem / Steps to reproduce

```sh
FZF_DEFAULT_OPTS= fzf --bind 'start:reload(echo "),")'
```
failed with `bind action not specified: ")`, which didn't work as expected like
```sh
FZF_DEFAULT_OPTS= fzf --bind start:reload\(echo\ "\)\,"\)
```

## EDIT
Okay, seems not a bug...search though the manual again and find this:
```
       If the argument contains parentheses, fzf may fail to parse the  expres‐
       sion.  In  that case, you can use any of the following alternative nota‐
       tions to avoid parse errors.
```

And the relevant code here, https://github.com/junegunn/fzf/blob//src/options.go#L1122
The "current using parentheses" cannot be used in shell command, in this case we have to use alternative, right? So maybe a wontfix...
```sh
# ok
FZF_DEFAULT_OPTS= fzf --bind "start:reload[echo '),']"
# bind action not specified: "]
FZF_DEFAULT_OPTS= fzf --bind "start:reload[echo '],']"
```

**Comment by junegunn** [comment]
Yes, I recommend using this notation:

```
 action-name:...
    The last one is the special form that frees you from parse errors as it
    does not expect the closing character. The catch is that it should be the
    last one in the comma-separated list of key-action pairs.
```

So, it becomes `fzf --bind 'start:reload:echo "),"'`

We could hopefully make the parsing logic smarter in the future, but for now `reload:...` is the recommended way to work around the limitation.

In this case, you can't bind multiple actions to a key or event at once (e.g. `reload(seq 100)+change-header(hi)`), but you can still do it like this:

```sh
# See the `+` before `change-header`
fzf --bind 'start:reload:seq 100' --bind 'start:+change-header:hi'
```
