### ISSUE TITLE
sink : "e" doesnt work for directories

### ISSUE THREAD

**Issue by netei** [junegunn/fzf#402]
with the following vimrc : 

```
set nocompatible              " be iMproved, required

" ----------------------------------------------------------------------------
" Bundles
" ----------------------------------------------------------------------------

" set the runtime path to include Vundle and initialize
if has('vim_starting')
  " Required:
  set runtimepath+=~/.$VIM_V/bundle/neobundle.vim/
endif

set rtp+=~/.fzf

command! -nargs=* J call fzf#run({
      \ 'source':  'echo "/tmp"',
      \ 'sink':    'e',
      \ 'options': '--ansi '.
      \            '--color hl:68,hl+:110',
      \ 'down':    '50%'
      \ })
```

then run `:J` , select the only line.

I would expect that the folder would be opened `/tmp`, but is is not, strangely.

It works fine from vim with `:e /tmp` 

Reproduced on both neovim 0.1 and vim 7.4

**Comment by junegunn** [comment]
Huh, interesting.
It can be reduced to `try | e /tmp | endtry` not bringing up netrw.
I'm not yet sure what's going on.

**Comment by justinmk** [comment]
Same issue as https://github.com/junegunn/fzf.vim/commit/2977f08e8f1aa7476b53ea76f33178b36f8ec113 I presume.

**Comment by junegunn** [comment]
@justinmk Ah yes, thanks. It just slipped out of my mind. So is this behavior a bug or is it expected?

**Comment by junegunn** [comment]
Related: https://groups.google.com/forum/#!topic/vim_use/EeQM4EWP7IY

**Comment by junegunn** [comment]
So, it doesn't seem like something we can do about right now.
Anyway, an easy workaround here is to use `Explore` as the sink.

**Comment by KevinSjoberg** [comment]
I'm running fzf (0.11.3) and seeing this problem still in Neovim.

```
nnoremap <Leader>b :call fzf#run({
      \ 'source': 'find . -path "*/\.*" -prune -o -type d -print',
      \ 'sink': 'e'})<CR>
```

fail to browse the directory. Manually calling `doautocmd BufEnter` make the tree listing appear.

Any ideas why this still fails?

**Comment by justinmk** [comment]
It happens in Vim too, no?

**Comment by KevinSjoberg** [comment]
@justinmk I'm currently just running Neovim, but I can certainly check if I can reproduce this within Vim as well.

**Comment by justinmk** [comment]
I don't think you need to check. Just wanted to clarify.

**Comment by junegunn** [comment]
@KevinSjoberg I think you're confused. I didn't fix the issue, because I can't.

> Thought #371 would solve it?

No, it fixes the sink function of `:FZF` command, not `fzf#run` function. `fzf#run` is not only for opening files – e.g. colorschemes, commands, word/line completion, etc – so it doesn't make sense to trigger `BufEnter` unconditionally.

**Comment by KevinSjoberg** [comment]
@junegunn I understand. So the current status of this issue is that it's not possible to fix?

**Comment by junegunn** [comment]
@KevinSjoberg It's up to each sink implementation to handle that.

**Comment by KevinSjoberg** [comment]
I see, thanks for clarifying. :+1:
