### ISSUE TITLE
Shell command mapped to via beocme execute on fzf start

### ISSUE THREAD

**Issue by rbhanot4739** [junegunn/fzf#4021]
### Checklist

- [X] I have read through the manual page (`man fzf`)
- [X] I have searched through the existing issues
- [X] For bug reports, I have checked if the bug is reproducible in the latest version of fzf

### Output of `fzf --version`

0.55.0 (brew)

### OS

- [ ] Linux
- [X] macOS
- [ ] Windows
- [ ] Etc.

### Shell

- [ ] bash
- [X] zsh
- [ ] fish

### Problem / Steps to reproduce

Here is the following one liner
```
ls | fzf --bind "del:become:(if [[ `echo \"Yes\nNo\" | fzf` == 'Yes' ]]; then echo 'Yes'; fi )"
```

When I run this, I straight away get the popup with `Yes/No` choices, but isn't that supposed to trigger only when I press the `del` key ? However, if I change it to below, I get the correct behavior where I first see the list of files in fzf and then pressing `del` opens up the sub popup.
```
ls | fzf --bind "del:become:(echo \"Yes\nNo\" | fzf )"
```

To give more context, what I am trying to do is if I choose a particular action from sub-popup on the press of `del` key and then perform a certain specific action for that choice. 

So is this behavior expected, if yes, then how can I alter it to do the above ?

**Comment by LangLangBart** [comment]
> When I run this, I straight away get the popup with `Yes/No` choices


[Bash Reference Manual - Simple-Command-Expansion](https://www.gnu.org/software/bash/manual/bash.html#Simple-Command-Expansion)

Command substitution has a higher precedence and is executed before the expanded command itself. 

Try to escape it:

```sh
ls | fzf --bind "space:become:[[ \$(echo -e \"Yes\nNo\" | fzf) == 'Yes' ]] && echo Yes || :"

# same, but with escaped backticks
ls | fzf --bind "space:become:[[ \`echo -e \"Yes\nNo\" | fzf\` == 'Yes' ]] && echo Yes || :"
```

**Comment by junegunn** [comment]
@LangLangBart Thanks for the comment.

`become` is great for simple cases, but if it starts requiring escaping stuff, you should consider doing it in shell script.

```sh
selected=$(ls | fzf) && yn=$((echo Yes; echo No) | fzf) && echo $selected - $yn
```
