### ISSUE TITLE
Prepending the PATH rather than appending in .fzf.zsh and .fzf.bash scripts

### ISSUE THREAD

**Issue by anhilde** [junegunn/fzf#4025]
### Checklist

- [X] I have read through the manual page (`man fzf`)
- [X] I have searched through the existing issues
- [ ] For bug reports, I have checked if the bug is reproducible in the latest version of fzf

### Output of `fzf --version`

0.55.0 (fc69308)

### OS

- [X] Linux
- [X] macOS
- [ ] Windows
- [ ] Etc.

### Shell

- [X] bash
- [X] zsh
- [ ] fish

### Problem / Steps to reproduce

After running 

`git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf ` 

and then the ~/.fzf/install script, the files ~/.fzf.zsh and ~/.fzf.bash are generated. Inside these files PATH variable is appended with the path to ~/.fzf/bin/fzf:

`PATH="${PATH:+${PATH}:}/home/andre/.fzf/bin"`

However on my systems (ubuntu 24.04, raspberry pi os) the fzf version installed by the systems installer (brew, apt) is resolved and since they don´t support the --zsh option, the source call fails. If I manually change the path in e.g. ~/.fzf.zsh by prepending the path entry like so:

`PATH="${HOME}/.fzf/bin:${PATH}"`

the newly installed version is resolved as desired. Is this done by intention or is this a bug? 

Best Regards

**Comment by LangLangBart** [comment]
> Is this done by intention or is this a bug?

Seems to be intentional. 
https://github.com/junegunn/fzf/commit/fdaa4e9b18a761dd0c60a1d4429c9f6c3eb58c96

**Comment by anhilde** [comment]
Hmm ok, seems strange having an install script that installs a piece of software in such a way that the installed piece of software is not usable afterwards and the reason being, that the piece of software it intentionally replaces may not be used afterwards. Anyway, thanks for the link.
