### ISSUE TITLE
fzf doesn't work well with --disabled option, possibly due to caching

### ISSUE THREAD

**Issue by QtRoS** [junegunn/fzf#4034]
### Checklist

- [X] I have read through the manual page (`man fzf`)
- [X] I have searched through the existing issues
- [X] For bug reports, I have checked if the bug is reproducible in the latest version of fzf

### Output of `fzf --version`

0.55.0 (1a32220c)

### OS

- [ ] Linux
- [X] macOS
- [ ] Windows
- [ ] Etc.

### Shell

- [ ] bash
- [X] zsh
- [ ] fish

### Problem / Steps to reproduce

I use `fzf` as UI for `rg`, like this:

```bash
qse() {
	RG_PREFIX="rg --files-with-matches"
	local file
	file="$(
		FZF_DEFAULT_COMMAND="$RG_PREFIX '$1'" \
			fzf --preview="[[ ! -z {} ]] && rg --pretty --context 5 {q} {}" \
				--ansi --disabled --query "$1" \
				--bind "change:reload:sleep 0.1; $RG_PREFIX {q}" \
				--bind "ctrl-r:disable-search" \
				--bind "f3:execute(bat --paging=always --pager=less --color=always {} < /dev/tty > /dev/tty)" \
				--bind "f4:execute(code {})" \
				--preview-window="70%:wrap"
	)" &&
	echo "$file"
}
```

In short, I simply pass search results from rg as input to fzf without filtering. Notice `--disabled` option. Docs say that it switches off filtering and search **completely**. But in my case **sometimes** fzf still filters results (I guess it's race condition or wrong cache invalidation). 

When I search something **for the first time** with this script everything works perfectly, shows exact number of results (files) `rg` finds. But later when I type something `fzf` kinda bugs and shows less results than `rg` returns, for example 1/3. Seems that caching part of `fzf` is kinda broken. After unsuccessful search (no result found) it often works well again for one more time. I guess different result count triggers merger cache invalidation.

I played with source code a little and changed [this line](https://github.com/junegunn/fzf/blob/master/src/matcher.go#L105):

```
// (this is NOT correct fix of this bug, just demonstration of my theory)
if cached, found := m.mergerCache[patternString]; found && false { // <-- notice && false
	merger = cached
}
```

In such case no caching is involved and it works fine. So, seems that `--disabled` option doesn't work well with caching. 
Also I found suspicious the usage of "paused" flag - no obvious affect on filtering found.

**Comment by junegunn** [comment]
No matter how long I try, I couldn't reproduce the problem. Can you provide a reliable way for me to reproduce it from my side? For example, 1. check out a specific commit of some git repository, 2. run `qse` function, 3. type something, 4. then something else, and so on.

**Comment by QtRoS** [comment]
Of course!
1. Create a folder for this experiment, for example `QSE_TEST`, `cd` to it
2. Clone some big repository here, for example VictoriaMetrics: `git clone https://github.com/VictoriaMetrics/VictoriaMetrics`
3. Run `qse` function
4. Type `func ParseAcc`
5. Notice 3/3 results
6. Type `e`, hit `backspace`, type `e` again, maybe type `ept`
7. Try this until you get 2/3 results, like this:

![image](https://github.com/user-attachments/assets/21746cd4-c728-4465-a33d-d22ac96a7d86)

8. Type `X`, so 0/0 results found
9. Then hit backspace and see 3/3 results again (cache invalidated)

**Comment by QtRoS** [comment]
https://github.com/user-attachments/assets/3c1888ab-2d6b-4c5b-9696-8e1011191de4

**Comment by QtRoS** [comment]
As I said before I fixed this behavior by chaning one line related to cache. Let me show you how it works with `qsf` function (which is exactly the same but uses fsf binary **with my fix**):

https://github.com/user-attachments/assets/19208303-ef7c-4a93-a619-e4aac29c691e

**Comment by QtRoS** [comment]
Fix looks fine to me 👍
What do we do now? Should I pull your changes and test them locally? Or you simply mark this issue as fixed and that's it?
