### ISSUE TITLE
Delta full line background not working in preview window

### ISSUE THREAD

**Issue by sndv** [junegunn/fzf#4038]
### Checklist

- [X] I have read through the manual page (`man fzf`)
- [X] I have searched through the existing issues
- [X] For bug reports, I have checked if the bug is reproducible in the latest version of fzf

### Output of `fzf --version`

0.55.0 (fc693080)

### OS

- [X] Linux
- [ ] macOS
- [ ] Windows
- [ ] Etc.

### Shell

- [X] bash
- [ ] zsh
- [ ] fish

### Problem / Steps to reproduce

When using [delta](https://github.com/dandavison/delta) for preview, the background color only shows behind the text instead of on the whole line.

normal delta output:

![2024-10-14_18-57-13](https://github.com/user-attachments/assets/b8b42d08-0891-44ab-a6e4-fc7b4df353cd)

fzf preview:

![2024-10-14_18-58-22](https://github.com/user-attachments/assets/5ac219dd-32e2-4609-982a-b7548dcab3d9)

It's related to the ANSI code `\x1b[0K` used by delta for the line background. There is this old issue #2249 when support for it was implemented, and that version works correctly, but the latest `master` does not. Git bisect shows that this commit is reintroducing the issue: 3c34dd82750ca61a1ee7f329ed47fe01e6d1ee30.

It only happens when there are no characters after `\x1b[0K` and before the end of the line:

![2024-10-14_19-05-32](https://github.com/user-attachments/assets/4e1f5bd2-f416-4240-986a-e82d6c8708ce)

but if you add a single space before the end of the line it works:

![2024-10-14_19-06-04](https://github.com/user-attachments/assets/e5d75b17-e0be-411f-aaa8-5fa7f079be00)

**Comment by junegunn** [comment]
Thanks, a24eb9967919c75bf19406c390ec0ae62f0ddb18 should fix the problem.

**Comment by sndv** [comment]
Thanks for the quick fix! It's working now.
