### ISSUE TITLE
Build on 00FAD5654C00 is not supported

### ISSUE THREAD

**Issue by arozehnal** [junegunn/fzf#4039]
### Checklist

- [X] I have read through the manual page (`man fzf`)
- [X] I have searched through the existing issues
- [ ] For bug reports, I have checked if the bug is reproducible in the latest version of fzf

### Output of `fzf --version`

0.55

### OS

- [ ] Linux
- [ ] macOS
- [ ] Windows
- [X] Etc.

### Shell

- [X] bash
- [ ] zsh
- [ ] fish

### Problem / Steps to reproduce

Some time ago I successfully compiled fzf v.0.40 for AIX.
When I try to build v.0.55 I get the message:

Makefile:74: *** Build on 00FAD5654C00 is not supported, yet... Stop

Is there any hope that fzf can be compiled for AIX?

**Comment by junegunn** [comment]
Related #2845

But you don't have to use the Makefile. Just try `go build` from the project root.

**Comment by arozehnal** [comment]
I'm sorry, I didn't think that the problem could be only in the Makefile.  ;-)
fzfz compiled, issue can be closed.
