### ISSUE TITLE
fzf can't work when i press CTRL -R in insert mode but can in normal mode.

### ISSUE THREAD

**Issue by Lithiumion007** [junegunn/fzf#4042]
### Checklist

- [X] I have read through the manual page (`man fzf`)
- [X] I have searched through the existing issues
- [X] For bug reports, I have checked if the bug is reproducible in the latest version of fzf

### Output of `fzf --version`

0.55

### OS

- [ ] Linux
- [X] macOS
- [ ] Windows
- [ ] Etc.

### Shell

- [ ] bash
- [X] zsh
- [ ] fish

### Problem / Steps to reproduce

I use zsh-vi-mode in my zsh. In normal mode ,fzf can work to search history.But in insert mode, when i pressed ctrl-R , it uses default search rather than fzf.

**Comment by LangLangBart** [comment]
Did you try the suggestions in the closed issues related to the `zsh-vi-mode` plugin?

For example:
- https://github.com/junegunn/fzf/issues/1304#issuecomment-1885944912

---

I assume it's just a sourcing issue with additional plugins. Check the readme and other issues in the `jeffreytse/zsh-vi-mode` repo if needed.

**Comment by Lithiumion007** [comment]
Thanks! I solved it after reading the closed issues . 
Add `zvm_after_init_commands+=('[`` -f $HOME/.fzf.zsh ] && source $HOME/.fzf.zsh')`  to my .zshrc helped me.

**Comment by ImTheEscapePlan** [comment]
another option to get it to work is to use `ZVM_INIT_MODE=sourcing` before the zsh-vi-mode plugin launches.
