### ISSUE TITLE
Start fzf from current row

### ISSUE THREAD

**Issue by george-b** [junegunn/fzf#405]
Rather than just dropping this on the wiki I just wanted to post this first as I'm sure it's pretty ugly.

This works out how may rows the terminal has and which row you are on. It then starts fzf on the current row and displays the possible completion options above or below depending on which has the most space. I find this makes the invocation of fzf less jarring in some ways.

Any and all feedback appreciated!

```sh
# The logic in the getpos function is stolen from
# http://stackoverflow.com/a/2575525
# Pass "row" or "col" as an argument to get their positions
getpos () {
  exec < /dev/tty
  oldstty=$(stty -g)
  stty raw -echo min 0
  echo -en "\033[6n" > /dev/tty
  IFS=';' read -r -d R -a pos
  stty $oldstty
  local row=$((${pos[0]:2} - 1))  # strip off the esc-[
  local col=$((${pos[1]} - 1))

  if [[ $1 = row ]]; then
    echo $row
  elif [[ $1 = col ]]; then
    echo $col
  fi
}

lines=$(tput lines)
row=$(getpos row)
halfway=$(expr $lines / 2)

# Start fzf from the current row
if [ "$row" -lt "$halfway" ]; then
  start_row=$(expr $row - 1)
  FZF_DEFAULT_OPTS+=' --reverse '
  FZF_DEFAULT_OPTS+=" --margin ${start_row},0,0 "
else
  start_row=$(expr $lines - $row + 1)
  FZF_DEFAULT_OPTS+=" --margin 0,0,${start_row} "
fi

fzf
```

**Comment by junegunn** [comment]
Amazing, I never thought this would be possible. This is definitely going to be useful when not on tmux. With a few improvements we can even consider adding it to `bin` directory of the repo. I'll try it for a while and give you some feedback. Thanks.

**Comment by george-b** [comment]
I got the desire of this sort of layout having played with [selecta](https://github.com/garybernhardt/selecta). It has some rendering issues which seem to be addressed in a rust clone [heatseaker](https://github.com/rschmitt/heatseeker) which I've stumbled across today. Not sure if you've thought about this kind of interface for fzf? Just an off-hand comment, I appreciate it's not very useful without patches.

**Comment by junegunn** [comment]
Oh yeah, I'm aware of those projects. Unlike fzf, they use low-level ANSI codes to control the screen instead of depending on ncurses. The approach has the benefit of not having to use fullscreen, which I think it's really nice. However, it seems much less stable than rock-solid ncurses, and cannot reliably support various key bindings and mouse like fzf does (yes I do use mouse on fzf sometimes!). And since tmux integration, I'm more or less content with the way fzf works.

I suggest a few changes to the script:
- `start_row=$(expr $lines - $row)` without `+ 1` seems to work better for me
- `fzf` should take the command-line arguments
    - But we should override `--reverse` or `--margin`, so I think it's better to directly pass those options to fzf instead of setting `FZF_DEFAULT_OPTS`
- It seems `$row` never reaches `$lines`, so we always have at least one empty line when the script is started with the cursor at the bottom of the screen which is most of the time. So I think it's reasonable to adjust the margin for that case.

```sh
# Start fzf from the current row
opts=
if [ "$row" -lt "$halfway" ]; then
  start_row=$(expr $row - 1)
  opts="--reverse --margin ${start_row},0,0"
else
  start_row=$(expr $lines - $row)
  [ $start_row -eq 1 ] && start_row=0
  opts="--no-reverse --margin 0,0,${start_row}"
fi

fzf "$@" $opts
```

And I like the script so far, it looks pretty clever, though I'm almost always on tmux so I'm not so sure if I'm going to use it often. Do you think it makes sense to include the script in the official repo?

**Comment by george-b** [comment]
Thanks for the insight! I agree with all your points.

> Do you think it makes sense to include the script in the official repo?

Originally I was intending to just put this on the wiki, I *think* this should be fairly portable so I guess it's not harmful to have it in the main repo. If it does go into the repo maybe the `getops` function should be simplified to just return the row number? I left the column stuff in just in-case I wanted to use it later.

**Comment by D630** [comment]
@george-b What's your termial? I have tested it in `st`, with no luck ...

By the way: You can calculate in POSIX shell without subshells using arithmetic expansion like `$(( x + y ))`. In bash you can also use `let` or `(( x=y+z ))` ( or: `typeset -i x=y+z ; x=x+=i`)

**Comment by george-b** [comment]
@D630 Guilty confession I'm in PuTTY most of the time these days, thanks for the arithmetic tip. I'll have to spin up a VM and do some testing with `st` and other terminals.

**Comment by george-b** [comment]
@D630 have you tried with modification @junegunn suggested? In my initial testing I realized my original example does not work if `FZF_DEFAULT_OPTS` is unset. This works for me in `st` and `gnome terminal` on a Fedora 23 VM.

**Comment by D630** [comment]
@george-b Ja, works.

https://gist.github.com/D630/ff2a40ca5a3288b08a7d

**Comment by junegunn** [comment]
@george-b How about sending me a pull request? We can continue the discussion there. By the way, I have absolutely no idea how we should call the script ;)

I think we can even consider using it in the default key bindings and fuzzy completion when not on tmux.

**Comment by acornejo** [comment]
AFAIK ncurses still clears the whole screen even when starting using a margin right?

**Comment by acornejo** [comment]
PS: I ask because I was preparing a pull-request which added an "auto-margin" option which retrieved the current cursor position and then computed the margin accordingly. However, after all the ioctls where done I realized that margin doesn't really prevent fzf from clearing the entire screen.

**Comment by junegunn** [comment]
> AFAIK ncurses still clears the whole screen even when starting using a margin right?

@acornejo Yeah, that is basically how ncurses works.

**Comment by acornejo** [comment]
Tks @junegunn, just closed the PR. If clearing the screen is unavoidable I don't see how starting from the current row is a desirable feature (if someone sees value on it, let me know since I had the code to add this to the fzf binary instead of doing it through shell scripts).

**Comment by george-b** [comment]
Woah totally forgot about this! I'm actually not using fzf much these days, @junegunn should this be closed?

**Comment by junegunn** [comment]
@acornejo I think the benefit is that we don't have to move our focus when fzf is started in full screen mode. But yeah, the usefulness of it is quite limited.

@george-b I'll close it. Thanks.
