### ISSUE TITLE
arbitrary shell commands with transform function of fzf

### ISSUE THREAD

**Issue by sabarish-vm** [junegunn/fzf#4064]
### Checklist

- [X] I have read through the manual page (`man fzf`)
- [X] I have searched through the existing issues
- [X] For bug reports, I have checked if the bug is reproducible in the latest version of fzf

### Output of `fzf --version`

0.55.0 (brew)

### OS

- [ ] Linux
- [X] macOS
- [ ] Windows
- [ ] Etc.

### Shell

- [ ] bash
- [X] zsh
- [ ] fish

### Problem / Steps to reproduce

Hi,
Thanks for all you put in to maintaining this amazing tool.
I am trying to use transform, to create a keybinding as given in the ADVANCED.md file.   That is,

--bind "ctrl-f:transform: $HOME/.dotfiles/fzf/fzf_level \$FZF_PROMPT" 

The above command fzf_level contains the following, 
prompt="$1"
if [[ ! "$prompt" =~ F ]]; then
    echo 'change-prompt(F> )+reload(fd --type file . )'
else
    echo 'change-prompt(D> )+reload(fd --type directory . )'
fi

Is something like this not possible ? The reason I want to do it in a separate script is to have more complicated branching and condition checking eventually.

**Comment by junegunn** [comment]
It should work, except you have to escape the second `$` to avoid immediate evaluation (i.e. `\$FZF_PROMPT`) or use the single-quotes.
