### ISSUE TITLE
Get rid of curses ruby gem

### ISSUE THREAD

**Issue by zbindenren** [junegunn/fzf#407]
Would be great, just to have go dep.

Great tool, btw.

**Comment by junegunn** [comment]
Can you elaborate a little more? This repo still contains the ancient Ruby implemetation, but it does not demand curses gem if your system can run one of the go binaries. The reason I haven't removed the old version yet is that we currently can build binaries only for linux and os x thus  have to fall back to the ruby version on other systems (e.g. cygwin)

**Comment by zbindenren** [comment]
Saw too late that it is not necessary for linux.

Closing issue.
