### ISSUE TITLE
Custom fuzzy completion for commands that are not first in the pipeline ($LBUFFER)

### ISSUE THREAD

**Issue by balta2ar** [junegunn/fzf#4074]
### Checklist

- [X] I have read through the manual page (`man fzf`)
- [X] I have searched through the existing issues
- [ ] For bug reports, I have checked if the bug is reproducible in the latest version of fzf

### Output of `fzf --version`

0.56.0 (ff16877)

### OS

- [X] Linux
- [ ] macOS
- [ ] Windows
- [ ] Etc.

### Shell

- [ ] bash
- [X] zsh
- [ ] fish

### Problem / Steps to reproduce

This must have been discussed somewhere during the fzf history, but I can't seem to find any relevant issues or a clear statement that it's not possible in man or on github  or wiki (https://github.com/junegunn/fzf/wiki/Examples-(completion)#writing-custom-fuzzy-completion) :disappointed:

I'm trying to make a custom completion for `llm` command to complete available LLM models:
```
git di | llm -m **<cursor>
```
A naive handler is simply not triggered:
```
_fzf_complete_llm() {
  ARGS="$@"
  if [[ $ARGS == 'llm'* ]]; then
...
```
or to be more precise, instead, git handler is triggered (which I have a custom handler for):
```
_fzf_complete_git() {
    ARGS="$@"
...
```
so it looks like everything that has to do with that type of completion works under the assumption that the command we're completing is the first one? So how can I have a handler for command that is not the first one in the pipeline? Is that possible at all?

I guess I could in that specific case override my git handler, make it more smart at parsing the whole line and check where the "cursor" is, but what if it's a different command I don't have a handler for, e.g.:
```
xclip -o -selection clibboard | llm --system "translate to english" -m **<cursor>
```

**Comment by LangLangBart** [comment]
It does work correctly in `bash`.

```bash
command env -i HOME=$HOME TERM=$TERM USER=$USER PATH=$PATH bash --norc
eval "$(fzf --bash)"

_fzf_complete_doge() {
  _fzf_complete --multi --reverse --prompt="doge> " -- "$@" < <(
    echo very
    echo wow
    echo such
    echo doge
  )
}
complete -F _fzf_complete_doge -o default -o bashdefault doge

[cmd1] | doge **
```

---

In **zsh**, the issue lies in the `__fzf_extract_command` function, which processes commands from left to right until the first command meets the requirement.

https://github.com/junegunn/fzf/blob/d938fdc496ccecfe5d747500927b675d31e1835a/shell/completion.zsh#L123-L135

As a workaround, you could try using `process substitution` so your intended command is placed first.




```sh
# process substitution
paste -sd ","  <(seq 15 -5 1)  
# 15,10,5

# process substitution with redirection
paste -sd "," - < <(seq 15 -5 1)
# 15,10,5
```

PS: Your reported issue is still valid, don't close it.

**Comment by junegunn** [comment]
@LangLangBart Oh, thanks for pointing it out.
