### ISSUE TITLE
spurious characters from previous view in preview window 

### ISSUE THREAD

**Issue by ALTree** [junegunn/fzf#4075]
```
$ fzf --version
0.56.0 (ff16877)
```
Using Bash on Linux. Reproducer:

```
echo -e "aaaaaaaaaa \nbbbbbbbbb" | fzf --preview-window=10 --preview="echo {}"
```

First item preview is correct:

![1](https://github.com/user-attachments/assets/661eba3f-2489-4694-80cd-dc456b7593e7)

The second isn't (note the `a` at the end):

![2](https://github.com/user-attachments/assets/b2e85daf-5ecb-47a1-84b9-a7f31fe0f7ff)

The last column of the preview window hasn't been cleaned, and it shows the `a` that was in that position for the previous item.

**Comment by junegunn** [comment]
Thanks, bacc860 should fix it, but please let me know if you see any regression from the change.
