### ISSUE TITLE
Abnormal behavior of `down` at the end of the list in the presence of multi-line items

### ISSUE THREAD

**Issue by junegunn** [junegunn/fzf#4083]
There is still a problem at the very end (the last page), where abnormal behavior can occur, but only when `--wrap` is on, even if there is no line to wrap.

In this example (with no line to wrap):
```bash
{ for i in {1..25}; do printf "item $i, line 1\0"; done; printf 'item 26, line 1\n         line 2\n         line 3\n         line 4\0'; for i in {27..58}; do printf "item $i, line 1\0"; done; } | fzf --read0 --reverse --height=35 --wrap
```
we get the following behaviour:

1. At the beginning we see items 1-30, item 1 selected.
2. After one `page-down`, we instantaneously see items 7-36, item 33 selected.
3. After a second `page-down`, after a sensible delay, we see items 26-55, with no visible item selected.
4. Further `page-down`s don’t have any effect.  But doing `down` once leads to seeing items 29-58, with item 58 selected.
5. Doing `down` again leads back to the state after step 3.  Doing `up` repeatedly leads to oscillations.

If we remove `--wrap` (or toggle it), everything is fine.  If we add `--scroll-off=12`, it seems to me that the delay is more sensible.

_Originally posted by @vejkse in https://github.com/junegunn/fzf/issues/4069#issuecomment-2466950696_

**Comment by junegunn** [comment]
@vejkse I believe the problem is fixed now. Thanks again.

**Comment by vejkse** [comment]
Thank you! It does look fixed.
