### ISSUE TITLE
Website misspells "navigation" as "nagivation"

### ISSUE THREAD

**Issue by topfunky** [junegunn/fzf#4092]
### Checklist

- [X] I have read through the manual page (`man fzf`)
- [X] I have searched through the existing issues
- [X] For bug reports, I have checked if the bug is reproducible in the latest version of fzf

### Output of `fzf --version`

0.56.2 (brew)

### OS

- [ ] Linux
- [X] macOS
- [ ] Windows
- [ ] Etc.

### Shell

- [ ] bash
- [X] zsh
- [ ] fish

### Problem / Steps to reproduce

On the website, the left nav bar mentions "nagivation" which should be spelled "navigation." The URL path is also misspelled.

I couldn't find the source of the website, otherwise I would have submitted a PR.

Thanks for this useful CLI tool!

https://junegunn.github.io/fzf/examples/directory-nagivation/

![Screenshot 2024-11-12 at 6 26 16 PM](https://github.com/user-attachments/assets/f536b8f1-8fba-4cff-97e3-5ca26fc23ae5)

**Comment by junegunn** [comment]
Fixed it, thanks!
