### ISSUE TITLE
Security Alert: Potential Trojan Detected in Windows Release 0.56.3

### ISSUE THREAD

**Issue by jathek** [junegunn/fzf#4097]
### Checklist

- [X] I have read through the manual page (`man fzf`)
- [X] I have searched through the existing issues
- [X] For bug reports, I have checked if the bug is reproducible in the latest version of fzf

### Output of `fzf --version`

0.56.2 (215ab48)

### OS

- [ ] Linux
- [ ] macOS
- [X] Windows
- [ ] Etc.

### Shell

- [ ] bash
- [X] zsh
- [ ] fish

### Problem / Steps to reproduce

Trying to update fzf to 0.56.3 but Windows Defender is flagging the exe. Probably a false positive as per previous issues?

![image](https://github.com/user-attachments/assets/bad5aefd-2d8e-42c8-87f5-7dbc004bc5a9)

**Comment by mahtaran** [comment]
Likely a false positive, like before https://github.com/junegunn/fzf/issues/3937#issuecomment-2241797145

**Comment by Eutropios** [comment]
Reporting identical popup.

**Comment by SSLbits** [comment]
This does appear to be a false positive. I was able to resolve the issue by updating to the latest Security Intelligence Update for Microsoft Defender Antivirus - KB2267602 (Version 1.421.310.0) - Current Channe (Broad) on Windows 11.

**Comment by mahtaran** [comment]
> This does appear to be a false positive. I was able to resolve the issue by updating to the latest Security Intelligence Update for Microsoft Defender Antivirus - KB2267602 (Version 1.421.310.0) - Current Channe (Broad) on Windows 11 through Windows Update.

Still being detected for me in version `1.421.316.0`, just submitted it to Microsoft for additional analysis.

**Comment by TonyApuzzo** [comment]
Virustotal shows hallmarks of false positive as well:

* 2/66 detection when uploaded: https://github.com/junegunn/fzf/releases/download/v0.56.3/fzf-0.56.3-windows_amd64.zip
* When using the URL based detection, 0/96 (sans Microsoft): https://www.virustotal.com/gui/url/b641b492e91ff737d130657f2702a6f58ea2fe2afd1bb12bb84c8fdc6a6b3cbe

**Comment by SSLbits** [comment]
I was also experiencing that after the previous definition updates. I've just updated to `Security Intelligence Update for Microsoft Defender Antivirus - KB2267602 (Version 1.421.326.0) - Current Channel (Broad)` and it's not detecting it as a virus. Hopefully, the back-and-forth is over at this point.

**Comment by junegunn** [comment]
Yes, it's a false positive. This happens quite often.
