### ISSUE TITLE
Env var / dynamic way to determine the preview hidden state within a transformer

### ISSUE THREAD

**Issue by ibhagwan** [junegunn/fzf#4098]
### Checklist

- [X] I have read through the manual page (`man fzf`)
- [X] I have searched through the existing issues
- [X] For bug reports, I have checked if the bug is reproducible in the latest version of fzf

### Output of `fzf --version`

0.56.2

### OS

- [X] Linux
- [ ] macOS
- [ ] Windows
- [ ] Etc.

### Shell

- [ ] bash
- [ ] zsh
- [ ] fish

### Problem / Steps to reproduce

Context: https://github.com/junegunn/fzf/issues/3817#issuecomment-2134248352.

Consider the example (from the above link):
```sh
TRANSFORMER='
  echo -n change-preview-window:
  if ((100 * FZF_COLUMNS / FZF_LINES >= 150)) && ((FZF_COLUMNS >= 120)); then
    echo "right,50%,border-left"
  elif ((FZF_LINES >= 40)); then
    echo "up,30%,border-bottom"
  else
    echo "hidden"
  fi
'

fzf --bind "start:transform($TRANSFORMER),resize:transform($TRANSFORMER)" --preview 'cat {}' --preview-window=hidden
```

There are a couple of issues with this:
- When running the above the transfomer doesn't take into account the preview hidden state, due to the transform running on `start`, the previewer opens in a visible state even though we specify `hidden`
- Hiding the previewer with a keybind and resizing the terminal causes the previewer to unhide

I tried the below  transformer (using `FZF_PREVIEW_COLUMNS`) but the previewer opens hidden and also hides itself when triggering resize:
```sh
TRANSFORMER='
  echo -n change-preview-window:
  if ((FZF_PREVIEW_COLUMNS == 0)) then
      echo "hidden"
  elif ((100 * FZF_COLUMNS / FZF_LINES >= 150)) && ((FZF_COLUMNS >= 120)); then
    echo "right,50%,border-left"
  elif ((FZF_LINES >= 40)); then
    echo "up,30%,border-bottom"
  else
    echo "hidden"
  fi
'
```

Am I missing something? Is there an env var I can use to determine if the previewer is hidden?

**Comment by junegunn** [comment]
No, there currently isn't a way. `FZF_PREVIEW_*` env vars are only exported to preview processes.

**Comment by ibhagwan** [comment]
> No, there currently isn't a way. `FZF_PREVIEW_*` env vars are only exported to preview processes.

Would you consider exporting these to the transform process? Could there be any downside?

**Comment by junegunn** [comment]
Will do. No downsides. The overhead for adding environment variables to other processes is going to be negligible.

**Comment by ibhagwan** [comment]
Ty @junegunn!
