### ISSUE TITLE
Near Doubling in number of files searched in "WSL Ubuntu bash 5.1.16" compared to "PowerShell 7.4.6".

### ISSUE THREAD

**Issue by mogggen** [junegunn/fzf#4104]
### Checklist

- [X] I have read through the manual page (`man fzf`)
- [X] I have searched through the existing issues
- [ ] For bug reports, I have checked if the bug is reproducible in the latest version of fzf

### Output of `fzf --version`

0.44.1 (d7d2ac3)

### OS

- [ ] Linux
- [ ] macOS
- [X] Windows
- [ ] Etc.

### Shell

- [X] bash
- [ ] zsh
- [ ] fish

### Problem / Steps to reproduce

Output of 'fzf --version':
0.29 (devel)

From my understanding I've gathered that apt isn't regurarly updated as mentioned in Issue #2599.

command: fzf -e

![Skärmbild 2024-11-20 103812](https://github.com/user-attachments/assets/1ff1d741-3ca4-4324-9e5b-6fa24a9b6f6f)

**Comment by junegunn** [comment]
I'm going to close this because both versions are quite outdated. Please leave a comment if you still see the problem when using the latest version of fzf, 0.56.3.

https://github.com/junegunn/fzf/releases/tag/v0.56.3
