### ISSUE TITLE
Option to disable Ctrl+R bindings (bash)

### ISSUE THREAD

**Issue by hahnandrew** [junegunn/fzf#4111]
### Checklist

- [X] I have read through the manual page (`man fzf`)
- [X] I have searched through the existing issues
- [X] For bug reports, I have checked if the bug is reproducible in the latest version of fzf

### Output of `fzf --version`

0.56.1 (brew)

### OS

- [ ] Linux
- [X] macOS
- [ ] Windows
- [ ] Etc.

### Shell

- [X] bash
- [ ] zsh
- [ ] fish

### Problem / Steps to reproduce

Reference #3678 

Ctrl-r conflicts with bash's [reverse-search-history (C-r)](https://linux.die.net/man/1/bash). FZF doesn't have an option to disable this binding

Add an option to skip fzf's Ctrl-r binding by setting a variable to an empty string, ie

`FZF_CTRL_R_COMMAND=  eval "$(fzf --bash)"`

**Comment by junegunn** [comment]
All the bindings override the default bash ones. But the important difference is that ALT-C and CTRL-T change the default behavior (`capitalize-word`, `transpose-chars`) but CTRL-R *enhances* the default `reverse-search-history`, so few want to turn it off (CTRL-R is one of the most loved features of fzf). Also, there is currently no `FZF_CTRL_R_COMMAND`, so introducing it just for disabling CTRL-R doesn't seem ideal.

If you do want the original `reverse-search-history` over the fzf's one, you can easily restore it like so:

```sh
eval "$(fzf --bash)"
bind '"\C-r": reverse-search-history'
```

**Comment by hahnandrew** [comment]
I think that'd make sense if the bindings were consistent with reverse/forward-search-history and readline's (kill line, search forward, etc disabled). The rebind worked, thank you.
