### ISSUE TITLE
[Bug] fzf tried to create a temporary history files?

### ISSUE THREAD

**Issue by crischutu07** [junegunn/fzf#4119]
### Checklist

- [X] I have read through the manual page (`man fzf`)
- [X] I have searched through the existing issues
- [X] For bug reports, I have checked if the bug is reproducible in the latest version of fzf

### Output of `fzf --version`

0.56.3 (add1aec)

### OS

- [X] Linux
- [ ] macOS
- [ ] Windows
- [ ] Etc.

### Shell

- [ ] bash
- [X] zsh
- [ ] fish

### Problem / Steps to reproduce

I'm using zsh 5.9 on Termux (0.118.1) Whenever I select a commands from my commands history it says `fzf-history-widget:18: can't create temp file for here document: no such file or directory`.

Step to reproduce:
1. Open commands history with `Ctrl + R`
2. Select a commands
3. It shows `fzf-history-widget:18: can't create temp file for here document: no such file or directory`

[![asciicast](https://asciinema.org/a/8lXAiszSF3HAPGhlYZd4zzNsM.svg)](https://asciinema.org/a/8lXAiszSF3HAPGhlYZd4zzNsM)

**Comment by LangLangBart** [comment]
Thanks for the report. It seems we just need to get rid of the `here-string` (`<<<`)[^1].

```bash
man 1 zshmisc | less --pattern here-string

<<< word
  Perform shell expansion on word and pass the result to  standard
  input.  This is known as a here-string.  Compare the use of word
  in here-documents above,  where  word  does  not  undergo  shell
  expansion.  The result will have a trailing newline after it.
```

> fzf-history-widget:18: can't create temp file for here document: no such file or directory

```bash
source <(fzf --zsh)
which fzf-history-widget | bat --line-range 15:+6 --language zsh --number

    15     local ret=$? 
    16     if [ -n "$selected" ]
    17     then
    18         if [[ $(awk '{print $1; exit}' <<< "$selected") =~ ^[1-9][0-9]* ]]
    19         then
    20             zle vi-fetch-history -n $MATCH
    21         else
```

---

Does the issue also occur for you with `bash`?

https://github.com/junegunn/fzf/blob/add1aec685ffe9033bb1fdcaf0df0eae95c9cacd/shell/key-bindings.bash#L79-L83

[^1]: [Zsh Mailing List Archive Re: Problem with zkbd](https://zsh.org/mla/users/2008/msg00483.html)

**Comment by LangLangBart** [comment]
Can you share the output of your `umask` command?

**Comment by LangLangBart** [comment]
Reproducible steps for macOS.

```bash
cat <<< "Hello"
# Hello

export TMPPREFIX=/nonexistent/directory
cat <<< "Hello"
# zsh: can't create temp file for here document: no such file or directory

export TMPPREFIX="$TMPDIR"
cat <<< "Hello"
# Hello
```

@crischutu07  can you check your `TMPDIR` and `TMPPREFIX` assignments?

**Comment by LangLangBart** [comment]
> Basically I only need to make `TMPPREFIX` variable the same as `TMPDIR` like you said. Thanks!

You are welcome. 

`TMPPREFIX` is assigned by default to `/tmp/zsh` by `zsh`; I don't know why it failed to assign the proper location for you.

Running it with  Docker, `TMPPREFIX` is assigned to `/data/data/com.termux/files/usr/tmp/zsh`:

```bash
docker run --rm termux/termux-docker:latest sh -c '
apt update && apt install -yq zsh
/bin/zsh -c "cat <<< Hello; echo TMPPREFIX \$TMPPREFIX"'
# …
# Hello
# TMPPREFIX /data/data/com.termux/files/usr/tmp/zsh
```

However, I would suggest closing this issue, as it might better fit into the `zsh` or `termux` community.
