### ISSUE TITLE
[Question] History for fzf

### ISSUE THREAD

**Issue by xiaoshihou514** [junegunn/fzf#4121]
### Checklist

- [X] I have read through the manual page (`man fzf`)
- [X] I have searched through the existing issues
- [ ] For bug reports, I have checked if the bug is reproducible in the latest version of fzf

### Output of `fzf --version`

0.56.3 (Fedora)

### OS

- [X] Linux
- [ ] macOS
- [ ] Windows
- [ ] Etc.

### Shell

- [ ] bash
- [ ] zsh
- [X] fish

### Problem / Steps to reproduce

Hi!
I am wondering if there's a way to have history (previous fzf search queries) in fzf, so that one can reuse previous queries via `C-p` or `C-n`. It seems like fzf is mostly stateless, and there will be problems regarding which queries to consider as "history" (fzf might be launched for different purposes).
One possible way to emulate this behavior is maybe by saving queries in some external state and pass them back in as environment variables (not sure if fzf has api for filling stuff into the prompt).
For reference I am building a in editor wrapper for fzf in neovim.
Thanks!

**Comment by LangLangBart** [comment]
> I am wondering if there's a way to have history (previous fzf search queries) in fzf

See `man fzf | less --pattern='--history'`

```bash
# Add a history entry
fzf --history /tmp/fzf_hist --query 'TESTING ABC' --bind 'start:accept'

# Get the last entry into the query input and print it (for demonstration purposes)
fzf --history /tmp/fzf_hist --bind 'start:prev-history+become:echo $FZF_QUERY'
# TESTING ABC
```

Ref: https://github.com/junegunn/fzf/issues/3533

---

> there will be problems regarding which queries to consider as "history" (fzf might be launched for different purposes). 

The `--listen` flag could be useful for your project.

Ref: https://github.com/junegunn/fzf/issues/3685

**Comment by xiaoshihou514** [comment]
I also see the possibility of binding keys to `curl` calls and writing some commands back...?

**Comment by junegunn** [comment]
> there will be problems regarding which queries to consider as "history" (fzf might be launched for different purposes)

You can use a different `--history` file for each purpose.

**Comment by xiaoshihou514** [comment]
Works like a charm, thanks!
