### ISSUE TITLE
fzf suddenly only outputting terminal colors??

### ISSUE THREAD

**Issue by peperonnii** [junegunn/fzf#4127]
### Checklist

- [X] I have read through the manual page (`man fzf`)
- [X] I have searched through the existing issues
- [X] For bug reports, I have checked if the bug is reproducible in the latest version of fzf

### Output of `fzf --version`

0.56.3 (add1aec6)

### OS

- [X] Linux
- [ ] macOS
- [ ] Windows
- [ ] Etc.

### Shell

- [ ] bash
- [ ] zsh
- [X] fish

### Problem / Steps to reproduce

Hello it was working a second ago and now i have no idea whats causing `fzf` to output this. Looks like its outputting my terminal colors??
![image](https://github.com/user-attachments/assets/5e3d8123-848e-4428-ac14-583d3175ef9b)

Other aspects work like alt c  ctrl t but the standard fzf command doesnt work. I have tried everything i could. Any idea?

```config.fish
fzf --fish | source

set -Ux EDITOR nvim
set -Ux SHELL /usr/bin/fish


function fish_prompt -d "Write out the prompt"
    printf '%s@%s %s%s%s > ' $USER $hostname \
        (set_color $fish_color_cwd) (prompt_pwd) (set_color normal)
end
if status is-interactive
    set fish_greeting
end
starship init fish | source
if test -f ~/.cache/ags/user/generated/terminal/sequences.txt
    cat ~/.cache/ags/user/generated/terminal/sequences.txt
end

alias pamcan=pacman
alias b=btop
alias v=nvim
alias spot="spicetify backup restore apply"

abbr p 'sudo pacman'
abbr ps 'sudo pacman -S'
abbr pr 'sudo pacman -R'
abbr pu 'sudo pacman -Syu'
abbr ys 'yay -S'
abbr yr 'yay -R'
abbr yu 'yay -Syu'
abbr cl 'tty-clock -c -s'
```

**Comment by LangLangBart** [comment]
> Looks like it's outputting my terminal colors??

Not reproducible with the information given.

Try starting `fish` without your config and only with some shell 
variables like `PATH`. Is the issue still reproducible?

```bash
command env -i "HOME=$HOME" "USER=$USER" "PATH=$PATH" \
   "TERM=$TERM" $(command which fish) --no-config
```

Alternatively, experiment with `Docker` to find reproducible steps.

```bash
docker run --interactive --tty --rm alpine:latest sh -c '
apk add fzf starship fish
{
  echo "fzf --fish | source"
  echo "set -Ux SHELL /usr/bin/fish"
  echo "starship init fish | source"
} >> /usr/share/fish/config.fish
fish'
```

**Comment by LangLangBart** [comment]
> peperonnii commented 4 days ago

Interesting, I didn't even see your issue listed over the last 4 days. 
On the `Wayback Machine`[^1], it is not listed either for the 12th of December. 🧐

<img src="https://github.com/user-attachments/assets/cfa69194-13ff-4dee-bd68-c1dc78b685c9" width="200">

```bash
gh api /repos/junegunn/fzf/issues/4127 --jq '.created_at'
  2024-12-11T21:05:51Z
```

[^1]: [web.archive.org - 12/Dec/24 - github.com/junegunn/fzf/issues](https://web.archive.org/web/20241212094941/https://github.com/junegunn/fzf/issues)

**Comment by junegunn** [comment]
I'm pretty sure this approach will fix your problem.

https://github.com/junegunn/fzf/issues/1415#issuecomment-593817975

You don't want to set up colors in a non-interactive session.

---

@LangLangBart 

> Interesting, I didn't even see your issue listed over the last 4 days.

Yeah, this is strange. I also was notified of this just yesterday.

**Comment by peperonnii** [comment]
> > peperonnii commented 4 days ago
> 
> Interesting, I didn't even see your issue listed over the last 4 days. On the `Wayback Machine`[1](#user-content-fn-1-0557e2ae63f4c272b93905e00ec3a913), it is not listed either for the 12th of December. 🧐
> <img alt="" width="200" src="https://private-user-images.githubusercontent.com/92653266/395860075-cfa69194-13ff-4dee-bd68-c1dc78b685c9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQzODc3MTEsIm5iZiI6MTczNDM4NzQxMSwicGF0aCI6Ii85MjY1MzI2Ni8zOTU4NjAwNzUtY2ZhNjkxOTQtMTNmZi00ZGVlLWJkNjgtYzFkYzc4YjY4NWM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE2VDIyMTY1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI1YzZjOTkxMDAyYzVjYmEwZjZlZDNmYjMxNTNiYTBkY2U1NTQ4YTI4YzQxMzljYjY1MTA0YWQ2YTA5MzRhMTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.gWE89IIzn-bqbqiPG3qzI69lDugldMOttJicg4cjry8">
> 
> ```shell
> gh api /repos/junegunn/fzf/issues/4127 --jq '.created_at'
>   2024-12-11T21:05:51Z
> ```
> 
> ## Footnotes
> 
>     1. [web.archive.org - 12/Dec/24 - github.com/junegunn/fzf/issues](https://web.archive.org/web/20241212094941/https://github.com/junegunn/fzf/issues) [↩](#user-content-fnref-1-0557e2ae63f4c272b93905e00ec3a913)

I like to time travel tbh 
(I was falsely shadowbanned on github cuz of an aliased email address)

**Comment by peperonnii** [comment]
> I'm pretty sure this approach will fix your problem.
> 
> [#1415 (comment)](https://github.com/junegunn/fzf/issues/1415#issuecomment-593817975)

Yes this fixed my issue, thanks for the help.
sorry for the lack of information towards reproducing the issue, i had *some* idea that it was outputting some color information and that was a clue, but otherwise i was completely lost.
