### ISSUE TITLE
A way to set the fzf popup to a specific width

### ISSUE THREAD

**Issue by Xe-no1** [junegunn/fzf#4147]
### Checklist

- [X] I have read through the manual page (`man fzf`)
- [X] I have searched through the existing issues
- [ ] For bug reports, I have checked if the bug is reproducible in the latest version of fzf

### Output of `fzf --version`

0.57.0 (brew)

### OS

- [X] Linux
- [X] macOS
- [ ] Windows
- [X] Etc.

### Shell

- [ ] bash
- [X] zsh
- [ ] fish

### Problem / Steps to reproduce

Hello, I was wondering if there is a way/flag I can set to specify the width of the fzf window, something like `--height=60%`, so far after looking for some time through the man page, I cannot seem to find any way to do so. Does such an option exist or am I out of luck? Thanks in advance.

**Comment by LangLangBart** [comment]
Try the `--margin` flag.

```bash
FZF_DEFAULT_OPTS= FZF_DEFAULT_COMMAND= fzf --margin=0,20,0,0 --height=10% --border
```

---

Alternatively, when using `tmux`[^1]

```bash
# start tmux
tmux
# see 'man fzf-tmux'
fzf-tmux -w 60% 
```

[^1]: [GitHub - tmux/tmux: tmux source code](https://github.com/tmux/tmux)

**Comment by Xe-no1** [comment]
Yeah your suggestion worked thanks!

**Comment by junegunn** [comment]
@LangLangBart Thanks for answering the question!

I'd like to mention that `fzf-tmux` script is being phased out in favor of the new `--tmux` option. You can run `fzf --tmux 60%` instead.
