### ISSUE TITLE
Removal of the "gutter's space" in between results and the gutter?

### ISSUE THREAD

**Issue by Rk4mo1fPoF** [junegunn/fzf#4149]
### Checklist

- [X] I have read through the manual page (`man fzf`)
- [X] I have searched through the existing issues
- [ ] For bug reports, I have checked if the bug is reproducible in the latest version of fzf

### Output of `fzf --version`

0.57.0 (0476a65)

### OS

- [X] Linux
- [ ] macOS
- [ ] Windows
- [ ] Etc.

### Shell

- [X] bash
- [ ] zsh
- [ ] fish

### Problem / Steps to reproduce

Hi, sorry for being annoying, I need this for a project involving a very small screen.
I cloned the repo and would like to remove this space in between the gutter and the results. ![image](https://github.com/user-attachments/assets/8f40a87f-56ad-4baa-aba5-c6d152278b43)
I've tried removing `Gutter` itself,  from `func init` in `src/tui/tui.go` but no luck since I'm no go programmer nor a programmer at all.

**Comment by junegunn** [comment]
See https://junegunn.github.io/fzf/releases/0.54.0/#empty-pointer-and-marker-signs
