### ISSUE TITLE
Update fzf prompt from within execute(...)

### ISSUE THREAD

**Issue by mhrebenyuk** [junegunn/fzf#416]
It would be nice to have possibility updating fzf prompt with text provided as a result of invoking execute(..).
It can be used for refreshing/updating candidates depending on logic in execute

**Comment by junegunn** [comment]
> It can be used for refreshing/updating candidates depending on logic in execute

I think it's beyond the scope of the feature. `execute` was designed for quickly previewing things. Heavyweight operations like changing the options or the source should be done by the shell script that wraps around fzf. `--expect` is especially useful for such purposes. You'll be able to find some good examples in [the wiki page](https://github.com/junegunn/fzf/wiki/Examples).

I'll close the issue for now. But feel free to leave some comments if you any other suggestion or ideas.
