### ISSUE TITLE
Completion trigger sometimes fails to fire

### ISSUE THREAD

**Issue by squatched** [junegunn/fzf#417]
Typing `emacs **<TAB>` fires off `fzf` as expected but `emacsclient **<TAB>` does not.

This is in bash and I just started using `fzf` so if this is PEBCAK, please excuse and feel free to tell me to go away.

**Comment by junegunn** [comment]
See #386. bash sucks. :hankey:

**Comment by junegunn** [comment]
Maybe we should add the command to the default list? What do you think?

**Comment by squatched** [comment]
Yeah, default command list makes sense for that since you've already got `emacs` there.

I have two additional suggestions (and first chance I get, if someone hasn't gotten to any of these already I'll submit a pull request):
1 - In the README.md, call out in the "Fuzzy completion for bash and zsh" that all commands might not work due to bash's functionality.
2 - Provide a means of extending those lists via environment variables.

Thanks for a fantastic tool, I look forward to finding new ways it can help my daily command line usage!

**Comment by junegunn** [comment]
Thanks for the suggestion. I updated the command list and added the description to the README page though I decided not to add more env vars.

**Comment by squatched** [comment]
Sounds good! Keep up the good work!
