### ISSUE TITLE
fzf cd always rescans

### ISSUE THREAD

**Issue by dploeger** [junegunn/fzf#418]
I'd like to use Alt-C to change the directory. However, it always rescans the directory trees and that takes quite a long time in that my wanted directory isn't included.

Using locate | fzf is much faster. So, would it be possible to speed up the process (i.e. using locate as stdin, using a scan cache file or something) or am I doing something wrong?

**Comment by junegunn** [comment]
It's the default behavior. I [recently updated the code](#408) to use `$FZF_ALT_C_COMMAND` if defined, so you can now customize the default behavior with it.
