### ISSUE TITLE
Can context-aware completion respect `FZF_DEFAULT_COMMAND`?

### ISSUE THREAD

**Issue by geoffharcourt** [junegunn/fzf#420]
Apologies if I'm just missing a configuration option.

When I use the suggested `fe()` function to find a file for editing, fzf uses my default command (Ag) and filters results that takes into account my `.gitignore` and `.agignore`. However, when I type `vim <C-t>` and launch fzf, the results set is very large, and isn't using those filters.

Is there a way to take advantage of my ignore files via Ag when I launch argument completion?

**Comment by junegunn** [comment]
https://github.com/junegunn/fzf#key-bindings-for-command-line

For <kbd>ctrl-t</kbd>, there's separate `FZF_CTRL_T_COMMAND`. Note that the default command for <kbd>ctrl-t</kbd> lists both files and directories while your ag command will only list files. I once wrote [a small wrapper script](https://github.com/junegunn/agl) to address the issue.

**Comment by geoffharcourt** [comment]
Thanks very much for the explanation!
