### ISSUE TITLE
fzf nvim terminal issue

### ISSUE THREAD

**Issue by acornejo** [junegunn/fzf#426]
I use fzf for almost everything these days. I recently tried out neovim, and realized fzf doesn't work in some settings.

Sometimes I chain two FZF's, first I select from one list of items, then based on that selection, I then present a second list of items. In these cases, the second selection is NOT in insert mode when using neovim, which cause all my keystrokes to be interpreted by neovim instead of FZF. Here is the smallest example I could come up with that reproduces the behavior (in reality I am doing more complicated things, but the issue is the same):

``` viml
command! FZFChainExample call fzf#run({                                                                                                                                               
\ 'source': "ls -1p ~ | awk -F/ '/\\/$/ {print $1}'",                                                                                                                         
\ 'sink': function('<sid>rec_handler'),                                                                                                                                           
\ 'options': '-m',                                                                                                                                                                
\ 'down': '50%'                                                                                                                                                                   
\ }) 

function! s:rec_handler(dir)                                                                                                                                                      
  execute 'lcd ~/'.a:dir                                                                                                                                                      
  execute 'FZF'                                                                                                                                                                   
endfunction
```

this command will first display a list of directories in the home folder, and then (once a directory is selected) it will present a second FZF with all files in that directory. The example doesn't matter, what matters is that this works well in vim, but in neovim the second FZF is not receiving the keystrokes (I have to press i to go to insert mode).

**Comment by khalidchawtany** [comment]
This could be related to https://github.com/junegunn/fzf.vim/issues/21. 
I think the issue is: switching from a terminal buffer to another terminal buffer, the second cannot perform "startinsert" successfully.

**Comment by junegunn** [comment]
@acornejo Not sure why (internal) `startinsert` doesn't work, but looks like we can workaround the issue with a `feedkeys` call.

```vim
function! s:rec_handler(dir)
  execute 'lcd ~/'.a:dir
  FZF
  call feedkeys('i')
endfunction
```

@khalidchawtany The same thing can be done in your case as well. Try changing `startinsert` to `call feedkeys('i')`.

**Comment by acornejo** [comment]
@junegunn yup, I can confirm this fixes the issue for me (makes sense, I was working around it by pressing i, so might as well have vim emualte that key press).

Right now I amended my scripts by sprinkling the following in the right places:

```viml
if has("nvim")
  call feedkeys('i')
endif
```

that being said, it would be wonderful if this fix was in fzf itself, so that user scripts don't have to care weather they are running in nvim or in plain old vim.

**Comment by junegunn** [comment]
> it would be wonderful if this fix was in fzf itself

But I'm not sure `startinsert` not working is the expected behavior. If it turns out to be a bug and neovim fixes it, we'll then have an extraneous `i`.

@tarruda Do you know why the code in the OP doesn't work as expected on neovim?

**Comment by acornejo** [comment]
good point, i missed that. don't know what startinsert is, but given the name i would certainly expect it to start insertion mode ;) so maybe I should file this issue in the neovim repo. i'll wait for @tarruda to reply

**Comment by junegunn** [comment]
https://github.com/junegunn/fzf/blob/0.11.0/plugin/fzf.vim#L359-L361

`startinsert` followed by `termopen()` is supposed to start insert mode in the term buffer. It works when `fzf#run()` is directly called, but it doesn't when we chain another `fzf#run` in the sink function as you reported. @khalidchawtany also reported a similar issue that can be concentrated as follows.

```vim
function! s:insert_sink(e)
  execute 'e' a:e
  startinsert
endfunction

command! FZFInsert call fzf#run({'sink': function('<sid>insert_sink')})
```

`startinsert` works in vim, but not on nvim.

**Comment by tarruda** [comment]
> @tarruda Do you know why the code in the OP doesn't work as expected on neovim?

I have an idea of what might be causing this: The `on_exit` callback is called while nvim is still in terminal mode, and due to the way `startinsert` is implemented(global flag, no way to queue `startinsert` commands) it doesn't work as expected when called outside normal mode. Unfortunately I can't think of a better way to work around this other than `feedkeys('i')`, but the `startinsert` implementation might be fixed later to allow this kind of use case.
