### ISSUE TITLE
change color theme and add keybindings

### ISSUE THREAD

**Issue by sirlnx** [junegunn/fzf#427]
Probably a very stupid question.

I would like to change the color theme and add more keybindings.

However, I can't find in the manpage which config-file I should have to change colors and keybindings.

Excuse me for my ignorance.

**Comment by junegunn** [comment]
There is no config file. Colors and key bindings are configured using `--color` and `--bind` options respectively and you can put them in `$FZF_DEFAULT_OPTS` env variable.

e.g.

```sh
export FZF_DEFAULT_OPTS='
  --bind ctrl-f:page-down,ctrl-b:page-up
  --color fg:124,bg:16,hl:202,fg+:214,bg+:52,hl+:231
  --color info:52,prompt:196,spinner:208,pointer:196,marker:208
'
```
