### ISSUE TITLE
FZF+ I3 + DMENU 

### ISSUE THREAD

**Issue by jkoz** [junegunn/fzf#43]
Hello,

I really really love your tool except one thing it is written in ruby ;-), however, I'm fine with this. I'm working to integrate your engine to work with dmenu & i3 wm window switcher.

In i3 WM, I hit alt-d it show list of window for choose to focus which powered by dmenu (see https://github.com/ziberna/i3-py/blob/master/examples/winmenu.py) I want to do similar things with fzf.

One thing that I don't like dmenu is that it doesn't support fuzzy matching. I also don't prefer to install too many fuzzy engine on my machine.

Currently, I have slmenu, dmenu, ctrlp, and fzf. As I know you tool, I want to eliminate other tools to use one only.

PS: it work be really nice if your such tool can be written in C so the performance will be improved a lot. I don't aware if there such tools written in C

 Thanks
Tai

**Comment by hyiltiz** [comment]
Hi @jkoz , given that `fzf` is a clear unix filter, would not it also be possible to get filter the list, rather than also introducing change to the interface? I liked the one-line interface `dmenu` provided, and am thinking maybe we could put `fzf` just after `dmenu` to further filter the results?

**Comment by jkoz** [comment]
Im not really get what you means. Is it better if you provide a clear example of your command. Agree that one line interface is pretty neat, but it does not support fuzzy logic which is what i want.

Just want to let you guy know that I currently use xdotool and sxhkdrc to layout terminal on the top of window, it seem a little bit hard code but it works

>>> grep dm ~/.config/sxhkd/sxhkdrc
    st -c Fzf -e sh -c "xdotool search 'Fzf' windowsize 100% 50% windowmove 0 20; dm fm"

dm is my fzf script which can found it my repos
