### ISSUE TITLE
Vendor dependencies instead of using forks

### ISSUE THREAD

**Issue by Tranquility** [junegunn/fzf#430]
If I saw that correctly you forked the dependencies only to control the changes to them. I am working on a package for Gentoo Linux and that means I need to package your forks as well. Which means I add packages that are only reasonable for the fzf package.
Before doing that I would like to ask you whether you are open to putting them in vendor directory, which seems to be the way the go community is heading https://golang.org/s/go15vendor.

**Comment by junegunn** [comment]
> only to control the changes to them

Yes, and to make sure that my build always succeeds even if the authors of the dependent libraries suddenly decide to put them down, which is extremely unlikely, but you see the point.

Anyway, I haven't migrated to Go 1.5 yet because there is no compelling reason to do so, but I'm open to the suggested change. I'll take a look at it when I get some time, or you can send me a PR.

**Comment by junegunn** [comment]
I'm going for vendoring + forks.

**Comment by junegunn** [comment]
Are you happy with the change? Actually I'm not so happy with it since it causes vim-plug to clone both submodules when most users don't really need them.

**Comment by netei** [comment]
+1 @junegunn , it makes more sense to me that the dependencies are in other repos, so that you keep only **your** source code in the repository.

**Comment by Tranquility** [comment]
Sorry for not getting back to you earlier. Thanks for working on this. I was happy with the change, it was working nicely.

I see two ways how I can finish the package now:

1. You use your forks only as backup and import the upstream repo.  That would be nice because I can add the upstream repo to the package tree which might be useful for other packages. I don't know how much overhead that would be to you.
2. I add the forks to the Gentoo package tree.

**Comment by Tranquility** [comment]
There is a third one:

You could move the go source into its own repository.

**Comment by junegunn** [comment]
Hi, sorry for reverting the change. But please understand that for me providing better experience to the users directly cloning this repo is more important that making it easier for you to package it. I'm mostly content with the status quo (moving out source codes will not make much difference) and see no good reason to abruptly change the structure at the moment.

**Comment by mitermayer** [comment]
what is the gentoo package fork for this ?
