### ISSUE TITLE
Add option for use Ctrl+J as Enter

### ISSUE THREAD

**Issue by averrin** [junegunn/fzf#431]
Add option for use Ctrl+J as Enter like in shell

**Comment by junegunn** [comment]
`--bind ctrl-j:accept`

**Comment by averrin** [comment]
Thank!!!

**Comment by aviloff** [comment]
> `--bind ctrl-j:accept`

Sorry, I'm a bit new here, where do i paste this if using MacVim primarily? is there some settings file that con be customized? I installed with fzf.vim and fzf with vimplug.

**Comment by KashcheyMC** [comment]
[]()```
- [ ] @averrin 
```

**Comment by KashcheyMC** [comment]
> `--bind ctrl-j:accept`
>

**Comment by KashcheyMC** [comment]
- [ ] @averrin

**Comment by KashcheyMC** [comment]
~~~~

**Comment by KashcheyMC** [comment]
@averrin

**Comment by KashcheyMC** [comment]
```

```

**Comment by KashcheyMC** [comment]
``

**Comment by KashcheyMC** [comment]
> Thank!!!
> 

[]()@averrin
