### ISSUE TITLE
tmux "set -g focus-events on" and fzf adds characters to vim

### ISSUE THREAD

**Issue by aliev** [junegunn/fzf#434]
if tmux option is enabled:

``set -g focus-events on``

(This option is required for [vim-tmux-focus-events](https://github.com/tmux-plugins/vim-tmux-focus-events) plugin)

fzf adds characters to vim when I run fzf

![](https://habrastorage.org/files/3e9/30c/6c7/3e930c6c70b1439eb788290462aa27f2.png)

maybe this is not issue, but it would be interesting to find a solution to so solve this problem.

I tried to add settings

```
au FocusGained * silent redraw!
au FocusLost * silent redraw!
```

but it did not help.

** UPD ** my shortcut to run Files command

```
nnoremap <silent> <Leader>f :Files<CR>
```

Thanks!

**Comment by junegunn** [comment]
Thanks for the report. I added `set -g focus-events on` to my [tmux.conf](https://github.com/junegunn/dotfiles/blob/master/tmux.conf) (I still don't know what the option is for though), reloaded the config, but I can't seem to reproduce the issue you reported.

**Comment by aliev** [comment]
@junegunn
```
Also, vim-tmux-focus-events makes the autoread option work properly for terminal vim. So far, this was only working in a GUI version.
```
and

```
FocusGained and FocusLost autocommand events are not working in terminal vim. This plugin restores them when using vim inside Tmux.
```
very usable.

I this same issue https://github.com/tmux-plugins/vim-tmux-focus-events/issues/2

**Comment by junegunn** [comment]
https://github.com/tmux-plugins/vim-tmux-focus-events/issues/2#issuecomment-87863831
