### ISSUE TITLE
ALT-C shortcut broken in ZSH

### ISSUE THREAD

**Issue by rhabbachi** [junegunn/fzf#437]
* uname:
`Linux 4.2.5-1-ARCH #1 SMP PREEMPT Tue Oct 27 08:13:28 CET 2015 x86_64 GNU/Linux`

* zsh --version
`zsh 5.2 (x86_64-unknown-linux-gnu)`

Since e99731ea852d1faac5390594cd980708edf826cf the ALT-C find shortcut is broken for me. I can get it back to work if I revert `shell/key-bindings.zsh` to the it's parent commit with:
```
gco c3cf3427b113514279b47349a993db51353a364a shell/key-bindings.zsh
```

**Comment by junegunn** [comment]
Thanks for the report. Since it's not reproducible for me, I need your assistance to examine the problem. I assume some of your zsh configuration is not compatible with the change. Any idea? Can you try again with an empty zsh configuration? Nothing but fzf.

**Comment by rhabbachi** [comment]
@junegunn Yeah I will try to do that.
Meanwhile if I execute only the find command in a prompt I get an error message:
```
~  command find -L . \\( -path '*/\\.*' -o -fstype 'dev' -o -fstype 'proc' \\) -prune -o -type d -print 2> /dev/null                                                                                                                                            
zsh: unknown file attribute:
```

**Comment by junegunn** [comment]
You have to replace `\\` with `\` if you want to execute the command directly without eval.

```
command find -L . \( -path '*/\.*' -o -fstype 'dev' -o -fstype 'proc' \) -prune -o -type d -print 2> /dev/null

# or eval
eval "command find -L . \\( -path '*/\\.*' -o -fstype 'dev' -o -fstype 'proc' \\) -prune -o -type d -print 2> /dev/null"
```

**Comment by rhabbachi** [comment]
Thank you @junegunn. After a while I couldn't reproduce the issue. Closing.

**Comment by IzakMaraisTAL** [comment]
> unknown file attribute:

`fzf-cd-widget` (the command called by Alt+C) was giving this error for me. It was fixed by changing from the `fzf-zsh-plugin` to the [`fzf` Oh-my-zsh plugin](https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/fzf).
