### ISSUE TITLE
include vim tags functions?

### ISSUE THREAD

**Issue by solars** [junegunn/fzf#438]
I know this is probably not the right place to ask but anyway: Why not include the two functions FZFTags, FZFTagsBuffer here:
https://www.reddit.com/r/vim/comments/3f0zbg/psa_if_youre_using_ctrlp_use_this_maintained_fork/

by default in FZF? I guess it would make sense as it is useful and a lot of people are coming fromctrlp

**Comment by junegunn** [comment]
Thanks for the suggestion but as [noted on the README page](https://github.com/junegunn/fzf#usage-as-vim-plugin), this repository only provides the basic Vim integration. You can check out [fzf.vim](https://github.com/junegunn/fzf.vim) project.
