### ISSUE TITLE
More options on the default keybindings would be appreciated

### ISSUE THREAD

**Issue by guiniol** [junegunn/fzf#441]
Hello,

It would be nice to have the option to tweak the keybindings in `fzf.{bash,zsh}` as well as the default options (I like reverse and more colors). I copied and modified it, but then I can't benefit from future improvements in the functions. 

Also, is there a documentation on how to do custom color scheme with `--color`?

**Comment by junegunn** [comment]
> tweak the keybindings

You'll be able to override the key bindings only without changing the implementation with `bind` command on bash, and `bindkey` on zsh after sourcing `~/.fzf.*` in your configuration file. I know it's not the most easiest thing to do, but I don't think I want to add more configuration variables at this point.

> the default options

Have you tried setting up `$FZF_DEFAULT_OPTS`?

```sh
export FZF_DEFAULT_OPTS='--reverse'
```

> Also, is there a documentation on how to do custom color scheme with --color?

See `man fzf` for the details. Also check out [the wiki page](https://github.com/junegunn/fzf/wiki/Color-schemes).

**Comment by guiniol** [comment]
> You'll be able to override the key bindings only without changing the implementation with bind command on bash, and bindkey on zsh after sourcing `~/.fzf.*` in your configuration file. I know it's not the most easiest thing to do, but I don't think I want to add more configuration variables at this point.

That would be fine by me, but since the keybindings are explicitely defined in `~/.fzf.*`, previous keybindings set in another place are removed. Also, if I change the history widget keybinding, then the sort toggle is not changed. Maybe a solution would be to have variables like `$FZF_DEFAULT_OPTS` for the keybindings? Then again, maybe it's only me.

> Have you tried setting up `$FZF_DEFAULT_OPTS`?

I tried, but it didn't change anything so I figured it wasn't for the functions with keybindings. I must have done something wrong and will try again.

> See man `fzf` for the details. Also check out [the wiki page](https://github.com/junegunn/fzf/wiki/Color-schemes)

I missed that page... sorry

**Comment by junegunn** [comment]
We now have more options for those key bindings:

https://github.com/junegunn/fzf#key-bindings-for-command-line

**Comment by guiniol** [comment]
Nice. I'll try that as soon as I can.
Thanks a lot.
