### ISSUE TITLE
lag with zsh and bash fzf integration

### ISSUE THREAD

**Issue by bturrubiates** [junegunn/fzf#445]
I decided to try out fzf today and installed it on my MacBook Pro (OS X 10.10.5) though brew (fzf version 0.10.9). The interface itself seems very response. If I hit alt-c I get a very usable fuzzy finding interface, but once I've selected the file itself the `cd` takes a couple of seconds on average and sometimes can take several seconds. I tried starting zsh without any of my configuration and I don't have any configuration in bash but both are still very slow once the file has been selected. This also seems to happen to a lesser extent in the text replace widget too (ctrl-t). The GIFs in the README seem to show much better performance after selection of the file than I'm experiencing. I thought it may have been fixed in a newer version so I installed from Git and I'm experiencing the same behavior.

The system itself is mostly idle so I don't think this should be happening, but I haven't seen any other issues about this so maybe it's unique to something on my system. I'm not exactly sure how to start debugging this, but I can reproduce it without any configuration. 

Other than this :+1: 

edit: I should also mention, this doesn't seem to happen if I run `fzf` directly and the reverse search functionality also doesn't seem affected.

**Comment by bturrubiates** [comment]
Oh, my fault. Figured it out, I didn't realize that `fzf` was trying to search through an NFS share I had mounted.

**Comment by junegunn** [comment]
Alright, note that you can change the command fzf uses for those key bindings with `FZF_CTRL_T_COMMAND` and `FZF_ALT_C_COMMAND`.
