### ISSUE TITLE
enabling compinit and setopt all_export crashes fzf on tab 

### ISSUE THREAD

**Issue by fishman** [junegunn/fzf#448]
Using the following options with zsh crashes:

 thread #1: tid = 0x44f9d9, 0x00007fff9cf00154 libsystem_c.dylib`wmemcmp + 14, queue = 'com.apple.main-thread', stop rea
son = EXC_BAD_ACCESS (code=1, address=0x0)
    frame #0: 0x00007fff9cf00154 libsystem_c.dylib`wmemcmp + 14
libsystem_c.dylib`wmemcmp:

    autoload -U compinit zrecompile

    compinit
    setopt all_export

    [ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

**Comment by junegunn** [comment]
Thanks for the report, but with the above snippet in my .zshrc, I can't reproduce the issue on my machine with zsh 5.0.8 (x86_64-apple-darwin15.0). Consider reinstalling or upgrading your zsh.
