### ISSUE TITLE
Adding --line-number ?

### ISSUE THREAD

**Issue by netei** [junegunn/fzf#449]
Grep has this option : 

> -n, --line-number
       Prefix each line of output with the 1-based line number  within  its  input  file.   (-n  is
       specified by POSIX.)

This is useful when you would like to know the line the user selected, for example if multiple lines have the same content but the position in the file matters (which could be useful for a log searcher I am writing).

**Comment by junegunn** [comment]
http://superuser.com/questions/10201/how-can-i-prepend-a-line-number-and-tab-to-each-line-of-a-text-file

Does this help?

**Comment by netei** [comment]
Indeed, that does the trick combined with --delimiter and --nth
