### ISSUE TITLE
fzf (ncurses?) fails to reflow the screen sometimes when in tmux

### ISSUE THREAD

**Issue by jez** [junegunn/fzf#450]
I've been a long time user of fzf (great project!), and I've tried debugging this issue multiple times to no avail. I've created an asciicast that demonstrates the bug, but it goes by kind of quickly. Here's the gist of it:

- I launch tmux in a project folder
- I launch fzf in a tmux split using the keybindings
- I type `bvh` and scroll through the results
  - note how there are some artifacts at the top that aren't part of the results
  - note how there the second option doesn't draw correctly until highlighted
- I repeat the process with `vec`
  - this time all the results are reachable, but most still don't draw correctly
- Finally for reference, I quit tmux and note that it's back to normal; everything reflows correctly.

[![asciicast](https://asciinema.org/a/6c8a3prm51fr8yrv5b5wuxlp8.png)](https://asciinema.org/a/6c8a3prm51fr8yrv5b5wuxlp8)

I'm using
- fzf 0.11.1
- zsh
- tmux 2.0
- iTerm2
- OS X

I thought for a long time that it might have been because I have a custom terminal info file that defines `xterm-256color-italic` for italics in the terminal, but I can reproduce it by completely disabling this and just using `xterm-256color`.

**Comment by junegunn** [comment]
No, you shouldn't be using `xterm-*`. See #176.
