### ISSUE TITLE
Override the empty buffer when splitting in Vim

### ISSUE THREAD

**Issue by chaucerbao** [junegunn/fzf#451]
Is there a way for FZF to close/override the empty buffer when opening splits in Vim?

For example, I open up Vim and start with an empty buffer. Then, I use FZF to select 2 files and open them in splits (CTRL-X or CTRL-V). I end up with 3 buffers: empty buffer, file-1, file-2. I would like to only see the 2 files I selected.

**Comment by junegunn** [comment]
Thanks for the suggestion. I like the idea and updated the vim plugin. I also updated the commands in [fzf.vim](https://github.com/junegunn/fzf.vim) project.
