### ISSUE TITLE
yank history for vim?

### ISSUE THREAD

**Issue by anvaka** [junegunn/fzf#454]
Hello,

Thanks for fzf. Love it a lot!

I'm just curios, is it possible to get yank history in vim similar to `:Buffers` command (e.g. `:Yank`)?

**Comment by junegunn** [comment]
Hi, looks like [the issue tracker of fzf.vim](https://github.com/junegunn/fzf.vim/issues) is a better place for this discussion, right? Anyway I don't think yank history of vim is directly available via API. Correct me if I'm wrong. There is a plugin called yankring that keeps track of the history but I don't use it and haven't looked at the code. Maybe it's possible to make `fzf#run` function access the data structure of yankring.

**Comment by netei** [comment]
Maybe a :Registers command would be useful, but I don't think that I would be using it.

**Comment by anvaka** [comment]
@junegunn thanks! I didn't realize fzf.vim is a separate repository. Please feel free to resolve it here. 

@netei thanks for point to :Registers; Looks like it's not as capable as `yankring`/`Unite history/yank`, but could work as a simple alternative.
