### ISSUE TITLE
fzf error when using tmux: No record of process xxxx

### ISSUE THREAD

**Issue by micho8402** [junegunn/fzf#460]
Hi, I'm having an error when I attempt to use fzf running tmux. The issue happens when after invoking fzf via autocompletion (vim **) or CTRL-R binding I select a file option or just ESC to exit, fzf crashes and tmux exits. I can see in my command line a msg like: `-bash: wait_for: No record of process xxxx`. What's interesting is that this does not happen if I just use CTRL-T binding. And it doesn't happen at all if not running tmux. Not sure really if this is on tmux or fzf.

My env:
OSX El Capitan
iTerm2 Build 2.1.4
tmux 2.2 (with no specific config)
$TERM=xterm-256color

I'm also using powerline (python) (only active for VIM)
Note: I installed fzf from git repo, then I changed my mind and re-installed it using brew (I uninstalled it first though)

Thanks

**Comment by junegunn** [comment]
I don't have the problem on El Capitan + iterm2 2.1.4 + tmux 2.1. Not sure if it's related to the problem you described, but for one thing, `xterm-256color` is not allowed on tmux.

Excerpt from: http://tmux.cvs.sourceforge.net/viewvc/tmux/tmux/FAQ

```
******************************************************************************
* PLEASE NOTE: most display problems are due to incorrect TERM! Before       *
* reporting problems make SURE that TERM settings are correct inside and     *
* outside tmux.                                                              *
*                                                                            *
* Inside tmux TERM must be "screen" or similar (such as "screen-256color").  *
* Don't bother reporting problems where it isn't!                            *
*                                                                            *
* Outside, it must match your terminal: particularly, use "rxvt" for rxvt    *
* and derivatives.                                                           *
******************************************************************************
```
See: https://github.com/junegunn/fzf/issues?utf8=%E2%9C%93&q=xterm-256color+

First check if changing it to `screen-256color` helps.

Also note that fzf on Homebrew is a couple months behind the master, but I don't think there was a critical bug fix during the time.

**Comment by micho8402** [comment]
Thanks, sorry for the obvious mistake, however I switched TERM to screen-256color, but it didn't solve the problem, my VIM now looks ugly though.
Also I updated fzf to <HEAD> version, it didn't work either, however it solved a problem I had before with paths including spaces where fzf was doing double escaping (`\\\`), and that's great!. Thanks.
I tried moving the tmux invoking up in my .bash_profile before everything else, the only difference now is that when it crashes the whole iTerm tab goes away.

Probably this is something related to my current config (although I'm setting up a new El Capitan installation from scratch), I haven't used tmux before so I guess I don't need it, main reason I was using it was to avoid fzf from opening "fullscreen". If there is not other obvious thing I can try I guess I can close the ticket. Thank you.

**Comment by micho8402** [comment]
Definitely something with my terminal configuration, not related with fzf. This is breaking my terminal from the very beginning:

# .bash_profile
export "TERM=screen-256color"
exec tmux

Thanks. Closing this.

**Comment by atweiden** [comment]
@junegunn in tmux 2.1 (https://github.com/tmux/tmux/commit/7382ba82c5b366be84ca55c7842426bcf3d1f521) $TERM inside tmux can be `tmux` or `tmux-256color`.

**Comment by junegunn** [comment]
@atweiden Oh, thanks. I think I'm going to stick to `screen-256color` for a while due to compatibility issue as I frequently ssh to many old servers.
