### ISSUE TITLE
Error when running ~/.fzf/install

### ISSUE THREAD

**Issue by idurandiaz** [junegunn/fzf#462]
After cloning the git manually or with vim-plug and running `~/.fzf/install`, I get the following error:

```
Downloading bin/fzf ...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:03 --:--:--     0curl: (77) error setting certificate verify locations:
  CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
  - Failed to download fzf-0.11.1-linux_amd64 !!!
```

**Comment by justinmk** [comment]
@idurandiaz something wrong with your OS root certificates, or curl. Not related to fzf.

**Comment by idurandiaz** [comment]
Any idea how to solve that?

**Comment by junegunn** [comment]
Only Google knows :)
As @justinmk said, it's not a problem of fzf itself, please let us know if you find a solution. Thanks

**Comment by idurandiaz** [comment]
Found a solution in this link: http://askubuntu.com/questions/342484/etc-pki-tls-certs-ca-bundle-crt-not-found

However for me it was enough to just add `sudo` to `~/.fzf/install` (and restart terminal). Thanks.
