### ISSUE TITLE
Anyway to toggle --exact mode after fzf was launched?

### ISSUE THREAD

**Issue by tkrugg** [junegunn/fzf#463]

**Comment by junegunn** [comment]
No, it's not currently supported.

I suggest instead getting used to readline keybindings <kbd>ALT-B</kbd><kbd>'</kbd><kbd>ALT-F</kbd> (or <kbd>CTRL-A</kbd><kbd>'</kbd><kbd>CTRL-E</kbd>) to quickly prepend `'` to the search term.

**Comment by akharrou** [comment]
I think a `toggle-exact` action would be actually useful, just like `toggle-sort`. E.g. I would like to bind it to `alt-e`, and toggle it on and off as need be, just like the sorting, it's super handy, and especially if we could see a `[-|+]E` in the prompt area, like the sorting `[-|+]S`, that would be amazing !
