### ISSUE TITLE
fzf android download

### ISSUE THREAD

**Issue by acornejo** [junegunn/fzf#465]
Just got a new tablet and realized how convenient it would be to be able to just download the fzf binary instead of installing from source.

Could it be added it to the releases?

**Comment by junegunn** [comment]
Hi, I just uploaded the binary [here](https://github.com/junegunn/fzf-bin/releases). Do you think we should also update install script for the platform?

**Comment by acornejo** [comment]
I think addling it to the install script would be incredibly useful. I think more and more folks are trying to use tablets as a dev environment, and having fzf available is a big productivity bonus.

There are a few details that need to worked out. Namely, android doesn't ship use gnulibc, but its own implementation of libc (known as bionic). There are two camps for running a terminal on android, on the one hand, there is termux (https://github.com/termux/termux-packages), and on the other there is gnuroot (https://github.com/corbinlc/gnuroot). The first one compiles all packages against the builtin/included bionic, which usually requires patching packages to get them to build (for instance, ncurses will not build unpatched against bionic). The second one first builds and android gnulibc, and then just uses the standard packages (i.e. you can install full blown debian or redhat chroot on your android device).

The Dockerfile I contributed uses the native libc provided by android (bionic), but for completness we should also provide a build that use the gnulibc, since there are  plenty of users of both approaches.

The next detail would be a way to detect weather the android system is using bionic or gnulibc. Something like this should work (may not be the actual string, but something along those lines).

```
if [[ $(ld $(which sh)) ~= "*/system/lib/libc* ]]; then
  echo using bionic
else
  echo using libc
fi
```

When I get some time I'll contribute another PR to add a build of fzf that uses gnulibc, and perhaps even some changes to the install script. Thoughts?

**Comment by junegunn** [comment]
Sounds great.

**Comment by fornwall** [comment]
On a related note: A fzf package was just added to Termux, which can be installed with `apt install fzf`. This one is custom to Termux (linking against both the Android bionic libc and the Termux libncurses) so doesn't change the need of a general solution discussed here, but I thought I would give a heads up if anyone is interested!
