### ISSUE TITLE
zsh ^R key binding in root shell doesn't work

### ISSUE THREAD

**Issue by kurkale6ka** [junegunn/fzf#466]
Context:

From a normal user zsh shell, run `sudo -E /usr/bin/env zsh`.
Then `^R` doesn't work because `fzf-tmux` freezes. I could make it work by setting: `FZF_TMUX=0`

Note: the problem isn't present if switching to root by doing: `su -`

**Comment by junegunn** [comment]
Nice find. This is not specific to zsh. fzf-tmux doesn't run in such situation. I'll see what I can do.

**Comment by junegunn** [comment]
Should be fixed now. Can you update and check if it works for you?

**Comment by kurkale6ka** [comment]
It works yes. Thanks!

**Comment by junegunn** [comment]
Thanks. Maybe someone would argue that the fifos should not be made writable by others. But I don't see a better option.
