### ISSUE TITLE
Option to automatically run selected shell history item?

### ISSUE THREAD

**Issue by af** [junegunn/fzf#467]
I really like fzf's interactive shell history (^R) support. However, it'd be even better if there was a way to automatically invoke the selected command, rather than pressing Enter again to confirm once fzf closes. Is this possible?

Apologies if this is documented somewhere, I couldn't find it.

**Comment by junegunn** [comment]
No, currently there's no option for that. But you can easily extend the behavior. For example on zsh,

```sh
fzf-history-widget-accept() {
  fzf-history-widget
  zle accept-line
}
zle     -N   fzf-history-widget-accept
bindkey '^R' fzf-history-widget-accept
```

And on bash

```sh
bind '"\C-r": " \C-e\C-u$(__fzf_history__)\e\C-e\e^\er\C-m"'
```

**Comment by af** [comment]
That works, thank you!

**Comment by melkster** [comment]
Hi! Is it possible for me to create a mapping inside of fzf to immediatly run the selection? That way I can choose if I want to run it immediately or if I want to just select the text so that I can edit it, etc.
