### ISSUE TITLE
Don't `set spell` in fzf buffer

### ISSUE THREAD

**Issue by euclio** [junegunn/fzf#469]
Currently, when invoking `:FZF` while `set spell` is enabled in nvim, the buffer contents are spellchecked. This causes distracting underlines to appear in the paths.

**Comment by junegunn** [comment]
Thanks. That makes more sense. I didn't realize it due to [the code](https://github.com/junegunn/fzf.vim/blob/b97a6393ff53acd6145185a400cf6aa44d525ecc/plugin/fzf.vim#L104) in fzf.vim project.
