### ISSUE TITLE
Illumos/SmartOS/Solaris Support

### ISSUE THREAD

**Issue by DominoTree** [junegunn/fzf#470]
I've been doing work lately with some Vim and NeoVim-related items in preparation to finish the last few things to get NeoVim working on Solaris and its derivatives.

With a couple minor changes to the install script, I can make fzf install cleanly on Solaris.  If you're interested, I can make a PR with the changes and provide binaries for releases; maybe they could end up at https://github.com/junegunn/fzf-bin/releases/download/0.11.1/fzf-0.11.1-sunos_i86pc.tgz or something similar.

There are a number of people who are interested in using NeoVim on Solaris, and I'm sure some of them would also like to use FZF (a couple of tweaks also need to happen with Ruby to get the fallback version working, so nothing actually works out of the box on Solaris right now)

I'd be glad to build binaries and keep everything up to date and working on this platform.  For that matter, it would probably also be worth building FreeBSD binaries (and it'd also probably be very easy), and I could take care of that as well.

Let me know if you're interested!

![OpenIndiana](http://i.imgur.com/6O8FCzW.jpg)

**Comment by junegunn** [comment]
Thanks. I should be able to build the binaries locally. Can't ask you every time I want to release a new version :) I'm currently using docker to spin up linux vm and build linux binaries on it. `make all linux android` is the command. If you could extend the build script, I'd happy to build and upload the binaries.

**Comment by DominoTree** [comment]
I can do that, Go is pretty friendly about cross-compiling

**Comment by junegunn** [comment]
Cool. I've been using docker and vm because of the numerous issues with ncurses and cgo.

**Comment by rosstimson** [comment]
I'd love to see FeeBSD binaries, or even just some documentation on how to compile myself without all the Docker stuff as you can't run FreeBSD in Docker unless you are already on a FreeBSD host.  The project doesn't seem to follow the usual conventions so it's not obvious to me, although I'm also a Go n00b.

**Comment by junegunn** [comment]
The prebuilt binaries are provided not to require Go development environment. If you do have Go installed on your system, `go get github.com/junegunn/fzf/src/fzf` will build the binary for you. Maybe I should add this workaround to `install` script. Having said that, I'd also like to provide binaries for more platforms, but it should be easy for me to build the set of binaries locally.

**Comment by rosstimson** [comment]
@junegunn  Awesome, that worked a treat!  I'd tried a bunch of ways such as copying the `fzf/src` contents into appropriate place in GOPATH and then `go build`.

Binaries would be great but I'm very pleased I now have FZF on my FreeBSD laptop.
