### ISSUE TITLE
Vim: When re-opening existing buffer the line is reset to 1.

### ISSUE THREAD

**Issue by dpc** [junegunn/fzf#472]
I use fzf map as <c-p> to quickly switch between buffers. One thing that is annoying is that even already open buffers are being re-opened, and the cursor line is back to 1.

I could probably workaround it with saving and restoring position in file like http://vim.wikia.com/wiki/Restore_cursor_to_file_position_in_previous_editing_session , but I wonder if it could be improved in FZF itself. It could detect if the buffer is already open and switch to it, instead of reopening the file.

**Comment by justinmk** [comment]
Use `set nostartofline` option in vim/neovim.

**Comment by dpc** [comment]
This solves my problem, thank you!
