### ISSUE TITLE
MRU sort order in vim

### ISSUE THREAD

**Issue by mattsawyer77** [junegunn/fzf#474]
I've been experimenting with your MRU examples for vim. Is there a way to sort the MRU files by how recently they were opened? Or is that information simply not available in vim? Would a plugin like [neomru](https://github.com/Shougo/neomru.vim) help any in this case? I've noticed that both CtrlP and Unite seem to be able to create a MRU list sorted correctly. 

The use case here is that I want to be able to switch back quickly to the previously viewed buffer (without having to type most of the filename).

**Comment by junegunn** [comment]
> Or is that information simply not available in vim? 

As far as I know, `v:oldfiles` is all we have. MRU plugins you mentioned manually do the bookkeeping.

- https://github.com/kien/ctrlp.vim/blob/master/autoload/ctrlp/mrufiles.vim#L133-L139
- https://github.com/Shougo/neomru.vim/blob/master/plugin/neomru.vim#L46-L49

.. which is not what I'm interested in doing. If might be possible though that we can use the information from those plugins, with their API or exposed global variables.

> The use case here is that I want to be able to switch back quickly to the previously viewed buffer

Are you aware of <kbd>CTRL-6</kbd> (`:help CTRL-6`)? <kbd>CTRL-O</kbd> is also nice.

**Comment by mattsawyer77** [comment]
thanks for the info @junegunn ! I was unaware of CTRL-6 and CTRL-O -- those should come in handy. And for now CtrlP's MRU works fine. Just thought if there was a way to do everything with FZF, it might be nice.

**Comment by junegunn** [comment]
<kbd>CTRL-6</kbd> is simply indispensable :)

**Comment by vito-c** [comment]
nice `CTRL-6`! maybe a shared MRU repo as plugin?

**Comment by tweekmonster** [comment]
I made my own script to track the MRU for fzf.vim sometime last year and didn't think to make it public.  I've been using the `FilesMru` command as a replacement for ctrl-p and the MRU tracking I added to it has been working pretty well.

Here it is if any of you are interested: https://github.com/tweekmonster/fzf-filemru
