### ISSUE TITLE
[bug?] Installs to wrong shell.

### ISSUE THREAD

**Issue by trusktr** [junegunn/fzf#475]
I use ZSH, but fzf appended a line only to bashrc.

**Comment by trusktr** [comment]
Nevermind, for some reason I didn't see it, but now I do.

**Comment by junegunn** [comment]
The install script updates .bashrc, .zshrc, and fish configuration regardless of the current shell. If you don't like the behavior you can only download the binary with `--bin` option and do the rest manually, or use `--no-update-rc` option.
