### ISSUE TITLE
respect Ag args

### ISSUE THREAD

**Issue by vbauerster** [junegunn/fzf#476]
At the moment :Ag command ignores own ag switches.
It would be nice, if it will be possible to pass --css switch for example in order to narrow search in css files only, like this:
```:Ag --css pattern```

**Comment by vbauerster** [comment]
Sorry, close this post, as it is addressed to vim pulgin

**Comment by junegunn** [comment]
See the discussion in https://github.com/junegunn/fzf.vim/issues/51. So the options are to use the `:Ag` command as it is, or to define your own command using `fzf#vim#ag(query, ag_options, options)` function. I hope to find a cleaner (and easier) solution.
