### ISSUE TITLE
Use fzf-completion *both* with, and without, a trigger, in Zsh

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [junegunn/fzf#478]
So, when in `viins` mode in Zsh, I use the following map:

    export FZF_COMPLETION_TRIGGER=';'

(I chose `;` because it's right above `.` and `/`, so my finger's already usually down there when typing paths; and it's senseless to want to normal-complete immediately after a semicolon.)

Now, I *want* to do this:

    bindkey    '^I' fzf-completion
    bindkey -a ';'  fzf-completion

That is, I want `esc-;` to function about the same way as `;-tab` (with, of course, the benefit of being able to preform other movements before initiating completion.)

Unfortunately, `$FZF_COMPLETION_TRIGGER` is checked, even when the zsh-widget is invoked in `vicmd` mode; so I'd *still* have to insert a `;` into the string before the completion-point when invoking `vicmd`-`;`.

Could I get the *meat* of `fzf-completion` extracted to a different widget that *doesn't* check `$FZF_COMPLETION_TRIGGER`, like `fzf-complete` or `fzf-directly-complete` or something? This would allow for the following:

    export FZF_COMPLETION_TRIGGER=';'
    bindkey    '^I' fzf-completion
    bindkey -a ';'  fzf-directly-complete

**Comment by junegunn** [comment]
I'm not sure if I understood your intention correctly largely because I don't use zsh. Is it possible to define your own function that temporarily swaps FZF_COMPLETION_TRIGGER around fzf-completion?

```sh
fzf-direct-completion() {
  FZF_COMPLETION_TRIGGER=''
  fzf-completion
  FZF_COMPLETION_TRIGGER=';'
}
```

Incidentally, some users prefer having a dedicated fzf completion key:
https://github.com/junegunn/fzf/wiki/Fuzzy-completion#zsh

**Comment by junegunn** [comment]
This seems to work well.

```sh
fzf-direct-completion() {
  FZF_COMPLETION_TRIGGER= fzf-completion
}
zle -N fzf-direct-completion
```
