### ISSUE TITLE
fzf autostarting and breaking with git commands

### ISSUE THREAD

**Issue by EduardoRT** [junegunn/fzf#480]
Hi! so first of all this could be ( almost 90% sure ) my fault but I can't find where this is breaking.

I'm using oh-my-zsh with various plugins enabled, I've already tried this without any plugins and it still breaks, I don't have any other issue with any other command that i've found other than `git`

it breaks when doing `git <command> <TAB>` or `git <TAB>` it opens a fzf search that keeps looping with 0/0 matches, it's also impossible to close.

https://youtu.be/tzD2urWE-n4

I've tried installing it through brew and manually, I've tried disabling keybindings and fuzzy search.

Other than that fzf is perfect and I'm in love with it.

**Comment by junegunn** [comment]
Please share your configuration file. It would be easier for me to look through if you could strip it down to the core.

And a few things to check:
- `bindkey "^I"`
- `bindkey | grep fzf`
- `echo $fzf_default_completion`

> it's also impossible to close.

You mean, CTRL-C doesn't work?

> I've tried disabling keybindings and fuzzy search

If you disable keybindings and fuzzy completion, there is no way fzf can start on tab key. Have you made sure that you restarted the shell?

**Comment by EduardoRT** [comment]
Thanks for the prompt response @junegunn, 

I haven't done any heavy modifications to any of my configs to be honest but here they are.

zshrc: 
http://sprunge.us/VGMf

this is the file that gets sourced:
http://sprunge.us/DPdG

and this is my oh-my-zshrc:
http://sprunge.us/DGAV

> You mean, CTRL-C doesn't work?

Yeah, CTRL-C does nothing, CTRL-Z doesn't send the job to the background, I have to kill my terminal or tmux panel.

> bindkey "^I"
>bindkey | grep fzf
>echo $fzf_default_completion

I'm sorry but what should I do whit this?

> If you disable keybindings and fuzzy completion, there is no way fzf can start on tab key. Have you made sure that you restarted the shell?

Yep, just tried it again, sourced and killed my terminal to be sure and it still does it ( I uninstalled it, closed my term and then reinstalled it again ).

Thanks again!

**Comment by junegunn** [comment]
I want you to see me the output of those commands.

> Yep, just tried it again, sourced and killed my terminal to be sure and it still does it ( I uninstalled it, closed my term and then reinstalled it again ).

You know that it does not make sense, right? Because you disable key bindings and fuzzy completion (by saying no to the prompt during install script), `~/.fzf.zsh` only touches your `$PATH` and `$MANPATH`. There must be some conflicting settings in your .zshrc. Try starting from a clean zshrc.

**Comment by EduardoRT** [comment]
Alright so,

`bindkey "^I"` returns : `"^I" fzf-completion`

`bindkey | grep fzf` returns:
```
"^I" fzf-completion
"^R" fzf-history-widget
"^T" fzf-file-widget
"^[c" fzf-cd-widget
```

and `echo $fzf_default_completion` returns:
`expand-or-complete`

I know it doesn't make sense but it is doing so, I'm pretty sure it's my fault though,

Here's the video.
https://www.youtube.com/watch?v=SXrZwAnJP40

If I remove `source ~/.oh-my-zsh/oh-my-zsh.sh` from my .zshrc it stops breaking, weird thing is I haven't done anything to my oh-my-zsh.sh directly, I've just activated plugins but It doesn't matter If I deactivate them it still wont work.

thanks for the help.

**Comment by junegunn** [comment]
> bindkey "^I" returns : "^I" fzf-completion

It means that the fuzzy completion from fzf is currently enabled.

1. Please run the install script again, opt-out fuzzy completion (press n), and restart the shell and check the output of the commands again. In this step, I'd like to make sure that fuzzy completion should not be enabled as expected.

2. Rerun the install script, say yes to fuzzy completion. Check if `ls **<tab>` brings fzf completion and it works. If it shows the same symptom as `git`, please share your full configuration file.

**Comment by junegunn** [comment]
I just checked your video. You have to **restart** (close the terminal) the shell after opting-out fuzzy completion, simplying re-sourcing zshrc won't do, since fuzzy completion is already set up and the updated `.fzf.zsh` won't touch it.

**Comment by EduardoRT** [comment]
Tried with closing instead of sourcing between every step and it still autocompletes me with <TAB> but just with the git command :/

**Comment by junegunn** [comment]
Cannot reproduce with this .zshrc

```sh
export ZSH=/Users/jg/.oh-my-zsh
ZSH_THEME="robbyrussell"
plugins=(git)
source $ZSH/oh-my-zsh.sh
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
```

**Comment by EduardoRT** [comment]
@junegunn thank you very much! I found the culprit with your config, it seems that oh-my-zsh's [common-aliases](https://github.com/robbyrussell/oh-my-zsh/wiki/Plugins#common-aliases) breaks it, just removing that specific plugin fixes everything, I'm really sorry, I thought that I tried that correctly but it seems I removed my plugins wrong before.

Thanks a lot!

**Comment by junegunn** [comment]
I'll check if the problem is reproducible with the plugin you mentioned, and see if there's something I can do about it.

**Comment by junegunn** [comment]
```sh
export ZSH=/Users/jg/.oh-my-zsh
ZSH_THEME="robbyrussell"
plugins=(git common-aliases)
source $ZSH/oh-my-zsh.sh
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
```
This still works. Maybe it's some combinations of plugins that cause the problem, but I don't know.
