### ISSUE TITLE
How to kill fzf from another tty?

### ISSUE THREAD

**Issue by D630** [junegunn/fzf#482]
Hi,

How can I kill fzf in tty A from tty B without making tty A unusable after killing and leaving?

```sh
# tty A
% echo $TERM ; tty
st-256color
/dev/pts/0
% fzf --reverse --bind="enter:execute(exec ps -p \$$ -o ppid= >/tmp/FZF)" || ls -1 /tmp | fzf --reverse

# tty B
% echo $TERM ; tty
st-256color
/dev/pts/6
% kill $(< /tmp/FZF)
```

**Comment by junegunn** [comment]
fzf handles SIGINT, so `kill -2` will trigger clean exit.

(FYI, `reset` command restores the terminal state)

**Comment by junegunn** [comment]
The next version will handle SIGTERM as well :)
