### ISSUE TITLE
fzf breaks with some kind of escape sequence

### ISSUE THREAD

**Issue by netei** [junegunn/fzf#483]
Whenever I run some program (which I can't share) and pipe it's output to fzf like this : 

`program | FZF_DEFAULT_OPTS="-1 --margin 5%,5%" fzf`

I get the following display error : 

![fzf_bug](https://cloud.githubusercontent.com/assets/13066384/12809575/82d379b2-cb20-11e5-8367-05cddf416a28.PNG)

What I then type is completely out of sync with the results shown : 

![fzf_bug_out_of_sync](https://cloud.githubusercontent.com/assets/13066384/12809607/bcfd1bde-cb20-11e5-8c56-fa8d4200d170.PNG)

I have tried to record the output of program to be able to share with you how it doesn't work, but so far, I wasn't able to capture the output of that program so that I can share it to you (because they must be some kind of "invisible" escape sequences for it ) . Here is a stackoverflow post of my attempts to capture that output : http://stackoverflow.com/questions/35181950/record-replay-stdout-including-escapes-timing?noredirect=1#comment58081761_35181950

Note that the error doesn't appear when I run 

`program | FZF_DEFAULT_OPTS="--margin 5%,5%" fzf`

so it has something to do with the -1 option.

Without the --margin option, the error still occurs, but it is easier to share that the cursor is completely out of sync whenever there is a margin.

I'm running this in tmux.

Whenever running the same outside of tmux, the bug occurs, but the cursor is moved on the bottom right of the screen instead of on the bottom left.

Any ideas ?

**Comment by junegunn** [comment]
Is it okay to make fzf wait until the "program" finishes? If so, does `--sync` option help?

**Comment by netei** [comment]
In this particular case, it is ok for me to use `--sync`, and I've tested and the problem doesn't occur when using 

`FZF_DEFAULT_OPTS="-1 --margin 5%,5% --sync" fzf`

I just wanted to send you this issue in case they is something special with `-1` that could explain this.

**Comment by junegunn** [comment]
`-1` delays the initialization of the screen until it is confirmed that there are more than 1 matches, so maybe the terminal is getting partial escape sequences before fzf starts? If that's the case, <kbd>CTRL-L</kbd> should correctly refresh the screen. Does it help?

By the way, is there any reason you set `FZF_DEFAULT_OPTS` here? You can simply `fzf -1 --margin 5%,5% --sync` .You probably should know this but..

**Comment by netei** [comment]
Strangely, C-L doesn't do anything (but it usually works when writing to stderr). 

Here's the output after pressing C-L

![ctrr-l](https://cloud.githubusercontent.com/assets/13066384/12812077/dfe89028-cb30-11e5-90d4-eb2c81df4e8a.PNG)

> By the way, is there any reason you set FZF_DEFAULT_OPTS here? You can simply fzf -1 --margin 5%,5% --sync .You probably should know this but..

Yes, I know that, I wanted to make it explicit that I don't have anything else in my `FZF_DEFAULT_OPTS`. I could have done `FZF_DEFAULT_OPTS="" fzf -1 --margin 5%,5%`  yoo

**Comment by junegunn** [comment]
> Yes, I know that, I wanted to make it explicit that I don't have anything else in my FZF_DEFAULT_OPTS.

:+1: 

Is there any way I can locally reproduce the problem?

**Comment by netei** [comment]
Here's a way to reproduce with nodejs (the bug appears with v0.12.7 and v5.5.0)

test.js
```
"use strict";

var yeoman = require("yeoman-generator");
var helpers = require("yeoman-test");
var P = require("bluebird");
var R = require("ramda");
var path = require("path");
var caches = [];
var id, cache;

beforeEach(function () {
  caches.push(R.evolve({}, require.cache));
  for (id in require.cache) {
    delete require.cache[id];
  }
});

afterEach(function () {
  for (id in require.cache) {
    delete require.cache[id];
  }
  cache = caches.pop();
  for (id in cache) {
    var parts = path.parse(id);
    require.cache[path.join(parts.root, id.substr(parts.root.length))] = cache[id];
  }
});

var yostart = yeoman.Base.extend({
  prompting: function () {
    var self = this;
    var done = self.async();
    return new P(function (resolve) {
      self.prompt({}, resolve);
    }).then(function (answers) {
      self.props = answers;
    }).then(done).catch(done);
  },
  writing: function () {
    this.fs.copyTpl(
      this.templatePath("foo"),
      this.destinationPath("foo"),
      this.props
    );
  }
});

it("the it", function () {
  return new P(function () {
    return helpers.run(yostart);
  });
});
```

Then do `npm install yeoman-generator yeoman-test bluebird ramda`

You also need mocha , install it with `npm install -g mocha`

Then run : `mocha test.js--reporter json-stream | fzf`

**Comment by junegunn** [comment]
<img width="1280" alt="screen shot 2016-02-05 at 12 39 21 am" src="https://cloud.githubusercontent.com/assets/700826/12820100/f1fd9806-cba0-11e5-9d3f-7706b030fa08.png">

Doesn't seem to be reproducible.

**Comment by edi9999** [comment]
Hi, I can reproduce on a completely different computer, tough, the bug isn't visible : the cursor was placed at the correct position, but the filtering didn't work : 

![selection_032](https://cloud.githubusercontent.com/assets/2071336/12839976/c40f7ed0-cbde-11e5-9cdf-f6951293aa80.png)

I will try to set up a dockerfile to test this.

**Comment by junegunn** [comment]
Okay, I don't have problem with filtering. I'm planning on releasing 0.11.3 within a few days, and I hope we get the idea of what's going on with this soon.

**Comment by edi9999** [comment]
Hi again,

here's a Dockerrepository that reproduces the issue : 

https://github.com/edi9999/testfzf

I've added instructions on how to reproduce in the [readme](https://github.com/edi9999/testfzf/blob/master/readme.md)

Strangely, they are some rendering issues no matter what the input is (even with `printf "foo\nbar\n" | fzf` ). But the filter is "out of sync" with the matches only with the input.

I've set TERM=screen

**Comment by junegunn** [comment]
Thanks, but for some reason, it doesn't work for me.

```
root@dc413e54d0c1:/src# mocha /src/test.js --reporter json-stream
module.js:341
    throw err;
    ^

Error: Cannot find module './vendor/parse'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/src/node_modules/yeoman-generator/node_modules/read-pkg-up/node_modules/read-pkg/node_modules/load-json-file/node_modules/parse-json/index.js:3:16)
    at Module._compile (module.js:413:34)
...
```

I also see `bash: /go/fzf/shell/key-bindings.bash: No such file or directory` on `docker run ...`. Is it expected?

**Comment by edi9999** [comment]
Indeed, the node_modues I commited were incorrect, try again now please

**Comment by edi9999** [comment]
I don't understand, it works now . So confused as to where this problem could come from

**Comment by junegunn** [comment]
Hmm, `git pull`ed, but seeing the same error.

**Comment by junegunn** [comment]
Let me know if it occurs again.

**Comment by edi9999** [comment]
Sure !
