### ISSUE TITLE
Completion trigger for fish

### ISSUE THREAD

**Issue by nh2** [junegunn/fzf#484]
I noticed that `**` completion triggers don't work in `fish`. Would be awesome if they did!

**Comment by junegunn** [comment]
Yes, fuzzy completion is only supported for bash and zsh.

https://github.com/junegunn/fzf#fuzzy-completion-for-bash-and-zsh

Unfortunately I'm not a fish expert and don't know to how to implement fuzzy completion on it. Let me know if you're interested in contributing.

**Comment by hauleth** [comment]
AFAIK it is not possible now. Actually it would be better to open issue in fish-shell/fish-shell to allow external completion tool, so `cmd <TAB><TAB>` would open `fzf` instead of built in fuzzy-finder.

**Comment by coderstephen** [comment]
This isn't available in the Fish core yet, but there is now a third-party script plugin that enables writing these types of completions called [`expand`](https://github.com/oh-my-fish/plugin-expand) (shameless plug, I wrote it). If you're looking for fancier fzf integration for Fish, likely a plugin could be written for it.

**Comment by junegunn** [comment]
Closed via #759.

**Comment by miyl** [comment]
This is 2016 - does `FZF_COMPLETION_TRIGGER` work in fish in 2021?
For me it seems it does not (e.g. `vim /etc/**<tab>` blinks and then nothing), but I don't see it mentioned anywhere that it shouldn't work?

**Comment by bs10x** [comment]
Does this work now? Still the same for me..

> This is 2016 - does `FZF_COMPLETION_TRIGGER` work in fish in 2021? For me it seems it does not (e.g. `vim /etc/**<tab>` blinks and then nothing), but I don't see it mentioned anywhere that it shouldn't work?

**Comment by janderssonse** [comment]
Same here, I guess it should not work in Fish as doc state "https://junegunn.github.io/fzf/shell-integration/#fuzzy-completion-for-bash-and-zsh"

**Comment by bakai-taalaibek** [comment]
I made a function for myself where upon pressing TAB I run a function that checks previous character and runs one of two functions conditionally. If previous character is " ", then I run fzf, otherwise atuin for command completion. 

function act_on_prev_char
    # Get full current commandline before the cursor
    set -l line (commandline --current-buffer --cut-at-cursor)
    
    # Get the last character before the cursor
    set -l last_char (string sub -l 1 -s -1 -- $line)

    if test "$last_char" = " " -o "$last_char" = "/"
        fzc
    else
        _atuin_search
    end
end

maybe it can help somebody
