### ISSUE TITLE
Strange entry when using `fzf-tmux`

### ISSUE THREAD

**Issue by hauleth** [junegunn/fzf#485]
When I call `fzf-tmux` there is strange first line input:

    Ptmux;]4;0;rgb:2b/30/3b\Ptmux;]4;1;rgb:bf/61/6a\Ptmux;]4;2;rgb:a3/be/8c\Ptmux;]4;3;rgb:eb/cb/8b\Ptmux;]4;4;rgb:8f/a1/b3\Ptmux;]4;5;rgb:b4/8e/ad\Ptmux;]4;6;rgb:96/b5/b4\Ptmux;]4;7;rgb:c0/c5/ce\Ptmux;]4;8;rgb:65/73/7e\Ptmux;]4;9;rgb:bf/61/6a\Ptmux;]4;10;rgb:a3/be/8c\Ptmux;]4;11;rgb:eb/cb/8b\Ptmux;]4;12;rgb:8f/a1/b3\Ptmux;]4;13;rgb:b4/8e/ad\Ptmux;]4;14;rgb:96/b5/b4\Ptmux;]4;15;rgb:ef/f1/f5\Ptmux;]4;16;rgb:d0/87/70\Ptmux;]4;17;rgb:ab/79/67\Ptmux;]4;18;rgb:34/3d/46\Ptmux;]4;19;rgb:4f/5b/66\Ptmux;]4;20;rgb:a7/ad/ba\Ptmux;]4;21;rgb:df/e1/e8\Ptmux;]10;rgb:c0/c5/ce\Ptmux;]11;rgb:2b/30/3b\Ptmux;]12;rgb:c0/c5/ce\lib/tasks/recreate.rake

Any idea what can be wrong? I can live with that, but it is kind of irritating.

**Comment by junegunn** [comment]
I never had the problem. Please provide the exact steps to reproduce the issue.

**Comment by hauleth** [comment]
I am not sure what is the issue. My TMux version is `tmux 2.1`.

It seems that this is issue with `fzf-tmux` itself as `ag --nocolor -g "" | fzf-tmux` works correctly.

**Comment by junegunn** [comment]
I also use tmux 2.1 and standalone `fzf-tmux` works nicely. Do you have `FZF_DEFAULT_COMMAND` set? What about `FZF_DEFAULT_COMMAND= fzf-tmux`, or `FZF_DEFAULT_COMMAND="seq 100" fzf-tmux`?

**Comment by hauleth** [comment]
All of them returns that strange line. What can be seen is that only first entry is mangled. What is stranger currently it returns valid entry when select the mangled one, so:

```
env FZF_DEFAULT_COMMAND='seq 1 100' fzf-tmux
<Enter>
1
```

I am using Fish 2.2.0 with TMux 2.1.

**Comment by hauleth** [comment]
It seems that `fzf` is also affected.

**Comment by hauleth** [comment]
Seems that this is problem with base16 thoughtbot/vim-rspec#91.

Closing as non related.

**Comment by hauleth** [comment]
This solves problem: chriskempson/base16-shell#48
