### ISSUE TITLE
Option to clear all default keybindings

### ISSUE THREAD

**Issue by D630** [junegunn/fzf#487]
Say, I want to ignore most available keys in fzf without writing `bind=key:ignore` many times. In this case, it would be nice to have an option, which "flushes" all bindings by preventing fzf's initialization of its default key bindings

**Comment by junegunn** [comment]
I see, but can you tell me why you want to do that? The default bindings are mostly basic readline stuff, and I don't see why you want to clear them.

**Comment by D630** [comment]
An example is [this script](https://github.com/D630/fzf-fs/tree/0.2.3) and this [function](https://github.com/D630/fzf-fs/blob/0.2.3/fzf-fs#L1540) resp.

If you consider it to be needless, no problem :)

**Comment by junegunn** [comment]
Whoa, that is impressive but to be honest looks a bit too radical to my taste. Are you sure fzf is the right tool for what you're trying to achieve here? You're transforming it into something else.

**Comment by D630** [comment]
Hehe, it's just a while loop + many env vars + ls + fzf with different options in different functions. That is, fzf-fs is a simple connection of different fzfs, not a transformation, I guess. Stupid shell scripting! :)

**Comment by junegunn** [comment]
https://github.com/D630/fzf-fs/blob/0.2.3/fzf-fs#L1505-L1525

You're effectively disabling the core function of fzf by remapping every possible key stroke – let's put aside the fact that unicode characters are not covered this way – so what we're left with is a really simple ncurses-based line selector, which is not what fzf, "fuzzy finder", was designed to be. It's a very interesting application, but I'm not sure if we should add more options for the case. I'll think about it.

**Comment by junegunn** [comment]
Closing as wontfix.
