### ISSUE TITLE
--tac without auto scroll

### ISSUE THREAD

**Issue by netei** [junegunn/fzf#491]
I have created my own log viewer using fzf (which is a really great tool for this job).

However, I have one single issue : I'm using `--tac` to have the latest log line at the bottom, and it creates the problem that the logs "automatically scroll down", which is something that is not always wanted.

You can get an idea of what I'm talking about by running 

`while true; do  echo "$RANDOM" ; sleep 0.03; done | fzf --tac`

 which will show that the results are automatically scrolling down.

If we had an action that would be 'toggle-auto-scroll', I could bind that action to a key so that users can stop fzf to scroll. 

What do you think of that idea ? Or do you have any other idea that could help me give a solution to my problem ?

**Comment by junegunn** [comment]
`--reverse` option was the first thing that came to my mind, but looks like you do need a way to "pause" and "resume" to stream, right? Hmm, it's complicated. Technically, when `--tac` is set, fzf does not "auto-scroll" the list, but the new entries from the input stream are prepended to the list. So the cursor position and the screen offset stay the same, but it looks like the input stream is flowing through the screen. We'll have to adjust the cursor position dynamically as the list grows, to give the illusion that the stream is "paused". I'll see if it can be done without too much effort.

**Comment by netei** [comment]
> but looks like you do need a way to "pause" and "resume" to stream, right?

Exactly

>  I'll see if it can be done without too much effort.

Great, thanks for looking into it !

**Comment by junegunn** [comment]
Okay, it wasn't too hard. This is basically it.

https://gist.github.com/junegunn/b047f0b98b794769592e

- Do you think `toggle-flow` is the right name? It is only used when `--tac` is set.
- We need a way to show if the stream is "paused" or not. The above patch simply appends `/F` to the info line if the stream is "flowing", like we append `/S` when `toggle-sort` is used. Any suggestions?

**Comment by edi9999** [comment]
I like the name of `toggle-flow`.

`toggle-*` is already the "standard" for fzf

Other nouns that came into my head : 

* `toggle-follow` like tail --follow (known as -f)
* `toggle-stream` but I don't like it that much and have never seen that

`/F` makes perfect sense since `/S` is the first letter uppercased of `sort` , and `/F` of `follow`

I like `follow` because that's what I'm used to with tail, however `flow` is ok too.

**Comment by justinmk** [comment]
:+1: to `toggle-follow`. Maybe "flow" could be confused with the concept of terminal "reflow".

**Comment by junegunn** [comment]
`toggle-follow` sounds good. Thanks.

**Comment by netei** [comment]
I've tested it and I'm not sure that this option is clear enough right now to be implemented.

The problem is that whenever you start searching, the option will not have any more effect (eg the entries are still flowing).

I think maybe I should be implementing this outside of fzf (by stopping the stream from the source)

**Comment by junegunn** [comment]
> The problem is that whenever you start searching, the option will not have any more effect (eg the entries are still flowing).

You mean until the screen is completely filled? It's not something we can't fix. The updated patch in the gist will make the stream stop in that case as well.

**Comment by netei** [comment]
Your updated diff indeed kind of corrects that problem.

But the issue is that when I start filtering my logs, if I make a typo and no lines of the input match (for example if I type `conusmer` instead of `consumer`), even after correcting the error, I only got one line.

What I really want is a way to say : "I'm not interested in new lines, and I would like to be able to see all logs until the line that I'm currently seeing, and be able to filter down those lines and only those"

I could do that with `bind`, by opening a sub-fzf, like this : 

`loggetter | tee foo | fzf --bind "f1:execute(fzf < foo)"`

This way, whenever I press `F1`, A fzf will open with all logs up to until I've pressed `F1`, and newer logs won't appear anymore.

I really think that I should be implementing this on my side.

If we had to implement it inside fzf, I think it would make more sense (for my use case), to not change indexes manually, but rather have some sort of `queuedLines` where we would push stdin once we have toggled follow to off. If we then toggle follow on, the `lines` and `queuedLines` would be merged into `lines`.

**Comment by junegunn** [comment]
> I only got one line.

Yeah, that's because I removed [offset adjustment](https://gist.github.com/junegunn/b047f0b98b794769592e#file-toggle-flow-patch-L683-L687) to address the issue raised in your previous comment. I can see that it can be very confusing.

> lines and queuedLines would be merged

The patch becomes non-trivial then. I'll just mark this issue "wontfix" and only apply the refactoring made in the patch.

**Comment by netei** [comment]
`loggetter | tee foo | fzf --bind "f1:execute(fzf < foo)"` really works well for my usecase, so thanks anyway for taking the time.

**Comment by junegunn** [comment]
That's clever.

**Comment by pauschuu** [comment]
I am working on the same thing, a small log viewer using the power of fzf and came across that very same problem as the original poster.

Wouldn't `--layout=reverse-list` be another way to implement this? Maybe an easier one, not sure though. It would work with an option that enables following the latest input of the stream.

With this theoretical option enabled it would behave like this:

- In "normal" mode it would always print the newest lines of the stream.
- When the user types a query it would print the matching lines and still following the stream, mean it would start scrolling once there are more lines matching than there is vertical space.
- Once the users scrolls, the current scroll position is kept. Which would be the current default behavior.
