### ISSUE TITLE
Option to remove duplicates

### ISSUE THREAD

**Issue by blueyed** [junegunn/fzf#492]
From https://github.com/junegunn/fzf.vim/issues/33#issuecomment-167243756:

It might be good to have an option for `fzf` to ignore duplicates (without the list required to be sorted)?!

While the issue itself has been fixed (by not having dupes in the input anymore, which was caused by another plugin), I still think that such an option would be useful to have with `fzf` (e.g. for  https://github.com/junegunn/fzf/issues/49 and whenever you cannot influence the input really).

(There's no default tool for that (`sort -u` changes the order, `uniq` needs it to be sorted), but you could use a awk script like this: https://www.gnu.org/software/gawk/manual/html_node/History-Sorting.html.)

The option should be able to either only keep the first or last occurrence of a duplicated entry.

**Comment by junegunn** [comment]
Thanks for the suggestion but I don't think we should as fzf tries to follow the unix philosophy. I know there's no default unix tool for that – which is unfortunate but quite understandable at the same time considering the memory requirement – but it's easy to preprocess the input. The awk example you mentioned should work and this one is in Ruby:

```ruby
require 'set'
set = Set.new
while line = $stdin.gets
  puts line if set.add?(line)
end
```

> whenever you cannot influence the input really

There really aren't many cases where you can't preprocess the input. The code for `CTRL-R` is just about ten lines or so, so it's feasible to have a modified version of it in one's config file.

> The option should be able to either only keep the first or last occurrence of a duplicated entry.

We already have two options to provide, keep first and keep last. And in case of `CTRL-R`, fzf should ignore the numeric index of each entry so we need yet another option (`--filter-dupe-with-nth`?). Builtin processor will never be as flexible as the external ones, and I'd like fzf to focus on something we can't do with pre- and post-processors.

**Comment by netei** [comment]
> Builtin processor will never be as flexible as the external ones, and I'd like fzf to focus on something we can't do with pre- and post-processors.

+1 

I personally use (nauniq)[https://github.com/perlancar/perl-App-nauniq/blob/master/bin/nauniq] for removing duplicates

**Comment by aaronjensen** [comment]
@netei @junegunn is there an example of how to remove duplicates for ctrl-r with fzf? I've seen a couple open issues about it and it'd be a nice thing to have.
