### ISSUE TITLE
Problem with finding Spec files of Rails projects?

### ISSUE THREAD

**Issue by aleks** [junegunn/fzf#493]
I don't know why, but fzf takes several seconds to find files in my Rails project's ```spec/``` folder.

Everything else (models, controllers etc.) works flawlessly. As far as i can see it, this is not related to my project size, since i have the same problem with small apps or fresh Rails installations.

Is there some kind of path or file configuration i'm missing? :sweat_smile:

**Comment by junegunn** [comment]
Please provide more information about your environment (OS, shell, relevant config) and the steps to reproduce the issue. fzf doesn't know or care what `spec` is, so it shouldn't behave differently.

**Comment by aleks** [comment]
Thanks for your quick response!

I looked further into this and found out, that if i rename ```spec``` to ```_spec``` (so it is above all other directories, based on the a-z sorting), fzf will find it faster. So it seems, like this is just an issue, because fzf will search form top to bottom through the files in my current directory.

My setup: Mac OS X (on an SSD), iTerm2 (same problem with standard Terminal) and zsh. I don't run any other "file based" services, that could interfere with fzf.

**Comment by junegunn** [comment]
```sh
find . -path '*/\.*' -prune -o -type f -print -o -type l -print 2> /dev/null | sed s/^..//
```

This is the command fzf internally use when no input is fed, check if it works smoothly. Also something like `fzf . | fzf`.

**Comment by aleks** [comment]
I fiddled around with the two commands (added directory excludes and so on), but no differnece. I guess this is a problem with my machine.

I'll close the issue, thanks! :)

**Comment by netei** [comment]
Maybe you have a directory that has lots of files in them, and that would explain why it takes a long time for `find` to find those files ? 

Some kind of /log directory or anything else ? Does the problem appear if you rename `spec` to something like `spuc` ?

**Comment by hendricius** [comment]
Having the same issue, I guess this is no bug, just a configuration issue.

**Comment by junegunn** [comment]
You probable have `$FZF_DEFAULT_COMMAND` set to a command that respects .gitignore.
