### ISSUE TITLE
_fzf_complete doesn't terminate in zsh

### ISSUE THREAD

**Issue by allait** [junegunn/fzf#494]
When trying to invoke any of the completions that are using `_fzf_complete` (e.g. `unset **<TAB>`) the shell locks up. zsh 5.2 on OS X, both zsh and fzf installed with homebrew.

At first I thought it was caused by my local config, but I can trigger the same behaviour by running:
```shell
zsh --no-rcs
source /usr/local/opt/fzf/shell/completion.zsh
unset **<TAB>
```
Rolling back the changes to zsh version of `_fzf_complete` made in https://github.com/junegunn/fzf/commit/82067463b8263692147d80b6fc909f1d98693d88 (i.e. bringing back `_fzf_feed_fifo`) seems to fix the issue, so I think it might have something to do with the way zsh is passing stdin to command substitution, making `$(cat ...)` block while it's waiting for input. 

I've tried changing `_fzf_complete` to accept the process substitution temporary file directly as an argument, instead of expecting it to be redirected to stdin, which makes it possible to pass it to the subshell:

```diff
@@ -80,15 +80,16 @@
 }

 _fzf_complete() {
-  local fzf_opts lbuf fzf matches post
+  local fifo fzf_opts lbuf fzf matches post
   fzf_opts=$1
   lbuf=$2
+  fifo=$3
   post="${funcstack[2]}_post"
   type $post > /dev/null 2>&1 || post=cat

   [ ${FZF_TMUX:-1} -eq 1 ] && fzf="fzf-tmux -d ${FZF_TMUX_HEIGHT:-40%}" || fzf="fzf"

-  matches=$(cat | ${=fzf} ${=FZF_COMPLETION_OPTS} ${=fzf_opts} -q "${(Q)prefix}" | $post | tr '\n' ' ')
+  matches=$(cat $3 | ${=fzf} ${=FZF_COMPLETION_OPTS} ${=fzf_opts} -q "${(Q)prefix}" | $post | tr '\n' ' ')
   if [ -n "$matches" ]; then
     LBUFFER="$lbuf$matches"
   fi
@@ -117,7 +118,7 @@
 }

 _fzf_complete_unset() {
-  _fzf_complete '-m' "$@" < <(
+  _fzf_complete '-m' "$@" <(
     declare -xp | sed 's/=.*//' | sed 's/.* //'
   )
 }
```

This seems to fix the issue, but breaks compatibility with any existing custom completion functions.

**Comment by junegunn** [comment]
Thank you very much for looking into this. This is my mistake, I should have checked if it worked when it's not using tmux pane (`FZF_TMUX=0`). Like you said, we're going to have to restore the use of fifo, and though I like your suggestion, but I'd rather not break backward compatibility.

**Comment by junegunn** [comment]
Pushed the fix and an accompanying test case. Thanks!
