### ISSUE TITLE
terminal's alternate screen

### ISSUE THREAD

**Issue by D630** [junegunn/fzf#495]
Hi,

How can I use fzf on my terminal's "alternate screen"?

**Comment by junegunn** [comment]
Sorry, I never use it and have no idea what should be done

**Comment by D630** [comment]
Seems to be a curses termcap initialization thing. Less has its -X option to use it, I guess:

```sh
# on real screen
$ clear ; ls -1 /
$ tput smcup

# on alternate screen
$ clear ; ls -1 --color=always / | less -RX
$ tput rmcup
```
