### ISSUE TITLE
[neovim] Vim Wiki examples broken in latest NeoVim version

### ISSUE THREAD

**Issue by adambiggs** [junegunn/fzf#498]
I'm using the [select buffer](https://github.com/junegunn/fzf/wiki/Examples-(vim)#select-buffer) and [narrow ag results](https://github.com/junegunn/fzf/wiki/Examples-(vim)#narrow-ag-results-within-vim) code snippets from the wiki. These worked great in nvim up till about a week ago, when I noticed the fzf terminal buffer would open without displaying anything.

Some observations:
- Terminal split opens at the correct size based on the amount of lines that *should* be displayed.
- About 75% of the time, an extra key press will fix the issue. After this point, fzf works normally until the next time it's opened.
- The other 25% of the time, nvim stays unresponsive after repeated key presses, eventually responding after a 5-10s delay.

I'm currently using NeoVim v0.1.3-128-gf887037. But I rebuild from source every morning.

Happy to provide more debugging info as needed.

**Comment by junegunn** [comment]
Sounds like a regression of Neovim, unless they made some breaking changes. Do you have the same issue when running `:Buffers` and `:Ag` commands from [fzf.vim project](https://github.com/junegunn/fzf.vim)?

**Comment by justinmk** [comment]
I just tried the "select buffer" example on `NVIM v0.1.3-130-g91254bd` (latest), with 413 buffers in `:ls`, and it works fine. @adambiggs Would you be willing to bisect to find the exact commit of Neovim that causes the issue?

**Comment by adambiggs** [comment]
Strange... Installing fzf.vim seems to have fixed the issue, even for the previously broken wiki examples. Not sure what caused the original issue, but I'm back in business now.

Thanks for the fzf.vim link @junegunn, I didn't even know about that project!
