### ISSUE TITLE
Assign :FZF to <leader>p

### ISSUE THREAD

**Issue by rahmatawaludin** [junegunn/fzf#502]
I could assign to ` <leader>p`, but sometimes after selecting file and press `Enter` or `ESC`, weird error show up like this:

![screen shot 2016-02-21 at 10 45 22 pm](https://cloud.githubusercontent.com/assets/1274849/13203579/26a4df56-d8ee-11e5-9ed5-f1009888ef01.png)

````
Error running /Users/rahmatawaludin/.fzf/bin/fzf --expect=ctrl-v,ctrl-x,ctrl-m,ctrl+t > /var/folders/40/some-random-string
````

*if I press `Enter` and this error show up, the file won't open.

What should I do to fix this? Thanks.

P.S: I'm using vim 7.4 and my `<leader>` key is space

**Comment by junegunn** [comment]
I can't investigate the problem if you just describe the condition as "sometimes".
Can you provide more information about your configuration and the steps to reproduce the problem?

**Comment by rahmatawaludin** [comment]
You can close this issue for now. I'll make another issue when I'm able to write steps to reproduce the problem. For now, this just come randomly. For your reference, here is my vimrc https://gist.github.com/rahmatawaludin/313474de5532b68ba25d

**Comment by junegunn** [comment]
Consider adding `set hidden` to your config and see if it helps.

As a side note, You can remove this line as it's automatically done in `plug#end()`.

https://gist.github.com/rahmatawaludin/313474de5532b68ba25d#file-vimrc-L11

Removing it will make your vim start faster.

**Comment by bcp1989** [comment]
@rahmatawaludin  I'm hitting this problem as well since recent update.
It only happens pretty often on random files, don't have repro yet.
Have you figured out a way to workaround it?

Thanks
