### ISSUE TITLE
fish shell support

### ISSUE THREAD

**Issue by jethrokuan** [junegunn/fzf#505]
Hi,

I've gotten shell support for fish, without the need for a temp directory. My code is here:
https://github.com/jethrokuan/fzf

If someone could look through, I could merge this upstream here.

**Comment by bucaran** [comment]
@junegunn

**Comment by junegunn** [comment]
Similar to #486?

**Comment by jethrokuan** [comment]
@junegunn actually, yes. The PR should work. I also have #477 implemented, but it should go in line with zsh or bash.

**Comment by jethrokuan** [comment]
#486 doesn't seem to support multiselect for Ctrl-t.

**Comment by bucaran** [comment]
I missed #486. @hauleth would you mind having a look at @jethrokuan PR too? It doesn't matter which one gets merged, but it would be sweet if fish users had a more positive experience with this tool out of the box and without having to resort to ["plugins"](https://github.com/gretel/pkg-fzf), etc.

**Comment by jethrokuan** [comment]
@hauleth I was mistaken. No need to read into an array. #486 is good to go.

**Comment by jethrokuan** [comment]
I think we can close this for now, sorry for the noise. missed #486 as well when I did this

**Comment by junegunn** [comment]
No problem, thank you for your contribution. I was waiting for the answers to my questions in the PR.
