### ISSUE TITLE
How to prevent fullscreen in vim?

### ISSUE THREAD

**Issue by rahmatawaludin** [junegunn/fzf#507]
I've read through this https://github.com/junegunn/fzf/wiki/Configuring-FZF-command-(vim) and https://github.com/junegunn/fzf/wiki/Examples-(vim). My goal was to show fzf in bottom of my vim screen (not fullscreen). Here is my setup:

````
let g:fzf_height = 40
nmap <silent> <leader>p :FZF<CR>
````

fzf always come in fullscreen. Is there any step I miss?

**Comment by junegunn** [comment]
You have to be on tmux, or use neovim for that. fzf is an ncurses program and basically runs in fullscreen.
