### ISSUE TITLE
issues with --bind 

### ISSUE THREAD

**Issue by DanielFGray** [junegunn/fzf#512]
Was unsure how to title this.. but here's the issue I have:

    apt-cache search '' | fzf --bind "Ctrl-X:execute: apt-cache show \$(awk '{print $1}' <<< {}) | less"

works as expected. And so does

    apt-cache search '' | fzf | awk '{print $1}'

However, combining the two:

    apt-cache search '' | fzf --bind "Ctrl-X:execute: apt-cache show \$(awk '{print $1}' <<< {}) | less" | awk '{print $1}'

breaks the output, and prints the first column from `apt-cache show` rather than the selection from fzf. I'm honestly not sure if this is an issue with the shell or fzf, but is there a fix for this? I can do for example

    fzf --multi --bind "ctrl-x:execute:apt-cache show \$(awk '{print \$1}' <<< {}) | less" --bind "return:execute: sudo apt install \$(awk '{print \$1}' <<< {})" < <(apt-cache search '')

but this then breaks reading input to `apt install` when asked `Do you want to continue? [Y/n]`.

**Comment by junegunn** [comment]
Hmm, this is an interesting problem with `execute` that I have overlooked.

```sh
seq 10 | fzf --bind 'x:execute:echo {}' | awk '{print "got:" $1}'
```

Pressing <kbd>x</kbd><kbd>x</kbd><kbd>x</kbd><kbd>x</kbd><kbd>up</kbd><kbd>enter</kbd> will give:

```
got:1
got:1
got:1
got:1
got:2
```

Because the output of each `execute` invocation is also passed to awk. If you only want the selection from fzf, you'll need to filter the output yourself. I can imagine a few ways to do it, but since you're already using awk, `END` block will do the trick.

```sh
seq 10 | fzf --bind 'x:execute:echo {}' | awk 'END {print "got:" $1}'
```

Does this answer your question?

**Comment by DanielFGray** [comment]
>Does this answer your question?

To be honest, not really :disappointed:

I have a script that's basically a fancier version of `apt-cache search '' | fzf --multi | awk '{print $1}' | xargs -I% sudo apt install %` [1] and I would really love to add the `--bind..apt-cache show..` functionality to it, but as far as I can tell it seems like I can't..

Unless you can think of a way to have `awk` distinguish the output from `fzf --multi` rather than `less`..

[1] full script is [here](https://gist.github.com/DanielFGray/c23ecf3c2e2bfd59abea/), if you like. It just tries to work with Arch and the AUR and colorize the package list..

**Comment by junegunn** [comment]
I don't think there's something fzf can do in that case. You'll have to find out a way not to use stdout. I didn't read your script, but maybe you can use stderr instead?

```sh
seq 10 | fzf --bind 'x:execute:echo {} 1>&2' | awk '{print "got:" $1}'
```

**Comment by netei** [comment]
@DanielFGray You could do the following : 

seq 10 | fzf --bind 'x:execute:echo {} | tee /tmp/file | less' ; lastline=$(tail -n 1 </tmp/file) && echo "$lastline"

**Comment by netei** [comment]
The real problem is that you can't both have interactive commands inside the --bind, and redirect the output of fzf (because the interactive commands are then also redirected to the output of fzf).

You could do the following 

    seq 10 | fzf --bind 'x:execute@echo {} | less@,enter:execute@echo {} > /tmp/file && killall fzf@' ; lastline=$(tail -n 1 </tmp/file) && echo "$lastline"

The killall part is a big hack, I don't know exactly how I could close fzf in that case.

An other option is to use tmux, and to run the interactive commands in an other pane

**Comment by junegunn** [comment]
I think we can use alternate screen here:

```
seq 10 | fzf --bind 'x:execute:tput smcup; echo {}; sleep 0.1; tput rmcup' | awk '{print "got:" $1}'
```

(I wasn't familiar with the concept, it was suggested by @D630 in #495)

**Comment by DanielFGray** [comment]
`apt-cache search '' | sort | fzf  --bind "Ctrl-X:execute: tput smcup; apt-cache show \$(awk '{print $1}' <<< {}) | less; tput rmcup"  --multi | awk '{print $1}'`

doesn't seem to help much, unless I'm doing that wrong.. the other approach I had was 

`fzf --multi --bind "ctrl-x:execute:apt-cache show \$(awk '{print \$1}' <<< {}) | less" --bind "return:execute: sudo apt-get install \$(awk '{print \$1}' <<< {})" < <(apt-cache search '')`

but then apt-get aborts as soon as it prompts `Do you want to continue? [Y/n]`.. I could force the install with `apt-get -y install` but that's not ideal at all

I suppose I could fiddle with the `--expect` switch in fzf, but I was hoping to avoid re-building the list each time.. though I guess at this point it might be the only solution

**Comment by D630** [comment]
@DanielFGray Can you also try the following one?

```sh
--bind='Ctrl-X:execute[p={} ; less < <(apt-cache show "${p%% *}")]'
--bind='return:execute[p={} ; </dev/tty sudo apt-get install "${p%% *}" >/dev/tty]'
```

**Comment by DanielFGray** [comment]
What is this sorcery???

**Comment by D630** [comment]
The sorcery is `</dev/tty` :)

By the way, you can put your bash code in a function atttributed as an export:

```sh
__apt ()
case $1 in
c1)
        apt-cache show "${2%% *}" \
        | less -R;
;;
c2)
         </dev/tty \
         sudo apt-get install "${2%% *}" \
         >/dev/tty;
esac

export -f __apt
```

And then:
```sh
apt-cache search '' \
| {
    fzf \
        --bind='ctrl-x:execute(__apt c1 {} )'  \
        --bind='enter:execute(__apt c2 {} )';
}
```
