### ISSUE TITLE
Center view when match not on screen

### ISSUE THREAD

**Issue by netei** [junegunn/fzf#513]
Whenever you search for a string and it is not visible, the view scrolls to the right.

The problem is that the string is at the right of the screen, so you don't see what is after that string in your entries.

For example : 
    
    yes $({ printf '=%.0s' {1..400} ;  echo "foobar" ; printf '<%.0s' {1..400}; }) |head -n 20 | FZF_DEFAULT_OPTS="" fzf

And then search for "foobar". 

![fzf_right_search](https://cloud.githubusercontent.com/assets/13066384/13430307/ccd53f42-dfc4-11e5-8878-6c5660511e84.PNG)

I propose to automatically center the screen when the part of the matched string is not in the base screen.

What do you think ?

**Comment by junegunn** [comment]
Yeah, it's something I have also wanted from time to time. Center alignment feels a bit too radical, I would rather implement something like `&sidescrolloff` in Vim.

```diff
diff --git a/src/constants.go b/src/constants.go
index e859f3b..1e31673 100644
--- a/src/constants.go
+++ b/src/constants.go
@@ -36,6 +36,8 @@ const (
 
 	// History
 	defaultHistoryMax int = 1000
+
+	sideScrollOff int32 = 10
 )
 
 // fzf events
diff --git a/src/terminal.go b/src/terminal.go
index 3c6f47c..af41725 100644
--- a/src/terminal.go
+++ b/src/terminal.go
@@ -565,6 +565,7 @@ func (t *Terminal) printHighlighted(item *Item, bold bool, col1 int, col2 int, c
 
 	// Overflow
 	text := make([]rune, len(item.text))
+	maxe = util.Min32(maxe+sideScrollOff, int32(len(text)))
 	copy(text, item.text)
 	offsets := item.colorOffsets(col2, bold, current)
 	maxWidth := C.MaxX() - 3 - t.marginInt[1] - t.marginInt[3]
```

**Comment by junegunn** [comment]
Like in Vim, setting `sideScrollOff` to a very large value will display the text on the center of the screen, which means it makes sense to make it configurable.

**Comment by junegunn** [comment]
Added `--hscroll-off` option, try it and let me know what you think!

**Comment by netei** [comment]
Works well ! Thanks !

**Comment by gertcuykens** [comment]
Could it be this is broken in master at the moment?

```
yes $({ printf '=%.0s' {1..400} ;  echo "foobar" ; printf '<%.0s' {1..400}; }) |head -n 20 | FZF_DEFAULT_OPTS="" fzf --hscroll-off 10
```

```
yes $({ printf '=%.0s' {1..400} ;  echo "foobar" ; printf '<%.0s' {1..400}; }) |head -n 20 | FZF_DEFAULT_OPTS="" fzf --hscroll-off 80
```

![image](https://user-images.githubusercontent.com/863731/55069536-965b9400-5084-11e9-83d4-b653fbc027fb.png)

**Comment by gertcuykens** [comment]
turns out the theirs was a new line after foobar example above

`yes $({ printf '.%.0s' {1..400}; printf 'foobar'; printf '+%.0s' {1..400}; }) | head -n 20 | FZF_DEFAULT_OPTS="" fzf --hscroll-off=800` works
