### ISSUE TITLE
Combined text when looking at history in tmux

### ISSUE THREAD

**Issue by landaire** [junegunn/fzf#518]
I have a strange issue with combined history text: https://imgur.com/a/XP0Cx

In the screenshots you can see there's some nonsensical commands, and pressing the up arrow clears that line... but this is a very strange issue that keeps happening. Is there a way to fix this?

**Comment by junegunn** [comment]
Invalid $TERM. See https://github.com/junegunn/fzf#rendering-issues
Also https://github.com/tmux/tmux/blob/master/FAQ#L3-L13

**Comment by landaire** [comment]
Whelp, guess I need to read better. Thanks, I think that fixed it. I had it set to `xterm-256color`.
