### ISSUE TITLE
ctrl+R with keybindings don't work in fish 2.2

### ISSUE THREAD

**Issue by danielb2** [junegunn/fzf#519]
```
blah<C-R> "-stdin-" [readonly] 8050L, 221380C"-stdin-" [readonly] 8050L, 221380C
```

typing blah followed by ctrl+r results in the string as in the example above.

``` bash
$ fish --version
fish, version 2.2.0-665-g58d56f9
```

**Comment by junegunn** [comment]
Works for me on OS X and Linux. I don't use fish so my fish config is clean. Maybe you have some config that conflicts with it? How about the other key bindings, ctrl-t and alt-c, do they work?

**Comment by danielb2** [comment]
Yeah, looks like tat must be it. I deleted a bunch of my stuff and it seems to work. Thanks. I'll try to figure out the conflicts and reopen if it's an issue on this end

**Comment by danielb2** [comment]
OK, FYI, it has issues with my PAGER setting...

`set -gx PAGER "col -b | vim -R -c 'runtime! macros/less.vim | set ft=man | set nolist' -"`

That's unfortunate because having the PAGER set elsewhere like this is very useful for me (man pages etc)

Is fzf really using the PAGER setting here to do something special?
