### ISSUE TITLE
[Question] Can you tell me the test files?

### ISSUE THREAD

**Issue by Shougo** [junegunn/fzf#52]
https://raw.githubusercontent.com/junegunn/i/master/fzf-commandt-ctrlp-unite.gif

I read the page and found unite.vim cache performance was too bad.
But I have improved file_rec/async performance in unite.vim.

I want to re-test for the files.

**Comment by ldong** [comment]
@Shougo Whats the latest update? Is unite.vim using fzf for best performance or stays with Ag? Thank you in advance.

**Comment by junegunn** [comment]
@ldong I don't think you see the point. You're comparing apples and oranges.

**Comment by ldong** [comment]
@junegunn Okay, I should really be comparing fzf with percol.
I was confused, and thought fzf was another alternative implementation of searching utility. Now, I see `fzf` is an interface for command line interactions, pick/open files, not a search engine like ag or find.

Was @Shougo just looking for optimizing `unite.vim`'s caching algorithm from `fzf` from this thread?
