### ISSUE TITLE
Restore window layout when using Neovim's terminal mode

### ISSUE THREAD

**Issue by blueyed** [junegunn/fzf#520]
I've noticed that using FZF commands in NeoVim will mess with the window layout after being closed, especially if there's a location list / quickfix window involved (at the bottom).

Given a window layout of:

    +-------------------------------------------+
    |                       |                   |
    |                       |                   |
    |                       |                   |
    |                       |                   |
    +------------------------                   +
    |                       |                   |
    |                       |                   |
    |                       |                   |
    |                       |                   |
    |-----------------------|                   |
    |                       |                   |
    | location list         |                   |
    +-------------------------------------------+

After opening FZF:

    +-------------------------------------------+
    |                       |                   |
    |                       |                   |
    |                       |                   |
    +------------------------                   +
    |                       |                   |
    |                       |                   |
    |-----------------------|                   |
    | location list         |                   |
    +-------------------------------------------+
    |                                           |
    | FZF                                       |
    |                                           |
    +-------------------------------------------+

After closing FZF:

    +-------------------------------------------+
    |                       |                   |
    |                       |                   |
    |                       |                   |
    +------------------------                   +
    |                       |                   |
    |                       |                   |
    |-----------------------|                   |
    | location list         |                   |
    |                       |                   |
    |                       |                   |
    |                       |                   |
    |                       |                   |
    +-------------------------------------------+

I've tried this with just `nvim -u vimrc.minimal`.

It gets worse on a second invocation, probably because of the `winfixheight` setting of quickfix/location list windows.

It would be nice, if fzf would restore the window layout from before it was invoked.

**Comment by netei** [comment]
Very similar to https://github.com/junegunn/fzf.vim/issues/42

**Comment by justinmk** [comment]
There is an issue I'm Neovim repo for augmenting window API to support this. Though I guess mkview could be abused somehow...

**Comment by junegunn** [comment]
Yeah, this is an issue with vim plugins that create temporary splits.

- `botright 10new`
- `botright new`
- `close`

Unfortunately I can't think of a simple solution to this problem. Suggestions are welcome.

**Comment by justinmk** [comment]
Is there a reason `(tabpagenr()-1).'tabedit|term ...` is not the default? That would preserve layout. It also wasn't obvious how to switch to this mode using `g:fzf_layout`.

IMO https://github.com/neovim/neovim/issues/3933 is the general solution to this problem.

**Comment by blueyed** [comment]
@justinmk 
What are you using for `g:fzf_layout` exactly?  I've found `let g:fzf_layout = {}` in your vimrc?! (makes it really not obvious then)
It seems to be a good workaround for now - also providing more space.. ;)

**Comment by justinmk** [comment]
@blueyed `let g:fzf_layout = {}` makes fzf use a tab instead of a split (had to dig around the code; not documented). However, it opens in the next tab slot instead of the previous, so it doesn't return to the original tabpage on cancel.

**Comment by blueyed** [comment]
> However, it opens in the next tab slot instead of the previous, so it doesn't return to the original tabpage on cancel.

It does so in my setup though.. :) (closing tabs to the left (https://github.com/blueyed/dotfiles/commit/1a1bfbce025ad49bda3e9ceaed96139e3975f644))
That makes the default better in that case, and I consider the default behavior in NeoVim inconvenient instead.

**Comment by junegunn** [comment]
Note that `g:fzf_layout` is only used by the commands in fzf.vim project.

https://github.com/junegunn/fzf.vim/blob/master/plugin/fzf.vim#L27-L31

This map is eventually passed to `fzf#run()` function, and it is supposed to contain down/up/left/right or window attribute. `window` attribute, which only works in neovim unlike the others, holds the ex command to create the terminal window. So what @justinmk suggested above can be done like follows:

```vim
let g:fzf_layout = { 'window': 'execute (tabpagenr()-1)."tabnew"' }
```
(There was a bug though, see 3073ca3.)

**Comment by junegunn** [comment]
Related: https://github.com/junegunn/fzf/commit/f704b94603f386c7b6458ba358816f52bbad2b36

**Comment by CrashyBang** [comment]
Should the above solution load the searched for and selected file in the split you executed it from?

**Comment by blueyed** [comment]
@CrashyBang 
You are probably hitting #559 there (`wincmd p` messes things up).
Would be great if you could try #559 and provide feedback there.

**Comment by edi9999** [comment]
As a workaround, we could tell users to use tmux instead of terminal mode even inside neovim. I would like to test that, but I don't think that there is an option to force tmux mode inside neovim. Is they one ?

**Comment by azag0** [comment]
@edi9999 I would just note that the terminal mode of neovim and freedom from tmux is one of the main reasons for me using neovim instead of vim.

**Comment by justinmk** [comment]
This commit to Vim (from today) may fix the window layout issue:

https://github.com/vim/vim/commit/991dea3ab185fb35e577ab0bdfd443cd4b43ccc6

Can someone apply it to Neovim and see if it resolves this fzf issue?

**Comment by edi9999** [comment]
You can now prefer to use tmux with the following option : 

`let g:fzf_prefer_tmux = 1`

**Comment by justinmk** [comment]
I recently discovered the VimL function `winrestcmd()` which gives an ex command that can be executed to restore window layout for the current tabpage. 

```vim
let save_win_layout = winrestcmd()
" ... show fzf split window; user selects item
execute save_win_layout  " restore window layout
```

There are some limitations (e.g. it won't work if new splits are opened) but I think this would solve the common case. `winrestcmd()` works well for a ["zoom" mapping](https://github.com/justinmk/config/blob/master/.config/nvim/init.vim#L1013-L1035) I recently hacked up.

**Comment by justinmk** [comment]
Derp, I just noticed that https://github.com/junegunn/fzf/commit/f025602841384fb10cc80d37492ec44c2b872860 uses `winrestcmd()`.

**Comment by junegunn** [comment]
@justinmk 

> Derp, I just noticed that f025602 uses winrestcmd().

It's a shame that we didn't know about it when the great ctrlp has been using it for like 5 years :)

Incidentally, I also have a zoom mapping. It uses `:tab split`, like Goyo.

```vim
" Zoom
function! s:zoom()
  if winnr('$') > 1
    tab split
  elseif len(filter(map(range(tabpagenr('$')), 'tabpagebuflist(v:val + 1)'),
                  \ 'index(v:val, '.bufnr('').') >= 0')) > 1
    tabclose
  endif
endfunction
nnoremap <silent> <leader>z :call <sid>zoom()<cr>
```
