### ISSUE TITLE
fzf_key_bindings.fish isn't checking for existence of fzf

### ISSUE THREAD

**Issue by danielb2** [junegunn/fzf#521]
It would be nice if the fish scripts to load the bindings check for the existence of fzf, and if it doesn't exist, not change them.  right now if fzf isn't installed, I get errors if I try to do ctrl+R for instance.

I would say this should be behavior with bash and zsh as well

either `fzf_key_bindings.fish` should check or the insert into `fish_user_key_bindings.fish`. I'm thinking the former is the cleaner way.

**Comment by danielb2** [comment]
So in the case of `fzf_key_bindings.fish`

A simple:
```

 set FZF (which fzf)
 if test -z "$FZF"
   return
 end
```

would do. For example

**Comment by junegunn** [comment]
I find the error message `fzf executable not found` in that case is very clear. Is it because you want to use the same configuration files on a different machine where you can't install fzf for some reason?

**Comment by danielb2** [comment]
that's it

**Comment by danielb2** [comment]
```
set FZF (which fzf)
if test -n "$FZF"
    fzf_key_bindings
end
```

i just did this instead for myself
