### ISSUE TITLE
2s initial delay

### ISSUE THREAD

**Issue by felixlaumon** [junegunn/fzf#522]
- Category
    - [x] fzf binary
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [x] zsh
    - [ ] fish

Hi, I'm getting a 2-second initial delay when invoking `fzf`. However, I won't see this delay if I do `ag -g "" | fzf`. Any idea why this would happen? It seems very strange to me because I have `export FZF_DEFAULT_COMMAND='ag -g ""'` set.

My current hacky workaround in shell is to alias `fzf` to `ag -g "" | fzf`. But this doesn't propagate to `vim` / `nvim`

Let me know if there is any profiling I should do. Thanks!

**Comment by junegunn** [comment]
- Do you see the delay when you unset `FZF_DEFAULT_COMMAND`?
- Do you still see the delay with `export FZF_DEFAULT_COMMAND='echo hello'`?
- What is the output of `echo $SHELL`?
- What happens when you do `$SHELL -c 'ag -g ""'`?

**Comment by felixlaumon** [comment]
For some reason, the delay seems to have gone away in my terminal today. I didn't do any restart or update at all.

I am using `zsh` (`echo $SHELL` -> `/usr/bin/zsh`) and I can see the same delay when using `$SHELL -c 'ag -g ""'`. It's probably because I have a bunch of plugins to load in from `zgen`.

I did have `set shell=/bin/sh` but neovim seems to call out `zsh` anyway. My current workaround is `let $SHELL='/bin/sh'`. I am using `fzf.vim` BTW.

Anyway it doesn't seem to be a `fzf` issue, so please feel free to close this out. Thanks for the help!

**Comment by junegunn** [comment]
Yeah, fzf internally uses `$SHELL` since #481. See https://github.com/junegunn/fzf/issues/481#issuecomment-180738655.

Since `$SHELL -c COMMAND` does not load .bashrc or .zshrc, a noticeable delay is usually not expected. You might want to figure out what's causing the delay first.

**Comment by felixlaumon** [comment]
> $SHELL -c COMMAND does not load .bashrc or .zshrc

That's good to know. Thanks for the help again!
