### ISSUE TITLE
symbols

### ISSUE THREAD

**Issue by D1mon** [junegunn/fzf#523]
- Category
    - [ x] fzf binary
    - [ ] Key bindings
    - [ ] Completion
    - [x ] Vim
    - [ ] Neovim
    - [ x] Etc.
- OS
    - [x ] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ x] bash
    - [x ] zsh
    - [ ] fish

instead of Russian letters appear strange symbols ( [http://imgur.com/tWBquyr] )
![fzf-rus](https://cloud.githubusercontent.com/assets/3872485/13730778/635a7186-e96a-11e5-9b79-fa38ae47545c.png)

**Comment by junegunn** [comment]
fzf supports UTF-8 characters, so this works:

```sh
echo "АБВГДЕЁЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯ" | fzf
```

<img width="442" alt="screen shot 2016-03-14 at 1 11 48 am" src="https://cloud.githubusercontent.com/assets/700826/13729836/d8ea44a0-e981-11e5-87a5-ad99a0f604a2.png">

Are you running the latest version of fzf?

**Comment by D1mon** [comment]
yes. 0.11.4
echo "АБВГДЕЁЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯ" | fzf
result: [http://imgur.com/0dAflOp](http://imgur.com/0dAflOp)

**Comment by junegunn** [comment]
1. Did you download the binary using install script, or did you build it yourself?
2. What is the value of `$LANG`?

**Comment by D1mon** [comment]
1. Using git (recommended)
2. ru_RU.UTF-8

**Comment by junegunn** [comment]
Try this:

```sh
sudo locale-gen ru_RU.UTF-8
sudo update-locale LANG=ru_RU.UTF-8
```

**Comment by D1mon** [comment]
did not help

**Comment by junegunn** [comment]
Output of `uname -sm`?
32-bit binaries can have the problem as they are currently not statically linked to libncursesw. But I can fix that.

**Comment by D1mon** [comment]
> Linux i686

**Comment by junegunn** [comment]
Okay that confirms problem. I rebuilt the binary and uploaded it. Delete the current binary and rerun the install script and see if it helps.

```sh
rm ~/.fzf/bin/fzf-0.11.4*
~/.fzf/install
```

**Comment by D1mon** [comment]
Works!!! Thanks!
