### ISSUE TITLE
FZF for window switching and selection

### ISSUE THREAD

**Issue by mkpaul** [junegunn/fzf#525]
- Category
    - [x ] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [x ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x ] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ x] bash
    - [ ] zsh
    - [ ] fish

Is it possible to use fzf to select one of the open windows? Instead of using ALT-TAB to switch between windows, it will be done via a fuzzy search of window titles of all open windows.

**Comment by junegunn** [comment]
I don't use Linux desktop environment, so there's not much I can help with, but if you have a command that returns the list of open windows, and a command for selecting one, it should be possible.

**Comment by george-b** [comment]
[Rofi](https://davedavenport.github.io/rofi/) does this.

**Comment by D630** [comment]
Have a look at this [list](https://github.com/D630/doc/wiki/Apps%3A-X11-tools). See also this [dir](https://github.com/D630/dotfiles/tree/master/xorg/local/bin) and pick up some line, if you like to.

**Comment by junegunn** [comment]
@george-b @D630 Cool, thanks for the info.

**Comment by mkpaul** [comment]
Thanks for the inputs. @george-b @junegunn @D630 
I knew about Rofi and wmctrl, but i don't have root permission to install it in the system. So started looking for other options.

**Comment by chrisamow** [comment]
This might not do mkpaul any good, but might save someone else some time...
(apt-get xdotool)
```
#two spaces after the d backslash (avoiding nested single quote hell)
alias winact='xdotool windowactivate $(wmctrl -l | fzf | cut -d\  -f1 )'
```
  
!<https://chrisamow.github.io/images/screen_fzf_winact.gif>
