### ISSUE TITLE
FZF_DEFAULT_OPTS not sourced

### ISSUE THREAD

**Issue by esn89** [junegunn/fzf#527]
- Category
    - [ x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ x] zsh
    - [ ] fish

I really want to pass in the flag of +x, such that fzf only matches words, and not the fuzzy aspect of it.  So when I type, for example, the word "source", I should only see that word.

However, I tried putting the line of export FZF_DEFAULT_OPTS="+x --inline-info" into my .zshrc and even the .fzf.zsh and it did not work.  Any ideas as to what I'm doign wrong?

**Comment by junegunn** [comment]
What you're looking for is `-e` (or `--exact`) and not `+x`, right?

**Comment by esn89** [comment]
Aah, you're right.  My bad.

When I pass it in, do I have to put the +x as well to turn off extended AND add -e?
Or just the -e?

**Comment by junegunn** [comment]
It's your choice. Extended-search mode is pretty simple and useful.
https://github.com/junegunn/fzf#search-syntax
