### ISSUE TITLE
Fzf-tmux is quite useful script, could it be generalized?

### ISSUE THREAD

**Issue by mtglsk** [junegunn/fzf#528]
- Category
    - [ ] fzf binary
    - [x] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

Replacing for example all fzf with selecta and commenting last line, makes it work without a hitch with selecta (well exit code doesn't get catched when commenting out the last line, not that well versed in bash scripting to figure it out, though). This script is quite useful and could be generalized to user defined command.

**Comment by junegunn** [comment]
Yeah I guess. But I don't think we need to provide a generalized version of it in this repository. It's an open source script after all, one can freely take the idea and build something out of it.
