### ISSUE TITLE
Ctrl + R in zsh with iTerm2 with tmux opens in a new pane

### ISSUE THREAD

**Issue by loeschg** [junegunn/fzf#530]
- Category
    - [x] fzf binary
    - [x] fzf-tmux script ???
    - [x] Key bindings
- OS
    - [x] Mac OS X
- Shell
    - [x] zsh

When using fzf in iTerm2 with tmux, the ctrl-r keybinding brings up fzf in a new pane on the last opened tab. 

Not sure if it's relevant or not, but I have the following iTerm2 configuration:
"Send text at start: `tmux -CC attach -t base || tmux -CC new -s base`"

I'll admit that my tmux knowledge is fairly limited, so it's very possible I'm abusing something :)

**Comment by junegunn** [comment]
I'm pretty sure there's something wrong with your configuration. CTRL-R binding uses `fzf-tmux` to split the pane and it's just `tmux split-window`, and I can't reproduce the problem in any way.
