### ISSUE TITLE
Calling :FZF in neovim uses left-most window on first run

### ISSUE THREAD

**Issue by zhimsel** [junegunn/fzf#532]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [x] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [x] zsh
    - [ ] fish

Continued from junegunn/fzf.vim/issues/105

**Comment by junegunn** [comment]
Please provide the exact steps to reproduce the problem. I can't reproduce with the following steps.

```sh
# Start nvim with a minimal config
nvim -u <(cat << EOF
call plug#begin('/tmp/plugged')
Plug 'junegunn/fzf'
call plug#end()
EOF) +PlugInstall

# When installation is complete :wincmd l | FZF
```

**Comment by zhimsel** [comment]
I cannot reproduce with that minimal config either. (FYI, nvim complains that `plug` is not valid, which it's not since it hasn't been installed).

I'll try to programmatically narrow down the source, and write out the exact steps.

**Comment by junegunn** [comment]
> FYI, nvim complains that plug is not valid

I assumed that you have plug.vim in your autoload directory (that's what most people do).

Anyway looks like you'll have to find the culprit in your config.

**Comment by zhimsel** [comment]
> I assumed that you have plug.vim in your autoload directory (that's what most people do).

Ah, no, I call it manually since I manage it externally via git submodules (soon to be subtrees).

https://github.com/zhimsel/dotfiles/tree/master/vim

**Comment by zhimsel** [comment]
Okay, it only seems to happen when there are multiple splits open of the same buffer. So that's another step to narrow down. So, what I have so far:

* Happens in neovim only. vim does not produce.
* Does not matter if `fzf.vim` is sourced or not (i.e. happens with both `:Lines` and `:FZF`)
* FZF-relevant config: 
```vim
let g:fzf_layout = { 'window': 'new' }
let g:fzf_action = {
  \ 'ctrl-t': 'tab split',
  \ 'ctrl-x': 'split',
  \ 'ctrl-v': 'vsplit' }
```

Steps to reproduce:
1. Open neovim, and create three splits for the same buffer
2. Call FZF, and close it (either select a file, or hit escape)
3. Focus then moves to the leftmost split for the buffer you were just in
4. Change the leftmost split to a different buffer
5. Repeat above, and it goes to the middle split (ignoring the other buffer)

See the video below:
![animation](https://s3.amazonaws.com/zhimsel-public/fzf_issue_532.gif)

**Comment by junegunn** [comment]
Is it reproducible with the minimal config above?

**Comment by zhimsel** [comment]
No, it's not. Which means it's likely a config/plugin conflict. I'm working on narrow it down.

**Comment by zhimsel** [comment]
Narrowed it down to kopischke/vim-stay... Thanks for your help! :)
