### ISSUE TITLE
bash control keys: you use vim... what about emacs?

### ISSUE THREAD

**Issue by sb-lock** [junegunn/fzf#533]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [x] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

**Comment by sb-lock** [comment]
the bash keybindings were influenced by emacs keybindings. 

I can tell you use vim, that's fine, but it's pretty frustrating for a long time bash and emacs user that installing fzf (as with cygwin) changes LONGstanding standard keybindings in a way that is not at all compatible.

has any thought been given to trying to be more emacs compatible rather than just breaking everything?

**Comment by junegunn** [comment]
I use emacs key bindings on bash and I don't see what you mean by breaking everything. Please be more specific.

**Comment by junegunn** [comment]
And those 3 key bindings are optional.The install script asks you if you want them or not.
