### ISSUE TITLE
Fuzzy completion for bash with custom Commands

### ISSUE THREAD

**Issue by oscarmorrison** [junegunn/fzf#536]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [X] Key bindings
    - [X] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [X] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [X] bash
    - [ ] zsh
    - [ ] fish

I can very easily run 
`$vim ** [tab] `
and fzf fuzzy search works as expected.

I would like to however set this up with my default editor (sublime)
currently doing:
`$sublime ** [tab] `
does nothing

**Comment by junegunn** [comment]
Bash requires you to set up completion function for each command. And the list of commands that we apply fuzzy completion is currently [hard-coded](https://github.com/junegunn/fzf/blob/0.11.4/shell/completion.bash#L252-L259) :confused: 

But you can manually set up completion for extra commands. Add the following after `source ~/.fzf.bash` line in your .bashrc:

```sh
complete -o bashdefault -o default -F _fzf_path_completion sublime
```

**Comment by oscarmorrison** [comment]
Thanks so much @junegunn for the excellent and timely response
