### ISSUE TITLE
Updating fzf causes sourcing of .fzf.bash on zsh

### ISSUE THREAD

**Issue by mdsn** [junegunn/fzf#537]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [x] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

My .zshrc file sources a virtualenvwrapper.sh file to set up some environment variables. When updating FZF (from vim, using vim-plug), the following line is added to my virtualenvwrapper.sh file:

`[ -f ~/.fzf.bash ] && source ~/.fzf.bash`

This causes the following errors to appear when opening a new shell.
```
/home/mariano/.vim/plugged/fzf/shell/key-bindings.bash:[:65: unknown condition: -gt
/home/mariano/.vim/plugged/fzf/shell/key-bindings.bash:70: command not found: bind
/home/mariano/.vim/plugged/fzf/shell/key-bindings.bash:71: command not found: bind
/home/mariano/.vim/plugged/fzf/shell/key-bindings.bash:77: command not found: bind
/home/mariano/.vim/plugged/fzf/shell/key-bindings.bash:83: command not found: bind
/home/mariano/.vim/plugged/fzf/shell/key-bindings.bash:86: command not found: bind
```
I temporarily solve this after upgrades by deleting the .fzf.bash file.

Thanks.

**Comment by junegunn** [comment]
You can tell the install script (the one used in *do* block of `Plug` statement for fzf) not to touch your configuration files.

```
usage: ./install [OPTIONS]

    --help               Show this message
    --bin                Download fzf binary only; Do not generate ~/.fzf.{bash,zsh}
    --all                Download fzf binary and update configuration files
                         to enable key bindings and fuzzy completion
    --[no-]key-bindings  Enable/disable key bindings (CTRL-T, CTRL-R, ALT-C)
    --[no-]completion    Enable/disable fuzzy completion (bash & zsh)
    --[no-]update-rc     Whether or not to update shell configuration files

    --32                 Download 32-bit binary
    --64                 Download 64-bit binary
```

> the following line is added to my virtualenvwrapper.sh file

Is this true? The script [adds the line to `.zshrc` or `.bashrc`](https://github.com/junegunn/fzf/blob/master/install#L369-L370). I don't know how it ended up in there. Can you look into it?

**Comment by mdsn** [comment]
This was my mistake. I forgot my .bashrc is a link to the other file.
Using the relevant option to install solves the issue.

Thank you
