### ISSUE TITLE
[zsh][question] How to override completion for commands that contain spaces, e.g. hg up

### ISSUE THREAD

**Issue by balta2ar** [junegunn/fzf#538]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [x] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

Hello! Completion for `hg up` in Ubuntu 12.04 is broken: branches are not listed. I decided to override it with fzf completion as follows:

``` zsh
elif [ "$tokens" = 'hg up' -a ${LBUFFER[-1]} = ' ' ]; then
  [ ${FZF_TMUX:-1} -eq 1 ] && fzf="fzf-tmux -d ${FZF_TMUX_HEIGHT:-40%}" || fzf="fzf"
  matches=$({ hg branches -a & hg tags } | ${=fzf} --no-sort ${=FZF_COMPLETION_OPTS} | cut -f1 -d' ')
  if [ -n "$matches" ]; then
    LBUFFER="$LBUFFER$matches"
  fi
  zle redisplay
```

That's just an ugly copy-paste from `kill` implementation in `~/.fzf/shell/completion.zsh`. But then I found new way to write custom completions (and using `**<Tab>`) here: https://github.com/junegunn/fzf/wiki/Examples-%28completion%29.

However, I only want to override `hg up` subcommand. Here is the code which I tried and which does not work (completion is not triggered):
``` zsh
_fzf_complete_hg_up() {
  _fzf_complete "--no-sort" "$@" < <(
    { hg branches -a & hg tags }
  )
}

_fzf_complete_hg_up_post() {
  cut -f1 -d' '
}
```

How do I override commands that contain spaces within that new framework?
Thank you!

**Comment by junegunn** [comment]
`$@` contains the prefix, you can examine its content to conditionally run `_fzf_complete` or fall back to `zle expand-or-complete` (or `zle ${fzf_default_completion:-expand-or-complete}`). Does this answer your question?

**Comment by balta2ar** [comment]
Yes, thank you! For those who might encounter this issue later, here is what I ended up with:
``` zsh
# Branch/tag completion for hg up
_fzf_complete_hg() {
  ARGS="$@"
  if [[ $ARGS == 'hg merge'* ]] || [[ $ARGS == 'hg up'* ]]; then
    _fzf_complete "--no-sort" "$@" < <(
      { hg branches -a & hg tags }
    )
  else
    eval "zle ${fzf_default_completion:-expand-or-complete}"
  fi
}

_fzf_complete_hg_post() {
  cut -f1 -d' '
}
```

**Comment by junegunn** [comment]
Guess we don't actually need the `eval`, right?

**Comment by balta2ar** [comment]
Looks as if we don't (I tried without it and it worked), but I took it from fzf source code and left as is. So blame is on you :stuck_out_tongue_winking_eye:

**Comment by balta2ar** [comment]
By the way, do you think it's a good idea to put an example like this into the wiki? I read the wiki and I still had questions how to do that.

**Comment by junegunn** [comment]
Yeah, it's something I noticed while looking at the source code and I wanted to get your confirmation. Putting it on wiki, maybe, but it doesn't work the same on bash, no zle. But we could at least mention about `$@`.
