### ISSUE TITLE
Override <ENTER> in fzf_action()

### ISSUE THREAD

**Issue by frederic-potvin** [junegunn/fzf#539]
Is it possible to use fzf_action() to override the <ENTER> key in VIM?

**Comment by junegunn** [comment]
I'm not sure if I follow. Please be more specific with examples.

**Comment by frederic-potvin** [comment]
I would like to open files in a new tab when using FZF commands in VIM instead of opening in a new buffer.

This is what the CTRL+T key does. I know I can use fzf#run() with the 'sink' options but I'd like to over ride the default behavior in all uses.

**Comment by WChargin** [comment]
Why not add `nnoremap <C-P> :call fzf#run({ 'sink': 'tabe' })` in your vimrc? (Replace `<C-P>` with whatever your current hotkey is.) What do you mean by override in "all uses"?

(Or do you always invoke fzf via `:FZF<CR>`?)

**Comment by frederic-potvin** [comment]
@WChargin I did and it work. And I would like to reproduce that behavior when using junegunn/fzf.vim plugin, for all commands.

If I can use fzf_action, to override the <ENTER> key, no added config would be required.

I'm just asking if it's currently possible. I can still use CTRL+T, which is fine.

**Comment by junegunn** [comment]
You can try something like `let g:fzf_action = { 'enter': 'tabedit' }`.
Though I (and many other Vim users) don't recommend using tabs for everything.

http://stackoverflow.com/questions/26708822/why-do-vim-experts-prefer-buffers-over-tabs

**Comment by frederic-potvin** [comment]
Thank you very much. This is exactly what I was looking for.

And thanks for sharing the advice on buffers. I've read the whole thing and will use them instead of tabs. I was missing the <pre>:set hidden</pre>
