### ISSUE TITLE
Unable to open files directly from fzf

### ISSUE THREAD

**Issue by alistaircolling** [junegunn/fzf#542]
When I press 'Enter' on a file in the list it does not open but the name and path is printed in the terminal. I'm running fzf by typing `fzf` and hitting enter. Ideally I'd like to open text files in neovim.

- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

**Comment by mjwestcott** [comment]
fzf is designed to be a 'Unix filter' meaning it reads from stdin and prints to stdout. If no stdin pipe is provided, it lists files from the current directory as a useful default.

To specialise the behaviour, you can write a short shell script or alias. For example:

`alias v='nvim $(fzf)'`

See the 'Usage' section of the README and the wiki for many more interesting examples.

**Comment by junegunn** [comment]
@mjwestcott Thanks :)

**Comment by alistaircolling** [comment]
Thanks @mjwestcott @junegunn Apologies for clogging up the issues, will check the 'Usage' section.

**Comment by fakefarm** [comment]
Hello, this solved my issue too. Thank you!

_I didn't realize that bash/zshell executes double quotes immediatly but not single quoutes do not. TIL!_

```bash
alias fs='subl $(fzf)' # desired behavior
alias fsx="subl $(fzf)" # not desired behavior (executes in .bash_rc)
```

**Comment by mehdico** [comment]
In mac you can do this:
```
alias f='open "$(fzf)"'
```
to open file by os default for selected file type.
