### ISSUE TITLE
Buffer list hangs every time

### ISSUE THREAD

**Issue by firedev** [junegunn/fzf#544]
- Category
    - [x] Buffers
    - [x] Neovim
- OS
    - [x] Mac OS X
- Shell
    - [x] zsh

I am using Neovim on MacOS and have the latest FZF managed by `vim-plug` as described in the wiki along with the code for `<leader><cr>` to accent buffers list. Every time I press `<leader><cr>` the new split opens and I have to go there and press `Ctrl-C` to break something or the list of recent files won't appear.

Please advise how I can provide more information. Thank you.

**Comment by junegunn** [comment]
Do you think it's related to https://github.com/junegunn/fzf.vim/issues/84?

**Comment by firedev** [comment]
Indeed, setting `let g:airline#extensions#branch#enabled = 0` fixed it. Guess I'll close this issue in favor of the one you've linked to.

**Comment by junegunn** [comment]
Yeah, it's probably a bug of neovim and not something I can fix.
