### ISSUE TITLE
add a command-line option to specify the input file

### ISSUE THREAD

**Issue by step-** [junegunn/fzf#545]
- Category
    - [x] fzf binary
- OS
    - [x] Linux
- Shell
    - [x] gtkdialog
    - [x] bash

HI, I'm scripting fzf from a [gtkdialog](https://github.com/01micko/gtkdialog) program. Unfortunately, gtkdialog's parser trips over standard shell input redirection characters, so I need an alternate way to specify the input file. Would you please add a command-line option to specify the input file? I know I could use a `cat` pipe as a work-around, but I don't want to fork an extra process just for that, because fzf is executed repeatedly in a tight loop.

Put it another way:
Syntax that breaks gtkdialog's parser (its fault but I can't control it): `fzf -f $term < input-file` 
request for enhancement: `fzf -f $term --input-file input-file`

Thank you for considering my request.

**Comment by junegunn** [comment]
```sh
> echo foo > /tmp/foo
> time for _ in $(seq 1000); do fzf -f foo < /tmp/foo; done > /dev/null

real    0m5.540s
user    0m1.387s
sys     0m3.179s

> time for _ in $(seq 1000); do cat /tmp/foo | fzf -f foo; done > /dev/null

real    0m5.711s
user    0m2.206s
sys     0m4.450s
```

So there is some overhead, but it's so small that I don't think you need to worry about it. I'm pretty sure you won't notice the difference of 0.1ms.

**Comment by step-** [comment]
OK, thanks.
