### ISSUE TITLE
In exact match mode `'` doesn't "unquote" the term

### ISSUE THREAD

**Issue by gene-pavlovsky** [junegunn/fzf#547]
- Category
    - [X] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [X] Linux (fzf 0.12.0 on Gentoo)
    - [ ] Mac OS X
    - [X] Windows (fzf 0.11.4 on Cygwin)
    - [ ] Etc.
- Shell
    - [X] bash
    - [ ] zsh
    - [ ] fish

The fzf manpage says: *If you don't prefer fuzzy matching and do not wish to "quote" (prefixing with ') every word, start fzf with -e or --exact option. Note that  when  --exact  is
set, '-prefix "unquotes" the term.*

In reality, in exact match mode `'` doesn't "unquote" the term. E.g. I cat bash's README file into `fzf -e`, searching for `Unix` I can find one line that mentions *Unix*, searching for `Unx` - no matches (as expected), searching for `'Unx` - still no matches (I expected `'` to make the match fuzzy). I want to have exact matching by default, but maybe sometimes fuzzy would be useful, because of this bug I have to either use `-x` option or live without fuzzy matching.

**Comment by gene-pavlovsky** [comment]
Actually, with `-e` option none of the special characters `^`, `$`, `|` seem to work. Everything seems to be matched literally.

**Comment by junegunn** [comment]
fzf was started as a Ruby script but it was completely rewritten in Go in early 2015. Since the go version does not compile on Cywgin, we have no choice but to use the Ruby version, but I no longer update it. It does not have the new features (I just made sure that it simply ignore the new flags) and some options are not compatible with the latest Go version. So we should leave the Ruby version out of the discussion.

Anyway, there's indeed a bug in the latest version, which I noticed just a few days ago :) The caching mechanism of partial result is broken in some cases. I'll try to fix it in a couple days and let you know of the progress.

**Comment by gene-pavlovsky** [comment]
Oh, I see. Didn't notice that. It looks like cygwin package keeps updating the shell scripts but not the ruby script (whose version is much older than the package version).
What is missing for compiling the `Go` version on Cygwin, the `Go` compiler is not available there?
Btw, how do I build the source on a Linux system? I want to help update the [Gentoo fzf ebuild](https://github.com/andjscott/overlays/issues/2), apparently it also uses the old ruby version.

**Comment by gene-pavlovsky** [comment]
I managed to build it, after I removed these lines from `Makefile`:

```
ifneq ($(shell uname -m),x86_64)
$(error "Build on $(UNAME_M) is not supported, yet.")
endif
```

My `uname -m` returns i686 (btw `UNAME_M` is not set in your Makefile). Why is this `ifneq` there?

**Comment by junegunn** [comment]
The Makefile is for building both 32-bit and 64-bit binaries on 64-bit machine. I use it to build official binaries, but you don't have to use it. The easiest way to build fzf on your system is to set up Go development environment (i.e. `$GOPATH`) and `go get github.com/junegunn/fzf/src/fzf` and it will put the built binary on `$GOPATH/bin`.

**Comment by junegunn** [comment]
> It looks like cygwin package keeps updating the shell scripts but not the ruby script (whose version is much older than the package version)

Yeah, and labeling it as 0.12.0 is horribly misleading :(

**Comment by gene-pavlovsky** [comment]
Thanks for build instructions.

> Yeah, and labeling it as 0.12.0 is horribly misleading :(

I agree. It could be avoided if the new version was renamed to `fzf2` or `gofzf` (for example), or the old version was renamed to `fzf-old`.

**Comment by junegunn** [comment]
> Does go get download the precompiled binaries that you made?

No it builds the binary on your system. My binaries are downloaded via install script for those who don't want to setup Go dev env. So basically that's all you need. 

> Why do you need the ifneq ($(shell uname -m),x86_64) conditional in your Makefile?

I remember there was some cross compilation issues, i.e. building 64-bit binary from 32-bit env didn't work. Maybe I did something wrong, but I didn't look further as I build binaries on 64-bit Darwin.

Anyway, the initial issue you reported (invalid caching) is now fixed and will be included in 0.12.1.

**Comment by gene-pavlovsky** [comment]
Thanks. All right, cheers.

**Comment by gene-pavlovsky** [comment]
JuneGunn, by the way, does the `-e` option imply `-x` automatically, or not? In the ruby version it does, but I'm not sure about the current version. If it does as well, perhaps the manpage should mention that.

**Comment by gene-pavlovsky** [comment]
You said you don't plan to support the Ruby version, but would you be willing to accept this patch? It makes the `-e` option usable, which is the only way Cygwin users can get this at the moment.

**Comment by gene-pavlovsky** [comment]
I was also thinking it's quite wrong the Cygwin package advertises fzf version as 0.11.4, and most of all includes the manpage which doesn't quite match the `fzf --help` output. I suppose I should complain to Cygwin's mailing list, but on the other hand just keeping the legacy ruby script in the repository like this invites that kind of mistake on the part of package builders. Maybe create a subdir `legacy`, put the ruby `fzf` there, along with the most appropriate manpage from an old commit, and mention about this whole Ruby->Go history in the README / install instructions?

**Comment by junegunn** [comment]
The Go version has diverged from its predecessor quite a lot. `-e` being orthogonal with `-x` is one thing, `-x` being the default is another. You can see the history [here](https://github.com/junegunn/fzf/blob/master/CHANGELOG.md).

The version number of the Ruby script is 0.8.9 but the latest version of fzf is 0.12.1. So basically they are different versions with different promises. I don't think it's appropriate that we transplant a subset of the accumulated changes to the legacy version while still calling it 0.8.9.

> it's quite wrong the Cygwin package advertises fzf version as 0.11.4

I agree. And I suppose the package is a collection of shell extensions and the vim plugin? So far, I have tried to make them work with the legacy Ruby version, just by making it not complaining about the new option flags, but I'm not sure if I can keep doing it.

> just keeping the legacy ruby script in the repository like this invites that kind of mistake on the part of package builders

I've been thinking about removing it from this repo. The thing is, I don't use it anymore, and I don't think I can pay enough attention to it. So what I suggest is to that you or the maintainer of the cygwin package (@me-and according to #410) create a separate repository that is for the package, Ruby version with custom patches (such as #558) and the correct man page for the version, etc.

But the best thing that can happen is that we finally build Go version on Windows (#147).
I don't use Windows, but have [heard that it's improving](https://channel9.msdn.com/Blogs/Seth-Juarez/Windows-Subsystem-for-Linux-Architectural-Overview), free lunch coming?

**Comment by gene-pavlovsky** [comment]
I think your points are completely reasonable, I'll get in touch with @me-and.
I've read about WSL just recently, it's quite suprising move from Microsoft (but I keep think - where's the catch? - since TANSTAAFL).
To be honest, I miss the days I was exclusively on a Linux desktop (Gentoo), recently I've made a decision to switch back in the midterm future, at most next time I buy a new laptop (which I do every ~4-5 years).

**Comment by me-and** [comment]
Hello! Cygwin maintainer here! @gene-pavlovsky pointed me at this thread over in me-and/Cygwin-fzf#2.

So far, I've just been naively packaging up latest fzf release for Cygwin every so often; there've been changes that look like they're relevant to Cygwin, in things like the Tmux script, and I've not been thinking too hard about things like whether the version numbers are actually appropriate.

Now I'm actually thinking about what's appropriate, I think the sensible thing to do is to officially fork fzf into a fully supported Ruby-based project and an exclusively Go-based project, with separate releases and presumably different names, rather than having the Ruby code languishing unmaintained here. Does that seem sensible to you?

If so, I've started with the very basics of ripping out the Go code to form a Ruby-based project over at [me-and/fzf:ruby](https://github.com/me-and/fzf/tree/ruby), and I suspect the sensible next step is for the Ruby code to be officially removed from this repository, possibly with a pointer in the README or similar to the Ruby fork.

**Comment by junegunn** [comment]
@me-and Sounds good. I'll remove Ruby script from this repo and update the install script to point to the fork on unsupported platforms (or simply on Cygwin). I think I'll have time for that early next week. By the way, I think you can still use many test cases from `test/test_go.rb`, but how you're going to test the Ruby version is up to you.

**Comment by gene-pavlovsky** [comment]
@me-and I've submitted my PR wrt this issue as well as manpage corrections to your repo.
