### ISSUE TITLE
Override $SHELL when running fzf

### ISSUE THREAD

**Issue by dalizard** [junegunn/fzf#552]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [x] Vim
    - [x] Neovim
- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
- Shell
    - [ ] bash
    - [ ] zsh
    - [x] fish

I am using neovim (using vim however would not make a difference) and fish shell. I have the following configuration:
```
~ $ echo $SHELL
/usr/local/bin/fish
~ $ cat ~/.config/nvim/init.vim | grep shell
set shell=/usr/local/bin/fish
~ $ fzf --version
0.12.0
```

The problem is when running fzf within neovim/vim (or the shell) there is a startup penalty because of the shell:
```
~ $ time /bin/bash -c "uname"
Darwin
        0.00 real         0.00 user         0.00 sys
~ $ time /usr/local/bin/fish -c "uname"
Darwin
        0.06 real         0.03 user         0.02 sys
~ $ 
```

This is not a huge difference, but I would to be able to set a different shell for fzf for performance reasons. When using fzf.vim this small startup penalty does make a bit of a difference. I found [this commit](https://github.com/junegunn/fzf/commit/e95d82748fc8fe5a05d93b30388ba37adb7dbac8), which make fzf use the default shell. Would it be possible to change the used shell just for fzf?

**Comment by junegunn** [comment]
`$FZF_DEFAULT_COMMAND` is only used in `:Files` command where we don't explicitly specify its source. Please let me know if the following patch helps in your case.

```diff
diff --git a/autoload/fzf/vim.vim b/autoload/fzf/vim.vim
index 99c78ec..3f8b730 100644
--- a/autoload/fzf/vim.vim
+++ b/autoload/fzf/vim.vim
@@ -188,6 +188,9 @@ function! fzf#vim#files(dir, ...)
   else
     let args.options .= ' --prompt '.shellescape(pathshorten(getcwd())).'/'
   endif
+  if exists('$FZF_DEFAULT_COMMAND')
+    let args.source = $FZF_DEFAULT_COMMAND
+  endif
 
   return s:fzf(fzf#vim#wrap(args), a:000)
 endfunction
```

**Comment by junegunn** [comment]
Tested with a bogus $SHELL (`sleep 1; sh "$@"`) and it helps.
