### ISSUE TITLE
Auto completion doesn't work

### ISSUE THREAD

**Issue by mrleolink** [junegunn/fzf#553]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [x] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

Auto completion doesn't work for both vi and cd.

`cd **<tab>`, then this shows up:

<img width="1058" alt="screen shot 2016-04-25 at 12 14 39 am" src="https://cloud.githubusercontent.com/assets/991367/14768345/a64213d8-0a7a-11e6-8586-e86d9198d102.png">

And if I quit that screen by ESC, this message shows up:

`cd **(eval):1: _fzf_compgen_dir: function definition file not found`

I'm using newest version from github, I just pulled fzf repo (fzf executable ... 0.12.0)
Reinstall via `install` will `--all` doesn't help.

**Comment by junegunn** [comment]
I don't use zsh, so I don't know if I can help. Google points me to this page you might want to take a look:
http://stackoverflow.com/questions/10585002/zsh-complains-about-rvm-rvm-cleanse-variables-function-definition-file-not-fo

**Comment by mrleolink** [comment]
wow it works, thank you!!!
