### ISSUE TITLE
Building on i686

### ISSUE THREAD

**Issue by gene-pavlovsky** [junegunn/fzf#555]
- Category
    - [X] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [X] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [X] bash
    - [ ] zsh
    - [ ] fish

I'd like to see the Makefile improved to support i686. On my Gentoo system, I get an error:

```
# emerge app-misc/fzf
...
make -j2 install
Makefile:11: *** "Build on  is not supported, yet.".  Stop.
 * ERROR: app-misc/fzf-0.12.0-r2::andjscott failed (compile phase):
 *   emake failed
```

I'm not sure about my machine type. It's a remote VPS (by RapidVPS), running on OpenVZ, as far as I know.
`uname -m` returns `i686`, but from `/proc/cpuinfo`: `model name : Intel(R) Xeon(R) CPU E5530 @ 2.40GHz`

I googled `Xeon E5530` and it's a 64-bit CPU. But maybe that is IA64, not x86-64? Either way, when I build the source manually, both executables have identical description and look like 32-bit:

```
fzf-linux_386:   ELF 32-bit LSB executable, Intel 80386, ...
fzf-linux_amd64: ELF 32-bit LSB executable, Intel 80386, ...
```

Both of them run fine. Btw in my case each file is a whopping 3.1 Mb, `strip`-ping them reduces size to 2.1 Mb - still big, but better. Does it make sense to `strip` in the Makefile?

**Comment by gene-pavlovsky** [comment]
Thanks to @andjscott, the [fzf ebuild for Gentoo Linux](https://github.com/andjscott/overlays/issues/2) now builds the Go version, works on both 32-bit and 64-bit machine.

**Comment by junegunn** [comment]
As I mentioned earlier, the Makefile is for building official binaries, 32-bit and 64-bit with ncurses statically linked. It's not necessary if you simply want to build a binary for your system.

> executables have identical description and look like 32-bit

You can install 32-bit OS on 64-bit machine, but not the other way around. Cross compilation in Go is done by setting `GOARCH` env variable. If you look at the Makefile, you'll notice `GOARCH=386` in `fzf/$(BINARY32)` target, but no `GOARCH` is set for `fzf/$(BINARY64)`, which is so because we *know* that we're on a 64-bit OS (`ifneq ($(shell uname -m),x86_64) ...`), and that's why you ended up with two 32-bit binaries. Add `GOARCH=amd64` to 64-bit binary target and see if you can properly build both binaries. If it works, we can remove the precondition. But if it doesn't we can still consider slightly modifying the Makefile so that it builds 32-binary only a 32-bit OS.

Go binaries are known to be big. This simple program makes a 2MB binary.

```go
package main

import (
	"fmt"
)

func main() {
	fmt.Println("Hello, playground")
}
```

We can cut down the size of the binary with `-ldflags '-s -w'`. I just haven't paid attention to the size as a few megabytes doesn't matter in most modern system. I'll consider that in the future releases. I remember there were some issues with stripping Go binary in the past, but it's probably fixed by now.

**Comment by andjscott** [comment]
How about changing the Makefile to build bin/fzf for the native architecture by default and making the cross compiling target a separate task?

**Comment by junegunn** [comment]
I don't want to change it too much. Looks like all you need is `make install`, so how about this?

```patch
diff --git a/src/Makefile b/src/Makefile
index 5d5779b..e15c446 100644
--- a/src/Makefile
+++ b/src/Makefile
@@ -7,11 +7,6 @@ else ifeq ($(UNAME_S),Linux)
 endif
 endif
 
-UNAME_M := $(shell uname -m)
-ifneq ($(UNAME_M),x86_64)
-$(error "Build on $(UNAME_M) is not supported, yet.")
-endif
-
 SOURCES     := $(wildcard *.go */*.go)
 ROOTDIR     := $(shell dirname $(realpath $(lastword $(MAKEFILE_LIST))))
 BINDIR      := $(shell dirname $(ROOTDIR))/bin
@@ -27,6 +22,15 @@ RELEASE64   := fzf-$(VERSION)-$(GOOS)_amd64
 RELEASEARM7 := fzf-$(VERSION)-$(GOOS)_arm7
 export GOPATH
 
+UNAME_M := $(shell uname -m)
+ifeq ($(UNAME_M),x86_64)
+	BINARY := $(BINARY64)
+else ifeq ($(UNAME_M),i686)
+	BINARY := $(BINARY32)
+else
+	$(error "Build on $(UNAME_M) is not supported, yet.")
+endif
+
 all: release
 
 release: test build
@@ -55,7 +59,7 @@ test: deps
 install: $(BINDIR)/fzf
 
 uninstall:
-	rm -f $(BINDIR)/fzf $(BINDIR)/$(BINARY64)
+	rm -f $(BINDIR)/fzf $(BINDIR)/$(BINARY)
 
 clean:
 	cd fzf && rm -f fzf-*
@@ -66,9 +70,9 @@ fzf/$(BINARY32): deps
 fzf/$(BINARY64): deps
 	cd fzf && go build -a -tags "$(TAGS)" -o $(BINARY64)
 
-$(BINDIR)/fzf: fzf/$(BINARY64) | $(BINDIR)
-	cp -f fzf/$(BINARY64) $(BINDIR)
-	cd $(BINDIR) && ln -sf $(BINARY64) fzf
+$(BINDIR)/fzf: fzf/$(BINARY) | $(BINDIR)
+	cp -f fzf/$(BINARY) $(BINDIR)
+	cd $(BINDIR) && ln -sf $(BINARY) fzf
 
 $(BINDIR):
 	mkdir -p $@
```

**Comment by gene-pavlovsky** [comment]
Building only one version, appropriate for ARCH, sounds reasonable to me.
I didn't succeed building with GOARCH=amd64.
Try 1:

```
cd fzf && GOARCH=amd64 go build -a -ldflags '-w' -tags "" -o fzf-linux_amd64
# github.com/junegunn/fzf/src/algo
../../gopath/src/github.com/junegunn/fzf/src/algo/algo.go:264: undefined: util.TrimRight
go build github.com/junegunn/fzf/src/curses: no buildable Go source files in /root/fzf/gopath/src/github.com/junegunn/fzf/src/curses
```

Try 2 (`CGO_ENABLED=1`, I have no idea what I'm doing):

```
cd fzf && GOARCH=amd64 CGO_ENABLED=1 go build -a -ldflags '-w' -tags "" -o fzf-linux_amd64
# runtime/cgo
cc1: error: CPU you selected does not support x86-64 instruction set
```

I think you're right and my VPS hosting provider runs 32-bit OS on a system with 64-bit-capable CPUs. So I give up on trying to build a 64-bit executable :)

The `ldflags '-w'` option result in 2.3 Mb binary vs 3.1 Mb without ldflags. Either version is 2.1 Mb after `strip`. Is compiling static binaries are common feature of Go compiler? It hardly makes sense if building a binary for your own system, is it trivial to add an option to `go` so it will compile a dynamically linked binary?

**Comment by junegunn** [comment]
Stripping Go binary seems to have issues;
- https://github.com/golang/go/issues/11622#issuecomment-119263915
- https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=717172

Not sure if it's fixed or not, but I don't think it's worth the trouble.

The official linux binaries I make via `make linux` are "partially static", only ncurses is statically linked. Static linking of ncurses is enabled only when you explicitly pass `TAGS=static` (see Makefile and curses.go). So what you built on your system with `make` or `make install` is a dynamic binary. And no, it's not possible to make Go binary smaller than that as far as I know.

I'm going to apply the patch I mentioned above and be done with this for now. I'll consider applying `-ldflags "-w"` for the next releases.

**Comment by gene-pavlovsky** [comment]
All right JG, thanks for your work, and sorry to take so much of your time! Kamsahamida!
