### ISSUE TITLE
FZF in Neovim Laggy in Some Cases

### ISSUE THREAD

**Issue by sbdchd** [junegunn/fzf#556]
- Category
   - [x] Neovim
- OS
    - [x] Mac OS X
- Shell
    - [x] bash

```bash
export FZF_DEFAULT_COMMAND='ag --hidden -U --ignore .git -g ""'
```

In Neovim, when I run `:FZF` in a directory with a git repo, with the default command as shown above, the terminal buffer freezes until I switch to a different tmux window and switch back.

The issue also appears to be present without Neovim being in tmux.

After some testing, it seems that 095f31b is the cause of the issue.

**Comment by junegunn** [comment]
I don't have the problem. Please check if the problem is reproducible with the following configuration

```vim
nvim -u <(cat << "EOF"
  call plug#begin('~/.vim/plugged')
  Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': 'yes \| ./install' }
  call plug#end()
  let $FZF_DEFAULT_COMMAND = 'ag --hidden -U --ignore .git -g ""'
EOF)
```

**Comment by sbdchd** [comment]
I am not sure why, but after removing vim-airline, the problem seems to be resolved.

Thanks for the help.

**Comment by junegunn** [comment]
Related: https://github.com/junegunn/fzf.vim/issues/84

I believe it's a bug of neovim.

**Comment by justinmk** [comment]
See https://github.com/junegunn/fzf.vim/issues/84#issuecomment-182404906. This bug probably is in Vim, but it doesn't happen there because tmux is used instead.

**Comment by junegunn** [comment]
@justinmk Thanks for chiming in. But no, it's not reproducible on original Vim. The bang versions of the commands such as `:FZF!` do not use tmux and they are still fine.

You can use this config to reproduce the problem:

```vim
set nocompatible
set laststatus=2

if !filereadable('/tmp/plug.vim')
  silent !curl -fLo /tmp/plug.vim
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
endif

autocmd VimEnter *
  \  if !empty(filter(copy(g:plugs), '!isdirectory(v:val.dir)'))
  \|   PlugInstall
  \| endif

source /tmp/plug.vim
call plug#begin('/tmp/plugged')
Plug 'junegunn/fzf', { 'do': './install --bin' }
Plug 'bling/vim-airline'
Plug 'tpope/vim-fugitive'
call plug#end()
```

**Comment by justinmk** [comment]
@junegunn Thanks for the repro! I just tried that vimrc with `NVIM v0.1.5-24-gef205c3` and didn't find much lag using `:FZF!` (with 57562 results) compared to Vim 7.4.52. (ubuntu 32-bit, ssh to VM from mintty, tmux 1.8)

> The bang versions of the commands such as :FZF! do not use tmux and they are still fine.

I didn't mean to imply that tmux is the differentiating factor--rather a blocking `system()` call (which [prevents statusline updates](https://github.com/junegunn/fzf.vim/issues/84#issuecomment-182417756)).

In Neovim, `:FZF!` still runs a `:term` buffer, so again it's non-blocking and we haven't made an apples-to-apples comparison vs. Vim.

**Comment by junegunn** [comment]
Hey @justinmk, did you run it on a git repo? It only happens when the current directory is inside a git repo.

**Comment by junegunn** [comment]
Ugh, only when you're at the root of a repo.

**Comment by justinmk** [comment]
At the root of a non-trivial git repo it definitely takes a few seconds for FZF to show up. Without airline it is instantaneous.

**Comment by junegunn** [comment]
In my case, it hangs indefinitely until I hit ESC.
