### ISSUE TITLE
`ctrl` + `t` not working.

### ISSUE THREAD

**Issue by yifanchen** [junegunn/fzf#557]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [x] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [x] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

I don't use ag, `ctrl` + `t` doesn't seem working for me. For example:

If I do `rm` then `ctrl` + `t`, nothing happens.

**Comment by junegunn** [comment]
What does `bindkey | grep fzf` say?

**Comment by yifanchen** [comment]
Nothing.

**Comment by junegunn** [comment]
How did you install fzf? Did you follow the instruction given in README page?

**Comment by yifanchen** [comment]
yes, I installed both fzf, and fzf vim, they all working by typing `fzf` and `:FZF` or `:FZF ~`. But `ctrl` + `t` doesn't work.

**Comment by junegunn** [comment]
Please be more specific. Did you run the install script? Do you have a line that loads ~/.fzf.zsh in your .zshrc? Did you reload .zshrc or restart zsh after installation?

**Comment by yifanchen** [comment]
I just did again, and removed `FZF_CTRL_T_COMMAND="seq 100"` form `.zshrc`. Then it worked. Nice. Thanks man.

Btw, can I set my default open directory to somewhere?

**Comment by junegunn** [comment]
> Btw, can I set my default open directory to somewhere?

Not sure what you mean by that. Try configuring `FZF_CTRL_T_COMMAND` as you like.

**Comment by yifanchen** [comment]
Sorry, I should've been more clear.

When I run `fzf`, the default directory starts where I am at. But, I sometimes want to search files that are two levels before. e.g. `../../tt.js`. In this case, I would like to have a fixed directory, no matter where I am at, my fazz search starts from that directory.

**Comment by junegunn** [comment]
See:
- https://github.com/junegunn/fzf#fuzzy-completion-for-bash-and-zsh
- https://github.com/junegunn/fzf/wiki/Fuzzy-completion#zsh

**Comment by yifanchen** [comment]
Cool, thanks man.
