### ISSUE TITLE
Problems integrating fast and fzf

### ISSUE THREAD

**Issue by pdoak** [junegunn/fzf#564]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [x] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

fzf is working well but I have tried to put this function in my .zshrc
`j() {
  local dir
  dir="$(fasd -Rdl "$1" | fzf -1 -0 --no-sort +m)" && cd "${dir}" || return 1
}`
When I invoke, it shows all the matches available but typing to find a file does not act on the list. Am I doing something wrong?

**Comment by junegunn** [comment]
It works for me fine. Can you post the screenshot or an [asciinema](https://asciinema.org/) recording of the situation?

**Comment by pdoak** [comment]
The recording is here: https://asciinema.org/a/8lft84bfutz4nne962fkao551

**Comment by junegunn** [comment]
Yo, that doesn't look like fzf at all. Make sure j is pointing to the right function. You can check the output of `type j`.

**Comment by pdoak** [comment]
Thanks, it was pointing to another alias. I have changed the function name and it now works.
