### ISSUE TITLE
[Help] C-t from ~/ (home directory) goes crazy, filling up the terminal with spaghetti, saying "too many levels of symbolic links".

### ISSUE THREAD

**Issue by krompus** [junegunn/fzf#565]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [x] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [x] zsh
    - [ ] fish

I've looked at the output, and it seems that it goes digging in my `~/.wine/` directory and finds a file system loop, and says there are too many levels of symbolic links.

I don't really need to have `.wine/` included in the fzf search. How would I exclude it or fix the loop?

**Comment by junegunn** [comment]
You can set up `FZF_CTRL_T_COMMAND` as suggested [here](https://github.com/junegunn/fzf#key-bindings-for-command-line). But CTRL-T by default does not include hidden files and directories so `.wine` showing up is strange.

**Comment by krompus** [comment]
Ah, I must have configured it to include hidden files; it was a while ago, and I don't remember how I did this. I actually don't mind (perhaps I'd prefer) including hidden files.

Anyways, for now, how would I make sure that it's not including hidden files?

Maybe it's this section in `key-binding.zsh` that I should modify?

    __fsel() {
      local cmd="${FZF_CTRL_T_COMMAND:-"command find -L . \\( -path '*/\\.*' -o -fstype 'dev' -o -fstype 'proc' \\) -prune \
        -o -type f -print \
        -o -type d -print \
        -o -type l -print 2> /dev/null | sed 1d | cut -b3-"}"
      eval "$cmd" | $(__fzfcmd) -m | while read item; do
        printf '%q ' "$item"
      done
      echo
    }

I've searched the repo for "hidden", and I didn't find anything about it.

**Comment by krompus** [comment]
Update:

I uninstalled fzf and the fzf vim plugin, checked that it wasn't working anymore, checked that there were no stray config files, then reinstalled as per the README.

It's still searching hidden files. There must be a config setting somewhere that I missed. I'm not sure where this would be. :/

**Comment by krompus** [comment]
And another update:

    echo $FZF_DEFAULT_COMMAND 
    find -L . -type f -o -type d -o -type l | sed 1d | cut -b3- | grep -v -e .git/ -e .svn/ -e .hg/
    unset FZF_DEFAULT_COMMAND 

Now `fzf` works as intended for the current terminal session, but `<C-t>` is still searching hidden files. `fzf` searches for hidden files in new terminals.

I've checked in `/etc/profile`, `/etc/zsh/zprofile` and `/etc/environment`, and there are no references to `fzf`.

**Comment by junegunn** [comment]
You should be looking at FZF_CTRL_T_COMMAND instead.

**Comment by krompus** [comment]
Well, it does the same thing when I execute `fzf` from `~/`, so I figured it was DEFAULT command. When I `unset FZF_DEFAULT_COMMAND` in the shell, `fzf` works normally, but `C-t` is still searching hidden files, so I figured it was both.

What should FZF_CTRL_T_COMMAND be by default, and where should I set it? it's not in `env`.

**Comment by junegunn** [comment]
You pasted the code in the above comment that refers to the variable and its default value.

https://github.com/junegunn/fzf/issues/565#issuecomment-217197399

You might want to check if the variable is correct at the spot.

**Comment by krompus** [comment]
Ah, so that is the default value? I'm not sure what would be overriding it.

I'm also not sure what you mean by "check if the variable is correct at the spot"?

**Comment by junegunn** [comment]
I mean like basic printf debugging. You can add an echo statement and see
the value of it there, right?

- junegunn
2016. 5. 6. 오후 12:08에 "krompus" <notifications@github.com>님이 작성:

**Comment by krompus** [comment]
I am unsure how I would begin debugging fzf with printf.

I'm really sorry for my incompetence. :/

**Comment by junegunn** [comment]
Temporarily add an echo statement to `__fsel` function you mentioned above
```sh
# CTRL-T - Paste the selected file path(s) into the command line
__fsel() {
  echo "FZF_CTRL_T_COMMAND: '$FZF_CTRL_T_COMMAND'" 1>&2
```
Reload the file and hit CTRL-T will see the current value of `$FZF_CTRL_T_COMMAND` at the context. Check if the value is empty.

**Comment by krompus** [comment]
Thanks! Yep, it's empty.

Actually, I think that I just needed to restart my machine, because it's fixed now; no more hidden files. I guess that somehow there was a value that I had deleted but was still loaded in the environment.

Thanks for your help, and thank you so much for this amazing program! :)

**Comment by junegunn** [comment]
Good to hear that the problem's gone. Yeah, it must have been a lingering env var from somewhere.
