### ISSUE TITLE
Trying to get fzf to use ag to honour .gitignore

### ISSUE THREAD

**Issue by CrashyBang** [junegunn/fzf#566]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [x] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [x] fish

Trying to follow this guide: https://github.com/junegunn/fzf#respecting-gitignore-hgignore-and-svnignore

So I have the following code in my `config.fish`:
```fish
set -g -x FZF_DEFAULT_COMMAND 'ag -g -i --depth -1  ""'
```

When I use fzf in vim this is not applying and searches like normal, I have talked to some of `fish` developers and they suggested it would be to talk to you as they weren't entirely sure of what to set up.

**Comment by junegunn** [comment]
For some reason, the variable is not exported to vim I guess? Not really familiar with fish. What does `:echo $FZF_DEFAULT_COMMAND` say?

**Comment by CrashyBang** [comment]
It gives the right command? 

```
ag -g -i --depth -1  ""
```

**Comment by junegunn** [comment]
Is that a correct ag command? If I run it on shell, I get the following error:

```
ERR: Error stat()ing:
ERR: Error opening directory : No such file or directory
```

**Comment by CrashyBang** [comment]
If I run it without the `""` it works like so: `ag -g -i --depth -1` sorry I was going off `ag -g ""`.

If i run `ag -g -i --depth -1` outside of neovim it works well, if inside it only gives a few results.

Cheers.

**Comment by CrashyBang** [comment]
Okay I figured it out a bit more it was the order I was adding the params if I run like this:

```bash
ag --ignore-case --depth -1 -g SEARCH-TERM
```

Where SEARCH-TERM is the string I want to search, if I run this from outside neovim it works well, however if I run this using the `$FZF_DEFAULT_COMMAND` I get the following error:

```bash
ERR: Error stat()ing: SEARCH-TERM
ERR: Error opening directory SEARCH-TERM: No such file or directory
```

Is this because of how `$FZF_DEFAULT_COMMAND` is used?

Cheers.

**Comment by CrashyBang** [comment]
I am an idiot... got it working with `ag --ignore-case --depth -1 -g ""` once again I am sorry but hopefully this helps anyone with Fish.
