### ISSUE TITLE
FZF gets unloaded from ZSH

### ISSUE THREAD

**Issue by tofagerl** [junegunn/fzf#567]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [x] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

For some reason my fzf-keybindings stop working in the shell at some point. Of course, I have no idea until I try using one, and then I just get a bell. I don't know what to do to troubleshoot this, but I run the normal fzf-bindings.zsh and fzf-completions.zsh, though come to think of it I don't actually use the completions...

Anyway, when I run `bindkey |grep fzf` while fzf is working, I get the result you would expect: 
```
"^R" fzf-history-widget
"^T" fzf-file-widget
"^[c" fzf-cd-widget
```
But then it stops working, and the same command, in the same zsh session, returns no hits.

I also use other plugins, but they shouldn't matter, since the loading happens at launch, and everything works fine until it doesn't. 
Anyway. The full list of my zplug packages is at the end. 

# FZF vars:
```
$fzf_default_completion = expand-or-complete
$FZF_COMPLETION_TRIGGER = ; # though not used 
$FZF_DEFAULT_COMMAND = ag -g ""
```

# zplug packages:
```
zplug "zsh-users/zsh-history-substring-search"
zplug "willghatch/zsh-saneopt" # Supposed sane options
zplug "plugins/osx", from:oh-my-zsh, if:"[[ $OSTYPE == *darwin* ]]" # Aliases and functions
zplug "plugins/brew", from:oh-my-zsh, if:"[[ $OSTYPE == *darwin* ]]" # Completion
zplug "plugins/brew-cask", from:oh-my-zsh, if:"[[ $OSTYPE == *darwin* ]]" # Completion
zplug "plugins/gem",   from:oh-my-zsh, if:"(( $+commands[gem] ))" # Completion
zplug "plugins/tmuxinator", from:oh-my-zsh, if:"(( $+commands[tmuxinator] ))" # Completion
zplug "zsh-users/zsh-syntax-highlighting", nice:10 # Syntax highlighting on CLI
zplug "dbkaplun/smart-cd" # automatic ls in dirs, git status in repos
zplug "zlsun/solarized-man" # Solarized man-pages
zplug "djui/alias-tips" # Let's you know there was an alias you could ahve used
zplug "powerline/powerline", use:"/powerline/bindings/zsh" # Power in a line
zplug "voronkovich/gitignore.plugin.zsh" # gitignore.io gi() and gii()
zplug "akoenig/gulp.plugin.zsh" # Gulp completion in dev dirs
zplug "chrissicool/zsh-256color" # Color autoset
zplug "zsh-users/zsh-autosuggestions" # Type some chars from a previous command and hit arrow-up to sort through matching commands from history
zplug "zsh-users/zsh-completions", use:src # Completions
zplug "supercrabtree/k" # Quick ls-replacement with git status
zplug "oz/safe-paste" # Don't execute lines when pasting
zplug "plugins/node", from:oh-my-zsh
zplug "joel-porquet/zsh-dircolors-solarized", if:"[[ $OSTYPE == *darwin* || $OSTYPE == *linux* ]]" # Solarized LS_COLOR
zplug "Tarrasch/zsh-autoenv", use:autoenv.zsh
zplug "uvaes/fzf-marks"
```

Looking for help in debugging this. I don't expect it to be a problem in fzf itself, but in my setup. The problem is my ZSH dotfiles are kind of sprawling, and I have no idea how to look for the problem...

**Comment by junegunn** [comment]
> But then it stops working, and the same command, in the same zsh session, returns no hits.

So what are those keys mapped to? I mean, what do you see on `bindkey | grep '"^[RT]"'`?

**Comment by tofagerl** [comment]
Nothing. Unmapped. At least as far as I remember. I'll have a look the next time it happens.

**Comment by tofagerl** [comment]
By the way, when I press alt-c I only get subfolders from my working directory to choose from. Any way to make it search from / instead?

**Comment by tofagerl** [comment]
```bindkey | grep '"^[RT]"' 
"^R" history-incremental-search-backward
"^T" transpose-chars```

Alt-C I can't grep for, but it looks empty from the full listing.

**Comment by junegunn** [comment]
Probably one of your zsh plugins is restoring the default key bindings at some point. You'll have to figure out which one is doing that.

**Comment by tofagerl** [comment]
Any idea what kind of syntax I should be looking for with ack or ag? Bindkey isn't returning anything interesting...

**Comment by junegunn** [comment]
You're asking a bash user here :)

`bindkey -d` and `bindkey -e` is something I would look for.

**Comment by tofagerl** [comment]
*Sharp intake of breath*
Dude... You should really try it...

Although if I were to start from scratch I might try Fish instead, my ZSH settings are a mess, and ZSH makes it quite easy to get into such a mess...

**Comment by tofagerl** [comment]
OK, after two days I'm ready to pronounce oz/safe-paste as the guilty plugin. It plays fast and dirty with bindkey.
