### ISSUE TITLE
$TERM-agnostic 256 colors

### ISSUE THREAD

**Issue by rosshadden** [junegunn/fzf#570]
- Category
    - [x] fzf binary
    - [x] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [ ] fish

I use [termite](https://github.com/thestinger/termite) as my terminal, and my `$TERM` environment variable is set to `xterm-termite`.  Termite definitely supports 256 colors, and true color as well.  I don't think `fzf` should look for the presence of `256` in `$TERM`.

I don't know what the best solution is, but based on [the terminfo file](https://github.com/thestinger/termite/blob/master/termite.terminfo#L12) I see the line `colors#256`... Maybe we can look in the terminfo files?

As a fallback, or even the final solution, I think we should add a `--256` option to complement the `--no-256` one, which would force 256 colors.  This would of course be the least amount of work and should probably happen regardless of if we come up with a more robust solution.

Thoughts?

**Comment by junegunn** [comment]
I don't like relying on the value `$TERM` but I'm not aware of a better method. Digging up a terminfo file seems like a bit of a hassle. And can we be sure that the location of the file is consistent across different OSes and distros? 

Regarding your suggestion of `--256`, does `fzf --color=dark` work?

**Comment by rosshadden** [comment]
Oh, we can use `tput colors`!  You're already using `tput` so this isn't even introducing another dependency.

In my terminal it returns `256`.  On terminals that don't support 256 colors it will return `8`, and I dunno what it would return if only one color is supported but I would imagine `1`.

**Comment by junegunn** [comment]
Spawning an external commands invariably adds some overhead to the startup time, it's not going to be huge of course, but I'd really like to avoid that. I wonder how other programs detect 256-color capability, e.g. `t_Co` of vim

**Comment by junegunn** [comment]
Okay, I found that we can find the info with `tigetnum("colors")`. It has to be called after ncurses initialization, so the option parser should defer its processing until then.

**Comment by rosshadden** [comment]
I have seen `tput colors` used by a lot of terminal apps, like [ranger](https://github.com/hut/ranger/blob/master/ranger/data/scope.sh#L94), but if you think `tigetnum` is best, it sounds good to me.  You clearly know a lot more about TUI performance optimization than I do :smile:

**Comment by justinmk** [comment]
For SSH and TMUX, at least, `$TERM` is a stronger hint than the state of terminfo on the remote server.

This road ends up very similar to the history of user-agent sniffing in web browsers. FZF is not the only application you'll be fighting if you refuse to put "256" in your `$TERM`.

**Comment by junegunn** [comment]
@rosshadden Updated the code to use tigetnum call. Will be included in the next release. Or you can easily build the latest binary with `go get github.com/junegunn/fzf/src/fzf` if you have Go.

@justinmk Thanks for chiming in. This is a new territory for me. The return value of `tigetnum("colors")` of ncurses seems to depend on the value of `$TERM` (e.g. `TERM=screen fzf` / `TERM=screen-256color fzf`), so I guess it's okay?

**Comment by rosshadden** [comment]
@junegunn Your change works perfectly.  Thank you!

@justinmk Your argument works even better against what you said.  Looking in `$TERM` for the presence of `256` is exactly the same in many ways as user-agent sniffing.  Looking at `tput colors` and `tigetnum('colors')` (which return numbers like 1, 8, 256, or greater) are more along the lines of feature testing, which is less hacky and more future-proof.  I think we may be saying the same thing, here, but ultimately being smart about the checks we make is a good practice, and I think you can probably agree that @junegunn's solution is indeed smart.

Also `fzf` is awesome!

**Comment by justinmk** [comment]
@rosshadden I am not advocating for or against any specific approach. Invariably a basket of heuristics is required, because users and distros misconfigure their terminals _and terminfo dbs_ in numerous fun ways. There's no such thing as a reliable "feature test" for all terminals in use.
