### ISSUE TITLE
Accept arbitrary input

### ISSUE THREAD

**Issue by rosshadden** [junegunn/fzf#571]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [x] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [ ] fish

Is there a current way to directly accept the current input as-is?  This would let `fzf` be used in situations where the user wishes to enter something not necessarily in the choice list.

The example I used when I implemented this in [pick](https://github.com/thoughtbot/pick/pull/61) was the following:

```sh
git checkout $(git branch | cut -c 3- | fzf)
```

Thus in addition to checking out an already-cloned branch, users could also checkout a specific commit.  In my case I have a [git cd alias](https://github.com/rosshadden/dotfiles/blob/3d737d5082c4273c00aa1aa32688fc1cffdfcbba/src/.gitconfig#L90), which will check out the branch if it exists or create/checkout if it does not.  Thus I can (using `pick` until I figure out how to do it with `fzf`) create new branches from the input as well.

**Comment by junegunn** [comment]
`git branch | cut -c 3- | fzf --print-query | tail -1` can be used in that context though not completely equivalent. There is currently no bindable action that only prints the query.

**Comment by edi9999** [comment]
> There is currently no bindable action that only prints the query.

I think it would make sense to have one :-)

**Comment by junegunn** [comment]
Yeah, I'm also going to make `alt-enter` and `alt-space` valid key names.

**Comment by rosshadden** [comment]
Cool! `alt-enter` is what I made perform this behavior in `pick`, so anyone else coming to `fzf` from that like I did will be used to it.
