### ISSUE TITLE
Running fzf-tmux by tmux itself (with run-shell) stopped working

### ISSUE THREAD

**Issue by sergei-dyshel** [junegunn/fzf#572]
- Category
    - [ ] fzf binary
    - [x] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [ ] fish

I'm running `fzf-tmux` by tmux itself (as part of tmux plugin). I worked nicely for me, until  [this change](https://github.com/junegunn/fzf/commit/c727ba1d992acfb175adb273a89729d3df2fd9b0#commitcomment-17433314). 
Commands run by tmux with `run-shell` have env `TMUX` defined but not `TMUX_PANE`. After change `$TMUX` -> `$TMUX_PANE` the script naturally to run `fzf` not inside tmux pane and of course fails. 

Can this be fixed?

**Comment by junegunn** [comment]
Okay.

**Comment by junegunn** [comment]
Fixed in 66f86e18700f08daa20404d212021da412800d53. Wrong issue reference :(
