### ISSUE TITLE
[Suggestion] add switch to narrow down default behavior to directories

### ISSUE THREAD

**Issue by vors** [junegunn/fzf#574]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [x] fish

When `fzf` run with no parameters, it displays all files.
It would be useful to add an option to narrow down this input just to **folders**, so something like [z](https://github.com/rupa/z) could be easily implemented on top (without building a database).

**Comment by junegunn** [comment]
fzf is a filter, so you can feed anything into it or you can customize the default command via `$FZF_DEFAULT_COMMAND`. Please refer to
- https://github.com/junegunn/fzf#usage
- https://github.com/junegunn/fzf#respecting-gitignore-hgignore-and-svnignore
