### ISSUE TITLE
Mapping data from input to expected outputs

### ISSUE THREAD

**Issue by marcaddeo** [junegunn/fzf#575]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

So not sure if it's possible to do this already, but it's something I'd like to be able to do with fzf.

For instance I'd like to use fzf to add files with `git add`. I know I can do `git add $(fzf)` but that's going to get all files. I'd like to be able to take the output of `git status --porcelain` and map that to information that actually gets selected.

So I'd like to be able to pass data such as this to fzf:

```
M file.txt : file.txt
M some/really/long/path/and/another/and/another/something.php : some/really/long/path/and/another/and/another/something.php
?? some/untracked/file : some/untracked/file
?? another : another
```

Where fzf would display the content to the left of the `:`, but return the content to the right of the `:`.

That way I can write a function to simply create the above data structure, pass it to fzf and get the expected result.

I may be overthinking this, or not articulating myself well.. But let me know if you have any suggestions on how to accomplish this, or if you think it'd be a good addition to fzf.

**Comment by junegunn** [comment]
You can post-process the output like you normally do in shell scripts; `sed`, `awk`, `cut`, `perl`, or whatever.

```sh
git status --porcelain | fzf-tmux -m | cut -c 4-
```

So I don't think what you asked is necessary in this case, but there's `--with-nth` option you can use for that purpose.

Anyway, I find it much more useful to have key bindings for selecting git objects. 

http://stackoverflow.com/questions/36513310/how-to-get-a-gits-branch-with-fuzzy-finder/37007733#37007733

The examples are for bash, but I believe you can easily tweak them for zsh.
