### ISSUE TITLE
[Question] Detect if the terminal buffer is used by fzf or not in neovim

### ISSUE THREAD

**Issue by ahmedelgabri** [junegunn/fzf#576]
- Category
    - [x] Neovim
- OS
    - [x] Mac OS X
- Shell
    - [x] zsh

I'd like to add this `tnoremap <esc>      <c-\><c-n>` to my `.vimrc` but the problem is that it breaks the <kbd>ESC</kbd> with fzf. So is there is any way I can check if the terminal buffer is related to fzf or not and then decide to apply this key binding to it or not?

**Comment by junegunn** [comment]
```vim
tnoremap <expr> <esc> &filetype == 'fzf' ? "\<esc>" : "\<c-\>\<c-n>"
```

FYI, you can use <kbd>CTRL-C</kbd> instead of <kbd>ESC</kbd> to close fzf.

**Comment by ahmedelgabri** [comment]
@junegunn Thanks!

I know about <kbd>CTRL+C</kbd> but it's just that my brain is programmed to use <kbd>ESC</kbd> for exit while <kbd>CTRL+C</kbd> is for killing processes :)

**Comment by xeyownt** [comment]
For the record, I just came with this solution:
```vim
tnoremap <Esc> <C-\><C-n>
au TermOpen term://*fzf* tnoremap <buffer> <Esc> <Esc>
```
Note that `tunmap` does not work. I also have to use the double wildcard in `*fzf*`.

In any case, junegunn's solution is better tmo.
