### ISSUE TITLE
Cripplingly slow in directories with many descendents

### ISSUE THREAD

**Issue by caesar** [junegunn/fzf#578]
On my old Macbook Pro, searching for a simple name directly in the current directory is unusably slow if the current directory has a lot of descendents.

Example: I open fzf in my home dir and type `dot`. There is a folder in my home dir called `dotfiles`. Because fzf (seemingly) searches in alphabetical order, and searches through the whole directory tree of each directory before continuing with the next entry, it has to search 70000 files before it finally finds my `dotfiles` dir. It can take minutes.
This seems to be mostly because it's searching all the `node_modules` in all the projects in my `code` dir, and through every descendent of my `AndroidStudioProjects` dir, both of which alphabetically come before `dotfiles`.

I propose an optimization for a common use case: Add the direct descendents of the current directory to the list *before* iterating through every directory tree. This would make it almost instant.
(I would argue this should be the strategy throughout the tree actually. "Closer" descendents should always be added before "further" ones.)

I am using the fish shell but I've tried it from bash too; no difference. As would be expected because it's not a shell integration issue.

**Comment by junegunn** [comment]
fzf does not implement directory traversal, it simply spawns `find` process with certain options for that when stdin is not fed.

Have you tried [this](https://github.com/junegunn/fzf#respecting-gitignore-hgignore-and-svnignore)? ag respects `.gitignore` and `node_modules` will not be listed as the directory is usually specified in `.gitignore`.

**Comment by caesar** [comment]
@junegunn, interesting. I have set it to use `ag` and it does indeed seem to run faster, however, now Ctrl-T doesn't include directories anymore.
Is there a solution? So far as I can see `ag` can't search for directory names, so I'm guessing not.

**Comment by junegunn** [comment]
I wrote a simlle wrapper script that can be used to extend the output of ag.

https://github.com/junegunn/dotfiles/commit/6661555889bb9c02c0bd7fc24a3473e6688ef5cf

**Comment by caesar** [comment]
@junegunn, that's great! Only problem I see is that it doesn't include empty dirs. That would require a different approach. But it's really helpful nonetheless, thanks.

A few thoughts:
- would it make sense to include that in `fzf` by default, or as an option?
- maybe it would be good to have two shortcuts, one for directories (use whatever mechanism Alt+C uses) and one for files?
- maybe `fzf` could automatically use `ag` if it is available?

Sorry for the false bug report. :-)

Off topic, but since I'm talking to you.... is there any reason the autocompletion (`**`) doesn't work in Fish? Is it just that nobody's written the code, or is there a reason it wouldn't work?
(I'm new to Fish, and honestly I'm seeing so many incompatibility issues I'm considering moving to ZSH, but I'm going to stick with it a few weeks and see how I feel then. Change is always hard and Fish has a lot of nice features...)

**Comment by junegunn** [comment]
> it doesn't include empty dirs

True, good point.

About your questions: No, I see fzf as a simple unix filter, just like grep, a tool you can build stuff with it, and I don't want to extend the scope of this repository any further. The more this repository tries to provide, the more time I'll be wasting dealing with someone else's issues. Some user may not have Ruby, some user may prefer pt over ag, some user may want to have caching mechanism, etc. I'll just leave it up to the users. Providing more key bindings for shells other than the ones that we have now is also not what I'm planning to do. Dealing with the endless issues of three different shells has been a big pain point for me as the maintainer of the project, especially considering that what I only use is bash. Users are encouraged to implement their own key bindings.

> is there any reason the autocompletion (**) doesn't work in Fish? Is it just that nobody's written the code, or is there a reason it wouldn't work?

The former.
