### ISSUE TITLE
fzf-history-widget in zsh doesn't handle parenthesis.

### ISSUE THREAD

**Issue by acornejo** [junegunn/fzf#579]
- Category
    - [ ] fzf binary
    - [x] fzf-tmux script
    - [x] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

Repro steps:

1. open up a zsh shell
2. type: (echo hello; echo world;)
3. hit ctrl-R to bring up fzf and select the most recent entry

outcome:

fzf-history-widget:2: bad pattern: (echo

This issue happens whenever there are parenthesis in the command line.

**Comment by deathmaz** [comment]
I tried to reproduce the issue but everything works just fine, without "bad pattern" thing

**Comment by acornejo** [comment]
@deathmaz could you provide the output of the following command: `echo $ZSH_VERSION`

in my case it is 5.0.5. Also I've reproduced this issue both inside and outside tmux.

**Comment by acornejo** [comment]
Also in case it matters (I don't think it does), here are the relevant FZF settings in my environment:

```
$ env | grep FZF
FZF_DEFAULT_OPTS=--bind alt-p:page-up,alt-n:page-down
FZF_DEFAULT_COMMAND=ag -l -g ""
```

**Comment by acornejo** [comment]
@deathmaz 

I am actually now very curious about what zsh version you are using, I just managed to get a very succint reproduction step:

```
selected=( $(echo "1 (echo hello;)" | fzf  +s --tac +m -n2..,.. --tiebreak=index --toggle-sort=ctrl-r ${=FZF_CTRL_R_OPTS} -q "${LBUFFER//$/\\$}") )
```

This is essentially the snippet executed by the fzf-history-widget, with the exception that I am not display your history but instead simulating a history with a single item, the `(echo hello;)` command.

**Comment by acornejo** [comment]
found the problem, its the glob_subst option.

@deathmaz 

Do this first `setopt glob_subst`

Now use the fzf history widget with a command with parenthesis and you should see the same problem.

**Comment by deathmaz** [comment]
@acornejo my zsh version is 5.2 and yes, after `setopt glob_subst` i can reproduce the issue

**Comment by junegunn** [comment]
Thanks for the report. Fixed it!
