### ISSUE TITLE
C-r is slow with `set blink-matching-paren on` in .inputrc

### ISSUE THREAD

**Issue by ptzz** [junegunn/fzf#580]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [x] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

There is a delay when accessing history with `C-r`, if `set blink-matching-paren on` is in .inputrc.
The reason seems to be the parentheses in the bound command: `bind '"\C-r": " \C-e\C-u$(__fzf_history__)\e\C-e\e^\er"'`.

I have tried to resolve it using `bind -x` (to execute the command silently so there are no parentheses to match), but the errors I get then is beyond my readline and bash level.

**Comment by junegunn** [comment]
Thanks for the report. Hmm, an easy fix would be to change the command substitutions to use backticks instead of `$(...)`. What do you think? Interestingly the change is not needed for `vi`-mode where `blink-matching-paren` doesn't seem to work.

```diff
diff --git a/shell/key-bindings.bash b/shell/key-bindings.bash
index 5ff20bb..41e707e 100644
--- a/shell/key-bindings.bash
+++ b/shell/key-bindings.bash
@@ -67,7 +67,7 @@ __fzf_use_tmux__() {
 [ $BASH_VERSINFO -gt 3 ] && __use_bind_x=1 || __use_bind_x=0
 __fzf_use_tmux__ && __use_tmux=1 || __use_tmux=0
 
-if [[ $'\n'$(set -o) != *$'\n'vi*on* ]]; then
+if [[ ! -o vi ]]; then
   # Required to refresh the prompt after fzf
   bind '"\er": redraw-current-line'
   bind '"\e^": history-expand-line'
@@ -82,10 +82,10 @@ if [[ $'\n'$(set -o) != *$'\n'vi*on* ]]; then
   fi
 
   # CTRL-R - Paste the selected command from history into the command line
-  bind '"\C-r": " \C-e\C-u$(__fzf_history__)\e\C-e\e^\er"'
+  bind '"\C-r": " \C-e\C-u`__fzf_history__`\e\C-e\e^\er"'
 
   # ALT-C - cd into the selected directory
-  bind '"\ec": " \C-e\C-u$(__fzf_cd__)\e\C-e\er\C-m"'
+  bind '"\ec": " \C-e\C-u`__fzf_cd__`\e\C-e\er\C-m"'
 else
   # We'd usually use "\e" to enter vi-movement-mode so we can do our magic,
   # but this incurs a very noticeable delay of a half second or so,
```

**Comment by ptzz** [comment]
Didn't think about that, brilliant fix!  👍

**Comment by junegunn** [comment]
Pushed the fix. We'll see if there's any side effects.

**Comment by ptzz** [comment]
Still having problems. Seems `[[ ! -o vi ]]` evaluates to `0` and the code path with your fix is not being executed. I have vi mode disabled:
```
~$ set -o | grep -w "vi"
vi             	off
~$ [[ ! -o vi ]]
~$ echo $?
0
```
