### ISSUE TITLE
Unable to load fzf plugin in vim

### ISSUE THREAD

**Issue by mrleolink** [junegunn/fzf#583]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [x] Vim
    - [x] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

Vim is unable to load fzf if fzf directory's path has spaces in it.

I managed to fixed it by making this change in `fzf/plugin/fzf.vim`:

` let s:fzf_go = expand('<sfile>:h:h').'/bin/fzf'`
to
`let s:fzf_go = "expand('<sfile>:h:h')".'/bin/fzf'`

Because I don't really know vim language so I don't make a pull request.
But it would be nice if this gets fixed.

**Comment by junegunn** [comment]
Fixed it, thanks for the report.
