### ISSUE TITLE
--delimiter is printed inside filter output

### ISSUE THREAD

**Issue by DanielFGray** [junegunn/fzf#585]
When using `-d`/`--delimiter` with `--with-nth`

    echo 'foo bar#baz' | fzf --with-nth='..-2' -d '#'

produces

    foo bar#

in the filter. I would expect to just see `foo bar`. I'm not sure if this is intentional, but I can't help think it isn't, unless there's something I'm missing..

- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [ ] fish

**Comment by junegunn** [comment]
It is intentional. It makes good sense for tab-separated data, comma-separated data, or input that is aligned by multiple spaces.

```
ls -al | sed 1d | column -t | fzf --with-nth 1,3..5,..
```

I once used U+2007 when I didn't want the delimiters to be shown but couldn't use space as the delimiter.
