### ISSUE TITLE
Pane title change breaks fzf on tmux 2.0

### ISSUE THREAD

**Issue by davidmh** [junegunn/fzf#586]
- Category
    - [ ] fzf binary
    - [x] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [x] fish

I'm running `tmux 2.0`, `fish 2.3.0` on ubuntu 15.04, 

fzf-tmux doesn't open the pane.

https://gfycat.com/ElasticIdolizedChupacabra

If I revert f074709, it works again.

The weird part is that tmux doesn't have any issues with `printf '\033]2;fzf\033\\';` on its own.

**Comment by junegunn** [comment]
@akashin Any idea?

**Comment by liyinsg** [comment]
Same issue, running Ubuntu 16.04, tmux 2.1-3build1, fish 2.2.0-676-g6a16bdb-1~wily

**Comment by junegunn** [comment]
@akashin I'm going to have to revert the change until the issue is resolved.

**Comment by akashin** [comment]
Sure, I'll take some time to investigate the issue.
