### ISSUE TITLE
Option to preview focused item with an external command

### ISSUE THREAD

**Issue by junegunn** [junegunn/fzf#587]
Something like:

```sh
git ls-files | fzf --preview "head -$LINES {}" --color light --margin 5,20
```

<img width="1280" alt="head" src="https://cloud.githubusercontent.com/assets/700826/15798496/a2599866-2a75-11e6-8ffa-ba5b8127e068.png">

With some ANSI colors:

```sh
git ls-files | fzf --preview "pygmentize {}" --color light --margin 5,20
```

<img width="1280" alt="pygmentize" src="https://cloud.githubusercontent.com/assets/700826/15798500/b71f0c9a-2a75-11e6-9f2f-a6572fdc69b4.png">

TBD:
- Yes or no
- Layout: top/bottom/left/right(/hidden), size

**Comment by deathmaz** [comment]
yes;
Layout - right side 70 or 80%

**Comment by infokiller** [comment]
Suggestion:
An improved version of shell history search where the selected command is fully displayed along with context. As a first step the context can include commands that were typed before and after. Later it would be also nice to add the output of that command.
That would also provide a nice solution to multi line commands, a feature that was requested (for example in #461).

Not sure how cool, but definitely helpful for me personally.

**Comment by junegunn** [comment]
@infokiller Thanks for the input. I tried to apply it to the shell history search idea as you suggested, but then I quickly ran into #590.

**Comment by infokiller** [comment]
Thanks @junegunn! 
fzf is already great, and this feature sounds awesome.

**Comment by junegunn** [comment]
Seems nice. Two different layouts.

```
FZF_CTRL_R_OPTS="--preview-window up:3 --preview 'echo {}'"
```
<img width="1280" alt="screen shot 2016-06-08 at 1 03 59 am" src="https://cloud.githubusercontent.com/assets/700826/15865240/043d5ba2-2d15-11e6-8f6c-59ee848d8e73.png">

```
FZF_CTRL_R_OPTS="--preview-window right:30% --preview 'echo {}'"
```
<img width="1280" alt="screen shot 2016-06-08 at 1 05 36 am" src="https://cloud.githubusercontent.com/assets/700826/15865301/2fde2d36-2d15-11e6-81a1-49f0f8242369.png">

**Comment by infokiller** [comment]
Cool!
Is it possible to get the selected line number in the `preview` command?
That way it would be possible to unambiguously show the context of the command (+-N lines).

**Comment by junegunn** [comment]
Hmm, not sure about that. In bash the command is just a long string and ncurses window (of fixed size) wraps the line and it finally tells me to stop putting more text on overflow.

**Comment by khalidchawtany** [comment]
This is great :+1:. 
I have always wanted to be able to see past the screen without horizontally scrolling, which is not possible in the first place.

**Comment by infokiller** [comment]
@junegunn 
I'm not really familiar with ncurses, so I'm not sure I'm following.
Given the line number of the selected line, wouldn't it be possible to grab +-N lines (for example using `head` and `tail`) and send it for display to the ncurses window?
What is the interface to the ncurses window? is it just a string that is passed?

**Comment by junegunn** [comment]
@infokiller Oh, I thought you were still talking about command history. And yes, that would be possible.

@khalidchawtany That's two more options, on by default or off by default, and the bindable action for toggling preview window. And soon we're going to hear from someone who wants the window to be hidden when the focus is moved, now we have three :) I'll think about it.

**Comment by infokiller** [comment]
@junegunn Just to clarify, my intention is to show in the preview window something similar to what you would get using grep's `-C` option.
For example, let's say I want to display 1 line of context. Furthermore, let's say I have these lines in my shell history:
```
echo 1
echo 2
echo 3
echo 4
echo 5
echo 6
```

Then, if I type 4 in the fzf prompt I want the preview window to show:
```
echo 3
echo 4
echo 5
```

**Comment by junegunn** [comment]
@infokiller Yeah, sure. If it's possible with shell scripting, it can be done. Anyway what I want to stress is that I'm not going to consider dynamic resizing of the preview window at this stage.

**Comment by infokiller** [comment]
That's more than fair.
Really looking forward to an fzf release with this feature!

**Comment by junegunn** [comment]
@khalidchawtany I was able to implement toggling without too much effort, it's going in.

```sh
fzf --preview 'echo {}' --preview-window up:10 --bind ?:toggle-preview
```

Still we need a way to specify if we want the preview window from the beginning or not (and *optionally* if we want to automatically hide it when you move your cursor or type in characters). Something like `up:10:hidden` comes to my mind, but I'm not sure yet.

**Comment by khalidchawtany** [comment]
@junegunn :+1:  At least the toggle binding is so much lovely to have. Even if there is no default on/off part.

I know for sure that others will request the on/off part so much, that you will not be able to resist :stuck_out_tongue_winking_eye:

**Comment by junegunn** [comment]
A simple but nice use case.

```sh
fzf --preview='file {}' --preview-window=down:1
```

<img width="640" alt="screen shot 2016-06-10 at 1 59 55 am" src="https://cloud.githubusercontent.com/assets/700826/15938688/3762d944-2eaf-11e6-8ace-18f826cf6eda.png">

**Comment by khalidchawtany** [comment]
@junegunn is there anyway to use a vim function for the `--preview` command?

**Comment by balta2ar** [comment]
@junegunn Can this functionality be used to display one-line hg log/git log on the left side, and corresponding changeset diff on the right side? If so, could you please demonstrate a simple example of that?

**Comment by junegunn** [comment]
@khalidchawtany I can't imagine a straightforward way to do that. Let me know if you find one.

@balta2ar It's not *simple*, but:

```sh
# fshow - git commit browser
fshow() {
  git log --graph --color=always \
      --format="%C(auto)%h%d %s %C(black)%C(bold)%cr" "$@" |
  fzf --ansi --no-sort --reverse --tiebreak=index --bind=ctrl-s:toggle-sort \
      --header "Press CTRL-S to toggle sort" \
      --preview "echo {} | grep -o '[a-f0-9]\{7\}' | head -1 |
                 xargs -I % sh -c 'git show --color=always % | head -$LINES'" \
      --bind "enter:execute:echo {} | grep -o '[a-f0-9]\{7\}' | head -1 |
              xargs -I % sh -c 'vim fugitive://\$(git rev-parse --show-toplevel)/.git//% < /dev/tty'"
}
```

`head -$LINES` part is necessary due to #598 which I'm going to fix it shortly.

**Comment by balta2ar** [comment]
@junegunn Thanks! I'm using this feature and I like it!

> Still we need a way to specify if we want the preview window from the beginning or not
 
Yes, that would be awesome. I miss that.

There is an issue, though. I'm using diff-so-fancy, and it probably detects terminal width upon execution to calculate the length of the horizontal bar. Unfortunately, with fzf it thinks that the horizontal space is wider than it actually is:

![](http://scrin.org/i/16/06/tmpyiblgoru0es.png)

Notice long white horizontal lines. They should not wrap the window. Like this:
![](http://scrin.org/i/16/06/tmp5ifnoxeshns.png)

Could fzf fix that?

**Comment by deathmaz** [comment]
Guys, can someone help me, i have the latest version of fzf on my laptop, but when i'm trying to use this example 

> `# fshow - git commit browser
fshow() {
  git log --graph --color=always \
      --format="%C(auto)%h%d %s %C(black)%C(bold)%cr" "$@" |
  fzf --ansi --no-sort --reverse --tiebreak=index --bind=ctrl-s:toggle-sort \
      --header "Press CTRL-S to toggle sort" \
      --preview "echo {} | grep -o '[a-f0-9]\{7\}' | head -1 |
                 xargs -I % sh -c 'git show --color=always % | head -$LINES'" \
      --bind "enter:execute:echo {} | grep -o '[a-f0-9]\{7\}' | head -1 |
              xargs -I % sh -c 'vim fugitive://\$(git rev-parse --show-toplevel)/.git//% < /dev/tty'"
}`

i'm getting this error
`unknown option: --preview`

**Comment by khalidchawtany** [comment]
@deathmaz I think that the version used when you use --preview is not the latest.

**Comment by deathmaz** [comment]
Maybe i'm doing something wrong, so here my terminal session:
[https://asciinema.org/a/512wy7k30engo7w5yzzivj51z](url)

**Comment by junegunn** [comment]
@balta2ar 
> Yes, that would be awesome. I miss that.

We already have `:hidden` suffix. e.g. `--preview-window right:hidden`, `--preview-window up:30%:hidden`

> Unfortunately, with fzf it thinks that the horizontal space is wider than it actually is:

Overriding `$COLUMNS` seems to work: `COLUMNS=30 diff-so-fancy`

**Comment by junegunn** [comment]
@deathmaz Check `which fzf`, it's probably pointing to an older binary in another location.

**Comment by deathmaz** [comment]
`which fzf` returns `/usr/bin/fzf`

**Comment by junegunn** [comment]
@deathmaz Yeah, that's not the place `install` script downloads fzf binary.

**Comment by deathmaz** [comment]
ok, what should i do to correct this?

**Comment by infokiller** [comment]
@deathmaz 
This not related to this issue. 
Please move the discussion to another issue.

**Comment by balta2ar** [comment]
> We already have :hidden suffix. e.g. --preview-window right:hidden, --preview-window up:30%:hidden

Thanks, I didn't notice that!

> Overriding $COLUMNS seems to work: COLUMNS=30 diff-so-fancy

Yes, it is indeed working. But it's it right for fzf itself to override it as long as it's limiting available space anyway? Otherwise in preview commands I will need to write something like this:
```
--preview "echo {} | cut -d' ' -f2 | COLUMNS=$(echo $COLUMNS/2-5|bc) xargs hg fdiff --color=always -c" \
```

**Comment by junegunn** [comment]
@balta2ar Hmm, I don't want to do that. `$LINES` and `$COLUMNS` are not guaranteed to work on different shells. As far as I know, shells like fish or tcsh do not use them. And even on bash or zsh, some programs directly refer to `/dev/tty` to find the screen size instead of relying on those variables. It's an incomplete solution that can cause extra confusion. I'll just leave it up to the users.

**Comment by balta2ar** [comment]
@junegunn okay, fair enough.

In that case I have another question. Is there a way to minimize wasted screen space? I know this is about aesthetics and is of course arguable, but I'd like to remove certain characters from the output. Look at the partial output near the preview window delimiter:
```
(20 hours.. │ Author:
```
Here we have:
1. Two characters `..` for ellipses
2. One character for space
3. One character for pipe
4. One character for space

Can I get rid of `..` and spaces and leave only vertical bar? I also would like to remove horizontal lines at the top and at the bottom and a vertical line on the right.

**Comment by junegunn** [comment]
Sorry, but no plan to add more options. Complexity control. As the name
implies the purpose of `--preview` is to present simple preview inside fzf
(in fshow example you can hit enter key to see the full content on vim).
It's not an attempt to turn fzf into a fully-customizable TUI framework.

- junegunn

**Comment by junegunn** [comment]
For those who have tried `pygmentize`, take a look at [coderay](https://github.com/rubychan/coderay), it's considerably faster.

**Comment by suweller** [comment]
@balta2ar, the way `diff-so-fancy` dresses up the git output also doesn't work when you resize your shell window either. I patched `diff-so-fancy`:
```
# diff-so-fancy/0.11.2/libexec/lib/node_modules/diff-so-fancy/libexec/diff-so-fancy.pl

sub horizontal_rule {
	my $color = $_[0] || "";
	my $width = 1; # <-- use 1 instead of --> `tput cols`;
```

**Comment by 3N4N** [comment]
@junegunn I want to enable prefix for only text files, not for binary files. Can it be done? I mean, I'm using `--preview 'head -10 {}'`. There might be some way to check beforehand if the highlighted file is binary or text.
