### ISSUE TITLE
Change cursor symbol via cli option

### ISSUE THREAD

**Issue by roboslone** [junegunn/fzf#592]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

I would really like to change symbol used for cursor (`>`) via command line option. Is that possible?

**Comment by junegunn** [comment]
`fzf --prompt "foobar "`

**Comment by roboslone** [comment]
Nope, I didn't mean prompt, I meant cursor:
```
     2.json
   > 1.json
     14/453
```

**Comment by roboslone** [comment]
Ping...

**Comment by junegunn** [comment]
Sorry, I decided not to add more options for customizing UI elements for the moment. Because if I start accepting such requests, we'll end up with so many insignificant options that few users actually use. If you really want to change it, consider building your own binary.

**Comment by cevhyruz** [comment]
@junegunn can you point on which part can we change the pointer?

**Comment by ddnexus** [comment]
> we'll end up with so many insignificant options that few users actually use

I understand and agree with the principle, however, the cursor doesn't look so "insignificant" to me.
It is a quite central part of the UI and it could be upgraded to a more visible character/icon like a full sized solid triangle for example.

**Comment by pawel-szopinski** [comment]
I totally agree with @ddnexus here. Pointers (>, <) are the central part of the fzf UI and I'd really like to be able to change it, so that it matches visually with other parts of my terminal.

**Comment by bdesham** [comment]
This has been possible with the `--pointer` option since fzf 0.21.0 was released in March 2020.

**Comment by ddnexus** [comment]
@bdesham Yup! Using it. I found it out after my post :)

**Comment by pawel-szopinski** [comment]
Thank you, @bdesham!

I was able to change prompt, pointer and marker. The only thing that I cannot change is "<" sign when --info=inline is used.

**Comment by lorens-osman-dev** [comment]
how i can change the --pointer , i did'nt find information about it ?

**Comment by LangLangBart** [comment]
> how i can change the --pointer , i did'nt find information about it ?

```sh
man fzf
#        --pointer=STR
#               Pointer to the current line (default: '>')
```

fzf --pointer '❯'

**Comment by CodesOfRishi** [comment]
@LangLangBart just wanted to check if you have the opposite symbol for '❯' as well, .i.e, the same symbol but pointing in left direction (<)?
