### ISSUE TITLE
using zsh ^T keybinding, pasting into fzf run on command line munges pasted text

### ISSUE THREAD

**Issue by stephentalley** [junegunn/fzf#594]
- Category
    - [x ] fzf binary
    - [ ] fzf-tmux script
    - [x ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x ] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x ] zsh
    - [ ] fish

Running zsh with latest fzf and fzf zsh key bindings.
On command line, typing ^T launches fzf, but pasting anything ("text", say) into the running fzf session prepends "0~" and appends "1~" to the pasted text ("0~text1~", now).  This obviously causes fzf to fail to find any matching files.
This does not happen when running fzf as normal, when NOT as part of a keybinding.
The old (ruby) version of fzf also worked fine when run as part of a zsh keybinding.
This seems to be independent of terminal (tried xterm and gnome-terminal) and $TERM (tried xterm, xterm-256color, and screen).
I am not running tmux.

**Comment by junegunn** [comment]
It's called brackted paste mode.

https://cirw.in/blog/bracketed-paste

I'll see if it makes sense to ignore those chars in fzf.

**Comment by junegunn** [comment]
Fixed in b8737b7. The change will be included in the next version, which I hope to release in a few days.

**Comment by stephentalley** [comment]
Perfect, thanks!
