### ISSUE TITLE
Toggling/different options for CTRL-R & CTRL-T?

### ISSUE THREAD

**Issue by ahmedelgabri** [junegunn/fzf#596]
- Category
    - [x] fzf binary
    - [x] Neovim
- OS
    - [x] Mac OS X
- Shell
    - [x] zsh

Is there is a way to have different options for <kbd>CTRL</kbd>+<kbd>R</kbd> and <kbd>CTRL</kbd>+<kbd>T</kbd>?

For example I want <kbd>CTRL</kbd>+<kbd>T</kbd> to always show preview `--preview` but I don't want this with <kbd>CTRL</kbd>+<kbd>R</kbd>?

currently this is my options

```zsh
export FZF_DEFAULT_OPTS='--reverse --extended --tabstop=2 --cycle --no-mouse --preview "pygmentize {}" --color light --margin 1'
```

**Comment by junegunn** [comment]
I don't think one should put `--preview` in `FZF_DEFAULT_OPTS` as it only makes sense for a specific type of input. Anyway, I'll add `FZF_CTRL_T_OPTS` and `FZF_ALT_C_OPTS` so you can customize the options.

**Comment by ahmedelgabri** [comment]
Thanks @junegunn

**Comment by ahmedelgabri** [comment]
One last question, will the `--preview` flag work in neovim using `fzf.vim`? because it doesn't work if I do this

```vim
autocmd VimEnter * command! Files
  \ call fzf#vim#files({'options': '--preview "pygmentize -g {}" --color light --bind ?:toggle-preview'})
```

it returns this error 
<img width="418" alt="screen shot 2016-06-12 at 15 40 00" src="https://cloud.githubusercontent.com/assets/63876/15991468/fb793f16-30b3-11e6-8e37-316dd6e90e05.png">

But it works if I have `--preview "pygmentize -g {}" --color light --bind ?:toggle-preview` as part of `FZF_DEFAULT_OPTS`

**Comment by junegunn** [comment]
The first argument to the function is the base directory to start search. The options dictionary should be the second.

**Comment by ahmedelgabri** [comment]
What if I want to keep everything as it is but just use different options? Do I need to duplicate the logic [here](https://github.com/junegunn/fzf.vim/blob/master/autoload/fzf/vim.vim#L190-L204)?

**Comment by junegunn** [comment]
No, the option in the dictionary you pass as the second argument will be appended to the default set of options.

**Comment by junegunn** [comment]
Also note that the default Files command takes an optional directory argument which to me is quite useful, you may not want to lose the functionality. Refer to [the definition of the command](https://github.com/junegunn/fzf.vim/blob/7c58cb98e92c6a324589ebc38ccb5e8594580884/plugin/fzf.vim#L41).

**Comment by ahmedelgabri** [comment]
Thanks for pointing this out. My solution was actually about only passing the `cwd` to `Files` something like this but I think this will break the optional argument.

```vim
autocmd VimEnter * command! Files
  \ call fzf#vim#files(expand('%:p:h'), { 'window': 'aboveleft 20new', 'options': substitute(system("echo $FZF_CTRL_T_OPTS"), '\n\+$', '', '') })

```

**Comment by junegunn** [comment]
If you see the definition of the original command, you'll realize that you only need to pass an empty string (`<q-args>` is empty when no argument is given) to start search from the current directory.

And `substitute(system("echo $FZF_CTRL_T_OPTS"), '\n\+$', '', '')` is a very long version of `$FZF_CTRL_T_OPTS`. Vim knows about env vars.

**Comment by ahmedelgabri** [comment]
Awesome, thanks!

**Comment by ahmedelgabri** [comment]
Everything is working fine except that when I define a custom `Files` command like above the colors are missed up, any idea why? commenting it out returns everything as normal.

```vim
 autocmd VimEnter * command! Files
   \ call fzf#vim#files('', { 'window': 'aboveleft 20new', 'options': $FZF_CTRL_T_OPTS })
```

**Comment by junegunn** [comment]
Hmm, I don't see the problem, please create a separate issue on fzf.vim project with a screenshot of the problem you're experiencing.
