### ISSUE TITLE
Avoid duplicate entry when fzf-ing shell history

### ISSUE THREAD

**Issue by benoittgt** [junegunn/fzf#600]
- Category
    - [X] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- Shell
    - [ ] bash
    - [X] zsh
    - [ ] fish

I would like to know if it's possible to limit the duplication in fzf specially in the shell history command? Or maybe I'm do it it wrong?

![capture d ecran 2016-06-15 a 09 40 39](https://cloud.githubusercontent.com/assets/8417720/16072095/58fe0392-32df-11e6-8f68-3cf9acb4f720.png)

**Comment by junegunn** [comment]
Hi, this is one of the recurring questions. Please see #49, #88, #492. Thanks.

**Comment by benoittgt** [comment]
Thanks @junegunn and sorry for the duplicate

**Comment by edi9999** [comment]
For other people encoutering this issue, here is the changes I've made to remove duplicates : 

```
__fzf_history__() {
  local line
  countskip="$(history | tail -n 1 | grep -E '^[0-9]+' -o | wc -c)"
  countskip="$(( countskip + 1 ))"
  echo "$countskip"
  line=$(
    HISTTIMEFORMAT= history |
    grep '.\{1,79\}' |
    sed 's/ *$//g' |
    tac |
    nauniq --skip-chars="$countskip" |
    tac |
    $(__fzfcmd) +s --tac +m -n2..,.. --tiebreak=index --toggle-sort=ctrl-r |
    \grep '^ *[0-9]') && sed 's/ *\([0-9]*\)\** .*/!\1/' <<< "$line"
}```

It requires nanuniq https://metacpan.org/pod/distribution/App-nauniq/bin/nauniq

**Comment by chew-z** [comment]
`perl -ne 'print if $seen{$_}++'` should do.

**Comment by chew-z** [comment]
`perl -ne 'print if !$seen{$_}++'` should do.

**Comment by GCorbel** [comment]
Using `setopt HIST_IGNORE_ALL_DUPS` on zsh did the trick in my case.

**Comment by benjaminbauer** [comment]
There are rare, desperate, cases, where I appreciate to browse through the history, in order to reconstruct something. 

On ZSH one might use `HIST_FIND_NO_DUPS` to suppress duplicates in the search. Dups still get written to history, as opposed to `HIST_IGNORE_ALL_DUPS`.

**Comment by giladsh1** [comment]
if you're using ZSH, put this in your ~/.zsh file -
```
export HISTFILE=~/.zsh_history
export HISTFILESIZE=1000000000
export HISTSIZE=1000000000
setopt INC_APPEND_HISTORY
export HISTTIMEFORMAT="[%F %T] "
setopt EXTENDED_HISTORY
setopt HIST_FIND_NO_DUPS
setopt HIST_IGNORE_ALL_DUPS
```

Look [here](https://www.soberkoder.com/better-zsh-history/#:~:text=From%20an%20zsh%20mailing%20list,'ll%20probably%20never%20hit) for a better explanation

**Comment by kljensen** [comment]
I wanted the same feature (removing repeated lines after fzf filtering) and wrote this small Rust program to satisfy my need: [semiuniq](https://github.com/kljensen/semiuniq/). I'd appreciate comments and pull requests.
