### ISSUE TITLE
Open file with Vim by specifying line number

### ISSUE THREAD

**Issue by exAspArk** [junegunn/fzf#602]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [x] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

----

Hi,

Is there any chance of making it possible to open files in Vim by specifying line (and maybe column) number?

For example, to suggest `some_spec.rb` file if I type `some_spec.rb:30` and open it in line `30`.

**Comment by junegunn** [comment]
So we have `some_spec.rb` in the list and you type in `smspcrb:30` and enter to match the file and open it in Vim? I don't think it's possible since the moment you type `:30` fzf will no longer match the file. And since fzf is a Unix filter that does not know the context, I can't think of a good way to allow it. I would just type in `30G` after opening the file.

By the way, if you use fzf in Vim, you might also want to checkout [fzf.vim](https://github.com/junegunn/fzf.vim) project.

**Comment by edi9999** [comment]
Or you could add a --bind with `:` to open a new fzf instance that lets you choose the line number

**Comment by romanoaugusto88** [comment]
@edi9999 Did your suggestion work like a charm? Please, tell us more about that.

I achieve the goal doing:

```bash
fzf --bind "enter:accept" --bind "::execute(awk '{print FILENAME\":\"NR}' {} | fzf && killall fzf)"
```

That way I can program a function in the editor to handle this output.

BUT that `killall fzf` is pretty ugly.

Anyone has any idea to get rid of this?
cc: @junegunn

**Comment by junegunn** [comment]
@romanoaugusto88 That looks interesting but I would write a shell function instead of trying to put everything inside `--bind` option.

```sh
#!/bin/bash
ol() {
  local lines file line
  mapfile -t lines < <(fzf --expect : --height 30% --reverse)
  [ ${#lines[@]} -ne 2 ] && return

  file=${lines[1]}
  if [ -z "${lines[0]}" ]; then
    vim "$file"
  else
    read -r -p "$file ($(wc -l "$file" | awk '{print $1}') line(s)): " line
    vim "$file" +$line
  fi
}
```

**Comment by junegunn** [comment]
Alternatively you can combine `abort` action like follows:

```sh
fzf --bind "::execute(awk '{print FILENAME\":\"NR}' {} | fzf)+abort"
```

Note that due to `abort` the exit status of the command is non-zero.
