### ISSUE TITLE
Autocomplete path in querystring

### ISSUE THREAD

**Issue by Ferdev** [junegunn/fzf#604]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [x] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

Hi!
I've adapted the `fe` zsh function to open files in vim even if they don't exist. To do that, I grab the query string entered to find files. Of course, I have to enter the full path in the querystring in order to be able to create the folder hierarchy if it doesn't exist...
I was wondering if there's a way to autocomplete the path in the querystring using tabs or any other key mapping (I've removed `Tab` key map in my setup), as if I were in the shell.

Thanks for the help!

**Comment by junegunn** [comment]
Thanks for the suggestion, but I don't think we should implement auto-completion on fzf. We'll at best end up reinventing a star-shaped wheel that doesn't shine. I would just terminate fzf (`ctrl-c` or `esc` or whatever) and use the proper auto-completion of the shell.

> I have to enter the full path in the querystring in order to be able to create the folder hierarchy if it doesn't exist

fzf is a fuzzy finder where we type in "fuzzy" queries to find the matches. Typing in an accurate file path on fzf doesn't feel like the most straightforward approach.

> To do that, I grab the query string entered to find files.

You're using `--print-query` option, right? I think it would be possible to write a zsh widget, which puts the query string on the command-line, so you can continue with the auto-completion of your shell. There are some options that you might want to take a look at; `--expect`, `print-query` action for `--bind`, etc.
