### ISSUE TITLE
fzf fails to download and install

### ISSUE THREAD

**Issue by janek-warchol** [junegunn/fzf#605]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [x] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

When I try to install from git according to readme, I get an error during `install` script:

```
Downloading bin/fzf ...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (77) error setting certificate verify locations:
  CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
  - Failed to download fzf-0.13.2-linux_amd64 !!!
```

**Comment by junegunn** [comment]
Looks like something's wrong with your installation of curl. The below command is used to download the binary, which for some reason fails on your system.

```sh
curl -fL https://github.com/junegunn/fzf-bin/releases/download/0.13.2/fzf-0.13.2-linux_amd64.tgz | tar -xz
```

I'm sure you'll be able to find the solution after some Googling.
Anyway, can you try this command instead? Does it work?

```sh
wget -O - https://github.com/junegunn/fzf-bin/releases/download/0.13.2/fzf-0.13.2-linux_amd64.tgz | tar -xz
```

**Comment by janek-warchol** [comment]
Yes, wget works.

**Comment by janek-warchol** [comment]
For what it's worth, copying certificates from one directory to another (as described in [this SO question](http://stackoverflow.com/a/30154802/2058424)) fixed curl for me.

**Comment by janek-warchol** [comment]
Thanks!

**Comment by junegunn** [comment]
No problem, thanks.
