### ISSUE TITLE
ZSH with ksh_arrays

### ISSUE THREAD

**Issue by acornejo** [junegunn/fzf#607]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [x] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

By default zsh arrays start at 1, while in ksh, bash and other shells it starts at 0. Zsh provides an option to make arrays behave differently called ksh_arrays, unfortunately if a user enables this option the fzf bindings have conflicts.

The fix is simple, add the `noksh_arrays` localoption inside `fzf-completion()` in `completion.zsh`

**Comment by junegunn** [comment]
Thanks for the heads up. So this is all we need?

```diff
diff --git a/shell/completion.zsh b/shell/completion.zsh
index 60ef3d2..dba025a 100644
--- a/shell/completion.zsh
+++ b/shell/completion.zsh
@@ -136,7 +136,7 @@ _fzf_complete_unalias() {
 
 fzf-completion() {
   local tokens cmd prefix trigger tail fzf matches lbuf d_cmds
-  setopt localoptions noshwordsplit
+  setopt localoptions noshwordsplit noksh_arrays
 
   # http://zsh.sourceforge.net/FAQ/zshfaq03.html
   # http://zsh.sourceforge.net/Doc/Release/Expansion.html#Parameter-Expansion-Flags
```

**Comment by junegunn** [comment]
Fixed, thanks!
