### ISSUE TITLE
Bash Ctrl-r: shortcut to run command

### ISSUE THREAD

**Issue by caneta** [junegunn/fzf#609]
- Category
    - [x] fzf binary
    - [x] Key bindings
    - [x] Completion
- OS
    - [x] Linux
- Shell
    - [x] bash

Using `Ctrl-r` on my Bash I run correctly fzf and hitting `Return` I get the history command selected on my bash prompt. But to run that command I have to hit `Return` again.

So, is there a way to let fzf running directly the command chosen, instead of completing the bash prompt? Maybe with a `Shift+Return` or something?

**Comment by edi9999** [comment]
Duplicate of https://github.com/junegunn/fzf/issues/477

**Comment by caneta** [comment]
Ok, at least I'm not alone requasting that! :-D

**Comment by junegunn** [comment]
Right, see https://github.com/junegunn/fzf/issues/477#issuecomment-230338992
