### ISSUE TITLE
[zsh] Completion functions expand aliases / call user-defined functions

### ISSUE THREAD

**Issue by eigengrau** [junegunn/fzf#611]
`completion.zsh` is currently meant to be sourced (since it sets up a keybinding). However, this will cause aliases to be expanded inside functions defined therein. E.g., `rm` might be aliased to always query, or to refuse deletion. Generally, shell library code should ignore aliases to ensure the desired effects apply.

I’m not sure how this could be achieved best. Disabling alias expansion temporarily and re-enabling it would be a hassle. As would be prefixing each external command with the `command` premodifier.

My guess is that the best practice here is to define things so they can be autoloaded, since Zsh has `autoload -U`, which inhibits alias expansion and is generally used when enabling library code.

**Comment by eigengrau** [comment]
Making the completion widget an autoloaded function wasn’t too hard. Though I’m not so sure now if this is the best way. While it does inhibit alias expansion, for things like `rm`, it’s just as likely that the user redefined them using functions (for argument parsing). However, what I’ve seen a bunch of times is that one hardcodes the absolute path when external commands are used. Maybe that’s a better way?

**Comment by eigengrau** [comment]
Silly me. I just now realized you were already escaping some external commands in the script so as not to expand aliases. It’s just that some instances aren’t escaped yet, and sadly this won’t stop triggering user-defined functions.

**Comment by junegunn** [comment]
Thanks.

> It’s just that some instances aren’t escaped yet

Yeah, we should fix them, should I just go ahead? Let me know if you have better ideas. The `autoload` thing you suggested, I'm not really familiar with the concept (I'm a bash user). Please note that I'm not looking for significant changes to the shell stuff at this stage. The code basically serves as a reference implementation, and it's meant to be forked/customized to different needs.

**Comment by eigengrau** [comment]
> Yeah, we should fix them, should I just go ahead? Let me know if you have better ideas.

Yeah, go ahead as you see fit. Autoloading isn’t a better option, since it doesn’t inhibit function calls either. However, if you don’t find it too ugly, you might want to write `command find` instead of `\find`. This will inhibit both alias expansion *and* shell function lookup. Maybe Zsh has some magics too solve this problem in a nicer-looking way, but unfortunately I couldn’t find them.

Anyway, thanks for making fzf!

**Comment by junegunn** [comment]
> you might want to write command find instead of \find. This will inhibit both alias expansion and shell function lookup

Good point, I wasn't aware of it. I will do it later in the day.

**Comment by junegunn** [comment]
Updated the code. Some commands like sed are still used without `command` prefix, but those are the commands that I don't think we should worry too much about.
