### ISSUE TITLE
fsel:setopt:5: no such option: pipefail

### ISSUE THREAD

**Issue by githubfun** [junegunn/fzf#615]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

when I ctrl-t I get 

> __fsel:setopt:5: no such option: pipefail

but it doesn't seem to affect usage.

**Comment by junegunn** [comment]
What is your `zsh --version`?

**Comment by githubfun** [comment]
it is the default zsh on centos 7. Now I realize it might be too old. 
```
 zsh --version
zsh 5.0.2 (x86_64-redhat-linux-gnu)
```

**Comment by junegunn** [comment]
Yeah, I can reproduce the problem on 5.0.2. I'll see if there's an easy workaround when I get some time.

**Comment by vexelenn** [comment]
I have the same version of zsh and following error: `fzf-history-widget:setopt:2: no such option: pipefail`

**Comment by junegunn** [comment]
`pipefail` was introduced in #601, but it's fine to ignore the error. I'll update the code shortly.

/cc @blueyed
