### ISSUE TITLE
Invalid fzf binary for Mac OS 10.7.5

### ISSUE THREAD

**Issue by srasku** [junegunn/fzf#617]
- Category
    - [ x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [x ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ x] bash
    - [ ] zsh
    - [ ] fish

This problem occurs for commit 6081eac58a0c1fe7cf920dc41d7d6ec07293b0ee

 $ ~/.fzf/install 
Downloading bin/fzf ...
  - Creating symlink: bin/fzf-0.13.2-darwin_amd64 -> bin/fzf
  - Checking fzf executable ... Error: 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   604    0   604    0     0   1315      0 --:--:-- --:--:-- --:--:--  1363
100  913k  100  913k    0     0   262k      0  0:00:03  0:00:03 --:--:--  427k
  - Creating symlink: bin/fzf-0.13.2-darwin_amd64 -> bin/fzf
  - Checking fzf executable ... Error: 
  - Invalid binary !!!

$ ~/.fzf/bin/fzf-0.13.2-darwin_amd64
Illegal instruction: 4

$ uname -a
Darwin picard.local 11.4.2 Darwin Kernel Version 11.4.2: Thu Aug 23 16:25:48 PDT 2012; root:xnu-1699.32.7~1/RELEASE_X86_64 x86_64

**Comment by junegunn** [comment]
Can you build the binary with `go get -u github.com/junegunn/fzf/src/fzf` on Lion? If that's possible, I'll update the install script to try building it if the downloaded binary does not work on the system.
