### ISSUE TITLE
fzf-tmux(0.12.2) not work on mac os x 

### ISSUE THREAD

**Issue by wa9035148** [junegunn/fzf#618]
- Category
    - [ ] fzf binary
    - [*] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [*] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [*] bash
    - [ ] zsh
    - [ ] fish

tmux version 2.1
fzf 0.12.1 (installed by brew)
When input /usr/local/bin/fzf-tmux nothing happened.

I also tried fzf 0.13.2 , it works well.

**Comment by junegunn** [comment]
I primarily use OS X, and I'm pretty certain that I had no issue when I released 0.12.1. But anyway, since you said 0.13.2 works fine, it's time for `brew update && brew reinstall fzf`.

https://github.com/Homebrew/homebrew-core/blob/master/Formula/fzf.rb#L6
