### ISSUE TITLE
No spinner shown when --inline-info is used

### ISSUE THREAD

**Issue by chdiza** [junegunn/fzf#619]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

When `--inline-info` is passed, no spinner is shown.  I'm not sure if this is a bug, or intentional, or whether it's too expensive to keep redrawing a spinner on the same line as the query input.

**Comment by junegunn** [comment]
It's intentional. But if you look closely, the color of `<` after the query changes when the input stream is closed. e.g. `sleep 1 | fzf --inline-info`
