### ISSUE TITLE
Fuzzy find for directories

### ISSUE THREAD

**Issue by jceb** [junegunn/fzf#62]
It would be awesome if fzf would be able to fuzzy find directories as well by providing an additional option on the command line.  I'd use it to quickly navigate to a subdirectory.

**Comment by timothyylim** [comment]
Firstly, thanks so much for this bit of code.

Is there a different option for mac? 

When I press ```ALT-C``` I get ```ç```

**Comment by junegunn** [comment]
@timothyylim If you use iterm2, take a look at https://www.iterm2.com/faq.html

```
Q: How do I make the option/alt key act like Meta or send escape codes?

A: Go to Preferences->Profiles tab. Select your profile on the left, and then open the Keyboard tab. At the bottom is a set of buttons that lets you select the behavior of the Option key. For most users, Esc+ will be the best choice.
```

**Comment by timothyylim** [comment]
You are a boss.
