### ISSUE TITLE
Error on running :FZF in vim

### ISSUE THREAD

**Issue by faruzzy** [junegunn/fzf#620]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [x] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

Sorry if I missed a piece of information, this is the first time I submit an issue..
I get the following error when running :FZF in vim
![image](https://cloud.githubusercontent.com/assets/766723/16785271/05ba8a02-4842-11e6-85cd-3706ac23e000.png)

**Comment by junegunn** [comment]
The code failed to handle multi-line FZF_DEFAULT_COMMAND. Should be fixed now though I'll see if there's a better way to handle this. Thanks for the report.

**Comment by faruzzy** [comment]
Thanks for looking into this!
