### ISSUE TITLE
Selections are not added to prompt after hitting enter.

### ISSUE THREAD

**Issue by domi91c** [junegunn/fzf#621]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [x] Key bindings
    - [x] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

Using `kill -9`, for example, after I've selected the commands I want from `fzf` by htting tab on each, when I hit enter, my terminal responds with a bell and `fzf` closes without outputting any of my selections. Is it enter that I should be pressing, or is it a different key that closes fzf and inputs my selections?

**Comment by junegunn** [comment]
It should work. I'm not sure what's going on. Can you share the recording of the situation using https://asciinema.org/ ?

**Comment by domi91c** [comment]
Sorry, I didn't run `/usr/local/opt/fzf/install`. It's working fine now, you can close this.
