### ISSUE TITLE
Window height is incorrect with --header option

### ISSUE THREAD

**Issue by mrbiggfoot** [junegunn/fzf#622]
I have a simple function:
```
function! TagSelectWindow(tag)
        let l:taglist = map(taglist('^' . a:tag . '$'),
                \'v:val["kind"] . " " . " " .v:val["filename"] . "\t" . v:val["cmd"]')
        call fzf#run({ 'source' : l:taglist, 'sink' : function('TagSelect'),
                \'down' : '~40%', 'options' : '--reverse --bind=tab:down --header=' .
                \ a:tag })
endfunction
```

When I call it on a tag that has 3 matches, the window looks like this:
```
~/projects/main/test/file.cc                                                                                                                            64,13          27%
>
  3/3
  CloseSessionAndTerminateProcess
> f  /home/xxx/projects/main/zeus/zeus.cc    /^void Zeus::CloseSessionAndTerminateProcess(int64 session_handle) {$/
  p  /home/xxx/projects/main/zeus/zeus.h     /^  static void CloseSessionAndTerminateProcess(int64 session_handle);$/
 > fzf
```
The third match is pushed out of the window because of the header line.

- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [x] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

**Comment by junegunn** [comment]
You can scroll past the screen boundary. In `3/3`, the first 3 is the number of matches - since the query is empty all lines match - and the second 3 is the total number of lines. Likewise, `seq 100000 | fzf` will display `100000/100000`. Maybe you want to increase the height of the split by increasing the value of `down` property?

**Comment by mrbiggfoot** [comment]
@junegunn I understand that I can scroll down. The thing is - even if I set "down" to "~90%", nothing changes. What happens is - the window height is automatically calculated based on the number of matches. But the calculated window height does not take the "--header" line into account, so the last match gets pushed out of the window no matter what "~X%" is set in "down". The auto-calculated window height should be incremented by 1 if "--header" is specified (but stay within the "~X%" bounds of course).

**Comment by mrbiggfoot** [comment]
In other words - on small number of matches, where all of them can fit in the window, one last match is not shown because of the header line.

**Comment by junegunn** [comment]
Oh I see. Technically, header string can contains any number of new line characters so just incrementing the height by 1 is not enough, but I don't think we can/should implement proper option parser in the Vimscript, so it's probably the most practical solution. (e.g. Without a proper parser, it can be easily tricked by something like `--query "--header foo"`)

**Comment by junegunn** [comment]
Fixed it. Tested with:

```vim
call fzf#run({'source': [1,2,3], 'down': '~50%', 'options': '--header foo'})
call fzf#run({'source': [1,2,3], 'down': '~50%', 'options': '--header foo --inline-info'})
call fzf#run({'source': [1,2,3], 'down': '~50%', 'options': '--header foo --no-header'})
```

Thanks for the report.

**Comment by mrbiggfoot** [comment]
Thanks @junegunn, your work is much appreciated!
