### ISSUE TITLE
Typo in wiki/example "Searching file contents" section

### ISSUE THREAD

**Issue by good5dog5** [junegunn/fzf#623]
- Category
    - [ ] fzf binary
    - [*] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [*] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [*] bash
    - [ ] zsh
    - [ ] fish

https://github.com/junegunn/fzf/wiki/Examples

My ag version is 0.19.2, it's does not have option name `--nonumbers`
should it be `--no-numbers`?

**Comment by junegunn** [comment]
Hi, in the latest version `--nonumbers` is the correct name. See: https://github.com/ggreer/the_silver_searcher/commit/528b2669c53896b59efcea8d6242ce9f4de4b8cf

You might want to upgrade your ag, it's two years behind. And FYI, the write permission to the wiki page is open to public and I don't audit the snippets users post there. So maybe there can be some broken examples. Feel free to ping me if you find any errors, thanks!
