### ISSUE TITLE
Vim plugin should respect the $FZF_TMUX env var

### ISSUE THREAD

**Issue by jasonmay** [junegunn/fzf#625]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [x] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

**Comment by junegunn** [comment]
Hi, `FZF!` (bang version) will open fzf in fullscreen. You might want to try out [fzf.vim project](https://github.com/junegunn/fzf.vim) which understands `g:fzf_layout` which is much more flexible than `FZF_TMUX` and `FZF_TMUX_HEIGHT`.

**Comment by junegunn** [comment]
Maybe it's time I should bring some good stuff from fzf.vim. I'll let you know if things change.
