### ISSUE TITLE
spaces in FZF_COMPLETION_TRIGGER do not trigger completion.

### ISSUE THREAD

**Issue by jedahan** [junegunn/fzf#628]
- Category
  - [x] Completion
- OS
  - [x] Mac OS X
- Shell
  - [x] zsh

`export FZF_COMPLETION_TRIGGER='  '` does not work. I would like to just be able to double-space, then <tab>, and get completion.

**Comment by junegunn** [comment]
It's currently not supported. The code was not written with such triggers in mind. I can imagine we can extend zsh completion to support it, but it may not be possible for bash. For now, you can try a different approach: https://github.com/junegunn/fzf/wiki/Fuzzy-completion
