### ISSUE TITLE
Slow to close on neovim

### ISSUE THREAD

**Issue by kassio** [junegunn/fzf#632]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [X] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [X] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [X] zsh
    - [ ] fish

Hi! First of all, thank you for the awesome project! 

I tried just the `fzf`, and tried it together with `fzf.vim`, but both ways it take too long to close on neovim(OSX, zsh).

**Comment by junegunn** [comment]
You're most likely running into this issue: https://github.com/neovim/neovim/issues/4487

Try the workaround suggested in the link (`let g:airline#extensions#branch#enabled = 0`) and see if it helps.

**Comment by justinmk** [comment]
It's possible this is fixed on Neovim master. What version are you using?

**Comment by kassio** [comment]
@justinmk still slow on:
```
$ nvim -v
NVIM v0.1.5-321-gba70504
Build type: Dev
```

**Comment by kassio** [comment]
@junegunn the workaround seems to improve a little bit, but still way slow compared with vim.

**Comment by kassio** [comment]
I added this:
```viml
if has('nvim')
  aug fzf_setup
    au!
    au TermOpen term://*FZF tnoremap <silent> <buffer> <esc><esc> <c-c>
  aug END
end
```
And with a double `<esc>` it close as fast as in vim.

**Comment by justinmk** [comment]
That just means your `ttimeoutlen` is too long. Try `set ttimeoutlen=10`.

**Comment by kassio** [comment]
my `ttimeoutlen` is `-1`. But I tried set it to `10` and didn't change the result. 😢

**Comment by justinmk** [comment]
What does `:tmap <esc>` say?

**Comment by kassio** [comment]
Good point! It's: `<Esc><Esc>  * <C-\><C-N>`

**Comment by justinmk** [comment]
And you are trying to close with a single `<Esc>`? Then nvim waits N seconds for the mapping to complete. 

You could do this instead:

```vim
if has('nvim')
  aug fzf_setup
    au!
    au TermOpen term://*FZF tnoremap <silent> <buffer><nowait> <esc> <c-c>
  aug END
end
```

The `<nowait>` means this mapping will not wait.

**Comment by kassio** [comment]
@justinmk great TIL! Thank you for the help!
