### ISSUE TITLE
key bindings no effect

### ISSUE THREAD

**Issue by gatspy** [junegunn/fzf#633]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [x] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

hi, `source ~/.fzf.zsh` must added into `.zshrc` file?
 i added this in `.zshrc.local`. but key bindings no effect.

**Comment by junegunn** [comment]
Unless the key bindings are reset in your configuration file, the location/position shouldn't matter. Check the output of `bindkey | grep fzf`.

**Comment by yevhen-m** [comment]
I have them all
```
$ bindkey | grep fzf
"^G^B" fzf-gb-widget
"^G^F" fzf-gf-widget
"^G^H" fzf-gh-widget
"^G^R" fzf-gr-widget
"^G^T" fzf-gt-widget
"^I" fzf-completion
"^R" fzf-history-widget
"^T" fzf-file-widget
"^[c" fzf-cd-widget
```
but bindings for git do nothing.

**Comment by yevhen-m** [comment]
Update.
Conflicted with zshell `git` plugin. After I removed it, everything works smooth.

**Comment by vaxXxa** [comment]
If you mean that – https://gist.github.com/junegunn/8b572b8d4b5eddd8b85e5f4d40f17236
So, these keybinds works for my zsh only after I turn off `git` plugin from `oh-my-zsh`.

**Comment by junegunn** [comment]
@yevhen-m You got the "bindings for git" from [this post](http://junegunn.kr/2016/07/fzf-git/), right? They are not from this repository.

**Comment by yevhen-m** [comment]
@junegunn that's right.
