### ISSUE TITLE
can't find dot files?

### ISSUE THREAD

**Issue by NgaNguyenDuy** [junegunn/fzf#634]
- Category
    - [x] fzf binary
    - [x] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

I can't find any dot files as .vimrc, .bashrc. Is it supported?

![2016-08-06-175459_1920x1080_scrot](https://cloud.githubusercontent.com/assets/1486790/17456372/c85f2a4c-5bff-11e6-90d9-06886059153d.png)

**Comment by junegunn** [comment]
The default commands fzf uses do not include file. If you want hidden files in the list, you have to define your own `$FZF_DEFAULT_COMMAND` or `$FZF_CTRL_T_COMMAND` depending on the context.

For example:

```sh
export FZF_DEFAULT_COMMAND='ag --hidden --ignore .git -g ""'
```

**Comment by nimamo** [comment]
When I try `export FZF_DEFAULT_COMMAND='ag --hidden --ignore .git -g ""'` fzf stops working in bash shell and lists no files at all (not only dot files, but nothing at all) but it works as expected in vim. I modified the default command and tried `export FZF_DEFAULT_COMMAND="find . -path '*/\.*' -type d -prune -o -type f -print -o -type l -print 2> /dev/null | sed s/^..//"` and fzf worked as expected both in bash and in vim. I guess this is related to how `ag` generates its output?

**Comment by junegunn** [comment]
@nimamo Have you checked the command itself (`ag --hidden --ignore .git -g ""`) work in bash?

**Comment by nimamo** [comment]
@junegunn Yes and it works as expected.

**Comment by junegunn** [comment]
@nimamo How about `ag --hidden --ignore .git -g "" | cat`? If it fails, upgrade ag.

**Comment by nimamo** [comment]
@junegunn This command works. I tried the same procedure ( `export FZF_DEFAULT_COMMAND='ag --hidden --ignore .git -g ""'` ) on a different Linux installation and it just worked fine. This doesn't seem to be a bug in fzf, yet seeing different results from `fzf` in bash and `:FZF` in Vim is worth noticing.

**Comment by junegunn** [comment]
@nimamo Please make sure you have the latest version of ag installed. Probably related: #573

**Comment by rikhuijzer** [comment]
The command to be used with ripgrep is
```
rg --hidden --no-ignore -l ""'
```

**Comment by junegunn** [comment]
See if `$SHELL -c 'ag --hidden --ignore .git -g ""'` works on you shell because that's what fzf does.

**Comment by Espylapiza** [comment]
A faster command for ripgrep is
```
export FZF_DEFAULT_COMMAND='rg --hidden --no-ignore --files'
```
which does not search the content of files.

**Comment by Mel28vin** [comment]
export FZF_DEFAULT_COMMAND='rg --files --follow --no-ignore-vcs --hidden -g "!{node_modules/*,.git/*}"'

**Comment by Mel28vin** [comment]
export FZF_DEFAULT_COMMAND='rg --files --follow --no-ignore-vcs --hidden -g "!{node_modules/*,.git/*}"'

This works for me!

**Comment by David-Else** [comment]
@junegunn I would like to include dot files and exclude `./.git` without adding another command line dependency. It seems by default fzf excludes the `.git` folder, I came up with:
```
export FZF_DEFAULT_COMMAND='find . -path './.git' -prune -o -print'
```
But I am not sure I am getting the original behaviour. Can you advise what to add to my `.bashrc` to keep the original behaviour and include dot files. Bonus would be to exclude `node_modules` :). Cheers!

**Comment by dharmaturtle** [comment]
Tweaking Mel28vin's command so it ignores node_module and .git sub-directories:

```sh
export FZF_DEFAULT_COMMAND="rg --files --follow --no-ignore-vcs --hidden -g '!{**/node_modules/*,**/.git/*}'"
```

Relevant ripgrep [thread](https://github.com/BurntSushi/ripgrep/issues/839).
