### ISSUE TITLE
Inverse of :hidden in --preview (maybe :visible) ?

### ISSUE THREAD

**Issue by edi9999** [junegunn/fzf#636]
In my bashrc , I do : 

`FZF_DEFAULT_OPTS="--bind '?:toggle-preview' --preview 'less <<< {}' --preview-window 'up:50%:hidden"`

(and others, since I find that I don't use preview-window that often, but might want to use it sometimes).

However, after sourcing this, I would like to force fzf to show the preview-window by default. 

So I do: 

`fzf --preview-window 'right:70%'` but the first hidden property is ignored (eg the preview window is hidden by default).

They are imo two ways of fixing this : 

1. The explicit way  : `fzf --preview-window 'right:70%:visible'` will override a previous hidden (but if no hidden nor visible is given, the preview-window is visible)
2. The implicit way : `fzf --preview-window 'right:70%'` should completely remove a previous :hidden property.

In this particular case, I'm not sure which way I prefer.

**Comment by edi9999** [comment]
Here's a patch if you decide for "2."

```
diff --git a/src/options.go b/src/options.go
index 2a72427..31ad497 100644
--- a/src/options.go
+++ b/src/options.go
@@ -724,6 +724,7 @@ func parseSize(str string, maxPercent float64, label string) sizeSpec {
 
 func parsePreviewWindow(opts *previewOpts, input string) {
 	layout := input
+	opts.hidden = false
 	if strings.HasSuffix(layout, ":hidden") {
 		opts.hidden = true
 		layout = strings.TrimSuffix(layout, ":hidden")
```

**Comment by junegunn** [comment]
Thanks for the report. Lingering hidden property is not what I intended, it's just a bug. I'll apply your patch.

**Comment by edi9999** [comment]
Ok, thanks !

**Comment by kljensen** [comment]
In case other people end up here, when you have a default option of `:hidden` for the `preview-window`, you can override that with `:nohidden` but not `:right`, `:left` or similar.
