### ISSUE TITLE
fzf process execution

### ISSUE THREAD

**Issue by dufferzafar** [junegunn/fzf#639]
I have a few doubts and suggestions related to how the `--bind execute` works:

* Do subshells work? I want do something like `fzf --bind "enter:execute(xdg-open $(dirname {}))"`

* fzf tries to run the process from the current shell so when the process is executed fzf window hides and waits for the process to close. Can this be overridden somehow? I want the process to just launch and not affect fzf.

- Category
    - [x] fzf binary
    - [x] fzf-tmux script
    - [x] Key bindings
- OS
    - [x] Linux
- Shell
    - [x] zsh

**Comment by junegunn** [comment]
Did you try appending `&` to the command? e.g. `fzf --bind 'enter:execute(sleep 100 &)'`

**Comment by dufferzafar** [comment]
That does work for the background part, but what about the subshell thing? 

This works: fzf --bind "enter:execute(xdg-open {})"
but this doesn't: fzf --bind "enter:execute(xdg-open $(dirname {}))"

**Comment by junegunn** [comment]
Use single-quotes around it. $(...) is expanded before it's passed to fzf.

**Comment by dufferzafar** [comment]
Oh. Thanks. That worked!

`fzf --bind 'enter:execute(xdg-open "$(dirname {})")'`
