### ISSUE TITLE
PowerShell bindings

### ISSUE THREAD

**Issue by tomfitzhenry** [junegunn/fzf#640]
I've started using PowerShell, but am missing fzf. It'd be great to have PowerShell hooked up to fzf. In particular, ctrl-r.

**Comment by tomfitzhenry** [comment]
My attempt so far:
```
Set-PSReadlineKeyHandler -Key Ctrl+r `
    -ScriptBlock {
        $fzf=cat $HOME/.history | fzf +s -m --tiebreak=index --toggle-sort=ctrl-r
        #[Microsoft.PowerShell.PSConsoleReadLine]::Insert($fzf)
    }
```

Problems:
1. `$HOME/.history` isn't where PowerShell stores its history
2. When I hit Ctrl-r, fzf is executing (according to `ps`), but I cannot see the curses interface. I wonder if this is a limitation of PowerShell's PSReadline?

**Comment by balta2ar** [comment]
This https://github.com/junegunn/fzf/blob/master/src/README.md#system-requirements says Windows is not supported.

**Comment by tomfitzhenry** [comment]
I'm using PowerShell on OSX, sorry, I should have mentioned.

OSX 10.11.6
fzf 0.13.2

**Comment by junegunn** [comment]
@balta2ar Turned out that fzf can now work on Windows with its new linux subsystem. See https://github.com/junegunn/fzf.vim/issues/186

@tomfitzhenry Hi, unfortunately I have zero experience in PowerShell, so I can't really help you with this. Please let me know if you find the solution.

**Comment by prabirshrestha** [comment]
Seems like this is now supported by https://github.com/kelleyma49/PSFzf

**Comment by junegunn** [comment]
@prabirshrestha Thanks. I'll mention the project somewhere on the wiki.
