### ISSUE TITLE
[WIKI] ftags gives permission denied and :Tags does not display the file, the tag belongs to.

### ISSUE THREAD

**Issue by sreeram-boyapati** [junegunn/fzf#641]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [x] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

I am using the following scripts from wiki. ftags for tmux and :Tags for neovim.
Issue with :Tags

1. It's really fast but it does not display the corresponding filepath for the tag

**Comment by junegunn** [comment]
- I don't see why you're getting permission denied.
- The wiki page is for showcasing how one can build things with fzf, and I'd like to keep the examples simple without too much sophistication. You might want to try out `:Tags` command provided by [fzf.vim project](https://github.com/junegunn/fzf.vim).
