### ISSUE TITLE
Question: how to abort and send typed characters to stdout

### ISSUE THREAD

**Issue by QiangF** [junegunn/fzf#644]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [x] Key bindings
    - [x] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

I have a bash function that displays cheat sheet for all matching files for partial file names in my cheat sheets dir. Fzf helps to find the cheat, but to view the documentation, completed file names doesn't work.

**Comment by junegunn** [comment]
I'm not sure if I follow you, can you share your script? Preferably with some screenshots. Anyway you can bind `print-query` action to a key like so:

```sh
fzf --bind 'enter:print-query'
```

**Comment by QiangF** [comment]
Thank you for the tip! 
The link to the cheats script I am using
is (https://github.com/lucaswerkmeister/cheats). By default if
you type a cheat command, like "cheat chown", it will list all
available cheats begin with that string, if you have two
cheats: "chown a","chown b", then it will print the doc string of
all matching cheats. I think fzf can be used to show the
matching cheats dynamically and I want the ability to view the
doc string if I want.

**Comment by junegunn** [comment]
I see, you might also want to check out `--preview` option in that case.

```sh
(cd ~/.cheats; fzf --reverse --preview 'cat < {}')
```
