### ISSUE TITLE
works on AIX  or Sparc ?

### ISSUE THREAD

**Issue by sivaswami** [junegunn/fzf#647]
- Category
  - [ x] fzf binary
  - [ ] fzf-tmux script
  - [ ] Key bindings
  - [ ] Completion
  - [ ] Vim
  - [ ] Neovim
  - [ ] Etc.
- OS
  - [ ] Linux
  - [ ] Mac OS X
  - [ ] Windows
  - [ x] Etc.
- Shell
  - [ ] bash
  - [ ] zsh
  - [ ] fish

line 112: /home/myhome/.fzf/bin/fzf: cannot execute binary file

**Comment by junegunn** [comment]
I have no experience on that platform. What does `uname -a` say? And can you try setting up Go development environment and building fzf from source? i.e. `go get -u github.com/junegunn/fzf/src/fzf`
