### ISSUE TITLE
fzf doens't showing up.

### ISSUE THREAD

**Issue by febrianrendak** [junegunn/fzf#648]
- Category
    - [ ] fzf binary
    - [x] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

Latest version doesn't work for me if I set tmux with -L option, ex: tmux -L tmux-test-session, when I press ctrl+r, fzf doens't showing up. Fzf working fine without -L option.

any help?

**Comment by junegunn** [comment]
Thanks for the report. This was caused by #646 which I just reverted. Please update and let me know how it goes.

**Comment by febrianrendak** [comment]
Thanks, working like charm.

**Comment by junegunn** [comment]
Sorry for the trouble. Thanks.
