### ISSUE TITLE
FZF --preview does not work with ccat

### ISSUE THREAD

**Issue by aliev** [junegunn/fzf#649]
- Category
    - [ x ] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ x ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [ x ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ x ] zsh
    - [ ] fish

Trying to use [ccat](https://github.com/jingweno/ccat) instead of coderew, highlighting does not work. My options example:

```
  let g:fzf_files_options =
      \ '--preview "(ccat {}) 2> /dev/null | head -'.&lines.'"'
```

**Comment by junegunn** [comment]
Try `--color=always` option. Without the option, ccat will not print ANSI color codes when stdout is not a tty device.

**Comment by aliev** [comment]
@junegunn thank you it works!
