### ISSUE TITLE
FZF_DEFAULT_COMMAND ignored in fzf-tmux?

### ISSUE THREAD

**Issue by xoliver** [junegunn/fzf#650]
- Category
    - [ ] fzf binary
    - [x] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

Steps to repro:
1. Have a folder `test` with a `.gitignore` claiming to ignore folders `build and .tox`
2. Have `FZF_DEFAULT_COMMAND` be `ag -g ""` so that `.gitignore` is considered
3. `ag -g ""` works: n folder `test`, `ag -g "" | fzf` ignores `build` and `.tox`. Same if called from another folder.
4. Problems:
  * Press `Ctrl+T` -> tmux split contains `build` but not `.tox`
  * Do `vim **<TAB><TAB>` -> tmux split contains `build` and `.tox`

Confusion

Thank you for such an amazing tool!

**Comment by junegunn** [comment]
For various reasons, CTRL-T and fuzzy completion require separate configuration.

- Set up `$FZF_CTRL_T_COMMAND` for CTRL-T
- See https://github.com/junegunn/fzf#settings for customizing fuzzy completion

**Comment by xoliver** [comment]
That works perfectly, and I should have spotted that in the README, my bad. Thanks for the reply!
