### ISSUE TITLE
[bash] vi-mode prohibits c+r and a+c bindings

### ISSUE THREAD

**Issue by laur89** [junegunn/fzf#655]
- OS
    - Linux (debian testing)
- Shell
    - bash [4.3.46(1)-release (x86_64-pc-linux-gnu)]
- fzf ver `1c81a58`

Setting shell to vi mode prohibits `C+R` & `A+C` bindings to execute; instead, this is in command line:

    `__fzf_history__`

Only when `enter` is pressed, then fzf launches as expected. Note that `C+T` expands immediately.

Reproduce:
- add `set editing-mode vi` to ~/.inputrc

Edit: I read everything, but it just now clicked:

> If you use vi mode on bash, you need to add set -o vi before source ~/.fzf.bash in your .bashrc, so that it correctly sets up key bindings for vi mode.

So this option probably can't be set via `.inputrc`, correct?

**Comment by laur89** [comment]
Yup, can't set vi mode in .inputrc either.

**Comment by junegunn** [comment]
We haven't found a nice solution to this; see #39.

**Comment by laur89** [comment]
Nah, it's not too bad requirement to simply add the option to bashrc before fzf is sourced. I simply didn't connect the dots that the caveat applied to vimrc as well. Perhaps mention it in the readme?
