### ISSUE TITLE
+m option is missing from the man-pages

### ISSUE THREAD

**Issue by laur89** [junegunn/fzf#658]
What does it do?

**Comment by junegunn** [comment]
`+` prefix is the convention used to represent the opposite of an option. So `+m` is the opposite of `-m` (or `--multi`) and can also be written as `--no-multi`. The same goes for `+e`, `+x`, and `+i`.

Although I skipped to mention in the manpage, every long option has `--no-xxx` counterpart that negates the option.

`-m` is not enabled by default so you probably don't need to use `+m` ever. The only reason I used `+m` in some scripts is to make sure to turn `-m` off in case it's enabled in `FZF_DEFAULT_OPTS`.

**Comment by laur89** [comment]
Wasn't aware of this convention. TIL.
