### ISSUE TITLE
Up down scrolling not working on Windows 10 built-in bash

### ISSUE THREAD

**Issue by ldzhjn** [junegunn/fzf#661]
Like the title says, the up down scrolling is not working.
When I press Ctrl+R to call out fzf, I cant select commands using up and down keys.
Fzf will exit and show "[A" on the shell for "up" key and "[B" for down key.

**Comment by junegunn** [comment]
I haven't had a chance to try WSL yet. Maybe the terminal emulator is sending difference character sequences on arrow keys. I'll take a look at it when I get a chance. Until then, you can use CTRL-J/K or CTRL-N/P combos instead.

**Comment by jrock2004** [comment]
The work around works. Hope you get some time to investigate

**Comment by junegunn** [comment]
Have you tried it? It should be fixed now.

**Comment by jrock2004** [comment]
I can use ctrl j/k only

**Comment by junegunn** [comment]
Even with the latest version? I myself confirmed that the issue was
resolved in 0.15.6.

- junegunn

2016. 11. 9. 오후 11:59에 "John Costanzo" <notifications@github.com>님이 작성:

**Comment by jrock2004** [comment]
You are right. It works, but sometimes when I press up It will type an A or if I press down it types a B. Should I open a new issue for this?

**Comment by junegunn** [comment]
Hmm, I thought 100ms delay was enough, and I was no longer able to reproduce the problem after applying the delay. You might want to experiment with different values of `retries` that I added in d206949f6258db36060af3e84fdae15cb7b9a45c. FYI, I tested on ConEmu.

**Comment by jrock2004** [comment]
Or I just need to slow down. lol

**Comment by junegunn** [comment]
Hmm, I'm seeing the same issue. Unfortunately I haven't found a proper fix to the problem. One thing to note is that the problem is not reproducible if you're on tmux.

**Comment by junegunn** [comment]
The problem will be properly fixed in 0.15.8.

https://github.com/junegunn/fzf/commit/8c661d4e8c8a4b643155aa46481ac92f6ebf75b9
