### ISSUE TITLE
NodeJS repl support?

### ISSUE THREAD

**Issue by aleclarson** [junegunn/fzf#662]
Is there an easy way to configure `fzf` to work inside the NodeJS repl? (or even the coffee-script repl?)

**Comment by junegunn** [comment]
I'm not a node.js guy, so I haven't tried it, but I did that with Ruby and Clojure REPL, so I suppose it should be possible in a similar way. See http://junegunn.kr/2016/02/using-fzf-in-your-program/

**Comment by kswilster** [comment]
here's how I interact with `fzf` in node
```js
var spawn = require('child_process').spawn;
var entries = ['things', 'I', 'want', 'to', 'search'].join('\n');

var fzf = spawn(`echo "${entries}" | fzf`, {
  stdio: ['inherit', 'pipe', 'inherit'],
  shell: true
});

fzf.stdout.setEncoding('utf-8');

fzf.stdout.on('readable', function() {
  var value = fzf.stdout.read();

  if (value !== null) {
    console.log(value);
  }
});
```

**Comment by junegunn** [comment]
@kswilster Thanks!
