### ISSUE TITLE
Can I use fzf to achieve specific auto-completion in Bash?

### ISSUE THREAD

**Issue by orschiro** [junegunn/fzf#664]
Dear all, 

I must admit that I not fully understand your documentation. 

Thus please bear with me that I am asking my question here. 

Originally I am coming from [this conversation on AskUbuntu](http://askubuntu.com/questions/825625/how-can-i-extend-the-tab-key-auto-completion-in-the-terminal-to-text-in-the-midd). 

There I was recommended to take a look at [this](http://superuser.com/questions/561451/is-there-a-shell-which-supports-fuzzy-completion-as-in-sublime-text/607338#607338) conversation which mentions fzf as a potential solution to my original question. 

Thus I would like to re-ask:

Can I use fzf to achieve the type of auto-completion originally asked on AskUbuntu in Bash?

Thankfully,

-Robert

**Comment by junegunn** [comment]
Can you clarify which part of the documentation you don't understand?

- https://github.com/junegunn/fzf#fuzzy-completion-for-bash-and-zsh
- https://github.com/junegunn/fzf/wiki/Examples-(completion)

> Can I use fzf to achieve the type of auto-completion originally asked on AskUbuntu in Bash?

I believe so, but you might want to try out [the solution](http://superuser.com/questions/561451/is-there-a-shell-which-supports-fuzzy-completion-as-in-sublime-text/607338#607338) suggested in the answer first.

**Comment by orschiro** [comment]
Dear @junegunn,

Thanks for your resources!

After having watched [this](https://www.youtube.com/watch?v=AX3u10bruOI) video I finally understood what to do. 

1. I installed fzf using the Git method
2. I type in `up`, press `Ctrl+t` and search for `192`
3. I confirm with `Return`
4. The absolute path to the file containing `192` is being inserted after the `up`. 

This is wonderful! :-)

-Robert

**Comment by junegunn** [comment]
Yeah, and you can do something like `up ~/**<TAB>` (fuzzy completion).

**Comment by orschiro** [comment]
@junegunn,

`up ~/**<TAB>` doesn't work for me in Bash. 

-Robert

**Comment by junegunn** [comment]
@orschiro Oh you're right, fuzzy completion in bash only works with a hard-coded set of commands. `vim ~/**<TAB>` will work. See #536 for the details.

**Comment by orschiro** [comment]
I see, thank you @junegunn!

-Robert
