### ISSUE TITLE
Make preview window scrollable

### ISSUE THREAD

**Issue by junegunn** [junegunn/fzf#669]
Suggested by @DanielFGray in the Gitter channel. I realized that it's actually easy to implement it.

1. Make the window scrollable with mouse scroll
2. Add bindable actions: ~~`preview-scroll-up` and `preview-scroll-down`~~ `preview-up` and `preview-down`

**Comment by deathmaz** [comment]
Hi @junegunn, when i'm trying this example:
`fzf --preview 'highlight -O ansi {}' --bind alt-j:preview-down,alt-k:preview-up`
i'm getting this:
`unknown action: preview-down`
Am i doing something wrong?

I'm using Linux with zsh 5.2 and tmux 2.2.
Thank you for your work!

**Comment by junegunn** [comment]
Did you build fzf from source? Prebuilt binaries are uploaded only when I release a new version.

**Comment by junegunn** [comment]
Try `make install` inside `src` directory.

**Comment by deathmaz** [comment]
> Did you build fzf from source? Prebuilt binaries are uploaded only when I release a new version.

Sorry, didn't know about this.

> Try make install inside src directory.

Thank you for this, preview scrolling works really great!

**Comment by junegunn** [comment]
No problem, thanks for testing it. I just added `preview-page-up` and `preview-page-down` as well (8c8b5b3).

**Comment by deathmaz** [comment]
Great, thank you!
