### ISSUE TITLE
Customizable Ctrl+R keybinding

### ISSUE THREAD

**Issue by jimmytheneutrino** [junegunn/fzf#672]
- Category
    - [x] Key bindings
- OS
    - [x] Linux
- Shell
    - [x] bash

Hi! As much as I adore fzf's ctrl+R behaviour, sometimes it gives too many results and requires more effort to get to the needed command than the original ctrl+R of bash.

I ended up binding fzf's ctrl+R to ctrl+F instead (by modifying key-bindings.bash) and use original ctrl+R and fzf's search interchangeably now. 

What do you think, 
1) is it possible to make this keybinding easily configurable
or maybe
2) just setting it to ctrl+F by default can be discussed?

**Comment by junegunn** [comment]
A few things you might want to consider first:
1. Sorting is by default disabled. You can enable it by pressing CTRL-R again.
2. If you want to enable sorting by default, set `export FZF_CTRL_R_OPTS='--sort'`
3. Prefix each search term with `'` (single-quote) to turn it into an exact (not fuzzy) term.
4. Or you can even add `--exact` to FZF_CTRL_R_OPTS as well. Then prefixing a term with `'` will make it fuzzy term.

Although fzf does not provide an option to customize the key, you can access the definition with `bind -s`, so you can use the information to customize the binding.

```sh
[ -f ~/.fzf.bash ] && source ~/.fzf.bash

bind "$(bind -s | grep fzf_history | sed 's/r/f/')"
bind '"\C-r": reverse-search-history'
```

**Comment by jimmytheneutrino** [comment]
Thanks! 

It seems --exact does work pretty much like default ctrl+r behaviour.

1)
One more thing though.
Bash's reverse-search-history immediately invokes the command on enter. 
Fzf copies the command to the command line instead. 
Is it configurable too?

2) 
I think it is worth putting such a snippet (with binding customization) in the readme.

**Comment by junegunn** [comment]
1) There's an open issue for that: #477. I have a solution for zsh (enter / ctrl-x), but not for bash. If you think you can hack it up let me know.

2) Agreed. I'll add a page to the wiki when I get some time.
