### ISSUE TITLE
accept \0 as entry separator  and multiline entries

### ISSUE THREAD

**Issue by nkh** [junegunn/fzf#675]
- Category
    - [x ] fzf binary

Allows searching blocks of text with embedded \n

**Comment by nkh** [comment]
having looked at the close issues, I notice that other have requested this and I saw why I would probabhaly not implemented.

A related feature could be to work on the input line up to a separator, defined as an option, this allows the user to squeeze in some user data

print "1 :magic: user data 1\n2 :magic: user data 2" | fzf -user_delimiter ':magic:' | further_processing

**Comment by junegunn** [comment]
Have you tried these? https://github.com/junegunn/fzf/blob/master/man/man1/fzf.1#L287-L292

(related #660)

**Comment by nkh** [comment]
No I haven't, till now, because they weren't in the man page of the version I run. --read0 does work with my version and that makes things _much_ easier. 

Thank you.
