### ISSUE TITLE
shortcut to switch preview on/off

### ISSUE THREAD

**Issue by nkh** [junegunn/fzf#676]
- Category
    - [x ] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x ] bash
    - [ ] zsh
    - [ ] fish

preview is indeed very practical in many cases but when the file name is very long, it is hidden by the preview pane. an "online" key shortcut to switch the pane on/off would greatly help

**Comment by DanielFGray** [comment]
I think `--bind='F2:toggle-preview'` is what you're looking for.
You can of course substitute `F2` for whatever key (or key combo) you like.

**Comment by nkh** [comment]
Works like a charm. Thank you.
