### ISSUE TITLE
Toggling the preview window many times crashes fzf

### ISSUE THREAD

**Issue by DanielFGray** [junegunn/fzf#677]
- Category
    - [x] fzf binary
- OS
    - [x] Linux
- Shell
    - [x] zsh

For instance if I run `fzf --preview='sleep 2; echo "foo"' --bind='?:toggle-preview'` and I hold `?` it eventually crashes and prints junk to the terminal, sometimes immediately, sometimes after several seconds...

I think this happens when the preview function doesn't finish? But that's just a guess.

I'm not sure how helpful it will be but here's a `strace`: http://sprunge.us/YHQX

**Comment by junegunn** [comment]
Nice find. Thanks for the report. I believe the above commit should fix the problem. I'll release the version shortly.
