### ISSUE TITLE
keep current entry when changing the search 

### ISSUE THREAD

**Issue by nkh** [junegunn/fzf#678]
- Category
    - [x ] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
     - [x ] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ x] bash
    - [ ] zsh
    - [ ] fish

say the search is 'abc'; fzf shows me a subset of the entries.
if I change the search to 'abc | 123', thus expanding the subset, the display is redrawn and what was the current entry, also still valid, can be moved away from the display.

keep the current entry current if possible, if not, the closest entry to the current entry

**Comment by junegunn** [comment]
The new matches for 123 can have better scores than the matches for abc and therefore can come before them.

```sh
(echo 'aaaaaaaaaabbbbbbbbbbbcccccccccc'; echo '123') | fzf
```

I believe the current behavior makes good sense, and I don't want to make it more complex. For example, you can move your cursor to the front and edit the first term to narrow down or broaden the result set, then what should happen? It's ambiguous. Let's just keep it stateless as it is.

**Comment by nkh** [comment]
can you please explain how two  plain strings can get different scores?

**Comment by junegunn** [comment]
You can find the description here: https://github.com/junegunn/fzf/blob/0.15.2/src/algo/algo.go#L39
