### ISSUE TITLE
Pass current query to preview

### ISSUE THREAD

**Issue by nkh** [junegunn/fzf#679]
- Category
    - [x ] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ x] bash
    - [ ] zsh
    - [ ] fish

This allows the preview to highlight the searched strings

**Comment by junegunn** [comment]
I'll think about it. I also thought about passing tokenized parts instead of the entire line. Using some expressions like `{1}`, `{2}`. But adding more special syntaxes can cause conflicts, so I'm being prudent.

**Comment by nkh** [comment]
That would be fine, although better names would be welcome; {query} ...
