### ISSUE TITLE
In preview {} is stripped from ANSI escape code

### ISSUE THREAD

**Issue by nkh** [junegunn/fzf#680]
- Category
  - [x ] fzf binary
  - [ ] fzf-tmux script
  - [ ] Key bindings
  - [ ] Completion
  - [ ] Vim
  - [ ] Neovim
  - [ ] Etc.
- OS
  - [x ] Linux
  - [ ] Mac OS X
  - [ ] Windows
  - [ ] Etc.
- Shell
  - [x ] bash
  - [ ] zsh
  - [ ] fish

this forces one to re-color the selection which is not always possible as the information about  what should be colored may be lost in a long chain of pipes 

I believe this should be an option as getting the string stripped has many use cases

**Comment by maikelmeyers** [comment]
I also stumbled upon this issue and would like to have such an option.

**Comment by nkh** [comment]
I opened this ticket 3 years ago, I must admit that I forgot the details. I'll try tofind an example. Maybe @mike239x remembers better.

**Comment by mike239x** [comment]
Uh oh I think you meant @maikelmeyers

**Comment by bAndie91** [comment]
if i understand well - and it's my demand also -, it'd be nice to have something like `{c}` macro for preview command, which resolves to the ansi-escape-code-ful representation of the currently selected line. 
and of course there'd be `{c+}` for all of  the selection, `{c1}` for the first field, etc. like the other macros.

**Comment by bAndie91** [comment]
i'm working on this feature and stuck because `replacePlaceholder()` in `terminal.go` does not seem to have ansi-ful items in `allItems` variable. @junegunn could you per chance help me out where to find not-trimmed input items?

**Comment by junegunn** [comment]
Closing as wontfix because it's actually not trivial to implement it because of the way fzf processes ANSI color codes.
