### ISSUE TITLE
invisible user data simplifies handling of non file name data

### ISSUE THREAD

**Issue by nkh** [junegunn/fzf#683]
- Category
    - [x ] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x ] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ x] bash
    - [ ] zsh
    - [ ] fish

user data starts at a separator, defined as an option, this allows the user to squeeze in some user data

this reduces clutter when the data is not a file  name but the file name is needed for further processing

the user data is not displayed by fzf but it is returned in the output

print "1 :magic: user data 1\n2 :magic: user data 2" | fzf -user_delimiter ':magic:' | further_processing

**Comment by junegunn** [comment]
You might want to use the combination of `--with-nth` and `--delimiter`.

**Comment by nkh** [comment]
base on my understanding I tried:
-d'DESCRIPTION|LONG_DESCRIPTION' --with-nth 1 --nth '1..3'

the output is limited to the first field but the delimiter is displayed!

I still need the search all the fields, that doesn't work with the options above, only the first field is searched. I may have misunderstood how to use --nth

**Comment by junegunn** [comment]
> I still need the search all the fields

`--with-nth` transforms the input and thus limits the search scope. It would be extremely confusing if fzf searches invisible part of the line. Let me close this issue as you opened a new one.

**Comment by nkh** [comment]
I think the new issue is orthogonal to this one and  related to display not search

And I meant to search in text that is not visible. 

I have though about turning the text black on black as a workaround.

**Comment by junegunn** [comment]
I understood, but I have no plan to change the current behavior. I see what you're trying to do though. You have a very extraordinary use case, most users don't try to use fzf with multi-line entries.

**Comment by nkh** [comment]
then I'll work around it or maybe a patch when I get time to learn so go :)
