### ISSUE TITLE
ANSI code not handled properly

### ISSUE THREAD

**Issue by nkh** [junegunn/fzf#684]
- Category
  - [x ] fzf binary
  - [ ] fzf-tmux script
  - [ ] Key bindings
  - [ ] Completion
  - [ ] Vim
  - [ ] Neovim
  - [ ] Etc.
- OS
  - [x ] Linux
  - [ ] Mac OS X
  - [ ] Windows
  - [ ] Etc.
- Shell
  - [ x] bash
  - [ ] zsh
  - [ ] fish

![peek 2016-09-29 14-24](https://cloud.githubusercontent.com/assets/45409/18953997/4ee26f22-8651-11e6-9800-15c7ff6313de.gif)

full command line:

```
ra show requirements/sorted/ --include_type requirement --include_description_data  --format raw -requirement_fields_filter_file <(echo "'LONG_DESCRIPTION' => 1, 'DESCRIPTION' => 1") | perl -MTerm::ANSIColor -pe 's/^\s+$// ; s/\t/    /g' | colout '(NAME)*(LONG_)*(DESCRIPTION)*' red,blue | fzf --read0 --no-sort -m --ansi --preview-window down:50% --no-hscroll --preview "echo {} | colout '(NAME)*(DESCRIPTION)*(LONG_)*(DEFINED_AT)*' red,blue,blue,blue " --bind "ctrl-v:execute(printf {} | colout '(NAME)' red | colout '(DESCRIPTION)*(LONG_)*(DEFINED_AT)*' blue | /usr/bin/less -R)" -d'DESCRIPTION|LONG_DESCRIPTION' --with-nth 1 --nth 1..3

ra show requirements/sorted/ --include_type requirement --include_description_data  --format raw -requirement_fields_filter_file <(echo "'LONG_DESCRIPTION' => 1, 'DESCRIPTION' => 1") | perl -pe 's/^\s+$// ; s/\t/    /g' | color_pipe  NAME red '(LONG_)*DESCRIPTION' bright_blue | fzf --read0 --no-sort -m --ansi --preview-window down:50% --no-hscroll --preview "echo {} | color_pipe NAME red '(LONG_)*DESCRIPTION' bright_blue 'DEFINED_AT.*' blue " --bind "ctrl-v:execute(printf {} | color_pipe NAME red '(LONG_)*DESCRIPTION' bright_blue 'DEFINED_AT.*' blue | /usr/bin/less -R)" -d'DESCRIPTION|LONG_DESCRIPTION' --with-nth 1 --nth 1..3
```

text from the demonstration of the problem:
- Hi, thanks again for fzf
- There is, I believe, a problem with how the ANSI color codes are handled
  
  This is even clearer the coloring is done by different tools
- Command line is: data_generator | coloring |  fzf fzf_options
  
  fzf option: --read0 --no--sort -m --ansi --preview-window down:50% --no-hscroll 
              -d'DESCRIPTION|LONG_DESCRIPTION' --with-nth 1 --nth 1..3
                  --preview "echo {} | coloring " 
                  --bind "ctrl-v:execute(printf {} | coloring"

where coloring is done by either 'colout' or code that I wrote which is much faster
- colout @ https://github.com/nojhan/colout
  
  options: '(NAME)_(LONG_)_(DESCRIPTION)*' red,blue
  
  the delimiter, 'DESCRIPTION', is visible (should it?)
  
  the preview shows the data I input colorized properly
- with color_pipe @ http://paste.debian.net/plain/843744
  
  options: color_pipe  NAME red '(LONG_)*DESCRIPTION' bright_blue
  
  the delimiter is NOT visible, except when the line is selected
  
  the preview does not shows the data I input colorized properly, but the OK when executed
  in the external viewer

**Comment by junegunn** [comment]
I have no idea what `ra` is, so please post the raw output on gist so I can test with it.

I added `--delimiter` and `--with-nth` option with tabular text in mind. To keep the table aligned after the transformation, we have to keep the trailing delimiter.

```sh
> column -t <(ls -al)
total       40
drwxr-xr-x  4   jg  staff  136    Sep  29  02:58  .
drwxr-xr-x  3   jg  staff  102    Sep  7   21:30  ..
-rw-r--r--  1   jg  staff  1809   Sep  29  02:58  fzf-tmux.1
-rw-r--r--  1   jg  staff  15037  Sep  29  02:58  fzf.1

> column -t <(ls -al) | fzf --with-nth 1..4,9 --reverse --inline-info

>   < 6/6
> total       40
  drwxr-xr-x  5   jg  staff  .
  drwxr-xr-x  3   jg  staff  ..
  -rw-r--r--  1   jg  staff  column
  -rw-r--r--  1   jg  staff  fzf-tmux.1
  -rw-r--r--  1   jg  staff  fzf.1

> ls -al | sed $'s/  */\t/g'
total   40
drwxr-xr-x      4       jg      staff   136     Sep     29      02:58   .
drwxr-xr-x      3       jg      staff   102     Sep     7       21:30   ..
-rw-r--r--      1       jg      staff   1809    Sep     29      02:58   fzf-tmux.1
-rw-r--r--      1       jg      staff   15037   Sep     29      02:58   fzf.1

> ls -al | sed $'s/  */\t/g' | fzf --with-nth 1..4,9 --delimiter $'\t' --tabstop 16 --reverse --inline-info

>   < 6/6
> total           40
  drwxr-xr-x      5               jg              staff           .
  drwxr-xr-x      3               jg              staff           ..
  -rw-r--r--      1               jg              staff           column
  -rw-r--r--      1               jg              staff           fzf-tmux.1
  -rw-r--r--      1               jg              staff           fzf.1
```

Since you seem to be using `--read0` in this case, have you considered using `--delimiter "\n"` instead?

**Comment by nkh** [comment]
ra is just an application generating lines, it doesn't matter which one is used. cat a file, or anything that makes sense to you. I can, if you want, send a snippet of text but, again, any text will do.

There are two problems
    -display colors being changed
            I hope the above input about what 'ra' does make it clear what problem I encounter

    - the delimiter being showed
                  I can probably work around this by inserting a phony delimiter

I do understand that you did not have free text in mind, maybe a note with these examples in the doc (if I haven't missed htat), would help other users. I certainly would like to see free text supported, I think it add a great dimension to fzf

**Comment by junegunn** [comment]
> There are two problems -display colors being changed

I need the raw output including ANSI escape sequences to reproduce the problem and fix it. It would be much easier for me if you can just post the output on gist than I try to install and use those programs I have no experience with.

> the delimiter being showed

`--delimiter "\n"` should work in this case, I suppose?

**Comment by junegunn** [comment]
Having said that, I also had a case where I didn't want the delimiters to be shown, and I used non-breaking space (`echo -e "foo\xc2\xa0bar"`) as the delimiter.

**Comment by nkh** [comment]
https://gist.github.com/anonymous/e871debce720b8f8ef170c9298b7011b

all contain a \0

**Comment by junegunn** [comment]
```sh
OPTS="--read0 --no-sort -m --ansi --preview-window down:50% --no-hscroll --preview 'echo {}' -d'DESCRIPTION|LONG_DESCRIPTION' --with-nth 1"

eval "fzf $OPTS" < raw_input_color_pipe
eval "fzf $OPTS" < raw_input_colout
```

The only difference I notice is the boldness of the text, which is correct according to the raw input (`\e[1;31m` vs. `\e[31m`). Is there any other problem you notice?

And like I said above, `\n` seems like a better delimiter to me here if you want to hide the delimiter.

OPTS="--read0 --no-sort -m --ansi --preview-window down:50% --no-hscroll --preview 'echo {}' -d'\n' --with-nth 1"
