### ISSUE TITLE
selected entries always match, which highest score

### ISSUE THREAD

**Issue by nkh** [junegunn/fzf#687]
- Category
  - [ x] fzf binary
  - [ ] fzf-tmux script
  - [ ] Key bindings
  - [ ] Completion
  - [ ] Vim
  - [ ] Neovim
  - [ ] Etc.
- OS
  - [ x] Linux
  - [ ] Mac OS X
  - [ ] Windows
  - [ ] Etc.
- Shell
  - [ x] bash
  - [ ] zsh
  - [ ] fish

if multiple sections are made and the search is changed, the selected entries may be removed from the display making it unnecessarily complicated to deselect entries. with the proposed option, the selection are always visible. if the entry id deselected and it doesn't match the search, the entry is removed from the list.

**Comment by junegunn** [comment]
Not exactly what you suggested, but with the latest version, it is now possible to deselect entries when the search query is changed.

```sh
# Whenever the query is changed move cursor to the top and deselect previously selected entries
fzf --multi --bind change:top+deselect-all
```

**Comment by nkh** [comment]
HI,

It is indeed better, not the same but good to have. Thank you.
