### ISSUE TITLE
user can set the maximum number of entries that can be selected

### ISSUE THREAD

**Issue by nkh** [junegunn/fzf#688]
- Category
  - [x ] fzf binary
  - [ ] fzf-tmux script
  - [ ] Key bindings
  - [ ] Completion
  - [ ] Vim
  - [ ] Neovim
  - [ ] Etc.
- OS
  - [ x] Linux
  - [ ] Mac OS X
  - [ ] Windows
  - [ ] Etc.
- Shell
  - [ x] bash
  - [ ] zsh
  - [ ] fish

I propose option -M which, as option m, allows the selection of multiple items, the difference is that -M takes the maximum number of items that can be selected.  of course -m option is good too.

**Comment by junegunn** [comment]
Closing as it's quite niche and brings more questions; should we simply disallow selecting more entries, or should we deselect the earliest selection? Don't want two more options.

Although not ideal, we can still post-process the output of fzf (i.e. `fzf -m | head -10`) or tell the user "you selected too many items".
