### ISSUE TITLE
IRC channel 

### ISSUE THREAD

**Issue by nkh** [junegunn/fzf#689]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ x] Linux
    - [ x] Mac OS X
    - [ x] Windows
    - [ x] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [ ] fish

submitting a new issue seems overkill when one only as a configuration question

other users may be able to answer the questions too

**Comment by junegunn** [comment]
I don't use IRC, but there is a gitter chat room: https://gitter.im/junegunn/fzf
