### ISSUE TITLE
replace unsightly perl code

### ISSUE THREAD

**Issue by nkh** [junegunn/fzf#690]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [x ] Etc.
- OS
    - [ ] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x ] bash
    - [ ] zsh
    - [ ] fish

in https://github.com/junegunn/fzf/wiki/Examples#with-write-to-terminal-capabilities, function writecmd is written in Perl. It can be written in a much cleaner way and even better if it is acceptable to have two functions. 'writecmd' and 'runcmd', can be written as below.
~~~~
runcmd (){ perl -e 'ioctl STDOUT, 0x5412, $_ for split //, <>' }

writecmd (){ perl -e 'ioctl STDOUT, 0x5412, $_ for split //, do{ chomp($_ = <>); $_ }' }

**Comment by junegunn** [comment]
Hi, I didn't add/test the example. If you think you can improve it, feel free to update it. Thanks.

**Comment by nkh** [comment]
example updated

**Comment by junegunn** [comment]
Thanks.
