### ISSUE TITLE
illegal option: --ansi troubles

### ISSUE THREAD

**Issue by EffOhEnTeEe** [junegunn/fzf#691]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

Hello, first I would like to thank you for your work.

Unfortunately, I am having a bit of a problem. When I first attempted to install fzf, I received an error saying that Ruby was not installed so I installed it (Ruby version 2.3.1) and Curses (version 1.0.2) and then attempted to use the function below which I obtained from https://github.com/paulirish/dotfiles/blob/master/.functions that starts at line 34.

~~~~~
# git commit browser. needs fzf
log() {
  git log --graph --color=always \
      --format="%C(auto)%h%d %s %C(black)%C(bold)%cr" "$@" |
  fzf --ansi --no-sort --reverse --tiebreak=index --toggle-sort=\` \
      --bind "ctrl-m:execute:
                echo '{}' | grep -o '[a-f0-9]\{7\}' | head -1 |
                xargs -I % sh -c 'git show --color=always % | less -R'"
}
~~~~~

Upon execution I receive the error that --ansi is an illegal option.

![screenshot from 2016-10-03 21-22-32](https://cloud.githubusercontent.com/assets/5957886/19059671/b595fa5c-89af-11e6-9243-b248b4677aec.jpg)

![screenshot from 2016-10-03 21-12-51](https://cloud.githubusercontent.com/assets/5957886/19059612/2b32dac4-89af-11e6-8687-a69c9685a7c9.jpg)

Steps I have tried to rectify the problem:
* Update fzf repo with and without the depth option.
* Downgrade Ruby from 2.3.1 to a 1.9.3 build.
* Uninstall Ruby and Curses and install Go and attempt to build from source with instructions from here https://github.com/junegunn/fzf/issues/300#issuecomment-124995968 .
* Have both Ruby and Go installed and run the install script.

Curiously, the binaries that are generated appear to be labeled properly but the --version output is incorrect as shown below. I am not sure this is related or not.

![screenshot from 2016-10-03 21-36-47](https://cloud.githubusercontent.com/assets/5957886/19060006/65f9893e-89b2-11e6-9808-8a50bb487dc1.jpg)
![screenshot from 2016-10-03 21-45-02](https://cloud.githubusercontent.com/assets/5957886/19060048/c1b797fc-89b2-11e6-8932-3ed9c4bf81fb.jpg)

Lastly, the fzf-tmux command is not working either.

My current system is running Ubuntu 16.04 and this is a fresh install from earlier today. I have made some configuration changes but I am unsure if any of those changes could have this effect on fzf's functionality. I have probably botched something but, for the life of me, I cannot figure out what I am doing incorrectly. I am happy to provide any documentation that you may need and I would appreciate any help you can provide.

**Comment by junegunn** [comment]
You don't need to care about the Ruby version, it's no longer maintained.

> When I first attempted to install fzf, I received an error saying that Ruby was not installed so I installed it

Can you post the log message? I wonder how you end up with this. The install script should not say anything about Ruby on Linux.

Take the following steps.

1. Check the output of `which fzf`. $PATH should contain `~/.fzf/bin`, not `~/.fzf`
2. Forget about Ruby or Go, let's just reinstall fzf as follows

    ```sh
    rm -rf ~/.fzf
    git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
    ~/.fzf/install
    # Say yes to the questions
    ```
3. Your .bashrc should be now updated. Reload it: `source ~/.bashrc`
4. See if `which fzf` is pointing to `~/.fzf/bin/fzf`. No? Examine your $PATH variable.

**Comment by EffOhEnTeEe** [comment]
Thank you for the quick reply! All is working now after your suggestion #1.

The log said that fzf was already found in path and <code>which fzf</code> returned <code>~/bin/fzf</code>
![screenshot from 2016-10-03 22-48-45](https://cloud.githubusercontent.com/assets/5957886/19061077/a3c84652-89bb-11e6-8239-076236af1164.png)

I deleted <code>~/bin/fzf</code> and reinstalled using your instructions. <code>~/.fzf/bin</code> is in the path now everything is working beautifully.

![screenshot from 2016-10-03 22-56-34](https://cloud.githubusercontent.com/assets/5957886/19061210/bc065a50-89bc-11e6-83a2-dfdf0e7b07d3.png)

I am not sure how that file ended up there, definitely user error though. I will look into that but for now the version is showing properly and everything is working great.  Thank you very much for your help.

**Comment by junegunn** [comment]
No problem.
