### ISSUE TITLE
re-wrote script in wiki

### ISSUE THREAD

**Issue by nkh** [junegunn/fzf#693]
- Shell
    - [x ] bash
    - [ ] zsh
    - [ ] fish

https://github.com/junegunn/fzf/wiki/Examples

search for 're-wrote the script above'

I cleaned up the original script but left it in the wiki as I did not write it.  you may want to keep only one of them

**Comment by junegunn** [comment]
Thanks. I haven't paid enough attention to the scripts posted there, but now I'll have to review them. And maybe remove the ones that do not work out of the box, and the ones that seem too verbose or complex.
