### ISSUE TITLE
keep partial matched in hit list

### ISSUE THREAD

**Issue by nkh** [junegunn/fzf#694]
- Category
  - [x ] fzf binary
  - [ ] fzf-tmux script
  - [ ] Key bindings
  - [ ] Completion
  - [ ] Vim
  - [ ] Neovim
  - [ ] Etc.

given the list 
  constant 1 2 3
  constant a b c

If the the query is set to 'constant a' , 'constant 1 2 3' should also be in the list, albeit with a much lower rank, otherwise it feels much less fuzzy than it could be and puts the burden on the user rather than on the program.

**Comment by junegunn** [comment]
When you type in `constant a`, it's a conjunctive query of `constant` and `a`. `constant` of course matches `constant`, and `a` matches `a` in `const*a*nt`. So `constant a` matches both `constant 1 2 3` and `constant a b c`, it's probably not you intended though. `constant a b c` will be ranked higher as `a` matches a start of a word. Having said that, I'm not sure if I follow your suggestion. Can you elaborate?

**Comment by nkh** [comment]
I'd like to see 'constant or a' which would rank lower than 'constant and a'

here is the use case, no it's not just for the fun of it

I'd like to replace bash history search with fzf, it just makes more sense to have more visual feedback than one line. Bash's search suck BIG TIME because it doesn't really care for what's on the line. I'd like the history search  with fzf to take that into account. I'm working on that.

Here is the "problem", I start typing: command this that; at this point I remember that I did something like that "still in my history" ago; if I hit ^R only the lines matching "command and this and that" will match.

IMHO, fuzzy is better whe it's ored than when it is anded. it makes it applicable to a whole bunch of problems.
