### ISSUE TITLE
Using fzf as a kind of "selection menu"

### ISSUE THREAD

**Issue by d630** [junegunn/fzf#70]
I would like to use `fzf` as a kind of "selection menu", in that way `dmenu` may be used. Therefore, it would be nice, if `fzf` had:
- a modifiable prompt
-  an option to print the query respectively the literal string to stdout, when `fzf` has not matched anything

**Comment by maxime-michel** [comment]
I'm also using fzf as a launcher (Alfred on OS X is my inspiration) and I'm getting spectacular results, thanks for the script! Like @D630 I would be interested in getting the query but only if there are no matches. I don't mind using the three lines you wrote but I'm not sure how to use them in my case? This is the beginning of the script I mapped to Win+Space.

	#!/bin/bash
	find * -path '*/\\.*' -prune -o -type f -print -o -type l -print -o -type d -print 2> /dev/null | /usr/bin/ruby ~/.fzf/fzf -e --print-query
	query="${output[0]}"
	matches=( ${output[@]:1} )
	echo $query # yt funny kittens
	echo $matches # t
