### ISSUE TITLE
Custom search algorithm

### ISSUE THREAD

**Issue by bentomas** [junegunn/fzf#700]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.

I love the fzf command line interface, and the interface for doing searches and selecting results, but I really don't like traditional fuzzy searches that search whole paths at once.  I have my own custom search algorithm that I've written in Vimscript, Ruby and Elixir, and in the past patched into searching tools like ctrlp or selecta.  Unfortunately, I don't know Go, and can't figure it out enough to patch in my own algorithm into the algo.go file for fzf.  

I will try an learn Go if that's my only option, but what I'm wondering about is if there could be some way to specify an external command for actually doing the matching.  I might not be the only person that is interested in custom searching algorithms.  

This would also maybe make fzf more versatile and easier to experiment with, because you could work on matching separately from the interface.

I'm a novice when it comes to writing cli scrips, but maybe the external script could take entries in through standard input and then a special line would indicate a pattern, and the script would write out the entries with their scores?

----

For those that are curious, my custom fuzzy algorithm for searching through file paths is to break the pattern into "parts", and then each pattern part (split by `,`) must individually match a path part (split by `/`), with the last pattern part having to match the file name.  So, for files like so:

1. `path/to/file.txt`
2. `path/to/other/file.txt`
3. `path/with/file/folder.txt`
4. `some/other/name.txt`

So, for the following patterns

+ `file` would _only_ match the first two paths, not the 3rd one.
+ `other` wouldn't match any path
+ `other,txt` would match paths 2 and 4.
+ `path,o` would match the 3rd path.

This makes it very easy to get exactly the file you want, by specifying a character from a couple directories and then a couple characters from the file name, and I find it matches the way I think bout the filesystem better than fuzzy searching across the whole path.

(or if someone could help me figure out how to make this work in Go, I'd be excited about that too!)

**Comment by junegunn** [comment]
Hi, pluggable algorithm may sound intriguing, but an arbitrary algorithm is not likely to be fully compatible with the existing search options of fzf and the extra layer will certainly add complexity and performance overhead. It's not something I'm interested in at the moment.

How long have you been using fzf? And I'd like to hear about real-world examples where fzf doesn't perform well. In my opinion, fzf performs much better than the alternatives you listed above in terms of the performance and the quality of the result (the latter especially since 0.15.0). So the specialized algorithm you needed with the other fuzzy finders may no longer be necessary with fzf if you become more familiar with the way fzf works (e.g. its [search syntax](https://github.com/junegunn/fzf#search-syntax), its [sorting criteria](https://github.com/junegunn/fzf/blob/0.15.4/src/algo/algo.go#L39-L40) that allows acronym search, and the options for limiting the search scope like `--nth` and `--delimiter`).

```sh
# This allows you to perform prefix search on the file name: ^file
fzf -d/ -n-1,..
```

**Comment by bentomas** [comment]
Yeah, I honestly figured that would be the answer.  Making the algorithm customizable would certainly take some work.  It was mostly wishful thinking.  And I appreciate that performance is such an important concern and think you've written an amazing tool!

Seriously, don't let me understate that: I think fzf is _amazing_, and will continue to use it over the previous tools I used.  So in the rest of this comment as I outline why I'm not 100% happy with the search algorithm, I'm still happier with fzf than anything else!

Yeah, I familiarized myself with the search syntax options, but to be blunt, when it comes to finding files I have no interest in using them.  For me the utility of a tool like this is that I get it set up with a key combination, and it works so fast, that I never have to _think_ about that I want: I just type characters from the file name (and maybe a few of the directories).  And having to use special syntax (and special characters are harder to reach on the keyboard) is an extra mental step I'm not going to do.

However, would I use the search syntax options when looking through log files or for other searches? You bet!

Now, fzf is a general purpose tool, and it isn't specifically for finding files, so I think the current algorithm is fantastic for searching arbitrary lines of text, but I guess for me, I don't think about searching for files as lines of text like this:

```
CHANGELOG.md
LICENSE
README.md
bin/fzf
bin/fzf-tmux
fzf
install
man/man1/fzf-tmux.1
man/man1/fzf.1
plugin/fzf.vim
shell/completion.bash
shell/completion.zsh
shell/key-bindings.bash
shell/key-bindings.fish
shell/key-bindings.zsh
src/algo/algo.go
src/algo/algo_test.go
src/ansi.go
src/ansi_test.go
src/cache.go
src/cache_test.go
src/chunklist.go
src/chunklist_test.go
src/constants.go
src/core.go
src/curses/curses.go
src/curses/curses_test.go
src/Dockerfile.android
src/Dockerfile.arch
src/Dockerfile.centos
src/Dockerfile.ubuntu
src/fzf/main.go
src/history.go
src/history_test.go
src/item.go
src/item_test.go
src/LICENSE
src/Makefile
src/matcher.go
src/merger.go
src/merger_test.go
src/options.go
src/options_test.go
src/pattern.go
src/pattern_test.go
src/reader.go
src/reader_test.go
src/README.md
src/result.go
src/result_test.go
src/terminal.go
src/terminal_test.go
src/tokenizer.go
src/tokenizer_test.go
src/update_assets.rb
src/util/atomicbool.go
src/util/atomicbool_test.go
src/util/chars.go
src/util/chars_test.go
src/util/eventbox.go
src/util/eventbox_test.go
src/util/slab.go
src/util/util.go
src/util/util_test.go
test/fzf.vader
test/test_go.rb
uninstall
```

I think about searching for files as navigating a tree like this where each file or directory is a node on that tree:

```
fzf
├── CHANGELOG.md
├── LICENSE
├── README.md
├── bin
│   ├── fzf -> /usr/local/bin/fzf
│   └── fzf-tmux
├── fzf
├── install
├── man
│   └── man1
│       ├── fzf-tmux.1
│       └── fzf.1
├── plugin
│   └── fzf.vim
├── shell
│   ├── completion.bash
│   ├── completion.zsh
│   ├── key-bindings.bash
│   ├── key-bindings.fish
│   └── key-bindings.zsh
├── src
│   ├── Dockerfile.android
│   ├── Dockerfile.arch
│   ├── Dockerfile.centos
│   ├── Dockerfile.ubuntu
│   ├── LICENSE
│   ├── Makefile
│   ├── README.md
│   ├── algo
│   │   ├── algo.go
│   │   └── algo_test.go
│   ├── ansi.go
│   ├── ansi_test.go
│   ├── cache.go
│   ├── cache_test.go
│   ├── chunklist.go
│   ├── chunklist_test.go
│   ├── constants.go
│   ├── core.go
│   ├── curses
│   │   ├── curses.go
│   │   └── curses_test.go
│   ├── fzf
│   │   └── main.go
│   ├── history.go
│   ├── history_test.go
│   ├── item.go
│   ├── item_test.go
│   ├── matcher.go
│   ├── merger.go
│   ├── merger_test.go
│   ├── options.go
│   ├── options_test.go
│   ├── pattern.go
│   ├── pattern_test.go
│   ├── reader.go
│   ├── reader_test.go
│   ├── result.go
│   ├── result_test.go
│   ├── terminal.go
│   ├── terminal_test.go
│   ├── tokenizer.go
│   ├── tokenizer_test.go
│   ├── update_assets.rb
│   └── util
│       ├── atomicbool.go
│       ├── atomicbool_test.go
│       ├── chars.go
│       ├── chars_test.go
│       ├── eventbox.go
│       ├── eventbox_test.go
│       ├── slab.go
│       ├── util.go
│       └── util_test.go
├── test
│   ├── fzf.vader
│   └── test_go.rb
└── uninstall
```

And for me, a search where I specify when I want to cross node boundaries with a comma, and _I have to find a match in the node that is ultimately chosen_ is much more intuitive.  

That's my biggest complaint about fzf for _finding files_ right now: it will often return results where the match doesn't happen anywhere in file name or directory name.  

(Yes, I can use `--nth` and `--delimiter` to specifically target just the last field, and split fields by `/`, but then I have to run a different fzf command if I want to look at both the last field AND the second to last field.  And I can't target the first field AND the last field)

To give you a bit of a contrived example that you'll be able to reproduce on your own system, if I run `fzf` in the project directory for fzf, and search for `fzf`, this is the output:

<img width="892" alt="screen shot 2016-10-12 at 09 58 01" src="https://cloud.githubusercontent.com/assets/49276/19317492/688fa99c-9062-11e6-9ed8-e999f78ac3f0.png">

If you look at that output, you'll see that the first 6 results are files or directories where the name contains fzf. Perfect!

Now, if I go up 1 directory and do the same thing, run the `fzf` command and search for `fzf`, this is the result:

<img width="892" alt="screen shot 2016-10-12 at 10 01 08" src="https://cloud.githubusercontent.com/assets/49276/19318480/25f76daa-9066-11e6-8049-197af8222281.png">

In this case, only 2 of those 6 files are now visible, as the it's prioritizing the `fzf` project directory over files containing `fzf`.  Personally, I think the results got _worse_ when I went up a directory, whereas with my preferred algorithm the results stay the same because it is thinking about nodes on the tree. If I wanted to see a list of results contained in a node with my algorithm, I'd do `fzf,`.

This isn't a hypothetical problem for me, my work project directory has quite a few directories whose names match files I want to find.  So I end up having to repeat the name.   

But who knows, maybe I'll get used to fzf's behavior, especially since I don't know Go at all.  But I'm still convinced that for _finding files_ my custom algorithm is a more intuitive approach.

But like I said, fzf rocks! Thanks!

**Comment by junegunn** [comment]
Yo, thanks for the detailed explanation. That was quite some food for thought. Like you said, fzf is a general purpose tool that is supposed to work okay with any type of data and I'm currently focusing on that aspect. But yeah, obviously file search is the number one use case of fzf and it would be nice if we could somehow make fzf better at that without hurting its simplicity. I appreciate your feedback.

In this particular case, you might want to test `fzf --tiebreak=end` which will prioritize matches that are closer to the end of the string. It simply calculates the distance from the end, so the list may look a bit disordered if you don't look closely. Maybe we should consider the relative position of the pattern rather than the absolute distance from the end. Something to think about.
