### ISSUE TITLE
`fzf-tmux` produces "no server running" (tmux) error

### ISSUE THREAD

**Issue by chaucerbao** [junegunn/fzf#702]
- Category
    - [ ] fzf binary
    - [x] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

I'm attempting to use command-line keybindings (CTRL-R, CTRL-T, ALT-C), and it produces

```
no server running on /private/tmp/tmux-501/default
```

tmux is installed, but not currently running. Loading tmux and using the keybindings works.

**Comment by matzebond** [comment]
got the same error, seems to be introduced recently
quickfix: `cd ~/.fzf && git checkout 0.15.4`

**Comment by junegunn** [comment]
Sorry for the troubles. Can you check if the latest commit fixes the issue?

**Comment by matzebond** [comment]
Works like a charm. Keep up the great work :+1:

**Comment by junegunn** [comment]
It was my oversight, thanks for the feedbacks.
