### ISSUE TITLE
Buffers opened through fzf require resourcing to get colorcolumns

### ISSUE THREAD

**Issue by RatanRSur** [junegunn/fzf#703]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [x] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [x] Mac OS X **Maybe, havne't yet tried it on my mac**
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

I currently have a setup which colors all the columns from 101 onwards:
`let &l:colorcolumn=join(range(101, 999), ',')`

For some reason, this does not work on buffers opened through fzf and I have to source my init.vim manually. Any ideas why this might be happening?

**Comment by junegunn** [comment]
`&l:colorcolumn` is local to buffer, remove `l:` part.
