### ISSUE TITLE
Install script should ask for which shell it installs fzf

### ISSUE THREAD

**Issue by ffittschen** [junegunn/fzf#705]
- Category
  - [x] fzf binary
  - [x] Etc.
- OS
  - [x] Mac OS X
- Shell
  - [x] bash
  - [x] zsh
  - [x] fish

Hi!

I'm mainly using fzf on my mac and installed it with `homebrew`. After upgrading, I run `/usr/local/opt/fzf/install`. But the install script always generates files for all shells, so I need to do a manual clean-up every time I update fzf... Is it feasible to ask for which shells it should install itself?

**Comment by junegunn** [comment]
Probably. What is your main shell? The install script does 4 things:

1. Add fzf/bin directory to $PATH
2. Add man page directory to $MANPATH
3. Set up fuzzy completion
4. Set up key bindings (CTRL-T, CTRL-R, and ALT-C)

The first two things are already handled by homebrew, the latter two are just two lines loading script files from fzf. For bash, this is it:

```sh
# Auto-completion
# ---------------
[[ $- == *i* ]] && source "/usr/local/opt/fzf/shell/completion.bash" 2> /dev/null

# Key bindings
# ------------
source "/usr/local/opt/fzf/shell/key-bindings.bash"
```

So you can consider manually adding those lines to your .bashrc (or equivalent lines to .zshrc) if you don't like the clutter install script creates.
