### ISSUE TITLE
show "real" command name for kill <TAB> when process renames argv[0]

### ISSUE THREAD

**Issue by unhammer** [junegunn/fzf#707]
- Category
  - [ ] fzf binary
  - [ ] fzf-tmux script
  - [ ] Key bindings
  - [x] Completion
  - [ ] Vim
  - [ ] Neovim
  - [ ] Etc.
- OS
  - [x] Linux
  - [ ] Mac OS X
  - [ ] Windows
  - [ ] Etc.
- Shell
  - [x] bash
  - [ ] zsh
  - [ ] fish

kill <TAB> should show /proc/<pid>/comm, at least where it differs from the first arg of /proc/<pid>/cmdline.

If you `exec -a fakename bash -l`, then /proc/<pid>/comm is "bash", while /proc/<pid>/cmdline is "fakename -l". It'd be nice if the kill completion could show both (at least where they differ), e.g. 

```
user 2942 2940 0 okt.16 pts/9  00:00:02 bash foo.sh
user 2943 2940 0 okt.16 pts/9  00:00:01 fakename[bash] bar.sh
```

**Comment by amosbird** [comment]
+1, and sorting by process time can further distinguish those pids.

**Comment by junegunn** [comment]
Patches are welcome, please make sure that the code works in both macOS and linux.
