### ISSUE TITLE
FZF Panicing on macOS Sierra

### ISSUE THREAD

**Issue by aaparella** [junegunn/fzf#709]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [x ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [ x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x ] zsh
    - [ ] fish

After updating to macOS Sierra (though I'm not 100% sure that it directly caused this issue), FZF occasionally panics with no apparent rhyme or reason. Some very brief error messages pop up that I managed to screenshot, and you can find them attached.

![screen shot 2016-10-19 at 4 52 01 pm 3](https://cloud.githubusercontent.com/assets/4794994/19541818/2a7d80ea-961e-11e6-9b2b-547fba5e5fbe.png)
![screen shot 2016-10-19 at 5 00 39 pm 3](https://cloud.githubusercontent.com/assets/4794994/19541819/2a933520-961e-11e6-9e8f-f9b8e7a8b563.png)

Looked around a bit and didn't see anyone experiencing anything similar. Thanks for any help you can give!

**Comment by junegunn** [comment]
Strange, which version of fzf are you running? If it's not 0.15.4, can you try rerunning the install script to download the latest?

**Comment by aaparella** [comment]
Updated it before making the issue, currently using 0.15.4.

**Comment by junegunn** [comment]
Is it reproducible in the shell as well? Using simple `fzf` command. If so, I'd like to know see the input list, that is, the output of `find . -path '*/\.*' -prune -o -type f -print -o -type l -print 2> /dev/null | sed s/^..//` (or that of $FZF_DEFAULT_COMMAND if you have defined it)

**Comment by junegunn** [comment]
Or can you post the output of `fzf -f . 2>&1`

**Comment by aaparella** [comment]
I can't seem to reproduce this using just fzf from the shell (zsh, if that's relevant).

**Comment by aaparella** [comment]
I removed and reinstalled the FZF vim plugin, and I can't recreate the issue anymore. Will re-open this issue if the problem arises again, thanks for your help!

**Comment by junegunn** [comment]
Huh, strange. Glad to hear that it's fixed anyway. If you run into the problem again, please let me know of the following details.

- Does fzf fail immediately, or fail after you type in some string?
- Do you have $FZF_DEFAULT_OPTS or $FZF_DEFAULT_COMMAND?
- Is it reproducible randomly or constantly? I'm trying to see if the failure is related to the input list.

Thanks!

**Comment by aaparella** [comment]
I will definitely report if I encounter it again. For the record:

* It fails mid-search, but not after a specific number or sequence of characters
* I do not have either variable set
* It is fairly consistent, but not 100% constant

**Comment by junegunn** [comment]
Thanks, I can't be sure but that could be related to #666, and probably your vim was not picking up the latest version of fzf.

**Comment by pixelstorm** [comment]
im getting the panic regularly in the command line, after upgrade to sierra. i updated fzf, still i get the panic. deleted the vim plugin, still get the panic.  i can reproduce just by typing fzf.
![screenshot_1207](https://cloud.githubusercontent.com/assets/1531433/19828849/2d63ae68-9e1d-11e6-974d-f8747286d938.jpg). I wish to reinstall to see if it fixes the issue. How can i uninstall so i can reinstall?

**Comment by junegunn** [comment]
@pixelstorm  How did you "update fzf"? The error message shows that you're running an old version of fzf. Follow the instruction in https://github.com/junegunn/fzf#upgrading-fzf. If the problem still persists, check if you're pointing to the right binary by `which fzf`?

**Comment by pixelstorm** [comment]
thanks for responding so quickly. i use the git for install

~: cd ~/.fzf && git pull && ./install
Already up-to-date.
Downloading bin/fzf ...
  - Already exists
  - Checking fzf executable ... 0.15.5
Do you want to enable fuzzy auto-completion? ([y]/n) y
Do you want to enable key bindings? ([y]/n) y

Generate ~/.fzf.bash ... OK
Generate ~/.fzf.zsh ... OK

Do you want to update your shell configuration files? ([y]/n) y

Update /Users/pixelstorm/.bashrc:
  - [ -f ~/.fzf.bash ] && source ~/.fzf.bash
    - Already exists: line #4 

Update /Users/pixelstorm/.zshrc:
  - [ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
    - Already exists: line #4 

Finished. Restart your shell or reload config file.
   source ~/.bashrc  # bash
   source ~/.zshrc   # zsh

Use uninstall script to remove fzf.

For more information, see: https://github.com/junegunn/fzf


i get this when i do ~/.fzf: which fzf
/usr/local/bin/fzf

errors still happening.

**Comment by junegunn** [comment]
`which fzf` should point to `~/.fzf/bin/fzf`. Looks like you installed fzf using homebrew. Try `brew uninstall fzf`.

**Comment by pixelstorm** [comment]
confused i am

~/.fzf: brew uninstall fzf
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- mach (LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Library/Homebrew/extend/pathname.rb:2:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Library/Homebrew/global.rb:3:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Library/brew.rb:15:in `<main>'
~/.fzf: fzf
~/.fzf: sudo brew uninstall fzf
Password:
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- mach (LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Library/Homebrew/extend/pathname.rb:2:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Library/Homebrew/global.rb:3:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Library/brew.rb:15:in `<main>'

**Comment by pixelstorm** [comment]
its working solid as a rock now. i had to update homebrew to fix error above. thanks for your help.

**Comment by ryanbas21** [comment]
I am having this issue - randomly after moving my work .zshrc to my home computer. I reinstalled fzf, - from brew - uninstalled it - and installed it from github

`which fzf` points to `/Users/RyanBas/.fzf/bin/fzf`

my zshrc file works at my work computer - which is a new macos - so I can update my OS which 🤷‍♂️ 


This is what it looks like for me. It works fine in `vim`, this is just a terminal issue.

<img width="1440" alt="screen shot 2018-08-24 at 6 16 52 pm" src="https://user-images.githubusercontent.com/18267769/44611974-3c32e180-a7ca-11e8-9cc8-81068f67634c.png">


CTRL-T and alt-c commands aren't working and produce this issue
