### ISSUE TITLE
fzf#wrap() ignores g:fzf_colors

### ISSUE THREAD

**Issue by sunaku** [junegunn/fzf#711]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [x] Vim
    - [x] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

The `fzf#wrap()` function provided in this repo currently ignores the `g:fzf_colors` setting in Vim. :see_no_evil:

To see a demonstration, run the following commands in either Vim or NeoVim :two_hearts: (they are both affected):

```vim
:let g:fzf_colors = { 'fg': ['fg', 'Error'] }
:Files ~/.vim
:call fzf#run(fzf#wrap('dot-vim', {'dir': '~/.vim'}, 0))
```

Notice that `:Files` honors the `g:fzf_colors` setting whereas the call to `fzf#wrap()` ignores it. :scream_cat:

Thanks for your consideration.

**Comment by junegunn** [comment]
Yeah, that's still only in fzf.vim. Perhaps because I'm not perfectly confident about the feature yet especially due to the new trend of using GUI color schemes in terminal Vim when fzf is unable to display true colors due to ncurses limitation. I'll look into this after #712.

**Comment by junegunn** [comment]
I just copy-pasted the code from fzf.vim project. Will remove it there once I release a new version of fzf.
