### ISSUE TITLE
Improve file search

### ISSUE THREAD

**Issue by damage220** [junegunn/fzf#713]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

First of all, thank you, fzf as fast as helpful, but sometimes there is an unexpected behavior when I do file searching (see images). This trouble occurs when you're working with namespaces. The problem is that fzf respect more directory names instead of filename. I think, it's not what user is expected. The proposition is to pay more attention to filename. I understand that fzf is abstract tool and doesn't work only with files so I propose to add third algorithm version (--algo=v3). It also saves backward compatibility.

![1](https://cloud.githubusercontent.com/assets/1643621/19625865/1b88231c-992d-11e6-8949-374f6de33ad2.png)
![2](https://cloud.githubusercontent.com/assets/1643621/19625864/1b7087de-992d-11e6-91d0-1f657f8e77c2.png)

**Comment by junegunn** [comment]
You'll get better result with `--tiebreak=end` or `--tiebreak=end,length`.

FYI, fzf used to evaluate `end` part using the absolute distance from the end of the string. I realized that it can yield unintuitive results so I changed it in https://github.com/junegunn/fzf/commit/0541c0dbcf96ff40bd80cb8359191dc0fa01d83d. The fix will be included in the next version that I'm going to release tonight.

**Comment by damage220** [comment]
`--tiebreak=end,length` is exactly what I was looking for. Thanks both for this and my previous issue.
