### ISSUE TITLE
Feature Request: cmd option

### ISSUE THREAD

**Issue by rainerborene** [junegunn/fzf#717]
Currently `fzf` only accepts input from `STDIN` I think it would be great to allow input via a flag like `--cmd`, and also provide an action to reload it.

For example,
```
fzf --cmd='ls -1' --bind=ctrl-r:reload --bind=ctrl-b:execute(rm {})
```

**Comment by kelleyma49** [comment]
You can overwrite the command by defining the environment variable `FZF_DEFAULT_COMMAND`.  Reload would be the only thing currently missing?

**Comment by rainerborene** [comment]
`FZF_DEFAULT_COMMAND` should work. `reload` action it's the only thing missing.

**Comment by junegunn** [comment]
When the list is reset, fzf has to reset everything inside the finder, cache, cursor position, and multiple selections. So you don't gain much compared to just restarting fzf like so:

```sh
while true; do
  IFS=$'\n' eval 'lines=( $(ls -1 | fzf --expect=ctrl-b) )' || break
  if [[ ${lines[0]} == ctrl-b ]]; then
    echo "delete ${lines[1]}"
    sleep 1
  else
    echo "selected ${lines[0]}"
    break
  fi
done
```

I don't think the benefit justifies the added complexity and the cost of synchronizing threads, so this is not something I'm interested in. Anyway, thanks for the suggestion.
