### ISSUE TITLE
Ubuntu installation through apt-get install

### ISSUE THREAD

**Issue by rmharrison** [junegunn/fzf#718]
- Category
  - [ ] fzf binary
  - [ ] fzf-tmux script
  - [ ] Key bindings
  - [ ] Completion
  - [ ] Vim
  - [ ] Neovim
  - [ ] Etc.
- OS
  - [x] Linux
  - [ ] Mac OS X
  - [ ] Windows
  - [ ] Etc.
- Shell
  - [ ] bash
  - [ ] zsh
  - [ ] fish

@junegunn: Would you be open to my adding fzf to the [PPA](https://help.launchpad.net/Packaging/PPA/InstallingSoftware) so that I can use `apt-get install` from Ubuntu?

**Comment by junegunn** [comment]
I have no good understanding of PPA, but it sounds like it's "personal" and thus non-official. Does making one require my permission or intervention?

**Comment by Kutsan** [comment]
+1

**Comment by kutsan** [comment]
There are PPA tutorials out there, should check them out. They are basically Homebrew for Linux. Once you publish a package users can install with `sudo apt install fzf` under Debian-based distributions.

**Comment by GregOriol** [comment]
It would be nice to have this indeed: using git doesn't work well for updating, you have to remember to update it manually, while apt is the usual stuff. Same goes for Linuxbew: it's a very nice tool but not so common (yet?) and you have to remember to update it separately from the usual stuff...

**Comment by Teknitix** [comment]
Has there been an update to this? Will FZF be made available in the Ubuntu / apt-get repositories?

**Comment by gliptak** [comment]
It is in the repos:

https://packages.ubuntu.com/search?keywords=fzf&searchon=names&suite=eoan&section=all

**Comment by joegreene** [comment]
> It is in the repos:
> 
> https://packages.ubuntu.com/search?keywords=fzf&searchon=names&suite=eoan&section=all

As of right now the package listed there is a bit out of date (0.18.0), although I'm not sure how big of an issue that is.

Also, if anyone uses this package and wants key bindings: after installing the repo navigate to `/usr/share/doc/fzf/README.Debian`. There are instructions in there for how to set them up for your respective shell.

For convenience, here are the (current) contents of that file:

<details>
  <summary>/usr/share/doc/fzf/README.Debian</summary>

```
Bash
====

Append this line to ~/.bashrc to enable fzf keybindings for Bash:

   source /usr/share/doc/fzf/examples/key-bindings.bash

Zsh
===

Append this line to ~/.zshrc to enable fzf keybindings for Zsh:

   source /usr/share/doc/fzf/examples/key-bindings.zsh

Fish
====

Issue the following commands to enable fzf keybindings for Fish:

   mkdir -p ~/.config/fish/functions/
   ln -s /usr/share/doc/fzf/examples/fish_user_key_bindings.fish ~/.config/fish/functions/

Vim
===

The most straightforward way is to append the following line to your vimrc:

   source /usr/share/doc/fzf/examples/fzf.vim

```
</details>

**Comment by mick-d** [comment]
@joegreene There is apparently a bug in this doc which does not include auto-completion instructions, and the official doc [here](https://salsa.debian.org/debian/fzf/blob/master/debian/README.Debian) should be used instead
