### ISSUE TITLE
About sort problem in search results

### ISSUE THREAD

**Issue by liangguohuan** [junegunn/fzf#719]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [x] Vim
    - [x] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

### search sample is here:
```
/h/h/dotfiles/gin  < 3/14
 > .gitignore
   .gitconfig
   .vim-plugin.vim

```
### expected
> file `.vim-plugin.vim` should be top

```
/h/h/dotfiles/gin  < 3/14
 > .vim-plugin.vim
   .gitignore
   .gitconfig
   

```

**Comment by junegunn** [comment]
It's expected. fzf prefers characters at the beginnings of the words.

```sh
# fzf prefers `oh-oh` even though the matched substring is longer
> (echo 'foo'; echo 'oh-oh') | fzf -f oo
oh-oh
foo
```

Refer to the following links:
- https://github.com/junegunn/fzf/issues/638
- https://github.com/junegunn/fzf/blob/master/src/algo/algo.go#L39
