### ISSUE TITLE
Building fzf on Ubuntu produces a binary without Unicode support

### ISSUE THREAD

**Issue by ivan** [junegunn/fzf#720]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux (Ubuntu 16.04.1)
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [x] fish

Installing `golang-1.6 libncurses5-dev libncursesw5-dev` on Ubuntu, then using

```
PATH=/usr/lib/go-1.6/bin:$PATH make fzf/fzf-linux_amd64
```

produces an `fzf` binary without Unicode support: all Unicode characters in the fzf UI are mangled instead of displayed correctly.

I managed to get a working binary after building with

```diff
diff --git a/src/curses/curses.go b/src/curses/curses.go
index 638a862..f93be0b 100644
--- a/src/curses/curses.go
+++ b/src/curses/curses.go
@@ -3,7 +3,7 @@ package curses
 /*
 #include <ncurses.h>
 #include <locale.h>
-#cgo !static LDFLAGS: -lncurses
+#cgo !static LDFLAGS: -lncursesw
 #cgo static LDFLAGS: -l:libncursesw.a -l:libtinfo.a -l:libgpm.a -ldl
 #cgo android static LDFLAGS: -l:libncurses.a -fPIE -march=armv7-a -mfpu=neon -mhard-float -Wl,--no-warn-mismatch
 
```

**Comment by junegunn** [comment]
I didn't change it to `ncursesw` because it doesn't exist on macOS and I build linux binaries with static tag. So try this instead:

```sh
PATH=/usr/lib/go-1.6/bin:$PATH TAGS=static make fzf/fzf-linux_amd64
```

**Comment by ivan** [comment]
Ah, great, thank you.

This might be worth mentioning in `src/README.md`, or spitting out some kind of warning, or just refusing to compile without Unicode support.  It's kind of tricky to track down the cause.  Anyway, thanks for fzf, I like it a lot.

**Comment by junegunn** [comment]
Yeah thanks, I'll probably have to refactor build tags once termbox build(#714)  is merged.
