### ISSUE TITLE
List submodules as well

### ISSUE THREAD

**Issue by supermarin** [junegunn/fzf#721]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [x] Vim
    - [x] Neovim
    - [x] Etc.
- OS
    - [x] Linux
    - [x] Mac OS X
    - [x] Windows
    - [x] Etc.
- Shell
    - [x] bash
    - [x] zsh
    - [x] fish

Currently if you have a project with git submodules, fzf will only list files of the root project.
Submodules could easily be read from the `.gitmodules` file in the project root.

Implementing this in fzf could make sense because you could traverse faster than doing a bunch of piped unix commands to get the file list.

**Comment by junegunn** [comment]
fzf is just a unix filter like grep and it's not really responsible traversing the file system. By default, it uses [find command](https://github.com/junegunn/fzf/blob/0.15.5/src/constants.go#L18) by default, but you can change it by setting `FZF_DEFAULT_COMMAND`.
