### ISSUE TITLE
toggle-preview hides header info

### ISSUE THREAD

**Issue by DanielFGray** [junegunn/fzf#722]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

```
fzf --header='foo bar baz' --preview='< {}' --bind='space:toggle-preview'
```

when the preview pane is toggled the header info disappears

**Comment by junegunn** [comment]
Good catch, thanks. Fixed it.

(A workaround for the old binaries is to hit CTRL-L to redraw the screen.)
