### ISSUE TITLE
Suggestion: highlight the entire line of selected result

### ISSUE THREAD

**Issue by andreypopp** [junegunn/fzf#723]
- Category
  - [x] fzf binary

The selected result should highlight the entire line, not only the text.

**Comment by vaz** [comment]
:+1:

**Comment by dmitriyK1** [comment]
👍

**Comment by sashoism** [comment]
For me this is the preferred behavior anyway. If anyone would like to pick it up and make it a configurable option for upstream, feel free :)

**Comment by junegunn** [comment]
`--highlight-line`
