### ISSUE TITLE
Suggestion: Wiki page for Fish examples

### ISSUE THREAD

**Issue by shkm** [junegunn/fzf#724]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [x] Etc.
- OS
    - [ ] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [x] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [x] fish

The wiki contains some fantastic examples, but many (all?) don't work under Fish. Would it be a good idea to have a fish-specific examples page?

I currently have two such examples in my dotfiles:
https://github.com/shkm/dotfiles/blob/master/.config/fish/functions/fco.fish
https://github.com/shkm/dotfiles/blob/master/.config/fish/functions/fssh.fish

**Comment by junegunn** [comment]
Makes sense. I added the page for fish shell. Feel free to update it.

https://github.com/junegunn/fzf/wiki/Examples-(fish)
