### ISSUE TITLE
ctrl-t to start from command-line argument

### ISSUE THREAD

**Issue by janpom** [junegunn/fzf#725]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [x] Key bindings
    - [x] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

First, thanks for this great tool. It's really handy. Here's a new feature proposal. I even include a draft implementation.

Scenario: I'm in my home directory (`~`). I'm looking for a file `foobar.txt` that I want to copy. So I go `cp <ctrl-t>foobar`... but it's not working because my home directory contains too many files and `find` is too slow listing them all. I know the file is somewhere in `~/projects/`. I wish I could type `cp projects/<ctrl-t>foobar` and `fzf` would start looking for the file from `~/projects/` rather than from `~`.

This may not seem so useful in this trivial example. One could simply `cd projects/` first, but imagine you're in a middle of a long command and need to specify a file parameter.

Anyway, I've been missing this feature so I hacked it together. The implementation is pretty lame (I'm not a shell programmer), but it seems to be working. All that's needed is modify the `__fsel` function. If you like the idea, feel free to use any of my code:
https://bitbucket.org/janpom/.dotfiles/src/8835152582ebcf0ad266448904587b87e8abf6ae/dotfiles/fzf.custom.zsh

**Comment by junegunn** [comment]
Have you considered using fuzzy completion instead for that purpose?

```sh
cp projects/**<tab>
```

You might want to take a look at https://github.com/junegunn/fzf/wiki/Fuzzy-completion#zsh if you don't like having to type in `**`.

**Comment by janpom** [comment]
Looks like I'm reinventing the wheel here. I didn't realize the `**<tab>` worked that way. The documentation sounded like it would substitute the pattern with the best match. I should have tested that. My bad.

I guess I still prefer `ctrl-t` to `**<tab>`. The fuzzy completion tip works for me. Thanks for the link! I can now remove the hack from my dot file.

Thanks for the quick response!

**Comment by junegunn** [comment]
No problem.
