### ISSUE TITLE
Add `$ man fzf` to README

### ISSUE THREAD

**Issue by eyalev** [junegunn/fzf#726]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [x] Etc.

Hi,

I think you should mention in the README that `$ man fzf` gives more documentation and examples.

For some reason I only thought about checking it out recently, and I wish I did it sooner.

**Comment by junegunn** [comment]
Thanks, I just updated the page.
