### ISSUE TITLE
Change history-size in fzf binary

### ISSUE THREAD

**Issue by kaatish** [junegunn/fzf#728]
- Category
    - [X] fzf binary
    - [X] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [X] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [X] bash
    - [ ] zsh
    - [ ] fish

I wish to increase the fzf history size from 1000 to something bigger. The command `fzf --history-size=N` does not seem to work for any N. I have tried a few numbers ranging from 100 to 10000. Is this really a problem or am I doing something incorrectly?

**Comment by junegunn** [comment]
`--history-size=N` should work with any N. If it doesn't, it's a bug. I just tested with some values, and it seems to work as expected. Have you tested with small values?

**Comment by kaatish** [comment]
Yes I have. I have attached a video [here](https://youtu.be/3n0ysuDdYps) which might explain what is going on. In the video I am pressing Ctrl-R and scrolling up as much as I can.

**Comment by junegunn** [comment]
That's bash history and unrelated to `--history` or `--history-size` of fzf.

http://superuser.com/questions/137438/how-to-unlimited-bash-shell-history
