### ISSUE TITLE
How do I change this color?

### ISSUE THREAD

**Issue by rainerborene** [junegunn/fzf#729]
![screen_shot_2016-11-07_at_13_42_43](https://cloud.githubusercontent.com/assets/101501/20063994/3e08413c-a4f0-11e6-8412-dd2d69a376ad.png)

I've tried to use `g:fzf_colors`but did not have any effect.

**Comment by junegunn** [comment]
Looks like you should have posted this in fzf.vim repo. Anyway,
- Do you have the latest version of fzf.vim?
- Which color scheme do you use? Does changing color scheme help?

**Comment by rainerborene** [comment]
I'm running the latest version of fzf.vim.  If I change the colorscheme to darkblue I can see the buffer number in a different color... But I've tried to change every color option and still not working.  I'm using the base16-twilight color scheme.

```VimL
let g:fzf_colors = {
      \ 'fg':      ['fg', 'Comment'],
      \ 'bg':      ['bg', 'Comment'],
      \ 'hl':      ['fg', 'Comment'],
      \ 'fg+':     ['fg', 'Comment', 'Comment', 'Comment'],
      \ 'bg+':     ['bg', 'Comment', 'Comment'],
      \ 'hl+':     ['fg', 'Comment'],
      \ 'info':    ['fg', 'Comment'],
      \ 'prompt':  ['fg', 'Comment'],
      \ 'pointer': ['fg', 'Comment'],
      \ 'marker':  ['fg', 'Comment'],
      \ 'spinner': ['fg', 'Comment'],
      \ 'header':  ['fg', 'Comment'] }
```

![screen shot 2016-11-08 at 19 24 32](https://cloud.githubusercontent.com/assets/101501/20117753/0f53e374-a5e9-11e6-8880-080fc903d4a3.png)

**Comment by junegunn** [comment]
What's the output of `:hi number`?

**Comment by rainerborene** [comment]
`:hi Number ctermfg=14` solved this issue. tnks
