### ISSUE TITLE
Start the history search with the word you typed at the prompt in bash

### ISSUE THREAD

**Issue by thiagotalma** [junegunn/fzf#731]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [x] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

I use hh and find it very useful to start the history search with the word that I typed before pressing `Ctrl+R`.

The hh command is defined as follows:
```
if [[$ - = ~. * I. *]]; Then bind ' "\ C-r": "\ C-a hh \ C-j"'; fi
```

I could do the same way with fzf overwriting the binding, but I would like to know if it is possible to get at this result using only the settings, without the need to override the binding.

**Comment by junegunn** [comment]
> if it is possible to get at this result using only the settings

Not currently. There is an open issue for the functionality: #432. Note that it is already implemented on zsh, but I was unable to find a clean solution for bash, especially while keeping bash 3 compatibility.
