### ISSUE TITLE
MINGW64 - character set not supported

### ISSUE THREAD

**Issue by anormann** [junegunn/fzf#734]
- Category
    - [x] fzf binary
    - [x] fzf built from source under mingw64
- OS
    - [x] Windows
- Shell
    - [x] bash

I get the following output in MINGW64:
$ fzf
character set not supported

It seems to work as expected in windows command prompt, both the premade binary and the one i built in mingw.

I couldn't find the string in the source, but it seems to be in the binary, so I'm guessing there's some included module that has issues. I tried to grep under /mingw64/lib/go and share/go, but couldn't find it.

Sorry to offer you such an unhelpful bug report.

**Comment by junegunn** [comment]
As far as I know, tcell library which fzf depends on does not support cygwin/msys.

https://github.com/gdamore/tcell#windows

You might want to consult with the author of tcell to see if there's any workaround.

/cc @kelleyma49

**Comment by Swoorup** [comment]
Through winpty I was able to get fzf working.
