### ISSUE TITLE
Extra characters `(B` with colored output

### ISSUE THREAD

**Issue by midchildan** [junegunn/fzf#735]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

### Symptom
Extra characters `(B` are shown when I use fzf to filter the results of ripgrep with colored output. 

### How to reproduce
Run `rg --vimgrep --color=always -i lorem | fzf --ansi`
I have attached the output piped to fzf [here](https://github.com/junegunn/fzf/files/587717/ansi.txt).

### Result
![result](https://cloud.githubusercontent.com/assets/7343721/20245286/40b16418-a9e1-11e6-8276-53c906ee3274.png)

**Comment by midchildan** [comment]
I did a `git bisect`, and it seems that commit 06a6ad8 is causing this problem.

**Comment by junegunn** [comment]
Thanks for looking into it. I have a good understanding of what's going on here. The ANSI processor of fzf only tries to process/strip out known ANSI sequences,  such as`\e[<COLOR/ATTR>m`, `^O`, and `^N`. But the output of ripgrep contains ANSI sequences that are not known to fzf, in this case, `\e(B`.

A quick googling reveals that it's a VT-100 code (http://www.comptechdoc.org/os/linux/howlinuxworks/linux_hlvt100.html), and I can update fzf to address that particular sequence, but obviously there are other code sequences of different lengths that fzf should process or ignore. Unfortunately I don't have a comprehensive list of such sequences, but I'll see what I can do.

**Comment by junegunn** [comment]
Hmm, comprehensive handling of escape sequences seems to require a non-trivial amount of work.

Excerpts from iTerm2:
- https://github.com/gnachman/iTerm2/blob/60e16c10c9e1acd18c6e683685356b0d4842d123/sources/VT100ControlParser.m#L62
- https://github.com/gnachman/iTerm2/blob/60e16c10c9e1acd18c6e683685356b0d4842d123/sources/VT100CSIParser.m#L382
- https://github.com/gnachman/iTerm2/blob/60e16c10c9e1acd18c6e683685356b0d4842d123/sources/VT100OtherParser.m#L28
- https://github.com/gnachman/iTerm2/blob/60e16c10c9e1acd18c6e683685356b0d4842d123/sources/VT100AnsiParser.m#L18

**Comment by junegunn** [comment]
- http://ascii-table.com/ansi-escape-sequences.php
- http://ascii-table.com/ansi-escape-sequences-vt-100.php

**Comment by junegunn** [comment]
Just pushed the fix. I'll release the new version in a few days. Thanks for the report.
