### ISSUE TITLE
ctrl t and alt c return empty screen

### ISSUE THREAD

**Issue by SoukyuuKa** [junegunn/fzf#736]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [x] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [ ] Mac OS X
    - [x] Windows
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

Hi, I am really new to bash shell and vim. I am running on a windows subsystem linux. I installed fzf and everything worked as expected. However, when I tried to use ctrl + t or alt + c in the terminal it gives me an empty list, Like below. My ctrl + r works fine though. Any suggestion on the issue? Thanks.
![image](https://cloud.githubusercontent.com/assets/23441543/20250208/803ab7d2-aa46-11e6-96aa-2a0cf90b2394.png)
![image](https://cloud.githubusercontent.com/assets/23441543/20250219/ac674a82-aa46-11e6-9d81-547e5796da85.png)

**Comment by junegunn** [comment]
Hmm, you're right. I'm seeing the same issue. The problem seems to be that the underlying find command fails on WSL with this message: `find: Cannot read mounted file system list`. I have no idea what this means and how to fix it yet but it is easily reproducible with the following command:

```sh
find . -printf %F
```

Do you see the same error?

**Comment by SoukyuuKa** [comment]
You are right. It didn't read any file system list.
![image](https://cloud.githubusercontent.com/assets/23441543/20279420/7513c2ac-aae3-11e6-88a0-ce816b9c9d22.png)
I found that fzf command alone works fine and will list all the files in the current directory. Except I can't append the file name after my command. Maybe you can come up with a work around?
![image](https://cloud.githubusercontent.com/assets/23441543/20279568/f9433742-aae3-11e6-9b9a-80a3f5f74255.png)

**Comment by junegunn** [comment]
`sudo ln -s /proc/self/mounts /etc/mtab` fixes the issue for me. Can you try it?

Reference: https://github.com/Microsoft/BashOnWindows/issues/150

**Comment by SoukyuuKa** [comment]
Wow it works perfectly now. Thank you very much. And FZF is truly an amazing plugin.

**Comment by cocoonkid** [comment]
@junegunn 

Apology for necrobumping this but just today I had the same issue inside a lxc container.

![image](https://user-images.githubusercontent.com/43231640/231725374-92d1ee3a-4070-4994-9965-cd98857439a6.png)
