### ISSUE TITLE
Customizing the scoring algorithm

### ISSUE THREAD

**Issue by ahmedre** [junegunn/fzf#737]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [x] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

Thanks for writing fzf, and I apologize in advance if this is already answered somewhere. I have recently started using fzf, and one thing I wish is that the score for "full matches" would be higher than the score for fuzzy matches.

Let me explain with an example - in my shell, I hit ctrl+r and see:

<img width="487" alt="screen shot 2016-11-15 at 12 48 42 am" src="https://cloud.githubusercontent.com/assets/47771/20298929/53ae3f5e-aacd-11e6-93ab-e7d28a237ab5.png">

Awesome, so I type in "amend" and I get this:

<img width="335" alt="screen shot 2016-11-15 at 12 49 44 am" src="https://cloud.githubusercontent.com/assets/47771/20298948/74593e84-aacd-11e6-9a9a-ce12e674e15a.png">

In this case, it's awesome that fzf found most of the letters in the gradle command I had recently used, but I really wanted 1689 in this case, `git commit --amend`, without the extra keystroke. This is just one case that I've ran into, but I've ran into similar other cases in the past few days when using fzf as ctrl+r for my shell.

Is it possible to score exact matches higher than partial matches (if not, may you consider it a feature request?)

Thanks!

**Comment by ahmedre** [comment]
i missed #638 - i'll take a look at that and the source and will reopen if i can't figure this out - thanks again!

**Comment by junegunn** [comment]
Hmm, no I don't think it's the right solution to your problem. See: https://github.com/junegunn/fzf/wiki/Configuring-shell-key-bindings#ctrl-r

**Comment by ahmedre** [comment]
thank you!
