### ISSUE TITLE
stty echo was disabled after suspend vim via CTRL-Z

### ISSUE THREAD

**Issue by zxdvd** [junegunn/fzf#740]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [x] Key bindings
    - [x] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

Steps to reproduce:
1. using vim to open a file find by fzf CTRL-T.
2. suspend the vim by CTRL-Z
3. stty echo was diabled

stty result after CTRL-Z
```
$ speed 9600 baud;
lflags: -icanon -echo echoe echoke echoctl
iflags: -icrnl iutf8
oflags: -oxtabs
cflags: cs8 -parenb
dsusp   lnext
<undef> <undef>
```

my origin stty
```
$ stty
speed 9600 baud;
lflags: echoe echoke echoctl pendin
iflags: iutf8
oflags: -oxtabs
cflags: cs8 -parenb
```
Command `less` got this problem too.

**Comment by junegunn** [comment]
I can't reproduce whether I'm on tmux or not. The output of `stty` stays the same.

**Comment by zxdvd** [comment]
It seems there is something wrong with tmux.
I can reproduce it on both osx and debian with tmux. But it works well without tmux.

**Comment by justinmk** [comment]
Does fzf (or go) modify `O_NONBLOCK`? Neovim had a similar issue, fixed recently: https://github.com/neovim/neovim/issues/5560
