### ISSUE TITLE
function key binds no longer work?

### ISSUE THREAD

**Issue by davidosomething** [junegunn/fzf#741]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [x] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

Previously I had `<f2>` bound to `:Buffers` in fzf.vim
Since `<f2>` triggers `^[OQ^C`, it technically hits `<esc>` and can close the FZF `:term` on its own (`<f2>` to open, `<f2>` or `<esc>` to close)

Now in 0.15.8 the function keys are not read the same, and even `--bind=f2:abort` does not work in an `fzf#run()` options.
How can I bind `<f2>` (and f3,f4,etc) to close fzf.vim `:term`s?

**Comment by junegunn** [comment]
Since 0.15.8, fzf relies on ncurses to interpret escape sequences for function keys. And it works as expected on terminal: `fzf --bind f2:abort`. So the problem you have seems to be an issue of Neovim terminal. Maybe this? https://github.com/neovim/neovim/issues/4343

**Comment by davidosomething** [comment]
Yes, it's a neovim terminal only issue -- that might be related

**Comment by junegunn** [comment]
Looks like there's ongoing work on fixing the issue: https://github.com/neovim/neovim/pull/5014

Until it's fixed in neovim, a workaround would be to remap function keys to another key chords that fzf understands.

```vim
autocmd FileType fzf tnoremap <buffer> <f1> <c-c>
```

**Comment by davidosomething** [comment]
that works for me, thanks for solution!
