### ISSUE TITLE
curses gem is not installed

### ISSUE THREAD

**Issue by j5shi** [junegunn/fzf#742]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

I tried to install fzf on my RaspberryPi (Debian based OS), after installation, when I launch fzf it complains "curses gem is not installed...", I actually installed it as suggested `gem install curses` and `gem list` showed `curses (1.0.2)`. also `gem which curses` showed `/usr/lib/ruby/1.8/arm-linux-eabihf/curses.so`. I don't know what was wrong.

**Comment by junegunn** [comment]
What is the output of `uname -sm` command? curses gem requirement is for the legacy Ruby version which is only selected by the install script as the last report when all the other options are not available. Can you post the full output of the install script?

**Comment by j5shi** [comment]
Here's what I got:
`> uname -sm`
`Linux raspberrypi 4.1.7-v7+ #817 SMP PREEMPT Sat Sep 19 15:32:00 BST 2015 armv7l GNU/Linux`

**Comment by junegunn** [comment]
Take a look at: https://github.com/junegunn/fzf/issues/685

According to the comment, you should be able to build fzf from source on Raspberry Pi if Go is installed.

**Comment by junegunn** [comment]
Try this:

1. Install go
2. Clone fzf repo
3. cd src && TAGS=tcell make install
    - Build with tcell not to require ncurses

**Comment by junegunn** [comment]
I'll close this as fzf now provides ARM binaries.
