### ISSUE TITLE
Using fzf inside other go programs

### ISSUE THREAD

**Issue by lucymhdavies** [junegunn/fzf#743]
I would like to leverage the power of fzf for my own go program.
i.e. I want the user to be able to use fzf to select from a list.

Currently I'm using tui.Menu for this purpose

```
// accts is a []string
x := tui.Menu("Select account", nil, accts...)
```

From looking around the FZF code, I can't figure out if this is doable, or if such a thing would require changes to the FZF code.

In the case of the latter, I'm willing to make those changes myself and PR them, if you can provide some pointers :)

**Comment by junegunn** [comment]
fzf is not designed to be used as an embeddable library. But you can shell out and run it as an external process. Take a look at this post: http://junegunn.kr/2016/02/using-fzf-in-your-program/

**Comment by lucymhdavies** [comment]
Thanks.

It's not ideal, but it'll work well enough.
It does mean my app will need to install fzf (but I can get around that limitation by using fzf in a docker container).

I'll see what I can come up with :)
