### ISSUE TITLE
Keybinding Ctrl+T provides empty result

### ISSUE THREAD

**Issue by sdaschner** [junegunn/fzf#744]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [X] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [ ] fish

I just tried out fzf today (I like the idea!), however when hitting `^T` in zsh I get the fzf view but with an empty result (0/0). Invoking `$> fzf` directly works as expected. I reinstalled (several times) with  `git clone` and `install`, and also by the fzf package on ArchLinux. I get the same issues on a Debian system. Could you tell me what I'm doing wrong or how can I debug this problem?

**Comment by junegunn** [comment]
CTRL-T by default uses the following command to populate the list. Does it work?

```sh
command find -L . \( -path '*/\\.*' -o -fstype 'devfs' -o -fstype 'devtmpfs' -o -fstype 'proc' \) -prune \
    -o -type f -print \
    -o -type d -print \
    -o -type l -print 2> /dev/null | sed 1d | cut -b3-
```

**Comment by sdaschner** [comment]
No that's just an empty output in zsh.

**Comment by junegunn** [comment]
It is a valid command on zsh (works fine for me), so you'll have to figure out why the command does not give you proper result.
