### ISSUE TITLE
Precompiled binary for 0.15.9?

### ISSUE THREAD

**Issue by chdiza** [junegunn/fzf#746]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

Will there be a precompiled binary release for 0.15.9?  I see that the latest available one on junegunn/fzf-bin/releases is 0.15.8.

**Comment by junegunn** [comment]
It was already there, but I forgot to make a separate commit for 0.15.9 so it was listed below 0.15.8. I updated the tag and force-pushed to fix the order. Thanks.

https://github.com/junegunn/fzf-bin/releases
