### ISSUE TITLE
Bind Space Key to abort while keeping text?

### ISSUE THREAD

**Issue by codezapper** [junegunn/fzf#748]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [X] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [ ] fish

This is just a suggestion. I think it'd be nice to be able to use the `Space` key to abort, but still keep what was written by the user. That way, a user could assign `Space` instead of Ctrl+T and have the fuzzy search start immediately.

For example, something like `ls[space]-l[space]dir/file` would trigger fzf on the first space, but hitting it again would go back to the command line keeping `ls -l` and hitting space again would start fzf again, only this time the user could actually search for the file.

Sorry, I'm not sure I explained it clearly.

I've tried to make the change by myself with no luck (I'm more of a Perl developer these days).

**Comment by junegunn** [comment]
Thanks for the suggestion. Unfortunately I think we won't be able to find a simple solution.
