### ISSUE TITLE
Messy looking prompt (shows directory instead of >)

### ISSUE THREAD

**Issue by kendagriff** [junegunn/fzf#754]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [x] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [x] fish

In Vim, my fzf prompt looks like this:

<img width="722" alt="screen shot 2016-12-01 at 11 30 17 pm" src="https://cloud.githubusercontent.com/assets/110935/20825076/dcb9b428-b81e-11e6-8915-ba9ed94394f0.png">

In the fish shell, however, it looks like this:

<img width="712" alt="screen shot 2016-12-01 at 11 35 51 pm" src="https://cloud.githubusercontent.com/assets/110935/20825092/fe28379c-b81e-11e6-9dd4-a05a40b6502f.png">

What have I done to mess up my prompt in Vim?

Thanks for any help – I love FZF!

**Comment by junegunn** [comment]
> What have I done to mess up my prompt in Vim?

It's intentional.`:FZF` (or `:Files` command from fzf.vim project) can be started with an optional path argument (e.g. `:FZF ~/Downloads`) and the files are listed relative to the directory, so the prompt shows which directory fzf is currently looking at. I personally like it better than just `>` because it gives the context of the search. The prompt of FZF command is not currently configurable, but that of (almost equivalent) Files command (from fzf.vim) can be redefined using `fzf#vim#files` function.

I just updated the Vim plugin to further shorten the path in the prompt. `/U/k/...` will be shown as `~/...`.

**Comment by kendagriff** [comment]
K, thanks, glad to hear it's set up correctly.

Admittedly, I liked it better as it was. When I'm in Vim, I'm already aware of the parent search directory, and prefer less noise.

**Comment by net** [comment]
@junegunn I'm not sure how to redefine `fzf#vim#files` as it calls `s:fzf`.

I too would love to see a cleaner interface. Replacing the vim prompt with a single character (e.g. `/`) would be a great option to have. The ability to remove the red pointer and grey line on the left side, and  the file count (`202/202`) would also nice.

Aesthetics complaints aside though, fzf is really impressive!

**Comment by junegunn** [comment]
Since the original question is answered, I'll close the issue.

@net Using it, not redefining it like so:

```vim
call fzf#vim#files('.', {'options': '--prompt "==>> " --inline-info'})
```

I'll think about your suggestions, but note that I've been conservative on adding more options. I'll link my previous comment on that issue here: https://github.com/junegunn/fzf/issues/692

**Comment by net** [comment]
@junegunn I understand your concerns, but Vim is by nature highly customizable. It should follow that its plugins be the same. My Vim, as is many other's, is set up to have a specific look. Fzf.vim is the best fuzzy finder available, but its visual complexity clashes with my Vim's style.

I know that fzf is not just a Vim plugin; the same argument follows for bash/zsh. I have no doubts that more visual customization options would be greatly welcome and widely used by many—if not most—of fzf's users.

**Comment by davidosomething** [comment]
@net you can customize the colors -- make them the same as your background color and they're essentially hidden

**Comment by net** [comment]
@davidosomething I tried that with no success. Enabling `--color 16` did hide the grey background, but I have been unable to hide the red `>`. Even so, the file list would then appear arbitrarily indented, which is not ideal.

**Comment by junegunn** [comment]
> Vim is by nature highly customizable

Well, I don't agree that it is so regarding its presentation style. What else can you do except the colors and the status line? You can't change the tilde characters beyond the end of a file, you can't change the margin between the line numbers and the text area, you can't change the height of the statusline and the tabline, you can't change the width of sign column, no configurable margins and paddings, to name a few.

Anyway for now, you might want to try the following options.

```sh
fzf --color pointer:0,bg+:-1,info:0,prompt:0 --inline-info

fzf --no-color --inline-info
```

**Comment by net** [comment]
That worked pretty well, thanks! It's not perfect, since my terminal is slightly transparent, but it's good enough.

I guess you're right about Vim. I never wanted to changes those things, so I never knew you couldn't. I made assumptions from the variety of plugins available.

Thanks again for the help! 😄

**Comment by gennaro-tedesco** [comment]
I have come across this issue trying to customise the look of the prompt as well: would it be possible to add the configurable options to the documentation, at least? It is arguably quite hidden that one should
```
call fzf#vim#files('.', {'options': '--prompt "==>> " --inline-info --no-color'})
```
or perhaps it is already there and I missed it in the docs?
