### ISSUE TITLE
Allow CTRL-T pick up the word at cursor and root the find there

### ISSUE THREAD

**Issue by quite** [junegunn/fzf#755]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [x] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

- Make sure that you have the latest version of fzf
- If you use tmux, make sure $TERM is set to screen or screen-256color
- For more Vim stuff, check out https://github.com/junegunn/fzf.vim

Describe your problem or suggestion from here ...
-->

It would be really cool if the fzf completion fzf-file-widget could take the current word at the cursor as a path for where __fsel should operate. That means essentially to root the find operation not in cwd, but in the path of choice.

That way I could do like:
  ```~/bar>``` less /usr/local/share/doc/ CTRL-T { fzf starts listing files down in /usr/local/share/doc/ }

**Comment by junegunn** [comment]
You can do that with fuzzy completion: `less /usr/local/share/doc/**<tab>`. And since you use zsh, you can configure CTRL-T as the completion trigger key. See https://github.com/junegunn/fzf/wiki/Configuring-fuzzy-completion#zsh
