### ISSUE TITLE
FZF not showing any files in vim OSX

### ISSUE THREAD

**Issue by brentluna** [junegunn/fzf#761]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [x] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

When I try to run :FZF in vim in either iterm2 or terminal, it opens the window, however it shows 0 files, when there are files. Running fzf in those same terminals, outside if vim works fine. I can't seem to find a solution for this. I use same setup on my arch linux desktop and it works fine.

**Comment by junegunn** [comment]
Can you present a minimal Vim configuration file that can be used to reproduce the problem?

**Comment by brentluna** [comment]
I ended up fixing it, by deleting my .vim folder and reinstalling everything. I was syncing the .vim folder via github, so maybe something was installed OS specific and caused an issue? Anyways, I added .vim to my .gitignore, so hopefully won't be an issue again.
