### ISSUE TITLE
fzf_key_bindings not getting executed

### ISSUE THREAD

**Issue by kyleholzinger** [junegunn/fzf#762]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [x] fish

In fish, when I install fzf it doesn't automatically enable the key bindings. Each time I start a new shell I have to run `fzf_key_bindings` in order to register them. Not sure if this is an issue with fish or fzf, but any idea what the solution is? `fzf_key_bindings` is in my `~/.config/fish/functions/fish_user_key_bindings.fish` script, so not sure what's going on.

**Comment by kyleholzinger** [comment]
Nvm, I'm a dumb dumb. Defined the function `fish_user_key_bindings` elsewhere so it was calling the wrong one.

**Comment by HolyGrace** [comment]
Up

**Comment by kyleholzinger** [comment]
I deleted my definition of `fish_user_key_bindings` lol @HolyGrace
