### ISSUE TITLE
fzf completely reindexes on every Ctrl+T

### ISSUE THREAD

**Issue by madstanners** [junegunn/fzf#763]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [x] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

I have a number of branches from an SVN repository checked out. Sometimes I need to compare files from different versions, but frustratingly `fzf` reindexes every time when I use the Ctrl+T shortcut. I may also be doing something wrong here, but I've tried searching zsh/fzf caching/indexing but have found nothing.

**Comment by junegunn** [comment]
fzf is a filter (think of it as an interactive version of grep) and is not responsible for indexing the file system. It's beyond the scope of this project. For CTRL-T, it simply reads the output of the command specified in `FZF_CTRL_T_COMMAND` which defaults to [a find command](https://github.com/junegunn/fzf/blob/16b5902aa278639fd99be89abe8ac50eb49b34aa/shell/key-bindings.zsh#L7-L10).

Set `FZF_CTRL_T_COMMAND` to a smarter command that caches the result.
