### ISSUE TITLE
Is there any way to run fzf as a daemon via API?

### ISSUE THREAD

**Issue by sandric** [junegunn/fzf#764]
I wish I could write `ivy` counsel mode for `fzf` in emacs, because term support in emacs is horroble so everything is messed up in output. Is there any way to run fzf as a daemon and send commands to it, so it will give away list of founds in some kind of format?
Or maybe you know other projects that make workaround for that, I saw you made vim plugin for fzf, I know nothing aboud VimL, can you explain please how it works there, you dumping output to some temporary file?

**Comment by junegunn** [comment]
To answer the question, no. Have you checked https://github.com/bling/fzf.el ?

**Comment by sandric** [comment]
Yes, I'm actually used it, but soon my own config overgrowth this wrapper, so I wrote my own wrapper for it. I was thinking about using the same way as ivy uses ag command with wrapper but haven't succeed - I know little about shell programming, but suggests its because ag prints strictly to console while fzf have much more complicated rendering logic.

**Comment by jojojames** [comment]
+1 to this. Decoupling the search/sorting from the UI frontend would let this be useable on Emacs. fzf.el isn't great since it has to use the term support.
