### ISSUE TITLE
Use `select-1` and `exit-0` by default?

### ISSUE THREAD

**Issue by Ambrevar** [junegunn/fzf#766]
What about adding the `select-1` and `exit-0` to the existing widget?

**Comment by junegunn** [comment]
I can definitely see the appeal, but it can be confusing to the new users. I think it's enough that we suggest some good examples of `FZF_XXX_OPTS` in the wiki page.

**Comment by junegunn** [comment]
Added a section to the page:

https://github.com/junegunn/fzf/wiki/Configuring-shell-key-bindings#using---select-1-andor---exit-0

Thanks for the nice suggestion.
