### ISSUE TITLE
Append '/' to folders in the file widget?

### ISSUE THREAD

**Issue by Ambrevar** [junegunn/fzf#767]
This would help differentiating folders from files.

Besdies, writing a folder with an appended slash on the commandline is usually what the user wants: the user can keep on completing/fzf-ing, it saves one key stroke :)

Implementation is easy: replace `-o -type d -print` with `-o -type d -printf '%p/\n`.

**Comment by junegunn** [comment]
Makes sense, but the sad truth is find command of macOS does not support `-printf` :/

**Comment by Ambrevar** [comment]
What about this then:

```
find ... -type d -exec printf '%s/\n' {} + ...
```

The `+` will make sure to spawn only one `printf`, so this shouldn't be any slower.

**Comment by junegunn** [comment]
Great, I like it 👍
You want to make a pull request? Or I can do that.

**Comment by Ambrevar** [comment]
I can make a PR, but this will conflict with #759 . You should merge that one first.

**Comment by Ambrevar** [comment]
Done.
