### ISSUE TITLE
Wrong characters displayed under tmux

### ISSUE THREAD

**Issue by wilywampa** [junegunn/fzf#77]
I tried fzf today on a PC running mintty/Cygwin and on my laptop running iTerm2/OS X and had the same problem both places. The results that come up as I'm typing are corrupted until I scroll through them or type Ctrl-L. This happens in tmux if I run fzf using the Ctrl-R key binding or if I run fzf just as 'fzf' from the command line. It does NOT happen when I invoke it with the Ctrl-T key binding (which opens up a new tmux pane). It also does not happen if I run fzf outside of tmux. I tried it with my .tmux.conf completely blank and that didn't help.

On my laptop I am running zsh 5.0.5, tmux 1.9a (I also tried a newer dev build of tmux, same results), and ruby 2.0.0p451.

Any ideas?

Here's what it looks like before/after redrawing with Ctrl-L:

![screen shot 2014-07-09 at 7 05 00 pm](https://cloud.githubusercontent.com/assets/4472522/3533660/c94e4a98-07d6-11e4-9264-dabc0c8ec372.png)
![screen shot 2014-07-09 at 7 05 10 pm](https://cloud.githubusercontent.com/assets/4472522/3533663/ce8b5eec-07d6-11e4-8050-ecc194df33d0.png)

**Comment by unphased** [comment]
Any idea how I should address this issue? I need to use `xterm-256color-italic` to get italics in vim (for comments). So I want to override my `$TERM` only when fzf is in use.

I find that `TERM=screen-256color fzf` works wonderfully when I run it in the shell, so I'll  just need to find out how to get it to do that with the key binds.

**Comment by junegunn** [comment]
@unphased Have you tried the method on the following page?
https://alexpearce.me/2014/05/italics-in-iterm2-vim-tmux/

**Comment by unphased** [comment]
I have not seen such a recommendation to make a screen-256color-italic terminfo, but it seems very straightforward to do so. Do you think this will also fix the tmux rendering problem? My workaround is pretty simple and seems to be working -- I just edited the `~/.fzf.zsh` and all its calls to `fzf` to `TERM=screen-256color fzf`.

**Comment by junegunn** [comment]
@unphased I haven't tried the solution nor italics on terminal so I don't know, but probably. It looks like you won't have to edit ~/.fzf.zsh or Vim plugin if it works. Can you try it and let me know how it goes?

**Comment by unphased** [comment]
I would love to try it.. but I think i've spent way too much time (all of Saturday!) reorganizing and rewriting things for my environment, and I have to work on something else today. 

Do you know if it is something that tmux does that specifically requires the `$TERM` to start with `screen` that addresses the issue?

I still have to keep my own unique `~/.fzf.zsh` because I don't use `fc -l 1` for the history list, i use my own python script for it. This way, it loads all my 50K and growing history entries from disk for browsing with fzf without having zsh load all of them every time I start zsh, saving memory and time.

**Comment by junegunn** [comment]
@unphased 

> Do you know if it is something that tmux does that specifically requires the $TERM to start with screen that addresses the issue?

Well, see here: http://tmux.cvs.sourceforge.net/viewvc/tmux/tmux/FAQ

> ******************************************************************************
> * PLEASE NOTE: most display problems are due to incorrect TERM! Before       *
> * reporting problems make SURE that TERM settings are correct inside and     *
> * outside tmux.                                                              *
> *                                                                            *
> * Inside tmux TERM must be "screen" or similar (such as "screen-256color").  *
> * Don't bother reporting problems where it isn't!                            *
> *                                                                            *
> * Outside, it must match your terminal: particularly, use "rxvt" for rxvt    *
> * and derivatives.                                                           *
> ******************************************************************************
