### ISSUE TITLE
Ctrl-T broken: Quotation marks around result for fish shell  

### ISSUE THREAD

**Issue by localhostport80** [junegunn/fzf#770]
- Category
    - [X] fzf binary
    - [ ] fzf-tmux script
    - [X] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [X] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [X] fish

All the bindings work as expected apart from Ctrl-T for file search which wraps the result in quotation marks.

I tried to add the "-e" flag to __fzfcmd.fish in .config/fish/functions but this did not help. Any ideas? Because the wrapping quotations are breaking the whole key bindings for me.

I installed fzf via homebrew and the fish fzf plugin using fisherman.

**Comment by junegunn** [comment]
As far as I know, it only wraps when the selected entry contains spaces or characters that need to be escaped. Are you saying that it wraps unconditionally?
