### ISSUE TITLE
Killing fish running fzf creates a CPU hog

### ISSUE THREAD

**Issue by Ambrevar** [junegunn/fzf#772]
- Category
    - [x] fzf binary
- OS
    - [x] Linux
- Shell
    - [x] fish

When calling fzf from a fish function that has some termination code, killing the terminal will reparent fzf and create a CPU hog. Very annoying :(
The bug is described extensively here: https://github.com/fish-shell/fish-shell/issues/3644.

According to some fish developers, all sides are to blame: fzf seems to ignore EOF when it reads from TTY. I haven't checked this for myself, but there might be something to investigate at least. Can you confirm?

**Comment by Ambrevar** [comment]
After further investigation (see the fish issue linked above), it seems that fzf is not involved here, but rather ncurses. The `--height option` makes this somewhat obsolete anyways. Closing.

**Comment by junegunn** [comment]
Alright, thanks for the investigation.
