### ISSUE TITLE
_fzf_complete API not working correctly

### ISSUE THREAD

**Issue by Mike-Now** [junegunn/fzf#773]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [x] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

The example [pass] using the experimental API [_fzf_complete] doesn't work. It allows single autocompletion with fzf, but then falls back to the default autocompletion permanently. 

The reason for this behavior is the shell/completion.bash script that tries to source the script that's currently running not itself. The following patch fixes the problem:

```
112c112
<     source "~/.fzf/shell/completion.bash"
---
>     source "${BASH_SOURCE[0]}"

```

However, it's not a pretty solution. I think fzf could set it's root directory as a hardcoded variable during installation. Or append env variable FZF_ROOT_DIR to .bashrc.

**Comment by junegunn** [comment]
Hi, the example works fine for me. I'm not sure if I understood your description of the problem. Can you provide the exact steps to reproduce it? Or it just doesn't work for you?

**Comment by Mike-Now** [comment]
In my dotfiles I source a file with completions like so:
`
source ~/.bash/completions
`
It doesn't work when completions are sourced as a separate file from .bashrc.
It does work when the code is directly in the .bashrc.

The information that the completion function that uses `_fzf_complete` API should be in the file that eventually sources `~/.fzf.bash` could be added to the wiki.

**Comment by Mike-Now** [comment]
The issue appears to be resolved (or was a mistake on my part).
