### ISSUE TITLE
Make setting MANPATH optional

### ISSUE THREAD

**Issue by mklein994** [junegunn/fzf#774]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [x] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

Arch Linux leaves $MANPATH unset by default, so that `manpath` can find the man pages. Setting $MANPATH in the install script breaks bash completion, because $MANPATH just becomes `:${fzf_base}/man`. To fix this, I did:
``` bash session
$ ln -s ~/.fzf/man/man1/fzf{,-tmux}.1 ~/.local/share/man/man1
```
&hellip;which is picked up by `manpath`. Now all that's needed is for the install script to have an option not to set $MANPATH.

I could submit a pull request, if you want.

**Comment by junegunn** [comment]
Thanks for the report. I just realized that we don't even need to do anything, as man can figure out which path to look at if `fzf/bin` is inside $PATH.

> man looks at the PATH variable and adds the corresponding directories to the manual page file search path.

Even without $MANPATH, I can see that man succeeds to find the man page for fzf (`man -d fzf`).

```
path directory /Users/jg/.vim/plugged/fzf/bin is not in the config file
but there is a man directory nearby
adding /Users/jg/.vim/plugged/fzf/man to manpath
```

**Comment by junegunn** [comment]
Updated install script to generate fzf.{bash,zsh} without MANPATH update. Let me know if you still see any issues. Thanks!
