### ISSUE TITLE
FZF blocks Vim while opened in tmux pane

### ISSUE THREAD

**Issue by toiffel** [junegunn/fzf#775]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [x] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

Steps to reproduce:

1. Run Vim inside tmux
2. Run FZF
3. Switch back to Vim pane
4. Type any characters

Expected: Vim consumes typed characters as usual
Observed: Vim is blocked and typed characters are echoed on the screen until FZF is closed

![fzf](https://cloud.githubusercontent.com/assets/1043953/21285819/7a6e8b76-c46d-11e6-9523-8d8b069f10d1.png)

This issue per se is not so important but it causes another bugs: https://github.com/junegunn/fzf/issues/434, https://github.com/tmux-plugins/vim-tmux-focus-events/issues/2. With `set -g focus-events on` tmux sends FocusIn/FocusOut escape sequences (`<Esc>[I` and `<Esc>[O`) to Vim instance. But since Vim is blocked by FZF, these escape sequences are echoed on the screen as `^[[I` and `^[[O`.

By default, Neovim doesn't have such issues because FZF is running asynchronously in separate terminal. But in Vim FZF is invoked with blocking system() call.

https://github.com/junegunn/fzf/blob/master/plugin/fzf.vim#L395

Would it be possible to have the same asynchronous FZF behavior in Vim as well, e.g. by using Vim 8 job API?

**Comment by junegunn** [comment]
I'm not sure if I want to rewrite Vim plugin to work in asynchronous manner, as it complicates the implementation without obvious benefit (and also because I don't use the tmux plugin). Have you tried the workaround suggested in https://github.com/tmux-plugins/vim-tmux-focus-events/issues/2#issuecomment-87863831?

**Comment by toiffel** [comment]
Yes, I've tried this workaround but unfortunately it doesn't work for me. Once I open FZF, leftover characters begin to appear.

Another affected plugin is https://github.com/christoomey/vim-tmux-navigator. Again, navigation works fine until I open FZF. While it's opened, I can't switch from Vim to other panes using vim-tmux-navigator because Vim is blocked.

I could give async FZF invocation a try using Neovim implementation as an example. At first glance, it doesn't seem to be so hard. Can you please point me out any clues/caveats here?
