### ISSUE TITLE
Suggestion: add frequency support

### ISSUE THREAD

**Issue by co-dh** [junegunn/fzf#777]
Hello: 
   I've being use it for a while and I like it. It's fast and works very well in neovim.
I'm wondering if you can add frequency support, with most used items at top.

Thanks in advance.

**Comment by junegunn** [comment]
It's beyond the scope of the project. Some pointers:

- https://github.com/rupa/z
- https://github.com/clvv/fasd
- https://github.com/junegunn/fzf/wiki/Examples#z
