### ISSUE TITLE
Scrolling down with mouse does not work

### ISSUE THREAD

**Issue by Chrysostomus** [junegunn/fzf#778]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [ ] fish

Scrolling down with mouse wheel/touchoad does not work. Regardless of terminal emulator and use of tmux

**Comment by junegunn** [comment]
Works for me. Please mark the check boxes.

**Comment by Chrysostomus** [comment]
I did already,  but they don't seem to be sticking.

**Comment by junegunn** [comment]
I have no experience with Manjaro linux so I don't think I can be of help here. Let's hope someone with Manjaro experience chimes in.

**Comment by Chrysostomus** [comment]
I'm afraid that is me, since I was one to include in the repos from aur... 

This is the PKGBUILD of the package :
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=fzf-git

Could this be an issue with ncurses?

**Comment by junegunn** [comment]
Does mouse work in other terminal programs that support it, like tmux and vim?

**Comment by Chrysostomus** [comment]
It does.

**Comment by Chrysostomus** [comment]
This has been solved with one of the updates, don't know which one.
