### ISSUE TITLE
Count-in selection frequency when offering closest matches

### ISSUE THREAD

**Issue by sshtmc** [junegunn/fzf#78]
Hi,

Thanks for this great tool, it's one of the few I use frequently for some time now.
What would be very cool for me is to give more weight/importance to the most-selected history entries. 
It should not be too difficult to do it, but it probably would be much faster for you to do it, than for me, since you already know the code.
The good thing is that you don't have to make this weight (the count of recent selections) persistent across sessions. For the first implementation, you might lose the weight when the shell is closed, and it would still be a very good improvement over the current code.

I'm not sure if it's clear what I'd like to see, so let me know if you would like some clarifications.

**Comment by junegunn** [comment]
Please note that the new go version sorts the result regardless of the number of matches. `--sort=N` number is silently ignored.
