### ISSUE TITLE
FZF_DEFAULT_OPTS ignored

### ISSUE THREAD

**Issue by AaronLasseigne** [junegunn/fzf#780]
- Category
    - [X] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [X] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [X] fish

I added this to my `config.fish`:

```
set -U FZF_DEFAULT_OPTS '--preview "begin; cat {}; or tree -C {}; end 2> /dev/null | head -200"'
```

When I try to use `fzf` the options appear to be ignored. If I manually add the args I get this:

```
> fzf $FZF_DEFAULT_OPTS
unknown option: --preview "begin; cat {}; or tree -C {}; end 2> /dev/null | head -200"
```

It looks like this might be from "options.go" which looks for "--preview=" but not "--preview". I'm not sure if that's related or helpful. ¯\\\_(ツ)\_/¯

If I manually type of that same bit (i.e. `fzf --preview "begin....`) it works.

I'm running 0.15.9.

Thanks for fzf, it's great!

**Comment by junegunn** [comment]
1. You need to export the variable (`-x`)
2. `eval "fzf $FZF_DEFAULT_OPTS"`
