### ISSUE TITLE
Can not list files within a unix symbolic link dir.

### ISSUE THREAD

**Issue by lvht** [junegunn/fzf#781]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

Would you @junegunn like to make the <kbd>-L</kbd> as the default option of `find` at [src/constants_unix.go#L7](https://github.com/junegunn/fzf/blob/master/src/constants_unix.go#L7), so that fzf could list files within a unix symbolic link dir.

While the find command could be override by the `FZF_DEFAULT_COMMAND` environment, it will be of great convenience to make <kbd>-L</kbd> as default.

Thanks :smile:

**Comment by junegunn** [comment]
Sure, that makes sense. Thanks for the suggestion.
