### ISSUE TITLE
Add `--height` option

### ISSUE THREAD

**Issue by junegunn** [junegunn/fzf#782]
- Category
    - [x] fzf binary

## Summary

Add `--height HEIGHT[%]` option to display fzf window below the cursor instead of opening it in fullscreen using ncurses or tcell.

## Why?

fzf-tmux provides flexible, non-fullscreen layouts, but it requires tmux and the experience can be suboptimal on large screens, where the tmux pane serving fzf can be far away from the cursor.

## A few things to note

- Supports preview window and mouse.
- 24-bit colors. We're not constrained by the limitation of ncurses.
- Requires `/dev/tty`, `stty`, and `tput`.
- Not sure about Windows.

The new option can be applied to the key bindings and fuzzy completion with the following environment variables.

```sh
FZF_TMUX=0
FZF_CTRL_T_OPTS='--height 40% --reverse'
FZF_CTRL_R_OPTS='--height 40%'
FZF_ALT_C_OPTS='--height 40% --reverse'
FZF_COMPLETION_OPTS='--height 40% --reverse'
```

Or it can be globally applied via `$FZF_DEFAULT_OPTS`:

```sh
export FZF_DEFAULT_OPTS='--height 40% --reverse'
```

## Sample images

<img width="1280" alt="fzf-height" src="https://cloud.githubusercontent.com/assets/700826/21546093/db47a20a-ce1f-11e6-92b1-bed3710dd616.png">

<img width="1280" alt="fzf-height-ctrl-r" src="https://cloud.githubusercontent.com/assets/700826/21546110/ec17df64-ce1f-11e6-813f-69edcfa5b202.png">

<img width="1280" alt="fzf-height-24bit" src="https://cloud.githubusercontent.com/assets/700826/21546114/f307352c-ce1f-11e6-95e7-c11cbe6dbeb7.png">

## Issues

- Windows support
- Manual handling of escape sequences might bring back #661

**Comment by paulhybryant** [comment]
I am using the latest version of fzf installed with homebrew, and it complains about 

unknown option: --height

I guess the binary is not up to date but this option is already added to the zsh binding file.

I think we should check the version in the zsh to avoid this problem (e.g. only add --height when the fzf version is newer than x.y.z)?

**Comment by junegunn** [comment]
@paulhybryant Rerun the install script to download the binary.

**Comment by paulhybryant** [comment]
Thanks @junegunn for the quick reply. Not sure which install script you are referring to.

What I did is 
brew reinstall fzf

and the error is still there.
fzf --version shows 0.15.9

**Comment by junegunn** [comment]
Looks like you're using the binary from homebrew, but scripts from manually cloned repo. If you installed fzf via homebrew, you should also use the scripts from the homebrew installation.

Anyway, I just opened a pull request on Homebrew, so the new version should be available shortly.

https://github.com/Homebrew/homebrew-core/pull/8955

**Comment by cbrwizard** [comment]
Running `brew upgrade` after @junegunn's change got merged helped me with this, gj!

**Comment by SaurabhBayani** [comment]
I am also getting same error as "height options is currently not supported on windows". I am trying to use fzf in window 8 with ConEmu,  Installed manually by cloning git. 

any workaround ?

**Comment by junegunn** [comment]
Not using `--height` option on Windows.
