### ISSUE TITLE
git-completion and fzf.bash conflict

### ISSUE THREAD

**Issue by brailsmt** [junegunn/fzf#783]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [x] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

fzf version:
```
[mb013619]$ fzf --version
0.15.9
```

tmux $TERM setting:
```
[mb013619]$ echo $TERM
screen-256color
```

If I source git-completion, then the tab completion with '**' to trigger fzf file search doesn't work, but the git completions do work.

If I then source ~/.fzf.bash, then the '**' trigger for fzf file search works, but the git completions do not work.

I can toggle back and forth reproducing the same conditions.

Both fzf and git installed by homebrew.

```
[mb013619]$ git --version
git version 2.11.0
```

Contents of ~/.fzf.bash
```sh
# Setup fzf
# ---------
if [[ ! "$PATH" == */usr/local/opt/fzf/bin* ]]; then
  export PATH="$PATH:/usr/local/opt/fzf/bin"
fi

# Man path
# --------
if [[ ! "$MANPATH" == */usr/local/opt/fzf/man* && -d "/usr/local/opt/fzf/man" ]]; then
  export MANPATH="$MANPATH:/usr/local/opt/fzf/man"
fi

# Auto-completion
# ---------------
[[ $- == *i* ]] && source "/usr/local/opt/fzf/shell/completion.bash" 2> /dev/null

# Key bindings
# ------------
source "/usr/local/opt/fzf/shell/key-bindings.bash"
```

**Comment by junegunn** [comment]
Thanks for the report. Can you check unsetting `_fzf_completion_loaded` fixes the issue? Like follows:

```sh
unset _fzf_completion_loaded
source /usr/local/opt/git/etc/bash_completion.d/git-completion.bash
[ -f ~/.fzf.bash ] && source ~/.fzf.bash
```

I'm not suggesting that you should do this, just trying to check if it's related to the problem.

IIRC, I added `_fzf_completion_loaded` to avoid re-evaluation of some not-so-trivial expressions, but I don't think it makes a significant difference, so I can consider removing it.

**Comment by brailsmt** [comment]
```
[mb013619]$ unset _fzf_completion_loaded
cwd: ~/bin  (master *% u=)
[mb013619]$ . /usr/local/etc/bash_completion.d/git-completion.bash
cwd: ~/bin  (master *% u=)
[mb013619]$ . ~/.fzf.bash
cwd: ~/bin  (master *% u=)
[mb013619]$ git checkout
HEAD            master          origin/HEAD     origin/master
```

The '**' also worked correctly.  So this appears to alleviate whatever is going on.

**Comment by junegunn** [comment]
Thanks for the confirmation. I just pushed the fix.
