### ISSUE TITLE
support true color

### ISSUE THREAD

**Issue by nhooyr** [junegunn/fzf#789]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [x] Vim
    - [x] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [x] Mac OS X
    - [x] Windows
    - [x] Windows Subsystem for Linux
    - [x] Etc.
- Shell
    - [x] bash
    - [x] zsh
    - [x] fish

Would allow fzf.vim to properly display gui vim colorschemes.

**Comment by junegunn** [comment]
This won't happen soon as ncurses does not support true colors. However, once #782 is merged, and the new renderer (which happens to support true colors) turns out to be stable and performant, we can consider replacing ncurses completely.

**Comment by junegunn** [comment]
Experimental support for 24-bit colors in `--color` option is in https://github.com/junegunn/fzf/commit/ae274158de38181bca27f2ce54c8b4fc0b688eff. However, I'm running into https://github.com/neovim/neovim/issues/4151 when trying to start fzf with `--height` option within Neovim terminal. So I can't make Neovim plugin use the option at the moment.

**Comment by ismay** [comment]
So should this just work? Or is there something that needs to be done to enable this?

**Comment by junegunn** [comment]
1. Set up your vim or neovim to use true colors (`set termguicolors`).
2. Define `g:fzf_colors` to tell fzf to extract colors from the current color scheme. See https://github.com/junegunn/fzf/wiki/Configuring-Vim-plugin for an example

Related: https://github.com/junegunn/fzf/issues/818

**Comment by ismay** [comment]
Sorry, didn't mean in vim. What I meant is if I'm running a terminal emulator that supports true color and has it enabled correctly, will fzf automatically run in true color as well (in the terminal, not vim), or do I need to do anything extra to enable it for fzf?

But that might be a stupid question.

**Comment by junegunn** [comment]
Yep. Colors are customizable via `--color`.

```sh
fzf --color 'fg:#839496,fg+:#93a1a1,bg:#002b36,bg+:#073642' --height 50%
```

**Comment by ismay** [comment]
Cool, thanks!
