### ISSUE TITLE
Treat accented characters as being similar to their non-accented counterparts

### ISSUE THREAD

**Issue by elvis-sik** [junegunn/fzf#790]
- Category:
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [x] matching algorithms
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

    > $ fzf --version
    > 0.15.9

I use `fzf` on my music collection. If I type `antonio jobim so danco samba` the top choice ends up being

```
./Antônio Carlos Jobim/[1965] - The Wonderful World Of Antonio Carlos Jobim/10 - Samba Do Aviao.mp3
```

Whereas it seems to me that this should be the one:

```
./Antônio Carlos Jobim/[1994] - Antonio Brasileiro/01 - Só Danço Samba.mp3
```

**Comment by junegunn** [comment]
Makes sense. I'll pay special attention to this because Jobim is great.

**Comment by junegunn** [comment]
Fixed in devel branch. I'm planning to release a new version in a few days, but feel free to test the devel branch (check out the branch and run install script to download the binary) and let me know of any issues you notice. Thanks.

**Comment by junegunn** [comment]
I changed my mind. Normalization is enabled by default and one has to pass `--literal` to disable it.
