### ISSUE TITLE
_fzf_complete_ssh() and known_hosts file

### ISSUE THREAD

**Issue by yevhen-m** [junegunn/fzf#791]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [x] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

What's the purpose of `known_hosts` in `_fzf_complete_ssh()`? 

When I use this completion func, I get hosts and a bunch of lines from `known_hosts`, that ruin all the beautiful picture.

By the way, telnet version does not use `known_hosts` and just outputs hosts.

**Comment by junegunn** [comment]
I'm not sure what you mean. I like that it shows hostnames that I have ever connected to.

**Comment by yevhen-m** [comment]
I don't have hostnames in `known_hosts`.  I get `|1|...=|....=` useless entries from it into completion candidates.

**Comment by junegunn** [comment]
Turned out we needed to filter out some entries in the file (reference: SSH_KNOWN_HOSTS FILE FORMAT section in `man sshd`). Let me know if you still see issues. Thanks.

**Comment by yevhen-m** [comment]
@junegunn now completions are fixed, but I get this after `**<tab>`
```
ssh **cat: /proc/self/fd/12: No such file or directory
```

**Comment by junegunn** [comment]
Hmm, I can't reproduce. Any idea why it is happening?
