### ISSUE TITLE
Killing tmux pane freezes fzf-tmux

### ISSUE THREAD

**Issue by toiffel** [junegunn/fzf#796]
- Category
    - [ ] fzf binary
    - [x] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [ ] fish

Steps to reproduce:

1. Run fzf-tmux inside tmux
2. Kill appeared pane with running fzf (by default C-b x)

Expected: tmux pane is closed and fzf-tmux exits with code 130
Observed: tmux pane is closed but fzf-tmux hangs until I press Ctrl+C

After some debugging I figured out that fzf-tmux freezes on the very last line:
```
exit "$(cat $fifo3)"
```

The script running inside tmux pane is generated on the fly with the following line:
```
cat <<< "\"$fzf\" $opts > $fifo2; echo \$? > $fifo3 $close" > $argsf
```

Normally it runs fzf and then writes its exit code into `$fifo3`. After that fzf-tmux reads exit code from `$fifo3` and correctly terminates. But when user kills tmux pane, the entire script is aborted. As a result, `$fifo3` is never written and fzf-tmux stucks when trying to read exit code from `$fifo3`.

I've tried to fix the issue using `trap` to handle `SIGHUP` signal from tmux but unfortunately had no luck. The annoying thing is that Vim freezes too when killing tmux pane with fzf, or complains that fzf is already running with my asynchronous patch.

**Comment by junegunn** [comment]
Thanks, I can confirm. But I can't seem to think of an easy way to solve this :(
