### ISSUE TITLE
Fzf works in bash, not in vim.

### ISSUE THREAD

**Issue by asilvadesigns** [junegunn/fzf#797]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [x] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [ ] fish

Fzf works perfectly in bash. I've setup using vim-plug as described here: https://github.com/junegunn/fzf.vim#installation, but nothing seems to happen when typing any of the commands.

For example, typing ":Files" or ":FZF" will do nothing, no errors, no indication of anything happening, However, I do have to type "ctrl-c" to return to normal mode. Would greatly appreciate any help, thanks!

**Comment by junegunn** [comment]
Hmm, I'm not sure but it could be an issue of tmux.
- Do you use tmux? 
- Does `:FZF!` work (command with exclamation mark)?

**Comment by asilvadesigns** [comment]
I had tmux installed, so I uninstalled and no changes.
`:FZF!` doesn't register anything.

I noticed this within bash, typing `FZF` does nothing, and typing `ctrl-c` exits the apparent operation. Again no errors or indication of problem.

However, in bash, using `ctrl-T`,  `ctrl-R`, or any of the hotkey commands works.

**Comment by junegunn** [comment]
I see, which version of Vim do you have? (`:version`)

**Comment by asilvadesigns** [comment]
Here ya go:

```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Jan  4 2017 03:54:40)
MacOS X (unix) version
Included patches: 1-142
Compiled by travis@Traviss-Mac-592.local
Huge version with MacVim GUI.  Features included (+) or not (-):
+acl             +cmdline_compl   +digraphs        +folding         +lambda          +mouse           +multi_lang      +profile         +statusline      +timers          +wildignore
+arabic          +cmdline_hist    +dnd             -footer          +langmap         +mouseshape      -mzscheme        +python/dyn      -sun_workshop    +title           +wildmenu
+autocmd         +cmdline_info    -ebcdic          +fork()          +libcall         +mouse_dec       +netbeans_intg   +python3/dyn     +syntax          +toolbar         +windows
+balloon_eval    +comments        +emacs_tags      +fullscreen      +linebreak       -mouse_gpm       +num64           +quickfix        +tag_binary      +transparency    +writebackup
+browse          +conceal         +eval            -gettext         +lispindent      -mouse_jsbterm   +odbeditor       +reltime         +tag_old_static  +user_commands   -X11
++builtin_terms  +cryptv          +ex_extra        -hangul_input    +listcmds        +mouse_netterm   +packages        +rightleft       -tag_any_white   +vertsplit       -xfontset
+byte_offset     +cscope          +extra_search    +iconv           +localmap        +mouse_sgr       +path_extra      +ruby/dyn        -tcl             +virtualedit     +xim
+channel         +cursorbind      +farsi           +insert_expand   +lua/dyn         -mouse_sysmouse  +perl/dyn        +scrollbind      +termguicolors   +visual          -xpm
+cindent         +cursorshape     +file_in_path    +job             +menu            +mouse_urxvt     +persistent_undo +signs           +terminfo        +visualextra     -xsmp
+clientserver    +dialog_con_gui  +find_in_path    +jumplist        +mksession       +mouse_xterm     +postscript      +smartindent     +termresponse    +viminfo         -xterm_clipboard
+clipboard       +diff            +float           +keymap          +modify_fname    +multi_byte      +printer         +startuptime     +textobjects     +vreplace        -xterm_save
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "$VIM/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/Applications/MacVim.app/Contents/Resources/vim"
Compilation: clang -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_MACVIM -Wall -Wno-unknown-pragmas -pipe  -DMACOS_X_UNIX  -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: clang   -L. -fstack-protector -L/usr/local/opt/libyaml/lib -L/usr/local/opt/readline/lib -L/usr/local/opt/libksba/lib -L/usr/local/opt/openssl/lib  -L. -fstack-protector -L/usr/local
/opt/libyaml/lib -L/usr/local/opt/readline/lib -L/usr/local/opt/libksba/lib -L/usr/local/opt/openssl/lib   -L/usr/local/lib -o Vim -framework Cocoa -framework Carbon       -lm  -lncurses -lic
onv -framework Cocoa   -fstack-protector  -L/System/Library/Perl/5.16/darwin-thread-multi-2level/CORE
```

**Comment by junegunn** [comment]
Ah, so it's Gvim. fzf is a command-line program so it works best with terminal Vim. On GVim, it has to start a terminal emulator window (xterm by default), and I'm not sure if you'll like the experience.

Probably `xterm` is not properly set up on your system. Try typing in `xterm` on shell.

**Comment by asilvadesigns** [comment]
ooh : ), no worries, I'd love to try it out.
yea definitely not setup properly, `xterm` does nothing, same as previous behavior, hangs until `ctrl-c`. I suppose I'll have to install that..

**Comment by asilvadesigns** [comment]
so, that didn't work, that's fine. I've got it setup in terminal vim, and have this mapping in place: `nnoremap <c-p> :FZF<cr>` which behaves as it should, except no results are loaded, for example...
![screen shot 2017-01-11 at 1 24 32 pm](https://cloud.githubusercontent.com/assets/7071307/21861084/58926a02-d801-11e6-9cbe-27f007000db7.png)
also.. discovered an interesting issue which might reveal the real problem. In terminal, I can hit `ctrl-t` and FZF works perfectly, or any other shortcut and perfect. Typing in FZF, does this:
![screen shot 2017-01-11 at 1 24 32 pm](https://cloud.githubusercontent.com/assets/7071307/21861260/1d8ca516-d802-11e6-898a-6e257e82768d.png)
same result as vim. *shrug.

**Comment by junegunn** [comment]
Do you have set `$FZF_DEFAULT_COMMAND`?

**Comment by asilvadesigns** [comment]
It was not, I did `export FZF_DEFAULT_COMMAND='ag -g ""'`.
`printenv` shows it now. But still same result, `ctrl-t` and `ctrl-r` work beautifully, but `fzf` nothing. What command does `ctrl-t` call, maybe I can use that as default?

**Comment by junegunn** [comment]
I didn't mean to suggest that you should set the variable. The problem is usually caused by an invalid command in it so I was trying to see if it was the case.

So if you set `export FZF_DEFAULT_COMMAND='seq 1000'`, do you see the numbers as expected?

**Comment by junegunn** [comment]
Anyway the default command fzf uses when `$FZF_DEFAULT_COMMAND` is unset is

```sh
find . -path '*/\.*' -prune -o -type f -print -o -type l -print 2> /dev/null | sed s/^..//
```

Does this command work correctly in your shell?

**Comment by asilvadesigns** [comment]
gotcha, when I set `export FZF_DEFAULT_COMMAND='seq 1000'`, check `printenv`, and do `fzf`, I see this:
![screen shot 2017-01-12 at 12 08 20 pm](https://cloud.githubusercontent.com/assets/7071307/21899873/e395fae2-d8bf-11e6-81cc-d5572ad2eb2c.png)

The command mentioned above, this one
`find . -path '*/\.*' -prune -o -type f -print -o -type l -print 2> /dev/null | sed s/^..//`
works.

**Comment by junegunn** [comment]
That's odd. What's in your `$SHELL`? Does `$SHELL -c "seq 1000"` work?

**Comment by asilvadesigns** [comment]
You are awesome. I had a bad shell setup, `$SHELL` revealed bad install of bash, I must have caused it a while ago when I was messing with zsh and bash configs, works perfectly, thanks man!!!
