### ISSUE TITLE
fzf freezes on bash 4.4.5(1)-release

### ISSUE THREAD

**Issue by dosentmatter** [junegunn/fzf#798]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

I was looking at the fzf shell function examples on this page:
https://github.com/junegunn/fzf/wiki/examples

I was trying to use the fdr() function:

    # fdr - cd to selected parent directory
    fdr() {
      local declare dirs=()
      get_parent_dirs() {
        if [[ -d "${1}" ]]; then dirs+=("$1"); else return; fi
        if [[ "${1}" == '/' ]]; then
          for _dir in "${dirs[@]}"; do echo $_dir; done
        else
          get_parent_dirs $(dirname "$1")
        fi
      }
      local DIR=$(get_parent_dirs $(realpath "${1:-$(pwd)}") | fzf-tmux --tac)
      cd "$DIR"
    }

For some reason, this function freezes on `GNU bash, version 4.4.5(1)-release (x86_64-apple-darwin16.3.0)` installed through homebrew. It freezes on the fzf display - it shows the list of parent directories, but I can't type to search or ctrl+c to exit.

I narrowed it down and found out it was freezing on the line

    local DIR=$(get_parent_dirs $(realpath "${1:-$(pwd)}") | fzf-tmux --tac)

With some more testing, I simplified it and it still froze on

    echo $(echo $(realpath "$(pwd)") | fzf)

This would be an invalid command but it also freezes on

    $($(realpath "$(pwd)") | fzf)

Here's a gif of the problem:

<img src='http://i.imgur.com/xm615x4.gif' title='fzf issue' width='' alt='fzf issue' />

Once I get into the fzf screen, I can't ctrl+c, ctrl+z, type anything to search, or move up and down (if it had results). I have to kill the terminal tab to stop it.

Things that cause it **not** to freeze:

- Removing the outer `$()`
- Changing `fzf` to `cat`
- changing `$(pwd)` to `$PWD`
- changing `realpath` to `echo`

Things that still make it freeze:

- Change realpath to ls
- Change $(pwd) to $(echo $PWD)

It doesn't seem to freeze on the on the bash version that comes preinstalled on OS X `GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin16)`

It also doesn't freeze on the preinstalled zsh and ksh on OS X

zsh

    zsh 5.2 (x86_64-apple-darwin16.0)

ksh

    sh (AT&T Research) 93u+ 2012-08-01

I also compiled `bash 4.4.5(1)-release` on my own and it also freezes along with the homebrew one.

I'm not sure if this is a bash or fzf problem and I'm not sure what else I can do to debug.

**Comment by junegunn** [comment]
Thanks for the report. I can reproduce the problem on my machine as well. I'll look into it when I get some time.

**Comment by junegunn** [comment]
Okay, I pushed the fix to devel branch. It will be included in the next release. The patch does not entirely fix the problem (the source of error is probably in bash), but it simply makes fzf quit when `/dev/tty` is hosed for some reason.

Thanks again for the detailed report!

**Comment by dosentmatter** [comment]
No problem. Thanks!
