### ISSUE TITLE
Preview does not work on ** completion

### ISSUE THREAD

**Issue by IngoHeimbach** [junegunn/fzf#799]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [x] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

Setting the environment variable `FZF_COMPLETION_OPT` to
```bash
export FZF_COMPLETION_OPTS='--preview="cat {}"'
```
leads to a fzf crash when `**` is expanded with `<Tab>`.

**Comment by junegunn** [comment]
Thanks for the report. The fix is pushed to devel branch. The branch will be merged to master in a few days.

However, setting `--preview` option in FZF_COMPLETION_OPTS may not be a good idea as completion works not only with files but with other types, any types of entities.

**Comment by jawang35** [comment]
@junegunn does it make sense to add an option for `_fzf_compgen_path` to have separate completion opts or a way to turn on preview only for that completion method?
