### ISSUE TITLE
** completion ignores FZF_DEFAULT_COMMAND

### ISSUE THREAD

**Issue by cskeeters** [junegunn/fzf#800]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [x] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [?] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [x] bash
    - [x] zsh
    - [ ] fish

I'm using 0.15.9.

When I run `vim term**<tab>`, I get entries in .hg and folders that are in `.hgignore`.  When I run fzf by itself, those ignored files are ignored given that `FZF_DEFAULT_COMMAND='ag -g ""'.  Seems as though the completion code uses find and doesn't utilize the FZF_DEFAULT_COMMAND environment variable, but I'd like it to.  Please advise.

**Comment by junegunn** [comment]
Because fuzzy completion for files can't use a single fixed command as it has to address base directory found in the completion prefix. So we use a function instead.

See https://github.com/junegunn/fzf#settings

**Comment by cskeeters** [comment]
Sorry, I missed that piece of the README.  That code meets my need.  Thanks!

I did some examination to see if `FZF_DEFAULT_COMMAND` could affect both `fzf` (used in stand alone mode) and for `**` completion.  I haven't given it much thought to other use cases, so it may not be worth implementing.  Still seemed worth posting, so I'll just through this out there.

If I'm understanding the issue, `FZF_DEFAULT_COMMAND` doesn't support allowing a directory to be substituted into the command, like `{}` in `find -exec` or `xargs -I {}`.  You have written a method `_fzf_compgen_path` that can be easily overridden to enable `$1` (the completion prefix directory) to be used in a custom command like `ag -g "" "$1"`.

FZF_DEFAULT_COMMAND can be used and take advantage of the `$1` completion prefix if _fzf_compgen_path is defined as follows:

```zsh
_fzf_compgen_path() {
    if [[ -z $FZF_DEFAULT_COMMAND ]]; then
        echo "$1"
        command find -L "$1" \
            -name .git -prune -o -name .svn -prune -o \( -type d -o -type f -o -type l \) \
            -a -not -path "$1" -print 2> /dev/null | sed 's@^\./@@'
    else
        FZF_BASE="$1" eval $FZF_DEFAULT_COMMAND
    fi
}
```

Then if `${FZF_BASE:-.}` can be used in FZF_DEFAULT_COMMAND to specify where the completion prefix directory goes in the custom command.

```zsh
export FZF_DEFAULT_COMMAND='ag -g "" "${FZF_BASE:-.}"'
```

This shouldn't be limiting since `FZF_BASE` can be omitted from `FZF_DEFAULT_COMMAND` without issue.  Also, `fzf` can still be run as is in stand alone mode since an undefined FZF_BASE result in the default of `.`, or the current working directory.
