### ISSUE TITLE
Make fzf installable by using `go get`

### ISSUE THREAD

**Issue by nomad-software** [junegunn/fzf#801]
- Category
  - [x] fzf binary
  - [ ] fzf-tmux script
  - [ ] Key bindings
  - [ ] Completion
  - [ ] Vim
  - [ ] Neovim
  - [ ] Etc.
- OS
  - [x] Linux
  - [x] Mac OS X
  - [x] Windows
  - [x] Windows Subsystem for Linux
  - [x] Etc.
- Shell
  - [x] bash
  - [x] zsh
  - [x] fish

Configure the repo so that the fzf binary can be installed in the usual way all other Go programs are, i.e. using `go get github.com/junegunn/fzf`.

**Comment by junegunn** [comment]
It's already possible. `go get -u github.com/junegunn/fzf/src/fzf`

**Comment by nomad-software** [comment]
```
/media/Data/Projects/Go/src/github.com/junegunn/fzf/src/tui/ncurses.go:7:21: fatal error: ncurses.h: No such file or directory
```

**Comment by junegunn** [comment]
You can't install ncurses using go get.

**Comment by jones77** [comment]
Looks like this changed to the following: `go get github.com/junegunn/fzf`
