### ISSUE TITLE
Support equivalent of path/filepath actions

### ISSUE THREAD

**Issue by myitcv** [junegunn/fzf#802]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [x] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

I can see the [actions supported for key bindings](https://github.com/junegunn/fzf/blob/a71c47140575b324afeb054a4fbc0e3fa505d4d0/man/man1/fzf.1#L420-L465) but I can't find actions that allow manipulation of what is probably the most common input to fzf and that is file paths.

In my case (which happens to be invoking from Neovim but that's not the critical factor here) I use the `--query` option to start the finder with the provided query. In my case that's a filepath, specifically the equivalent of (in pseudo code, mixing Go and Vimscript) `filepath.Rel($CWD, "%:h")`. This means my results are constrained to the directory containing the current file. 

What I would like is an action that then allows me to set the query string to the result of `filepath.Dir(queryString)`.

Is there a way of doing this? 

Using `unix-word-rubout` feels like the wrong solution, not least because it would require configuration, but also because it isn't platform-aware. `filepath.Dir` is platform-aware.. so an action-equivalent would be great.

**Comment by junegunn** [comment]
I'm not sure if I understood your intention correctly, but is this what you're looking for?

```vim
function! s:fzf_on_dir(arg, bang)
  let dir = fnamemodify(a:arg, ':h')
  let query = shellescape(fnamemodify(a:arg, ':t'))
  call fzf#run(fzf#wrap({'dir': dir, 'options': '--query '. query}, a:bang))
endfunction

command! -nargs=* -bang -complete=file F call <sid>fzf_on_dir(<q-args>, <bang>0)
```

**Comment by myitcv** [comment]
@junegunn apologies for not being clear on what I was asking for. 

Let's take the following example:

```bash
cd `mktemp -d`
mkdir -p src/github.com/a/
touch src/github.com/a/{apple,banana}.txt
fzf --query src/github.com/a/
```

which gives us the following:

```
  src/github.com/a/banana.txt
> src/github.com/a/apple.txt
  2/2
> src/github.com/a/
                   ^
```

(with the cursor at the position shown by the caret)

For me the default mapping for the action `kill-word` is `alt-del`. If we `kill-word` once we are left with:

```
  src/github.com/a/banana.txt
> src/github.com/a/apple.txt
  2/2
> src/github.com/
                 ^
```

If we `kill-word` again we are however left with:

```
  src/github.com/a/banana.txt
> src/github.com/a/apple.txt
  2/2
> src/github.
             ^
```

`kill-word` isn't really what I'm trying to do here; I'm trying to make the query string equal to the value of [`filepath.Dir(currentQueryString)`](https://godoc.org/path/filepath#Dir) in Go terms. 

So what I'm asking is whether it would be possible to introduce an action (to which I can then add a key binding) that makes this possible.

Does that help to clarify?

**Comment by myitcv** [comment]
Updated [my previous comment](https://github.com/junegunn/fzf/issues/802#issuecomment-272677847) to make a couple of points clearer.

**Comment by junegunn** [comment]
To be clear, it's `backward-kill-word` (which is mapped to alt-backspace) not `kill-word`, right?

Since `backward-kill-word` suffices for me and fzf is a general purpose filter (though you're probably correct that it's most frequently used with files) I'm not really inclined to add an action specialized for file search. When you get `src/github.`, you can just hit `alt-backspace` one more time. Does it really bother you much? That's what we do on our shells.

The same also applies to backward-word and forward-word. So if we're really going to do this, for completeness's sake, we would have to add 3 actions in total. Also we would have to allow customizing path separator, since theoretically, one can be filtering a list of files from another platform.

**Comment by myitcv** [comment]
> To be clear, it's `backward-kill-word` (which is mapped to `alt-backspace`) not `kill-word`, right?

Correct, fixed in my comment above.

> I'm not really inclined to add an action specialized for file search. 

Totally understand your point of view. These actions would, however, be additions to the action API:

```
filepath-backward-kill-element
filepath-kill-element
filepath-backward-element
filepath-forward-element
```

I've proposed a prefix here which would help to separate them from the existing actions, and used the term 'element' from the [`path/filepath`](https://godoc.org/path/filepath) godocs. 

The actions would be extremely well-defined, have a clear and simple implementation and so to my mind would add real value for what we both agree is the most common use case for `fzf`

> When you get src/github., you can just hit alt-backspace one more time. Does it really bother you much? That's what we do on our shells.

... and I'm not happy about it in `bash` either 😄 . The issue is that I know I'm dealing with a filepath; I know I'm trying to backward-kill the last element of that filepath. I don't want to have to visually inspect the last element of the filepath to see how many non-wrod characters are in that element so that I can compensate my number of key presses. It seems that within `fzf` we're not forced to maintain an API that is a subset/superset of various shells' actions, so we have some flexibility in what we do.

> Also we would have to allow customizing path separator, since theoretically, one can be filtering a list of files from another platform.

I would argue (based on a gut feel) this is an _extremely_ rare use case and certainly not one to consider at this point in time.

**Comment by junegunn** [comment]
Maybe it's simpler to add a single option (like `--file-word`) that overrides the behaviors of 4 existing options?

**Comment by myitcv** [comment]
> Maybe it's simpler to add a single option (like `--file-word`) that overrides the behaviors of 4 existing options?

That's certainly another option (if we are 🚲 shedding on the name I would prefer `--filepath-word`, it's more consistent with the Go `path/filepath` language). This approach raises a couple of questions for me:

* by doing this we rule out people using both behaviours, i.e. in an input where they want to erase either a word or a filepath element and bind keys accordingly; I don't think they need to be mutually exclusive because, as you point out, inputs aren't guaranteed to be so
* how much more complex does this makes the documentation?

```
--filepath-word       alters the definition of 'word' in actions (see below) to be a filepath
                      element, according to the definition here https://godoc.org/path/filepath
```

Are there other parts of documentation that would need changing?

Adding to the API we at least avoid both aforementioned problems.

**Comment by junegunn** [comment]
The name doesn't have to be consistent with the naming convention of Go. The language fzf is written in doesn't matter to the users. I prefer shorter names. The definition of "path separator" should be clear to the users, I don't think we need to mention godoc.org for describing such a well known, language-agnostic concept. I would just say "Make word-wise movements and actions respect path separators".

> we rule out people using both behaviours

I doubt that there will be a significant number of users who would try to find 4 more key chords they can bind to those 4 new options. You know, there actually aren't too many free key chords available for binding. And to be honest, it's hard for me to see the benefit of the option, as I rarely type in more than 5-6 characters to fzf prompt and I don't spend more than several seconds inside fzf finder most of the time. And I haven't used `--query` in such a way.

Having said that, it was trivial to implement the option, but I haven't decided if it's essential to fzf, can you share your script that you're implementing using `--query`?

**Comment by myitcv** [comment]
> The name doesn't have to be consistent with the naming convention of Go

True, I was only advocating using similar/the same language in order to keep things simple, and in the case a phrase/term is not clear there's a pre-existing reference we can point people at for a precise, cross-platform definition.

> I doubt that there will be a significant number of users who would try to find 4 more key chords they can bind to those 4 new options. 

This is a good point.

> And I haven't used --query in such a way.

> Having said that, it was trivial to implement the option, but I haven't decided if it's essential to fzf, can you share your script that you're implementing using --query?

Here are the relevant bits (I've borrowed heavily from your excellent scripts); note this will only likely work on Unix systems:

```vim
fun! myitcv#util#nonDotRel()
  let l:dir = fnamemodify(expand("%"), ':h:.')

  if l:dir == '' || l:dir == '.' || l:dir =~ '^/'
    return ''
  endif

  return l:dir.'/'
endf

fun! myitcv#util#filesOrGitFiles(args, ...)
  " see whether cwd is part of a git tree
  " note this intentionally uses the CWD of the neovim process and not
  " the working directory of the current window
  call system('git rev-parse --show-toplevel')

  if !v:shell_error
    " part of a git tree
    let rel = myitcv#util#nonDotRel()

    return s:fzf('gfiles', {
    \ 'source':  'git ls-files | awk "{print gsub(/\//,\"/\"), \$0}" | sort -s -n -k 1,1 | cut -d\  -f2- '.a:args,
    \ 'dir':     getcwd(),
    \ 'options': '-m --prompt "GitFiles> " --query '.shellescape(rel)
    \}, a:000)
  else
    " part of a git tree
    call fzf#vim#files(a:args, {'options': '--query '.shellescape(myitcv#util#nonDotRel())})
  endif
endf

```

I then trigger this with the binding:

```vim
map <Leader>t :call myitcv#util#filesOrGitFiles('')<CR>
```

Additionally I have the following environment variable set:

```bash
export FZF_DEFAULT_COMMAND='( find . -path "*/\.*" -prune -o -type f -printf "%P\n" -o -type l -printf "%P\\n" | awk "{print gsub(/\//,\"/\"), \$0}" | sort -s -n -k 1,1 | cut -d\  -f2- ) 2> /dev/null'
```

The idea is that, regardless of whether I'm in a git tree or not, `--query` is pre-populated to the directory of the file in the current window, relative to either its git root or the CWD of the neovim process. I find that more often than not I want to work with a file in the same directory (package), hence why this pre-population of `--query` is so useful. Less often I want to expand the search by going up a directory, hence why I need the equivalent of `filepath-backward-kill-element`

**Comment by junegunn** [comment]
I see, thanks for the comment. That looks useful. On the second thought, I agree that `--filepath-word` is a better name.

**Comment by myitcv** [comment]
Ok great.

Just to emphasise one important point here (apologies if this is already clear). Notice the trailing separator on the query string I start with: `"src/github.com/a/"`, but also the progression of values after `filepath-backward-kill-element` (using my terminology for clarity's sake) also have a trailing separator:

```
src/github.com/a/
src/github.com/
src/
```

Reason being this disambiguates from any sibling directories of the new query string that may start with the same prefix, and guarantees that any further typing will match under the directory and not on the name of a sibling. By way of an example:

```
cd `mktemp -d`
mkdir -p src/github.com/a/
touch src/github.com/a/{apple,banana}.txt
mkdir src/github.comp
touch src/github.comp/truck.txt
touch src/github.com/pear.txt
```

Then compare:

```bash
  src/github.com/a/banana.txt
  src/github.com/a/apple.txt
  src/github.comp/truck.txt
> src/github.com/pear.txt
  4/4
> src/github.com

# now type p

  src/github.com/a/apple.txt
  src/github.com/pear.txt
> src/github.comp/truck.txt
  3/4
> src/github.comp
```

with:

```bash
  src/github.comp/truck.txt
  src/github.com/a/banana.txt
  src/github.com/a/apple.txt
> src/github.com/pear.txt
  4/4
> src/github.com/

# now type p

  src/github.com/a/apple.txt
> src/github.com/pear.txt
  2/4
> src/github.com/p
```

**Comment by junegunn** [comment]
Yeah, the above implementation already handles that, just like the default backward-kill-word leaves the trailing white spaces.

**Comment by myitcv** [comment]
👍 

Just seen the commit you've pushed up... I'm happy to help try this out: just let me know when I can switch to the `devel` branch

**Comment by junegunn** [comment]
Everything merged to master :)

**Comment by myitcv** [comment]
@junegunn - brilliant. Working like a dream; thank you!
