### ISSUE TITLE
Error running /bin/zsh "/var/folders/f3/l0x65b_j2c90lr5g6d_0y6x80000gn/T/vV1qr7d/7"|"/Users/xlc/.fzf/bin/fzf"

### ISSUE THREAD

**Issue by liuchengxu** [junegunn/fzf#806]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [x] Vim
    - [x] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

vim:
```vim
Error running /bin/zsh "/var/folders/f3/l0x65b_j2c90lr5g6d_0y6x80000gn/T/v4Vnsdl/4"|"/Users/xlc/.fzf/bin/fzf" --color=bg+:237,bg:235,spinner:104,hl:168,fg:249,header:30,info:176,poi
nter:160,marker:36,fg+:36,prompt:134,hl+:81 --color=bg+:237,bg:235,spinner:104,hl:168,fg:249,header:30,info:176,pointer:160,marker:36,fg+:36,prompt:134,hl+:81 -m  --prompt '~/' --ex
pect=ctrl-v,ctrl-x,ctrl-t --height=19 > /var/folders/f3/l0x65b_j2c90lr5g6d_0y6x80000gn/T/v4Vnsdl/3
```
<img width="1279" alt="2017-01-16 2 11 16" src="https://cloud.githubusercontent.com/assets/8850248/21972637/da6dbf2a-dbf5-11e6-97f1-545708a9a97a.png">

neovim:
<img width="1274" alt="2017-01-16 2 10 43" src="https://cloud.githubusercontent.com/assets/8850248/21972650/e9fa52aa-dbf5-11e6-82d2-2b9cc8f00531.png">

I notice that you have just released a new version and I also update to the latest, does it caused by the new release? Is there any notes for this release?

**Comment by junegunn** [comment]
Rerun the install script (~/.fzf/install) to download the latest binary.

**Comment by liuchengxu** [comment]
Thanks!

**Comment by juandazapata** [comment]
I hit this same wall while using `fzf` in `nvim` inside `iTerm`. What's weird is that it works most of the time, but it fails about 3/10 times.

**Comment by junegunn** [comment]
You can check if the command printed in the error message works outside of nvim.

**Comment by juandazapata** [comment]
I'm also getting this random segfaults errors while in the terminal (outside vim)

```
/usr/local/bin/fzf-tmux: line 89: 54372 Segmentation fault: 11  fzf "${args[@]}"
```

**Comment by junegunn** [comment]
Please post the full command you executed.

**Comment by tupton** [comment]
I'm getting the original issue in vim. I've re-run the installation command to download the latest binary like you mentioned.

I get the following when I try `:Files`:

`Error running /usr/local/bin/zsh "/var/folders/47/n2r2wmk55s977ztm6m2r1jlc0000gn/T/v0XdqgI/16"|"fzf"  -m  --prompt '~/' --expect=ctrl-v,ctrl-x,ctrl-t --height=17 > /var/folders/47/n2r2wmk55s977ztm6m2r1jlc0000
gn/T/v0XdqgI/15`

The `var/folders/47/n2r2wmk55s977ztm6m2r1jlc0000gn/T/v0XdqgI/` directory does not exist.

**Comment by juandazapata** [comment]
I completely uninstalled `fzf` and installed the latest version and the problem went away. It's been working perfectly for the last 2 weeks. 🎉

**Comment by indeedwatson** [comment]
@junegunn I thought I'd ask here before I open a new issue, but I keep randomly having this error and it's annoying to the point that's making me consider not use fzf, which is one of my favorite plugins.

I've reinstalled fzf and fzf-git from aur mutliple times, updating the script from vim every time as well, but no matter what this bug comes back, and worse of all it makes my cpu spike to high temperatures until I kill it with ctrl+c.

The full error that I get is:

```Error running ( /bin/zsh '/tmp/nvimghd8Jx/4' )|'fzf' --history '/home/yama/.local/share/fzf-
history/FZF' --color=bg+:#383a3e,spinner:#F92772,hl:#75715E,fg:#E8E8E3,header:#75715E,info:#
A6E22D,pointer:#F92772,marker:#66d9ef,fg+:#E8E8E3,prompt:#F92772,hl+:#F92772 '--multi' '--pr
ompt' '~/' --expect=ctrl-v,ctrl-x,ctrl-t --no-height > /tmp/nvimghd8Jx/3```
