### ISSUE TITLE
FZF completion slow in tmux

### ISSUE THREAD

**Issue by Jeansen** [junegunn/fzf#810]
- Category
    - [ ] fzf binary
    - [x] fzf-tmux script
    - [ ] Key bindings
    - [x] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

Running FZF in a plain xterm with bash works like a charm but running it in tmux is very slow. For instance, I am in my homefolder and do `ls tmp/**<Tab>` which brings up FZF. After selecting an entry, is is there instantly. The same in tmux takes about 2 seconds.

**Comment by junegunn** [comment]
Are you running the latest version of fzf?

**Comment by Jeansen** [comment]
I just ran an update (did that a couple days ago, also). Anyway, I seemed to have been one version behind. With the latest version it works! Sorry, for not having checked beforehand.

**Comment by junegunn** [comment]
Good to hear that the update helped. But it's not that the root cause of the problem is fixed but the problem's just avoided by the new version not using tmux by default. I think you will still have the same issue when running fzf-tmux script.

**Comment by Jeansen** [comment]
Oh, I see. Well, for now I am not using it explicitly. But I guess soon I will want to use it with the power of tmux panes. Any way I can help?

**Comment by junegunn** [comment]
Nah, It's okay. Lately I'm also using `--height` instead of fzf-tmux in most cases. I guess it's probably something to do with your tmux setup.

**Comment by giodamelio** [comment]
I am having this same issue, even with default tmux with absolutely no config.
