### ISSUE TITLE
iTerm2 shell integration and fzf lag

### ISSUE THREAD

**Issue by sheldond** [junegunn/fzf#813]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [x] Etc.
- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

Dear @junegunn, I found recently that fzf started behaving very slowly. I was receiving lag of multiple seconds for each keypress, while fuzzy searching my shell history. I tracked this issue to the following config from my .zshrc

```
# iTerm2 shell integration
test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"
```

Removing this line of code solves the problem for me. 

I don't use iTerm2 shell integration, so I don't need it and I stopped my investigation here. I figured I would submit an issue to document my findings, in case others are running into this issue as well.

Regards, thanks for fzf, I use it daily!
sheldon

**Comment by junegunn** [comment]
Hi, thanks for the heads up. I don't know about the script, but I'll look into it when I get a chance.

**Comment by rstacruz** [comment]
Thanks for the heads up! This affected me and I was using `fish`, not `zsh`. Apparently iterm2 also has bindings for fish.
