### ISSUE TITLE
Shell Example for `fo`

### ISSUE THREAD

**Issue by matthewgrossman** [junegunn/fzf#815]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [X] Etc.
- OS
    - [ ] Linux
    - [X] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [x] bash
    - [x] zsh
    - [ ] fish

I'm having an issue with [ `fo` in this Example diff](https://github.com/junegunn/fzf/wiki/Examples/_compare/71ef8907a8a81f2223d51c149c975105187a3048...535eff6eb1b0600f4954d491625426691a9d056f).

Hitting Enter (instead of `ctrl-o`, `ctrl-e`) doesn't seem to work for me. From examining `$out`, I've noticed that newline isn't in `${out[0]}`. My understanding of the correct behavior would be that `${out[0]}` is whatever key was pressed (blank for Enter, `ctrl-o` otherwise), followed by lines containing each of the selected results from fzf.

My guess is that when we starting wrapping the `$(fzf)` into an array (`($(fzf))`), the shell automatically dropped the blank line as the zero-eth character. Here's a demonstration:
```
bash-3.2$ IFS=$'\n' out=($(printf "hello\nworld" | fzf --expect=ctrl-o)) # press ctrl-o
bash-3.2$ echo ${out[0]}
ctrl-o
bash-3.2$ IFS=$'\n' out=($(printf "hello\nworld" | fzf --expect=ctrl-o)) # press enter
bash-3.2$ echo ${out[0]}
hello
```

When debugging this, I found out that bash 0-indexes their arrays while zsh 1-indexes them. This would also not make this example work, as I would expect `key=${out[1]}` in zsh. 

The prior version of this example [keeps `$out` as a string](https://github.com/junegunn/fzf/wiki/Examples/_compare/30cc2f41f2357cb9577d803dee3242d0335e6679...61fddc19c5ab9d374dd4246c15e6aedccf807ced) and uses `head`/`tail` to filter out the key/files. Though this isn't as syntactically pretty, it wouldn't introduce incompatibilities between bash/zsh (this project officially seems to support both), and it wouldn't run into this blank-line-array issue.

Let me know if you are able to reproduce the bug or if you see something that might be wrong with my setup.

**Comment by junegunn** [comment]
Thanks, you correctly spotted out a bash/zsh compatibility issue in the example. I agree with your suggestion and I just reverted the diff.

The write permission to the wiki page is publicly open, and I haven't thoroughly verified the changes people have made. I'm a bash user so I have made mistakes of not testing on zsh, and on the flip side, I guess there should be some examples that aren't carefully tested on bash. However, splitting the page into two (or three) seems like an overkill as it's just a set of examples to show how one can use fzf. I'll go over the examples when I get some time and remove the ones that are too complex and have compatibility issues.

**Comment by matthewgrossman** [comment]
Great, sounds like a excellent solution. I use bash or zsh depending on context, so I run into these issues pretty quickly. If I get a chance I'll try to go through some of the examples and update / make them as generic as possible.
