### ISSUE TITLE
execute-one or execute-and-quit [feature request]

### ISSUE THREAD

**Issue by acornejo** [junegunn/fzf#816]
These days I use fzf for everything (almost use it more than bash ;) ).

When writing long fzf scripts I have often wanted an execute-once command, which allows me to setup a key binding that will execute a given command and then exit fzf.

There are lots of examples where this is useful, but here is the most recent use case I had:

I am listing a lot of folders, where the user can select to which want to jump (i.e. like fcd or whatever), and if the user presses Ctrl-X I want fzf to copy the selected directory to the clipboard and exit. I can almost achieve this with --header 'Ctrl-X to copy' --bind 'ctrl-x:execute:echo {} | pbcopy', with the caveat that this will not cause fzf to exit, which is very annoying.

Thoughts?

PS: The new feature of fzf which makes it render nicely without tmux is AMAZING btw, I have wanted this for a long time.

**Comment by junegunn** [comment]
Normally I would suggest using `--expect` (you aware of it?), but I can relate since I have this:

```sh
export FZF_CTRL_R_OPTS="--preview 'echo {}' --preview-window down:3:hidden --bind '?:toggle-preview' --bind 'ctrl-y:execute(echo -n {2..} | pbcopy)' --header 'Press CTRL-Y to copy command into clipboard'"
```

I can see the appeal, no need for external scripting to handle `--expect`, and we can directly use the result of tokenization (`echo -n {2..}`).

However, I'm still left with a question if it's a right thing to do because fzf is a filter. Say that we implement `fork` action so I can write

```sh
export FZF_CTRL_R_OPTS="--bind 'ctrl-y:fork(echo -n {2..} | pbcopy)' --header 'Press CTRL-Y to copy command into clipboard'"
```

The problem is that now fzf becomes a completely different process producing different output than what's expected from the script invoking it in the first place.

**Comment by acornejo** [comment]
Thanks for bringing up `--expect` I have used it in the past but grepping through my dotfiles it seems I am not using it anymore, and I agree I can definitely handle my usecase without (at the expense of more complexity when handling the output of fzf).

I see your point about how implementing an fzf `fork` would be hard to do while mantaining sane behavior. However, I was trying to suggest something more similar to `execve` than `fork`.

Specifically, currently if I do `key:execute:cmd` then whenever I press `key` fzf will execute `cmd`, and when `cmd` completes fzf will render again. I was proposing adding `key:execute-and-quit:cmd` so that if I press `key` then fzf would execute cmd, so that when cmd finishes we also leave fzf and return at the shell prompt.

While hypothetically you could implement this using execve to replace the fzf process with the cmd process, perhaps it is simpler to implement by just having fzf execute cmd and exit when cmd returns.

What do you think? I hope I didn't miss the point you were describing.

**Comment by junegunn** [comment]
Understood.

> perhaps it is simpler to implement by just having fzf execute cmd and exit when cmd returns.

Yeah, it should be much simpler. Leads to another question: should fzf print the focused entry on exit or not? I mean, is it `execute-and-abort`, or `execute-and-accept`? What do you have in mind?

**Comment by acornejo** [comment]
To be honest initially I thought `execute-and-abort`, but now that you brought it up it seems obvious that `execute-and-accept` would be a lot more useful, especially given that one could easily achieve the effect of `execute-and-abort` by doing `fzf >/dev/null`.

If this is a feature you would contemplate adding to `fzf` but you are short on time I would be happy to contribute a PR to it.

**Comment by junegunn** [comment]
`execute-and-abort` and `execute-and-accept` both can make sense in `FZF_CTRL_R_OPTS` example depending on what I want. `abort` version can modify the behavior, and `accept` version can "inject" extra behavior without having to edit the original script.

Note that we also have `execute-multi`, so if we decided to support both options, we'll have to add 4 new actions in total. `execute{,-multi}-and-{accept,abort}`. I'm a little worried that this can quickly become unwieldy. Maybe it's a good idea to allow chaining actions? e.g. `toggle-up` can be expressed as `toggle+up`. So we can do `execute(...)+abort`, but this can't be applied to  the special form `execute:...`.

**Comment by acornejo** [comment]
Being able to chain multiple actions per binding is definitely a much more powerful idiom, I'll leave it up to you to evaluate how much more complicated this would be to implement.

The caveats about not being able to chain actions when using `execute:` doesn't seem like a bad thing, since that form already has caveats (can only be used on the very last comma separated key binding), and by design using that form will always introduce limitations since it essentially means you can't continue parsing the string once you reach that point.
