### ISSUE TITLE
[RFC] Drop ncurses dependency

### ISSUE THREAD

**Issue by junegunn** [junegunn/fzf#818]
- Category
    - [x] fzf binary

### Cross-compilation
With no ncurses dependency, cross-compilation becomes trivial and we can provide binaries for different OSs and platforms (freebsd, openbsd, arm*). Makefile and install script should be updated accordingly.

- Close #465
- Close #497 
- Close #685

### Official support for 24-bit colors

<img width="1280" alt="screen shot 2017-01-22 at 2 32 59 pm" src="https://cloud.githubusercontent.com/assets/700826/22180330/72f48b8e-e0b0-11e6-9cfa-5c0890010be5.png">

- Close #789 
- Close #357

## Trying it out

Alpha binaries will be uploaded to https://github.com/junegunn/fzf-bin/releases/alpha

**Comment by balta2ar** [comment]
Could you please demonstrate examples where 24bit color support is really helpful? I don't think I've ever used it, so maybe others could point out the benefits so that I could make my console experience better. Thanks.

**Comment by junegunn** [comment]
It's mostly about the looks (https://github.com/junegunn/fzf.vim/issues/294). Some people would use it to display images in the preview window (#738), but most terminal emulators (and fzf) are not really optimized for that use case, so it's not something I'd recommend at the moment.

**Comment by sliceofcode** [comment]
![2017-01-24-22 29 40](https://cloud.githubusercontent.com/assets/4206232/22280307/a2c5895a-e284-11e6-8e6f-9ac4896494c7.png)

Thank you! This works flawlessly.

**Comment by junegunn** [comment]
Good to hear that. Let me know if you run into any issues with the new version (a bug fix release is planned in the next few days).
