### ISSUE TITLE
fzf does not clean lines

### ISSUE THREAD

**Issue by ael-code** [junegunn/fzf#819]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [x] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

version: `0.16.1`

When fzf is invoked it does not clean the lines before to populate them. Thus if there is already something drown under the current line fzf will overlap it.

You can reproduce it with the following steps:
```
cd /etc/<TAB>
```
If you have autocompletion enabled you should see something like
![fzf_comple_pre](https://cloud.githubusercontent.com/assets/4229536/22199800/bdc05038-e15c-11e6-8de7-2bd825d8e247.png)

Then you invoke fzf:
```
cd /etc/**<TAB>
```
![fzf_comple_post](https://cloud.githubusercontent.com/assets/4229536/22199831/d7a022a8-e15c-11e6-817c-6153d21b999f.png)

**Comment by junegunn** [comment]
I believe it's fixed in devel branch. The fix will be included in the next version.
Can you check if the alpha binary in the link below doesn't have the issue?

https://github.com/junegunn/fzf-bin/releases/alpha

**Comment by junegunn** [comment]
Fixed in 0.16.2.

**Comment by ael-code** [comment]
> I believe it's fixed in devel branch. The fix will be included in the next version.
> Can you check if the alpha binary in the link below doesn't have the issue?
> 
> https://github.com/junegunn/fzf-bin/releases/alpha

I confirm that the bug has been fixed in the alpha release

**Comment by junegunn** [comment]
Yeah, and 0.16.2 is out.

**Comment by NullVoxPopuli** [comment]
I'm running in to this issue and I have 0.29 (devel) :upside_down_face:

**Comment by NullVoxPopuli** [comment]
just kidding same problem :(
