### ISSUE TITLE
Feature request: --preview without a preview window

### ISSUE THREAD

**Issue by danr** [junegunn/fzf#820]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.

One great use I have of fzf is to change buffers in the kakoune text editor. I am using a `--preview` command that sets the buffer immediately, which works as a nice preview. So, I do not use the stdout of this command which renders the preview window unecessary. The problem is that there does not seem to be any way to get rid of the preview window when using the preview command. This is a feature I would like to see in fzf.

**Comment by junegunn** [comment]
I see, it makes sense and it's something we can do relatively easily.

Since `--preview-window` already takes `hidden` flag (dormant), introducing another keyword for this invisible window will cause confusion. So let's use `--preview-window` option with size 0 (position doesn't matter) for this.

**Comment by balta2ar** [comment]
@danr May I ask you to record a gif or something similar to show how it looks like? I'm interested, maybe I would do the same.

**Comment by danr** [comment]
@junegunn thanks for the quick fix and for your efforts in making fzf!

@balta2ar I recorded a video and put it here: https://vimeo.com/200792397

**Comment by junegunn** [comment]
@danr Thanks for the interesting video. Inspired me to come up with #823.
