### ISSUE TITLE
fzf-vim Tags broken behaviour

### ISSUE THREAD

**Issue by yevhen-m** [junegunn/fzf#821]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [x] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

After update I got this issue:
![image](https://cloud.githubusercontent.com/assets/10185058/22227671/196aab36-e1d5-11e6-900a-c1bdd8953db0.png)
When I start to type, input line disappears and I land on the first matching tag. When I 'backspace', input line is back, but tags in fzf buffer are scrambled and redrawn when I go up with `<c-k>`.

Normal behaviour is this:
![image](https://cloud.githubusercontent.com/assets/10185058/22227710/3f51b416-e1d5-11e6-9dc0-8c66b354e007.png)

**Comment by junegunn** [comment]
Any clue why it's happening? I can't reproduce locally.

**Comment by yevhen-m** [comment]
I have the same problem with `:Tags` on my mac. Strange that only `:Tags` command misbehaves.

**Comment by yevhen-m** [comment]
I use `enew` layout in neovim. If I change it to `new`, then there is no problem BUT only if I use `:Tags` in the window with no vertical splits. If I open a vertical split  and use `:Tags` in the right vertical split, then problem is still present.

**Comment by junegunn** [comment]
I still can't reproduce even with `let g:fzf_layout = { 'window': 'enew' }`.

Can you check if you still have the issue with this minimal configuration?

```sh
nvim -Nu <(curl https://gist.githubusercontent.com/junegunn/6936bf79fedd3a079aeb1dd2f3c81ef5/raw/vimrc)
```

**Comment by yevhen-m** [comment]
If I add `let g:fzf_layout = { 'window': 'enew' }` to your minimal config, then issue is present. As I can see, default layout is not affected.

**Comment by junegunn** [comment]
Confirmed that the problem is caused by the way fzf handles tab characters. fzf has to recalculate the width of each line after trimming it.

```diff
diff --git a/src/terminal.go b/src/terminal.go
index d06f752..081f715 100644
--- a/src/terminal.go
+++ b/src/terminal.go
@@ -847,6 +847,7 @@ func (t *Terminal) printHighlighted(result *Result, attr tui.Attr, col1 tui.Colo
 				offsets[idx].offset[1] = util.Min32(offset.offset[1], int32(maxWidth))
 			}
 		}
+		displayWidth = t.displayWidthWithLimit(text, 0, displayWidth)
 	}
 
 	var index int32
```

**Comment by yevhen-m** [comment]
@junegunn thanks. Waiting for fzf 0.16.3.
