### ISSUE TITLE
Jump to line number

### ISSUE THREAD

**Issue by schef** [junegunn/fzf#824]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [x] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [x] bash
    - [x] zsh
    - [x] fish

It would be a cool feature to be able to select a line number when you search. I use fzf with bash history and sometimes it seems easier to just remember the line number and type for example 2006.

**Comment by balta2ar** [comment]
I think you can number bash history lines before streaming them to fzf, then you can filter by them.

**Comment by junegunn** [comment]
bash prepends line numbers to history by default, doesn't it? Anyway, I guess you want fzf to prepend line numbers to any type of input. It is possible, but we can already do manually.

```sh
ls -al | awk '{printf("%-3d %s\n", NR, $0)}' | fzf --tac | sed 's/^[0-9 ]* *//'
```

It's infinitely more flexible than fzf doing it automatically; think about the formatting of the line numbers, colors, padding, justification, etc. I'll close the issue, but thanks for the suggestion.

**Comment by junegunn** [comment]
FYI, you might want to check out jump action.

```sh
ls -al | fzf --bind 'tab:jump'
```
