### ISSUE TITLE
Unable to map 'ctrl-space'

### ISSUE THREAD

**Issue by petobens** [junegunn/fzf#825]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [x] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

Hi, is there a reason why `ctrl-space` bindings are not supported? Currently if try 
```
--bind=ctrl-space:toggle+down
```
I get `__fzf_history__ unsupported key: ctrl-space`. Thanks in advance!

**Comment by junegunn** [comment]
I was not sure if ctrl-space is universally supported by various terminal emulators. 

Excerpt from https://en.wikipedia.org/wiki/Control_character#How_control_characters_map_to_keyboards:

> The NULL character (code 0) is represented by Ctrl-@, "@" being the code immediately before "A" in the ASCII character set. For convenience, a lot of terminals accept Ctrl-Space as an alias for Ctrl-@.

But if it's supported by most of the popular terminal emulators, we can consider adding it to fzf.

**Comment by petobens** [comment]
Seems to work for me. Thank you!

**Comment by junegunn** [comment]
Thanks for the confirmation, 0.16.3 will be released in a few days.

**Comment by liuweiming1997** [comment]
@petobens Hello, I haven`t solved my problem, could u mind telling me what`s the syntax u use? thanks.
it does not work as my understanding.
```
bind -m emacs-standard -x '"\C-@": fzf-file-widget'
```

**Comment by petobens** [comment]
My question was about binding ctr-space within fzf. AFAICT you are trying to do so from within your bashrc.

**Comment by liuweiming1997** [comment]
My question also was about binding ctr-space within fzf...could u show me your `key-bindings.bash`?

**Comment by petobens** [comment]
Sure. This is how I bind it: https://github.com/petobens/dotfiles/blob/6ea423ebc6f828922af76b11f7feb9245e3b7642/fzf_bash.sh#L32-L41

**Comment by vimiPonyai** [comment]
thanks, guy. Your theme looks very amazing. @petobens
