### ISSUE TITLE
Weird behavior with ctrl-r on 0.16.3 and iterm2

### ISSUE THREAD

**Issue by benoittgt** [junegunn/fzf#826]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [X] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [X] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [X] zsh
    - [ ] fish

Hello
I've updated to 0.16.3 and I have weird completion issues now. It happens only in iterm2 not in terminal. It seems that text inserted are not display and the refresh behavior is strange. Is there someone who have the same issue? I'm using fzf since a year and have this issue with the update (don't remember which version I had before).

![jan-30-2017 16-34-59](https://cloud.githubusercontent.com/assets/8417720/22429199/13835fc6-e70a-11e6-9671-e40ef5059762.gif)

**Comment by benoittgt** [comment]
My bad. It's related to terminal type.

![capture d ecran 2017-01-30 a 17 02 55](https://cloud.githubusercontent.com/assets/8417720/22430262/f8f963d6-e70d-11e6-9e43-31c426dd00cd.png)

Be sure to have settings like this.

It's fixed. Thanks a lot for fzf.

**Comment by junegunn** [comment]
No problem, thanks.
