### ISSUE TITLE
Macvim iterm2 v3 integration

### ISSUE THREAD

**Issue by maitriyogin** [junegunn/fzf#827]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [x] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh/iterm2
    - [ ] fish

Hi,
I'v tried implementing the mac vim solution for iterm2 v3.
I'v created the script `~/.vim/In_a_new_term_function.vim` made it executable.

Also amended the following to .vimrc :
``` 
" == junegunn/fzf ==
let g:fzf_launcher = "In_a_new_term_function %s"`
nnoremap <C-T> :FZF<CR>
inoremap <C-T> <ESC>:FZF<CR>i
```

When I type ctrl-t in mccvim I get the following error :
```
Error running In_a_new_term_function '"/Users/stephenwhite/.fzf/bin/fzf"  --multi  --prompt '"'"'~/'"'"'  --expect=ctrl-v,ctrl-x,ctrl-t > /var/folders/0g/z7zq0_t56mb7hj_9y
zw39_tr0000gn/T/vGmvXDd/12'  
```

It works great on the command line and when running vim from iterm.

Any ideas as to what the problem is?

/Stephen.

**Comment by junegunn** [comment]
Try the following instead and see if it helps

```vim
let g:fzf_launcher = "~/.vim/In_a_new_term_function.vim %s"
```

it's a shell script, so `.vim` is not the right extension, but anyway.
