### ISSUE TITLE
fzf freeze in tmux. Can't kill process

### ISSUE THREAD

**Issue by fidelram** [junegunn/fzf#829]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

I normally run fzf inside tmux. I just check and I think that the process that runs is fzf and not fzf-tmux. The problem I have is that sometimes, after running fzf and selecting a line (or not selecting anything) I get the following output:

 `$(__fzf_history__)` 

What is quite annoying is that I don't know how to recover from this. Ctrl-Z or Ctrl-C don't do anything. The only solution has been to shutdown the tmux session.

I wonder if there is something that I could do to recover when this happens.

**Comment by junegunn** [comment]
I'm not sure what's happening there, but the latest version of fzf prefers to use `--height` option over fzf-tmux, so it's going to be a non-issue (if you don't insist on using fzf-tmux). You might want to consider upgrading fzf first.
