### ISSUE TITLE
error in auto completion - fzf-completion:18: unrecognized modifier 

### ISSUE THREAD

**Issue by kkurni** [junegunn/fzf#830]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    **- [X ] Completion**
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    **- [X ] Linux**
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    **- [X ] zsh**
    - [ ] fish

I get this error on my Linux every time i try to do autocomplete. e.g cd and then press Tab.
fzf-completion:18: unrecognized modifier

I try many things, upgrading to the latest zsh doesn't help.

The only thing is I can disable it in .fzf.zsh by removing this line.
[[ $- == *i* ]] && source "/local/home/kurniak/.fzf/shell/completion.zsh" 2> /dev/null

Otherwise I cannot use autocomplete at all.

Hopefully there is a way to enable this in my unix box.

Thanks

**Comment by junegunn** [comment]
What's your exact zsh version?

I would first try if it's possible to reproduce the problem even with a minimal zshrc.

**Comment by kkurni** [comment]
here is the version.
zsh 4.3.10 (x86_64-redhat-linux-gnu)

I tried to upgrade it with zsh 5.3 for linux, but it still does not work.

Thanks

**Comment by junegunn** [comment]
We don't support that version of zsh (#665 #733) which was released in 2012.

I haven't experienced the problem with zsh 5 or above. Works fine with zsh 5.3.

**Comment by Khalian** [comment]
does not work with 5.0.2

**Comment by junegunn** [comment]
Works with 5.0.2. It is tested on Travis CI environment (trusty).

https://travis-ci.org/junegunn/fzf

**Comment by agrandi** [comment]
I am currently using zsh 5.7.1  (x86_64-pc-linux-gnu) inside a tmux panel and I get the following error every time I press <TAB>:

```
fzf-completion:24: unrecognized modifier
```

Is this related? How can I debug this?

**Comment by Muffo** [comment]
I am currently using zsh 5.7.1 (x86_64-pc-linux-gnu) inside a tmux panel and I get the following error every time I press < TAB >:

```
fzf-completion:24: unrecognized modifier
```

Is this related? Should I open a new ticket?
