### ISSUE TITLE
multi select problem 

### ISSUE THREAD

**Issue by zakariaGatter** [junegunn/fzf#831]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [X] bash
    - [ ] zsh
    - [ ] fish

i want to use muti select in fzf but when i run this command : 

`echo -e "Back\n$(dpkg -l | grep "^ii" | awk '{print $2}')" | fzf -m --print0 --prompt="Select Package to Remove :>: " --reverse  --color=16`

the command work fine but the output is freak : 

`firefoxthunar`

but it should be look like that 

`firefox thunar`

if anyone know that solution help me thnx :1st_place_medal:

**Comment by junegunn** [comment]
I don't think you want to use `--print0` here. Use something like `tr` to replace new lines into spaces.
