### ISSUE TITLE
How to change git snippets from fzf-tmux to fzf

### ISSUE THREAD

**Issue by yevhen-m** [junegunn/fzf#833]
- Category
    - [ ] fzf binary
    - [x] fzf-tmux script
    - [ ] Key bindings
    - [x] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [x] bash
    - [x] zsh
    - [ ] fish

I enjoy your fzf git snippets a lot and use them very often. But now I'd like to change them, so they use `fzf` instead of `fzf-tmux`.
For instance, I have a snippet to select changed files:
``` zsh
gj() {
  is_in_git_repo || return
  git -c color.status=always status --short |
  fzf-tmux -m --ansi --nth 2..,.. \
    --preview 'NAME="$(cut -c4- <<< {})" &&
    (git diff --color=always "$NAME" | sed 1,4d; cat "$NAME") | head -'$LINES | cut -c4-
}
bind-git-helper() {
  local char
  for c in $@; do
    eval "fzf-g$c-widget() LBUFFER+=\$(g$c | join-lines)"
    eval "zle -N fzf-g$c-widget"
    eval "bindkey '^g^$c' fzf-g$c-widget"
  done
}
bind-git-helper j
```
But when I change `fzf-tmux` to `fzf`, then it stops working. Selected file names are not inserted on the line. Can you tell me what's wrong, or provide a correct way to do this? So I can change all other snippets as well.

**Comment by junegunn** [comment]
You probably need `zle redisplay` or `zle reset-prompt`.

See the updated code and the related discussion here:
https://gist.github.com/junegunn/8b572b8d4b5eddd8b85e5f4d40f17236

**Comment by yevhen-m** [comment]
@junegunn thanks a lot. Perfect as always.
