### ISSUE TITLE
Latest release does not contain a directory with version

### ISSUE THREAD

**Issue by krisleech** [junegunn/fzf#834]
The tar.gz for the [latest release](https://github.com/junegunn/fzf/releases/tag/0.16.4) does not contain a directory, e.g. `fzf-16.0.4`, but instead contains the binary only, `fzf`. All previous released tar's contain a directory which contains the binary.

I wanted to know if this was a mistake or this is how the releases will be from now on, I can update my build tool accordingly.

Many thanks.

**Comment by junegunn** [comment]
I believe you're talking about the file name of the binary in the tarball. It's an intended change. I decided that it would be easier for the users. Makefile and install script were updated accordingly. See https://github.com/junegunn/fzf/commit/ee5aeb8

**Comment by krisleech** [comment]
Thanks for the explanation. I'll update my Ansible task.

**Comment by lonix1** [comment]
@krisleech Do you have a sample/example ansible task for installing/configuring fzf for ansible?

That would be very useful, because as you know, fzf automatically modifies bashrc and zshrc etc., so would be useful to know what to manually configure when using ansible...

Thanks for any help!
