### ISSUE TITLE
Tag search is broken in vim

### ISSUE THREAD

**Issue by alxyang** [junegunn/fzf#835]
- Category
    - [x] fzf binary
    - [x] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [x] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [x ] bash
    - [ ] zsh
    - [ ] fish

![image](https://cloud.githubusercontent.com/assets/2774449/22662459/00a972ec-ec5e-11e6-8389-e5664b769f6c.png)

This is the output of `:Tags`
I ran `:PluginUpdate` via vundle to get the latest version of FZF and this still happens.

Actually, maybe this issue is better suited to go under https://github.com/junegunn/fzf.vim. Let me know if I should move it there.

**Comment by junegunn** [comment]
Looks like a configuration issue. Check if you can still reproduce the problem with a minimal vimrc

```sh
vim -Nu <(curl https://gist.githubusercontent.com/junegunn/6936bf79fedd3a079aeb1dd2f3c81ef5/raw/vimrc)
```

**Comment by alxyang** [comment]
Running with minimal vimrc did indeed solve the problem.  I then noticed in my vundle entries  I was only updating fzf.vim and I didn't have an entry for fzf.  Adding fzf and updating it fixed the problem.  Thanks!
