### ISSUE TITLE
sudo su fires fzf after install

### ISSUE THREAD

**Issue by jaymem** [junegunn/fzf#837]
- Category
    - [ x ] fzf binary
    - [ x ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ x ] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ x ] bash
    - [ ] zsh
    - [ ] fish

HI,

After installing fzf on an Ubuntu 16.04 AWS instance, when I type sudo su, it launches $(fzf)

I have to hit escape and it brings me to my root prompt. I am then stuck with fzf running and I can not use the command prompt until hitting ctrl + z.

I would like to access root shell using sudo su and not have it trigger fzf. Checked previous issues and could not find an occurrence of this.

Any thoughts are much appreciated.

[sudo su command invoking fzf.mov.zip](https://github.com/junegunn/fzf/files/759738/sudo.su.command.invoking.fzf.mov.zip)

**Comment by junegunn** [comment]
I'm cerntain that this is a configuration issue, and I can't really help you with that. Closely examine your configuration files to find out what's going on.

**Comment by jaymem** [comment]
What config files would I look at? It is definitely not .bashrc or the usual suspects. These have been closely vetted. Since this is a post fzf install issue, could fzf have modified a config file or create one?

**Comment by jaymem** [comment]
Here is a list of all my configs, I have gone through the usuals and nothing to indicate a replacement of sudo su to sudo $(fzf)
![2017-02-07](https://cloud.githubusercontent.com/assets/8275312/22724837/f52de968-ed96-11e6-81ad-33fbbf04454c.png)

**Comment by junegunn** [comment]
> could fzf have modified a config file or create one?

It (optionally) adds a line to your .bashrc for sourcing ~/.fzf.bash, that's all.

> Any idea which config could be the culprit?

Not sure. grep for `fzf`.

**Comment by junegunn** [comment]
I'm closing this, as I'm pretty certain that it's not an issue of fzf itself.
