### ISSUE TITLE
zsh alt-c keybind always changes working dir even when cancelling

### ISSUE THREAD

**Issue by DanielFGray** [junegunn/fzf#839]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [x] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

this is particularly annoying with `chpwd()` hooks like running `ls` automatically

I double-checked to see if this happens in bash but it didn't seem so (although I did notice it writes `__fzf_cd__` to the prompt? seems annoying...)

**Comment by junegunn** [comment]
Thanks, let's fix it, I left a comment on your PR.
