### ISSUE TITLE
fzf-tmux pane fails to open automatically when terminal is on 'vi editing-mode'

### ISSUE THREAD

**Issue by faruzzy** [junegunn/fzf#842]
- Category
    - [ ] fzf binary
    - [x ] fzf-tmux script
    - [x ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [x ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [x ] bash
    - [ ] zsh
    - [ ] fish

When using the functions shown here: https://gist.github.com/junegunn/8b572b8d4b5eddd8b85e5f4d40f17236
while having the following in my ~/.inputrc file:
set editing-mode vi
set keymap vi-command

Tmux fails to open the pane automatically until I press enter

**Comment by junegunn** [comment]
The snippets are written for non-vi mode. If you use vi mode, you'll have to slightly change it.

You might want to take a look at https://github.com/junegunn/fzf/blob/master/shell/key-bindings.bash to see how it's done.
