### ISSUE TITLE
Tmux completion example question

### ISSUE THREAD

**Issue by yevhen-m** [junegunn/fzf#843]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [x] Completion
    - [] Vim
    - [] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

I consider your [tmux example](https://github.com/junegunn/fzf/wiki/examples#tmux) very useful. But imagine a situation when there are ssh sessions in all the panes in the tmux window. I want to switch to another session, but I have to get to the local shell (find it in another window or create a new pane), and then call `fs`. Is it possible to bypass this limitation somehow? Ideally with a tmux binding, that will start session name completion or something like that, what do you think?

**Comment by junegunn** [comment]
Hi, actually most of the snippets in the wiki page are not mine. I haven't really used fs so far. I'll try it when I get some time.
