### ISSUE TITLE
Suggestion: Make Tab in Multi-select go in the direction of more files

### ISSUE THREAD

**Issue by berfarah** [junegunn/fzf#845]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [x] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

Allow me to explain!

In normal FZF mode, you have a list of files starting from the bottom going upwards. Tab goes in a downwards motion, meaning that you will always have to go up and down (2 actions per file) to select files.

In reverse order, tab continues to go downwards direction – but now in the same direction as the files – which has the nice side effect of being able to select the first few files with just one key stroke per file rather than two.

My suggestion would be to change Tab to go in the opposite direction for normal (non-`reverse`) mode to save on keypresses.

It's a small optimization that some people may disagree with, just thought I'd suggest it and see what you think!

Now that I have that out of the way, I just want to say I'm a huge fan of this project! I use this application countless times a day and it has a huge impact on my happiness when developing! Thank you for creating such a great product!

**Comment by junegunn** [comment]
> meaning that you will always have to go up and down (2 actions per file) to select files.

Shift-tab moves the cursor upward.

> My suggestion would be to change Tab to go in the opposite direction for normal (non-reverse) mode to save on keypresses.

You can use `--bind` option to map tab and shift-tab to `toggle-out` and `toggle-in` respectively instead of `toggle+down` and `toggle+up` like so:

```sh
fzf --bind tab:toggle-out,shift-tab:toggle-in -m
fzf --bind tab:toggle-out,shift-tab:toggle-in -m --reverse

export FZF_DEFAULT_OPTS="--bind tab:toggle-out,shift-tab:toggle-in"
```

The names of these actions are a bit obscure, they're named as such as they move cursor "outwards" and "inwards".

So why aren't they the default? First, because of backward compatibility, and second, I'm not sure that they are the better default for everyone. For me, I prefer that I can consistently move the cursor upwards with shift-tab and downwards with tab regardless of the layout.

> Thank you for creating such a great product!

Thanks :)

**Comment by berfarah** [comment]
Thanks for taking the time to answer my question. Completely understand that it's not better for everyone and there are issues with backwards compatibility - and with keybindings available for this I'm happy either way.

I just realized that the reason I didn't discover `shift-tab` is because a neovim issue where it isn't passed to the terminal correctly (which is slotted to be fixed in the next release). Hope this little tidbit of information can help other users.

**Comment by junegunn** [comment]
> shift-tab is because a neovim issue where it isn't passed to the terminal correctly

Oh, I see. I also noticed that before. Thanks for the clarification.
