### ISSUE TITLE
Key bindings working but errors shown

### ISSUE THREAD

**Issue by skamsie** [junegunn/fzf#846]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [x] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

Getting errors after running the command for key bindings:

```
/usr/local/opt/fzf/shell/key-bindings.bash:70: command not found: bind
/usr/local/opt/fzf/shell/key-bindings.bash:71: command not found: bind
/usr/local/opt/fzf/shell/key-bindings.bash:[:74: unknown condition: -gt
/usr/local/opt/fzf/shell/key-bindings.bash:79: command not found: bind
/usr/local/opt/fzf/shell/key-bindings.bash:83: command not found: bind
/usr/local/opt/fzf/shell/key-bindings.bash:86: command not found: bind
```

I run the command ` /usr/local/opt/fzf/install`, answer yes to all the questions, no errors. I restart the shell, the key bindings work, but first thing that gets printed are the errors above.

**Comment by junegunn** [comment]
Looks like your zsh config is loading ~/.bashrc, which is not syntactically compatible. I recommend that you don't do that, but it you insist, you can edit the line in .bashrc so that it's not loaded under zsh.

```sh
[ -z "$ZSH_NAME" ] && [ -f ~/.fzf.bash ] && source ~/.fzf.bash
```

**Comment by skamsie** [comment]
Yes, it looks like I was sourcing `.bashrc` in my `.bash_profile` which was then sourced in `.zshrc`. A big mess indeed. Thank you for your help.

**Comment by ical10** [comment]
Fixed it for me as well, thank you!

**Comment by KirillY** [comment]
In my case I set bash key bindings in `.zshrc` 
`source /usr/share/doc/fzf/examples/key-bindings.bash` 
Soulution was to change them to zsh ones
`source /usr/share/doc/fzf/examples/key-bindings.zsh`
