### ISSUE TITLE
fzf-contrib

### ISSUE THREAD

**Issue by lazywei** [junegunn/fzf#85]
As @junegunn suggests in #84, let discuss more detail about how to organize useful snippets for users.
A `fzf-contrib` would be great. Any other thought?

**Comment by george-b** [comment]
Would a github organization perhaps be an option? Something like this tmux organization https://github.com/tmux-plugins for example.

This would allow for separate repos which is useful for things like vim plugin managers. I've created a [repo](https://github.com/george-b/vim-fzf) which is essentially a mirror of the vim plugin in this repo with some minor additions purely to better integrate with my dotfiles.

**Comment by junegunn** [comment]
@george-b I'd thought about it. But felt that it would not be very useful to many, as everyone has different tastes and needs. So we would have to provide stuff that can be heavily customized, but then again, most of the stuff have only a few lines of code, so doing so can be an overkill or too much work at the same time. So, I'm currently okay with the current way of sharing examples on the wiki page. I have a feeling though, that the page is getting too long. We may need to split the page into sub pages.

**Comment by george-b** [comment]
@junegunn I suppose the vim plugin is the only complex thing, as you say the other snippets are fairly simple.
:+1: for breaking up the wiki though.

**Comment by lazywei** [comment]
@george-b @junegunn 

Sorry I totally forgot this issue ...

I'm somehow against placing snippets in wiki as it's not easy to maintain them (without version control, and modification management). Either placing them into fzf repo, or using `fzf-contrib` to contain them would be better, IMHO.

By the way, @george-b , if you'd like to, maybe I can add you as fzf-contrib's collaborator, and then we can transfer the snippets to that repo?

Thanks.

**Comment by junegunn** [comment]
@lazywei @george-b I see it differently now. For me, they are just examples to give the idea of what can be done with fzf, so I don't think strict version management is really required. I want the users of fzf to creatively come up with their own solutions to their problems on their environment after skimming through the examples, instead of just picking up random stuff without fully understanding them. In the sense, I think wiki pages, blog posts or [video screencasts](https://www.youtube.com/playlist?list=PLqv94xWU9zZ2fMsMMDF4PjtNHCeBFbggD) should suffice. Anyway, that's just my idea.

**Comment by D630** [comment]
Hey, if someone is still interested in "organizing" code snippets around fzf, have a look at [this](https://github.com/D630/fzf-contrib). It's simply a first draft (or something like that). Feel free to fork and modify it to your needs.

**Comment by teto** [comment]
@D360, thanks for the initiative. I like the way ctrlp snippets do things. If you want to filter on registers you can install the plugin  'ctrlp-register' and then add it to the list of authorized ctrlp plugins. IMO the contrib folder could split the snippets into several repositores "fzf-registers.vim", "fzf-marks.vim" what do you think ?
