### ISSUE TITLE
Do we really need `--ignore .git` when...

### ISSUE THREAD

**Issue by ikariwing** [junegunn/fzf#850]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [ ] fish

I noticed that an explanation in README.md:

> If you don't want to exclude hidden files, use the following command:
> export FZF_DEFAULT_COMMAND='ag --hidden --ignore .git -g ""'

For the `--ignore .git` part, if I understand correctly, ag will ignore .git by default and `--hidden` will not change that behavior, so I was wondering why this part is there.

By the way, you did a good job, which is exactly what I want :)

**Comment by junegunn** [comment]
Hi, if I'm not mistaken, we need to explicitly exclude `.git` when using `--hidden` option.

See https://github.com/ggreer/the_silver_searcher/issues/790

**Comment by ikariwing** [comment]
I am not sure whether it's a back-compatibility issue of ag,
however on my machine, 
`--unrestricted` reveals the .git, 
while `--hidden`  don't.

My ag version:
```
╰─➤  ag --version                                                                                                                                                              1 ↵
ag version 1.0.2

Features:
  +jit +lzma +zlib
```

Feel free to close this issue if you want, since it seems that no harm.
고맙습니다

**Comment by junegunn** [comment]
I just updated ag to the latest, but I'm still seeing .git directory with `--hidden` as follows:

```
> ag --version; ag --hidden -g "" | grep ^.git/
ag version 1.0.2

Features:
  +jit +lzma +zlib
.git/config
.git/description
.git/HEAD
.git/hooks/applypatch-msg.sample
.git/hooks/commit-msg.sample
.git/hooks/post-update.sample
.git/hooks/pre-applypatch.sample
.git/hooks/pre-commit.sample
.git/hooks/pre-push.sample
.git/hooks/pre-rebase.sample
.git/hooks/pre-receive.sample
.git/hooks/prepare-commit-msg.sample
.git/hooks/update.sample
.git/info/exclude
```

I'm not sure why you're getting different results, but anyway, we'll have to keep it.

ありがとうございます :)

**Comment by ikariwing** [comment]
Hi, sorry to mislead you :$
I found the different result on my machine was due to my .agignore setting, which already includes .git/.hg/.svn .
So we do need the `--ignore .git` as you said.

And I might also mislead you about my nationality since my GitHub name is Japanese-like. Actually, I am a completely Taiwanese ;-)

謝謝！

**Comment by junegunn** [comment]
@ikariwing Whoops, my bad, thanks for the clarification :)
