### ISSUE TITLE
How to perform case insensitive search in fzf?

### ISSUE THREAD

**Issue by hezjing** [junegunn/fzf#852]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [x] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [ ] Mac OS X
    - [x] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [ ] fish

May I know to perform case insensitive search in fzf?

**Comment by hezjing** [comment]
It looks like typing the pattern in lowercase will search files in case insensitive mode. Typing the pattern in uppercase will search files in case sensitive mode?

**Comment by mbudde** [comment]
`fzf -i` to force case-insensitive search. Default is smart-case match where the search will be case-sensitive if you use at least one uppercase letter your pattern and case-insensitive otherwise. Take a look at `fzf --help` for all options you can give to FZF.
