### ISSUE TITLE
suggestion : ctrl t in command line

### ISSUE THREAD

**Issue by FinallyFinancialFreedom** [junegunn/fzf#853]
so, ctrl-t will list all files and direcotries. can you detect it automatically ? i mean, when cd ctrl-t, it only list directories like `cd $(find . -type d |fzf)` while vi ctrl-t, it only list files. Maybe vi a directory is useful sometimes.

**Comment by junegunn** [comment]
It's not possible on bash. For that purpose, you are supposed to use fuzzy completion `cd **<tab>`. If you use zsh, see https://github.com/junegunn/fzf/wiki/Configuring-fuzzy-completion#zsh
