### ISSUE TITLE
Ability to bind `

### ISSUE THREAD

**Issue by sassanh** [junegunn/fzf#854]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [x] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [ ] fish

It'd be great if we could bind ` to some action. Some people map ` to `<esc>` in vim and it'd be nice if we could have same binding in fzf.

**Comment by junegunn** [comment]
```sh
fzf --bind '`:abort'
```

See `man fzf` for more info.

**Comment by sassanh** [comment]
I read about bind, I should've provide more context: while `set -x FZF_DEFAULT_OPTS '--bind shift-tab:down,tab:up,q:abort'` works `set -x FZF_DEFAULT_OPTS

```--bind shift-tab:down,tab:up,`:abort' ```

doesn't work

**Comment by junegunn** [comment]
Note that I wrapped the expression with single quotes.

**Comment by junegunn** [comment]
Try this:

```sh
FZF_DEFAULT_OPTS='--bind \`:abort' fzf
```

**Comment by sassanh** [comment]
Thanks, escaping `` ` `` fixed it.
