### ISSUE TITLE
Processing user input and matching it with list like vim-abbrev-matcher

### ISSUE THREAD

**Issue by sassanh** [junegunn/fzf#855]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [ ] fish

I'm using this ctrlp plugin https://github.com/sergei-dyshel/vim-abbrev-matcher, it's really nice. For example an input like `'cp '/xyz '/test/` in fzf can be written there like this `cp/xyz/test/` which is 5 characters less and that's a lot for an abbrev matcher. I was thinking maybe we can have the same here in fzf maybe as an optional alternative.

**Comment by junegunn** [comment]
I'm not interested in adding more modes to keep it simple. In fact, I don't think another mode is needed in this case. fzf already has a sophisticated ranking algorithm so just type in `cp/xyz/test` (or just `cpxyztest`) and you'll most likely get the result you want as the top match.

See https://github.com/junegunn/fzf/blob/master/src/algo/algo.go for the details.

**Comment by sassanh** [comment]
Is it possible to apply a custom calibration for this ranking algorithm for end user?
This is the problem in details:

I have lots of curl requests copied from chrome (long curl requests) in my fish history. When I press `c-r` and search for a specific curl request, when I type `curl` it brings results with `curl` highlighted, when I type the hostname for example or some parameter in the curl request I'm searching for (whatever except the first word in the history items which is curl) fzf brings results that 2 out of 14 have that exact word highlighted (which aren't top results) and others have the letters of that word shuffled in the whole item. It'd be nice if we could have it bring results that have the exact word with higher rank.

**Comment by junegunn** [comment]
Have you read this part?

https://github.com/junegunn/fzf#key-bindings-for-command-line

**Comment by sassanh** [comment]
Oh sorry, it works perfectly after pressing `c-r` again.

**Comment by junegunn** [comment]
Yeah, I have noticed that many users are unfortunately unaware of it. So I've been thinking if it would be better to add something like `--header "Press CTRL-R to toggle sort"` to avoid confusion. But that can be annoying to the users who already know that.

Anyway, to enable sort by default, you can add `--sort` to `$FZF_CTRL_R_OPTS`.

**Comment by sassanh** [comment]
Yeah I was reading this conversation: https://github.com/junegunn/fzf/commit/a57b375b413e12b01e648d4fcaf91e29a53ae75d

In fzf-vim we have `Press CTRL-S to toggle sort`. I never expected sort to mean "sort by relevance to input" here. Maybe you can show a message only when the user hasn't use this feature yet.

**Comment by junegunn** [comment]
Well, I just decided to enable it by default.
