### ISSUE TITLE
Armhf / aarch64 support

### ISSUE THREAD

**Issue by dopykuh** [junegunn/fzf#857]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.

Prebuilt binaries for armhf / aarch64 on linux?

**Comment by junegunn** [comment]
I'm not familiar with that platform. Does arm8 binary work there? I'm building it with `GOOS=linux GOARCH=arm64`.

https://github.com/junegunn/fzf-bin/releases/download/0.16.5/fzf-0.16.5-linux_arm8.tgz

**Comment by dopykuh** [comment]
I'll try it on my odroid and pine64 later ;)

Am 25.02.2017 15:23 schrieb "Junegunn Choi" <notifications@github.com>:

**Comment by dopykuh** [comment]
Odroid seems to be a armv7l, so this works fine ;)
