### ISSUE TITLE
First result always has ?[?1h?= prepended

### ISSUE THREAD

**Issue by KibaFox** [junegunn/fzf#860]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [x] fish

Mac OS X Version: 10.11.6 (El Capitan)
Fish Version: 2.5.0
fzf Version: 0.16.5
iTerm2 Version: 3.0.14
`TERM=xterm-256color`

When I run the `fzf` command to search for files, I always get `?[?1h?=` added to the front of the first result.

For example, when I run `fzf` in my fish configuration folder I get something like this:
```
functions/fish_right_prompt.fish
functions/fish_prompt.fish
functions/fish_greeting.fish
?[?1h?=config.fish
```

If I run `bash` from `fish`, I still get the `?[?1h?=` prefixed to the first result.

If I change my shell over to `bash` using `chsh -s /bin/bash`, then the first result is correct and does not have the prefix.

**Comment by junegunn** [comment]
Hmm, that's strange. Is `?[?1h?=` cleared when you press CTRL-L, or move the cursor up and down?

**Comment by KibaFox** [comment]
Yeah. I'm perplexed at where this is coming from...

Pressing `Ctrl+L` and moving the cursor up and down (using the arrow keys) does not clear the `?[?1h?=`.

**Comment by KibaFox** [comment]
I noticed that if I change my shell over to `bash` using `chsh -s /bin/bash` and run `fish` from `bash` I don't get the `?[?1h?=` prefix.

Could Mac OS be doing something to login shells?  I diffed the environments in `bash` and in `fish` and nothing really stood out. 

For reference, here's how I installed `fish` on the Macbook Pro:

1. Install via `brew install fish`
2. Add `/usr/local/bin/fish` to `/etc/shells`
3. Run `chsh -s /usr/local/bin/fish`

**Comment by junegunn** [comment]
Hmm, I followed the steps, but I can't reproduce the problem.

**Comment by KibaFox** [comment]
This must be an issue with my system then.  I'm going to go ahead and close the issue, but I'll report back if I find a solution.  Thank you for trying to reproduce this, @junegunn!

**Comment by KibaFox** [comment]
Ah!  I figured out what was causing the issue.

I had put in a fix, copied from a [discussion on the issue](https://github.com/fish-shell/fish-shell/issues/2139#issuecomment-137228149), to get the delete key to work when using the suckless terminal (st).  Taking this fix out solves the problem.

Here is the culprit found in my [dotfiles/fish/config.fish](https://github.com/KibaFox/dotfiles/blob/06c5119966b8e40a70461b1ffb14956280e951e9/fish/config.fish):
```fish
# Fix the delete key when using st
# https://github.com/fish-shell/fish-shell/issues/2139#issuecomment-137228149
tput smkx ^/dev/null
function fish_enable_keypad_transmit --on-event fish_postexec
    tput smkx ^/dev/null
end

function fish_disable_keypad_transmit --on-event fish_preexec
    tput rmkx ^/dev/null
end
# end of - Fix the delete key when using st
```

**Comment by tomsmeding** [comment]
Sorry for bumping an old issue, this is just a note for future confused users who land here.

I had the same issue with the smkx hack for st + fish; the direct reason why this gives problems with fzf is because fzf (of course) spawns [shell commands using $SHELL](https://github.com/junegunn/fzf/blob/e6d33f77da8cc36786c814f499f6cb3405e8c4c1/src/util/util_unix.go#L13), and $SHELL is `fish`. With the smkx hack, any time you start fish, it will print that code, which is precisely what you see in the fzf preview window when this happens: `tput smkx` prints `\e[?1h\e=`.

But doing `tput smkx` doesn't make sense if you're not in a terminal session, so my advice is: put the smkx hack in an `if isatty; ...; end` block, and fzf --preview works fine again. :)

**Comment by KibaFox** [comment]
@tomsmeding that's excellent!  Could you write a code snippet that shows exactly what you mean?

That'll allow others who are having the issue to have a quick copy & paste solution that's improved from the one I previously made.

**Comment by tomsmeding** [comment]
Quick turnaround over here :)

I looked around a little better, and also found [this comment](https://github.com/fish-shell/fish-shell/issues/2139#issuecomment-305506138) later on in the fish issue linked above, where we all have the hack from.

It seems tmux writes smkx to the terminal itself now ([source](https://github.com/fish-shell/fish-shell/issues/2139#issuecomment-286643633)), so all that remains is fixing it for bare `st`.

I rewrote your snippet using some newer `fish` syntax and some stuff from the comment I found above; I think this solves everything nicely (and indeed fixes the behaviour in fzf --preview):

```fish
# Fix the delete key when using st
# https://github.com/fish-shell/fish-shell/issues/2139#issuecomment-305506138
if string match -qr '^st-' "$TERM" && status is-interactive
    tput smkx 2>/dev/null
    function fish_enable_keypad_transmit --on-event fish_postexec
        tput smkx 2>/dev/null
    end

    function fish_disable_keypad_transmit --on-event fish_preexec
        tput rmkx 2>/dev/null
    end
end
# end of - Fix the delete key when using st
```
