### ISSUE TITLE
Customizing color of UI elements

### ISSUE THREAD

**Issue by alexlafroscia** [junegunn/fzf#861]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [x] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

More of a question than anything; How do you custom the color of the part of the UI that appears brown here?

<img width="647" alt="screen shot 2017-02-26 at 10 00 40 pm" src="https://cloud.githubusercontent.com/assets/1645881/23350406/26aadd66-fc6f-11e6-9c60-b6f8452136e8.png">

I've been through all of the documentation on editing the colors used, and was able to get all the rest of it to match my color scheme. However, none of them seem to adjust that part.  For what it's worth, I looked through the source code as much as I could, but didn't have much luck working it out for myself.

**Comment by junegunn** [comment]
That grey line is the statusline of fzf buffer in Neovim. It's currently customizable via User autocmd.
See here: https://github.com/junegunn/fzf.vim#status-line-neovim

If you only need to change the colors, you can assign colors to fzf{1,2,3} highlight groups like so:

```vim
hi fzf2 guifg=yellow ctermfg=yellow guibg=blue ctermbg=blue
```

**Comment by alexlafroscia** [comment]
Excellent! That worked, thanks so much!
