### ISSUE TITLE
Navigating directories

### ISSUE THREAD

**Issue by dsjkvf** [junegunn/fzf#862]
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

After inspecting Wiki and a bit of googling, I've combined a script for `fzf` for navigating directories, which:

  - either presents `fzf` with a list of parent directories *and their surroundings* all the way up till the root
  - or the list of nested directories
  - or a combined list of these two

Now, what do I mean by *surroundings*? Imagine the following structure:

    ~/
     | -- Applications
     |----ABC.app
     |------Contents
     |----XYZ.app
     |------Bin
     |----MyTestSuite
     |------Dir1
     |------Dir2
     |------Dir3
     |--------YouAreHere

Then, navigating parent directories will usually only let you choose from `Dir3`, `MyTestSuite`, `Applications`, `/`. However, I find myself usually seeking to change to some nearby directory. Thus, this script will present you with the following choices: `Dir3`, `Dir2`, `Dir1`, `MyTestSuite`, `XYZ.app`, `ABC.app`, `Applications`, `/`.

Now, it's definitely not some rocket science task, and I'm sure everyone interested already has something like this. Therefore (and since I myself am not a programmer by all means), I'd very grateful for possible advices, corrections or optimizations (it's kinda slow on large lists).

Here it goes (requires `realpath` or [similar](http://stackoverflow.com/a/3572105/1068046)):

    fdz() {
        # Define variables
        local declare parent_dirs=()
        # Defne helpers
        get_parent_dirs() {
            # if an argument provided to this function is not a directory the function was called from...
            if [[ "${1}" != $PWD ]]
            then
                # ...but is a directory and not a file...
                if [[ -d "${1}" ]]
                then
                    # ...store it to the resulting array
                    parent_dirs+=("$1")
                    # now, if an argument provided to this function is not a root directory...
                    if [[ "${1}" != '/' ]]
                    then
                        # ...then explore its content one by one
                        # (both normal and "hidden" files)
                        for the_subdir in $(find -L "${1}" -type d -maxdepth 1 -not \( -name .git -prune \))
                        do
                            # and if the content in question is a directory...
                            if [[ -d "${the_subdir}" ]]
                            then
                                # ...and it wasn't already stored...
                                if ! [[ " ${parent_dirs[*]} " =~ "${the_subdir}" ]]
                                then
                                    # ...store it to the resulting array, too
                                    parent_dirs+=("$the_subdir")
                                fi
                            fi
                        done
                    fi
                else
                    return # does it happen at all?
                fi
            fi
            # if the argument provied to this function is a root directory already
            if [[ "${1}" == '/' ]]
            then
                # then stop and print out the resulting array
                for the_dir in "${parent_dirs[@]}"
                do
                    echo $the_dir
                done
                # otherwise use recursion to dive deeper
                # (dirname <DIR> returns the parent directory)
            else
                get_parent_dirs $(dirname "$1")
            fi
        }
        # Define main
        if [ "$1" == "--all" ]
        # if asked for directories in both diretions...
        then
            # define variables
            local declare all_sub_dirs=()
            # find all nested subdirectories
            while read sub_dir
            do
                abs_sub_dir="${sub_dir/./$PWD}"
                all_sub_dirs+=("$abs_sub_dir")
            done < <(find -L . -type d -not \( -name .git -prune \))
            # request all parent directories
            all_parent_dirs=($(get_parent_dirs $(realpath "$PWD")))
            # join these two arrays
            both_ends=("${all_sub_dirs[@]}" "${all_parent_dirs[@]}")
            # run fzf
            local DIR=$(for i in "${both_ends[@]}"; do echo $i; done | fzf --exact --preview "tree -C {} | head -200")
            cd "$DIR"
        # if asked only for nested directories
        elif [ "$1" == "--down" ]
        then
            # define variables
            local declare all_sub_dirs=()
            # find all nested subdirectories
            while read sub_dir
            do
                abs_sub_dir="${sub_dir/./$PWD}"
                all_sub_dirs+=("$abs_sub_dir")
            done < <(find -L . -type d -not \( -name .git -prune \))
            # join these two arrays
            # run fzf
            local DIR=$(for i in "${all_sub_dirs[@]}"; do echo $i; done | fzf --exact --preview "tree -C {} | head -200")
            cd "$DIR"
        # if asked only for parent directories
        else
            # request all parent directories
            all_parent_dirs=($(get_parent_dirs $(realpath "$PWD")))
            # run fzf
            local DIR=$(for i in "${all_parent_dirs[@]}"; do echo $i; done | fzf --exact --preview "tree -C {} | head -200")
            cd "$DIR"
        fi
    }

**Comment by dsjkvf** [comment]
(On a side note, could someone please explain, why I have to declare a var **before** the subfunction this var will only be used in? I'd expected to declare it inside, why this is wrong?)

**Comment by junegunn** [comment]
Interesting idea. Here's my take. 

```sh
traverse-upwards() {
  local dir=$(
    [ $# = 1 ] && [ -d "$1" ] && cd "$1"
    while true; do
      find "$PWD" -mindepth 1 -maxdepth 1 -type d
      echo "$PWD"
      [ $PWD = / ] && break
      cd ..
    done | fzf --tiebreak=end --height 50% --reverse --preview 'tree -C {} | head -200'
  ) && cd "$dir"
}
```

(I think `--tiebreak=end` works better in this case than the default `--tiebreak=length`)
