### ISSUE TITLE
--Hidden not working

### ISSUE THREAD

**Issue by IQubic** [junegunn/fzf#864]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [ ] fish

 It doesn't look like --hidden is working for me. Even running `fzf --help` doesn't show a --hidden flag existing. Why then does the README say that --hidden is a thing that works? Is there anything I'm missing, or does --hidden just not work?

**Comment by junegunn** [comment]
I believe you misread the documentation.
