### ISSUE TITLE
Suggestion: Allow mlocate/slocate as file list sources as opposed to find

### ISSUE THREAD

**Issue by fourjay** [junegunn/fzf#865]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [x] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [x] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [x] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [x] bash
    - [x] zsh
    - [x] fish

The shell script bindings use find. For large filesets this takes an appreciable time, and given find's nature this is probably unavoidable. I've tested against mlocate/slocate /file/path and see that fzf finishes almost instantly. Would you be open to providing a environmental variable to control what utility does the underlying searching for the built shell bindings?

**Comment by junegunn** [comment]
We already have configuration variables.

https://github.com/junegunn/fzf#key-bindings-for-command-line
