### ISSUE TITLE
drop down for files with Specific extension (say *.java)

### ISSUE THREAD

**Issue by sivaswami** [junegunn/fzf#866]
- Category
    - [X ] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ X] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ X] bash
    - [ ] zsh
    - [ ] fish

I want to create a short cut for editing all java files , *.java  from my root folder.
Is there any way I can list like

vi **.java <tab>

or  do I need special coding / script for this ?

**Comment by junegunn** [comment]
The current implementation of fuzzy completion provided in this repository only supports `**` at the end of the pattern. So you can do `vim .java**<tab>` (or `vim ~/my-project/.java**<tab>`). fzf will start with `.java` as the default query, and you can type in the rest of the pattern [after a space](https://github.com/junegunn/fzf#search-syntax)

`> .java foobar`.
