### ISSUE TITLE
FZF clears previous line of prompt

### ISSUE THREAD

**Issue by paymog** [junegunn/fzf#867]
- Category
    - [x] fzf binary
    - [x] fzf-tmux script
    - [ ] Key bindings
    - [x] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [x] CentOS7
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

I have a multiline prompt in zsh and recently updated fzf (I don't know the previous version I was on unforutnately). I've found that now when I hit CTRL-T in my prompt to bring up the search window then ESC out of it, the previous line in my prompt gets erased. See https://imgur.com/a/TJyep

I just tested making my prompt a single line and the issue doesn't persist. See https://imgur.com/a/9UDtj

**Comment by junegunn** [comment]
Can you share the source code for your prompt so I can test with it?

**Comment by paymog** [comment]
Here's a copy of my prompt: http://pastebin.com/9EG9aCWx

It's a shittily modified version of https://github.com/sorin-ionescu/prezto/blob/master/modules/prompt/functions/prompt_sorin_setup

Thanks for following up on this!

**Comment by junegunn** [comment]
Well, I tried your config (which required me to install prezto as well), but it seems like it has issues not only with fzf but also with other command-line completions. For example, simply doing `vim <tab>` or `ls <tab>` causes the problem you described. I think you should fix the issue first. Let me know if you still have problems with fzf bindings even after that.

**Comment by paymog** [comment]
Interesting, that doesn't happen for me.
![ls not broken](https://cloud.githubusercontent.com/assets/1986950/23563699/a3986a60-fffc-11e6-9449-6730f68c23ae.gif)

**Comment by paymog** [comment]
Oh, nevermind. I was able to repro with `ls` too.

**Comment by paymog** [comment]
@junegunn I can't repro this issue with `ls <tab> <ctrl-c>` or `vim <tab> <ctrl-c>` anymore but now `<ctrl-t> <down arrow> <enter>`, `<ctrl-t> <esc>` and `<ctrl-t> <ctrl-c>` all cause the previous line to be eaten.

If you don't mind looking into this again, here's my latest prompt: https://github.com/paymog/prezto/blob/4a5a78b744c111f506623754a91bebb2925bbbb0/modules/prompt/functions/prompt_sorin_setup

**Comment by paymog** [comment]
This also happens with the `steeef` prompt that's packaged with `prezto`. Also the `bart` prompt.

**Comment by ivanalejandro0** [comment]
It looks like the problem is with the multi-line prompts, see here: https://github.com/junegunn/fzf/issues/490

**Comment by juanibiapina** [comment]
This is not fixed on `zsh 5.7.1 (x86_64-apple-darwin17.7.0)`
