### ISSUE TITLE
tab completion in fish

### ISSUE THREAD

**Issue by cvogt** [junegunn/fzf#868]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [x] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [x] fish

has command tab completion for fish been considered? e.g.  `git co<tab>`

**Comment by junegunn** [comment]
No, I don't use fish, so patches are welcome. Note that we don't support `git co<tab>` even in bash and zsh.

**Comment by blankname** [comment]
@faho That's pretty nice. Unfortunately `complete -C` doesn't seem to always return the same results that you get with tab completion in fish (with `commandline -f complete`).

An area where this occurs is with file name sub-strings that aren't exact prefixes. 
An example is this commandline while in a directory containing a file named `presubpost`.
`cp sub`

Tab completion will complete the file name, `complete -C` (or `complete -C'cp sub'`) won't return any completions.

**Comment by weaming** [comment]
Another version of complete function https://gist.github.com/weaming/765703bb6e295cffdfcc16ac6cf037ac

**Comment by c02y** [comment]
> Try this:
> 
> ```fish
> function fzf_complete
>     set -l cmdline (commandline)
>     # HACK: Color descriptions manually.
>     complete -C | string replace -r \t'(.*)$' \t(set_color $fish_pager_color_description)'$1'(set_color normal) \
>     | fzf -d \t -1 -0 --ansi --header="$cmdline" --height="80%" --tabstop=4 \
>     | read -l token
>     # Remove description
>     set token (string replace -r \t'.*' '' -- $token)
>     commandline -rt "$token"
> end
> 
> bind \t 'fzf_complete; commandline -f repaint'
> ```
> 
> I don't think that's something I'd merge, but it's a neat experiment.

Thanks, this is very useful, but how can I use `Tab`/`Shift-Tab` to navigate the fzf list like `UP/DOWN`?

**Comment by junegunn** [comment]
Closing (until someone decides to implement and maintain the fish version).
