### ISSUE TITLE
Chocolatey package

### ISSUE THREAD

**Issue by majkinetor** [junegunn/fzf#869]
FYI, 

I maintain chocolatey package and it will keep all versions, with up to few hours latency after you release on Github:

https://chocolatey.org/packages/fzf

The update is automated and the report is available here: https://gist.github.com/majkinetor/a700c70b8847b29ebb1c918d47ee4eb1

Windows users can install fzf now with: `cinst fzf` or `cinst fzf --version x.y.z`.

The binaries are embedded in the package and will always work regarding the github status.

Cheers, and thanks for the great tool.

**Comment by junegunn** [comment]
Thanks for letting me know, I'll add the link to the README page.
