### ISSUE TITLE
cd tab completion not working

### ISSUE THREAD

**Issue by tnguyen14** [junegunn/fzf#872]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [x] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

For some reason, `cd <tab>` is not auto-complete for me. I am running on a linux terminal X11-forwarded to a Windows machine.

fzf version is `0.16.6`.

I have narrowed down the problem to these lines in `shell/completion.bash`:
```sh
# Directory
for cmd in $d_cmds; do
  _fzf_defc "$cmd" _fzf_dir_completion "-o nospace -o plusdirs"
done
```

Commenting them out gives me back the regular tab autocompletion behavior.

Please let me know if there's some way I could debug this further.

**Comment by dqgthb** [comment]
You should `cd **<tab>` I guess?

**Comment by tnguyen14** [comment]
I'm not sure what you mean. `cd foo<tab>` should match any file/ directory that starts with `foo`.

**Comment by dqgthb** [comment]
Oh sorry, I guess I now understand what you meant. You are saying that the normal, default bash behavior of autocompletion does not work after installing FZF, right? That sounds strange.

**Comment by tnguyen14** [comment]
@dqgthb  yes that's exactly what I meant. It is very strange to me too.

**Comment by junegunn** [comment]
- > Is that only for cd, or for others as well such as vim foo<tab>?
- What's the output of `complete | grep cd$`?

**Comment by tnguyen14** [comment]
It is for others as well, not just `cd`.

And the output for `complete | grep cd$` is
```
complete -o nospace -F _fzf_dir_completion cd
```

**Comment by junegunn** [comment]
Hmm, it looks different than mine:

```sh
complete -o nospace -o plusdirs -F _fzf_dir_completion cd
```

Not sure why, bash version?

**Comment by tnguyen14** [comment]
Hmm yeah I'm not sure - the one I have is bash version `4.3.42(1)`

**Comment by junegunn** [comment]
What happens when you directly paste the command (`complete -o nospace -o plusdirs -F _fzf_dir_completion cd`) on your shell? Still no `plusdirs`?

**Comment by tnguyen14** [comment]
Sorry for the slow response. I needed to wait and try it on the work
terminal where this is happening.

If I paste the command on the shell directly, tab completion for `cd` works
again.

**Comment by junegunn** [comment]
Then it's probably you have some other plugin or configuration that are interfering with completion. Can you check if you can still reproduce the problem with a vanilla bashrc that only loads fzf and nothing else?

**Comment by tnguyen14** [comment]
Here's what I just tried:

```shell
:; bash --noprofile --norc
# cd tab-completion works
:; source ~/.fzf.bash
# now tab-completion does not work
:; cat ~/.fzf.bash
# Setup fzf
# ---------
if [[ ! "$PATH" == */home/tnguyen14/.fzf/bin* ]]; then
  export PATH="$PATH:/home/tnguyen14/.fzf/bin"
fi

# Auto-completion
# ---------------
[[ $- == *i* ]] && source "/home/tnguyen14/.fzf/shell/completion.bash" 2> /dev/null

# Key bindings
# ------------
source "/home/tnguyen14/.fzf/shell/key-bindings.bash"
```

**Comment by junegunn** [comment]
I'm as clueless as you are. You're getting different results when you run `complete -o nospace -o plusdirs -F _fzf_dir_completion cd` manually and when it's run by `completion.bash`. 😕

**Comment by ezschemi** [comment]
I have this exact same issue since a few days.

As soon as this line is executed:
```
[[ $- == *i* ]] && source "$HOME/.fzf/shell/completion.bash" 2> /dev/null
```
tab completion stops working.

On an older system with bash 3.2.25 everything is still working. 

When using putty from Windows to the Linux-system tab completion is still working.

This is the only bash plugin installed. 

Running ```complete -o nospace -o plusdirs -F _fzf_dir_completion cd``` does not change anything, tab completion is not working.


System: 
Red Hat Enterprise Linux 7.2
bash 4.2.46

**Comment by junegunn** [comment]
Hmm, I can't seem to reproduce the issue on Centos 7. I used this Dockerfile to set up the environment.

```dockerfile
FROM centos:7

RUN yum -y update
RUN yum -y install git vim
RUN git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf && \
    ~/.fzf/install --all
WORKDIR /usr/
```

**Comment by ezschemi** [comment]
I don't know what the differences between RHEL7.2 and Centos 7 (version?) are or how the Docker environment is different to a real installation.

fzf has just been uninstalled and reinstalled from scratch and the issue still exist. 

What do you suggest for debugging completion.bash ?

**Comment by ezschemi** [comment]
Here you go:
```
> complete | grep cd$
complete -o nospace -F _fzf_dir_completion cd
```
this is with latest status on the master branch. Tab completion is not working.

**Comment by junegunn** [comment]
@ezschemi Does the output of `complete | grep cd$` change when you manually execute the complete command?

```sh
complete -o dirnames -o nospace -F _fzf_dir_completion cd
```

If it doesn't, do you have any clue why it's not correctly applied to your system? Since I can't reproduce the problem locally, I need your assistance on this.

**Comment by ezschemi** [comment]
It does change:
```
> complete | grep cd$
complete -o nospace -F _fzf_dir_completion cd
02:36:38 /home/ezschemi
> complete -o dirnames -o nospace -F _fzf_dir_completion cd
02:37:19 /home/ezschemi
> complete | grep cd$
complete -o dirnames -o nospace -F _fzf_dir_completion cd
```

but tab completion still does not work.

Also note that tab completion does not work for commands like ls or cat, not just cd.

**Comment by junegunn** [comment]
Okay, so it does change when you do it manually, but it doesn't change when it's called within completion.bash script? Strange, right? Can you help debugging the issue?

**Comment by ezschemi** [comment]
Sure I can help. I have never debugged a bash script before though. What do you want me to do? 

Let me see if I can quickly create a VM with RHEL 7.2 for you with remote access. Then you can debug it. Might be more efficient...

**Comment by aceforeverd** [comment]
I got unset tab complete not working.
Tested in Gentoo & Arch

**Comment by CeleritasCelery** [comment]
I am having the same issue as @ezschemi mentioned. when I run `complete | ag cd$` I get the output
```
complete -o dirnames -o nospace -F _fzf_dir_completion cd
```
If I manually change it to `complete -o bashdefault -o default -F _fzf_dir_completion cd` that fixes it. For now that is going to be my workaround until this issue is resolved. 

System:
Suse Linux
bash 4.4.0

**Comment by enanajmain** [comment]
I'm having same problem.

I have tried with only this line
`[ -f ~/.fzf.bash ] && source ~/.fzf.bash`
My bash version is 4.3.48. 

The output of 
`complete | grep cd$` is 
`complete -o nospace -F _fzf_dir_completion cd`

**Comment by enanajmain** [comment]
@junegunn You need to look at the problem from this angle, maybe.

I found out that the problem is with tmux. When I'm outside tmux, inside neovim's terminal, tab-completion works normally. But when I'm inside tmux, it doesn't work. So, there must be something wrong with tmux.

**Comment by Falcqn** [comment]
I'm on CentOS 7.5, having the exact same issues as mentioned above.
Tab-Completion seems to be affected by screen/tmux too, as @enanajmain is experiencing.

```sh
## tab complete works
daev> screen
## now tab-complete doesn't work
daev> complete | grep cd$
complete -o nospace -F _fzf_dir_completion cd
daev> complete -o nospace -o plusdirs -F _fzf_dir_completion cd
daev> complete | grep cd$
complete -o nospace -o plusdirs -F _fzf_dir_completion cd
## now tab complete works again
```

**Comment by enanajmain** [comment]
Wow, I stopped using fzf for this issue and again installed it yesterday only to see that the bug is not fixed. What happened?

**Comment by 097115** [comment]
Just for the sake of it, just tried `complete | grep cd$` under various versions of bash (3.2.53(1)-release and 4.4.23(1)-release), under screen and under tmux (with the latest fzf). The result was always the same:

    ~> complete | grep cd$
    complete -o dirnames -o nospace -F _fzf_dir_completion cd

**Comment by junegunn** [comment]
@enanajmain 

> I stopped using fzf for this issue

That doesn't make sense to me as you can easily opt-out fuzzy completion during the installation process.

**Comment by enanajmain** [comment]
How do I opt-out fuzzy completion?

**Comment by enanajmain** [comment]
> you can easily opt-out fuzzy completion
I installed it with vim, so I didn't get the yes/no options that I got today when I installed it using git. I guess it was my bad.

**Comment by junegunn** [comment]
FYI, `install` script provides flags (see `./install --help`) for non-interactive installation.

```sh
# All but fuzzy completion
./install --all --no-completion

# Just download the binary, and nothing else
./install --bin
```

**Comment by enanajmain** [comment]
Ya, changed my `init.vim`. Thanks.

**Comment by jameshanlon** [comment]
I am experiencing this same issue running a vanilla .bashrc with only `source $HOME/.fzf.bash`.

Running on CentOS Linux release 7.5.1804 with GNU bash, version 4.2.46(2)-release (x86_64-redhat-linux-gnu). Interestingly, the issue only occurs using Gnome Terminal (3.22.1) or Xfce terminal, in Xfce-4, and not via SSH or with XTerm.

Within Gnome terminal:
```
$ complete | grep cd$
complete -o nospace -o plusdirs -F _fzf_dir_completion cd
```
And setting explicitly:
```
complete -o dirnames -o nospace -F _fzf_dir_completion cd
```
Resolves the issue.

**Comment by ryanlee** [comment]
I had same issue on bash, and finally figured out (at least in my case) it's related to the location fzf.bash get sourced, at the end of my default .bashrc, there are some stock completion like below erased fzf completion, after moving fzf bash source after this fix the issue.

.bashrc:

# source fzf.bash # was sourced here and not working!

if ! shopt -oq posix; then                                  
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion            
  elif [ -f /etc/bash_completion ]; then                    
    . /etc/bash_completion                                  
  fi                                                        
fi                            

source fzf.bash # move to here works!

**Comment by jasonsyoung** [comment]
So i figured out a fix for me, which is the opposite of the previous comment. Moving `
[ -f ~/.fzf.bash ] && source ~/.fzf.bash` to the TOP of my `.bashrc` makes tab completion work, as well as `Ctrl-R` fuzzy finding for history.

**Comment by richtong** [comment]
OK running on Mac with homebrew and I discovered that for me, it has to go to the BOTTOM of ~/.bashrc. I think this is because there are some completions that are overwriting. A quick look at the bash.completion script makes it hard to figure out what is going on here, but basically the shortcuts seem to work anywhere, but the `**` completion only works when it behind all the other completions. I have to have it after the bash completion installation. 

This probably related to me installing bash_completion and not bash_completion@2 as described by https://docs.brew.sh/Shell-Completion, but for v1 on bash 5.x this does work

```shell
source "$(brew --prefix)/ext/bash_completion"
[ -f ~/.fzf.bash ] && source ~/.fzf.bash
```

**Comment by rayiik** [comment]
Hey just a note my cd complete reads as complete -o nospace -v -F _fzf_dir_completion cd and works however you might want to try switching the trigger from ** to ^^ or ~~ i believe your shell options (shopt) are causing bash ti interpret the ** as a glob pattern and not a trigger in-fact i was able to reproduce by set -o posix
Try set +o posix and that should fix your issue if im correct posix

**Comment by richtong** [comment]
Ok what I see is that if I don’t put it after the bash completion that there is no FSD complete for cd at all. They are there for other commands like vim.

So seems like bash completion is overwriting the fzf completions for fzf

Sent via Superhuman iOS ( https://sprh.mn/?vip=rich@tongfamily.com )

**Comment by rayiik** [comment]
Hmm maybe its a separate issue i found then because the only way i could reproduce is (while working) set -o posix then it stopped working or does set spawn a new environment i had a script for a while that was on / off switch for environmental variables that broke fzf completion would unset some of the completion variables try adding an echo “$SHLVL” before and after both the fzf source and the bash complete source will help narrow down how the environment is being effected.

**Comment by junegunn** [comment]
@richtong 

> it has to go to the BOTTOM of ~/.bashrc. I think this is because there are some completions that are overwriting

That's correct. The fzf completion should be loaded at the end. The completion script of fzf is smart enough to keep the previous completion function as the fallback, but you can't expect the other scripts to do the same.

@rayiik Thanks for trying to help, but @richtong already found the right answer.

**Comment by richtong** [comment]
It probably should be documented somewhere. Or the installer script might add as a comment when it sticks it into the profile :-)

Sent via Superhuman iOS ( https://sprh.mn/?vip=rich@tongfamily.com )

**Comment by boweeb** [comment]
FWIW, @rayiik gave the clue I needed.  I was playing with various `shopt` glob settings and discovered `nullglob` will break completions.  Handy for scripts but a bad idea for interactive login shells.
