### ISSUE TITLE
Sort Input

### ISSUE THREAD

**Issue by laktak** [junegunn/fzf#873]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

Would it be possible to add an option to sort the input dynamically?

I'm using this to get all files of my notes folder sorted by modified date:

```
ag -f -la '.*' | while read file
do
  DATE=$(stat -c %y "$file" 2> /dev/null)
  echo ${DATE/%\ */} $file
done | sort -r
```

This gives me a list like:
```
2017-03-12 foo
2017-03-13 bar
2017-03-14 foobar
```

Which is fine except that because of `| sort` fzf has to wait for the process to complete before it receives any data. If it could sort the input data itself it could start displaying the results immediately.

**Comment by junegunn** [comment]
No, it's not something I would add to fzf. As you can see in `man sort`, sorting is not trivial and I don't think it's a good idea to try to reimplement the process in fzf. And as soon as you type in a query string to fzf, fzf will sort the matched items by the relevance score, so I don't see much value in having another way of sorting the input.
