### ISSUE TITLE
Question: complete command flags on bash

### ISSUE THREAD

**Issue by petobens** [junegunn/fzf#874]
I read this article about zsh: http://code.joejag.com/2014/why-zsh.html and loved the part about completing command line flags (the section titled "What was that switch?"). 
I'm using bash, and after seeing what you did with `kill` completion, was wondering if it is possible to implement command flag completion on bash using fzf. 
Feel free to close if this is not possible or you cannot provide any pointers.
Thanks in advance!!

**Comment by junegunn** [comment]
Yeah, it's possible but you would have to implement completion for each command with the complete knowledge of its flags. You may get some ideas in the following links

- https://github.com/junegunn/fzf/wiki/Examples-(completion)
- https://github.com/junegunn/fzf/issues/760
