### ISSUE TITLE
Please clarify project description. One sentence is not enough.

### ISSUE THREAD

**Issue by fidergo-stephane-gourichon** [junegunn/fzf#875]
Hello,

> :cherry_blossom: A command-line fuzzy finder written in Go 

"commande-line" is not clear enough. Screencast looks like it is a tool for vim to quickly find a file based on a part of filename. Is it only that? Is there an independent command-line interface?

"fuzzy finder" is not clear enough. What's a fuzzy finder? (Of course I can Google for that and I have, but your project deserves at least a few more words.)

How does it get its data? Where does it store it? Does it analyze file content? Text formats only? Can it index removable storage and put the information on the storage, rather than in user home dir? Is the data updated real time or only on command?

Adding this kind of information to the main README.md would sure be helpful to visitors to understand what the project is and is not.  Thanks!

**Comment by junegunn** [comment]
Thanks, I'll think about it when I get some time, and of course a pull request is welcome.
