### ISSUE TITLE
Output different delimiter than 'space' for 'execute-multi' option

### ISSUE THREAD

**Issue by eyalev** [junegunn/fzf#876]
- Category
    - [x] fzf binary
    - [x] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [x] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

This "base" scenario works fine:

I run
````
$ echo "one\ntwo\nthree\nfour" | fzf --bind "enter:execute-multi(echo {})" -m +s --tac
````

choose "two" and "three"

````

  one
 >two
 >three
> four
  4/4 (2)
>

````

hit "Enter", and I get:

````
two three
````

[All good here]

----

Is there a way to change the options so I will get output with a different delimiter than space between the chosen items?

e.g

````
two;three
```` 

or a 'newline'

````
two
three
````

Thanks!

**Comment by junegunn** [comment]
I don't think it's necessary, you can process the list in the execute command. For example,

```sh
echo $'one\ntwo\nthree\nfour' |
  fzf --bind "enter:execute-multi:python -c 'import sys; print \";\".join(sys.argv[1:])' {}" -m +s --tac2
```

If the command feels too complicated and unreadable, you should probably create an external script file.

```vim
echo $'one\ntwo\nthree\nfour' |
  fzf --bind "enter:execute-multi:~/bin/foobar.py {}" -m +s --tac
```

**Comment by jbrubake** [comment]
I do not think this is satisfactory (although it does work) because, if your entries have spaces in them, this hack is *required*. Just like normal output from `fzf` has the `--print0` option, I think it would be good if `execute-multi` had at a minimum the same capability
