### ISSUE TITLE
--height doesn't work when running in a shell within neovim

### ISSUE THREAD

**Issue by pokey** [junegunn/fzf#878]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [x] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

When running the following command

```
printf "hi\nthere" | fzf --height=30%
```

from a zsh shell within a neovim terminal buffer, nothing happens until I subsequently press any two keys in succession, at which point the fzf window shows up as normal.  This doesn't occur without `--height`, or when using `fzf-tmux`.

**Comment by justinmk** [comment]
same as https://github.com/junegunn/fzf/issues/809#issuecomment-273226434
