### ISSUE TITLE
Error on vim `:Files` invocation on remote machine

### ISSUE THREAD

**Issue by jfo** [junegunn/fzf#879]
Hi I am running into an error when trying to use fzf in tmux+vim on an ssh session on a remote linux vm.

From within vim, I get the error:

```
Error running "fzf"  -m  --prompt ./working-directory --expect=ctrl-v,ctrl-x,ctrl-t --height=31 > /tmp/vsCQUfm/16
```
I have mapped

```
nmap <C-P> :Files<CR>
nmap <leader>b :Buffers<CR>
```

In my vimrc, which might be pertinent, but it works locally (OSX) and I get the same error running `:Files` directly. Happens in and outside of tmux.

Please lmk if you have any advice here, happy to look into this myself if you can point me to a place to start or an existing issue.

Love the program it's really improved my workflow dramatically working within a large tree. Thanks!

- Category
    - [x] fzf binary
    - [x] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [x] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

**Comment by junegunn** [comment]
Make sure that the command shown in the error message works correctly on your shell. I mean this one:

```sh
 "fzf"  -m  --prompt ./working-directory --expect=ctrl-v,ctrl-x,ctrl-t --height=31
```

**Comment by jfo** [comment]
aha

```
[~]> fzf  -m  --prompt ./working-directory --expect=ctrl-v,ctrl-x,ctrl-t --height=31
unknown option: --height=31
```

**Comment by jfo** [comment]
You know what, 

I have an outdated binary on my vm.

Updating that fixed it, thanks! I just overlooked it when updating the plugin.

**Comment by junegunn** [comment]
Yeah, so it's probably a good idea to run the install script whenever the repo is updated.

```vim
Plug 'junegunn/fzf', { 'do': './install --bin' }
```
