### ISSUE TITLE
ctrl+r history results should be unique by command

### ISSUE THREAD

**Issue by bnovc** [junegunn/fzf#88]
I normally have used ctrl+r and hit it a few times to get the right command pre-fzf, which worked fine, and now with fzf, I can use my arrow keys to scroll the results, but I have _many_ more to scroll than before. I don't see any value in presenting numerous duplicate results here, and zsh's default ctrl+r behavior doesn't do this.

**Comment by cbrwizard** [comment]
@junegunn could you please provide an example on how to enable this option in `fish`? It doesn't have `setopt`

**Comment by vpshastry** [comment]
I want my history file to contain the duplicates, because I want to see my history. But I don't want them showing up in multiple entries when I search them through fzf. Can't we do that?

**Comment by junegunn** [comment]
It's not simple as it sounds so it's not supported. If you know some shell scripting, you should be able to implement your own version of the binding.
