### ISSUE TITLE
fzf does not allow input to be a named pipe

### ISSUE THREAD

**Issue by hkupty** [junegunn/fzf#880]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

I'm trying to asynchronously feed data into fzf via a named pipe.

However, it drills down to two options which don't fully work:

`tail -f /tmp/my_fifo | fzf` - This works, allowing me to incrementally input data into the fifo that appear on fzf, but after choosing the result, I must force close the `tail` command, which makes this method inviable for use within vim.
`fzf < /tmp/my_fifo` - This reads the first occurrence of data and immediately closes the fd.

Are there other options for reading data from a named pipe?

**Comment by junegunn** [comment]
```sh
(tail -f foo & echo $! > pid) | fzf; kill -9 $(<pid)
```

Makes sense?

**Comment by hkupty** [comment]
Works!

Cheers
