### ISSUE TITLE
FZF issue in tmux

### ISSUE THREAD

**Issue by deepredsky** [junegunn/fzf#881]
- Category
    - [x] fzf binary
    - [x] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [x] bash
    - [x] zsh
    - [x] fish

The first item in the result is prefixed by some weird characters 

```
?Ptmux;??]1337;CursorShape=0??\
```

![](https://www.dropbox.com/s/bn1dzowj9bnx0m1/Screenshot%202017-03-22%2020.36.05.png?dl=1)

fzf version 0.16.6
tmux 2.3

This only happens in tmux. I have tried both `fzf` and `fzf-tmux` commands

**Comment by junegunn** [comment]
I'm not familiar with that `CursorShape=0`. Is it from your configuration?
Also, what is the value of `$TERM`? Does it start with `screen-`?

**Comment by deepredsky** [comment]
Dunno where the CursorShape is coming from. i also tried with clean install of tmux with no custom config but got same result

```
echo $TERM
screen-256color
```

**Comment by junegunn** [comment]
This looks related: https://www.iterm2.com/documentation-escape-codes.html

**Comment by deepredsky** [comment]
I looked into this issue a bit more and i m convinced this is not related to fzf but its due to iTerm setting up CursorShape when starting the tmux server. If I start a clean tmux session from another emulator like terminal or alacrity the issue does not appear (which i can use as as workaround as well). The escape codes link is probably a clue to fix it but not something i was able to do. Thank for looking into this issue though.

**Comment by junegunn** [comment]
I use iterm2 but I don't have the issue. Please let me know if you find out more about the issue, thanks.

**Comment by blaxill** [comment]
I had this issue when using the fish shell, and it could be an issue with how the fish shell [sets the cursor shape](https://github.com/fish-shell/fish-shell/blob/d73ff39393a35e8aaf7c04e57fe8013cdd115b2c/share/functions/__fish_cursor_1337.fish#L3) [for different vi modes](https://github.com/fish-shell/fish-shell/blob/f17ddb6770626892217d2a3a7cf494e5bcbbd720/share/functions/fish_vi_cursor.fish#L1). As a workaround, you can disable different cursor displays for different vi modes in the fish shell by adding the following to your `~/.config/fish/config.fish` file:

```fish
function fish_vi_cursor; end
```

**Comment by kozie** [comment]
I'm having [similar](https://github.com/junegunn/fzf.vim/issues/400) [issues](https://github.com/neovim/neovim/issues/7067) where i can not seem to use `:GFiles` in a tmux environment using fish shell.

I tried the above but adding the `fish_vi_cursor` function doesn't seem to do anything and adding `__fish_cursor_1337` breaks my tmux by not starting a shell anymore within tmux. I tried adding them both and individually.

**Comment by deanashton** [comment]
@kozie placing it before `fish_vi_key_bindings` in `~/.config/fish/config.fish` fixed it for me:

```
function fish_vi_cursor; end
fish_vi_key_bindings
```

**Comment by kozie** [comment]
Holy nuts.. I did that while also setting the tmux term back to screen-256color and it seems to work! :) Thanks a bunch!

**Comment by deepredsky** [comment]
perfect! placing it before invoking the vi bindings in fish config fixed it for me as well. Thanks @blaxill  and @deanashton

**Comment by 1ak31sha** [comment]
thank you @deanashton ! i had same issue but when using prettier in nvim.
