### ISSUE TITLE
Slow start up when using fzf --height on alacritty

### ISSUE THREAD

**Issue by wooken** [junegunn/fzf#884]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

When using fzf with --height option, fzf is slow to start up. This issue is not occurring with termite.

alacritty config: default
fzf version: 0.16.6

It takes a noticeable ~1 second for fzf --height 40% to start up.

**Comment by junegunn** [comment]
Hmm, my guess is that the terminal emulator is not reporting the cursor position promptly. Do you see immediate result when you do `echo -e '\x1b[6n'`?

(reference: https://en.wikipedia.org/wiki/ANSI_escape_code#CSI_codes)

**Comment by wooken** [comment]
```
 ~ ❯❯❯ echo -e '\x1b[6n'
 ~ ❯❯❯ git log -1 fcb1d93326c25048c3a639502b3440e905e310f3
bck-i-search: 6c_
```

The sequence activates reverse-i-search for some reason. Is this expected?

**Comment by junegunn** [comment]
No, that's strange. Can you post the output of `bindkey`? And please check if you have the same issue on bash.

**Comment by wooken** [comment]
Here is the output for bindkey:
```
"^A"-"^C" self-insert
"^D" list-choices
"^E"-"^F" self-insert
"^G" list-expand
"^H" vi-backward-delete-char
"^I" fzf-completion
"^J" accept-line
"^K" self-insert
"^L" clear-screen
"^M" accept-line
"^N"-"^P" self-insert
"^Q" push-line-or-edit
"^R" fzf-history-widget
"^S" self-insert
"^T" fzf-file-widget
"^U" vi-kill-line
"^V" vi-quoted-insert
"^W" vi-backward-kill-word
"^X^R" _read_comp
"^X^S" prepend-sudo
"^X?" _complete_debug
"^XC" _correct_filename
"^Xa" _expand_alias
"^Xc" _correct_word
"^Xd" _list_expansions
"^Xe" _expand_word
"^Xh" _complete_help
"^Xm" _most_recent_file
"^Xn" _next_tags
"^Xt" _complete_tag
"^X~" _bash_list-choices
"^Y"-"^Z" self-insert
"^[" vi-cmd-mode
"^[," _history-complete-newer
"^[/" _history-complete-older
"^[E" expand-cmd-path
"^[M" copy-prev-shell-word
"^[OA" up-line-or-history
"^[OB" down-line-or-history
"^[OC" forward-char
"^[OD" backward-char
"^[OF" end-of-line
"^[OH" beginning-of-line
"^[Q" push-line-or-edit
"^[[200~" bracketed-paste
"^[[2~" overwrite-mode
"^[[3~" delete-char
"^[[A" up-line-or-history
"^[[B" down-line-or-history
"^[[C" vi-forward-char
"^[[D" vi-backward-char
"^[[Z" reverse-menu-complete
"^[c" fzf-cd-widget
"^[e" expand-cmd-path
"^[m" copy-prev-shell-word
"^[q" push-line-or-edit
"^[~" _bash_complete-word
"^\\\\"-"^_" self-insert
" " magic-space
"!"-"~" self-insert
"^?" backward-delete-char
"\M-^@"-"\M-^?" self-insert
```

I tried using bash and I am still getting the same ~1 second load time when compared to zsh/bash in termite.
I removed my zprezto config and had zshrc with only the single line that fzf requires to run. It didn't seem to help.

**Comment by junegunn** [comment]
I see, thanks for the information. I'll have to try alacritty myself.

**Comment by deepredsky** [comment]
I have also experienced the same slow startup on Alacrity when using the height option. Im using fish shell. doesnt happen if i drop into a tmux session though.

**Comment by wooken** [comment]
thanks @deepredsky, I can also confirm that I do not see this issue when in tmux.

**Comment by wooken** [comment]
This seems to be inadvertently fixed on the alacritty side by the patch mentioned in the following issue:

https://github.com/jwilm/alacritty/issues/497

**Comment by junegunn** [comment]
Thanks for the update.
