### ISSUE TITLE
by_filename option

### ISSUE THREAD

**Issue by mqnfred** [junegunn/fzf#886]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [x] Vim
    - [x] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

Hey,

I am looking for whether or not fzf has a similar option to the one in CtrlP named "by_filename". When activated, this options allows the user to first type the filename (the most instantaneous thing that comes to mind,) and if that is not enough, type a `;` and type things relevant to the path (the second thing that comes to mind, the seggregating factor between multiple filenames.)

Is that already present in fzf? If not, is this something that could be considered? This option feels very instinctive to me and I am surprised I did not find anything on the matter before. Maybe I used the wrong search terms?

Cheers!

**Comment by junegunn** [comment]
First note that fzf is a general-purpose text filter and does not know if the input is a list of file paths, so there's no specialized handling for specific type of input.

There are several approaches I can suggest
1. `fzf --tiebreak=end`
    fzf prioritizes matches that are close to the end, so it's likely that you'll see matches in file names are ranked higher.
2. `fzf --delimiter / --nth -1,..`
    These options tell fzf to first search within the last token (`-1`) separated by delimiter `/`, which should be the file name, and if no match is found, search the whole line (`..`)
3. If you know the extension of the file you can use the information to greatly narrow down the result, e.g. `.md$ readme`.
