### ISSUE TITLE
Add --index/--print-index scripting options

### ISSUE THREAD

**Issue by nkgm** [junegunn/fzf#887]
- Category
    - [ ] fzf binary

In similar fashion to `--query`, use `--index` to specify which line to initially place the cursor on (after `--query` has been applied if provided). This, together with `--sync` will be especially useful in implementations such as `:BLines` as you could start the cursor on the line you're on. It would also enable resuming fuzzy sessions (the user could cache the lines in a temp file when it makes sense to do so - very useful for resuming `:Ag` searches where you left them).

**Comment by junegunn** [comment]
There have been similar requests in the past. The most recent one was #883 which is a superset of the feature suggested here.

If you think about it, it's actually not trivial.

> especially useful in implementations such as :BLines as you could start the cursor on the line you're on

Let's say we're on line 100, and the new `:BLines` implementation starts fzf with cursor on line 100. If the height of the terminal is shorter than 100 lines, line 100 is not on the first page and fzf will have to start with positive scroll offset. And as soon as we type in a query string, fzf will sort the matching lines according to its own ranking algorithm. And if there are more than 100 matching lines, fzf is now pointing to the 100th match, which is probably not the one we're looking for. Also, fzf currently doesn't have scroll indicator, so we may not even notice that we're looking at a low-rank match on page 3 or 4, and it can be quite confusing.

And if we're not going to type in a query, there's really no point of running `:BLines` in the first place.

The options make more sense with the case of `:Ag`, and I agree that the current workflow of selecting multiple matches to build quickfix list of Vim is not ideal.

However, even if we have those options, the underlying ag command will start searching from the scratch again, and fzf will have to block user input until there are N matches available. The experience will not be ideal. And we would need more information such as scroll offset, cursor position on the query prompt, etc, to make the new fzf process look exactly the same as the previous process. The idea naturally develops to the state dump/load option suggested in #883, which is going to be much more complex implementation-wise.

I think we can do better by taking a whole different approach. That is, setting up `execute` / `execute-silent` bindings and `preview` command to send messages to Vim or Neovim using their RPC mechanisms (`+clientserver` and `msgpack_rpc`), without closing fzf. fzf can stay in a tmux pane, or in a hidden terminal buffer if we're using Neovim.

As far as I know, no one has attempted to implement the idea with Vim, but someone actually implemented a similar one with Kakoune, and it looks quite promising.

https://vimeo.com/200792397

I'm going to close this, but thanks for the suggestion. I'll let you know if there's any progress.

**Comment by nkgm** [comment]
I'm definitely looking into `execute-silent`. Using `preview` already and it has been a lifesaver - problem starts when you realize you just selected the wrong result, so you have to start over.

I'll give it some more thought, but just to be sure we're on the same page, let me clarify my initial suggestion.

I'm basically looking for a way to hit the `<Up>` or `<Down>` key **n times** IFF the following conditions are met:
* `--sync` has been provided and input stream is complete
* `--query` has been fully applied
* `+s, --no-sort` has been fully applied - can't get any more deterministic than that!

It is up to the end user to make sane use of the above in order to arrive at the desired result, provided they undestand what's possible and what's not. If `--index` is not a proper name and you need to name it `--simulate-key=<Up> --simulate-n-times=10` or similar, so be it. But it would be best to abstract away `--reverse`.

Yet another way to put it is would be: how can I map something like `:BLines<CR><Down><Down><Down>...`?

Hope that makes sense - and thanks for your great work 😄

**Comment by nkgm** [comment]
An even better candidate for initial cursor placement would be `:BTags`.

**Comment by junegunn** [comment]
It will have the same issue of non-zero scroll offset I described above. A better, and much simpler, approach would be to reorganize the input (e.g. if you're on line 100, print line 100 to end of the file, then line 1 ~ line 99) and set `--cycle` option so you can easily go to the other end of the list by a single keystroke.

**Comment by junegunn** [comment]
By the way, we already support `execute-silent` action and `--preview-window` with size 0 (invisible, only used to fire some commands on every cursor movement). See `man fzf` for the details.
