### ISSUE TITLE
fzf has no version option

### ISSUE THREAD

**Issue by ezh** [junegunn/fzf#888]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [ ] fish

`--no-clear` wad added 24 days ago but I couldn't verify fzf local version

```bash
fzf -v
unknown option: -v
```

```bash
fzf -h 2>&1 | grep ver
    --tac                 Reverse the order of the input
    --reverse             Reverse orientation
    FZF_DEFAULT_OPTS      Default options (e.g. '--reverse --inline-info')
```

Please mark builds with commit sha1 value at least or something more verbose.

**Comment by junegunn** [comment]
We have `fzf --version` which is used in [install script](https://github.com/junegunn/fzf/blob/master/install#L75).

> Please mark builds with commit sha1 value at least or something more verbose.

Thanks for the suggestion. I'll think about this. We'll have to be careful though since fzf has been around for more than 3 years and changing the format might break some user scripts.

**Comment by ezh** [comment]
```
fzf --help 2>&1 | grep version
    --tac                 Reverse the order of the input
    --reverse             Reverse orientation
    FZF_DEFAULT_OPTS      Default options (e.g. '--reverse --inline-info')
```

There is no version key, but it works

**Comment by ezh** [comment]
fzf --version
0.16.6

--version is option for advanced users? It is very distracting for me :disappointed:

**Comment by junegunn** [comment]
> --version is an option for advanced users?

No, it's not. I just haven't felt that I needed to list it on `--help` output as it seemed too obvious to me. `bash --version`, `zsh --version`, `grep --version`, `awk --version`, `ruby --version`, `python --version`, `perl --version`, the list goes on. Not saying that I won't add it to `--help` in the next version.

> I work under macos and fzf installed as vim plugin.

Me too.

> I suspect that there are more that one man fzf

You can easily fix that. Do you use Homebrew?

**Comment by ezh** [comment]
If you feel that it is ok then it is ok. I just report. Thank you.

Actually I use huge amount of OSes but my workplace is under mac os. That is why I near always read builtin help. It is a point of my distraction. There are too many dialects of same tools.

**Comment by junegunn** [comment]
Yeah, I see, thanks. By the way, I don't know how you installed fzf, but if you installed fzf using Homebrew, you can just add `set rtp+=/usr/local/opt/fzf` to your vimrc, instead of installing it again using a plugin manager.
