### ISSUE TITLE
There is no --no-clear option within buitin help

### ISSUE THREAD

**Issue by ezh** [junegunn/fzf#889]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [ ] fish

```bash
❯ echo | fzf --no-clear -f 1
```
There is on error and it is work.

```bash
❯ fzf -h 2>&1 | grep clear
```

is empty

**Comment by junegunn** [comment]
Some advanced, niche options are intentionally not shown in `--help` not to distract ordinary users. You can find the full list of options and more detailed descriptions in `man fzf`. Please let me know if you find it lacking. Thanks.
