### ISSUE TITLE
cannot find tag in ctags file? 

### ISSUE THREAD

**Issue by jinleileiking** [junegunn/fzf#892]
- Category
    - [x ] fzf binary
    - [x ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ x] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x ] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x ] zsh
    - [ ] fish

cannot find tag? 

ctrlp can locate the tag in ctags file. can fzf do this?

**Comment by junegunn** [comment]
👉  https://github.com/junegunn/fzf.vim
