### ISSUE TITLE
doc cannot generated using  vundle

### ISSUE THREAD

**Issue by jinleileiking** [junegunn/fzf#893]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [x] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [ ] fish

`:he FZF` fail

**Comment by junegunn** [comment]
Added vim doc file to the repo.
