### ISSUE TITLE
fzf does not respect --hidden flag in Ag and ripgrep 

### ISSUE THREAD

**Issue by zigius** [junegunn/fzf#897]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [x] Vim
    - [x] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

Hi, I cant get fzf to index my hidden files. 
I have tried many default commands but none of them work. 

Among the options i tried: 
`export FZF_DEFAULT_COMMAND='ag --hidden --ignore .git -g ""'`
`export FZF_DEFAULT_COMMAND='rg --files  --hidden --follow --glob "!.git/*"'`

fzf version: 0.16.6
ag version: 1.0.2
ripgrep version: 0.5.0

Installed fzf using vim plug. Hidden files are not displayed not in the terminal and not in vim.

By the way, when using fzf like this: 

`fzf **<TAB>` 
hidden files are shown.

Thanks!

**Comment by zigius** [comment]
My bad, not relevant :)

**Comment by rileyrg** [comment]
Can you comment on what was not relevant? I'm having the same issue. updated default command to include --hidden:

     export FZF_DEFAULT_COMMAND='ag --hidden --ignore .git -g ""'

and its not picking up dot files.

**Comment by zigius** [comment]
@rileyrg im using fzf with the following command to include files from .gitignore in search results: 
```sh
export FZF_DEFAULT_COMMAND='rg --files --no-ignore-vcs --hidden'
```
It ignores files from `.ignore` files but not from `.gitignore`
Im guessing there is a similar option in Ag.
