### ISSUE TITLE
fe alias issue

### ISSUE THREAD

**Issue by partounian** [junegunn/fzf#898]
- Category
    - [ ] fzf binary
    - [x] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [x] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

When I use this snippet in tmux, if there is only one option and it automatically opens vim/neovim with the size of half a pane, if there is multiple and I need to select my file it works fine.
```
fe() {
  local files
  IFS=$'\n' files=($(fzf-tmux --query="$1" --multi --select-1 --exit-0))
  [[ -n "$files" ]] && ${EDITOR:-vim} "${files[@]}"
}
```

**Comment by junegunn** [comment]
I can't reproduce the problem on my machine. I guess it's an issue of your tmux installation or configuration. You might want to consider using `--height` option instead of `fzf-tmux` if you have issues with it. e.g. `fzf --height 40%`.
