### ISSUE TITLE
mac/osx cd autocomplete does not work

### ISSUE THREAD

**Issue by sathishvj** [junegunn/fzf#899]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [x] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

I have a couple of macs. I'm able to install and run fzf on it.  However 'cd **' form of autocomplete just does not work on either.  On another linux box though, it does work.  Meanwhile other commands like ```alias vimf='vim $(fzf)'``` also works on the mac.  

Any reason why the cd autocomplete does not work?

**Comment by junegunn** [comment]
I'm a mac user myself, and it works as expected.

Try something like the follows to see if it's a configuration issue.

```sh
bash --rcfile ~/.fzf/shell/completion.bash
```

**Comment by sathishvj** [comment]
it works now.  why is this not part of the documentation?

**Comment by junegunn** [comment]
Thanks. May I ask what was the problem?

**Comment by sathishvj** [comment]
I do not know honestly.  I ran that command and it was ok. 
was the install script supposed to have run it?  I answered yes for the completion question.

Does it need to be run in sudo mode?

**Comment by junegunn** [comment]
No, maybe you didn't reload your shell configuration file after the installation?

**Comment by sathishvj** [comment]
so this line needs to be added in a .bashrc/.profile?

**Comment by junegunn** [comment]
What do you mean by "this line"? You mean `bash --rcfile ~/.fzf/shell/completion.bash`? Then no, it's not something you use regularly. I suggested the command to help you debug your configuration issue, as it isolates all other shell configuration.

**Comment by sathishvj** [comment]
In that case, adding that line to my .profile on macos/osx is what is making it work well for me.

**Comment by junegunn** [comment]
My guess is that you're not loading your ~/.bashrc from your .profile or .bash_profile?
If that's the case, consider adding `. ~/.bashrc` to your ~/.bash_profile or ~/.profile.

Also take a look at #282.

**Comment by sathishvj** [comment]
You are correct.  I wasn't using a .bashrc.  I've sourced it now and it works fine.  Thank you, and also apologies if I wasted your time.

**Comment by junegunn** [comment]
No problem, thanks for clarification.

- junegunn

**Comment by singhai0** [comment]
Thanks @junegunn
