### ISSUE TITLE
Reverse search (`-n` option) slow

### ISSUE THREAD

**Issue by ericboehs** [junegunn/fzf#90]
When reverse searching in zsh (and probably bash) with a large history (40k+), fzf is quite sluggish. I narrowed this slowness down to the `-n` option. I started to go through the code to see if I could fix it but I gave up after I couldn't get a pry debugger session going.

Anyways, I don't care to address commands by number (as typing a 5 digit number isn't very efficient) so I made fzf's reverse search faster by remove the `-n` call. I didn't make a PR for this as I know you really like addressing commands by number but I thought it'd be good to open an issue to address/document this sluggishness.

Here's my solution to the problem: https://github.com/ericboehs/dotfiles/commit/5f6510 (`-e` being another of my preferences as long `curl` calls commonly come up first rather than the much shorter command I'm usually looking for). It strips out the number column from `fc -l 1` alleviating the need to use `-n`.

I know 40k may seem like a large list but this is the result of programming on the same machine every day for 10+ months. I also don't dedup my history so I can perform statistical analysis on which commands I run most often. I'm also adding `| awk ' !x[$0]++'` to my [fzf config](https://github.com/ericboehs/dotfiles/commit/abed0592) to make the list unique without sorting it.

**Comment by junegunn** [comment]
Closing as fzf has become significantly faster now.
