### ISSUE TITLE
CTRL-T keybinding hangs

### ISSUE THREAD

**Issue by paymog** [junegunn/fzf#900]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [x] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [x] bash
    - [x] zsh
    - [ ] fish

I've been using fzf flawlessly for months now but suddenly the CTRL-T hangs or doesn't work at all.
Prior to this issue happening, the list brought up by CTRL-T would start populating immediately but now it seems like I need to wait for the underlying `find` command to finish. For some reason I think that fzf isn't working asynchronously anymore. 
![image](https://cloud.githubusercontent.com/assets/1986950/24680440/d023205e-1945-11e7-9a1b-f168270e41e7.png)

However, if I run `fzf` directly, use `**<tab>` or run it through vim, it works exactly as expected. The file list starts populating immediately.

I've tried updating fzf with `cd ~/.fzf && git pull && ./install` but that didn't help. 

I have a custom default command: `export FZF_DEFAULT_COMMAND="find -L * -path '*/\.*' -prune -o -type f -print -o -type l -print 2> /dev/null"`. I tried commenting that out of my `.zshrc` but it didn't help which I expected because fzf works without using the keybinding.

This problem exists when I run the keybinding in bash too.

Does fzf store logs somewhere that I can inspect to hopefully debug what's going on?

**Comment by junegunn** [comment]
No, you'll have to "echo-debug" the problem. I haven't made any change that might have affected the behavior of the key binding, so it must be a configuration issue, and there's not much I can help you with that.

By the way CTRL-T does not use `FZF_DEFAULT_COMMAND`, but `FZF_CTRL_T_COMMAND`.

Try this and see if you can still reproduce the problem:

```sh
FZF_CTRL_T_COMMAND= bash --rcfile ~/.fzf/shell/key-bindings.bash
```

**Comment by paymog** [comment]
Hmm, it seems to have fixed itself and I have no idea why. Closing the issue.
