### ISSUE TITLE
`fz` does not change directory in `tmux` `zsh` when directory path contains trailing slash (`/`)

### ISSUE THREAD

**Issue by czchen** [junegunn/fzf#901]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

fzf version is `0.16.6`
It is in tmux environment, and `TERM` is `screen-256color`.

When there is a trailing slash (`/`) at the end of directory path, `fz` command will not change directory.

For example, I want to change to `/home/czchen/Downloads` directory with `fz`. The first directory path si `/home/czchen/Downloads/` which contains the trailing `/` and it is the one auto completed by tab. `fz` will not change directory to the path. However, if I remove the trailing `/`, `fz` will change directory to the path.

```zsh
# czchen @ sune in ~ 
$ fz /home/czchen/Downloads/

# czchen @ sune in ~
$ fz /home/czchen/Downloads 

# czchen @ sune in ~/Downloads
$
```

**Comment by junegunn** [comment]
You should report this to the issue tracker of fz, not here.
