### ISSUE TITLE
Weird error after update...

### ISSUE THREAD

**Issue by staycreativedesign** [junegunn/fzf#902]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [x ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [ x] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ x] bash
    - [ ] zsh
    - [ ] fish

 

For some reason after I ran the most recent updat it gave me this error ...

Error running /bin/bash "/var/folders/tf/hvd8kvvs13l5b7r74mh0zrr80000gn/T/vkMZrI
H/2"|"fzf"  --multi  --prompt '~/'  --expect=ctrl-v,ctrl-x,ctrl-t --height=9 > /
var/folders/tf/hvd8kvvs13l5b7r74mh0zrr80000gn/T/vkMZrIH/1

**Comment by junegunn** [comment]
You should upgrade fzf binary as well. After upgrade, check if this commands works on your shell `"fzf" --multi --prompt '~/' --expect=ctrl-v,ctrl-x,ctrl-t --height=9`.

**Comment by kennykaye** [comment]
@junegunn I am experiencing something similar to this. The issue was that I had a different fzf binary installed via home brew. Running the fzf `./install` script did not update that binary. After removing the conflicting version the error about the unknown `--height` option was fixed.

**Comment by junegunn** [comment]
👉  https://github.com/junegunn/fzf#upgrading-fzf

**Comment by staycreativedesign** [comment]
I removed fzf from vim .... And magically it is working in vim :)
