### ISSUE TITLE
adds double backslash on mac folders with space in name

### ISSUE THREAD

**Issue by sathishvj** [junegunn/fzf#903]
- Category
    - [x] fzf binary
- OS
    - [x] Mac OS X
- Shell
    - [x] bash

fzf doesn't seem to work well with folders on osx that have a space in them.  It seems to add double backslash. 
```
cd Application\\\ Support/Storj\\\ Share/Local\\\ Storage/
-bash: cd: Application\ Support/Storj\ Share/Local\ Storage/: No such file or directory
```

**Comment by junegunn** [comment]
I can't reproduce the problem. Please provide exact steps to reproduce the issue.

**Comment by junegunn** [comment]
Ah okay, I thought you were using CTRL-T, which doesn't have the issue.

Seems like it's caused by `-o plusdirs` option, let me look into it.

```sh
complete -o nospace -o plusdirs -F _fzf_dir_completion cd

complete -o nospace -F _fzf_dir_completion cd
```

**Comment by junegunn** [comment]
Fixed it. It was obviously a mistake to apply `plusdirs`. Thanks for the report.

**Comment by sathishvj** [comment]
dude. you rock.  thank you.
