### ISSUE TITLE
Installation with ZSH, segmentation fault ERROR

### ISSUE THREAD

**Issue by poupougnac** [junegunn/fzf#904]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

Hello, I have this error : 

[1]    13246 segmentation fault (core dumped)  zsh -xv

What I do : 
I install normally fzf without completion nor key bindings.
I start zsh -xv (to have a debug trace)
I run source ~/.zshrc
I press CTRL+R
And the segmentation fault occurs.

I use the last version of fzf (0.16.6).

**Comment by junegunn** [comment]
It looks like an issue of your zsh installation, not fzf.

**Comment by poupougnac** [comment]
Ok, I'll check but it's not going to be easy to investigate as only the integration with fzf causes the crash. Thank you for your fast answer :zap:

**Comment by junegunn** [comment]
You can simply check if `fc -l 1 | fzf --tac` works.

**Comment by poupougnac** [comment]
It works, and I realize that my zsh doesn't support CTRL+R after source .zshrc even without fzf. So, you've right and something is not clear by my side. As fzf change the behavior or CTRL+R, it was tricky :penguin:. Thank you :rocket:
