### ISSUE TITLE
fzf wont stop searching

### ISSUE THREAD

**Issue by NiklasGoegge** [junegunn/fzf#905]
- Category
    - [x ] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [x ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ x] zsh
    - [ ] fish

 The search is not stoping. I tried installing over brew and git but issue still exists.
Any ideas?
<img width="157" alt="screen shot 2017-04-16 at 2 38 33 pm" src="https://cloud.githubusercontent.com/assets/8077169/25071246/81e11ad8-22b2-11e7-82b1-d66a9acaede5.png">

**Comment by junegunn** [comment]
What are you searching for? Please provide the steps to reproduce the issue.

**Comment by NiklasGoegge** [comment]
I was not searching for anything this happened when ever i started fzf from my home directory. When i executed fzf from my home/Desktop it worked just fine. The directory which is causing the trouble is located in home/Library/Containers which contains this:
<img width="713" alt="screen shot 2017-04-16 at 6 27 52 pm" src="https://cloud.githubusercontent.com/assets/8077169/25072598/d64ad9a4-22d2-11e7-8c1f-45d890b18670.png">
in each of these com.apple. directories their is a Data directory which contains references to my some of my directories in home. 
Example for com.apple.weather/Data:
<img width="590" alt="screen shot 2017-04-16 at 6 35 56 pm" src="https://cloud.githubusercontent.com/assets/8077169/25072619/9edd7fd4-22d3-11e7-85f3-b5d72b33d585.png">

Somehow fzf is not ignoring these in pink marked References and so it works its way through them over and over again resulting in this seemingly endless search.

Is there a way to tell fzf to ignore these References?

**Comment by junegunn** [comment]
It looks like the default `find` command is not correctly detecting circular symlinks:

https://github.com/junegunn/fzf/blob/master/src/constants_unix.go#L7

What you can do is to set `FZF_DEFAULT_COMMAND` so that it does not follow symlinks or uses a different program to recursively list files (see https://github.com/junegunn/fzf#tips).

**Comment by NiklasGoegge** [comment]
Replacing find with ag worked. Thanks!
