### ISSUE TITLE
unicode prompt disappears on input

### ISSUE THREAD

**Issue by sodiumjoe** [junegunn/fzf#907]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

```bash
fzf --version
0.16.6
```

works normally:
```
echo "foo\nbar\nbaz" | fzf --prompt="->"

  baz
  bar
> foo
  3/3
->
```

```
> foo
  1/3
->foo
```

broken:

```
  baz
  bar
> foo
  3/3
❯
```
(prompt has disappeared)
```
> foo
  1/3
 foo
```
![2017-04-27 at 10 58 am](https://cloud.githubusercontent.com/assets/845857/25497182/900e1a64-2b38-11e7-8e52-59b6327ffdce.gif)

**Comment by junegunn** [comment]
Works for me.

<img width="430" alt="screen shot 2017-04-28 at 5 04 49 pm" src="https://cloud.githubusercontent.com/assets/700826/25519926/d5394e9a-2c34-11e7-9c3d-0f5fb2031cb4.png">

**Comment by sodiumjoe** [comment]
I think I've narrowed it down to tmux 2.4.

**Comment by edi9999** [comment]
Possible, I also updated to tmux 2.4 and can reproduce the issue (but I haven't tested with prior versions)

**Comment by junegunn** [comment]
Yeah, I can reproduce the issue with tmux 2.4 as well. And it looks like there's not much I can do about it.

**Comment by sodiumjoe** [comment]
Any idea what the issue is? Should I open a bug on tmux?

**Comment by junegunn** [comment]
This definitely looks like a tmux issue, because if I enter copy-mode of tmux when that happens, the prompt string suddenly appears. I couldn't find steps to reproduce the problem without fzf though.

**Comment by sodiumjoe** [comment]
I just build tmux from master and can't repro this bug so I'll close this. thanks!
