### ISSUE TITLE
Use mattn's go-isatty, go-runewidth and go-shellwords

### ISSUE THREAD

**Issue by tomfitzhenry** [junegunn/fzf#908]
- Category
    - [x] fzf binary
- OS
    - [x] Linux

I'm a big fan of fzf, and so am currently packaging fzf for Debian: https://github.com/tomfitzhenry/pkg-fzf

It's working, but there's a slight issue.

fzf depends on:
* https://github.com/junegunn/go-isatty
* https://github.com/junegunn/go-runewidth
* https://github.com/junegunn/go-shellwords

This isn't necessarily a problem, but I noticed that:
* each of those libraries is a fork: [go-isatty](https://github.com/mattn/go-isatty), [go-runewidth](https://github.com/junegunn/go-runewidth), [go-shellwords](https://github.com/junegunn/go-shellwords)
* your forks seem to have no commits that aren't in upstream
* upstream has commits that aren't in your forks
* Debian has already packaged the three upstreams: [golang-github-mattn-go-isatty-dev](https://packages.debian.org/sid/golang-github-mattn-go-isatty-dev), [https://packages.debian.org/sid/golang-github-mattn-go-runewidth-dev](https://packages.debian.org/sid/golang-github-mattn-go-runewidth-dev), [https://packages.debian.org/sid/golang-github-mattn-go-shellwords-dev](https://packages.debian.org/sid/golang-github-mattn-go-shellwords-dev)

Consequently does it make more sense to have fzf depend on mattn's libraries?

**Comment by junegunn** [comment]
I just wanted to secure the correctness of the build by using my own forks. When I started rewriting fzf in Go, there was no good way to manage the dependencies and that was my choice. Theoretically, upstream repositories can make breaking changes at any time that might affect the behaviour of fzf and they can even be deleted from GitHub by their authors. By using my own forks, I can be always be sure that fzf is unaffected by such events.

I know that those events are probably not going to happen, and now I use a script (https://github.com/junegunn/fzf/blob/master/src/deps) for checking out the exact revisions, but with forks, simple `go get` build will always be reproducible.

**Comment by tomfitzhenry** [comment]
Thanks for the prompt response.

I can see the benefits to depending only on your code, especially if  upstream starts making breaking changes.

But there are ways to depend on upstream, and maintain reproducible builds. Godep allows you to depend on a particular revision of a dependency, which handles the breaking change issue you mentioned. See [pgweb's Godeps.json](https://github.com/sosedoff/pgweb/blob/6289e479a58af8accbc7e6d231febeee38f71729/Godeps/Godeps.json) as an example.

Advantages of using mattn's packages rather than your forks:
* Contributors to isatty/runewidth/shellwords will only have one 
* Distributions only have to package on version of isatty (if every app forked all their dependencies, that'd be a lot of packaging!)

Advantages of using Godep rather than your forks+scripts:
* Contributors will be more familiar dependency management
* Easier for packagers
* Ability to version golang.com/x/crypto, without having to fork that
* Option to use dynamic linking, thus allowing for easier security updates

Advantages of having this packaged in Debian and Ubuntu:
* Exposure to more users. More users = more bugs! Err, I mean... more users = woo!
* Better experience for Debian/Ubuntu users, and more likely for fzf to make its way onto production boxes. There's already been a few people interested in fzf being on Debian over the years. https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=783307
* Benefit from Debian's infrastructure on [Reproducible Builds](https://reproducible-builds.org/) (_binary-bit-for-bit_ reproducible, rather than _buildable-from-source_ reproducible)

What are your thoughts on these?

Are you open to a PR switching to godeps?

**Comment by junegunn** [comment]
I would choose a proper dependency tool if I'm going to start developing fzf today so I'm open to pull requests (make sure to base it on devel branch). FYI, I tried Godeps a few months ago, but I had some issues that I was unable to resolve, so I just decided to write my own script.

**Comment by junegunn** [comment]
Glide it is.
