### ISSUE TITLE
Set TERM for Neovim and fzf built with tcell

### ISSUE THREAD

**Issue by fimkap** [junegunn/fzf#911]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [*] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [*] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [*] bash
    - [ ] zsh
    - [ ] fish

I'm using fzf v. 0.16.6, neovim v0.2.0-1303-gdd391bf, iTerm2 v. 3.0.15. The fzf built from the source with TCELL.
As follows from Tcell's docs one needs TERM set to something like xterm-truecolor in order to display true color in tcell box. So this one works great from the command line:
```shell
TERM=xterm-truecolor fzf --preview "~/dev/termpix/bin/termpix --width 80 --true-color {} 2> /dev/null"
```
The problem is that I cannot set TERM in the context of running fzf inside neovim (using its terminal emulator, I assume). Using alias for fzf or setting it in .bashrc doesn't work. 
So what's the best way to enable true color in TCELL when running fzf from neovim?

**Comment by justinmk** [comment]
You can `:let $TERM=...` in nvim.

**Comment by fimkap** [comment]
That's great! Indeed, I see that the original version of fzf works from the command line with true colors in iTerm2, no need to set TERM. It seems however, that the version built with TCELL tags has better performance when displaying images. 
There's another issue when I try fzf from inside neovim.
<img width="1129" alt="screenshot 2017-05-02 19 46 56" src="https://cloud.githubusercontent.com/assets/2026502/25631660/5a523576-2f71-11e7-9849-fcc0d334f5a3.png">
<img width="1093" alt="screenshot 2017-05-02 19 47 15" src="https://cloud.githubusercontent.com/assets/2026502/25631674/60d9080c-2f71-11e7-8269-5a4a46accb21.png">

Is it something related to NVIM v.0.2.0 ?

**Comment by junegunn** [comment]
Do you see the same issue outside Neovim?

**Comment by fimkap** [comment]
No. Outside Neovim everything works.
```
fzf --preview "~/dev/termpix/bin/termpix --width 50 --true-color {} 2> /dev/null"
```
<img width="1125" alt="screenshot 2017-05-02 23 47 36" src="https://cloud.githubusercontent.com/assets/2026502/25640957/0114a00e-2f92-11e7-95d2-6a69b7360239.png">

**Comment by junegunn** [comment]
Closing as it's an issue of Neovim rather than fzf.

**Comment by fimkap** [comment]
Hi, from NeoVim version 0.2.1 and the latest fzf the true colors work inside the editor with fzf preview. Thanks
<img width="1444" alt="screen shot 2017-11-17 at 3 49 56 pm" src="https://user-images.githubusercontent.com/2026502/32990999-b1dbd97c-cd33-11e7-8960-643920dea7d4.png">
