### ISSUE TITLE
Problem with 0.16.7 and using in NeoVim

### ISSUE THREAD

**Issue by markwoodhall** [junegunn/fzf#917]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [x] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

Thanks so much for making FZF, I love it, and appreciate the work that goes into it. I'm currently experiencing an issue with the latest version. I'm running zsh on Arch, and am having issues using FZF from NeoVim, outside of NeoVim everything works fine. 

I've been using without any issues for quite some time but I can't get the 0.16.7 release to work inside NeoVim, if I roll back to 0.16.6 everything works fine again. I'm using the latest fzf.vim. 

This is the error I get when using the latest fzf.vim with 0.16.7 of fzf. 

![error](http://i.imgur.com/VW24Vwt.gif)

```
sh: : command not found
```

```
Error running /usr/bin/zsh "/tmp/nvimO5gMCA/4"|"" --color=bg+:#343d46,spinner:#fac863,hl:#65737e,fg:#fcfcfc,header:#65737e,info:#fac863,pointer:#ec5f67,marker:#c594c5,fg+:#fcfcfc,prompt:#c594c5,hl+:#ec5f67 -m  --prompt '~/.fzf/' --expect=ctrl-v,ctrl-x,ctrl-t --no-height > /tmp/nvimO5gMCA/3
```

Cheers, 
Mark

**Comment by johnoshea** [comment]
Do you have `*/bin/*` as part of your `wildignore` string by any chance? I had a similar error (on OS X/vim) and removing that fixed it.

For reference, [this is the change](https://github.com/junegunn/fzf/commit/7a11a06cbd03353e7c0c7ddc25cd6e9fe58cef6d#diff-24d9d57e35df5afce7890f2400917919L44)  responsible for the change in FZF behaviour.

**Comment by markwoodhall** [comment]
Oh wow. Yeah, I do a lot of .net stuff so ignore bin/object etc. Will check
it out and report back, thanks.

On 21 May 2017 16:05, "johnoshea" <notifications@github.com> wrote:

Do you have */bin/* as part of your wildignore string by any chance? I had
a similar error (on OS X/vim) and removing that fixed it.

For reference, this is the change
<https://github.com/junegunn/fzf/commit/7a11a06cbd03353e7c0c7ddc25cd6e9fe58cef6d#diff-24d9d57e35df5afce7890f2400917919L44>
responsible for the change in FZF behaviour.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/junegunn/fzf/issues/917#issuecomment-302942337>, or mute
the thread

**Comment by junegunn** [comment]
@johnoshea Interesting. Can you check the values of `s:base_dir`, `s:fzf_go`, and `s:fzf_expand(s:fzf_go)` when that happens?

**Comment by johnoshea** [comment]
@junegunn Sure. With `/bin/` back in my wildignore setting I get the following (output wrapped in square brackets):

    s:fzf_go [/usr/local/Cellar/fzf/0.16.7/bin/fzf]
    s:base_dir [/usr/local/Cellar/fzf/0.16.7]
    s:fzf_expand(s:fzf_go) []
    expand(s:fzf_go) []

and with `/bin/` removed, the last two items produce the same output as the first.

**Comment by junegunn** [comment]
Thanks, I didn't expect wildignore to have such an effect on the return value. I'll see what I can do.

**Comment by junegunn** [comment]
I just removed unnecessary `expand()` call as @johnoshea suggested, thanks for the help. @markwoodhall can you confirm that your problem was caused by this?

**Comment by justinmk** [comment]
@junegunn you could pass `1` as the 2nd arg to expand(), to ignore 'wildignore'.

**Comment by junegunn** [comment]
@justinmk That's even better, thanks.

**Comment by markwoodhall** [comment]
@junegunn yep, it was indeed the wildignore causing the problem. Thanks for the help! 👍
