### ISSUE TITLE
request: more keybindings

### ISSUE THREAD

**Issue by DanielFGray** [junegunn/fzf#918]
there are a few keys that i've tried to `--bind` or `--expect` that fzf complains about unsupported keys.

* shift-enter
* shift-space
* ctrl-enter
* ctrl-space

I know that some sequences are interpreted by the terminal somewhat 'ambiguously', ctrl-m and enter, ctr-i and tab for example, but I think it should be possible to allow binding to these.

**Comment by junegunn** [comment]
I believe most terminal emulators cannot process those key chords. I just googled a bit, here are some related SO links.

http://stackoverflow.com/questions/598113/can-terminals-detect-shift-enter-or-control-enter
http://stackoverflow.com/questions/279959/how-can-i-make-shiftspacebar-page-up-in-vim

**Comment by jan-warchol** [comment]
I have also been looking for a way to bind ctrl-enter in FZF. Thanks @junegunn for providing SO links - I learned about Ctrl-J and it seems to solve my problem :-)
