### ISSUE TITLE
FZF not finding files in some subdirectories

### ISSUE THREAD

**Issue by ddickstein** [junegunn/fzf#919]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

If I try running `fzf` on my `~/.vim` directory and filter with the text `after`, I get a list of files that appear in `plugged/../after/` subdirectories.  However, no results from the `~/.vim/after` subdirectory appear in this list.
```
$ cd ~/.vim
$ fzf
> after
  12/1065
> plugged/vim-xhp/after/syntax/php.vim
  plugged/vim-xhp/after/indent/php.vim
  plugged/vim-jsx/after/syntax/jsx.vim
  plugged/vim-jsx/after/indent/jsx.vim
  plugged/vim-hack/after/syntax/php.vim
  plugged/vim-jsx/after/ftplugin/jsx.vim
  plugged/vim-hack/after/ftplugin/php.vim
  plugged/UltiSnips/after/plugin/UltiSnips_after.vim
  plugged/vim-hack/after/syntax/php-builtins/classes.vim
  plugged/vim-hack/after/syntax/php-builtins/functions.vim
  plugged/vim-hack/after/syntax/php-builtins/interfaces.vim
  plugged/arcanist.vim/ftdetect/arcanist.vim
```
If I directly try running FZF in `~/.vim/after`, I see the results I would have expected to see in the previous query.
```
$ cd ~/.vim/after
$ fzf
>
  15/15
> ftplugin/vim.vim
  ftplugin/text.vim
  ftplugin/php.vim
  ftplugin/python.vim
  ftplugin/arcanistdiff.vim
  ftplugin/hgcommit.vim
  ftplugin/snippets.vim
  ftplugin/sql.vim
  ftplugin/conf.vim
  ftplugin/help.vim
  ftplugin/java.vim
  ftplugin/csv.vim
  syntax/php.vim
  syntax/python.vim
  indent/php.vim
```
Why are these files not included?

**Comment by ddickstein** [comment]
Issue was that the after folder is symlink to elsewhere, and fzf doesn't follow symlinks.

**Comment by junegunn** [comment]
It does follow symlinks (see `-L` in https://github.com/junegunn/fzf/blob/6898849e3e7908c8c5d7fff243ff3d8b630ebc75/src/constants_unix.go#L7) by default. Check if your FZF_DEFAULT_COMMAND does that (if you configured it).

**Comment by ddickstein** [comment]
Yeah I think I had configured it to not follow symlinks and had just forgotten that those directories were symlinked.
