### ISSUE TITLE
Possibility to remove total number line

### ISSUE THREAD

**Issue by sassanh** [junegunn/fzf#920]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [ ] fish

It's just a question, is it possible to eliminate the line that shows number of items?

**Comment by junegunn** [comment]
No option for that currently. Alternatively, you can consider using `--inline-info` or change the color of the line using `--color` option. See `man fzf` for details.

**Comment by sassanh** [comment]
Yeah I ended up using `--inline-info` but I still think it's nice to be able to remove it altogether instead of inlining it.

**Comment by Valloric** [comment]
Any chance of an option being added that hides these numbers? `--inline-info` doesn't make things much better; to me the numbers are just random noise I'd rather not have to perceive.
