### ISSUE TITLE
fzf on Centos no results

### ISSUE THREAD

**Issue by hackhowtofaq** [junegunn/fzf#922]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [ ] fish

Whass up...

I am straggling to make fzf work on Centos 7 and I am in a very strange situation.

Everything is done by the book.

When I execute fzf in a folder with 10 files, I am getting 
```
  0/0 
>
```
If I feed fzf with find results it is working!

```
find . -type f | fzf
```

Any clues...?

As a workaround I renamed `fzf` to `fzf.bin` and I made a bash shell `fzf`
```
#!/bin/bash
find . -type f | fzf.bin "$@"
```

Ty

**Comment by hackhowtofaq** [comment]
I found it!!

Even though I was in Bash shell, `SHELL` env variable was set to `/bin/tcsh`

```
echo $SHELL
> /bin/tcsh
```
If I set SHELL 
```
SHELL=/bin/bash fzf
```
fzf is working as expected!!!

**Comment by junegunn** [comment]
> SHELL env variable was set to /bin/tcsh

Any idea why?

**Comment by hackhowtofaq** [comment]
SHELL is set to the default shell (set by admin) which in my case is `tcsh`

If i switch to bash by executing `bash` on tcsh, SHELL is still pointing to `tcsh`.

I am not sure if this is the correct behavior or a Centos bug.

**Comment by junegunn** [comment]
Oh, right, thanks. `$SHELL` only reflects the login shell. Unfortunately, it seems there is no good way to determine the current shell.

http://stackoverflow.com/questions/3327013/how-to-determine-the-current-shell-im-working-on

**Comment by zhuzhzh** [comment]
@hackhowtofaq I use this command to get the running shell

CURSHELL=`ps|grep $$|awk '{print $4}'`
