### ISSUE TITLE
Search and play tracks in iTunes

### ISSUE THREAD

**Issue by chew-z** [junegunn/fzf#923]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [x] Etc.
- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [x] bash
    - [x] zsh
    - [ ] fish

Using a bit of Javascript glue I have made fzf search through iTunes Library.

 iTunes collection could be huge in itself and fzf performs here brilliantly locating tracks I didn't know exists.

With help of ```--bind execute-silent``` option fzf plays selected track. It works in loop and changes fzf in highly searchable iTunes player.

If you still use iTunes. 

Available in VIM or your favorite shell.

Perhaps worth mention in fzf Wiki.

Not and issue.

**Comment by junegunn** [comment]
Thanks for sharing, feel free to add your project to https://github.com/junegunn/fzf/wiki/Related-projects
