### ISSUE TITLE
An option to select a row by default

### ISSUE THREAD

**Issue by sassanh** [junegunn/fzf#924]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [ ] fish

It's a feature request. It would be great to set initial selected row (currently it's first row). I know about ---header-lines, but I don't want to make some rows header lines, I just want fzf to have second row for example when it runs.

**Comment by junegunn** [comment]
This was discussed before. Although adding the option may seem trivial, there are some subtle issues and complications it entails that we don't have good answers to. See #883 and #887.

I may revisit this later, but I'm not considering the option at the moment to keep fzf simple.

**Comment by sassanh** [comment]
I see. I guess I can deal with it.
