### ISSUE TITLE
Request: --cycle only for up/down not page-up/down

### ISSUE THREAD

**Issue by GrumpyDave** [junegunn/fzf#928]
- Category
    - [x ] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [ ] fish

I'd like to suggest that the --cycle option apply to the up and down actions but not the page-up and page-down actions.  Paging up should stop at the top of the list and paging down at the bottom.  The arrow keys or their equivalents should move the cursor and wrap around the list as they do today when --cycle is enabled.

I use a similar program for X-based menus and it functions this way.  I find it much more intuitive and useful.  It lets you know when you've reached the beginning or end of the list.  The way fzf works now once you start scrolling by page it's too easy to get lost or overshoot if you're just trying to quickly get back to the top, for example.

I realize that scrolling through pages isn't the primary use since this is a search tool but sometimes it's helpful and I can say from my direct experience this would improve the experience.

**Comment by junegunn** [comment]
Thanks for the suggestion. I personally don't use `--cycle`, but I can see your point. I'll commit to devel branch for now.
