### ISSUE TITLE
Sets norelativenumber

### ISSUE THREAD

**Issue by rosshadden** [junegunn/fzf#930]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [x] Vim
    - [x] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [ ] fish

Using `fzf` inside vim sets `norelativenumber`, globally.  I cannot figure out where this is happening, but `:verbose set relativenumber?` says it is set by this plugin, in `fzf/plugin/fzf.vim`.  Sure enough, the `relativenumber`setting in my vim config is respected until I run `fzf`, after which point it is disabled.

> UPDATE:  Only neovim has the issue.  Vim is unaffected.

**Comment by junegunn** [comment]
I can't seem to reproduce. Can you reproduce the issue with other plugins disabled?

https://gist.githubusercontent.com/junegunn/6936bf79fedd3a079aeb1dd2f3c81ef5/raw

**Comment by justinmk** [comment]
This happens only in terminal buffers. Your global setting isn't changed. If you want relativnumber in terminal buffers :

    au TermOpen * set relativenumber

**Comment by rosshadden** [comment]
@justinmk You're right, it happens with a function I made to open Ranger in a terminal buffer as well.  Misdiagnosed this is as something wrong with fzf.  Thanks.

Also do you know why neovim does this?  It seems like a bug to me, and if you agree I'll report it.

**Comment by justinmk** [comment]
@rosshadden It's intentional. In terminal-mode 'realtivenumber' is meaningless https://github.com/neovim/neovim/pull/6185/commits/857113ca8c76cd103b752ad4460ee1b091e0831a

**Comment by rosshadden** [comment]
@justinmk Sure, but I don't see why neovim doesn't restore the previous setting when you exit terminal mode.  Unless opening a file from within terminal mode (through shell, fzf, ranger, etc.) stays in it, I suppose.

**Comment by justinmk** [comment]
It's just a local default. However, thinking on it some more, I don't think we need this default anymore, since terminal-buffer cursor position was fixed in 0.2 (in 0.1.7 and earlier, the normal-mode cursor always shifted to the bottom).

With https://github.com/neovim/neovim/pull/6796 terminal will no longer modify 'number' and 'relativenumber'.
