### ISSUE TITLE
FZF not working with GVIM

### ISSUE THREAD

**Issue by yashLadha** [junegunn/fzf#936]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [x] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

 TZF works in vim and not working in graphical interface. Saying that it is not able to use the xterm command.
![screenshot from 2017-06-04 15-45-36](https://cloud.githubusercontent.com/assets/18033231/26760694/e528fd12-493c-11e7-9720-dc68fd5cea3b.png)

**Comment by junegunn** [comment]
You probably don't have xterm.

See #331 and https://github.com/junegunn/fzf/blob/master/README-VIM.md#gvim

**Comment by junegunn** [comment]
The error message can be improved though.
