### ISSUE TITLE
Navigate tmux tabs in addition to sessions

### ISSUE THREAD

**Issue by devth** [junegunn/fzf#938]
- Category
    - [ ] fzf binary
    - [x] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

Tabs are also named. To see the full list you can use `prefix + s`, then hit space bar on a session to expand all of its tabs.

**Comment by junegunn** [comment]
Sorry, but I'm not sure what you're suggesting here.
