### ISSUE TITLE
/usr/local/opt/fzf/install not exist!

### ISSUE THREAD

**Issue by zxdposter** [junegunn/fzf#942]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

When I use brew install fzf, `/usr/local/opt/fzf/install` this file not exist.

So I cannot use key binding `ctrl + r` `ctrl + t`. Why?

**Comment by junegunn** [comment]
Thanks for the report. It looks like the recent update of Homebrew formula mistakenly dropped the file.

**Comment by junegunn** [comment]
Should be fixed when https://github.com/Homebrew/homebrew-core/pull/14410 is merged.
