### ISSUE TITLE
How make fzf distinct result when I search zsh_history?

### ISSUE THREAD

**Issue by zxdposter** [junegunn/fzf#947]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

like this
![wx20170612-134047](https://user-images.githubusercontent.com/13846260/27020538-d13164aa-4f74-11e7-8870-ddb336cd5898.png)

actually, they only have to show just once...

I used this in my .zshrc, but it only effective for continuous orders.
    setopt HIST_IGNORE_DUPS

**Comment by junegunn** [comment]
Have you tried setting up `HIST_IGNORE_ALL_DUPS`?

Reference: http://zsh.sourceforge.net/Doc/Release/Options.html

**Comment by zxdposter** [comment]
Thank so much!😊
