### ISSUE TITLE
[Feature request] Subsume functionatliy of "autojump"

### ISSUE THREAD

**Issue by SRGOM** [junegunn/fzf#948]
There are autojump programs that keep a history of recently visited dirs. It'd be great if `Alt-C` could show those as well to jump to.

List of such programs: 

bash: https://github.com/rupa/z
ruby: https://github.com/madx/jumpr

Example usage with current programs, after installation:

```
[~]$ cd ~/x 
[~/x] $ cd ~/y
[~/y] $ cd ~/z
[~/z] $ z x
[~/x] $
```

**Comment by junegunn** [comment]
You can easily hook fzf up to those programs, see:

https://github.com/junegunn/fzf/wiki/Examples#z
