### ISSUE TITLE
Inconsistent look between find files (CTRL+T) and find previous commands (CTRL+R).

### ISSUE THREAD

**Issue by chaoren** [junegunn/fzf#949]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

Currently CTRL+T (find files) looks like this:
![screenshot from 2017-06-14 11 04 03](https://user-images.githubusercontent.com/10055601/27139695-b453cb2e-50f1-11e7-97cf-99b92b54d3a6.png)
which I like very much, but CTRL+R (find previous commands) still looks like this:
![screenshot from 2017-06-14 11 06 03](https://user-images.githubusercontent.com/10055601/27139681-acf3f5b6-50f1-11e7-837b-8a647d0471f1.png)
Is there a reason why they're inconsistent? If it's just an oversight, I would very much appreciate it if the CTRL+R list looked like the CTRL+T list.

Also, I see the gif on the README still shows the old CTRL+T, which is a shame because this new look is so much better.

**Comment by chaoren** [comment]
Ah, that's right, CTRL+R requires shell to evaluate !n.

**Comment by junegunn** [comment]
That's to list the commands in chronological order, from top to bottom. To override, you can add `--reverse` to `$FZF_CTRL_R_OPTS`, or you can add it to `$FZF_DEFAULT_OPTS` if you want to apply the option globally.

> Also, I see the gif on the README still shows the old CTRL+T, which is a shame because this new look is so much better.

Yeah, the gif's really outdated, I need to find some time to re-record that.

**Comment by chaoren** [comment]
> That's to list the commands in chronological order,

I meant the ugly `$ __fzf_history__` too. CTRL-T solves it either `bind -x`, but CTRL-R needs to have the shell evaluate !n.

**Comment by junegunn** [comment]
Yeah, that's right. Actually, I don't think I prefer `bind -x` version of CTRL-T as it completely hides the current command line. The old implementation (without `-x`) replaces the command line with `__fzf_select__` but it still shows my PS1, gives me some context.

Neither zsh nor fish have this issue.
