### ISSUE TITLE
Shell configuration updated no matter what (possibly?)

### ISSUE THREAD

**Issue by booc0mtaco** [junegunn/fzf#950]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [x] Etc.
- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

I recently performed a reinstall of `fzf` and when running the install script, I got this output:

```shell

Do you want to update your shell configuration files? ([y]/n) n

Update /Users/andrewh/.bashrc:
  - [ -f ~/.fzf.bash ] && source ~/.fzf.bash
    - Already exists: line #3 

Update /Users/andrewh/.zshrc:
  - [ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
    - Already exists: line #2 

Update /Users/andrewh/.config/fish/functions/fish_user_key_bindings.fish:
  - fzf_key_bindings
    - Already exists: line #2 
```

So it **seems** like even when selecting `n`, it tries to update the configuration anyway. This might be a problem for people with delicate config files.

Am I reading this correctly? I saw this when running `install` on the latest version (0.16.8)

**Comment by junegunn** [comment]
No, it doesn't update, they're just informational messages. You can test it after removing that line from one of your files. Having said that, I agree that the message can be confusing. I'll fix it.
