### ISSUE TITLE
Change CRTL-T keybinding to something else? (e.g. CRTL-Q)

### ISSUE THREAD

**Issue by jgorham** [junegunn/fzf#952]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [x] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

I love this project! I do have a question though; I bind CRTL-T to specific bindings in my .screenrc, and I was hoping to change all the CRTL-T functionality to CRTL-Q [or something like that]. I already tried just swapping out C-c t with C-c q in the zsh keybindings file, but that didn't seem to work. Is there a preferred way to make this switch?

Thanks!

**Comment by junegunn** [comment]
You can use `bindkey` command like follows.

```sh
bindkey -r '^T'
bindkey '^Q' fzf-file-widget
```

Make sure to do it after you load `~/.fzf.zsh`.
