### ISSUE TITLE
Multiline item's separator doesn't use '\n'

### ISSUE THREAD

**Issue by amosbird** [junegunn/fzf#953]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [x] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [x] fish

I'm trying to get multiline history completion work by `history -z | fzf --read0`. However it generates items that are not separated by `\n` but `\?` which breaks command line substitution.

![](https://la.wentropy.com/p7hy.png)

**Comment by junegunn** [comment]
fzf does not officially support multi-line entries, and with the premise, a new line character is not a valid character fzf can properly display on screen, and fzf prints it as `?` character instead. I know it is not ideal, but it's how it works right now.

fzf displays those characters as `?`, but that does not affect the final output of fzf, so you can still depend on it.

```sh
> echo -en "foo\nbar" | fzf --read0 --select-1 | wc -l
       2
```

Notice that we have no issues with multi-line commands in bash and zsh, as `history` and `fc -l 1` commands of them are smart enough to transform a multi-line command into a single-line entry.

```
$ a() {
> 1
> 2
> }
$ HISTTIMEFORMAT= history | tail -2
94918  a() { 1; 2; }
94919  HISTTIMEFORMAT= history | tail -2
$
```

Maybe fish can do something similar?

**Comment by amosbird** [comment]
ah, fish's read command also needs a `-z` flag.  This works `history -z | eval (__fzfcmd) --read0 -q '$str' | read -lz result`
