### ISSUE TITLE
Expanding the `mpc` integration

### ISSUE THREAD

**Issue by piotryordanov** [junegunn/fzf#955]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [x] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

- - - -

I love the `mpc` integration. I noticed that it only picks up the current playlist. 
Is there a way to have it search the library for songs, artists, albums and genre?

**Comment by piotryordanov** [comment]
I found a way to do so.

```
# Search for Genre
fmg() {
  local genre
  genre=$(mpc list genre | \
    fzf-tmux --query="$1" --reverse --select-1 --exit-0) || return 1
  [ -n "$genre" ] && mpc search genre $genre | mpc insert; mpc next
}

# Search for any Song
fms() {
  local song
  song=$(mpc search any "" | \
    fzf-tmux --query="$1" --reverse --select-1 --exit-0) || return 1
  [ -n "$song" ] && mpc add $song; mpc next
}
```

But, I think I can make it even better. I'll close this issue and open a pull request with updates soon.

**Comment by junegunn** [comment]
You mean the wiki page? You can freely edit the page, no need for a pull request. Just make sure that your code is robust 😄

**Comment by piotryordanov** [comment]
Yup. It all depends on how the implementation goes. If it's too complex, I'll take ur advise, maybe I better spin it as a plugin, maybe not. Less is better :)

**Comment by piotryordanov** [comment]
@junegunn

I came up with this rather long set of function. But, hey! I can have so much more power now. it almost mimics what aflred does for itunes. I didn't include playlists though cuz I don't have any :P 

Would it be too long to get in the wiki, or is it fine?

```
# MPD FTW
# This function will invoke a meny that lets you select What kind of search you wish to do.
# It's an easy shortcut for the other methods, in case you're lazy to type them ;)
fm() {
  local list
  list=$(echo 'Any' && echo 'Genre' && echo 'Artist' && echo 'Albums' && echo 'Clear Playlist')
  rm -f fileTypes
  echo $list > fileTypes

  type=$(cat fileTypes | \
    fzf-tmux --query="$1" --reverse --select-1 --exit-0 ) || return 1
  case `echo $type` in
    'Genre') fmg;;
    'Artist') fmaa;;
    'Albums') fma;;
    'Clear Playlist') fmc;;
    *) fms;;
  esac
}

# Function to show the current playlist
fmpc() {
  local song_position
  song_position=$(mpc -f "%position%) %time% - %artist% - %title%" playlist | \
    fzf-tmux --query="$1" --reverse --select-1 --exit-0 | \
    sed 's/).*//') || return 1
  [ -n "$song_position" ] && mpc -q play $song_position
}

# Search for any Song
fms() {
  local song
  song=$(mpc search any "" | \
    fzf-tmux --query="$1" --reverse --select-1 --exit-0) || return 1
  [ -n "$song" ] && mpc add $song; mpc play; mpc next
}

# Search Genres
fmg() {
  local genre
  genre=$(mpc list genre | \
    fzf-tmux --query="$1" --reverse --select-1 --exit-0) || return 1
  mpc clear;
  [ -n "$genre" ] && mpc search genre $genre | mpc insert; mpc play
}

# Search Artists
fmaa() {
  local artist
  artist=$(mpc list artist | \
    fzf-tmux --query="$1" --reverse --select-1 --exit-0) || return 1
  mpc clear;
  [ -n "$artist" ] && mpc search artist $artist | mpc insert; mpc play
}

# Search Albums
fma() {
  local albums
  album=$(mpc list album | \
    fzf-tmux --query="$1" --reverse --select-1 --exit-0) || return 1
  mpc clear;
  [ -n "$album" ] && mpc search album $album | mpc insert; mpc play
}

# Clear the playlist and invoke the fm()
fmc() {
  mpc clear
  fm
}
```

**Comment by junegunn** [comment]
@piotryordanov Thanks for sharing. Since the purpose of the wiki page is to help users learn how to use fzf with other programs rather than to provide complete source code for sophisticated applications, I suggest that you put the code on a gist (or a separate git repository), and add a link to it below the basic `mpc` example we currently have.

**Comment by piotryordanov** [comment]
@junegunn I ended up buildign and releasing this script as a standalone zsh script.
It's [here](https://github.com/piotryordanov/fzf-mpd)

I also added it to the [wiki](https://github.com/junegunn/fzf/wiki/Examples#fzf-mpd). I kept the original mpc script because I do not support it in the plugin.
Everything looking good?

Cheers!
