### ISSUE TITLE
`Ctrl-T` in zsh current directory not used

### ISSUE THREAD

**Issue by skulumani** [junegunn/fzf#956]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [X] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [X] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [X] zsh
    - [ ] fish

Thank you for the great work. I have a question about the `Ctrl-T` keybinding in zsh. I think this is similar to #945 

I'm using the instructions from the [wiki](https://github.com/junegunn/fzf/wiki/Configuring-fuzzy-completion) but it seems that using `Ctrl-T` only searches the current directory rather than using the path already entered. 

If possible it would make the most sense to have the keybinding work exactly that same as the default `**<tab>` capability. 

Any suggestions on what I'm not setting up correctly?

Thanks

**Comment by junegunn** [comment]
It works for me. Have you made sure that you added the snippet after `[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh`?

**Comment by skulumani** [comment]
Here's a excerpt from my `.zshrc`

~~~
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh                                      
                                                                             
export FZF_COMPLETION_TRIGGER='**'
bindkey '^T' fzf-completion
bindkey '^I' $fzf_default_completion
~~~

The '**<Tab>' operation works as expected but `Ctrl-T` does not work

**Comment by junegunn** [comment]
You shouldn't have done this.

https://github.com/junegunn/fzf/wiki/Configuring-fuzzy-completion/_compare/681cf020f23e4e8f89b52c32485a30c19e3b317d...323ecc3bdbd09500b9be1d4a95c5af7bac7048e9
