### ISSUE TITLE
Suggestsion are scrolled horizontally off screen.

### ISSUE THREAD

**Issue by tmccombs** [junegunn/fzf#957]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [x] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [ ] fish

If I edit a buffer and scroll horizontally to the right, then use `:FZF` the suggestion buffer from fzf is also horizontally scrolled, which makes the suggestions impossible to read.

**Comment by junegunn** [comment]
Are you on Vim or Neovim? Vim shouldn't have the problem, but Neovim, see https://github.com/junegunn/fzf.vim/issues/385

**Comment by tmccombs** [comment]
Neovim, I accidentally checked the wrong box. I'll close as duplicate.
