### ISSUE TITLE
[neovim] File completion on Windows seems to fail if FZF is launched in the same console Window.

### ISSUE THREAD

**Issue by mikesmiffy128** [junegunn/fzf#958]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [x] Completion
    - [ ] Vim
    - [x] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [ ] Mac OS X
    - [x] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [ ] fish

Hi, I'm having a bit of a weird problem. I made a very quick and dirty modification (mikesmiffy128@e5f2d2cb83d4fee3e27adf6a9b661d4414d4e86c) so that FZF will fill the Windows console when using Vim, rather than popping up another window. This seems to work, except that `:FZF` and `:Files` generate a blank list. This only happens if I launch it directly, and fixes itself when using `start`. Even weirder, it works fine with fzf.vim functionality like `:GFiles`, `:Commands` etc, just not files.

Sorry if I'm overlooking something obvious, I'm just kind of hoping there'll be some quick hackish way to fix this. Although if it does end up being unfixable I can of couse deal with the separate pop up.

Thanks for making this tool, by the way, it works great with the exception of this small issue.

**Comment by junegunn** [comment]
Hi, I'm not a Windows expert, so I'm going to ping @janlazo :)

**Comment by janlazo** [comment]
Is this for the Neovim TUI?
Running `:!fzf` produces the empty list. I assume fzf is prevented from running the default shell command or from updating the entries.
Running `:!git ls-files | fzf` works.

**Comment by mikesmiffy128** [comment]
Yeah, it's for the TUI. I should also have mentioned that `!fzf` fails, I'd forgotten that when I made the issue 😕. I suppose that means there's no problem on the Vim plugin side of things, so either fzf itself or Neovim is doing something wrong.

**Comment by janlazo** [comment]
https://github.com/neovim/neovim/issues/1496 is unresolved so running `:!fzf` and similar commands is not officially supported in Neovim. For comparison, `:!fzf` and `:!git ls-files | fzf ` fail in Ubuntu 16.04 for both TUI and GUI.

If you want the hack to work in Windows only, you can set `FZF_DEFAULT_COMMAND` to the [default command](https://github.com/junegunn/fzf/blob/master/src/constants.go#L59) so the results are piped to fzf although I haven't had success with this approach for ack or ag.

**Comment by janlazo** [comment]
If your console is ConEmu or a similar terminal that supports splits, it's possible to do the tmux equivalent of running fzf in a separate split in the terminal instead of a separate window.

**Comment by mikesmiffy128** [comment]
Hmm, it looks like `:!dir /s /b|fzf` does work for me, however I didn't realise it's not supposed to work so I suppose I shouldn't really rely on it. I have considered ConEmu but I don't think I really need any of the fancy features it has. I can probably just wait for `:terminal` support since it looks like it probably won't take that much longer now, and in the meantime I have other Vim stuff still to learn / mess with. I'll leave this open in the meantime in case anyone else knows anything that might be useful.

**Comment by janlazo** [comment]
Is this resolved now?

**Comment by mikesmiffy128** [comment]
I think the reason it didn't work was that running `!fzf` opens a pipe and Neovim doesn't send anything, so FZF comes up empty. However, this was only ever a hacky workaround; everything works correctly when using `:term`, so I'll close this.
