### ISSUE TITLE
fasc save completion

### ISSUE THREAD

**Issue by piotryordanov** [junegunn/fzf#959]
Hey,

I am using the `[fasd](https://github.com/junegunn/fzf/wiki/Examples#with-fasd-1)` function from the wiki and it works, but it doesn't seem to save the results I click, meaning that my history doesn't update. Any idea how to fix that?

**Comment by edi9999** [comment]
You have to use the option --history to use the history. 

for example : 

```
v() {
  local file
  file="$(fasd -Rfl "$1" | fzf -1 -0 --no-sort +m --history ~/.fasdfzfhistory)" && vi "${file}" || return 1
}
```

Or you can declare `FZF_DEFAULT_OPTS="--history ~/.fzfhistory"` if you prefer to have a unique history for all your fzf instances

**Comment by piotryordanov** [comment]
The second option did the job for me.

Note however, it had to be `FZF_DEFAULT_OPTS="--history $HOME/.fzfhistory"`
