### ISSUE TITLE
locate: illegal option -- A error 

### ISSUE THREAD

**Issue by nikitavoloboev** [junegunn/fzf#964]
- Category
    - [z ] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ x] Completion
    - [ ] Vim
    - [ ] Neovim
    - [z ] Etc.
- OS
    - [ ] Linux
    - [z ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ z] zsh
    - [ ] fish

Using this script from examples : 

```Bash
# cf - fuzzy cd from anywhere
# ex: cf word1 word2 ... (even part of a file name)
# zsh autoload function
cf() {
  local file

  file="$(locate -Ai -0 $@ | grep -z -vE '~$' | fzf --read0 -0 -1)"

  if [[ -n $file ]]
  then
     if [[ -d $file ]]
     then
        cd -- $file
     else
        cd -- ${file:h}
     fi
  fi
}
```

Gives me this error : 

```Bash
locate: illegal option -- A
usage: locate [-0Scims] [-l limit] [-d database] pattern ...

default database: `/var/db/locate.database' or $LOCATE_PATH
grep: invalid option -- z
usage: grep [-abcDEFGHhIiJLlmnOoqRSsUVvwxZ] [-A num] [-B num] [-C[num]]
	[-e pattern] [-f file] [--binary-files=value] [--color=when]
	[--context[=num]] [--directories=action] [--label] [--line-buffered]
	[--null] [pattern] [file ...]
```

Not sure what I can do to fix this.

**Comment by junegunn** [comment]
Looks like the example is for Linux, so you'll have to change the options so that it works on macOS. Would've been nice if it was clearly stated. Note that the wiki page is maintained by the community, and I usually don't review updates.

**Comment by elliottregan** [comment]
@nikitavoloboev Did you get this working on macOS?

**Comment by nikitavoloboev** [comment]
Dont think I did

**Comment by geoyws** [comment]
Can anyone get this to work on macOS? :(

**Comment by thouger** [comment]
same problem，but，i don't install fzf,
