### ISSUE TITLE
^R broken with fish: "history: invalid option -- -z"

### ISSUE THREAD

**Issue by ludovicaelbrecht** [junegunn/fzf#966]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [x] Key bindings
    - [x] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [x] fish

I've been using fzf with fish (version 2.3.1, latest on Fedora 25) for a couple of months now. Was mostly using the completion it offers when I hit ^R. 

Decided to update fzf (git pull in ~/.fzf, then ~/.fzf/install), and now it's broken: when I hit ^R in fish, I get this: "history: invalid option -- -z". Still works fine in bash.

Here's what it looks like:

```
~/.fzf (master) $ git pull
Already up-to-date.
~/.fzf (master) $ ~/.fzf/install
Downloading bin/fzf ...
  - Already exists
  - Checking fzf executable ... 0.16.8
Do you want to enable fuzzy auto-completion? ([y]/n) y
Do you want to enable key bindings? ([y]/n) y

Generate ~/.fzf.bash ... OK
Update fish_user_paths ... OK
Symlink /home/ludovic/.config/fish/functions/fzf_key_bindings.fish ... OK

Do you want to update your shell configuration files? ([y]/n) y

Update /home/ludovic/.bashrc:
  - [ -f ~/.fzf.bash ] && source ~/.fzf.bash
    - Already exists: line #55 

Update /home/ludovic/.config/fish/functions/fish_user_key_bindings.fish:
  - fzf_key_bindings
    - Already exists: line #3 

Finished. Restart your shell or reload config file.
   source ~/.bashrc  # bash
   fzf_key_bindings  # fish

Use uninstall script to remove fzf.

For more information, see: https://github.com/junegunn/fzf
~/.fzf (master) $ history: invalid option -- -z
```
This last line, with the error message, shows up each time I hit ctrl-R.

Am I doing something wrong? Maybe the -z version is only supported in more recent versions of fish?

Thanks!
Ludovic

**Comment by junegunn** [comment]
> Maybe the -z version is only supported in more recent versions of fish?

I just googled it and it turns out fish 2.4 is required.

https://github.com/fish-shell/fish-shell/commit/a26f68d63fb3780a1eb0c092b31b99bc67290933

/cc @tomfitzhenry

**Comment by tomfitzhenry** [comment]
@ludovicaelbrecht thanks for the report!

https://github.com/junegunn/fzf/pull/954/commits/7643d9513ab41c851b397e6e5a512f731b7f8071 is the commit that introduced this regression against fish 2.3. As a workaround, you could manually reverse that change in `~/.config/fish/functions/fzf_key_bindings.fish`.

I'll have time to develop and test a better fix in ~12 hours.

**Comment by ludovicaelbrecht** [comment]
Wow, thanks for the quick response!

I tried out your patch, it fixes the issue for me 👍 

Looking at the PR, it looks like as soon as the added space on line 4 is removed, the PR will get merged.

Cheers @tomfitzhenry
