### ISSUE TITLE
Some keypresses are not registered when using a never finishing stdin

### ISSUE THREAD

**Issue by edi9999** [junegunn/fzf#973]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

I have finally found out how to reproduce my bug with a simple program : 

For some reason, when I use fzf with input coming from a "tailing" command (eg a command that never ends to output text), the keys that I type in fzf are sometimes totally ignored.

For example, in the GIF below, I type 

`abcdefghijklmnopqrstuvwxyz`

![gifrecord_2017-07-12_011746](https://user-images.githubusercontent.com/2071336/28095028-7260ac04-66a0-11e7-9fe2-c14efc3be924.gif)

and you see that some of the keys are not registered. The keys that are not registered differ each time fzfbug is this command 

```
ssh storage tee /tmp/foo << EOF
1d99dc9d-e978-4123-b307-5f603bf25de9
29a030e0-5655-4288-b4c1-5bdfbbeb657e
ebab6bcc-c91d-44f4-be57-d016b3e8894c
5f025b5c-9b8b-4296-90a1-4892271f16f1
f7a32416-0de7-4ba6-9437-3f0d5a88df36
09dd49bd-f655-4040-a01e-95ce172e0db8
b1dd1cc1-0300-4b46-b254-c2f0aed29b0f
02cecfc4-fd18-4a01-bd4b-80c8de617180
65f2e1b7-2a9d-49f0-b774-2a677a00c462
2e50472d-0752-448f-9724-c74f8aab1d6f
f4b4fa34-faac-4551-a96b-40e392c3f462
271de359-be77-4917-872a-b713251d8443
57fbd40a-d599-4a70-90fe-0c440d3200de
5eb70f73-de94-4e35-a4cb-0b87bd4cf280
b53237f5-7c92-45a9-baf2-8edb2a8261b2
ac0c06d5-4678-464c-99cf-bbebe00952bc
6b35fa69-f7ce-46cc-be95-a40e919e518b
d43a12af-ef12-4b99-bd64-7cb4e676add3
91ff4df1-4c04-456c-9478-59c1f967ca02
53a75053-1be8-49e7-a27f-b82dd0a98215
cda1e311-5c23-4dee-b9a3-11070831ae6a
99ffb1f1-9f89-42f7-acfa-b66d88ae6248
68c7cf29-c0a1-4943-9f3e-d17380c81a6f
73dacdb3-01b0-48f0-95d6-b2b5369a7e39
e68aca9a-2c47-40b0-b9cf-e3ad5cef1848
142d8a84-1758-45a3-a235-6c9798442f6c
5f54c614-1796-4001-9384-6acb9a87abf6
EOF
ssh storage tail -f /tmp/foo | FZF_DEFAUlT_OPTS="" fzf
```

For some reason, this issue doesn't happen if : 

1. I use cat instead of tail -f:

```
ssh storage cat /tmp/foo | FZF_DEFAUlT_OPTS="" fzf
```

2. I do the tail -f locally : 

```
tail -f /tmp/foo | FZF_DEFAULT_OPTS="" fzf
```

Any idea of what is happening ?

I am experiencing this issue both within tmux and without tmux, and with xfce4-terminal , alacritty and xterm. 

my TERM is screen-256color

**Comment by edi9999** [comment]
I have found out that I can find a command that triggers this bug that is even more simple : 

just 

```
ssh storage bash -c 'echo 1; sleep 1000'| FZF_DEFAULT_OPTS="" fzf
```

I'm putting FZF_DEFAULT_OPTS="" just to show to you that they are absolutely no options set up.

**Comment by edi9999** [comment]
This problem really seems related to how ssh outputs the text, since even with docker, it cannot be reproduced : 

```
docker run ubuntu:16.04 bash -c 'echo 1; sleep 1000'| FZF_DEFAULT_OPTS="" fzf
```

**Comment by junegunn** [comment]
I can reproduce. It looks like ssh command reads `/dev/tty` and happens to intercept some keystrokes from fzf. One way to prevent this is to change the standard input of ssh:

```sh
ssh storage bash -c 'echo 1; sleep 1000' < /dev/tty | FZF_DEFAULT_OPTS="" fzf
```

**Comment by edi9999** [comment]
Strangely changing it doesn't seem to work for me, but it works well with /dev/null

```
ssh storage bash -c 'echo 1; sleep 1000' < /dev/null | FZF_DEFAULT_OPTS="" fzf
```

Do you know why this happens with ssh, and not with other potentially "interactive programs" ? 

Is this some sort of bug of ssh itself ? I'm quite ignorant of how tty work in general, for example, I didn't know that multiple programs could read from the tty at the same time, and it is even more surprising to me that a program can read "partially" from the tty (what seems to happen here).

Do you have any knowledge of why it is happening ?

Thanks for the solution tough, you really do very good stuff !!

**Comment by junegunn** [comment]
> but it works well with /dev/null

Oh right, it was a typo, glad you figured it out.

We can't blame ssh here because it's fzf who's cheating in this picture. The standard input of ssh command is tty device (/dev/tty) with which it reads unbuffered key strokes to emulate remote terminal experience. In other words, ssh "owns" it. However, the standard input of fzf is the standard output of ssh command, but instead of conforming to the protocol, fzf directly reads `/dev/tty` for key strokes, so now we have two processes competing to read key strokes from the same device, and that caused the problem you observed. By assigning `/dev/null` as the standard input of ssh, ssh no longer tries to read `/dev/tty` and all is well (except [it lingers on even after fzf is finished](https://serverfault.com/questions/365651/why-is-head-hanging-and-not-terminating)).

> Thanks for the solution tough, you really do very good stuff !!

No problem, thank you for your support :)

**Comment by edi9999** [comment]
Thanks for the explanation, it perfectly makes sense !
