### ISSUE TITLE
fzf eating all my CPU

### ISSUE THREAD

**Issue by sobolevn** [junegunn/fzf#975]
- Category
    - [x] fzf binary
- OS
    - [x] Mac OS X
- Shell
    - [x] zsh

I have just installed `fzf` and it is working fine, except it eats all my CPU completely. 
It is a bug or feature? Maybe some indexing/caching/etc is happening in the background?

If so, I guess it should be mentioned somewhere in the docs.

Here's a screenshot of the processes. 
<img width="912" alt="2017-07-15 10 28 34" src="https://user-images.githubusercontent.com/4660275/28237620-24e031da-694c-11e7-86ac-a4a7f7e18114.png">

**Comment by junegunn** [comment]
No, it's not normal. You have multiple fzf processes not properly terminated for some reason, just kill them. What exactly did you do? Can you provide the steps to reproduce the problem?

**Comment by sobolevn** [comment]
I was just messing around with it. Just some basic commands (coping all my history):

**Comment by junegunn** [comment]
Can you reliably reproduce the case?

**Comment by sobolevn** [comment]
Not really, I guess it could be closed as unreproducible.

**Comment by junegunn** [comment]
Alright, let me know if it happens again.

**Comment by leventis** [comment]
just experienced this as well.  here is a screenshot after killing one of the offending fzf instances:

![Screen Shot 2019-07-31 at 12 08 00 PM](https://user-images.githubusercontent.com/914080/62240475-ed9fa700-b38b-11e9-963b-700e504bf037.png)

**Comment by Nic0S** [comment]
I am able to reproduce this consistently using oh my zsh on Mac OSX Monterey (M1 processor):

- Ctrl + R to active history search
- Close the Terminal tab with the search open, click Terminate for "Do you want to terminate running processes in this tab?"
- A zsh process using 100% CPU gets created

Could not replicate this with the fzf plugin disabled (using the default history search).
