### ISSUE TITLE
FZF unsets relativenumber in nvim split

### ISSUE THREAD

**Issue by rcorre** [junegunn/fzf#978]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [x] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [ ] fish

`README.md`:

```md
This is a Readme
===

```

`minrc`:

```vimrc
source /usr/share/vim/vimfiles/plugin/fzf.vim

set rnu             " Relative numbering
set nu              " full line number on current line

"autocmd! OptionSet number echom 'option ' . v:option_old . ' -> ' . v:option_new 
"autocmd! OptionSet relativenumber echom 'option ' . v:option_old . ' -> ' . v:option_new 
```

1. `nvim -u minrc README.md`
2. `set rnu?` returns `relativenumber`
3. `:FZF`
4. Open `README.md` in a vertical split
5. `set rnu?` returns `norelativenumber` in the new `README.md` split

If you uncomment the `autocmd` lines you can see that `rnu` and `nu` are set when opening FZF, and somehow apply to the new split.

Related: #930. However, that links to a patch that should be in nvim 0.2, which I'm using.

**Comment by junegunn** [comment]
We don't have any code that touches the option. See https://github.com/junegunn/fzf.vim/issues/396

**Comment by rcorre** [comment]
Fixed on neovim master. Sorry about that
