### ISSUE TITLE
`__fzf_history__`bash: fzf-tmux -d40%: command not found

### ISSUE THREAD

**Issue by sivaswami** [junegunn/fzf#979]
- Category
    - [ ] fzf binary
    - [x ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ x] bash
    - [ ] zsh
    - [ ] fish

when i press ctrl-R from bash in tmux session I hit the error 
`__fzf_history__`bash: fzf-tmux -d40%: command not found

Here are my env variables. any suggestions ?
$> env | grep -i fzf
FZF_TMUX=1
FZF_DEFAULT_OPTS=--reverse --inline-info --height 40%
FZF_CTRL_T_COMMAND=rg --files --no-ignore --hidden --follow --glob "!.git/*"
FZF_DEFAULT_COMMAND=rg --files --no-ignore --hidden --follow --glob "!.git/*"
_fzf_orig_completion_git=complete -o bashdefault -o default -o nospace -F %s git #__git_wrap__git_main

**Comment by junegunn** [comment]
The message is clear. [`fzf-tmux`](https://github.com/junegunn/fzf/blob/master/bin/fzf-tmux) is not found on your `$PATH`. How did you install fzf?

**Comment by sivaswami** [comment]
I don't want to keep .fzf folder in my /home. So I copied fzf folder to different folder and set the path accordingly in .bashrc

The settings are working fine without tmux started. 
The error message only occurs inside tmux. 
when I check fzf-tmux inside tmux environment, its showing its available in path.

$> type fzf-tmux
fzf-tmux is /myhome/myuser/FZF/bin/fzf-tmux

$> `__fzf_history__`bash: fzf-tmux -d40%: command not found
$>


The environment variables are same in both tmux and without tmux.

**Comment by junegunn** [comment]
Does this work? `$(echo 'fzf-tmux -d40%')`

**Comment by sivaswami** [comment]
## Without tmux

$> $(echo 'fzf-tmux -d40%')
bash: fzf-tmux -d40%: command not found

$> `__fzf_history__`
<495/495/s
495 $(echo 'fzf-tmux -d40%')

## with tmux

$> $(echo 'fzf-tmux -d40%')
bash: fzf-tmux -d40%: command not found

$>  `__fzf_history__`bash: fzf-tmux -d40%: command not found

**Comment by sivaswami** [comment]
Also I understand FZF is not in path. is there any way we can have a FZF_HOME to set globally and it can default to /home/$USER/.fzf  ? A small suggestion.

**Comment by sivaswami** [comment]
ok, I got it working now. I unset FZF_TMUX env variable inside tmux. it is working now.

$unset FZF_TMUX

is there any way to automatically unset it if it is inside tmux session ?

**Comment by junegunn** [comment]
1. `$(echo 'fzf-tmux -d40%')` should work if your `$PATH` is correct (why it shouldn't?). This is definitely some misconfiguration and not an issue of fzf.
2. Not sure why you insist having `FZF_TMUX` outside tmux, it makes no sense.
3. You can clone fzf anywhere on your system. `.fzf` is just a suggestion. install script will take care of everything.
