### ISSUE TITLE
No option to limit fzf to the current directory?

### ISSUE THREAD

**Issue by for-coursera** [junegunn/fzf#980]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

Am I missing something, or there's no option to limit `fzf` to the current directory only and not to go down recursively? Something like `--maxdepth`?

And (for now?) this is only possible if the `FZF_DEFAULT_COMMAND` is set to something like `ag` or `rg`?

**Comment by junegunn** [comment]
fzf is a unix filter, like grep. It doesn't know what each line means.

```sh
seq 1000 | fzf
```


You can set `FZF_DEFAULT_COMMAND` to find command with `-maxdepth` option.

**Comment by vorg** [comment]
For all the lost souls like me before figuring it out. Testes on macOS with zsh:

Add this to `~/.zshrc`

```zsh
export FZF_DEFAULT_COMMAND="find . -maxdepth 1"
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
```

And then instead of `cd **[TAB]`  use `cd [ctrl+t]` and you should get file list only 1 level deep .

**Comment by mgarort** [comment]
Further to @vorg's suggestion, you can use `sed` to remove the annoying first two characters `./` of every line, which take up valuable screen real state.

```bash
export FZF_DEFAULT_COMMAND="find . -maxdepth 1 | sed 's/^..//'"
```

**Comment by jcaffey** [comment]
> For all the lost souls like me before figuring it out. Tested on macOS with zsh:
> 
> Add this to `~/.zshrc`
> 
> ```shell
> export FZF_DEFAULT_COMMAND="find . -maxdepth 1"
> export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
> ```
> 
> And then instead of `cd **[TAB]` use `cd [ctrl+t]` and you should get file list only 1 level deep .

bless you.

**Comment by hbendi** [comment]
If your directories are separated using [ / ], then you can use:

1. `fzf` + `[enter]` = start fuzzy search 

2. type `!/` = exclude lines with backslash


If you want to further limit search to let's say dotless files, you can extend fzf search with:

3. type `!^.` = exclude files starting with dot

**Comment by hbendi** [comment]
If your directories are separated using [ / ], then you can use:

1. `fzf` + `[enter]` = start fuzzy search 

2. type `!/` = exclude lines with backslash


If you want to further limit search to let's say dotless files, you can extend fzf search with:

3. type `!^.` = exclude files starting with dot


If you want to see also directories in current folder, you could do:

`fzf < <(fd --max-depth 1)`

Too much to type out? Add alias to `.bashrc` or `.zshrc` file:

```
     # [ fzfc ]= fuzzy search current 
fzfc='fzf < <(fd --max-depth 1)'
```

**Comment by SteelAtlas** [comment]
> For all the lost souls like me before figuring it out. Tested on macOS with zsh:
> 
> Add this to `~/.zshrc`
> 
> ```shell
> export FZF_DEFAULT_COMMAND="find . -maxdepth 1"
> export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
> ```
> 
> And then instead of `cd **[TAB]` use `cd [ctrl+t]` and you should get file list only 1 level deep .

THANK YOU SO SO MUCH

**Comment by Rudxain** [comment]
> `find . -maxdepth 1 | sed 's/^..//'`

This should be faster:
```sh
find . -maxdepth 1 | cut -c3-
```

but it includes an empty line, so it must become:
```sh
find . -maxdepth 1 | tail -c+3 | cut -c3-
```
which might be slower than a single `sed`, but [definitely faster than `awk`](https://datagubbe.se/cutvawk/)
