### ISSUE TITLE
Help with command to replace CtrlP in VIM

### ISSUE THREAD

**Issue by sittim** [junegunn/fzf#981]
I have been trying to move to FZF, but cannot figure out the command.  For CtrlP, I have the following:

```
let g:ctrlp_user_command = 'ag --ignore={build,.git,.project,*.o,*.d,hw_1_5/*} %s -l --hidden -g ""'
```

How would I define a VIM command to replace the CtrlP?

**Comment by junegunn** [comment]
See https://github.com/junegunn/fzf#environment-variables

**Comment by sittim** [comment]
I am looking for something that can be placed into **project specific `.vimrc`**.  Setting the *environment variables* will change the behavior for **all VIM projects and terminal**, which is not desirable.

**Comment by junegunn** [comment]
Define it in your .vimrc, you can.

**Comment by sittim** [comment]
I tried this:

`let g:FZF_DEFAULT_COMMAND = 'ag --ignore={build,.git,.project,*.o,*.d,hw_1_5/*} %s -l --hidden -g ""'`

but it does not seem to work for me...

**Comment by sittim** [comment]
No more help kind sir?

**Comment by junegunn** [comment]
See `:help :let-environment`

**Comment by mcjohnalds** [comment]
It would be nice if there was a wiki entry for this topic. I was just looking at fzf as a replacement for [ctrlp.vim](https://github.com/ctrlpvim/ctrlp.vim). With Ctrl-P I just had to do this:

```
Plug 'ctrlpvim/ctrlp.vim'
```

```
set wildignore+=**/node_modules/**,**/package-lock.json
```
