### ISSUE TITLE
Search directory option for the fzf binary

### ISSUE THREAD

**Issue by hos** [junegunn/fzf#982]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [ ] zsh
    - [ ] fish

I was looking at the fzf binary manpage, and could not notice an option to choose the search directory. Am I failing to see something obvious? For example, most of the time I need to search in my home directory, so I instinctively look for say a `--directory` flag.

I know that there are workarounds to deal with this, but is it a design choice to omit such functionality, so that fzf is just a filter program? If not, can I suggest that it be added?

**Comment by junegunn** [comment]
> fzf is just a filter program

Yes, it is. `find SOME_DIRECTORY | fzf` is infinitely more flexible. fzf does not implement scanning the file system, but it starts `find` process (or the command specified in `$FZF_DEFAULT_COMMAND`) when its standard input is a tty device just for convenience.
