### ISSUE TITLE
Add an --ansi-output option

### ISSUE THREAD

**Issue by blankname** [junegunn/fzf#983]
- Category
    - [x ] fzf binary

--ansi-output would opt in to preserving ANSI color codes in fzf's output.

**Comment by junegunn** [comment]
What would be the use case of this?

**Comment by blankname** [comment]
I ended up not needing this.
Will re-open if I find a use case.

**Comment by bAndie91** [comment]
I'd like to reopen it. My usecase is a command like `fzgrep`:
```
FZF_DEFAULT_COMMAND="grep --with-filename --line-number --color=always ^ ${*:--}" fzf --no-sort --ansi --nth=3.. --delimiter=: --filter="$pattern"
```
