### ISSUE TITLE
Cancelling FZF history erases all previously entered text:

### ISSUE THREAD

**Issue by felixSchl** [junegunn/fzf#985]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [x] Completion
    - [ ] Vim
    - [ ] Neovim
    - [x] Etc.
- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

Cancelling `__fzf_history__` erases all previously entered text:

So if start typing "ssh", then do "Ctrl-R" to invoke fzf history, then cannot find what I am looking for and cancel ("Ctrl-C" or "Ctrl-G"), my originally entered text is lost.

Happens both with `FZF_TMUX` on and off.

**Comment by junegunn** [comment]
Yeah, I'm aware of the issue. I tried to find the solution, but I concluded that it's not really possible on bash, even with `bind -x` of bash 4. FWIW, zsh and fish don't have this problem.

Anyway if you have a solution, please send me a pull request. Thanks.

**Comment by felixSchl** [comment]
So how is it possible for "Ctrl-T" then? That behaves just fine.

**Comment by junegunn** [comment]
Because it doesn't have to invoke readline function conditionally. You might want to read the source code.

**Comment by arungopalan** [comment]
I think one fix for this would be just show the entered text as a history entry below the other entries, so that i can chose it and it is retained. Is that doable?
