### ISSUE TITLE
Unwanted space inserted when exiting Ctrl-T without selection

### ISSUE THREAD

**Issue by ptzz** [junegunn/fzf#987]
- Category
    - [x] Completion
- OS
    - [x] Mac OS X
- Shell
    - [x] bash

When triggering completion with Ctrl-T and exiting without selecting anything, a space is inserted on the command line. Can this be avoided?

**Comment by junegunn** [comment]
Not possible with bash 3. You'll have no issue if you upgrade to bash 4.
