### ISSUE TITLE
Tags too slow in opening

### ISSUE THREAD

**Issue by kaldown** [junegunn/fzf#989]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [x] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

For instance I had a project with python, js and other languages in there.
doing this: `find . -type f -name '*.py' -not -path "./.env/*" -not -path "*/.tox/*" | ctags -L-
` I rely only for searching python code. I mean - its truncated more than it should be.
And still, have 22k tags, `:Tag SomeClass` indexing couple seconds before start finding.
I'm using pyCharm manually, which looks for everything (js, ruby, python, env, tests, variables and etc) right after I clicked double shift.
Is it possible to "remember" or "pre-indexing" my tags and not spen time waiting at least for signle session (closing tags and calling it after did the same await)?
Thanks

**Comment by junegunn** [comment]
`:Tags` command generates tags file only when it's not found (`:echo tagfiles()`). If one already exists, it starts immediately. So I'm not sure what you're describing. Can you post an asciinema recording of the problem?

**Comment by kaldown** [comment]
Hmm
Actualy I thought that when hit `:Tags` there increasing numbers on bottom are about 'reading' tags. So I thought that you must wait until left part becomes equal right part and only after that you can write tag you want to search for.
Now I tested last searching a tag which starts with 'Z' letter (so it should be last one), before thos numbers become equal, and this tag were found.
So I don't understand, what this numbers are?
![2017-07-23--18 54 32_187x133_scrot](https://user-images.githubusercontent.com/3754017/28500841-6b60e022-6fd8-11e7-9815-d2133a853419.png)

**Comment by junegunn** [comment]
fzf works asynchronously, so you don't have to wait until fzf finished reading the input. You can just start typing. Left: number of matches, right: number of lines read.

Also make sure that you have the latest version of fzf, which is 0.16.10. The initial scanning performance has improved, so the numbers will go up noticeably faster.

**Comment by junegunn** [comment]
And if you know the prefix of the tag, you should use the built-in `:tag` command instead, which should be much faster as it can perform binary search over the tags. `:Tags` command on the other hand has to load the entire tags file on memory and look at every line.

**Comment by kaldown** [comment]
Yeap. That is what I'm asking about.
Would it be better to store tags in memory, rather than re-read it every time you type `:Tags`, even if there is no changes?

**Comment by junegunn** [comment]
No, it's not possible. fzf is a separate process and vim synchronously waits for its completion.

I believe one should use `:Tags` only when fuzzy matching is needed, i.e. don't know the exact tag. I don't use it often. For prefix or exact matching, builtin command and key bindings are much more efficient.

Having said that, I just pushed a commit to fzf.vim (https://github.com/junegunn/fzf.vim/commit/685f9aae97072a190a1230a5c79692e15b7f46c9), which should make the initial loading of Tags significantly faster.
