### ISSUE TITLE
Unwanted space inserted when exiting fzf after trigger sequence

### ISSUE THREAD

**Issue by ptzz** [junegunn/fzf#990]
- Category
    - [x] Completion
- OS
    - [x] Mac OS X
- Shell
    - [x] bash

If I trigger fzf with e.g. `vim **<TAB>` and exit fzf without selection, the resulting command line is `vim **<SPACE>`. Is this by design or because of limits in Bash?

Ideally, I guess the desired result is just `vim<SPACE>`, i.e. the typed command but with the trigger sequence trimmed off.

**Comment by junegunn** [comment]
No it's not intentional. Will see if I can improve it.

**Comment by ptzz** [comment]
Thank you!

**Comment by junegunn** [comment]
Sorry, but I had to revert this as I realized that it affected normal completion with `**`.
