### ISSUE TITLE
How to make the preview output colored?

### ISSUE THREAD

**Issue by wfxr** [junegunn/fzf#992]
- Category
    - [x] fzf binary
- OS
    - [x] Linux
- Shell
    - [x] zsh

Sorry for disturbing, but I really wonder which command make the preview content colored (just like the [screenshot](https://raw.githubusercontent.com/junegunn/i/master/fzf-preview.png) on README).

**Comment by ptzz** [comment]
It is described [here](../wiki/Configuring-shell-key-bindings#preview) and requires `highlight` to be installed:

`export FZF_CTRL_T_OPTS="--preview '(highlight -O ansi -l {} 2> /dev/null || cat {} || tree -C {}) 2> /dev/null | head -200'"`

**Comment by wfxr** [comment]
Oh I see, thank you very much.

**Comment by junegunn** [comment]
It's not limited to CTRL-T. I also use preview for CTRL-R and ALT-C.

https://github.com/junegunn/dotfiles/blob/0cbd36e1510e853de77b61e0fc83827313e09dad/bashrc#L338-L341

And [this is the script](https://github.com/junegunn/fzf.vim/blob/master/bin/preview.rb) I use it on fzf.vim project.

Anyway, see `man fzf` to learn more about `--preview` and `--preview-window` option.
