### ISSUE TITLE
Bash: Line wrapping issue

### ISSUE THREAD

**Issue by leonklingele** [junegunn/fzf#994]
- Category
    - [ ] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [x] Etc.
- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

Steps to reproduce:

1. Use bash with fzf
2. Do an `echo "abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc"` (so you have that command in your bash history)
3. `export PS1="abc abc abc abc abc abc abc abc abc abc abc abc abc abc abc"`
4. Activate fzf's reverse-i-search (Ctrl + r)
5. Select the `echo "abc .."` line, press enter
6. Bash prompt is wrapped incorrectly. After pressing enter in the last step, the cursor is placed at the very end of the line (right after the closing `"`), however there is more text on the right side of the cursor (after EOL).

Is that caused by fzf?

See this demonstration video: ![fzf bash line wrapping issue](https://i.imgur.com/1uOx3lL.gif)

__EDIT__: Filled out issue template. Sorry.

**Comment by junegunn** [comment]
It is probably a minor rendering bug of bash, and unfortunately there's not much we can do about it. Pressing CTRL-L clears the prompt when that happens.

**Comment by junegunn** [comment]
Possibly related: #681

**Comment by leonklingele** [comment]
Yup, this is a duplicate of #681
Continuing the discussion over there.
