### ISSUE TITLE
select-all action doesn't update preview pane

### ISSUE THREAD

**Issue by ahal** [junegunn/fzf#995]
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [ ] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

This likely affects deselect-all, toggle-all, etc as well.

STR:
$ seq 10 | fzf -m --preview "echo {+}" --bind ctrl-a:select-all
&lt;ctrl-a&gt;

Expected:
The preview pane shows numbers 1-10

Actual:
Preview pane remains blank

After doing a normal <tab> toggle, the preview pane then gets updated with the correct items.

I assume this affects all platforms and shells, but I haven't verified so left it unchecked.

**Comment by junegunn** [comment]
Nice find, fzf currently updates preview window only when the focus is moved.

**Comment by junegunn** [comment]
Fixed on master branch. Thanks.

**Comment by ahal** [comment]
Thanks for the quick fix!
