### ISSUE TITLE
Can we use '\n' instead of space as a multi line delimiter?

### ISSUE THREAD

**Issue by wfxr** [junegunn/fzf#996]
- Category
    - [x] fzf binary
- OS
    - [x] Linux
- Shell
    - [x] zsh

Selected lines can be accessed by '{+}' which was a space-separated list. But sometimes It will cause confusion when a selected line contains space too. I find it's hard to implement copying selected lines with some hotkey, C-y for example.
My config is like this:
```
--bind='ctrl-y:execute-silent(echo {+} | $pbcopy)+abort'
```
So can we use '\n' instead of ' ' as a multi line delimiter?

**Comment by wfxr** [comment]
Selected lines can be accessed by '{+}' which was a space-separated list. But sometimes It will cause some confusion when a selected line contains space. So can we use '\n' instead of ' ' as a line delimiter?

**Comment by junegunn** [comment]
There should be a number of workarounds, for example, this works:

```sh
fzf --multi --bind='ctrl-y:execute-silent(ruby -e "puts ARGV" {+} | pbcopy)+abort'
```

Or you can use `--expect ctrl-y` instead of `execute` binding and use shell script if you need more control.

**Comment by wfxr** [comment]
Thanks for your patient. I learned that
