### ISSUE TITLE
Wiki: Improved tmux session switcher

### ISSUE THREAD

**Issue by felixSchl** [junegunn/fzf#997]
I'd like to offer an improved tmux session switcher for the wiki:

* Display at top of screen like default switcher
* Put current session as first entry (hence dismissing with "enter" becomes a noop)
* Show number of attached clients
* Show session id
* Switch by unique session id
* Opens in dedicated window, not pane (because hardly usable from small panes)
* Easy switching by id (typing number after pre-populated '$' query gives high chance to select it)

Works fine on OSX, have not been able to test on anything else.

```bash
# Use FZF to switch Tmux sessions:
# bind-key s run "tmux new-window 'bash -ci fs'"
fs() {
	local -r fmt='#{session_id}:|#S|(#{session_attached} attached)'
	{ tmux display-message -p -F "$fmt" && tmux list-sessions -F "$fmt"; } \
		| awk '!seen[$1]++' \
		| column -t -s'|' \
		| fzf -q '$' --reverse --prompt 'switch session: ' -1 \
		| cut -d':' -f1 \
		| xargs tmux switch-client -t
}

```

Edit: ~~Hold on, there's an issue with switching to a session that has a space in it's name.~~ Fixed

**Comment by junegunn** [comment]
Looks good to me. Write permission to the wiki page is open to everyone, so feel free to update the page. Thanks!
