### ISSUE TITLE
Tip: Switch between projects

### ISSUE THREAD

**Issue by tastycode** [junegunn/fzf#999]
I work on many side-projects, and navigating between them takes _seconds_. I wondered if i could make a "fast project switcher" using `fzf`. 

![](https://dl.dropboxusercontent.com/s/1u6rvh05g9fjorh/342BA406-9147-4EBF-A95E-8FA77FD8911A-18105-00001D1A12473C5A.gif?dl=0)

The code is 
```bash
cd ~/`cd ~; { find workspace -maxdepth 1 & find dev -maxdepth 1; } | fzf`
```

Where `~` is the grandparent directory for your project directories, and `workspace` and `dev` are directories where each subfolder is a project. So, if all of your projects were in `~/projects`, you wouldn't need to combine the output of two commands, you could just do:

```bash
cd ~/`cd ~;  find projects -maxdepth 1  | fzf`
```

I'm not sure if an issue is the best place for this, but thought i'd share this tip with others. Feel free to close.

**Comment by junegunn** [comment]
Thanks for sharing. Adding a preview window would be a nice touch.

```sh
# Showing the content of README.md.
# You can use programs for syntax highlighting instead of cat.
#   See: https://github.com/junegunn/fzf#preview-window
cd ~/`cd ~;  find projects -maxdepth 1  | fzf --preview 'cat {}/README.md'`

# Using tree command to show the project structure
cd ~/`cd ~;  find projects -maxdepth 1  | fzf --preview 'tree {} | head -200'`
```
